### ISSUE TITLE
Add alias support for OCI Charts

### ISSUE THREAD

**Issue by cobexer** [helm/helm#10013]
Helm charts can have dependencies to other charts.
The root chart and those other charts may come from OCI "repositories" (registries) which the charts have to reference directly currently.

However in the datacenters we have to operate and during the development of our helm charts (dev, staging and production environments) the repositories where those charts are stored change. With the legacy helm repositories we could use repository aliases to avoid global references to other charts.

OCI charts can't currently use repository aliases to point to other helm charts in their dependencies.

Please add alias support for OCI dependencies.

Explaining this using bitnami as an example:
bitnami recommends to use
```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
```
Using bitnamis Drupal chart as an example: https://github.com/bitnami/charts/blob/041766798ed98af83465cab490bb63b73720a79a/bitnami/drupal/Chart.yaml

```yaml
...
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 9.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
...
```

bitnami would need to patch every Chart to support co-existence of traditional and OCI charts... or use repo aliases:

```yaml
# bitnais Drupal helm chart
...
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: alias:bitnami
    version: 9.x.x
  - name: common
    repository: alias:bitnami
    tags:
      - bitnami-common
    version: 1.x.x
...
```

with that change, the helm chart can be used in both tar.gz and OCI formats with dependencies that come from the appropriate repository. Alias support for OCI registries would also make migration to OCI easier.

AND most importantly for our usecase: The repository may be different in every datacenter: it may be hosted inside said datacenter without access to the internet (yes, this is a thing - it's non negotiable actually)
