### ISSUE TITLE
helm upgrade fails to remove keys from Secrets when using `stringData`

### ISSUE THREAD

**Issue by thesuperzapper** [helm/helm#10010]
If a chart templates a `Secret` using the `stringData` field, then `helm upgrade ...` will fail to remove keys that are removed, and instead sets their value to an empty string.

### Chart Definition:
```yaml
## templates/my-secret.yaml
##
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  STATIC_VALUE: "xxxx"
  {{- if .Values.enabled }}
  OPTIONAL_VALUE: "true"
  {{- end }}
```

### Steps:
1. Run: `helm install --set enabled=true ...`
1. Run:  `kubectl get Secret/my-secret -o yaml`:
     __OUTPUT:__
    ```yaml
    ...
    data:
      OPTIONAL_VALUE: dHJ1ZQ==
      STATIC_VALUE: eHh4eA==
    ...
    ``` 
1. Run: `helm upgrade --set enabled=false ...`
1. Run:  `kubectl get Secret/my-secret -o yaml`:
    __OUTPUT:__
    ```yaml
    ...
    data:
      OPTIONAL_VALUE: ""
      STATIC_VALUE: eHh4eA==
    ...
    ```

## Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

## Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mattfarina** [comment]
I can understand the confusion around this. I ran a couple tests to double check my own understanding.

If you perform the same task with kubectl you will have the same result. For example, if you took the secret here with the value for `STATIC_VALUE` and applied it to a cluster then removed that static value and applied the file again you would still see `STATIC_VALUE` with an emptry string as its value when using `kubectl get` to look at the data from the secret.

What you are experiencing is how Kubernetes works.

**Comment by thesuperzapper** [comment]
@mattfarina

I do see that using `kubectl apply -f ...` to remove a `stringData` key, also results in an empty string remaining, which is honestly very strange behaviour that should probably be changed in upstream K8S, especially as this does not happen with the `data` field.

Do you think helm itself should work around this? Currently, there is no safe way to use the `stringData` field, it's a timebomb for users, as the only way to (fully) remove a field that was once defined in `stringData` is MANUALLY patching the Secret.

From a helm perspective, I think introducing a special case for patching Secrets with `stringData` is a good idea, it would make the templates closer to what they are supposed to be, declarative. That is, I expect the Secret in the cluster to match my helm template, and not possibly have empty strings.

**Comment by thesuperzapper** [comment]
For reference, https://github.com/kubernetes/kubernetes/issues/89938 discusses this behaviour from a Kubernetes side.

**Comment by mattfarina** [comment]
> Do you think helm itself should work around this?

This is complicated. First, I have to admit that there is a problem with the way this works. The Kubernetes issue highlights it. Thanks for pointing it out.

But, in general I think Helm should follow the way Kubernetes does things for two reasons...

1. People working with YAML files have the same experience using Helm as they would outside of Helm. This means the guides and docs online would work the same way. When things are the same it simplifies things. When there are bugs it's bug for bug compatible. It means a chart creator can copy a working YAML file right into a chart and start turning it into a template.
2. It enables Helm to use the Kubernetes packages to do the work. This greatly simplifies the amount of work Helm maintainers have to deal with. They can focus on good package management without having to duplicate this work.

Yet, this issue is kind of annoying. I would be open to hearing a good solution to it.

**Comment by thesuperzapper** [comment]
I still think this is an important issue, right now if you use `stringData` in secrets, your helm templates are not "declarative", because they will sometimes leave keys with empty strings.

**Comment by thesuperzapper** [comment]
Bumping for bot.

**Comment by yxxhero** [comment]
@thesuperzapper Need more discussion.

**Comment by joejulian** [comment]
This is how Kubernetes works. There has been no more discussion since 2021. re-closing.

**Comment by thesuperzapper** [comment]
@joejulian we might want to at least document this behavior in the Helm docs, as its slightly non-intuitive unless your really think abut it?

**Comment by joejulian** [comment]
There's a section on [this page](https://kubernetes.io/docs/concepts/configuration/secret/) that touches on the difference between data and stringData. I think that would be the right place to document this.

**Comment by thesuperzapper** [comment]
@joejulian This seems more like something that should be in the helm docs (not the Kubernetes docs), for example in ["Chart Development Tips and Tricks"](https://helm.sh/docs/howto/charts_tips_and_tricks/)?

**Comment by joejulian** [comment]
Feel free to suggest a PR for helm-www, but helm is just filling in the template you provide. Properly documenting the behavior of a Secret is the responsibility of Kubernetes.

**Comment by DBLaci** [comment]
set empty data like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: php-secret-env
type: Opaque
data: # Note: if you omit this, stringData will always be merged with the last. No keys would be deleted ever.
stringData:
  EXAMPLE1: {{ .Values.app.example1 | quote }}
```
