### ISSUE TITLE
[Support] Chart dependency in different repositories

### ISSUE THREAD

**Issue by Xendar** [helm/helm#10029]
Hello,

I am quite new to Helm, so I am grasping the concepts progressively.
Currently I am building 2 charts, one being a subchart of the other.

Here is the `Chart.yaml`:

```yaml
apiVersion: v2
name: mychart
description: The application Helm chart

type: application
version: 0.1.0
appVersion: ""

dependencies:
  - name: mysubchart
    version: 0.1.0
    repository: "@myproject-snapshot"
    condition: mysubchart.enabled
```

Now, the problem I am facing is that the charts can be stored in two different repositories: `myproject-snapshot` or `myproject-release`. So I would ideally need to provide a list of repositories where the chart can be found.
Is there a way to describe this in the `Chart.yaml`?
For now I am manually updating the `repository` depending on where the chart is.

Thanks
