### ISSUE TITLE
Allow environment variables substitition values.yaml

### ISSUE THREAD

**Issue by drtobbyas** [helm/helm#10026]
Hi, I would like to propose allowing environment variable substitution in values.yaml file. Something like 
```
// values.yaml

namespace: ${NAMESPACE}

replicaCount: ${REPLICA_COUNT}

port: ${PORT}

image:
  repository: ${IMAGE}
  pullPolicy: IfNotPresent
  tag: ${TAG}

imagePullSecrets:
  - name: regcred

fullnameOverride: ${APP_NAME}
````
This would be much similar to what is achievable with docker-compose.yml
```
// docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: ${IMAGE}:${TAG}
    container_name: ${APP_NAME}
    ports:
      - '8080:8080'
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
    restart: always

```
This is especially useful in CI/CD environments as values can be exported as environment variables and the value.yaml file is aware of such values and adequately substituted like in docker-compose.

Running Helm in a CI/CD usually involves constructing a separate values.yaml which will be passed as an argument to 'helm upgrade' command or directly setting each and every value in the command line as arguments

it is somehow daunting keeping multiple values.yaml file for different environments, and deployment targets and having to update each one for every change to a value.yaml

With this feature implemented,  only one values.yaml may be maintained for all environments and deployment targets. The respective values are substituted as needed in the values.yaml (since in most cases, most of the values are already exposed and available as CI variable or environment variable in the CI environment). This will alleviate the pain of replicating/constructing/maintaining multiple values.yaml.

I'd be open to contributing a PR to this
