### ISSUE TITLE
Using range and split

### ISSUE THREAD

**Issue by denzhel** [helm/helm#10027]
I have this yaml block:
```
datastores:
   db:
      servers:
      - host: host1
        port: 27017
      - host: host2
        port: 27017
      - host: host3
        port: 27017
```

I need to pass into a config map in the following format:
```
hosts: [ "host1:27017", "host2:27017", "host3:27017" ]
```

How can I achieve this ? 

Thank you :)
