### ISSUE TITLE
tpl function fails when called within a named template that uses a dict

### ISSUE THREAD

**Issue by danehans** [helm/helm#10046]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-12T12:27:07Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.12-gke.2100", GitCommit:"82b41aad731f2dda24cc5ca99e09328163474782", GitTreeState:"clean", BuildDate:"2021-07-16T09:23:20Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

`tpl` fails when being used inside a named template that uses a `dict` to pass in values. Here is my use case:

values.yaml:
```
sso:
  oidc:
    host: foo
    realm: bar
  token_url: "https://{{ .Values.sso.oidc.host }}/auth/realms/{{ .Values.sso.oidc.realm }}/protocol/openid-connect/token"
  auth_url: "https://{{ .Values.sso.oidc.host }}/auth/realms/{{ .Values.sso.oidc.realm }}/protocol/openid-connect/auth"
```

template.yaml:
```
...
{{- $enabled := true }}
{{- $defaults := include "my.named.template" (dict "root" .  "enabled" $enabled) }} 

{{- define "my.named.template" -}}
...
    auth:
      signout_redirect_url: {{ .root.Values.monitoring.sso.grafana.signout_redirect_url | default (tpl "https://{{ .root.Values.sso.oidc.host }}/auth/realms/{{ .root.Values.sso.oidc.realm }}/protocol/openid-connect/logout" .) }}
```

Running `helm install test ./chart --dry-run --debug` generates the following error:
```
Error: template: templates/monitoring/values.yaml:6:17: executing "templates/monitoring/values.yaml" at <include "my.named.template" (dict "root" . "enabled" $enabled)>: error calling include: template: templates/monitoring/values.yaml:73:99: executing "my.named.template" at <tpl "https://{{ .root.Values.sso.oidc.host }}/auth/realms/{{ .root.Values.sso.oidc.realm }}/protocol/openid-connect/logout" .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: https://{{ .root.Values.sso.oidc.host }}/auth/realms/{{ .root.Values.sso.oidc.realm }}/protocol/openid-connect/logout: "BasePath" is not a value
```

Calling `.root.Values.xxx` works as expected for accessing globally scoped values but not within `tpl`.

The behavior is similar to https://github.com/helm/helm/issues/5979, but I'm not using `range` anywhere and none of the workarounds provided in the issue work for my use case.
