### ISSUE TITLE
values.yaml always evaluated when custom values file specified via --values 

### ISSUE THREAD

**Issue by n0v1** [helm/helm#10054]
### Environment

Output of `helm version`:
`version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
Docker Desktop, on premises

### Issue

When specifying a custom values file (e.g. `values-local.yaml`) using the `--values` command line option of `helm install`, Helm shows some behaviour that surprised me: If there is a file named `values.yaml` in the chart directory, it will still/always be evaluated. Is this intended? My expectation was that if I specify a custom values file, only this will be taken into account.

Example directory structure:
```
helm-test
|   Chart.yaml
|   values-local.yaml
|   values.yaml
```

`Chart.yaml`:
```yaml
apiVersion: v2
name: test
description: Test
type: application
version: 0.0.1
```

`values-local.yaml`:
```yaml
some-key:
  prop1: values-local
```

`values.yaml`:
```yaml
some-key:
  prop1: values.yaml
  prop2: foo
  prop3: bar
```

Test:
```yaml
$ helm install test . --values values-local.yaml --debug --dry-run
USER-SUPPLIED VALUES:
some-key:
  prop1: values-local

COMPUTED VALUES:
some-key:
  prop1: values-local
  prop2: foo
  prop3: bar
```

I would have expected computed values to only contain `prop1: values-local` and not contain any values from `values.yaml`.

Background: We use `values.yaml` for deployments to our staging cluster. For local testing we use `values-local.yaml`. With the current behaviour it's not enough to specify properties that deviate from template defaults in `values-local.yaml` but we also have to add all properties from `values.yaml` where we need different values. One solution would of course be to rename `values.yaml` to something else but is this really the intended behaviour?
