### ISSUE TITLE
How to set affinity via the helm CLI command using --set?

### ISSUE THREAD

**Issue by saikarthikp9** [helm/helm#10068]
How to set the affinity in values.yaml file using the helm install command and passing the affinity via --set parameter.

Example affinity block from values yaml file:
```
affinity: 
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: lifecycle
          operator: In
          values:
          - spot
```
