### ISSUE TITLE
URL is not a valid chart repository or cannot be reached error converting YAML to JSON: yaml:

### ISSUE THREAD

**Issue by knowhoper** [helm/helm#10073]
Im trying to setup a Helm chart repo using Github pages. Everything appears to work fine with generating the index.yaml etc via Github Actions, awesome. 

index.yaml

```
    apiVersion: v1
    entries:
      test:
      - apiVersion: v1
        created: "2021-08-27T09:54:44.830905882Z"
        description: Testing the chart releaser
        digest: b41b263d236ef9eee0a75e877982a10ea73face093b4999c6004263b041f0fad
        keywords:
        - test
        name: test
        urls:
        - https://github.com/xxx/xxx/releases/download/test-0.0.9/test-0.0.9.tgz
        version: 0.0.9
    generated: "2021-08-27T09:54:44.587113879Z"

```
And a test chart

```
    name: test
    description: Testing the chart releaser
    version: 0.0.9
    apiVersion: v1
    keywords:
      - test
    sources:
    home:
```

However, when i try to add the repo using 

    `helm repo add test https://didactic-quibble-e0daddd0.pages.github.io/`

I get the error

> Error: looks like "http://didactic-quibble-e0daddd0.pages.github.io/" is not a valid chart repository or cannot be reached: error converting YAML to JSON: yaml: line 188: mapping values are not allowed in this context

`The URL http://didactic-quibble-e0daddd0.pages.github.io/index.yaml `returns the index.yaml file described above.

Any help would be much appreciated.

Cheers
