### ISSUE TITLE
SecretProviderClass is missing from InstallOrder in kind_sorter.go

### ISSUE THREAD

**Issue by aledesma78** [helm/helm#10071]
Output of `helm version`:
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS EKS

When deploying a Chart that contains a SecretProviderClass using the `Kubernetes Secrets Store CSI Driver` the template is rendered and the resource is created after the Deployment which then makes the secret-store CSI driver fail when retrieving the SecretProviderClass:

```
[utils.go:79] GRPC error: failed to get secretproviderclass default/csi-secrets, error: SecretProviderClass.secrets-store.csi.x-k8s.io "csi-secrets" not found
[nodeserver.go:204] "node publish volume complete" targetPath="/var/lib/kubelet/pods/c156b025-98c6-40c6-8bfc-cfa8676e1a07/volumes/kubernetes.io~csi/secrets/mount" pod="default/secret-provider-class-test-rfffefxsdd"
secretproviderclasspodstatus_controller.go:101] "failed to patch secret owner ref" err="failed to get spc csi-secrets, err: SecretProviderClass.secrets-store.csi.x-k8s.io \"csi-secrets\" not found"
```

Helm chart test:

```
 helm template --debug ./secret-provider-class-test                                                                                                             ✔  imp_cluster ⎈  aledes027@deployvm
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /home/aledes027/tmp/secret-provider-class-test

---
# Source: secret-provider-class-test/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-secret-provider-class-test
  labels:
    helm.sh/chart: secret-provider-class-test-0.1.0
    app.kubernetes.io/name: secret-provider-class-test
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: secret-provider-class-test/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-secret-provider-class-test
  labels:
    helm.sh/chart: secret-provider-class-test-0.1.0
    app.kubernetes.io/name: secret-provider-class-test
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: secret-provider-class-test
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: secret-provider-class-test/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-secret-provider-class-test
  labels:
    helm.sh/chart: secret-provider-class-test-0.1.0
    app.kubernetes.io/name: secret-provider-class-test
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-provider-class-test
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-provider-class-test
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: RELEASE-NAME-secret-provider-class-test
      securityContext:
        {}
      containers:
        - name: secret-provider-class-test
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
          volumeMounts:
        - name: secrets
          mountPath: "/secrets"
      volumes:
       - name: secrets
         csi:
          driver: secrets-store.csi.k8s.io
          volumeAttributes:
            secretProviderClass: csi-secrets
---
# Source: secret-provider-class-test/templates/secretsproviderclass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: csi-secrets
  labels:
    helm.sh/chart: secret-provider-class-test-0.1.0
    app.kubernetes.io/name: secret-provider-class-test
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:some-region:0000000000000000:secret:MySecret-3HbV9s"
        objectType: "secretsmanager"
        objectAlias: mysecret
```
