### ISSUE TITLE
`helm dependency update` complains about lack of `version` even when `repository` is not set

### ISSUE THREAD

**Issue by felipecrs** [helm/helm#10095]
Let's say I have:

```yaml
# Chart.yaml
apiVersion: v2
appVersion: "0.1"
description: A Helm chart for Kubernetes
name: chart-b
version: 0.0.1

dependencies:
  - name: chart-a
    condition: chart-a.enabled
```

And my `chart-a` is under `chart-b/charts/chart-a`.

The following happens:

```console
$ cd chart-a
$ helm dependency update
Error: dependency "chart-a" has an invalid version/constraint format: improper constraint:
```

Nonetheless, if I put the version, the following happens:

```
$ helm dependency update
Saving 1 charts
Dependency chart-a did not declare a repository. Assuming it exists in the chart directory
Deleting outdated charts
```

As it is stated in the output, as `repository` is not set, `helm` correctly assumes that we are managing the `charts/chart-a` by ourselves. Thus, it is redundant for checking the presence of `version` when `repository` is not set.

It is even a problem because when we bump the version of the `chart-a`, now it needs to be bumped in `chart-b` as well, even though the dependency is directly linked on the file system.

**Comment by felipecrs** [comment]
The workaround for this issue is to write the dependencies like so:

```yaml
dependencies:
  - name: chart-a
    condition: chart-a.enabled
    version: ">0.0.0-0"
```

So that, no given version must be specified, and `helm dep up` does not fail.
