### ISSUE TITLE
Is Merge Key Language-Independent Type supported for Values files?

### ISSUE THREAD

**Issue by KukyNekoi** [helm/helm#10098]
I'm trying to merge two dicts using [Merge Key Language-Independent Type](https://yaml.org/type/merge.html) and I keep getting this error:

```
Error: YAML parse error on test/templates/valuetest.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead
helm.go:88: [debug] error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead
YAML parse error on ned/templates/valuetest.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        helm.sh/helm/v3/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).Run
        helm.sh/helm/v3/pkg/action/install.go:247
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:242
main.newTemplateCmd.func2
        helm.sh/helm/v3/cmd/helm/template.go:82
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
```

`values.yaml` used to reproduce this problem:
```yaml
postgresql: &postgresql 
  #painfully long map
  namespace: common-services
  enabled: true
  
global:  
  postgresql:
    <<: *postgresql
    host: <RELEASE>-postgresql-headless.svc
```

But using anchors on a value works just fine, just as stated on the documentation:

```yaml
postgresql: 
  namespace: &postgresql common-services
  enabled: true
  
global:  
  postgresql:
    namespace: *postgresql
    host: <RELEASE>-postgresql-headless.svc
```
which yields:

template.yaml
```yaml
# {{ .Values.global }}
```

dry-run output:
```yaml
---
# Source: test/templates/valuetest.yaml
# map[postgresql:map[host:<RELEASE>-postgresql-headless.svc namespace:common-services]]
```

Which led me to the question if this operation is supported by helm's yaml parser, as helm uses [sigs.k8s.io/yaml](https://github.com/kubernetes-sigs/yaml) which uses [go-yaml](https://github.com/go-yaml/yaml), which has merging support. :cry: 

## Extra info:

Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.6"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"archive", BuildDate:"2021-07-16T17:16:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS, Minikube, k3s
