### ISSUE TITLE
helm test not exit if BackoffLimitExceeded event

### ISSUE THREAD

**Issue by wirwolf** [helm/helm#10103]
I use helm test for testing my application(integration-test running). 
```
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-test-functional"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name}}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the job is considered part of the release.
    "helm.sh/hook": test
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  parallelism: 1
  backoffLimit: 0
  template:
    metadata:
      name: "{{ .Release.Name }}-test-functional-{{  randAlphaNum 5 | lower }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name}}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}-integration
          image: "{{ $.Values.image.registry }}/{{ $.Values.image.repository }}_test:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - /app/vendor/bin/codecept
            - run
            - integration
          envFrom:
            - secretRef:
                name: {{ .Values.app.secretPrefix }}-generic


```
Run command: 
```
      GRAND_EXIT=0
      helm test --debug --namespace ${KUBE_NAMESPACE} ${HELM_APP_NAME} || GRAND_EXIT=1
      for pod in $($KUBECTL get pods -n ${KUBE_NAMESPACE} -l helm.sh/hook=test -o name)
      do
        kubectl logs -n ${KUBE_NAMESPACE} --all-containers $pod
      done
      exit ${GRAND_EXIT}
```
After the run when I see the event BackoffLimitExceeded because test fail

Expected result:  helm command exit with status code 1
Actual result: helm command waiting 5m(default value) and no check status of job
