### ISSUE TITLE
deprecated apiVersion for ingress helm deploy

### ISSUE THREAD

**Issue by MattiasVahlberg** [helm/helm#10100]
Related issue: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2374

### Bug description

When deploying jupyterhub helm chart with config.yaml containing ingress configuration it deploys an old apiVersion for ingress. 
#### Expected behaviour

Expecting apiVersion for ingress object in Kubernetes to be
```
apiVersion: networking.k8s.io/v1 
kind: Ingress
```
#### Actual behaviour

Ingress apiVersion deployed is:
```
apiVersion: extensions/v1beta1
kind: Ingress
```

Pattern in Helm chart: 

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/1f21ccd85b43f68766d846b7758ce853343639ba/jupyterhub/templates/ingress.yaml#L2-L6: 
```
 {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }} 
 apiVersion: networking.k8s.io/v1 
 {{- else }} 
 apiVersion: networking.k8s.io/v1beta1 
 {{- end }} 
```
### How to reproduce

1. `helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/`
2. `helm repo update`
3. Create config.yaml:
```
proxy:
  secretToken: "xxxx"
  service:
    type: ClusterIP
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/client-max-body-size: "250m"
    nginx.ingress.kubernetes.io/proxy-body-size: "250m"
  hosts: 
    - someurl.com
  pathSuffix:
  pathType: Prefix
  tls: 
    - hosts:
      - someurl.com
      secretName: tls
```
5. Deploy to kubernetes:
```
helm upgrade --cleanup-on-fail \                              
  --install jupyterhub jupyterhub/jupyterhub \
  --namespace <yournamespace> \
  --version=1.1.3 \
  --values config.yaml
```
6. Verify ingress: `kubectl -n <yournamespace> get ingress jupyterhub -o yaml`

### Output of API resources in kubernetes
Deprecation note for ingress: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
`networking.k8s.io/v1` available from 1.19 the old ingress api version is removed from 1.22.

`kubectl api-versions | grep networking`
output:

```
networking.k8s.io/v1
networking.k8s.io/v1beta1
```

`kubectl api-resources | grep ingresses`
output:

```
ingresses                                ing           extensions/v1beta1                    true         Ingress
ingresses                                ing           networking.k8s.io/v1                  true         Ingress
```
Output of `helm version`:

helm version: `v3.6.3`

Output of `kubectl version`:

kubernetes version: `1.19.11`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

Output `nginx version`:
 - app version: `0.45.0`
 - chart version: `ingress-nginx-3.27.0`
