### ISSUE TITLE
Helm to use same subchart and deploy multiple charts

### ISSUE THREAD

**Issue by myvelmurugan** [helm/helm#10116]
I have requirement of having multiple dependencies and used the same subcharts for multiple times.

Parent chart has 3 dependencies  and using the same chart path.  I have to deploy the subcharts with below alias name but its not working.

I need to create 3 subscharts with this alias-name used as sub-chart name.

```
dependencies:
- name: applayer
  repository: file://charts/applayer
  condition: applayer-1.enabled
  alias: applayer-1
- name: applayer
  repository: file://charts/applayer
  condition: applayer-2.enabled
  alias: applayer-2
- name: applayer
  repository: file://charts/applayer
  condition: applayer-3.enabled
  alias: applayer-3
```
