### ISSUE TITLE
Helm template post-render doesn't work if set `--output-dir` for 

### ISSUE THREAD

**Issue by charles-woshicai** [helm/helm#10115]
Output of `helm version`:
```shell
➜  ~ helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

### without `--output-dir`

```shell
➜  JsonPatch git:(develop) ✗ helm template ../../charts --post-renderer ./post-renderer-kustomize.sh 
```

```yaml                       
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    eventing.knative.dev/injection: enabled
    k1: v1
    k2: v2
    knative-eventing-injection: enabled
  labels:
    app: knative-show-case
    chart: knative-show-case
    ede.io/postrender: "true"
    heritage: Helm
    release: RELEASE-NAME
  name: knative-show-case-trigger
spec:
  broker: default
  filter:
    attributes:
      topic: ShowEvent
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knative-show-case
```

### with `--outpur-dir`

> The apiVersion of knative trigger is `v1beta1` which is not replaced as expected.

```shell
➜  JsonPatch git:(develop) ✗ helm  ../../charts --post-renderer ./post-renderer-kustomize.sh --output-dir ../../test          
➜  JsonPatch git:(develop) ✗ cat ../../test/knative-show-case/templates/trigger.yaml 
```
```yaml
---
# Source: knative-show-case/templates/trigger.yaml
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: knative-show-case-trigger
  annotations:
    knative-eventing-injection: enabled
    k1: v1
    k2: v2
  labels:
    app: knative-show-case
    chart: knative-show-case
    release: RELEASE-NAME
    heritage: Helm
spec:
  broker: default
  filter:
    attributes:
      topic: ShowEvent
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knative-show-case
```

### My kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - all.yaml
patches:
  - patch: |-
      - op: replace
        path: "/apiVersion"
        value: eventing.knative.dev/v1
      - op: add
        path: "/metadata/annotations/eventing.knative.dev~1injection"
        value: enabled
      - op: add
        path: "/metadata/labels/ede.io~1postrender"
        value: "true"

    target:
      group: eventing.knative.dev
      kind: Trigger
```

### post-renderer-kustomize.sh
```shell
#!/bin/bash

# save incoming YAML to file
cat <&0 > all.yaml

kustomize build . && rm all.yaml
```
