### ISSUE TITLE
Helm Adds Environment Variables For Unrelated Different Sections

### ISSUE THREAD

**Issue by pchang388** [helm/helm#10129]
I'm using a modified version of the helm chart for apache/druid (https://github.com/apache/druid/tree/master/helm/druid). When trying to add environment variables from values.yaml file to deployments/statefulsets, we have two sections for environment variables: `.Values.env` and `.Values.{{ component }}.env` . 

My thought is the `.Values.env` gets applied for all components in the chart and `.Values.{{ component }}.env` get applied to only the component deployment/statefulset. But after testing, I saw this - example: Component=Broker has the environment variables from Component=Router which causes the application to not run properly. 

Relevant Contents of values.yaml:
```
env:
  # Deep storage
  druid_storage_type: s3
  druid_s3_disableChunkedEncoding: true
  druid_s3_enablePathStyleAccess: true
  ...

broker:
  env:
      DRUID_XMX: 12g
      DRUID_XMS: 12g
      DRUID_MAXDIRECTMEMORYSIZE: 10500m


router:
  env:
    DRUID_MAXDIRECTMEMORYSIZE: 10500m
    DRUID_XMS: 1g
    DRUID_XMX: 1g
    druid_host: 10.167.98.132:8888
    druid_router_http_numConnections: 40
    druid_router_http_numMaxThreads: 80
    druid_server_http_numThreads: 80
````

In the deployment/statefulset files - Example of relevant sections:
```
spec:
  template:
    spec:
      containers:
        env:
          {{- range $key, $value :=  mergeOverwrite .Values.env .Values.broker.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
```

I have verified that the `.Values.env` section does not contain any duplicate data from any other  `.Values.{{ component }}.env` section and is unique to the values.yaml file. I also tried without using the mergeOverwrite function and instead going through each separately. But the output of dry run and `upgrade` commands shows that `.Values.env` section holds all the `Values.{{ component }}.env` values (for all components in the values.yaml of the chart). I tried searching through the open issues and was unable to find any reference to a similar issue. 

Also a note (if this matters): we are using values.yaml file as a base and overwriting some values using `{{ env }}-values.yaml` . I also checked the base values.yaml file and we do not have the component specific variables specified there either.

Output of `helm version`: 
`version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}`

Output of `kubectl version`: 
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+vmware.1", GitCommit:"088f01db2ffab397a290be443902918b59ee032c", GitTreeState:"clean", BuildDate:"2021-04-17T01:01:00Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  PKS

**Comment by zonggen** [comment]
Tried to reproduce this issue but no luck so far. I've compared `{{- range $key, $value :=  mergeOverwrite .Values.env }}` vs. `{{- range $key, $value :=  mergeOverwrite .Values.env .Values.broker.env }}`. And here's the corresponding result:

```yaml
          env:
          - name: druid_s3_disableChunkedEncoding
            value: "true"
          - name: druid_s3_enablePathStyleAccess
            value: "true"
          - name: druid_storage_type
            value: "s3"
```
vs.
```yaml
          env:
          - name: DRUID_MAXDIRECTMEMORYSIZE
            value: "10500m"
          - name: DRUID_XMS
            value: "12g"
          - name: DRUID_XMX
            value: "12g"
          - name: druid_s3_disableChunkedEncoding
            value: "true"
          - name: druid_s3_enablePathStyleAccess
            value: "true"
          - name: druid_storage_type
            value: "s3"
```

here you can see `{{- range $key, $value :=  mergeOverwrite .Values.env }}` does not contain values from `broker`.

Environment setup:
* https://github.com/apache/druid/tree/master/helm/druid with only modifications being:
  1. remove leading comment section to workaround `Eror: unable to build kubernetes objects from release manifest: error validating "": error validating data: apiVersion not set` error ([link to stackoverflow answer](https://stackoverflow.com/questions/62747453/helm-3-chart-install-error-error-validating-data-apiversion-not-set?rq=1))
  2. Replace all `env:` section in `statefulset.yaml` and `deployment.yaml` with `{{- range $key, $value :=  mergeOverwrite .Values.env .Values.broker.env }}`
  3. `helm dependency update`
  4. `helm install test-custom-druid ./ --dry-run`

```bash
$ helm version

version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.6"}
```
