### ISSUE TITLE
Files.Get not working with nested range

### ISSUE THREAD

**Issue by antonisnyc94** [helm/helm#10144]
Im trying to use recursion in order to be adding contents of files in the ConfigMap.yaml but i dont seem to get it right. I dont get the content of the file no matter what i try. The location of the file is correct because i can get the content without recursion. {{.Files.Get "config/gitlab.conf" | indent 4 -}}

Any help would be greatly appreciated! Thank you

ConfigMap.yaml:
```
{{- if  .config.file }}
{{- range $path, $config := .config.file }}
  {{ $path }}: |
{{ tpl ($.Files.Get (printf "%s" $config )) $ | indent 4 -}}
{{- end -}}
{{- end -}}
```

Values.yaml:
```
config:
        configName: gitlab-conf
        file:
          logstash.conf: config/gitlab.conf
```

OUTPUT:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-conf
  namespace: elk
data:
  logstash.conf: |
```

Output of `helm version`:  3.6.3

**Comment by zonggen** [comment]
Here's an working example tested with `helm create hello-world`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-conf
  namespace: elk
data:
  {{- $ := . }}
  {{- if  .Values.config.file }}
  {{- range $path, $config := .Values.config.file }}
    {{ $path }}: |
  {{ tpl ($.Files.Get $config) $ | indent 4 -}}
  {{- end -}}
  {{- end -}}
```

Used same `values.yaml`. Hope this works for you.

**Comment by antonisnyc94** [comment]
Thank you so much Zonggen! I guess it was my bad that i didnt mention the nested loop which is a game changer since I cant get your method to work for me.. Im sorry for the confusion, but if you solve this you are a rockstar!

```
{{- if .Values.volConfigMap}}
{{- range .Values.volConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .config.configName }}
  namespace: {{ $.Release.Namespace }}
data:
{{- if and (not .config.data) (not .config.file) }}
{{ fail " .Values.volConfigMap.config.data or .Values.volConfigMap.config.file required" }}
{{- end }}
{{- if  .config.data }}
{{- range $path, $config := .config.data }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end }}
{{- end }}
{{- if  .config.file }}
{{- range $path, $config := .config.file }}
  {{ $path }}: |
{{ tpl ($.Files.Get $config) $ | indent 4 -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

**Comment by zonggen** [comment]
No problem :) Tried again with your ConfigMap without any modification, still rendered normally for me. My setup is simple:

`values.yaml`:

```yaml
testValue: testValue
testValue2: testValue2

volConfigMap:
  - config:
      configName: gitlab-conf
      file:
        logstash.conf: config/gitlab.conf

```

`config/gitlab.conf`:

```
testKey={{ .Values.testValue }}
testKey2={{ .Values.testValue2 }}
```

output:

```
$ helm install hello-world . --dry-run --namespace elk

---
# Source: hello-world/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-conf
  namespace: elk
data:
  logstash.conf: |
    testKey=testValue
    testKey2=testValue2
---
```

Since we are using the same ConfigMap, I'm suspecting the `config/gitlab.conf` template :thinking:
