### ISSUE TITLE
Best approach for moving CRD from crds folder to templates folder?

### ISSUE THREAD

**Issue by sureleo** [helm/helm#10143]
Hello,

We are trying to move CRD from crds to templates for some reasons, so Helm could handle the CRD upgrade in the future (we have made sure this suits our use case). Our CRD in crds folder does not have any annotations nor labels.

Here is the approach that I am using but I am unsure if this the best way to do it. It would be great that you can take a look and this could serve as a guideline for the community if anybody encounter the same scenario.

Assuming version 1.0.0 is the version that CRD is in the crds folder, and 2.0.0 is the version that CRD is in the template folder.

1. In 2.0.0, use a pre-install hook to add the following annotations to the CRD that has been installed by 1.0.0:
```
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
```
2. In 2.0.0, we move CRD from crds folder to templates folder and add the above annotations and labels in the yaml file.
3. Once 2.0.0 is installed, Helm should be able to handle upgrade afterward. i.e. 3.0.0 included a new version of the CRD.

Thanks in advance!
