### ISSUE TITLE
Helm Lint error

### ISSUE THREAD

**Issue by ushabapat** [helm/helm#10149]
[ERROR] templates/aad-identity.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: "aadpodidentity.k8s.io/v1

when template has  --- separator, helm lint is failing with above error. After removing the separator (---) from the yaml , it works.  But our template file that consists of two YAML blocks wrapped into conditions that are separated with 3 dashes. We cant separate the yaml file for aad identity and binding.  Can you please check on this part.

It works if we change the helm version to 3.6.3

Output of `helm version`: 3.7.0

Output of `kubectl version`:  v1.18.0"

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

**Comment by zonggen** [comment]
Can reproduce:
```bash
$ helm create issue-10149 
```
`templates/serviceaccount.yaml`:

```yaml
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "issue-10149.serviceAccountName" . }}
  labels:
    {{- include "issue-10149.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "issue-10149.fullname" . }}
  labels:
    {{- include "issue-10149.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "issue-10149.selectorLabels" . | nindent 4 }}

{{- end }}

```
```
$ helm lint issue-10149

==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/serviceaccount.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: v1

Error: 1 chart(s) linted, 1 chart(s) failed
```

```
$ helm version
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"dirty", GoVersion:"go1.16.6"}
```

Also tried same chart with`v3.6.3`:
```
$ helm lint issue-10149
==> Linting issue-10149
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

One thing to note is that for both `v3.7.0` and `v3.6.3`, I can `helm install` without Error:

```
$ helm install hello-world issue-10149
NAME: hello-world
LAST DEPLOYED: Fri Sep 17 15:04:14 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=issue-10149,app.kubernetes.io/instance=hello-world" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT

```
