### ISSUE TITLE
hidden files in `charts` directory cause panic `SIGSEGV` when running `helm package -u chart`

### ISSUE THREAD

**Issue by mfinelli** [helm/helm#10141]
With helm 3.7.0 running `helm package -u chart` if the `charts` directory contains any hidden files (e.g., `.gitignore`) causes a panic. Interestingly the dependencies are downloaded successfully, but the panic still happens.

For example create a new directory `test` with a file in it:

```yaml
# test/Chart.yaml
apiVersion: v2
name: sigsegv
description: repro test
type: application
version: 0.1.0

dependencies:
  - name: postgresql
    version: 10.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
```

Then create a `.gitignore` file:

```gitignore
# test/charts/.gitignore
*
!.gitignore
```

(Note, that this does not need to be `.gitignore` specifically. It can simply be an empty hidden file named whatever `test/charts/.file` will trigger it too)

Now, issue `helm package -u test` and observe the panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x53b980d]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/chart.(*Chart).Name(...)
        helm.sh/helm/v3/pkg/chart/chart.go:76
helm.sh/helm/v3/pkg/downloader.(*Manager).safeMoveDeps(0xc000141c20, {0xc000646020, 0x1, 0x38}, {0xc001d208c0, 0x32}, {0xc0020a8210, 0x2f})
        helm.sh/helm/v3/pkg/downloader/manager.go:452 +0x48d
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll(0xc000141c20, {0xc000646020, 0xc0005390a0, 0x1})
        helm.sh/helm/v3/pkg/downloader/manager.go:371 +0x176b
helm.sh/helm/v3/pkg/downloader.(*Manager).Update(0xc000141c20)
        helm.sh/helm/v3/pkg/downloader/manager.go:201 +0x109
main.newPackageCmd.func1(0xc00061e780, {0xc000557140, 0x1, 0x2})
        helm.sh/helm/v3/cmd/helm/package.go:99 +0x5f6
github.com/spf13/cobra.(*Command).execute(0xc00061e780, {0xc000557120, 0x2, 0x2})
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00061e000)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        helm.sh/helm/v3/cmd/helm/helm.go:87 +0x234
```

`helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
```

**Comment by bacongobbler** [comment]
I was able to reproduce the issue, however I received a different error.

```
bacongobbler@ultralisk /tmp ><> helm create test-10141
Creating test-10141
bacongobbler@ultralisk /tmp ><> cd test-10141/
bacongobbler@ultralisk /tmp/test-10141 ><> l
charts  Chart.yaml  templates  values.yaml
bacongobbler@ultralisk /tmp/test-10141 ><> touch .gitignore
bacongobbler@ultralisk /tmp/test-10141 ><> helm package .
Successfully packaged chart and saved it to: /tmp/test-10141/test-10141-0.1.0.tgz
bacongobbler@ultralisk /tmp/test-10141 ><> l
charts  Chart.yaml  templates  test-10141-0.1.0.tgz  values.yaml
bacongobbler@ultralisk /tmp/test-10141 ><> rm .gitignore 
bacongobbler@ultralisk /tmp/test-10141 ><> touch charts/.gitignore
bacongobbler@ultralisk /tmp/test-10141 ><> helm package .
Successfully packaged chart and saved it to: /tmp/test-10141/test-10141-0.1.0.tgz
bacongobbler@ultralisk /tmp/test-10141 ><> ls charts/ -al
total 8
drwxr-xr-x 2 bacongobbler bacongobbler 4096 Sep 16 09:25 .
drwxr-xr-x 4 bacongobbler bacongobbler 4096 Sep 16 09:25 ..
-rw-rw-r-- 1 bacongobbler bacongobbler    0 Sep 16 09:25 .gitignore
bacongobbler@ultralisk /tmp/test-10141 ><> vim Chart.yaml 
bacongobbler@ultralisk /tmp/test-10141 ><> helm package .
Error: found in Chart.yaml, but missing in charts/ directory: postgresql
bacongobbler@ultralisk /tmp/test-10141 ><> helm dep up
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
Saving 1 charts
Downloading postgresql from repo https://charts.bitnami.com/bitnami
Deleting outdated charts
Could not verify charts/.gitignore for deletion: file 'charts/.gitignore' does not appear to be a gzipped archive; got 'application/octet-stream' (Skipping)panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1a20f8e]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/chart.(*Chart).Name(...)
	helm.sh/helm/v3/pkg/chart/chart.go:76
helm.sh/helm/v3/pkg/downloader.(*Manager).safeMoveDeps(0xc000186cf0, 0xc006778018, 0x1, 0x1, 0xc00071e006, 0x9, 0xc00071e000, 0x6, 0x1f, 0xc00162a360)
	helm.sh/helm/v3/pkg/downloader/manager.go:452 +0x46e
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll(0xc000186cf0, 0xc006778018, 0x1, 0x1, 0x0, 0x0)
	helm.sh/helm/v3/pkg/downloader/manager.go:371 +0x671
helm.sh/helm/v3/pkg/downloader.(*Manager).Update(0xc000186cf0, 0xc000186cf0, 0x2)
	helm.sh/helm/v3/pkg/downloader/manager.go:201 +0x1b7
main.newDependencyUpdateCmd.func1(0xc000241400, 0x2fde340, 0x0, 0x0, 0x0, 0x0)
	helm.sh/helm/v3/cmd/helm/dependency_update.go:74 +0x1da
github.com/spf13/cobra.(*Command).execute(0xc000241400, 0x2fde340, 0x0, 0x0, 0xc000241400, 0x2fde340)
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000240a00, 0xc00011b010, 0x1, 0xc00081ff60)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	helm.sh/helm/v3/cmd/helm/helm.go:87 +0x27b
```

```
bacongobbler@ultralisk /tmp/test-10141 ><> cat Chart.yaml 
apiVersion: v2
name: test-10141
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 10.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
```
