### ISSUE TITLE
serviceAccountName not removed during upgrade

### ISSUE THREAD

**Issue by Stono** [helm/helm#10183]
Hi, 
We've just run into: https://github.com/helm/helm/issues/8589 which was closed as you aren't able to reproduce.
In our case, we had the following:

- A chart specifying `serviceAccountName`
- A `DaemonSet` with `serviceAccount` **and** `serviceAccountName` in the cluster PodSpec when inspected
- We removed `serviceAccountName` from the helm chart
- The helm upgrade succeeded however we noticed the workloads did not restart 
- The ServiceAccount resource was removed as expected, but the DaemonSet was left referencing the `serviceAccountName` 

```
598     	Fri Sep 24 16:26:23 2021	superseded	helm-platform-node-exporter-0.1.0	           	Upgrade complete
599     	Fri Sep 24 16:33:41 2021	superseded	helm-platform-node-exporter-0.1.0	           	Upgrade complete
```

Version 599 removed the ServiceAccount, so looking at 598:
```
❯ helm -n core-system get manifest helm-platform-node-exporter --revision 598 | grep -i serviceAcc
# Source: helm-platform-node-exporter/templates/serviceaccount.yaml
kind: ServiceAccount
      serviceAccountName: prometheus-node-exporter
```

And then in 599, it's gone from the manfiest:
```
❯ helm -n core-system get manifest helm-platform-node-exporter --revision 599 | grep -i serviceAcc
```

However it is still on the cluster:
```
❯ k -n core-system get daemonset prometheus-node-exporter -o yaml |grep -i serviceAccount
      serviceAccount: prometheus-node-exporter
      serviceAccountName: prometheus-node-exporter
```

Let me know if there's any more information I can provide to help you.

Output of `helm version`:
3.6.3

Output of `kubectl version`:
1.19

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by yxxhero** [comment]
@Stono Can you provide a simple example to help reproduce this issue?  Thanks very much.

**Comment by Stono** [comment]
@yxxhero it's literally as simple as having something with a `serviceAccountName` in the spec, then removing it and doing a helm deploy, and observing it not being removed from the cluster.

**Comment by Evesy** [comment]
If you have an initial chart with just the below template being deployed:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meves-test
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      serviceAccountName: meves-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meves-test
```

Install that, `helm install meves-test .`.

Then edit the manifest to remove the `ServiceAccount` and remove the ref from the deployment, so you're left with:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meves-test
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

Run `helm upgrade meves-test .`

The `ServiceAccount` is removed, and `helm get manifest meves-test` shows `spec.serviceAccountName` being removed from the manifest, however the actual Deployment resource on the cluster is unchanged
