### ISSUE TITLE
helm lookup doesn't work when lookup used for resources created in same chart

### ISSUE THREAD

**Issue by komalarg2010** [helm/helm#10186]
Output of `helm version`:
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:18:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube 

I am trying to create series of EnvoyFilter in loop in a helm chart.  I would like the envoyfilter to be created only if it does not exist, so I am using lookup before creating it. 

```
{{- range $port := .Values.gateway.ports }}
{{- $efName:= print "proxy-protocol-" ($port.number|toString) -}}
{{- if not (lookup "networking.istio.io/v1alpha3" "envoyfilters.networking.istio.io" "foo" $efName) }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ $efName }}
  namespace: foo
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: LISTENER
      match:
        listener:
          portNumber: {{ $port.number }}
      patch:
        operation: MERGE
        value:
          listener_filters:
            - name: envoy.filters.listener.proxy_protocol
            - name: envoy.filters.listener.tls_inspector
---
{{- end }}
{{- end }}
```

Values passed: please note some ports can be passed multiple times , that's the reason I want to lookup before creating.
But helm installation fails with error: 
Error: envoyfilters.networking.istio.io "proxy-protocol-443" already exists 

```
gateway:
  ports:
  - number: 443
    protocol: https
  - number: 80
    protocol: http
  - number: 3443
    protocol: https
  - number: 8444
    protocol: http2
  - number: 443
    protocol: https
  - number: 8446
    protocol: https
  - number: 8445
    protocol: http2
  - number: 8447
    protocol: https
```

I can fix the values to not have duplicate values, however, is lookup expected to work in this case? is there a work around?

**Comment by zonggen** [comment]
I can confirm this still happens in `v3.7.0`. Replaced `networking.istio.io/v1alpha3` and `envoyfilters.networking.istio.io` to just `v1` and `Job`

```
{{- range $port := .Values.gateway.ports }}
{{- $efName:= print "proxy-protocol-" ($port.number|toString) -}}
{{- if not (lookup "v1" "Job" "default" $efName) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $efName }}
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure
---
{{- end }}
{{- end }}
```
and
```
gateway:
  ports:
  - number: 443
    protocol: https
  - number: 80
    protocol: http
  - number: 3443
    protocol: https
  - number: 8444
    protocol: http2
  - number: 443
    protocol: https
  - number: 8446
    protocol: https
  - number: 8445
    protocol: http2
  - number: 8447
    protocol: https
```

output:
```
$ helm install hello-world .

Error: INSTALLATION FAILED: jobs.batch "proxy-protocol-443" already exists
```

This seems to be because `lookup` only looked at the cluster state before the installation and not counting on the resources during installtion.

A possible workaround is to use `uniq` function:

```
{{- range $port := (.Values.gateway.ports | uniq) }}
{{- $efName:= print "proxy-protocol-" ($port.number|toString) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $efName }}
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure
---
{{- end }}
```

output:
```
$ helm install hello-world .

NAME: hello-world
LAST DEPLOYED: Mon Sep 27 13:33:26 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=issue-10186,app.kubernetes.io/instance=hello-world" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
```

Please change to `networking.istio.io/v1alpha3` and `envoyfilters.networking.istio.io` accordingly.
