### ISSUE TITLE
Having issues provisioning Datasources using --set due to datasource.yaml 

### ISSUE THREAD

**Issue by ryanberger-az** [helm/helm#10208]
Output of `helm version`:

version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}

Output of `kubectl version`: 

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"4966fd0dded6419fd23233a38c8905c67a3ea78e", GitTreeState:"clean", BuildDate:"2021-08-17T02:06:07Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

Hi all,
i am having some trouble getting --set to work when overriding some values that have `. `'s in the property names. i've tried the recommendation from the helm website but it's not doing the trick and escaping out the `.` for me. i am trying to configure a grafana chart to automatically set up a datasource for me using an azure devops pipeline and injecting some key vault values, but the datasources.yaml property is breaking when it goes to be parsed and putting the properties under the wrong area (see screenshot). i've tried various different escaping options and i just can't get it to properly send them into the right area. can anyone assist?

the code snippet below is in the values.yaml for the helm chart - see official documentation: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml

```
datasources:
  datasources.yaml:
    apiVersion: 1 # config file version
    datasources:
      - name: Azure Monitor
        type: grafana-azure-monitor-datasource
        access: proxy
        jsonData:
          azureAuthType: clientsecret
          cloudName: azuremonitor # See table below
          tenantId:
          clientId:
          subscriptionId: # Optional, default subscription
        secureJsonData:
          clientSecret:
        version: 1
```
my --set is being passed through the helm task for azure devops, and looks a bit like this:
```
datasources.datasources\.yaml.datasources.jsonData.tenantId=$(my-tenantid),datasources.datasources\.yaml.datasources.jsonData.clientId=$(grafana-app-dev-clientid),datasources.datasources\.yaml.datasources.jsonData.subscriptionId=$(my-dev-subid),datasources.datasources\.yaml.datasources.secureJsonData.clientSecret=$(grafana-app-dev-secret)
(edited)
```
i've been unable to get these values properly placed where they need to be, so i've been testing with --dry-run to check it. the screenshot below is an output of my --dry-run. you can see that the .yaml is being treated as its own property.

does anyone have any ideas to get around this? i want to use --set for these values so i can set up all of my different environments to use the proper client id's, secrets, etc and automate the deployment of grafana to all of them.

![image](https://user-images.githubusercontent.com/60238330/135672898-2a28f83c-adab-4034-8ae6-8457f4f452f9.png)
