### ISSUE TITLE
Could you clarify values.yaml document procedure for nested values?

### ISSUE THREAD

**Issue by Crono1981** [helm/helm#10203]
On [the website](https://helm.sh/docs/chart_best_practices/values/#document-valuesyaml) it's mentioned that documenting chart values should be done in a way so that documentation tools can "reliably correlate doc strings with the parameters they describe".

There's an example showing how to go with flat values, but none for nested values. And I'm not sure which way I should go.

I was thinking in the lines of:

```yaml
# db holds database server related configuration values
db:
  # serverAddress is the address of the targeted database server
  serverAddress:

  # catalog is the name of the database catalog the service must connect to, if different than default
  catalog: "default-catalog-here"

  # user is the database user the service must authenticate with
  user:
```

But it may be better to go this way instead:

```yaml
db:
  # db.serverAddress is the address of the targeted database server
  serverAddress:

  # db.catalog is the name of the database catalog the service must connect to, if different than default
  catalog: "default-catalog-here"

  # db.user is the database user the service must authenticate with
  user:
```

Is there any recommendations for nested values documentation? Or is it just for flat values? Either way, I think there should be a mention of this on the website.

(BTW I'm aware that flat values should be favored over nested for most scenarios. The `YAML` above is just used as an example.)
