### ISSUE TITLE
3-way merge upgrade not working for subchart CR resources

### ISSUE THREAD

**Issue by tbuchier** [helm/helm#10210]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Happen in any kind.

---

Hello 🙂 , 

* I deploy some Custom Resources using Helm. The CR manifests in Helm specify the replicaCount / cpu and mem requests. 
* I scale the CR or edit it's resources requests using kubectl. 
* Then If I do a helm upgrade, replicaCount and requests **are not overwritten** to the original value specified in helm manifest..

The helm debug output show me manifests that correctly contains the original replicaCount / requests, but it's not applied like if Helm didn't compared with the live state and enforced the value.
When reproducing the same with a simple deployment, it works fine, live state is corrected.

More detail on my setup:

The main chart `clustered` deploy a set of subcharts each one being a different CR.
Let's take one of these CR: Worker

Live deployed CR:
`kubectl get worker dummy-worker-write -o yaml`
```
apiVersion: dummy.org/v1alpha1
kind: Worker
metadata:
  annotations:
    meta.helm.sh/release-name: dummytest
    meta.helm.sh/release-namespace: test2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: dummy-worker-write
  namespace: test2
spec:
  image: dummy:1.0.1.1
  k8s:
    replicaCount: 0
    resources:
      limits:
        cpu: "3"
        memory: 6Gi
      requests:
        cpu: "1"
        memory: 1Gi
   ....
```

`helm upgrade --debug`

```
upgrade.go:139: [debug] preparing upgrade for dummytest
upgrade.go:147: [debug] performing update for dummytest
upgrade.go:319: [debug] creating upgraded release for dummytest
client.go:218: [debug] checking 7 resources for changes
upgrade.go:154: [debug] updating status for upgraded release for dummytest
Release "dummytest" has been upgraded. Happy Helming!

...

HOOKS:
MANIFEST:
---
# Source: clustered/charts/workers/templates/workers.yaml
apiVersion: dummy.org/v1alpha1
kind: Worker
metadata:
  name: dummy-workers-write
spec:
  image: dummy:1.0.1.1
  k8s:
    replicaCount: 1
    resources:
      limits:
        cpu: "1"
        memory: 5Gi
      requests:
        cpu: "1"
        memory: 1Gi
```
But live resource is not fixed.

`helm diff upgrade dummytest ../helm-charts/clustered`
return nothing

Note: the CR doesn't have all the default helm annotation/labels like `helm.sh/chart` but I don't think it matters as doc say
"Helm itself never requires that a particular label be present."

Any idea to investigate this issue ?
Thanks!
