### ISSUE TITLE
helm dependency build fails getting oci chart 

### ISSUE THREAD

**Issue by nbraun-wolf** [helm/helm#10236]
Hi, I am using helm 3.7.0. I just re packaged a chart and pushed to ACR. I am able to pull the chart with

```bash
$ helm pull oci://myorg.azurecr.io/helm/v2/emqx --version 0.2.0
Pulled: myorg.azurecr.io/helm/v2/emqx:0.2.0
Digest: sha256:shome-hash
```

But I am not able to use this as dependency in another chart. 

```yaml
apiVersion: v2
name: app
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: emqx
    version: "0.2.0"
    repostitory: oci://myorg.azurecr.io/helm/v2/ # i tried also appending emqx like this helm/v2/emqx
    condition: createEmqx
```

It fails with this message

```bash
$ helm dependency build
Error: directory charts/emqx not found
```
