### ISSUE TITLE
ConfigMap Template - don't populate variables

### ISSUE THREAD

**Issue by jtai-omniex** [helm/helm#10241]
Is it possible to not fill in variables from a YAML file? For example, configmaps may include templates that are to be filled out later. In the following example `.rollout.metadata.name` should not be attempted to be populated when installing or upgrading the chart, it should just be used to create the data in the ConfigMap.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
  template.rollout-completed: |-
    message: Rollout {{.rollout.metadata.name}} has been completed.
```

using `kubectl apply` on a file containing the above would succeed, but using `helm upgrade` on the same file would fail with something like the following:

```
Error: Failed to render chart: exit status 1: Error: template: argo-rollouts/templates/notifications-install.yaml:5:31: executing "argo-rollouts/templates/notifications-install.yaml" at <.rollout.metadata.name>: nil pointer evaluating interface {}.metadata
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS
