### ISSUE TITLE
Improve `helm package` to dynamically set Chart.yaml annotations

### ISSUE THREAD

**Issue by armingerten** [helm/helm#10249]
Projects like [Artifact Hub](https://artifacthub.io/) use annotations in a `Chart.yaml` to extend and visualize meta information of a chart. While some annotations (e.g. `artifacthub.io/maintainers`, `artifacthub.io/license`, etc.) are rather static and might be changed by a commit, other annotations (e.g. `artifacthub.io/changes`) are typically dynamically set during a ci build.

The `helm package` command already allows setting dynamic meta information like a chart's `version` or `appVersion`. This issue proposes to enhance the command furthermore, to allow setting annotations dynamically. The syntax could be:
```sh
Usage:
  helm package [CHART_PATH] [...] [flags]

Flags:
      --set-annotation  stringArray   set annotations on the chart to this value (can specify multiple or separate values with commas: key1=val1,key2=val2)
      ...
```

For example the command 

```sh
helm package charts/my-chart --set-annotation "artifacthub.io/changes=- Added cool feature\n- Fixed minor bug"
```

would set the `artifacthub.io/changes` annotation in the `Chart.yaml`. Previously existing annotations (e.g. `artifacthub.io/maintainers` remain unaffected:

```yaml
apiVersion: v2
name: my-chart
annotations: 
  artifacthub.io/maintainers:  |
    - name: user1
      email: user1@email.com
  artifacthub.io/changes: |
    - Added cool feature
    - Fixed minor bug
```

WDYT?
