### ISSUE TITLE
Helm dependency condition is always true when it's checking a value that doesn't exist

### ISSUE THREAD

**Issue by sincejune** [helm/helm#10296]
For each dependency in `Chart.yml`, the condition will be considered as `true` if it is checking a value that doesn't exist.

For this example:
```
...

dependencies:
  - name: subchart
    repository: http://localhost:10191
    version: 0.1.0
    condition: subchart.enabled

...
```
If `subchart.enabled` is missing in `values.yml`, the `subchart` will be enabled by default which is considered as an unexpected behavior.
