### ISSUE TITLE
Major Helm plugin security issue

### ISSUE THREAD

**Issue by braderhart** [helm/helm#10316]
Output of `helm version`: 3.7.1
Output of `kubectl version`: 1.22.3

There is a major problem with how plugins are installed and updated. It is basically the same as piping a foreign bash script into your shell. An exploited user may not even know, but they could easily have their entire production Kubernetes clusters exposed, passwords, and more.

For example, take the `helm-push` plugin:

`plugin.yaml`
```
name: "cm-push"
version: "0.10.1"
usage: "Please see https://github.com/chartmuseum/helm-push for usage"
description: "Push chart package to ChartMuseum"
command: "$HELM_PLUGIN_DIR/bin/helm-cm-push"
downloaders:
- command: "bin/helm-cm-push"
  protocols:
  - "cm"
useTunnel: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
```

As you can see, it is blanket running a script during install `scripts/install_plugin.sh` as the user. Let's say a malicious user wanted to get your `~/.kube` credentials and `~/.config/glcoud`. All they have to do is include commands to silently upload those. This exposes all files that user has access to, can add commands to run on user login and more. A malicious actor could even have a useful plugin, but with an undisclosed exploit.

Users installing plugins are not going to be aware that simply installing a plugin could do something as damaging as remove their entire user directory, and it shouldn't be allowed. Kubernetes is a big ecosystem, and I doubt it would be that hard to convince users to install your Helm plugin. A user running `helm plugin install https://github.com/helmawesome/helm-awesome-plugin.git` will have no clue that by doing so, they could have just exposed their entire system.
