### ISSUE TITLE
Some values get 'stuck', even after changing

### ISSUE THREAD

**Issue by rolaca11** [helm/helm#10333]
Output of `helm version`: 3.7.0

Output of `kubectl version`: 1.22.1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): DigitalOcean

I have a helm chart for an ELK stack:

_Chart.yaml:_
```
apiVersion: v2
name: elk-stack-chart
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.0

dependencies:
  - name: elasticsearch
    version: 7.15.0
    repository: "https://helm.elastic.co"
  - name: kibana
    version: 7.15.0
    repository: "https://helm.elastic.co"
  - name: logstash
    version: 7.15.0
    repository: "https://helm.elastic.co"
  - name: filebeat
    version: 7.15.0
    repository: "https://helm.elastic.co"
  - name: metricbeat
    version: 7.15.0
    repository: "https://helm.elastic.co"

```

_values.yaml (omitted irrelevant parts):_
```
# ...
elasticsearch:
  clusterHealthCheckParams: wait_for_status=yellow&timeout=10s
  esConfig:
    elasticsearch.yml: |
      xpack:
        security:
          enabled: true
      discovery:
        type: single-node
  minimumMasterNodes: 1
  replicas: 1
  resources:
    limits:
      cpu: '1'
      memory: 1000Mi
    requests:
      cpu: 300m
      memory: 1000Mi
  volumeClaimTemplate:
    resources:
      requests:
        storage: 10Gi
  esJavaOpts: -Xmx550m -Xms550m
# ...
```

Running `helm upgrade monitoring . -n kube-system --dry-run --debug -v 3`, in the USER-SUPPLIED VALUES section I see this:
```
elasticsearch:
  clusterHealthCheckParams: wait_for_status=yellow&timeout=10s
  envFrom:
  - secretRef:
      name: monitoring-elk-stack-chart-credentials
  esConfig:
    elasticsearch.yml: |
      xpack:
        security:
          enabled: true
          transport:
            ssl:
              enabled: true
  minimumMasterNodes: 1
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 800Mi
    requests:
      cpu: 300m
      memory: 500Mi
  roles:
    master: "true"
  volumeClaimTemplate:
    resources:
      requests:
        storage: 10Gi
```

Some of these values differ from what I have in my `values.yaml`. At some point I did have these values, but they have been rewritten multiple times now. I can also see the section about `fluentd`, but this has been deleted weeks ago. This is problematic, because it obviously passes wrong configuration values to kubernetes as well.

Another interesting thing is when I try to install this chart with another name on another namespace, the `USER-SUPPLIED VALUES` part is empty and the values I defined in `values.yaml` are passed correctly.

What causes this error to occur? How can I reset this?

_UPDATE:_
I tried running `helm install monitoring . -n kube-system --dry-run --debug -v 3` (so on the same namespace, same name as the currently deployed chart, but instead of _upgrade_, I used _install_) and the USER-SUPPLIED VALUE section is correct again. Obviously I can't use that without the --dry-run flag, because there is a chart already deployed with that name, but it might help in debugging.
