### ISSUE TITLE
Allow different output formats in `helm dependency list`

### ISSUE THREAD

**Issue by paleloser** [helm/helm#10345]
The current `helm dependency list` subcommand only allows configuring the standard's output column width.

However, for automated processes it'd be nice to have a way to configure the output format, so a user could run `helm dep list -o json` (or `yaml`, as in other commands). It doesn't seem complicated to show a JSON or YAML view of the standard table:

```json
[
  {
    "name": "mariadb",
    "version": "9.x.x",
    "repository": "https://charts.bitnami.com/bitnami",
    "status": "missing"
  }
]
```

```yaml
---
- name: mariadb
  version: 9.x.x
  repository: https://charts.bitnami.com/bitnami
  status: missing
```

I believe this minor proposal doesn't require a HIP.

Output of `helm version`:

> version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}

Output of `kubectl version`:

Doesn't apply.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Doesn't apply.
