### ISSUE TITLE
resource is deleted after helm uninstall with annotation 

### ISSUE THREAD

**Issue by mohan-nagandlla** [helm/helm#10359]
HI team I just passed the annotation to PVC to make it available even after helm uninstall 
```
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      helm.sh/resource-policy: keep
```
But if I uninstall the helm release I am loosing PVC too any additional things am I need pass?

**Comment by bacongobbler** [comment]
Hi @mohan-nagandlla. Please provide the information requested in the issue template:

```
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```

It is unclear what version of Helm/Kubernetes you are testing against, so we cannot rule out whether you're using an older version of Helm that may be missing an important bugfix.

Additionally please provide a sample chart to test. That way others can attempt to reproduce the issue and attempt to identify a fix.

Thanks.

**Comment by mohan-nagandlla** [comment]
```
Helm version 3.7.0
Kubectl version 1.18.0
```

**Comment by mohan-nagandlla** [comment]
Any updates

**Comment by bacongobbler** [comment]
> Additionally please provide a sample chart to test. That way others can attempt to reproduce the issue and attempt to identify a fix.

Without a way to reproduce the issue, we cannot help you.

**Comment by AlexisDuf** [comment]
Hello, 

It seems I have the same issue: 

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  annotations:
    meta.helm.sh/release-name: elasticsearch-stack
    meta.helm.sh/release-namespace: elk
   "helm.sh/resource-policy": keep
```

I also tried `"meta.helm.sh/resource-policy": keep`

Helm version: v3.7.2
Kubectl version: v1.22.2
Cluster Type: Kind(v1.21.1)
