### ISSUE TITLE
[Question] How to use templates in Files.AsConfig (with range loop)?

### ISSUE THREAD

**Issue by seungdols** [helm/helm#10358]
Output of `helm version`:
❯ helm version  
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}

Output of `kubectl version`:

❯ minikube version
minikube version: v1.24.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

minikube 

There are several environmental settings such as Nginx, Filebeat. 

```yaml
  nginx:
    volumes:
      - name: nginx-config-volume
        mountPath: /home/apps/nginx/conf/nginx.conf
        subPath: nginx.conf
        configMap:
          files:
            - files/nginx/dev/nginx.conf
       - name: filebeat-config-volume //bla bla      
       - name: other config-volume 
```

files/nginx/dev/nginx.conf 

```conf
  upstream  front {
    server {{ env }}-front-server fdns;
  }

```

values.yaml

```yaml
env: dev //  dev 1 dev2  or production
```

configmap 

```yaml
{{- $files := .Files }}
{{- range $key, $value := $volumes }}
  {{- if $value.configMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $defaultName }}-{{ $key }}
data:
    {{- range $name := $value.configMap.files }}
{{ tpl ($files.Glob $name).AsConfig .  | indent 2 }} <--- error: at <.>: wrong type for value; expected chartutil.Values; got string
    {{- end }}
  {{- end }}
{{- end }}
```

And in this case, the tpl function does not operate in this case, and how it is not working normally.

I want to apply tpl functions to each setting in range loop.  

What should I do ?
