### ISSUE TITLE
How to label a namespace in pre-install hook & delete after Helm uninstall

### ISSUE THREAD

**Issue by moluzhui** [helm/helm#10355]
I have a project that needs to use `mutating Webhook`, based on `namespaceselector`, which needs to add specific **label** to namespace first. 

I used three hooks, **hook1(pre-install, pre-delete,etc)** to create **RBAC** for **hook2(pre-install)** to add a label to namespace by **Job** and **hook3(pre-delete)** to remove the label by **Job**
Hook content is as follows:

**Hook1** to set permissions 
```
# RBAC.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ns-edit
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ns-edit
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edit-ns
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ns-edit
subjects:
- kind: ServiceAccount
  name: ns-edit
  namespace: kube-system
```
**hook2** to add label to namespace
```
# label-ns.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: label-ns
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: labeler
        image: gcr.io/google_containers/hyperkube:v1.18.0
        command:
        - kubectl
        - label
        - ns
        - kube-system
        - mutating=disabled
        - --overwrite
      restartPolicy: Never
      serviceAccountName: ns-edit
```
**hook3** to delete label to namespace from hook2
```
# delete-ns-label.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: del-ns-label
  namespace: kube-system
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: labeler
        image: gcr.io/google_containers/hyperkube:v1.18.0
        command:
        - kubectl
        - label
        - ns
        - kube-system
        - mutating-
      restartPolicy: Never
      serviceAccountName: ns-edit
```

After **helm install ...**, **both hook2 and hook3 jobs were triggered** and **completed**.

```
helm install mutating-webhook mutating-webhook-0.1.0.tgz --debug
client.go:254: [debug] Starting delete for "ns-edit" ServiceAccount
client.go:283: [debug] serviceaccounts "ns-edit" not found
client.go:108: [debug] creating 1 resource(s)
client.go:254: [debug] Starting delete for "ns-edit" ClusterRole
client.go:283: [debug] clusterroles.rbac.authorization.k8s.io "ns-edit" not found
client.go:108: [debug] creating 1 resource(s)
client.go:254: [debug] Starting delete for "edit-ns" ClusterRoleBinding
client.go:283: [debug] clusterrolebindings.rbac.authorization.k8s.io "edit-ns" not found
client.go:108: [debug] creating 1 resource(s)
client.go:108: [debug] creating 1 resource(s)
client.go:463: [debug] Watching for changes to Job label-ns with timeout of 5m0s
client.go:491: [debug] Add/Modify event for label-ns: ADDED
client.go:530: [debug] label-ns: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:491: [debug] Add/Modify event for label-ns: MODIFIED
client.go:530: [debug] label-ns: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:491: [debug] Add/Modify event for label-ns: MODIFIED
client.go:254: [debug] Starting delete for "ns-edit" ServiceAccount
client.go:254: [debug] Starting delete for "ns-edit" ClusterRole
client.go:254: [debug] Starting delete for "edit-ns" ClusterRoleBinding
client.go:254: [debug] Starting delete for "label-ns" Job
client.go:108: [debug] creating 10 resource(s)
...

helm get manifest mutating-webhook | kubectl get -f -
...
NAME                     COMPLETIONS   DURATION   AGE
job.batch/del-ns-label   1/1           3s         3m40s
job.batch/label-ns       1/1           3s         3m40s
```
Why does **post-delete hook** trigger at `helm install` and it seems that the `"helm.sh/hook-delete-policy": hook- succeeded` policy did not trigger to delete job.

I really appreciate any help with this.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"archive", BuildDate:"2021-05-25T03:24:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"archive", BuildDate:"2021-05-25T03:24:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
