### ISSUE TITLE
Values not passed to second instance of aliased sub sub chart

### ISSUE THREAD

**Issue by thrawny** [helm/helm#10407]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"2444b3347a2c45eb965b182fb836e1f51dc61b70", GitTreeState:"clean", BuildDate:"2021-11-17T13:05:33Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"darwin/amd64"}
```

## Problem

I came across this bug when trying to create multiple instances of a of dependency that in turn had aliased dependencies. Can be reproduced with the following chart.

```yml
apiVersion: v2
name: parent
description: parent
type: application
version: 0.0.1
dependencies:
- name: sub-chart
  version: 0.0.1
  alias: sub1
- name: sub-chart
  version: 0.0.1
  alias: sub2
```

```yml
apiVersion: v2
name: sub-chart
description: sub-chart
type: application
version: 0.0.1
dependencies:
- name: sub-sub-chart
  version: 0.0.1
  alias: sub-sub1
```

In sub-sub-chart we have a template like this.
```yml
name: {{ required "name is required" .Values.name }}
```

Using this values file for the parent chart.
```yml
sub1:
  sub-sub1:
    name: foo
sub2:
  sub-sub1:
    name: baz
```

Testing it out gives this error
```
helm template test ./subsubalias
Error: execution error at (parent/charts/sub2/charts/sub-sub-chart/templates/test.yaml:1:9): name is required
```

Values are not getting passed to `sub2.sub-sub1`.

From my limited understanding of the code base, it seems the bug comes from the fact that a requirement with an alias has its name overwritten to the alias value at some point. And if that requirement is used again it cannot be matched against an existing chart by name. See linked PR with chart example and proposed code fix: https://github.com/helm/helm/pull/10381
