### ISSUE TITLE
dynamically pull data from values.yaml

### ISSUE THREAD

**Issue by angsdey2** [helm/helm#10400]
I have values.yaml like below

 ```
configMap:
  data:
    dev:
      ATTR1 : "Value1-dev"
      ATTR2 : "Value2-dev"
    qa:
      ATTR1 : "Value1-qa"
      ATTR2 : "Value2-qa"
```
My configMap template is like below

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.service.name }}-configmap"
data:
  ATTR1: "{{ .Values.configMap.data.<env>.ATTR1 }}"
  ATTR2: "{{ .Values.configMap.data.<env>.ATTR2 }}"
```
Is there any way I can dynamically pass the "env" value to populate data for different environment?
