### ISSUE TITLE
Passing json objects/arrays as values through --set

### ISSUE THREAD

**Issue by lucadirocco** [helm/helm#10428]
I would like to set  json objects/arrays as values through --set.
According to https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set
currently that is not possible (with the exception of arrays of scalar types) 

As example, let's  take the following excerpt from my values.yaml file:

```
spec:
  ....
  sNssaiUpfInfoList:
  - sNssai:
      sd: 0002f0
      sst: 1
    dnnUpfInfoList:
    - dnn: intranet
      ipv4AddressRanges:
      - end: 9.9.9.94
        start: 9.9.9.65
  ....
```

In the template there is all the "range" based logic for slices and maps, to correctly render sNssaiUpfInfoList from .Values.spec.sNssaiUpfInfoList, so further elements could be added to each of the above arrays and they would appear in the final manifest generated by helm.

In order to set sNssaiUpfInfoList above, currently I have to set the individual leaf attributes of the data structure, by providing the following with --set  on command line:

`'spec.sNssaiUpfInfoList[0].sNssai.sd=0002f0,spec.sNssaiUpfInfoList[0].sNssai.sst=1,spec.sNssaiUpfInfoList[0].dnnUpfInfoList[0].dnn=intranet, spec.sNssaiUpfInfoList[0].dnnUpfInfoList[0].ipv4AddressRanges[0].end=9.9.9.94, spec.sNssaiUpfInfoList[0].dnnUpfInfoList[0].ipv4AddressRanges[0].start=9.9.9.65'
`

This is not very flexible because extra logic is required to translate the data structure into individual key=val for each of its leaf attributes. Moreover, the arrays are dynamic, and quite a long list of key=val could be generated.

I think it would be much simpler if we had an option to set a complete json array/object on the command line.  
For example, to set sNssaiUpfInfoList above, we could use something like:

`--set-json  'spec.sNssaiUpfInfoList=[{"sNssai":{"sd":"0002f0","sst":1},"dnnUpfInfoList":[{"dnn":"intranet","ipv4AddressRanges":[{"end":"9.9.9.94","start":"9.9.9.65"}]}]}]'
`

Is it possible to add this option to helm?

**Comment by mattfarina** [comment]
I think this would be possible.

**Comment by lucadirocco** [comment]
Thank you for your reply.
Do you think it can be an interesting feature and get implemented?
In case, what the next steps would be?

**Comment by mattfarina** [comment]
@lucadirocco I think it's an interesting feature. The next step would be for someone who is interested in the feature to create a pull request and try to implement it. Anyone is welcome to do this.

**Comment by lucadirocco** [comment]
Hello @mattfarina , I have implemented this feature already last month, but I haven't issued a pull request due to lack of time and info about possible conditions/processes to be fulfilled/followed before issuing a pull request.
Can you please share any links/docs that can help me with the info above?
I'm going to have some spare time in the coming weeks and I would like to complete the work and issue a pull request.
Thanks in advance.

**Comment by anurnomeru** [comment]
I am writing this pr, which can implement the json replacement for a key mentioned in the issues, but there are several problems here, and K8s has encountered similar problems.

And according to the existing helm design, the actual effect is not to replace the value of entire key, but to cover the specific value. In addition, ambiguity arises when dealing with arrays:

That is to say, the original values.yaml is as follows:
````
spec:
  ....
  sNssaiUpfInfoList:
  - sNssai:
      sd: 0002f0
      sst: 1
    dnnUpfInfoList:
    - dnn: intranet
      ipv4AddressRanges:
      - end: 9.9.9.94
        start: 9.9.9.65
  ....
````

After "--set-json 'spec.sNssaiUpfInfoList[0]=[{"dnnUpfInfoList":[{"dnn":"intranet","ipv4AddressRanges":[{"end":"9.9.9.100"}]}]}]'"

The result obtained is actually:

(append to the array `dnnUpfInfoList`)

````
spec:
  ....
  sNssaiUpfInfoList:
  - sNssai:
      sd: 0002f0
      sst: 1
    dnnUpfInfoList:

    - dnn: intranet
      ipv4AddressRanges:
      - end: 9.9.9.100

    - dnn: intranet
      ipv4AddressRanges:
      - end: 9.9.9.94
        start: 9.9.9.65
  ....
````

or (replace the original array `dnnUpfInfoList`):

````
spec:
  ....
  sNssaiUpfInfoList:
  - sNssai:
      sd: 0002f0
      sst: 1
    dnnUpfInfoList:

    - dnn: intranet
      ipv4AddressRanges:
      - end: 9.9.9.100

  ....
````

but not (merge by `dnn: intranet`):

````
spec:
  ....
  sNssaiUpfInfoList:
  - sNssai:
      sd: 0002f0
      sst: 1
    dnnUpfInfoList:

    - dnn: intranet
      ipv4AddressRanges:
      - end: 9.9.9.100
        start: 9.9.9.65
  ....

Because in fact, the values ​​of helm do not have a design similar to **patchStrategy**, it is impossible to know whether the user wants to merge according to some item's trait in the array, or append the item ​​into the array, or even replace all the elements of the array.
