### ISSUE TITLE
Downloader plugins "commands" fields not consistent

### ISSUE THREAD

**Issue by jdolitsky** [helm/helm#10431]
Downloader plugins appear to need a custom `command`, separate from the top level command.

Given the following example:
```yaml
name: "demo"
version: "1.2.3"
command: "bin/demo.sh"
downloaders:
  - protocols:
      - "demo"
```

Running a pull command returns a strange error:
```
$ helm pull demo://some.example.com/mychart-1.2.3.tgz
Error: fork/exec /Users/myuser/Library/helm/plugins/demo: permission denied
```

So we fix this by adding a nested `command`. Here is the new example:
```yaml
name: "demo"
version: "1.2.3"
command: "bin/demo.sh"
downloaders:
  - protocols:
      - "demo"
     command: "bin/demo.sh"
```

which works, but is a bit redundant.

However, this is somehow not a valid plugin config to run the plugin command itself:
```
$ helm demo
Error: fork/exec bin/upload.sh: no such file or directory
```

Finally, we are able to get everything working by adding `HELM_PLUGIN_DIR` to the root `command`:
```yaml
name: "demo"
version: "1.2.3"
command: "$HELM_PLUGIN_DIR/bin/demo.sh"
downloaders:
  - protocols:
      - "demo"
     command: "bin/demo.sh"
```

```
$ helm pull demo://some.example.com/mychart-1.2.3.tgz
(no error)
$ helm demo
(no error)
```

So ok, lets try adding `HELM_PLUGIN_DIR` everywhere so at least we are consistent:
```yaml
name: "demo"
version: "1.2.3"
command: "$HELM_PLUGIN_DIR/bin/demo.sh"
downloaders:
  - protocols:
      - "demo"
     command: "$HELM_PLUGIN_DIR/bin/demo.sh"
```

which causes a new issue:
```
$ helm demo
(no error)
$ helm pull demo://some.example.com/mychart-1.2.3.tgz
Error: fork/exec /Users/myuser/Library/helm/plugins/demo/$HELM_PLUGIN_DIR/bin/upload.sh: no such file or directory
```

Both `command` fields should be consistent. They should respect `$HELM_PLUGIN_DIR` in the same way (or both use relative paths). In addition, a top level command should be sufficient for a downloader plugin to function (i.e. the first example at the top should work fine).

Discovered this issue working on #10430

**Comment by mattfarina** [comment]
I think this might be a documentation issues, more than anything.

A plugin can contain multiple downloaders for different protocols and the command for each downloader can be different from the other downloaders and from the plugin itself. There is a lot of flexibility here.

I ended up going back to re-read https://helm.sh/docs/topics/plugins/#downloader-plugins and look at the testing example at https://github.com/helm/helm/blob/main/pkg/plugin/testdata/plugdir/good/downloader/plugin.yaml

**Comment by jdolitsky** [comment]
@mattfarina - please try installing and running the example plugin you shared. You will notice that even `"echo Download"` example is unsupported:

```
$ git clone https://github.com/helm/helm.git
Cloning into 'helm'...
...
$ helm plugin install helm/pkg/plugin/testdata/plugdir/good/downloader/
Installed plugin: downloader
$ helm pull myprotocol://r.example.com/mychart
Error: fork/exec /Users/myuser/Library/helm/plugins/downloader/echo: no such file or directory
```

So we have both a docs issue and a functionality issue.

The most popular downloader plugin is probably [helm-s3](https://github.com/hypnoglow/helm-s3). Even there, you have one command referencing `$HELM_PLUGIN_DIR/bin/helms3` and the other `bin/helms3`. Why?

Why could I not have either `bin/helms3` twice or `$HELM_PLUGIN_DIR/bin/helms3` twice?

Furthermore, if the commands are identical, why do I need to specify the second one? (I understand that multiple protocols could be mapped to different commands, so this seems less high priority)

Here is the helm-s3 `plugin.yaml`:

```yaml
name: "s3"
version: "0.10.0"
usage: "Manage chart repositories on Amazon S3"
description: |-
  The plugin allows to use s3 protocol to upload, fetch charts and to work with repositories.
  https://github.com/hypnoglow/helm-s3
command: "$HELM_PLUGIN_DIR/bin/helms3"
downloaders:
- command: "bin/helms3"
  protocols:
    - "s3"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./hack/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./hack/install.sh"
```
