### ISSUE TITLE
Docs/Help:  persist installed packages configuration (not just values)

### ISSUE THREAD

**Issue by reddec** [helm/helm#10455]
Hi everyone.

I am new in Helm and sorry to bother you. Maybe I am blind, but didn't find anything about how to persist installed packages configuration (not just values).

In my mind it should be something like:

```yaml
- package: example/wordpress
  version: x.y.z
  namespace: wordpress-example
  values: # ...
```

Obviously I found info about storing **values** in files, but not packages (at least names and versions). Something like should be opportunity to call `helm apply -f packages.yaml` and restore cluster configuration.

Am I missing something? Shall I just contribute and create PR for that?
