### ISSUE TITLE
nil pointer evaluating interface in ranges

### ISSUE THREAD

**Issue by k3env** [helm/helm#10454]
`.Release` contains an `nil` value when using `range` in template

Output of `helm version`: `version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+k3s1", GitCommit:"61a2aab25eeb97c26fa3f2b177e4355a7654c991", GitTreeState:"clean", BuildDate:"2021-11-04T00:24:35Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): k3s

**Comment by yxxhero** [comment]
@k3env Can you provide a example? Thanks very much.

**Comment by k3env** [comment]
template:
```
{{- range .Values.values }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-{{ .config }}
  namespace: {{ .Release.Namespace }}
data:
  config:  {{ .config }}
  value: {{ .value }}
{{ end -}}
```
values:
```
values:
  - config: foo
    value: bar
  - config: abc
    value: def
```
expected output:
```
helm template test-chart .
---
# Source: test-chart/templates/config.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-foo
  namespace: default
data:
  config:  foo
  value: bar

kind: ConfigMap
apiVersion: v1
metadata:
  name: test-abc
  namespace: default
data:
  config:  abc
  value: def
```
output:
```
helm template test-chart .
Error: template: test-chart/templates/config.yaml:6:24: executing "test-chart/templates/config.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
```

**Comment by yxxhero** [comment]
@k3env  In the range statement, the scope of `.` is changed. You should assign the global `.` to the variable outside the range statement, and then refer to it.

**Comment by k3env** [comment]
Thanks for the explanation.
I used `{{ $.Release.Namespace }}` instead of `{{ .Release.Namespace }}` and it worked.
Didn't pay attention to this section https://helm.sh/docs/chart_template_guide/control_structures/
where it says directly that `$` is a pointer to the root scope

**Comment by alexssantos** [comment]
Thanks, @k3env !! It works for me.  Same problem. <3

**Comment by kkashyap1707** [comment]
Didn't worked.

` at <$.mdnsOverlay.replicas>: nil pointer evaluating interface {}.replicas
`

**Comment by Heldenkrieger01** [comment]
@yxxhero I followed the comment made by @k3env, but I still get the same error, as also reported a week ago by @kkashyap1707.

`Error: template: .../deployment.yaml:3:8: executing ".../deployment.yaml" at <include "named.template" .>: error calling include: template: .../_helpers.tpl:6:17: executing "named.template" at <$.Release.Namespace>: nil pointer evaluating interface {}.Namespace`

_helpers.tpl
``` yaml
{{- define "named.template" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .config.name | default "def-nam" }}
  namespace: {{ $.Release.Namespace }}
spec:
[trimmed]
---
{{- end }}
```

deployment.yaml
``` yaml
{{- range .Values.values}}
  {{- include "named.template" . }}
{{- end }}
```
