### ISSUE TITLE
Request entity too large on installation

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [helm/helm#10483]
I saw this topic came up several times but none of the previous topics was able to clarify my problem here. I created a simple chart that produces the following output on `helm template ... ...`

the keystores here are for my localhost machine so there is nothing especially secret on them.

```yaml
---
# Source: my-panstar/templates/panstar-gateway/panstar-gateway-config-map.yml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: panstar-gateway-215-config-map
  name: panstar-gateway-215-config-map
binaryData:
  panstar-gateway-tls.p12: |
    MIIKVwIBAzCCChAGCSqGSIb3DQEHAaCCCgEEggn9MIIJ+TCCBcAGCSqGSIb3DQEHAaCCBbEEggWtMIIFqTCCBaUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFIy1KIGHArBzjbAnuU/LL7fVPS/2AgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ3F4xDV+AWHl9bBuo1mfrzQSCBNBtCN116fayQ/3zGhXiJPXPmpMIS+xMeuszxyc4uSszWTSG1/Mgbkql58/HXjVjlMQb8Bz0wKFgM6cPdBvJ+P9S/0VOuceQKPx+FwvB/fB40eViKuPrTQKj7C7QFgb3KupW+arAZTwvwTR1AE0GtLLhgZYByd94qpOnN5+802quSLQnHUHHt24UXiTExHt2Kq8FasD6MKoRi45O57sQIl2NS0V5ezgKFf/Y2vT3i4PL9oD017X4blA18WCKZo4oUh7J9yqasQglmTJdDetmqLM15cuZ0WHZZqWo/rhCCOJ3DCCkNBcDU5tQR4Pr8iF07xIWLdUJoeu5mF+2m/y2uk5JQipedJ7prlhrWuYNArrrSxvFqKPrKWJTprbQ5OoedmvTSrhl0kDOKDpaNpaSh2cmZOfWFZQNlUOaqTeVdY3+/LbRnGkdpyFmqZGlN8Dzngn3GtIPcx4T2poQY7mceEsxiLmdZjzuW8TwJcwx9VVVE7OMyuoHvYKDn2BfZBm+XkA8IWq7MgFEcO3UfEe/npE78Pa6IF8R1m/ImksvP+0cXoa/vfyBwVcAZulMd6F908zBd7D2n67LWUvFSLvKcTE3QFFMhNC7o+MYCpD+45ZO5BKHcPCSynalA9tRCTSm7tCOZjIMr9EB5QIlvibRWVUeKUeuEMpWCI8cAM3l7jkciBQru/hYsrszd+KSElSaG4gua1H9pm5XFa/9r8YeCfs8wn+AL/iC2KrPaBMhIjpdiznSJHI+oenK8XPPXMaV0d3mWMmQX7sMwpPXmV07yCx4TGyCXNHA8Z8Y8CNV1eVgp/fxqIlsDpu3j4H3ns6pvlnLrKaRQrFTHXno1QglR7daIEM2SqphBUG6YXwcwH01Zz8ohmfgHYGbFY34AErFYH7EL38YIWJRC8vBHCOXP6PZaNsB25+kv7IMdtYBMOM2U20qP99Rt3sSv/Z2G7OImsaCfhA27psmAEMDvjhi4CEp0Jd4YYyNw4qmzCXYGMbxg5pb/RyweLiWb3ZQtuEQJM4LlIuF5eZ5uyRh78GDAsMc5P/0zJ0bU++2DfisJVmIBhJ1FElWsFzGzpWaY4rAgzAy7rhEd55nJ29BlwzKTKTpSE0jZr9lE/58jmHksIa4VWm/qXXH25DBtIusg4pu+YOcB9h5eDKsFGC85bEaGn6bz82vmjPRJAJ8dhA+7HlBorUq7KvVo8DpMr9hPQvLpwFvKpm27i8h5N3aw9xLMgCAFlFOJ6wayEc0CRYVz0f0DnAegUywTg6RJcJYMCTqBsQDX9Foh5yFtrnZt/Eh0IJXBTNw0W9A8ncjXfUw3jucgbxOpwKLVgCEfmk5lLLX7w8rcd2uWyA7wnWJFRJHgbR6zW6Xxaam1vQLXY7D0iS5+HfNPWEO+v/LymJcFtekIbqagWpUN216MjXBsPsmNmX/TjzmwPfNw+sH62zDSfBo7R7kMgIHqnavNoVqN/vIYF4JN+Y+NjMSJdspKHzHkGeQWYHwybqM68rvCeuG9Gu+lKSM1JTJGbYP9D+jZA8LIKzjNIcU2cgutjA3L7Z1mjsWTO4IcWi3WecWVT6gkUs98pBjVJsBtiFL2IuOzQTmiEL3H4TMKC0JbKFvoI7CMjnDBGTVopjGSqSrgal0jzPg4DFSMC0GCSqGSIb3DQEJFDEgHh4AcABhAG4AcwB0AGEAcgAtAGcAYQB0AGUAdwBhAHkwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTYzOTgyMzU5MzU0NjCCBDEGCSqGSIb3DQEHBqCCBCIwggQeAgEAMIIEFwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBTTgL2WSAtzOMAN9K1hNkz6A7c5cAICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEOAy3TeOoqSfA2KXPjmfqsKAggOgAtN5Pri+z83UEgX+uAZVKiccB8KINUhjEWfdWkSEnhUFuGeQEIvHnVZnJcXmt/SRt/NkdKMtovlNGyhEBvMmzJCF5RIm4pB2ZllyCrbJiQD/XdqF05LJkpRMBGxq6FSvglm8QKi/VShfYbLjQSLejLiuSqzYoQauYZmHRvqNyUVJ9ZWRU+7M6CkYbXmWFmLA2lAK3H/H20u4O1tRt3H+OztTzML/umas3ga5KZlPKx+caEtgveZcGdnsjI7tMAtdd3oEOjqj02y8TvKJcmcxnkhujczfQS2solgCl4gG96Hqc6vju/LR2axDED2m/zmJYrD5KxWdUNAIQCqDYVP2qbSvi+MHfw310T7r6r5Ik4d1Ucg5J0BEYDL900K/IdEAGc/8HlZBw50c81Hlw17Y3qsZYWdvdCVBEQgP/vcLDMtBRuG2Ya8mplKgd3aSDAjF9siHDxT0/5VrVZGfrDI3A9XzduPW4u4WuJQnv3ogCrM3wdKc8Jj2HIiB9gQPW67XAe1kaRCQ1mRUceh6LQbaYChiPZhcx8c+hmGuBynGjStXlCsGKM4eVn+Zsix0AHFaPzw4QFxJcrO9wEdXwCH5tZ2HqcR5cZxJOXC8lZPvA1zV1n7nuxXpMQXU1xvxTnB0QBk3iV+uVwV9KkbWzSmq7u/U/IVYGgLdGUp6TmelWEYwSE+i81aB66w3a038689ER53AWlmgmEqqouvhWehVzQEJCd4BwALZhCLs91yb/maiiiJ5Ghj99PteIzhaDo2RdEcKUZ+7ZrHLuSyuCJ8oy5DlnYyyRfootXvPEVfE2zNd/tk7jCe2iRLKa//liRJcQYewXhlLr1e3lMUANCu6yQ61+JaONPUP5D+3Pu8Z/H0S4QKF5GBks8+pyXfW9V8OOldEooJegPnpKWH/6u1++WOHpZvgDvizgcAkhjxjxGaPJOk8J1xiw9At/EguVW/2eBY1hVcfx12oGR+G2lDVmiiLxE8p3HWcD2gXiSuTrByrOQodKpJPA6UEAfSYNqz9r5vajReLTyuXOkytBWZo5le3lI8EE0yQ6OFoLAJDnTwRX+BdXDtfdMKmRsJ4PXJ9292HnJqJa0rL4cwypht7/Xh6T8HLJI3U9dGHwYBN0iSgf6F5c9kBP3K1k/Plm1/X7SN7zm1DRQt3RrR9v1rXKw1uXaqBZfQHF7qb+W3Tf3JxpG4ugn3tuvstMdZOPX1LS6OaCop/aTQwtNHJpPyE4jA+MCEwCQYFKw4DAhoFAAQU+5nWue8J7tQi9k8da832gVHZWK4EFHUODp460XkzYtjNh8puZ6+zctcjAgMBhqA=
  panstar-gateway.truststore: |
    MIIKMQIBAzCCCeoGCSqGSIb3DQEHAaCCCdsEggnXMIIJ0zCCBboGCSqGSIb3DQEHAaCCBasEggWnMIIFozCCBZ8GCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFLIQMyDf/Fq2HTUOTtwSuvPjgI5kAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQWLblVr8hd36vmZe9sT1XMwSCBNCBFfAlLO0+uTBvl94rwTDYL8OLw2HkMCHuQ9LzuyLQyjqxugn1p5jAYnvVEGnjIvJcpAKkeSP++SrY8sQfxK8/OfP6ZzVXrTreGJw2NGn2/87jUBPkIuOqaXq2iAyD/DxJmopcTi8zXt031zYqiZ4GxDEr18akPjUlMuKL7SQ9lbhXvDdgQwlE93aQlcUJyxdQGIe+zRM6ees7y5lXHkhgofdv1V9DmoNjNjBzw585L1Qw1AjokIWnkBu7QQdYvsSGef+C9Q85apRwxGZBPF4/sbjdQ+7NupqQwI4qFd2X17+SyOrEEuNykolST5SK/3en2KaK+IqiG0Hu/BxIOiTERUkj9v3s4kbVXvz8MOBGFQnCjdbszePnk1YfKyMWjIqzDjYMLIQcGRUxbhnIqav81F3qRAgV8ntsfY9hTlKALEV7TFYja1XroFYmFm9WyfNzz8Sbk8viFJ3Nk+MCTKa8stQhxy/hor3/Eqs1HQr/O5KRDdQPT2LI3ShChGYKLJd+FaeZjeTl0r7sPkM4oMGJCakirkKAwAeSD3yxXK9Hu/+PeuEKuK5BshIlv6wnP395kG64tj1Hl7tn+4zfZmFK49hlFisHNqBXqBh1+03rrHtf4W+p8oHATQ7X9/5FZhApocuirOYtyDKsluJ3DPZKLzAd8pXBRb4gdZ20cEFVQwpgJxpekjLoSaYiOu8Qx2fBv9JVgtvivzSQrYQtmgRzMpI0G5QNLHWjeIjZmNizARFZ1srPXhSskcRYaMotLsZ5TUw2qHrNxJEpjlTXUkFlytc2U6GJEwoYnijnbYeW6PA3x4bEFE+JYzbTjzIlaDVzY95CyBvFJVcgyhSmNllcVXndZUbmu0UNSSbCaKQ3gA4N2YwQgNVTd4e+LWDfZtUtSDmUu8BPZ92671M4/ZPMZDQLGPlDyRJDAAcIV6phvmabvDPu+fCvCW+LdvUmZl3xYg/H9sVFKCFsJXQMD+ahP6za3/cvj0pKTWEFAldWc8Jy1Mfae+BX8yzKomemU4YZB0o1dpuFu+pUZluT07ORhU8jPwGGrG2k1EjpUUFPKELpMv9KlH35Bgs1oc05HXSieMCoFU+EDXRAye0RhIw7dkITBOrLkodkRyoJiLzjXNsquYhzPYksUFtzYtoP4cnEw0xTjCqmPNgzM1igNn6bEDp/qr6hUvIDeucIx1EBABYKCi4awb9Im0QJ4oFnuk+/5Y8S6boXwrlRBvv06hWn1oULnpBlMJ49zj0qdW+6UAdNL8NZBlscfq5VM5MjpoMBhWtEFU1qys7Y4OLEHTCJNB3aUGWP9r8zBUWn/lavQdbniZ2G4O+4b8WeZVo/HFLlB0WU3jerHYZlq8onNPp/7rKVBsTEIf6n4vtBJidCB0kW9KlhbHy7BK67EEROasklVmttBaVuLnnJbIgErYc8CBo8YTBpZkm+1A7W2CH2/R3RSt97kLIVc1K93PQXKTF42XXKyYBdPxQFTHBmVXQzyFe+VajJqI3X1tBAz9JYIAyDHfJHkOXmWa4a9fN0VwUlgqRceeqEBepDHlTMBBnA2R0L8IN2tfrcd9CPXTz/bhMBWT1rGstzaOEyGkGWmJZOGkXNIYqaXy1JCjAJxZ5Anwp9YTYvcCQbREnvBGPYkjFMMCcGCSqGSIb3DQEJFDEaHhgAcABhAG4AcwB0AGEAcgAtAGMAbwByAGUwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTYzOTY2MTY0Njc3MzCCBBEGCSqGSIb3DQEHBqCCBAIwggP+AgEAMIID9wYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBSj22N4s/OMCjZTTvp5Bnfhq/MSJwICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEH4+RSD90bZTksODWkt8RS2AggOAjQEZObQzJ7s1tC+sKvWhIM9Y00AOwV6pZZhm5ea/a9VK/Li4xxHhqmcu5/7083BKTpdIwZ+s+sxKH1cQWvBao8NkxsfHpiC9+mF3f8o5ElBI6Qc9fMru1Qlw4PRlqWMVn/qc1CUGrd5QXsf5QIDr/+VdUtXvQUIJv7MROMLDvzlTvC7MWEs3Z42BZ0m0nviQnOnq22KsFnB1qRlel/drmzUj5lbGRR34QplEtlZ0LkvWJ+2HyjxS4VE84KDIxy11XhbAI0tYcLXbGdhtByUqtpinCNpFZjxP+vxqJZtCqEZoBX/9e/ffFh6H734GPbCbtkBFMYwN8h4KamUAj3bmoq39QTs2zi3dQ7fPSqb1f97BhXrkHyjlXjRgljfE1MrPT1UCvc4pBdsj75Q69xPXZ4IjS3z2ONtNoz0qZ1e0us1AvYX1dbKhDR3kF9/Xjx/QY9p0L/gNs2dsaM8Bh8Pj+3MoUvfLJuGUltrNAjDSYp5jUwRYGlAROvqPg717nJG1ela9+enXgHX6sSKgzsh9LE4rD8jiiPT1BMqEr5QS6oHX8Nx42+u6V1dORx+VS3/Ef0XJ/lbHciVIdnRRKt/weLsfG3lS4D9EEMML8qTjGHYHKVRWfxdbXeUeu4vmWUbendoMq9jXI1tZOwkNxmqHzKQtcwte/QJ7QfLQluC0Qlauxra5k5+tI+xDvI8MK4U9dmnUESStJPIGoUAZW6COOepyQUXCoKdzYxVFaOGANPapXiYJfILi0su7uJSEXVnh2o/0suau4Mh9eVx6ezAPh68HFUa38n/FObjeU+QNtlYImr2TbRgirw/rb7hSDk3wAU7Jxl7qwyol0DF24psE2tmfxAMOeS4qjGgacZ09zij0neJBVcWYwfEzvahgKI9SKyuepnTcW9nuFlxbBfbltwN1llG5+RBiWK7O3JgFvR/sBrnqr2Z/FOCrSh6AgA+KyPFWzt1jchS0Y2BbjVN4zip3GOEAH+6Yu97TsFEANUvnLG+/+R0NCSVwq6cW871KE/6Q6K8vYW6MRZFvtsNqlCAOO8qETvGvI3/K4vn2EIYm3NeGqcGhm5/yPH3M3TyfxrF0HeyGJsPXeI9dMjJ+Q4/Voa5TVkX7yTB7LPZKSrbcKfZr9M4WY2iAfLFKXyWfCeTyYmGlRlSHQQlyOzvBGVnDE7+fkIn66kdpp9hqpvgwPjAhMAkGBSsOAwIaBQAEFImLvvDUA4BvRsFJHMgK/YM9fpBgBBSh9TBrjqWkIZ2pDUzaBLjWCcDWEQIDAYag
data:
  # the application.properties file and the log4j2.xml that are mounted into the container
  application.properties: |
    server.port=8443
    logging.config=/opt/panstar-gateway/config/log4j2.xml
    #
    server.ssl.key-store=/opt/panstar-gateway/config/panstar-gateway-tls.p12
    server.ssl.key-store-type=PKCS12
    server.ssl.key-store-password=123456
    #
    # Panstar CORE Settings
    panstar.core.apikey=123456
    panstar.core.url=https://panstar-core-215-service
    #
    panstar.core.trust-store=file:////opt/panstar-gateway/config/panstar-gateway.truststore
    panstar.core.trust-store-password=123456
    panstar.core.trust-store-type=JKS
    #
    ############################
    server.ca.port=7444
    server.ca.key-store=file:/opt/panstar-gateway/config/panstar-gateway-tls.p12
    server.ca.key-store-password=123456
    server.ca.key-password=123456
    server.ca.key-alias=panstar-gateway
    server.ca.key-store-type=PKCS12
    #
    server.ca.trust-store=/opt/panstar-gateway/config/panstar-gateway-tls.p12
    server.ca.trust-store-password=123456
    server.ca.trust-store-type=PKCS12
    #
    server.psk.port=7445
    server.psk.key-store=file:/opt/panstar-gateway/config/panstar-gateway-tls.p12
    server.psk.key-store-password=123456
    server.psk.key-store-type=PKCS12
    server.psk.key-alias=panstar-gateway
    server.psk.key-password=123456
    ############################

  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="WARN">
       <Appenders>
           <Console name="Console" target="SYSTEM_OUT">
               <PatternLayout
                       pattern="%d{DATE} [%t] %-5level [%X{correlation-id}] [%t] %logger{36} (%F:%L) - %msg%n%throwable"
               />
           </Console>
       </Appenders>
       <Loggers>
           <Root level="info">
               <AppenderRef ref="Console"/>
           </Root>
       </Loggers>
    </Configuration>
---
# Source: my-panstar/templates/panstar-gateway/panstar-gateway-service.yml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: panstar-gateway-215-service
  name: panstar-gateway-215-service
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: panstar-gateway-215
  type: ClusterIP
---
# Source: my-panstar/templates/panstar-gateway/panstar-gateway-deploy.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: panstar-gateway-215
  name: panstar-gateway-215
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panstar-gateway-215
  strategy: { }
  template:
    metadata:
      labels:
        app: panstar-gateway-215
    spec:
      containers:
        - image: docker-hub.govkg.de/autent/panstar/panstar-gateway:2.1.5
          imagePullPolicy: IfNotPresent
          name: panstar-gateway-215
          ports:
            - containerPort: 8443
              name: panstar-gateway
              protocol: TCP
          volumeMounts:
            - name: panstar-gateway-config
              mountPath: /opt/panstar-gateway/config
          command:
            - /bin/bash
            - -c
            - |
              cd /opt/panstar-gateway
              java -jar ./panstar-gateway.jar --spring.config.additional-location=/opt/panstar-gateway/config/application.properties
      volumes:
        - name: panstar-gateway-config
          configMap:
            name: panstar-gateway-215-config-map
---
# Source: my-panstar/templates/panstar-gateway/panstar-gateway-ingress.yml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: panstar-gateway-215-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
    - host: panstar-gateway
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: panstar-gateway-215-service
                port:
                  number: 443

```

This output is not even close to 3MB and still the command:

`helm install my-panstar my-panstar`

produces the following error message:

```
PS D:\Dropbox\kubernetes\panstar> helm install my-panstar my-panstar
Error: INSTALLATION FAILED: create: failed to create: Request entity too large: limit is 3145728
```

If I copy the output above produced with `helm template my-panstar my-panstar > output` and paste it directly into my kubernetes dashboard it works fine. So what does helm produce to create this problem?
