### ISSUE TITLE
proposal(template func): add filter function to filter list

### ISSUE THREAD

**Issue by longkai** [helm/helm#10499]
There are many list item in k8s yaml, like ports, volumes and mounts:

```yaml
ports:
- protocol: TCP
  port: 80
  name: http
  targetPort: 9376
- protocol: TCP
  port: 443
  name: https
  targetPort: 12345
```
Currently when dealing with list in template, we have to `range` then `if` check what we want. The experience is not good.

How about provides a `filter` function to do it? I have custom in our own project, it looks like below:

```yaml
{{- with .Values.ports | filter "name" "http" | first }}
wantPort: {{ .port }}
{{- end -}}
```

Which supports struct field and map key, and results a clean template code. So how about adding one?
