### ISSUE TITLE
Default values for dict in a array

### ISSUE THREAD

**Issue by DougTrajano** [helm/helm#10498]
Hi guys, I'm creating a helm chart and I need to define default values for the objects inside an array.

Let me explain it with a practical example:

### Helm Chart (values.yaml)

```yaml
apps:
  - image:
      registry: docker.io
      repository: nginx
      tag: latest
      pullPolicy: IfNotPresent
    param1: alpha
    param2: beta
````

### HelmRelease
```yaml
...
apps:
  - image:
      registry: docker.io
      repository: nginx
      tag: latest
      pullPolicy: IfNotPresent
    param1: echo
    param2: delta
  - image:
      repository: nginx
      tag: latest
      pullPolicy: IfNotPresent
    param1: echo
...
```

I would like to have the `image.registry` as "docker.io" and `param2` as "beta" in the second element of the array "apps".

I tried to create a Helm Template for that, but it doesn't works. :/

**Comment by DougTrajano** [comment]
I'm trying to handle this issue by creating a template in my `templates/_helper.tpl` with the following content:

```yaml
{{- define "app.appTemplate" -}}
image:
  registry: docker.io
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent
param1: alpha
param2: beta
{{- end -}}
```

Then, in each Kubernetes Resource Definition file, I'm trying to merge each element of the array `.Values.apps` with the given template.

```yaml
{{- range $i, $app := .Values.apps }}
# {{- $newApp := merge $app "app.appTemplate" }}
{{- $newApp := deepCopy "app.appTemplate" | merge $app }}
```

I got the following error message:

```log
Helm install failed: executing ".../templates/deployment.yaml" at <"app.appTemplate">: can't handle "app.appTemplate" for arg of type map[string]interface {} Last Helm logs:
```
