### ISSUE TITLE
helm3 --value flag not adding values for a dictionary key together 

### ISSUE THREAD

**Issue by shomeprasanjit** [helm/helm#10494]
How to inject or add dictionary values for a specific key present in values.yaml by using an override file. 

config.yaml file

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  config.yaml: |
    validators:
    {{- range .Values.validators -}}
      {{- $validator := deepCopy . -}}
      {{- if eq $validator.type "notaryv1" -}}
        {{- $_ := unset $validator "auth" -}}
      {{- else if eq $validator.type "notaryv2" -}}
      {{- else if eq $validator.type "cosign" -}}
      {{- end }}
    - {{- $validator | toYaml | trim | nindent 6 -}}
    {{- end }}
    policy:
    {{- range $k,$v := .Values.policy }}
    - {{- $v | toYaml | trim | nindent 6 -}}
    {{- end }}
```   

values.yaml file
```
validators:
# static validator that allows each image
- name: allow
  type: static
  approve: true
# static validator that denies each image
- name: deny
  type: static
  approve: false
- name: cloudops
  type: cosign  # or other supported validator (e.g. "cosign")
  trust_roots:
  - name: cloudops
    key: |
      -----BEGIN PUBLIC KEY-----
     ABCDXYZ
      -----END PUBLIC KEY-----
  auth:  # credentials in case the trust data requires authentication
    secret_name: ecr-docker-creds-cloudops
  #  # or (only for notaryv1 validator)
  #  username: myuser
  #  password: mypass
- name: product
  type: cosign  # or other supported validator (e.g. "cosign")
  trust_roots:
  # # the `default` key is used if no key is specified in image policy
  - name: product
    key: |
      -----BEGIN PUBLIC KEY-----
      ABCD
      -----END PUBLIC KEY-----
  auth:  # credentials in case the trust data requires authentication
    secret_name: ecr-docker-creds-product
- name: dockerhub-basics
  type: notaryv1
  host: notary.docker.io
  trust_roots:
  # public key securesystemsengineering repo including Connaisseur images
  # !this key is critical for Connaisseur!
  - name: securesystemsengineering-official
    key: |
      -----BEGIN PUBLIC KEY-----
      XXXXXXXXXXXXX
      -----END PUBLIC KEY-----
 ```
Override.yaml file looks like

```
validators:
- name: cloudops
  type: cosign  # or other supported validator (e.g. "cosign")
  trust_roots:
  - name: cloudops
    key: |
      -----BEGIN PUBLIC KEY-----
      CLOUDOPSHELL
      -----END PUBLIC KEY-----
  auth:  # credentials in case the trust data requires authentication
    secret_name: ecr-docker-creds-cloudops
  #  # or (only for notaryv1 validator)
  #  username: myuser
  #  password: mypass
- name: product
  type: cosign  # or other supported validator (e.g. "cosign")
  trust_roots:
  # # the `default` key is used if no key is specified in image policy
  - name: product
    key: |
      -----BEGIN PUBLIC KEY-----
      CLOUDOPSHELLOQ
      -----END PUBLIC KEY-----
  auth:  # credentials in case the trust data requires authentication
    secret_name: ecr-docker-creds-product
```
Output of `helm template --dry-run connaisseur -n connaisseur ./connaisseur-1.0.0.tgz -f override.yaml`:

```
# Source: connaisseur/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: connaisseur-config
  namespace: connaisseur
  labels:
    app.kubernetes.io/name: connaisseur
    helm.sh/chart: connaisseur-1.0.0
    app.kubernetes.io/instance: connaisseur
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    validators:
    -
      auth:
        secret_name: ecr-docker-creds-cloudops
      name: cloudops
      trust_roots:
      - key: |
          -----BEGIN PUBLIC KEY-----
          CLOUDOPSHELL
          -----END PUBLIC KEY-----
        name: cloudops
      type: cosign
    -
      auth:
        secret_name: ecr-docker-creds-product
      name: product
      trust_roots:
      - key: |
          -----BEGIN PUBLIC KEY-----
          CLOUDOPSHELLOQ
          -----END PUBLIC KEY-----
        name: product
      type: cosign
```

Expected output content

```
---
# Source: connaisseur/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: connaisseur-config
  namespace: connaisseur
  labels:
    app.kubernetes.io/name: connaisseur
    helm.sh/chart: connaisseur-1.0.0
    app.kubernetes.io/instance: connaisseur
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    validators:
    -
      approve: true
      name: allow
      type: static
    -
      approve: false
      name: deny
      type: static
    -
      auth:
        secret_name: ecr-docker-creds-cloudops
      name: cloudops
      trust_roots:
      - key: |
          -----BEGIN PUBLIC KEY-----
          CLOUDOPSHELL
          -----END PUBLIC KEY-----
        name: cloudops
      type: cosign
    -
      auth:
        secret_name: ecr-docker-creds-product
      name: product
      trust_roots:
      - key: |
          -----BEGIN PUBLIC KEY-----
          CLOUDOPSHELLOQ
          -----END PUBLIC KEY-----
        name: product
      type: cosign
    -
      host: notary.docker.io
      name: dockerhub-basics
      trust_roots:
      - key: |
          -----BEGIN PUBLIC KEY-----
         XXXXXXXXXXXXX
          -----END PUBLIC KEY-----
        name: securesystemsengineering-official
      type: notaryv1
 ```
