### ISSUE TITLE
--wait-for-jobs does not fails if job failed

### ISSUE THREAD

**Issue by egorchepiga** [helm/helm#10500]
Output of helm version:
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

Output of kubectl version:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

I have this template:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-{{ .Values.hash }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }} 
spec:
  template:
    spec:
      containers:
      - name: test
        image: test:{{ .Values.hash }}
      restartPolicy:  Never
      imagePullSecrets:
        - name: gitlab-pull-secret
  backoffLimit: 1
```

I installs it with this command:
helm install CHART --wait-for-jobs --wait --timeout 10m

Sometimes job failed (because of tests, yeap :) ), does not restart (because of reaching backoffLimit) and then helm just... waits.
I think that helm should not wait if job failed without any other restarts

#9285 
#9950
