### ISSUE TITLE
Should `required` be evaluated in a `{{ if false }}` block?

### ISSUE THREAD

**Issue by kuisathaverat** [helm/helm#10512]
I was trying to use required to validate some Helm values are defined if others are, so I put a `required` block inside and `if` block, the expected behavior is that the `required` block is only evaluated when the `if` condition is true, but seems like it is always evaluated, Is that correct? 

This simple template causes the error if `token`  is not defined.

secret.yaml
```
apiVersion: v1
data:
  name: foo
{{- if false }}
  token: {{ required 'Should it fail?' .Values.token }}
{{- end }}
kind: Secret
metadata:
  name: secretName
  namespace: default
```

Output of `helm version`: 
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.14-gke.1900", GitCommit:"abc4e63ae76afef74b341d2dba1892471781604f", GitTreeState:"clean", BuildDate:"2021-09-07T09:21:04Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
does not matter

**Comment by bacongobbler** [comment]
This would be a good question to ask the Go authors why functions within `if` blocks are evaluated ahead of time.

**Comment by mattfarina** [comment]
@kuisathaverat This is a good question. It's the Go template engine in the standard library that handles this. This sort of logic is part of that package and isn't something Helm can change.

**Comment by jlemaes** [comment]
This should work fine if you use double quotes for your string:
`token: {{ required "Should it fail?" .Values.token }}`

**Comment by kuisathaverat** [comment]
nice, the `"` replacement makes the trick, the following block is only evaluated when the condition is true.

```
apiVersion: v1
data:
  name: foo
{{- if false }}
  token: {{ required "Should it fail?" .Values.token }}
{{- end }}
kind: Secret
metadata:
  name: secretName
  namespace: default

```
