### ISSUE TITLE
helm dependencies cannot reference external values.yaml

### ISSUE THREAD

**Issue by chenyanshan** [helm/helm#10530]
When I use  helm dependencies:
```
├─helm-repo
│  └─java-ms
│      └─Chart.yaml
└─read-table
      └─values.yaml
```

helm-repo/java-ms/Chart.yaml
```
---
apiVersion: v2
name: java-ms
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: java-ms
  version: 0.0.2
  repository: https://*****/helm-repo
```

helm-repo/vihome-read-table/values.yaml
```
project:
  name: "read-table"
  group: "hm"
  env: "test"
  restartPolicy: Always
```

```
helm-repo\java-ms> helm template .  --namespace hm-test ./ --values=../../read-table/values.yaml --debug

helm.exe install read-table -f ../../read-table\values.yaml --dry-run ./
```

"../../read-table/values.yaml" Don't take effect
The generated result is the default value

If the default values.yaml in java-ms chart are deleted
get the error：

```
Error: template: read-table/charts/java-ms/templates/deployment.yaml:4:18: executing "read-table/charts/java-ms/templates/deployment.yaml" at <.Values.project.name>: nil pointer evaluating interface {}.name
```

The specified values.yaml does not take effect at all

Output of `helm version`:
version.BuildInfo{Version:"v3.5+unreleased", GitCommit:"b30f61d76de3805a839a95dc0f8ef8d8e208b09f", GitTreeState:"clean", GoVersion:"go1.15.8"}

**Comment by chenyanshan** [comment]
```
java-ms:
  project:
    name: "read-table"
    group: "hm"
    env: "test"
    restartPolicy: Always
```
need values add java-ms subchart name
