### ISSUE TITLE
Deployment error when specifying annotations

### ISSUE THREAD

**Issue by rliskunov** [helm/helm#10606]
Output of `helm version`: v3.5.1

Output of `kubectl version`: v1.22.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): don't use a cloud provider

I have a service for which I am going to specify prometheus annotations. I need it to get metrics from java applications. However, I get an error when I update it:
Error: UPGRADE FAILED: cannot patch "test-worker" with kind Service: Service "test-worker" is invalid: metadata.labels: Invalid value: "/actuator/prometheus": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

The most amazing thing is that the annotations then appear at the service and at the pod. Could you please tell me what could be the problem? In general, is this a problem?

values.yml
```
---
annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "7050"
  prometheus.io/path: "/actuator/prometheus"
```

service.yml
```
---
services:
  - name: test-worker
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "7050"
      prometheus.io/path: "/actuator/prometheus"
    type: NodePort
    ports:
      - name: test-worker
        port: 3010
        targetPort: 3010
        nodePort: 10001
```

**Comment by bacongobbler** [comment]
The error is originating from Kubernetes, informing you that a certain label in your existing Service is invalid. You may be able to force a fix by using the `--force` or the `--disable-openapi-validation` flags. Alternatively you can try to edit the service manually using kubectl.

**Comment by hibohra1398** [comment]
facing same issue even after passing port as string i see below issue
Error:
 json: cannot unmarshal number into Go struct field ObjectMeta.spec.template.metadata.annotations of type string


Annotations:
````
podAnnotations:
  prometheus.io/port: "8080"
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
````
