### ISSUE TITLE
cannot take complex structure from array in values file

### ISSUE THREAD

**Issue by ffoysal** [helm/helm#10604]
values.yaml
```
---
volumesAndMounts:
  volumes:
    - name: mount-0
      hostPath:
        path: /tmp
    - name: mount-1
      hostPath:
        path: /tmp
  volumesMounts:
    - mountPath: /a
      name: mount-0
    - mountPath: /b
      name: mount-1
```
template.yaml
```
---
  volumes:
    {{- range .Values.volumesAndMounts.volumes }}
    - {{ . | toYaml | nindent 6 -}}
    {{- end }}
```
output
```
---
  volumes:
    - 
      
    - 
      
```
dont know why output is empty
