### ISSUE TITLE
if/else statement checking if value from for loop exist. 

### ISSUE THREAD

**Issue by hunkeelin** [helm/helm#10615]
Traditionally here's what I do, and it works just fine
```
           resources:
             {{- if $.Values.resources -}} # check if value exist
             {{- toYaml $.Values.odyssey.resources | nindent 12}}
             {{- else -}}
             // some custom limits and requests
             {{- end -}}
```

Now my `value.yaml` files looks like this
```
cluster:
  databases:
    db-1:
      resources:
        limits:
          memory: "900Mi"
          cpu: "900m"
        requests:
          memory: "900Mi"
          cpu: "900m"
    db-2:
      resources:
        limits:
          memory: "500Mi"
          cpu: "1500m"
        requests:
          memory: "500Mi"
          cpu: "1500m
```

Now I want to do something like this
```
{{ range $key, $value := .Values.cluster.databases }}
// ...

           resources:
             {{- if get $value "resources" -}} # 
             {{- toYaml get $value "resources" | nindent 12 }} # 
             {{- else -}}
             // some custom limits and requests
             {{- end -}}
{{ end }}
```

The above gives me `at <$value>: can't give argument to non-function $value`. What's the correct syntax to implement my logic?
