### ISSUE TITLE
How can we override dependencies "version" in helm chart Chart.yaml file?

### ISSUE THREAD

**Issue by NiniiGit** [helm/helm#10639]
I am wondering and apparently have not yet found anywhere if there is a way via which I can specifically override the value of "version" key's value from the dependencies chart in Helm

```
# Chart.yaml
dependencies:
- name: bitnami/postgresql
  version: **"8.10.5"**
  repository: "https://charts.bitnami.com/bitnami"
```
I tried something like below:
```
# Chart.yaml
dependencies:
- name: bitnami/postgresql
  version: "{{.Values.postgresql.version}}"
  repository: "https://charts.bitnami.com/bitnami"
```
and
```
# Values.yaml
postgreSQL:
  version: "8.10.5"
```
But I am getting below error:
```
Error: cannot load Chart.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.postgresql.version":interface {}(nil)}
```
If this is currently not possible then can someone advise how do you update the "version" of dependencies in Charts.yaml whenever new version is available of them?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: net/http: TLS handshake timeout
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  kind cluster
