### ISSUE TITLE
Any possible workarounds for OCI dependency version matching?

### ISSUE THREAD

**Issue by P15233971** [helm/helm#10645]
I was hoping to get some advice on workarounds for version matching in OCI chart dependencies. My understanding is that this feature is not yet available but I'm struggling to think of an alternative method that doesn't involve tons of scripts.

Our use case:

We have individual service charts that are pushed to our OCI repo and we also have umbrella charts with their own pipelines that pull groups of service charts. 

We'd like to be able to push hot-fixes on service pipelines by incrementing the patch version (e.g. a hotfix for version `1.0.0` would be `1.0.1`), but in order for our umbrella chart to not redeploy an old version we could have the dependency set to `~ 1.0.0` or equivalent.

Since we can't use this kind of version matching for OCI charts, are they any other approaches available in helm that supports OCI?

Current config:

```
dependencies:
  - name: example
    version: 1.0.0
    repository: "oci://repo
```

Desired config (or equivalent end result):

```
dependencies:
  - name: example
    version: ~1.0.0
    repository: "oci://repo
```

Our environment:

Google artifact registry + Helm v3.7.2

Thanks
