### ISSUE TITLE
FR: Reference values of annotations in chart.yaml to a property included in the values.yaml file

### ISSUE THREAD

**Issue by volker-raschek** [helm/helm#10653]
Hello people,
I want to deploy more and more applications via helm. This requires a lot of meta information for the complete product ecosystem which is generated generically. Static information are stored in the `values.yaml` file. Information of the product ecosystem is stored in `system.yaml` files. The application will be deployed by referencing booth yaml files. The information will be merged together: `helm install my-app repo/my-app --values values.yaml --values system.yaml`.

The problem is, that relevant meta information about the product ecosystem does not belong to a deployment, daemon set or other resource. The information simply belongs to the release of the chart. 

Now I tried to reference the value of an annotation to the corresponding value in `system.yaml`. Unfortunately helm does not interpret the template format at this point. 

```yaml
apiVersion: v2
name: my-application
description: My great application
type: application
version: 0.1.0
appVersion: 1.5.7

annotations:
  app.company.local/service-version: "{{ .Values.service.version }}"
```

I needed this function to be able to store meta information generically. Are there already plans for this? Otherwise, this would be a very useful feature.

**Comment by bacongobbler** [comment]
Hi @volker-raschek. We've heard this idea before in different forms, however I haven't seen anyone interested in picking up this work. For example https://github.com/helm/helm/issues/10562, https://github.com/helm/helm/issues/4782, https://github.com/helm/helm/issues/4275, and https://github.com/helm/helm/issues/10022.

The first step to propose a new feature would be to write a HIP.

We intend HIPs to be the primary mechanisms for proposing major new features, for collecting community input on an issue, and for documenting the design decisions that have gone into the project. The proposal author is responsible for building consensus within the community and documenting dissenting opinions.

See [Proposing an Idea](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea) for more information on this process.

**Comment by o-shevchenko** [comment]
We are interested in the same feature.
Our use case is getting annotations as proposed in https://github.com/helm/community/blob/main/hips/hip-0015.md but it doesn't support dynamic version setting:
```
annotations:
  example.com/images: |-
    - name: image-name
      image: image-name: {{ .Chart.AppVersion }}
 ```
 We would like to use templating or convenient override like:
 ```
 helm package ${CHART_PATH} --app-version ${VERSION}
