### ISSUE TITLE
helm template: option to override certain templates from rendering.

### ISSUE THREAD

**Issue by jala-dx** [helm/helm#10690]
Output of `helm version`: v3.4.2

Is it possible to provide an override flag not to render builtin objects for ex., **{{ .Release.Revision }}**

Let us say i have this configmap in the chart, it always gets rendered to 1 because it gets rendered by the `template engine`. This value has to be dynamically populated based on the Revision number present in the cluster.  I understand that  that `helm install` or `helm upgrade` will populate the correct value. But our usecase is such that, we render first using `helm template` and then do `helm install/upgrade` 

Please let me know if there is any workaround that can override certain templates, specifically **{{ .Release.Revision }}**  in the manifests when running `helm template`

```
$ helm template jala-chart ./jala-chart -n test --dry-run --debug | grep revision
  revision: '1'
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app.kubernetes.io/instance: security-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: example-chart
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: example-chart-0.1.0
  labels:
    app: example
    component: nginx
data:
  revision: '{{ .Release.Revision }}'

```

**Comment by MarcoStuurman** [comment]
You could probably use the [default function](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-default-function) to override the revision whenever set.

So it looks like:

```
marco@DESKTOP:~/testme$ helm template test .  -n test --dry-run --debug --set revisionOverride=9 | grep revision
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: /home/marco/testme

        revision: '9'
marco@DESKTOP:~/testme$ helm template test .  -n test --dry-run --debug | grep revision
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: /home/marco/testme

        revision: '1'
```

The ConfigMap will look like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app.kubernetes.io/instance: security-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: example-chart
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: example-chart-0.1.0
  labels:
    app: example
    component: nginx
data:
  revision: '{{ .Values.revisionOverride | default .Release.Revision }}'
```
