### ISSUE TITLE
helm linter not detecting %!s(<nil>) values

### ISSUE THREAD

**Issue by nitram509** [helm/helm#10706]
Hi, using the latest helm version, I stumbled upon an issue, what helm lint could not detect

### what I did 

* created a blank folder
* ```helm create uber-chart```
* ```cd charts```
* ```helm creat sub-chart```
* manually stripped off many files, in order to simplify this bug-report
* created a template helper in the uber-chart, called "some-template"
* used the "some-template" in the sub-chart/templates/service.yaml
* run ```helm template .``` in the uber-chart folder
* got this result ```via_template: "%!s(<nil>)-%!s(<nil>)"```
* run ```helm lint.``` in the uber-chart folder
* got NO errors 
service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: "name"
  labels:
    via_template: "{{ template "some-template"  }}"
    via_template_with_dot: "{{ template "some-template" . }}"
    via_include: "{{/* include "some-template"      <-- missing dot will result in error. */}}"
    via_include_with_dot: "{{ include "some-template" . }}"
spec:
  selector: []
```

```helm template .```

```text
apiVersion: v1
metadata:
  name: "name"
  labels:
    via_template: "%!s(<nil>)-%!s(<nil>)"
    via_template_with_dot: "sub-chart-0.1.0"
    via_include: ""
    via_include_with_dot: "sub-chart-0.1.0"
spec:
  selector: []
```

### what I expect

using a template language, where some values might be null/undefined should be detected by the linter and result at least in a warning. 

### technical background

I did follow Helm's best practices and added helm lint in our deployment pipeline.
Since I'm not so familiar with Helm, I forgot to add this little dot (see attached source) and got these ```<nil>```.
Unfortunately, they landed in Kubernetes, via Helm Upgrade and it took me hours to figure out what was wrong.

Side note, Helm's documentation does not very well describe the meaning of the dot.
I still do not fully understand, why it's needed and believe I'm not the only one out there.
I would rather prefer a linter telling me some potential weaknesses in my template to spot&fix my issues earlier.
Clearly, this ```<nil>``` should not be rendered.

### additional thoughts

When I use the include function instead of template, the dot is required,
and the linter and template commands from Helm will complain immediately.
the template function in contrast will print these ```<nil>```.
In terms of consistency ... the linter should complain in both cases, no? 

### Context

Full Sources
[helm-linter-issue.zip](https://github.com/helm/helm/files/8144856/helm-linter-issue.zip)

Output of `helm version`:
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
n/a (local shell only)
