### ISSUE TITLE
Helm lint and upgrade commands do not enforce Chart version to be in SemVer compatible format

### ISSUE THREAD

**Issue by thecooldrop** [helm/helm#10700]
Output of `helm version`:
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

Output of `kubectl version`:
Not relevant / Not used in this bug

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS, but is locally reproducible.

Expected behavior:

If the `version` field in Chart.yaml is not valid SemVer, then Helm commands needing this value should fail with proper warning. I would expect that `helm lint` would inform me of incomatible version naming.

Actual behavior:

If a Chart.yaml is created with following content:

```yaml
apiVersion: v2
name: test
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 20220224-093343-68fa7b32

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
```

Then the output of `helm lint` is as follows:

>==> Linting .
>[INFO] Chart.yaml: icon is recommended
>
>1 chart(s) linted, 0 chart(s) failed

As you can see there is no error. Further I have installed an application with non-SemVer version via `helm upgrade` command and it worked without issue.

I consider this a bug, since the documentation [here](https://helm.sh/docs/topics/charts/#charts-and-versioning) says following : 

>More complex SemVer 2 names are also supported, such as version: 1.2.3-alpha.1+ef365. But non-SemVer names are explicitly disallowed by the system.
