### ISSUE TITLE
Autoscaling apiVersion

### ISSUE THREAD

**Issue by d3p4rt** [helm/helm#10710]
Hello everybody,
i found this problem with my chart.

I'm tring to update apiversion of HPA from _autoscaling/v2beta1_ to _autoscaling/v2beta2_.

After deploying i don't see new version of api:
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/
[...]
  managedFields:
  - apiVersion: autoscaling/v2beta2
    fieldsType: FieldsV1
    fieldsV1:
```

Another example is, on hpa.yaml template file:
```
 metrics:
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization 
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}

```

On kubernetes:
```
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50

```

If i execute command helm template <my-chart name> the result is:

```
---
# Source: onetime-token/templates/onetime-hpa.yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
```

From helm template i see correctly new version of apiversion.

There are others informations:
Helm version: v3.5.0
kubectl version: v1.19.4
Cloud Provider: AWS
EKS Version: v1.19.15

It's like that helm interprets it correctly but then on the cluster it does not install it correctly.
I don't know if it's a problem of helm or EKS.

Can you helm ( 😄 ) me?
