### ISSUE TITLE
Creating a CronJob with PVC and a WaitForFirstConsumer SC times out

### ISSUE THREAD

**Issue by threesquared** [helm/helm#10733]
Output of `helm version`: `version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `EKS`

When specifying a PVC on a CronJob using a StorageClass that uses the WaitForFirstConsumer [volume binding mode](https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode) as is recommended when using a topology-constrained storage backend like EBS. Helm upgrade will time out as the PVC Status is "Pending"

```
|   Type    Reason                Age                   From                         Message                                                                                                                   │
│   ----    ------                ----                  ----                         -------                                                                                                                   │
│   Normal  WaitForFirstConsumer  4m28s (x62 over 19m)  persistentvolume-controller  waiting for first consumer to be created before binding
```

However this is the expected success condition as the volume should not be bound until the cronjob runs.

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name:cronjob
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          name: cronjob
        spec:
          containers:
          - command:
            - /app/scripts/test.sh
            volumeMounts:
            - mountPath: /tmp/test
              name: backup
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: pvc
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
parameters:
  encrypted: "true"
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1000Gi
  volumeMode: Filesystem
status:
  phase: Pending
```

This issue also relates to the following closed issues:

https://github.com/helm/helm/issues/10196
https://github.com/helm/helm/issues/6350
https://github.com/helm/helm/issues/8715

**Comment by bacongobbler** [comment]
Hi @threesquared. We'd appreciate a patch to fix this behaviour.

I noticed you were testing against an older version of Helm. Have you tried Helm 3.8 to see if this has been patched in future releases?

**Comment by bamsammich** [comment]
@bacongobbler could we get this issue reopened? This is still an issue.

Use case: Building chart testing using kind which has a standard SC with WaitForFirstConsumer. Chart includes a backup cronjob that backups up to a PVC, but the cronjob doesn't run during chart installation, thus hanging the install waiting for the PVC.

**Comment by tculp** [comment]
@bacongobbler Just ran into this issue too, the official GitLab helm chart can be set to deploy a backup cronjob with persistence. I would also like this issue reopened

**Comment by stephan2012** [comment]
This issue has the help wanted label assigned. What does it need to get the fix merged?

**Comment by stephan2012** [comment]
By the way, a _workaround_ (hesitating to call it so …) is to create a `Job` from the `CronJob`, which forces volume binding. At least it takes you past the Helm deployment.

```console
kubectl create job foo -n mynamespace --from=cronjob/my-cronjob-name
```

**Comment by huyle10** [comment]
My workaround to successfully re-deploy helm chart every time is to add a init pod with randomly generated name. The init pod will attach to the pvc to force volume creation:
```
apiVersion: v1
kind: Pod
metadata:
  name: init-pod-{{ randAlphaNum 8 | lower }}
spec:
  volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: pvc
  containers:
    - command: ["/bin/echo"]
      args: ["hello world"]
      volumeMounts:
        - mountPath: /tmp/test
           name: backup
```
