### ISSUE TITLE
Removal of duplicate array entry removes completely from Kubernetes

### ISSUE THREAD

**Issue by cablespaghetti** [helm/helm#10741]
Output of `helm version`: `version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS EKS 1.21

We had a Helm chart with a duplicate value in the `env` array, this was de-duplicated automatically by Kubernetes/YAML and so when this was noticed and the duplicate was removed, the only entry for this value was removed from Kubernetes.

**To reproduce**
1. Make a helm chart with a deployment and env configuration like this
```
        env:
        - name: "APPLICATION_STAGE"
          value: {{ .Values.stage | quote }}
        - name: "COMMIT_ID"
          value: {{ .Values.tag | quote }}
        - name: "DATABASE_URL"
          valueFrom:
            secretKeyRef:
              name: db-{{ .Values.app_name }}
              key: connection
        - name: "SENTRY_DSN"
          value: {{ .Values.sentry_dsn | quote }}
        - name: "DD_AGENT_HOST"
          value: "datadog-apm.datadog.svc.cluster.local"
        - name: "REDIS_URI"
          value: {{ .Values.redis_uri | quote }}
        - name: "DATABASE_URL"
          valueFrom:
            secretKeyRef:
              name: db-{{ .Values.app_name }}
              key: connection
```

2. Deploy this Helm chart and observe that in Kubernetes there is actually only a single `DATABASE_URL` entry in the Deployment configuration.
3. Remove the extra `DATABASE_URL` (in our case the second one)
4. Run a `helm upgrade` and see that there is no `DATABASE_URL` at all in the deployment.

Admittedly this is not something which should ever happen, but we all make mistakes and having to manually edit deployments managed by helm isn't very desirable.

**Comment by bacongobbler** [comment]
Hmm... I'd be curious if this may be due to an underlying but in kubectl's patch logic. Were you able to determine the root cause of this?

**Comment by cablespaghetti** [comment]
No we just worked around it. However I've been playing around this evening to try and track it down.

Deploying this YAML with `kubectl apply` results in a deployment with two COMMIT_ID env vars in Kubernetes (and a warning on apply). Removing the duplicate and applying again removes the duplicate on Kubernetes.

Put the same YAML in a Helm chart and there is only ever a single COMMIT_ID in Kubernetes. And removing the duplicate and running `helm upgrade` removes that single COMMIT_ID env var.

Helm template shows two COMMIT_ID vars so it's something between template and apply within helm doing the de-duplication and ultimately causing the problem.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: patchtest
  name: patchtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patchtest
  template:
    metadata:
      labels:
        app: patchtest
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: "APPLICATION_STAGE"
          value: "dev"
        - name: "COMMIT_ID"
          value: "1234"
        - name: "DD_AGENT_HOST"
          value: "datadog-apm.datadog.svc.cluster.local"
        - name: "COMMIT_ID"
          value: "1234"
```
