### ISSUE TITLE
out of memory on helm lint execution with in incorrect template

### ISSUE THREAD

**Issue by Mo1hen** [helm/helm#10759]
Hello team!

When I run 'helm lint' for incorrect template (example configmap resource), i get out of memory (available RAM - 32Gb)
Expected behavior print error and exit. Actual one we crushed with oom. 

example incorrect resource (extra space between { { ):
```
{ { if eq .Values.TEST_PARAM "ENABLE" } }
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.SERVICE_NAME }}-configmap
data:
  myvalue: "Hello World"
{ { end } }
```
values.yaml:
```
TEST_PARAM: "ENABLE"
SERVICE_NAME: "test-service"
```

I check it behavior on 3.6.1 and 3.8.1 helm version.

Please fix it. Thank you!
