### ISSUE TITLE
Question: coredns rewrite

### ISSUE THREAD

**Issue by amccool** [helm/helm#10778]
I need to do a DNS rewrite for an ingress to service so that the pods inside can hairpin correctly.    However this appears to only work by modifying the `kube-system` namespace.  In addition it only appears to work by changing the .:53 zone. 

How can I get this rewrite addon into my helm chart and working under a user namespace?

```kubectl edit configmap coredns -n kube-system```

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health {
           lameduck 5s
        }
        ready
->        rewrite name XXXws.k8.local XXXws-service.default.svc.cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-22T18:54:47Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "11086518"
  uid: 0f5b125c-4405-4343-8cb7-d8c59174d9aa
```

I tried things like

```
apiVersion: v1
data:
  Corefile: |
    k8.local.:53 {
        rewrite name XXXws.k8.local XXXws-service.default.svc.cluster.local
    }
```

but it has no effect even after coredns restarts and waiting for progagation.

**Comment by amccool** [comment]
I am reading addition posts that coredns/corefile must be under the `kube-system` namespace.   Be that as it may, can I somehow put this change into a helm chart?

**Comment by Saran33** [comment]
@amccool yes it's possible to put it in a Helm chart. For example, you could modify the ConfigMap and update the coredns deployment in a chart hook job:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: coredns-config-patch
  namespace: kube-system
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: patch-coredns
      containers:
        - name: patch-coredns
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              COREFILE_CONTENT=".:53 {
                  errors
                  health {
                      lameduck 5s
                  }
                  ready
                  {{- range .Values.coredns.rewrites }}
                  rewrite name {{ .name }} {{ .target }}
                  {{- end }}
                  kubernetes cluster.local in-addr.arpa ip6.arpa {
                      pods insecure
                      fallthrough in-addr.arpa ip6.arpa
                      ttl 30
                  }
                  prometheus :9153
                  forward . /etc/resolv.conf {
                      max_concurrent 1000
                  }
                  cache 30
                  loop
                  reload
                  loadbalance
              }"
              FORMATTED_COREFILE_CONTENT=$(echo "$COREFILE_CONTENT" | sed ':a;N;$!ba;s/\n/\\n/g')
              kubectl patch cm coredns -n kube-system --type=merge -p "{\"data\":{\"Corefile\":\"$FORMATTED_COREFILE_CONTENT\"}}"
              kubectl rollout restart -n kube-system deployment/coredns

              # Delete the service account, role, and rolebinding after the main task is done
              kubectl delete rolebinding patch-coredns -n kube-system
              kubectl delete role patch-coredns -n kube-system
              kubectl delete sa patch-coredns -n kube-system
      restartPolicy: Never
```
The job will need a service account with permissions to retrieve and update ConfigMaps in the `kube-system` namespace. If you want  to delete the service account as a security precaution after the job has completed, then the service account will also need a role for deleting those resources.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-coredns
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-coredns
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delete-rbac
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-coredns
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-coredns
subjects:
  - kind: ServiceAccount
    name: patch-coredns
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delete-rbac
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: delete-rbac
subjects:
- kind: ServiceAccount
  name: patch-coredns
  namespace: kube-system
```
This assumes you have a `values.yaml` file with something like this to add as many rewrites as you like (using the values in your example):
```yaml
coredns:
  rewrites:
    - name: XXXws.k8.local
      target: XXXws-service.default.svc.cluster.local
```
