### ISSUE TITLE
Imported values not usable as conditions

### ISSUE THREAD

**Issue by albgp22** [helm/helm#10781]
I have the following chart structure:
- **main chart**: a chart having the following two dependencies
- **dependency chart**: a functional chart
- **values chart**: a chart having no objects, used to import values to the main chart via import-values.

Both subcharts are added as a dependency for the main chart, and are activated with a condition value. The dependency order is the following

```
dependencies:
- repository: file://../chart-vals/
  condition: profiles.chartvals.enabled
  version: 0.1.0
  name: chart-vals
  import-values:
  - custom-vals
- repository: file://../chart-dep/
  condition: chartdep.enabled
  version: 0.1.0
  name: chart-dep
```

The values chart has, as exported value, the condition for the dependency chart to be enabled, however, helm omits this activation value and it doesn't enable the dependency chart, as it'd be expected.

A laboratory chart environment has been uploaded here https://github.com/albgp22/helm-conditions-issue. It can be easily reproduced by running
```
helm dep up .
helm template . --set profiles.chartvals.enabled=true
helm template . --set chartdep.enabled=true
```
inside the main chart.

Output of `helm version`: v3.7.2

Output of `kubectl version`: v1.23.1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Bare metal
