### ISSUE TITLE
Helm update of a new chart dependency will not install its CRD's

### ISSUE THREAD

**Issue by mitchellhuang** [helm/helm#10784]
We have an internal Helm chart `cluster-core` that we use to install various core cluster components. We use Helm's dependency feature to tightly couple these core charts into a single `cluster-core` chart that is then rolled out to our clusters.

It works great, except we have run into an issue. If we add a new dependency, e.g. `aws-load-balancer-controller` and run a `helm upgrade --install` with the `cluster-core` chart already installed, it will error due to missing CRD's. We found this is because Helm [will not install CRD's](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) during a helm upgrade of an existing chart. But in this case, helm is only checking if the parent chart `cluster-core` is installed - not if it's the first time installing the dependency itself.

Is what we have discovered expected behavior or a bug? Can we add new logic into `helm upgrade` to detect if a dependency is being added to a chart for the first time install the dependency's CRD's?

```
dependencies:
- name: aws-auth
  version: "0.4.0"
  repository: "oci://[redacted].dkr.ecr.us-east-1.amazonaws.com/charts/aws-auth"
- name: aws-load-balancer-controller
  version: "1.4.0"
  repository: "oci://[redacted].dkr.ecr.us-east-1.amazonaws.com/charts/aws-load-balancer-controller"
```

```
$ helm upgrade --install -f values.yaml <chart>
unable to recognize "": no matches for kind "IngressClassParams" in version "elbv2.k8s.aws/v1beta1"
```

Output of `helm version`: v3.8.1

Output of `kubectl version`: v1.22.5

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS
