### ISSUE TITLE
Value deletion from external values file does not work as expected/documented

### ISSUE THREAD

**Issue by EHP4321** [helm/helm#10795]
Output of `helm version`:
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

Value deletion from external values file does not work as expected/documented here:
https://helm.sh/docs/chart_template_guide/values_files/

How to reproduce:
Create a chart that includes this haproxy chart:
Content of my Chart.yaml:
```
name: haproxy
apiVersion: v2
version: 1.12.0
description: Haproxy running in kubernetes
keywords:
  - haproxy
dependencies:
  - name: haproxy
    version: 1.12.0
    repository: https://haproxytech.github.io/helm-charts
```

This is my file structure after `helm dep update`:
```
my-haproxy-chart/
  Chart.lock
  Chart.yaml
  charts/
    haproxy-1.12.0.tgz
```
Running `helm template .` in my-haproxy-chart/ shows us the default ports 80, 443 and 1024.

I Want to remove those and replace them with my own. A value file like this does the trick:
my-haproxy-chart/values.yaml content:
```
haproxy:
  containerPorts:
    test: 1234
    http: null
    https: null
    stat: null
```
Now `helm template . --values values.yaml` shows only the "test" port 1234 which is what I want.

But I want to specify it in an external values file.
Move the values file to another location `mv values.yaml ../my-external-values.yaml`
and for good measure `touch values.yaml`
Now Id expect `helm template . --values values.yaml --values ../my-external-values.yaml`
to return the same as before, i.e only the test ports. But it doesn't. It returns both the default and the test ports, which means the values form my-external-values.yaml are being applied, except the ports set to null.
This cant be the intended behavior. It looks like a bug in helm to me.
