### ISSUE TITLE
helm post-upgrade hook executed before configmap mount changes on disk

### ISSUE THREAD

**Issue by jcourtat** [helm/helm#10817]
Output of `helm version`:
version.BuildInfo{Version:"v3.7.1+7.el8", GitCommit:"8f33223fe17957f11ba7a88b016bc860f034c4e6", GitTreeState:"clean", GoVersion:"go1.16.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v0.21.0-beta.1", GitCommit:"96e95cef877ba04872b88e4e2597eabb0174d182", GitTreeState:"clean", BuildDate:"2021-11-15T14:54:31Z", GoVersion:"go1.16
.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+ffbb954", GitCommit:"3a0f2c90b43e6cffd07f57b5b78dd9f083e47ee2", GitTreeState:"clean", BuildDate:"2021-11-29T05:06:16Z", GoVersion:"go1.1
6.6", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (0.21) and server (1.22) exceeds the supported minor version skew of +/-1

Cloud Provider/Platform (Openshift 4.9.10 on my bare metal servers):

Hello,
i want one of my container to reload its configuration when doing a helm upgrade. Since i'm a beginner with helm and kubernetes, i must admit i don't know if that's the way things should be done.
My program running in container is reading its configuration from a file on disk. I have set up a configmap that is filled by the values file.
I tried to monitor changes on that file on the filesystem to automatically reload configuration, with no luck, since the config map file which is mounted in the container has its content updated but no event advertising that something changed. Anyway, i moved to an alternate solution based on post-upgrade hook and some REST api.
I added a kubernetes Job that is run on post-upgrade hook, which sends a patch request to my container program. On reception of that request, my program reads the configuration file and reload things.
The issue is that when the post-upgrade hook is run, the configmap mounted as volume in my container is not updated yet, and my program reads a configuration file which hasn't been updated. Once the helm upgrade has finished, if i log into the container and dump the configuration file, i can see it has been updated.
Here are some dumps to help understand the test:

```
# Source: alis-r9/templates/reload-kalisto-cfg-job.yaml
 apiVersion: batch/v1
kind: Job
metadata:
  name: reload-kalisto-cfg-alisaf-yellow
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "alisaf-yellow"
    app.kubernetes.io/version: 9.0.0
    helm.sh/chart: "alis-r9-1.0.0"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: reload-kalisto-cfg-alisaf-yellow
      labels:
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/instance: "alisaf-yellow"
        helm.sh/chart: "alis-r9-1.0.0"
    spec:
      restartPolicy: Never
      containers:
      - name: post-upgrade-job
        image: "curlimages/curl:latest"
        command: ["/usr/bin/curl"]
        args: [
            "-X", "PATCH", "http://service-alisaf-yellow-master-aqsacom:8080/config"
        ]
```
This is how i install my chart:
```
[jcourtat@FR-JCT-F9PV25J rhel8] (master)$ helm install --namespace ci -f alisaf-yellow-generic-values.yaml alisaf-yellow alis-r9
NAME: alisaf-yellow
LAST DEPLOYED: Thu Mar 31 10:26:07 2022
NAMESPACE: ci
STATUS: deployed
REVISION: 1
TEST SUITE: None
[jcourtat@FR-JCT-F9PV25J rhel8] (master)$ oc get pods
NAME                                 READY   STATUS      RESTARTS   AGE
alisaf-yellow-master-aqsacom-fzljw   12/12   Running     0          38s
```
i can log into the container and check some parameter into the kalisto.conf file:
```
[jcourtat@FR-JCT-F9PV25J rhel8] (master)$ k8s_alis_shell ci kalisto alisaf-yellow-master-aqsacom
[root@alisaf-yellow-master-aqsacom-bxptd /]# cat /opt/aqsacom/ini/kalisto.conf 
{   
   ...
    "images": {
        "x1p": "image-registry.openshift-image-registry.svc:5000/ci/rhel8_alis-m-debug:0.0.18-5"
    },
   ...
}
```
Now i upgrade my release by modifying a parameter (an image name):
```
[jcourtat@FR-JCT-F9PV25J rhel8] (master)$ helm upgrade alisaf-yellow alis-r9 -f alisaf-yellow-generic-values.yaml --set service.kalisto.x1p.image=image-registry.openshift-image-registry.svc:5000/ci/rhel8_alis-m-debug:0.0.18-7
Release "alisaf-yellow" has been upgraded. Happy Helming!
NAME: alisaf-yellow
LAST DEPLOYED: Thu Mar 31 10:17:15 2022
NAMESPACE: ci
STATUS: deployed
REVISION: 2
TEST SUITE: None
```
If i log into the container and look at logs, i can see the patch request was received and it dumped what was read:
```
[jcourtat@FR-JCT-F9PV25J rhel8] (master)$ k8s_alis_shell ci kalisto alisaf-yellow-master-aqsacom
[root@alisaf-yellow-master-aqsacom-bxptd /]# cat /log/kalisto.0-0.jrn
2022-03-31 08:26:34,610 INFO:===== Started kalisto Kubernetes client ======
2022-03-31 08:26:34,820 INFO:load configuration file /opt/aqsacom/ini/kalisto.conf
2022-03-31 08:26:34,821 INFO:updating running configuration with {..., 'images': {'x1p': 'image-registry.openshift-image-registry.svc:5000/ci/rhel8_alis-m-debug
:0.0.18-5'}, ...}
2022-03-31 08:26:34,823 INFO:xfer_wrapper: connecting localhost
2022-03-31 08:26:42,831 INFO:xfer_wrapper: connected
2022-03-31 08:27:34,794 INFO:rest_interface: received patch command on resource ['/config']
2022-03-31 08:27:34,795 INFO:load configuration file /opt/aqsacom/ini/kalisto.conf
2022-03-31 08:27:34,796 INFO:updating running configuration with {..., 'images': {'x1p': 'image-registry.openshift-image-registry.svc:5000/ci/rhel8_alis-m-debug
:0.0.18-5'}, ...}
```
We can see that the image parameter read is 'mage-registry.openshift-image-registry.svc:5000/ci/rhel8_alis-m-debug
:0.0.18-5, but i upgraded the release with new value 'image-registry.openshift-image-registry.svc:5000/ci/rhel8_alis-m-debug
:0.0.18-7 !!
The configmap  mounted as volume has the good value, meaning helm has successfully updated it:
```
[root@alisaf-yellow-master-aqsacom-bxptd /]# cat /opt/aqsacom/ini/kalisto.conf 
{   
   ...
    "images": {
        "x1p": "image-registry.openshift-image-registry.svc:5000/ci/rhel8_alis-m-debug:0.0.18-7"
    },
   ...
}
```
The post-upgrade job has been successfully run since i don't see any other still created after upgrade:
```
[jcourtat@FR-JCT-F9PV25J rhel8] (master)$ oc get jobs
No resources found in ci namespace.
 ```
Regards,
Julien
