### ISSUE TITLE
Print the Helm Secret

### ISSUE THREAD

**Issue by kferrone** [helm/helm#10815]
Output of `helm version`: version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS EKS

I really want to print the Helm secret to the terminal. Honestly I don't know what to call this secret. IMHO it is the most mysterious aspect of Helm. 

I am talking about the secrets like this which are created after installing a helm chart:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sh.helm.release.v1.apollo-server.v10
  namespace: default
  labels:
    modifiedAt: '1646255650'
    name: apollo-server
    owner: helm
    status: superseded
    version: '10'
data:
  release: >- ...
```

I would love to have a simple flag on the template/dry-runs like so: `helm template foo ./chart --print-secret`

There seems to be absolutely no way to get this, other than actually installing into a live cluster. Is there a reason why? Maybe I missed something and I actually can?
