### ISSUE TITLE
question mark in yaml list bug

### ISSUE THREAD

**Issue by nofearOnline** [helm/helm#10818]
Output of `helm version`: version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): It does not matter

Hi, so apparently a question mark in a YAML list value crashes helm with: error converting YAML to JSON: yaml: line **: did not find expected ',' or ']'

How to replicate:
--- Chart.yaml ---
```
apiVersion: v2
name: helm-question-mark-bug
version: 111.111.102
```
--- values.yaml ---
```
command: ["$?"]
##### In my case it is some other command with a question mark
##### I tried to escape it with \ , \\ and ?? nothing helped
```
--- templates/pod.yaml ---
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bug
  name: bug
spec:
  containers:
  - image: alpine
    name: bug
    command: {{ .Values.command }}
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```
Then try to template with:
helm template question-mark-bug ./

**Comment by yxxhero** [comment]
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bug
  name: bug
spec:
  containers:
  - image: alpine
    name: bug
    command:
{{ toYaml .Values.command | indent 6 }}
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```
