### ISSUE TITLE
Helm range when multiple values.yaml specified

### ISSUE THREAD

**Issue by AliakseiVenski** [helm/helm#10821]
As we know helm will append maps from multiple values files as shown below:
values.yaml 1:
```yaml
app:
  env:
    name1: value1
```

values.yaml 2:
```yaml
app:
  env:
    name2: value2
```

So, when we specify both files during chart installation, we'll have these values provided to the chart
```yaml
app:
  env:
    name1: value1
    name2: value2
```

But if we remove value from values.yaml 2 like this:
values.yaml 2:
```yaml
app:
  env:
    # name2: value2
```
We will get our values erased:
```yaml
app:
  env: null
```
 For me it looks like such arithmetic operation:
1+1 = 2
1+0 = 0

This is weird behavior, isn't it?

Output of `helm version`:
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13", GitCommit:"ddb8dba0a4420ec79de95cebfa4bd7d41aed848a", GitTreeState:"clean", BuildDate:"2021-11-01T16:41:29Z", 

GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS
