### ISSUE TITLE
Default values of grandchild in child are not available in parent chart when pulling charts from repository

### ISSUE THREAD

**Issue by Diliz** [helm/helm#10835]
Output of `helm version`:
`v3.7.1`
Output of `kubectl version`:
```
oc version
Client Version: 4.8.0-202110262219.p0.git.88e7eba.assembly.stream-88e7eba
Server Version: 4.8.14
Kubernetes Version: v1.21.1+a620f50
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`Openshift`

# Problem

Actually, I have:
- a parent chart: parent
- a child chart: child
- a grandchild chart: grandchild

The child have the grandchild as a dependency, with dependency values setted inchild values.yaml file.
The parent have the child as a dependency, and no values defined for the grandchild here.

When I try to template the parent chart, the grandchild default values coming from the child defined values are available if my dependencies are not pulled from a distant repository (in a tgz file). It works if all my subcharts are untarred - available locally.

# Case
I have the following files and directories:

```
├── parent/
│   ├── charts/
│   │      └── child(.tgz)/
│   │               ├── Chart.yaml
│   │               ├── charts/
│   │               │       └── grandchild(.tgz)/
│   │               │               └── templates/ ... > check if toto value is available
│   │               └── values.yaml > toto empty by default
│   ├── Chart.yaml > dependency grandchild
│   ├── templates/ ...
│   └── values.yaml > grandchild:
│                                      toto: "titi"
└── values.yaml > child values defined without grandchild values
```

## parent files

Chart.yaml:

```yaml
description: Bug
type: application
name: parent
version: 1.0.0

dependencies:
- name: helm-child-chart
  alias: childchart
  version: "1.x.x"
  repository: "file://./charts/child"
```

values.yaml:

```yaml
child:
  toto: "oh"
```

## child files

Chart.yaml:

```yaml
description: Bug
type: application
name: child
version: 1.0.0

dependencies:
- name: helm-grandchild-chart
  alias: grandchild
  version: "1.x.x"
  repository: "file://./charts/grandchild"
```

values.yaml:

```yaml
toto: "ah"

grandchild:
  tata: "hi"
```

## grandchild files

Chart.yaml:

```yaml
description: Bug
type: application
name: grandchild
version: 1.0.0
```

values.yaml:

```yaml
tata:
```

templates/test.yaml:
```yaml
{{- if not .Values.tata-}}
{{- fail "No tata found." -}}
{{- else -}}
tata: {{ .Values.tata }}
{{- end -}}
```

# Reproducing the bug

If all the subcharts are locally available, use the following command:
```bash
# In the parent folder root
helm template --dry-run --debug . -f .\values.yaml

# Result:
tata: hi
```

If the subcharts are pulled from a repository and available as tgz files:

```bash
# In the parent folder root
helm template --dry-run --debug . -f .\values.yaml

# Result:
Error: execution error at (parent/charts/child/charts/grandchild/templates/test.yaml:x:x): No tata found.
```

Thanks for reading the whole ticket.

**Comment by Diliz** [comment]
Actually found the root cause of my issue! I updated the previous message with the real bug case :)

The problem is the granchild alias declaration in the child chart is lost from the parent side, this issue occurs only with builded/tarred dependencies.

My current fix is the following:
- Parent values:
```yaml
child:
  toto: "oh"
```
- Child values:
```yaml
toto: "ah"

grandchild: &grandchild
  tata: "hi"

helm-grandchild-chart: *grandchild
```
- Grandchild values:
```yaml
tata:
```

The result:
```bash
# In the parent folder root
helm template --dry-run --debug . -f .\values.yaml

# Result:
tata: hi
```
