### ISSUE TITLE
range function's inconsistencies when reading values with dependencies in place

### ISSUE THREAD

**Issue by niesmo** [helm/helm#10837]
Hi
I noticed some inconsistencies in the way helm templates behave when they are used directly vs when they are dependents of other charts. Also, this inconsistency seems to be different in different scenarios.

### Setup
Given this template `./charts/random-template/templates/random.yaml`:
```yaml
global:
  globaldata:
    - /straight/from/template
  {{- range $key, $value := .Values.global.globalData }}
    - {{ $key }}
  {{- end }}
```
and `./charts/random-template/values.yaml`:
```yaml
global:
  globalData:
    /random/template:
```
and `./Chart.yaml`:
```yaml
apiVersion: v2
name: main-chart
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: random-template
    repository: "file://../random-template"
```
and `./values.yaml`:
```yaml
global:
  globalData:
    /parent/chart:
```

When I run `helm template .` at the root directly, I would expect to see 3 values under `.global.globaldata` but I only see two 😢 . I would have expected the `/parent/chart` to show up in the list as well.
```yaml
---
# Source: main-chart/charts/random-template/templates/random.yaml
global:
  globaldata:
    - /straight/from/template
    - /random/template
```
but if I template out the `random-template` directly (meaning there's no dependencies in place), I get what I expect (`helm template .\charts\random-template\`). Note that `/parent/chart` is not expected in this case.
```yaml
---
# Source: random-template/templates/random.yaml
global:
  globaldata:
    - /straight/from/template
    - /random/template
```

### Issue

I feel like the behavior of the `range` function (or the data that's visible to it) is different if there's a dependency in place (I could be very wrong, I'm very new to helm in general).

### Workaround

As a work around, I have found that if I add any value to the `/parent/chart:` key in the values.yaml, it will cause it to render correctly. So given `./values.yaml`:
```yaml
global:
  globalData:
    /parent/chart: meaningless
```
running `helm template .` will result in all 3 values to show up 😵.
```yaml
---
# Source: main-chart/charts/random-template/templates/random.yaml
global:
  globaldata:
    - /straight/from/template
    - /parent/chart
    - /random/template
```

### Question
Why does the range function only able to render the `/parent/template` when there's a value for that key? but it has no problems rendering the `/random/template` key even though there's no value for it.

P.S. there's another scenario that even adding a value to the key does not fix the problem which I have documented in the [README of this repo.](https://github.com/niesmo/helm-dependency-behavior)

Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube
