### ISSUE TITLE
Chart.yaml dependencies gets empty in subchart

### ISSUE THREAD

**Issue by khauser** [helm/helm#10889]
Bug-Report:

We have moved the dependencies-block of a chart into the `Chart.yaml` since using `requirements.yaml` is deprecated.
E.g.:
Child-chart:
```
name: icm
version: 0.2.8
dependencies:
  - name: icm-as
    version: 0.2.6
    repository: file://../icm-as
  - name: icm-web
    version: 0.1.30
    repository: file://../icm-web
```

Parent-chart:
```
name: icm-replication
version: 0.0.1
dependencies:
  - name: icm
    version: 0.2.8
    repository: file://../icm
    alias: icm-live
  - name: icm
    version: 0.2.8
    repository: file://../icm
    alias: icm-edit
```

If we now do a `helm dependeny update` on the parent chart, the `Chart.yaml` within subcharts tgz doesn't contain the dependencies block.
When using `requirements.yaml` the file is also available within the tgz and does contain the dependencies block.

Output of `helm version`:
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
