### ISSUE TITLE
Helm install generates different deployed resources than helm template

### ISSUE THREAD

**Issue by sarasensible** [helm/helm#10880]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:51Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

I am trying to install the Argo CD Helm chart with Helm and my values file does not seem to be honored in the Helm manifest.  I have doublechecked the values and they are indented properly, and the `helm get values argo-cd` command shows the correct values.  If I render the template using `helm template` and do a `kubectl apply -f -` I get the correct output, however if I do a `helm upgrade --install argo-cd` and then check the manifest with `helm get manifest argo-cd` I do not see the correct values.

Specifically, my values file contains this:

```
dex:
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /api/dex/.well-known/openid-configuration
      port: 5556
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 2
  extraVolumes:
    - emptyDir: {}
      name: dexconfig
    - name: google-json
      secret:
        defaultMode: 420
        secretName: argocd-service-account-secret
  extraVolumeMounts:
    - mountPath: /etc/dexconfig
      name: dexconfig
    - mountPath: /etc/dexconfig/oidc
      name: google-json
      readOnly: true
```

`helm get manifest argo-cd` shows this deployment after executing `helm upgrade --install argo-cd argo/argo-cd --version "v2.3.0" -f my-values.yaml`:
```
# Source: argo-cd/templates/dex/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-cd-argocd-dex-server
  labels:
    app.kubernetes.io/name: argocd-dex-server
    helm.sh/chart: argo-cd-2.3.0
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/version: v2.22.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
      app.kubernetes.io/instance: argo-cd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-dex-server
        helm.sh/chart: argo-cd-2.3.0
        app.kubernetes.io/instance: argo-cd
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/component: dex-server
        app.kubernetes.io/version: v2.22.0
    spec:
      initContainers:
      - name: copyutil
        image: argoproj/argocd:v1.5.4
        imagePullPolicy: IfNotPresent
        resources:
          {}
        command:
        - cp
        - /usr/local/bin/argocd-util
        - /shared
        volumeMounts:
        - mountPath: /shared
          name: static-files
      containers:
      - name: dex-server
        image: quay.io/dexidp/dex:v2.22.0
        imagePullPolicy: IfNotPresent
        command:
        - /shared/argocd-util
        - rundex
        ports:
        - name: http
          containerPort: 5556
          protocol: TCP
        - name: grpc
          containerPort: 5557
          protocol: TCP
        volumeMounts:
        - mountPath: /shared
          name: static-files
      containers:
      - name: dex-server
        image: quay.io/dexidp/dex:v2.22.0
        imagePullPolicy: IfNotPresent
        command:
        - /shared/argocd-util
        - rundex
        ports:
        - name: http
          containerPort: 5556
          protocol: TCP
        - name: grpc
          containerPort: 5557
          protocol: TCP
        volumeMounts:
          - mountPath: /shared
            name: static-files
        resources:
          {}
      serviceAccountName: argocd-dex-server
      volumes:
        - emptyDir: {}
          name: static-files
```
Notice that there are no volumes or volumemounts corresponding to my extraVolumes and extraVolumeMounts.

However if I do a `helm template argo-cd argo/argo-cd -f my-values.yaml`, I get the volumes and volume mounts correctly mounted, and I can then directly apply this output to get the desired outcome.

```
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /shared
          name: static-files
        - mountPath: /etc/dexconfig
          name: dexconfig
        - mountPath: /etc/dexconfig/oidc
          name: google-json
          readOnly: true
        resources:
          {}
      serviceAccountName: argocd-dex-server
      volumes:
      - emptyDir: {}
        name: tmp-dir
      - emptyDir: {}
        name: static-files
      - emptyDir: {}
        name: dexconfig
      - name: google-json
        secret:
          defaultMode: 420
          secretName: argocd-service-account-secret
```

Not sure what the deal is here, this is the first time I've seen anything happen like this, any help would be greatly appreciated.
