### ISSUE TITLE
Deep merge in containers field in chart with two deployments

### ISSUE THREAD

**Issue by malcolm061990** [helm/helm#10927]
Hi.
I have `library` chart:
```yaml
# only part from it
containers:
- name: {{ .Chart.Name }}
  {{- if .Values.config.command }}
  command: {{ .Values.config.command }}
  {{- end }}
  resources:
    {{- toYaml .Values.config.resources | nindent 10 }}
  {{- if .Values.config.containerPort}}
  ports:
  - containerPort: {{ .Values.config.containerPort }}
  {{- end}}
  envFrom:
  {{- if .Values.config.envFrom }}
    {{- toYaml .Values.config.envFrom | nindent 10 }}
  {{- end }}
...
# from the Common Helm Helper Chart
{{- define "common-chartlib.deployment" -}}
{{- include "common-chartlib.util.merge" (append . "common-chartlib.deployment.tpl") -}}
{{- end -}}
```

There is `application` chart that contains two deployments that differs only with `command` field value:
```yaml
# values
  command1: ["123"]
  command2: ["456"]

# deployment1
spec:
  containers:
  - name: deployment1
    command: {{ .Values.config.command1 }}

# deployment2
spec:
  containers:
  - name: deployment1
    command: {{ .Values.config.command2 }}
```

If I run `helm template` I will get:
```yaml
      containers:
      - command:
        - 123
        name: backend
      # other fields like ports, envFrom, resources were removed
      volumes:
      - name: backend-private-key
        secret:
          secretName: backend-private-key
```

As you see all fields except `name` and `command` were removed after merging.

Expected result:
```yaml
      containers:
      - command:
        - 123
        name: backend
# other fields taken from library chart like ports, envFrom, resources must NOT be removed
        ports: 
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend
      volumes:
      - name: backend-private-key
        secret:
          secretName: backend-private-key
```

Output of `helm version`:
`version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}`
Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}`

Please help.
