### ISSUE TITLE
Helm does not return control immediately after the end of the deployment with the wait option

### ISSUE THREAD

**Issue by waewoo** [helm/helm#10941]
Output of `helm version`:

> version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:

> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15+IKS", GitCommit:"bef807c747db0037aebbcbebd12699950a06d1a2", GitTreeState:"clean", BuildDate:"2022-01-20T14:23:00Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

> IBMCloud Kubernetes (IKS)

hello, 

When I use a helm hook (pre-install or post-install) specifying for example an optional **wait** with **timeout** of 600s... I noticed that, even if my deployment ended in 100 s... I had to reach the 600s of my timeout before my helm returns (successfully in my case).

Is this the normal behavior? Shouldn't the helm return as soon as the deployment is complete?

`helm install  kafka-connect-dev-1 ./kafka-connect --wait --timeout 600s`

```
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-connect-dev-1
  annotations:
    helm.sh/hook: pre-install
  labels:
    app: kafka-connect
    release: kafka-connect-dev-1
    helm.sh/chart: kafka-connect-1.0.0
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/name: kafka-connect
    app.kubernetes.io/instance: kafka-connect-dev-1
    app.kubernetes.io/component: kafka-connect
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    metadata:
      name: kafka-connect-dev-1
      labels:
        app: kafka-connect
        release: kafka-connect-dev-1
        helm.sh/chart: kafka-connect-1.0.0
        app.kubernetes.io/version: "3.1.0"
        app.kubernetes.io/name: kafka-connect
        app.kubernetes.io/instance: kafka-connect-dev-1
        app.kubernetes.io/component: kafka-connect
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: my-secret-reg
      restartPolicy: Never
      containers:
      - name: kafka-connect-post-install
        image: "private.fr2.icr.io/myregistry/kafka-connect-splunk:2.0.7-3.1.0"
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
```
