### ISSUE TITLE
How can I access the tags inside the chart?

### ISSUE THREAD

**Issue by justinmchase** [helm/helm#10953]
I have multiple dependencies, and in one I want to check to see if the other was installed.

```yaml
# parent/Chart.yaml
dependencies:
- name: A
  tags:
  - A
- name: B
  tags:
  - B
```
```yaml
# parent/values.yaml
tags:
  A: false
  B: false
```

Then when I'm installing suppose I'm doing `--set tags.B=true`

Then inside of the B chart I just want to do some logic in my template like this:
```yaml
example: {{ .Values.tags.A | ternary "yes A is installed" "no A is not installed" }}
```

But  `.Values.tags` appears to be `nil` and I can't seem to figure out how to access the tag values. I can't seem to find it in the docs either.
