### ISSUE TITLE
Dots syntax appear to not work in networking.k8s.io/v1

### ISSUE THREAD

**Issue by anthony-sarkis** [helm/helm#10962]
Output of `helm version`:

```ValidationError(Ingress.spec.rules[0].http.paths[2].backend.service): unknown field "port.number" in io.k8s.api.networking.v1.IngressServiceBackend]```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Azure

Works:
```
        backend:
          service:
            name: diffgram-walrus
            port:
                number: 8080
```
but this doesn't
```
    backend:
      service.name: frontend
      service.port.number: 8080

```
Sorry if I am misunderstanding 
https://github.com/diffgram/diffgram-helm
