### ISSUE TITLE
Pending Pods are not making Helm install fail

### ISSUE THREAD

**Issue by Tim-Schwalbe** [helm/helm#10974]
I just implemented podAntiAffinity in my deployment template managed by Helm.
I want to avoid that pods getting deployed on the same node.

```
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: releaseNameCommitShortSHA
                operator: In
                values:
                - "{{ .Release.Name }}-{{.Values.CI_COMMIT_SHORT_SHA}}"
            topologyKey: "kubernetes.io/hostname"
```

The problem is that helm says STATUS: deployed, even when I have pending pods during the roll out.

**For example:**
If I want 4 replicas, but only have 3 Nodes, 1 Pod keeps in pending state, but the helm install does not recognise this as a problem and succeeds. 

![image](https://user-images.githubusercontent.com/16404601/169064962-5247db75-2272-4aee-b7fc-f363c7fd1f26.png)

Output of `helm version`:
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7-gke.1500", GitCommit:"565bc494bfc66bfb42aec331000c61f72b020f1a", GitTreeState:"clean", BuildDate:"2022-03-10T09:33:51Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE
