### ISSUE TITLE
Feature: Support references to other value definitions for values.yaml

### ISSUE THREAD

**Issue by xcbeyond** [helm/helm#10978]
In the values.yaml file, references to other value definitions are supported。

 for example：

```yaml
ingress:
  hosts:
    - host: xxx.github.io
       paths:
         - path: /xcbeyond
           pathType: Prefix
  tls:
  - hosts:
    - $(ingress.hosts.host)
```
