### ISSUE TITLE
How to template the values of dependent chart

### ISSUE THREAD

**Issue by genofire** [helm/helm#10992]
How to template the values of dependent chart, like:

```yaml
global:
  domain: "example.org"

element-web:
  ingress:
    hosts:
     - "element.{{ global.domain }}"
  server_address: "https://{{ global.domain }}"
  homeserver: "{{ global.domain }}"
```

i do not find any documentation, somwhere in an issue is written that it is supportet by lua in helm3.
