### ISSUE TITLE
import-values from sub charts are not working since 3.8.2

### ISSUE THREAD

**Issue by to4kin** [helm/helm#10998]
As described in documentation, we can import values from sub charts into parent chart:

```
# child's values.yaml file

exports:
  data:
    image:
      repository: busybox
```

```
# parent's Chart.yaml file
apiVersion: v2
name: test
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: child
    repository: "file://charts/child"
    version: 1.0.0
    tags:
      - child
    import-values:
      - data
```

```
# parent's values.yaml file
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""
```

Before version v3.8.2 we had the following output:

helm upgrade -i test . --set tags.child=true --dry-run --debug

```
COMPUTED VALUES:
child:
  exports:
    data:
      image:
        pullPolicy: IfNotPresent
        repository: busybox
        tag: ""
  global: {}
image:
  pullPolicy: IfNotPresent
  repository: busybox
  tag: ""
```

As you can see the image was changed in parent chart, but if we'll try the same with version >=v3.8.2:
```
COMPUTED VALUES:
child:
  exports:
    data:
      image:
        repository: busybox
  global: {}
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: ""
```

I can't understand what was changed and how to achieve the same in last version of helm?

Output of `helm version`: version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS EKS
