### ISSUE TITLE
Issue while looping thru' hash of lists

### ISSUE THREAD

**Issue by sahajhaksh** [helm/helm#11004]
I have the following list of values in ```values.yaml```
```
env:
   - name: PORT0
      value: "3000"
   - name: RAILS_ENV
      value: "dev"
   - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: abc
          key: xyz
```
I tried this in the ```deployment.yaml```
```
{{- with .Values.env }}
 {{- range $key, $val := . }}
   - name: {{ $key }}
      value: "{{ $val }}"
 {{- end }}
 {{- end }}
```
But I ended up getting this as the output
```
env:
          - name: 0
            value: map[name:PORT0 value:3000]
          env:
          - name: 1
            value: map[name:RAILS_ENV value:dev]
          env:
          - name: 2
            value: map[name:DATABASE_URL valueFrom:map[secretKeyRef:map[key:xyz name:abc]]]
---
```
Could someone help me with the correct iteration here? Thanks
