### ISSUE TITLE
Error: could not find : no matching version

### ISSUE THREAD

**Issue by anetbnd** [helm/helm#11013]
Hello

Since today I get an error when running `helm dependency build` in our project. It has been working since many month and we did not change anything on the helm chart. Now the error is:
```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "openshift-actions-runner" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Save error occurred:  could not find : no matching version
Error: could not find : no matching version
```

The chart file is looking like that: 
```
apiVersion: v2
name: myapp
description: A Helm chart for my application
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: "8.24.3"
- name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: "8.8.2"
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: "15.5.5"
```

And the `Chart.lock` is looking like this:
```
dependencies:
- name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 8.24.3
- name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 8.8.2
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.5
digest: sha256:09d9256a4f88a69c82ee9c01fc02d9f4e436a4f808193ea1a007ebb3945786a1
generated: "2021-11-12T22:12:58.885184+01:00"
```

When running `helm dependency update`. The error message is a little bit different:
```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "openshift-actions-runner" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: can't get a valid version for repositories rabbitmq, mysql, redis. Try changing the version constraint in Chart.yaml
```

Does anyone know, what the root cause for this error is? 

Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"windows/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
-
