### ISSUE TITLE
ValidationError for resourceRequirements information in CronJob k8s kind

### ISSUE THREAD

**Issue by vicentefb** [helm/helm#11024]
Output of `helm version`: ```version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}```

I have the following CronJob template file:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
  name: collection
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 100
      template:
        spec:
          containers:
          - args:
            - /collection.sh
            command:
            - bash
            env:
            - name: COLLECTION
              valueFrom:
                configMapKeyRef:
                  key: COLLECTION
                  name: collection
            - name: DB
              valueFrom:
                configMapKeyRef:
                  key: DB
                  name: collection
            - name: MAX_BACKUPS
              valueFrom:
                configMapKeyRef:
                  key: MAX_BACKUPS
                  name: collection
            - name: RESULTS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: RESULTS_DB_HOST
                  name: collection
            - name: RESULTS_DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: RESULTS_DB_PORT
                  name: collection
            image: 1.2.3.45:67701/image:latest
            imagePullPolicy: IfNotPresent
            name: collection
            resources: {{- toYaml .Values.collection.resources | nindent 10 }}
            volumeMounts:
            - mountPath: /collection_data
              name: collection
          hostname: backup-results-collection
          initContainers:
          - command:
            - sh
            - -c
            - until nc -z db 9999; do echo waiting; sleep 2; done;
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            name: db
          restartPolicy: Never
          volumes:
          - hostPath:
              path: /var/nfs/collection_data
              type: DirectoryOrCreate
            name: collection
  schedule: 0 0 * * *

```

I have the following values.yaml file: 

```
collection:
  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 200Mi
```

The error I keep getting when using ```helm install --debug --dry-run -n test --kubeconfig test.conf test_one /Path/To/Chart/test``` 

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CronJob.spec.jobTemplate.spec.template.spec): unknown field "limits" in io.k8s.api.core.v1.PodSpec, ValidationError(CronJob.spec.jobTemplate.spec.template.spec): unknown field "requests" in io.k8s.api.core.v1.PodSpec]
helm.go:84: [debug] error validating "": error validating data: [ValidationError(CronJob.spec.jobTemplate.spec.template.spec): unknown field "limits" in io.k8s.api.core.v1.PodSpec, ValidationError(CronJob.spec.jobTemplate.spec.template.spec): unknown field "requests" in io.k8s.api.core.v1.PodSpec]
```

I was wondering if it's possible to reference resources information inside values.yaml for a CronJob k8s resource? Or is my CronJob template wrong ? 

Referencing resources key works fine with Deployment k8s kind.

Thanks!
