### ISSUE TITLE
How to manage controlled helm chart updates across environments?

### ISSUE THREAD

**Issue by musabmasood** [helm/helm#11035]
Apologies if this is not the right place to ask this.

Say you have a helm chart version `0.1.0` with two values files:

```
- values-staging.yaml
- values-production.yaml
```

In your automation, you release and publish a new version of this chart `0.2.0` but you want to slowly roll out your change from `staging` to `production`. Since the chart `version` is same for both environments, how do you roll-out your change?

One option is to create a separate `Chart` per environment but that defeats the purpose of shared templates.

Any other ideas?

**Comment by hickeyma** [comment]
@musabmasood Trying to better understand your scenario.  Have some questions about what you are trying to do.

If you have chart version `0.1.0 and `0.2.0`,  does this mean you then have 2 versions of a chart? So, you should be able to install version `0.1.0` and also version `0.2.0`. Therefore, you can have deployments of the chart with `0.1.0` and also version `0.2.0`.

Or am I misunderstanding the issue?

**Comment by musabmasood** [comment]
Lets saw you have this helm chart called `foo` that uses a dependent chart called `bar`

```
# chart.yaml
apiVersion: v2
name: foo
version: 0.1.0
dependencies:
- name: bar
  version: 0.1.0
  repository: somerepo
```

This chart `foo` is deployed on `staging` with `values-staging.yaml` and on production with `values-production.yaml`. Things are live.

Now lets say there is a new release of `bar` => `0.2.0`. If I update my `chart.yaml` to this:

```
# chart.yaml
apiVersion: v2
name: foo
version: 0.1.0
dependencies:
- name: bar
  version: 0.2.0 <==== upgrade
  repository: somerepo
```

If you do this ^ then `staging` and `production` **both** get the new changes from `bar`. This is not what I want. I want to test changes in `bar` only on `staging` before _promoting_ them to `production`.
