### ISSUE TITLE
semver2 version constraint in dependencies is wrong

### ISSUE THREAD

**Issue by Stefanqn** [helm/helm#11032]
Output of `helm version`:
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS
---
I published an own `keycloak-operator` to ACR, with versions: [
18.0.0_18
0.0-setDuringBuild_17
0.0-setDuringBuild_16
0.0-setDuringBuild_15
18.0.0_14
17.0.1_13
]

my umbrella chart dependencies contain:
```yaml
dependencies:
  - name: keycloak-operator
    version: "~18.0.0" # this version must be pinned as ~ does not work
    repository: "oci://ACR.azurecr.io/helm"
```
```bash
helm dependency update
``` resolves "Pulled: ACR.azurecr.io/helm/keycloak-operator:18.0.0_14"

**This is wrong.** I have to pin the version to `version: "18.0.0+18"` to make it work.
