### ISSUE TITLE
Helm not updating Kubernetes resources after manual changes

### ISSUE THREAD

**Issue by 3schwartz** [helm/helm#11040]
Hi,

After manual changing some resource helm doesn't change to manifest when running new deployment.

I can see others have experienced the same https://github.com/helm/helm/issues/5915 however this issue is closed.

I have been able to reproduce the error by following steps below.

# Reproduce

## Create a new helm chart
Run `helm create helm-issue`.

## Add dependencies

I have experience the error when changing Keda Scaled Objects manually. Change `Charts.yaml` to align with below *(Since I'm working on Docker Desktop I also need to deploy a metric-server)*

````
apiVersion: v2
name: helm-issue
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: keda
    tags:
      - scaling
    version: 2.6.1
    repository: https://kedacore.github.io/charts
  - name: metrics-server
    tags:
      - observability
    version: 6.0.7
    repository: https://charts.bitnami.com/bitnami
````

## Simplify `values.yaml` *(optional)*

Change `values.yaml` to align with below and delete blocks not needed in `./template/deployment.yaml` and other templates.

````
metrics-server:
  apiService:
    create: true
  extraArgs: 
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-insecure-tls=true

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
````

## Create a Scaled Object

Add file `./template/scaledobject.yaml` and add below to file 

````
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Chart.Name }}-scale
spec:
  scaleTargetRef:
    name: {{ .Chart.Name }}
    envSourceContainerName: {{ .Chart.Name }}
  pollingInterval: 15
  cooldownPeriod: 20
  minReplicaCount: 1
  maxReplicaCount: 3
  fallback:
    failureThreshold: 3
    replicas: 1
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "60"
  - type: memory
    metadata:
      type: Utilization
      value: "60"    
````

## Deploy soluton

Update dependencies `helm dependencies update .`
Run `helm upgrade --install helm-issue .`

## Change Scaled Object manual

Both Scaled Object and HPA should be deployed. You can validate this be running below commands
````
kubectl get scaledobject
kubectl get hpa
````

The Scaled Objects should report both CPU and Memory as triggers and HPA should report metrics for these.

Now edit the Scaled Object manually and remove the CPU trigger
````
kubectl edit scaledobject helm-issue-scale
...
remove CPU trigger
````

You should see CPU trigger removed if you run `kubectl get scaledobject`.

## Upgrade deployment

Now deploy again by running `helm upgrade --install helm-issue .`

## Validate error present

If you run `kubectl get scaledobject` the CPU trigger isn't added again as expected.

If you run `helm get manifest helm-issue` the Scaled Object is correctly specified with both triggers.

````
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: helm-issue-scale
spec:
  scaleTargetRef:
    name: helm-issue
    envSourceContainerName: helm-issue
  pollingInterval: 15
  cooldownPeriod: 20
  minReplicaCount: 1
  maxReplicaCount: 3
  fallback:
    failureThreshold: 3
    replicas: 1
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "60"
  - type: memory
    metadata:
      type: Utilization
      value: "60"
````

# Versions

Output of `helm version`:
````
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
````
Output of `kubectl version`:
````
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
````
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS and demo above in Docker Desktop

**Comment by bacongobbler** [comment]
See https://helm.sh/docs/faq/changes_since_helm2/#upgrades-where-live-state-has-changed

**Comment by bacongobbler** [comment]
Alternatively use `helm upgrade -force` which forces Kubernetes to use the manifest as an HTTP PUT request.

**Comment by 3schwartz** [comment]
> See https://helm.sh/docs/faq/changes_since_helm2/#upgrades-where-live-state-has-changed
> 
> changes made to the live state always wins. That is to say, if you removed the trigger manually then called helm upgrade, the trigger removal will remain. Use `helm rollback` to revert changes made to the live state. Please see the FAQ for more information.

Thanks for the reply - it clarifies a lot :-)

FYI @dtu-ruth

**Comment by waleed-cariad** [comment]
Hi @bacongobbler 

I am having the `unexpected behaviour`
Helm chart contains the following
```
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
```

After `helm install .....` there will be a kubernetes ` deployment` created. Next, I removed the above from the deployment directly and it is like this in the deployment manifest on kubernetes cluster
`resources: {}`

After that, I ran `helm upgrade ...`. What I was expecting is that helm should respect the `live` state and should not populate that `requests` block with corresponding values but I am seeing that they are added again after running `helm upgrade.....`
Is it the right behavior?
Helm Version: `version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.5"}`
