### ISSUE TITLE
Helm list with --selector

### ISSUE THREAD

**Issue by keriksson-rosenqvist** [helm/helm#11049]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"3396beebcd97ed3b01f57127fba1b8565b311acb", GitTreeState:"clean", BuildDate:"2022-06-04T17:58:54Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

I am trying to use the label selector functionality described in the documentation and [here](https://github.com/helm/helm/issues/4639), without any success. Is anyone able to actually use this in their releases and filtering with `helm list -l key=value`?
I currently have a release with the following configmap and when using the -l flag I get no results at all.
```
apiVersion: v1
data:
  TEST_1: "1"
  TEST_2: two
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    name: test-config
    namespace: test
```
I've tried the following commands but neither finds any results.
```
$ helm list -l "app.kubernetes.io/managed-by=Helm" -n test
$ helm list -l app.kubernetes.io/managed-by=Helm -n test
$ helm list -l "app.kubernetes.io/managed-by==Helm" -n test
$ helm list -l app.kubernetes.io/managed-by==Helm -n test
```
What am I doing wrong?
