### ISSUE TITLE
use file as configmap (AsConfig) while keep accessibility to charts variables

### ISSUE THREAD

**Issue by MUCZ** [helm/helm#11088]
here is a use case of function `AsConfig`
``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
{{ (.Files.Glob "foo/conf.json").AsConfig | indent 2 }}
```

I want to keep accessibility to charts variables inside the file `foo/conf.json`, and I want them to be rendered in runtime.  for 
example, inside my `foo/conf.json`, i would like to use some values defined in values.yaml.
``` json
{
 "_comment":"this is a json file, but i wanna use helm variables as below",
  "name": {{$.Values.name}}
}
```

I really need this feature because editing a json file(my app's config file) inside a yaml file(helm yaml file) is really error prone since i have no grammar check.
