### ISSUE TITLE
Error: INSTALLATION FAILED: parse error at (tls-secret/templates/externalsecrets.yaml:25): function "pemCertificate" not defined

### ISSUE THREAD

**Issue by Pavan976** [helm/helm#11091]
Hello Team, 

I'm trying to build the helm charts for exeternalsecrets creation on oracle cloud, but i got the below error, could you please someone help here.

Error: INSTALLATION FAILED: parse error at (tls-secret/templates/externalsecrets.yaml:25): function "pemCertificate" not defined

externalsecret.yaml file -----------------------------------------

```
{{- if and (.Values.externalSecrets.tls.tlsSecret) (.Values.externalSecrets.createExternalSecrets) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.tls.name }}
  {{- if .Values.externalSecrets.tls.labels }}
  labels:
{{ toYaml .Values.externalSecrets.tls.labels | indent 4 }}
{{- end }}
{{- if .Values.externalSecrets.tls.annotations }}
  annotations:
{{ toYaml .Values.externalSecrets.tls.annotations | indent 4 }}
{{- end }}
spec:
    refreshInterval: "1m"
    secretStoreRef:
      kind: ClusterSecretStore
      name: {{ .Values.externalSecrets.tls.secretStoreName }}
    target:
      name: {{ .Values.externalSecrets.tls.k8sSecretName }}
      creationPolicy: Owner
      template:
        type: kubernetes.io/tls
        data:
          tls.crt: "{{ .certificate | pemCertificate }}"
          tls.key: "{{ .privatekey | pemPrivateKey }}"
    data:
      - secretKey: certificate
        remoteRef:
          key: {{ .Values.externalSecrets.tls.cert }}
      - secretKey: privatekey
        remoteRef:
          key: {{ .Values.externalSecrets.tls.key }}
{{- end }}
```

**Comment by yxxhero** [comment]
@Pavan976 pemCertificate func? where form? Thanks very much.

**Comment by Pavan976** [comment]
@yxxhero tls.crt needs pemCertificate format.

```
data:
      - secretKey: certificate
        remoteRef:
          key: {{ .Values.externalSecrets.tls.cert }}
      - secretKey: privatekey
        remoteRef:
          key: {{ .Values.externalSecrets.tls.key }}
``` 
the certificate and privatekey gets value from vault and then i need to convert that value to pem format and supply to tls.crt and tls.key
 and when i use that pemCertificate and pemPrivateKey it is throwing the function not defined error. i have not defined any function in chart or helpers.

reference: https://external-secrets.io/v0.5.3/guides-templating-v1/#helper-functions

the k8s manifest file which is working perfectly fine if run ```k create -f filename ``` and i'm trying to convert the manifest to helm chart i'm getting above mentioned error.

manifest :
```apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: template-tls-example2
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: certificate3
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .mycret | pemCertificate }}"
        tls.key: "{{ .mykey | pemPrivateKey }}"

  data:
  - secretKey: mycret
    remoteRef:
      key: cert
  - secretKey: mykey
    remoteRef:
      key: private_key
```

please help me to convert the above manifest to helm chart
