### ISSUE TITLE
Empty template file throws an error that 

### ISSUE THREAD

**Issue by Garrett-R** [helm/helm#11103]
## Bug

Observe this template:

```yaml
# If a template file is completely empty, `helm template` throws an error. The presence of
# this comment ensures there's something in the file.
{{- if eq .Values.environment "staging" }}
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: value-redacted.dkr.ecr.us-east-1.amazonaws.com/my/repo
          command: ["./do_thing.sh"]
{{ end }}
```

If you run this with:

```shell
helm template  . -s templates/deployments/worker-deployment.yaml   --set environment=dev
```

it works fine, but if you remove the comment in that file, and run that command again, you get:
```shell
Error: could not find template templates/deployments/worker-deployment.yaml in chart
```

## Versions

EDIT Output of `helm version` after updating:
```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Output of `kubectl version`:
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-17T22:28:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.21) exceeds the supported minor version skew of +/-1
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Amazon EKS (although, that's not relevant here)

**Comment by Garrett-R** [comment]
Sorry, I should have updated Helm before posting, although updating to the latest stable Helm, I still get the issue.  Here my terminal session showing it:
```shell
~/Desktop/tmp_helm_bug $ helm version
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
~/Desktop/tmp_helm_bug $ tree .
.
├── Chart.yaml
└── templates
    └── deployments
        └── worker-deployment.yaml

2 directories, 2 files
~/Desktop/tmp_helm_bug $ cat Chart.yaml 
apiVersion: v2
name: upcodes-web
description: The UpCodes web app.
type: application

# This field is required by helm and used for versioning in public
# charts. We don't use it or update it
version: 0.1.0
~/Desktop/tmp_helm_bug $ cat templates/deployments/worker-deployment.yaml 
{{- if eq .Values.environment "staging" }}
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: value-redacted.dkr.ecr.us-east-1.amazonaws.com/my/repo
          command: ["./do_thing.sh"]
{{ end }}
~/Desktop/tmp_helm_bug $ helm template  . -s templates/deployments/worker-deployment.yaml   --set environment=dev
Error: could not find template templates/deployments/worker-deployment.yaml in chart
~/Desktop/tmp_helm_bug $ 

```

I'm on Ubuntu 20.04 if that makes a difference.

**Comment by mneira10** [comment]
Can confirm a repro in MacOS 12.2.1 zsh with helm 3.8.1 and 3.9.0: 

3.8.1:
```shell
$ helm version
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}
$ tree .
.
├── Chart.yaml
└── templates
    └── deployments
        └── worker-deployment.yaml

2 directories, 2 files
$ cat Chart.yaml
apiVersion: v2
name: upcodes-web
description: The UpCodes web app.
type: application

# This field is required by helm and used for versioning in public
# charts. We don't use it or update it
version: 0.1.0
$ cat templates/deployments/worker-deployment.yaml
{{- if eq .Values.environment "staging" }}
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: value-redacted.dkr.ecr.us-east-1.amazonaws.com/my/repo
          command: ["./do_thing.sh"]
{{ end }}
$ helm template . -s templates/deployments/worker-deployment.yaml --set environment=dev
Error: could not find template templates/deployments/worker-deployment.yaml in chart
```

3.9.0:
```shell
$ helm version
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}
$ tree .
.
├── Chart.yaml
└── templates
    └── deployments
        └── worker-deployment.yaml

2 directories, 2 files
$ cat Chart.yaml
apiVersion: v2
name: upcodes-web
description: The UpCodes web app.
type: application

# This field is required by helm and used for versioning in public
# charts. We don't use it or update it
version: 0.1.0
$ cat templates/deployments/worker-deployment.yaml
{{- if eq .Values.environment "staging" }}
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: value-redacted.dkr.ecr.us-east-1.amazonaws.com/my/repo
          command: ["./do_thing.sh"]
{{ end }}
$ helm template . -s templates/deployments/worker-deployment.yaml --set environment=dev
Error: could not find template templates/deployments/worker-deployment.yaml in chart
$
```

**Comment by yxxhero** [comment]
@Garrett-R From the source code. I think of that it is not a bug. 
When a template file is empty after rendered. It will be sikped.

**Comment by yxxhero** [comment]
I will submit PR to try to optimize this logic.

**Comment by Garrett-R** [comment]
> When a template file is empty after rendered. It will be sikped.

You're saying it will be skipped?  That would be great!  BTW, this is in the context of having many templates, not just a single one, so yeah, if it just skips over the empty ones, that would be ideal.

**Comment by yxxhero** [comment]
@Garrett-R yes. Thanks very much.

**Comment by mneira10** [comment]
Hi, I'm currently facing the same issue.

**Comment by Garrett-R** [comment]
@yxxhero I think you mentioned you'd try to submit a PR to optimize this logic, is that still on the roadmap?  No worries if not though!

**Comment by yxxhero** [comment]
@Garrett-R sorry. I haven't started working on it yet, but this issue doesn't affect usage.

**Comment by Garrett-R** [comment]
True, no prob!

**Comment by alexistdk** [comment]
I'm having the same problem

```
{{- if .Values.php.enabled }}
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: value-redacted.dkr.ecr.us-east-1.amazonaws.com/my/repo
          command: ["./do_thing.sh"]
{{- end }}
```
With the exact same error message 
``` 
$ helm template . -s templates/php-deployment.yaml --set php.enabled=true
Error: could not find template templates/php-deployment.yaml in chart
```
What could be the reason?

Helm version
`version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10"}`

Also, I'm using a subchart. I don't know if that's a problem.
