### ISSUE TITLE
SecretProviderClass not patched properly when recovering from failed Helm release with wait

### ISSUE THREAD

**Issue by jozala** [helm/helm#11104]
You can use attached Helm chart to reproduce the bug.
[show-bug-app.tar.gz](https://github.com/helm/helm/files/9028496/show-bug-app.tar.gz)

## Steps to reproduce
1. Install Helm release with chart including SecretProviderClass and Deployment resources (attached)
   ```sh
   $ helm upgrade --debug -i --set secretProviderClass.objectName=somekey --set initSleepTime=1 --wait --timeout 1m show-bug-app ./show-bug-app
   ```
   Note: Helm release will be in deployed status now
   
   
2. Upgrade Helm release with values:
   - changing SecretProviderClass `objectName` to empty value
   - changing Deployment so it will fail waiting because of init container running for too long
   ```sh
   helm upgrade --debug -i  --set initSleepTime=10000 --wait --timeout 1m show-bug-app ./show-bug-app
   ```
   Note: Helm release will be in failed status now, after 1 minute timeout.
   
   
3. Upgrade Helm release again with values:
   - changing SecretProviderClass `objectName` to old value (from 1.)
   - changing Deployment so it will run init container quickly
   ```sh
   helm upgrade --debug -i --set secretProviderClass.objectName=somekey --set initSleepTime=1 --wait --timeout 1m show-bug-app ./show-bug-app
   ```
   Note: Helm release will be back in deployed status now

### Expected result:
SecretProviderClass `objectName` should have non-empty value as passed in values.

### Actual result:
SecretProviderClass `objectName` value is still empty when checking with `kubectl get secretproviderclass <name>`.
However, command `helm get manifest <release-name>` shows expected value in `objectName`.

## Other info

**Output of `helm version`:**
```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}
```

**Output of `kubectl version`:**
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** 
AKS

**Comment by bacongobbler** [comment]
Have you tried using `helm rollback` instead of another `helm upgrade`?

**Comment by jozala** [comment]
@bacongobbler
Sorry for slow reply. It is my vacation time :) .
Do you suggest to try `helm rollback` to gather some additional information or as a solution? I am not able to try it currently (still out of office), but I will be able to do that soon.
That would probably solve the issue, but I cannot do that in real deployment flow. We are using [Flux](https://fluxcd.io/) which is running Helm operations. I believe Flux can expect that Helm upgrade will patch the SecretProviderClass resource properly.

**Comment by jozala** [comment]
@bacongobbler 
I've tested the behaviour when running `helm rollback` instead of `helm upgrade`.
Rollback works properly. SecretProviderClass `objectName` has back non-empty value after rollback. Also `helm get manifest show-bug-app` gives same output for SecretProviderClass resource as `kubectl get secretproviderclass show-bug-app-secret -o yaml`.

I am not sure if you've suggested it as a solution or to prove some behaviour. Could you please elaborate?

I believe Helm behaviour is erroneous when using `helm upgrade ...` command on failed Helm release in this case. The prove of that is that Helm release is in deployed status after all operations, but SecretProviderClass looks differently in outputs of `helm get manifest show-bug-app` and `kubectl get secretproviderclass show-bug-app-secret -o yaml` (see comments in YAMLs below). 

Output of `helm get manifest show-bug-app`:
```yaml
# Source: show-bug-app/templates/secretprovider.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: show-bug-app-secret
  labels:
    app: show-bug-app
    chart: show-bug-app-1.0.0
    release: show-bug-app
    heritage: Helm
spec:
  provider: azure
  secretObjects:
    - secretName: show-bug-app-secret
      type: Opaque
      labels:
        app: show-bug-app
        release: show-bug-app
      data:
        - objectName: "someSecretKey"
          key: "secretKeyName"
  parameters:
    usePodIdentity: "true"
    keyvaultName: "some-kv"
    objects: |
      array:
        - |
          objectName: "somekey"     # <-- this is set here
          objectType: secret
          objectAlias: "someSecretKey"
    resourceGroup: "some-rg"
    subscriptionId: "d172a7d0-9f49-48ce-9731-c81b5e08d9d4"
    tenantId: "ff558a31-6668-4232-9dd4-a8322c646dcf"
```

Output of `kubectl get secretproviderclass show-bug-app-secret -o yaml`:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  annotations:
    meta.helm.sh/release-name: show-bug-app
    meta.helm.sh/release-namespace: nexus-dev
  creationTimestamp: "2022-07-20T15:15:35Z"
  generation: 2
  labels:
    app: show-bug-app
    app.kubernetes.io/managed-by: Helm
    chart: show-bug-app-1.0.0
    heritage: Helm
    release: show-bug-app
  name: show-bug-app-secret
  namespace: nexus-dev
  resourceVersion: "317559695"
  uid: 468615ad-0ae6-4228-9bb5-25ea01f8ced0
spec:
  parameters:
    keyvaultName: some-kv
    objects: |
      array:
        - |
          objectName: ""   # <-- but it is empty here. Why?
          objectType: secret
          objectAlias: "someSecretKey"
    resourceGroup: some-rg
    subscriptionId: d172a7d0-9f49-48ce-9731-c81b5e08d9d4
    tenantId: ff558a31-6668-4232-9dd4-a8322c646dcf
    usePodIdentity: "true"
  provider: azure
  secretObjects:
  - data:
    - key: secretKeyName
      objectName: someSecretKey
    labels:
      app: show-bug-app
      release: show-bug-app
    secretName: show-bug-app-secret
    type: Opaque
```
