### ISSUE TITLE
Unclear error about "table" destination

### ISSUE THREAD

**Issue by Woovie** [helm/helm#11118]
In multiple places, Helm uses the term "table" when describing the destination for a value. Example:

https://github.com/helm/helm/blob/db2485b20c8f53d802f4fc98c2f95e1fc0460d15/pkg/chartutil/coalesce.go#L222-L224

Error seen:

jbanasik@akira:~/k8s/loki$ helm install cassandra bitnami/cassandra --namespace loki -f cassandra.values.yaml
coalesce.go:223: warning: destination for cassandra.dbUser.existingSecret is a table. Ignoring non-table value ()
coalesce.go:223: warning: destination for cassandra.dbUser.existingSecret is a table. Ignoring non-table value ()

My code where this error is coming from:

```yaml
dbUser:
  user: cassandra
  forcePassword: false
  existingSecret:
    name: loki-cassandra-secret
    keyMapping:
      cassandra-password: cassandra-password
```

How do I, a consumer and user of Helm, know what this error means? What's a table? What's a non-table? None of this is defined, and even looking at the code I couldn't explain to you what a table is. I'd like to see something a bit more verbose to explain exactly what this means.

The container picks the value up fine ultimately, but I still didn't find this error to be anything that helped me diagnose my issue and only lead to more confusion.
