### ISSUE TITLE
remap sub-subchart values

### ISSUE THREAD

**Issue by foosinn** [helm/helm#11123]
Hey,

we are trying to wrap an external chart into a subchart like this:

our application -> our subchart -> external chart

The idea behind this is to version control the external chart in our subchart. That way multiple applications depend on our subchart. For updates we simply can modify our subchart and not all applications.

The downside is that all variable definitions look now like this:

```yaml
application:
  subChart:
    externalChart:
      key: value
```

Is there any way to remove the additional nesting and present it like this to the subchart users:

```yaml
application:
  subchart:
    key: value
```

This would require a option in `subchart` to map every value to `externalChart`. Sadly i've been unable to find any examples or feature requests for this usecase.

Thanks for your time!
