### ISSUE TITLE
Helm Secrets copying truststores as directory

### ISSUE THREAD

**Issue by mg230181** [helm/helm#11131]
I am trying this
```
apiVersion: v1
kind: Secret
metadata:
  name: stsadmin-keystores
  labels:
    tier: backend
    app: stsadmin-keystores
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{ (.Files.Glob "secrets/*.jks").AsSecrets | indent 2 }}
```
and this works and I get the below on my pod 
ls -lrt wildfly/modules/com/systematic/stsadmin/resources/main/
total 72
--rw-r--r-- 1 root  root  34822 Jul 11 05:49 truststore.jks
-rw-r--r-- 1 root  root   5928 Jul 11 05:49 sts_client.jks
-rw-r--r-- 1 root  root   5923 Jul 11 05:49 sp_client.jks
-rw-r--r-- 1 root  root   5927 Jul 11 05:49 mb_client.jks
-rw-r--r-- 1 root  root   5927 Jul 11 05:49 ch_client.jks

But when I am trying to get the secrets directory path from the values 
```
apiVersion: v1
kind: Secret
metadata:
  name: stsadmin-keystores
  labels:
    tier: backend
    app: stsadmin-keystores
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- $path :=printf "%q/*.jks" .Values.secretSelector }}
{{ (.Files.Glob $path ).AsSecrets | indent 2 }}
```
the .jks files are copied as directories
[jboss@stsadmin-app-5bd55566f8-f5xv7 main]$ ls -lrt
total 4
drwxrwxrwt 2 root  root   40 Jul 11 04:38 mb_client.jks
drwxrwxrwt 2 root  root   40 Jul 11 04:38 sp_client.jks
drwxrwxrwt 2 root  root   40 Jul 11 04:38 sts_client.jks
drwxrwxrwt 2 root  root   40 Jul 11 04:38 truststore.jks
drwxrwxrwt 7 root  root  160 Jul 11 04:38 ch_client.jks

Can somebody help - where I am going wrong. I have spent days trying to fix this

**Comment by mg230181** [comment]
> Hi @mg230181,
> 
> It is very hard to read your issue, I guess the newlines somehow got lost. This happens, if you use the single back-tick syntax instead of three back-ticks syntax: See https://github.github.com/gfm/#fenced-code-blocks
> 
> I also don't quite understand what you mean with "the .jks files are copied as directories", could provide the output of `helm template` for more clarity?
> 
> One guess: I think you have to use `printf "%s/*.jks"` (`%s` not `%q`).

Thank You for responding bacongobbler. I have updated the original post to make the code clearer!
So I have tried using `**printf "%s/*.jks"` (`%s` not `%q`).** , but the issue remains the same. 

Let me try and explain the issue . 
With the original code (first block) , the .jks files are picked up from the secrets directory and copied on the container as **files**. 
However with the updated code (second block) , the .jks files are picked up from the secrets directory and copied on the container as **directories**. 

Hope this will help you in helping me further!

**Comment by phil9909** [comment]
Could you also share the template for the `stsadmin-app` deployment?

I don't need the whole thing, the `spec.template.spec.volumes` and `spec.template.spec.containers.volumeMounts` should be sufficient.

**Comment by mg230181** [comment]
Here you go phil
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: backend
    app: stsadmin-app
  name: stsadmin-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stsadmin-app
  template:
    metadata:
      labels:
        app: stsadmin-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - env:
        - name: AUTH_SERVER_URL
          # value: https://saml.sts-admin.kombitbuildcluster.eu-de.containers.appdomain.cloud/auth
          value: https://saml.sts-admin.{{ .Values.namespace }}.kombitbuildcluster.eu-de.containers.appdomain.cloud/auth
        - name: DISABLE_TRUST_MANAGER
          value: "true"
        - name: ENVIRONMENT
          value: test
        - name: HOST_ENVIRONMENT
          value: DEV
        - name: PRODUCTION_DATA
          value: "false"
        - name: JACOCO_OPTS
          value: "-javaagent:/data/jboss/tools/jacoco/org.jacoco.agent-0.8.2-runtime.jar=address=*,port=36320,destfile=jacoco-it.exec,output=tcpserver"
        #image: docker.kombitbuildcluster.eu-de.containers.appdomain.cloud/repository/kombit/stsadmin/backend:latest
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: app
        ports:
        - containerPort: 8080
        - containerPort: 8787
        - containerPort: 8849
        - containerPort: 9990
        - containerPort: 36320
        volumeMounts:
          - name: secrets
            mountPath: /opt/jboss/wildfly/modules/com/systematic/stsadmin/resources/main/ch_client.jks
            subPath: ch_client.jks
            readOnly: true
          - name: secrets
            mountPath: /opt/jboss/wildfly/modules/com/systematic/stsadmin/resources/main/ch_nsis_client.jks
            subPath: ch_nsis_client.jks
            readOnly: true            
          - name: secrets
            mountPath: /opt/jboss/wildfly/modules/com/systematic/stsadmin/resources/main/mb_client.jks
            subPath: mb_client.jks
            readOnly: true
          - name: secrets
            mountPath: /opt/jboss/wildfly/modules/com/systematic/stsadmin/resources/main/sp_client.jks
            subPath: sp_client.jks
            readOnly: true
          - name: secrets
            mountPath: /opt/jboss/wildfly/modules/com/systematic/stsadmin/resources/main/sts_client.jks
            subPath: sts_client.jks
            readOnly: true
          - name: secrets
            mountPath: /opt/jboss/wildfly/modules/com/systematic/stsadmin/resources/main/sts_nsis_client.jks
            subPath: sts_nsis_client.jks
            readOnly: true
          - name: secrets
            mountPath: /opt/jboss/wildfly/modules/com/systematic/stsadmin/resources/main/truststore.jks
            subPath: truststore.jks
            readOnly: true
        resources:
          requests:
            memory: "1.5Gi"
          limits:
            memory: "3Gi"
      restartPolicy: Always
      volumes:
        - name: secrets
          secret:
            secretName: "stsadmin-keystores"
            items:
              - key: ch_client.jks
                path: ch_client.jks
              - key: mb_client.jks
                path: mb_client.jks
              - key: sp_client.jks
                path: sp_client.jks
              - key: sts_client.jks
                path: sts_client.jks
              - key: truststore.jks
                path: truststore.jks
              - key: ch_nsis_client.jks
                path: ch_nsis_client.jks
              - key: sts_nsis_client.jks
                path: sts_nsis_client.jks
      nodeSelector:
        usage: {{ .Values.nodeSelector }}
```
