### ISSUE TITLE
How does helm hook to keep the rbac release becasue the hook it self depends on the rbac

### ISSUE THREAD

**Issue by kitianFresh** [helm/helm#11151]
I have a helm chart, when i uninstall the helm chart, i use a helm hook to clear something by "post-delete", but the rbac has been deleted when uninstall helm, i want to keep it until the hook is succeed, after the hook succeed, delete the rbac resource

```
nodes is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "nodes" in API group "" at the cluster scope
```

```yaml
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
```

Anyone can help?? @luisdavim
