### ISSUE TITLE
Helm hook itself need rbac to do something

### ISSUE THREAD

**Issue by kitianFresh** [helm/helm#11157]
I have a helm chart, when i uninstall the helm chart, i use a helm hook to clear something by "post-delete", but the rbac has been deleted when uninstall helm

```
nodes is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "nodes" in API group "" at the cluster scope
```

```yaml
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
```
