### ISSUE TITLE
tpl fails when called in a template rendered in the subchart context

### ISSUE THREAD

**Issue by Kytech** [helm/helm#11168]
When calling `tpl` from a template being rendered in the context of a subchart (using `{{ include "common.configmap" .Subcharts.common }}` as detailed in PR #9957, which introduced the `.Subcharts` object to support such a use case), the following error occurs:

```
error calling include: template: prometheus/charts/common/templates/_configmap.yaml:39:8: executing "common.configmap.tpl" at <tpl (toYaml $configs) .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function
```

It appears that a similar issue ([#10082](https://github.com/helm/helm/issues/10082)) occurred before due to `.Template` being removed from the scope at one point in time and it seems that `.Template` has been available in the subchart scope previously based on [this comment in PR #10084](https://github.com/helm/helm/pull/10084#issuecomment-920998122) and the change made in that PR.

I am able to work around this by copying `.Template` to `.Subcharts.common` before rendering the subchart-provided template, which seems to indicate that this is indeed the cause of the problem. I'm thinking that this is a regression since PR [#10084](https://github.com/helm/helm/pull/10084) would have resulted in `.Template` being exposed under `.Subcharts.<name>.Template` as well.

---

Output of `helm version`:
```
version.BuildInfo{Version:"v3.9.1", GitCommit:"a7c043acb5ff905c261cfdc923a35776ba5e66e4", GitTreeState:"clean", GoVersion:"go1.18.4"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:52:41Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: net/http: TLS handshake timeout
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): k8s

**Comment by Kytech** [comment]
@joejulian it looks like this is still a problem. Could we get this re-opened?

**Comment by omry-arpaly** [comment]
I've also run into the same situation, and this is using Helm 3.10.3 and 3.11.0-rc2.
It appears the whole "$" context is missing when running a template positioned in a subchart... (in my case - calling template A from subchart X, when template A is defined in subchart Y).

**Comment by yverbin** [comment]
I have some issue with official grafana chart (https://grafana.github.io/helm-charts ) when use it as dependency

**Comment by omry-arpaly** [comment]
It's still alive and annoying - any of the maintainers care to commnet? 🙏

**Comment by Kytech** [comment]
Would love to hear some updates on this myself. If I had the time available to go back through and try to implement a fix myself, I would gladly put together a fix and a PR, but I've had many other things that have had to take priority over looking into this, especially since I haven't been working on writing helm charts as part of my work for a while now. I've kept my eye on this, but I can't say when, or if, I'll be able to take a deeper look into this any time soon.

**Comment by Lazken** [comment]
Just ran into the same issue. Grafana chart can not be used in a dependency context at this time.

**Comment by Kytech** [comment]
After opening this issue more than a year ago and not receiving any updates, coupled with the fact that I haven't been responsible for helm charts impacted by this bug for a while now and I have too many other demands on my time, I'm not going to request this issue be re-opened. If this issue comes up again for me in the future when I have the time, maybe I'll try to create a fix myself, but if anyone else is encountering this problem, please feel free to just open a new issue and reference this one for further background on the problem. Seems like it did not receive much attention from any maintainers or contributors after initial triage.

**Comment by vio-f** [comment]
This is still happening  - can this issue be re-opened please ?!

**Comment by CrazyByDefault** [comment]
This is a regression and is definitely an issue, can we at least not auto-close this even if people are not able to work on it today? At the least, it prevents duplicates, and at best, it allows for discovery of this bug when others run into this issue.

**Comment by gjenkins8** [comment]
I had not seen this issue until now. I will try and find time to triage next week

**Comment by bebosudo** [comment]
Hello, I just got bitten by this too.. @gjenkins8 did you have any luck debugging this?

For anyone interested in working on this, I created the smallest reproducible I could think of:

```yaml
# ./Chart.yaml
apiVersion: v2
name: parentchart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

# ./values.yaml
subchart:
  port: "8081"

# ./templates/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: parentchart-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: {{ include "subchart.podPortNumber" .Values.subchart }}

# ./charts/subchart/Chart.yaml
apiVersion: v2
name: subchart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

# ./charts/subchart/values.yaml
port: "8080"

# ./charts/subchart/templates/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: subchart-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: {{ include "subchart.podPortNumber" .Values }}

# ./charts/subchart/templates/_helpers.tpl
{{- define "subchart.podPortNumber" -}}
{{ tpl .port . }}
{{- end -}}
```

This is what I get when running it (slightly different error message from when the issue was first opened):

```bash
$ helm template testrelease .
Error: template: parentchart/charts/subchart/templates/pod.yaml:10:24: executing "parentchart/charts/subchart/templates/pod.yaml" at <include "subchart.podPortNumber" .Values>: error calling include: template: parentchart/charts/subchart/templates/_helpers.tpl:2:3: executing "subchart.podPortNumber" at <tpl .port .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: 8081: "BasePath" is not a value
```

Here are my helm and kubectl versions:
```
$ helm version 
version.BuildInfo{Version:"v3.11", GitCommit:"", GitTreeState:"", GoVersion:"go1.20.1"}
$ kubectl version 
Client Version: v1.28.1
```
