### ISSUE TITLE
Ingress Upgrade with Helm Error: error validating "": error validating data:  [ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe):  unknown field "port" in io.k8s.api.core.v1.Probe,  ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe):  unknown field "port" in io.k8s.api.core.v1.Probe,  ValidationError(Deployment.spec.template.spec.containers[0]): 	missing required field "name" in io.k8s.api.core.v1.Container]

### ISSUE THREAD

**Issue by GabySpalding** [helm/helm#11167]
When upgrading ingress it gives error on validating current deployments

Deploy file looks like this

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-tax
  labels:
    helm.sh/chart: tax-0.1.0
    app.kubernetes.io/name: tax
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tax
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tax
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: default
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        name: tax
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
        image: "tax:latest"
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 30
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS
