### ISSUE TITLE
Helm package removes dependencies section from chart.yaml

### ISSUE THREAD

**Issue by skhamkar-tibco** [helm/helm#11170]
Output of `helm version`: v3.8.0

Output of `kubectl version`: v1.21.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): kind

Chart.yaml before packaging chart ->

```
apiVersion: v1
name: tenant
version: 1.44.1
appVersion: 1.44.1
dependencies:
  - name: admin-web-server
    version: "1.44.*"
    repository: alias: cloud
    condition: primaryDeploymentMode.enabled
```
Chart.yaml after packaging chart ->

```
apiVersion: v1
appVersion: 1.44.1
description: TIBCO CIC Cloud Dashboard
maintainers:
- email: dev@tibco.com
  name: Cloud Dev Team
name: tenant
version: 1.44.1

```
In above dependencies section is missing due to which I am not able to disable the sub chart while deploying the parent helm chart even after setting the condition to false.
