### ISSUE TITLE
Subcharts are getting enabled on upgrades when there was no previous subchart values with --reuse-values

### ISSUE THREAD

**Issue by tjg184** [helm/helm#11177]
Start with a release with a parent chart and 1 subchart.

**Chart.yaml**
```
dependencies:
  - name: subchart1
    version: 0.1.0
    condition: subchart1.enabled
```

**Helm Command (Install)**
```helm install release1 ./charts --timeout=15m0s --set subchart1.enabled=true```

**Add a new subchart**
Chart.yaml
```
dependencies:
  - name: subchart1
    version: 0.1.0
    condition: subchart1.enabled
  - name: subchart2
    version: 0.1.0
    condition: subchart2.enabled
```

**Helm Command (Upgrade)**
```
helm upgrade release1 ./charts --reuse-values
```

**Expected**

Only subchart1 would be deployed 

**Actual**

Subchart2 gets deployed as part of this release even though there is a condition for `subchart2`

Output of `helm version`:

```version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-84b4fe6", GitCommit:"c813d094d1e9fa409079753049cfaa9a67524ed2", GitTreeState:"clean", BuildDate:"2022-06-09T18:20:31Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS EKS
