### ISSUE TITLE
Lookup function is not working

### ISSUE THREAD

**Issue by nicotruc** [helm/helm#11187]
Hi, 

It seems there is trouble with the lookup function.

Have the following template :
```yaml
{{- $secret := "foo" -}}
{{- $secret_lookup := lookup "v1" "Secret" .Release.Namespace "test" -}}
{{- if $secret_lookup -}}
{{- $secret := "bar" -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: test
type: Opaque
data:
  KEY: {{ $secret | b64enc | quote }}
```

So **when i install my release, it should have a KEY with value"foo". But when i update as it should lookup for the secret that have to exist in the release namespace, it should set the value to "bar**". So upgrading should change the value to "bar"

Here is CLI output :

```bash
➜ helm upgrade test ./test --atomic --timeout=10m
NAME: test
LAST DEPLOYED: Thu Jul 28 16:10:45 2022
NAMESPACE: ns
STATUS: deployed
REVISION: 1
NOTES:

➜ kubectl get secret test -o jsonpath="{.data.KEY}" | base64 --decode
foo%                                                                                                                                                                       
➜ helm upgrade test ./test --atomic --timeout=10m
Release "test" has been upgraded. Happy Helming!
NAME: test
LAST DEPLOYED: Thu Jul 28 16:11:50 2022
NAMESPACE: ns
STATUS: deployed
REVISION: 2
NOTES:

➜ kubectl get secret test -o jsonpath="{.data.KEY}" | base64 --decode
foo%
```

**When changing my template between install and upgrade to the following** (inverting $secret defalt value with conditional value so when upgrade, as lookup should see a secret, KEY should keep value "foo"), **we then have the secret changing to "bar"**, showing there might be trouble with the lookup function
```yaml
{{- $secret := "bar" -}}
{{- $secret_lookup := lookup "v1" "Secret" .Release.Namespace "test" -}}
{{- if $secret_lookup -}}
{{- $secret := "foo" -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: test
type: Opaque
data:
  KEY: {{ $secret | b64enc | quote }}
```
So my guess from this is that the lookup function does not work as expected.

---

Output of `helm version`: 
```bash
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Output of `kubectl version`:  
```bash
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:57:43Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5+3afdacb", GitCommit:"3c28e7a79b58e78b4c1dc1ab7e5f6c6c2d3aedd3", GitTreeState:"clean", BuildDate:"2022-05-10T16:30:48Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Openshift 4.8.9

**Comment by dcode** [comment]
I posted a question about a similar setup on [StackOverflow](https://stackoverflow.com/questions/73143622/re-using-uuid-in-helm-configmap) yesterday, but using a ConfigMap. 

To have it all in the issue, here's my test case.

```
---
{{- $config := (lookup "v1" "ConfigMap" .Release.Namespace "{{ .Release.Name }}-testcase") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-testcase"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
{{- if $config }}
  TEST_VALUE: {{ $config.data.TEST_VALUE | quote }}
{{- else }}
  TEST_VALUE: {{ uuidv4 | quote }}
{{ end }}
```

When deployed with:

```
helm upgrade --install --namespace test mytest .
```

It continues to generate a new value for each upgrade or diff.
