### ISSUE TITLE
Question: Does the checksum calculation happen on computed files or the template files ? 

### ISSUE THREAD

**Issue by amartya-dev** [helm/helm#11192]
I was looking into restarting deployments when there is an update in config and secret values, I added the annotations of those files as checksums like so:
```yaml
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.general.namespace }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
  labels:
    app: {{ .Values.general.app_name }}
    chart: {{ .Chart.Name }}
```

My question is: when we generate this checksum, does that take the updated file (with the injected values) into consideration ? Or the one with templates (i.e. with {{ Values.something }} as the value ) ?

The deployment (at least in my case) does not get restarted with `helm upgrade` when I inject the values via `set` or through changes in the `values.yaml` file.
