### ISSUE TITLE
How to update Helm Chart values via go programmatically 

### ISSUE THREAD

**Issue by wadexu007** [helm/helm#11209]
Questions: I can successfully update values like replicaCount to 3 via helm go sdk.

But how to update values for below object? Can you help here?
```
  resources:
    limits:
       cpu: 100m
       memory: 128Mi
    requests:
       cpu: 100m
       memory: 128Mi
```

Example code to update values `replicaCount`
```
# test function to update Helm Chart values 
func (h *helmAPI) Update(chartPath, releaseName string, values map[string]interface{}) (*release.Release, error) {
	log.Println("Call Helm Update Chart method")

	chart, err := loader.Load(chartPath)
	if err != nil {
		log.Printf("%+v", err)
	}

       # test update values
        values := map[string]interface{}{
		"replicaCount": 3,
	}

	client := action.NewUpgrade(h.actionConfig)
	res, err := client.Run(releaseName, chart, values)
	if err != nil {
		log.Printf("%+v", err)
	}
	return res, err
}
```
