### ISSUE TITLE
Invalid ordering of `FlowSchema`/`PriorityLevelConfiguration`

### ISSUE THREAD

**Issue by danopia** [helm/helm#11202]
I created a basic helm chart with `PriorityLevelConfiguration` resources and also `FlowSchema` resources that reference the `PriorityLevelConfiguration`s. When I try installing it, helm tries creating the `FlowSchema` first which fails due to the cross-resource dependency:

`Error: INSTALLATION FAILED: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't recognize the priority level configuration "custom-authenticated" used within flow-schema "custom-authenticated-users"`

When running `kubectl apply -f` this is not an issue as long as the `PriorityLevelConfiguration` first in the YAML file. However I cannot find a way to make Helm print one resource before another in the YAML.

Output of `helm version`: 

```
version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.18.4"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:52:41Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12-gke.1700", GitCommit:"6c11aec6ce32cf0d66a2631eed2eb49dd65c89f8", GitTreeState:"clean", BuildDate:"2022-05-13T09:31:25Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

Here's an example of two YAML documents which contain a reference and get outputted in the wrong order:
```yaml
---
apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: PriorityLevelConfiguration
metadata:
  name: custom-fairness-metrics
spec:
  type: Limited
  limited:
    assuredConcurrencyShares: 5
    limitResponse:
      queuing:
        handSize: 6
        queueLengthLimit: 50
        queues: 128
      type: Queue

---
apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: FlowSchema
metadata:
  name: custom-fairness-metrics
spec:
  matchingPrecedence: 2000
  priorityLevelConfiguration:
    name: custom-fairness-metrics
  rules:
  - resourceRules:
    - apiGroups:
      - metrics.k8s.io
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - group:
        name: system:authenticated
      kind: Group
```
