### ISSUE TITLE
Creating a dynamic ConfigMap template

### ISSUE THREAD

**Issue by thepaulmacca** [helm/helm#11213]
I'm not sure of the best approach here, so any help appreciated!

I'm working on some library chart templates, and I need to make my `_configmap.tpl` template a bit more flexible. For example, one app may use a `key:value` pair, but the other may use some `application.properties` (debezium being one of them).

Here is what my current template looks like:

```yaml
{{/*
Renders the ConfigMap objects required by the chart
*/}}
{{- define "tpm-library.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tpm-library.fullname" . }}-configmap
  labels:
    {{- include "tpm-library.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configmap }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end -}}
{{- define "tpm-library.configmap" -}}
{{- include "tpm-library.util.merge" (append . "tpm-library.configmap.tpl") -}}
{{- end -}}
```

One of my hard-coded `ConfigMap` templates looks like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "next-product-debezium.fullname" . }}-configmap
  labels:
    {{- include "next-product-debezium.labels" . | nindent 4 }}
data:
  application.properties: |-
    debezium.sink.type=eventhubs
    debezium.sink.eventhubs.connectionstring=${DEBEZIUM_SINK_EVENTHUBS_CONNECTIONSTRING}
    ...
```

How can I make the `_configmap.tpl` template flexible to allow either configs? I'm a bit new to Go templating, so any help would be great

Thanks
