### ISSUE TITLE
!!int function not working 

### ISSUE THREAD

**Issue by MohamedBenighil** [helm/helm#11227]
Output of `helm version`:
v3.9.3
Output of `kubectl version`:
1.22

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

I have wordpress helm chart, but i get port number as string instead of integer. My values.yml look like : 
```
networkPolicy:
  enabled: true
  ingress:
    enabled: true
  ingressRules:
    customRules:
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: kube-system
            podSelector:
              matchLabels:
                app: ingress-appgw
        ports:
          - protocol: TCP
            port: "{{ .Values.containerPorts.http }}" # here i got '8080' (notice quotes) instead of integer (ie 8080)
```
So when deploy it i get the following error : 
```
Error: INSTALLATION FAILED: NetworkPolicy.extensions "wp-wordpress-ingress" is invalid: [spec.ingress[0].ports[0].port: Invalid value: "
\"8080\"": must contain only alpha-numeric characters (a-z, 0-9), and hyphens (-), spec.ingress[0].ports[0].port: Invalid value: "\"8080\"": must contain at least one letter or number (a-z, 0-9)]
```
I would like know why ?

**Comment by phil9909** [comment]
This should work:

```yaml
networkPolicy:
  enabled: true
  ingress:
    enabled: true
  ingressRules:
    customRules: |
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: kube-system
            podSelector:
              matchLabels:
                app: ingress-appgw
        ports:
          - protocol: TCP
            port: {{ .Values.containerPorts.http }}
```

Notice: the `customRules` is now a string.

I don't know, if this is the optimal solution. Maybe ask the bitnami maintainers as this is specific to their `common.tplvalues.render` function.
