### ISSUE TITLE
`helm test` using `Jobs` cannot show logs

### ISSUE THREAD

**Issue by johnnyhuy** [helm/helm#11236]
We're unable to get the logs of pods when using `helm test` with [Kubernetes Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/job/). Looks like documentation is only describing the use of Pods.

This is a continuation to #9776

`example-chart/templates/tests/job.yaml`

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example
  annotations:
    helm.sh/hook: test
spec:
  backoffLimit: 1
  parallelism: 1
  completions: 1
  template:
    spec:
      containers:
        - name: example
          image: {{ .Values.image | quote }}
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
      restartPolicy: Never
```

Running the test command.

```bash
$ helm test --logs example

Error: unable to get pod logs for example: pods "example" not found
```

It looks like it's trying to get the pod name, but since there's a Kubernetes Job in charge of producing the pod, there's a unique ID at the end of the pod name e.g. `example-6qh95` instead of `example`.

Output of `helm version`:

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}

Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.13-eks-84b4fe6", GitCommit:"e1318dce57b3e319a2e3fecf343677d1c4d4aa75", GitTreeState:"clean", BuildDate:"2022-06-09T18:22:07Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

EKS
