### ISSUE TITLE
Recursive templating with tpl not possible

### ISSUE THREAD

**Issue by vio-f** [helm/helm#11296]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}
```

Output of `kubectl version`:
```
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:47:37Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): bare-metal

Considering the following values:
```
global:
  urls:
    clusterDomain: foo.local
    kafkaUrl: "kafka-0.kafka-headless.somenamespace.svc.{{ clusterDomain }}"

extraEnvVars:
    - name: KAFKA_HOST
      value: "{{ .Values.global.urls.kafkaUrl }}:9092"
```

with the following templates, very common in bitnami charts:
```
# deployment.yaml
spec:
  ..
  template: 
    ..
    spec:
      ..
      containers:
        - name: some_container
          env:
            ..
            {{- if .Values.deployment.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.deployment.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
     
# bitnami/common chart / _tplvalues.tpl
{{/*
Renders a value that contains template.
Usage:
{{ include "common.tplvalues.render" ( dict "value" .Values.path.to.the.Value "context" $) }}
*/}}
{{- define "common.tplvalues.render" -}}
    {{- if typeIs "string" .value }}
        {{- tpl .value .context }}
    {{- else }}
        {{- tpl (.value | toYaml) .context }}
    {{- end }}
{{- end -}}
``` 

What I would expect `KAFKA_HOST` to be rendered to is  
```
- name: KAFKA_HOST
  value: kafka-0.kafka-headless.somenamespace.svc.foo.local
```
but instead I get:
```
- name: KAFKA_HOST
  value: kafka-0.kafka-headless.somenamespace.svc.{{ clusterDomain }}
```

It seems that tpl function is not recursively rendering the input.
