### ISSUE TITLE
Modifiable chart Values

### ISSUE THREAD

**Issue by fisju** [helm/helm#11299]
**Current behaviour**:
Chart values are not immutable and shared between multiple dependencies.

If a chart is used as a dependency multiple times the values can be modified using `merge` `set` and `unset` functions and the modified version is available in the next dependency

Given `Chart.yaml` with local dependencies:
```yaml
apiVersion: v2
name: test
type: application
version: 0.0.1

dependencies:
  - name: subchart
    alias: alias-a
    version: 0.0.1
    repository: file://subcharts/subchart

  - name: subchart
    alias: alias-b
    version: 0.0.1
    repository: file://subcharts/subchart
```

subchart with `values.yaml`

```yaml
sharedValues: {}
```

and code in any template (e.g. `modify.yaml`)
```helm
sharedValues: {{ .Values.sharedValues | toYaml | nindent 2 }}
{{ $_ := merge .Values.sharedValues (dict .Template.Name "value") }}
sharedValuesModified: {{ .Values.sharedValues | toYaml | nindent 2 }}
```

outputs following:
```yaml
# Source: test/charts/alias-a/templates/modify.yaml
sharedValues:
  test/charts/alias-b/templates/modify.yaml: value
sharedValuesModified:
  test/charts/alias-a/templates/modify.yaml: value
  test/charts/alias-b/templates/modify.yaml: value

# Source: test/charts/alias-b/templates/modify.yaml
sharedValues:
  {}
sharedValuesModified:
  test/charts/alias-b/templates/modify.yaml: value
```

using any of `merge` `set` or `unset` it is possible to modify those values. Modifying `.Values` directly does not preserve changes so added new values under `.Values` are discarded but modifying values defined in `values.yaml` preserves the changes for next dependency

**Expected output**: Values are not shared between charts and always read from `values.yaml` file
