### ISSUE TITLE
Wrong scope generated with merge

### ISSUE THREAD

**Issue by JeyJer** [helm/helm#11295]
Hi everyone,

I'm a french student currently working with helm. I noticed a strange behavior :

I use the named templates with a scope. The scope is generated with the merge function and I store it in a variable ; then the variable is reused as scope for the functions defined in my _helpers.tpl file.
The merge unifies the root scope ```$``` with some ```.Values``` defined in a values.yaml file.
Each template file merges differents .Values with the root scope. I expect to get the .Values according to each specific section. But it is not so. It seems that I always get the same scope, even if the merge should generate a different scope by file...

Clearer than my explications above, look at the code below : 

``` yaml
### values.yaml
section1:
  name: section1

section2:
  name: section2
```

``` yaml
### section1.yaml
{{- $scopeSect1 := merge $ .Values.section1 -}}
apiVersion: v1
kind: Deployment
metadata:
  {{- include "test.name" $scopeSect1 | nindent 4 -}}
```

``` yaml
### section2.yaml
{{- $scopeSect2 := merge $ .Values.section2 -}}
apiVersion: v1
kind: Deployment
metadata:
  {{- include "test.name" $scopeSect2 | nindent 4 -}}
```

``` yaml
### _helpers.tpl
{{- define "test.name" -}}
name: {{ .name | quote }}
release: {{ .Release.Name }}
{{- end -}}
```
I get the following result :

``` yaml
---
# Source: helpers/templates/section1/section1.yaml
apiVersion: v1
kind: Deployment
metadata:
    name: "section2" # should be "section1" instead of "section2" !!!
    release: helpers
```

``` yaml
---
# Source: helpers/templates/section2/section2.yaml
apiVersion: v1
kind: Deployment
metadata:
    name: "section2"
    release: helpers
```

I generate the templates with the following command :
```helm template --dry-run -f values.yaml --output-dir dist helpers .```

Is it a bug ? Or may I miss something ?

Output of `helm version`: 
version.BuildInfo{Version:"v3.9.1", GitCommit:"a7c043acb5ff905c261cfdc923a35776ba5e66e4", GitTreeState:"clean", GoVersion:"go1.17.5"}

**Comment by joejulian** [comment]
From the [sprig documentation](http://masterminds.github.io/sprig/dicts.html#merge-mustmerge):

## merge, mustMerge

Merge two or more dictionaries into one, giving precedence to the dest dictionary:

$newdict := merge $dest $source1 $source2

This is a deep merge operation but not a deep copy operation. Nested objects that are merged are the same instance on both dicts. If you want a deep copy along with the merge than use the deepCopy function along with merging. For example,

deepCopy $source | merge $dest

mustMerge will return an error in case of unsuccessful merge.

---

The first merge adds `name` to `$` because it doesn't exist yet. The next merge tries to add its `name`, but is superseded by the `name` that's already in `$`.

To test this, go to https://repeatit.io and fill the input and template fields with these examples:

Input

```yaml
Values:
  foo: bar
section1:
  name: section1
section2:
  name: section2
```

```go
{{ $ := .Values }}
{{ $ }}
{{ merge $ .section1 }}
{{ $ }}
{{ merge $ .section2 }}
{{ $ }}
```

The result shows:
```
map[foo:bar]
map[foo:bar name:section1]
map[foo:bar name:section1]
map[foo:bar name:section1]
map[foo:bar name:section1]
```

You could do what you're trying to do by using mergeOverwrite.
