### ISSUE TITLE
nil pointer evaluating interface {}.controlPlane

### ISSUE THREAD

**Issue by abashir236** [helm/helm#11307]
Output of `helm version`: version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.19"}

Output of `kubectl version`: 1.24.3 Client and 1.24.0 server

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Docker Desktop 4.11.1 (84025)

Doing a helm install and getting the error: `helm-clusterclass	0.1.0	False	False	Helm upgrade failed: template: helm-clusterclass/templates/deployment.yaml:54:52: executing "helm-clusterclass/templates/deployment.yaml" at <.builtin.controlPlane.version>: nil pointer evaluating interface {}.controlPlane`

Below is a snippet of the line that is showing the error along with a few lines before and after. Keep in mind that I am using fluxcd with ClusterAPI as well and when I test without helm then it works fine. Also the error goes away if I test deleting the line in question however it picks another few lines down the yaml and unless I delete these few lines altogether the helm install will not succeed. When it succeeds it does nothing and the workload cluster is never created.

```
- definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/initConfiguration/nodeRegistration/kubeletExtraArgs/cgroup-driver
        value: cgroupfs
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/joinConfiguration/nodeRegistration/kubeletExtraArgs/cgroup-driver
        value: cgroupfs
      selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
    description: |
      Sets the cgroupDriver to cgroupfs if a Kubernetes version < v1.24 is referenced.
      This is required because kind and the node images do not support the default
      systemd cgroupDriver for kubernetes < v1.24.
    enabledIf: '{{ semverCompare "<= v1.23" .builtin.controlPlane.version }}'
    name: cgroupDriver-controlPlane
  - definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/joinConfiguration/nodeRegistration/kubeletExtraArgs/cgroup-driver
        value: cgroupfs
      selector:
        apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
        kind: KubeadmConfigTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - default-worker
    description: |
      Sets the cgroupDriver to cgroupfs if a Kubernetes version < v1.24 is referenced.
      This is required because kind and the node images do not support the default
      systemd cgroupDriver for kubernetes < v1.24.
    enabledIf: '{{ semverCompare "<= v1.23" .builtin.machineDeployment.version }}'
    name: cgroupDriver-machineDeployment



```
