### ISSUE TITLE
Can I create namespace.yaml in helm chart?

### ISSUE THREAD

**Issue by NEM-NE** [helm/helm#11312]
When I work on my istio project, I need to inject sidecar enabled labels in backend namespace, default namespace.

So, I want to create namespace that include custom labels.

Can I Create namespace.yaml in chart's template folder?

like this

```yaml

kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Release.Namespace }}
  labels:
    istio-injection: {{  .Values.istio.injection.enabled  }}

```

if it isn't best practice, why isn't best practice?
