### ISSUE TITLE
Unexpected behavior when using "dependencies.condition"

### ISSUE THREAD

**Issue by ngraf** [helm/helm#11338]
Hi, this is supposed to be a bug report (or at least I am looking for an explanation for my observed behavior).

**Current state**

Given I have this in my `Chart.yaml` file. Two dependencies that have same alias, but with different conditions:

```
dependencies:
  - name: hello-world
    version: 0.1.0
    alias: alias-a
    repository: 'https://helm.sikalabs.io'
    condition: conditionA

  - name: hello-world
    version: 0.2.0
    alias: alias-a
    repository: 'https://helm.sikalabs.io'
    condition: conditionB
```

When I then run `helm install --set conditionA=false --set conditionB=true demo helm --namespace demo`

Then **no deployment** is created at all.

**My expected state**
Then **one deployment** with version `0.2.0` is created, because `conditionB` is `true`.

**Comment**
Maybe helm stops after `conditionA` for same alias `alias-a` was `false`? But I don't understand it. I want to make use of this constellation to deploy my alias in different variants via one `Chart.yaml` file.

----

Output of `helm version`:
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker for Desktop

**Comment by wujunwei** [comment]
https://github.com/helm/helm/blob/a48b87f32af266b7aa55709fbe88ea11d7032829/pkg/chartutil/dependencies.go#L161~L183

**Comment by wujunwei** [comment]
BTW,do we allow to use the same version and name (but different alias ) in dependencies?

**Comment by joejulian** [comment]
GitHub only allows assignment to folks in the org. Feel free to open a PR though. I'm sure your comment, here, is sufficient to let others know you're working on it.

**Comment by joejulian** [comment]
Oh, wait... they changed it. Assigned!

**Comment by wujunwei** [comment]
> Oh, wait... they changed it. Assigned!

Maybe you assigned the wrong one 😂

**Comment by ngraf** [comment]
Yes, you assigned to wrong one. Please don't assign to me. I am not a good developer, just a user of "helm".

**Comment by wujunwei** [comment]
ping @joejulian I have create a PR, PTAL .

**Comment by SaeidAshian** [comment]
I almost have the same situation but did not succeed to handle. My case is to parameterize the Redis (version 6 or 7) installation from the values file.
here is my chart.yaml
```
dependencies:
- name: redis
  version: ~15.7.0
  repository: https://artifacts ... (our own)
  tags:
    - version6
- name: redis
  version: ~17.1.0
  repository: https://artifacts ... (our own)
  tags:
    - version7
```

I have tried with both condition and tags but the problem is, when I do template, it will create both version and set the replica always to the latest redis7, even I did set it false in my values.yaml file
```
redisCache:
  enabled: true 
  tags:
    version6: true
    version7: false
```
Not sure if this is a behaviour of Helm or Reids(as in version 6 create statfulset and in version 7 is application.yaml). 
**Workaround:**
When I do helm dep up will put both redis 6,7 chart into chart folder but if I do manually delete the redis7 in this case will just do template for version 6!
**Conclusion**
Is it a bug or anyone can handle this scenario and give me hint?

**Comment by wujunwei** [comment]
could you whos your file directory structure？ I don't know your `redisCache` in values.yaml mean.

**Comment by wujunwei** [comment]
@SaeidAshian   as your case shows , same name in `dependencies` have bug in current helm version,   it works well in my [PR](https://github.com/helm/helm/pull/11396)

so you can wait maintaners merge it ( please add thumb up to my pr ,let them know you faced the same bug.) or just add alias to solve this problem like below shows.
```yaml
dependencies:
  - name: redis
    version: ~15.7.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - version6
  - name: redis
    alias: redis7
    version: ~17.3.11
    repository: https://charts.bitnami.com/bitnami
    tags:
      - version7
```
