### ISSUE TITLE
Tpl function is not calling included function (defined in .tpl file)

### ISSUE THREAD

**Issue by nicotruc** [helm/helm#11350]
I have to adapt a gitlab runner charts so it is runnable fully on our clusters with all our requirements.
https://gitlab.com/gitlab-org/charts/gitlab-runner/-/tree/main

To do this, i'm building a two remote repository, with one remote referring to gitlab's repository to which i remove the push url so i'm only able to pull information, and another one to our repository. When there will be new version of their runners, i'd like to merge theirs change to my workspace, so i have the least change to do at each iteration and i'm able to quickly provide their version to our clusters.

Their charts provide a .Values.runner.config (https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/main/values.yaml#L317), where i have to put configuration for each runner (as value's setting as been deprecated). This value is then added to theirs configmap as a configuration (https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/main/templates/configmap.yaml#L108), which is then used on runtime to instanciate runners (https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/main/templates/configmap.yaml#L160). 

One of the requirements for my cluster is to provide a pvc to chart, which should be used as a shared cache (because i don't have access to any bucket or similar feature), so on value.yaml of my workspace, i've set the runners.config like the following :

```runners:
  # runner configuration, where the multi line strings is evaluated as
  # template so you can specify helm values inside of it.
  #
  # tpl: https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function
  # runner configuration: https://docs.gitlab.com/runner/configuration/advanced-configuration.html
  config: |
    [[runners]]
      name = {{ .Release.Name }}
      [runners.kubernetes]
        ...
        cachedir = "/shared-cache"
        ...
        [runners.kubernetes.volumes]
          [[runners.kubernetes.volumes.empty_dir]]
            name = "empty-dir-tmp"
            mount_path = "/tmp"
            medium = "Memory"
          ...
          [[runners.kubernetes.volumes.pvc]]
            name = "{{ include "gitlab-runner.fullname" . }}-cache"
            mount_path = "/shared-cache"
```

But when i tried to render, it seems to not work because of using the include function, as when i remove it, templating work, but when i add it, i have this kind of error : 

```➜  gitlab-runner ✗ helm template .
Error: template: gitlab-runner/templates/deployment.yaml:28:32: executing "gitlab-runner/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: gitlab-runner/templates/configmap.yaml:108:27: executing "gitlab-runner/templates/configmap.yaml" at <tpl (toYaml .Values.runners.config) $>: error calling tpl: error during tpl function execution for "\"[[runners]]\\n  name = {{ .Release.Name }}\\n  ...................... name\n  = \\\"{{ include \\\"gitlab-runner.fullname\\\" . }}-cache\\\"\\n        mount_path = \\\"/shared-cache\\\"\\n\"": parse error at (gitlab-runner/templates/deployment.yaml:15): unexpected "\\" in operand

Use --debug flag to render out invalid YAML
```

As it work when replacing the include by a "upper .Release.Name" , **i suspect the tpl function to not call function defined on .tpl files**, which seems a problematic behavior, because in my case, i'm dependant on chart instanciation to know the name of the PVC to use.

I could also make strong update to the configmap so i can make use of old values to the template, but this seems strong update that i'd like to avoid so when updating version, it require the least components to take care of.

Output of `helm version`:
`version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:57:43Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5+3afdacb", GitCommit:"3c28e7a79b58e78b4c1dc1ab7e5f6c6c2d3aedd3", GitTreeState:"clean", BuildDate:"2022-05-10T16:30:48Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Openshift 
`
Client Version: 4.8.9
Kubernetes Version: v1.23.5+3afdacb
`

**Comment by joejulian** [comment]
I pulled the latest chart (d623d12) and put your snippit in a file (adding the missing `runners:` key): `/tmp/v.yaml` then did a `helm template foo . --values=/tmp/v.yaml` and didn't get any errors with helm 3.9.4:

```toml
  config.template.toml:   |
    [[runners]]
      name = foo
      [runners.kubernetes]
        ...
        cachedir = "/shared-cache"
        ...
        [runners.kubernetes.volumes]
          [[runners.kubernetes.volumes.empty_dir]]
            name = "empty-dir-tmp"
            mount_path = "/tmp"
            medium = "Memory"
          ...
          [[runners.kubernetes.volumes.pvc]]
            name = "foo-gitlab-runner-cache"
            mount_path = "/shared-cache"
```

**Comment by joejulian** [comment]
As an aside, I think you want:
```
name = {{ quote .Release.Name }}
```
to satisfy toml formatting requirements.

**Comment by nicotruc** [comment]
The problem is not on variable interpolation, but on chart's defined function calling, like hereby :

`name = "{{ include "gitlab-runner.fullname" . }}-cache"`

This function seems to not be recognized and interpreted by the tpl function.

**Comment by nicotruc** [comment]
Ok, I'll check that with a later version

**Comment by nicotruc** [comment]
With version 3.9.4, i still have the problem with an included function.
Replacing the `{{ include "gitlab-runner.fullname" . }}` with `{{ upper .Release.Name }}` will make it work, and using {{ include "gitlab-runner.fullname" . }} directly in the configmap.yaml work fine, thus make me think there is really problem with included function in tpl call.

You're right about quoting

**Comment by joejulian** [comment]
Here's my attempt at a repro if you can figure out why yours fails but this doesn't, please post the steps:

```sh
git clone https://gitlab.com/gitlab-org/charts/gitlab-runner.git
cat > /tmp/v.yaml <<EOF
runners:
  config: |
    [[runners]]
      name = {{ quote .Release.Name }}
      [runners.kubernetes]
        ...
        cachedir = "/shared-cache"
        ...
        [runners.kubernetes.volumes]
          [[runners.kubernetes.volumes.empty_dir]]
            name = "empty-dir-tmp"
            mount_path = "/tmp"
            medium = "Memory"
          ...
          [[runners.kubernetes.volumes.pvc]]
            name = "{{ include "gitlab-runner.fullname" . }}-cache"
            mount_path = "/shared-cache"
EOF

helm template foo gitlab-runner --values=/tmp/v.yaml | yq -r '.|select(.kind == "ConfigMap")|.data."config.template.toml"'
```
producing
```toml
[[runners]]
  name = "foo"
  [runners.kubernetes]
    ...
    cachedir = "/shared-cache"
    ...
    [runners.kubernetes.volumes]
      [[runners.kubernetes.volumes.empty_dir]]
        name = "empty-dir-tmp"
        mount_path = "/tmp"
        medium = "Memory"
      ...
      [[runners.kubernetes.volumes.pvc]]
        name = "foo-gitlab-runner-cache"
        mount_path = "/shared-cache"
```
