### ISSUE TITLE
Unexpected merging of dictionaries with the name "config"

### ISSUE THREAD

**Issue by klamas1** [helm/helm#11364]
If I create a dict in values.yaml like this
Content values.yaml
```
ingress:
  config:
    className: "nginx"
    annotations: {}
    service:
      suffix: "0"
      port: 80
  main:
    service:
      suffix: "1"
      port: 81
  whitelist:
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
```

And when I try to call to a specific sub-dictionary .Values.ingress.config, I get a dictionary which is the result of the three config+main+whitelist sub-dictionary
Content templates/ingress.yaml
```
{{ .Values.ingress.config | toYaml | printf "\n%s" | fail }}
```

Output helm template and helm upgrade --dry-run
```
Error: execution error at (test/templates/ingress.yaml:1:53):
annotations:
  nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  nginx.ingress.kubernetes.io/ssl-redirect: "false"
  nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
className: nginx
service:
  port: 81
  suffix: '1 '
```

If I rename the sub-dictionary `config` to any other name, example, `config1` and call it `{{ .Values.ingress.config1 | toYaml | printf "\n%s" | fail }}`, then I only get the contents of .Values.ingress.config1 as expected
```
Error: execution error at (test/templates/ingress.yaml:1:53):
annotations: {}
className: nginx
service:
  istioGatewayPort: 80
  port: 80
  suffix: "0"
```

Output of `helm version`:
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:14:10Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"0000000000000000000000000000000000000000", GitTreeState:"archive", BuildDate:"2022-07-15T02:34:37Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Baremetal
