### ISSUE TITLE
Support pull/install helm chart from OCI repository over index.yaml

### ISSUE THREAD

**Issue by ognjen-it** [helm/helm#11361]
Hi all,

First, thank you for being such an excellent problem-solving / developer team. I hope that one day I will be able to join you and contribute.

I just want to introduce you to a problem that could be a bug or not implemented feature :)
I tied to find something about that in Issues / PR / Stackoverflow but I didn't find a solution and maybe you can resolve that.

So, we want to store our application in AWS ECR witch is the OCI base repository. So, only one chart could be in one repository which is totally ok if you have only one microservice. But I the other case, with 50+ microservices you need to have the same number of repository. And it's totally fine, but our clients must add 50+ repositories to install one application... which is not fine 😆 

To fix this issue I found in xyz (10+) page of google search that you can make index.yaml, store somewhere as public yaml file and it would be your "repository" which will redirect the specific chart to the specific repository on AWS ECR. So, our clients should just add one repo (the link to index.yaml) and with the commend `helm search repo <repo name>` they will be able to see and ofc install the application.

So, here is an example how I tried to do it:
export my AWS profile:
`export AWS_PROFILE=ognjen-dev`

Get token for ecr access:
`aws ecr get-login-password --region eu-central-1 | HELM_EXPERIMENTAL_OCI=1 helm registry login --username AWS --password-stdin 123456789012.dkr.ecr.eu-central-1.amazonaws.com`

Package my two microservices:
`helm package my-first-microservice`
`helm package my-second-microservice`

Push them to the AWS ECR
`HELM_EXPERIMENTAL_OCI=1 helm push my-first-microservice-0.0.1.tgz oci://123456789012.dkr.ecr.eu-central-1.amazonaws.com`
`HELM_EXPERIMENTAL_OCI=1 helm push my-second-microservice-0.0.1.tgz oci://123456789012.dkr.ecr.eu-central-1.amazonaws.com`

Create index.yaml:
`HELM_EXPERIMENTAL_OCI=1 helm repo index ./ --url oci://123456789012.dkr.ecr.eu-central-1.amazonaws.com`

Upload this index.yaml file somewhere (in my case it's s3) with public access.
For example it's https://www.example.com/index.yaml (if you curl https://www.example.com/ you will get index.yaml also)
The yaml looks like:
```
apiVersion: v1
entries:
  my-first-microservice:
  - apiVersion: v2
    appVersion: 2.5.0
    created: "2022-09-19T14:06:09.594407+02:00"
    description: A Helm chart for Kubernetes
    digest: e552ef5b127b6df699848977b0bch9d2eccef688872e7944476b1d134527c7c0
    name: my-first-microservice
    type: application
    urls:
    - oci://123456789012.dkr.ecr.eu-central-1.amazonaws.com/my-first-microservice-0.0.1.tgz
    version: 0.0.1
  my-second-microservice:
  - apiVersion: v2
    appVersion: 2.5.0
    created: "2022-09-19T14:06:09.594852+02:00"
    description: A Helm chart for Kubernetes
    digest: 10df3ve9h51f8a19057hd28126b10c75690e79672d1dyb641372d3a10y3b386a3
    name: my-second-microservice
    type: application
    urls:
    - oci://123456789012.dkr.ecr.eu-central-1.amazonaws.com/my-second-microservice-0.0.1.tgz
    version: 0.0.1
generated: "2022-09-19T14:06:09.593513+02:00"
```
Now, I can add the repository:
`helm repo add ognjen https://www.example.com/`

I can search the repository:
`helm search repo ognjen`
Output:
```
NAME                              	CHART VERSION	APP VERSION	DESCRIPTION
ognjen/my-first-microservice         	0.0.1        	2.5.0      	A Helm chart for Kubernetes
ognjen/my-second-microservice	        0.0.1        	2.5.0      	A Helm chart for Kubernetes
```

But I cannot pull/install:
helm -n ognjen-ns install first-ms ognjen/my-first-microservice --debug -v 1

The error is:
```
install.go:178: [debug] Original chart version: ""
Error: INSTALLATION FAILED: object required
helm.go:84: [debug] object required
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.4.0/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1594
```

However, I can install it with the next command:
`helm -n ognjen-ns install first-ms oci://123456789012.dkr.ecr.eu-central-1.amazonaws.com/my-first-microservice`

**So, do you know why I cannot install the chart from OCI repo over index.yaml?**

Output of `helm version`:
```
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}
```
Output of `kubectl version`:
```
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.23.7-eks-4721010
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS
