### ISSUE TITLE
[Bug] Cannot override empty map from a dependency Chart

### ISSUE THREAD

**Issue by dacamposol** [helm/helm#11379]
## Context

1. I have a `Chart A` which has the `Chart B` as dependency.
2. The `Chart B` has the following key on its `values.yaml`.
```yaml
myKey: {}
```
3. Then I try to override this default value in `Chart A` as follows:
```yaml
# Chart.yaml
dependencies:
  - name: chart-b
     alias: chartB
     version: 0.1.0
     repository: ...
---
# values.yaml
chartB:
  myKey:
    hereIAddSomething: "this-is-something-value"
```

### Problem

All the other keys which are not empty-maps are correctly overridden. The key which is set by default to an empty map **isn't** overridden so the templating which depends on it doesn't work.

Example of what I mean:

```yaml
# Template on Chart B
{{- if .Values.myKey }}
{{ toYaml .Values.myKey | indent 4}}
{{- end }}
```

The section which should be written, as `myKey` actually has a value, isn't written.

### Expected result

The section is written, as `myKey` actually has a value.

## Environment

Output of `helm version`: 
```shell
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}
```

## Real-life example

In Argo Workflows, the chart for a ConfigMap resource [depends on a key to exist](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml#L61), but since [it's defaulted to an empty map](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml#L523), it cannot be overridden, as the generated ConfigMaps from `helm template` don't have the `.gcs` entry at all.
