### ISSUE TITLE
Feature Request: Template Function to Parse Kubernetes Resource

### ISSUE THREAD

**Issue by abursavich** [helm/helm#11376]
I frequently find myself needing to parse the values of container resource requests/limits to calculate some other value. For instance, to set the GOMAXPROCS or GOMEMLIMIT env variables. It's possible to cover most of the bases within the limits of go templates, but it ends up being pretty gnarly.

**Comment by joejulian** [comment]
The way I do it is to have the request/limits in the values.yaml and have a named template in _helpers.tpl that calculates those environment variables. Then I just reference that named template in the container env object.

```yaml
env:
  - name: GOMEMLIMIT
    value: {{ include calculated-gomemlimit .}}
```

**Comment by abursavich** [comment]
I still think this would be a nice feature to have, but a little while after creating this issue I went back and was able to compact my templates down quite a bit. I don't think I'd ever actually used a hex float literal before, but it _really_ helped with the SI scales.

```go
{{- define "resource-quantity" -}}
    {{- $value := . -}}
    {{- $scale := 1.0 -}}
    {{- if typeIs "string" . }}
        {{- $suffixes := dict "m" 1e-3 "k" 1e3 "Ki" 0x1p10 "M" 1e6 "Mi" 0x1p20 "G" 1e9 "Gi" 0x1p30 "T" 1e12 "Ti" 0x1p40 "P" 1e15 "Pi" 0x1p50 "E" 1e18 "Ei" 0x1p60 -}}
        {{- range $k, $v := $suffixes -}}
            {{- if hasSuffix $k $ -}}
                {{- $value = trimSuffix $k $ -}}
                {{- $scale = $v -}}
            {{- end -}}
        {{- end -}}
    {{- end -}}
    {{- mulf (float64 $value) $scale -}}
{{- end -}}

{{- define "gomaxprocs" -}}
    {{- with .Values.resources -}}{{- with .limits -}}{{- with .cpu -}}
        {{- include "resource-quantity" . | float64 | ceil | int -}}
    {{- end -}}{{- end -}}{{- end -}}
{{- end }}

{{- define "gomemlimit" -}}
    {{- with .Values.resources -}}{{- with .limits -}}{{- with .memory -}}
        {{- include "resource-quantity" . | float64 | mulf 0.95 | ceil | int -}}
    {{- end -}}{{- end -}}{{- end -}}
{{- end }}
```

```yaml
env:
  {{- with include "gomaxprocs" . }}
  - name: GOMAXPROCS
    value: {{ quote . }}
  {{- end }}
  {{- with include "gomemlimit" . }}
  - name: GOMEMLIMIT
    value: {{ quote . }}
  {{- end }}
```
