### ISSUE TITLE
Question: Can Helm get its file path?

### ISSUE THREAD

**Issue by 0xF4D3C0D3** [helm/helm#11386]
The below is the content of foo/bar/baz.yaml
```yaml
apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
...
  tags:
    - key: IaCSource
      value: {{ $current_file_path }} # instead of foo/bar/baz.yaml
```

Can Helm get its file path like above? I've googled with keywords like working directory or path etc.. but I couldnt find any method..
