### ISSUE TITLE
Helm indent introduced extra whitespace on previous row

### ISSUE THREAD

**Issue by underside** [helm/helm#11405]
Helm indent function insert trailing whitespaces on previously line. 

Output of `helm version`:
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}

Output of `kubectl version`:
Client Version: v1.24.4
Kustomize Version: v4.5.4

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Local tests with helm template .

I have:
- statefulset.yaml helm template: (it's just part of it if you need full template, I can add it)

```
resources:
            limits:
              memory: {{ if .Values.tg.NOT_PROD }}350{{ else }}800{{ end }}
            requests:
              cpu: 100m
              memory: {{ if .Values.tg.NOT_PROD }}350{{ else }}800{{ end }}
          volumeMounts: {{- include "tg.volumeMounts" $ | indent 12 }}
```

- _helpers.yaml defintions:
```
{{ define "tg.volumeMounts" }}
{{- range $v := .Values.tg.statefulset.volumes }}
- name: {{ $v.name }}
  mountPath: {{ $v.mountPath }}
{{- if $v.readOnly }}
  readOnly: true
{{- end -}}
{{- if $v.subPath }}
  subPath: {{ $v.subPath }}
{{- end -}}
{{- end -}}
{{ end }}

```

- values.yaml:
```
    volumes:
      - name: app-secret
        mountPath: /secret
        resourceType: secret
        resourceName: some-secret
      - name: configs
        mountPath: /usr/local/app/etc/logconfig.xml
        readOnly: true
        subPath: logconfig.xml
        resourceType: configMap
        resourceName: app-config
      - name: configs
        mountPath: /usr/local/app/etc/application.yml
        readOnly: true
        subPath: application.xml
        resourceType: configMap
        resourceName: app-config
        items:
          - key: application.yml
            path: application.yml
          - key: logback.xml
            path: logback.xml

```

When I template it works, but add trailing whitespaces on previous line for example (trailing whitespaces after "volumeMounts: "):

```
          volumeMounts:            
            - name: app-secret
              mountPath: /secret
```
The quantity of this trailing whitespaces exactly equal to the "indent " value. So if I set "indent 10" it will be 10 trailing whitespaces, the same story if I set 12 e.t.c.

I have found some similar issue for other project on github, maybe it will help 

https://github.com/Alluxio/alluxio/issues/10724
