### ISSUE TITLE
cannot 

### ISSUE THREAD

**Issue by nessa829** [helm/helm#11437]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}
```

Output of `kubectl version`:
```Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-6d3986b", GitCommit:"8877a3e28d597e1184c15e4b5d543d5dc36b083b", GitTreeState:"clean", BuildDate:"2022-07-20T22:05:32Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS EKS 

=============

Our helm chart structure is like : 
**├── service-a**
│   ├── Chart.yaml
│   ├── templates
│   │   ├── NOTES.txt
│   │   ├── _helpers.tpl
│   │   ├── deployment.yaml
│   │   ├── hpa.yaml
│   │   ├── ingress.yaml
│   │   ├── namespace.yaml
│   │   ├── service.yaml
│   │   └── serviceaccount.yaml
│   ├── values-alpha.yaml
│   └── values-production.yaml
**├── service-b**
│   ├── Chart.yaml
│   ├── templates
│   │   ├── NOTES.txt
│   │   ├── _helpers.tpl
│   │   ├── deployment.yaml
│   │   ├── hpa.yaml
│   │   ├── ingress.yaml
│   │   ├── namespace.yaml
│   │   ├── service.yaml
│   │   ├── serviceaccount.yaml
│   ├── values-alpha.yaml
│   └── values-production.yaml

Also, we are using a single ALB with AWS ingress controller as an endpoint and we defined ACM with ingress annotation.
Because many services are sharing a single ALB, I am worrying if there are mismatched ACM info. 
For example, in service-a 
```
alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:356765580539:certificate/someid"
```

and in service-b 
```
alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:356765580539:certificate/anotherid"
```

Therefore i am trying to implement something like cross chart values. 
First i tried subchart and global values, but it did not work as i desired, becasue it seems that you cannot use custom values file with subcharts. Also, we use argocd application to install helm chart, and installing form subchart does not import global values from parent chart.. 

Is there any good solution?

**Comment by joejulian** [comment]
Two normal ways of handling this:

The most common I've seen is to use a wrapper chart that sets that value for each of its subcharts (or use [global](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values) and configure your subcharts to override the local value with the global value if it exists).

The other way would be to use helm's post-renderer to do some substitution using kustomize.

**Comment by websi96** [comment]
here is what I did to share values between subcharts:

Assume this mongodb dependencies in my Parent Chart.yaml
```yaml
#Chart.yaml in parent chart

dependencies:
  - name: mongodb
    version: "13.4.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
    import-values:
    - child: auth
      parent: global.mongodb.auth
  ```
 
  Here I pass the auth values from the mongodb subchart to the global values of my parent chart.
  Then I can set the auth settings in values.yaml of the parent chart like so:
  
 ```yaml
#values.yaml in parent chart
 
mongodb:
  enabled: true
  auth:
    usernames:
    - user_1
    - user_2
    passwords:
    - user_1_pw
    - user_2_pw
    databases:
    - user_1_db
    - user_2_db
  ```
  
  In any other Sub Chart I can then access the users like os:
  
  ```yaml
 #any template.yaml in subchart
 
{{- with .Values.global.mongodb.auth -}}

  {{- $pws := .passwords -}}
  {{- $dbs := .databases -}}
  {{- $users := .usernames }}

{{- end -}}
  ```
  
My only problem is, that this only works with objects like auth and not the users array directly.
If I would reference an array I get this:
  ```
dependencies.go:247: Warning: ImportValues missing table from chart mongodb: "auth.usernames" is not a table
  ```
  
  BTW: you should change the name of this issue..
