### ISSUE TITLE
Missing RBAC resources when templating using --output-dir option 

### ISSUE THREAD

**Issue by ethcero** [helm/helm#11481]
RBAC resources are not rendered in a very specific case when they reside in the same template file that another resource with hook annotations and we use `--output-dir` option.

Data to reproduce:

**templates/dummy.yaml**
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummy-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dummy-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dummy-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dummy-role
subjects:
- kind: ServiceAccount
  name: dummy-sa
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dummy-cm
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  dummy_data: dummy_data
```

Run helm template command:
```
helm template helm-dummy-chart --output-dir ./tmp
```

Rendered file:
```
---
# Source: helm/templates/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dummy-cm
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  dummy_data: dummy_data
```

If I remove the `"helm.sh/hook": post-install` from annotations, the file is rendered correctly and all RBAC resources are present.

Output of `helm version`:
```
➜ helm version
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.19.2"}
```
