### ISSUE TITLE
release secret size optimization

### ISSUE THREAD

**Issue by elops-od** [helm/helm#11493]
hi
we started to get an error `Too long: must have at most 1048576 bytes` when tried to install victoria-metrics-k8s-stack.
investigation shows that if we install victoria-metrics-k8s-stack chart, decode **sh.helm.release.v1** secret has size 6.56MB(encode secret size:  840924 bytes) and structure
![image](https://user-images.githubusercontent.com/75570519/199446043-ae058a4d-b174-4ad3-b626-b9d75e7ee67f.png)

but if we add victoria-metrics-k8s-stack to dependencies of empty chart 
```
apiVersion: v2
description: A Helm chart for Kubernetes
name: emptyChart
version: 0.1.0-SNAPSHOT
dependencies:
  - name: victoria-metrics-k8s-stack
    alias: victoria-metrics-k8s-stack
    version: ~0.0.0-0
    repository: https://victoriametrics.github.io/helm-charts/
```
decode **sh.helm.release.v1** secret has size 2.94MB(encode secret size:  211660 bytes) and structure 
![image](https://user-images.githubusercontent.com/75570519/199447655-8c04afad-439e-40ef-9e1d-036ac6c0f4df.png)

the difference in size between the first and second options for installing is 2 times.
As far as I understand, this is because in the second option everything is stored in the manifest field and this gives significant savings.
is it possible to optimize the first option so that all templates are stored in the manifest field (mean combine everything that is in the chart field with the manifest field)

Output of `helm version`:
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
1.21.10-gke.2000
