### ISSUE TITLE
Aliased dependencies cannot build. Neither render.

### ISSUE THREAD

**Issue by stavros-k** [helm/helm#11511]
Output of `helm version`:
`version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`k3s`

Consider this:
`Chart.yaml`
```yaml
apiVersion: v2
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.7.7
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.7.7
    alias: test
```

`values.yaml`
```yaml
image:
  repository: repo1
  tag: v1
  pullPolicy: IfNotPresent

test:
  image:
    repository: repo2
    tag: v1
    pullPolicy: IfNotPresent
```

After `helm dependency build .`
```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "truecharts" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading common from repo https://library-charts.truecharts.org
Already downloaded common from repo https://library-charts.truecharts.org
Deleting outdated charts
```
`/charts` contains only 1 file `common-10.7.7.tgz`

`helm template .` 
Renders only the parent chart, Nothing of the subchart.

---

Tried to with a diff version on charts:
`Chart.yaml`
```yaml
apiVersion: v2
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.7.7
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.7.5
    alias: test
```

Same `values.yaml`

After `helm dependency build .` I now have 2 files in `/charts` (`common-10.7.7.tgz` and `common-10.7.5.tgz`)

But still `helm template .` Does not render the  subchart at all..
