### ISSUE TITLE
Allow import-values to accept arrays, single and whole chart values!

### ISSUE THREAD

**Issue by websi96** [helm/helm#11515]
Hi I am currently struggeling with importing values from subcharts.

Here is what I did to share values between subcharts:

Assume this mongodb dependencies in my Parent Chart.yaml
```yaml
#Chart.yaml in parent chart

dependencies:
  - name: mongodb
    version: "13.4.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
    import-values:
    - child: auth
      parent: global.mongodb.auth
  ```
 
  Here I pass the auth values from the mongodb subchart to the global values of my parent chart.
  If I then add auth settings for the subchart in values.yaml of the parent chart like so:
  
 ```yaml
#values.yaml in parent chart
 
mongodb:
  enabled: true
  auth:
    usernames:
    - user_1
    - user_2
    passwords:
    - user_1_pw
    - user_2_pw
    databases:
    - user_1_db
    - user_2_db
  ```
  
  I can use the global values in any other Sub Chart like so:
  
  ```yaml
 #any template.yaml in subchart
 
{{- with .Values.global.mongodb.auth -}}

  {{- $pws := .passwords -}}
  {{- $dbs := .databases -}}
  {{- $users := .usernames }}

{{- end -}}
  ```
  
My only problem is, that this only works with objects like auth and not the usernames array directly.
If I would reference an array I get this:
  ```
dependencies.go:247: Warning: ImportValues missing table from chart mongodb: "usernames" is not a table
  ```
  
How would we also allow arrays here?

I already found these issues and pull requests:
- https://github.com/helm/helm/issues/2746
- https://github.com/helm/helm/issues/9817
- https://github.com/helm/helm/pull/11162
- https://github.com/helm/helm/pull/10515
- https://github.com/helm/helm/pull/9957

_Originally posted by @websi96 in https://github.com/helm/helm/issues/10515#issuecomment-1304861751_
