### ISSUE TITLE
Printf receives wrong data type from YAML parser?

### ISSUE THREAD

**Issue by emike922** [helm/helm#11522]
Given the following template directive:

```yaml
{{ printf "%d" .Values.port | quote }}
```

Helm renders either `"80"` when supplied with `--set port=80` or `"%!d(float64=80)"` when supplied with `port: 80` via values.yaml

Output of `helm version`:
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}

**Comment by joejulian** [comment]
Try
```
{{ printf "%s" .Values.port | int | quote }}
```

**Comment by emike922** [comment]
Well, unfortunately that doesn't solve my problem as in actuality I am passing multiple args to printf, something like "%s %s:%d". I just wanted to share a minimalistic way to reproduce.

**Comment by yxxhero** [comment]
@emike922 Please show your whole example.

**Comment by emike922** [comment]
@yxxhero, I shared the minimal steps you need to reproduce the behavior, now whether I add a few %s before or after %d should not make any difference whatsoever!?

But to comply with your request, you can assume I have a situation as illustrated below, and a consumer that depends on the exact format specified in printf:

values.yaml
```yaml
foo: abc
bar: def
port: 80
```

templates/pod.yaml
```yaml
kind: Pod
spec:
  containers:
    - args:
      - {{ printf "%s %s %d" .Values.foo .Values.bar .Values.port | quote }}
```

**Comment by yxxhero** [comment]
@emike922 and the render result and expected result?

**Comment by emike922** [comment]
```shell
$ helm template . -s templates/pod.yaml 
---
# Source: chart/templates/pod.yaml
kind: Pod
spec:
  containers:
    - args:
      - "abc def %!d(float64=80)"
$ helm template . -s templates/pod.yaml --set port=80
---
# Source: chart/templates/pod.yaml
kind: Pod
spec:
  containers:
    - args:
      - "abc def 80"
```

I am expecting to get the latter, `"abc def 80"`, not `"abc def %!d(float64=80)"`

**Comment by yxxhero** [comment]
@joejulian try:
```
pod: "80"
```

**Comment by yxxhero** [comment]
@joejulian Or
```
kind: Pod
spec:
  containers:
    - args:
      - {{ printf "%s %s %d" .Values.foo .Values.bar (.Values.port | int) | quote }}
```
