### ISSUE TITLE
Feature: Add an option to add annotations and labels to the manifests generated via helm template

### ISSUE THREAD

**Issue by markussiebert** [helm/helm#11556]
UseCase: 

When you setup Talos k8s it's possible to add manifests on node bootstrap time - before kubernetis is really running and the nodes are ready. But you can only apply manifests, not helm charts. In my special case, it's the cilium cni.

https://www.talos.dev/v1.2/kubernetes-guides/network/deploying-cilium/#method-3-helm-manifests-hosted-install

The documentation generates the manifest via helm template... so far so good!

Afterwards, I would like to manage the cni via the official helm chart, but I can't without manually label and annotate all resources.

It would be nice, if helm template could include all resources and labels, that it would append to resources if it installs/upgrades them. So it would be much easier to manage them later on with your gitops tool of your choice.

As a workaround (if someone else has a similar problem) you can use kustomize afterwards with a kustomization like this:
```yaml
resources:
- cilium-manifest.yaml
patchesJson6902:
- target: 
    name: ".*"
  patch: |-
    - op: add
      path: /metadata/labels
      value:
        "app.kubernetes.io/managed-by": "Helm"
    - op: add
      path: /metadata/annotations
      value:
        "meta.helm.sh/release-name": "cilium"
        "meta.helm.sh/release-namespace": "kube-system"
```
Works - but it would be great, if the helm cli could handle this directly.
