### ISSUE TITLE
Dependency charts with same library chart, but different version, have unexpected behavior

### ISSUE THREAD

**Issue by jlubawy** [helm/helm#11561]
Output of `helm version`: v3.10.2 (macOS/arm64), I also went back as far as v3.8 and it is still an issue
Output of `kubectl version`: N/A
Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

I have a collection of charts with the following dependency structure:
- `issue-x-apps` (application chart)
  - `issue-x-app-1` (application chart)
    - `issue-x-lib` (library chart, version 1.0.0)
  - `issue-x-app-2` (application chart)
    - `issue-x-lib` (library chart, version 2.0.0)

For demo purposes `issue-x-lib` looks like this:

### Version 1.0.0 (label is `issue-x-lib-1`)

```yaml
{{- define "issue-x.serviceAccount" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: issue-x
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: "issue-x-lib-1"
{{- end -}}
```

### Version 2.0.0 (label is `issue-x-lib-2`)

```yaml
{{- define "issue-x.serviceAccount" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: issue-x
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: "issue-x-lib-2"
{{- end -}}
```

### issue-x-app-1 and issue-x-app-2

I then have two application charts that instantiate the template provided by the library chart, one app uses 1.0.0 of the chart, the other uses 2.0.0:

```
{{- include "issue-x.serviceAccount" . -}}
```

### issue-x-apps

These are then combined into a single parent application chart:

```yaml
apiVersion: v2
name: issue-x-apps
type: application
version: 1.0.0
dependencies:
  - condition: issue-x-app-1.enabled
    name: issue-x-app-1
    repository: file://../issue-x-app-1
    version: 1.0.0
  - condition: issue-x-app-2.enabled
    name: issue-x-app-2
    repository: file://../issue-x-app-2
    version: 2.0.0
```

The expected output of `helm template issue-x-apps .` is:

```yaml
---
# Source: issue-x-apps/charts/issue-x-app-1/templates/serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: issue-x
  namespace: "default"
  labels:
    name: "issue-x-lib-1"
---
# Source: issue-x-apps/charts/issue-x-app-2/templates/serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: issue-x
  namespace: "default"
  labels:
    name: "issue-x-lib-2"
```

But it looks like version `2.0.0` of `issue-x-lib` is not being used, it uses `1.0.0` instead (actual output, notice second label should be `issue-x-lib-2`):

```yaml
---
# Source: issue-x-apps/charts/issue-x-app-1/templates/serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: issue-x
  namespace: "default"
  labels:
    name: "issue-x-lib-1"
---
# Source: issue-x-apps/charts/issue-x-app-2/templates/serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: issue-x
  namespace: "default"
  labels:
    name: "issue-x-lib-1"
```

I have a branch that adds this as a unit test here: https://github.com/jlubawy/helm/compare/main...jlubawy:helm:jlubawy/issue-x
