### ISSUE TITLE
Helm Install Failed: cannot unmarshal number into Go struct field XXX of type string

### ISSUE THREAD

**Issue by JiayangZhou** [helm/helm#11562]
My helm install on a helm chart has been working but out of a blue the helm install (command used: helm install release_name .)stops working and complains the error as such:
`Error: INSTALLATION FAILED: CronJob in version "v1" cannot be handled as a CronJob: json: cannot unmarshal number into Go struct field EnvVar.spec.jobTemplate.spec.template.spec.containers.env.value of type string`

Under the corn job template, the env was set up as such:

``` 
 ...
 env:
    - name: MAX_DAYS
      value: {{ .Values.test }}
```
and the in value files:
`
test: "14"
` 
simple as it is. but with this setup, helm install will fail and complain the error above.

However, if I do something like this:

``` 
 ...
 env:
    - name: MAX_DAYS
      value: "14"
```
helm install will work. 

It says in doc https://helm.sh/docs/chart_best_practices/values/#make-types-clear that we should quota all string type as best practice but I quoted 14 in two scenarios above, specifilly in value files but in that case it is not working, which is hard for me to understand.

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}
```
Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"windows/amd64"}  
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"c23d69c673335261c7029c60c877d81c9bfef2a8", GitTreeState:"clean", BuildDate:"2022-11-09T17:12:37Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}    
WARNING: version difference between client (1.22) and server (1.24) exceeds the supported minor version skew of +/-1        
```

**Comment by JiayangZhou** [comment]
```
 ...
 env:
    - name: MAX_DAYS
      value: {{ .Values.test | quote}}
```

this solved it

**Comment by yxxhero** [comment]
@JiayangZhou Thanks for your issue and answer.

**Comment by JiayangZhou** [comment]
Thank you, however, is helm's behavior in the first scenario expected though?
I would naturelly think if the value of `test` is quoted in value files, the below should just work, not requiring the `value: {{ .Values.test | quote}}`

```
...
 env:
    - name: MAX_DAYS
      value: {{ .Values.test }}
```
