### ISSUE TITLE
Not able to dynamically override map

### ISSUE THREAD

**Issue by juan-vg** [helm/helm#11563]
Output of `helm version`: 3.x

## Context

When using a 3rd party Chart there's no way (or at least I've not been able to find it) to override all attributes. Default and provided values are merged. If there's a need to replace all the default map-attributes with the new provided ones, it can't done in a dynamic way. It's true each attribute can be nulled if they're known, but it would be better to have a way to override them all independently of their number and names.

default values.yaml
```yaml
containerPorts:
  http: 80
  https: 443
  stat: 1024
```

provided values.yaml
```yaml
containerPorts:
  db: 5432
```

computed Values
```yaml
containerPorts:
  http: 80
  https: 443
  stat: 1024
  db: 5432
```

## Workaround

```yaml
containerPorts:
  http: null
  https: null
  stat: null
  db: 5432
```

This requires knowing the default attributes in order to null them. From my point of view this should be improved.

## Desirable solution

default values.yaml
```yaml
containerPorts:
  http: 80
  https: 443
  stat: 1024
```

provided values.yaml
```yaml
# As an example: first we remove all the content of the variable
containerPorts: {}
# Then add desired attributes
containerPorts:
  db: 5432
```

computed Values
```yaml
containerPorts:
  db: 5432
```

Of course this doesn't make sense from the values' processing point of view, but I believe it illustrates what I mean.
