### ISSUE TITLE
Multiple Values files - keys are overwritten not merged

### ISSUE THREAD

**Issue by cjabrantes** [helm/helm#11581]
Hi,

helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}

I was not able to find it in the documentation, if its the expected behaviour or may be a bug when using multiple values files, i was expecting that the values would be merged with the ones with lower prio or overwrite if already exists.

If i have values.yaml:

```
access:
  authtype: XXXX
  config: YYY
```

and a secrets.yaml:
```
access:
  user: user1
  pass: pass1
```

When i use helm .... -f values.yaml -f secrets.yaml --dry-run  i can see in USER-SUPPLIED VALUES all the values (what i expected):

```
access:
  user: user1
  pass: pass1
  authtype: XXXX
  config: YYY
```

But if i have something like  values.yaml:

```
servers:
   - name: A
      authtype: XXXX
      config: YYY
   - name: B
      authtype: XXXX
      config: YYY
```

and a secrets.yaml:
```
servers:
   - name: A
      user: user
      pass: pass
   - name: B
      user: user
      pass: pass
```

When i use helm ....  -f values.yaml -f secrets.yaml --dry-run i can only see in USER-SUPPLIED VALUES only:

```
servers:
   - name: A
      user: user
      pass: pass
   - name: B
      user: user
      pass: pass
```

Seems that the keys from the first values file were overwritten, is this the expected behaviour (by design)?

Thanks,
