### ISSUE TITLE
helm upgrade is using an unexpected value for namespace

### ISSUE THREAD

**Issue by veleek** [helm/helm#11583]
I'm running a helm upgrade step in Github Actions that has previously deployed.  The existing deployment uses the `default` namespace.  

I'm not passing in a namespace, and I can't identify anything anywhere that is passing in a namespace, but it seems like an implicit namespace of `github-actions-runners-github-com` is getting set SOMEWHERE, but I can't for the life of me figure out where it's coming from.  

What are the sources that helm uses to determine which namespace to use?

-----

`kubectl config get-contexts` returns:
```
CURRENT   NAME        CLUSTER     AUTHINFO                    NAMESPACE
*         my-cluster  my-cluster  my-cluster
```

*Action YAML snippet*
```yaml
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.5.3'

      - name: Deploy ingress
        shell: bash
        run: |
          helm upgrade ingress-nginx ./build/ingress-nginx --values=./build/ingress-nginx/values.yaml --install --timeout 15m
```

*Output from Github Actions*
```plain
helm upgrade ingress-nginx ./build/ingress-nginx --values=./build/ingress-nginx/values.yaml --install --timeout 15m
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /runner/_work/my-org/my-org/gha-creds-bfc6b7da324228f9.json
    GOOGLE_APPLICATION_CREDENTIALS: /runner/_work/my-org/my-org/gha-creds-bfc6b7da324228f9.json
    GOOGLE_GHA_CREDS_PATH: /runner/_work/my-org/my-org/gha-creds-bfc6b7da324228f9.json
    CLOUDSDK_CORE_PROJECT: my-org-prd
    CLOUDSDK_PROJECT: my-org-prd
    GCLOUD_PROJECT: my-org-prd
    GCP_PROJECT: my-org-prd
    GOOGLE_CLOUD_PROJECT: my-org-prd
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    KUBECONFIG: /runner/_work/my-org/my-org/d00517c36b9e3294f66c6183
    KUBE_CONFIG_PATH: /runner/_work/my-org/my-org/d00517c36b9e3294f66c6183
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /runner/_work/my-org/my-org/d00517c36b9e3294f66c6183
Release "ingress-nginx" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "ingress-nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "github-actions-runners-github-com": current value is "default"
```

Output of `helm version`: 3.5.3

Output of `kubectl version`: `v1.25.4`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by hickeyma** [comment]
It would use the default or current namespace of the cluster.

**Comment by gjenkins8** [comment]
> Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "ingress-nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "github-actions-runners-github-com": current value is "default"

If you `kubectl describe clusterrole ingress-nginx`, I suspect you will see this role already exists in `github-actions-runners-github-com` namespace, and has the annotation `meta.helm.sh/release-namespace=github-actions-runners-github-com` . 

Thus helm is not able to install your chart, as it also wants to install this same cluster role (namespace is not relevant for cluster-wide resources)

(You can see in the error, helm is trying to use the `default` namespace as the default for resources for your chart. But that isn't the problem here)

**Comment by veleek** [comment]
@hickeyma - I included my bug report the output of `kubectl config get-contexts` where it shows that there is no default namespace defined for the cluster so it _should_ be defaulting to `default`.

@gjenkins8 - You're reading the error backwards.  
> ```
> key "meta.helm.sh/release-namespace" must equal "github-actions-runners-github-com": current value is "default"`
>                                                                                          ^-----------------^
> ```
It says that the _existing_ clusterrole is `default` but helm is running using a namespace `github-actions-runners-github-com` and therefore it doesn't have permission to modify the one in the `default` namespace because it doesn't own it.  
I have confirm this by looking at the existing cluster role and verifying that it had the namespace `default`.  I was also able to workaround the issue by passing `--namespace default` as an extra parameter to the `helm upgrade` command but I shouldn't need to pass it (and I would prefer not to update the dozen other workflows that do this).  I'm trying to figure out why helm thinks the namespace is `github-actions-runners-github-com'

**Comment by joejulian** [comment]
@veleek No, @gjenkins8 is correct.
`key "meta.helm.sh/release-namespace" must equal "github-actions-runners-github-com"`
Telling you how to fix it.


`current value is "default"`
telling you what's wrong with the resource you're passing to the API.

**Comment by veleek** [comment]
@joejulian - That is incorrect.  I confirmed that the current value in the cluster had the namespace of default.  I then re-ran the helm command and I passed `--namespace github-actions-runners-github-com` (so the namespace I was targeting would "match" the actual namespace) and it continued to fail in the same way.

As I mentioned, I was able to workaround the issue by passing `--namespace default` and it succeeded.  It will only succeed if the namespace you are targeting (e.g. the `--namespace` parameter) matches the namespace of the object in the cluster.  

To reword the error:
```
key "meta.helm.sh/release-namespace" must equal "github-actions-runners-github-com"

The key "meta.helm.sh/release-namespace" on the existing object must equal "github-actions-runners-github-com".  The current value of the "release-namespace" property on the existing object is "default" and since helm is targeting the namespace "github-actions-runners-github-com" it does not own the existing object so we will no overwrite it.
```

**Comment by veleek** [comment]
@joejulian - That is incorrect.  I confirmed that the current value in the cluster had the namespace of default.  I then re-ran the helm command and I passed `--namespace github-actions-runners-github-com` (so the namespace I was targeting would "match" the actual namespace) and it continued to fail in the same way.

As I mentioned, I was able to workaround the issue by passing `--namespace default` and it succeeded.  It will only succeed if the namespace you are targeting (e.g. the `--namespace` parameter) matches the namespace of the object in the cluster.  

To reword the error:
```
key "meta.helm.sh/release-namespace" must equal "github-actions-runners-github-com"

The key "meta.helm.sh/release-namespace" on the existing o must equal "github-actions-runners-github-com"
```

**Comment by veleek** [comment]
You can confirm this by looking at the source here: https://github.dev/helm/helm/blob/3636f6824757ff734cb265b8770efe48c1fb3737/pkg/action/validate.go#L86

`annos` is the annotations of the existing object (see line 74), and `releaseNamespace` is the namespace helm is deploying to.  The `requireValue` function uses `releaseNamespace` as the second parameter for the error message, the third parameter `default` is the actual value that it gets from the annos.

**Comment by joejulian** [comment]
I'm not guessing:
https://github.com/helm/helm/blob/3636f6824757ff734cb265b8770efe48c1fb3737/pkg/action/validate.go#L107

**Comment by veleek** [comment]
@joejulian Okay, I think I see the misunderstanding between us.  

You said:
> `key "meta.helm.sh/release-namespace" must equal "github-actions-runners-github-com"`
> Telling you how to fix it.

Yes, I agree that this is telling me how to fix it.  My problem is: "how is the namespace getting set to `github-actions-runners-github-com`?".  I'm not passing in a `--namespace` parameter, and I don't have a `HELM_NAMESPACE` environment variable, so helm is picking up its namespace configuration from somewhere else, and I would like to find out where that is so that I can go fix it.

I ran the following pipeline

```
jobs:
  test-helm:
    runs-on: [ self-hosted, linux-runner ]
    steps:

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.5.3'

      - run: |
          echo "HELM_ENVIRONMENT=$HELM_ENVIRONMENT"
          echo "========"
          helm env
```

And the output looks like this
```
HELM_ENVIRONMENT=
========
HELM_BIN="helm"
HELM_CACHE_HOME="/home/runner/.cache/helm"
HELM_CONFIG_HOME="/home/runner/.config/helm"
HELM_DATA_HOME="/home/runner/.local/share/helm"
HELM_DEBUG="false"
HELM_KUBEAPISERVER=""
HELM_KUBEASGROUPS=""
HELM_KUBEASUSER=""
HELM_KUBECAFILE=""
HELM_KUBECONTEXT=""
HELM_KUBETOKEN=""
HELM_MAX_HISTORY="10"
HELM_NAMESPACE="github-actions-runners-github-com"
HELM_PLUGINS="/home/runner/.local/share/helm/plugins"
HELM_REGISTRY_CONFIG="/home/runner/.config/helm/registry.json"
HELM_REPOSITORY_CACHE="/home/runner/.cache/helm/repository"
HELM_REPOSITORY_CONFIG="/home/runner/.config/helm/repositories.yaml"
```

Where did `HELM_NAMESPACE` come from?

**Comment by veleek** [comment]
_Note: As you can see in the GithubActions job above, I'm using a `self-hosted` Github Actions runner.  I know that this is impacting how helm runs, and I just want to reiterate that my question is that I don't know where the namespace value helm is using is coming from and I would like to figure it out._

**Comment by veleek** [comment]
No, I have no github-actions-runners-github-com namespace.
No, I don't have any helm releases in that namespace.
Yes, the release that I'm trying to deploy attempts to create a ClusterRole name nginx-ingress.
Yes, the nginx-ingress ClusterRole that's deployed is set to the `default` namespace.

![image](https://user-images.githubusercontent.com/1055021/208224568-980bec04-c0b4-4924-8d06-44b93fbf473d.png)

The helm command I ran in the GitHub Actions workflow above to show the environment does not even have a KUBECONFIG because I wanted to verify that it was a helm issue, not an issue with the Kubernetes cluster.  The `HELM_NAMESPACE="github-actions-runners-github-com"` output value is unrelated to the cluster that I am targeting with the helm deploy.  Helm is getting the namespace value from somewhere, and I'm unable to determine where.

**Comment by veleek** [comment]
*List of all of the helm releases and namespaces that I have deployed in the cluster:*
![image](https://user-images.githubusercontent.com/1055021/208224717-5e860691-4636-43cd-acd4-fa95eaa0cf6f.png)

**Comment by joejulian** [comment]
Awesome, thanks. That does paint a clearer picture.

How about `helm get manifests ingress-nginx` and `helm get values ingress-nginx` and see if there's anything there that offers a clue.

**Comment by veleek** [comment]
@joejulian sure, I can get that.  Can you help me understand how this information will help us troubleshoot the problem?  I'd like to try and rephrase my original question using some of the info that we've uncovered since I posted this thread.

Updated Question:  When I run `helm env` in my self-hosted GitHub Actions runner, it says that the `HELM_NAMESPACE` variable is equal to `github-actions-runner-github-com`.  Where does helm get that namespace from?  This is true even from a clean state on the runner.  Where does the environment variable value come from?

I would assert that the output from the above two helm commands is not useful, but here it is.
*Output of `helm get values`.  Note that I had to add `--namespace default` because the deployment `ingress-nginx` doesn't exist in the `github-actions-runners-github-com` namespace that helm is configured to use somehow:*
```
helm get values ingress-nginx --namespace default
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /runner/_work/mp-groups/mp-groups/666d770c178555593c273dd3
USER-SUPPLIED VALUES:
controller:
  addHeaders: {}
  admissionWebhooks:
    annotations: {}
    certificate: /usr/local/certificates/cert
    createSecretJob:
      resources: {}
    enabled: true
    existingPsp: ""
    failurePolicy: Fail
    key: /usr/local/certificates/key
    labels: {}
    namespaceSelector: {}
    objectSelector: {}
    patch:
      enabled: true
      image:
        digest: sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660
        image: ingress-nginx/kube-webhook-certgen
        pullPolicy: IfNotPresent
        registry: k8s.gcr.io
        tag: v1.1.1
      labels: {}
      nodeSelector:
        kubernetes.io/os: linux
      podAnnotations: {}
      priorityClassName: ""
      runAsUser: 2000
      tolerations: []
    patchWebhookJob:
      resources: {}
    port: 8443
    service:
      annotations: {}
      externalIPs: []
      loadBalancerSourceRanges: []
      servicePort: 443
      type: ClusterIP
  affinity: {}
  allowSnippetAnnotations: true
  annotations: {}
  autoscaling:
    behavior: {}
    enabled: false
    maxReplicas: 11
    minReplicas: 1
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  autoscalingTemplate: []
  config: {}
  configAnnotations: {}
  configMapNamespace: ""
  image:
    allowPrivilegeEscalation: false
    image: defaultbackend-amd64
    pullPolicy: IfNotPresent
    readOnlyRootFilesystem: true
    registry: k8s.gcr.io
    runAsNonRoot: true
    runAsUser: 65534
    tag: "1.5"
  labels: {}
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  minAvailable: 1
  name: defaultbackend
  nodeSelector:
    kubernetes.io/os: linux
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  port: 8080
  priorityClassName: ""
  readinessProbe:
    failureThreshold: 6
    initialDelaySeconds: 0
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources: {}
  service:
    annotations: {}
    externalIPs: []
    loadBalancerSourceRanges: []
    servicePort: 80
    type: ClusterIP
  serviceAccount:
    automountServiceAccountToken: true
    create: true
    name: ""
  tolerations: []
dhParam: null
imagePullSecrets: []
podSecurityPolicy:
  enabled: false
rbac:
  create: true
  scope: false
revisionHistoryLimit: 10
serviceAccount:
  automountServiceAccountToken: true
  create: true
  name: ""
tcp: {}
udp: {}
```

*Output of `helm get manifests`*
```
# Source: ingress-nginx/templates/controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx
  namespace: default
automountServiceAccountToken: true
---
# Source: ingress-nginx/templates/controller-configmap-proxyheaders.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-custom-proxy-headers
  namespace: default
data:
  X-Request-Source: MTLS
---
# Source: ingress-nginx/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: default
data:
  allow-snippet-annotations: "true"
  proxy-set-headers: default/ingress-nginx-custom-proxy-headers
---
# Source: ingress-nginx/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
  name: ingress-nginx
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - get
      - list
      - watch
---
# Source: ingress-nginx/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
  name: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx
subjects:
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: "default"
---
# Source: ingress-nginx/templates/controller-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - ingress-controller-leader
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
# Source: ingress-nginx/templates/controller-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-nginx
subjects:
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: "default"
---
# Source: ingress-nginx/templates/controller-service-metrics.yaml
apiVersion: v1
kind: Service
metadata:
  annotations: 
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller-metrics
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 10254
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
---
# Source: ingress-nginx/templates/controller-service-webhook.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller-admission
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: https-webhook
      port: 443
      targetPort: webhook
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
---
# Source: ingress-nginx/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: SingleStack
  ipFamilies: 
    - IPv4
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
---
# Source: ingress-nginx/templates/controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/component: controller
  replicas: 1
  revisionHistoryLimit: 10
  minReadySeconds: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/instance: ingress-nginx
        app.kubernetes.io/component: controller
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: controller
          image: "k8s.gcr.io/ingress-nginx/controller:v1.1.0@sha256:f766669fdcf3dc26347ed273a55e754b427eb4411ee075a53f30718b4499076a"
          imagePullPolicy: IfNotPresent
          lifecycle: 
            preStop:
              exec:
                command:
                - /wait-shutdown
          args:
            - /nginx-ingress-controller
            - --publish-service=$(POD_NAMESPACE)/ingress-nginx-controller
            - --election-id=ingress-controller-leader
            - --controller-class=k8s.io/ingress-nginx
            - --configmap=$(POD_NAMESPACE)/ingress-nginx-controller
            - --validating-webhook=:8443
            - --validating-webhook-certificate=/usr/local/certificates/cert
            - --validating-webhook-key=/usr/local/certificates/key
          securityContext: 
            capabilities:
              drop:
              - ALL
              add:
              - NET_BIND_SERVICE
            runAsUser: 101
            allowPrivilegeEscalation: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LD_PRELOAD
              value: /usr/local/lib/libmimalloc.so
          livenessProbe: 
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe: 
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: metrics
              containerPort: 10254
              protocol: TCP
            - name: webhook
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: webhook-cert
              mountPath: /usr/local/certificates/
              readOnly: true
          resources: 
            requests:
              cpu: 100m
              memory: 90Mi
      nodeSelector: 
        kubernetes.io/os: linux
      serviceAccountName: ingress-nginx
      terminationGracePeriodSeconds: 300
      volumes:
        - name: webhook-cert
          secret:
            secretName: ingress-nginx-admission
---
# Source: ingress-nginx/templates/controller-ingressclass.yaml
# We don't support namespaced ingressClass yet
# So a ClusterRole and a ClusterRoleBinding is required
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
---
# Source: ingress-nginx/templates/controller-prometheusrules.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ingress-nginx-controller
  namespace: "default"
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
spec:
  groups:
  - name: ingress-nginx
    rules:
    - alert: NGINXTooMany400s
      annotations:
        description: Too many 400s
        summary: More than 5% of all requests returned 400, this requires your attention
      expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"4.+"} ) / sum(nginx_ingress_controller_requests) ) > 5
      for: 1m
      labels:
        severity: warning
---
# Source: ingress-nginx/templates/controller-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-controller
  namespace: "default"
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
    kronus.unity3d.com/monitoring: enabled
spec:
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector: 
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/component: controller
---
# Source: ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
# before changing this value, check the required kubernetes version
# https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#prerequisites
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.13
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: admission-webhook
  name: ingress-nginx-admission
webhooks:
  - name: validate.nginx.ingress.kubernetes.io
    matchPolicy: Equivalent
    rules:
      - apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingresses
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        namespace: "default"
        name: ingress-nginx-controller-admission
        path: /networking/v1/ingresses
```
