### ISSUE TITLE
Cannot inject values into dependecy blocks from templates.

### ISSUE THREAD

**Issue by stavros-k** [helm/helm#11595]
So assume this setup:

`values.yaml`
```yaml
# Main pod
image:
  repo: main/repo
# ... other values
subchart:
  enabled: false
```

`templates/subchart.tpl`
```yaml
{{- define "subchart.values" -}}
# subchart pod
enabled: true
image:
  repo: subchart/repo
# ... other values
{{- end -}}
```

`templates/common.yaml`
```yaml
{{- $_ := set .Values "subchart" (include "subchart.values" . | fromYaml) -}} 
# ... other includes
```

Expected to see subchart get the values from "subchart.values".
But it did not.

I guess it parses the values.yaml first and then moves on to `templates/`?
If that's the case
 1. I can't seem to find anything on the docs regarding order of parsing, maybe it's there but I can't see it
 2. What options do I have to make something like the above work?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}
```

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by miles-w-3** [comment]
It may work if you use = rather than :=, since sub chart is already a defined item in the values dict. I can try this out myself to verify, but it's likely due to the value already existing since I've had success with this when storing it as a new dict instead of within values

**Comment by stavros-k** [comment]
Isn't the `$_ :=` just a trap for the return value, cause it's required from Go Template? Because I no problem doing something like that:

```yaml
{{ $someDict := (dict "key" "value") }}
{{ $_ := set $someDict "key" "othervalue" }}
```
https://helm.sh/docs/chart_template_guide/function_list/#set

Another live example like the above:
https://helm-playground.com/#t=LQhQGcHsFsFMBECWBjALgLgASk5g3npgHQBqAhgDYCus4RUcSamAPpqpAJpnQWYC%2B-HNgKYAJAH1M6ALyZwsVMXLVa9GAhRKARAGtYAT22ZtkVAAtYAJxU1jg0BA1MM2XKNKUadBpuZsObl4BISA&v=LQhQGcHsFsFMBECWBjALgLgASk5g1rAJ5YBuAhgDYCusoQA


Also the `:=` will assign the return value to `$_` which will fail with `=` if it's not previously initialized

**Comment by joejulian** [comment]
`{{- $_ := set .Values "subchart" (include "subchart.values" . | fromYaml) -}}` will work for the template that it's in. Everything below that line will have access to `.Values.subchart`.

If you just want to override the values of your subchart, you can do that with values in the parent chart:
```
subchart:
  enabled: true
  image:
    repo: subchart/repo
# ... etc
```
