### ISSUE TITLE
helm  upgrade --install cause  deployment duplicate value

### ISSUE THREAD

**Issue by wujunwei** [helm/helm#11606]
How to reproduce the bug:
---
my charts have only three files:
- ./Chart.yaml
```yaml
apiVersion: v2
appVersion: 1.16.0
name: test
type: application
version: 0.1.0
```
- ./templates/service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  type: NodePort
  ports:
    - port: 123
      nodePort: {{.Values.port1}}
      protocol: TCP
      name: http
    - port: 124
      nodePort: {{ .Values.port2 }}
      protocol: TCP
      name: http12
  selector:
    app: nginx

```
- ./templates/deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - name: http
              containerPort: {{.Values.port1}}
              protocol: TCP
```

And do as follows:
---
```shell
# step 1: use two ports which are used by existed nodeport service.
 helm install test ./ --set="port1=30222,port2=30717" 
```
ports30221 & 30717 are ports which is used by another nodeport service, and it will produce `Error: Service "test" is invalid: spec.ports[0].nodePort:  Invalid value: 30222: provided port is already allocated` and it's as expected.

```shell
# step 2: change first port to unused port.
 helm install test ./ --set="port1=30221,port2=30717" 
```
it will produce `spec.ports[1].nodePort: Invalid value: 30717: provided port is already allocated`,which is as expected too.

```shell
# step 3 : change second port to unused port.
helm install test ./ --set="port1=30221,port2=30716"
```
 it will output : `Error: UPGRADE FAILED: cannot patch "nginx-deployment"  with kind Deployment: Deployment.apps "nginx-deployment" is invalid: spec.template.spec.containers[0].ports[1].name: Duplicate value: "http" `
why does this happen? deployment.yaml has only one port in containers !

Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```
It can be reproduce at latest branch `main`
Output of `kubectl version`:
```
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```
