### ISSUE TITLE
`deepCopy`, will not override an integer value with the value `0`

### ISSUE THREAD

**Issue by cunningr** [helm/helm#11618]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.18.1"}
```

Output of `kubectl version`:

N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

CAPI/Openstack, vanilla k8s.

**Issue:**

When doing a `deepCopy`, it is not possible to override an integer value with the value `0`.  I am not sure if this is a bug or a know behaviour (but it is a little annoying :-)).

We can reproduce this in the [helm playground](https://helm-playground.com/#t=LQhQG92ACASA7A9gEwKYHEBOiCuAHaALgF5o1U8BhRPATzgDoA1AQwBsdUBnB7Nt3ABcAyoMwtBqAOa0AjNAA%2B0ALY4uggLKpMU1I1YduvRPyGjxkmQCZoAX1sRw0QYgCaLZWzhI0WXAXsgA&v=LQhQCcHsBtshXALgZUeAhogpgcwJ4CMAXKAASmJ4AOWRpASjNAJYB2OAqlQCaZZmkosNpx58S5cgFt0ADw6t0AN3TNo6AEbRapAgOlzk8cDh16ITBCjR98AJgkVqOxsPZde2AUJbux2RwN5RRU1TW06AAZ9UhlZIxMzUCA)

With values:

```
---
rolloutStrategy1:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

rolloutStrategy2:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
``` 

and template:

```
---
{{- $nodeGroup := deepCopy $.Values.rolloutStrategy1 | mustMerge $.Values.rolloutStrategy2 }}
{{ toYaml $nodeGroup }}
```

I would expect the values in `rolloutStrategy2` to override the values in `rolloutStrategy1`, which they do, unless the value is a `0`.
