### ISSUE TITLE
Inconsistent handling of maps with empty values

### ISSUE THREAD

**Issue by gman0** [helm/helm#11617]
Output of `helm version`: `version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}`

There is inconsistency in how map entries with no value (defined in `values.yaml`) are handled. When deploying a chart with such a map, these entries will have a default value of `null`. However, if this chart is used as a dependency of some other chart, these empty entries are skipped entirely.

Example:

### Chart-A:

This is the base chart that defines a `config` map in its values.yaml, and then populates a ConfigMap object with its contents. Here everything works as expected.

`values.yaml`:
```yaml
config:
  a:
  b: {}
  c: {}
  d:
```

`templates/config.yaml`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  config: |+
    {{- range $k, $v := .Values.config }}
    key="{{ $k }}"
    value="{{ $v | toJson }}"
    .
    {{- end }}
```

Output of `$ helm template chart-a`:
```yaml
# Source: chart-a/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  config: |+
    key="a"
    value="null"
    .
    key="b"
    value="{}"
    .
    key="c"
    value="{}"
    .
    key="d"
    value="null"
    .
---
```

### Chart-B

Chart-B includes Chart-A as a dependency. `my-config` ConfigMap from Chart-A is missing entries that don't specify "null" value explicitly:

Output of `$ helm template chart-b`:
```yaml
# Source: chart-b/charts/chart-a/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  config: |+
    key="b"
    value="{}"
    .
    key="c"
    value="{}"
    .
---
```

Only keys `b` and `c` are present. `a` and `d` are omitted because of no value. I would expect the behavior to be the same as it was with chart-a -- they should have had an implicit value `null`.
