### ISSUE TITLE
Question: helm eq (true | quote) "true" evaluates to false

### ISSUE THREAD

**Issue by xgt001** [helm/helm#11612]
I got my fingers burnt wildly by basing my conditional logic based on 
``` {{- if eq (true|quote) "true"}} ``` -> this always evaluates to false, since I assume we are doing a string comparison, shouldn't this evaluate to true?

To try it out quickly you can run:

```
kind: Pod
metadata:
  name: test
  labels:
    test: {{- eq (true | quote) "true" }}
```
you will see a render of this fashion:
```
kind: Pod
metadata:
  name: test
  labels:
    test:false
```
