### ISSUE TITLE
subchart | the same input values, but computed values are different

### ISSUE THREAD

**Issue by nemethk** [helm/helm#11611]
## Short description
We got different "computed values" depending on how we declared the values of subcharts. Focus is only on values of subcharts. Is it a bug in templating or is it the normal way how Helm works? If it is normal, could you please share the url for the appropriate documentation.

Here is the demo repository for easier understanding: https://github.com/BlackBeltTechnology/helm-debugging

### Values

Path: `mychart/values.yaml`

#### A:
```
deployments:
  mysubchart1:
    enabled: false
  mysubchart2:
    enabled: true
```
#### B:
```
mysubchart1:
  enabled: false
mysubchart2:
  enabled: true
```
#### C1:
```
helm upgrade --install helm-debugging mychart --dry-run --debug > output/helm-debug-$(date "+%Y%m%d-%H%M%S")
```
#### C2:
```
helm upgrade --install helm-debugging mychart -f myfiles/extraconfig.yaml --dry-run --debug > output/helm-debug-$(date "+%Y%m%d-%H%M%S")
```

#### A + C1
Only `mysubchart2` related values are visible.
```
COMPUTED VALUES:
deployments:
  mysubchart1:
    enabled: false
  mysubchart2:
    enabled: true
extra:
  data: []
  enable: ""
fruit:
  data: apple
  enabled: true
meal:
  drink: coffee
  food: goulash
menu: lunch
mysubchart2:
  dessert: muffin
  global: {}
  name: subchart-2
name: main-chart
```

#### A + C2
Values of both subcharts are visible. 
```
COMPUTED VALUES:
deployments:
  mysubchart1:
    enabled: false
  mysubchart2:
    enabled: true
extra:
  data:
  - pepper
  - salt
  - crushed red pepper
  enable: true
fruit:
  data: apple
  enabled: true
meal:
  drink: coffee
  food: goulash
menu: lunch
mysubchart1:
  dessert: pudding
mysubchart2:
  dessert: muffin
  global: {}
  name: subchart-2
name: main-chart
```

#### B + C1
Values of both subcharts are visible but there are some differences regarding previous commands.
```
COMPUTED VALUES:
extra:
  data: []
  enable: ""
fruit:
  data: apple
  enabled: true
meal:
  drink: coffee
  food: goulash
menu: lunch
mysubchart1:
  dessert: cake
  enabled: false
  global: {}
  name: subchart-1
mysubchart2:
  dessert: muffin
  enabled: true
  global: {}
  name: subchart-2
name: main-chart
```

#### B + C2
Values of both subcharts are visible but there are some differences regarding previous commands.
```
COMPUTED VALUES:
extra:
  data:
  - pepper
  - salt
  - crushed red pepper
  enable: true
fruit:
  data: apple
  enabled: true
meal:
  drink: coffee
  food: goulash
menu: lunch
mysubchart1:
  dessert: pudding
  enabled: false
mysubchart2:
  dessert: muffin
  enabled: true
  global: {}
  name: subchart-2
name: main-chart
```

## Versions
Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}
```
Output of `kubectl version`:
```
$ kubectl version  --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.1",
    "gitCommit": "e4d4e1ab7cf1bf15273ef97303551b279f0920a9",
    "gitTreeState": "clean",
    "buildDate": "2022-09-14T19:49:27Z",
    "goVersion": "go1.19.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): RKE2, k3s, on premises k8s
