### ISSUE TITLE
Accessing subchart values with .Subcharts breaks if dependency is referenced on local disk

### ISSUE THREAD

**Issue by red8888** [helm/helm#11621]
Output of `helm version`: version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.19.3"}

I'm using the subcharts feature to get a subchart's builtin Chart variables.

Example used in a template in parent chart: 

`{{ include "my-subchart.myfunc.that.useschartvars" (index .Subcharts "my-subchart")}}
`

The function in my subchart looks like this, it calls another function that returns the Chart name and version:

```
{{- define "my-subchart.otherfunc" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "my-subchart.myfunc.that.useschartvars" -}}
helm.sh/my-subchart: {{ include "my-subchart.myfunc.that.useschartvars" . }}
{{- end -}}
```

If referenced the chart via my repo path this works as expected:

```
dependencies:
- name: my-subchart
   repository: https://myrepo-url/myrepo
   version: 1.2.3
```

BUT if I try to reference it from my local disk all the `.Chart.*` values are null:
```
dependencies:
- name: my-subchart
   repository:  "file://../../../../../../my-subchart-project/my-subchart"
   version: 1.2.3
```

It makes local dev frustrating because I can't reference on local disk to test changes.
