### ISSUE TITLE
Modifications not reflecting on adopted IstioOperator resource

### ISSUE THREAD

**Issue by cotej** [helm/helm#11638]
It's tricky to tell whether this is an issue specifically with Helm or perhaps with the IstioOperator CRD, however I figure this is a good place to start.  Here's a scenario that demonstrates a strange behavior that I'm seeing:

* Starting with a fresh minikube cluster
* Run some initial setup to install the Istio operator into the cluster with `istioctl operator init` and `kubectl create namespace istio-system`
* Deploy an IstioOperator CRD into the cluster with `kubectl apply -f ./pilot-raw.yaml`
```yaml
# pilot-raw.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 50m
```

The goal is "adopt" this resource into a new Helm chart for managing Istio.
* First we must patch the resource to include the annotations expected by Helm
```bash
patchBody='{
  "metadata": {
    "annotations": {
      "meta.helm.sh/release-name": "my-istio",
      "meta.helm.sh/release-namespace": "istio-system"
    },
    "labels": {
      "app.kubernetes.io/managed-by": "Helm"
    }
  }
}'
kubectl patch -n istio-system istiooperator "istio-operator" --type=merge -p "$patchBody"
```
* Now we can go ahead an install the Helm chart with `helm upgrade my-istio ./helm --install --namespace istio-system`
* Here the `./helm` directory is a chart which contains just a single template of the same IstioOperator CRD, but modified to add some new values under `.spec.values.global`
```yaml
# pilot-helm.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 50m
      # These below should be added by the helm chart install
      meshID: my-mesh
      multiCluster:
        clusterName: my-cluster
      network: my-network
```
* The chart installs "successfully", however the expected modifications to the resource are not applied!

Now for the strange findings that are leaving me confused whether this is a Helm-problem or an Istio-problem...

* I attempted adding `--force` to the `helm upgrade` command above but the same behavior is observed.  _However_, if I repeat the upgrade a 2nd time with `--force` then the new values get added.
* If I do this same experiment on some other "normal" resource, like an arbitrary Opaque secret, it seems to work just fine on the first try, and no `--force` necessary. 

Are CRDs handled as a special case by Helm?
Could the IstioOperator CRDs be rejecting the modifications but Helm isn't able to see that?  If so, why does it magically work after the 2nd upgrade with --force?

---

Output of `helm version`:
```
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
Minikube
```
Istio version
```
client version: 1.13.7
control plane version: 1.13.7
data plane version: none
```
