### ISSUE TITLE
Problem with chart name

### ISSUE THREAD

**Issue by ehsan-tashkhisi** [helm/helm#11643]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`Minikube`

I have problem when adding the Infinispan chart as a dependency to my chart as below:

```
dependencies:
  - name: infinispan-infinispan
    alias: infinispan
    version: 0.3.0
    repository: https://charts.openshift.io/
```
After running `helm dep up`

The content of the charts directory is as below:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/61104684/207938752-53f25946-cd0e-4968-970d-597e46f3dd94.png">

As you can see the tar file was generated with the name `infinispan-infinispan` but the name of the folder inside that tar file is `infinispan`. for this reason when I run `helm install` command I get the following error:
```
INSTALLATION FAILED: found in Chart.yaml, but missing in charts/ directory: infinispan-infinispan
```
Based on Helm documentation `name` in dependency should match the `name` in the chart but with this chart, it is not possible, because the name that I should use in dependency is `infinispan-infinispan` but the name of the chart is infinispan. Is there any workaround to solve it in Helm?

**Comment by yxxhero** [comment]
@ehsan-tashkhisi I think this is a bug.

**Comment by yxxhero** [comment]
@ehsan-tashkhisi PR is welcome.

**Comment by ehsan-tashkhisi** [comment]
Thanks @yxxhero for the quick reply, to my mind, this is more of a bug in the Infinispan chart, as stated in the Helm documentation the name for dependency should match the name of the chart but this chart is not developed that way. here is the example and the quote from the [helm dependency documentation](https://helm.sh/docs/helm/helm_dependency/):
```
# Chart.yaml
dependencies:
- name: nginx
  version: "1.2.3"
  repository: "https://example.com/charts"
- name: memcached
  version: "3.2.1"
  repository: "https://another.example.com/charts"
```

> **The 'name' should be the name of a chart, where that name must match the name in that chart's 'Chart.yaml' file.**

The problem is that now I can not use this chart as a dependency, I have to wait until they fix it in their repository, I wanted to know if there is any workaround to solve it, is there any way to use the .tgz file locally as a dependency?
