### ISSUE TITLE
Helm template merges only first yaml document from template if template contains multiple yaml documents

### ISSUE THREAD

**Issue by malcolm061990** [helm/helm#11647]
Output of `helm version`:
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}

Output of `kubectl version`: 
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}

Hi. I have chart:
```yaml
# app/Chart.yaml
apiVersion: v2
name: app
description: Helm chart for app
type: application
version: "0.0.1"
appVersion: "0.0.1"

dependencies:
- name: common-chartlib
  version: 0.1.0
  repository: file://../common-chartlib

# app/values.yaml
service:
  port: 9591

serviceMonitor:
  port: 9591

# app/templates/servicemonitor.yaml
{{- include "common-chartlib.servicemonitor" (list . "app.servicemonitor") -}}
{{- define "app.servicemonitor" -}}
{{- end -}}
```

And common chart library used by chart above:
```yaml
# common-chartlib/templates/_servicemonitor.yaml. This file contains TWO kinds: Service and ServiceMonitor
{{- define "common-chartlib.servicemonitor.tpl" -}}
{{- if .Values.serviceMonitor}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "common-chartlib.fullname" . }}-prometheus-service
  labels:
    {{- include "common-chartlib.labels" . | nindent 4 }}
    app: {{ include "common-chartlib.fullname" . }}
    component: {{ include "common-chartlib.fullname" . }}-prometheus-service
spec:
  ports:
  - name: {{ include "common-chartlib.fullname" . }}-port
    port: {{ .Values.serviceMonitor.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    component: {{ include "common-chartlib.fullname" . }}
status:
  loadBalancer: {}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common-chartlib.fullname" . }}
  namespace: monitoring
  labels:
    app: {{ include "common-chartlib.fullname" . }}
    release: prometheus
spec:
  selector:
    matchLabels:
      component: {{ include "common-chartlib.fullname" . }}-prometheus-service
  endpoints:
  - port: {{ include "common-chartlib.fullname" . }}-port
    interval: 15s
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}
{{- end}}
{{- end}}
{{- define "common-chartlib.servicemonitor" -}}
{{- include "common-chartlib.util.merge" (append . "common-chartlib.servicemonitor.tpl") -}}
{{- end -}}

# common-chartlib/templates/_util.yaml
{{- define "common-chartlib.util.merge" -}}
{{- $top := first . -}}
{{- $overrides := fromYaml (include (index . 1) $top) | default (dict ) -}}
{{- $tpl := fromYaml (include (index . 2) $top) | default (dict ) -}}
{{- toYaml (merge $overrides $tpl) -}}
{{- end -}}

# common-chartlib/templates/_helpers.tpl
{{/*
Expand the name of the chart.
*/}}
{{- define "common-chartlib.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "common-chartlib.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "common-chartlib.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "common-chartlib.labels" -}}
helm.sh/chart: {{ include "common-chartlib.chart" . }}
{{ include "common-chartlib.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "common-chartlib.selectorLabels" -}}
app.kubernetes.io/name: {{ include "common-chartlib.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "common-chartlib.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "common-chartlib.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}
```

Expected output (both kinds: Service and ServiceMonitor):
```yaml
---
apiVersion: v1
kind: Service
...
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
...
```

Real output (only Service kind is generated but not ServiceMonitor):
```bash
helm template . --name-template app -s templates/servicemonitor.yaml
---
# Source: app/templates/servicemonitor.yaml
apiVersion: v1
kind: Service # only this is generated without kind: ServiceMonitor
metadata:
  labels:
    app: app
  name: app
  namespace: ns
spec:
  ports:
  - name: app
    port: 9591
    protocol: TCP
    targetPort: 9591
  selector:
    component: app
status:
  loadBalancer: {}
```

I understand that we need to change something in `common-chartlib/templates/_util.yaml` but don't understand what. Checked different variants - no luck. Please help

**Comment by joejulian** [comment]
If I'm reading this right, I think you're calling fromYaml on the output of the template. I'm pretty sure that won't work on multi-doc yaml.

**Comment by malcolm061990** [comment]
> If I'm reading this right, I think you're calling fromYaml on the output of the template. I'm pretty sure that won't work on multi-doc yaml.

Yes, you are right. Ok, fromYaml doesn’t work with multidoc yaml. In this case how can I send each doc separately to fromYaml?

**Comment by gjenkins8** [comment]
It seems you're trying to template a `kind: Service` and `kind: ServiceMonitor` together. Why not just do that, and remove the `common-chartlib.util.merge` function? Overall, it might be better to attempt to reduce complexity to improve maintainability here.

Also, would it be okay to update the title of the issue here too please?

**Comment by malcolm061990** [comment]
> Overall, it might be better to attempt to reduce complexity to improve maintainability here.

Totally agree. `common-chartlib.util.merge` is used in all other templates. So we can't just remove it. Or do you mean to remove `common-chartlib.util.merge` only from `common-chartlib/templates/_servicemonitor.yaml`? In this case how we can generate the output for both kinds?

**Comment by gjenkins8** [comment]
I mean, why not just have something as simple as the below. In your example, I don't think you use the `override` functionality (in the `merge` function). As the additional complexity of the `merge` seems to be to support this functionality.

```
# templates/servicemonitor.yaml
{{- if .Values.serviceMonitor}}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "common-chartlib.fullname" . }}-prometheus-service
  labels:
    {{- include "common-chartlib.labels" . | nindent 4 }}
    app: {{ include "common-chartlib.fullname" . }}
    component: {{ include "common-chartlib.fullname" . }}-prometheus-service
spec:
  ports:
  - name: {{ include "common-chartlib.fullname" . }}-port
    port: {{ .Values.serviceMonitor.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    component: {{ include "common-chartlib.fullname" . }}
status:
  loadBalancer: {}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common-chartlib.fullname" . }}
  namespace: monitoring
  labels:
    app: {{ include "common-chartlib.fullname" . }}
    release: prometheus
spec:
  selector:
    matchLabels:
      component: {{ include "common-chartlib.fullname" . }}-prometheus-service
  endpoints:
  - port: {{ include "common-chartlib.fullname" . }}-port
    interval: 15s
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}
{{- end}}
```

If you wanted/needed multiple `Service`/`ServiceMonitor` pairs for a chart: then yes, you would need duplicate the yaml above.

If you wanted to use this chart as a library chart, and the consuming chart would use this `override` functionality, then yes, you will need (AFAICT) to fix the `merge` functionality to support multiple yaml docs.
