### ISSUE TITLE
uuidv4 weirdness

### ISSUE THREAD

**Issue by Morriz** [helm/helm#11668]
Hi, if I create a chart with only this resource:
```yaml
# templates/job.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Release.Name uuidv4 }}
data:
  oki: doki
```
and then template it with release name `bla`, I see the resource name always ending up like `bla${random 2 alphanumeric chars}`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bla23
data:
  oki: doki
```
I don't know why, but however I phrase the template, the uuidv4 part always seems to strip off the dash next to it and then prints two chars.

Output of `helm version`:
`version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:57:43Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}`
