### ISSUE TITLE
Aliased grandchild not being applied in parent chart.

### ISSUE THREAD

**Issue by AsfaMumtaz** [helm/helm#11679]
### Summary
I have chart (parent) which has a subchart. In the subchart I have another chart as a dependency referenced twice. Once with an alias and once without it.

When I helm template the parent chart, the resources of aliased chart are not present. 

```
**parent chart:
   subchart:
     grandchild
     grandchild-aliased.**
```

**subchart dependencies:**
```
 dependencies:
 - name: granchild
   alias: myalias
   version: 1.0.0
 - name: granchild
   version: 1.0.1
```

#### Expected result
granchild applied twice in parent chart.

#### Output
Only the non aliased chart resources are present
