### ISSUE TITLE
Global Values not available in partial of sub charts

### ISSUE THREAD

**Issue by trpouh** [helm/helm#11703]
Output of `helm version`:
`version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}`

Output of `kubectl version`:
not relevant

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
not relevant

## Problem
Global values from subchart can not be accessed from partials used in other sub chart. (Names are changed and dependencies are simplified)

I have the following logical structure of charts (all charts are stored in individual repositories):

```
- app             # combines all charts
-- base           # contains some global values
-- appserver      # mainly deployment
--- helpers       # helpers for creating k8s labels
```

The dependencies are structured as follows (successfully - as they are present in the charts folder after retrieving them via `helm dependency update`):

```yaml
# Chart.yaml of app chart
dependencies:
- base
- appserver
```

```yaml
# Chart.yaml of appserver chart
dependencies:
- helpers
```

The global values are set in the `base` chart as following:
```yaml
# values.yaml of base chart
global:
  organisationUnit: myDepartment
```

And included in the `appserver` chart via (tried both `.` context and `$` context - same result)

```yaml
# templates/deployment.yml of appserver chart
spec:
{{ include "labels" . | indent 8 }}
```

which is defined in the `helpers` chart
```yaml
# templates/_helpers.tpl of helpers chart
{{- define "labels" -}}
mylabel: {{ required ".Values.global.organisationUnit required" .Values.global.organisationUnit | quote }}
{{- end -}}
```

which when templating results in the following error:

```yaml

$ helm template -f <values> .

install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: <path-to-app>


Error: execution error at (<appserver>/templates/deployment.yml:28:3): .Values.global.organisationUnit required
helm.go:84: [debug] execution error at (<appserver>/templates/deployment.yml:28:3): .Values.global.organisationUnit required
```

where `deployment.yml:28:3` points directly to the snippet of the `deployment.yml` posted above.

which seems strange to me, because according to the [helm documentation](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values) it should work:

> Because of the way globals work, both mychart/templates/configmap.yaml and mysubchart/templates/configmap.yaml should be able to access that value as {{ .Values.global.salad }}.

In the example given by the helm doc, `base` would be `mychart` and `appserver` would be `mysubchart`. 
If the field is set in the `values.yaml` of the `app` chart it works just fine. I read the whole _Chart template Guide_ but can't wrap my head around the issue in my helm charts. 

Thank you for your help.

**Comment by joejulian** [comment]
I think this is describing what you're asking and works as expected. Play with this and see if you can get the behavior you're experiencing.

[base.tar.gz](https://github.com/helm/helm/files/10396973/base.tar.gz)

**Comment by trpouh** [comment]
thanks for the fast reply, however the example is not exactly what I was describing. I changed your chart and added a small README to explain it.

[chart.zip](https://github.com/helm/helm/files/10400567/chart.zip)

**Comment by joejulian** [comment]
I don't see a difference.

```
/tmp/foo/chart/wanted $ helm template . --set global.organisationUnit=foo 
---
# Source: app/charts/appserver/templates/deployment.yaml
baseValues: | 
  global:
    organisationUnit: foo
  helpers:
    global:
      organisationUnit: foo
labels: 
  mylabel: "foo"
```

```
/tmp/foo/chart/working 
$ helm template . --set global.organisationUnit=foo
---
# Source: app/charts/appserver/templates/deployment.yaml
baseValues: | 
  global:
    organisationUnit: foo
  helpers:
    global:
      organisationUnit: foo
labels: 
  mylabel: "foo"
```

```
$ helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}
```

**Comment by trpouh** [comment]
The whole point of this issue is that contrary to the documentation, the parameters from one subchart (base) are not available in partials of other subcharts (appserver -> helpers). I don't understand how setting the parameter manually correlates to this issue.

**Comment by joejulian** [comment]
Ah, I think I see now what you're saying. If I'm now understanding correctly you're saying that these value files:

***base***
```
globals:
  base: foo
```

***subchart1***
```
globals:
   subchart1: bar
```

***subchart2***
```
globals:
  subchart2: baz
```

should result in all three charts having:
```
globals:
  base: foo
  subchart1: bar
  subchart2: baz
```

**Comment by joejulian** [comment]
So with the attached charts, each chart defines one global. All globals are printed in each template using:
```
global: {{ nindent 2 (toYaml .Values.global) }}
```
resulting in
```
---
# Source: base/charts/subchart1/templates/globals.yaml
global: 
  base: foo
  subchart1: bar
---
# Source: base/charts/subchart2/templates/globals.yaml
global: 
  base: foo
  subchart2: baz
---
# Source: base/templates/globals.yaml
global: 
  base: foo
```
[testchart.tar.gz](https://github.com/helm/helm/files/10473894/testchart.tar.gz)
