### ISSUE TITLE
Naming subchart based on dynamic parent charts created with alias

### ISSUE THREAD

**Issue by tnayhsud** [helm/helm#11716]
Output of `helm version`: 
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

I am a beginner to helm world. So pardon me for lack of my understanding helm. 
I have a chart for bitnami kafka, which includes subchart for zookeeper. Both these charts use **common.names.fullname** template from **common** subchart included in same bitnami package to generate names for the kafka and zookeeper components using ```name: {{ include "common.names.fullname" . }}``` in metadata section wherever it is required.

Common template for generating names:
```
{{- define "common.names.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

My requirement is that i am using alias feature to install multiple kafka clusters using a main parent chart. Main parent chart.yaml looks like following:

```
apiVersion: v2
name: main-chart
description: A Helm chart for kafka cluster
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: kafka
    condition: kafka-1.enabled
    alias: kafka-1
    version: 15.3.5
  - name: kafka
    condition: kafka-2.enabled
    alias: kafka-2
    version: 15.3.5 
   .
   .
   .
  - name: kafka
    condition: kafka-5.enabled
    alias: kafka-5
    version: 15.3.5
```

As I am using alias to generate names, there will be multiple kafka clusters. But zookeeper names will be same for every parent kafka chart, which will result in errors. Also i can not generate any random identifier prefix/suffix for zookeeper components because I need to generate consistent zookeeper service names to be referred in kafka stateful sets.

I was wondering if there is any way of passing dynamic identifier from alias name kafka-**identifier** down to **common.names.fullname** template from **common** subchart when this template is invoked in zookeeper subchart.

For e.g.
If I have kafka chart name as **kafka-1**, then zookeeper component name is, say, **zk-sts-1**.
Generally speaking, if kafka chart name is **kafka-m**, then zookeeper component name is, say, **zk-sts-m**. 
So, that naming is consistent. 

Please help. Again let me know if more context is needed. Thanks

**Comment by phil9909** [comment]
You could add the following values to your `values.yaml`:

```yaml
kafka-1:
  zookeeper:
    fullnameOverride: zk-sts-1
kafka-2:
  zookeeper:
    fullnameOverride: zk-sts-2
kafka-3:
  zookeeper:
    fullnameOverride: zk-sts-3
kafka-4:
  zookeeper:
    fullnameOverride: zk-sts-4
kafka-5:
  zookeeper:
    fullnameOverride: zk-sts-5
```
