### ISSUE TITLE
Failed to replace object: PersistentVolumeClaim when upgrading from helm v3.1.1 to v3.9.4

### ISSUE THREAD

**Issue by cretzel** [helm/helm#11729]
I want to upgrade from helm v3.1.1 to v3.9.4, but helm upgrade fails on a PVC with the new version. Target platform is Azure AKS.

```
client.go:261: [debug] error updating the resource "loki-claim": failed to replace object: PersistentVolumeClaim "loki-claim" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
      AccessModes:      {"ReadWriteOnce"},
      Selector:         nil,
      Resources:        {Requests: {s"storage": {i: {...}, s: "64G", Format: "DecimalSI"}}},
-     VolumeName:       "pvc-55f471bc-8587-43c9-b4f7-d558510a85e5",
+     VolumeName:       "",
      StorageClassName: &"default",
      VolumeMode:       &"Filesystem",
      ... // 2 identical fields
  }
```

The template looks like this:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: loki
    component: "loki"
    release: monitoring
  name: loki-claim
  namespace: management
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "64G"
  storageClassName: default
```

Output of `helm version`:
We are upgrading from v3.1.1
`version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}`
to v.3.9.4:
`version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Azure AKS

I found similar issues but they were mostly related to the storageClassName. It seems this is only related to the VolumeName. Any ideas?
