### ISSUE TITLE
Helm could not upgrade Knative deployments

### ISSUE THREAD

**Issue by patrik93** [helm/helm#11733]
Question

Hi there, 
I'm currently facing some issues with knative 1.8.1 (but had this issues since 1.0, already talked to knative contributors, they suggested me to ask here).
Helm does not upgrade the services properly (https://knative.dev/docs/). I mean for example I have changed the `readinessProbe` for the serving, or changed the `args: ['dummy']` of the service manifest in the helm chart, run the usual `helm upgrade <chartName>` command.
It creates a new revision, with the new revision id, but the actual configuration of the pod does not change.

I expect that, when the helm upgrade happening and the new revision is created, I have the updated service.

I was expecting the following `readinessProbe`:
```
readinessProbe:
  failureThreshold: 1
  httpGet:
    path: /healthz
    scheme: HTTP
  initialDelaySeconds: 40
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
```
But when I check the service in my terminal i found actually this:
```
readinessProbe:
  successThreshold: 1
  tcpSocket:
    port: 0
```
Is there anyone out there who had this issue before? 

I don't have this issue (and never had) when using `kubectl`

Output of `helm version`:
`version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}`

Output of `kubectl version`:
` Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

**Comment by joejulian** [comment]
> already talked to knative contributors

Is this somewhere you can link to for context?

The only possibility that comes to mind is that the 3-way merge is ending up with a readinessProbe that has both, but I don't think that would be valid and I would expect an error.

**Comment by patrik93** [comment]
Unfortunately their first answer was to contact the helm project. I just mentioned this _"already talked to knative contributors"_ to avoid the redirection to knative project 😄

**Comment by patrik93** [comment]
The big problem with this, I'm not exactly sure how to reproduce this issue, but let me try to write down what I have experienced so far:
In case of knative service, there are a bunch of other resources which are going to be deployed. 
A simple knative service looks like this:
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: service
spec:
  template:
    metadata:
      name: sevice-3d495013
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/target: "3"
    spec:
      containers:
          image: image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      timeoutSeconds: 3600
```
This will create the knative service itself, but will create additional resources in the knative api, like `configuration`, `revision`, `route` etc. 
We use our Jenkins to update the development environment on every successful develop build - this means we update our helm chart a few times a day - and there are some cases when the new revision is created (in knative if you change an existing service, it will create a new revision and switch to that) but without having the changes from the build. The example above about the readinessProbe was just an example, we have this problem with `args` too. 

Moreover, the git hash of our application still represents the previous build's git hash (we show it for reference which comes handy in this case). When this happens the revision have the latest git commit hash in the name (we use it to identify revisions) **but** the code itself and the configuration of the knative resource is still from the previous revision. 

I hope this story brings you closer to understand my struggle.
