### ISSUE TITLE
Difference when treating nullified nodes when `-f` parameter is used

### ISSUE THREAD

**Issue by jacek-jablonski** [helm/helm#11737]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}
```

Hi,
I've very simple Chart with subchart:
Chart.yaml:
```yaml
apiVersion: v2
dependencies:
  - name: drupal
    version: 12.5.13
    repository: https://charts.bitnami.com/bitnami
name: mydrupal
type: application
version: 0.1.0
```

values.yaml:
```yaml
drupal:
  updateStrategy: null
```

Now, I get quite different template generation results depending on whether the `-f` parameter is used or not.
```bash
$ helm template drupal . > 1.yaml
$ helm template drupal . -f values.yaml> 2.yaml
$ diff 1.yaml 2.yaml
[CUT]
192,193d191
<   strategy:
<     type: RollingUpdate
```

I'm wondering why the result of both command invocations is different. Shouldn't it be that in both cases the updateStrategy field should not be rendered?
