### ISSUE TITLE
Helm dependency build Error: the lock file (Chart.lock) is out of sync with the dependencies file

### ISSUE THREAD

**Issue by VaibhavSharma-47** [helm/helm#11750]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:18:48Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/arm64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker Desktop

I have a chart.yaml file like so with dependencies - 
```
apiVersion: v2
name: test
description: test dependencies
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: rbac-manager
    version: 1.13.1
    repository: https://charts.fairwinds.com/stable
```
I did a `helm dependency update` and a `chart.lock` file was created. Then I removed the dependencies from  `chart.yaml`  and ran the `helm dependency update` again.  Now if I run `helm dependency build` I get this error - `Error: the lock file (Chart.lock) is out of sync with the dependencies file (Chart.yaml). Please update the dependencies`. 
Am I missing something here ?
