### ISSUE TITLE
Clarification of best practices around documentation 

### ISSUE THREAD

**Issue by matt-carr** [helm/helm#11787]
Referring to https://helm.sh/docs/chart_best_practices/values/#document-valuesyaml (helm 3.11.0 docs)

I've seen another issue or two here about this and wanted to clarify - where the docs say "defined property", do they mean "final-level key" or do they mean "literally any key"

i.e. following those best practices, say I'm using subchart `foo`, do I document like:

```yaml
# someKey is an example key I've picked for this exercise
someKey: quux
# foo is the application responsible for baring the baz
foo:
  # livenessProbe handles configuration of the foo livenessProbe
  livenessProbe:
    # endpoint is the HTTP endpoint that the livenessProbe should GET to check liveness
    endpoint: /healthz
```

or

```yaml
# someKey is an example key I've picked for this exercise
someKey: quux

foo:
  livenessProbe:
    # endpoint is the HTTP endpoint that the livenessProbe should GET to check liveness
    endpoint: /healthz
```

Option 1 seems unnecessarily verbose and prone to repetition, and option 2 seems like it would make it harder to grep out documentation. One might use option 2 and fully qualify the key (e.g. `foo.livenessProbe.endpoint`) but that isn't quite what's said in the docs

In the case that the answer is the secret Option 3, that being "figure it out on your own, we're not gonna tell you how to write all your comments" would you be open to a change to the docs (I'd be happy to put up a PR) stating that? I've been looking around for a while and haven't been able to get a 100% clear opinion on the matter, and I imagine I'm not the only one
