### ISSUE TITLE
Helm truncates trailing zero in tag versions to the closest whole number

### ISSUE THREAD

**Issue by oreillymj** [helm/helm#11800]
If I have a tag version 1.0 in values.yml, my deployment will fail due to a missing container. A dry run shows the following

Tag setting in values.yml
```
fullname: k8sclient
image:
  repository: localhost/k8sclient
  tag: 1.0
```
Output of deployment dry-run

```
      - name: k8client
        image: "localhost/k8sclient:**1**"
```

I get a tag suffix of 1 instead of the expected 1.0.

Since the tag can contain values like "latest", most people would expect it to use string formatting and not truncate trailing zero's
Changing the tag to 1.01 in values.yml results in the expected output....
```
      - name: k8client
        image: "localhost/k8sclient:1.01"
        imagePullPolicy: IfNotPresent
```

**Comment by joejulian** [comment]
`1.0` will be interpreted as a float64. What you probably want is a string:
```
fullname: k8sclient
image:
  repository: localhost/k8sclient
  tag: "1.0"
```
