### ISSUE TITLE
`merge` does not pass through null entries in some cases

### ISSUE THREAD

**Issue by sirianni** [helm/helm#11812]
## Setup
Simple helm chart that reproduces this issue https://github.com/sirianni/helm-merge-bug

File: `defaultConfig.yaml`
```yaml
parent:
  a:
  b: 2
```

Template: `test.yaml`
```
{{- $defaultConfig := $.Files.Get "defaultConfig.yaml" | fromYaml -}}
{{- merge .Values.config $defaultConfig | toYaml }}
```

## Test
```
$ helm template ./chart --set config.parent.c=3
```
```yaml
---
# Source: chart/templates/test.yaml
parent:
  b: 2
  c: 3
```

I expect `parent.a` to be present in the result.  If I call `helm template` with no values, this works as expected:
```
$ helm template ./chart
```
```yaml
---
# Source: chart/templates/test.yaml
parent:
  a: null
  b: 2
```

Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}
```
