### ISSUE TITLE
Helm does not remove annotations

### ISSUE THREAD

**Issue by sig-piskule** [helm/helm#11823]
Output of `helm version`:
3.8.1

Output of `kubectl version`:
1.18

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

-----

I have found that Helm does not delete annotations. That is, if I have a helm chart *something* like this (call it version 1.0):
deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 1
  template:
    spec:
      containers:
         image: ubuntu:20.04
```

and deploy it, let's say I get a running ubuntu pod (example isn't 100%, but bear with me).

If I then annotate the deployment manually with something like this:
```
kubectl patch deployment mydeployment spec.template.metadata.annotations.key value
```

Let's say my K8S object then looks like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        key: value
    spec:
      containers:
         image: ubuntu:20.04
```

Let's say that is an emergency-patch to fix an issue, where going through a complete SDLC would take too long to update the helm chart. Let's say we then fix the issue, and no longer want the annotation to be there. So, we deploy the *next* version of the application, call it 1.1. Let's furthermore assume that if the annotation exists, it breaks my application. This time, the helm chart looks something like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 1
  template:
    spec:
      containers:
         image: ubuntu:20.14
```

If I run helm upgrade using the above helm chart, my annotation continues to exist
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        key: value
    spec:
      containers:
         image: ubuntu:20.14
```

While I understand I personally violated Configuration-as-Code by running `kubectl patch`, I eventually want to get back to a "known state" for my application where my application matches my helm chart. However, Helm is not wiping out the annotation and replacing it. Somehow, it persists the annotation, and I specifically tested this use-case as I need to patch all of my production environment due to this.

Is this a bug in Helm? Is it intentional on Helm's end? Is there a way to "wipe out" or "reset" all objects owned by Helm? This seems like very strange behavior to me.

If this is a known issue, I apologize for asking, however I did not see any direct results on Google Search or any of the release notes in Helm, meaning that this post will probably end up being the top-result for this question. Details on whether this is a bug, and potential mitigations would be much appreciated.
