### ISSUE TITLE
Helm dependency ignores conditions

### ISSUE THREAD

**Issue by yonahd** [helm/helm#11836]
Helm version -> version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}

When running `helm dependency update` 
it ignores the conditionals in the Chart.yaml

This may be the expected behavior but having conditionals would be necessary in the case of helm libraries, where you would want a certain version in one environment and a different one in another.

Is this a bug? or a feature that should be added?

**Comment by joejulian** [comment]
The Chart.yaml is not a template. It will not be processed by the template engine.

**Comment by yonahd** [comment]
@joejulian let me clarify, I'm referring to these conditions reffered here https://helm.sh/docs/chart_best_practices/dependencies/

**Comment by joejulian** [comment]
Ah, sorry, I read the description and was thrown off by the phrasing.

I do wonder if you're experiencing this same issue: https://github.com/helm/helm/issues/3796#issuecomment-1440237593

**Comment by yonahd** [comment]
No. This is only one condition and this is not during deploy, it is during the dependency update.

**Comment by yonahd** [comment]
@joejulian Should this have a bug label?

**Comment by joejulian** [comment]
I don't think this is a bug. `helm dependency update` is not designed to only update some dependencies. In order to help me understand the impact of what you're asking, let me ask this: why would it matter if all dependencies are updated?

**Comment by yonahd** [comment]
My use case is when the dependency is the same just with a different version as follows:
```
dependencies:
- name: nginx
  version: "1.3.1"
  condition: is.stg
- name: nginx 
  version: "1.2.1"
  condition: is.prd
```
This is especially useful when using library Charts

**Comment by joejulian** [comment]
I believe this is when to use aliases.

**Comment by yonahd** [comment]
Can you give an example of how an alias would solve this?

**Comment by joejulian** [comment]
If you alias the different versions:
```
dependencies:
- name: nginx
  version: "1.3.1"
  condition: is.stg
  alias: nginx-staging
- name: nginx 
  version: "1.2.1"
  condition: is.prd
  alias: nginx-production
```
Then you would set your condition and only the desired version is templated.

This would mean having values under nginx-production and under nginx-staging or using global values if the charts support that.

If they don't, you can do some more advanced tricks using File and template, but that's more advanced than I'd be willing to describe in a issue comment.

You can look at https://github.com/redpanda-data/helm-charts/blob/3fafe828012819f5147419b45f9460b05f3c151e/charts/redpanda/templates/console/deployment.yaml#L123 for inspiration though.
