### ISSUE TITLE
helm cannot replace a specified env value, only replace all env values when using parent chart values to replace sub chart values

### ISSUE THREAD

**Issue by Pual97** [helm/helm#11862]
### Description

helm cannot replace a specified env value, only replace all env values when using parent chart values to replace sub chart values

### How to reoccurrence <br><br>

**sub chart values**
```
subChart:
    env:
        - name: aaa
          description: "aaa"
          value: "true"
        - name: bbb
          description: "bbb"
          value: "true"
        - name: ccc
          description: "ccc"
          value: "true"
```

**sub chart  deployment** 
```
...

{{- range $k,$v  := .Values.env }}
  {{printf "code = '%s'; value = %s;" $v.name $v.value  | indent 2}}
{{- end }}

...
```

**parent chart values**

```
subChart
  env:
      - name: aaa
        description: "aaa"
        value: "false"
```

It is expected that only the value of the env aaa will be replaced, as like 

**sub chart  deployment** 
```
...
code = aaa; value = false;
code = bbb; value = true;
code = ccc; value = true;
...
```

But the actual result is when template is executed

**sub chart  deployment** 
```
...
code = aaa; value = false;
...
```

Is this my use problem or a bug? I don't seem to have seen the corresponding description on the official website

**Comment by joejulian** [comment]
From a purely yaml standpoint, how would you merge that?

```
subChart:
    env:
        - name: aaa
          description: "aaa"
          value: "true"
        - name: bbb
          description: "bbb"
          value: "true"
        - name: ccc
          description: "ccc"
          value: "true"
```

merged with 

```
subChart:
    env:
        - name: bbb
          description: "bbb"
          value: "false"
```

either replaces the list (observed behavior) or replaces the first item in the list which would result in:

```
subChart:
    env:
        - name: bbb
          description: "bbb"
          value: "false"
        - name: bbb
          description: "bbb"
          value: "true"
        - name: ccc
          description: "ccc"
          value: "true"
```

If you're interested in how values merge, see https://github.com/helm/helm/blob/e007c900ce5f2233c8583565d5ba1b0433b1a213/pkg/chartutil/coalesce.go#L159-L188
