### ISSUE TITLE
missing required field : podSelector for networkPolicy in Helm but no problem with OpenShift 

### ISSUE THREAD

**Issue by jc305697** [helm/helm#11895]
Output of `helm version`:
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"1928ac4250660378a7d8c3430478dfe77977cb2a", GitTreeState:"clean", BuildDate:"2022-12-07T05:08:22Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+deccab3", GitCommit:"eddac29feb4bb46b99fb570999324e582d761a66", GitTreeState:"clean", BuildDate:"2023-02-07T15:05:37Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Openshift Container Platform 4.11.29

Hello I have encountered a weird problem with helm when doing a  helm install using this template: 
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
spec:
  podSelector:
  ingress:
  - from:
    - podSelector: {} 
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-kube-apiserver-operator
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-kube-apiserver-operator
      podSelector:
        matchLabels:
          app: kube-apiserver-operator
  policyTypes:
  - Ingress
```

During the helm install I get this error for both NetworkPolicy: 
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(NetworkPolicy.spec): missing required field "podSelector" in io.k8s.api.networking.v1.NetworkPolicySpec
`

Though when I do an oc apply on these network policies openshift doesn't give an error nor a warning and it creates the network policies. 

I am unsure if this is a bug or a feature. 

I was able to do an helm install with the corrected policies: 
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-kube-apiserver-operator
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-kube-apiserver-operator
  podSelector:
    matchLabels:
      app: kube-apiserver-operator
  policyTypes:
  - Ingress
```

I tought it might be worthwhile to signal this because since it might be a bug or just a difference in parsing between OpenShift and upstream K8s that I am not aware of. 

I couldn't find something similar in the helm-users slack channel. 

If it helps these policies come from the following openshift documentation: https://docs.openshift.com/container-platform/4.12/networking/network_policy/multitenant-network-policy.html
