### ISSUE TITLE
Aliased subchart annotations leaking to another alias

### ISSUE THREAD

**Issue by romeuhcf** [helm/helm#11891]
I have this Chart.yaml
```yaml
apiVersion: v2
name: inf-traefik
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: traefik
    version: ">0"
    repository: https://helm.traefik.io/traefik
    alias: traefik-external
  - name: traefik
    version: ">0"
    repository: https://helm.traefik.io/traefik
    alias: traefik-internal
```
And this values.yaml
```yaml
traefik-external:
  ingressRoute:
    dashboard:
      annotations:
        kubernetes.io/ingress.class: traefik-ext

  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "*.lb-ext.alpha.example.com"


traefik-internal:
  ingressRoute:
    dashboard:
      annotations:
        kubernetes.io/ingress.class: traefik-int

  service:
    name: traefik-int
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "*.lb-int.alpha.example.com"
```

When running template I would expect that each aliased subchart receives only its specific values. But rendering the template, I get both services with same value.

```
❯ helm template . | grep hostname:
    external-dns.alpha.kubernetes.io/hostname: '*.lb-int.alpha.example.com'
    external-dns.alpha.kubernetes.io/hostname: '*.lb-int.alpha.example.com'
```
Where I'd expect to have
```
❯ helm3 template . | grep hostname:
    external-dns.alpha.kubernetes.io/hostname: '*.lb-ext.alpha.example.com' # not an actual result
    external-dns.alpha.kubernetes.io/hostname: '*.lb-int.alpha.example.com'
```

Interesting enough, other sections don't get mixed:

```
❯ helm3 template . | grep ingress.class:
    kubernetes.io/ingress.class: traefik-ext
    kubernetes.io/ingress.class: traefik-int
```

Initially I was leaning to think it is a traefik helm chart issue, but I think that ,by design, each alias shouldn't have access to other alias values. Or should it?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T16:01:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  not applicable

**Comment by joejulian** [comment]
With the following chart that only outputs the values in a one-line template, I get each value where it belongs:

```
$ helm template .
---
# Source: foo/charts/bar-none/templates/values.yaml
values: 
  global: {}
  myvalue: 2
---
# Source: foo/charts/bar-some/templates/values.yaml
values: 
  global: {}
  myvalue: 1
```

[foo.tar.gz](https://github.com/helm/helm/files/10962884/foo.tar.gz)

If you can find a way to duplicate your issue with this chart, please share. As it is now, I cannot duplicate the issue.

**Comment by romeuhcf** [comment]
Hey @joejulian , sorry for the late response. Attached follows the smaller reproducible code I could provide.

Notice that playing with `foo/values.yaml`,  changing it to: 
```yaml
bar-some:
  aaa:
    baz: some
bar-none:
  aaa:
    baz: none
  bbb:
    baz2: none2

```
resulted in the expected content:
```yaml
---
# Source: foo/charts/bar-none/templates/values.yaml
baz: none
baz2: none2
---
# Source: foo/charts/bar-some/templates/values.yaml
baz: some
```
While with the content:
```yaml
bar-some:
  aaa:
    baz: some
bar-none:
  aaa:
    baz: none

```

I get the wrong output:

```yaml
---
# Source: foo/charts/bar-none/templates/values.yaml
baz: some
---
# Source: foo/charts/bar-some/templates/values.yaml
baz: some

```
[foo-reproduced.tar.gz](https://github.com/helm/helm/files/11186848/foo-reproduced.tar.gz)

**Comment by joejulian** [comment]
This has to do with how you're using the [merge function](http://masterminds.github.io/sprig/dicts.html#merge-mustmerge).

With this template file you can see what's happening a little better:
```
Values: {{- toYaml .Values | nindent 2 }}
merged:
  {{- with (merge .Values.bbb .Values.aaa) }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
```

which produces
```
# Source: foo/charts/bar-none/templates/values.yaml
Values:
  aaa:
    baz: none
  bbb:
    baz: some
  global: {}
merged:
  baz: some
---
# Source: foo/charts/bar-some/templates/values.yaml
Values:
  aaa:
    baz: some
  bbb: {}
  global: {}
merged:
  baz: some
```

You're always merging bbb on top of aaa. When bbb is empty, aaa is kept.
