### ISSUE TITLE
How to deploy dependency chart in specific namespace

### ISSUE THREAD

**Issue by Dotisandhyarani** [helm/helm#11900]
I wanted to deploy the Helm chart using flux.  

Here is the **chart.yaml** file

```
apiVersion: v2
name: kubernetes-dashboard
description: A Helm chart for Kubernetes

type: application
version: 0.1.18
appVersion: "v2.7.0"

dependencies:
  - name: metrics-server
    version: 3.8.3
    repository: https://kubernetes-sigs.github.io/metrics-server/
    condition: metrics-server.enabled

```

here is the **HelmRelease.yaml**
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  install:
    disableWait: true
  upgrade:
    disableWait: true
  interval: 5m
  chart:
    spec:
      chart: ./charts/src/common/kubernetes-dashboard/
      sourceRef:
        kind: GitRepository
        name: fleet-infra
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: kubernetes-dashboard
      valuesKey: values.yaml

```
The dependency deploy to `flux-system` namespace, but I wanted to deploy it to `kubernetes-dashboard` namespace.

How to deploy the dependency 'metrics-server' from `chart.yaml` into `kubernetes-dashboard` namespace.
