### ISSUE TITLE
How can I override the `repository:` field of sub-dependencies?

### ISSUE THREAD

**Issue by justinmchase** [helm/helm#11925]
My company has a pretty aggressive firewall, its blocking all major helm repositories and they make use use an Artifactory mirror instead.

This generally works with `helm repo add ...` and using the new url. However one particular dependency I have, has a dependency of its own and in their Chart.yaml it has a full path to the repository:

https://github.com/bitnami/charts/blob/main/bitnami/nginx-ingress-controller/Chart.yaml#L8

```yml
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
```

Is there a way to override the repository of a sub-dependency to tell it to use the mirror instead?
