### ISSUE TITLE
helm generate different spec when using repo vs local directory

### ISSUE THREAD

**Issue by tanvp112** [helm/helm#11976]
Run the following command to re-produce the issue:

_helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server
helm template metrics-server metrics-server/metrics-server --set addonResizer.enabled=true | grep volumes -A 6_

```
volumes:
  - name: tmp
    emptyDir: {}      # Notice the missing volume spec. See below.
```

The missing volume is due to the ["if" statement in the deployment template](https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/templates/deployment.yaml#L124) is NOT evaluated correctly.

Now, try this:

_helm repo remove metrics-server
git clone https://github.com/kubernetes-sigs/metrics-server.git
helm template metrics-server ./metrics-server/charts/metrics-server --set addonResizer.enabled=true | grep volumes -A 6_

```
volumes:
  - name: tmp
    emptyDir: {}
  - name: nanny-config-volume      # <-- now it correctly evaluated the if statement and generated the volume spec
    configMap:
      name: metrics-server-nanny-config
```

Anyone knows why helm generate the manifest differently? This issue has caused helm to fail to deploy.

Output of `helm version`:
`version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.18.10"}
`

Output of `kubectl version`:
```
clientVersion:
  buildDate: "2023-03-15T13:39:54Z"
  compiler: gc
  gitCommit: 0ce7342c984110dfc93657d64df5dc3b2c0d1fe9
  gitTreeState: clean
  gitVersion: v1.25.8
  goVersion: go1.19.7
  major: "1"
  minor: "25"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2023-03-20T21:32:06Z"
  compiler: gc
  gitCommit: 83fe90de881ffe7450876d204ccdc37a0f95bda3
  gitTreeState: clean
  gitVersion: v1.25.8-eks-ec5523e
  goVersion: go1.19.7
  major: "1"
  minor: 25+
  platform: linux/amd64
```

**Comment by wujunwei** [comment]
The package in repo  https://kubernetes-sigs.github.io/metrics-server is not same as  https://github.com/kubernetes-sigs/metrics-server.git
you can use `helm pull metrics-server/metrics-server --untar` to download the package whose deployment.yaml shows as below:
```yaml
 volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
```

And `extraVolumes`  in values.yaml is empty array.
