### ISSUE TITLE
Relative Repository dependencies

### ISSUE THREAD

**Issue by s-geiger-si** [helm/helm#11981]
At the time of this writing helm is at version 3.11.1.

My use case is the following, I have multiple helm charts (i.e., backend, frontend, wrapper) and I would like that `wrapper` depends on the `backend` and `frontend` charts, so that I can deploy the wrapper chat and that pulls in the backend and the frontend chart.

I understand that in order to declare a dependency in a helm chart I can use the helm dependencies mechanism as explained in https://helm.sh/docs/helm/helm_dependency/#helm:

```
# Chart.yaml for wrapper
dependencies:
- name: backend
  version: "1.2.3"
  repository: "https://example.com/charts"
- name: frontend
  version: "1.2.3"
  repository: "https://example.com/charts"
```

However, this requires that I write absolute repository URLs for each dependency. As I understand it, this breaks relocatability of the charts since the repository URL is now a fixed part of the chart. I would like to write my charts in a way that makes them relocatable, so that I can push them to different repositories, without having to modify their implementation.

Is there a way that I can declare relative dependencies to charts that are stored in the same repository, such as

```
# Chart.yaml for wrapper, desired feature
dependencies:
- name: backend
  version: "1.2.3"
  repository: "."   # alternatively omit key?
- name: frontend
  version: "1.2.3"
  repository: "."
```

If the wrapper chart lives in "https://example.com/charts/wrapper" then helm would automatically try to resolve the frontend at `https://example.com/charts/frontend", etc.

Is this possible with current helm or is there a reason why this is not supported at the moment?
