### ISSUE TITLE
Take values as defaults from another list if values are not defined in current list

### ISSUE THREAD

**Issue by malcolm061990** [helm/helm#12012]
Hi.
I have `values.yaml` with default values:
```yaml
scheduleJob:
  vault:
    kvSecret:
      - path: path1
        secrets: # secrets field defined
          - secret1
          - secret2
```
and `dev.yaml` with overwritten values:
```yaml
scheduleJob:
  vault:
    kvSecret:
      - path: path2 # secrets field not defined but we want to use secrets field from values.yaml
```
I need to use `secrets` values from `values.yaml` in result output if the `secrets` values are not defined in  `path: path2` in `dev.yaml`:
```yaml
scheduleJob:
  vault:
    kvSecret:
      - path: path2 # taken from dev.yaml
        secrets: # taken from values.yaml because its not defined in dev.yaml
          - secret1
          - secret2
```
Is it possible or technically it's not logic? :)
We don't want to copy/paste `secrets` field in all environments files
Output of `helm version`: version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}
