### ISSUE TITLE
Unexpected "shared resource"

### ISSUE THREAD

**Issue by katarzynainit** [helm/helm#12011]
Hi

I have observed a strange behavior of Helm, related to ownership of the resources. Please help me understand if this is expected or a bug. I'm also aware of the fact, that described use case is not a valid helm usage.

Steps to reproduce:
1. I have created two empty Charts: `test-a` and `test-b` (`helm create <name>`)
2. In both, I have removed everything, leaving only unchanged Chart.yaml, .helmignore 
3. In both, I have added service.yaml under templates/ with such content (it can be any resource you prefer):
```
apiVersion: v1
kind: Service
metadata:
  name: test-service    # please mind, that I use the same name of the service in both charts
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: test-app-A       #in test-b chart the value is: test-app-B
```
4. I call `helm install test-a ./test-a` - service is created, with such annotations:
```
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: test-a
    meta.helm.sh/release-namespace: <my_namespace>
  labels:
    app.kubernetes.io/managed-by: Helm
...
  selector:
    app: test-app-A
```
5. I run `helm install test-b ./test-b` and receive expected error
```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. 
Unable to continue with install: Service "test-service" in namespace "<my-namespace>" exists 
and cannot be imported into the current release: 
invalid ownership metadata; annotation validation error: 
key "meta.helm.sh/release-name" must equal "test-b": current value is "test-a"
```
6. So, (as advanced user) I either remove the service manually or update annotation to "test-b"
7. Now `helm install test-b ./test-b` works without errors, and the service contains `-b` related annotations and selector:
```
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: test-b
    meta.helm.sh/release-namespace: <my_namespace>
  labels:
    app.kubernetes.io/managed-by: Helm
...
  selector:
    app: test-app-B

```
8. --- Until now, all works as expected ---
9. Now I run `helm upgrade test-a ./test-a` - all works:
```
Release "test-a" has been upgraded. Happy Helming!
NAME: test-a
LAST DEPLOYED: Thu Apr 20 12:27:14 2023
NAMESPACE: <my-namespace>
STATUS: deployed
REVISION: 2
TEST SUITE: None
```
and service now is `-a` related
10. So, another upgrade `helm upgrade test-b ./test-b`, and again Happy Helming, and service is now `-b` related

**So my question is:** Is that expected that both charts can change this resource, regardless ownership annotations?

-------- 
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE
