### ISSUE TITLE
why doesn't `helm lint` fail for missing values in nested maps

### ISSUE THREAD

**Issue by ntextreme3** [helm/helm#12014]
When trying to reference a value that doesn't exist, I'd expect `helm lint` to fail. Example:

```yaml
# values.yaml
service:
  type: ClusterIP
  port: 80
```

```yaml
# templates/service.yaml
  ports:
    - port: {{ .Values.service.port }}
      something: {{ .Values.service.doesNotExist }}
```

Full repo with example: https://github.com/ntextreme3/helm-lint-nested-map-issue/commit/28f037dcf98fc994d9d544618ec62ecb89509346

Reproduce:

1.  `helm create helm-lint-nested-map-issue`
2. `cd helm-lint-nested-map-issue`
3. Update `templates/service.yaml` to reference a value in a nested map that doesn't exist (e.g. `.Values.service.doesNotExist`) 
4. `helm lint --strict .` does not fail

If you go deeper into the nesting, it _does_ fail. So it seems as long as the top-level map exists, it doesn't fail on its keys. Example:

```yaml
  ports:
    - port: {{ .Values.service.port }}
      something: {{ .Values.service.doesNotExist.alsoDoesNotExist }}
```

```sh
$ helm lint .
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: helm-lint-nested-map-issue/templates/service.yaml:11:27: executing "helm-lint-nested-map-issue/templates/service.yaml" at <.Values.service.doesNotExist.alsoDoesNotExist>: nil pointer evaluating interface {}.alsoDoesNotExist

Error: 1 chart(s) linted, 1 chart(s) failed
```

Output of `helm version`: 

```
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}
```

Also, I came across JSON Schema validation while digging into this https://helm.sh/docs/topics/charts/#schema-files -- but would only go that route if this is the expected behavior.
