### ISSUE TITLE
Helm parent chart add extra field and overwrite field for the child chart.

### ISSUE THREAD

**Issue by shanzhengliu** [helm/helm#12049]
Hi, 

now I have a requirement. I have a basic chat as a subchart like
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80  

```

and I would like to use the parent chart to add like 
```
        volumeMounts:
         - name: config-volume
           mountPath: /usr/share/nginx/html/assets/
      volumes:
        - name: config-volume
          configMap:
            name: myconfigmap   
```

So what I expect the final compute will like 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
         - name: config-volume
           mountPath: /usr/share/nginx/html/assets/
      volumes:
        - name: config-volume
          configMap:
            name: myconfigmap     
```

any solutions in this moment we can achieve that ?

Output of `v3.11.2`:

Output of `v1.25.6`:

Cloud Provider/Platform (AKS):
