### ISSUE TITLE
Inconsisent Output using helm.sh/resource-policy: keep

### ISSUE THREAD

**Issue by matt314** [helm/helm#12048]
I've noticed some inconsistency with how the `helm.sh/resource-policy` annotation works. Using this template:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: keepme
---
apiVersion: v1
kind: Namespace
metadata:
  name: deleteme
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    helm.sh/resource-policy: whatever
  name: deletemetoo
---
apiVersion: v1
data:
  key: |
    House
kind: ConfigMap
metadata:
  name: key
  namespace: deleteme
  annotations:
    helm.sh/resource-policy: keep
```

Then when I uninstall, the output is:
```
% helm uninstall delete
These resources were kept due to the resource policy:
[ConfigMap] key
[Namespace] keepme

release "delete" uninstalled
```

However, a few unexpected things happen:
- The namespace `deletemetoo` isn't mentioned in the output, but is retained. My guess is it's a logic error where the output function checks the value of the annotation == keep, but the delete function skips deletion as long as the annotation exists regardless of value.
```
% oc get ns keepme deleteme deletemetoo
NAME          STATUS   AGE
keepme        Active   4m40s
deletemetoo   Active   4m41s
Error from server (NotFound): namespaces "deleteme" not found
```
  - I'd like to see the delete function check the value and only keep when it's set to `keep`. That seems like the intuitive behavior anyway, but it also allows a chart upgrade to later set that annotation to something else, and a second upgrade to remove it entirely.

- The ConfigMap is deleted despite `helm.sh/resource-policy: keep`; this is reasonable since the containing namespace is being deleted. Perhaps helm should either retain the namespace or issue a warning. Or add a doc note explaining this case instructing the user to make sure to annotate the namespace if helm controls it.
```
% oc get cm -n deleteme key
Error from server (NotFound): namespaces "deleteme" not found
```

Thanks!

Output of `helm version`:
`version.BuildInfo{Version:"v3.11.3", GitCommit:"66a969e7cc08af2377d055f4e6283c33ee84be33", GitTreeState:"clean", GoVersion:"go1.20.3"}`

Output of `kubectl version`:
```yaml
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.24.12+ceaf338
WARNING: version difference between client (1.27) and server (1.24) exceeds the supported minor version skew of +/-1
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
Openshift 4.11.37
```
