### ISSUE TITLE
Unable to get the variables defined in range function in  .Files.Lines helper

### ISSUE THREAD

**Issue by ajaykanse** [helm/helm#12078]
I have scenario, where values.yaml includes array which indicates file names to loop over and using Files.Lines I want to add the contents of the file in the resource route.

There is files folder which has file1 and file2 files under chart. 

Below is values.yaml file.
```
namespace: sprint

appGrpName: test
env: dev 

virtualWebHosts:
- file1
- file2

virtualSvcHosts:
- sprint-xxx-svc
```
Below is route.yaml :
```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
 name: {{ $webHost }}
spec:
 host: {{ $webHost }}
 path: "/web"
 to:
  kind: Service
  name: {{ $.Values.appGrpName }}-{{ $.Values.env }}-web
  certificate: |
   {{- with $webHost }}
   {{- range $.Files.Lines "files/{{ $webHost }}" }}    <=== unable to get the variable resolved
   {{ . }} {{ end }} {{ end }}
{{ end }}
```

Output: ( As you see below certificate field is empty in route resource )
```
# Source: sample/templates/route.yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
 name: file1
spec:
 host: file1
 path: "/web"
 to:
  kind: Service
  name: test-dev-web
  certificate: |
```
---
```
# Source: sample/templates/route.yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
 name: file2
spec:
 host: file2
 path: "/web"
 to:
  kind: Service
  name: test-dev-web
  certificate: |
```

So the question is how do we get the $webHost variable resolved inside Files.Lines function ?
If I replace files/{{ $webHost }}" with files/file1" i see the contents of file in certificate field.
