### ISSUE TITLE
Camel Case function is broken since 3.11.2

### ISSUE THREAD

**Issue by JMoserCricut** [helm/helm#12081]
the CamelCase function appears to be broken as of 3.11.2, as described in the [docs](https://helm.sh/docs/chart_template_guide/function_list/#camelcase) it should take snake case and return camel case. However at least with an all caps snake case it now just returns with out the underscores.

The docs seem to mention that we have to get to kebabcase by first going through camel case, but this test below seems to show that it's not needed anymore.

Here's the template:
``` yaml
metadata:
  name: {{ camelcase $key | kebabcase }}
  annotations:
    name: {{ $key }}
    camelName: {{ camelcase $key }}
    kebabName: {{ kebabcase $key }}
```

and the output:
``` yaml
metadata:
  name: asdfqwerpoiu
  annotations:
    name: ASDF_QWER_POIU
    camelName: ASDFQWERPOIU
    kebabName: asdf-qwer-poiu
```

Output of `helm version`:
3.11.2

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.10-eks-48e63af", GitCommit:"9176fb99b52f8d5ff73d67fea27f3a638f679f8a", GitTreeState:"clean", BuildDate:"2023-01-24T19:17:48Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS
