### ISSUE TITLE
Helm upgrade doesn't uninstall old resource properly

### ISSUE THREAD

**Issue by suxiaoxiaomm** [helm/helm#12085]
Hi Dear Experts,
I am currently trying to install a Knative Service via helm charts.

I want to use a helm value(as below "knativeService") to control whether to deploy a Knative Service or a normal deployment + normal service.
When the "knativeService" is equal to "true", it will deploy knative Service, otherwise, it deploy a normal deployment + normal service.

However, during the switch( I am using the command: **helm upgrade -i** ), it will stuck at uninstall knativeService.

It seems when using Knative Service, there is an ExternalName type k8s service will be created. When I switch to a normal k8s deployment, it will also try to create a k8s service which has the same name as previous ExternalName service.

This caused the Knative controller confused and reporting error. And thus, the Knative Service CR cannot be uninstalled successfully: Similarly, If I want to switch from normal k8s deployment to Knative Service, still go problems.

But I can do helm uninstall first, then try to do install. This would properly switch.

**So I am wondering:**
**1. What is the mechanism for using "helm upgrade"? Does it uninstall unnecessary old resource first, then try to install the new resource?** 
**2. Is there a way to guarantee the upgrade workflow's order to make sure the unnecessary resources got delete first?**

Appreciate any suggestions!

Below is my helm template:

```
---
{{ if eq .Values.knativeService "true" }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
      - name: {{ $container }}
        image: {{ $registry }}/{{ $container }}:{{ (tuple $scope ( index $imageVersionsList $i)) | include "imageVersion" }}

{{ else }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - name: http-web
      port: 80
      targetPort: {{ default "80" .Values.servicePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ $container }}
        image: {{ $registry }}/{{ $container }}:{{ (tuple $scope ( index $imageVersionsList $i)) | include "imageVersion" }}
        imagePullPolicy: "Always"

{{ end }}

```
