### ISSUE TITLE
kindIs returns false when documentation says it should return true

### ISSUE THREAD

**Issue by NeodymiumFerBore** [helm/helm#12084]
## Description

`{{ if kindIs "int" 123 }}` returns false when [documentation says it should return true](https://docs.helm.sh/docs/chart_template_guide/function_list/#reflection-functions).

## How to reproduce

Reproduce this sample Chart:

<details>
  <summary>Sample Chart</summary>

> Chart.yaml
```
version: 1
name: test
```

> values.yaml
```
env:
  myVarA: text
  myVarB: false
  myVarC: true
  myVarD: 123
  myVarE: 5.5
  myVarF: ["a", "b"]
  myVarG:
    someStuff:
      a: b
```

> templates/test.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
{{- with .Values.env }}
{{- range $k, $v := . }}
{{- if or (kindIs "string" $v) (kindIs "int" $v) (kindIs "bool" $v) }}
  {{ $k }}: {{ $v }}
{{- end }}
{{- end }}
{{- end }}
```
</details>

Render the sample Chart: `helm template ./ -f values.yaml`

> Output
```
---
# Source: test/templates/test.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  myVarA: text
  myVarB: false
  myVarC: true
```

## Excepted result

`myVarD: 123` should appear in the output, [as stated in the documentation](https://docs.helm.sh/docs/chart_template_guide/function_list/#reflection-functions).

If I change the condition to `kindIs "float64" 123`, it returns `true`. While it may suit some needs, I don't want to have floating numbers included in my output.

## Issue

Could you please either:
- fix the documentation
- fix the `kindIs` function
- explain/document why it behaves like this if it's intended

## Environment

Output of `helm version`: `version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}`

Same behavior with Helm `v3.8.0-linux-amd64` and `v3.11.3-linux-amd64`.

Output of `kubectl version`: None (local templating)

Cloud Provider/Platform (AKS, GKE, Minikube etc.): None (local templating)
