### ISSUE TITLE
v3.6 & v3.10 repeat deployment of job failing using helm

### ISSUE THREAD

**Issue by 30goingon50** [helm/helm#12092]
Output of `helm version`:
`version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}`

Output of `kubectl version`:
```
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"dc2f9dc64421983f0f7839da8ab4ab6d4673daad", GitTreeS
tate:"clean", BuildDate:"2023-04-08T13:29:19Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

Issue: 
- Deploy helm chart which has a job manifest: works
- Redeploying same helm chart fails on the job manifest below
- Deploying, reconfiguring and redeploying the same job manifest directly with kubectl does **NOT** exibit the same errors

Context:
I have a chart which is deploying resources for keda to use (i.e. keda has been installed and is the controller for these). I wanted to be able to redeploy the said charts. I had ran in to an issue with one of the charts where by when redeploying it would say the spec.template was immutable and so I added the --force flag to my helm upgrade command so that instead of attempting to upgrade them, it would remove and then redeploy new job manifests. This corrected my issue with the other manifests but the manifest below was throwing errors related to selectors. **Note** when this job is deployed, keda assigns a 

Error:
`failed to replace object: Job.batch "name-of-my-job" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"name-of-my-job"}: `selector` does not match template `labels`, spec.selector: Invalid value: "null": field is immutable, spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"",`

Helm Deploy Command:
```
      helm upgrade `
        --install repoName ./repoName `
        --namespace repoName `
        --values $overridesPath `
        --create-namespace `
        --force `
        --debug
```

Job Manifest:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: name-of-my-job
spec: # JOB SPEC
  # selector:
  #   matchLabels:
  #     app: name-of-my-job
  backoffLimit: 10
  template: # POD Template
    metadata:
      labels:
        app: name-of-my-job
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec: # POD SPEC
      serviceAccountName: some-service-account-name
      restartPolicy: OnFailure
      containers:
        - name: name-of-my-job
          image: someazureacr.azurecr.io/linux:someimage-50501.1
          resources:
            requests:
              memory: 600Mi
              cpu: 200m
            limits:
              memory: 700Mi
              cpu: 1000m
          env:            
            - name: IS_STANDALONE
              value: "true"
            - name: ENV_VARIABLES_FOR_CONTAINER
               value: SOME_VALUE        

          volumeMounts:
          - name: some-volume-mount
            mountPath: "/somepath/somepath"
            readOnly: true
      volumes:
      - name: some-volume-name
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            anAttributeName: someValue
      nodeSelector:        
        "kubernetes.azure.com/agentpool": linux
```
