### ISSUE TITLE
Value in values.yaml is trimmed in helm template output

### ISSUE THREAD

**Issue by bczudek** [helm/helm#12090]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.18.10"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+rke2r2", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-10-04T22:39:02Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Rancher

Problem statement: helm trims '0' when substituting values

How to reproduce:
1. templates: single pod with following syntax:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
  - name: ctr-example
    image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag_major }}.{{ .Values.image.tag_minor_patch }}"
```
2. values.yaml:
```
image:
  registry: registry.address
  repository: repo-name
  tag_major: 1
  tag_minor_patch: 0.34370
```

please pay attention to the value of tag_minor_patch
now run:
```
helm template helm . -f values.yaml
```
and see the result:
```
---
# Source: example/templates/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
  - name: ctr-example
    image: "registry.address/repo-name:1.0.3437"
```
**image value is missing 0 at the end**

see other scenarios for values.yaml and helm template:
tag_minor_patch: 0.343701 -> image: "registry.address/repo-name:1.0.343701"
tag_minor_patch: 0.34371 -> image: "registry.address/repo-name:1.0.34371"

expected behavior:
tag_minor_patch: 0.34370 -> image: "registry.address/repo-name:1.0.34370"

regards,
Bartek
