### ISSUE TITLE
Templating nested subcharts with values.schema.json and using aliases has erratic behavior

### ISSUE THREAD

**Issue by tmsdce** [helm/helm#12100]
Output of `helm version`:

`version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}`

Output of `kubectl version`:

`Client Version: v1.27.2`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): RKE

Hi,

This issue seems quite intricate and I may be missing something here. When using `helm template` on a chart with at least 2 levels of nested subcharts dependencies that are using schema validation, I have two different behaviors if I use the `-f values.yaml` option or not.

### Steps to reproduce

- Create a `Chart.yaml` file with the following content
```
apiVersion: v2
name: test-nested-subcharts
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: splunk-otel-collector
  repository: https://signalfx.github.io/splunk-otel-collector-chart
  version: 0.76.0
```
The `splunk-otel-collector` chart also has dependencies (on cert-manager and opentelemetry-operator) + ships with a [values.schema.json file](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/values.schema.json) + uses aliases in its [dependencies declaration](https://github.com/signalfx/splunk-otel-collector-chart/blob/eb4ba48bad7bfa90a7442f43d276c7567f2f9072/helm-charts/splunk-otel-collector/Chart.yaml#L20)
- Create a simple `values.yaml` file to comply with the required values specified in the splunk-otel-collector chart's `values.schema.json` file
```
splunk-otel-collector:
  clusterName: mycluster
  splunkObservability:
    realm: eu0
    accessToken: dummy
```
- Build dependency using `helm dependency update`
- Try to generate a template with the following command
```
helm template --name-template testing --namespace test --include-crds -f values.yaml .
```
Templates are correctly generated
- Try to generate a template **without** the `-f values.yaml` option
```
helm template --name-template testing --namespace test --include-crds .
```
This fails with the following error:
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
splunk-otel-collector:
- (root): Additional property cert-manager is not allowed
- (root): Additional property opentelemetry-operator is not allowed
```

### Expected behavior

The two template commands should return the same result, correctly generating the templates.

### Actual behavior

It seems that values processing differs when using the `-f` option or not in this specific case (i.e. using nested subcharts with aliases and schema validation). The error implies that the aliases are not correctly propagated when omitting the `-f` option.
The schema validation in the splunk-otel-collector chart is strict in that it explicitly sets `"additionalProperties": false`. When I manually set it to true, the two template commands generate the same set of templates without any issues and values are correctly interpolated.

Again, this seems quite intricate and may be an unusual use-case. It may not even be directly related to helm and more to the schema validation of the splunk-otel-collector chart but I need this to be clarified.
