### ISSUE TITLE
Cannot access $ in template

### ISSUE THREAD

**Issue by caibirdme** [helm/helm#12115]
Output of `helm version`:  v3.12.0

Output of `kubectl version`: none

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  mac

mininal reproducable example:

./templates/foo/configmap.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: qwe
{{- include "hello.configmap" .Values.qq }}
```

./templates/_helper.tpl
```yaml
{{- define "hello.configmap" -}}
data:
  foo: |
    {{ .bar }}
    {{$.Values.foo}}
{{- end }}
```
values.yaml
```yaml
foo: "adasds"
qq:
  bar: "qqqq"
```

helm template .

outputs:
```
Error: template: example/templates/foo/configmap.yaml:6:4: executing "example/templates/foo/configmap.yaml" at <include "hello.configmap" .Values.qq>: error calling include: template: example/templates/_helpers.tpl:8:7: executing "hello.configmap" at <$.Values.foo>: nil pointer evaluating interface {}.foo
```
