### ISSUE TITLE
When Using Alias in Helm Chart, .Chart.Name Becomes The Name of the Alias, Is This Correct?

### ISSUE THREAD

**Issue by v1ferrarij** [helm/helm#12142]
Output of `helm version`: 3.12.0

I have noticed when using an alias like below:

```yaml
# Chart.yaml
apiVersion: v2
name: devops-chart
version: 0.0.1
description: Helm Chart for DevOps Testing
dependencies:
  - name: python
    alias: devops-1
    version: 0.0.1
    repository: https://example.azurecr.io/helm/v1/repo/
  - name: python
    alias: devops-2
    version: 0.0.1
    repository: https://example.azurecr.io/helm/v1/repo/
```

```yaml
# values.yaml
devops-1:
  foo: bar
  bar: foo

devops-2:
   foo: bar
   bar: foo
```

The values of .Chart.Name become **devops-1** & **devops-2**, is this correct?

I would have thought the value should have been **python**, as that is the chart name and not the alias?
