### ISSUE TITLE
helm function getHostByName only returns single ip even if multiple exist

### ISSUE THREAD

**Issue by cratoo** [helm/helm#12146]
Output of `helm version`: version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}

Output of `kubectl version`: irrelevant

Cloud Provider/Platform (AKS, GKE, Minikube etc.): irrelevant but local k8s 1.25.6

I'm trying to create NetworkPolicies in my helm chart by supplying connections via variables. But apparently helm fails to correctly resolve a multi A-record DNS entry.

```
  - to:
    - ipBlock:
        cidr: {{ getHostByName somehost.local | quote }}
      ports:
        - protocol: TCP
          port: 80
```
This results in:
```
  - to:
    - ipBlock:
        cidr: "10.0.0.200"
      ports:
        - protocol: TCP
          port: 443
```
even if the host actually has 10.0.0.200 and 10.0.0.201 as its a records.
