### ISSUE TITLE
Updating an ingress fails if the name has changed

### ISSUE THREAD

**Issue by ferm10n** [helm/helm#12157]
Output of `helm version`: `version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5+k3s1", GitCommit:"7cefebeaac7dbdd0bfec131ea7a43a45cb125354", GitTreeState:"clean", BuildDate:"2023-05-27T00:05:40Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): k3s

Continuation of https://github.com/helm/helm/issues/11176, but that issue was closed because it went stale and didn't have an example.

Lets say you've deployed a helm chart with an ingress:
```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
        - path: /path
          pathType: Prefix
          backend:
            service:
              name: myservice
              port:
                number: 80
```

And then you try to update the helm chart and deploy it again with these modifications:
```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-updated-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: localhost
      http:
        paths:
        - path: /path
          pathType: Prefix
          backend:
            service:
              name: myservice
              port:
                number: 80
```

The only thing changed in this example is the name, but you could make additional changes to this.

Unfortunately attempting to do this fails with this message:
```
Error: UPGRADE FAILED: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "localhost" and path "/path" is already defined in ingress default/my-ingress
```

Likely explanation https://github.com/helm/helm/issues/11176#issuecomment-1539236102:
> As my knowledge for Helm is when helm upgrade is performed, helm add the existing resources which is not in current resource list to the toBeDeleted group, and helm will delete these resources first, then upgrade resources which have already existed in k8s cluster.
>
> For the scenario, since the upgraded ingress name is different from the ingress name existed in cluster, the existed ingress should be deleted by Helm first, then new ingress will created.
> For other resource type like Service/Deployment, the result is what we expected, so the question is why ingress behave different ?
