### ISSUE TITLE
Reference values inside values.yaml

### ISSUE THREAD

**Issue by davhdavh** [helm/helm#12168]
I seem to miss something fundamental in how helm/subchart works, because I cannot get value references inside values.yaml to work.

Chart.yaml:
```yaml
dependencies:
  - name: something
    version: 0.2.15
    repository: https://outsideMyControl.com
  - name: someOtherThing
    version: 1.2.15
    repository: https://outsideMyControl2.com
```

values.yaml:
```yaml
userSuppliedSecret: ""
something: # subchart config
  needsSecretInThisKey: {{ .Values.userSuppliedSecret }}
someOtherThing: # subchart config
  needsSecretInSomeOtherKey: {{ .Values.userSuppliedSecret}}
```

Or is something as trivial as having the top-level chart user just supply the secret once impossible?
