### ISSUE TITLE
Upgrading an helm installation with the same version leads to some recources to be eventually patched

### ISSUE THREAD

**Issue by lburgazzoli** [helm/helm#12178]
Output of `helm version`:

```
version.BuildInfo{
  Version:"v3.12.1", 
  GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", 
  GitTreeState:"clean", 
  GoVersion:"go1.20.5"
}
```

Output of `kubectl version`:

```yaml
clientVersion:
  buildDate: "2023-06-14T09:47:38Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: darwin/arm64
kustomizeVersion: v5.0.1
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

```
kind
```

I've noticed that when performing an empty upgrade. i.e. by trying to upgrade to the same version of a chart already installed, the process does not seems to be idempotent, as example, we can install [dapr](https://github.com/dapr/dapr) using its helm chart with the following command:

```
➜ helm upgrade --install dapr dapr/dapr \
--version=1.11 \
--namespace dapr-system \
--create-namespace \
--wait
```

Then if I try to upgrade the chart to the same version installed, I'd expect that nothing should have been changed, however the `helm upgrade` debug output does seems to report that some resources need a patch:

```
➜ helm upgrade --version=1.11  --debug dapr dapr/dapr 
upgrade.go:150: [debug] preparing upgrade for dapr
upgrade.go:158: [debug] performing update for dapr
upgrade.go:330: [debug] creating upgraded release for dapr
client.go:385: [debug] checking 35 resources for changes
client.go:678: [debug] Looks like there are no changes for ServiceAccount "dapr-injector"
client.go:678: [debug] Looks like there are no changes for ServiceAccount "dapr-operator"
client.go:678: [debug] Looks like there are no changes for ServiceAccount "dapr-placement"
client.go:678: [debug] Looks like there are no changes for ServiceAccount "dapr-sentry"
client.go:678: [debug] Looks like there are no changes for Secret "dapr-webhook-cert"
client.go:678: [debug] Looks like there are no changes for Secret "dapr-webhook-ca"
client.go:678: [debug] Looks like there are no changes for Secret "dapr-trust-bundle"
client.go:678: [debug] Looks like there are no changes for Secret "dapr-sidecar-injector-cert"
client.go:678: [debug] Looks like there are no changes for ClusterRole "dapr-injector"
client.go:678: [debug] Looks like there are no changes for ClusterRole "dapr-operator-admin"
client.go:687: [debug] Patch ClusterRole "dapr-placement" in namespace 
client.go:678: [debug] Looks like there are no changes for ClusterRole "dapr-sentry"
client.go:678: [debug] Looks like there are no changes for ClusterRoleBinding "dapr-injector"
client.go:678: [debug] Looks like there are no changes for ClusterRoleBinding "dapr-operator-admin"
client.go:678: [debug] Looks like there are no changes for ClusterRoleBinding "dapr-placement"
client.go:678: [debug] Looks like there are no changes for ClusterRoleBinding "dapr-sentry"
client.go:678: [debug] Looks like there are no changes for Role "dapr-injector"
client.go:678: [debug] Looks like there are no changes for Role "dapr-operator"
client.go:678: [debug] Looks like there are no changes for Role "secret-reader"
client.go:678: [debug] Looks like there are no changes for Role "dapr-sentry"
client.go:678: [debug] Looks like there are no changes for RoleBinding "dapr-injector"
client.go:678: [debug] Looks like there are no changes for RoleBinding "dapr-operator"
client.go:678: [debug] Looks like there are no changes for RoleBinding "dapr-secret-reader"
client.go:678: [debug] Looks like there are no changes for RoleBinding "dapr-sentry"
client.go:678: [debug] Looks like there are no changes for Service "dapr-api"
client.go:678: [debug] Looks like there are no changes for Service "dapr-webhook"
client.go:678: [debug] Looks like there are no changes for Service "dapr-placement-server"
client.go:678: [debug] Looks like there are no changes for Service "dapr-sentry"
client.go:678: [debug] Looks like there are no changes for Service "dapr-sidecar-injector"
client.go:678: [debug] Looks like there are no changes for Deployment "dapr-operator"
client.go:678: [debug] Looks like there are no changes for Deployment "dapr-sentry"
client.go:678: [debug] Looks like there are no changes for Deployment "dapr-sidecar-injector"
client.go:678: [debug] Looks like there are no changes for StatefulSet "dapr-placement-server"
client.go:687: [debug] Patch Configuration "daprsystem" in namespace dapr-system
client.go:687: [debug] Patch MutatingWebhookConfiguration "dapr-sidecar-injector" in namespace 
upgrade.go:165: [debug] updating status for upgraded release for dapr
Release "dapr" has been upgraded. Happy Helming!
```

However as you notice, some resources are patched:
1. ClusterRole "dapr-placement"
2. Configuration "daprsystem"
3. MutatingWebhookConfiguration "dapr-sidecar-injector"

The patch for `ClusterRole "dapr-placement"` is generated by the fact that the related `ClusterRole` has an empty rules section which seems not to be handled properly when helm computes the diff. Some additional info can be found on [slack](https://kubernetes.slack.com/archives/C0NH30761/p1685539949041009) 

The patch for `Configuration "daprsystem"` is generated because it looks like that helm detects that some annotations are missing and tries to re-add them, so the patch looks like 
```json
{
    "metadata": {
        "annotations": {
            "meta.helm.sh/release-name": "dapr",
            "meta.helm.sh/release-namespace": "dapr-system"
        },
        "labels": {
            "app.kubernetes.io/managed-by": "Helm"
        }
    }
}
```

However, when looking at the resource on Kubernetes, I noticed that all the labels and annotations reported as missing are actually present on the CR and as result the patch does not result in an actual change (not event the `resourceVersion` field changes)

The patch for `MutatingWebhookConfiguration "dapr-sidecar-injector"` seems to be about some ordering issues as the generated patch is:

```json
{
    "$setElementOrder/webhooks": [
        {
            "name": "sidecar-injector.dapr.io"
        }
    ],
    "webhooks": [
        {
            "name": "sidecar-injector.dapr.io",
            "rules": [
                {
                    "apiGroups": [
                        ""
                    ],
                    "apiVersions": [
                        "v1"
                    ],
                    "operations": [
                        "CREATE"
                    ],
                    "resources": [
                        "pods"
                    ]
                }
            ]
        }
    ]
}
```

However, as for the `Configuration "daprsystem"` patch, nothing actually change on the CR.

This has some side effect on tooling using helm as example, the [helm-operator provided by the operator-sdk](https://sdk.operatorframework.io/docs/building-operators/helm/) seems to end into an endless loop trying to reconciling resources as every time the operator tries to re-apply the helm chart to ensure the current cluster state has not drifted from the desired state, it detects a drift because helm reports some patches have been generated.

I would expect that an upgrade like this one would not result in any patch being generated.

**Comment by gjenkins8** [comment]
> The patch for ClusterRole "dapr-placement" is generated by the fact that the related ClusterRole has an empty rules section which seems not to be handled properly when helm computes the diff. Some additional info can be found on [slack](https://kubernetes.slack.com/archives/C0NH30761/p1685539949041009)

From slack:

I did some debugging and effectively, when helm computes the patch, it generates `{"rules":[]}` even if both the current and target have empty rules.

The patch is generated because in [this](https://github.com/helm/helm/blob/1c4885fce74d44b94a8b100f660cca4cc633176c/pkg/kube/client.go#L606) method, both the target and current  resources have the rules array defined as an empty array. However when the actual object is retrieved from Kubernetes, the rules field is set to nil hence a patch is generated.

**Comment by gjenkins8** [comment]
> The patch for Configuration "daprsystem" is generated because it looks like that helm detects that some annotations are missing and tries to re-add them, so the patch looks like

To confirm, the annotations are not missing? If they have been removed, I think it would be correct for Helm to re-add them.

> The patch for MutatingWebhookConfiguration "dapr-sidecar-injector" seems to be about some ordering issues as the generated patch is..

Are there other changes being made to this array (other than from Helm)? IIRC, generating patches for modified arrays are tricky. Because if there isn't additional metadata to define a "key" for the array, it isn't possible to meaningfully merge arrays.
    
But if the above isn't true (the array remains unmodified as a single element), it seems unusual (buggy) for Helm to create a patch here.


Thanks for the detailed report. I suspect you're correct, and none of the above scenarios should produce patches (and an operator should be able to short-circuit when it detects an empty patch set).

Are you able to build your operator against a local/modified version of the Helm SDK?

**Comment by lburgazzoli** [comment]
I think the operator behaves correctly at this stage as helm effectively generates some patches like if a drift is detected from some unknown (at least to me) reasons so I checked out and amended the helm code to also dump information about the current and target object as well as the generated patch, and here the results:

* **ClusterRole "dapr-placement"**

Here what can be observed using `kubectl`

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: dapr
    meta.helm.sh/release-namespace: dapr-system
  creationTimestamp: "2023-07-19T12:26:34Z"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dapr
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.11.1
  name: dapr-placement
  resourceVersion: "609"
  uid: ad39c72e-a653-4688-9030-b52365ce3911
rules: null
```

When running the my patched helm binary:

```yaml
client.go:691: [debug] current:
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: dapr
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.11.1
  name: dapr-placement
rules: []

client.go:692: [debug] target:
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: dapr
    meta.helm.sh/release-namespace: dapr-system
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dapr
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.11.1
  name: dapr-placement
rules: []

client.go:693: [debug] patch:
{"rules":[]}
```

* **Configuration daprsystem**

Here what can be observed using `kubectl`

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  annotations:
    meta.helm.sh/release-name: dapr
    meta.helm.sh/release-namespace: dapr-system
  creationTimestamp: "2023-07-19T12:26:34Z"
  generation: 1
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dapr
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.11.1
  name: daprsystem
  namespace: dapr-system
  resourceVersion: "657"
  uid: 56ce5ffa-80ec-44a9-9ce3-3a31f9254cfc
spec:
  metric:
    enabled: true
  metrics:
    enabled: true
  mtls:
    allowedClockSkew: 15m
    enabled: true
    workloadCertTTL: 24h
```

When running the my patched helm binary:

```yaml
client.go:691: [debug] current:
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: dapr
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.11.1
  name: daprsystem
  namespace: dapr-system
spec:
  mtls:
    allowedClockSkew: 15m
    enabled: true
    workloadCertTTL: 24h

client.go:692: [debug] target:
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  annotations:
    meta.helm.sh/release-name: dapr
    meta.helm.sh/release-namespace: dapr-system
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dapr
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.11.1
  name: daprsystem
  namespace: dapr-system
spec:
  mtls:
    allowedClockSkew: 15m
    enabled: true
    workloadCertTTL: 24h

client.go:693: [debug] patch:
{"metadata":{"annotations":{"meta.helm.sh/release-name":"dapr","meta.helm.sh/release-namespace":"dapr-system"},"labels":{"app.kubernetes.io/managed-by":"Helm"}}}
```

* **MutatingWebhookConfiguration dapr-sidecar-injector**

Here what can be observed using `kubectl`

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: dapr
    meta.helm.sh/release-namespace: dapr-system
  creationTimestamp: "2023-07-19T12:26:34Z"
  generation: 1
  labels:
    app: dapr-sidecar-injector
    app.kubernetes.io/component: sidecar-injector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dapr
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.11.1
  name: dapr-sidecar-injector
  resourceVersion: "663"
  uid: 8ccbbf0f-db9d-457f-aa0e-26135f7e35d0
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: 'redacted'
    service:
      name: dapr-sidecar-injector
      namespace: dapr-system
      path: /mutate
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: sidecar-injector.dapr.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: IfNeeded
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10

```

When running the my patched helm binary:

```yaml
client.go:691: [debug] current:
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: dapr-sidecar-injector
    app.kubernetes.io/component: sidecar-injector
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: dapr
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.11.1
  name: dapr-sidecar-injector
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: 'redacted'
    service:
      name: dapr-sidecar-injector
      namespace: dapr-system
      path: /mutate
  failurePolicy: Ignore
  name: sidecar-injector.dapr.io
  reinvocationPolicy: IfNeeded
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None

client.go:692: [debug] target:
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: dapr
    meta.helm.sh/release-namespace: dapr-system
  labels:
    app: dapr-sidecar-injector
    app.kubernetes.io/component: sidecar-injector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dapr
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.11.1
  name: dapr-sidecar-injector
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: 'redacted'
    service:
      name: dapr-sidecar-injector
      namespace: dapr-system
      path: /mutate
  failurePolicy: Ignore
  name: sidecar-injector.dapr.io
  reinvocationPolicy: IfNeeded
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None

client.go:693: [debug] patch:
{"$setElementOrder/webhooks":[{"name":"sidecar-injector.dapr.io"}],"webhooks":[{"name":"sidecar-injector.dapr.io","rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}]}]}
```
