### ISSUE TITLE
Helm seems to interpret on and off as true and false

### ISSUE THREAD

**Issue by bjd2385** [helm/helm#12179]
Output of `helm version`:

Observed on 3.9.4 and then I upgraded to latest and it's still the same behavior.

```shell
$ helm version
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}
```

```shell
$ helm version
version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.4"}
```

Output of `kubectl version`:

This isn't relevant.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Neither is this, it's local-only.

**Comment by bjd2385** [comment]
```yaml
# values.yaml
env:
  testFlight: off
```

```yaml
# templates/deployment.yaml
spec:
...
  template:
...
    spec:
...
      containers:
        - name: {{ .Chart.Name }}
...
          env:
...
            - name: TEST_FLIGHT
              value: {{ .Values.env.testFlight }}
...
```

and when I run `helm template <path>/<to>/<chart>` I observe that this creates an env var of type bool ~

```yaml
...
            - name: TEST_FLIGHT
              value: false
...
```

Minimum working example:

```yaml
# values.yaml

# Resolved to bools
test1_on: on
test1_off: off

# Resolved to strings
test2_on: 'on'
test2_off: 'off'
```

```
# templates/test.yaml

test1_on: {{ .Values.test1_on }}
test1_off: {{ .Values.test1_off }}

test2_on: {{ .Values.test2_on }}
test2_on: {{ .Values.test2_on }}
```

produces ~

```yaml
$ helm template .
---
# Source: interchange/templates/test.yaml
test1_on: true
test1_off: false

test2_on: on
test2_on: on
```
