### ISSUE TITLE
Support for using hyphen (-) template yaml files

### ISSUE THREAD

**Issue by venkatesh3889** [helm/helm#12188]
We getting the following error while we are trying to replace tag from values.yaml file"{{ .Values.images.abc-load-testing }}"

Error: UPGRADE FAILED: parse error at (abc-deployment/templates/abclingloadtest.yml:10): bad character U+002D '-'

Can someone help me how to replace hyphen -() here

Thanks

**Comment by yxxhero** [comment]
@venkatesh3889 please use "_".

**Comment by venkatesh3889** [comment]
Nope, it's still not working, it's giving an error bad character U+0022 '"'

**Comment by wujunwei** [comment]
> {{ .Values.images.abc-load-testing }}

using {{ .Values.images.abc_load_testing }} instead of {{ .Values.images.abc-load-testing }}, you should also change this name in values.yaml

**Comment by venkatesh3889** [comment]
thanks, 
this is the file which i am using
```
apiVersion: batch/v1
kind: Job
metadata:
  name: abc-load-test
spec:
  template:
    spec:
      containers:
      - name: abc-load-test
        image: dockerhub.com/011_load-testing/abc-load-testing:{{ .Values.images.abc_load_testing }}
```
it's failing due to  error converting YAML to JSON: yaml: line 12: mapping values are not allowed in this context. and tried adding quotes like , it's returing emty tag.
```
dockerhub.com/011_load-testing/abc-load-testing:"{{ .Values.images.abc_load_testing }}"
```

**Comment by wujunwei** [comment]
try this
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: abc-load-test
spec:
  template:
    spec:
      containers:
      - name: abc-load-test
        image: "dockerhub.com/011_load-testing/abc-load-testing:{{ .Values.images.abc_load_testing }}"
```
