### ISSUE TITLE
Incorrect upward propagation of Helm global values in a bundle

### ISSUE THREAD

**Issue by fstaudt** [helm/helm#12181]
I noticed an issue with upward propagation of global values in a bundle.\
I've created repository https://github.com/fstaudt/helm-global-values-upward-propagation to reproduce the issue.

---

Considering the 4 following charts structure:
```
- bundle
| - subchart-1
  | - template
| - subchart-2
  | - template
```

Chart **template** defines a template to display global values from 2 different collections:
- `global.data.*`
- `global.configMap.data.*`

Chart **subchart-1** depends on chart **template**.\
It also defines one key in each collection in its `values.yaml`:
- `global.data.subchart-1`
- `global.configMap.data.subchart-1`

Chart **subchart-2** also depends on chart **template**.\
It also defines one key in each collection in its `values.yaml`:
- `global.data.subchart-2`
- `global.configMap.data.subchart-2`

Chart **bundle** depends on charts **subchart-1** and **subchart-2**.\ 
It also defines one key in each collection in its `values.yaml`:
- `global.data.bundle`
- `global.configMap.data.bundle`

Following [rules of propagation for global values](https://helm.sh/docs/topics/charts/#global-values), 
the following data are expected in generated resources for bundle chart:
```yaml
---
# Source: bundle/charts/subchart-1/charts/template/templates/configMap.yaml
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: subchart-1
data:
  global.data.bundle: "test"
  global.data.subchart-1: "test"
  global.configMap.data.bundle: "test"
  global.configMap.data.subchart-1: "test"
---
# Source: bundle/charts/subchart-2/charts/template/templates/configMap.yaml
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: subchart-2
data:
  global.data.bundle: "test"
  global.data.subchart-2: "test"
  global.configMap.data.bundle: "test"
  global.configMap.data.subchart-2: "test"
```

The following data are found in generated resources with Helm v3.12.1 (or lower):
```yaml
---
# Source: bundle/charts/subchart-1/charts/template/templates/configMap.yaml
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: subchart-1
data:
  global.data.bundle: "test"
  global.data.subchart-1: "test"
  global.configMap.data.bundle: "test"
  global.configMap.data.subchart-1: "test"
  global.configMap.data.subchart-2: "test"
---
# Source: bundle/charts/subchart-2/charts/template/templates/configMap.yaml
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: subchart-2
data:
  global.data.bundle: "test"
  global.data.subchart-2: "test"
  global.configMap.data.bundle: "test"
  global.configMap.data.subchart-1: "test"
  global.configMap.data.subchart-2: "test"
```

Global values for `global.data` have not leaked from sub-charts and are only propagated downward (OK).\
Global values for `global.configMap.data` have however leaked from sub-charts to the bundle chart and have been propagated everywhere (NOK).

Issue is similar to https://github.com/helm/helm/issues/9332 fixed with https://github.com/helm/helm/pull/9333. \
Issue has been noticed on 3.12.1 and can also be reproduced on 3.7.0.

Could you confirm that the issue described above is indeed a bug ?\
Could you provide a fix for it ?

---

Output of `helm version`:
``` shell
$ helm version
version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.4"}
```

Output of `kubectl version`:
``` shell
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.10-eks-c12679a", GitCommit:"bbfa7e393476eb418f98a8c785721a006ba830cd", GitTreeState:"clean", BuildDate:"2023-05-22T20:31:17Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

**Comment by aseychell** [comment]
+1 I'm experiencing the same issue here

**Comment by gjenkins8** [comment]
For posterity, can you provide the commands you are running to replicate. I see:

```
$ helm-global-values-upward-propagation $ helm template testtest bundle/ # produces no output
$
```

**Comment by fstaudt** [comment]
> For posterity, can you provide the commands you are running to replicate. I see:
> 
> ```
> $ helm-global-values-upward-propagation $ helm template testtest bundle/ # produces no output
> $
> ```

Hello @gjenkins8 ,

here are the commands I used to reproduce issue with [reproducer repository](https://github.com/fstaudt/helm-global-values-upward-propagation):
```bash
cd helm-global-values-upward-propagation
helm dependency update subchart-1
helm dependency update subchart-2
helm dependency update bundle
helm template bundle        # produces output indicated in issue description
```

**Comment by fstaudt** [comment]
@gjenkins8 ,

why is this issue labeled as question / support ?

The issue reproduced in the example project looks more like a bug to me.\
The global values should only be propagated downward as documented in [Helm documentation](https://helm.sh/docs/topics/charts/#global-values):
> If a subchart declares a global variable, that global will be passed downward (to the subchart's subcharts), but not upward to the parent chart. There is no way for a subchart to influence the values of the parent chart.

**Comment by gjenkins8** [comment]
(regarding the above, I've been meaning to find time to go through this issue in more detail. Have not yet had time)

**Comment by csjiang-oscar** [comment]
this still occurs in v3.13.2.

**Comment by gjenkins8** [comment]
I can't see any reason why the `global.configMap.data.subchart-1` value would propagate to `subchart-2` and vice-versa. So I agree, this is a bug (unless I am mistaken somehow).

Determining why the code does propagate the values incorrectly would be the next step I think. And there is the problem, that changing this behavior will need strong consideration, and it might be "grandfathered in" at this point (until a new Helm or chart API version)

**Comment by richardwhiuk** [comment]
There's a lack of deep copy of tables, in part of the coalesceGlobal code which can cause issues here.

**Comment by maximveksler** [comment]
Hey guys, this is indeed a bug. However we're exploiting it for a workaround to share values between sub chats which is currently not supported officially at all.

I would kindly suggest implementing something akin to a "shared" values namespace that can be rendered at runtime (for example for password generation) while still being accessible and readable by any level of chart dependencies.

**Comment by fstaudt** [comment]
@gjenkins8 ,

I've seen that the issue has been flagged with v4.x.

Has it been fixed in v4.0.x ?

**Comment by AlexanderK46** [comment]
There is another section of the [Helm documentation](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values) about Global values ​​which states the following

> Global values are values that can be accessed from any chart or subchart by exactly the same name.

Thus, global values ​​should be available in any chart or subchart, regardless of their level, and their values ​​should be identical.
Related issue: https://github.com/helm/helm/issues/11703

As a workaround, we use explicit Global Values ​​imports for each dependency. This works, but theoretically slows down rendering, especially for charts with a large number of dependencies.
```
  - name: mychart
    version: '1.0.0'
    repository: '@helm'
    import-values:
      - child: global
        parent: global
```

The documentation contains conflicting information. Which one is true?
