### ISSUE TITLE
Values of subcharts are not correctly namespaced

### ISSUE THREAD

**Issue by Vedrillan** [helm/helm#12197]
Output of `helm version`: version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"archive", BuildDate:"2023-06-15T08:14:06Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform : AKS

Hi, I have a chart containing all the central tooling of my cluster by adding many subcharts to it. It worked perfectly until I tried to add the Airflow chart and noticed some issues.

After adding the airflow dependency I got the following error:
```
Error: template: infra-helm/charts/airflow/templates/_helpers.yaml:504:16: executing "redis.serviceAccountName" at <.Values.redis.serviceAccount.create>: nil pointer evaluating interface {}.serviceAccount
```

Which seems to indicate an issue with the airflow chart itself which I reported on their repo https://github.com/apache/airflow/issues/32482, however after some investigations I found out the issue was because values were conflicting with another subchart, oauth2-proxy.

So basically both dependencies (airflow and oauth2-proxy) can include redis, but it is like the subchart airflow is accessing the values of the oauth2-proxy values. Si if I use the following values the error goes away:
```
oauth2-proxy:
  redis:
    serviceAccount:
      create: false
airflow:
  redis:
    enabled: false
```

Based on the chart documentation values of subcharts should not have access to its parent and subsequently to its siblings because they are namespaced, but here it is not the case. Is this a bug or a feature?

I can reproduce the issue by using the following simplified chart conf:
```yaml
apiVersion: v2
name: infra-helm
description: infrastructure bundle for install and maintaining kubernetes clusters
type: application
version: "1.0.0"
appVersion: "2023-04-06"
dependencies:
  - name: oauth2-proxy
    repository: https://charts.bitnami.com/bitnami
    version: 3.7.1
  - name: airflow
    repository: https://airflow.apache.org
    version: 1.10.0
```

`helm upgrade -n clusterwide infra-helm . --reset-values --atomic --dry-run --install --create-namespace` wil generate the error `Error: template: infra-helm/charts/airflow/templates/_helpers.yaml:504:16: executing "redis.serviceAccountName" at <.Values.redis.serviceAccount.create>: nil pointer evaluating interface {}.serviceAccount`

`helm upgrade -n clusterwide infra-helm . --reset-values --atomic --dry-run --install --create-namespace --set oauth2-proxy.redis.serviceAccount.create=false` will not have the error.
