### ISSUE TITLE
Integers bigger 1M are being converted into exponential form

### ISSUE THREAD

**Issue by serge-name** [helm/helm#12195]
Output of `helm version`:
```text
version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.4"}
```

#### 1) `values.yaml`:
```yaml
someVarOne: 999999
someVarTwo: 1000000
```
#### 2) `templates/configmap.yaml`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: whatever
data:
  ONE: {{ .Values.someVarOne }}
  TWO: {{ .Values.someVarTwo }}
  TWO_Q: {{ .Values.someVarTwo | quote }}
```

#### 3) render that
```yaml
% helm template .
---
# Source: whatever/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: whatever
data:
  ONE: 999999
  TWO: 1e+06
  TWO_Q: "1e+06"
```

## Expected behavior:

```yaml
% helm template .
---
# Source: whatever/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: whatever
data:
  ONE: 999999
  TWO: 1000000
  TWO_Q: "1000000"
```
