### ISSUE TITLE
Is it possible to inject an object via --set-file during helm install/upgrade?

### ISSUE THREAD

**Issue by mwilkins99** [helm/helm#12207]
I am using a helm chart and it gives the option to be able to inject initContainers and sidecarContainers. I wanted to separate the container spec into its own file. I have used the `--set-file` flag in the past to pull in files. Most of those were mapped into a configmap. In this case, I want to take the content as is without it adding `|-`. Am I using the right flag or is there another flag that I could use to pull this in from a file?

Example:

Values.yaml
```
entries:
  - name: sampleEntry1
     initContainers: []
     sidecarContainers: []
  - name: sampleEntry2
     initContainers: []
     sidecarContainers: []
```

sampleinitcontainer.yaml
```
name: copyfile
image: someimage:tag
command: ["sh", "-c", "cp /inputfile.txt /files/outputfile.txt"]
volumeMounts:
  - name: file-dir
     mountPath: /files
```

I was trying with this command:
`helm install testrun --set-file entries[0].initContainers[0]=sampleinitcontainer.yaml`

Any assistance would be greatly appreciated.

Thanks!
