### ISSUE TITLE
Incorrect chart name in _helpers template

### ISSUE THREAD

**Issue by coding4food** [helm/helm#12205]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): None

`<CHARTNAME>.chart` template helper produces incorrect label value.

When we use `Chart.yaml` with following content
```
apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for Kubernetes
name: foo-bar
type: application
version: 1.234.5-some-long-semver-pre-release-version-goes-here+d34db33f
```
for default chart produced with `helm create`, it creates incorrect label:
```
# Source: foo-bar/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-foo-bar
  labels:
    helm.sh/chart: foo-bar-1.234.5-some-long-semver-pre-release-version-goes-here_
```
which K8s refuses with error:
```
metadata.labels: Invalid value: "foo-bar-1.234.5-some-long-semver-pre-release-version-goes-here_": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```
