### ISSUE TITLE
I need help with debugging a Helm chart

### ISSUE THREAD

**Issue by KostLinux** [helm/helm#12226]
I am attempting to deploy multiple ArgoCD projects with their namespaces using a Helm template. However, I am encountering an error during deployment.

templates/appproject.yaml
```
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  {{- range $key, $value := .Values.instance_preconfig.argocd.projects -}}
  {{- range $value.project -}}
  name: {{ . }}
  {{- end -}}
  {{- end -}}
  namespace: {{ .Values.instance_preconfig.argocd.argocd_namespace }}
spec:
  destinations:
  {{- range $key, $value := .Values.instance_preconfig.argocd.projects -}}
  {{- range $value.namespaces -}}
  - name: in-cluster
    namespace: {{ . }}
    server: https://kubernetes.default.svc
  {{- end -}}
  {{- end -}}
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
```
values.yaml
```
---
instance_preconfig:
  argocd:
  # Namespace where ArgoCD instance will be located  
    argocd_namespace: 'project-argocd-app'
    redis_password: '123'
  # Projects & Namespaces where ArgoCD will have access
    projects:
      project1:
        project: 
          - project1
        namespaces:
          - project1-app
          - project1-base
          - project1-db
      project2:
        project: 
          - pproject2
        namespaces:
          - project2-app
      project3:
        project: 
          - project3
        namespaces:
          - project3-app
          - project3-base
          - project3-db
```

Error code:
```
[ERROR] templates/argocd-project.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context
```

Output of `helm version`:  `version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.5"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube
