### ISSUE TITLE
Scaling Deployments: unable to retrieve the complete list of server APIs

### ISSUE THREAD

**Issue by porscheme** [helm/helm#12230]
Output of `helm version`:
```version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}```

Output of `kubectl version`:
'''WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"f18584a06fc476806da2e340e2eed960659871e8", GitTreeState:"clean", BuildDate:"2023-06-12T18:45:20Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.26) exceeds the supported minor version skew of +/-1'''

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

KEDA Version: 2.11.1

- I have a simple service in graph K8S namespace
- I deployed KEDA in the same namespace (graph)
- I have created a scaledObject in the same namespace with Deployment kind scaleTargetRef

I see below error we see in the Keda-operator pod
```unable to get client for deployments': unable to get full preferred group-version-resource for deployments.apps: failed to get API group resources: unable to retrieve the complete list of server APIs: apps/: converting (v1.APIGroup) to (v1.APIResourceList): unknown conversion```

Any help how to t-shoot the issue?

scaledObject.yaml
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: graphfd-scaler
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
    autoscaling.keda.sh/paused-replicas: "0"
  namespace: graph
spec:
  scaleTargetRef:
    name: graphqueryfrontdoor
    kind: Deployment
    apiVersion: apps/v1
  pollingInterval: 10
  idleReplicaCount: 0
  cooldownPeriod: 20
  minReplicaCount: 1
  maxReplicaCount: 3
  fallback:
    failureThreshold: 3
    replicas: 1
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: azure-blob
    name: graphqueryfrontdoor-trigger
    #authenticationRef:
    #  name: graphqueryfrontdoor-auth
    metadata:
      blobContainerName: keda
      accountName: mystorageaccount
      blobCount: "1"
      blobPrefix: ""
      cloud: Private
      endpointSuffix: blob.core.windows.net
      connectionFromEnv: SCALEDOBJECT_CONN_STRING
```

Complete Error Stacktrace
```
2023-07-17T19:39:13Z	ERROR	target resource doesn't expose /scale subresource	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"graphqueryfrontdoor-scaler","namespace":"graph"}, "namespace": "graph", "name": "graphqueryfrontdoor-scaler", "reconcileID": "4b77223d-1614-49bd-a37b-2155ab8f9e58", "resource": "apps/v1.Deployment", "name": "graphqueryfrontdoor", "error": "unable to get client for deployments.apps: unable to get full preferred group-version-resource for deployments.apps: failed to get API group resources: unable to retrieve the complete list of server APIs: apps/: converting (v1.APIGroup) to (v1.APIResourceList): unknown conversion"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).checkTargetResourceIsScalable
	/workspace/controllers/keda/scaledobject_controller.go:334
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:238
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:177
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:314
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:265
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:226
```

KEDA installation steps followed
```
- helm repo add kedacore https://kedacore.github.io/charts
- helm install -f keda.values.yaml keda kedacore/keda -n graph
```
