### ISSUE TITLE
[BUG] Incorrect templating with multiple yaml documents, and comments

### ISSUE THREAD

**Issue by L1ghtman2k** [helm/helm#12260]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.5"}
```

```
# (C) Copyright 2023 MY_COMPANY_BLAH_BLAH
{{- range $i, $namespace := .Values.namespaces }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-{{ $namespace.name }}
  namespace: {{ $namespace.name }}
spec:
  limits:
  - type: Container
{{ toYaml $namespace.resource_constraints.limit_range | indent 4 }}
{{- end }}
```

values.yaml:
```
namespaces:
  - name: test-namespace
    resource_constraints:
      limit_range:
        default:
          memory: "64Mi"
        defaultRequest:
          memory: "64Mi"
```

The above creates following template:

```
---
# Source: namespaces-applier/templates/limit_range.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-test-namespace
  namespace: test-namespace
spec:
  limits:
  - type: Container
    default:
      memory: 64Mi
    defaultRequest:
      memory: 64Mi
---
# Source: namespaces-applier/templates/limit_range.yaml
# (C) Copyright 2023 MY_COMPANY_BLAH_BLAH

```

Why would it put the `# (C) Copyright 2023 MY_COMPANY_BLAH_BLAH` at the bottom, and why would it add an extra `---`, given I only have a single element in the namespaces list
