### ISSUE TITLE
Unable to use multiple versions as base charts for different aliases

### ISSUE THREAD

**Issue by nc-nhn** [helm/helm#12282]
Hi,

When attempting to use multiple versions as base charts for different aliases within a Chart.yaml, we encountered an unexpected behavior that led to a conflict in template replacements. Here's the context:

- We want to update the base charts of 2 sub-components (aliases) with specific version to include a new feature of PVC as:

![image](https://github.com/helm/helm/assets/48241316/12265146-eb6e-4c8a-9ed3-02cdcde49a80)

- To further investigate, we attempted to download the Helm package and inspect its contents.

- We verified that the base chart version for the sub-component is correctly defined as version 2.0.5.

- However, upon extracting the Helm package, we observed that the templates for the sub-component were unexpectedly replaced with those from version 2.0.11, leading to the aforementioned error.

Extracted Helm package (example):

<img width="879" alt="image" src="https://github.com/helm/helm/assets/48241316/5f2135bb-f167-4a3e-bced-156aaee73ec4">

Our expected behaviour is to have a support of multiple versioning for base charts.

Output of `helm version`:  version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v5.0.1

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

**Comment by wujunwei** [comment]
I try it in latest version `3.12.` I did not reproduce this problem.
```
dependencies:
  - name: cassandra
    repository: http://127.0.0.1/repo
    version: 3.11.4
    alias: A
  - name: cassandra
    repository: http://127.0.0.1/repo
    version: 3.12.4
    alias: B
  - name: cassandra
    repository: http://127.0.0.1/repo
    version: 3.12.4
    alias: C
  - name: cassandra
    version: 3.11.4
    repository: http://127.0.0.1/repo
    alias: D
# run helm dep update it will download two packages 3.12.4 and 3.11.4 as expected.
```

Do I understand your question correctly? If not, please provide detailed reproduction steps :)
