### ISSUE TITLE
Helm install not pulling required image when installing chart under the directory of the chart.yaml 

### ISSUE THREAD

**Issue by Loveen01** [helm/helm#12309]
Added the chart 
`helm repo add grafana https://grafana.github.io/helm-charts
`

Output of `helm repo list`: 
`grafana                         https://grafana.github.io/helm-charts  
`

 **Chart.yaml:**
```
apiVersion: v2
name: skube-localdev-pyroscope
description: A Helm chart for Pyroscope

type: application
version: 0.1.0

dependencies: 
  - name: phlare
    version: 0.5.4
    AppVersion: "weekly-f23-4bb98e30"
    repository: alias:grafana
```
**values.yaml**: 
 ```
phlare:
  image:
    # overrides the image tag whose default is the AppVersion. 
    tag: "weekly-f23-4bb98e30"
```

If I base my helm installation on my chart.yaml and run the command in the **directory** of the Chart.yaml it fails to pull the correct image:
`helm install pyros2 .
`

Output of `kubectl describe pod pyros2-phlare-0`
```
Containers:
  phlare:
    Container ID:  docker://f44071440cfcbb46b606816aa77ec913cd7ab0ee67fe6f1428382cbe1011dcd2
    Image:         grafana/phlare:0.5.1
    Image ID:      docker-pullable://grafana/phlare@sha256:330f990cdad942e7d6d3e0144494ea54c3ef65ac9e4b4fac3b9b4b556f0fe1c0

```
As you can see above it pulls the older image **0.5.1** even though I have specified it to pull this image **"weekly-f23-4bb98e30"**

However, **If I do it in this way then it pulls the correct image**:

`helm install pyros grafana/phlare -f values.yaml
`

Output of `kubectl describe pod pyros-phlare-0`

```
Containers:
  phlare:
    Image:         grafana/phlare:weekly-f23-4bb98e30
```

Output of `helm version`:
- Tried with helm versions 3.8.1 and 3.12.1

Output of `kubectl version --short`:

```Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.2
```

**Comment by Ithrael** [comment]
First of all, it seems that dependencies do not have the "AppVersion" attribute. Please refer to https://helm.sh/docs/helm/helm_dependency/ If you only provide Chart.yaml and values.yaml, before running "helm install pyros2 .", you need to run "helm dependency build" first. The build process only relies on Chart.lock. The Chart.lock should be generated using the Chart.yaml and values.yaml that you provided.
```
dependencies:
- name: phlare
  repository: https://grafana.github.io/helm-charts
  version: 0.5.4
digest: sha256:5398ad07262feecfb9cb54d5907b19b460e253a95c223560f20fd2729fccbd8a
generated: "2023-08-17T19:50:00.55304+08:00"
```
At this point, when you run "helm install pyros2 .", it will use the charts from phlare version 0.5.4. The default value for the "image:tag" in the charts is 0.5.1. Therefore, when you first check the "imagetag" of the pod "pyros2-phlare-0" using "kubectl describe pod", it will be 0.5.1.

**Comment by Loveen01** [comment]
I have removed the AppVersion attribute and it still pulls the old image (image tag 0.5.1). 
Secondly I have always run "helm dependency build" before installing, and the changes have been updated on chart lock, and yet it does not pull the latest image once I install. 

When I run `helm install pyros2 . `, it is pulling the old image (0.5.1) even though I **overridden the image tag** in the **values.yaml file**. When overriding the image tag in this way, it **should** pull the latest image that I have specified in the values.yaml, (even though the default image tag is 0.5.1). This issue is strange. 

I have also tried to run this line (after "dependency updates" and "dependency build"):
`helm install pyros2 . -f values.yaml`
and it still does not override the image.tag with the one i have specified **(weekly-f23-4bb98e30)**

**Comment by Ithrael** [comment]
You run helm install pyros2 ., and the image pull (0.5.1) is normal because you specified the chart version of phlare as 0.5.4, and this chart corresponds to the image version 0.5.1.
<img width="1320" alt="image" src="https://github.com/helm/helm/assets/38208715/a8d1c658-569f-4f78-b453-7aae78d4239d">

However, when you run helm install pyros2 . -f values.yaml, in theory, it should override this variable. I initially thought the same, but during my testing, I found that the override was not successful. After my investigation, I found that when you execute helm dependency build, a charts directory is created in the current directory, which contains a phlare-0.5.4.tgz file.

For example, I execute this command.  helm template pyros2 . -f values.yaml | grep image
<img width="741" alt="image" src="https://github.com/helm/helm/assets/38208715/ea2e320a-76c1-4db1-85d2-44ecf741f05b">
But I execute this command.  helm template pyros2 charts/phlare-0.5.4.tgz -f values.yaml | grep image
<img width="932" alt="image" src="https://github.com/helm/helm/assets/38208715/1ffe21be-720c-45ed-adc2-bf70ff08fa0f">

ou can see that -f values.yaml is taking effect. I used --debug and can see that these two commands are actually using different charts.

<img width="1007" alt="image" src="https://github.com/helm/helm/assets/38208715/d13e8ddb-86d2-4833-8c5c-8a546136b715">
I am still investigating why they are not the same Chart. I hope the previous response has been helpful to you.

**Comment by Loveen01** [comment]
Thank you for your response. That really is strange ... I wonder why that is. 
Im looking forward to hearing from you

**Comment by Ithrael** [comment]
I found the reason. If you use 'helm template pyros2 charts/phlare-0.5.4.tgz -f values.yaml',  then you are using phlare as the chart. However, when you use 'helm template pyros2 . -f values.yaml --debug', Phlare is a sub-chart, it is because the Chart.yaml in the '.' directory is this way.

```
apiVersion: v2
name: skube-localdev-pyroscope
description: A Helm chart for Pyroscope

type: application
version: 0.1.0

dependencies: 
  - name: phlare
    version: 0.5.4
    AppVersion: "weekly-f23-4bb98e30"
    repository: alias:grafana

```
So writing it this way in values.yaml won't be able to locate the tag.
```
phlare:
  image:
    # overrides the image tag whose default is the AppVersion. 
    tag: "weekly-f23-4bb98e30"
```
You need to first locate the sub-chart, so you should write it like this.
```
phlare: # Used to locate the sub-chart
  phlare:
    image:
      # overrides the image tag whose default is the AppVersion. 
      tag: "weekly-f23-4bb98e30"
```
<img width="791" alt="image" src="https://github.com/helm/helm/assets/38208715/ed746360-9865-4ed5-92fe-f16da56b6a30">
