### ISSUE TITLE
Support customization of labels and annotations helm adds to every object

### ISSUE THREAD

**Issue by ldemailly** [helm/helm#12314]
Today helm adds to every object it creates some annotations and labels, eg.
```
  annotations:
    meta.helm.sh/release-name: fortio
    meta.helm.sh/release-namespace: fortio
  labels:
    app.kubernetes.io/managed-by: Helm
```

We have the need to add additional labels and annotations, without modifying every single chart and their templates, and as helm already does that for the above, it'd be great to support additional labels
(so for instance `helmfile`'s `commonLabels` would be more directly useful, and would put these labels on all objects)

ps: if I am missing how to do it today, I apologize and please let me know; I don't mean though to do `helm template | processing`
