### ISSUE TITLE
yaml comments do not take effect in one case

### ISSUE THREAD

**Issue by rudyares** [helm/helm#12319]
### How to recurrence
**step 1**: Create a new simple chart.
`helm create demo`
**step 2**: Render chart templates locally and display the output.
`helm template demo`
This step will render correctly.
**step 3**: Comment the entire service.yaml file in templates folder and render again.
The service.yaml file is as follows:
```yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "demo.fullname" . }}
#   labels:
#     {{- include "demo.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "demo.selectorLabels" . | nindent 4 }}
```
Render chart templates again, it will not render as expected, the result is as follows:
```yaml
# Source: demo/templates/service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: release-name-demo
#   labels:
#
    helm.sh/chart: demo-0.1.0
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
# spec:
#   type: ClusterIP
#   ports:
#     - port: 80
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: release-name
```

Output of `helm version`: v3.9.0
Output of `kubectl version`: v1.16.14

How should I achieve the desired comment effect, or is this a persistent bug？

**Comment by Ithrael** [comment]
I have encountered the same situation before, and this is how I resolved it. I used the {{- /* */}} comment syntax.

reference  https://helm.sh/docs/chart_best_practices/templates/#helm

```
{{- /*
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
*/}}
```
I hope it is helpful to you.
