### ISSUE TITLE
Helm index.yaml with OCI references 

### ISSUE THREAD

**Issue by juan131** [helm/helm#12322]
## Context 

index.yaml-based repositories support listing chart dependencies using OCI references. For instance:

```yaml
apiVersion: v1
entries:
  foo:
    appVersion: X.Y.Z
    dependencies:
    - name: bar
      repository: oci://some-oci-registry-url
      version: 0.x.x
    description: Some description
    digest: abcdefghijklmnopqrstuvwxyz
    home: https://helm.sh/helm
    name: foo
    sources:
    - https://github.com/foo/foo
    urls:
    - https://repo-registry/foo-0.1.0.tgz
    version: 0.1.0
```

However, _urls_ field doesn't seem to support it. I can see the  **helm** renders _urls_ as an **array of strings**, see:

* https://github.com/helm/helm/blob/main/pkg/repo/index.go#L257

Then, it treats them as absolute or relative URL(s), see: 

* https://github.com/helm/helm/blob/main/pkg/repo/chartrepo.go#L271-L280

## Request

Would it be possible to support referencing the chart URL using OCI? E.g. using sth like this:

```yaml
    urls:
    - oci://some-oci-registry-url/foo --version 0.1.0
```

OR:

```yaml
    urls:
    - oci://some-oci-registry-url/foo@0.1.0
```

## Use case

Use OCI exclusively to publish charts while keeping an `index.yaml` to continue offering discovering capabilities currently not supported on OCI registries, see https://github.com/helm/helm/issues/11000
