### ISSUE TITLE
"helm lint" does not complain on duplicate keys in chartfile YAML

### ISSUE THREAD

**Issue by edbmiller** [helm/helm#12381]
Currently, `helm lint` accepts chartfiles which have duplicate mapping keys (this constitutes invalid YAML), e.g. it accepts the following:

```yaml
apiVersion: v2
name: test
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
appVersion: "1.2.3"      <------ DUPLICATE KEY
dependencies:
  - name: trivy-operator
    repository: https://aquasecurity.github.io/helm-charts/
    version: 0.18.0
    version: 0.17.1      <------ DUPLICATE KEY
 ```
 
I think to fix this we can simply:
 - change [this function call](https://github.com/helm/helm/blob/main/pkg/chartutil/chartfile.go#L36) in pkg/chartutil to the [strict version](https://github.com/kubernetes-sigs/yaml/blob/master/yaml.go#L63) (`yaml.UnmarshalStrict`)
  - ~~check the resulting Metadata struct has a non-empty Name, a required field [according to this comment](https://github.com/helm/helm/blob/main/pkg/chart/metadata.go#L48)~~ this shouldn't be necessary, we can just use the error return value of the unmarshal function as we currently do

Happy to submit a PR with this change!

Minimal steps to reproduce:
  - `helm create testy-mctest`
  - update `Chart.yaml` with example above (or any key duplicated)
   - `helm lint`
   
Output of `helm version`:

```
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}
```
