### ISSUE TITLE
helm template shows different output than what is getting deployed, -f values.yaml also further changes behavior

### ISSUE THREAD

**Issue by BlacCello** [helm/helm#12398]
I currently have a very strange behaviour, where helm template shows different annotations, than what is deployed in the cluster afterwards. I provided an example code here <https://github.com/BlacCello/helm-template-bug>.

You can see the issue when:
1. Run `helm template .` and see the annotations section
```yaml
...
  annotations:
    test1: 
    test2: 
    test3: "important-annotation"
    ingress.kubernetes.io/rewrite-target: "/$1"
...
```
2. Deploy the example as it is with `helm upgrade --install -n test --create-namespace test .`. See what is deployed in the cluster with `kubectl get ingress -n test test -o yaml`
```yaml
...
  annotations:
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: test
...
```
**Both annotations, test3 with "important annotation" and the rewrite-target annotations are missing.**

3. Run `helm template . -f values.yaml` and see the annotations output, which is semantically the same as 1:
```yaml
...
  annotations:
    test3: "important-annotation"
    ingress.kubernetes.io/rewrite-target: "/$1"
...
```
4. Deploy again to the cluster with values.yaml: `helm upgrade --install -n test --create-namespace test . -f values.yaml`. Check the ingress resource again:  `kubectl get ingress -n test test -o yaml`:
```yaml
...
  annotations:
    ingress.kubernetes.io/rewrite-target: /$1
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: test
    test3: important-annotation
...
```
**Now both annotations were getting deployed as expected and as helm template shows**

Final words: I do not understand this, especially that with the first steps without `-f values.yaml` helm template and helm upgrade/install are doing something different.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.7", GitCommit:"84e1fc493a47446df2e155e70fca768d2653a398", GitTreeState:"clean", BuildDate:"2023-07-19T12:16:45Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Rancher
