### ISSUE TITLE
ServiceAccount is not created before Jobs/Pods

### ISSUE THREAD

**Issue by lynshi** [helm/helm#12414]
According to the [`InstallOrder`](https://github.com/helm/helm/blob/3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e/pkg/releaseutil/kind_sorter.go#L31C1-L32C1), `ServiceAccount` should be installed before both `Pod` and `Job`. However, I've observed occasions where the `ServiceAccount` is not created before Jobs (or even standalone Pods).

# Steps to reproduce
1. Run `helm create ...` to create a fresh new Helm chart.

2. Copy the following resource definitions under `templates/`.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-sa
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-3"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
---
kind: Job
apiVersion: batch/v1
metadata:
  name: my-job
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-3"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    spec:
      serviceAccountName: my-sa
      containers:
      - name: my-pod
        image: mcr.microsoft.com/cbl-mariner/base/python:3.9
        command: ["/bin/bash", "-c", "sleep 600"]
      restartPolicy: Never
```
Note that both the `ServiceAccount` and `Job` have the same hook weight of `-3`.

3. `kubectl get serviceaccounts` and `kubectl get jobs -n $namespace -w` to watch the resource creation.

4. Install the chart: `helm install -n $namespace ...`.

The output of the watched resources shows that the `Job` is created but no `ServiceAccount` is created.
<img width="783" alt="image" src="https://github.com/helm/helm/assets/9373058/a3222f09-f44a-4432-9a15-9091730fdcba">

The `Job` also fails to create `Pods`.
<img width="1448" alt="image" src="https://github.com/helm/helm/assets/9373058/c8544cea-b187-4b90-84c7-3793831dc0d9">

---
If I weight the `ServiceAccount` lower so it gets prioritized, it will get created before the `Job`, so the hook itself seems to work as expected.
<img width="185" alt="image" src="https://github.com/helm/helm/assets/9373058/6d31d105-f4e4-4af1-9e02-93e61ef4927b">

<img width="285" alt="image" src="https://github.com/helm/helm/assets/9373058/e66a53da-38e3-4517-b5a8-60848e453049">

<img width="362" alt="image" src="https://github.com/helm/helm/assets/9373058/950ccc8c-c0a6-4581-8977-4d15711da547">

---

Output of `helm version`: `version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"f18584a06fc476806da2e340e2eed960659871e8", GitTreeState:"clean", BuildDate:"2023-06-12T18:45:20Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS
