### ISSUE TITLE
helm setting resources to null instead of removing them

### ISSUE THREAD

**Issue by alexgaganashvili** [helm/helm#12421]
Output of `helm version`:

version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

Hi,

I need to remove cpu limits from a generated manifest. When I set cpu limits via `--set`, it correctly removes cpu limits in one Deployment; in another Deployment, it sets cpu to the value of `null`, which causes a problem when the manifest gets applied to K8s. I can't figure out what's causing this inconsistency and why helm sets cpu (or any other parameter in the manifest) to null instead of removing it.

Thanks

**Comment by gjenkins8** [comment]
And example would be helpful here please. Generally, Helm will only remove null _values_. And it depends how the chart is using said values to render the Kubernetes objects.

**Comment by alexgaganashvili** [comment]
**template:**
```
---
...
        resources:
{{ toYaml .Values.container1.resources | indent 10 }}
...
---
...
        resources:
{{ toYaml .Values.container2.resources | indent 10 }}
...
```

**helm overrides:**
**_--set container1.resources.limits.cpu=null_** --set container1.resources.requests.cpu=100m **_--set container2.resources.limits.cpu=null_** --set container2.resources.requests.cpu=200m


**rendered manifest:**
# 1)
```
resources:
  limits:
    cpu: null
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
```

# VS
# 2)
```
resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 200m
    memory: 2Gi
```
