### ISSUE TITLE
[fix-issue-9027] Doesn't handle dict override to null

### ISSUE THREAD

**Issue by JordanGoasdoue** [helm/helm#12441]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.20.8"}
```

Output of `kubectl version`:
```
Client Version: v1.24.13
Kustomize Version: v4.5.4
Server Version: v1.24.13
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE / On Premise

###########################################
###########################################

I am testing the the fix of the issue-9027
It seems it only works with simple key but not dict override:

let say I have a chart called subchart with these values

```
strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 10%
  type: RollingUpdate
```
In one of my other chart, I want to use this subchart as a dependency, but I want to have a Recreate strategy instead of the RollingUpdate one:

so I'm doing this:
```
subchart:
  strategy:
    rollingUpdate: null
    type: Recreate
```

But then I can't render the helm template because of this error
```
coalesce.go:286: warning: cannot overwrite table with non table for xxx.subchart.strategy.rollingUpdate (map[maxSurge:25% maxUnavailable:10%])
```

What I can only do is the following by overriding my dict children as null:
```
subchart:
  strategy:
    rollingUpdate:
      maxSurge: null
      maxUnavailable: null
    type: Recreate
```

This is not what I want because this way I will render this 
```
spec:
  strategy:
    rollingUpdate: {}
    type: Recreate
```
Which will give me this error after applying to a kubernetes cluster:
```
spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

**Comment by ReneWerner87** [comment]
have the same error
in the helm chart i have a readiness probe which i want to overwrite completely in some cases when using it

**Comment by ReneWerner87** [comment]
I suspect it has something to do with this

https://github.com/helm/helm/commit/e8a748d3003faaa4846d2a9f30f7225d232b76d5

**Comment by gjenkins8** [comment]
Can you quickly check if the behavior is different in Helm 3.12 please?

https://github.com/helm/helm/pull/12162 (of which e8a748 was part of) fixes a number of values handling bugs. And was released in Helm 3.13.

**Comment by ReneWerner87** [comment]
Sure tomorrow

**Comment by ReneWerner87** [comment]
@gjenkins8 its working with 
![image](https://github.com/helm/helm/assets/7063188/36929a65-192a-4e3f-966d-6bf5af8c87aa)
3.12.3

not working with 
![image](https://github.com/helm/helm/assets/7063188/5e59d9e5-1f05-4ead-83f3-e76137fa1485)
3.13.0
![image](https://github.com/helm/helm/assets/7063188/bcb71f60-4671-4c2c-a1a7-90a96ade4269)

**Comment by JordanGoasdoue** [comment]
> Can you quickly check if the behavior is different in Helm 3.12 please?
> 
> #12162 (of which e8a748 was part of) fixes a number of values handling bugs. And was released in Helm 3.13.

with helm 3.12.3:

```
subchart:
  strategy:
    rollingUpdate: null
    type: Recreate
```

it's giving me:

```
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
    type: Recreate
```

It's like overriding with {} it does nothing

Yes I was following the PR 12162, but it seems it only fix this issue for non dict content
