### ISSUE TITLE
[Question] How to escape `{{` inside the K8s resource spec

### ISSUE THREAD

**Issue by haphamdev** [helm/helm#12458]
I use DataDog for the logs of our system, and I also create some alerts based on the logs.
For example, I have an alert when the log `payment failure` is found in the past 5m.

DataDog alert can be created as a K8s resource using `DatadogMonitor` controller ([more info here](https://github.com/DataDog/datadog-operator/tree/main/controllers/datadogmonitor)), something like this:
```
apiVersion: k8s.datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: {{.Chart.Name}}-paymen-failure
spec:
  name: "[{{ .Values.environment }}][{{ .Chart.Name }}] Payment failure"
  type: "log alert"
  query: "logs(\"service:payment-service env:{{.Values.environment}} status:error Payment failure\").index(\"*\").rollup(\"count\").last(\"1h\") > 0"
  message: |
    Payment failure occurred. Please have a look.
    @slack-payment-alerts
  {{ end }}
  tags:
    - "env:{{.Values.environment}}"
    - "service:{{.Chart.Name}}"
{{ end }}

```

Let's focus on the `message`.
It contains the alert message and the Slack channel to be notified.

I want the `message` value to be like this:
```
{{#is_alert}}
Payment failure occurred. Please have a look.
@slack-payment-alerts
{{/is_alert}}
```
Please note that `{{#is_alert}}` and `{{/is_alert}}` is DataDog syntax, not variables from helm.
However, I do not know how to escape `{{#` characters and add `{{#is_alert}}` to the message value.

Helm failed to parse the special characters like `{` or `#`.

I tried a couple of ways, but nothing helped, as mentioned [here](https://github.com/DataDog/datadog-operator/issues/937#issue-1923313318).

How can I do it?

Helm version:
```
> helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}
```

**Comment by JSchlarb** [comment]
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: scratch_349
data:
  test: |
    {{ "{{#is_alert}}" }}
    Payment failure occurred. Please have a look.
    @slack-payment-alerts
    {{ "{{/is_alert}}" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scratch_349
data:
  test: |
    {{#is_alert}}
    Payment failure occurred. Please have a look.
    @slack-payment-alerts
    {{/is_alert}}
```
