### ISSUE TITLE
subchart override with --set not taken into account

### ISSUE THREAD

**Issue by JordanGoasdoue** [helm/helm#12469]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.20.8"}
```

Output of `kubectl version`:
```
Client Version: v1.24.13
Kustomize Version: v4.5.4
Server Version: v1.24.13
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE / On Premise

###########################################
###########################################
can't override subchart values with "--set"
It seems it only works with values override from file directly

let say I have a chart called subchart with these values

```
strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 10%
  type: RollingUpdate
```
In one of my other chart, I want to use this subchart as a dependency, but I want to have a Recreate strategy instead of the RollingUpdate one:

so I'm doing this:
```
subchart:
  strategy:
    rollingUpdate: null
    type: Recreate
```

```
helm template --release-name demo path/to/chart --output-dir .
```

My Deployment has 
```
spec:
  strategy:
    type: Recreate
```

But if I try with --set flag instead of null in the values file
```
helm template --release-name demo path/to/chart --set subchart.strategy.rollingUpdate=null --output-dir .
```
It doesn't work In the end I have 

```
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
    type: Recreate
```

**Comment by gjenkins8** [comment]
From https://github.com/helm/helm/issues/12441, I believe this consider is a regression in Helm 3.13.0's behavior.

I will (hopefully later today) dig further.

**Comment by mattfarina** [comment]
I tried reproducing this issue and `--set` worked for me. I'm sure I'm doing something differently. Can someone provide a chart or more detail so I can reproduce the problem?

**Comment by mattfarina** [comment]
oh, i think is see what's going on. I'll look at this more tomorrow

**Comment by naemono** [comment]
Wanted to chime in here with a full working example of this not working either via values file, or `--set`:

https://github.com/naemono/helm-failing-subchart-override

### Parent Chart

#### default values file

```
child:
  enabled: false
```

#### Chart.yaml

```
apiVersion: v2
name: parent-child-test
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: child
    condition: child.enabled
    repository: file://charts/child
```

### Child Chart

#### default values file

Truncated for brevity
```
spec:
  test:
    value: set
```

### Example values file for testing

```
child:
  enabled: true
  spec:
    test: null
```

## To reproduce

Neither setting via a values file, or via `--set` options work:

```shell
❯ helm template --release-name demo . -f examples/child/values.yaml | yq '.spec.test'
value: set

❯ helm template --release-name demo . --set child.enabled=true --set child.spec.test=null | yq '.spec.test'
value: set
```
