### ISSUE TITLE
v3.13.0 breaks OCI charts on ghcr.io

### ISSUE THREAD

**Issue by ba-work** [helm/helm#12464]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.20.8"}
```

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

Works on v3.12.3 and not on v3.13.0. See here: https://github.com/ba-work/helm-bug/actions/runs/6434433277/job/17473648959

I used this workflow to repro:
```yaml
name: helm bug

on:
  workflow_dispatch:

jobs:
  bug:
    strategy:
      fail-fast: false
      matrix:
        version: ["v3.12.3", "v3.13.0"]
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-helm@v3
      with:
        version: ${{ matrix.version }}        
    - run: helm version
    - run: helm pull oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set --debug
```
This is probably the same as #12463
