### ISSUE TITLE
how to delete configmap on basis of token

### ISSUE THREAD

**Issue by jainpratik163** [helm/helm#12508]
we have install helm chart and on some condition it create some dummy configmap , now we disbale flag and when we run again helm upgrade dummy configmap which are already created should delete.
how we can do this.

Output of `helm version`:3.11

Output of `kubectl version`:1.26

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  NA

**Comment by tuunit** [comment]
Hi @jainpratik163,

usually when configuring `ConfigMaps` or `Secrets` to be deployed based on conditions. You have to enclose the whole content of the template file in your condition:

```yaml
{{ if eq .Values.favorite.drink "coffee" }}
apiVersion: v1
kind: ConfigMap
metadata:
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | default "tea" | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
{{- end }}
```

In this example when you set `favorite.drink` to the value `coffee` the `ConfigMap` will be created during install or upgrades. If the value isn't equal to `coffee` the `ConfigMap` will either not be created or deleted, if it exists from a previous install/upgrade.

**Comment by jainpratik163** [comment]
Hi @tuunit,
thanks for the update but let say `favorite.drink` to the value `coffee` 1st it will install CM but latter say value is diff and when we run helm upgrade this will not install but cm will present in the env as in 1st run it is created.
so my doubt is if we can add such option to delete cm when we run `helm upgrade `command

**Comment by tuunit** [comment]
Do you mean that you have a reference to the CM in your deployment?

**Comment by jainpratik163** [comment]
yes.. we have created one crd which bind cm to deployment.

**Comment by tuunit** [comment]
I think I would need some example code snippets of what you actually want to accomplish. I'm still not 100% sure on that. Otherwise it is really hard for me to follow your description of the issue. Can you provide your CRD definition and/or an example of would you would like to be able to change between upgrades. So I can get a better understanding of your desired outcome.

**Comment by jainpratik163** [comment]
let say when i run the Helm install command, it creates one configmap.
now when we are running `helm upgrade` again, but this time we want to delete the configmap which is created before, so it is possible to achieve this?

**Comment by tuunit** [comment]
First of all, let's clarify that it doesn't matter if you do upgrade or install both are essentially the same. You can even do `helm upgrade --install` which will either trigger an install if nothing has been deployed yet or does an upgrade.

Furthermore, if you want to do the creation and deletion you will have to do the encasing of the complete definition as shown before and all references to the `ConfigMap` have to be encased with an if block of the same condition as well. So for example

```
env:
  - name: ONE_ENV
    value: xxxx
{{ if .Values.yourcondition }}
envfrom:
  - configMapRef:
      name: your-cm 
{{- end }}
```

Or if you truly want to check or have a condition based on first install vs upgrade. You can use the following Built-in Objects:
https://helm.sh/docs/chart_template_guide/builtin_objects

```
{{ if .Release.IsInstall }}
...
{{-end }}

{{ if .Release.IsUpgrade }}
...
{{-end }}
```

**Comment by jainpratik163** [comment]
let see in my helm chart i am using this 
and when i run helm upgrade with value drink=coffee in this case it will create this cm.
let say next time i want to run helm upgrade again but this time drink=tea so in this case it will not create this cm 
but cm is already present in the env so now what i want this time if condition is false and cm present should automatically delete .

```
{{ if eq .Values.favorite.drink "coffee" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: abc
data:
  application.yaml: |-
   
    services:
     
      aaa:
        serviceUrl: 'http://abc-wiremock.{{ .Values.ns }}.{{ .Values.cluster_domain }}:8080'
      bbb:
        serviceUrl: 'http://xyz-wiremock.{{ .Values.ns }}.{{ .Values.cluster_domain }}:8080'
{{ end }}
```

**Comment by tuunit** [comment]
In that case it will automatically delete. As helm will check for the difference to the previous deployment and it will have to restart your deployment as it's new env will not include the config map anymore.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
        - name: FIXED_ENV
          value: FIXE_VALUE
        {{ if eq .Values.favorite.drink "coffee" }}
        envFrom:
        - configMapRef:
            name: your-cm
        {{- end }}
```
