### ISSUE TITLE
Unable to run multiple tests with `helm test` when using filters

### ISSUE THREAD

**Issue by Radoslaw-Kutylowski** [helm/helm#12509]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.16-eks-2d98532", GitCommit:"af930c12e26ef9d1e8fac7e3532ff4bcc1b2b509", GitTreeState:"clean", BuildDate:"2023-07-28T16:52:47Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```
and:
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5-gke.2100", GitCommit:"fb74cdd1129d07001a41dedea406cacaec99a70f", GitTreeState:"clean", BuildDate:"2023-06-14T09:21:50Z", GoVersion:"go1.19.9 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS and GKE

---

## Issue description

We use helm to run multiple different test Jobs, using the `helm-hook: test` annotation and `helm test` command. We used to run each of them separately using `helm test --filter "name=job_name"`, but now we want some of them to run in parallel to speed up our workflows, we still need filters though as not all of them can be ran at the same time.
While trying to implement that we ran into the following issues:
1. If one `helm test` command is already running against a given release, launching a second one always exits immediately with the information that it's already started, even though the filter does not match.
2. If we put mutliple test names into the filters (as in documentation, e.g. `helm test --filter "name=test1,name=test2"), only the first one is launched.

An example which can be used to reproduce the issue (we have also tried Pods with `restart_policy: Never` instead of Jobs, with the same result):

deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: "test"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: nginx:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: {{ .Release.namespace }}
  labels:
    app: test
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  selector:
    app: test
```
test1.yaml
```
apiVersion: batch/v1
kind: Job
metadata:
  name: "test1"
  annotations:
    "helm.sh/hook": test
spec:
  template:
    spec:
      containers:
        - name: curl001
          image: busybox
          command: ['sh', '-c', 'echo The Pod is running && sleep 6']
      restartPolicy: Never
```
test2.yaml
```
apiVersion: batch/v1
kind: Job
metadata:
  name: "test2"
  annotations:
    "helm.sh/hook": test
spec:
  template:
    spec:
      containers:
        - name: curl002
          image: busybox
          command: ['sh', '-c', 'echo The Pod is running && sleep 6']
      restartPolicy: Never
```

Commands used to test first issue (ran in quick succession, sleep can be increased in yamls to get more time):
```
helm upgrade --install test-helm-jobs ./test --namespace test-helm-jobs
helm test test-helm-jobs --filter "name=test1" --namespace test-helm-jobs
helm test test-helm-jobs --filter "name=test2" --namespace test-helm-jobs
```
Command used to test second issue:
```
helm upgrade --install test-helm-jobs ./test --namespace test-helm-jobs
helm test test_release --filter "name=test1,name=test2" --namespace test-helm-jobs
```

Please let us know if there's something wrong with the way we use `helm test` or is it a bug.
