### ISSUE TITLE
Problem with subchart template conflicts)

### ISSUE THREAD

**Issue by pentago** [helm/helm#12503]
In a scenario where one uses a parent chart with many sub-charts, there can be a templating conflict, and I'm not sure whether this is Helm CLI or an actual application issue.

For example, if I run `helm template` on a directory with my parent chart, I get the following error and I'm not sure why one chart's template would impact others, leading me to think there's no isolation between sub-charts.

How do I resolve this issue so templates do not collide?

The error:

```
Error: template: core-helm-charts/charts/sealed-secrets/templates/serviceaccount.yaml:12:14: executing "core-helm-charts/charts/sealed-secrets/templates/serviceaccount.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: core-helm-charts/charts/jaeger/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: core-helm-charts/charts/jaeger/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
helm.go:84: [debug] template: core-helm-charts/charts/sealed-secrets/templates/serviceaccount.yaml:12:14: executing "core-helm-charts/charts/sealed-secrets/templates/serviceaccount.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: core-helm-charts/charts/jaeger/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: core-helm-charts/charts/jaeger/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

The parent chart:

```
apiVersion: v2
name: core-helm-charts
description: An umbrella Helm chart for Helix 3rd party Kubernetes components
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:

  - name: cert-manager
    alias: cert-manager
    version: v1.13.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled

  - name: argo-cd
    alias: argo-cd
    version: 5.46.8
    repository: https://argoproj.github.io/argo-helm
    condition: argocd.enabled

  - name: traefik
    alias: traefik
    version: v24.0.0
    repository: https://traefik.github.io/charts
    condition: traefik.enabled

  - name: rabbitmq
    alias: rabbitmq
    version: 12.2.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: rabbitmq.enabled

  - name: grafana
    alias: grafana
    version: 6.61.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled

  - name: jaeger
    alias: jaeger
    version: 0.71.17
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled

  - name: loki-stack
    alias: loki
    version: 2.9.11
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled

  - name: prometheus
    alias: prometheus
    version: 25.1.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled

  - name: connect
    alias: 1password-connect
    version: 1.14.0
    repository: https://1password.github.io/connect-helm-charts
    condition: 1password.enabled

  - name: sealed-secrets
    alias: sealed-secrets
    version: 1.5.9
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: sealed-secrets.enabled

  - name: ingress-nginx
    alias: ingress-nginx
    version: 4.8.2
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled

```

The parent chart `values.yaml`:

```
cert-manager:
  enabled: true

argocd:
  enabled: true

traefik:
  enabled: true

rabbitmq:
  enabled: true

grafana:
  enabled: true

loki:
  enabled: true

prometheus:
  enabled: true

1password:
  enabled: true

ingress-nginx:
  enabled: true

sealed-secrets:
  enabled: true

jaeger:
  enabled: true

```

Output of `helm version`:

```
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.21.3"}
```

`Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4+k3s1", GitCommit:"36645e7311e9bdbbf2adb79ecd8bd68556bc86f6", GitTreeState:"clean", BuildDate:"2023-07-28T09:46:04Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A
