### ISSUE TITLE
range can't iterate over .Values getting from dict

### ISSUE THREAD

**Issue by asahnovskiy** [helm/helm#12528]
Hello, Basically I have a values in value.yaml
```
cloudProvider: gcp

skaResources:
  storageClasses:
    aws:
      gp2:
        isDefaultClass: "false"
   azure:
     default:
        isDefaultClass: "true"
  gcp:
    standard:
        isDefaultClass: "true"
```
in temaple 

```
{{- $cloudsTypes := dict }}
{{- $_ := set $cloudsTypes "aws" ".Values.skaResources.storageClasses.aws" }}
{{- $_ := set $cloudsTypes "azure" ".Values.skaResources.storageClasses.azure" }}
{{- $_ := set $cloudsTypes "gcp" ".Values.skaResources.storageClasses.gcp" }}

{{ range $name, $value := ( get $cloudsTypes .Values.cloudProvider ) }}

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: '{{ $value.isDefaultClass }}'
{{ end }}
```
When I try to generate template I got

Error: template: resources/templates/storageclass.yaml:12:52: executing "resources/templates/storageclass.yaml" at <.Values.cloudProvider>: range can't iterate over .Values.skaResources.storageClasses.gcp

Can you help me? Thanks
