### ISSUE TITLE
`toYaml` does not properly indent list items

### ISSUE THREAD

**Issue by fheinecke** [helm/helm#12577]
Calling `toYaml` always places array items at the same indentation depth as the parent item. Here's an example of this behavior:

Template:
```yaml
---
{{- $valuesInObjForm := mustDeepCopy .Values -}}

# Via pipe:
{{ $valuesInObjForm | toYaml }}

# Via arg:
{{ toYaml $valuesInObjForm }}
```

Values:
```yaml
---
array:
  - val 1
  - val 2

key:
  nestedArray:
    - val 1
    - val 2
```

Output of `helm template`:
```yaml
---
# Source: bugtest/templates/test-template.yaml
# Via pipe:
array:
- val 1
- val 2
key:
  nestedArray:
  - val 1
  - val 2

# Via arg:
array:
- val 1
- val 2
key:
  nestedArray:
  - val 1
  - val 2
```

I would expect the following output instead:
```yaml
---
# Source: bugtest/templates/test-template.yaml
# Via pipe:
array:
  - val 1
  - val 2
key:
  nestedArray:
    - val 1
    - val 2

# Via arg:
array:
  - val 1
  - val 2
key:
  nestedArray:
    - val 1
    - val 2
```

Am I missing something here? If this is an actual bug then I figured somebody else would have found it by now.

Output of `helm version`:
`version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.21.4"}`
Also tested this on v3.10 with identical results

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A
