### ISSUE TITLE
set namespace on dependencies

### ISSUE THREAD

**Issue by cometta** [helm/helm#12585]
Output of `helm version`:
v3.13.2
Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
not relevent

```
dependencies:
- name: something
  repository: file://charts/something
- name: postgresql
   version: "13.2.9"
   repository: "@bitnami"
```
for custom subchart above `something` i able to set custom namespace in values.yaml but for 2nd subchart @bitnami, i can't set custom namespace in values.yaml.  Is this supported?
