### ISSUE TITLE
Chart not found in index prints error but does not exit

### ISSUE THREAD

**Issue by yonahd** [helm/helm#12582]
Output of `helm version`:
version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}

When running helm upgrade with a version that exists in the helm registry but not in the index I get the error

`Error: chart "my-chart" matching 1.2.3 not found in my-helm-registry index. (try 'helm repo update'): no chart version found for my-chart-1.2.3`

This is expected, but the code returns 0 which indicates success.

**Comment by yonahd** [comment]
The question is why here https://github.com/helm/helm/blob/main/pkg/repo/index.go#L162 we just continue and don't fail?

**Comment by gjenkins8** [comment]
Can you give some more concrete reproduction steps please. I think I understand what you mean, but e.g. reproduction steps would help to clarify.

**Comment by yonahd** [comment]
@gjenkins8 
This happens on an indexing issue.
e.g.

A Helm registry that has 

- my-chart-1.2.2
- my-chart-1.2.3
- my-chart-1.2.4

And the index looks like this (missing 1.2.3)

```
apiVersion: v1
entries:
  my-chart:
  - apiVersion: v2
    created: 2023-11-20T13:15:39.344285121Z
    name: my-chart
    urls:
    - https://my-helm-registry/my-chart/my-chart-1.2.2.tgz
  - apiVersion: v2
    created: 2023-1-21T10:15:39.344285121Z
    name: my-chart
    urls:
    - https://my-helm-registry/my-chart/my-chart-1.2.4.tgz    
```
