### ISSUE TITLE
Why are the quotes in an array of strings removed?

### ISSUE THREAD

**Issue by sora11023539** [helm/helm#12597]
## Why did ["bash", "-c"] become [bash -c] ??
Output of `helm version`:
```sh
version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.21.4"}
```
Output of `kubectl version`:
```sh
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:10:18Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.3+k0s", GitCommit:"a8a1abc25cad87333840cd7d54be2efaf31a3177", GitTreeState:"clean", BuildDate:"2023-11-07T08:13:20Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  k0s

values.yaml
```yaml
command: ["bash", "-c"]
args: rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'
```

deployment.yaml
```yaml
      containers:
          {{- if .Values.command }}
          command: {{ .Values.command }}
          args:
            - {{ .Values.args }}
          {{- end }}
```

```sh
$ helm install --debug --dry-run hoge --namespace fuga -f values.yaml .
      containers:
          command: [bash -c]
          args:
            - rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'
```

```sh
$ helm install hoge --namespace fuga -f values.yaml .
$ kubectl describe pods hoge
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Warning  Failed     15s (x2 over 21s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "bash -c": executable file not found in $PATH: unknown
```

## I was successful when I wrote it below.
values.yaml
```yaml
args: rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'
```

deployment.yaml
```yaml
          {{- if .Values.args }}
          command: ["bash", "-c"]
          args:
            - {{ .Values.args }}
          {{- end }}
```
