### ISSUE TITLE
How to detect execution phase?

### ISSUE THREAD

**Issue by mnp** [helm/helm#12595]
Re-opening #5801 

It would be fine to use builtins like `Release.IsInstall` and `Release.IsUpgrade` to detect hook phase, except there are two problems.

First, IsInstall appears to be True when performing `helm uninstall`.  So you can't use those builtins both being false to infer delete phase.  In this example, the hook job pod logs, `upgrade: false, install: true` when performing `helm uninstall`:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "alpine:3.3"
        command:
          - "echo"
          - "upgrade: {{ .Release.IsUpgrade }}, install: {{ .Release.IsInstall }}"
```

The second problm is  the granularity is insufficient to distinguish, eg, pre-delete from post-delete.   In all these cases, one can workaround by writing one job for each hook but that's duplication.  One could use a template to reduce the duplication, but that's complexity. 

Best case, IMO, 
1. Fix `Release.IsInstall` to be False on delete.
2. Add a new builtin object, maybe `Release.Phase` whose value would be the strings `pre-install`, `post-install`, etc.. for all phases applicable.

Thanks!

Output of `helm version`: 
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.21.3"}

Output of `kubectl version`:
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kind
