### ISSUE TITLE
Dot in value name is misinterpreted by toYaml

### ISSUE THREAD

**Issue by ogarcia** [helm/helm#12606]
I have this:
```yaml
librdkafka_options:
  "security.protocol": sasl_ssl
```

Once the filter is passed it is modified by this other one:
```yaml
librdkafka_options:
  security.protocol: sasl_ssl
```

By removing the quotes, the final system ends up interpreting it in this way:
```yaml
librdkafka_options:
  security:
    protocol: sasl_ssl
```

To reproduce simply try to use following `yaml`:
```yaml
testyaml:
  librdkafka_options:
    "security.protocol": sasl_ssl
```

With this template:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name:  test
  labels:
    alabel
data:
  config.yaml: |
{{ tpl (toYaml .Values.testyaml) . | indent 4 }}
```

**Comment by Ithrael** [comment]
> By removing the quotes, the final system ends up interpreting it in this way:
> 
> ```
> librdkafka_options:
>   security:
>     protocol: sasl_ssl
> ```

At first, I was somewhat confused about this, because I thought for k8s, it doesn't matter whether the key has quotes or not. The tests I did also seem to support this.

<img width="676" alt="image" src="https://github.com/helm/helm/assets/38208715/23a191cb-a6c4-4c1a-854d-8c9add425aa1">
Up to this point, it seems that the helm template method of stripping quotes doesn't pose a problem. 

However, if we treat the quoted part as a string value of a key, then the situation seems to be different.
<img width="764" alt="image" src="https://github.com/helm/helm/assets/38208715/7a66d0cd-f763-445e-9ed5-1d2ddf152634">

**Comment by ogarcia** [comment]
> By removing the quotes, the final system ends up interpreting it in this way:
> 
> ```yaml
> librdkafka_options:
>   security:
>     protocol: sasl_ssl
> ```

This statement is what I think is happening, but it may not be exactly like that. Don't pay too much attention to that.

Actually the problem can be seen in [this issue](https://github.com/vectordotdev/helm-charts/issues/349). 

With the complete configuration:
```yaml
role: Agent
service:
    enabled: false
serviceHeadless:
    enabled: false
customConfig:
    data_dir: /vector-data-dir
    api:
        enabled: true
        address: 127.0.0.1:8686
        playground: false
    sources:
        kubernetes_logs:
            type: kubernetes_logs
    sinks:
        kafka:
            type: kafka
            inputs:
                - kubernetes_logs
            bootstrap_servers: the.kafka.server:9093
            topic: aprettytopic
            encoding:
                codec: json
            sasl:
                enabled: true
                mechanism: PLAIN
                username: user
                password: pass
            librdkafka_options:
                "security.protocol": sasl_ssl
```

What the chart does is to apply the filter that I mentioned before (`{{ tpl (toYaml .Values.testyaml) . | indent 4 }}`) on the field `customConfig` and ends up generating the following:
```yaml
apiVersion: v1
data:
  vector.yaml: |
    api:
      address: 127.0.0.1:8686
      enabled: true
      playground: false
    data_dir: /vector-data-dir
    sinks:
      kafka:
        bootstrap_servers: the.kafka.server:9093
        encoding:
          codec: json
        inputs:
        - kubernetes_logs
        librdkafka_options:
          security.protocol: sasl_ssl
        sasl:
          enabled: true
          mechanism: PLAIN
          username: user
          password: pass
        topic: aprettytopic
        type: kafka
    sources:
      kubernetes_logs:
        type: kubernetes_logs
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: vector
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2023-11-27T10:52:37Z"
  labels:
    app.kubernetes.io/component: Agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.34.1-distroless-libc
    helm.sh/chart: vector-0.29.0
  name: vector
  namespace: monitoring
  resourceVersion: "314255883"
  uid: anuuid
```

Which removes the quotation marks from `"security.protocol"` which then causes Vector not to interpret it correctly (this is [documented here](https://vector.dev/docs/reference/configuration/sinks/kafka/#librdkafka_options)).

Of course, if I edit the configmap by hand and put the quotation marks around it, everything works correctly. 

It's not really clear to me whose problem it is. If it's in Helm for removing the quotes, if it's in the chart because it should be declared otherwise or if the problem is really that Vector should maybe pick up those extra settings from a Yaml list or a literal.
