### ISSUE TITLE
Execute `helm uninstall` got unexpected result.  RBAC resources was deleted before pod resources. 

### ISSUE THREAD

**Issue by fakecore** [helm/helm#12627]
Output of `helm version`:
v3.9.3
Output of `kubectl version`:
1.23.7
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubeadm

Action:
I have an operator cluster. 
with resource:
xx-operator
A-daemonset.yaml
```yaml
//A-daemonset.yaml
lifecycle:
  prestop:
    exec:
      command: ["/bin/bash","-c", "kubectl label node $node_name   xx/label-"]
```
after deleting. I always found the label is still exist in $node_name.
try `helm uninstall -v`
found output
```shell
delete rbac...
delete pod resources.
```

How can I delete pod resource before rbac?
