### ISSUE TITLE
How helm upgrade  work?

### ISSUE THREAD

**Issue by egoisz** [helm/helm#12631]
Firstly, I deployed a service using helm, and MANIFEST is as follows:
```
# Source: nginx-test/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx-test
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
```
Then I added the following configuration using `kubectl edit deploy`:
```
          volumeMounts:
          - mountPath: /tmp
            name: test
---
        volumes:
        - name: test
          persistentVolumeClaim:
            claimName: test
```
Finally, I upgraded the service using `helm upgrade`, the MANIFEST:
```

# Source: nginx-test/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 4 # change point
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx-test
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
```
However, I found that the configuration of volumeMounts and volumes still exists.
So Does `help upgrade` not equal `kubectl apply - f MANIFEST` ?

Can you provide more detailed explanations? I am more interested. Thank you

Output of `helm version`:
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17+k3s1", GitCommit:"abb8d7d44e4370f2a4ed2378debbc37907090295", GitTreeState:"clean", BuildDate:"2023-03-10T21:33:46Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17+k3s1", GitCommit:"abb8d7d44e4370f2a4ed2378debbc37907090295", GitTreeState:"clean", BuildDate:"2023-03-10T21:33:46Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
v1.23.17+k3s1
