### ISSUE TITLE
An exception occurs when different dependencies have the same name

### ISSUE THREAD

**Issue by yxxhero** [helm/helm#12666]
```
name: helmfile
version: 1.0.0
apiVersion: v2
dependencies:
- name: operator
  repository: git+https://github.com/minio/operator@helm/operator?ref=master
  version: '*'
- name: operator
  repository: https://charts.redpanda.com
  version: '*'
```
An exception occurs when different dependencies have the same name.
