### ISSUE TITLE
Values precedence in Helm is an incompatibility mess!

### ISSUE THREAD

**Issue by hedayat** [helm/helm#12677]
There was a behavior in Helm versions up until 3.8.2, which broke in 3.8.2 as reported in #10998 and #10899. 

This was an incompatible change, appeared in a minor version! 

Finally, it was fixed in https://github.com/helm/helm/pull/11162 

However, then #12460 was reported as an incompatibility and the behavior reverted back to that of 3.8.2-3.12. 

And now #12599 and #12511 are also open. 

It is really frustrating, please decide on the final behavior for once and fix it. Note that the old behavior makes things possible that is not possible with the **new** one. I personally prefer the old one (that of the versions prior to 3.8.2), as it allows you to override some values using a tag to import and override some other values.

**Comment by gjenkins8** [comment]
See the notes on:
https://github.com/helm/helm/pull/12162 

(and which was slightly patched with https://github.com/helm/helm/pull/12480 )

#12162 fixed many bugs. Unfortunately fixing these ultimate was going to change Helm behavior, especially for users who had "discovered" how Helm worked in certain scenarios. And thus had become reliant on the buggy implantation.

#12162 + #12480 are intended be the final implementation. But ultimately (IMHO) that given a lot of this behavior has been implemented without a tight specification, it is subjective as to what the "correct" behavior actually should be. And there still might be further bugs out there.

**Comment by hedayat** [comment]
First, as far as I can see, imported values does **NOT** override other sub-chart values. Actually, it seems that imported values doesn't override anything.


Second, the 'Using the child-parent format' section in Helm docs (https://helm.sh/docs/topics/charts/) explicitly says that imported values override parent values, as it was true before Helm 3.8.2. So, if there isn't any spec, there is at least documentation (and also old behavior). The example in docs:

Parent chart:
```
# parent's Chart.yaml file

dependencies:
  - name: subchart1
    repository: http://localhost:10191
    version: 0.1.0
    ...
    import-values:
      - child: default.data
        parent: myimports
```

```
# parent's values.yaml file

myimports:
  myint: 0
  mybool: false
  mystring: "helm rocks!"

```

```
# subchart1's values.yaml file

default:
  data:
    myint: 999
    mybool: true
```

The parent chart's resulting values would be:
```
# parent's final values

myimports:
  myint: 999
  mybool: true
  mystring: "helm rocks!"
```

As can be seen, it is expected that imported values override parent ones (e.g. myint became 999).
