### ISSUE TITLE
Error: INSTALLATION FAILED: type mismatch on crds: %!t(<nil>)

### ISSUE THREAD

**Issue by hrishidurg** [helm/helm#12678]
Output of `helm version`:
hdurg@hdurg-mac .kube % helm version
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}

Output of `kubectl version`:
hdurg@hdurg-mac .kube % kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.7

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  OCI- K8s 
Seeing below error while trying to install helm chart [MacOs Sonoma 14.2]

hdurg@hdurg-mac k8s % helm install mystskube stskube --create-namespace --namespace testmonitoring
Error: INSTALLATION FAILED: type mismatch on crds: %!t(<nil>)

Let me know the possible fix for the same .

**Comment by hrishidurg** [comment]
chart.yaml 
```
apiVersion: v2
name: stskube
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
- name: kube-prometheus-stack
  version: "54.2.1"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: traefik
  version: "25.0.0"
  repository: "https://helm.traefik.io/traefik"
```
