### ISSUE TITLE
toYaml with nindent still parsed when line is commented

### ISSUE THREAD

**Issue by mohammadfalahat** [helm/helm#12676]
I modified my templates/deployment.yaml and commented a line that contains toYaml function with nindent, 

for example:

```
            #            {{- toYaml .Values.db_resources | nindent 12 }}
```

helm still parsed a multi line result and it may occur some errors:

```
            #
            limits:
              cpu: 500m
              memory: 12Gi
            requests:
              cpu: 250m
              memory: 2Gi
```
