### ISSUE TITLE
[feature request] merge option that appends lists

### ISSUE THREAD

**Issue by cornfeedhobo** [helm/helm#12675]
As a chart developer, I would like a way to merge dictionaries with nested lists, without overwriting them.

Got:

```yaml
dst:
  list:
    - first
    - second
    - third
src:
  list:
    - forth
```

```plain
toYaml (merge .Values.dst .Values.src)
```

```yaml
list:
  - first
  - second
  - third
```

Want:

```plain
toYaml (mergeAppend .Values.dst .Values.src)
```

```yaml
list:
  - first
  - second
  - third
  - forth
```

**Comment by gjenkins8** [comment]
It is possible to "manually" specify the behavior your want (at least for simple cases). Something like:

```
result := merge .Values.dst .Values.src
result.list = concat .Values.src .Values.dst.list
```

The reason I suggest this, is that I don't disagree that in many scenarios, the replace behavior is not desirable. But overall, the problem is that there are three options for "merging" lists: replace, append and key-based merge. And isn't possible to generically know for a given list, which is the desired behavior (without additional information).

Which is why the implementation tends to default to the most basic option, and require more complex needs to be met manually (in lieu of a better solution)

**Comment by cornfeedhobo** [comment]
Thanks for pointing out that workaround. I didn't think of that.

After making this, I realized that I probably should have opened this upstream with [sprig](https://github.com/Masterminds/sprig). I might follow up on that eventually, because the above workaround gets nasty if the lists are further nested.

**Comment by tgriffitts-ns** [comment]
> result.list = concat .Values.src .Values.dst.list
@gjenkins8 Thank you so much for the solution.  Can you give an example, e.g.,  My problem (and many people's problem):

`helm upgrade -f some-remote-writes.yaml -f more-remote-writes.yaml`

```
#some-remote-writes.yaml
prometheus:
  prometheusSpec:
    remoteWrite:
    - url: https//someplace.com/write
```
```
#more-remote-writes.yaml
prometheus:
  prometheusSpec:
    remoteWrite:
    - url: https//moreplace.com/write
```
