### ISSUE TITLE
Inconsistent .Chart.Name and .Chart.Version for nested dependencies

### ISSUE THREAD

**Issue by antrusd** [helm/helm#12720]
The way Helm render `.Chart.Name` and `.Chart.Version` were different when nested chart dependencies as a wrapper charts involved. Tested with 2 level of chart dependencies.

```yaml
# grandpa/Chart.yaml

apiVersion: v2
name: grandpa
type: application
version: 1.0.0
```

```yaml
# grandpa/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: family
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
```

```yaml
# father/Chart.yaml

apiVersion: v2
name: father
type: application
version: 2.0.0

dependencies:
  - name: grandpa
    version: 1.0.0
    repository: file:///../grandpa
```

```yaml
# child/Chart.yaml

apiVersion: v2
name: child
type: application
version: 3.0.0

dependencies:
  - name: father
    version: 2.0.0
    repository: file:///../father
```

Output of `helm template`:
```yaml
---
# Source: child/charts/father/charts/grandpa/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: family
  labels:
    helm.sh/chart: father-1.0.0
```

Based on the implementation above, the end result are `.Chart.Name` takes the first level of subchart (`father`), while `.Chart.Version` takes the second level (grandpa's version) subchart (`1.0.0`).

Output of `helm version`:
```
version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.20.11"}
```
