### ISSUE TITLE
Helm dependency condition not honored when chart is pulled from OCI

### ISSUE THREAD

**Issue by saranstarz** [helm/helm#12726]
Output of `helm version`: 
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

Helm dependency condition is ignored when the chart is pulled as an OCI artifact from a registry.

Steps to repro:

1. Create a chart with a dependency and conditions

For example,
```
apiVersion: v1
appVersion: "0.1.0"
name: mychart
description: Test chart
version: 0.1.0

dependencies:
- name: dependency-chart
  version: "v0.1.0"
  repository: "file://dependency-chart"
  condition: installDependency
```

2. Package the chart and push it to OCI registry
```
helm package .
helm push mychart0.1.0.tgz oci://<registry>/helm-charts
```
3. Install the chart from oci registry directly and set the condition to false.
```
helm install  --set installDependency=false --namespace mynamespace mychart oci://<registry>/helm-charts/mychart --version 0.1.0 --create-namespace
```
Issue:
The dependency chart is always installed ignoring the condition.
