### ISSUE TITLE
read in values from subsection of values.yaml file

### ISSUE THREAD

**Issue by cometta** [helm/helm#12734]
when i `helm install something /path/parentchart/subchart2_dir --values ./values.yaml` , 

my values.yaml look like
```
subchart1:
   key1: value1
   key2: value2

subchart2:
   key1: value1
   key2: value2

```

can i do helm install --values and read only all the keys from subchart2 section of values.yaml and skip subchart1 information ?
