### ISSUE TITLE
validation: more than one dependency with name or alias

### ISSUE THREAD

**Issue by dbluxo** [helm/helm#12748]
With Helm `v3.14.0` the following use case is broken:

```
dependencies:
  - name: kube-rbac-proxy
    version: "0.9.1"
    repository: "<redacted>"
    alias: loki-query-proxy
    condition: loki-query-proxy.enabled
  - name: kube-rbac-proxy
    version: "0.9.1"
    repository: "<redacted>"
    alias: loki-ingestion-proxy
    condition: loki-ingestion-proxy.enabled
```

Various Helm commands (e.g. `helm dependency update`) now lead to the following error message:

`index.go:366: skipping loading invalid entry for chart "<redacted>" "1.3.0" from <redacted>: validation: more than one dependency with name or alias "kube-rbac-proxy"`

According to the [documentation for the Chart.yaml](https://helm.sh/docs/topics/charts/#the-chartyaml-file) using name twice with separate aliases seems to be valid:

> alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times

The error was probably introduced with [this PR](https://github.com/helm/helm/pull/9176). With Helm `v3.13.2` it worked without any problems.

**Comment by dastrobu** [comment]
While looking for a fix I found that aliasing as you wish to use it will actually not work in many cases, see #9150 and https://github.com/helm/helm/pull/9175/files#r1043661769. 
As I reported this three years ago, I did not remember all the details. 

My suggestion would be to lift the validation constraint on your case, when #9150 is fixed. Otherwise, there is a high risk of getting undefined behavior, but maintainers may have other opinions. 


Apart from that, I was actually not able to reproduce your error. 

I was trying with the following example 

```bash
mkdir -p parent/charts/child/templates

echo '
apiVersion: v2
appVersion: 1.0.0
name: child
type: application
version: 1.0.0
' > parent/charts/child/Chart.yaml

echo '
apiVersion: v2
appVersion: 1.0.0
name: parent
type: application
version: 1.0.0

dependencies:
- name: child
  alias: foo
  version: 1.0.0
- name: child
  alias: bar
  version: 1.0.0
' > parent/Chart.yaml

echo '
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
{{ toYaml .Values | indent 2}}
' > parent/charts/child/templates/dummy.yaml


touch parent/values.yaml

helm version
helm lint parent
```

which produces 

```
version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.6"}
==> Linting parent
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

Could you help to provide a full example to reproduce the error?

**Comment by dbluxo** [comment]
Thanks @mschuett for the hint, indeed it seems to be a combination of Helm `v3.14.0` and Artifactory:

Does work without errors with Helm `v3.14.0`:

```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories
```
---

Does not work without errors with Helm `v3.14.0`:

```
$ helm repo add bitnami https://<redacted>/artifactory/bitnami-helm-virtual
index.go:366: skipping loading invalid entry for chart "grafana-mimir" "0.1.0" from https://<redacted>/artifactory/bitnami-helm-virtual: validation: more than one dependency with name or alias "memcached"
index.go:366: skipping loading invalid entry for chart "grafana-mimir" "0.1.1" from https://<redacted>/artifactory/bitnami-helm-virtual: validation: more than one dependency with name or alias "memcached"
...
```
---

**But** does work without errors with Helm `v3.13.2`:

```
$ helm repo add bitnami https://<redacted>/artifactory/bitnami-helm-virtual
"bitnami" has been added to your repositories
```

**Comment by zisuu** [comment]
fyi: we also noticed that all our Devs working with helm version v3.14.0 were having those errors (we all need to pull dependencies via internal Artifactory). Some people with older helm versions can not reproduce those errors. For example v.3.10.1 seem to be fine.

**Comment by mandrean** [comment]
We're also experiencing an outage of our pipelines due to this + GHA bumping the bundled `helm` version to `3.14.0` where the `alias` validation regression exists.

**Comment by mandrean** [comment]
FYI we unblocked our pipelines by just pinning `helm` to `v3.13.2`:

```
env:
  HELM_VERSION: v3.13.2
```
```
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
           version: ${{ env.HELM_VERSION }}
           token: ${{ secrets.GITHUB_TOKEN }}
```
