### ISSUE TITLE
Overriding global values for sub charts

### ISSUE THREAD

**Issue by aqeelat** [helm/helm#12755]
Output of `helm version`: version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.6"}

### chart.yaml
```yaml
apiVersion: v2
name: myChart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: camunda-platform
    version: 8.2.8
    repository: https://helm.camunda.io
```
### values.yaml
``` yaml
global:
  image:
    repository: "myRepo"
    tag: ""
    pullPolicy: Always
    pullSecret: ""

  replicas: 1

  logLevel: "INFO"

myStuff:
  image:
    name: "myImage"
    tag: ""

camunda-platform:
  global:
    image:
      registry: ""
      pullPolicy: IfNotPresent
      tag: 8.2.8
      pullSecrets: []
    identity:
      auth:
        enabled: false
```
### values.yaml for camunda-platform:
https://github.com/camunda/camunda-platform-helm/blob/camunda-platform-8.2.8/charts/camunda-platform/values.yaml
The relevant part:
```yaml
global:
  annotations: {}
  labels:
    app: camunda-platform

  image:
    registry: ""
    tag: 8.2.8
    pullPolicy: IfNotPresent
    pullSecrets: []
```
## The issue
When I run `helm template .`, the generated yaml in camunda platform uses the values of my global object.
### example output:
```yaml
# Source: myChart/charts/camunda-platform/charts/tasklist/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-tasklist
  labels:
    app: camunda-platform
    app.kubernetes.io/name: tasklist
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    helm.sh/chart: tasklist-8.2.8
    app.kubernetes.io/version: ""
    app.kubernetes.io/component: tasklist
  annotations:
    {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-platform
      app.kubernetes.io/name: tasklist
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: camunda-platform
      app.kubernetes.io/component: tasklist
  template:
    metadata:
      labels:
        app: camunda-platform
        app.kubernetes.io/name: tasklist
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: camunda-platform
        helm.sh/chart: tasklist-8.2.8
        app.kubernetes.io/version: ""
        app.kubernetes.io/component: tasklist
    spec:
      imagePullSecrets:
        []
      containers:
      - name: tasklist
        image: "camunda/tasklist:"
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "auth"
          - name: GRAPHQL_PLAYGROUND_ENABLED
            value: "true"
          - name: GRAPHQL_PLAYGROUND_SETTINGS_REQUEST_CREDENTIALS
            value: "include"
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 400m
            memory: 1Gi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            scheme: HTTP
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: config
          mountPath: /app/resources/application.yml
          subPath: application.yml
      volumes:
      - name: config
        configMap:
          name: release-name-tasklist
          defaultMode: 484
```
Look specifically at:
* `app.kubernetes.io/version: ""` (should be `8.2.8`)
* `image: "camunda/tasklist:"` (should be `"camunda/tasklist:8.2.8"`)
* `imagePullPolicy: Always` (should be `IfNotPresent`)

After inspecting [camunda-platform/charts/tasklist/templates/deployment.yaml](url)
I found `imagePullPolicy: {{ .Values.global.image.pullPolicy }}` which seems to be the correct way to do it, but this means that I cannot override it from the individual service.

What should I do?
Bard suggests changing my global values structure to avoid collision (which actually works) but I don't think this is a scalable solution, especially when I depend on other charts that might have collisions between themselves.

I guess the main question is:
Why doesn't `.Values.global` translates to `.Values.release-name.global | default .Values.global`?
