### ISSUE TITLE
Set value with --set unexpected behaviour

### ISSUE THREAD

**Issue by pmcgrath** [helm/helm#12756]
I'm seeing default chart values being removed If I use `--set` for certain values, which I did not expect

Can use the [podinfo](https://github.com/stefanprodan/podinfo) chart to illustrate
```
helm template podinfo podinfo/podinfo \
  --set ingress.className=ing \
  --set ingress.enabled=true \
  --set ingress.hosts[0].host=podinfo.example.com | \
  yq 'select(.kind=="Ingress")'

# Source: podinfo/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo
  labels:
    helm.sh/chart: podinfo-6.5.4
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: "6.5.4"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: ing
  rules:
    - host: "podinfo.example.com"
      http:
        paths:
```
So we can see the **paths** data is missing, can see the chart templating [here](https://github.com/stefanprodan/podinfo/blob/dc830d02a6e0bcbf63bcc387e8bde57d5627aec2/charts/podinfo/templates/ingress.yaml#L34)

It seems by setting `ingress.hosts[0].host` it nulled out the sibling `ingress.hosts[0].paths` data

Strangely if I ALSO supply the values file it then works as expected and the `ingress.hosts[0].paths` data is preserved 
```
helm template podinfo podinfo/podinfo \
  --set ingress.className=ing \
  --set ingress.enabled=true \
  --set ingress.hosts[0].host=podinfo.example.com \
  -f https://raw.githubusercontent.com/stefanprodan/podinfo/master/charts/podinfo/values.yaml | \
  yq 'select(.kind=="Ingress")'

# Source: podinfo/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo
  labels:
    helm.sh/chart: podinfo-6.5.4
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: "6.5.4"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: ing
  rules:
    - host: "podinfo.example.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: podinfo
                port:
                  number: 9898
```

The **paths** are populated as I would have expected 

Output of `helm version`:
```
version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.5"}
```

Output of `kubectl version`:
```
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
kind
```
