### ISSUE TITLE
Helm dependency build support replace of repository

### ISSUE THREAD

**Issue by tlightsky** [helm/helm#12750]
Output of `helm version`:
3.13.2

Scenario:
for some reason the original helm repo dependency is very slow to access
```
dependencies:
  - name: helm-shared
    version: ~1.2.3
    repository: https://original.service/
````

when we do `helm dependency build`, it will often timeout

we want to have an ability to replace the original helm chart repository setting as a new mirror:

`helm dependency build --set-dependency helm-shared https://mirror.service/`
