### ISSUE TITLE
Helm allows duplicate ports in the service spec

### ISSUE THREAD

**Issue by franceschongg** [helm/helm#12771]
Output of `helm version`:
version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.20.2"}

Output of `kubectl version`:

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:11Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.12-eks-5e0fdde", GitCommit:"95c835ee1111774fe5e8b327187034d8136720a0", GitTreeState:"clean", BuildDate:"2024-01-02T20:34:50Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

The issue is the `helm upgrade` allows duplicate ports for the service yaml.

Example input 
```
apiVersion: v1
kind: Service
metadata:
  name: main
  labels:
    app.kubernetes.io/name: examples-go-service-main
    app.kubernetes.io/part-of: mono-repo-examples-go-service
spec:
  ports:
    - name: health
      port: 3001
      targetPort: 3001
    - name: http
      port: 8080
      targetPort: 8080
    - name: http2
      port: 8080
      targetPort: 8080
  selector:
    name: examples-go-service-main
```

But what gets applied to the service object is 
```apiVersion: v1
kind: Service
metadata:
  name: main
  labels:
    app.kubernetes.io/name: examples-go-service-main
    app.kubernetes.io/part-of: mono-repo-examples-go-service
spec:
  ports:
    - name: health
      port: 3001
      targetPort: 3001
    - name: http
      port: 8080
      targetPort: 8080
```

The issue is that after the first clean apply with duplicate service ports, and you remove the duplicate service port from the service yaml, it removes that port completely causing unexpected behaviour.

I've dug through the logic of where it happens, and this is where the issue is occurring.
https://github.com/helm/helm/blob/e81f6140ddb22bc99a08f7409522a8dbe5338ee3/pkg/kube/client.go#L653-L659

at `patch, err := strategicpatch.CreateThreeWayMergePatch(oldData, newData, currentData, patchMeta, true)`

The `oldData` here is pointing to what helm has as the previous release (which includes the duplicate ports).
The `newData` is what should be applied the new release.
The `currentData` is what gets returned from the kubernetes api server.

The three way merge is causing issues and should it be a two way merge between the `newData` and `currentData` instead of including the `oldData`.
