### ISSUE TITLE
Helm upgrade --install incorrectly sets .Release.IsUpgrade to true on clean install

### ISSUE THREAD

**Issue by jprecuch** [helm/helm#12805]
We found strange behaviour of helm upgrade --install command. 

We are trying to install chart which was not yet installed = no release with name exists.
We are using command:
```
helm upgrade --install ... ...
```
Our chart yaml job has following annotations
```
metadata:
  name: db-setup
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Release.IsUpgrade }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- end }}
```
This should trigger only when upgrade on these environments are happening. However here it is getting triggered also on "install" which is triggered by helm upgrade --install. 
When we do same command but we exchange "helm upgrade --install" with "helm install" stuff:
```
helm install ... ...
```
Everything works fine and the annotations code is not triggered.
Can you please fix this and make "helm upgrade --install" and "helm install" to be the same thing? 
It would be good if this bug would behave following way:
```
helm install = .Release.IsInstall
helm upgrade --install (no release existing) = .Release.IsInstall
helm upgrade --install (release existing) = .Release.IsUpgrade
```
Or is there some workaround for this?

Output of `helm version`:
Version:"v3.12.2"

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.11", GitCommit:"8cfcba0b15c343a8dc48567a74c29ec4844e0b9e", GitTreeState:"clean", BuildDate:"2023-06-14T09:57:26Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.11", GitCommit:"c08f6fefa516ad42eb3e5a3fe8373311b4355f5e", GitTreeState:"clean", BuildDate:"2023-11-02T19:48:50Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Any. Tested on AKS
