### ISSUE TITLE
Validate container spec inside a cron job

### ISSUE THREAD

**Issue by drewwells** [helm/helm#12807]
The container spec inside a cronjob is not validated. In fact, you can install this into the cluster without an error which I find very odd. The only thing that appears to catch the error is spinnaker. How do I validate the spec properties of the nested container inside a cronjob?

Example cronjob spec with a bug (cmd should be command)

```
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            cmd: ["/bin/bash"]
```

Output of `helm version`: 3.11.3

Output of `kubectl version`: 1.24

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/A
