### ISSUE TITLE
Allow ignoring resource for `--wait`

### ISSUE THREAD

**Issue by ctron** [helm/helm#12800]
Aside from issue https://github.com/helm/helm/issues/10733 it might come in handy to exclude certain resources from `--wait`.

It would be great to have some kind of annotation, telling Helm to consider this resource "ready":

```yaml
metadata:
  annotations:
    helm.sh/ignoreWait: "true"
```
