### ISSUE TITLE
(feat): Chart.yaml dependency additional values-custom.yaml is not supported

### ISSUE THREAD

**Issue by dataops1948-2** [helm/helm#12813]
I would like to add to my Chart.yaml dependency for example:
Chart.yaml
```yaml
apiVersion: v2
name: application
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.x.x
  values: values-custom.yaml
```

`helm version`:
3.14.2
