### ISSUE TITLE
Can't render Chart.yaml and values.yaml in Secret template

### ISSUE THREAD

**Issue by jmcgrath207** [helm/helm#12817]
Output of `helm version`: 
```bash
version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.6"}
```

Output of `kubectl version`:
```bash
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.0
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kind

I am trying to add my helm chart's `values.yaml` and `Chart.yaml` to a secret. However, I only find `.helmignore` when do `(.Files.Glob "*")` in my secret template. I have also witnessed this behavior in config maps as well.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: chart-yaml
type: Opaque
data:
{{ (.Files.Glob "*").AsSecrets | indent 2 }}


# Source: test/templates/chart-secert.yaml
apiVersion: v1
kind: Secret
metadata:
  name: chart-yaml
type: Opaque
data:
  .helmignore: IyBQYXR0ZXJucyB0byBpZ25vcmUgd2hlbiBidWlsZGluZyBwYWNrYWdlcy4KIyBUaGlzIHN1cHBvcnRzIHNoZWxsIGdsb2IgbWF0Y2hpbmcsIHJlbGF0aXZlIHBhdGggbWF0Y2hpbmcsIGFuZAojIG5lZ2F0aW9uIChwcmVmaXhlZCB3aXRoICEpLiBPbmx5IG9uZSBwYXR0ZXJuIHBlciBsaW5lLgouRFNfU3RvcmUKIyBDb21tb24gVkNTIGRpcnMKLmdpdC8KLmdpdGlnbm9yZQouYnpyLwouYnpyaWdub3JlCi5oZy8KLmhnaWdub3JlCi5zdm4vCiMgQ29tbW9uIGJhY2t1cCBmaWxlcwoqLnN3cAoqLmJhawoqLnRtcAoqLm9yaWcKKn4KIyBWYXJpb3VzIElERXMKLnByb2plY3QKLmlkZWEvCioudG1wcm9qCi52c2NvZGUvCg==
```
