### ISSUE TITLE
The update strategies of Native-Resource and Custom-Resource are difference when upgrading

### ISSUE THREAD

**Issue by rudyares** [helm/helm#12827]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:14:10Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12", GitCommit:"696a9fdd2a58340e61e0d815c5769d266fca0802", GitTreeState:"clean", BuildDate:"2022-04-13T19:01:10Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
### Describe
When I install a release with helm, I edit the field of part of the resource through kubectl, and then upgrade the release with helm, then something interesting happens. In the case of a Native Resource, the modified field in the resource is updated to the value set in the chart, but the Custom-Resource is left with the value after kubectl-edit without being updated.

### To reproduce

1. Install a release by helm，the chart contains the following two simple resources：
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      restartPolicy: Always
---
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: {{ include "demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  replicas: 1
  updateStrategy:
    type: InPlaceIfPossible
    inPlaceUpdateStrategy:
      gracePeriodSeconds: 10
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
---
# values.yaml
resources:
  limits:
    cpu: 500m
    memory: 528Mi
    ephemeral-storage: 100Mi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 100Mi
```
2. Respectively by kubectl edit command to change the fields(spec.template.spec.containers[0].resources.limits.cpu) of the two resources to 600m.
3. Upgrad this release by helm again, the chart contents remain unchanged.
4. The end result is that the cpu in deployment is updated to the value(500m) defined in the chart, while the value of the cpu in cloneset remains the value(600m) after kubectl edit.

### Additional

- I have tried the same tests with other Custom-Resources and Native-Resources, and the results are the same, so I can confirm that there is no problem with the CloneSet implementation.
- I know that the field-manager of the field will be changed to "kubectl-edit" after using kubectl edit, but why does the field-manager of the Native-Resource change back to "helm" after helm upgrade but Custom-Resource is not?
- For the above point, I consulted the helm source code, guess may be related to the following code snippet. In this code, the created patch type for CR or CRD is "merge-patch" and the created patch type for Native-Resource is "strategic-merge-patch". I'm not sure if the issue is related to the logic here.
```
// source: pkg/kube/client.go
func createPatch(target *resource.Info, current runtime.Object) ([]byte, types.PatchType, error) {
	oldData, err := json.Marshal(current)
	if err != nil {
		return nil, types.StrategicMergePatchType, errors.Wrap(err, "serializing current configuration")
	}
	newData, err := json.Marshal(target.Object)
	if err != nil {
		return nil, types.StrategicMergePatchType, errors.Wrap(err, "serializing target configuration")
	}

	// Fetch the current object for the three way merge
	helper := resource.NewHelper(target.Client, target.Mapping).WithFieldManager(getManagedFieldsManager())
	currentObj, err := helper.Get(target.Namespace, target.Name)
	if err != nil && !apierrors.IsNotFound(err) {
		return nil, types.StrategicMergePatchType, errors.Wrapf(err, "unable to get data for current object %s/%s", target.Namespace, target.Name)
	}

	// Even if currentObj is nil (because it was not found), it will marshal just fine
	currentData, err := json.Marshal(currentObj)
	if err != nil {
		return nil, types.StrategicMergePatchType, errors.Wrap(err, "serializing live configuration")
	}

	// Get a versioned object
	versionedObject := AsVersioned(target)

	// Unstructured objects, such as CRDs, may not have an not registered error
	// returned from ConvertToVersion. Anything that's unstructured should
	// use the jsonpatch.CreateMergePatch. Strategic Merge Patch is not supported
	// on objects like CRDs.
	_, isUnstructured := versionedObject.(runtime.Unstructured)

	// On newer K8s versions, CRDs aren't unstructured but has this dedicated type
	_, isCRD := versionedObject.(*apiextv1beta1.CustomResourceDefinition)

	if isUnstructured || isCRD {
		// fall back to generic JSON merge patch
		patch, err := jsonpatch.CreateMergePatch(oldData, newData)
		return patch, types.MergePatchType, err
	}

	patchMeta, err := strategicpatch.NewPatchMetaFromStruct(versionedObject)
	if err != nil {
		return nil, types.StrategicMergePatchType, errors.Wrap(err, "unable to create patch metadata from object")
	}

	patch, err := strategicpatch.CreateThreeWayMergePatch(oldData, newData, currentData, patchMeta, true)
	return patch, types.StrategicMergePatchType, err
}
```
### Expected behavior

1. How can I update fields of CR modified by other managers by helm? The --force flag causes the resource update mode to be "replace", this mode is too violent, and I am afraid there are many other problems.
2. Is there a way to ensure that the update behavior is consistent between the two resource type?

I really need your help. Thank you.
