### ISSUE TITLE
helm dependency includes incorrect version with semantic versioning

### ISSUE THREAD

**Issue by jprecuch** [helm/helm#12852]
We build charts for multiple hyperscalers and they sometimes have same version but differs with plus sign (GCP, AWS ..).
Like here we have two "other-chart" with same version but different hyperscaler.
```
2311.2.1-RC.1+GCP
2311.2.1-RC.1+AWS
```
We have following in our Chart.yaml
```
name: somechart
version: 2311.2.1
dependencies:
- condition: other-chart.enabled
  name: other-chart
  repository: PROPER_REPO_URL
  version: 2311.2.1-RC.1+GCP
```
However when we check the contents of charts directory inside of "somechart" that was created it has not the GCP version but AWS
```
apiVersion: v2
appVersion: 2311.2.1-RC.1+AWS
name: other-chart
version: 2311.2.1-RC.1+AWS
```
We tried to fetch the chart manually using helm fetch and that gets us proper chart with +GCP.
```
helm fetch testing/other-chart --version 2311.2.1-RC.1+GCP
```
The issue seems to be only with dependencies. 
It is easily reproducable also by deleting charts directory and then running locally
```
helm dependency build
```
Can you please check/explain why helm dependencies does not pick proper version +GCP but +AWS instead when there are two same versions with different name after plus sign? 

Output of `helm version`:
version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.6"}

Output of `kubectl version`:
any

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
any
