### ISSUE TITLE
Helm 3.14.1+ flags charts as invalid due to validation error on chart.metadata.name

### ISSUE THREAD

**Issue by astraldawn** [helm/helm#12868]
## Description

When using helm `3.14.1` or later, running `helm repo update` gives this error / warning message:

```
index.go:370: skipping loading invalid entry for chart "bitnami/kibana" "10.13.0" from https://artifact.corp.org/artifactory/helm: validation: chart.metadata.name "bitnami/kibana" is invalid
```

We construct our own `index.yaml` and the entry for `bitnami/kibana` for the requested version is:

```yaml
apiVersion: v1
entries:
  ...
  bitnami/kibana:
  - description: "Kibana is an open source, browser based analytics and search dashboard for Elasticsearch. Kibana strives to be easy to get started with, while also being flexible and powerful."
    digest: 4cc5731d05a0a38f1bbc7d8f89cfac8a511534240eaf06c374dfdba7662dc787
    name: bitnami/kibana
    urls:
    - https://artifact.corp.org/artifactory/api/helm/helm/bitnami/kibana-10.13.0.tgz
    appVersion: "8.12.2"
    version: "10.13.0"
  ...
```

`helm search repo` and `helm show values` for the chart continue to work, returning the correct search result for the chart as well as displaying values respectively.

When testing with helm `3.14.0`, there is no error / warning message.

## Additional information

Output of `helm version`: Tested against `3.14.0`, `3.14.1` and `3.14.2`

Output of `kubectl version`: NA

Cloud Provider/Platform (AKS, GKE, Minikube etc.): NA
