### ISSUE TITLE
Chain of subcharts won't allow exported values to be at root level

### ISSUE THREAD

**Issue by patrykk21** [helm/helm#12889]
Hello,

I'm wondering if I'm missing something or this is a bug and would love to have a feedback around this. I struggled with this problem for a couple of days already and couldn't find a solution.

The situation:
```
helm
|- testChart (application)
  |- depends on shared
|- shared (library)
  |- depends on helmet
    |- depends on bitnami common
```

```yaml
# testChart - Chart.yaml
apiVersion: v2
description: The test application
name: testChart
type: application
version: 0.1.0
dependencies:
  - name: shared
    version: 0.1.0
    repository: file://../shared
```

```yaml
# shared - Chart.yaml
apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for Kubernetes
name: shared
type: library
version: 0.1.0
dependencies:
  - name: helmet
    version: 0.11.0
    repository: https://charts.companyinfo.dev
    import-values:
      - defaults
```

When I convert `shared` temporarily to a application and add a `app.yaml` template with contents 
```
{{ include "helmet.app" . }}
```
The template gets generated correctly.

However when I use it as a library the template throws an error because the `defaults` values were not imported, or rather `.Values.configMap` is not present (this gets populated by importing `defaults` values).

If I print the `.Values` the default values were added to a sub level of `shared` like this: 
```yaml
shared:
  # ... default values here
```

But when rendering this chart directly it imports the values not into a sub-level but root level.

Please, help

Output of `helm version`: version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.22.1"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.14-dispatcher-dirty", GitCommit:"009f3ac5f1d09b1ec5d4dc811b6032271fe61f75", GitTreeState:"dirty", BuildDate:"2022-09-19T01:28:37Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.1", GitCommit:"bc401b91f2782410b3fb3f9acf43a995c4de90d2", GitTreeState:"clean", BuildDate:"2024-01-17T15:41:12Z", GoVersion:"go1.21.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  _irrelevant_
