### ISSUE TITLE
helm lint and helm package fail to find a charts subdirectory

### ISSUE THREAD

**Issue by MattiL** [helm/helm#12887]
[root@red app-deployment]# helm lint
==> Linting .
[WARNING] /root/deploy/smartview-operator/deployment/app-deployment: chart directory is missing these dependencies: smartview-client

1 chart(s) linted, 0 chart(s) failed

[root@red app-deployment]# helm package .
Error: found in Chart.yaml, but missing in charts/ directory: smartview-client

[root@red app-deployment]# ls charts/
apps-control-panel  common  community-operator  locate-server  message-gateway  nginx-ingress  rabbitmq  smartview-client  status-server  zk-cache  zookeeper

[root@red app-deployment]# cat Chart.yaml 

```
apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
dependencies: # A list of the chart requirements
  - name: nginx-ingress
    version: ~v3.4.3
    repository: https://helm.nginx.com/stable
  - name: community-operator
    version: ~0.9.0
    repository: https://mongodb.github.io/helm-charts
  - name: apps-control-panel
    version: ~5.1.140
    repository: https://repo.portalify.com/repository/helm-hosted
  - name: locate-server
    version: ~5.0.94
    repository: https://repo.portalify.com/repository/helm-hosted
  - name: zk-cache
    version: ~5.0.28
    repository: https://repo.portalify.com/repository/helm-hosted
  - name: message-gateway
    version: ~5.0.100
    repository: https://repo.portalify.com/repository/helm-hosted
  - name: zookeeper-operator
    version: ~0.2.15
    repository: https://charts.pravega.io
  - name: rabbitmq
    version: ~12.15.0
    repository: https://charts.bitnami.com/bitnami
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
  - name: status-server
    version: ~5.0.4
    repository: https://repo.portalify.com/repository/helm-hosted
  - name: smartview-client
    version: ~5.0.2-SNAPSHOT-202403150606
    repository: https://repo.portalify.com/repository/helm-hosted
name: smartview
version: 0.1.0
icon: https://portalify.com/wp-content/uploads/2022/09/logo_portalify_northcom.png

```
Output of `helm version`:
version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.21.7"}

Output of `kubectl version`:
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.11+rke2r1", GitCommit:"b9e2ad67ad146db566be5a6db140d47e52c8adb2", GitTreeState:"clean", BuildDate:"2024-02-14T16:36:00Z", GoVersion:"go1.21.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.11+rke2r1", GitCommit:"b9e2ad67ad146db566be5a6db140d47e52c8adb2", GitTreeState:"clean", BuildDate:"2024-02-14T16:36:00Z", GoVersion:"go1.21.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Name         : rke2-server
Version      : 1.27.11~rke2r1
Release      : 0.el8
Architecture : x86_64
