### ISSUE TITLE
Upgrade release with specified values doesn't merge current values

### ISSUE THREAD

**Issue by chenxinlong** [helm/helm#12901]
Reproduce:

Let say I have a chart with only two template files : 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foo.fullname" . }}
  labels:
    {{- include "foo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "foo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "foo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: foo
          image: "alpine:latest"
          imagePullPolicy: Always
          command:
          - sleep
          - infinity
          volumeMounts:
            - name: storage
              mountPath: /storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "foo.fullname" . }}-pvc
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "foo.fullname" . }}-pvc
  labels:
    {{- include "foo.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClass }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
```

values.yaml : 
```yaml
# Default values for ipstat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
storageClass: ""
```

Install chart:
```
root@master01:~/cxl# helm install foo foo-0.1.0.tgz --set storageClass=longhorn
NAME: foo
LAST DEPLOYED: Thu Mar 21 18:11:57 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

Failed when upgrade release with specified values : 
```
root@master01:~/cxl# helm upgrade foo foo-0.1.0.tgz --set replicaCount=2
Error: UPGRADE FAILED: cannot patch "foo-pvc" with kind PersistentVolumeClaim: PersistentVolumeClaim "foo-pvc" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	... // 2 identical fields
  	Resources:        {Requests: {s"storage": {i: {...}, s: "10Mi", Format: "BinarySI"}}},
  	VolumeName:       "pvc-679baf59-fca8-4249-b201-a1964dfb2e02",
- 	StorageClassName: &"longhorn",
+ 	StorageClassName: nil,
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  	DataSourceRef:    nil,
  }
```

As you can see, I'm only update the `replicaCount` field, but the storeageClass changed to nil : 
```
- 	StorageClassName: &"longhorn",
+ 	StorageClassName: nil,
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.21.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:14Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:21Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
