### ISSUE TITLE
When I rollback a Service, it fails because the Service's ClusterIP field cannot be updated.

### ISSUE THREAD

**Issue by yangchnet** [helm/helm#12916]
Output of `helm version`: version.BuildInfo{Version:"v3.14.1", GitCommit:"e8858f8696b144ee7c533bd9d49a353ee6c4b98d", GitTreeState:"clean", GoVersion:"go1.21.7"}

Output of `kubectl version`:
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.21.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

**What happened**:
1. run `helm install kruise openkruise/kruise --version 1.1.0`
2. run `helm upgrade kruise openkruise/kruise --version 1.4.0`
3. run `helm rollback kruise` or `helm rollback kruise --force`
4. got error: `Error: failed to replace object: Service "kruise-webhook-service" is invalid: [spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset, spec.ipFamilies[0]: Invalid value: []core.IPFamily(nil): primary ipFamily can not be unset]
`

**What you expected to happen:** Can rollback normally

**What have you found:**
If I install 1.1 first, then upgrade to 1.3, then upgrade to 1.4, then rollback, no error occurs.

I tried to find the reason and found that after installing 1.1 for the first time, the Service stored in the release was as follows:
```yaml
{
    "apiVersion": "v1",
    "kind": "Service",
    "spec": {
        "ports": [
            {
                "port": 443,
                "targetPort": 9876
            }
        ],
        "selector": {
            "control-plane": "controller-manager"
        }
    }
}
```

then update to 1.4, the Service stored in the release was as follows:
```yaml
{
    "apiVersion": "v1",
    "kind": "Service",
    "spec": {
        "clusterIP": "10.98.92.214",
        "clusterIPs": [
            "10.98.92.214"
        ],
        "ipFamilies": [
            "IPv4"
        ],
        "ipFamilyPolicy": "SingleStack",
        "ports": [
            {
                "port": 443,
                "targetPort": 9876
            }
        ],
        "selector": {
            "control-plane": "controller-manager"
        },
        "type": "ClusterIP"
    }
}
```

When I want to rollback from 1.4 to 1.1, when executing ThreeWayMergePatch, the patch for its product is:

```yaml
{
    "spec": {
        "clusterIP": null,
        "clusterIPs": null,
        "ipFamilies": null,
        "ipFamilyPolicy": null,
        "type": null
    }
}
```

This patch wants to delete the ClusterIP field of the Service in the cluster, which is obviously impossible to succeed.

So the error occurs.

But if I install 1.1 first, upgrade to 1.2, upgrade to 1.4, and then roll back from 1.4 to 1.2, no errors occur. This is because the release of 1.2 contains fields such as ClusterIP, so the patch generated by ThreeWayMergePatch does not update the Service.

Is this a bug? Or I can avoid it by passing some parameters？

Deleting the Service is a good solution, but I don't want to do it every time :)
