### ISSUE TITLE
Merge operation leaks to the elements

### ISSUE THREAD

**Issue by thiagomata** [helm/helm#12928]
## Context

The [merge](https://helm.sh/docs/chart_template_guide/function_list/#merge-mustmerge) operation doc is unclear on how that operation should affect the arguments. Based on the [Example 1](https://helm-playground.com/#t=LYUwTg5iAmCGBcACA3sxpIkQOgGqwBsBXEAZ2wwgEsA7CHfYs7WRRAX3YCgBiRVgNTpw1OlwzQYAIySphmBoRLlKteniXMpbTr36Ih2oarESYAYwCMstJSwamKkWsWPs5ndz6DERxB%2BNnMXEgiBtXZQpQji9EIhpzAAtYOhguBBQ0B0jWXT54pJSoaC4ZTIitGL0C5NSS83Ds5g9dIA&v=LQhQCIFsFMCcHMCWA7e4BcoAEXwGcB7GAFwAsU11doAbPacbXZAQxg1xgQsfBY6b4i0MhQBmsIvyp9eAIwyDCJcqglEFMhRADGinEJXjJkPTL2ggA), we suspect that the expected result is to mutate and return the first element. 

## [Example 1](#) - Merge seems to be mutable to the first element
<details>

### Values
```yaml
---
"merging":
  "something": "else"
  "name": "merging"
"a": 
  "somethingfroma": "a"
"b":
  "somethingfromb": "b"
"c":
  "somethingfromc": "c"
```

### Template
```yaml
# mergeda = a + original merging
mergeda: {{ merge .Values.merging .Values.a  }}

# merdedb = a + b + original merging
merdedb: {{ merge .Values.merging .Values.b  }}

# merdedc = a + b + c + original merging
merdedc: {{ merge .Values.merging .Values.c  }}

# merging = a + b + c + original merging
merging: {{ .Values.merging }}

# a is unchanged
a: {{ .Values.a }}

# b is unchanged
b: {{ .Values.b }}

# c is unchanged
c: {{ .Values.c }}
```

### Output
```yaml
# mergeda = a + original merging
mergeda: map[name:merging something:else somethingfroma:a]

# mergedb = a + b + original merging
merdedb: map[name:merging something:else somethingfroma:a somethingfromb:b]

# mergedc = a + b + c + original merging
merdedc: map[name:merging something:else somethingfroma:a somethingfromb:b somethingfromc:c]

# merging = a + b + c + original merging
merging: map[name:merging something:else somethingfroma:a somethingfromb:b somethingfromc:c]

# a is unchanged
a: map[somethingfroma:a]

# b is unchanged
b: map[somethingfromb:b]

# c is unchanged
c: map[somethingfromc:c]
```
</details>

## The Issue

But, when both elements have nested elements, the second element of the merge operation is affected by the merge operation. As described in the [Problem](https://helm-playground.com/#t=CoCwpgBAtmBODmkD2AHOBDALgSyQOwmwGcJ1oBXTdAIwBtk1YtcDMQtSAzTsAY0xLUkbCGHow8AiAHdwBPGCKYwAEwCEAKA0wEq9AC4IAbyPQ4iCADoAaulrlFlnfGx54V2-cdkIAX18aAMSkEADUZgiu8NpwKqrUhiYRFjZ2DkRO5lEeaY7UEH4BwWTh%2BeHOUTGwcSq8AIyJps6QqV4ZFW45bZa8Bf5BIaVhEL3lWW5axTLoJLz4VFCuWKoQADwAvJtb2zvbogAeaPwr5Hi87G6qGugNxqat6ZZk-cGn5%2BiXKhrUt0kPeYUBm8LogvvVGl1Hr1%2BkA&v=LQhQCIFsFMCcHMCWA7e4BcoAEXwGcB7GAFwAsU11doAbPacbXZAQxg1xgQsfBY6bhW7Kn0Y4%2BAY0kYmElgo59FEAEayJwhqPWCW0jTlyqTSk7vAzMmtttwy9B60ctP7BoA), the merge operation also affected the first element of the list.

## [Problem](https://helm-playground.com/#t=CoCwpgBAtmBODmkD2AHOBDALgSyQOwmwGcJ1oBXTdAIwBtk1YtcDMQtSAzTsAY0xLUkbCGHow8AiAHdwBPGCKYwAEwCEAKA0wEq9AC4IAbyPQ4iCADoAaulrlFlnfGx54V2-cdkIAX18aAMSkEADUZgiu8NpwKqrUhiYRFjZ2DkRO5lEeaY7UEH4BwWTh%2BeHOUTGwcSq8AIyJps6QqV4ZFW45bZa8Bf5BIaVhEL3lWW5axTLoJLz4VFCuWKoQADwAvJtb2zvbogAeaPwr5Hi87G6qGugNxqat6ZZk-cGn5%2BiXKhrUt0kPeYUBm8LogvvVGl1Hr1%2BkA&v=LQhQCIFsFMCcHMCWA7e4BcoAEXwGcB7GAFwAsU11doAbPacbXZAQxg1xgQsfBY6bhW7Kn0Y4%2BAY0kYmElgo59FEAEayJwhqPWCW0jTlyqTSk7vAzMmtttwy9B60ctP7BoA) - List element is contaminated
<details>

### Values
```yaml
---
"merging":
  "something": "else"
  "name": "merging"
"a": 
  "name": "a"
  "acc":
    "aaa": "aaa"
"b":
  "name": "b"
  "acc":
    "bbb": "bbb"
"c":
  "name": "c"
  "acc":
    "ccc": "ccc"
```

### Template
```yaml
The merge operation is a mutable operation that affects both elements when nested!

# a + original merging
mergeda: {{ merge .Values.merging .Values.a  }}

# a + b + original merging
merdedb: {{ merge .Values.merging .Values.b  }}

# mergedc = a + b + c + original merging
merdedc: {{ merge .Values.merging .Values.c  }}

# a was contaminated <=================== expected unchanged
a: {{ .Values.a }}

# b is unchanged
b: {{ .Values.b }}

# c is unchanged
c: {{ .Values.c }}
```

### Output

```yaml
The merge operation is a mutable operation that affects both elements when nested!

# mergeda = a + original merging
mergeda: map[acc:map[aaa:aaa] name:merging something:else]

# mergedb = a + b + original merging
merdedb: map[acc:map[aaa:aaa bbb:bbb] name:merging something:else]

# mergedc = a + b + c + original merging
merdedc: map[acc:map[aaa:aaa bbb:bbb ccc:ccc] name:merging something:else]

# a was contaminated <=================== expected unchanged
a: map[acc:map[aaa:aaa bbb:bbb ccc:ccc] name:a]

# b is unchanged
b: map[acc:map[bbb:bbb] name:b]

# c is unchanged
c: map[acc:map[ccc:ccc] name:c]
```
</details>

The first element to merge with the merging object has the map property element replaced with the merging object.
```
a: map[acc:map[aaa:aaa bbb:bbb ccc:ccc] name:a]
```
Expected:
```
a: map[acc:map[aaa:aaa] name:a]
```
So, both arguments are being changed by the merge function call.
Even more curious is that it seems to only affect the first value element to merge with "merging", "a" in the example.
So, "b" and "c" don't have the same issue.

### The Initial Expectation - Immutable
My initial expectation is that the merge operation would be immutable.
So, no argument from the merge operation would be affected except if explicitly overwritten.

```yaml
# mergeda = a + merging
mergeda: map[acc:map[aaa:aaa] name:merging something:else]

# merdedb = b + merging
merdedb: map[acc:map[bbb:bbb] name:merging something:else]

# merdedc = c + merging
merdedc: map[acc:map[ccc:ccc] name:merging something:else]

# merging unchanged
merging: map[something:else name:merging]

# a unchanged
a: map[acc:map[aaa:aaa] name:a]

# b unchanged
b: map[acc:map[bbb:bbb] name:b]

# c unchanged
c: map[acc:map[ccc:ccc] name:c]
```

### The Mutable Expectation
Then, I changed the expectation to assume that the merge operation mutates only the first argument.

```yaml
# mergeda = a + merging
mergeda: map[acc:map[aaa:aaa] name:merging something:else]

# mergedb = a + b + merging
merdedb: map[acc:map[aaa:aaa bbb:bbb] name:merging something:else]

# mergedc = a + b + c + merging
merdedc: map[acc:map[aaa:aaa bbb:bbb ccc:ccc] name:merging something:else]

# merging = a + b + c + merging
merging: map[acc:map[aaa:aaa bbb:bbb ccc:ccc] name:merging something:else]

# a unchanged
a: map[acc:map[aaa:aaa] name:a]

# b unchanged
b: map[acc:map[bbb:bbb] name:b]

# c unchanged
c: map[acc:map[ccc:ccc] name:c]
```

### The Unexpected Outcome
But for sure, I was not expecting the merge operation to mutate both elements when nested.
The merge operation is a mutable operation that sometimes affects both elements when nested!

```yaml
# mergeda = a + merging
mergeda: map[acc:map[aaa:aaa] name:merging something:else]

# merdedb = a + b + merging
merdedb: map[acc:map[aaa:aaa bbb:bbb] name:merging something:else]

# merdedc = a + b + c + merging
merdedc: map[acc:map[aaa:aaa bbb:bbb ccc:ccc] name:merging something:else]

# merging = a + b + c + merging
merging: map[acc:map[aaa:aaa bbb:bbb ccc:ccc] name:merging something:else]

# a was contaminated <================================================= unexpected value change
a: map[acc:map[aaa:aaa bbb:bbb ccc:ccc] name:a]
# expected >> a: map[acc:map[aaa:aaa] name:a]
# unexpected " bbb:bbb ccc:ccc"

# b is unchanged
b: map[acc:map[bbb:bbb] name:b]

# c is unchanged
c: map[acc:map[ccc:ccc] name:c]
```

### Workaround

Using deep copy in both elements [seems](https://helm-playground.com/#t=CoCwpgBAtmBODmkD2AHOBDALgSyQOwmwGcJ1oBXTdAIwBtk1YtcDMQtSAzTsAY0xLUkbCGHow8AiAHdwBPGCKYwAEwCEAKA0BiUhADU0OPGx54GmAlXoAXBADe9o1YgAKAHQA1dLXKL3liZmEAA%2BECpgYCgAwqgAngCUbl4%2BfkTuZKHhkTHxSQC%2B%2BVq61AbOQeaWESrUdo7lkB7evv6BpvBZEVGxKInJzWnupZ05PX2FxRC8ZW1mFnDVvHVOgY0pLemzHWFdub1JTan%2B0zujeRAQEzoQ5Hi87Gaq8wjtyxDrg1uXRbq39%2BiPFQaWwOJwffxkCa-O4PRBA2qg94DfylKE3GEAuEaJaI8HpaYTIA&v=LQhQCIFsFMCcHMCWA7e4BcoAEXwGcB7GAFwAsU11doAbPacbXZAQxg1xgQsfBY6bhW7Kn0Y4%2BAY0kYmElgo59FEAEayJwhqPWCW0jTlyqTSk7vAzMmtttwy9B60ctP7BoA) to be the safer way to ensure that your values will not interact in a unexpected way.

```yaml
# a + merging
mergeda: {{ merge (.Values.merging | deepCopy) (.Values.a  | deepCopy) }}

# b + merging
merdedb: {{ merge (.Values.merging | deepCopy) (.Values.b  | deepCopy) }}

# c + merging
merdedc: {{ merge (.Values.merging | deepCopy) (.Values.c | deepCopy)  }}

# unchanged
merging: {{ .Values.merging }}
# unchanged
a: {{ .Values.a }}
# unchanged
b: {{ .Values.b }}
# unchanged
c: {{ .Values.c }}
```
```yaml
# a + merging
mergeda: map[acc:map[aaa:aaa] name:merging something:else]

# b + merging
merdedb: map[acc:map[bbb:bbb] name:merging something:else]

# c + merging
merdedc: map[acc:map[ccc:ccc] name:merging something:else]

# unchanged
merging: map[name:merging something:else]
# unchanged
a: map[acc:map[aaa:aaa] name:a]
# unchanged
b: map[acc:map[bbb:bbb] name:b]
# unchanged
c: map[acc:map[ccc:ccc] name:c]

```
