### ISSUE TITLE
Helm having issues with properly resolving nested (duplicated) dependencies

### ISSUE THREAD

**Issue by ED220-RitM** [helm/helm#12954]
Output of `helm version`:
version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.21.9"}

Output of `kubectl version`: Shouldn't be relevant here, but
Client Version: v1.28.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): not relevant

### Issue:

We are having some base components (like services) defined in pre-defined charts that we are then using to build up more complex structures.

E.g.:
component-service: defines a kubernetes service resources with variable placeholders
component-quarkus: defines a lot of base setup (including deployment, poddisruptionbudget, ...), as well as include the above component for configuring a service
actual app repo: then uses component-quarkus and configures the quarkus deployment by eg providing image, env and some other configuration

Now we had the need to have more than one deployment in a single app repository.
The idea sounded simple: just add the component-quarkus chart twice as a dependency (with two different aliases), and configure them individually. But for some reason, helm is having issues resolving the template within the component-service within that, once the dependency is added twice.

### Simplified Example:

<details>
<summary>component-inner</summary>

component-inner/templates/service.yml:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.global.namespace | default "namespace" }}
  labels: {} # empty for mvp
spec:
{{- if .Values.type }}
  type: {{ .Values.type }}
{{- end }}
  ports:
  {{- range $k,$v := .Values.ports }}
    {{- if $v }}
    - name: {{ $k }}
      port: {{ tpl ( $v | toString ) $ }}
      protocol: TCP
      targetPort: {{ $k }}
    {{- end }}
  {{- end }}
  selector: {} # empty for mvp
```
component-inner/Chart.yaml:
```yaml
apiVersion: v2
type: application
name: component-inner
version: 0.1.0
description: <insert description>
```
</details>

<details>
<summary>component-outer</summary>

component-outer/Chart.yaml:
```yaml
apiVersion: v2
type: application
name: component-outer
version: 0.1.0
description: <insert description>
dependencies:
  - name: component-inner
    alias: inner
    version: 0.1.0
    repository: file://../component-inner
```
component-outer/values.yaml:
```yaml
inner:
  ports:
    http: "8080"
```
</details>

<details>
<summary>app</summary>

app/Chart.yaml:
```yaml
apiVersion: v2
type: application
name: app
version: 0.1.0
description: <insert description>
dependencies:
  - name: component-outer
    alias: outerone
    version: 0.1.0
    repository: file://../component-outer
  - name: component-outer
    alias: outertwo
    version: 0.1.0
    repository: file://../component-outer
```
app/values.yaml:
```yaml
outerone:
  inner:
    type: someType

outertwo:
  inner:
    type: someType
```
</details>

<details>
<summary>Resulting template result of app, after resolving dependencies:</summary>

```yaml
---
# Source: app/charts/outerone/charts/inner/templates/service.yml
apiVersion: v1
kind: Service
metadata:
  name: release-name
  namespace: namespace
  labels: {} # empty for mvp
spec:
  type: someType
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector: {} # empty for mvp
---
# Source: app/charts/outertwo/charts/component-inner/templates/service.yml
apiVersion: v1
kind: Service
metadata:
  name: release-name
  namespace: namespace
  labels: {} # empty for mvp
spec:
  ports:
  selector: {} # empty for mvp
```
</details>

### Observations:

- For the component, which is rendered second, neither the ports, nor the type are passed correctly
- the comment with the source in the final result shows that for the second service, the alias is ignored, and it is just using the inner component directly
- this behavior depends on the order of the dependencies defined in the Chart.yaml. If outerone and outertwo would be switched, then the other one would be rendered incorrectly
- when using two different versions of component-outer in the app, then the issue seems to be resolved (even though they still use the same version of the inner component)
- when referencing/using outertwo.component-inner.ports/type (as suggested from the result path) from app/values.yaml instead of the configured alias, then the properties are available in the actual template

Are we doing something wrong here? Or is this a bug with helm?
