### ISSUE TITLE
Additional YAML document header when rendering CRDs to stdout 

### ISSUE THREAD

**Issue by magat** [helm/helm#12953]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.22.2"}
```

Context: the CI for our charts renders all the content including CRDs before piping the result to kyverno to check compliance with internal policies. This step fails because helm produces empty documents.

This bug arises only for CRDs when rendering to stdout, if the yaml file for the CRD in the subchart starts with the document separator `---`.

To reproduce, in this repository:
```
# Add a --- at the beginning of the CRD file
$ echo -e "---\n$(cat ./cmd/helm/testdata/testcharts/subchart/crds/crdA.yaml)" > ./cmd/helm/testdata/testcharts/subchart/crds/crdA.yaml
# render
$ helm template --include-crds cmd/helm/testdata/testcharts/subchart/ | head
```

The output:
```
---
# Source: subchart/crds/crdA.yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testcrds.testcrdgroups.example.com
spec:
  group: testcrdgroups.example.com
  version: v1alpha1
```

After looking at the code, I suspect that the problem lies in this code that directly write the crd file content: https://github.com/helm/helm/blob/14d0c13e9eefff5b4a1b511cf50643529692ec94/pkg/action/action.go#L190
