### ISSUE TITLE
Default values are not getting removed when passed as null from Parent Chart

### ISSUE THREAD

**Issue by Venkatesh1505** [helm/helm#12963]
From an ArgoCD Parent App, when I refer to HAProxy helm chart by adding it as a dependency, and pass containerPorts values for http, https and stat as null, it is expected to be removed from the default values.yaml and hence not applied to services and deployments, but it's not being considered.

**Chart.yaml:**
```
apiVersion: v2
name: test-haproxy
description: This helm chart is used to extend the haproxytech haproxy helm chart.

type: application
version: 1.21.0
appVersion: 2.9.5

dependencies:
  - repository: https://haproxytech.github.io/helm-charts
    name: haproxy
    version: 1.21.0
```

**Helm values passed from Parent Chart:**
```
helm:
  values: |
    haproxy:
      containerPorts:
        http: null
        https: null
        stat: null
        mariadb: 3306
        metrics: 8404
```

The new ports added are being considered and added to services and deployments, but since http, https and stat are passed as null, it is expected that they are removed from [values.yaml](https://github.com/haproxytech/helm-charts/blob/main/haproxy/values.yaml#L170) and not passed down to services and deployments. But, even then it's not getting removed.

**Service ports snapshot:**
<img width="212" alt="image" src="https://github.com/helm/helm/assets/28728193/4caf918a-1cc2-4b3a-990e-b25a607fe570">

Saw similar issues raised, but still this issue persists - [here](https://github.com/helm/helm/issues/9027)

Output of `helm version`:
`version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.21.4"}`

Output of `kubectl version`:
```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.11-eks-b9c9ed7
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS EKS
