### ISSUE TITLE
 toToml filter converts int to float

### ISSUE THREAD

**Issue by dud225** [helm/helm#12987]
Given the following data structure in values.yaml:
```
config:
  bar: 9
```

And this in my configmap template:

```
data:
  telegraf-local.conf: |-
{{ .Values.config | toToml | indent 4 }}
```

I get this:
```
data:
  telegraf-local.conf: |-
    foo = 9.0
```
Even casting the variable via bar: `!!int 9` doesn't change the behavior, can't reproduce using the toJson filter either.

I'm running Helm version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.21.9"}

**Comment by gjenkins8** [comment]
`toToml` uses github.com/BurntSushi/toml to encode:

```
	e := toml.NewEncoder(b)
	err := e.Encode(v)
```

https://github.com/helm/helm/blob/c6beb169d26751efd8131a5d65abe75c81a334fb/pkg/engine/funcs.go#L125-L133

Either Helm is representing the value internally as float, and toToml is rendering that. Or the design decision/issue with rendering ints as floats lies upstream with github.com/BurntSushi/toml. The former should be determined first I think.

**Comment by johanfleury** [comment]
IIRC, the internal representation is float. #6010 was made to use [`json.Number`](https://pkg.go.dev/encoding/json#Number) but was then reverted.

It seems like the toml module supports `json.Number`: https://github.com/BurntSushi/toml/blob/77ce8589413d1fc280be524c8992599c42027c61/encode.go#L259-L272

**Comment by CalvinKrist** [comment]
I made a draft PR to demonstrate this, but adding unit tests for the `toToml` function that test the int and float conversion makes it appear that `BurntSushi` is handling this correctly and the issue is likely elsewhere https://github.com/helm/helm/pull/13012

**Comment by CalvinKrist** [comment]
That said, I did repro this issue. I did `helm create` to make a simple helm chart, added the following config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  telegraf-local.conf: |-
{{ .Values.config | toToml | indent 4 }}
```

copied their values:
```
config:
  bar: 9
```

and then `helm template .` returns:
```
---
# Source: mychart/templates/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  telegraf-local.conf: |-
    bar = 9.0
```
