### ISSUE TITLE
Helm packaging problem

### ISSUE THREAD

**Issue by djjudas21** [helm/helm#12992]
I am working on a Helm chart, and I have added some repositories so I can specify dependencies. `helm dep build` does the right thing but `helm package` fails.

My `chart.yaml`

```yaml
apiVersion: v2
name: authelia
version: 0.9.0-beta3
kubeVersion: ">= 1.13.0-0"
description: Authelia is a Single Sign-On Multi-Factor portal for web apps
type: application
keywords:
  - SSO
  - Authentication
  - Security
  - Two-Factor
  - YubiKey
  - Webauthn
  - Duo
  - TOTP
  - Time-based One Time Password
  - Push Notifications
  - LDAP
home: https://www.authelia.com
sources:
  - https://github.com/authelia/chartrepo/tree/master/charts/authelia
  - https://www.github.com/authelia/authelia
dependencies:
  - name: postgresql
    version: ~15
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ~19
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mariadb
    condition: mariadb.enabled
    version: ~18
    repository: "https://charts.bitnami.com/bitnami"
maintainers:
  - name: james-d-elliott
    email: james-d-elliott@users.noreply.github.com
    url: https://github.com/james-d-elliott
icon: https://avatars2.githubusercontent.com/u/59122411?s=200&v=4
appVersion: 4.38.8
deprecated: false
annotations: {}
```

My steps to reproduce:

```sh
[jonathan@latitude authelia]$ helm dep build
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "tx-smtp-relay-helm" chart repository
...Successfully got an update from the "immich" chart repository
...Unable to get an update from the "openebs" chart repository (https://openebs.github.io/charts):
	failed to fetch https://openebs.github.io/charts/index.yaml : 404 Not Found
...Successfully got an update from the "awx-operator" chart repository
...Successfully got an update from the "democratic-csi" chart repository
...Successfully got an update from the "camerahub" chart repository
...Successfully got an update from the "node-feature-discovery" chart repository
...Successfully got an update from the "portainer" chart repository
...Successfully got an update from the "actions-runner-controller" chart repository
...Successfully got an update from the "intel" chart repository
...Successfully got an update from the "k8s-home-lab" chart repository
...Successfully got an update from the "beluga-cloud" chart repository
...Successfully got an update from the "runix" chart repository
...Successfully got an update from the "oauth2-proxy" chart repository
...Successfully got an update from the "t3n" chart repository
...Successfully got an update from the "nextcloud" chart repository
...Successfully got an update from the "vmware-tanzu" chart repository
...Successfully got an update from the "rook-release" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "vikunja" chart repository
...Successfully got an update from the "authelia" chart repository
...Successfully got an update from the "harbor" chart repository
...Successfully got an update from the "djjudas21" chart repository
...Successfully got an update from the "mattermost" chart repository
...Successfully got an update from the "influxdata" chart repository
...Successfully got an update from the "kasten" chart repository
...Successfully got an update from the "deliveryhero" chart repository
...Successfully got an update from the "sosivio" chart repository
...Successfully got an update from the "ananace-charts" chart repository
...Successfully got an update from the "adfinis" chart repository
...Successfully got an update from the "gabe565" chart repository
...Successfully got an update from the "gitlab" chart repository
...Successfully got an update from the "secureCodeBox" chart repository
...Successfully got an update from the "fairwinds-stable" chart repository
...Successfully got an update from the "grafana" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "prometheus-community" chart repository
...Successfully got an update from the "k8s-at-home" chart repository
...Successfully got an update from the "truecharts" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Downloading postgresql from repo https://charts.bitnami.com/bitnami
Downloading redis from repo https://charts.bitnami.com/bitnami
Downloading mariadb from repo https://charts.bitnami.com/bitnami
Deleting outdated charts

[jonathan@latitude authelia]$ ls charts/
mariadb-18.0.2.tgz  postgresql-15.2.5.tgz  redis-19.1.3.tgz

[jonathan@latitude authelia]$ helm package .
Error: found in Chart.yaml, but missing in charts/ directory: postgresql, redis, mariadb
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.22.2"}
```

Has also been observed with Helm v3.13.3 and [chart-releaser](https://github.com/helm/chart-releaser) via GitHub Actions, not sure which version.

Output of `kubectl version`:
```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
MicroK8s
