### ISSUE TITLE
Helm sometimes renders unnecessary additional yaml document containing only a comment when templating

### ISSUE THREAD

**Issue by wimnat** [helm/helm#12996]
Output of `helm version`: version.BuildInfo{Version:"v3.14.3", GitCommit:"v3.14.3", GitTreeState:"", GoVersion:"go1.21.7"}

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

Context

Recently when trying to install Envoy Gateway via Jsonnet I hit an obscure problem using `std.prune`.  The reason I had been trying to use `std.prune` was to remove empty objects from the Envoy Gateway [install.yaml](https://github.com/envoyproxy/gateway/releases/download/v1.0.1/install.yaml) file.  This file is created via `helm template` [here](https://github.com/envoyproxy/gateway/blob/2e0971b288097e9c4d03b1d7d7300d6659ed4c39/tools/make/kube.mk#L228).

When the `install.yaml` file is rendered, it ends up with yaml documents that contain only the "Source: " comment before being followed by another document containing the actual manifest.  Example:

Actual output:

```
---
# Source: gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: securitypolicies.gateway.envoyproxy.io
```

Expected output:

```
---
# Source: gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: securitypolicies.gateway.envoyproxy.io
```

The original issue I raised with Envoy Gateway is [here](https://github.com/envoyproxy/gateway/issues/2927).

This happens because `helm template` doesn't take in to account how a manifest begins.  If it doesn't start with the `---` then it adds it in along with the comment and all is well.  However, if it does start with `---` then `helm template` will insert a document that has a comment only and then the manifest will be added after that and because the manifest starts with `---`, it is added as a separate document.

The offending line appears to be https://github.com/helm/helm/blob/main/cmd/helm/template.go#L116

My suggestion is that `helm template` should check for the yaml start document line `---\n` prior to the comment addition and remove it if it exists so that the comment will always appear _in the same document_ as the manifest it is rendering.

I'm happy to work on the issue but just want some feedback on my proposed solution.

**Comment by banjoh** [comment]
@wimnat looking at https://github.com/envoyproxy/gateway/releases/download/v1.0.1/install.yaml, it seems to contain multiple documents inside one YAML file i.e parts split with `---\n`. Some of the documents contain comments starting with `# Source: ...`

Here is an output after running `helm template`
```
#
# Gateway API Experimental channel install
#
---
# Source: foo/templates/install.yaml
# Source: gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
---
# Source: foo/templates/install.yaml
# Source: gateway-helm/crds/generated/gateway.envoyproxy.io_clienttrafficpolicies.yaml
---
# Source: foo/templates/install.yaml
# Source: gateway-helm/crds/generated/gateway.envoyproxy.io_envoypatchpolicies.yaml
---
# Source: foo/templates/install.yaml
# Source: gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
---
# Source: foo/templates/install.yaml
# Source: gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
---
# Source: foo/templates/install.yaml
# Source: gateway-helm/templates/certgen-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eg-gateway-helm-certgen
  namespace: 'envoy-gateway-system'
  labels:
    helm.sh/chart: gateway-helm-v0.0.0-latest
```

> My suggestion is that helm template should check for the yaml start document line ---\n prior to the comment addition and remove it if it exists so that the comment will always appear in the same document as the manifest it is rendering.

I'm not sure I follow your suggestion here. Specifically, what do you mean by `will always appear in the same document as the manifest`? The manifest in question contains multiple documents which helm renders as expected.
