### ISSUE TITLE
Cannot remove objects in dependent charts by setting values to null

### ISSUE THREAD

**Issue by zsolt-marta-bitrise** [helm/helm#12991]
### We're seeing that we cannot remove objects in dependent charts by setting the values to `null` , they will still get included in the result.

This used to work before, and this is causing apps deployed using ArgoCD to fail on probes getting introduced incorrectly (as they are defined in the dependent charts and cannot be nulled out). 
This works well in ArgoCD 2.9.1, bot not in 2.9.2 which [upgraded](https://github.com/argoproj/argo-cd/pull/16344/files) helm from 3.12.1 to 3.13.2, so the issue got introduced between those versions. I suspect this has to do something with this [PR](https://github.com/helm/helm/commit/0a5148faffb7110bab58a466a52be0686a69947c). The default template `ProcessDependencies()` got replaced with `ProcessDependenciesWithMerge()`, which ultimately does not remove null keys. 

Related issues:
- https://github.com/helm/helm/issues/12637 
- https://github.com/helm/helm/issues/12741
- https://github.com/argoproj/argo-cd/issues/16312

## Issue 

After running `helm template . -f values.yaml` in `helm-issue` (see setup below) and `values.yaml`:

```yaml
helm-dep:
  port: null
```

- **Got**:

```yaml
...
 spec:
      containers:
        - image: nginx:alpine
          name: nginx
          resources: {}
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
```

- **Want**:

```yaml
...
 spec:
      containers:
        - image: nginx:alpine
          name: nginx
          resources: {}
```

Please ignore that this is not functional this way, this is just to demonstrate the issue. In our real use case, this is causing probes getting incorrectly introduced, failing deployments in newer ArgoCD versions.

---

**Note: we get the correct result if we do**

```yaml
helm-dep:
  port: ""
```

## Minimal setup:
- `helm-issue/Chart.yaml`:

```
---
apiVersion: v2
appVersion: "0.1.27"
description: A Helm chart that demonstrates nulling issue
name: helm-issue
version: "0.1.0"
dependencies:
  - name: helm-dep
    version: "0.1.0"
    repository: "file://../helm-dep"
```

- `helm-issue/values.yaml`:

```yaml
helm-dep:
  port: null
```

- `helm-dep/templates/deployment.yaml`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helmtest
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helmtest
  template:
    metadata:
      labels:
        app: helmtest
    spec:
      containers:
        - image: nginx:alpine
          name: nginx
          resources: {}
          {{- with .Values.port }}
          ports:
              - containerPort: {{ .containerPort }}
                protocol: TCP
                name: {{ .name }}
          {{- end }}
```

- `helm-dep/Chart.yaml`:

```yaml
---
apiVersion: v2
appVersion: "0.1.27"
description: A Helm subchart that demonstrates nulling issue
name: helm-dep
version: "0.1.0"
```

- `helm-dep/values.yaml`:

```yaml
port:
  containerPort: 80
  name: http
```

(Of course, `helm dependency update` has to be run)

**Comment by kastl-ars** [comment]
I have the same issue with Helm v3.14.4, while it was working some time ago. Will try to get my hands on older releases and check if those are working...

**Comment by pierluigilenoci** [comment]
Can #12879 or #13654 solve this?

**Comment by scottrigby** [comment]
> Can [#12879](https://github.com/helm/helm/pull/12879) or [#13654](https://github.com/helm/helm/pull/13654) solve this?

Yes 👍 Those PRs have been merged 👏 This fix is scheduled to be in Helm 3.17.1.

**Comment by spalberg** [comment]
Still an issues in Helm v3.17.2.

But this exact issue only occurs when the chart is dependent. So if my main chart references my subchart `sub` in it's `Chart.yaml` like this:
```yaml
dependencies:
  - name: sub
    version: 0.0.1
    condition: 'sub.enabled'
``` 
I still have the original properties in my subchart.

As soon as I comment out this dependency everything works and the null override results in the removal of the property in the subchart. Does this make any sense?
