### ISSUE TITLE
Helm variables set array values (Azure Devops kubectl deployment)

### ISSUE THREAD

**Issue by jihadkhawaja-bottomline** [helm/helm#13022]
Is there a workaround for this? as I keep getting this error upon deployment in Azure DevOps

```
yaml-files/build.yml (Line: 47, Col: 5): A mapping was not expected
yaml-files/build.yml (Line: 50, Col: 5): A mapping was not expected
yaml-files/build.yml (Line: 93, Col: 5): A mapping was not expected
```

```
variables:
  excludedKeys: [ '1', '2', '3' ]
  excludedTenants: []
  excludedTenantsKeywords: []
```

Output of `helm version`:
2.14

Output of `kubectl version`:
1.30
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS
