### ISSUE TITLE
`default` template function treats 0 value as "omitted"

### ISSUE THREAD

**Issue by Endevir** [helm/helm#13036]
Hi!
I've encountered an interesting problem with helm templating engine: `default` function treats 0 (integer) values as unspecified and uses $default parameter.

---

A small example:
Having single templating yaml and values:

`template.yaml`:
```
apiVersion: v1
kind: Something
metadata:
  name: {{ default 1 .Values.myvalue0 }}
  surname: {{ default 1 .Values.myvalue555 }}
```

`values.yaml`
```
myvalue0: 0
myvalue555: 555
```

Running `helm template test test`

**Received output:**

```
---
# Source: test/templates/template.yaml
apiVersion: v1
kind: Something
metadata:
  name: 1
  surname: 555
```

**Expected output:**

```
---
# Source: test/templates/template.yaml
apiVersion: v1
kind: Something
metadata:
  name: 0
  surname: 555
```

**Seems like helm treats zero values as unspecified and replaces with first argument for `default` templating function, which is not expected behavior.**

---

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}
```

Output of `kubectl version`: 
```
k version                      (minikube/default)
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `Minikube (doesn't actually matter)`
