### ISSUE TITLE
Overriding Helm chart dependency version in parent chart

### ISSUE THREAD

**Issue by apiwoni** [helm/helm#13041]
Given chart definition as follows:

```
apiVersion: v2
name: container-chart
description: Chart containing many other charts
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: other-chart
  version: 1.1.0
  repository: <repositoryUrl>
```
Given multiple environment specific parent Helm charts with dependency. on the above defined as follows:

```
apiVersion: v2
name: parent-environment-chart
description: Parent chart for specific environment
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name:  container-chart
  version: 1.0.0
  repository: <fileRepositoryUrl>
```
Can I override "other-chart" Helm chart version in "parent-environment-chart" with other compatible version like 1.1.1?

Please note "container-chart" is not published and is part of repo for "parent-environment-chart"  so its repository is file-based. Also, I need specific version for "other-chart" in "parent-environment-chart".
For this reason, why don't you publish "container-chart' with different dependency version is not relevant solution!
