### ISSUE TITLE
Use of Helm build-in objects in Helm templates representing JSON value

### ISSUE THREAD

**Issue by sysarch-repo** [helm/helm#13065]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.15.0-rc.2", GitCommit:"c4e37b39dbb341cb3f716220df9f9d306d123a58", GitTreeState:"clean", GoVersion:"go1.22.3"}
```

Output of `kubectl version`:
```
Client Version: v1.28.5-eks-5e0fdde
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9-eks-036c24b
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
Linux ip-10-0-17-41 6.5.0-1020-aws #20~22.04.1-Ubuntu SMP Wed May  1 16:10:50 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
```

I want to template the following JSON key-value-pair contained in a JSON configuration file:
```
"serviceToDial": "{{ .Values.global.dns1.sigDnsName }}:53"
```
This is working well with the hardcoded value of "dns1" representing the release name.

When I want to make the templating generic to the release name, then the only way I have figured out is:
```
"serviceToDial": "{{ index .Values.global .Release.Name "sigDnsName" }}:53"
```
Note the quotes inside the quotes that work well during Helm templating (e.g. helm template) but **make helm lint fail**.

Is there a way to do it in a more JSON-schema conformant way?

**Comment by gjenkins8** [comment]
`printf` might allow writing the gotemplate better.

https://helm.sh/docs/chart_template_guide/function_list/#printf

You don't say what the lint error is? Nor why this is related to json-schema?

**Comment by sysarch-repo** [comment]
@gjenkins8 thanks for your comments.

As an example (and it's really just an example), let's assume the following template:
```
ubuntu@dm1:~/cicd/files/helm-lint$ cat templates/configmap.yml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: | {{ (tpl .Values.global.config $) | trim | nindent 4 }}
```
With the following values.yaml 
```
ubuntu@dm1:~/cicd/files/helm-lint$ cat values.yaml 
global:
  config: "{}"
```
the related manifest will be:
```
ubuntu@dm1:~/cicd/files/helm-lint$ helm template rel1 .
---
# Source: test/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rel1
  namespace: default
data:
  config.json: | 
    {}
```
In the next step, let's introduce the following external config.json file:
```
ubuntu@dm1:~/cicd/files/helm-lint$ cat config.json 
{
  "serviceToDial": "{{ index .Values.global .Release.Name "sigDnsName" }}:53"
}
```
along with the following values override file:
```
ubuntu@dm1:~/cicd/files/helm-lint$ cat overrides.yaml 
global:
  rel1:
    sigDnsName: lb.com
```
The templated manifest is as expected:
```
ubuntu@dm1:~/cicd/files/helm-lint$ helm template -f overrides.yaml --set-file global.config=config.json rel1 .
---
# Source: test/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rel1
  namespace: default
data:
  config.json: | 
    {
      "serviceToDial": "lb.com:53"
    }
```
The lint command throws the following error:
```
ubuntu@dm1:~/cicd/files/helm-lint$ helm lint -f overrides.yaml --set-file global.config=config.json .
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: test/templates/configmap.yml:7:21: executing "test/templates/configmap.yml" at <tpl .Values.global.config $>: error calling tpl: error during tpl function execution for "{\n  \"serviceToDial\": \"{{ index .Values.global .Release.Name \"sigDnsName\" }}:53\"\n}\n": template: gotpl:2:23: executing "gotpl" at <index .Values.global .Release.Name "sigDnsName">: error calling index: index of nil pointer

Error: 1 chart(s) linted, 1 chart(s) failed

```
Is there a way to write the config.json file in a way where both the template and lint commands succeed?
