### ISSUE TITLE
Helm incorrect processes nodeSelecto with GPU Nodes 

### ISSUE THREAD

**Issue by DoryZi** [helm/helm#13078]
Output of `helm version`:
version.BuildInfo{Version:"v3.15.1", GitCommit:"e211f2aa62992bd72586b395de50979e31231829", GitTreeState:"clean", GoVersion:"go1.22.3"}

Output of `kubectl version`:
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-gke.1589020

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

When I try to follow this guide to add GPU to an Autopilot deployment. 
The outputed yaml generated by helm looks incorrect (I use dry-run=client)
I believe there is a bug in how helm process the files:

deployment template:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-someapp-deployment
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.someapp.replicas }}
  selector:
    matchLabels:
      app: someapp
    {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: someapp
      {{- include "helm.selectorLabels" . | nindent 8 }}

    spec:
      containers:
      - image: {{ .Values.someappDeployment.someappApp.image.repository }}:{{ .Values.someappDeployment.someappApp.image.tag | default .Chart.AppVersion }}
        name: someapp
        args: {{- toYaml .Values.someappDeployment.someappApp.args | nindent 8 }}
        command:
        - python
        env:
        - name: PYTHONPATH
          value: "/app"
        ports:
        - containerPort: 50051
        resources: {{- toYaml .Values.someappDeployment.someappApp.resources | nindent
          10 }}
      nodeSelector: {{- toYaml .Values.someappDeployment.nodeSelector | nindent 8 }}
```

relevant values from values fileL:
```someappDeployment:
  replicas: 2
  someappApp:
    args:
     - backend/grpc/server.py
    resources:
      limits:
        memory: 5G
        nvidia.com/gpu: 1
      requests:
        cpu: 2
        memory: 5G
  nodeSelector:
    cloud.google.com/compute-class: "Accelerator"
    cloud.google.com/gke-accelerator: nvidia-l4
    cloud.google.com/gke-accelerator-count: 1

```

output:

```
# Source: withmartian-helm/templates/15-someapp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: someapp-deployment
  labels:
    helm.sh/chart: company-helm-0.1.0
    app.kubernetes.io/name: company-helm
    app.kubernetes.io/instance: router
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: someapp
      app.kubernetes.io/name: company
      app.kubernetes.io/instance: router
  template:
    metadata:
      labels:
        app: someapp
        app.kubernetes.io/name: company
        app.kubernetes.io/instance: release

    spec:
      containers:
      - image: <image>
        name: someapp
        args:
        - backend/grpc/server.py
        command:
        - python
        env:
        - name: PYTHONPATH
          value: "/app"
        ports:
        - containerPort: 50051
        resources:
          limits:
            memory: 5G
            nvidia.com/gpu: 1
          requests:
            cpu: 2
            memory: 5G
      nodeSelector:
        cloud.google.com/compute-class: Accelerator
        cloud.google.com/gke-accelerator: nvidia-l4
        cloud.google.com/gke-accelerator-count: 1
        loud.google.com/compute-class: Accelerator # <=========== this looks like a code bug / error

```
How can I get this to work ok? 
Can you guys please fix this ?
