### ISSUE TITLE
templating is slower when using dependencies with tagged version

### ISSUE THREAD

**Issue by Diliz** [helm/helm#13108]
helm version: 3.15.2
kubectl version:
```
Client Version: v1.26.1
Kustomize Version: v4.5.7
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Openshift

Hello there!

Currently using tagged dependencies like the following:
- mychart:1.0.0
- mychart:1.0.0+mytag
- mychart:1.0.0+0.0.0-mytag
- mychart:1.0.0+0.0.1-mytag

my Chart.yaml have the following dependency:
```
dependencies:
- name: mychart
  repository: "@myhelmrepository"
  version: 1.0.0+0.0.0-mytag
```

When I use the `helm dependency build` command then `helm template`, it's really slow, I don't know the real reason yet.

My chart uses a lot of templated functions in my case, but here is the difference in templating time:
- when using `mychart:1.0.0`: 4s
- when using `1.0.0+0.0.1-mytag`: 1m32.556s (more than 20x the original templating time)

Did you already encountered this one?
