### ISSUE TITLE
Helm Conversion issues: cannot unmarshal string into Go struct field Secret.data of type map[string][]uint8

### ISSUE THREAD

**Issue by balinteu** [helm/helm#13149]
Output of `helm version`: **version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.22.2"}**

Output of `openshift version`: **4.13.38**

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  **Private Cloud, Openshift Cluster**

 * Secret in version "v1" cannot be handled as a Secret: json: cannot unmarshal string into Go struct field Secret.data of type map[string][]uint8
 * Secret in version "v1" cannot be handled as a Secret: json: cannot unmarshal object into Go struct field Secret.data of type []uint8
  * Secret in version "v1" cannot be handled as a Secret: json: cannot unmarshal object into Go struct field Secret.data of type []uint8
  * Secret in version "v1" cannot be handled as a Secret: json: cannot unmarshal object into Go struct field Secret.data of type []uint8

Hello everybody, we are trying to restructure some of our deployments into helm Charts and I am unable to fix the issue mentioned.  Our initial take on the creation of this secret was **oc create secret  <secretName> --from-file=<K8S Config Resource>** and it worked without any issues, however in Helm it seems that the Go language has some problems with converting the **data** part of the secret into a map. 

I've been trying to find a solution for days now. I also tried importing tpl functions, tried with include, Files.Get, but somehow I end up at the same result. Any idea on how to solve this would be highly appreciated. Thank you!

```
{{- range $relatedClusters := .Values.relatedClusters }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $relatedClusters.name }}
  namespace: {{ $.Values.project }}
data:
  {{ $relatedClusters.name }}:
    apiVersion: v1
    kind: Config
    clusters:
    - name: {{ (split "-" $relatedClusters.name)._0 }}
      cluster:
        certificate-authority-data: {{ $relatedClusters.certData | toString}}
        server: {{ $relatedClusters.server }}
    contexts:
    - name: istiod-basic@{{ (split "-" $relatedClusters.name)._0 }}
      context:
        cluster: {{ (split "-" $relatedClusters.name)._0 }}
        namespace: istio-system
        user: istiod-basic
    users:
    - name: istiod-basic
      user:
        token: {{ $relatedClusters.token | toString }}
  current-context: istiod-basic@{{ (split "-" $relatedClusters.name)._0 }}
  {{- end }}
```

The value entries that I am working with right now are:
```
relatedClusters:
  - name: access-cluster
    server: https://dummyurl1:1234
    certData: test
    token: test
  - name: ha-cluster
    server: https://dummyurl2:2345
    certData: test
    token: test
  - name: worker1-cluster
    server: https://dummyurl3:4567
    certData: test
    token: test
```

**NOTE: This issue DOES NOT show up when using --dry-run. When I use --dry-run the Secret resource is being created by helm without any issues**

**Comment by idsulik** [comment]
@balinteu hi!
Try this one:
```
{{- range $relatedClusters := .Values.relatedClusters }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $relatedClusters.name }}
  namespace: {{ $.Values.project }}
type: Opaque
data:
  {{ $relatedClusters.name }}: |
    {{- $yaml := printf `apiVersion: v1
kind: Config
clusters:
- name: %s
  cluster:
    certificate-authority-data: %s
    server: %s
contexts:
- name: istiod-basic@%s
  context:
    cluster: %s
    namespace: istio-system
    user: istiod-basic
users:
- name: istiod-basic
  user:
    token: %s
current-context: istiod-basic@%s
` (split "-" $relatedClusters.name)._0 $relatedClusters.certData $relatedClusters.server (split "-" $relatedClusters.name)._0 (split "-" $relatedClusters.name)._0 $relatedClusters.token (split "-" $relatedClusters.name)._0 }}
    {{ $yaml | b64enc | quote }}
{{- end }}
```

https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#Secret 

> data (map[string][]byte)
> Data contains the secret data. Each key must consist of alphanumeric characters, '-', '_' or '.'. The serialized form of the secret data is a base64 encoded string, representing the arbitrary (possibly non-string) data value here. Described in https://tools.ietf.org/html/rfc4648#section-4
