### ISSUE TITLE
Condition not properly taken into account when linting/template/install

### ISSUE THREAD

**Issue by sushiMix** [helm/helm#13141]
When using such sample chart :
```yaml
apiVersion: v2
name: test
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: cert-manager
    version: 1.12.12
    repository: https://charts.jetstack.io/
  - name: trust-manager
    version: 0.11.0
    repository: https://charts.jetstack.io/
    condition: trust-manager.enabled
```

The condition is defined accordingly to https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags which seems a nice and readable way to manage it
running:
`helm lint` is fine.

but when running (as i'd like to validate all dependencies configuration)
```
helm lint --set "trust-manager.enabled=true"
==> Linting .
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist
[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
trust-manager:
- (root): Additional property enabled is not allowed
```
it fails.

Output of `helm version`:
version.BuildInfo{Version:"v3.15.1", GitCommit:"e211f2aa62992bd72586b395de50979e31231829", GitTreeState:"clean", GoVersion:"go1.22.3"}

Output of `kubectl version`: Not required

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Not required

could you remove the condition when forwarding the values to the sub chart to avoid such error ?

edit(mattfarina): to fix code blocks for readability.
