### ISSUE TITLE
Failing to build dependencies from OCI registrries

### ISSUE THREAD

**Issue by dvarrazzo** [helm/helm#13151]
helm version: tested 3.15.2, 3.13.2

I am trying to create a chart containing dependencies. However, `helm dependency build` fails if an OCI dependency is specified.

I believe I am following the [documentation about OCI dependencies](https://helm.sh/docs/topics/registries/#specifying-dependencies) as needed. The `Chart.yaml` file contains

```yaml
apiVersion: v2
name: service-infra
description: Deploy all the infra packages on a cluster
type: application
version: 6.0.0

dependencies:
  - name: test-metadata
    version: 0.6.0
    url: oci://testcicd.azurecr.io/helm

  - name: akv2k8s
    version: 2.3.2
    repository: https://charts.spvapi.no
    condition: akv2k8s.enabled
```

Running `helm dependency build ./charts/serivce-infra --debug` results in an error. The way I read it, it doesn't say that pulling failed, but only that building doesn't find the sub-chart where expected:

```
$ helm dependency build ./charts/service-infra --debug
Hang tight while we grab the latest from your chart repositories...
[...]
...Successfully got an update from the "spvapi" chart repository
[...]
Update Complete. ⎈Happy Helming!⎈
Error: directory charts/service-infra/charts/test-metadata not found
helm.go:84: [debug] directory charts/service-infra/charts/test-metadata not found
helm.sh/helm/v3/internal/resolver.GetLocalPath
	helm.sh/helm/v3/internal/resolver/resolver.go:257
helm.sh/helm/v3/internal/resolver.(*Resolver).Resolve
	helm.sh/helm/v3/internal/resolver/resolver.go:68
helm.sh/helm/v3/pkg/downloader.(*Manager).resolve
	helm.sh/helm/v3/pkg/downloader/manager.go:235
helm.sh/helm/v3/pkg/downloader.(*Manager).Update
	helm.sh/helm/v3/pkg/downloader/manager.go:194
helm.sh/helm/v3/pkg/downloader.(*Manager).Build
	helm.sh/helm/v3/pkg/downloader/manager.go:95
main.newDependencyBuildCmd.func1
	helm.sh/helm/v3/cmd/helm/dependency_build.go:71
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_amd64.s:1695
```

Note that authentication and paths seem ok, i.e., I can download the chart manually with:

```
helm pull oci://testcicd.azurecr.io/helm/test-metadata --version 0.6.0
```

and, after moving the received `tgz` package to `charts/serivce-infra/charts`, directory, `helm template` works ok. However `dependency build` fails even if the sub-chart package is in the `charts` directory and therefore I am unable to produce a `Charts.lock`.

Am I doing anything wrong or is it a bug?

**Comment by mattfarina** [comment]
I see an issue. Take a look at:

```yaml
dependencies:
  - name: test-metadata
    version: 0.6.0
    url: oci://testcicd.azurecr.io/helm
```

The `oci` parts starts off with `url`. Instead of `url` you should have `repository`.
