### ISSUE TITLE
semverCompare is not working properly when we add in annotation section in K8s v1.30.0

### ISSUE THREAD

**Issue by prasadsoudi** [helm/helm#13152]
Output of `helm version`:
/my-dummy-app_nw_2_bkp# helm version
version.BuildInfo{Version:"v3.15.0-rc.2", GitCommit:"c4e37b39dbb341cb3f716220df9f9d306d123a58", GitTreeState:"clean", GoVersion:"go1.22.3"}

Output of `kubectl version`:
my-dummy-app_nw_2_bkp# kubectl version
Client Version: v1.29.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

ISSUE:
semverCompare is not working properly when I use it in the annotation section.

Example section in deployment.yaml:
```
{{- $kubeVersion := trimPrefix "v" .Capabilities.KubeVersion.Version }}
...
template:
  metadata:
    annotations:
      {{- if semverCompare "<1.30" (trimPrefix "v" $kubeVersion) }}
      container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: runtime/default
      {{- end }}
...
```

So when I install this chart in K8s version v1.30.0, the above condition will be false, and hence it is not supposed to add the AppArmor annotation.

If I just run helm template, I do not see AppArmor in the annotation, which is the correct behavior.

```
helm template my-dummy-app_nw_2_bkp/ -n dummy
---
# Source: my-dummy-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-dummy-app-release-name
  labels:
    app: my-dummy-app
    chart: my-dummy-app-0.1.0
    release: release-name
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: my-dummy-app
    release: release-name
---
# Source: my-dummy-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dummy-app-release-name
  labels:
    app: my-dummy-app
    chart: my-dummy-app-0.1.0
    release: release-name
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dummy-app
      release: release-name
  template:
    metadata:
      annotations:
      labels:
        app: my-dummy-app
        release: release-name
    spec:
      containers:
        - name: my-dummy-app
          image: "akg/proj-dev/scheduler:10.7.0-h79a98r3"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: ["while true; do sleep 3600; done"]
          ports:
            - containerPort: 80
          resources:
            {}
          env:
            - name: KUBE_VERSION
              value: "v1.30.0"
            - name: SECURITY_CONTEXT
              value: "1.30.0"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - all
            appArmorProfile:
              type: RuntimeDefault
```

But if I deploy and then describe the pod, I see the AppArmor annotation, which is incorrect.
```
kubectl get pod my-dummy-app-my-release-6dd7c64f6b-csjcc -n dummy -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: b7444bbd1533d3da396f4b0d75d60ee816f3c7b4ffee64ea005ee776355857a1
    cni.projectcalico.org/podIP: 185.5.79.137/32
    cni.projectcalico.org/podIPs: 185.5.79.137/32
    container.apparmor.security.beta.kubernetes.io/my-dummy-app: runtime/default
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "185.5.79.137"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-07-02T13:29:22Z"

```

Why is semverCompare behaving differently in helm template and when deployed?

I am attaching the chart files which I used to experiment with this.
[dummyCharts.txt](https://github.com/user-attachments/files/16069564/dummyCharts.txt)
