### ISSUE TITLE
 yaml: invalid map key: map[interface 

### ISSUE THREAD

**Issue by DimaMakarevich** [helm/helm#13157]
Hello, i have sparkApplication.yaml with driver configutation:
`  driver:
    cores:  {{.Values.params.driver_cores}}`
    
in my values.yaml file:
  `params:
    driver_cores: 1`
    
   and after that in CI i tried to set  `--set params.driver_cores="\{\{ params.driver_cores \}\}"` (i want I want to use jinja template to redefine it later during the launch in airflow )
   but i got error :
   

`install.go:222: [debug] Original chart version: ""
install.go:239: [debug] CHART PATH: /builds/sparkjob
Error: YAML parse error on sparkjob/sparkApplication.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"params.driver_cores":interface {}(nil)}
helm.go:84: [debug] error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"params.driver_cores":interface {}(nil)}
YAML parse error on sparkjob/templates/sparkApplication.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:168
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
	helm.sh/helm/v3/pkg/action/install.go:312
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:314
main.newTemplateCmd.func2
	helm.sh/helm/v3/cmd/helm/template.go:95
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:[27](https://gitlab****/-/jobs/51744#L27)1
runtime.goexit
	runtime/asm_amd64.s:1695`

**BUT** when i used --set params.driver_cores="0\{\{ params.driver_cores \}\}" with 0 before brackets it work, i think helm have bug which not symbols {{ after rendering in begin,  
not allowed
`  driver:
    cores:  {{params.driver_cores}}`
allowed
`  driver:
    cores:  0{{params.driver_cores}}`
 
Output of `helm version`:3.15.2

Output of `kubectl version`:1.30.2

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Gitlab Ci,  **image:  name: alpine/k8s:1.30.2**

**Comment by gjenkins8** [comment]
```
driver:
    cores:  {{params.driver_cores}}
```

This is invalid yaml. The parser is trying to interpret the braces (`{`) as the start of a dict/map. You need to escape the braces.

**Comment by anisharaz** [comment]
# same error

ingress.yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: wsapp-ingress
  annotations:
    nginx.org/websocket-services: "wsserver-svc"

spec:
  ingressClassName: nginx
  rules:
    - host: { { .Values.ingressDomain } }
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wsclient-svc
                port:
                  number: 80
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: wsserver-svc
                port:
                  number: 80
```
values.yaml
```
ingressDomain: app.local
webSocketServerReplicas: 1

```
