### ISSUE TITLE
Cannot patch chart as the the order in patch list  does not match $setElementOrder list 

### ISSUE THREAD

**Issue by sonasingh46** [helm/helm#13161]
I have the following in my values file: 

```yaml
containerPort:
  http: 80
  https: 443
```

which is used as below in the deployment template: 

```yaml
          ports:
          {{- range $key, $value := .Values.containerPort }}
            - name: {{ $key }}
              containerPort: {{ $value }}
              protocol: TCP
          {{- end }}
```

I do a helm installation using the above configuration and it is successful. And later I update the helm values to have the following: 

```yaml
containerPort:
  http: 80
  https: 443
  user-http: 80
  user-https: 443
```

And then I try to upgrade the installation which fails with the following error: 

```
Error: UPGRADE FAILED: cannot patch "alpha-mychart" with kind Deployment: The order in patch list:
[map[containerPort:80 name:user-http] map[containerPort:80 name:http protocol:TCP] map[containerPort:443 name:user-https] map[containerPort:443 name:https protocol:TCP]]
 doesn't match $setElementOrder list:
[map[containerPort:80] map[containerPort:443] map[containerPort:80] map[containerPort:443] map[containerPort:10524]]
```

I expected that it should update the deployment as to what is present in the helm value. I am not able to understand the behaviour here and not sure if it is some bug or it is expected.    

Output of `helm version`:
```
version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.6"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.9-eks-036c24b", GitCommit:"f75443c988661ca0a6dfa0dc01ea82dd42d31278", GitTreeState:"clean", BuildDate:"2024-04-30T23:54:04Z", GoVersion:"go1.21.9", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
EKS
```
