### ISSUE TITLE
helm template when using our own helm library outputs in different order

### ISSUE THREAD

**Issue by dtwilliamsWork** [helm/helm#13168]
We are trying to convert all our helm charts to use our own standardised helm chart library.

When changing our deployment.yaml to use our chart and then running `helm template test-release-chart .` the output is different to the original deployment.yaml making it difficult to do a comparison.

for example, we're trying to change this subset deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helpers.fullname" . }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.deployment.strategy }}
  selector:
    matchLabels:
      {{- include "helpers.selectorLabels" . | nindent 6 }}
```

to use our library

```
{{- define "this.deployment" -}}
#
# Your customization here
#          
{{- end -}}
{{ if ((.Values.deployment).enabled) -}}
{{- include "nc-library-chart.deployment" (list . "this.deployment") -}}
{{- end -}}
```

but the output is different. The name in the metadata is first in the list, where as from our library it is at the bottom

```
# Source: nc-client-service-chart/templates/deployment-test.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-release-chart-nc-client-service-chart
  labels:
    helm.sh/chart: nc-client-service-chart-0.0.2
    app.kubernetes.io/name: nc-client-service-chart
    app.kubernetes.io/instance: test-release-chart
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: nc-client-service-chart
      app.kubernetes.io/instance: test-release-chart
---
# Source: nc-client-service-chart/templates/deploymentnew.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: test-release-chart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nc-client-service-chart
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: nc-client-service-chart-0.0.2
  name: test-release-chart-nc-client-service-chart
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-release-chart
      app.kubernetes.io/name: nc-client-service-chart
```

Our library is a simple implementation

```
{{- define "nc-library-chart.deployment.tpl" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nc-library-chart.fullname" . }}
  labels:
    {{- include "nc-library-chart.labels" . | nindent 4 }}
spec:
  {{- if ((.Values.autoscaling).enabled) }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nc-library-chart.selectorLabels" . | nindent 6 }}
{{- end -}}
{{- define "nc-library-chart.deployment" -}}
{{- include "nc-library-chart.util.merge" (append . "nc-library-chart.deployment.tpl") -}}
{{- end -}}
```

Is it the merge or append causing the ordering to change or is it a bug?

Output of `helm version`: v3.15.2

Output of `kubectl version`: v1.29.0-eks-5e0fdde

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS EKS
