### ISSUE TITLE
Is there any way to get the node number of cluster before `helm install`

### ISSUE THREAD

**Issue by mousimin** [helm/helm#13166]
Output of `helm version`: version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:
Client Version: v1.25.5
Kustomize Version: v4.5.7
Server Version: v1.25.15

Cloud Provider/Platform (AKS, GKE, Minikube etc.): NA

==========================
I am creating a helm chart for my own "prometheus", I'd like to deploy one pod per node, like which DaemonSet is doing, but as the storage limit, we only have a storage which only supports ReadWriteOnce, so the best choice for me is StatefulSet with affinity:
```
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
          - key: "app"
            operator: In
            values:
            - agent
      topologyKey: "kubernetes.io/hostname"
```
But by using this solution, users still need to specify the replicas, the value should be equals to their node number. This is really not convenient for users to use the chart. So my question is that is there any way to get the node number of cluster before `helm install`?
