### ISSUE TITLE
Configmap and Virtual Service not overwritten after helm upgrade

### ISSUE THREAD

**Issue by saivamsibodavulaTR** [helm/helm#13184]
Hello Team.,
I am facing an issue while trying to perform a helm Upgrade.
My current Env : Helm version tried with 3.5.4 and 3.14.0 as well
AKS version : 1.28.9
Am trying to upgrade my Helm Chart using ADO Pipelines.

Issue: After Helm Upgrade , My previous configmap / virtual service are not updated.

Here is my Helm Command: 
```
helm upgrade -i -f ./$(appName)/values.yaml -f ./$(appName).yaml \
           --set deployment.registry=${{ variables.registryName }}.azurecr.io \
           --set deployment.replicas=${{ variables.replicaCount }} \
           --set deployment.AZURE_CLIENT_ID=$(AppconfigAppspnID) \
           --set deployment.AZURE_CLIENT_SECRET=$(AppconfigAppspnSecret) \
           --set deployment.AZURE_TENANT_ID=${{ variables.spnTenantId }} \
           --set deployment.javaVMArgument="--AZURE_APP_CONFIGURATION_ENABLE=true --spring.cloud.azure.appconfiguration.stores[0].endpoint=$(PrimaryAppconfigUrl) --spring.cloud.azure.appconfiguration.stores[0].endpoints[0]=$(DRAppconfigUrl) --spring.cloud.azure.appconfiguration.stores[0].fail-fast=false --spring.cloud.azure.appconfiguration.stores[0].selects[0].keyFilter=$prefix" \
           $(appName) ./$(appName) \
           --namespace $(nameSpace) \
           --no-hooks
```
           
   Expectation:
   should be able to upgrade the helm chart, deloyment should get updated, and subsequent objects if any ( virtual service, configmap), should also get updated, if there are any changes in the values.yaml
   If I delete any value in my values.yaml/ azure app config, concerned value should be getting deleted in configmap and virtual service., 
   
   here is my configmap file :
```
   apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.app.name}}-config-map
data:
{{ template "workflow.yamlToProperty" (list "" .Values.configmap .) }}

```
and my virtual service file: 
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.configmap.app.name }}
spec:
  gateways:
    - {{ .Values.deployment.istioGateway }}
  hosts:
    - {{ .Values.deployment.hostname }}
    - {{ .Values.deployment.environment }}.highqmod.thomsonreuters.com
    - {{ .Values.deployment.environment }}.highqmod.int.thomsonreuters.com
  http:
    - match:
      - uri:
          prefix: /{{ .Values.configmap.app.name }}
      route:
      - destination:
          host: {{ .Values.configmap.app.name }}-service.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: {{ .Values.deployment.port }}
```

   
   Reality:
  Even old entries exists in the configmap and virtual service. 
  this is quite annoying, as virtualservice files would be having hostname entries and should updated after modifications.
