### ISSUE TITLE
import-values in child-parent format doesn't work

### ISSUE THREAD

**Issue by realitycheck** [helm/helm#13223]
Hello,

This is a remake of the **closed as completed** but not **fixed** bug #10052.

I'm aware of a plenty of issues like #12677, however I'd like to draw attention here since it's unclear to me why the documentation contains description of scenario which is seemed like never being correct for v3 helm.

I believe that either the documentation or the helm itself has to be fixed to mark a valid issue as **completed**.

Output of helm version:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}

version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.20.11"}

version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.21.7"}

version.BuildInfo{Version:"v3.15.3", GitCommit:"3bb50bbbdd9c946ba9989fbe4fb4104766302a64", GitTreeState:"clean", GoVersion:"go1.22.5"}
```

Original statement:

---

Hi, Can't get example from here to work:
https://helm.sh/docs/topics/charts/#using-the-child-parent-format

To reproduce:
```
cat >Chart.yaml <<EOF
apiVersion: v2
name: mychart
version: 0.1.0
dependencies:
- name: subchart1
  version: 0.1.0
  import-values:
  - child: default.data
    parent: myimports
EOF

cat >values.yaml <<EOF
myimports:
  myint: 0
  mybool: false
  mystring: "helm rocks!"
EOF

mkdir -p templates
cat >templates/test.yaml <<EOF
out: | {{ $.Values | toYaml | nindent 2 }}
EOF

mkdir -p charts/subchart1/
cat >charts/subchart1/Chart.yaml <<EOF
apiVersion: v2
name: subchart1
version: 0.1.0
EOF

cat >charts/subchart1/values.yaml <<EOF
default:
  data:
    myint: 999
    mybool: true
EOF
```
helm template .

Result:
```
---
# Source: mychart/templates/test.yaml
out: | 
  myimports:
    mybool: false
    myint: 0
    mystring: helm rocks!
  subchart1:
    default:
      data:
        mybool: true
        myint: 999
    global: {}
```
Expected:
```
---
# Source: mychart/templates/test.yaml
out: | 
  myimports:
    mybool: true
    myint: 999
    mystring: helm rocks!
  subchart1:
    default:
      data:
        mybool: true
        myint: 999
    global: {}
```
