### ISSUE TITLE
`helm template --show-only` fails to show manifests starting with `---`

### ISSUE THREAD

**Issue by sybereal** [helm/helm#13230]
When a manifest begins with the characters `---`, it is not possible to use `helm template --show-only` to display its contents.

I noticed this issue with the Grafana Alloy chart:

```shell
$  helm template grafana/alloy --version 0.5.1 --include-crds --set 'crds.create=true' --show-only 'charts/crds/crds/*'
---
# Source: alloy/charts/crds/crds/monitoring.grafana.com_podlogs.yaml
```

The source file for the given manifest is here: https://github.com/grafana/alloy/blob/0e524c45bcaeff17b8eb77a41db563a11ee9b30b/operations/helm/charts/alloy/charts/crds/crds/monitoring.grafana.com_podlogs.yaml#L1

Digging through the source code with the help of Delve, I found what I believe to be the issue in `releaseutil.SplitManifests()`:

https://github.com/helm/helm/blob/a958f3a9b65df7c809c88c180cc89886fee7768c/pkg/releaseutil/manifest.go#L36-L60

Inspecting the `docs` variable in line 48 shows that the `# Source: ...` comment and the actual manifest contents are separated due to the split operation.

```
(dlv) p docs
[]string len: 9, cap: 16, [
        "",
        "# Source: alloy/charts/crds/crds/monitoring.grafana.com_podlogs....+4 more",
        "apiVersion: apiextensions.k8s.io/v1\nkind: CustomResourceDefiniti...+9652 more",
        "# Source: alloy/templates/serviceaccount.yaml\napiVersion: v1\nkin...+330 more",
        "# Source: alloy/templates/configmap.yaml\napiVersion: v1\nkind: Co...+822 more",
        "# Source: alloy/templates/rbac.yaml\napiVersion: rbac.authorizati...+2019 more",
        "# Source: alloy/templates/rbac.yaml\napiVersion: rbac.authorizati...+484 more",
        "# Source: alloy/templates/service.yaml\napiVersion: v1\nkind: Serv...+511 more",
        "# Source: alloy/templates/controllers/daemonset.yaml\napiVersion:...+2089 more",
]
```

The code for the `template` command then matches on that magic `# Source: ...` comment to decide which manifests to print, and since the CRD without the source comment does not match, it gets skipped in line 158.

https://github.com/helm/helm/blob/a958f3a9b65df7c809c88c180cc89886fee7768c/cmd/helm/template.go#L138-L185

For reasons I have not yet investigated, this does not occur with the CRDs from the `prometheus-operator-crds` chart. My assumption is that this is because they have a comment at the start of the file, so that `---` isn't the first thing in the file:
https://github.com/prometheus-community/helm-charts/blob/dc28578a1ffc27bd7f14faa62c845fc60beaa337/charts/prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml#L1

Running `helm template prometheus-operator-crds prometheus-community/prometheus-operator-crds --version 13.0.2 --show-only 'charts/crds/templates/crd-alertmanagerconfigs.yaml'` gives the following:

```yaml
---
# Source: prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
    operator.prometheus.io/version: 0.75.2
  name: alertmanagerconfigs.monitoring.coreos.com
# ...
# SNIP
# ...
---
# Source: prometheus-operator-crds/charts/crds/templates/crd-alertmanagerconfigs.yaml
# https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.75.2/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.15.3", GitCommit:"3bb50bbbdd9c946ba9989fbe4fb4104766302a64", GitTreeState:"clean", GoVersion:"go1.22.5"}
```

Output of `kubectl version`:
```
Client Version: v1.29.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS, but running `helm template` in offline mode
