### ISSUE TITLE
`helm dep build --skip-refresh` doesn't work as expected

### ISSUE THREAD

**Issue by markmcmurray-sysdig** [helm/helm#13241]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.15.3", GitCommit:"3bb50bbbdd9c946ba9989fbe4fb4104766302a64", GitTreeState:"clean", GoVersion:"go1.22.5"}
```
Output of `kubectl version`:
```
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6-gke.1038001
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`GKE`

## Setup
I have created a scaffold chart by running `helm create foo` and added a dependency to it, it looks like this:

```
apiVersion: v2
name: foo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: linkerd-partials
    version: 0.0.5
    repository: oci://us-docker.pkg.dev/artifact-registry-dev/gar-charts
```

When I run `helm dep build --skip-refresh` it downloads the dependency as expected, creating a Chart.lock file and adding a directory `charts/` alongside the Chart.yaml:

```
# cat Chart.lock
dependencies:
- name: linkerd-partials
  repository: oci://us-docker.pkg.dev/artifact-registry-dev/gar-charts
  version: 0.0.5
digest: sha256:566a28f7e08c527ea73512133dab70c955f5d286e8617e1f1afad3cd2163b7b6
generated: "2024-08-09T13:38:57.160559+01:00"
```

```
# ls charts/
linkerd-partials-0.0.5.tgz
```

## Problem

The problem comes now when I re-run `helm dep build --skip-refresh`; the dependency is again downloaded (with a `tmpcharts/` directory being created in the interim). The contents of `charts/` is exactly the same before and after, confirmed by SHA.

This process only takes a matter of seconds but I'm trying to do this as part of a dev-loop so ~5s x multiple releases (different micro-services being worked on) can extend this dev-loop refresh time too much.

Am I misunderstanding how `--skip-refresh` should work? Or is this how it works with OCI charts? Is there a way to get helm to use the existing local dependency chart?
