### ISSUE TITLE
`helm dependency update` and `helm dependency build` generate a `Chart.lock` using arbitrary build info ordering

### ISSUE THREAD

**Issue by HenriBlacksmith** [helm/helm#13245]
Output of `helm version`:
`
version.BuildInfo{Version:"v3.15.1", GitCommit:"e211f2aa62992bd72586b395de50979e31231829", GitTreeState:"clean", GoVersion:"go1.22.3"}
`

I am using `helm dependency update` and `helm dependency build` commands to build a `Chart.lock` file from a `Chart.yaml` file of the following form:

```yaml
apiVersion: v2
name: my-api
description: Chart to deploy My API

type: application
version: 0.1.0+00ae8
dependencies:
  - name: my-api
    version: 0.1.0+00ae8
    repository: https://artifactory.mycompany.org/helm
```

This pattern is used by Argo CD to enable deployment of applications from parallel git branches, to do so, we build charts from our application repository with a SemVer2 version having the format `{major}.{minor}.{patch}+{build_info}`

Where build_info is `git rev-parse --short=5 HEAD`.

Though when trying to build a `Chart.lock` file from that or when simply trying to sync that file from ArgoCD, Helm always return the latest version matching `{major}.{minor}.{patch}` and with the latest `build_info` in terms of lexicographic order despite the exact version specified in the `Chart.yaml`.

I might be wrong but: 

- the `build_info` must not be used to order versions between themselves as it is an arbitrary string
- Helm dependency management must honor the exact version in `dependencies.version` when specified.

Otherwise it is completely useless to support SemVer2 versions as build_info are misused.

Furthermore it prevents the use of parallel builds from parallel branches to deploy Helm charts in a dev workflow.

- Can you confirm my interpretation is correct?
