### ISSUE TITLE
 $files.get does not work on windows

### ISSUE THREAD

**Issue by zakaryanla** [helm/helm#13295]
When using the grafana template, an empty value is formed in configmap.

Chart:
https://github.com/grafana/helm-charts/blob/fde4cc02a095327e6fdb1f860ed02d0bdb5195ae/charts/grafana/templates/_config.tpl#L52

My values.yaml:
```
alerting:
  crud-alert-rules.yaml:
    file: "rules.yaml"
```

Resault helm install -f values.yaml:
```
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: pm
  labels:
    helm.sh/chart: grafana-8.4.8
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "11.1.4"
    app.kubernetes.io/managed-by: Helm
data:
  crud-alert-rules.yaml:
    ""
```
The contents from rules.yaml were not pulled in, although the file is located next to values.yaml

**Output of `helm version`:**
version.BuildInfo{Version:"v3.15+unreleased", GitCommit:"a958f3a9b65df7c809c88c180cc89886fee7768c", GitTreeState:"clean", GoVersion:"go1.22.5"}

**Output of `kubectl version`:**
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
**Cloud Provider/Platform (AKS, GKE, Minikube etc.): **
minikube version: v1.33.1
commit: 5883c09216182566a63dff4c326a6fc9ed2982ff
