### ISSUE TITLE
Helm `merge` mutates the leftmost dict

### ISSUE THREAD

**Issue by aqeelat** [helm/helm#13308]
Given these files:
templates/_helpers.tpl:
```tpl
{{- define "test" -}}
# {{ toString .global.random }}
{{- $val := merge .global.random (dict "name" .name)  }}
- name: {{ $val.name }} # {{ toString .global.random }}
  value: {{ .name }}
{{- end -}}
```

templates/test.yaml:
```yaml
env:
{{- range $appName, $appValues := .Values.apps }}
{{ include "test" (dict "name" $appName "global" $.Values.global) | indent 2 }}
{{- end }}
# {{ toString .Values.global.random }}
```
values.yaml:
```
global:
  random: {}

apps:
  app1: {}
  app2: {}
  app3: {}
```

Run `helm template .`

Output:
```
---
# Source: test/templates/test.yaml
env:
  # map[]
  - name: app1 # map[name:app1]
    value: app1
  # map[name:app1]
  - name: app1 # map[name:app1]
    value: app2
  # map[name:app1]
  - name: app1 # map[name:app1]
    value: app3
# map[name:app1]
```
As you can see, at first, .Values.global.random was empty, but then it changed after the first iteration.

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.15.4", GitCommit:"fa9efb07d9d8debbb4306d72af76a383895aa8c4", GitTreeState:"clean", GoVersion:"go1.22.6"}
```
