### ISSUE TITLE
Helm does not handle duplicate volume mount names; only the last defined volume mount is used

### ISSUE THREAD

**Issue by Abubakar-K-Back** [helm/helm#13311]
**What happened?**
When deploying a Helm chart that defines multiple volume mounts with the same `mountPath`, Kubernetes applies only the last defined volume mount to that path. Helm does not currently detect or warn about these conflicts during the template rendering phase.

**What you expected to happen?**
Helm should detect when multiple volume mounts are defined with the same `mountPath` and raise a warning or error. This would help prevent configuration conflicts and ensure the deployment behaves as expected.

**How to reproduce it (as minimally and precisely as possible)?**
1. Create a Helm chart with a pod specification that defines multiple volume mounts with the same `mountPath`.
2. Deploy the chart to a Kubernetes cluster.
3. Observe that Kubernetes only applies the last volume mount defined for the conflicting `mountPath`.

**Example:**
```
apiVersion: v1
kind: Pod
metadata:
  name: my-test-pod
spec:
  containers:
  - name: test-container
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: /app/config    # First volume mount with /app/config
    - name: secrets-volume
      mountPath: /app/config    # Second volume mount with the same path /app/config (this will cause a conflict)
  volumes:
  - name: config-volume
    configMap:
      name: config
  - name: secrets-volume
    secret:
      secretName: secrets
```

Output of `helm template .` on chart/: no error

Output of `kubectl apply -f deployment.yaml`: The Pod "my-test-pod" is invalid: spec.containers[0].volumeMounts[1].mountPath: Invalid value: "/app/config": must be unique

Output of `helm version`: version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

Output of `kubectl version`:Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2

I would like to work on a solution for this issue. If possible, could someone assign this issue to me? I am interested in contributing a fix and would appreciate any guidance or pointers to the relevant parts of the codebase.
