### ISSUE TITLE
helm rollback sometimes doesn't rollback to the original state

### ISSUE THREAD

**Issue by matthiasvegh** [helm/helm#13346]
Output of `helm version`:
version.BuildInfo{Version:"v3.16.1", GitCommit:"5a5449dc42be07001fd5771d56429132984ab3ab", GitTreeState:"clean", GoVersion:"go1.22.7"}

also tested on:
version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.20.8"}

The 3-way merging logic of Helm is causing me some headaches. If a new container (for example) is added to my deployment that I upgrade to but that upgrade fails, Helm sometimes considers the new container to be an external addition that then does not remove even with `helm rollback`.

Given the following Chart:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leakyrollback
spec:
  selector:
    matchLabels:
      app: leakyrollback

  replicas: 1
  template:
    metadata:
      labels:
        app: leakyrollback
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: main
          image: busybox:latest
          args:
            - "/bin/sh"
            - "-c"
            - "date && sleep infinity"
        {{ if (.Values.feature) }}
        - name: featureimplementer
          image: busybox:latest
          args:
            - "/bin/sh"
            - "-c"
            - "echo Feature implementer && sleep infinity"
        {{ end }}
---
{{- if (.Values.makeUpgradeFailAtPost) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "failurecauser"
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: never
          image: busybox:latest
          args:
            - "/bin/sh"
            - "-c"
            - "date && false"
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0
{{- end -}}
```
If I install with `helm install -n NS`, all is well. If I then upgrade to enable the feature with `helm upgrade --set feature=true --set makeUpgradeFailAtPost=true` the upgrade fails but only _after_ the Deployment manifest has been patched. So far, perfectly reasonable behavior.

If I then revert the values changes and update the release with `helm upgrade`, the additional container is considered to be externally added as suggested in [3-way-strategic-merge-patches](https://helm.sh/docs/faq/changes_since_helm2/#improved-upgrade-strategy-3-way-strategic-merge-patches). This seems to be because Helm considers the _last successful_ deployment to be the basis of comparison, and ignores the the last _attempted_ deployment even if it failed in post-upgrade which means that most differences to the manifests are actually coming from the upgraded release, not an external tool.

This is rather confusing behavior. Once the new revision is complete, the new container is now part of the live Pods, and even a `helm rollback 1` keeps it there.

Of course, the change in the chart need not be a new container in an existing Pod, it could be a new envvar, a new spec setting and so on. The only fields that appear to be immune from this are fields that were already set in the successful revision (i.e., image tags of previously present containers are always rolled back).

The only scenario I can see where Helm removes the newly added container is if I invoke `helm rollback` immediately after the failed upgrade (or use `--atomic`). Any intervening upgrades that "adopt" the changes cause `helm rollback` to keep them.

Shouldn't `helm rollback r` behave the same regardless of how many intervening failed `helm upgrade`s there were?
I can see why it follows from having 3-way merges and taking the last _successful_ deployment as base, but is that wise? As things stand, changes made in failed upgrades can be adopted by Helm which are then kept for subsequent upgrades and rollbacks making them sticky.

Reproduction steps and full logs are below.

## Initial install and validation

```bash
kubectl create ns leakyrollback
helm install -n leakyrollback test .
kubectl -n leakyrollback get pod
```

Output:

```
NAME: test
LAST DEPLOYED: Mon Sep 23 18:39:34 2024
NAMESPACE: leakyrollback
STATUS: deployed
REVISION: 1
TEST SUITE: None

NAME                             READY   STATUS    RESTARTS   AGE
leakyrollback-67d976b847-l5gr9   1/1     Running   0          5s
```
So far, so good.

## helm upgrade to enable feature-flag which fails

```bash
helm upgrade -n leakyrollback --debug test . --set makeUpgradeFailAtPost=true --set feature=true
kubectl -n leakyrollback get pod
```

Output:
```
upgrade.go:164: 2024-09-23 18:39:57.119827386 +0200 CEST m=+0.239306317 [debug] preparing upgrade for test
upgrade.go:172: 2024-09-23 18:39:57.751371326 +0200 CEST m=+0.870850236 [debug] performing update for test
upgrade.go:375: 2024-09-23 18:39:58.08346789 +0200 CEST m=+1.202946800 [debug] creating upgraded release for test
client.go:393: 2024-09-23 18:39:58.215098365 +0200 CEST m=+1.334577300 [debug] checking 1 resources for changes
client.go:693: 2024-09-23 18:39:58.342892703 +0200 CEST m=+1.462371645 [debug] Patch Deployment "leakyrollback" in namespace leakyrollback
client.go:486: 2024-09-23 18:39:58.553708001 +0200 CEST m=+1.673186902 [debug] Starting delete for "failurecauser" Job
client.go:490: 2024-09-23 18:39:58.613858169 +0200 CEST m=+1.733337100 [debug] Ignoring delete failure for "failurecauser" batch/v1, Kind=Job: jobs.batch "failurecauser" not found
wait.go:104: 2024-09-23 18:39:58.613930096 +0200 CEST m=+1.733409027 [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: 2024-09-23 18:39:59.011984507 +0200 CEST m=+2.131463432 [debug] creating 1 resource(s)
client.go:712: 2024-09-23 18:39:59.085350708 +0200 CEST m=+2.204829636 [debug] Watching for changes to Job failurecauser with timeout of 5m0s
client.go:740: 2024-09-23 18:39:59.148795119 +0200 CEST m=+2.268274062 [debug] Add/Modify event for failurecauser: ADDED
client.go:779: 2024-09-23 18:39:59.148864227 +0200 CEST m=+2.268343159 [debug] failurecauser: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: 2024-09-23 18:40:02.772383345 +0200 CEST m=+5.891862287 [debug] Add/Modify event for failurecauser: MODIFIED
client.go:779: 2024-09-23 18:40:02.772440631 +0200 CEST m=+5.891919558 [debug] failurecauser: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: 2024-09-23 18:40:02.796101363 +0200 CEST m=+5.915580301 [debug] Add/Modify event for failurecauser: MODIFIED
client.go:486: 2024-09-23 18:40:02.929281415 +0200 CEST m=+6.048760316 [debug] Starting delete for "failurecauser" Job
wait.go:104: 2024-09-23 18:40:02.991465058 +0200 CEST m=+6.110943987 [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
upgrade.go:487: 2024-09-23 18:40:03.118025239 +0200 CEST m=+6.237504168 [debug] warning: Upgrade "test" failed: post-upgrade hooks failed: 1 error occurred:
        * job failurecauser failed: BackoffLimitExceeded


Error: UPGRADE FAILED: post-upgrade hooks failed: 1 error occurred:
        * job failurecauser failed: BackoffLimitExceeded


helm.go:86: 2024-09-23 18:40:03.192032186 +0200 CEST m=+6.311511122 [debug] post-upgrade hooks failed: 1 error occurred:
        * job failurecauser failed: BackoffLimitExceeded


UPGRADE FAILED
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:243
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:85
runtime.main
        runtime/proc.go:271
runtime.goexit
        runtime/asm_amd64.s:1695

NAME                             READY   STATUS    RESTARTS   AGE
leakyrollback-65b784fd7c-4jv2l   2/2     Running   0          13s
```

While the helm upgrade itself failed, we can see that both containers are present in the pod.

## helm upgrade to revert

```bash
helm upgrade -n leakyrollback --debug test .
kubectl -n leakyrollback get pod
```

Output:
```
upgrade.go:164: 2024-09-23 18:40:19.241595035 +0200 CEST m=+0.243035762 [debug] preparing upgrade for test
upgrade.go:172: 2024-09-23 18:40:19.935801768 +0200 CEST m=+0.937242508 [debug] performing update for test
upgrade.go:375: 2024-09-23 18:40:20.281323747 +0200 CEST m=+1.282764483 [debug] creating upgraded release for test
client.go:393: 2024-09-23 18:40:20.421229221 +0200 CEST m=+1.422669949 [debug] checking 1 resources for changes
client.go:693: 2024-09-23 18:40:20.549737101 +0200 CEST m=+1.551177813 [debug] Patch Deployment "leakyrollback" in namespace leakyrollback
upgrade.go:180: 2024-09-23 18:40:20.695406318 +0200 CEST m=+1.696847045 [debug] updating status for upgraded release for test
Release "test" has been upgraded. Happy Helming!
NAME: test
LAST DEPLOYED: Mon Sep 23 18:40:19 2024
NAMESPACE: leakyrollback
STATUS: deployed
REVISION: 3
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
{}

HOOKS:
MANIFEST:
---
# Source: leakyrollback/templates/Deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leakyrollback
spec:
  selector:
    matchLabels:
      app: leakyrollback

  replicas: 1
  template:
    metadata:
      labels:
        app: leakyrollback
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: main
          image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/busybox:latest
          args:
            - "/bin/sh"
            - "-c"
            - "date && sleep infinity"

NAME                             READY   STATUS    RESTARTS   AGE
leakyrollback-65b784fd7c-4jv2l   2/2     Running   0          30s
```
While the upgrade itself was successful, it did not remove the second container. Given that this is the primary difference between r1 and r2, this upgrade hasn't accomplished much, but unless we inspect the deployed objects, we'd have no way of noticing.

## Try again with helm rollback

```bash
helm rollback --debug -n leakyrollback test 1
kubectl -n leakyrollback get pod
```

Output:
```
rollback.go:65: 2024-09-23 18:40:40.660052874 +0200 CEST m=+0.230967088 [debug] preparing rollback of test
rollback.go:131: 2024-09-23 18:40:40.808039551 +0200 CEST m=+0.378953770 [debug] rolling back test (current: v3, target: v1)
rollback.go:72: 2024-09-23 18:40:40.871551892 +0200 CEST m=+0.442466105 [debug] creating rolled back release for test
rollback.go:78: 2024-09-23 18:40:41.026198976 +0200 CEST m=+0.597113191 [debug] performing rollback of test
client.go:393: 2024-09-23 18:40:41.452228464 +0200 CEST m=+1.023142654 [debug] checking 1 resources for changes
client.go:693: 2024-09-23 18:40:41.578535731 +0200 CEST m=+1.149449959 [debug] Patch Deployment "leakyrollback" in namespace leakyrollback
rollback.go:257: 2024-09-23 18:40:41.712636358 +0200 CEST m=+1.283550575 [debug] superseding previous deployment 3
rollback.go:84: 2024-09-23 18:40:41.784515114 +0200 CEST m=+1.355429326 [debug] updating status for rolled back release for test
Rollback was a success! Happy Helming!

NAME                             READY   STATUS    RESTARTS   AGE
leakyrollback-65b784fd7c-4jv2l   2/2     Running   0          48s
```

At this point, it appears that the previous upgrade has inherited the second container, but as it wasn't present in the rendered-form of the previous upgrade, it is considered external and so _still_ kept.
