### ISSUE TITLE
Could not delete default keys from subcharts if subchart is defined in dependencies

### ISSUE THREAD

**Issue by shcherbak** [helm/helm#13370]
Could not delete default keys from subcharts if subchart is defined in dependencies

Output of `3.16.1`:

Output of `1.30.4`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): all (local templating)

if subchart has for example
```
resources:
  limits:
    cpu: 4
    memory: 3Gi
  requests:
     cpu: 700m
     memory: 70Mi
```
it is unable to override with
```
resources:
  limits: null
  requests: null
```

the same as https://github.com/helm/helm/issues/9027
