### ISSUE TITLE
range and if logic is not working properly 

### ISSUE THREAD

**Issue by jaswanth2273** [helm/helm#13406]
deployment yaml file 

```
{{ range .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
{{ if .service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
  selector:
    app: {{ .name }}
{{ end }}
{{ end }}
```
values file
```
deployments:
  - name: dep1
    replicas: 2
    image: dep1-image:latest
    service:
      enabled: false
      type: ClusterIP
      port: 80

  - name: dep2
    replicas: 3
    image: dep2-image:latest
    service:
      enabled: true
      type: ClusterIP
      port: 80
```

as per values file it needs to create deployment with name dep1 and dep2 and a service for dep2 . but it is not working in this pattern.  can you please check this.

Output of `helm version`:
version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.17.13"}

Output of `kubectl version`:
v1.24.9

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  on premiss

**Comment by kolsware** [comment]
you probably want to paste the output. It works for me with `Version:"v3.13.3`

**Comment by jaswanth2273** [comment]
@kolsware 

as per deployment file and values given , i need two deployment and a service for second deployment . but  deployment dep2 is not created. below screenshot gives the complete details. 

<img width="687" alt="Screenshot 2024-10-25 at 12 04 46 AM" src="https://github.com/user-attachments/assets/fdcb8381-aa2f-4897-bd93-20556c6d246a">


but helm template gives the expected output. 
<img width="610" alt="Screenshot 2024-10-25 at 12 07 30 AM" src="https://github.com/user-attachments/assets/b14224a1-ff61-49a3-bc7c-4347c6f2475c">

**Comment by stamilarasan-wowcorp** [comment]
I am following this issue as I am also facing the same.

**Comment by stamilarasan-wowcorp** [comment]
Hi [jaswanth2273](https://github.com/jaswanth2273), I worked for me. Please add --- before your range end.

Example:

{{ range .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
---
{{ if .service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
  selector:
    app: {{ .name }}
---
{{ end }}
{{ end }}

**Comment by jaswanth2273** [comment]
@kolsware  could you please help here.

**Comment by yxxhero** [comment]
@jaswanth2273 the result is right. I saw the deploymet `dep2`.

**Comment by jaswanth2273** [comment]
@yxxhero  Did you use the deployment file and values file mentioned above? If not, could you please provide the file that you used? Also, will there be any dependencies related to the Kubernetes version or Helm version?

**Comment by yxxhero** [comment]
@jaswanth2273 what's your expected output? please show that.

**Comment by jaswanth2273** [comment]
Expected output:  it needs to create deployment with name dep1 and dep2 and a service with name dep2

**Comment by yxxhero** [comment]
@jaswanth2273 
```
{{ range .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
{{ if .service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
  selector:
    app: {{ .name }}
{{ end }}
{{ end }}
```
