### ISSUE TITLE
Using httpasswd user files in Helm

### ISSUE THREAD

**Issue by david-thrower** [helm/helm#13415]
Output of `helm version`:

version.BuildInfo{Version:"v3.16.2", GitCommit:"13654a52f7c70a143b1dd51416d633e1071faffb", GitTreeState:"clean", GoVersion:"go1.22.7"}

Output of `kubectl version`:

Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.30.5+k3s1

Cloud Provider/Platform  k3s

### I can deploy this outside of an automated pipeline like this: 

`htpasswd -cb users.txt user1 password1`
`htpasswd -b users.txt user2 password2`

Then

`kubectl create secret generic basic-auth --from-file=users.txt -n mynamespace`

Then:

myapp.yaml:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: my-basic-auth
  namespace: mynamespace
spec:
  basicAuth:
  secret: basic-auth 
---

# an ingress having the annotation: 

traefik.ingress.kubernetes.io/router.middlewares: my-basic-auth

```

Then

`kubectl apply -f myapp.yaml`

THIS **WILL** WORK, but it doesn't scale if you want to deploy this for several users. I want to be able to run a Helm chart that **parameterizes** this operation with regard to the users file.

I tried to add this to a HELM chart:

In a template:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: mynamespace
type: Opaque
stringData:
  users: |-
    {{ .Values.basicauth.userFile | b64enc | quote }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: my-basic-auth
  namespace: mynamespace
spec:
   basicAuth:
    secret: basic-auth
--- 
# The same ingress with the host also parameterized
```

In values.yaml:

```yaml
basicauth:
  userFile: [get your own user file]
...
```

Then I run:

```
# There is a variable USER_FILE containing the contents of the file
helm [install | upgrade] myapp --set basicauth.userFile="$USER_FILE"
```

This will create a secret that is defective, and the basic-auth resource will fail to create. I have tried numerous permutations of ways to parse the text content. I have tried using:

users: {{ .Files.Get "dxtx-app-users.txt" | b64enc }}

Why does it work when I use kubectl to create a secret but not when I try creating the same secret in Helm and what can I do to make this work?
