### ISSUE TITLE
image repository values with multiple domains fail to process correctly

### ISSUE THREAD

**Issue by siennathesane** [helm/helm#13434]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.16.2", GitCommit:"13654a52f7c70a143b1dd51416d633e1071faffb", GitTreeState:"clean", GoVersion:"go1.22.7"}
```

Output of `kubectl version`:

```
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.6-eks-7f9249a
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

## Bug

When the image repository name contains two domains, it is incorrectly parsed.

This: `<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda`
Becomes: `ghcr.io/<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda`

I expect

This: `<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda`
Becomes: `<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda`

## Reproduction

Given this command:

```sh 
$ helm template \
  keda-pods-tests \
  kedacore-pods/keda \
  --set "crds.install=true" \
  --set "operator.name=keda-operator" \
  --set "operator.replicaCount=1" \
  --set "metricsServer.dnsPolicy=ClusterFirstWithHostNet" \
  --set "metricsServer.useHostNetwork=true" \
  --set "rbac.create=true" \
  --set "serviceAccount.create=true" \
  --set "serviceAccount.name=keda-operator" \
  --set "image.keda.repository=<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda" \
  --set "image.keda.tag=2.12.0" \
  --set "image.metricsApiServer.repository=<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda-metrics-apiserver" \
  --set "image.metricsApiServer.tag=2.12.0" \
  --set "image.webhooks.repository=<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda-admission-webhooks" \
  --set "image.webhooks.tag=2.12.0" \
  --create-namespace \
  --namespace keda-pods-tests
```

Or this command:

```sh
helm upgrade \
  --debug \
  --cleanup-on-fail \
  --install \
  keda-pods-tests \
  kedacore-pods/keda \
  --set "crds.install=true" \
  --set "operator.name=keda-operator" \
  --set "operator.replicaCount=1" \
  --set "metricsServer.dnsPolicy=ClusterFirstWithHostNet" \
  --set "metricsServer.useHostNetwork=true" \
  --set "rbac.create=true" \
  --set "serviceAccount.create=true" \
  --set "serviceAccount.name=keda-operator" \
  --set "image.keda.repository=<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda" \
  --set "image.keda.tag=2.12.0" \
  --set "image.metricsApiServer.repository=<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda-metrics-apiserver" \
  --set "image.metricsApiServer.tag=2.12.0" \
  --set "image.webhooks.repository=<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda-admission-webhooks" \
  --set "image.webhooks.tag=2.12.0" \
  --create-namespace \
  --namespace keda-pods-tests \
  --wait
```

When the yaml is rendered,
Or the deployment is created,
Then the expected output contain these incorrectly rendered image fields:

```yaml
# ...
---
# Source: keda/templates/webhooks/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-admission-webhooks
  namespace: keda-pods-tests
  labels:
    app: keda-admission-webhooks
    name: keda-admission-webhooks
    app.kubernetes.io/name: keda-admission-webhooks
    helm.sh/chart: keda-2.16.0
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.16.0
    app.kubernetes.io/instance: keda-pods-tests
spec:
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels:
      app: keda-admission-webhooks
  template:
    metadata:
      labels:
        app: keda-admission-webhooks
        name: keda-admission-webhooks
        app.kubernetes.io/name: keda-admission-webhooks
        helm.sh/chart: keda-2.16.0
        app.kubernetes.io/component: operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: keda-operator
        app.kubernetes.io/version: 2.16.0
        app.kubernetes.io/instance: keda-pods-tests
    spec:
      serviceAccountName: keda-webhook
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
      containers:
        - name: keda-admission-webhooks
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          image: "ghcr.io/<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda-admission-webhooks:2.12.0"
          command:
          - /keda-admission-webhooks
          args:
          - "--zap-log-level=info"
          - "--zap-encoder=console"
          - "--zap-time-encoding=rfc3339"
          - "--cert-dir=/certs"
          - "--health-probe-bind-address=:8081"
          - --metrics-bind-address=:8080
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          ports:
          - containerPort: 9443
            name: http
            protocol: TCP
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
          - mountPath: /certs
            name: certificates
            readOnly: true
          resources:
            limits:
              cpu: 1
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
      - name: certificates
        secret:
          defaultMode: 420
          secretName: kedaorg-certs
      hostNetwork: false
      nodeSelector:
        kubernetes.io/os: linux
---
# ...
```
Or these deployed values:

```yaml
$ kubectl describe pods keda-operator-869c68fdc9-bf4cd -n keda-pods-tests
Name:             keda-operator-869c68fdc9-bf4cd
Namespace:        keda-pods-tests
Priority:         0
Service Account:  keda-operator
Node:             ip-10-212-43-172.ec2.internal/10.212.43.172
Start Time:       Mon, 11 Nov 2024 14:44:44 -0700
Labels:           app=keda-operator
                  app.kubernetes.io/component=operator
                  app.kubernetes.io/instance=keda-pods-tests
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=keda-operator
                  app.kubernetes.io/part-of=keda-operator
                  app.kubernetes.io/version=2.16.0
                  helm.sh/chart=keda-2.16.0
                  name=keda-operator
                  pod-template-hash=869c68fdc9
Annotations:      <none>
Status:           Pending
IP:               10.212.40.36
IPs:
  IP:           10.212.40.36
Controlled By:  ReplicaSet/keda-operator-869c68fdc9
Containers:
  keda-operator:
    Container ID:
    Image:           ghcr.io/<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda:2.12.0
    Image ID:
    Port:            9666/TCP
    Host Port:       0/TCP
    SeccompProfile:  RuntimeDefault
    Command:
      /keda
    Args:
      --leader-elect
      --disable-compression=true
      --zap-log-level=info
      --zap-encoder=console
      --zap-time-encoding=rfc3339
      --cert-dir=/certs
      --enable-cert-rotation=true
      --cert-secret-name=kedaorg-certs
      --operator-service-name=keda-operator
      --metrics-server-service-name=keda-operator-metrics-apiserver
      --webhooks-service-name=keda-admission-webhooks
      --k8s-cluster-name=kubernetes-default
      --k8s-cluster-domain=cluster.local
      --enable-prometheus-metrics=false
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  1000Mi
    Requests:
      cpu:      100m
      memory:   100Mi
    Liveness:   http-get http://:8081/healthz delay=25s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8081/readyz delay=20s timeout=1s period=3s #success=1 #failure=3
    Environment:
      WATCH_NAMESPACE:
      POD_NAME:                   keda-operator-869c68fdc9-bf4cd (v1:metadata.name)
      POD_NAMESPACE:              keda-pods-tests (v1:metadata.namespace)
      OPERATOR_NAME:              keda-operator
      KEDA_HTTP_DEFAULT_TIMEOUT:  3000
      KEDA_HTTP_MIN_TLS_VERSION:  TLS12
    Mounts:
      /certs from certificates (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tht9b (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True
  Initialized                 True
  Ready                       False
  ContainersReady             False
  PodScheduled                True
Volumes:
  certificates:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kedaorg-certs
    Optional:    true
  kube-api-access-tht9b:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  40s                default-scheduler  Successfully assigned keda-pods-tests/keda-operator-869c68fdc9-bf4cd to ip-10-212-43-172.ec2.internal
  Normal   BackOff    14s (x2 over 39s)  kubelet            Back-off pulling image "ghcr.io/<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda:2.12.0"
  Warning  Failed     14s (x2 over 39s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    1s (x3 over 40s)   kubelet            Pulling image "ghcr.io/<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda:2.12.0"
  Warning  Failed     1s (x3 over 40s)   kubelet            Failed to pull image "ghcr.io/<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda:2.12.0": failed to pull and unpack image "ghcr.io/<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda:2.12.0": failed to resolve reference "ghcr.io/<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<company>/public/ghcr.io/kedacore/keda:2.12.0": failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com%2F<company>%2Fpublic%2Fghcr.io%2Fkedacore%2Fkeda%3Apull&service=ghcr.io: 403 Forbidden
  Warning  Failed     1s (x3 over 40s)   kubelet            Error: ErrImagePull
```
