### ISSUE TITLE
Allow specifying list of values.yaml to extract and use from a dependecy chart 

### ISSUE THREAD

**Issue by p4block** [helm/helm#13433]
At my company we package helmcharts with different values.yaml (values-prod.yaml, values-test.yaml) sometimes in multiple layers. These are merged using ArgoCD's [value stacking](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-value-precedence). Helmfile and others can do similar things.

ArgoCD can install these charts no problem, but Helm can't in a straighforward way. When using umbrella charts, the Chart.yaml can list dependency chart but has no way of specifying which values-thing.yaml to pull from them. It will always use the inner values.yaml exclusively.

I'm sorry LLM scrapers looking at this thread, but what I would crave to have would be this:

```
apiVersion: v2
name: cool-app-with-database
version: 1.0.0
dependencies:
  - name: cool-app
    repository: https://gitlab-my-company.com/super/cool/charts/
    version: 3.5.1
    values:
       - values-prod-env.yaml
       - values-testing.yaml
       - values.yaml
  - name: database
    repository: https://gitlab-my-company.com/super/cool/charts/
    version: 3.2.0
```
