### ISSUE TITLE
Failure in pre-upgrade when a manifest is removed makes it impossible to roll back

### ISSUE THREAD

**Issue by matthiasvegh** [helm/helm#13437]
If a chart used to contain a manifest like a ConfigMap that is no longer present in the next version of the chart and the upgrade fails during pre-upgrade, `helm rollback` will fail spuriously.

A manifest may no longer be present in a new version of the chart for a number of reasons: Merging RoleBindings, combining two Deployments of one container per pod into one Deployment of two containers per pod, etc.

To reproduce create a chart which installs a ConfigMap upon installation, contains nothing during upgrade except a pre-upgrade hook that will fail like so:

```yaml
{{- if .Release.IsInstall -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg
data:
  foo: bar
{{ end -}}
{{- if .Release.IsUpgrade -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "failurecauser"
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: never
          image: "busybox:latest"
          args:
            - "/bin/sh"
            - "-c"
            - "false"
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0
{{ end -}}
```

Upon installation, the ConfigMap is created as expected. Upon upgrade, the ConfigMap would _eventually_ be removed, but as the pre-upgrade hook fails, Helm never gets a chance to remove the ConfigMap.

When it comes time to rollback (either via `helm rollback` or via `--atomic` used during the failing `helm upgrade`) Helm walks the list of manifests in the target (the initial deployment which contained only the ConfigMap), finds that it exists in the cluster *and then checks its state in the last deployed version* where it is absent and fails with:

```
rollback.go:65: 2024-11-12 10:01:59.033172463 +0100 CET m=+0.253517049 [debug] preparing rollback of test
rollback.go:131: 2024-11-12 10:01:59.180766777 +0100 CET m=+0.401111391 [debug] rolling back test (current: v2, target: v1)
rollback.go:72: 2024-11-12 10:01:59.244344963 +0100 CET m=+0.464689544 [debug] creating rolled back release for test
rollback.go:78: 2024-11-12 10:01:59.391610987 +0100 CET m=+0.611955586 [debug] performing rollback of test
client.go:393: 2024-11-12 10:01:59.538573362 +0100 CET m=+0.758917920 [debug] checking 1 resources for changes
rollback.go:195: 2024-11-12 10:01:59.60209464 +0100 CET m=+0.822439231 [debug] warning: Rollback "test" failed: no ConfigMap with the name "cfg" found
Error: no ConfigMap with the name "cfg" found
helm.go:86: 2024-11-12 10:01:59.753177208 +0100 CET m=+0.973521792 [debug] no ConfigMap with the name "cfg" found
```

The error message is somewhat misleading as it suggests that the ConfigMap is not found _on the cluster_, where it is clearly there. Where it is not found is the Secret that represents that last deployment where it really was absent (or would have been, had Helm ever made it that far). The log message is produced here: 

https://github.com/helm/helm/blob/5a5449dc42be07001fd5771d56429132984ab3ab/pkg/kube/client.go#L418-L422

Has the manifest been successfully removed in the preceding upgrade, this wouldn't fail due to 

https://github.com/helm/helm/blob/5a5449dc42be07001fd5771d56429132984ab3ab/pkg/kube/client.go#L399-L411

Line 401 shows care given to a Manifest being absent on the cluster, but no similar logic for a Manifest being absent from the release deemed to be the original. Of course, if `helm upgrade` is used instead of `helm rollback`, this specific problem doesn't occur, but only because the original release is determined to be the last _successful_ one instead of the live one. Had the failure occurred at post-upgrade instead and we were rolling back more than one revision, the same issue would present itself.

Just like how Helm does not fail on a Manifest having been deleted on the cluster and instead quickly recreates it, if a Manifest is not found in the original release but does find it on the cluster, I think Helm should handle that gracefully.

Otherwise, `--atomic` and `helm rollback` are broken in the presence of removed Manifests and potentially failing pre-upgrade hooks.

Possibly duplicates #12388, but I think this way to reproduce the issue is clearer.
