### ISSUE TITLE
Option to ignore missing files for helm fileParameters

### ISSUE THREAD

**Issue by morremeyer** [helm/helm#13442]
## Summary

This is a feature request to add a "ignore this configuration if the file is missing" option for helm `fileParameters` as it exists for values files with `ignoreMissingValueFiles` already.

## Detailed description

We use an ApplicationSet to deploy a specific helm chart to all clusters, using the `clusters` generator.

Example ApplicationSet:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: monitoring
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "monitoring-{{ metadata.labels.environment }}"
      namespace: monitoring
    spec:
      project: monitoring
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: k8s-monitoring
          targetRevision: 1.6.6
          helm:
            releaseName: monitoring
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/monitoring/values.yaml
              - $values/monitoring/values/{{ metadata.labels.environment }}.yaml
            fileParameters:
              - name: extraConfig
                path: $values/monitoring/values/extraConfig/{{ metadata.labels.environment }}.alloy
        - repoURL: REDACTED
          targetRevision: main
          ref: values                
      destination:
        namespace: monitoring
        name: "{{ name }}"
```

For the `extraConfig` value, we use `fileParameters`.

However, we do not need to set `extraConfig` for all clusters, therefore we would like to only create the  `$values/monitoring/values/extraConfig/{{ metadata.labels.environment }}.alloy` file if there is actual config to set.

Currently, this is not possible and if the file does not exist, the Application state turns Unknown with a `no such file or directory` error.
