### ISSUE TITLE
Rollback failed with error "no xxx with the name "xxx" found"

### ISSUE THREAD

**Issue by dayeguilaiye** [helm/helm#13462]
If the resource with `helm.sh/resource-policy: keep` got removed when upgrade, then rollback will fail with error `no xxx with the name "xxx" found`.

# Reproduce:
## step 1
chart v1 with two resources:
aaa.yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aaa
```

bbb.yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bbb
  annotations:
    helm.sh/resource-policy: keep
```
## step 2
`helm install test-release /path/to/this/chart`

## step 3
remove the bbb.yaml in the chart

## step 4
`helm upgrade test-release /path/to/this/chart`
This step will success with keeping the configmap bbb.

## step 5
`helm rollback test-release`

## got error
```shell
Error: no ConfigMap with the name "bbb" found
```

# Problem
I think there might be two problem:
1. Should it fail in this case?
2. Even if the situation was intended to fail, the error message is too confusing.

Output of `helm version`:
3.6.0
Output of `kubectl version`:
1.22.3
