### ISSUE TITLE
`int` conversion doesn't work if value comes from function using `quote`

### ISSUE THREAD

**Issue by davinkevin** [helm/helm#13463]
Hello, 

I would like to report a behavior I've identified as a bug when the `int` conversion function is used. In some specific cases, this function returns `0` instead of the converted value. 

For example, with the following template: 

```
standard:
  one: {{ 1 }}
  one-from-string: {{ "1" | int }}
with-function:
  {{- define "returns_one" }}
    {{- 1 }}
  {{- end }}
  one-from-function: {{ include "returns_one" . }}
  one-from-function-as-int: {{ (include "returns_one" .) | int }}
with-quote-function:
  {{- define "returns_one_with_quote" }}
    {{- 1 | quote }}
  {{- end }}
  one-from-function: {{ include "returns_one_with_quote" . }}
  one-from-function-as-int: {{ (include "returns_one_with_quote" .) | int }}
```

The generation using `helm template` gives me the following result: 

```yaml
---
# Source: foo/templates/example.yaml
standard:
  one: 1
  one-from-string: 1
with-function:
  one-from-function: 1
  one-from-function-as-int: 1
with-quote-function:
  one-from-function: "1"
  one-from-function-as-int: 0
```

You can see the value `with-quote-function.one-from-function-as-int` returns `0` where every other cases return 1 as an `int` or `string`. 

I wasn't able to understand what's causing this issue and I consider it as a bug.

All files to reproduce the case are available [in this GitLab repository](https://gitlab.com/davinkevin.fr/issues/helm/-/blob/issue-with-string-conversion-to-int/foo/templates/example.yaml?ref_type=heads)

Output of `helm version`: v3.16.3

Output of `kubectl version`: N/A, just the templating part is concerned

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A, just the templating part is concerned
