### ISSUE TITLE
Error: invalid_reference: invalid tag when chart exposed as OCI url in index.yaml

### ISSUE THREAD

**Issue by michelesr** [helm/helm#13466]
Running an helm command with `--repo` fails with `invalid tag` error when the selected chart is exposed as OCI url in the repository index.yaml .

```
$ helm template --repo https://charts.bitnami.com/bitnami external-dns --version 8.5.1 | head
---
# Source: external-dns/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: release-name-external-dns
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm

$ helm template --repo https://charts.bitnami.com/bitnami external-dns --version 8.6.0
Error: invalid_reference: invalid tag
```

These are the relevant [index.yaml](https://charts.bitnami.com/bitnami/index.yaml) bits:

8.6.0

```yaml
  external-dns:
  - name: external-dns
    urls:
    - oci://registry-1.docker.io/bitnamicharts/external-dns:8.6.0
    version: 8.6.0
    ...
```

8.5.1

```yaml
  - name: external-dns
    urls:
    - https://charts.bitnami.com/bitnami/external-dns-8.5.1.tgz
    version: 8.5.1
    ...
```

Output of `helm version`:

```
version.BuildInfo{Version:"v3.16.3", GitCommit:"cfd07493f46efc9debd9cc1b02a0961186df7fdf", GitTreeState:"dirty", GoVersion:"go1.23.3"}
```
