### ISSUE TITLE
Verbose pod labels

### ISSUE THREAD

**Issue by stevehipwell** [helm/helm#13515]
Since #11649 the new Helm chart template has switched to use common labels instead of selector labels for the pod labels which means that Helm specific labels are now added directly to the pod. Given the comments on the PR (that seemed to be against the change) and a lack of supporting issue this change doesn't seem right. Could the maintainers please provide some supporting justification for why this change was made as if there are specific reasons they should be documented both to understand the change and to support existing charts adopt best practices.

**Comment by banjoh** [comment]
Adding helm specific labels does seem a bit unnecessary given that the pod resource is not directly managed by Helm.

```yaml
kind: Deployment
metadata:
  name: release-name-foo
  labels:
    helm.sh/chart: foo-0.1.0
    app.kubernetes.io/name: foo
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: foo
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: foo-0.1.0
        app.kubernetes.io/name: foo
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
```

 I'm not sure there is documentation about the reasons around it. Given that https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels are the needed labels, perhaps not adding Helm specific labels to pods would be better. I'll leave that to @helm/helm-core-maintainers to comment on.
