### ISSUE TITLE
implement post-renderer for dependencies

### ISSUE THREAD

**Issue by rotty3000** [helm/helm#13536]
### Feature Proposal (with implementation)

Add support for a post-renderer operation on dependency such that the operation can be "packaged" with the root chart avoiding the need for the dependency to be forked.

e.g. _(YTT just used as an example.)_
```
dependencies:
- name: nginx
  version: "1.2.3"
  repository: "https://example.com/charts"
  postRenderer:
    command: ytt
    args:
    - "--file"
    - "overlays/nginx/overlay.yaml"
    - "--file"
    - "-"
```

### The Appeal

First. Today, Helm's dependency management is handcuffed by the fact that it does not have the ability to mutate the dependency's manifests as part of the deliverables of the root chart. This often leads to the need to fork the dependency.

This means that I, as a chart creator, cannot depend on a third party chart using `dependencies` if said chart overlooks even a single concern that is important to me. This belies composition of charts.

Second. Kubernetes is an evolving landscape. Helm's current design does not allow me as chart developer to adopt new transversal features until all the dependencies of my chart have adopted said features, leading again to the need for forking.

As an example, suppose I want to add [Pod Scheduling Readiness](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/) to all the pods in my chart and it's dependencies. Again, I would be forced to fork every chart until such a time as they adopt this feature.

### The Upside

Helm already has a internal mechanism that could be leveraged to address this use case with very little change. Please find a PR (incoming) for review that demonstrates a working implementation of this.
