### ISSUE TITLE
Configure helm to use a oci registry mirror/proxy without setting HTTP(S)_PROXY

### ISSUE THREAD

**Issue by deniswassmann-alephalpha** [helm/helm#13615]
I operate a CI environment that runs many different kinds of jobs, some of which run helm and fetch OCI charts from dockerhub, which eats into the rate limit of dockerhub. For docker/podman I can set a mirror in the configuration files that I am certain the CI jobs don't touch. For helm there doesn't seem to be such an option.

- pushing the burden of specifying a proxy/mirror onto the CI users is the best option that I can think of, but there will always be some jobs that don't use it and coordinating this with the users is not always easy
- setting `HTTP_PROXY` or the other variants would affect all programs in the ci jobs, which is not ideal either
- i tried using [a registry configuration file](https://github.com/helm/helm/issues/11714) with the contents [`{"proxies":{"default":{"httpsProxy":"https://localhost:12345"}}}`](https://docs.docker.com/engine/cli/proxy/), but helm seemed to ignore it when running `helm --debug pull oci://registry-1.docker.io/bitnamicharts/mysql --version 12.2.1`

Is there a way to configure helm to connect to a http server of my choice instead of connecting to dockerhub, aside from the options mentioned above?

**Comment by gjenkins8** [comment]
We have had an outstanding HIP to support registry aliases for a long time. Lack of maintainer time has meant this has languished.

But I do think supporting an existing standard would be good, like e.g. 
https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md#remapping-and-mirroring-registries

**Comment by felipecrs** [comment]
Actually, my solution was to change from:

```yaml
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ^16.4.6
```

To:

```yaml
dependencies:
  - name: postgresql
    repository: oci://myinternalregistry.com/bitnamicharts
    version: ^16.4.6
```
