### ISSUE TITLE
"helm.sh/hook-delete-policy" supports executing the component creation only once.

### ISSUE THREAD

**Issue by ace0527** [helm/helm#13616]
I have a scenario where I have an umbrella chart project with the following structure:

project
---app-core
---umbrella

In this project, besides app-core, there may be multiple apps such as app1, app2, etc.
I need to create a namespace for each app, with the namespace name following this rule: {appName}
(Additionally, since I am new to k8s, I am not sure if setting a namespace for each app is an anti-pattern. If it is, should each app be in the same namespace?)
Since there may be multiple apps, I don't want to manually create namespaces using `kubectl create namespace`.
Currently, I am doing it this way, creating a Namespace component in the template folder of each app, as follows:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "app-core.namespace" . }}
  labels:
    {{- include "app-core.labels" . | nindent 4 }}
```
However, because this app depends on ingress-nginx and overrides its `namespaceOverride`:
```yaml
app-core:
  ingress-nginx:
    namespaceOverride: "app-core"
```
The components in ingress-nginx will use the app-core namespace, but an error occurs during installation:
```
Error: failed pre-install: warning: Hook pre-install project/charts/app-core/charts/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml failed: 1 error occurred:
	* namespaces "app-core" not found
```
So I modified the namespace component to create the namespace before installation:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "app-test.namespace" . }}
  labels:
    {{- include "app-test.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-failed
    "helm.sh/resource-policy": keep
```
However, this brings the following issues:
1. If `helm.sh/hook-delete-policy` is set to `before-hook-creation`, the namespace will be deleted and recreated, and all components under the namespace will also be deleted and recreated, which is obviously not acceptable.
2. If `helm.sh/hook-delete-policy` is set to `hook-succeeded`, the namespace obviously needs to remain in k8s, so this cannot be set.
3. If `helm.sh/hook-delete-policy` is set to `hook-failed`, when the hook is executed again, it will find that the namespace already exists and report an error:
```
Error: UPGRADE FAILED: pre-upgrade hooks failed: warning: Hook pre-upgrade project/charts/app-core/templates/namespaces/namespace-override.yaml failed: 1 error occurred:
	* namespaces "prod-app-core" already exists
```
So I am wondering if there is a way to make the hook not execute if the component already exists during installation? For example, setting `helm.sh/hook-delete-policy: hook-keep`
