### ISSUE TITLE
Weird extra whitespace when using defined templates

### ISSUE THREAD

**Issue by lbogdan-together** [helm/helm#13618]
Output of `helm version`: `version.BuildInfo{Version:"v3.16.4", GitCommit:"7877b45b63f95635153b29a42c0c2f4273ec45ca", GitTreeState:"dirty", GoVersion:"go1.23.4"}` (installed with `brew` on macOS)

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

A simple chart reproducing the issue:

`templates/_helpers.tpl`:

```helm
{{- define "test.getSecretData" }}
{{- range $key, $value := . }}
{{ $key }}: {{ $value }}
{{- end }}
{{- end }}
```

`templates/secret.yaml`:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test1
stringData: 
  {{- include "test.getSecretData" .Values.secrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: test2
stringData: 
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}
```

`values.yaml`:

```yaml
secrets:
  foo: bar
  bar: baz
```

When rendering this with `helm template`, the result is: (screenshot, so that trailing spaces are visible):

<img width="328" alt="image" src="https://github.com/user-attachments/assets/f441ca09-de09-4c83-aaea-47f6ac885b55" />

Notice the 2 trailing spaces after `stringData:` in the first secret.

Am I doing something wrong, or is this behaviour expected?
