### ISSUE TITLE
Helm plugin new platformCommand structure not functioning

### ISSUE THREAD

**Issue by tibeer** [helm/helm#13640]
Hi everyone, 

I was reading and following the documentation from here: https://helm.sh/docs/topics/plugins/#building-a-plugin
and copied the exact same yaml file to a folder called "last" (the file itself was called "plugin.yaml").

```yaml
name: last
version: 0.1.0
usage: get the last release name
description: get the last release name
ignoreFlags: false
platformCommand:
  - command: ${HELM_BIN}
    args:
      - list
      - --short
      - --max=1
      - --date
      - -r
```

After that I ran `helm plugin install ./last` which resulted in:

```sh
tibeer@tibeer tmp % helm plugin install ./last
Error: plugin is installed but unusable: failed to load plugin at "/Users/tibeer/Library/helm/plugins/last/plugin.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "args"
```

Out of curiosity I removed the args part and the installation worked, but the command did not:

```sh
tibeer@tibeer tmp % helm last --help
no plugin command is applicableError: plugin "last" exited with error
```

I then tried the old plugin.yaml structure wich looks like this:

```yaml
name: last
version: 0.1.0
usage: get the last release name
description: get the last release name
ignoreFlags: false
command: date
```

Which worked right away:

```sh
tibeer@tibeer tmp % helm last
Mi 15 Jan 2025 15:45:23 CET
```

I am running on MacOS with helm version:

```sh
tibeer@tibeer tmp % helm version
version.BuildInfo{Version:"v3.16.4", GitCommit:"7877b45b63f95635153b29a42c0c2f4273ec45ca", GitTreeState:"dirty", GoVersion:"go1.23.4"}
```

I guess I am doing something wrong? Maybe someone has an idea what is going on :)
