### ISSUE TITLE
How can I configure different hook-weights for post-install and pre-delete in the same YAML file?

### ISSUE THREAD

**Issue by pilotshuk** [helm/helm#13641]
There are  two different deployment YAML files, A and B. I want Deployment A to be installed before Deployment B when using Helm, and Deployment B to be uninstalled before Deployment A during uninstallation.

Can I configure the hook annotations this way to ensure the YAML installs first and deletes later? 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: eventsource-test
  namespace: test
  annotations:
    "helm.sh/hook": post-install,pre-delete
    "helm.sh/hook-weight": "-2,-1"
```

Or  is there another available method?
