### ISSUE TITLE
Helm upgrade convert string value to number for ConfigMap

### ISSUE THREAD

**Issue by exilehanharr** [helm/helm#13652]
Hello!

I have following `values.yaml` file:

```yaml
image:
  image: "myApp"
  tag: ""

envs:
  ...
  IMAGE_TAG: "{{ .Values.image.tag }}"
  ...
```

My configmap template:

```yaml
{{- if .Values.envs -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
  labels:
    ...
data:
  {{- range $key, $value := .Values.envs }}
  {{-   $key | nindent 2 }}: {{ tpl $value $ | quote }}
  {{- end }}
{{- end -}}

```

If my image tag have value like `07082526` my upgrade will fail with following error message:

```log
json: cannot unmarshal number into Go struct field ConfigMap.data of type string
```

`helm template` doesn't contain errors and my `IMAGE_TAG` value have qoutes. But for `upgrade` it doesn't work. How I can fix it?
