### ISSUE TITLE
`release: not found` when I do `helm install` on a chart with some weird properties

### ISSUE THREAD

**Issue by iameli** [helm/helm#1996]
Came across this while doing some mad science on directories that are both Helm charts and Javascript modules. [Minimal repro case is here](https://github.com/streamplace/weird-chart-bug). The end result is that Helm successfully deploys a chart and immediately forgets that it did, like so:

```
> helm install --name test .
NAME:   test
Error: getting deployed release "test": release: not found
```

It does actually create the relevant Deployment object, but it doesn't know anything about the `test` release. I have to manually go in and delete the Deployment with `kubectl`.

I'm sure the problem is related to the `node_modules` directory -- it contains a zillion files and directories for all of my Javascript dependencies. Potentially I'm exceeding some hidden limit for files allowed within a Helm chart? Obviously I should be putting `node_modules` in `.helmignore`, but presumably Helm should also be doing something more coherent upon this failure case.

**Comment by technosophos** [comment]
Can you get the output of Tiller's logs using `kubectl`? Also, if you do `kubectl get configmap --namespace kube-system`, do you see a config map with that release name (e.g. `test`)? THat's where it stores its deployment record.

**Comment by iameli** [comment]
Ah, looks like you got it, Tiller complains that it can't create the ConfigMap:

```
2017/02/22 01:58:57 storage.go:133: Getting release history for 'test'
2017/02/22 01:58:57 release_server.go:913: Executing pre-install hooks for test
2017/02/22 01:58:57 release_server.go:940: Hooks complete for pre-install test
2017/02/22 01:58:57 storage.go:133: Getting release history for 'test'
2017/02/22 01:58:57 release_server.go:913: Executing post-install hooks for test
2017/02/22 01:58:57 release_server.go:940: Hooks complete for post-install test
2017/02/22 01:58:57 storage.go:45: Create release "test" (v1) in storage
2017/02/22 01:58:57 cfgmaps.go:316: configmaps: create: failed to create: ConfigMap "test.v1" is invalid: data: Too long: must have at most 1048576 characters
2017/02/22 01:58:57 release_server.go:817: warning: Failed to record release "test": ConfigMap "test.v1" is invalid: data: Too long: must have at most 1048576 characters
2017/02/22 01:58:59 storage.go:133: Getting release history for 'test'
```

**Comment by technosophos** [comment]
Ah! So the chart is too large to get stored. IIRC, there's a limit in Kubernetes 1.5 that no resource can be larger than (approximately) 1M. We do gzip the chart, but it probably still pushed beyond that limit.

**Comment by Mario54** [comment]
Would it be possible to have a better error message for this? I had the same error `release: not found`, and it took me a while to figure out that the problem was that there was too much data to fit in a `ConfigMap`.

I'm not familiar with the design of Helm and Tiller, but maybe there's an easy way for Tiller to return this as a clear error message which Helm would show to the user?

**Comment by erikbgithub** [comment]
I'd like to +1 the error message part. Ran into the same problem and had to figure out that the issue is a configmap (in my case one that didn't get delete with `--purge` for whatever reason).

**Comment by sstarcher** [comment]
This should be updated to be a bug.  When this issue happens the user gets a bad error message and the chart installs get orphaned.  If possible it would also be great to catch this prior to any kubernetes objects being installed or even by helm lint.

```
helm install .
NAME:   ugly-newt
Error: getting deployed release "ugly-newt": release: "ugly-newt" not found


helm delete --purge ugly-newt
Error: Unable to lock release "ugly-newt": release not found


kubectl get pods | grep ugly
ugly-newt-prometheus-alertmanager-2167339090-2tf56          2/2       Running            0          1m
ugly-newt-prometheus-kube-state-metrics-2256588538-w98gm    1/1       Running            0          1m
ugly-newt-prometheus-server-3612114810-flv8f                2/2       Running            0          1m
```

**Comment by kwilliams057** [comment]
+1 for updating this to a bug.
I ran into the same problem. The charts were orphaned and i had to manually delete all the resources helm created and couldnt do a helm delete --purge

```bash
[storage/driver] 2017/10/02 15:25:43 create: failed to create: ConfigMap "mangy-hog.v1" is invalid: data: Too long: must have at most 1048576 characters
[tiller] 2017/10/02 15:25:43 warning: Failed to record release mangy-hog: ConfigMap "mangy-hog.v1" is invalid: data: Too long: must have at most 1048576 characters

-> % kubectl get statefulset
NAME                                    DESIRED   CURRENT   AGE
hardy-camel-mongodb-replicaset          3         1         16m
innocent-pronghorn-mongodb-replicaset   3         1         21m
loping-boxer-mongodb-replicaset         3         1         19m
mangy-hog-mongodb-replicaset            3         1         9m
mongo-log-rec-mongodb-replicaset        3         1         23m
veering-whippet-mongodb-replicaset      3         1         10m
volted-dragonfly-mongodb-replicaset     3         1         15m
```

**Comment by thoyt** [comment]
I ran into this as well and it took quite a while to realize it's because I had a scratch file in the chart directory. A better error message would be greatly appreciated.

**Comment by hobti01** [comment]
This looks like more than just bug relating to the error message.  We have ConfigMaps that are nearly 1MB on their own and already contain compressed data.  Kubernetes handles these without issue, but when helm combines them into a single ConfigMap it hits the Kubernetes limit.

The issue is magnified with sub-charts.

**Comment by dtirer** [comment]
i'm having an issue with this at well, though i don't understand whats contributing to such a large ConfigMap

**Comment by bacongobbler** [comment]
@dtirer try running `helm template`; that might give you more information on what's being written to the release configmap. :)

**Comment by dtirer** [comment]
this was the result.  Nothing appear to be problematic to my eye...

```
---
# Source: jenkins/templates/jenkins-volume.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2 # must match your storageclass from above
  resources:
    requests:
      storage: 50Gi
---
# Source: jenkins/templates/jenkins-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: "LoadBalancer"
  selector:
    app: jenkins
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
# Source: jenkins/templates/jenkins-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: jenkins
        image: 1234567.dkr.ecr.us-east-1.amazonaws.com/company/jenkins:127
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-data
```
