### ISSUE TITLE
Add "from" field to the Charts.yaml

### ISSUE THREAD

**Issue by technosophos** [helm/helm#209]
I am thinking that it might be a good idea to add this to the `helm fetch` workflow:

When a chart is fetched, the `from:` field in the `Chart.yaml` is added, and its value is set to the name and version of the original chart. The `name:` field is then changed to the name the user supplied in the `helm fetch` command.

For example, say we begin with this chart:

```yaml
name: alpine
home: http://github.com/deis/helm
version: 0.0.1
description: Simple pod running Alpine Linux.
maintainers:
  - Matt Butcher <mbutcher@deis.com>
details:
  This package provides a basic Alpine Linux image that can be used for basic
  debugging and troubleshooting. By default, it starts up, sleeps for a long
  time, and then eventually stops.
```

Now the user runs `helm fetch alpine myalpine`

The newly copied chart now looks like this:

```yaml
name: myalpine
from:
  name: alpine
  version: 0.0.1
home: http://github.com/deis/helm
version: 0.0.1
description: Simple pod running Alpine Linux.
maintainers:
  - Matt Butcher <mbutcher@deis.com>
details:
  This package provides a basic Alpine Linux image that can be used for basic
  debugging and troubleshooting. By default, it starts up, sleeps for a long
  time, and then eventually stops.
```

This gives the new chart its own identity, but also gives us a base to provide features like diffs against upstream.
