### ISSUE TITLE
Secret Management in Helm

### ISSUE THREAD

**Issue by johnw188** [helm/helm#2196]
Consider configuration of a Jenkins instance. In our `values.yaml` we might encounter

```yaml
Master:
  AdminUsername: admin
  AdminPassword: passw0rd!
```

with a secret being defined as

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.Master.AdminPassword }}
  jenkins-admin-password:  {{ .Values.Master.AdminPassword | b64enc | quote }}
  {{ else }}
  jenkins-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  jenkins-admin-user: {{ .Values.Master.AdminUsername | b64enc | quote }}
{{- end }}
```

The problem is that anyone with access to tiller can run a `helm get values` command and be sent back the password in plain text.

# Requirements

- Chart authors should be able to provide, through `helm inspect`, a listing of secrets that can be set for the chart
- Chart consumers should be able to edit values for these secrets through a `--set` directive or by passing a yaml file, as they do with `values.yaml` currently.
  - It should be obvious that secrets are being treated differently by Helm
- Consumers should be able to update secret values through a `helm upgrade` command
- Secrets will be available to chart templates in the same fashion as non secret values
- Once tiller executes it's commands against the kubernetes API server, the secret should not be accessible
- No assumptions are made about how chart authors utilize secret values. While the standard use case will be to create kubernetes secrets, this will be entirely handled through the existing template system.
- No additional effort will be made to improve upon the existing kubernetes secrets support from kubernetes core. That work should be undertaken at the core kubernetes level and then utilized by helm once it makes a release.

# Proposed implementation

1. Allow users to specify secrets. There are two possible solutions here that I can see.
- Add a special, root key to `values.yaml` of `Secrets` (`helm:Secrets`?). This would inform Tiller that the values under that key are to be treated as secret values. The downside to this approach is it feels a bit magick-y.
- Split the existing `values.yaml` approach into `values.yaml` and `secrets.yaml`. This approach is more clear, but the existing workflow of `helm inspect stable/jenkins > myvalues.yaml` -> `helm install -f myvalues.yaml stable/jenkins` is quite elegant and I can't see a good way to maintain that simplicity with two separate config files.
2. Allow chart authors to reference secrets in their templates. This implementation is straightforward, I would change `{{ if .Values.Master.AdminPassword }}` to `{{ if .Secrets.Master.AdminPassword }}`
3. Ensure tiller is configured to receive and handle the new secret values.
4. Tiller should substitute secret values with a one way hash of the secret value before writing to its storage backend. This allows tiller to compare a provided secret with the previous value of that secret without needing to store the secret in plaintext.
5. Add a `--set-secret` command to helm to allow for command line setting/upgrading of secrets
