### ISSUE TITLE
PROPOSAL: Add `source:` field to Chart.yaml

### ISSUE THREAD

**Issue by technosophos** [helm/helm#221]
Existing charts have been using the `home:` field ambiguously. Some people have pointed it to a project's home page, while others are pointing to the home source of the Docker container image.

Example: Should the Alpine chart point to the Alpine Linux home page or the DockerHub source of the image?

The original intent of the `home:` field was to point to the source of the image (ideally so that people who wanted to build their own versions of an image would be able to). But I am seeing that there is definitely value to pointing to the origin project.

So I'd like to propose adding a `source:` field with the stated aim of pointing it to the source for the docker image (e.g. somewhere where the Dockerfile and source code can be located).

```yaml
name: alpine
home: http://www.alpinelinux.org/
source: https://hub.docker.com/_/alpine/
```
