### ISSUE TITLE
Feature request: Allow overriding untemplated values in templates

### ISSUE THREAD

**Issue by omkensey** [helm/helm#2399]
It would be nice if I could override values in templates even if they're not properly templated, e.g. given this:

templates/myservice.yaml:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
    component: frontend
  name: myapp-frontend-svc
spec:
  ports:
    - name: myapp-frontend
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: myapp
    component: frontend
```

I could do something like this:

`$ helm install stable/myapp --dynamic-value Values.Local.servicePort=myservice.yaml:spec.ports.myapp-frontend.port --set Values.Local.servicePort=81`

(N.B. Kubernetes doesn't require names if a service only has one port, in which case :spec.ports.port could be valid.)

An alternate method could be to simply assign values to the parse tree endpoint directly, e.g. `--set-dynamic myservice.yaml:spec.ports.myapp-frontend.port=81`

This would probably require annotating the deployed object in some way so that future helm sessions can deal intelligently with dynamically-set values that don't correspond to any known version of a chart.
