### ISSUE TITLE
requirements conditions ignore existing values during `helm upgrade`

### ISSUE THREAD

**Issue by kujenga** [helm/helm#2444]
I'm working on a chart where I would like to allow users to select between multiple options for a storage backend. These multiple options take the form of multiple subcharts, which the user of the chart can switch between using values that affect the requirements.yaml `condition` fields. This approach works well on installation, but I'm running into some odd behavior with upgrades.

I've isolated an example of the issue in an example repo: https://github.com/kujenga/chart-requirements-bug. Given the following `requirements.yaml` file and a [`values.yaml`](https://github.com/kujenga/chart-requirements-bug/blob/master/charts/test/values.yaml) file that enables redis by default, I experience the behavior outlined in the script block below.

```yaml
dependencies:
  - name: memcached
    version: 0.4.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: memcached.enabled
  - name: redis
    version: 0.5.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
```

the [`memcached-values.yaml`](https://github.com/kujenga/chart-requirements-bug/blob/master/memcached-values.yaml) file enables memcached and turns off redis.

```sh
helm install --name=example charts/test -f memcached-values.yaml
# the memcached deployment is available
helm get values example
# the values are set to the contents of memcached-values.yaml
helm upgrade example charts/test
# the redis deployment is now active
helm get values example
# the values are still set to the contents of memcached-values.yaml
helm upgrade example charts/test -f memcached-values.yaml
# the memcached chart is restored
```

It appears that the requirements conditional logic is not using the proper version of the values to determine what to install.

**Comment by technosophos** [comment]
Have you looked at the `--reuse-values` flag to `helm upgrade`?

/cc @jascott1

**Comment by kujenga** [comment]
@technosophos Yes, I tried that as well it did not seem to have an effect on the end result. If I understand correctly, the flag should be a no-op when there are no specific new values being set, is that correct?

**Comment by jascott1** [comment]
After running with the --reuse-values flag like so

```
helm install --name=example charts/test -f memcached-values.yaml
helm upgrade example charts/test --reuse-values
helm get values example 
```
I get an en empty result for the `helm get values example`. I will keep looking to see if an error is getting eaten somewhere or other silliness.

**Comment by jascott1** [comment]
@technosophos Im not experienced with `--reuse-values` but I got desired behavior by doing the following:

```
helm install --name=example charts/test -f memcached-values.yaml
helm get values example
```
The response is
```
memcached:
  enabled: true
redis:
  enabled: false
```
Then upgrading and explicitly using charts/test/values:
```
helm upgrade example charts/test -f charts/test/values.yaml
helm get values example
```
Gives correct response:
```
memcached:
  enabled: false
redis:
  enabled: true
```

It seems the release is being changed properly on upgrade using the above commands. Is that a bug in `--reuse-values`?
