### ISSUE TITLE
No support for kind DaemonSet

### ISSUE THREAD

**Issue by rimusz** [helm/helm#253]
````
[WARN] No support for kind DaemonSet. Ignoring.
---> Running `kubectl create -f` ...
---> Done
````

**Comment by arschles** [comment]
@rimusz can you post the command that you ran and the version you're running?

**Comment by jchauncey** [comment]
you need kubectl 1.1.1 and a 1.1.1 k8s cluster. 

Here is a manifest you can use.

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  labels:
    heritage: helm
    k8s-app: fluentd-elasticsearch
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      name: fluentd-elasticsearch
      labels:
        heritage: helm
        k8s-app: fluentd-elasticsearch
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluentd-elasticsearch
        image: fabric8/fluentd-kubernetes:1.3
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        env:
        - name: "ES_HOST"
          value: "elasticsearch-logging"
        - name: "ES_PORT"
          value: "9200"
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
```

make sure you start k8s api server with this - `--runtime-config=extensions/v1beta1=true,extensions/v1beta1/daemonsets=true`

verify that daemonsets is enabled by doing this - `curl -s http://<apihost>:8080/apis/extensions/v1beta1`
