### ISSUE TITLE
Getting the NOTES.txt data from a subchart

### ISSUE THREAD

**Issue by dfee** [helm/helm#2751]
Let's say I've got a dependency on `postgresql`:
```
dependencies:
  - name: postgresql
    version: 0.7.1
    repository: https://kubernetes-charts.storage.googleapis.com
```

If I install my chart (`helm install .`), it doesn't seem possible to get the (rather helpful) notes from the postgresql subchart. I.e. `helm status my-chart` does not list the notes for `postgresql`, only what's listed in `templates/NOTES.txt`.

Is there a workaround?
