### ISSUE TITLE
Feature: Better Dependency Management Specification

### ISSUE THREAD

**Issue by apeschel** [helm/helm#2759]
The dependency management in helm at the moment is extremely rudimentary. There is no protection against duplicated charts dependencies in `requirements.yaml`.

For example, the following `requirements.yaml`

```
dependencies:
- name: postgresql
  version: 0.6.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: postgresql
  version: 0.6.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: postgresql
  version: 0.5.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: postgresql
  version: 0.5.0
  repository: https://example.com
```

Results in the following:

```
$helm dependency list .
NAME            VERSION REPOSITORY                                              STATUS
postgresql      0.6.0   https://kubernetes-charts.storage.googleapis.com/       too many matches
postgresql      0.6.0   https://kubernetes-charts.storage.googleapis.com/       too many matches
postgresql      0.5.0   https://kubernetes-charts.storage.googleapis.com/       too many matches
postgresql      0.5.0   https://example.com
```

Attempting to use this will result in a large amount of chaos.

Putting conflicting charts into `requirements.yaml` is not something that happens in a normal workflow at the moment, but this is something that will quickly arise with recursive dependency management.

Some thoughts:

There are plenty of examples of dependency managers to use as a reference: npm, pip, ruby gems, etc. It may even make sense to just reuse the dependency manager library from another project.

The spec should probably look something like this:

- Return an error if a single chart lists the same dependency more than once.
- Return an error if two or more charts have different repositories for the same dependency
- Allow version range semantics (eg `>=1.2.7 <1.3.0`) for dependencies
- Return an error if dependency range requirements cannot be met for all subcharts.

What is the right behavior if two subscharts have different dependency versions? EG:

```
topchart
├── subchart1
│   ├── postgresql-0.5.0
│   └── redis-0.3.6
└── subchart2
    ├── postgresql-0.6.0
    └── redis-0.4.6
```
