### ISSUE TITLE
helm edit is not saving

### ISSUE THREAD

**Issue by technosophos** [helm/helm#286]
I tried the following against HEAD:

```
⇒  export EDITOR=mvim                                                                                                                                                                                   
☃ @ENG001590.local ~/Code/Go/src/github.com/helm/helm «/Users/mattbutcher/Code» ‹feat/objects-1.1*›
⇒  helm edit openldap
```

Inside of the editor, I modified the Chart.yaml to have lots of details, setting description, home, maintainers and details. Then I did `:wq` in VIM.

When I went to my `$HELM_HOME/workspace/charts/openldap` chart, the Chart.yaml was set back to its originally generated value:

```yaml
name: openldap
home: http://example.com/your/project/home
version: 0.1.0
description: Provide a brief description of your application here.
maintainers:
- Your Name <email@address>
details: |-
  This section allows you to provide additional details about your application.
  Provide any information that would be useful to users at a glance.
```

/cc @gabrtv
