### ISSUE TITLE
Stop download dependencies if not needed

### ISSUE THREAD

**Issue by rleffd** [helm/helm#30199]
Hello,

I'm using a chart that have two dependencies. These dependencies are conditionned by a bool variable in values. Even if I disable the use of theses charts in my values, helm always pull the dependencies charts even if I don't need them.

```yaml
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.x.x
- condition: mariadb.enabled
  name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
```

`mariadb.enabled' is set to false because I don't need to install mariadb. But these charts are always downloaded.

Is there a way to disable this behaviour ?
