### ISSUE TITLE
Annotation "helm.sh/chart" seems incorrect with aliasing

### ISSUE THREAD

**Issue by mbrancato** [helm/helm#30578]
I was playing with adjusting the release name for a subchart, and I wondered how to install two of the same chart such as two databases. I came up with something like this:

```yaml
dependencies:
  - name: redis
    version: 20.x.x
    repository: https://charts.bitnami.com/bitnami
    alias: keys
  - name: redis
    version: 20.x.x
    repository: https://charts.bitnami.com/bitnami
    alias: users
```

And then I noticed that the `helm.sh/chart` annotation is a bit weird on the resources created. This is from `helm template`:

```yaml
# Source: mychart/charts/keys/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: mychart-keys
  namespace: "default"
  labels:
    app.kubernetes.io/instance: mychart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keys
    app.kubernetes.io/version: 7.4.2
    helm.sh/chart: keys-20.8.0
spec:
  podSelector:
    matchLabels:
...
```

I felt that the annotation should still be `helm.sh/chart: redis-20.8.0` and the `alias` field should only affect `Release.Name`.

Related to: #9052
