### ISSUE TITLE
Helm Fails with Limited RBAC When resourceNames is Specified

### ISSUE THREAD

**Issue by matteogastaldello** [helm/helm#30588]
**Description:**  
Helm encounters an authorization error when attempting to install a resource under a restricted RBAC policy that specifies `resourceNames`.  

### **Steps to Reproduce**  
1. Apply the following RBAC Role:  
   ```yaml
   apiVersion: rbac.authorization.k8s.io/v1
   kind: Role
   metadata:
     name: fireworksapp-8
     namespace: krateo-system
   rules:
   - apiGroups: [""]
     resourceNames:
     - composition-fireworksapp-8-tabpane-applicationstatus-row-column-1
     resources:
     - configmaps
     verbs: ["*"]
   ```
2. Use Helm to install a resource that matches the RBAC constraints.
3. Helm fails with the following error:  
   ```
   configmaps is forbidden: User "system:serviceaccount:krateo-system:fireworksapps-v1-1-13" 
   cannot create resource "configmaps" in API group "" in the namespace "krateo-system"
   ```

### **Root Cause**  
Helm leverages Kubernetes CLI Runtime to interact with the cluster. Specifically:  
- [Helm code](https://github.com/helm/helm/blob/c95d8cefcd69b63ee0983a0dfea59b5a6e4d2528/pkg/kube/client.go#L602) calls Kubernetes CLI Runtime.  
- The underlying CLI Runtime function ([resource helper](https://github.com/kubernetes/cli-runtime/blob/81a7e0854310ccd588adf75ccb7da3db67747c48/pkg/resource/helper.go#L240)) does not specify the resource name in its request to the Kubernetes API server.  

Since the API request does not include the specific resource name, the RBAC check requires full access to the resource type (e.g., `configmaps`), even though the intention is to operate on a single resource.

### **Impact**  
- Helm cannot operate under RBAC constraints that limit access to specific resource names using `resourceNames`.  
- The issue also affects `GET` operations, preventing retrieval of individual resources when `resourceNames` is used.  

### **Expected Behavior**  
Helm should support installations and retrievals under RBAC policies that restrict access to specific resource names.
