### ISSUE TITLE
add a way to override some templates from a helm chart without forking

### ISSUE THREAD

**Issue by sibelius** [helm/helm#30595]
I'd like to be able to customize or change some resources of a helm chart without forking it or vendoring it

Use case

I'm using argocd helm chart, but it is not applying some values.yaml correctly, so I'd like just to modify some resources to another template

```
apiVersion: v2
name: argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 7.8.5
    repository: https://argoproj.github.io/argo-helm
````

The structure would be like this

argocd
- templates/<> some templates that I want to customize from the helm chart
- Chart.lock
- Chart.yaml
- values.yaml

In my use case was this one

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    helm.sh/chart: argo-cd-7.8.5
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.14.2"
data:
  policy.csv: |
    # my custom policy
  policy.default: ""
  policy.matchMode: glob
  scopes: '[groups]'
```

the problem is when I add this resource to my helm chart and apply it, I get an warning in my argocd

I'm using argocd to sync and update argocd itself

<img width="1198" alt="Image" src="https://github.com/user-attachments/assets/8be63c7a-e11c-431e-9036-977a92ab61e5" />
