### ISSUE TITLE
Helm Upgrade Does Not Apply New CRD After Adding to Chart

### ISSUE THREAD

**Issue by vishwahiremat** [helm/helm#30600]
I have added a new Custom Resource Definition (CRD) to my Helm chart, but when performing a helm upgrade, the CRD does not get created or updated in the Kubernetes cluster. I was expecting helm upgrade to apply the new CRD added to the charts.

But running `kubectl apply -f <crd.yaml>` helped me to apply the newly added CRD to the cluster.

**Comment by outofrange** [comment]
How did you add your CRD to the chart? As part of `templates` or `crds`? (also see [docs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/))

**Comment by heruan** [comment]
I'm having a similar issue:

- if I put my CRDs in the `crds/` directory: they're never upgraded if they change on new chart versions (e.g. a new CRD version is added to `spec.versions`);

- if I put my CRDs as templates: when I install multiple releases of the same chart, it fails claiming the CRD belongs to another release.

Putting CRDs in `crds/` sounds more reliable, since it allows multiple releases of the same chart to install without conflicting with each other. It would be fine if Helm wouldn't allow changes of an already existing CRD version, but adding a new version should be supported.

**Comment by heruan** [comment]
Let's say I have this `app.yaml` file in `crds/` for chart version 1.0.0:

```yaml
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "apps.vaadin.com"
spec:
  group: "vaadin.com"
  names:
    kind: "App"
    plural: "apps"
    singular: "app"
  scope: "Namespaced"
  versions:
  - name: "v1"
    schema: ...
```

Then I release chart version 2.0.0 adding a version to `crds/app.yaml`:

```yaml
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "apps.vaadin.com"
spec:
  group: "vaadin.com"
  names:
    kind: "App"
    plural: "apps"
    singular: "app"
  scope: "Namespaced"
  versions:
  - name: "v1"
    schema: ...
  - name: "v2"
    schema: ...
```

I would expect `helm upgrade` to add the new version of the CRD.
