### ISSUE TITLE
--take-ownership does not adopt custom resources

### ISSUE THREAD

**Issue by p-se** [helm/helm#30622]
If a resource exists in the cluster and is to be adopted by `helm install --take-ownership`, it is left unchanged while helm reports the installation to have succeeded.

# Reproduce

0. Helm version v3.17.1+g980d8ac

1. Install any CRD

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datas.crd.com
spec:
  group: crd.com
  scope: Namespaced
  names:
    plural: datas
    singular: data
    kind: Data
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
```

2. Apply a custom resource onto the cluster.

```yaml
kind: Data
apiVersion: crd.com/v1
metadata:
  name: crd-test
  namespace: kube-system
  labels:
    test: adopt
spec:
  color: blue
  size: large
```

3. `helm install --take-ownership` a chart that contains a different version of the custom resource.

```yaml
kind: Data
apiVersion: crd.com/v1
metadata:
  name: crd-test
  namespace: kube-system
  labels:
    test: adopt
spec:
  weight: heavy
```

4. Notice that the custom resource has not changed at all (still at initial state) but helm reported the operation to have succeeded, including the creation of a helm release.

```
helm install foo ./foo --take-ownership 
NAME: foo
LAST DEPLOYED: Wed Mar  5 17:10:16 2025
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

# Suggested Solution

Transparently use three-way merge for `--take-ownership`.
