### ISSUE TITLE
Getting all "computed" values of a chart and dependencies without deploying it

### ISSUE THREAD

**Issue by donatelloOo** [helm/helm#30656]
Hi,

I'd like to get all the values ("COMPUTED VALUES") of a chart (and its dependencies) without deploying it:

* Like `helm show values`, but to get all possible values for current chart and dependencies.
* Like `helm get values --all`, but working on an undeployed chart

eg `helm show values ./path/to/chart --all` (there is no `--all` flag as of now)

COMPUTED VALUES:
```yaml
global:
 ...
subchart1:
 enabled: true
 image:
   name: example.com/org/repo
   version: 1.2.3
```

Could you please provide this feature ?

The use case is to dynamically parse / update some values and repackage the chart in a reliable way.

Note that previous issue https://github.com/helm/helm/issues/10435 was closed without valid workaround.
