### ISSUE TITLE
Modify dependency chart values in an child dict

### ISSUE THREAD

**Issue by tschenkelz** [helm/helm#30663]
It would be great if values of dependency charts can be overriden in an child dict. An example.
`Chart.yaml`
```
dependencies:
  - name: nginx
    version: 19.0.2
    repository: "https://charts.bitnami.com/bitnami"
    alias: 'mydict.mynginx'`
```
`values.yaml`
```
mydict:
  mynginx:
    containerPorts:
      http: 8000
```

Idk if alias would be the best way to go for this. Its only for demonstration purposes. Currently this results in an error, since it doesnt match this [regex](https://github.com/helm/helm/blob/4ac69fceb6cf2d87ac821410e14e2c8f68dd1ad9/pkg/chart/v2/chart.go#L31).
`C:\Users\User\dev\helm-demonstrate> helm template .
Error: validation: dependency "nginx" has disallowed characters in the alias`

For me it would be great if this could be done somehow. I am also interested in other opinions to this.

BR
