### ISSUE TITLE
"helm.sh/resource-policy: keep" cause custom resource not updated

### ISSUE THREAD

**Issue by dayeguilaiye** [helm/helm#30690]
# reproduce
1. Create any custom resource and a configmap in chart with `elm.sh/resource-policy: keep` annotation, for example MyCr:
```yaml
apiVersion: test.com.cn/v1
kind: MyCr
metadata:
  name: cr-a
  annotations:
    helm.sh/resource-policy: keep
spec:
  key: value-0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-a
  annotations:
    helm.sh/resource-policy: keep  
data:
  a: a-0
```
2. Execute `helm install test-release /path/to/chart`
3. Execute `helm uninstall test-release` (now both ConfigMap `cm-a` and MyCr `cr-a` still exist in k8s cluster)
4. Edit the yaml in chart, change `cr-a`'s spec into `key: value-1`, and change ConfigMap `cm-a` data into `a: a-1`
5. Execute `helm install test-release /path/to/chart`

**The Configmap `cm-a` will be updated, while the MyCr `cr-a` will not**
