### ISSUE TITLE
Error converting YAML to JSON

### ISSUE THREAD

**Issue by NikolaiKuznetsov** [helm/helm#30711]
Good afternoon. I've been struggling for two days. Please help me.
Helm displays error:
`Error: INSTALLATION FAILED: YAML parse error on amqp-integration-adapter/templates/deployment.yaml: error converting YAML to JSON: yaml: line 80: did not find expected key`

Helm version 3.17.2
OS: Linux RedOS 8

Template:
```
{{- if or (eq ($.Values.kind | toString | lower) "deployment") (not $.Values.kind) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.name | default .Chart.Name }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
    {{- include "template.valuesLabels" . | nindent 4 }}
    {{- include "template.valuesMetadataLabels" . | nindent 4 }}
  annotations:
    {{- include "template.annotations" . | nindent 4 }}
spec:
  {{- include "template.replicas" . | nindent 2 }}
  {{- include "template.strategy" . | nindent 2 }}
  selector:
    matchLabels:
      {{- include "template.selectorLabels" . | nindent 6 }}
      {{- include "template.valuesLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "template.selectorLabels" . | nindent 8 }}
      {{- include "template.valuesLabels" . | nindent 8 }}
      annotations:
        {{- include "template.rollout" . | nindent 8 }}
        {{- include "template.annotations" . | nindent 8 }}
        {{- include "template.annotationsChecksum" . | nindent 8 }}
    spec:
      {{- include "template.serviceAccountName" . | nindent 6 }}
      {{- include "template.imagePullSecrets" . | nindent 6 }}
      {{- include "template.podSecurityContext" . | nindent 6 }}
      {{- include "template.nodeSelector" . | nindent 6 }}
      {{- include "template.hostAliases" . | nindent 6 }}
      {{- include "template.hostname" . | nindent 6 }}
      {{- include "template.affinity" . | nindent 6 }}
      {{- include "template.tolerations" . | nindent 6 }}
      {{- include "template.dnsPolicy" . | nindent 6 }}
      {{- include "template.dnsConfig" . | nindent 6 }}
      {{- include "template.terminationGracePeriodSeconds" . | nindent 6 }}
      {{- if $.Values.initContainers }}
      initContainers:
        {{- include "template.initContainers" . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Values.name | default .Chart.Name }}
          {{- include "template.image" . | nindent 10 }}
          {{- include "template.imagePullPolicy" . | nindent 10 }}
          {{- include "template.command" . | nindent 10 }}
          {{- include "template.args" . | nindent 10 }}
          {{- include "template.defaultEnv" . | nindent 10 }}
          {{- include "template.env" . | nindent 10 }}
          {{- include "template.extraEnv" . | nindent 10 }}
          {{- include "template.extraEnvVars" . | nindent 10 }}
          {{- include "template.envFrom" . | nindent 10 }}
          {{- include "template.startupProbe" . | nindent 10 }}
          {{- include "template.livenessProbe" . | nindent 10 }}
          {{- include "template.readinessProbe" . | nindent 10 }}
          {{- include "template.resources" . | nindent 10 }}
          {{- include "template.securityContext" . | nindent 10 }}
          {{- include "template.lifecycle" . | nindent 10 }}

          

          {{- if or $.Values.ports $.Values.extraPorts }}
          ports:
            {{- include "template.ports" . | nindent 12 }}
            {{- include "template.extraPorts" . | nindent 12 }}
          {{- end }}        

          {{- if or $.Values.volumeMounts $.Values.extraVolumeMounts }}
          volumeMounts:
            {{- include "template.volumeMounts" . | nindent 12 }}
            {{- include "template.extraVolumeMounts" . | nindent 12 }}
          {{- end }}

        {{- include "template.extraContainers" . | nindent 8 }}

      {{- if or $.Values.volumes $.Values.extraVolumes }}
      volumes:
        {{- include "template.volumes" . | nindent 8 }}
        {{- include "template.extraVolumes" . | nindent 8 }}
      {{- end }}
{{- end }}

``` 
Output of `helm template amqp-integration-adapter --debug` command:
```
install.go:225: 2025-03-28 09:58:31.015074155 +0400 +04 m=+0.041776465 [debug] Original chart version: ""
install.go:242: 2025-03-28 09:58:31.015127348 +0400 +04 m=+0.041829659 [debug] CHART PATH: /home/admin/iua-helm-charts/amqp-integration-adapter

---
# Source: amqp-integration-adapter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-integration-adapter
  labels:
    helm.sh/chart: amqp-integration-adapter-2.7.6
    app.kubernetes.io/name: amqp-integration-adapter
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.7.6"
    app.kubernetes.io/managed-by: Helm
    
    
  annotations:
    helm.sh/template: 1.0.1
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app.kubernetes.io/name: amqp-integration-adapter
      app.kubernetes.io/instance: release-name
      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: amqp-integration-adapter
        app.kubernetes.io/instance: release-name
        
      annotations:
        
        rollout: "GR1g6e4XIWpG"
        helm.sh/template: 1.0.1
        
    spec:
      
      
      
      
      
      
      
      
      
      
      
      containers:
        - name: amqp-integration-adapter
          
          imagePullPolicy: Always
          
          
          env:
          ## from 'template.defaultEnv'
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          
          
          
          
          
          
          
          
          
          
          volumeMounts:
            
            ## from $.Values.volumeMounts
            - mountPath: /mnt
              name: smev-nfs-key
            - mountPath: /basket
              name: smev-nfs-basket
``` 

What could be the problem? I loaded `--debug` output into the YAML analyzer. The answer is Valid YAML!

**Comment by yxxhero** [comment]
@NikolaiKuznetsov please show the the values file and chart.

**Comment by robertsirc** [comment]
Hello, thank you for your issue but I have to agree with @yxxhero here and we would need to know your values and chart file so we can reproduce.

**Comment by NikolaiKuznetsov** [comment]
Thank you for showing interest in my problem. Here's what you asked for:

Chart.yaml
```
apiVersion: v2
name: amqp-integration-adapter
description: amqp-integration-adapter
type: application
version: 2.7.6
appVersion: 2.7.6
``` 

values.yaml
```
name: "amqp-integration-adapter"

volumeMounts:
  - mountPath: /mnt
    name: smev-nfs-key
  - mountPath: /basket
    name: smev-nfs-basket
```

**Comment by ingydotnet** [comment]
I suspect it's this part of your `deployment.yaml`:

```
      containers:
        - name: {{ $.Values.name | default .Chart.Name }}
          {{- include "template.image" . | nindent 10 }}
          {{- include "template.imagePullPolicy" . | nindent 10 }}
```

After `- name:` you are assigning a name string and then have other content afterwards.

This is invalid YAML:

```
foo: bar
- baz
```

I googled you error message and found https://github.com/soketi/soketi/issues/100

You can test by removing that section from your deployment.yaml and then running `helm template ...` on your chart and see if you still get that error.

**Comment by NikolaiKuznetsov** [comment]
> I suspect it's this part of your `deployment.yaml`:
> 
> ```
>       containers:
>         - name: {{ $.Values.name | default .Chart.Name }}
>           {{- include "template.image" . | nindent 10 }}
>           {{- include "template.imagePullPolicy" . | nindent 10 }}
> ```
> 
> After `- name:` you are assigning a name string and then have other content afterwards.
> 
> This is invalid YAML:
> 
> ```
> foo: bar
> - baz
> ```
> 
> I googled your error message and found [soketi/soketi#100](https://github.com/soketi/soketi/issues/100)
> 
> You can test by removing that section from your deployment.yaml and then running `helm template ...` on your chart and see if you still get that error.

I didn't understand from your answer what my problem was. YAML validators do not show errors. The `helm template amqp-integration-adapter --debug` command also does not output any errors.

![Image](https://github.com/user-attachments/assets/08876652-fbfb-40e3-9033-97763a4f6a11)

![Image](https://github.com/user-attachments/assets/fcde498a-1700-478a-81fa-682e04a8a239)

**Comment by ingydotnet** [comment]
Is it possible for you to share everything need for someone to reproduce?

* The `amqp-integration-adapter` chart source
* `env/local.yml` file
* `env/local/amqp-integration-adapter.yml` file

**Comment by ingydotnet** [comment]
The root cause appears to be that the template generation result is something akin to:

```
key: value
- value
- value
```

which is of course not valid yaml.

**Comment by NikolaiKuznetsov** [comment]
@ingydotnet
I apologize for not providing all the information right away. Here's what you asked for.

The `amqp-integration-adapter` chart source:
```
apiVersion: v2
name: amqp-integration-adapter
description: amqp-integration-adapter
type: application
version: 2.7.6
appVersion: 2.7.6
``` 

`env/local.yml` file:
```
# Global helm values
image:
  registry:  localhost:32000
  repository: dev
  imagePullPolicy: Always

restartPolicyJob: OnFailure

strategy:
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
  type: RollingUpdate

rollout: true

keysPath: "/root/iua-mnt/keys"
basketPath: "/root/iua-mnt/basket"
fileIntegrationPath: "/root/iua-mnt/file-integration"

pvc:
  smev-nfs-key:
    size: 100Mi
  smev-nfs-basket:
    size: 5Gi
  file-integration-adapter:
    size: 5Gi

storageClass: microk8s-hostpath

extraEnvVars:
  LOGGING_LEVEL_ROOT:  "INFO"
  TZ: "Europe/Moscow"
  kafka_servers: "192.168.1.77:9092"
  storage_adapter_url: "jdbc:postgresql://192.168.1.77:5432/smev_adapter_develop?user=smev_adapter&password=smev_adapter"
  storage_configuration_url: "jdbc:postgresql://192.168.1.77:5432/smev_adapter_develop?user=smev_adapter&password=smev_adapter"
  incoming_attachments_path: "/basket/incoming_attachments"
  storage_path: "/basket"
  storage-tool: "postgresql"
  storage_type: "postgresql"
  CRYPTO: ""
  COMPANY: ""
  version: "4.0.3"
  smev_http_adapter_url: "http://smev-http-adapter:7576"
  inner_integration_adapter_url: "http://inner-integration-adapter:7577"

# Chart values
volumes:
  - name: smev-nfs-key
    persistentVolumeClaim:
      claimName: smev-nfs-key
  - name: smev-nfs-basket
    persistentVolumeClaim:
      claimName: smev-nfs-basket
  - name: file-integration-adapter
    persistentVolumeClaim:
      claimName: file-integration-adapter
```

`env/local/amqp-integration-adapter.yml` file:
```
replicaCount: 1

resources:
  requests:
    memory: '100Mi'
    cpu: '100m'
  limits:
    memory: '900Mi'
    cpu: '1'
```
