### ISSUE TITLE
Helm allows conflicting subcharts and dependencies without warning

### ISSUE THREAD

**Issue by banjoh** [helm/helm#30710]
Given a helm chart with a subchart in the `charts` directory, say `nginx`, and a conflicting dependency is added to `Chart.yaml` Helm does not detect this when downloading dependencies. Instead, a duplicate chart is downloaded.

**Chart.yaml**
```yaml
apiVersion: v2
name: foo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: nginx
    version: 19.0.3
    repository: oci://registry-1.docker.io/bitnamicharts
```

**Contents of the chart**
```
.
├── Chart.lock
├── Chart.yaml
├── charts
│   ├── nginx
│   │   ├── Chart.lock
│   │   ├── Chart.yaml
...
├── templates
│   ├── NOTES.txt
...
└── values.yaml
```

**The problem**
`charts/nginx` chart was downloaded using `helm pull oci://registry-1.docker.io/bitnamicharts/nginx --untar -d charts/`. Running `helm dependency update` will download nginx dependency to `charts/nginx-19.0.3.tgz`. Helm will template seems to prefer the `charts/nginx` subchart. This behaviour can be confusing because it would not be clear which dependency would be preferred. 

**Proposal**
Helm ought to better detect that a duplicate dependency in `Chart.yaml` conflicts with another subchart in `charts` directory and error accordingly with something like below

```sh
Error: Dependency conflict detected: A subchart named 'nginx' already exists in charts/ directory.  
Please remove the manually added subchart or exclude it from Chart.yaml dependencies.
```
