### ISSUE TITLE
Semver doesn't correctly patch versions

### ISSUE THREAD

**Issue by tkelloggcribl** [helm/helm#30758]
Hi! Really love the project and wanted to report something that I'm confident the team is already aware of but if not wanted to have a place for comments about expected behavior:

The underlying semver library doesn't respect major|minor|patch in pre-release versions.

For example:

```
{{ semverCompare ">=1.18.0"  "v1.31.6-eks-bc803b4" | quote }}
```

returns false rather than true.

To reproduce, we can run create a "bugreport" chart:

`bugreport/Chart.yaml`:
```
apiVersion: v2
name: semver-bug-report
version: 0.1.0
appVersion: "1.0"
description: Demonstrates semverCompare issue with EKS version suffix.
```

`bugreport/templates/cm.yaml`
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-semver-debug
data:
  kube_version_provided: {{ .Capabilities.KubeVersion.Version | quote }}

  comparison_1_constraint: ">=1.18.0"
  comparison_1_version: {{ .Capabilities.KubeVersion.Version | quote }}
  comparison_1_expected: "true"
  comparison_1_actual: {{ semverCompare ">=1.18.0" .Capabilities.KubeVersion.Version | quote }}

  {{- $kubeVersionClean := .Capabilities.KubeVersion.Version | splitList "-" | first -}}
  comparison_2_constraint: ">=1.18.0"
  comparison_2_version: {{ $kubeVersionClean | quote }}
  comparison_2_expected: "true"
  comparison_2_actual: {{ semverCompare ">=1.18.0" $kubeVersionClean | quote }}
```

And then test by passing in explicit version: 
```
helm template myrelease ./bugreport --kube-version "v1.31.6-eks-bc803b4"
```

Output:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myrelease-semver-debug
data:
  kube_version_provided: "v1.31.6-eks-bc803b4"

  # --- Compare with real kubernetes version ---
  comparison_1_constraint: ">=1.18.0"
  comparison_1_version: "v1.31.6-eks-bc803b4"
  comparison_1_expected: "true"
  comparison_1_actual: "false"

  # --- Compare with cleaned version ---comparison_2_constraint: ">=1.18.0"
  comparison_2_version: "v1.31.6"
  comparison_2_expected: "true"
  comparison_2_actual: "true"
```

tldr:

Expect semver to honor major|minor|patch even with pre-release versions

Thanks again!
