### ISSUE TITLE
Support for importing files from parent charts in subchart templates (e.g., for dynamic dashboard resources)

### ISSUE THREAD

**Issue by dzabel** [helm/helm#30761]
### Summary

In our setup, we have a Helm chart named `grafanamanager`, which is responsible for deploying Grafana instances using the Grafana Operator. This chart is reused extensively in various umbrella charts.

A common use case is to provision multiple `GrafanaDashboard` resources based on JSON files. These JSON files are defined in a directory within the umbrella chart (e.g., `dashboards/*.json`). Currently, we must implement the logic to import and process these files in *each* umbrella chart individually.

We would prefer to encapsulate this logic directly in the `grafanamanager` subchart, so that umbrella charts only need to supply the JSON files in a specific path (via `values.yaml`) without re-implementing the import logic.

Unfortunately, due to current Helm limitations (as discussed in [helm/helm#4026](https://github.com/helm/helm/issues/4026) and [helm/helm#3276](https://github.com/helm/helm/issues/3276)), `.Files.Glob` and `.Files.Get` cannot access files located outside the current chart's root directory.

### Desired Behavior

We would like to request (or discuss) support in a future Helm version (perhaps Helm 4) for:

- Allowing subcharts to reference files provided in the umbrella chart's directory (via `Files.Glob` or `Files.Get`)
- Or, alternatively, a way to explicitly *pass* file references from parent to child chart templates (not just values)

### Why this matters

This enhancement would:

- Greatly improve modularity and reuse of subcharts
- Eliminate repetitive logic in umbrella charts
- Enable DRY principles for Helm chart design in large setups

### Example of the current workaround (defined in each umbrella chart):

```yaml
{{- range $path, $bytes := .Files.Glob "dashboards/*.json" }}
{{- $name := base ($path) | replace "_" "-" | trimSuffix ".json" | trunc 63 | trimSuffix "-" }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: {{ $name }}
  labels:
    app: grafana
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  instanceSelector: {{ $.Values.dashboards.instanceSelector | toYaml | nindent 4 }}
  json: >
{{ $.Files.Get $path | indent 4 }}
  datasources:
    - inputName: "DS_PROMETHEUS"
      datasourceName: "Prometheus"
{{- end }}
```

We’d like to move this template logic into the grafanamanager subchart – but this is currently not possible because the subchart has no access to files in the umbrella chart context.

Final thoughts
This limitation affects many Helm users and prevents clean separation of responsibilities between reusable subcharts and project-specific umbrella charts. We’d be happy to collaborate or test any proposals for this in Helm 4.

Thanks for your consideration!
