### ISSUE TITLE
Error templating when multiple subchart used bitnami/common

### ISSUE THREAD

**Issue by Baboulinet-33** [helm/helm#30772]
Hello,
I'm having a problem using 2 bitnami charts in my project.
Each chart uses a sub-chart called ‘common’ and I think there is collusion in the names of the functions.

For example, when I run a `helm template test .`, I get:
```
Error: template: test/charts/redis/templates/replicas/serviceaccount.yaml:13:14: executing "test/charts/redis/templates/replicas/serviceaccount. yaml‘ at <include ’common.labels.standard‘ (dict ’customLabels‘ .Values.commonLabels “context” $)>: error calling include: template: test/charts/etcd/charts/common/templates/_labels.tpl:6:27: executing ’common.labels.standard‘ at &lt;include ’common.names.name" . >: error calling include: template: test/charts/etcd/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

I created a public project to show the concern: https://github.com/Baboulinet-33/helm_test

Translated with DeepL.com (free version)

**Comment by jamoflaw** [comment]
This is due to Bitnami bumping the major version of the common library in the redis chart but not in the etcd chart

if you extract the etcd chart and bump the bitnami common as per:

```
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  # change this from 1.x.x to 2.x.x
  version: 2.x.x
```

it will work (or at least template - I haven't validated if the chart is consistent with this version of the common library)
