### ISSUE TITLE
Copy status field for objects that are updated for PUT request when doing helm upgrade --install --force

### ISSUE THREAD

**Issue by mlhv** [helm/helm#30789]
When `helm upgrade --force` replaces an object with the new release manifest, the status of the object is overwritten entirely. This messes up the status of the object. It would be best if when doing helm forced installs: the status field of objects are copied (similar to how kubectl replace conducts a GET request and then a PUT request).  

We want `--force` to replace the spec of the manifests it's applying (but not the status) because we do not want to preserve manual edits in the cluster. But when doing so, we do not want it to wipe out the status of said objects.

Example of kubectl replace, with logs shown:

`kubectl replace -f my-example.yaml -v=8`

**Comment by TerryHowe** [comment]
Were you going to include logs?

**Comment by mlhv** [comment]
> Were you going to include logs?

Hi, yeah these are some example logs of us trying to recreate the issue from Argo Rollouts:

### Setup
- Install [Argo Rollouts](https://argo-rollouts.readthedocs.io/en/stable/installation/) and the CRDs
- Make a chart called argo-example and add the following files to your templates (delete any other irrelevant files)
```yaml
#rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: default
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  strategy:
    blueGreen:
      activeService: rollouts-demo-active
      previewService: rollouts-demo-preview
      autoPromotionEnabled: false
    # canary:
    #   steps:
    #   - setWeight: 20
    #   - pause: {}
    #   - setWeight: 40
    #   - pause: {duration: 10}
    #   - setWeight: 60
    #   - pause: {duration: 10}
    #   - setWeight: 80
    #   - pause: {duration: 10}
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - image: argoproj/rollouts-demo:yellow
        name: rollouts-demo
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 32Mi

#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-active
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: rollouts-demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-preview
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: rollouts-demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```


### Experimenting with Argo Rollouts and helm upgrade --force --install

### helm initial installation of argo chart/services
```
helm upgrade --install argo-example ./argo-example
Release "argo-example" does not exist. Installing it now.
NAME: argo-example
LAST DEPLOYED: Thu Apr 24 11:37:37 2025
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
- Initialized Rollout object status:
```
status:
  HPAReplicas: 5
  availableReplicas: 5
  blueGreen:
    activeSelector: 6cf78c66c5
    previewSelector: 6cf78c66c5
  canary: {}
  conditions:
  - lastTransitionTime: "2025-04-24T15:37:54Z"
    lastUpdateTime: "2025-04-24T15:37:54Z"
    message: RolloutCompleted
    reason: RolloutCompleted
    status: "True"
    type: Completed
  - lastTransitionTime: "2025-04-24T15:37:59Z"
    lastUpdateTime: "2025-04-24T15:37:59Z"
    message: Rollout is healthy
    reason: RolloutHealthy
    status: "True"
    type: Healthy
  - lastTransitionTime: "2025-04-24T15:37:54Z"
    lastUpdateTime: "2025-04-24T15:37:59Z"
    message: ReplicaSet "rollouts-demo-6cf78c66c5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-24T15:37:59Z"
    lastUpdateTime: "2025-04-24T15:37:59Z"
    message: Rollout has minimum availability
    reason: AvailableReason
    status: "True"
    type: Available
  currentPodHash: 6cf78c66c5
  observedGeneration: "1"
  phase: Healthy
  readyReplicas: 5
  replicas: 5
  selector: app=rollouts-demo,rollouts-pod-template-hash=6cf78c66c5
  stableRS: 6cf78c66c5
  updatedReplicas: 5
```
### Rollout Tests
- After changing the image in the Rollout spec to `argoproj/rollouts-demo:yellow` and upgrading the chart with `helm upgrade --install --force argo-example ./argo-example`, the Rollout does not pause, and proceeds to the promotion stage immediately.

```
helm upgrade --install --force argo-example ./argo-example
Release "argo-example" has been upgraded. Happy Helming!
NAME: argo-example
LAST DEPLOYED: Thu Apr 24 11:42:27 2025
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
```
- Status (immediately skipped promotion -- see activeSelector and previewSelector fields):
```
status:
  HPAReplicas: 5
  availableReplicas: 5
  blueGreen:
    activeSelector: 687d76d795
    previewSelector: 687d76d795
  canary: {}
  conditions:
  - lastTransitionTime: "2025-04-24T15:37:54Z"
    lastUpdateTime: "2025-04-24T15:37:54Z"
    message: RolloutCompleted
    reason: RolloutCompleted
    status: "True"
    type: Completed
  - lastTransitionTime: "2025-04-24T15:42:31Z"
    lastUpdateTime: "2025-04-24T15:42:31Z"
    message: Rollout is healthy
    reason: RolloutHealthy
    status: "True"
    type: Healthy
  - lastTransitionTime: "2025-04-24T15:37:54Z"
    lastUpdateTime: "2025-04-24T15:42:31Z"
    message: ReplicaSet "rollouts-demo-687d76d795" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-24T15:42:31Z"
    lastUpdateTime: "2025-04-24T15:42:31Z"
    message: Rollout has minimum availability
    reason: AvailableReason
    status: "True"
    type: Available
  currentPodHash: 687d76d795
  observedGeneration: "2"
  phase: Healthy
  readyReplicas: 5
  replicas: 5
  selector: app=rollouts-demo,rollouts-pod-template-hash=687d76d795
  stableRS: 687d76d795
  updatedReplicas: 5
```
### Without --force tag
- Initial status of Rollout:
```
status:
  HPAReplicas: 5
  availableReplicas: 5
  blueGreen:
    activeSelector: 5747959bdb
    previewSelector: 5747959bdb
  canary: {}
  conditions:
  - lastTransitionTime: "2025-04-24T16:06:40Z"
    lastUpdateTime: "2025-04-24T16:06:40Z"
    message: Rollout has minimum availability
    reason: AvailableReason
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-24T18:08:55Z"
    lastUpdateTime: "2025-04-24T18:08:55Z"
    message: Rollout is healthy
    reason: RolloutHealthy
    status: "True"
    type: Healthy
  - lastTransitionTime: "2025-04-24T18:08:55Z"
    lastUpdateTime: "2025-04-24T18:08:55Z"
    message: ReplicaSet "rollouts-demo-5747959bdb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-24T18:08:55Z"
    lastUpdateTime: "2025-04-24T18:08:55Z"
    message: RolloutCompleted
    reason: RolloutCompleted
    status: "True"
    type: Completed
  - lastTransitionTime: "2025-04-24T18:08:55Z"
    lastUpdateTime: "2025-04-24T18:08:55Z"
    message: Rollout is paused
    reason: RolloutPaused
    status: "False"
    type: Paused
  currentPodHash: 5747959bdb
  observedGeneration: "14"
  phase: Healthy
  readyReplicas: 5
  replicas: 5
  selector: app=rollouts-demo,rollouts-pod-template-hash=5747959bdb
  stableRS: 5747959bdb
  updatedReplicas: 5
```

- After changing the image in the Rollout spec to `argoproj/rollouts-demo:yellow` and upgrading the chart with `helm upgrade --install argo-example ./argo-example`, the Rollout properly pauses and waits for manual promotion:

```
status:
  HPAReplicas: 5
  availableReplicas: 5
  blueGreen:
    activeSelector: 5747959bdb
    previewSelector: 6cf78c66c5
  canary: {}
  conditions:
  - lastTransitionTime: "2025-04-24T16:06:40Z"
    lastUpdateTime: "2025-04-24T16:06:40Z"
    message: Rollout has minimum availability
    reason: AvailableReason
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-24T18:12:34Z"
    lastUpdateTime: "2025-04-24T18:12:34Z"
    message: Rollout is not healthy
    reason: RolloutHealthy
    status: "False"
    type: Healthy
  - lastTransitionTime: "2025-04-24T18:12:34Z"
    lastUpdateTime: "2025-04-24T18:12:34Z"
    message: RolloutCompleted
    reason: RolloutCompleted
    status: "False"
    type: Completed
  - lastTransitionTime: "2025-04-24T18:12:38Z"
    lastUpdateTime: "2025-04-24T18:12:38Z"
    message: Rollout is paused
    reason: RolloutPaused
    status: Unknown
    type: Progressing
  - lastTransitionTime: "2025-04-24T18:12:38Z"
    lastUpdateTime: "2025-04-24T18:12:38Z"
    message: Rollout is paused
    reason: RolloutPaused
    status: "True"
    type: Paused
  controllerPause: true
  currentPodHash: 6cf78c66c5
  message: BlueGreenPause
  observedGeneration: "15"
  pauseConditions:
  - reason: BlueGreenPause
    startTime: "2025-04-24T18:12:38Z"
  phase: Paused
  readyReplicas: 5
  replicas: 10
  selector: app=rollouts-demo,rollouts-pod-template-hash=5747959bdb
  stableRS: 5747959bdb
  updatedReplicas: 5
```
- Promoting changes for rollout:
```
kubectl argo rollouts promote rollouts-demo
rollout 'rollouts-demo' promoted
```
- Final status after promotion
```
status:
  HPAReplicas: 5
  availableReplicas: 5
  blueGreen:
    activeSelector: 6cf78c66c5
    previewSelector: 6cf78c66c5
  canary: {}
  conditions:
  - lastTransitionTime: "2025-04-24T16:06:40Z"
    lastUpdateTime: "2025-04-24T16:06:40Z"
    message: Rollout has minimum availability
    reason: AvailableReason
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-24T18:13:55Z"
    lastUpdateTime: "2025-04-24T18:13:55Z"
    message: Rollout is healthy
    reason: RolloutHealthy
    status: "True"
    type: Healthy
  - lastTransitionTime: "2025-04-24T18:13:55Z"
    lastUpdateTime: "2025-04-24T18:13:55Z"
    message: ReplicaSet "rollouts-demo-6cf78c66c5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-24T18:13:55Z"
    lastUpdateTime: "2025-04-24T18:13:55Z"
    message: RolloutCompleted
    reason: RolloutCompleted
    status: "True"
    type: Completed
  - lastTransitionTime: "2025-04-24T18:13:55Z"
    lastUpdateTime: "2025-04-24T18:13:55Z"
    message: Rollout is paused
    reason: RolloutPaused
    status: "False"
    type: Paused
  currentPodHash: 6cf78c66c5
  observedGeneration: "15"
  phase: Healthy
  readyReplicas: 5
  replicas: 5
  selector: app=rollouts-demo,rollouts-pod-template-hash=6cf78c66c5
  stableRS: 6cf78c66c5
  updatedReplicas: 5
```

TLDR: We would like to be able to `--force` install the manifests without affecting (or outright removing) the `status` subresource of each object, which should be owned/managed by the controller owning the resource type.
