### ISSUE TITLE
toYaml function loses indentation in lists

### ISSUE THREAD

**Issue by pkesso** [helm/helm#30790]
toYaml function loses indentation in lists.

in values.yaml I have:
```
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: loadtest
                operator: In
                values:
                  - "true"
```
in template:
```
      affinity:
        {{- toYaml .Values.config.affinity | nindent 8 }}
```
result would not pass yamllint due to bad indents:
```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: loadtest
                operator: In
                values:
                - "true"
```

```
$ helm version
version.BuildInfo{Version:"3.17.0", GitCommit:"301108edc7ac2a8ba79e4ebf5701b0b6ce6a31e4", GitTreeState:"clean", GoVersion:"go1.24rc2"}
```
