### ISSUE TITLE
Helm behaves differently between installing a chart versus updating a chart

### ISSUE THREAD

**Issue by pareion** [helm/helm#30815]
**Issue**
The issue occurs when first installing a HelmChart which has a ConfigMap with either an empty property or a property with a null value. When installing the HelmChart the first time, the ConfigMap will contain all the properties no matter that value the property has, but when updating the HelmChart the properties will be stripped from the ConfigMap.

**Reproduction steps**
When installing a HelmChart with a ConfigMap which has a property like so:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: "configmap"
data:
  value_property: "value"
  null_property: null
  empty_property:
```
It will create the ConfigMap (Installed with `helm upgrade --install my-app .`) with all properties wether they are null, empty or has a value:
```
apiVersion: v1
data:
  empty_property: ""
  null_property: ""
  value_property: value
kind: ConfigMap
metadata:
  name: configmap
```

Running the same command without changing any properties in my pod config or ConfigMap file results in the the `null_property` and `empty_property` being removed from the ConfigMap.

Result after running the command (`helm upgrade --install my-app .`) again:
```
apiVersion: v1
data:
  value_property: value
kind: ConfigMap
```

**Expected result**
The configMap configuration to be created the same, either trimming all the properties as in the update scenario or being created always in the installation scenario. We don't want to handle the two scenarios differently, but it should always remain the same.

**Notes**
Files used
`Chart.yaml`
```
apiVersion: v2
name: deployment
version: 0.0.1
```
`templates/configMap.yaml`
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: "configmap"
data:
  value_property: "value"
  null_property: null
  empty_property:
```
`templates/pod.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "deployment"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "app"
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: "app"
    spec:
      containers:
      - name: "deployment"
        image: "stefanprodan/podinfo:latest"
        imagePullPolicy: "IfNotPresent"
        envFrom:
        - configMapRef:
            name: "configmap"
```
