### ISSUE TITLE
`helm package` clobbers subcharts with different aliases and versions

### ISSUE THREAD

**Issue by damienwebdev** [helm/helm#30821]
## What I was doing

I was packaging a chart that I have built, run and tested locally so that I can distribute it in an OCI registry.  This chart has two dependencies that are the same helm chart at different versions (for a blue-green deployment). 

The `Chart.yaml` looks like:

```yml
apiVersion: v2
name: temp-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- alias: opensearch
  name: opensearch
  repository: https://opensearch-project.github.io/helm-charts/
  version: 1.14.0
  tags:
    - blue
- alias: opensearch2
  name: opensearch
  repository: https://opensearch-project.github.io/helm-charts/
  version: 2.32.0
  tags:
  - green
```

## What happened

When I install this chart from source locally, it works as expected. However, when I install this chart after running `helm package`, I wind up without subcharts installed because `helm package` clobbered the other version of the subchart to a single folder with the same name.

The crux of the issue is the way that helm is packaging the tarball. Looking at the local version of the chart, it looks like:

`find .`

```bash
./.helmignore
./templates
./values-green.yaml
./values.yaml
./Chart.lock
./charts
./charts/opensearch-2.32.0.tgz
./charts/opensearch-1.14.0.tgz
./Chart.yaml
./values-blue.yaml
```

Where as the packaged tarball looks like:

`tar -tf temp-chart-0.1.0.tgz `

```
temp-chart/Chart.yaml
temp-chart/Chart.lock
temp-chart/values.yaml
temp-chart/.helmignore
temp-chart/values-blue.yaml
temp-chart/values-green.yaml
temp-chart/charts/opensearch/Chart.yaml
temp-chart/charts/opensearch/values.yaml
temp-chart/charts/opensearch/templates/NOTES.txt
temp-chart/charts/opensearch/templates/_helpers.tpl
temp-chart/charts/opensearch/templates/configmap.yaml
temp-chart/charts/opensearch/templates/extraManifests.yaml
temp-chart/charts/opensearch/templates/ingress.yaml
temp-chart/charts/opensearch/templates/networkpolicy.yaml
temp-chart/charts/opensearch/templates/poddisruptionbudget.yaml
temp-chart/charts/opensearch/templates/podsecuritypolicy.yaml
temp-chart/charts/opensearch/templates/role.yaml
temp-chart/charts/opensearch/templates/rolebinding.yaml
temp-chart/charts/opensearch/templates/securityconfig.yaml
temp-chart/charts/opensearch/templates/service.yaml
temp-chart/charts/opensearch/templates/serviceaccount.yaml
temp-chart/charts/opensearch/templates/statefulset.yaml
temp-chart/charts/opensearch/.helmignore
temp-chart/charts/opensearch/CHANGELOG.md
temp-chart/charts/opensearch/README.md
temp-chart/charts/opensearch/ci/ci-ingress-class-name-values.yaml
temp-chart/charts/opensearch/ci/ci-rbac-enabled-values.yaml
temp-chart/charts/opensearch/ci/ci-values.yaml
temp-chart/charts/opensearch/Chart.yaml
temp-chart/charts/opensearch/values.yaml
temp-chart/charts/opensearch/templates/NOTES.txt
temp-chart/charts/opensearch/templates/_helpers.tpl
temp-chart/charts/opensearch/templates/configmap.yaml
temp-chart/charts/opensearch/templates/extraManifests.yaml
temp-chart/charts/opensearch/templates/ingress.yaml
temp-chart/charts/opensearch/templates/networkpolicy.yaml
temp-chart/charts/opensearch/templates/poddisruptionbudget.yaml
temp-chart/charts/opensearch/templates/podsecuritypolicy.yaml
temp-chart/charts/opensearch/templates/role.yaml
temp-chart/charts/opensearch/templates/rolebinding.yaml
temp-chart/charts/opensearch/templates/securityconfig.yaml
temp-chart/charts/opensearch/templates/service.yaml
temp-chart/charts/opensearch/templates/serviceMonitor-secret.yaml
temp-chart/charts/opensearch/templates/serviceMonitor.yaml
temp-chart/charts/opensearch/templates/serviceaccount.yaml
temp-chart/charts/opensearch/templates/statefulset.yaml
temp-chart/charts/opensearch/.helmignore
temp-chart/charts/opensearch/CHANGELOG.md
temp-chart/charts/opensearch/README.md
temp-chart/charts/opensearch/ci/ci-ingress-class-name-values.yaml
temp-chart/charts/opensearch/ci/ci-rbac-enabled-values.yaml
temp-chart/charts/opensearch/ci/ci-values.yaml
```

## Steps

> You do not need a running cluster validate this behavior.

1. `helm create temp-chart`
2. `cd temp-chart`
3. Add the following to `dependencies` of your `Chart.yaml`
```yml
dependencies:
- alias: opensearch
  name: opensearch
  repository: https://opensearch-project.github.io/helm-charts/
  version: 1.14.0
  tags:
    - blue
- alias: opensearch2
  name: opensearch
  repository: https://opensearch-project.github.io/helm-charts/
  version: 2.32.0
  tags:
    - green
```
4. `rm -rf templates/*` - they are irrelevant to this bug.
5. Make three values files:

values.yml
```yml
tags:
  blue: false
  green: false
```

values-green.yaml
```yml
tags:
  blue: false
  green: true
```

values-blue.yaml
```yml
tags:
  blue: true
  green: false
```

6. Run `helm template --dry-run --debug .  | grep "helm.sh/chart"`
7. See 

```bash
install.go:225: 2025-05-01 09:30:11.301655334 -0400 EDT m=+0.073608137 [debug] Original chart version: ""
install.go:242: 2025-05-01 09:30:11.301724543 -0400 EDT m=+0.073677246 [debug] CHART PATH: /path
```

7. Run `helm template --dry-run --debug . --values=values-green.yaml | grep "helm.sh/chart"`
8. See

```
install.go:225: 2025-05-01 09:31:07.223549616 -0400 EDT m=+0.054741537 [debug] Original chart version: ""
install.go:242: 2025-05-01 09:31:07.223608122 -0400 EDT m=+0.054799943 [debug] CHART PATH: /path

    helm.sh/chart: opensearch2-2.32.0
    helm.sh/chart: opensearch2-2.32.0
    helm.sh/chart: opensearch2-2.32.0
    helm.sh/chart: opensearch2-2.32.0
    helm.sh/chart: opensearch2-2.32.0
        helm.sh/chart: opensearch2-2.32.0
```

9. Run `helm template --dry-run --debug . --values=values-blue.yaml | grep "helm.sh/chart"`
10. See

```bash
install.go:225: 2025-05-01 09:32:39.188689304 -0400 EDT m=+0.052087095 [debug] Original chart version: ""
install.go:242: 2025-05-01 09:32:39.188746911 -0400 EDT m=+0.052144702 [debug] CHART PATH: /path

    helm.sh/chart: opensearch-1.14.0
    helm.sh/chart: opensearch-1.14.0
    helm.sh/chart: opensearch-1.14.0
    helm.sh/chart: opensearch-1.14.0
    helm.sh/chart: opensearch-1.14.0
        helm.sh/chart: opensearch-1.14.0
```

11. Run: `helm package .`
12. Run `helm template --dry-run --debug temp-chart-0.1.0.tgz --values=values-blue.yaml | grep "helm.sh/chart"`
13. ❗❗❗❗ See 

```bash
install.go:225: 2025-05-01 09:33:51.565214874 -0400 EDT m=+0.048118930 [debug] Original chart version: ""
install.go:242: 2025-05-01 09:33:51.565270681 -0400 EDT m=+0.048174637 [debug] CHART PATH: /path/temp-chart-0.1.0.tgz
```
14. Run `helm template --dry-run --debug temp-chart-0.1.0.tgz --values=values-green.yaml | grep "helm.sh/chart"`

See

```
install.go:225: 2025-05-01 09:33:57.168878138 -0400 EDT m=+0.077686380 [debug] Original chart version: ""
install.go:242: 2025-05-01 09:33:57.168935046 -0400 EDT m=+0.077743188 [debug] CHART PATH: /path/temp-chart-0.1.0.tgz

    helm.sh/chart: opensearch2-2.32.0
    helm.sh/chart: opensearch2-2.32.0
    helm.sh/chart: opensearch2-2.32.0
    helm.sh/chart: opensearch2-2.32.0
    helm.sh/chart: opensearch2-2.32.0
        helm.sh/chart: opensearch2-2.32.0
```

## Potential Solutions

When packaging the chart, we need to either store charts into `charts` as their `alias` or store them as is done locally like `${name}-${version}`.

## Workarounds

I suspect that I can just package up the chart with tar myself and distribute that instead.

## System Info
```bash
$ helm version
version.BuildInfo{Version:"v3.17.3", GitCommit:"e4da49785aa6e6ee2b86efd5dd9e43400318262b", GitTreeState:"clean", GoVersion:"go1.23.7"}
```

This is the same as https://github.com/helm/helm/issues/11484#issuecomment-2352551590 however, I'm not exactly sure what https://github.com/helm/helm/issues/11484 so I don't want to conflate the two issues.

I was also able to confirm that this bug exists on `main`...

1. `git clone git@github.com:helm/helm.git`
2. `make build`
3. cd `temp-chart`
4. `PATH_TO/bin/helm package .`
5. `PATH_TO/bin/helm template --dry-run --debug temp-chart-0.1.0.tgz --values=values-blue.yaml`

See:

```bash
level=DEBUG msg="Original chart version" version=""
level=DEBUG msg="Chart path" path=/path/temp-chart/temp-chart-0.1.0.tgz
level=DEBUG msg="number of dependencies in the chart" dependencies=0
```
