### ISSUE TITLE
Feature request: enable values.yaml interpolation from previously defined values

### ISSUE THREAD

**Issue by jmtx1020** [helm/helm#30851]
For example, you can do the following in Ansible:

```yaml
db_user: 'admin'
db_pass: 'supersecret'
db_name: 'postgres'
db_url: 'postgres://{{ db_user }}:{{ db_pass }}@localhost/{{ db_name }}'
```

it would be nice to be able to do the same in values.yaml for instance:

```yaml
# parent chart
parent_chart_values:
  imagePullSecrets:
    - name: docker-hub-creds

# subchart values
subchart_values:
  imagePullSecrets: {{ this.parent_chart_values.imagePullSecrets | toJson }}
```

**Comment by TerryHowe** [comment]
It sounds like you are asking for two things combine values into one value and access parent chart values. I would say combining values into one other value would be confusing if a user overrode `db_pass` and also `db_url`.

**Comment by jmtx1020** [comment]
> It sounds like you are asking for two things combine values into one value and access parent chart values. I would say combining values into one other value would be confusing if a user overrode `db_pass` and also `db_url`.

Not really, it shouldn't matter where the value is defined, the values file should be able to reference previously defined values.

If they want to update the `db_url` they can do that as well.

This isn't specifically about parent or sub charts, I was just using that as an example, thought maybe it would make sense to create a namespace for each chart to avoid collision. 

In ansible, it's doable so long as you define a value before you use it.

```yaml
username: "user"
password: "password"
db_url: "postgres://{{ this.username }}:{{ this.password }}@localhost:5432/{{ this.db_name }}";

# in a hypothetical Postgres Chart 
postgresChart:
  username: {{ this.username }}
  password: {{ this.password }}

# in a hypothetical Postgres Backup Chart
postgresBackup:
  username: {{ this.username }}
  password: {{ this.password }}
  # this is running in a different pod so we need to overwrite the URL
  db_url: "postgres://{{ this.username }}:{{ this.password }}@localhost:5432/{{ this.db_name }}";
```
