### ISSUE TITLE
[3.18.0] Boolean check when integer is 0 is not True

### ISSUE THREAD

**Issue by carlosjgp** [helm/helm#30923]
Using helm `3.17.2`

```
            {{- if .Values.s3.httpsPort }}
            - containerPort: {{ .Values.s3.httpsPort }}
              name: swfs-s3-tls
            {{- end }}
```
with value
```
s3:
  enabled: true
  # add additional https port
  httpsPort: 0
```
resulted on
```
if .Values.s3.httpsPort
```
evaluated as `false`

with Helm `3.18.0`

```
if .Values.s3.httpsPort
```

is evaluated as `true` and breaks the release with 0 being an invalid port
