### ISSUE TITLE
helm dep up does not extract dependency charts to the expected path

### ISSUE THREAD

**Issue by gjemp** [helm/helm#30949]
Hi,
have searched if anyone has posted something about my case but have not found anything exactly same for now . 

So  my case: 

1. private OCI registry
2. chart published  with long path - oci://private-registry/helm-common/service-name/dev/service-name:1.0.0-asdas
3. Parent chart contains only values.yml 

dependency defined as following:
```
dependencies:
  - name: service-name/dev/service-name
    version:  ^1.0.0-0
    repository: oci://private-registry/helm-common
```

when i run `helm dep up` it will pull the latest version and store the service-name-1.0.0-asdas.tgz under charts/ directory and update Chart.lock  

I was expecting that it will extract the package .

Now when I run  `helm template .` it will  complain about missing chart path 

`Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: service-name/dev/service-name`

Running `helm dep build`  does exactly same thing as `helm dep up`

What is the point to update dependency if you can not verify the chart

**Comment by manslaughter03** [comment]
Hello,

According to the documentation name should be the name of the Chart dependency not a path.

> The name field is the name of the chart you want.

Have you try to update your Chart.yaml to move `service-name/dev` to repository field ?

```yaml
dependencies:
  - name: service-name
    version:  ^1.0.0-0
    repository: oci://private-registry/helm-common/service-name/dev
```
