### ISSUE TITLE
Spurious warnings when parent and dependency charts have different types for the same value

### ISSUE THREAD

**Issue by ianroberts** [helm/helm#30940]
I have a chart that has a dependency on the [bitnami rabbitmq chart](https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq), and I'm getting a spurious warning about a "non-table value".  After a bit of digging I have reduced the example down to the following:

**Chart.yaml**
```yaml
apiVersion: v2
name: test-chart
description: Chart to demonstrate spurious warnings
type: application
version: 0.1.0
appVersion: "0.1"

dependencies:
  - name: rabbitmq
    version: 15.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
```

**values.yaml**
```yaml
ingress:
  enabled: true
  tls:
    host: host.example.com
```

(plus any template, I've just used one that renders `{{ .Values | toYaml }}` to show the final merged values).

Running this chart with `helm template` gives:

```
coalesce.go:301: warning: destination for rabbitmq.ingress.tls is a table. Ignoring non-table value (false)
```

---

The `values.yaml` file in the rabbitmq chart includes

```yaml
ingress:
  tls: false
```

So in the subchart `ingress.tls` is boolean, but in the top-level chart `ingress.tls` is a table.

Running helm under a debugger I see that the warning message is being printed when helm is exploring the dependency tree, and seems to be trying to coalesce the _top level_ chart values with those of the rabbitmq _subchart_.  This seems wrong since if you want to override a subchart value from the parent chart you would prefix it with/nest it under the subchart name (e.g. `rabbitmq.ingress.tls`).  The culprit appears to be this recursive call inside `processDependencyEnabled`:

https://github.com/helm/helm/blob/de62ed1b2e05155e5cea66e90b798961d296f72b/pkg/chart/v2/util/dependencies.go#L214

where `t` is the subchart (rabbitmq) but `cvals` is the (already-coalesced) _top-level_ values - I believe that instead of the top-level `cvals` we should be passing down just the values relevant to the subchart (`cvals[t.Metadata.Name]`).

The `{{ .Values | toYaml }}` template shows me that the actual merged values used to render are fine, the warning just appears due to the incorrect coalesce that happens during the process to determine which dependencies are enabled and which are not.
