### ISSUE TITLE
helm pull --version does not block when chart with complex semver is not found in the repo.

### ISSUE THREAD

**Issue by daezaa** [helm/helm#30986]
I have an [index.yaml](https://github.com/IBM/charts/blob/master/repo/ibm-helm/index.yaml) as below

```
apiVersion: v1
entries:
  cpd-platform:
  - apiVersion: v2
    appVersion: 5.2.0
    created: "2025-06-10T02:18:50.976532031Z"
    description: A Helm chart for Kubernetes
    digest: aff60dd61241863725ae724e33045043ae193f9d277c185e81adbe82ca48b74d
    name: cpd-platform
    type: application
    urls:
    - https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm/cpd-platform-5.2.0+20250516.013559.108.tgz
    version: 5.2.0+20250516.013559.108
```

When I try to pull helm chart with wrong version, the cli still downloads the latest version.

```
$ helm pull --repo https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm --version 5.2.0+missing.chart cpd-platform
$ ls
cpd-platform-5.2.0+20250516.013559.108.tgz
```

The `version` of the chart is valid semver 2 based on https://semver.org/.

I was expecting error like `Error: chart "cpd-platform" version "5.2.0+missing.chart" not found in https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm repository`

Is this expected behaviour by `helm` cli?
