### ISSUE TITLE
proposal: Helm dynamic aliases

### ISSUE THREAD

**Issue by kfox1111** [helm/helm#3126]
TL:DR; Essentially it is a way for an end user to instantiate multiple versions of a subchart and give it the values for each instances.

I would like to have a new flag on dependencies in requirements.yaml which is a boolean such as:
dynamic-alias: true

When the dependency is set as a dynamic alias, the following behaviour is changed:
the values are consulted for the typical value section for the child chart. (either the aliased name if specified, or the charts name if alias is not specified).
1. If the section is blank, the child chart is not used at all. (treated like it is conditionally disabled)
2. If the section has data, the root of the section is a hash. The key is used to name the child chart instance. One instance per key. The values in the subsection is used for that instance of the object.
3. the subcharts release would be named after the release and the key. such as "parent-child".

As extra credit, :), perhaps there should be a 'defaults' key that is used to set defaults that effect all instances in the section. so like:

requirements.yaml:
```yaml
dependencies:
- name: mariadb
  version: 0.7.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  dynamic-alias: true
```

values.yaml:
```
some_stuff:...
mariadb:
    defaults:
      pvc.create: true
    foo:
      memsize: 16g
    bar:
      memsize: 8g
```

Which would launch two mariadb instances with different memory sizes.

I have some charts that I currently launch as half a dozen instances of the chart, that I could use this functionality, and a tweak to the values file to treat as a single chart I upgrade when I want to add more instances that are 99% the same config as the rest. (prometheus node exporters with different node selectors/plugins per host type, flannel instances with different nic configs, etc)
