### ISSUE TITLE
Resource policy flag ignores value

### ISSUE THREAD

**Issue by Indigenuity** [helm/helm#3150]
The annotation for keeping a persistent resource seems to not behave as expected.  Consider this brief chart:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.volume.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "volume.beta.kubernetes.io/storage-class": "{{ .Values.volume.name }}"
    "helm.sh/resource-policy": {{ .Values.volume.resourcePolicy }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
```
The `"helm.sh/resource-policy"` annotation is what I'm focused on.

When the annotation is set to `keep`, I can install the chart and delete it properly--the volumeclaim is correctly kept, rather than being deleted with the rest of the release.

When I remove the annotation altogether, I can install the chart and delete it properly--the volume claim is correctly deleted with the rest of the release.

When the annotation is set to anything other than `keep` (e.g. `delete`, hard-coded or through .Values), I can install the chart properly, but the delete does not function as expected--the volumeclaim is not deleted with the rest of the release

I would expect that a value besides keep would not cause the volume to be kept after a delete.
