### ISSUE TITLE
Add 'export-values' to requirements

### ISSUE THREAD

**Issue by withnale** [helm/helm#3242]
There is a need for an `export-values` method when working with requirements.

At present there is already a mechanism for _pulling_ values from subcharts into the parent chart using the 'import-values' method defined in [docs/chart.md](https://github.com/kubernetes/helm/blob/master/docs/charts.md#importing-child-values-via-requirementsyaml). However, there is no equivalent method for encapsulating parts of the values tree when wishing to provide specific trees to subcharts.

We use parent charts often with many subcharts, but often these subcharts are used by many parent charts (M:N). In this scenario there is often a set of values we wish to pass to various sets of charts.

The methods we have right now allow:

1. We can put the value explicitly in the subcharts tree i.e.  `subchart1.myvalue` - however, this doesn't scale too well, since we want to define this value once in the parent chart but if multiple subcharts require this value, we need to explicitly set for each subchart in the parents values. i.e. `subchart1.myvalue`, `subchart2.myvalue`, etc. When we spin up a release, we want to specify the minimal set of value overrides (using `-f overrides.yaml`) as possible and not have to specify this for each subchart - so this isn't really viable.
1. Alternatively, we could use the `globals` namespace within the values tree. However, this isn't ideal either, since this tree is duplicated in all subcharts the values file quickly gets massive, and there are benefits in having the trees in use by each chart encapsulated specifically in the requirements. Managing a global namespace isn't ideal and can easily generate unforeseen side effects.

The attached PR approaches this by mimicking the `import-values` functionality but in the other direction - allowing you to specify the tree in the parent chart you wish to export into the values of the child chart.It also allows you to _ringfence_ settings to a duplicate (aliased) subchart, as can be seen in the example below:

```
dependencies:
      - name: subchart1
        repository: http://localhost:10191
        version: 0.1.0
        export-values:
          - child: release
            parent: release.old

      - name: subchart1
        repository: http://localhost:10191
        version: 0.1.0
        export-values:
          - child: release
            parent: release.new
        alias: subchart1a
```
Obviously, this simple use case can be achieved through other methods - it's when there are many requirements using a mix & match of various parent values that this change become effective.
