### ISSUE TITLE
confusing UX when using chart dependencies

### ISSUE THREAD

**Issue by majewsky** [helm/helm#3311]
So I saw that some other charts in my team's helm-charts repo use `requirements.yaml` like this:

```yaml
$ cat openstack/keystone/requirements.yaml
dependencies:
  - name: memcached
    repository: file://../../common/memcached
    version: 0.0.1
  - name: rabbitmq
    repository: file://../../common/rabbitmq
    version: 0.1.0
  - name: postgresql
    repository: file://../../common/postgresql
    version: 0.3.0
  - name: pgmetrics
    repository: file://../../common/pgmetrics
version: 0.1.0
```

I wanted to use that for my own chart as well, so I copied the `requirements.yaml` over into my chart and edited it to refer to the dependencies that I want to pull in. To generate `requirements.lock`, I was told by a colleague to use `helm dependency up`:

```
$ helm dependency up
Error: open /home/stefan/.helm/repository/repositories.yaml: no such file or directory
```

No idea what is going on here. I was told that `helm init -c` might fix stuff:

```
$ helm init -c
Creating /home/stefan/.helm/repository 
Creating /home/stefan/.helm/repository/cache 
Creating /home/stefan/.helm/repository/local 
Creating /home/stefan/.helm/starters 
Creating /home/stefan/.helm/cache/archive 
Creating /home/stefan/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /home/stefan/.helm.
Not installing Tiller due to 'client-only' flag having been set
Happy Helming!
$ helm dependency up
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Deleting outdated charts
```

No idea why it's writing errors there, but then it succeeds anyway and I now have a `requirements.lock` that looks plausible.

It appears that I likely did stuff that the Helm developers did not anticipate, so I tried finding documentation for `requirements.yaml`, but the only thing I can find in the docs is how to host repositories. I just want to pull in a chart from another directory, not deploy webservers.

Any idea how to make this procedure less confusing?
