### ISSUE TITLE
helm does not support objects with metadata.generateName

### ISSUE THREAD

**Issue by yuvipanda** [helm/helm#3348]
In kubernetes objects, if you set `metadata.generateName` rather than `metadata.name`, k8s will generate a unique name for you, and you can figure out the name from the full object returned from the initial create call. I'd expect this to work with helm, but helm does not seem to support this.

To reproduce, create a chart with the following template:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generateName: some-name-
  name: some-name
  labels:
    app: testcase
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testcase
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: gcr.io/google_containers/pause:3.0
```

If you install this, you'll get:
```
NAME:   wat12
LAST DEPLOYED: Tue Jan 16 01:21:12 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> MISSING
KIND           NAME
deployments    
```

Note that helm considers the deployment to be missing, even though kubectl tells you that the deployment was indeed created. If you try to upgrade this release,

```
Error: UPGRADE FAILED: Could not get information about the resource: resource name may not be empty
```

And the deployment object is then sort of 'lost' forever, untracked.

Ideally, helm would use the response from the original create call to figure out the name of the object to track and track that...
