### ISSUE TITLE
Support git repos in requirement repository field

### ISSUE THREAD

**Issue by carlpett** [helm/helm#3362]
There are a lot of projects that have helm charts in their git repositories, but that do not have a "real chart repo". 
It would be nice to be able to specify a requirement upon such a chart by referencing the git repo, something like 

```yaml
dependencies:
  - name: some-repo
    repository: git://github.com/org/some-repo.git/path-into-charts-directory
    version: master # branch/tag/commit
```

Currently I clone the repo and copy the chart directory, but managing updates from upstream is quite a bit more complicated this way.
