### ISSUE TITLE
Fail to import values when using an alias 

### ISSUE THREAD

**Issue by sgandon** [helm/helm#3457]
Hello,
I am using helm 2.7.2 and I believe I found an issue.
I have a simple subchart with one *values.yaml* file with on value
```
other:
  val3: val3
``` 
and the parent chart does an import-values like this
```
dependencies:
- name: subchart
  version: 0.1.0
  repository: http://chart.datapwn.com
  import-values:
    - child: other
      parent: parentkey.other
```
This works fine and the resulting values is
```
COMPUTED VALUES:
parentkey:
  other:
    val3: val3
subchart:
  global: {}
  other:
    val3: val3
```
but when I use an alias in the depenency definition like this
```
dependencies:
- name: subchart
  alias: foo
  version: 0.1.0
  repository: http://chart.datapwn.com
  import-values:
    - child: other
      parent: parentkey.other
```
the import-values fails to work and I have the following result
```
COMPUTED VALUES:
foo:
  global: {}
  other:
    val3: val3
```

I would expect that aliasing a dependency would not have any impact on the import-values process.
