### ISSUE TITLE
Extra newline generated from 'toyaml' function which is not removed even by an {{- end }}

### ISSUE THREAD

**Issue by lostmimic** [helm/helm#3470]
Created a values.yaml file with the following:
```
labels:
  tier: frontend
  foo: bar
  foo3: bar3
```

and a template with the following:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: "bug bug"
data:
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 2 }}{{- end }}
  bug: yes
```

When I run a dry run it returns:
```
[debug] Created tunnel using local port: '41519'

[debug] SERVER: "127.0.0.1:41519"

[debug] Original chart version: ""
[debug] CHART PATH: /home/me/bug

NAME:   eponymous-whale
REVISION: 1
RELEASED: Wed Feb  7 13:35:39 2018
CHART: bug-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
labels:
  foo: bar
  foo3: bar3
  tier: frontend

HOOKS:
MANIFEST:

---
# Source: bug/templates/bug-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "bug bug"
data:
  foo: bar
  foo3: bar3
  tier: frontend

  bug: yes
```

The empty line above `bug: yes` has the 2 spaces from the indent but the `{{- end }}` should have removed them (or better yet not passed back the extra line from the toyaml function
```
helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
related: https://github.com/kubernetes/helm/issues/3410

**Comment by CrusaderX** [comment]
I have issue:

```
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
spec:
  containers:
  - name: app
    image: image
    volumeMounts:
      - mountPath: test
        name: test
    resources:
{{ toYaml .Values.pod.resources | indent 6 }}
  volumes:
  - name: test
    emptyDir: {}
```
when I use this code without `-}}` it's adding a newline:

```
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
spec:
  containers:
  - name: app
    image: image
    volumeMounts:
      - mountPath: test
        name: test
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 64Mi
      
  volumes:
  - name: test
    emptyDir: {}
```

but when I use `-}}` it's concate to previous line position. What Im doing wrong?
```
...
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 64Mi
      volumes: <- shoud be in indent 2
  - name: test
    emptyDir: {}
```

```
helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

**Comment by consideRatio** [comment]
Still an issue in v2.8.2. I followed the code, this is the trace for reference.

https://github.com/kubernetes/helm/blob/be1e974cccec4f5583ef6e67b229f35f9e6edd2e/pkg/chartutil/files.go#L168-L179

Apparently `toYaml(...)` within Helm is a wrapper function around [github.com/ghodss/yaml](github.com/ghodss/yaml) `yaml.Marshal(...)`. I could confirm that the added new line comes from that functions return value by running the code below. But github.com/ghodss/yaml in turn uses [`gopkg.in/yaml.v2`](https://github.com/go-yaml/yaml) which has the actual source of the new line somewhere.

```go
package main

import (
	"fmt"

	"github.com/ghodss/yaml"
/* ghodss/yaml utilizes the following yaml package, using that directly gives us the same result.
	"gopkg.in/yaml.v2"
*/
)

type Person struct {
	Name string `json:"name"` // Affects YAML field names too.
	Age  int    `json:"age"`
}

func main() {
	p := Person{"Erik", 31}
	y, _ := yaml.Marshal(p)
	fmt.Println(string(y))
	fmt.Println(string(y))
	/* Output:
	age: 31
	name: Erik

	age: 31
	name: Erik

	*/
}
```

### Solution 1
Trim away the new line within Helm toYaml wrapper function.

### Solution 2
Make [`gopkg.in/yaml.v2`](https://github.com/go-yaml/yaml) remove the new line, and make that update propegate to [github.com/ghodss/yaml](github.com/ghodss/yaml) and finally into Helm.

### Solution 3
![hqdefault](https://user-images.githubusercontent.com/3837114/38341453-e340611c-3878-11e8-98e6-bd6876ad9322.jpg)

**Comment by consideRatio** [comment]
### Solution 4
Find a way to make the whitespace chomping work on the new line outputted by the toYaml, that would be the best solution I think! Why does that not work!?

__TODO__
- [ ] Track down what code is responsible for the whitespace chomping. Is it Helm or Go text/template perhaps?

**Comment by consideRatio** [comment]
Submitted PR to fix this, input appreciated!

**Comment by bacongobbler** [comment]
We've reverted this change due to breaking the Prometheus charts that expected this behaviour. Because this is expected behaviour we cannot change this, so we're gonna have to keep this one closed as intentional for Helm 2, but keep it open for Helm 3.

**Comment by WHEREINDAWORLDISAMY84** [comment]
So what is helm 3

**Comment by bacongobbler** [comment]
https://github.com/kubernetes-helm/community

**Comment by bivas** [comment]
So far I've managed to workaround this issue by calling `trim` on the `toYaml` output.
By doing something like this:
```
{{- range $i, $vol := .Values.volumes }}
        - name: {{ $vol.name }}
{{ toYaml $vol.path | trim | indent 10 }}
{{- end }}
```

I got the following output:
```
volumes:
        - name: log-volume
          hostPath:
            path: /var/log/foo
        - name: process-comm
          hostPath:
            path: /tmp/process/foo
        - name: config-volume
          configMap:
            name: foo-config
```
