### ISSUE TITLE
Importing child chart values and overriding

### ISSUE THREAD

**Issue by jwarder** [helm/helm#3498]
I'm building a chart which depends on the rabbitmq-ha chart from the default chart repository (https://github.com/kubernetes/charts/tree/master/stable/rabbitmq-ha). I am experiencing issues trying to import and override the child values from the rabbitmq-ha chart. Ideally I want to import all of the values from the child chart and override only a subset from the parent chart:

1) How can I import all values from the child chart which are at the root level?

2) I'm trying to override certain values from the parent which doesn't seem to work?

This is my requirements.yaml from the parent:

```
dependencies:
  - name: rabbitmq-ha
    version: 0.1.1
    repository: https://kubernetes-charts.storage.googleapis.com
    import-values:
      - child: rbac.create
        parent: rbac.create
```
values.yaml from parent:

```
## Role Based Access
## Ref: https://kubernetes.io/docs/admin/authorization/rbac/
##
rbac:
  create: false
```

values.yaml from child:

https://github.com/kubernetes/charts/blob/master/stable/rabbitmq-ha/values.yaml

Essentially as a start I'm trying to override rbac.create from the parent with false. In the child chart it is set to true.
