### ISSUE TITLE
Add metadata to created namespace

### ISSUE THREAD

**Issue by sathieu** [helm/helm#3503]

**Comment by sathieu** [comment]
Currently [createNamespace](https://github.com/kubernetes/helm/blob/a31e3b8fe1dbc1c6ab549d1ced97ed21e81142c0/pkg/kube/namespace.go#L26) doesn't set any metadata. Please add the following:
```yaml
apiVersion: v1
kind: namespace
metadata:
  name: foo
  labels:
    app: HERE
    chart: HERE
    heritage: Tiller
    release: HERE
```
