### ISSUE TITLE
Enable imagePullSecrets definition at the helm level, not the charts

### ISSUE THREAD

**Issue by jvassev** [helm/helm#3529]
Using private repositories is very common. The easiest way to pull from one is by configuring `imagePullSecrets` on the service account.

A lot of charts support `rbac.create=true` to enable serviceaccount provisioning.

This is where things get complicated: a user has to clone a chart (just to extend the sa.yaml templates) if they to set `image.repository` pointing to a private repo.

It would be nice if helm supported --image-pull-secrets=a,b,c that is applied on top of every resource of type ServiceAccount by populating the `.imagePullSercrets` field. This way all the charts that use rbac need not be changed (for example https://github.com/kubernetes/charts/blob/master/stable/prometheus/templates/alertmanager-serviceaccount.yaml)

To work around this behavior I now use this:
```bash
helm install --set rbac.create=true ... # install chart
kubectl patch sa ... #patch the service account
kubectl delete pod ... # when recreated, kubelet can pull
```

**Comment by hmagph** [comment]
Have you considered passing the image pull secret directly through the chart, so you don't need to patch the service account ?

e.g.
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
```

then you can pass the pull secret as an argument on the helm install command (--set ...)
