### ISSUE TITLE
Can not access sub-elements using with

### ISSUE THREAD

**Issue by vladimirtiukhtin** [helm/helm#3541]
Let's assume your values.yaml looks like:
```
services:
  first:
    replicas: 2
    image:
      name: blabla
      tag: bla
  second:
    replicas: 1
    image:
      name: albalb
      tag: alb
```
Then do:
```
{{ with .Values.services }}
...
{{ end }}
```
In that case I can make work .replicas, but can not .image.tag... It looks like "with" allows us to access just first level of dictionary. Correct me please if I am wrong
