### ISSUE TITLE
How to use existing static IP address when installing chart

### ISSUE THREAD

**Issue by appsyouwear** [helm/helm#3560]
Hi

How can I use an existing IP address when installing?
Sorry if this question should be for nginx-ingress?

Note: I have a static IP address on Google Cloud Network

```
helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
```

I have the following value.yaml:

```
# Default values for sample-go.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/my-cloud/sampler-go
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  loadBalancerIP: x.x.x.x
  port: 80

ingress:
  enabled: true
  annotations: {
        kubernetes.io/tls-acme: "true",
    kubernetes.io/ingress.class: "gce",
    kubernetes.io/ingress.global-static-ip-name: "kube-ingress"
  }

    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

```
