### ISSUE TITLE
Kubernetes restarted all of my pods when chensum/config changed

### ISSUE THREAD

**Issue by hiscal2015** [helm/helm#3584]
Hi, all

I have a chart with below templates files:
![template](https://user-images.githubusercontent.com/15604715/36835182-5cd535ee-1d70-11e8-92ea-e71f36562686.jpg)

values.yaml:
```
serverConfigFile:
  nginx1:
    nginx.conf: |
      user  nginx;
      worker_processes  2;

      error_log  /var/log/nginx/error.log warn;
      pid        /var/run/nginx.pid;

      events {  
          worker_connections  8192;
      }


      http {
          include       /etc/nginx/mime.types;
          default_type  application/octet-stream;

          log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for"';

          access_log  /var/log/nginx/access.log  main;

          sendfile        on;
          #tcp_nopush     on;

          keepalive_timeout  65;

          #gzip  on;

          include /etc/nginx/conf.d/*.conf;
      }  
  nginx2:
    nginx.conf: |
      user  nginx;
      worker_processes  2;

      error_log  /var/log/nginx/error.log warn;
      pid        /var/run/nginx.pid;

      events {  
          worker_connections  65535;
      }


      http {
          include       /etc/nginx/mime.types;
          default_type  application/octet-stream;

          log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for"';

          access_log  /var/log/nginx/access.log  main;

          sendfile        on;
          #tcp_nopush     on;

          keepalive_timeout  65;

          #gzip  on;

          include /etc/nginx/conf.d/*.conf;
      }                    
```
configmap-nginx1.yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: testnginx1-qa-config
data:
{{ toYaml .Values.serverConfigFile.nginx1 | indent 2 }}
```
configmap-nginx2.yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: testnginx2-qa-config
data:
{{ toYaml .Values.serverConfigFile.nginx2 | indent 2 }}
```

and part of deployment-nginx1.yaml:
```
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-nginx1.yaml") . | sha256sum }}    
```
and part of deployment-nginx2.yaml:
```
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-nginx2.yaml") . | sha256sum }}    
```

Then I updated configmap for nginx1 by editing values.yaml, I expected to see only pod nginx1 will be restarted, but actually both of my pods were restarted, what am I missing?

**Comment by laurieaw63** [comment]
@hiscal2015  Are you still seeing this issue or did you get around it? I am also seeing this behavior.

**Comment by hiscal2015** [comment]
@laurieaw63 I still have this issue and no solutions till now.

**Comment by hiscal2015** [comment]
@laurieaw63 I finally find out the issue. I defined chart: "{{ .Chart.Name }}-{{ .Chart.Version }}" in my deployment, it will be changed each time when chart version is changed, it caused sha256sum changed.
Check that if you have dynamic area in your configmap.

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
```
