### ISSUE TITLE
Extra newline being added when using "range .Files.Lines <filename>"

### ISSUE THREAD

**Issue by bobclarke** [helm/helm#3617]
Hello,

I have the following template:
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-binding
subjects:
  {{- range .Files.Lines "admins.data" }}
- kind: User
  name: {{ . }}
  apiGroup: rbac.authorization.k8s.io
  {{- end }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```
This is iterating over the file **admins.data**  which has the contents:
```
Alice
Bob
```

When helm install (dry-run) is executed the following output is produced:
```
---
# Source: devops-k8s-access-control/templates/cluster-admin-role-binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-binding
subjects:
- kind: User
  name: Alice
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: Bob
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name:
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```

As can be seen an extra iteration is taking place which is resulting in a blank name entry as follows:
```
- kind: User
  name:
  apiGroup: rbac.authorization.k8s.io
```
This causes an exception when I try to apply to my cluster because of the blank name field.

I have tried pretty much eveything I can think of and have checked the file with cat -v and vi (:set list), I can see nothing wrong. 

Can you tell me how to step this extra iteration for occurring?

Thanks,
Bob
