### ISSUE TITLE
Using .Chart.name in range function

### ISSUE THREAD

**Issue by idirouhab** [helm/helm#3684]
I'm trying to use the following syntax in one of the templates (deployment.yaml):

```
        {{- range $key, $value := .Values.secrets }}
        - name: $key
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}
              key: $value
        {{- end }}
```

But when I run helm upgrade --install I get this error:

```
Error: UPGRADE FAILED: render error in "MY_APP/templates/deployment.yaml": template: MY_APP/templates/deployment.yaml:29:25: executing "MY_APP/templates/deployment.yaml" at <.Chart.name>: can't evaluate field Chart in type interface {}
```
Looks like I'm able to use any kind of variable inside a range function. Neither `{{ .Values.env }}`

Is it expected behavior?

**Comment by thomastaylor312** [comment]
@idirouhab So because you are in a `range` block, `.` no longer refers to the top level scope. I believe you should be able to use `$` (e.g. `$.Chart.name`) to access the top level variables

**Comment by idirouhab** [comment]
Thanks @thomastaylor312 ,

unfortunately doesn't work, I tried even defining a variable in the very first line and try to using it but works just for simple string but not variables.



That works:
```
       {{ $myChartName := "FooBar" }}
        {{- range $key, $value := .Values.secrets }}
        - name: $key
          valueFrom:
            secretKeyRef:
              name: {{ $myChartName }}
              key: $value
        {{- end }}
```

That doesn't work:
```
       {{ $myChartName := .Chart.name }}
        {{- range $key, $value := .Values.secrets }}
        - name: $key
          valueFrom:
            secretKeyRef:
              name: {{ $myChartName }}
              key: $value
        {{- end }}
```

**Comment by mmingorance-dh** [comment]
I also face this issue when trying to use .Chart.Name and .Release.Version inside a range

**Comment by svend** [comment]
I'm working around this by storing `.` in a variable.

```
{{- $dot := . }}
{{- range $name, $data := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    app: {{ include "cronjob.name" $dot }}
    chart: {{ include "cronjob.chart" $dot }}
    release: {{ $dot.Release.Name }}
    heritage: {{ $dot.Release.Service }}
data: {}
```

**Comment by kierenj** [comment]
Just to confirm, as per my minimal repro here - https://github.com/kierenj/helm-template-issue-repro - that this is a bug.  The documentation even cites `$.Chart.Name` as the example use case where `$` as a root global scope is useful.  It just doesn't work

**Comment by Freyert** [comment]
Just to highlight a common problem that might bring people to this issue, but is NOT this issue. 

If you have a `template` and you see `Error: UPGRADE FAILED: render error in "MY_APP/templates/deployment.yaml": template: MY_APP/templates/deployment.yaml:29:25: executing "MY_APP/templates/deployment.yaml" at <.Chart.name>: can't evaluate field Chart in type interface {}` something to that effect; you need to add a dot to your template call.

`BAD: {{ template "cool-thing" }}`
`GOOD: {{ template "cool-thing" . }}`

**Comment by mdeknowis** [comment]
Also something good to know:

```txt
BAD: {{ template "cool-thing" . | quote }}
GOOD: {{ template "cool-thing" . }}
```

**Comment by bacongobbler** [comment]
@kierenj dot variables are not accessible through `define` functions, hence why it won't work. If you want to pass in variables to a function, use the `template` directive instead as others have demonstrated in this thread.

Looks like this can be closed because the original submitter's question seems to have been answered by several community members chiming in. Thanks everyone!

**Comment by fredleger** [comment]
Just for reference here in case you are landing to this issue, the documented way is working . as long as you are using `template` as mentioned by @bacongobbler : 

```yaml
  labels:
    app: {{ template "mychart.name" $ }}
    chart: {{ template "mychart.chart" $ }}
```
