### ISSUE TITLE
helm repo index with subfolders creates urls with backslashes

### ISSUE THREAD

**Issue by wemu** [helm/helm#3690]
Hello

We try to setup a chart registry and planned to structure it with subfolders. So here an example that represents what we tried:

```
$ tree .
.
|-- cockroachdb
|   |-- cockroachdb-0.5.4.tgz
|   `-- cockroachdb-0.6.6.tgz
`-- postgresql
    |-- postgresql-0.8.13.tgz
    |-- postgresql-0.9.0.tgz
    |-- postgresql-0.9.1.tgz
    `-- postgresql-0.9.2.tgz

2 directories, 6 files
```

Then create the index:
```
$ helm repo index --url https://gitserver/scm/k8s/charts/raw .
$ cat index.yaml
```

This results in the urls having a "%5C" in them (I believe a backslash):
```
...
    urls:
    - https://gitserver/scm/k8s/charts/raw/postgresql%5C/postgresql-0.9.0.tgz
    version: 0.9.0
  - created: 2018-03-15T13:47:43.2792366+01:00
    description: Object-relational database management system (ORDBMS) with an emphasis
      on extensibility and on standards-compliance.
    digest: be307fd5fab1b6e2af67b23d6a17dbdad66ee2c7ce2d166b04d1f36f3e1555dd
    engine: gotpl
    home: https://www.postgresql.org/
    icon: https://www.postgresql.org/media/img/about/press/elephant.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    maintainers:
    - name: swordbeta
    - name: databus23
    name: postgresql
    sources:
    - https://github.com/kubernetes/charts
    - https://github.com/docker-library/postgres
    urls:
    - https://gitserver/scm/k8s/charts/raw/postgresql%5C/postgresql-0.8.13.tgz
    version: 0.8.13
generated: 2018-03-15T13:47:43.2767378+01:00
```

using helm version 2.8.2 on windows.
this might not evevn be supported. I found some closed PR that should allow recursive index creation and slashes in chart names. So not sure if this is intentional. Since all commands work without complaints I see it as a bug.

We will use a flat structure for now - so nothing urgent. If all our services become helm charts we easily will have around 500 charts with 0-40 versions of each chart per week.
