### ISSUE TITLE
helm upgrade not picking up the new image tag specified via values.yml

### ISSUE THREAD

**Issue by ajay-aggarwal** [helm/helm#3702]
We have image tag specified in values.yml file. When we change this tag in this file and run helm upgrade, the release revision gets bumped up but new image is not picked up. 

In service template

`        image: {{ .Values.images.repository }}/my-performance:{{ .Values.images.tag }}
`
And in values.yml

 ```
images:
    tag: 8.0.0.327
```

Instead if we specify the new image tag directly in the service template, then helm upgrade correctly picks up the new image. 

Our helm version
```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

**Comment by ajay-aggarwal** [comment]
I noticed that its marked as question/support and not a bug/issue. Is it incorrect usage on my part? Thanks.

**Comment by ajay-aggarwal** [comment]
Should I be using ''--reset-values" flag with helm upgrade? What is the exact purpose of this flag? Is values.yml file completely ignored with helm upgrade if this flag is not used?

Thanks.

**Comment by jascott1** [comment]
Hi @ajay-aggarwal 

We often label new issues as `question/support` until we can confirm if it is a bug or not.

 `--reset-values` tells the upgrade process to use the _original_ values supplied with the chart. `--reuse-values` will merge in any new values into the original values. 

`helm upgrade` should upgrade your image tag without either of these flags in most cases. Can you try adding `--debug --dry-run` and confirming that the updated value is in the manifest?

**Comment by bacongobbler** [comment]
This might also be relevant: https://www.youtube.com/watch?v=dSw0w1x96ak&index=14&list=PLVt9l4b66d5EjjJ_VBe_5tEiJrAGLsDb-

**Comment by ajay-aggarwal** [comment]
Hi @jascott1 

Yes the manifest generated by `helm upgrade --debug --dry-run` does show the updated values.

**Comment by ajay-aggarwal** [comment]
Sure its a deployment. Here is the snippet from the helm template. Let me know if more details are needed. Thanks!

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: oci
    io.kompose.service: oci-service-performance
  name: oci-service-performance
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: oci-service-performance
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oci
        io.kompose.service: oci-service-performance
    spec:
      serviceAccountName: oci-service
      containers:
        image: {{ .Values.images.repository }}/oci-service-performance:{{ .Values.images.tag }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}

```
