### ISSUE TITLE
Hook delete policy not honored for preceding resource on a failure

### ISSUE THREAD

**Issue by mtherreault** [helm/helm#3714]
I have two jobs configured in `pre-upgrade` hook which both have `hook-succeeded,hook-failed` as the delete policy.

If both jobs succeed they are properly deleted. But if the second job is failing (and obviously the first has succeeded), the first job is not deleted.

Documentation about hooks being not very precise, I don't know is this should be the expected behavior, but this is not what I would expect intuitively.

Here a simple template that can be used to easily reproduce it with the latest version (2.8.2):

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-hook-1
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed
spec:
  backoffLimit: 1
  template:
    metadata:
      name: test-hook-1
    spec:
      restartPolicy: Never
      containers:
      - name: hook-script
        image: quay.io/coreos/hyperkube:v1.9.4_coreos.1
        command:
          - bash
          - -c
          - exit 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-hook-2
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: test-hook-2
    spec:
      restartPolicy: Never
      containers:
      - name: hook-script
        image: quay.io/coreos/hyperkube:v1.9.4_coreos.1
        command:
          - bash
          - -c
          - exit 1
```

**Comment by Lentil1016** [comment]
This is an expected behavior, at least to the maintainer of this code.

``` golang
pkg/tiller/release_server.go: 377
// If all hooks are succeeded, checkout the annotation of each hook to determine whether the hook should be deleted
// under succeeded condition. If so, then clear the corresponding resource object in each hook
```

And this behavior is also necessary in some specific case. When tiller start to execute a series of hook ordered by weight, it create one hook, and wait **until** this hook get into `ready` state, then start to create the next one. If tiller delete a hook as soon as this hook is ready, it will be hard to implement something like "run a job that depends on a configmap object as a pre-install hook". because the configmap will be deleted before the job is being created.

``` YAML
apiVersion: batch/v1
kind: Job
metadata:
    name: db-add-field
    annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
    template:
        spec:
            restartPolicy: Never
            containers:
            - name: oracle-delete-field
              image: harbor.io/system/:db-cli:0.0.1
              volumeMounts:
              - mountPath: /job
                name: job
              command: ["/bin/bash"]
              args: ["/job/delete_field.sh"]
            volumes:
            - name: job
              configMap:
                  name: db-scripts
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: db-scripts
data:
  add_field.sh: |
  remove_field.sh: |
    #!/bin/bash
    FIELD_ID=`echo test | md5sum | cut -b 1-6`
    ORACLE_URL="oracle/oracle@oracle:1521/oracle"
    sqlplus -S ${ORACLE_URL} << EOF
    DELETE FROM CCOD.CFG_NODE WHERE oid = '${FIELD_ID}';
    DELETE FROM GLS_SERVICE_UNIT WHERE areaid = '${FIELD_ID}';
    DELETE FROM GLS_MONITOR_CONFIG WHERE CONFIGDOMAIN = '${FIELD_ID}';
    DELETE FROM GLS_SERVICE_ROUTE WHERE ROUTEDOMAIN = '${FIELD_ID}';
    commit;
    EOF
```

**Comment by Lentil1016** [comment]
This is an expected behavior, at least to the maintainer of this code.

``` golang
pkg/tiller/release_server.go: 377
// If all hooks are succeeded, checkout the annotation of each hook to determine whether the hook should be deleted
// under succeeded condition. If so, then clear the corresponding resource object in each hook
```
When tiller start to execute a series of hook ordered by weight, it create one hook, and wait **until** this hook get into `ready` state, then start to create the next one. 

In your case. The job "test-hook-2" don't have its `spec.backoffLimit` configured. So [by default](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#pod-backoff-failure-policy), backoffLimit = 6. 

![image](https://user-images.githubusercontent.com/12230071/37751931-3a4a677c-2dd0-11e8-8c84-934fd16dc45b.png)

Before reaching the back-off Limit and return `failed`, Job is going to retry for six times. At the same time tiller just hang and waiting for "test-hook-2" become `ready` or `failed`, deletions haven't been started yet.

And starting deletions after all executions done is also necessary in some specific case. If tiller delete a hook as soon as this hook is `ready`, it will be hard to implement something like "run a job that depends on a configmap object as a pre-install hook". because the configmap will be deleted before the job is being created.

``` YAML
apiVersion: batch/v1
kind: Job
metadata:
    name: db-add-field
    annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
    template:
        spec:
            restartPolicy: Never
            containers:
            - name: oracle-delete-field
              image: harbor.io/system/:db-cli:0.0.1
              volumeMounts:
              - mountPath: /job
                name: job
              command: ["/bin/bash"]
              args: ["/job/delete_field.sh"]
            volumes:
            - name: job
              configMap:
                  name: db-scripts
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: db-scripts
  annotations:
      "helm.sh/hook": pre-install
      "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
data:
  remove_field.sh: |
    #!/bin/bash
    FIELD_ID=`echo test | md5sum | cut -b 1-6`
    ORACLE_URL="oracle/oracle@oracle:1521/oracle"
    sqlplus -S ${ORACLE_URL} << EOF
    DELETE FROM CCOD.CFG_NODE WHERE oid = '${FIELD_ID}';
    DELETE FROM GLS_SERVICE_UNIT WHERE areaid = '${FIELD_ID}';
    DELETE FROM GLS_MONITOR_CONFIG WHERE CONFIGDOMAIN = '${FIELD_ID}';
    DELETE FROM GLS_SERVICE_ROUTE WHERE ROUTEDOMAIN = '${FIELD_ID}';
    commit;
    EOF
```
