### ISSUE TITLE
Incorrect image when installing chart dependency with previously used (and purged) release name

### ISSUE THREAD

**Issue by chainlink** [helm/helm#3761]
Incorrect redis image installed as sub dependency
Output of `helm get`:

```
kind: Deployment
metadata:
  name: api-redis
  labels:
    app: api-redis
    chart: "redis-1.1.20"
    release: "api"
    heritage: "Tiller"
spec:
  template:
    metadata:
      labels:
        app: api-redis
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
      - name: api-redis
        image: "bitnami/redis:3.2.9-r2"
        imagePullPolicy: "IfNotPresent"
```

The chart dep specifies `1.1.20` which is correct, but it should use `redis:4.0.8-r7` 

Strangely, this only happened when after doing a `delete --purge`, and then `install` using the same name. If I install using a new name, it uses the new chart/image. Could it be grabbing something from old release data? 

Also, the `charts/redis-1.1.20.tgz` file has the correct redis version.

Potentially related: https://github.com/kubernetes/helm/issues/3249 (I did not run a `helm dep update` before the install)

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.9-gke.1", GitCommit:"c205eb8319d25aa46b1eb39b6c1d2bc5d1a49fae", GitTreeState:"clean", BuildDate:"2018-03-13T17:49:52Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE
