### ISSUE TITLE
Merge lists in chart dependencies values.yaml

### ISSUE THREAD

**Issue by jacobtomlinson** [helm/helm#3767]
I'm not sure how to approach a problem I have. Potentially it could result in a feature proposal, or we could just decide it isn't desired functionality. I would appreciate some guidance and discussion.

I am creating a chart which has a subchart. 

The subchart `values.yaml` file has a list item.

```yaml
foo: []
```

In the main chart I need to add an entry to that list. 

```yaml
mysubchart:
  foo:
    - "bar"
```

This works fine, however if a user of my chart wants to set `subchart.foo` they will override my list completely. Ideally I want the user's list and the chart list to be merged, however that would mean they couldn't override the value if they wanted to. 

If there wasn't a subchart dependency I would just put the values directly in the template, or have two lists sequentially in the template. However I don't have control over the templates.

~~I see three solutions:~~

- ~~Merge lists by default with the flag to override~~
- ~~Override lists by default with a flag to merge~~
- ~~Add way to override templates~~

**Comment by jacobtomlinson** [comment]
Thinking about it a bit more perhaps a better solution would be to allow `values.yaml` to reference itself. So the main chart could have a `foo` value, and then `subchart` would then have `foo` with a default and also the `foo` from the main chart. This would allow the user to append by setting `foo` or override by setting `mysubchart.foo`.

Example syntax (definitely up for debate, but illustrative)

```yaml
foo: []

mysubchart:
  foo:
    {{ foo }}
    - "bar"
```

**Comment by djablonski** [comment]
Another way to solve this problem, at least if your list entries are objects themselves, is using a hash instead of a list. This makes the template a little bit more complicated, but allows for individual overrides

If your original list looks like similar to this:
```
foo:
- bar:
    name: abc
    value: 123
- baz:
    name: xyz
    value: 987
```

In your template, use something like this:
```
foo:
{{- range $key, $value := .Values.foo }}
- {{ $key }}:
    {{ $value }}
{{- end }}
```

And, finally, in your values file, define the list like this instead
```
foo:
  bar:
    name: abc
    value: 123
  baz:
    name: xyz
    value: 987
```

**Comment by jacobtomlinson** [comment]
Thanks for the response @djablonski. 

I guess part of the point is I don't have control over the template, it is in a dependency that is managed by someone else.

**Comment by djablonski** [comment]
Okay, then it obviously doesn't help :(

**Comment by bacongobbler** [comment]
seems like https://github.com/kubernetes/helm/pull/3252 might be relevant here.

**Comment by bric3** [comment]
Hoping it can help some, I had this kind of setting in some of our legacy app.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  config.yaml: |+
    app:
      foo:
        keys:
          0:
            type: "xxx"
            key: "..."
          1:
            type: "yyy"
            key: "..."
          2:
            type: "zzz"
            key: "..."
```

And I want to make the keys tree / object configurable, thanks to @djablonski https://github.com/helm/helm/issues/3767#issuecomment-376769054, I was able to craft the configmap this way :

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  config.yaml: |+
    app:
      foo:
        keys:
          {{- range $key, $value := .Values.ckeys }}
          {{ $key }}:
            {{- toYaml $value | nindent 12 }}
          {{- end }}
```

Once we fixed the yaml parser of the app, it didn't like the keys to be quoted, we could revert to something more readable

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  config.yaml: |+
    app:
      foo:
        keys:
          {{- toYaml .Values.ckeys | nindent 10 }}
```


The values being : 

```
ckeys:
  0:
    type: "aaa"
    key: "..."
  1:
    type: "bbb"
    key: "..."
  2:
    type: "ccc"
    key: "..."

```
