### ISSUE TITLE
toYaml's and consistent indentation - ehh...

### ISSUE THREAD

**Issue by consideRatio** [helm/helm#3854]
## About
I've learned some stuff while I was trying to establish a good way to work with `toYaml` in Heml templates and that also generates output that is approved by a yaml linter. I'll first describe what I learned, then suggest something.

#### Block indentation
0. Many Helm charts create block indentation with a code block like `{{ ... | indent 4 }}` without any indentation in the template file, and it often looks like this.
```yaml
        volumeMounts:
        - name: xxxxx-volume
          mountPath: {{ .Values.xxxxx.persistence.mountPath | quote }}
        resources:
{{ toYaml .Values.xxxxx.resources | indent 10 }}
        readinessProbe:
        # ...
```
1. Sprigs `nindent` available since Helm 2.7 together with whitespace chomping improves the situation.
```yaml
        volumeMounts:
        - name: xxxxx-volume
          mountPath: {{ .Values.xxxxx.persistence.mountPath | quote }}
        resources:
          {{- .Values.xxxxx.resources | toYaml | nindent 10 }}
        readinessProbe:
        # ...
```
2. Until #3837 you also need to use `trimSuffix "\n"` together with `toYaml` in order to avoid either whitespace clutter or indentation issues down the line...
3. A more invasive but cleaner alternative to 1. and 2. until #3837 is probably to use `trim` ([thanks @keitwb](https://github.com/Masterminds/sprig/issues/54#issuecomment-360572045))
```yaml
spec:
  selector:
    # note the lack of whitespace chomping
    {{ .Values.hub.db.pvc.selector | toYaml | indent 4 | trim }}
```
#### List indentation
0. [kubernetes/charts list indentation](https://github.com/kubernetes/charts/blob/master/test/circle/lintconf.yml#L33) has surrendered consistency, and many repo's both use and not use list indentation.
1. `toYaml` formats lists with no extra indentation (`- key: value`, no spaces before `-`), so if you want to get consistent indentation, you must also do that. This is because if you use `toYaml` to output a nested list somewhere, it will have it's way and you end up with inconsistent indentation if you don't do the same as `toYaml`.
2. If you do decide to use no extra indentation, you need to adjust your indentation on `toYaml` output based on if is a list or dict.

```yaml
# values.yaml
list:
- key1: value1
dict:
  key1: value1

# template.yaml
myList:
  {{ .Values.list | toYaml | indent 0 | trim }}
myDict:
  {{ .Values.dict | toYaml | indent 2 | trim }}

# rendered template.yaml
myList:
- key1: value1
myDict:
  key1: value1
```

## I suggest that...
Oh I don't know... Perhaps someone comes up with a good idea on how to relieve the Helm users of this trouble in general. I only come up with the general idea that others could be helped in this journey by reading the docs on Helm in some way. Perhaps it could be documented...
- that `indent` in conjunction with `trim` can look nice for block indentation.
- that Helm through `toYaml` is opinionated towards using no list indentation, and you will need to adjust for the datatype `toYaml` is parsing for systematic indentation if you use no list indentation.

Perhaps the [recommended chart examples](https://github.com/kubernetes/charts#chart-format) could be updated to a way you think makes sense to recommend currently? Does it make sense to start using nindent instead of indent for example?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by madonius** [comment]
@bacongobbler this issue still persists. Please reopen the ticket, if possible.
I could open a new one if that is requested

**Comment by bacongobbler** [comment]
Have you tried using `nindent` as suggested by the OP? Can you explain what issues you’re running into?

**Comment by dbackeus** [comment]
Still an issue in that, why put users through the trouble of adding `| trim` to avoid unnecessary blank space in the YAML output? 

My personal question would be why put users through the trouble of indenting at all. The obvious thing to do is to automatically indent to the same level as the `{{ toYaml }}` is being run in. Eg. I would expect this to "just work":

Input:

```yaml
# values.yaml
map:
  key1: value1
  key2: value2

# templates/foo.yaml
map:
  {{ toYaml .Values.map }}
  key3: value3
```

Output:

```
map:
  key1: value1
  key2: value2
  key3: value3
```

If we really wanted to delight users it would seem nice to default to calling `toYaml` automatically since that appears to be the obvious use case for interpolating maps, eg. same results for the following template:

```
# templates/foo.yaml
map:
  {{ .Values.map }}
  key3: value3
```

That is what I attempted today before finding myself having to look up `toYaml` -> `indent` -> `nindent` -> `trim` to achieve what I wanted.

**Comment by consideRatio** [comment]
@dbackeus I've adopted the following pattern and and are now currently very happy about the current situation. I'd advice to skip `trim` stuff and go for this pattern.

```yaml
# values.yaml
map:
  key1: value1
  key2: value2

# templates/foo.yaml
map:
  {{- .Values.map | toYaml | nindent 2 }}
  key3: value3
```

**Comment by AlissonRS** [comment]
`nindent` adds an extra empty line which is annoying. However `indent` doesn't work unless you put the template expression in column 1 on the file (e.g. without any indentation itself).

**Comment by consideRatio** [comment]
I suggest doing like this now


```yaml
metadata:
  annotations:
    {{- .Values.annotations | toYam | nindent 4 }}
```
