### ISSUE TITLE
Helm dependency build requirements.lock is out of sync with requirements.yaml

### ISSUE THREAD

**Issue by cog-qlik** [helm/helm#3880]
Here's my settings, where I've got a dependency to the Redis chart (mind the `~` in the version).
`requirements.yaml`
```yaml
dependencies:
- name: redis
  version: ~1.2.1
  repository: "@stable"
```

`requirements.lock` (generated some day ago)
```yaml
dependencies:
- name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.2.1
digest: sha256:261a8e6b5fa755b41f7d4ca1b5da5f9f063c057349c7267a352b0a2577d22afe
```
If I run
```bash
helm dependency build mychart
```
it fails saying
```
Error: requirements.lock is out of sync with requirements.yaml
```
As far as I understood, even though a new version (patch) of the Redis chart is available (which is the case at the moment), the `build` command should only use the `requirements.lock` (as per [documentation](https://github.com/kubernetes/helm/blob/master/docs/helm/helm_dependency_build.md#synopsis)) file to construct the chart's dependency instead of failing.

---

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `minikube`
