### ISSUE TITLE
Proposal: function that lists entries in a directory

### ISSUE THREAD

**Issue by zuzzas** [helm/helm#3885]
Would it be possible to implement a [function](https://golang.org/pkg/io/ioutil/#ReadDir) that lists entries of a given directory? Perhaps, with an ability to traverse an arbitrary tree of directories?

**Comment by majewsky** [comment]
Does `.Files.Glob` do what you want? Use like:

```
{{ range $path, $content := .Files.Glob "*.txt" }}
...
{{ end }}
```

Relative paths like above are interpreted relative to the chart's top-level directory (the one that contains the `Chart.yaml`).

**Comment by distol** [comment]
Hi! No, `.Files.Glob` is not enough!

For example, we have directory with the following structure:
```
$ tree grafana-dashboards/
grafana-dashboards/
├── applications
│   ├── elasticsearch.json
│   ├── etcd.json
│   ├── ...
├── kubernetes-cluster
│   ├── capacity-planing.json
│   ├── ....
├── main
│   ├── deployment.json
│   ├── ...
└── nginx-ingress
    ├── controller.json
    ├── ...
```

And we could not add all dashboards to one ConfigMap, because of the size limit of ConfigMaps, so we hardcode the list of folders, and when we add a new one — we shall not forget to edit templates.
```
{{- range (tuple "applications" "kubernetes-cluster" "main" "nginx-ingress") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-definitions-{{ . }}
data:
{{ ($context.Files.Glob (print "grafana-dashboards/" . "/*.json")).AsConfig | indent 2 }}
{{- end }}
```
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  dashboards.yaml: |+
    apiVersion: 1
    providers:
{{- range (tuple "applications" "kubernetes-cluster" "main" "nginx-ingress") }}
    - name: {{ . }}
      orgId: 1
      folder: {{ . | replace "-" " " | title | quote }}
      type: file
      options:
        path: /grafana-dashboard-definitions/{{ . }}
{{- end }}
    - name: custom
      orgId: 1
      folder: Custom
      type: file
      options:
        path: /grafana-dashboard-definitions/custom
```
