### ISSUE TITLE
alias charts of the same app removed during helm package

### ISSUE THREAD

**Issue by jeff-knurek** [helm/helm#3909]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

So if you have a chart that has two dependencies of different version using alias (for example):
```
alias-test/
├── Chart.yaml
├── charts
│   ├── nginx-ingress-0.13.2.tgz
│   └── nginx-ingress-0.8.26.tgz
├── requirements.lock
├── requirements.yaml
├── templates
└── values.yaml
```
and the `requirements.yaml` file contains:
```
dependencies:
  - name: nginx-ingress
    version: 0.8.26
    alias: nginxIngressOld
    repository: https://kubernetes-charts.storage.googleapis.com

  - name: nginx-ingress
    version: 0.13.2
    alias: niNew
    repository: https://kubernetes-charts.storage.googleapis.com
```

And then you package that chart. The contents of `alias-test-0.1.0.tgz` will be:
```
../alias-test/
├── Chart.yaml
├── charts
│   └── nginx-ingress
│       ├── Chart.yaml
│       ├── README.md
│       ├── templates
│       │   ├── NOTES.txt
│       │   ├── _helpers.tpl
│       │   ├── clusterrole.yaml
...
│       │   └── udp-configmap.yaml
│       └── values.yaml
├── requirements.lock
├── requirements.yaml
└── templates
```

------
**NOTE**: there is only one version of `nginx-ingress` included as a subchart and it's version is 0.8.26

---------------

When you install the packaged chart: `helm install alias-test-0.1.0.tgz --dry-run --debug`, only one version of the nginx dependency gets installed.

See the diagram:
![alias-install](https://user-images.githubusercontent.com/25501371/38871407-1aac99d6-4251-11e8-9cc2-560ed398a6aa.png)
