### ISSUE TITLE
Proposal: --merge option for "helm inspect values"

### ISSUE THREAD

**Issue by bastianeicher** [helm/helm#3926]
## Motivation

Running `helm inspect values [CHART]` outputs the contents of a chart's `values.yaml` verbatim. This is often used to determine which configuration options a chart exposes. However, it does not provide the contents of `values.yaml` files of potential subcharts bundled in the `charts` subdirectory.

## Proposal

I would like to propose a new command-line option `--merge` for the `helm inspect values` sub-command.

This would cause Helm to merge the `values.yaml` files of a chart and all its subcharts and output the result. The code would need to handle prefixing value names from subcharts with the respective chart names, except for `global` values.

## Sample

Contents of `mychart/values.yaml`:
```yaml
somevar: 123
global:
  sample1: 'abc'
  sample2: 'def'
```

Contents of `mychart/charts/subchart/values.yaml`:
```yaml
somevar: 456
global:
  sample2: 'xyz'
  sample3: 'xyz'
```

Output of `helm inspect values --merge mychart`:
```yaml
somevar: 123 # from mychart
subchart: # prefixed with subchart name
  somevar: 456 # from subchart
global: # no prefixing for global
  sample1: 'abc' # from mychart
  sample2: 'def' # from mychart, value from subchart ignored
  sample3: 'xyz' # from subchart
```

## Implementation

If you guys think this is a sensible approach we (@andreasbieber, @typusomega, @bastianeicher) would be happy to give a PR a try.
