### ISSUE TITLE
configmap not overwritten

### ISSUE THREAD

**Issue by gsemet** [helm/helm#3933]
On helm 2.7 (cannot try on helm 2.8 yet), sometime when a user configmap is changed (by rendering), helm does not replace it on the kube cluster, while I expect it should have. Is it a known issue?

Mitigation is to delete the configmap and restart helm upgrade.

**Comment by jascott1** [comment]
Hi @gsemet 

Sorry for the trouble. Is there anyway you can share exact steps to reproduce?

**Comment by jascott1** [comment]
Helm upgrade does upgrade configmaps. To clarify, are you saying the configmap resource is unchanged and/or that the pod does not see the change?

**Comment by gsemet** [comment]
The configmap does not change, sadly. It is hard to reproduce, because most of the time the configmap is well updated. But last time when I changed `cull.enabled` (see the configmap [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/hub/configmap.yaml#L6)), the configmap wasn't updated by helm.

I verified that when i somehow recreate the configmap (delete/recreate), next helm upgrade will have the related pod restart (jupyterhub chart does use the checksum trick).

**Comment by jascott1** [comment]
I have tried to install to assist with troubleshooting but the chart times out for me. Would you be able to extract a simplified example we can use for a test case?

**Comment by jgerardsimcock** [comment]
I've been unable to update my configmap since the first deployment. I've deleted my config map and run update: 

<img width="941" alt="screen shot 2018-05-02 at 11 03 14 am" src="https://user-images.githubusercontent.com/6101444/39549175-9bf47d12-4df8-11e8-99f2-ba87b7e44aee.png">

Below is the values.yml that updates the configmap.

```
# Create and use roles and service accounts on an RBAC enabled cluster.
rbac:
  enabled: true


# Dependency configuration values
# -------------------------------
# To configure dependencies you must create a key with the name of the dependency
# and then configure as per the dependent chart's values.yaml. Don't forget to indent!

jupyterhub:
  singleuser:
    image:
      name: rhodium/notebook
      tag: 2018-04-26.1
    storage:
      capacity: 10Gi
    dynamic:
      storageClass: jupyterhub-user-ssd
    serviceAccountName: daskkubernetes
    cmd: ['start-singleuser.sh']
    defaultUrl: "/lab"
    storage:
      extraVolumes:
        - name: fuse
          hostPath:
            path: /dev/fuse
      extraVolumeMounts:
        - name: fuse
          mountPath: /dev/fuse
    cloudMetadata:
      enabled: true

  hub:
    extraConfig: |
      from kubernetes import client
      def modify_pod_hook(spawner, pod):
          pod.spec.containers[0].security_context = client.V1SecurityContext(
              privileged=True,
              capabilities=client.V1Capabilities(
                  add=['SYS_ADMIN']
              )
          )
          return pod
      c.KubeSpawner.modify_pod_hook = modify_pod_hook
      c.Authenticator.whitelist = {redacted}
      c.JupyterHub.logo_file = '/usr/local/share/jupyter/hub/static/custom/images/logo.png'
      c.JupyterHub.template_paths = ['/usr/local/share/jupyter/hub/custom_templates/',
                                    '/usr/local/share/jupyter/hub/templates/']

    

    image:
      name: jupyterhub/k8s-hub
      tag: v0.6

    extraVolumes:
      - name: custom-templates
        gitRepo:
          repository: "https://github.com/RhodiumGroup/rhodium-custom-jupyterhub-templates.git"
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyter/hub/custom_templates
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/templates"
      - mountPath: /usr/local/share/jupyter/hub/static/custom
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/assets"     
    
  cull:
    enabled: true
    users: false
    timeout: 1200
    every: 600 
```
