### ISSUE TITLE
helm template ignore empty yaml objects

### ISSUE THREAD

**Issue by rglyons** [helm/helm#3979]
Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Hi there,

I've been using `helm template` to generate YAML files for deployment. I would like to alter which YAMLs are output based on an `env` value in my values.yaml file so that I may generate production, dev, staging, etc deployments. For example, I only want to output a tls secret in a production environment:

values.yaml:
```yaml
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: production

namespace:
  foo: baz
.
.
.
```

tls.yaml:
```yaml
{{- if eq .Values.env "production" }}
apiVersion: v1
kind: Secret
metadata:
  name: tls
  namespace: {{ .Values.namespace.foo }}
  labels:
    app: bar
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
{{- end }}
```

Currently, tls.yaml is output as 
```yaml
---
# Source: mychart/templates/tls.yaml

```

If I try to apply this YAML object, kubectl outputs `error: no objects passed to apply`. Ideally, if a YAML object is empty after executing the go template, it should just not appear in the output.

I'd like to know two things: 
1. Can I or some existing contributor add a condition and/or runtime argument flag to tell `helm template` to skip empty objects in its output? I know exactly where to implement this change, and I considered forking, implementing, and opening a PR, but I wanted to hear whether this functionality has been intentionally left out thanks to some better work flow that achieves the same goal. 
2. If this functionality has been intentionally excluded, why? What is the better flow for achieving this goal?

Thanks in advance!
