### ISSUE TITLE
`Error: UPGRADE FAILED: timed out waiting for the condition`

### ISSUE THREAD

**Issue by jgerardsimcock** [helm/helm#3980]
Output of `helm version`: 
![screen shot 2018-04-26 at 4 35 21 pm](https://user-images.githubusercontent.com/6101444/39341666-f5194086-496f-11e8-9029-9ac8df6d5c70.png)

Output of `kubectl version`:
![screen shot 2018-04-26 at 4 35 50 pm](https://user-images.githubusercontent.com/6101444/39341677-fd6fe258-496f-11e8-8cf3-f36e7d91d90f.png)

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE
--------

I am currently unable to upgrade my deployment. The  `--debug` and `--wait --timeout 300` flags don't seem to add much. 

![screen shot 2018-04-26 at 4 32 00 pm](https://user-images.githubusercontent.com/6101444/39341943-44f39fe2-4971-11e8-9a57-7412c0d38aaf.png)

When I run `kubectl --namespace={namespace} get pods` I get the following info:

![screen shot 2018-04-26 at 4 32 24 pm](https://user-images.githubusercontent.com/6101444/39341994-7cbb3f84-4971-11e8-95d0-03c819a77957.png)

**Comment by jstoja** [comment]
Would you be able to provide a sample of the chart currently running and the one that you're trying to upgrade with?

**Comment by jgerardsimcock** [comment]
@jstoja I am new to this so if I've misunderstood your intentions, please excuse me. We usually redeploy due to updates to our docker image. We don't often update the chart itself. 

We are running a modified [jupyterhub](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/master/jupyterhub) cluster.  Below is a copy of their values/config.yml:

```
hub:
  service:
    type: ClusterIP
    ports:
      nodePort:
  baseUrl: /
  cookieSecret:
  publicURL:
  uid: 1000
  fsGid: 1000
  nodeSelector: {}
  concurrentSpawnLimit: 64
  activeServerLimit:
  db:
    type: sqlite-pvc
    upgrade:
    pvc:
      annotations: {}
      selector: {}
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      subPath:
      storageClassName:
    url:
  labels: {}
  extraConfig: {}
  extraConfigMap: {}
  extraEnv: {}
  extraContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  image:
    name: jupyterhub/k8s-hub
    tag: generated-by-chartpress
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi
  services: {}
  imagePullPolicy: IfNotPresent
  pdb:
    enabled: true
  networkPolicy:
    enabled: false
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0


rbac:
  enabled: true


proxy:
  secretToken: ''
  service:
    type: LoadBalancer
    labels: {}
    annotations: {}
    nodePorts:
      http:
      https:
  chp:
    image:
      name: jupyterhub/configurable-http-proxy
      tag: 3.0.0
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 0.2
        memory: 512Mi
  nginx:
    image:
      name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      tag: 0.9.0
      pullPolicy: IfNotPresent
    proxyBodySize: 64m
    resources: {}
  lego:
    image:
      name: jetstack/kube-lego
      # We need a couple of fixes related to ingress.provider that are in master
      # When 0.1.6 is released, switch to that!
      tag: master-2368
    resources: {}
  labels:
  nodeSelector: {}
  pdb:
    enabled: true
  https:
    enabled: true
    type: letsencrypt
    letsencrypt:
      contactEmail: ''
    manual:
      key:
      cert:
    hosts: []
  networkPolicy:
    enabled: false
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0


auth:
  type: dummy
  whitelist:
    users:
  admin:
    access: true
    users:
  dummy:
    password:
  ldap:
    dn:
      search: {}
      user: {}
    user: {}
  state:
    enabled: false
    cryptoKey:


singleuser:
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
      tag: generated-by-chartpress
  cloudMetadata:
    enabled: false
    ip: 169.254.169.254
  networkPolicy:
    enabled: false
    egress:
    # Required egress is handled by other rules so it's safe to modify this
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 169.254.169.254/32
  extraLabels: {}
  extraEnv: {}
  lifecycleHooks:
  initContainers:
  nodeSelector: {}
  uid: 1000
  fsGid: 100
  serviceAccountName:
  schedulerStrategy:
  storage:
    type: dynamic
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: '{username}'
    capacity: 10Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass:
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteOnce]
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: generated-by-chartpress
    pullPolicy: IfNotPresent
  startTimeout: 300
  cpu:
    limit:
    guarantee:
  memory:
    limit:
    guarantee: 1G
  cmd: jupyterhub-singleuser
  defaultUrl:


prePuller:
  hook:
    enabled: true
    extraEnv: {}
    image:
      name: jupyterhub/k8s-image-awaiter
      tag: generated-by-chartpress
  continuous:
    enabled: false
  extraImages: []
  pause:
    image:
      name: gcr.io/google_containers/pause
      tag: '3.0'


ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls:


cull:
  enabled: true
  users: false
  timeout: 3600
  every: 600
  concurrency: 10
  maxAge: 0
  podCuller:
    image:
      name: jupyterhub/k8s-pod-culler
      tag: generated-by-chartpress


debug:
  enabled: false
```

When run `helm upgrade...` I am supplying a modified values.yml below:

```
# Rhodium-Pangeo configuration values
# --------------------
# The following configuration options are specifically for the custom Pangeo components.
# Some values will be inherited into the dependent chart configs. See requirements.yaml for info.

# Create and use roles and service accounts on an RBAC enabled cluster.
rbac:
  enabled: true


# Dependency configuration values
# -------------------------------
# To configure dependencies you must create a key with the name of the dependency
# and then configure as per the dependent chart's values.yaml. Don't forget to indent!

jupyterhub:
  singleuser:
    image:
      name: rhodium/notebook
      tag: 2018-04-26.1
    storage:
      capacity: 10Gi
    dynamic:
      storageClass: jupyterhub-user-ssd
    serviceAccountName: daskkubernetes
    cmd: ['start-singleuser.sh']
    defaultUrl: "/lab"
    storage:
      extraVolumes:
        - name: fuse
          hostPath:
            path: /dev/fuse
      extraVolumeMounts:
        - name: fuse
          mountPath: /dev/fuse
    cloudMetadata:
      enabled: true

  hub:
    extraConfig: |
      from kubernetes import client
      def modify_pod_hook(spawner, pod):
          pod.spec.containers[0].security_context = client.V1SecurityContext(
              privileged=True,
              capabilities=client.V1Capabilities(
                  add=['SYS_ADMIN']
              )
          )
          return pod
      c.KubeSpawner.modify_pod_hook = modify_pod_hook
      c.Authenticator.whitelist = {"user1", "user2"}

      c.JupyterHub.logo_file = '/usr/local/share/jupyter/hub/static/custom/images/logo.png'
      c.JupyterHub.template_paths = ['/usr/local/share/jupyter/hub/custom_templates/',
                                    '/usr/local/share/jupyter/hub/templates/']

    

    image:
      name: jupyterhub/k8s-hub
      tag: v0.6

    extraVolumes:
      - name: custom-templates
        gitRepo:
          repository: "https://github.com/RhodiumGroup/rhodium-custom-jupyterhub-templates.git"
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyter/hub/custom_templates
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/templates"
      - mountPath: /usr/local/share/jupyter/hub/static/custom
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/assets"     
    
  cull:
    enabled: true
    users: false
    timeout: 1200
    every: 600 
```
