### ISSUE TITLE
How does one pass k8s secrets to black-box subcharts?

### ISSUE THREAD

**Issue by nicroto** [helm/helm#4154]
I thought I should somehow get them evaluated in my top-level values.yaml, but later learned values don't get expanded/templated.

So the question I have is - if I have a black-box dependency chart (I wan't to keep it like that) like Concourse or PostgreSQL, how do I pass credentials that I'have stored as k8s Secret objects in the cluster?

For my charts, I would expose secrets as env vars in my containers by referencing them from a template file (deployment.yaml etc.) (is this the best way, btw?) through:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
...
spec:
...
      containers:
...
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: secretUsername
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: secretPassword
```

But since I don't want to change my dependencies charts (I just want to used them as they are), I would like to be able to pass these secrets to them. The only mechanism I see for this is the values.yaml, but that doesn't evaluate secretKeyRef's and I am basically passing just a contentless unexpanded configuration.

**Comment by nicroto** [comment]
I think I've answered this one for myself - the subchart needs to provide a way for it. Either:

 * a `secretName` setting should be provided and then a fixed names for the expected secret property names should be used (so the subchart finds the correct values in it) or;
 * to allow to get the setting as yaml, so it is evaluated in the subchart's template - i.e. this could be in deployment.yaml:

```yaml
apiVersion: apps/v1beta2
kind: Deployment
...
spec:
...
  spec:
    containers
      - name: {{ .Chart.Name }}
...
          env:
            - name: SECRET_USERNAME
{{ toYaml .Values.secrets.secretUserName | indent 14 }}
            - name: SECRET_PASSWORD
{{ toYaml .Values.secrets.secretPassword | indent 14 }}
...
```

The only other option that I see would be to generate my top-level values.yaml outside of helm and only keep _templated_ version of my values.yaml within source control.
