### ISSUE TITLE
How to iterate through folders in chart

### ISSUE THREAD

**Issue by sparty02** [helm/helm#4157]
Given a chart that looks like this:

```
test
├── Chart.yaml
├── config
│   ├── group1
│   │   ├── bar.properties
│   │   └── foo.properties
│   └── group2
│       ├── baz.properties
│       └── qux.properties
├── templates
│   └── configmap.yaml
└── values.yaml
```

I'd like to generate a config map that looks like this:

```yaml
---
# Source: test/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: group1
data:
  bar.properties: a=b
  foo.properties: c=d
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: group2
data:
  baz.properties: e=f
  qux.properties: g=h
   
---

```
Note that this provides a simple convention for filling the config/ directory with folders that have the name of config maps, and files that have the config map contents in them.

However, I can't figure out how to iterate through the folders in the config directory.  I got somewhat close by iterating through the files, then resolving the base directory for each via a configmap.yaml template that looks like:

```yaml
{{- range $path, $bytes := .Files.Glob "config/**" }}
{{- $name := base (dir $path) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
data:
{{ ($.Files.Glob (printf "config/%s/*" $name)).AsConfig | indent 2 }}
---
{{- end }}
```

But this prints out a config map for each file, hence with two files in each directory, this doubles up the config maps and outputs this:

```yaml
---
# Source: test/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: group1
data:
  bar.properties: a=b
  foo.properties: c=d
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: group1
data:
  bar.properties: a=b
  foo.properties: c=d
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: group2
data:
  baz.properties: e=f
  qux.properties: g=h
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: group2
data:
  baz.properties: e=f
  qux.properties: g=h
  
---
```

Is there a simple way to accomplish this that I'm just missing?  Or is the ability to iterate through folders just missing from the set of helm template functions?  If so, would it make sense to add something like .Folders (vs .Files)?  Or make .Files more generic and create something like .Paths?  Thoughts?
