### ISSUE TITLE
Question: Helm multitenant support

### ISSUE THREAD

**Issue by roldancer** [helm/helm#4163]
Hi All, I would like to know if Helm support chart installation on different namespaces based on the client permission, we have several namespaces, each namespace has an admin user.

Any idea?

Thanks.

**Comment by PureWhiteWu** [comment]
You can install multi tillers, one per namespace.
That's the multitenant solution for me.

**Comment by SlickNik** [comment]
Hi @roldancer -- good question! Like @PureWhiteWu mentions above, one common way to achieve this is by installing a separate tiller for each namespace. The blog post at http://technosophos.com/2017/11/20/securing-helm.html (esp. point 4) talks a little about how to go about doing this.

Let us know if you have any further questions!

**Comment by PureWhiteWu** [comment]
@SlickNik Thank you for confirming this!

**Comment by roldancer** [comment]
Hi @SlickNik @PureWhiteWu I think that having a tiller for each namespace is ok for a cluster with few namespaces, but if you have 300 (my case) or more namespaces it would be much more efficient (memory usage) to have just one tiller for all the kubernetes cluster and that's from my point of view multitenant support.

Thanks.

**Comment by PureWhiteWu** [comment]
If you need 300 or more namespaces, then you must have 300 or more other services which all namespaces have. Tiller will only use a little memory, which is not  worth mentioning comparing with your other services.

**Comment by bacongobbler** [comment]
@roldancer the blog post @SlickNik linked to mentions how to do this, though it doesn't explicitly explain how to grant Tiller access to deploy to multiple namespaces. The blog post demonstrates how you can deploy Tiller to one namespace (`staging-tiller`) while managing resources in another namespace (`staging`), but you can add as many namespaces you wish Tiller can deploy to by granting multiple Roles and RoleBindings to the tiller service account.

[The RBAC documentation around deploying Tiller in one namespace, restricted to deploying resources in another namespace](https://docs.helm.sh/using_helm/#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-in-another-namespace) can be expanded by taking the example Role and RoleBindings and creating one Role and one RoleBinding for each namespace you want your tiller instance to deploy to, binding the RoleBinding to the service account Tiller is bound to.

It's a little clumsy, but hey, that's Kubernetes RBAC for ya ;)

Does that help answer your question?

**Comment by bacongobbler** [comment]
Here's an expanded example: deploying Tiller to `foo-system` with the ability to deploy resources in namespaces foo, bar, car and star:

```
$ kubectl create namespace foo-system
namespace "foo-system" created
$ kubectl create serviceaccount tiller --namespace foo-system
serviceaccount "tiller" created
```

Then, let's create the Roles and RoleBindings.

In `tiller-roles.yaml`:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: foo
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: bar
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: car
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: star
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
```

```
$ kubectl create -f tiller-roles.yaml
role "tiller-manager" created
role "tiller-manager" created
role "tiller-manager" created
role "tiller-manager" created
```

In `tiller-rolebindings.yaml`:

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: foo
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: foo-system
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: bar
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: foo-system
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: car
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: foo-system
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: star
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: foo-system
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
```

```
$ kubectl create -f tiller-rolebindings.yaml
rolebinding "tiller-binding" created
rolebinding "tiller-binding" created
rolebinding "tiller-binding" created
rolebinding "tiller-binding" created
```

Follow through the rest of https://docs.helm.sh/using_helm/#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-in-another-namespace as described in the docs.

Hope this helps!
