### ISSUE TITLE
Creating namespaces with custom labels

### ISSUE THREAD

**Issue by bgehman** [helm/helm#4178]
Is it possible to create a namespace, and add our own custom labels to that namespace?  We are in the process of migrating our JINJA based templates over to Helm and having issues...

YAML:
```
apiVersion: v1
kind: Namespace
metadata:
   name: {{ .Release.Namespace }}
   labels:
       app_name: core
```

Errors running `helm install`:
```
$ helm install --namespace core --name core core 
Error: release core failed: namespaces "core" already exists
```

Output of `helm version`:
```
$ helm version --short=true
Client: v2.9.1+g20adb27
Server: v2.9.1+g20adb27
```

Output of `kubectl version`:
```
$ kubectl version --short=true
Client Version: v1.9.6
Server Version: v1.9.6
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
docker-edge
