### ISSUE TITLE
Structure output of helm lint

### ISSUE THREAD

**Issue by AssafKatz3** [helm/helm#4205]
I would use helm lint as part of our build pipeline and reject in case of errors. Currently "helm lint" doesn't allow structure output (JSON, YAML) so it is problematic to integrate it with other systems. We are using Jenkins and [SonarQube ](https://www.sonarqube.org/) so integrate this feature to them is best.

The general idea is adding support of -o yaml option and instead get:

```
 == Linting chart-location
 [ERROR] Chart.yaml: unable to parse YAML
 	error converting YAML to JSON: yaml: line 2: found character that cannot start any token
 [ERROR] templates/: error converting YAML to JSON: yaml: line 2: found character that cannot start any token
``` 
The output will be:
```
chart: chart-location
errors:
  - file: Chart.yaml
    line: 2
    message: unable to parse YAML. error converting YAML to JSON: yaml: line 2: found character that cannot start any token
  - file: templates/
    line: 2
    message: error converting YAML to JSON: yaml: line 2: found character that cannot start any token
```
