### ISSUE TITLE
2 subcharts with different versions results in one not being rendered during dry-run/install

### ISSUE THREAD

**Issue by tldoty** [helm/helm#4310]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3+coreos.0", GitCommit:"f588569ed1bd4a6c986205dd0d7b04da4ab1a3b6", GitTreeState:"clean", BuildDate:"2018-02-10T01:42:55Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

I have a Chart with a requirements.yaml that looks like the following:

```
dependencies:  
  - name: chartA
    repository: "LOCAL-REPO"
    version: 1.0.0
  - name: chartB
    repository: "LOCAL-REPO"
    version: 2.0.0
    alias: "friendlyNameB"
  - name: chartB
    repository: "LOCAL-REPO"
    version: 1.0.0
    alias: "friendlyNameC"
```

I deploy chartB twice with different override configurations and also different versions of chartB.
In the output of my dry-run only one of the chartB templates get rendered. When they both use the same version then all templates render as expected. Is it expected to use the same version of subcharts of the same origin?
