### ISSUE TITLE
cannot overrride value with --set to string "false"

### ISSUE THREAD

**Issue by ghost** [helm/helm#4359]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Rancher 2.0.7 on baremetal

I have a configuration value that defaults to string `true` and i need it to be string `false`. Somehow this seems not to be possible via the `--set` option. Here is the minimal source of my chart:

mychart/templates/configmap.yml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
{{ toYaml .Values.environment | indent 2 }}
```

mychart/values.yml:
```
environment:
  foo: "true"
```
---
**Here is, what happens without overriding `foo`:**
```
#$ helm install --dry-run --debug mychart
...
# Source: mychart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: estranged-turtle-configmap
data:
  foo: "true"
```
*This is valid since the value `true` comes in quotes and is treated as string.*

**Here is, what happens when overriding `foo`**
```
helm install --dry-run --debug --set environment.foo=false mychart
# or helm install --dry-run --debug --set environment.foo='false' mychart
# or helm install --dry-run --debug --set environment.foo="false" mychart
...
# Source: mychart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-waterbuffalo-configmap
data:
  foo: false
```
*This is invalid because `false` is unquoted and is therefore treated as boolean.*

**Escaping the quotes does not work either:**
```
#$ helm install --dry-run --debug --set environment.foo=\"false\" mychart
...
# Source: mychart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: messy-indri-configmap
data:
  foo: '"false"'
```

**Expected of course is the following output:**
```
# Source: mychart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: messy-indri-configmap
data:
  foo: "false"
```

Any Ideas?
Thanks in advance.

**Comment by norbertbuchmueller** [comment]
You may want to use `--set-string environment.foo=false` instead.

**Comment by useltmann** [comment]
nope, same thing. Forgot to mention that.
```
#$ helm install --dry-run --debug --set-string environment.foo=false mychart
#helm install --dry-run --debug --set-string environment.foo="false" mychart
#helm install --dry-run --debug --set-string environment.foo='false' mychart
...
# Source: mychart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fun-jackal-configmap
data:
  foo: false
```

**Comment by norbertbuchmueller** [comment]
Well, i think the problem is that your shell removes the quotes (single or double) before the option is seen by Helm. Let's try this: `--set 'environment.foo="false"'`

**Comment by useltmann** [comment]
As said above, when I escape the quotes - which has the same effect - it leads to a quoted string with quotes. So no, this is not working either:
```
#$  helm install --dry-run --debug --set 'environment.foo="false"' mychart
#helm install --dry-run --debug --set-string 'environment.foo="false"' mychart
...
# Source: mychart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fallacious-worm-configmap
data:
  foo: '"false"'

**Comment by michelleN** [comment]
Hey @useltmann -- I was able to reproduce the issue you're seeing. Looks like this bug was fixed with #4142 so it is available in helm [v.2.10.0-rc.1](https://github.com/helm/helm/releases/tag/v2.10.0-rc.1) and will also be available in the next release.

I tested this on head and it works as you would expect:
```
helm [master]$ helm install -n test . --set-string environment.foo="false" --dry-run --debug
```
outputs:
```
# Source: mychart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  foo: "false"
```
