### ISSUE TITLE
non-deterministic ordering from "range" results in unnecessary deployments

### ISSUE THREAD

**Issue by Stono** [helm/helm#4375]
Hi, 
We have a template which iterates over a range of key value pairs and creates environment config for them.

```
{{- if $.Values.config }}
{{- range $key := keys $.Values.config }}
      - name: {{ $key }}
        valueFrom:
          configMapKeyRef:
            name: {{ $appName }}
            key: {{ $key }}
{{- end }}
{{- end }}
```

We noticed that we're getting rolling deployments of an app when nothing had actually changed.  Digging into diffs between the deployments, we noticed that the environment variables were ordered differently (resulting in a patch). 

```
102c102
<           - name: AT_CONFIDENTIAL_SEARCH_ONE_CLIENT_AUTH
---
>           - name: AT_CONFIDENTIAL_ATD_UK_PAF_PASSWORD
105c105
<                 key: AT_CONFIDENTIAL_SEARCH_ONE_CLIENT_AUTH
---
>                 key: AT_CONFIDENTIAL_ATD_UK_PAF_PASSWORD
107c107
<           - name: AT_CONFIDENTIAL_ATD_UK_PAF_PASSWORD
---
>           - name: AT_CONFIDENTIAL_SEARCH_ONE_CLIENT_AUTH
110c110
<                 key: AT_CONFIDENTIAL_ATD_UK_PAF_PASSWORD
---
>                 key: AT_CONFIDENTIAL_SEARCH_ONE_CLIENT_AUTH
```

So it feels like the `range` function doesn't iterate over items in the order in which they're loaded from `.Values.config`.

Is there anything that can be done about this?  Both short term fix (some way to order `range` by key name pershaps?) and also a longer term one?

**Comment by technosophos** [comment]
The recommended pattern is to use `keys` and `sortAlpha`, and then fetch each value by key. There's an example here: http://masterminds.github.io/sprig/dicts.html

**Comment by Stono** [comment]
Brilliant
Thanks Matt

**Comment by Hermsi1337** [comment]
Hey @Stono,

I'm facing the exact same problem. Did you fix yours by using `sortAlpha`?

My Template looks like this:

```yaml
{{- $keys := keys .Values.deployments | uniq | sortAlpha -}}

{{ range $keys }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ . }} || {{ $keys }}"
...

{{ end }}
```

My `values.yaml`:

```yaml
deployments:
  bar: {...}
  foo: {...}
```

When I run `helm template` it results in either one of the following...

... false:
```yaml
# Source: chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "foo || [bar foo]"
--
# Source: chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "bar || [bar foo]"
```
... correct:
```yaml
# Source: chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "bar || [bar foo]"
--
# Source: chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "foo || [bar foo]"
```

Helm version:
```shell
$ helm version
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

I can't figure out why the `range`-context seems to change on every `helm template`-run, while the `$keys`-list is always in the same - and correct - order.

Any help is greatly appreciated!

Regards,
