### ISSUE TITLE
How test two charts that are dependent on each other?

### ISSUE THREAD

**Issue by varun-da** [helm/helm#4377]
Output of `helm version`: {SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}

Hi,

I am developing two charts, Chart A and Chart B. Chart A is dependent on Chart B. Chart A was developed standalone, tested and uploaded to a repo. And now Chart B is being developed. To test, a requirement is added to Chart A, in the requirements.yaml:
```
dependencies:
  - name: B
    repository: file://../B
    version: 0.1.0
```

It all works fine locally. 

Now I need to test it on my build server, so I change the requirements.yaml for Chart A to:
```
dependencies:
  - name: B
    repository: https://repo_url/B
    version: 0.1.0
```

This obviously fails because Chart B does not exist on https://repo_url/B. But I cannot release until I can test it on the build server where the local `file://` directive would not work.

How do you test such dependencies? Has this problem already been solved? Is there a better or different way to do this?

Thanks!
