### ISSUE TITLE
Didn't apply ports to service

### ISSUE THREAD

**Issue by stamm** [helm/helm#4382]
I have already deployed service with port 80, and want to update ports in that service

```
# Source: re-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      name: http
    - port: 8002
      protocol: TCP
      name: debug
    - port: 82
      protocol: TCP
      name: grpc
```

But service didn't get new ports:
```
==> v1/Service
NAME                          TYPE       CLUSTER-IP   EXTERNAL-IP  PORT(S)  AGE
service  ClusterIP  10.20.69.35  <none>       80/TCP   2h
```

When I deleted release with `helm delete --purge service` I install and service gets new ports

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
kServer: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): baremetal
