### ISSUE TITLE
Importing Child Values via requirements.yaml doesn't work with aliases

### ISSUE THREAD

**Issue by alebabai** [helm/helm#4391]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
 **Minikube**
If dependency has an alias that differ form dependency chart name then "Importing Child Values" seems not work.
Example:
```yaml
  - name: postgresql
    version: 0.15.0
    repository: 'https://kubernetes-charts.storage.googleapis.com/'
    condition: global.pg1.enabled
  - name: postgresql
    alias: pg2
    version: 0.15.0
    repository: 'https://kubernetes-charts.storage.googleapis.com/'
    condition: global.pg2.enabled
    import-values:
      - child: service
        parent: global.pg2.service
```

So `.Values.global.pg1.service` will have values, but `.Values.global.pg2.service` will be `null`.
