### ISSUE TITLE
Helm repo index file not manage properly build info (metadata) on version

### ISSUE THREAD

**Issue by sebglon** [helm/helm#4404]
Output of `helm version`:
2.9.1

I want to push my chart on my private GCS repository.
for that i use nouney/helm-gcs plugin. but but on your code, it use helm lib to generate index file and chek if chart version already exist.

When i push my first version with metadata, all is good.
But when i push second build, it fail because index.has(version) return true because semver compare not chek metadata.

the index.has fuction not chek metadata and index is not properly updated.
I have only the first version with the metadata but not the new build.

 nouney/helm-gcs#11

**Comment by sebglon** [comment]
this is the index file:
```
apiVersion: v1
entries:
  pim:
  - created: "2018-07-31T11:35:29.837482073+02:00"
    description: Akeneo PIM package
    digest: 483d7301883e28a25cd3bd56d74ae8528887f3cfa516828e002ef731d8f87ad3
    icon: https://raw.githubusercontent.com/akeneo/pim-community-dev/2.3/web/favicon.ico
    name: pim
    urls:
    - gs://akeneo-charts-dev/pim-0.2.0-alpah1-pr-6+0022.tgz
    version: 0.2.0-alpah1-pr-6+0022
generated: "2018-07-31T09:30:07.327790654+02:00"
```
And if i want to push hel chart version `0.2.0-alpah1-pr-6+0023`, it upload file but not update indnex and fail with message 
```
helm gcs push ./pim-0.2.0-alpha1-pr-6+0033.tgz akeneo-charts-dev
Error: chart pim-0.2.0-alpha1-pr-6+0033 already indexed. Use --force to still upload the chart

```

Result of helm search:
```
helm search /pim -l
NAME                  	CHART VERSION         	APP VERSION	DESCRIPTION                                       
akeneo-charts-dev/pim 	0.2.0-alpah1-pr-6+0022	           	Akeneo PIM package                                
local/pim             	0.2.0-alpha1-pr-6+0033	           	Akeneo PIM package                                
local/pim             	0.2.0-alpha1-pr-6+0009	           	Akeneo PIM package                                
local/pim             	0.2.0-alpha1-pr-6+0010	           	Akeneo PIM package                                
local/pim             	0.2.0-alpah1-pr-6+0022	           	Akeneo PIM package                                
```
