### ISSUE TITLE
Jobs don't deleted with CronJob

### ISSUE THREAD

**Issue by janosroden** [helm/helm#4417]
If I delete a CronJob with helm then the related jobs and pods aren't deleted.
However if I install with helm and delete with kubectl everything works fine.

## How to reproudce

1. `helm create cronjob-test`
1. `rm cronjob-test/templates/{NOTES.txt,*.yaml}`
1. Add cronjob.yaml (see below)
1. `helm install -n cronjob-test cronjob-test`
1. Wait ~1 min for the first job and check if the created job has the correct metadata.ownerReferences: `kubectl get job -l app=cronjob-test -w -o yaml`
1. `helm delete cronjob-test --purge`
1. The cronjob has deleted, but the job still exists (without ownerReferences)
1. Delete jobs manually: `kubectl delete job -l app=cronjob-test`
1. Install the chart again
1. Wait for a job again
1. Delete the cronjob with kubectl: `kubectl delete cronjob cronjob-test`
1. Jobs deleted
1. `helm delete cronjob-test --purge`

### cronjob.yaml

```
cat << 'EOF' > cronjob-test/templates/cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "cronjob-test.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "cronjob-test.fullname" . }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
EOF
```

---
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-06-24T01:54:00Z", GoVersion:"go1.9", Compiler:"gc", Platform:"linux/amd64"}
```

Output of `oc version`:
```
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://blacksalt.cloud:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OpenShift
