### ISSUE TITLE
Feature request: tiller doesn't recognise `auth-provider` from kubeconfig

### ISSUE THREAD

**Issue by rimusz** [helm/helm#4422]
Output of `helm version`: v2.9.1

Output of `kubectl version`: v1.10.5

Cloud Provider/Platform: GKE/EKS/AKS

Running `tiller` off-cluster it doesn't recognise in `kubeconfig` the `auth-provider` from the user section, it spits the error `Cannot initialize Kubernetes connection: No Auth Provider found for name "gcp"`, attached the `kubeconfig` part example below:

```
...
users:
- name: gke_xxxxxx_cluster-1
  user:
    auth-provider:
      config:
        access-token: xxxxxxxxxxxxxxxx
        cmd-args: config config-helper --format=json
        cmd-path: /google/google-cloud-sdk/bin/gcloud
        expiry: 2018-08-02T12:34:04Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
