### ISSUE TITLE
Helm does not handle resource removal if namespace was changed

### ISSUE THREAD

**Issue by r7vme** [helm/helm#4424]
I have tiny chart that creates two "services" (can be any other resource). I'm moving one service to other namespace and expect that Helm will delete old one.

Unfortunately, when service moved between namespaces Helm can not handle deletion of old resource, but when i rename resource within same namespaces i see that helm successfully deletes old resource.

Steps to reproduce:
- create chart with `svc.yaml` below
- install with `helm upgrade --install x-chart x-chart`
- change namespace of first servcice in `svc.yaml` from `kube-system` to `default`
- upgrade chart with `helm upgrade --install x-chart x-chart`

`svc.yaml`
```
kind: Service
apiVersion: v1
metadata:
  name: my-service1
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: my-service2
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

Actual result:
first service still exists in namespace `kube-system`

Expected result:
first service deleted from namespace `kube-system`

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS
