### ISSUE TITLE
Why should I have dependencies under charts/

### ISSUE THREAD

**Issue by gkarthiks** [helm/helm#4432]
When I am specifying the `dependency chart name`, `version` and `repo` (the mandatory details to identify and download a chart) details in the `requirements.yaml` why should I have to add the `tgz` charts in the `charts\` folder. Why not helm read that `requirements.yaml` file and do the magic on the fly.

```yaml
dependencies:
- name: grafana
  version: 1.12.0
  repository: https://kubernetes-charts.storage.googleapis.com/
```
