### ISSUE TITLE
Incompatible types during `--set` operation

### ISSUE THREAD

**Issue by exu** [helm/helm#4450]
I have problem when setting chart values by `--set` 

My YAML file
```
apiVersion: v1
kind: Service
metadata:
  name: {{ template "example-go-service.fullname" . }}
  labels:
    example: go-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ template "example-go-service.fullname" . }}
      prefix: /go/
      service: {{ template "example-go-service.fullname" . }}
      variable_type: {{ .Values.canary.weight | printf "%T"}}
      {{ if gt .Values.canary.weight 0.0 }}weight: {{ .Values.canary.weight }}{{ end }}
```

it looks like Helm | go-template treat values starting from `0` as strings eihter floats are not converted correctly.

```
❯ helm upgrade --namespace api --set image.tag=v1 --set canary.weight=0.0000001 go-v1 . --debug --dry-run        
[debug] Created tunnel using local port: '46839'

[debug] SERVER: "127.0.0.1:46839"

Error: UPGRADE FAILED: render error in "example-go-service/templates/service.yml": template: example-go-service/templates/service.yml:16:12: executing "example-go-service/templates/service.yml" at <gt .Values.canary.we...>: error calling gt: incompatible types for comparison
                                          
```

When line with comparison is removed type of variable looks like following:

- setting to float starting from `0`
```
❯ helm upgrade --namespace api --set image.tag=v1 --set canary.weight=0.0000001 go-v1 . --debug --dry-run | grep variable
      variable_type: string
```

- setting to int starting from `0`
```
❯ helm upgrade --namespace api --set image.tag=v1 --set canary.weight=0 go-v1 . --debug --dry-run | grep variable                                       
      variable_type: string
```
- Setting to value >= 1
```
❯ helm upgrade --namespace api --set image.tag=v1 --set canary.weight=10 go-v1 . --debug --dry-run | grep variable                                      
      variable_type: float64
                                 
```

- Setting to valid float doesn't work too: 
```
❯ helm upgrade --namespace api --set image.tag=v1 --set canary.weight=99.00 go-v1 . --debug --dry-run | grep variable                                       
      variable_type: string                
```

- Setting to string: 
```
helm upgrade --namespace api --set image.tag=v1 --set canary.weight=\"10\" go-v1 . --debug --dry-run | grep variable                                       
      variable_type: string
```

If value is going from YAML file it's ok: 

```
helm upgrade --namespace api --set image.tag=v1 go-v1 . --debug --dry-run | grep variable                                        
      variable_type: float64
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.2-gke.1", GitCommit:"75d2af854b1df023c7ce10a8795b85d3dd1f8d37", GitTreeState:"clean", BuildDate:"2018-05-10T17:23:18Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE
