### ISSUE TITLE
How to assign k8s apiserver ip and port manually when using helm install

### ISSUE THREAD

**Issue by Beyyes** [helm/helm#4498]
I created a k8s cluster, and the content of ```kubectl config view``` is as below.
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://10.190.148.73:8080
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
  name: kubernetes
current-context: kubernetes
kind: Config
preferences: {}
users: []
```

After I installing Tiller using ```helm init``` (helm pod was installed on a slave node in k8s cluster),
If I execute the command ```helm install xxx```, it has the error
 ```
Error: Get http://localhost:8080/version: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```

If I execute the command ```sudo helm install xxx```, it has the error
```
Error: Get https://10.190.148.73:6443/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: x509: certificate signed by unknown authority
```
I just wonder could I assign the k8s apiserver ip and port(http://10.190.148.73:8080, not https) when using ```helm install```? 

Output of `helm version`: 
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:21:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
