### ISSUE TITLE
Build umbrella chart with exact dependency helm chart version in requirements.yaml file

### ISSUE THREAD

**Issue by rgaduput** [helm/helm#4516]
In umbrella chart ```requirements.yaml``` dependencies chart details are added with version, repository.
When we specify exact chart version in ```requirements.yaml```, sometimes it fails to find that chart in Nexus helm repo, though it actually exists.    
After some investigation found that, seems it looks for the version in ```index.yaml``` of that nexus repo, if required version is not same as like the one in ```index.yaml``` file it fails.
```index.yaml``` contains latest version always, but what if we want to work with different version than latest one ? how can we fix this ?
Below is the snippet of requirements.yaml file

```
dependencies:
  - name: ms1
    version: "1.3.0"
    repository: http://user:passwd@nexus_host:8081/repository/helm_chart_repo/ms1
  - name: ms2
    version: "1.3.0"
    repository: http://user:passwd@nexus_host:8081/repository/helm_chart_repo/ms2
  - name: ms3
    version: "1.2.0"
    repository: http://user:passwd@nexus_host:8081/repository/helm_chart_repo/ms3
  - name: ms4
    version: "1.3.1"
    repository: http://user:passwd@nexus_host:8081/repository/helm_chart_repo/ms4
```
