### ISSUE TITLE
health checks get removed

### ISSUE THREAD

**Issue by magick93** [helm/helm#4519]
Hello

I'm trying to deploy Apache Ignite using Helm, and I am adding to the deployment.yaml file some health checks. Should be very straight forward.

If there is a formatting error in the yaml then helm complains, and rightfully so. However, I am not getting any validation errors in this case.

**Problem**
When I run `helm install .  --devel --name ignite` ignite is deployed, however the health checks mysteriously never show.

I have also tried `helm install --name my-release stable/dokuwiki` and these health checks do remain. And I have based my healthchecks on this example.

**Deployment.yaml**

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "ignite.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ignite.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ignite.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-serviceaccount
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OPTION_LIBS
              value: ignite-kubernetes,ignite-rest-http
            - name: IGNITE_QUIET
              value: "false"
            - name: CONFIG_URI
              value: {{ .Values.configPath }}
          livenessProbe:
          httpGet:
            path: /ignite?cmd=version
            port: {{ .Values.service.restSecondPort }} # REST port number.
          initialDelaySeconds: 30
          timeoutSeconds: 10
          ports:
          # Ports to open.
          # Might be optional depending on your Kubernetes environment.
          - name: http
            containerPort: {{ .Values.service.restSecondPort }} # REST port number.
            hostPort: {{ .Values.service.restSecondPort }}
          - containerPort: {{ .Values.service.communicationSpiPort }} # communication SPI port number.
            hostPort: {{ .Values.service.communicationSpiPort }}
          - containerPort: {{ .Values.service.discoverySpiPort }} # discovery SPI port number.
            hostPort: {{ .Values.service.discoverySpiPort }}
          - containerPort: {{ .Values.service.jmxPort }} # JMX port number.
            hostPort: {{ .Values.service.jmxPort }}
          - name: rest
            containerPort: {{ .Values.service.restport }} # Rest Port
            hostPort: {{ .Values.service.restport }}
          - name: thinclients
            containerPort: {{ .Values.service.thinclientsport }} # Thin client port
            hostPort: {{ .Values.service.thinclientsport }}
      #    {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /ignite?cmd=version
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        #  {{- end }}
        #  {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /ignite?cmd=version
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        #  {{- end }}
#      nodeSelector:
#        ignite: "true"
```

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Baremetal
