### ISSUE TITLE
the POST made to /apis/security.openshift.io/v1/securitycontextconstraints is spelled wrong

### ISSUE THREAD

**Issue by ryanrf** [helm/helm#4533]
Using OpenShift Origin 3.9

Output of `helm version`:
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-04-11T20:47:54Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-04-11T20:47:54Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

OpenShift Origin 3.9 (running on AWS)

I'm trying to create a chart that uses some templates to build a new SCC (security context constraint) in openshift. When I attempt to install the chart I keep getting the error:
`Error: release <release name> failed: the server could not find the requested resource`

I added the `-logtostderr` and `-v 8` to the tiller server to get some verbose logs. I then went through the HTTP requests very carefully and came accross:
```

I0824 23:39:36.201924       1 round_trippers.go:383] POST https://172.30.0.1:443/apis/security.openshift.io/v1/securitycontextconstraintses
--
  | I0824 23:39:36.201940       1 round_trippers.go:390] Request Headers:
  | I0824 23:39:36.201945       1 round_trippers.go:393]     Content-Type: application/json
  | I0824 23:39:36.201955       1 round_trippers.go:393]     Accept: application/json
  | I0824 23:39:36.201965       1 round_trippers.go:393]     User-Agent: tiller/v0.0.0 (linux/amd64) kubernetes/$Format
```

That extra 'es' at the end of securitycontextconstraintses is causing a 404, which is resulting in the resource not being found. I have confirmed I can POST to the correct URL if I manually create the request with curl (using the same Authorization token). I'm not so great with Golang so I had a hard time seeing how the request was being built and how that extra 'es' ended up there. I've attempted this on at least two different openshift origin 3.9 clusters.

I should add that I can successfully create the scc using the `oc create` command or the `kubectl create` command (I need to set `--validate=false`). I used the templates that were generated using `helm install --debug --dry-run`.

Please let me know if I can provide any further information.

**Comment by jascott1** [comment]
Hi @ryanrf 

As far as I can tell, there is no openshift specific code in Helm/Tiller. I suspect this is not something that Tiller is causing but Im not sure.  Does your chart use this api in its charts, `securitycontextconstraints`? Perhaps there is a typo in one of the manifests in the chart?

**Comment by Schnitzel** [comment]
I got the same issue, I did some more testing:

`test.yaml`:
```yaml
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: null
allowedFlexVolumes: null
apiVersion: v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  name: nonroot2
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:gitlab-develop:default
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
```

with `oc apply` it POST to:
```
https://console-govcms.amazeeio.hosting:443/api/v1/securitycontextconstraints
```

with `kubectl apply` it POST to:
```
POST https://console-govcms.amazeeio.hosting:443/api/v1/securitycontextconstraintses
```

looks like others also found that issue before:
https://github.com/NetApp/trident/blob/master/cli/k8s_client/k8s_client.go#L1224-L1231

seems to me a bug of openshift used together with kubectl?

**Comment by jascott1** [comment]
Thanks @Schnitzel 

@ryanrf Do you concur that this is a bug with kubectl? If so we should follow that issue and close this one.

**Comment by bacongobbler** [comment]
👋 hey @Schnitzel!

So if I'm understanding the issue correctly:

- helm uses the kubectl client APIs to interact with kubernetes
- there is a bug in kubernetes' client APIs that don't work with security context constraints (SCCs)
- therefore, using `helm install` on a chart that installs SCCs causes this bug.

Does that seem right? If so then perhaps the best place to follow up would be upstream, but it does sound like a bug which occurs in Helm as well given that we use kubectl client APIs.

**Comment by ryanrf** [comment]
@Schnitzel Thanks for testing. I thought this might have to do with openshift's API or kubectl, so it wouldn't surprise me if that's the case. But my testing is still showing some inconsistent results between helm and kubectl. I've enabled an audit log in my openshift environment. If I use `helm install test/` I see the POST is attempting to hit `/apis/security.openshift.io/v1/securitycontextconstraintses`, if I use `helm template . | kubectl apply -f - --validate=false` see it hitting `/apis/security.openshift.io/v1/securitycontextconstraints/scc-test1` (the name of my scc is scc-test1), and the scc is successfully created.

So while it would make much more sense, especially considering there is already an issue open that references this issue, I'm getting some different results. @jascott1, I can't agree at this point that it's a bug with `kubectl`. 

I should also add that when I tried using `kubectl apply -f test_scc.yaml` with @Schnitzel's yaml manifest I was able to successfully apply the scc. Here's the helm template I've been using:
```
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-test1
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users: []
groups: []
```
