### ISSUE TITLE
Helm documentation advises secured installation, but provides no working examples

### ISSUE THREAD

**Issue by bert-laverman** [helm/helm#4537]
I have been spending a lot of time setting up a "simple" Kubernetes cluster in Google Cloud, installing Helm, and then getting a (helm supported, pretty much default) installation of SonarQube working behind a (helm supported, pretty much default) NGINX Ingress controller.

The documentation states in section "Installing Helm", second paragraph, that it is strongly recommended to run a secured installation of Helm. However, following the proffered information I have not been able to get it to work. Google was a dubious friend, as it provides many inconsistent and incomplete examples.

1. It is advised to create a service-account for the tiller, with no further details. Simply creating the account will get you a service-account in the default namespace, which the Tiller installation subsequently will be unable to find. Simply having the service account is not enough, as it also needs RoleBindings. I have found several GitHub issues about this, but no definitive example of the "minimal working" situation.

    1. One example created a Role as follows:
      ```
        kind: Role
        apiVersion: rbac.authorization.k8s.io/v1beta1
        metadata:
          name: tiller-manager
          namespace: tiller-namespace
       rules:
       - apiGroups: ["", "batch", "extensions", "apps"]
         resources: ["*"]
         verbs: ["*"]
      ```
    2. Other examples left out the namespace, added the "rbac.authorization.k8s.io" group. While wrestling with "one tiller per namespace" I finally followed yet another example, which simply added the "cluster-admin" role.

2. Going for the "one tiller per namespace", installing SonarQube went right, but installing the Ingress controller gave me a non-working service due to missing rights. I suppose this isn't meant to say the tiller's right weren't sufficient, because of the cluster-admin? So rather the charts for the Ingress controller had something. The Ingress controller docs however presume no Helm.

3. So far the only working scenario was the basic "one tiller in kube-system, no special service-account", but with TLS.

PS
I have been hunting and trying so many different approaches, that I simply delete the cluster and start re-creating everything from scratch. I have everything in scripts now, but the first working environment only as a running system. (before I started recording my attempts in scripts) If some kind soul wants to help and you need specific error details, let me know which scenario you want followed, and I'll set up a GitHub project containing scripts and logs. If that scenario solves everything at the first try, then let's make sure the Helm documentation is just as detailed. I have no background in Go, limited Kubernetes, lots of (medium) Linux and advanced Java.
