### ISSUE TITLE
helm create -> ingress template + values files should be slightly different

### ISSUE THREAD

**Issue by naseemkullah** [helm/helm#4556]
ingress paths should be a list in the values file like this:

```
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
``` 

and then in the ingress template something like this:

```
{{- $ingressPaths := .Values.ingress.paths -}}
...
...
.
.
.
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        {{- range $ingressPaths }}
          - path: {{ . | quote }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
        {{- end }}
  {{- end }}
```

notice i added an 's'
