### ISSUE TITLE
Ingress yaml file malformed

### ISSUE THREAD

**Issue by nlamirault** [helm/helm#4557]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

I create an `ingress` template like that : 

```yaml
# Copyright (C) Foo Bar

# FOO
# BAR
# Copyright

{{- $name := include "atmosdb.name" . -}}
{{- $ingressPath := .Values.ingress.path -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: atmosdb
  labels:
    k8s-app: atmos
    component: backend
    app: {{ include "atmosdb.name" . }}
    chart: {{ include "atmosdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $name }}
              servicePort: http
  {{- end }}
```

ouput : 

```yaml
# Source: atmosdb/templates/ingress.yaml
# Copyright (C) Foo Bar

# FOO
# BAR
# CopyrightapiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: atmosdb
  labels:
    k8s-app: atmos
    component: backend
    app: atmosdb
    chart: atmosdb-1.9.0-rc0
    release: 1.9.0-rc0
    heritage: Tiller
spec:
  tls:
    - hosts:
        - "api.atmos.minikube"
      secretName: wildcard-atmos
  rules:
    - host: "api.atmos.minikube"
      http:
        paths:
          - path: /
            backend:
              serviceName: atmosdb
              servicePort: http
```

`apiVersion` line in on the same line as the comment.

I've got this error with install command : 
```
Error: validation failed: unable to recognize "": no matches for kind "Ingress" in version ""
```

To fix that i must write like that : 

```yaml
# Copyright (C) Foo Bar

# FOO
# BAR
# Copyright

{{- $name := include "atmosdb.name" . -}}
{{- $ingressPath := .Values.ingress.path -}}

{{/* COMMENT */}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: atmosdb
  labels:
    k8s-app: atmos
    component: backend
    app: {{ include "atmosdb.name" . }}
    chart: {{ include "atmosdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $name }}
              servicePort: http
  {{- end }}
```

Then output could be interpreted : 

```yaml
# Source: atmosdb/templates/ingress.yaml
# Copyright (C) Foo Bar

# FOO
# BAR
# Copyright

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: atmosdb
  labels:
    k8s-app: atmos
    component: backend
    app: atmosdb
    chart: atmosdb-1.9.0-rc0
    release: 1.9.0-rc0
    heritage: Tiller
spec:
  tls:
    - hosts:
        - "api.atmos.minikube"
      secretName: wildcard-atmos
  rules:
    - host: "api.atmos.minikube"
      http:
        paths:
          - path: /
            backend:
              serviceName: atmosdb
              servicePort: http

```
