### ISSUE TITLE
Add an option to pass tags to subcharts

### ISSUE THREAD

**Issue by ovk** [helm/helm#4563]
Currently `.Values.tags` only available in the parent charts and inaccessible from subcharts. However, in some cases it may be very useful to pass `tags` to subcharts, so that they could use information about enabled tags to do proper configuration.

**Comment by durera** [comment]
We would also like this very much.  We ended up adding a step in our pipeline that takes all tags and generates a `tags-global.yaml` file that is passed in as another `--values` argument so that we can use tags both in requirements.yaml and in templates to control conditional behaviours.  It would be great to not have to do this and just be able to treat tags as `.Tags.x` or somesuch.

`requirement.yaml` - subchart1 only installs if featureToggle = true, subchart2 always installs, but `SOME_ENV_VAR` is only defined if featureToggle is true (because the secret we need to set that env var doesn't exist unless featureToggle is true)
```
- name: subchart1
  ..
  tags:
    - featureToggle
- name: subchart2
  ...
```

`deployment.yaml` from subchart2 - only adds `SOME_ENV_VAR` if `featureToggle` is true
```
           {{ if (.Values.global.tags.featureToggle) }}
           - name: SOME_ENV_VAR
             valueFrom:
               secretKeyRef:
                 key:  myKey
                 name: mySecret
           {{ end }} 
```
