### ISSUE TITLE
Helm upgrade only the specific dependent chart

### ISSUE THREAD

**Issue by anannaya** [helm/helm#4575]
I have umbrella chart 
nkcscf/
├── charts
│   ├── coredisp-18.5.0-PI.2.IT.2-3.tgz
│   ├── gmdisp-18.5.0-PI.2.IT.2-3.tgz
│   ├── icscf-18.5.0-PI.2.IT.2-3.tgz
│   ├── mastericm-18.5.0-PI.2.IT.2-3.tgz
│   ├── pcscf-18.5.0-PI.2.IT.2-3.tgz
│   └── scscf-18.5.0-PI.2.IT.2-3.tgz
├── Chart.yaml
├── example-values.yaml
├── LICENSE
├── OWNERS
├── README.md
├── requirements.lock
├── requirements.yaml
├── templates
│   ├── _helpers.tpl
│   └── pvc.yaml
└── values.yaml

Part of values.yaml file.
{{
scscf:
 ```
 required: true  
  global:
    scscf_image:
      name: scscf
      tag: NODB
icscf:
  required: true  
  global:
    icscf_image:
      name: icscf
      tag: NODB
```

I want to upgrade only one specific chart by changing the image. I have changed the image in values.yaml and tried $helm upgrade nkcscf nkcscf/  it didnt upgrade ? Is there way to upgrade the only the specific helm chart?

In each charts i have multiple containers, 1 container is common across all the dependent charts. Is there any way i can upgrade only the specific chart by with the latest common container image??
