### ISSUE TITLE
Changing Docker image in Helm Chart doesn't actually change the image used in the deployment

### ISSUE THREAD

**Issue by Neekoy** [helm/helm#4586]
Heya,

I believe the following is a bug, however I might be missing something. I've edited a chart and it doesn't change the Docker image it's using, even though I've changed it in the values.yaml. I have the following:

requirements.yaml:

```
- name: myapp-server
  version: "~4.0.6"
  repository: "file://../myapp-server/"
```

Old values yaml:
../myapp-server/values.yaml
```
image:
  repository: 226617721124.dkr.ecr.eu-west-1.amazonaws.com
  name: myapp-server
  tag: this-image-is-pulled-always
  pullPolicy: Always
```

New values.yaml:
../myapp-server/values.yaml
```
image:
  repository: 226617721124.dkr.ecr.eu-west-1.amazonaws.com
  name: myapp-server
  tag: this-is-not-getting-pulled
  pullPolicy: Always
```
I've changed the values.yaml from the former to the latter, then deleted the `charts` folder, and `requirements.lock`, then I updated the dependencies with `helm dep up`.

I confirmed that after updating the dependencies the chart in the main folder in `charts` contains the correct Docker conatainer tag.

Even then, when I run `helm install .` I get a deployment with the `this-image-is-pulled-always` and not the updated one.

Can someone please confirm if I'm missing something, or I've encountered a bug?

Cheers,
Hristian

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS EC2 (not AKS)
