### ISSUE TITLE
Helm "package" command removes a zero at the start of "version" string.

### ISSUE THREAD

**Issue by KIVagant** [helm/helm#4594]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
localhost
```

Hello. I use Helm for several environments and for development environment I usually build helm charts with the `version` value equal to a short git hash. I found that if the git hash contains a zero at the start of the string. For example:

```
apiVersion: v1
name: abcdef
description: A test
version: 0439268
maintainers:
  - name: Someone
    email: something@here.com
keywords:
  - project
home: https://github.com/
sources:
  - https://github.com/helm/helm/
icon: https://www.somethinghere.com/favicon.ico
tillerVersion: ">=2.9.1"
```

```
helm package helm/abcdef/ -d helm/packages/
Successfully packaged chart and saved it to: helm/packages/abcdef-439268.tgz
```

As you can see, the zero is removed from the version string.

**Comment by bacongobbler** [comment]
Helm follows semantic versioning, so version specifiers are taken as integer values so it makes sense that the leading zero was stripped out by the parser.

From https://semver.org/#spec-item-2:

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

I'm not sure that we can reasonably support non-integer values in Helm 2 as that goes against the semver spec. @mattfarina any opinions here?

**Comment by mattfarina** [comment]
@KIVagant SemVer has a methodology for dev releases using pre-releases. For example, `1.2.3-dev.1`. Automation can even increment the number in the pre-release. Doing it this way you can tell where the dev versions call relative to the releases. Note, this is the intent in SemVer for handling these cases rather than my opinions on versioning.

**Comment by KIVagant** [comment]
@mattfarina, that's a good advice, thank you.

**Comment by bacongobbler** [comment]
I'm going to close this but please let me know if there's something I missed and we need to re-open this.

**Comment by kivagant-ba** [comment]
@bacongobbler , @mattfarina , it's been a while since I opened this issue but now I'm working with Helm again and I have absolutely the same issue and, unfortunately, your advices can't help me. :(


```
---
apiVersion: v1
name: bla
description: bla
# Do NOT set the version manually. Jenkins will do this for you for each build.
version: 0.0.1-3196cc4.1
maintainers:
  - name: bla/blabla
    email: bla@bla.bla
keywords:
  - bla
home: https://bla.bla/
sources:
  - https://github.com/bla/bla
icon: https://bla.bla/favicon.ico
tillerVersion: ">=2.12"
```

```
CHART_VERSION=0.0.1-3196cc4.1
helm package --app-version=${CHART_VERSION} helm/bla -d helm/packages/
helm lint helm/packages/bla-${CHART_VERSION}.tgz

Successfully packaged chart and saved it to: helm/packages/bla-0.0.1-3196cc4.1.tgz
==> Skipping helm/packages/bla-0.0.1-3196cc4.1.tgz
No chart found for linting (missing Chart.yaml)

Error: 0 chart(s) linted, 1 chart(s) failed

```
