### ISSUE TITLE
Specify values file in requirements.yaml

### ISSUE THREAD

**Issue by 2ZZ** [helm/helm#4606]
Feature Request

In requirements.yaml it would be very useful to be able to override the name of the values file used from within a dependent chart. In this way multiple different environment configs can be stored cleanly within a chart without having to resort to using the pluck function to pull out the appropriate values from a shared values.yaml file. 

*Example requirements.yaml*
```
dependencies:
  - name: mytestchart
    version: 1.2.3
    repository: http://example.com/charts
    values: production.yaml
```
*Example chart*
```
mytestchart/
├── Chart.yaml
├── production.yaml
├── staging.yaml
└── templates
```
