### ISSUE TITLE
helm delete removes more then it should remove

### ISSUE THREAD

**Issue by yhaskell** [helm/helm#4615]
### Intro

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-18T14:14:00Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS, Minikube

### Description

I created a very simple chart `failing`. It contains one template of a configmap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configName }}
  labels:
    release: {{ .Release.Name }}
spec:
  data:
    config: whatever
```

My `values.yaml` file consits of one line:
```yaml
configName: fail
``` 

Then I deploy it two times using this commands:
```
$ helm install -n failing-1 charts/failing/
NAME:   failing-1
LAST DEPLOYED: Mon Sep 10 13:12:13 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME  DATA  AGE
fail  0     0s

$ helm install -n failing-2 charts/failing/
Error: release failing-2 failed: configmaps "fail" already exists
$
```

Which is expected.

Then I remove my failed release `failing-2`.

```
$ helm delete --purge failing-2
release "failing-2" deleted
$
```

### Expectations
I expect release to be removed, and my configmap to stay (since it belongs to `failing-1`).

### Results

Release is removed, and configmap is also removed.

**Comment by kylehodgetts** [comment]
The config map isn't going to stay because it takes the config map name "fail" and deletes it from the kubernetes API. 

Chart releases are discrete, in the sense that they should not affect one another so Helm not going to differentiate between a resource belonging to one release or the next when it's removing them

If you want it to stick around prepend the release name to the config map name or something. Like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{.Values.configName }}
  labels:
    release: {{ .Release.Name }}
spec:
  data:
    config: whatever
```
