### ISSUE TITLE
Feature Request: List Helm releases filtered by labels

### ISSUE THREAD

**Issue by mumoshu** [helm/helm#4639]
I'd want to label "helm releases" to efficiently retrieve only part of helm releases.

To achieve that, I'm imagining at least one enhancement to `helm list`. That is to accept `--selector key1=val1` or `-l key1=val1` like `kubectl get RESOURCE -l key1=val1` does. `helm list -l key1=val` shows helm releases that matches the selector. In this case it means those labeled `key1: val1` onto their underlying configmaps(or secrets) that tiller created to store the releases info.

## Initial U/X

Today what tiller creates for a helm release named `httpserver` looks like this:

```
  kind: ConfigMap
  metadata:
    creationTimestamp: 2018-09-09T05:44:08Z
    labels:
      MODIFIED_AT: "1536471850"
      NAME: httpserver
      OWNER: TILLER
      STATUS: DEPLOYED
      VERSION: "1"
    name: httpserver.v1
```

You can label the configmap by:

```
kubectl label configmap httpserver.v1 tier=web
```

So that, with the new `-l` flag added to `helm list`, I can list only `web` related releases:

```
helm list -l tier=web
```

### How release labels are implemented in release configmaps/escrets

Note that I intentionally opted to not add a UPPSER_CASE prefixes to labels.

Instead of the below:

```
  kind: ConfigMap
  metadata:
    creationTimestamp: 2018-09-09T05:44:08Z
    labels:
      MODIFIED_AT: "1536471850"
      NAME: httpserver
      OWNER: TILLER
      STATUS: DEPLOYED
      VERSION: "1"
      RELEASE_LABEL_tier: web
    name: httpserver.v1
```

I would see:

```
  kind: ConfigMap
  metadata:
    creationTimestamp: 2018-09-09T05:44:08Z
    labels:
      MODIFIED_AT: "1536471850"
      NAME: httpserver
      OWNER: TILLER
      STATUS: DEPLOYED
      VERSION: "1"
      tier: web
    name: httpserver.v1
```

So that we can use the same infrastructure to implement features like https://github.com/helm/helm/issues/4143#issuecomment-393226417 (cc/ @rcorre). That is, `helm helm ls --namespace MYNS` becomes equivalent to `helm list -l NAMESPACE=MYNS`.

## Future Works

Personally I'm ok with also implementing ways to add labels to the release at installation time. `helm install mycharts/httpserver -l tier=web`, and `helm upgrade --install mycharts/httpserver -l tier=web`.

For feature parity with kubernetes labels, `helm label RELEASE K=V` would also make sense.

Also, `kubectl label` allows you to remove labels by using `-` suffix, e.g. `kubectl label configmap NAME K-`. If we get to implement the `helm label` command, it would be nice to also add support for removing label.

However, I intentionally leave these as future works for now, to make the scope of this feature request minimum, and ease implementing the MVP.

**Comment by michelleN** [comment]
Hey @mumoshu - Thanks for this proposal. This looks like a useful feature and it's not the first time I've heard this request (cc/ @mikelorant. At the moment, we are not accepting any major features for Helm v2. I am adding the v3 label to this so that we can consider it for helm v3.

**Comment by Jancis** [comment]
+1 on this. Release name is limited to specific amount of chars and it really does not describe anything. We need a way to add metainfo based on labels so that we can select releases using some specific selectors. I'd also love to see something like "description" or "comment" for the release that woud make entries in `helm ls` listing more descriptive.

**Comment by mikemowgli** [comment]
We badly need this as well. Has this been considered for Helm v3?

**Comment by hickeyma** [comment]
@mikemowgli I don't think anyone is working on this. 

@mumoshu Have you had time to do any work on the proposal?

**Comment by TBeijen** [comment]
While we're at it, wouldn't annotations be a good addition as well? Not sure if it would warrant opening a separate issue.

I'm thinking of use cases like dev/feature deploys that can be cleaned up after a certain period. So an annotation like `uninstall-after: <some-date>` could be very useful.

**Comment by keriksson-rosenqvist** [comment]
Is anyone able to actually use this in their releases and filtering with `helm list -l key=value`?
I currently have a release with the following configmap and when using the -l flag I get no results at all.
```
apiVersion: v1
data:
  TEST_1: "1"
  TEST_2: two
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    name: test-config
    namespace: test
```
I've tried the following commands but neither finds any results.
```
$ helm list -l "app.kubernetes.io/managed-by=Helm" -n test
$ helm list -l app.kubernetes.io/managed-by=Helm -n test
$ helm list -l "app.kubernetes.io/managed-by==Helm" -n test
$ helm list -l app.kubernetes.io/managed-by==Helm -n test
```
What am I doing wrong?
