### ISSUE TITLE
install dependency twice with different values

### ISSUE THREAD

**Issue by benmathews** [helm/helm#4646]
I'd like to make an umbrella chart that involves multiple installations of a dependency with different values. Currently, this isn't supported. I'd envision modifying `requirements.yaml` to something like this.

```
dependencies:
- name: vanillaicecream
  chart: icecream
  version: "1.2.3"
  repository: "@stable"
- name: chocolateicecream
  chart: icecream
  version: "1.2.3"
  repository: "@stable"
```

Then the `values.yaml` being passed in could include:

```
vanillaicecream:
  flavor: vanilla
chocolateicecream:
  flavor: chocolate
```

Does this seem reasonable?
