### ISSUE TITLE
yaml ancho problem

### ISSUE THREAD

**Issue by zlcnju** [helm/helm#4669]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
Output of `kubectl version`:
```Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-22T05:40:33Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

my yaml ancho use like this:
```
dashboard:
  image:
    dashboard:
      registry: *registry
  
registry: 
  address: &registry A.com
```
 when i execute:
       helm install --set registry.address=B.com
I expect this:
```
dashboard:
  image:
    dashboard:
      registry: B.com
  
registry: 
  address: B.com
```

but it actually this:

```
dashboard:
  image:
    dashboard:
      registry: A.com
  
registry: 
  address: B.com
```
