### ISSUE TITLE
"Forbidden: updates to statefulset spec [...] are forbidden" when chart version changed

### ISSUE THREAD

**Issue by michaelkunzmann-sap** [helm/helm#4695]
We are using Helm programmatically (not from the command line) and we are seeing weird issues when we upgrade a Helm release. We are using our own Helm chart.

```
rpc error: code = Unknown desc = StatefulSet.apps "pcdtl-0" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

We could isolate that the issue occurs when we increase the chart version of our own chart from ```0.4.0``` to ```0.5.1```.  **It works if we do not change the version number.**

Apart from that, we are not doing any changes to the ```StatefulSet``` at all. We are only updating the value of a certain field in a secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keystore
  labels:
    app: {{ template "mychart.name" . }}
    chart: {{ template "mychart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  key: {{ .Values.key | b64enc }}
```
Here, we change the line ```  key: {{ .Values.key | b64enc }}``` to ```  key: {{ .Values.key }}```.

This is how we call Helm:
```
...
# chartValuesYAML contains the full values yaml, not just the overrides
helmClient.UpdateReleaseFromChart(
		releaseName,
		chart,
		helm.ReuseValues(false),
		helm.UpgradeRecreate(true),
		helm.UpdateValueOverrides(chartValuesYAML),
```

Our Gopkg.lock:
```
...
[[projects]]
  name = "k8s.io/helm"
  packages = [
    "pkg/chartutil",
    "pkg/downloader",
    "pkg/getter",
    "pkg/helm",
    "pkg/helm/environment",
    "pkg/helm/helmpath",
    "pkg/helm/portforwarder",
    "pkg/ignore",
    "pkg/kube",
    "pkg/plugin",
    "pkg/proto/hapi/chart",
    "pkg/proto/hapi/release",
    "pkg/proto/hapi/services",
    "pkg/proto/hapi/version",
    "pkg/provenance",
    "pkg/repo",
    "pkg/resolver",
    "pkg/sympath",
    "pkg/tlsutil",
    "pkg/urlutil",
    "pkg/version"
  ]
  revision = "20adb27c7c5868466912eebdf6664e7390ebe710"
  version = "v2.9.1"
...
```

**Comment by bacongobbler** [comment]
That error looks like it's coming from kubernetes' API server which is indicating that a change has occurred between the last apply and the current one. I'd try with `helm upgrade` using v2.9.1 in isolation and see if you can reproduce it without the custom program you're writing. Can you try that and see if you can reproduce it there first? That way we can nail it down to one of two things:

- it's something originating from the chart itself
- it's something originating from the usage of the helm client packages

Thanks!

**Comment by michaelkunzmann-sap** [comment]
Yes, I have the same issue with the command line client:
```
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
$ helm upgrade -f newvalues.yaml pcdtl-0 . --debug
[debug] Created tunnel using local port: '39390'

[debug] SERVER: "127.0.0.1:39390"

Error: UPGRADE FAILED: StatefulSet.apps "pcdtl-0" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' areforbidden.
```

**Comment by michaelkunzmann-sap** [comment]
I found the issue. In my ```_helpers.tpl``` I had the following code:
```
{{- define "mychart.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```
And in my statefulset:
```
...
metadata:
  name: {{ .Release.Name }}
  labels:
    ...
    chart: {{ template "scp-bc-qaas-quorum-chart.chart" . }}
```
This resulted my statefulset to be changed when the chart version changed. Any implications for changing the ```chart``` field to
```
   chart: {{ template "scp-bc-qaas-quorum-chart.name" . }}
```
?

**Comment by Simon3** [comment]
See https://github.com/helm/charts/issues/7803 ?

**Comment by luisdavim** [comment]
I'm having the same issue when trying to modify `spec.template.spec.containers[].resources` and according to the error message:
```
is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```
It should be allowed.

**Comment by Simon3** [comment]
Please read helm/charts/issues/7803. 
If the problem comes from a label in volumeClaimTemplate being updated because because of the chart version, it is indeed not normal and the chart needs to be fixed. Most of helm/charts have already been fixed, the last one being incubator/cassandra a few days ago by myself (note: you still need to delete the statefulset one last time and then you will be able to upgrade the subsequent times). If the problem comes from a field mutating on purpose, then it is probably normal, by design.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by dnozay** [comment]
what we have in the file `some-service/templates/statefulset.yaml`
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: some-service
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
...
```

vs what the output of helm template:
```
# Source: some-service/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: some-service
    chart: some-service-0.452.0
    heritage: Helm
    release: my-release
...
```

I'm facing this problem trying to migrate from helm 2 / upgrade the release because it tries to add
a `chart` label everywhere which is not allowed in `StatefulSet`.
