### ISSUE TITLE
Install Role Error: unable to recognize "": no matches for kind "Role" in version ""

### ISSUE THREAD

**Issue by mitchellmaler** [helm/helm#4776]
Trying to install a Role using Helm and I keep getting the error ```unable to recognize "": no matches for kind "Role" in version ""```. I can apply the Role manually but ushing helm it won't.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"g
c", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"
gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Openstack

The tiller logs with the error is:
```
[tiller] 2018/10/15 01:01:10 failed install perform step: unable to recognize "": no matches for kind "Role" in version ""
```

The Template is:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: leader-election
rules:
- apiGroups:
  - "" # "" indicates the core API group
  resources:
    - endpoints
  # only giving access to these operations on the resource objects
  verbs:
    - get
    - create
    - update
```
