### ISSUE TITLE
How to avoid translate some `{{` of the charts?

### ISSUE THREAD

**Issue by cheyang** [helm/helm#4789]
Output of `helm version`:
v2.9.1
Output of `kubectl version`:
v1.11.2
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Baremetal

I want to put the following CRD into helm chart, but it contains go raw template. How to make helm not translate `{{` and `}}` inside `rawTemplate`. Thanks for your response.
https://github.com/kubeflow/katib/blob/master/examples/random-example.yaml

```
apiVersion: "kubeflow.org/v1alpha1"
kind: StudyJob
metadata:
  namespace: katib
  labels:
    controller-tools.k8s.io: "1.0"
  name: random-example
spec:
  studyName: random-example
  owner: crd
  optimizationtype: maximize
  objectivevaluename: Validation-accuracy
  optimizationgoal: 0.99
  requestcount: 4
  metricsnames:
    - accuracy
  parameterconfigs:
    - name: --lr
      parametertype: double
      feasible:
        min: "0.01"
        max: "0.03"
    - name: --num-layers
      parametertype: int
      feasible:
        min: "2"
        max: "5"
    - name: --optimizer
      parametertype: categorical
      feasible:
        list:
        - sgd
        - adam
        - ftrl
  workerSpec:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.WorkerId}}
            namespace: katib
          spec:
            template:
              spec:
                containers:
                - name: {{.WorkerId}}
                  image: katib/mxnet-mnist-example
                  command:
                  - "python"
                  - "/mxnet/example/image-classification/train_mnist.py"
                  - "--batch-size=64"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never
  suggestionSpec:
    suggestionAlgorithm: "random"
    requestNumber: 3
```
