### ISSUE TITLE
Feature request: .env file parsing

### ISSUE THREAD

**Issue by ReDev1L** [helm/helm#4796]
Hello, i would like to propose a feature, that generates secrets.yaml, based on current environment (with prefix filter, i.e. "HELM_ENV_") or .env file.

Currently i'm using "workaround" - dumping needed env vars with "printenv > .env" then using following function in template:
https://github.com/ReDev1L/helm-env-file-parsing
Function does following:
```
KEY_ENV1=VAL_ENV1           KEY_ENV1: base64(VAL_ENV1)
KEY_ENV2=VAL_ENV2       =>  KEY_ENV2: base64(VAL_ENV2)
KEY_ENV3="${VAL_ENV3}"      KEY_ENV3: base64("${VAL_ENV3}")
```
Environment secret yaml template:
```
apiVersion: v1
kind: Secret
metadata:
  name: php-fpm-{{ .Values.environment }}-env
  labels:
    environment: {{ .Values.environment }}
type: Opaque
data:
{{ tuple . "configs/backend/php-fpm/.env" | include "env.parseFile" | indent 2}}
```
