### ISSUE TITLE
Substitute variables in file content

### ISSUE THREAD

**Issue by mmhelm** [helm/helm#4797]
Is there a convenient way to substitute all variables in a file when loading its file content?

For instance I have the following property files which contain property values referencing variables defined in `values.yaml`.
File: `files/app.properties`
```ini
app.property1={{ .Values.app.prop1 }}
app.property2={{ .Values.app.prop2 }}
```
File: `files/db.properties`
```ini
db.property={{ .Values.db.prop }}
```
Values: `values.yaml`
```yaml
app:
  prop1: value1
  prop2: value2

db:
  prop: value1
```

When defining the `ConfigMap` the variables should get resolved and the files should contain the values defined in `values.yaml`.
ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
...
data:
{{ (.Files.Glob "files/**").AsConfig | indent 2 }}
```

Output:
```yaml
...
data:
  "app.properties": "app.property1=value1\napp.property2=value2"
  "db.properties": "db.property=value1"
```
