### ISSUE TITLE
maxSurge: 1 prevents fixing deployment where there's extra pod in CrashLoopBackOff state from previous failed deploy

### ISSUE THREAD

**Issue by sheerun** [helm/helm#4811]
I think I'm finally able to reproduce this issue. I also think **it's not kubernetes issue** but helm's one as I'm able to manually edit deployment (change image) with kubectl and everything works.

How to reproduce:

1. Create helm deployment with following strategy on deployment:

```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
```

2. Set livecheck on deployed service:

```
        readinessProbe:
          initialDelaySeconds: 1
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 5
          tcpSocket:
            port: {{ $d.service.internalPort }}
        livenessProbe:
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 15
          initialDelaySeconds: 15
          tcpSocket:
            port: {{ $d.service.internalPort }}
```

3. Deploy correct service with helm
4. Change image to broken one (eg. docker tag `broken` that crashes during startup)
5. Newly deployed image enters crashed loop while healthy one still works and is serving:

```
kubectl get pods --namespace blog
NAME                    READY     STATUS             RESTARTS   AGE
blog-5978979fd-j7zgl    0/1       CrashLoopBackOff   1          20s
blog-7f6f977d7d-5nm6h   1/1       Running            0          4
```

6. Change image back to working one (e.g. `latest`)
7. Notice how healthy release is not deploying (probably because it's waiting for crashing one to be ready which will never happen

Now if you change maxSurge to 2 everything is deployed correcly because new service can start while bad one is crashing.

### Solution?

- Make `maxSurge` ignore pods in  CrashLoopBackOff status.
- ???

### Info

Output of `helm version`:

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:53Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AKS
