### ISSUE TITLE
helm create --starter does not replace <CHARTNAME> in requirements.yaml.

### ISSUE THREAD

**Issue by blindworld** [helm/helm#4813]
Our requirements.yaml file has a conditional dependency scoped to the chartname, so our requirements.yaml looks like:

```
dependencies:
  - name: nginx-ingress
    version: ~0.29
    repository: '@stable'
    condition: <CHARTNAME>.standalone
```

run `helm create demo --starter my-starter`

expected output:
```
dependencies:
  - name: nginx-ingress
    version: ~0.29
    repository: '@stable'
    condition: demo.standalone
```

actual output:
```
dependencies:
  - name: nginx-ingress
    version: ~0.29
    repository: '@stable'
    condition: <CHARTNAME>.standalone
```

We are using this method as a workaround for this issue: https://github.com/helm/helm/issues/4490

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
