### ISSUE TITLE
Question: HELM Consul custom value uiIngress hosts issue

### ISSUE THREAD

**Issue by vadimAnte** [helm/helm#4817]
Hello,

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-eks", GitCommit:"58c199a59046dbf0a13a387d3491a39213be53df", GitTreeState:"clean", BuildDate:"2018-09-21T21:00:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS EKS

My objective is setup Consul with AWS internal Load Balancer.

I have custom value.yaml file:

```yaml
Domain: consul.<my_environment>.localz
Replicas: 2
ImageTag: "1.3.0"
DatacenterName: <my_environment>
StorageClass: "gp2"
uiService:
  enabled: true
  type: "LoadBalancer"
uiIngress:
  enabled: true
  annotations: {
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0,
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"}
  hosts: [
    consul.<my_environment>.localz
      http:
      paths:
      - path: /
        backend:
          serviceName: consul-ui
          servicePort: http]
  tls: {}
```

Command `helm install --name consul --values charts/stable/consul/values.yaml --values ../3-consul/consul-value-${ENV_NAME}.yaml charts/stable/consul` returns:
```bash
Error: failed to parse ../3-consul/consul-value-<my_environment>.yaml: error converting YAML to JSON: yaml: line 15: did not find expected ',' or ']'
```
Help or right direction advice would be highly appreciated.

**Comment by vadimAnte** [comment]
```  hosts: [
    consul.<my_environment>.localz]
```
will allow create consul, but with external, instead of internal AWS LB.

**Comment by bacongobbler** [comment]
YAML lists use the syntax

```
this:
  - is
  - a
  - list
```

So the correct form would be

```
hosts:
    - consul.<my_environment>.localz:
      http:
      paths:
      - path: /
        backend:
          serviceName: consul-ui
          servicePort: http
```

Try that and see what happens.

Ansible has some pretty great docs on YAML basics:  https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html#yaml-basics
