### ISSUE TITLE
tiller and PSP: container has runAsNonRoot and image has non-numeric user (nobody), cannot verify user is non-root

### ISSUE THREAD

**Issue by mszumilak** [helm/helm#4818]
kubectl version: 1.11.3
helm version: 2.11.0

With k8s version 1.11 pod security policy mechanism has been introduced.

Due to `USER NOBODY` in Dockerfile (https://github.com/helm/helm/blob/master/rootfs/Dockerfile) after `helm init` I'm getting for tiller pod:
`kubectl -n mytestnamespace describe pod | grep Events -A 20`
```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  18s               default-scheduler  Successfully assigned mytestnamespace/tiller-deploy-74bdf5fc67-4626p to node3
  Normal   Pulled     5s (x3 over 18s)  kubelet, node3     Container image "gcr.io/kubernetes-helm/tiller:v2.11.0" already present on machine
  Warning  Failed     5s (x3 over 18s)  kubelet, node3     Error: container has runAsNonRoot and image has non-numeric user (nobody), cannot verify user is non-root
```

It works properly when particular PSP is defined however I do not like:
- "RunAsAny"
- "privileged: true"
- "allowPrivilegeEscalation: true"
- "allowedCapabilities"

The whole, minimal perm policy here:

`kubectl get psp tiller -o yaml`:
```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: tiller
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - CAP_SETUID
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
```

**Comment by bacongobbler** [comment]
Sorry, I'm not quite sure what the ask is here in this ticket. Would you please mind explaining in more detail what the issue is, and how you suggest we might fix that?

**Comment by mszumilak** [comment]
I have no idea if I should classify this as bug report or feature request. I believe it's more like bug report as of release notes 2.11.0 supports k8s 1.11 and PSP is a part of this version.

You may want to consider using `USER <uid>`  instead of `USER NOBODY` or supply proper Pod Security Policy along with the service user and role that allows to use that PSP.

**Comment by mszumilak** [comment]
Please specify UID instead of "NOBODY"

According to: [https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups](url):

> Requires that the pod be submitted with a non-zero runAsUser or have the USER directive defined (using a numeric UID) in the image.

In this case this is definitely a bug, not question.

**Comment by davidkarlsen** [comment]
I can confirm that adding a proper securityContext makes it pass:
``` 
      dnsPolicy: ClusterFirst
      nodeSelector:
        fs.evry.com/finods-group: aot
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: <-- 
        runAsUser: 65534 <--
      serviceAccount: tiller
      serviceAccountName: tiller
      terminationGracePeriodSeconds: 30
```
