### ISSUE TITLE
Can helm chart requirements have templated overrides?

### ISSUE THREAD

**Issue by mhamilton723** [helm/helm#4822]
More specifically I am trying to understand if I could do the following:

Chart A Values.yaml:
```
foo: "here"
```
Chart B requirements.yaml:
```
dependencies:
  - name: a
    repository: ...
    version: ...
```
Chart B values.yaml (or somewhere in the parent chart):
```
a.foo = "{{.Values.someKeyFromB}} nontrivial template text {{.Values.someOtherKeyFromB}}"
```

Basically I would like to do something like overriding a field with something more complex. Thanks in advance!
