### ISSUE TITLE
problem to get value from env params 

### ISSUE THREAD

**Issue by zyriuse75** [helm/helm#4832]
hy folks 
currently i've a problem when i try to deploy my helm _deployment.yaml_  file . When i run the command 
`kubectl get deployment --namespace ds-svc-cas -o yaml ` after executed helm i dont see the value of my env ???
on the other hand if i execute the same file but kubectl format everything work perfectly !
Did i forget something or it's a bug because i search on internet and read a lot of things and i didn't find anything weird .

**deployment.yaml -o yaml  ( helm ) ** 
```
 template:
    metadata:
      labels:
        app: {{ .Values.containers.name }}
    spec: 
      containers:
      - name: {{ .Values.containers.name }} 
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.image.ports.https }}
        - containerPort: {{ .Values.image.ports.ssh }}
        env:
        - name: JAVA_APP_CONFIGS
          values: "/apps/ds-cas-webapp/context"
        volumeMounts:
        - mountPath: {{ .Values.volumeMounts.path }}
          name: {{ .Values.volumeMounts.mountName }}
      volumes:
        - name: {{ .Values.volumeMounts.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name }}

```

**deployment.yaml -o yaml (kubernetes file )**
```
    app: ds-mg-cas
  template:
    metadata:
      labels:
        app: ds-cas
#        app: ds-mg-cas
        env: beta
    spec:
      containers:
      - name: ds-cas
#      - name: ds-mg-cas
        image: docker-all.xxxxx.net/library/ds-mg-cas:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        - containerPort: 6402
        env:
        - name: JAVA_APP_CONFIGS
          value: "/apps/ds-cas-webapp/context"
        - name: JAVA_EXTRA_PARAMS
          value: "-Djava.security.auth.login.config=./config/jaas.config -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6402"

        volumeMounts:
        - name: ds-cas-vol
          mountPath: "/apps/ds-cas-webapp/context"
      volumes:
        - name: ds-cas-vol
          persistentVolumeClaim:
            claimName: ds-cas-pvc

```

**Output of `helm version`:**
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Output of `kubectl version`:**
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
