### ISSUE TITLE
wrong name given on deployment.yaml during the install  ??

### ISSUE THREAD

**Issue by zyriuse75** [helm/helm#4835]
hy folks 

firstly i hope i'm not on the wrong place to ask this question .
when i run the command to install my helm chart everything doing good . but when i look the description i've 
 
> helm install cas/ --name=ds-cas-de  --namespace=ds-svc-cas --tls
```
 
 RESOURCES:
 ==> v1/Service
 NAME     TYPE       CLUSTER-IP  EXTERNAL-IP  PORT(S)   AGE
 svc-cas  ClusterIP  192.2.0.94  <none>       8443/TCP  26s
 
 ==> v1beta1/Deployment
 NAME            DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
 deployment-cas  1        1        1           0          26s
 mistral-api     1        1        1           0          26s

```
i set the name **mistral-api** on my  `deployment.yaml` but i still have **deployment-cas** . It was the first given name. I dont understand how it get it and where it found this params (**deployment-cas**) .
Before to run the install command i executed 

`helm del --purge ds-cas-de --tls
`
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
#  name: {{ .Values.containers.name }}
  name: mistral-api
  labels:
    app:
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.containers.name }}
  template:

```

Does the problem come from **helm** or from **kubernetes** ?  or from the chi.. on my computer lol...
Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
