### ISSUE TITLE
Helm is not deleting CRDs

### ISSUE THREAD

**Issue by gintautassulskus** [helm/helm#4840]
I installed a [cert-manager chart](https://hub.kubeapps.com/charts/stable/cert-manager). The chart comes with several CRDs. Then, I deleted the chart but the CRDs were not cleaned up. Subsequent attempts to install cert-manager chart are now failing because of the lingering CRDs.

Output of `helm version`: v2.11.0

Output of `kubectl version`: v1.12.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  minikube

**Comment by mattfarina** [comment]
As a short term fix you can use `kubectl` to delete the CRDs. For example, you can list CRDs with the command `kubectl get crds` and you can delete one with `kubectl delete crd [NAME]`.

I'm going to dig into this a little more. We either need to better document this or fix a bug.

**Comment by mortent** [comment]
I think this is closely related to this issue: #4697
The limitations (and caveats) of using the crd-install hook is pretty well described in the initial PR #3982, but I think the documentation could be improved.

**Comment by gintautassulskus** [comment]
Thanks, @mattfarina, this is what I am doing at the moment. Although it complicates automation code.

Also, I feel the following issue is somewhat related. An attempt to add a custom cert-manager's esource `ClusterIssuer` gives:
```
Error: unable to decode "": no kind "ClusterIssuer" is registered for version "certmanager.k8s.io/v1alpha1"
```

with the culprit being `cert-manager/templates/custom-crd.yaml`:

```yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: acme-issuer
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  acme:
    # The ACME server URL
    server: "server"
    # Email address used for ACME registration
    email: "email"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: acme-issuer
    # Enable the HTTP-01 challenge provider
    http01: {}
```

Steps to reproduce:
```
git clone https://github.com/gintautassulskus/charts /tmp/cert-manager-crd-issue
cd /tmp/cert-manager-crd-issue
git checkout cert-manager-crd-issue
helm dependency update stable/cert-manager/
helm package stable/cert-manager/
helm install stable/cert-manager/
```
