### ISSUE TITLE
How to copy files as part of post-upgrade/post-install hook ?

### ISSUE THREAD

**Issue by gautammoulik** [helm/helm#4875]
To start with this is most likely not a bug.  This is more of a verification if I am doing correctly. 
I have to replace a .NET application's config file (app.config) with my custom config file before we start the pod. I am copying my custom config file using the config-maps and it works fine, my custom config file gets copied into a custom directory named "config".
Now, in order to copy this file into the bin folder of the application I am taking help of the PostInstall and PostUpgrade hook. 
I am following this documentation for my hook implementation,  https://github.com/helm/helm/blob/master/docs/charts_hooks.md and this is how my command is to copy and replace the config into the bin folder  
```
spec:
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.azure.containerRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/cp","/config/customapp.exe.config","/customapp/Content/"]
```
Here, the customapp.exe.config file need to be copied and placed into the /customapp/Content/ folder.
I don't see it is copying the file.
How to check the helm release logs to see what it did with the PostInstall/PostUprgade hook. 

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:59:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

_Edited to add code blocks for readability_
