### ISSUE TITLE
YAML merge (<<) should allow deep merge

### ISSUE THREAD

**Issue by yann-soubeyrand** [helm/helm#4914]
Hi,

When doing a YAML merge (<<), the merge which is done isn't a deep merge, which makes this operation really less interesting.

Example input:
```
common:
  &common
  main1: "main1"
  main2: "main2"
  main3:
    sub1: "sub1"
    sub2: "sub2"

specific1:
  <<: *common
  main1: "overriden main1"
  main3:
    sub1: "overriden sub1"
```
Example output:
```
specific1:
  main1: "overriden main1"
  main2: "main2"
  main3:
    sub1: "overriden sub1"
```
Expected output:
```
specific1:
  main1: "overriden main1"
  main2: "main2"
  main3:
    sub1: "overriden sub1"
    sub2: "sub2"
```

In my opinion, deep merge would greatly improve the usability of this operator (<<).

Output of `helm version`:

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS
