### ISSUE TITLE
Helm does not render mountOptions: in deployment which should throw an error

### ISSUE THREAD

**Issue by ajfriesen** [helm/helm#4926]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS with rancher

# Problem description

We are using a helm chart which uses a direct nfs mount without persistentVolumes and persistentVolumeClaim.

We add "mountOptions:" to the template and helm does not throw an error when parsing this.
It somehow skips these entrys and generates a valid deployment.

## deployment with mountOptions:

```
...yaml
      volumes:
        - name: installation-volume
          nfs:
            server: {{ .Values.[URL-TO-NFS-SERVER]}}
            path: {{ .Values.nfsPath}}{{ .Release.Name | lower }}
            readOnly: true
            {{- include "nfs_mount_options" .| indent 12 }}
```

## _helpers.tpl with the mountOptions:

```
{{/*
Mount options.
*/}}
{{- define "nfs_mount_options" }}
mountOptions:
  - async
  - nfsvers=4
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
  - retrans=2
  - noresvport
{{- end }}
```

## Rendered output from helm

```
...
      volumes:
      - name: installation-volume
        nfs:
          path: /
          server: [URL-TO-NFS-SERVER]
```

# Expected behaviour

Helm should warn like kubectl that deployments do not have mountOptions:

## deployment-direct-nfs-mount.yaml

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        env:
        image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx-deployment
        ports:
        volumeMounts:
        - mountPath: /nfs
          name: installation-volume
      volumes:
      - name: installation-volume
        nfs:
          server: [URL-TO-NFS-SERVER]
          path: /
          readOnly: true
          mountOptions:
            - ro
            - async
            - nfsvers=4.1
            - rsize=1048576
            - wsize=1048576
            - hard
            - timeo=600
            - retrans=2
            - noresvport
            - acdirmin=1
            - acdirmax=1

```

## error from kubectl

```
kubectl apply -f deployment-direct-mount.yaml
error: error validating "deployment-direct-mount.yaml": error validating data: ValidationError(Deployment.spec.template.spec.volumes[0].nfs): unknown field "mountOptions" in io.k8s.api.core.v1.NFSVolumeSource; if you choose to ignore these errors, turn validation off with --validate=false
```
