### ISSUE TITLE
Does sha256Sum change when the values are rendered?

### ISSUE THREAD

**Issue by Omnipresent** [helm/helm#4988]
This is in reference to the trick mentioned here: https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change

Would the `sha256sum` of `configmap.yaml` change if it is picking up values from `values.yaml` which are being changed from `--set` option in helm CLI?

Below is a detailed scenario:

**configmap.yaml**
```
    ---
    apiVersion: V2.23
    kind: ConfigMap
    metadata:
       name: my-configmap
    data: 
       image.tag: {{ .Values.image.tag }}
```

**deployment.yaml**
```
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```

**values.yaml**

```
    image:
      repository: myrepo
      tag: latest
      pullPolicy: IfNotPresent
```

**Jenkinsfile**

```
            sh """
              helm upgrade --install --force \
              --namespace=default \
              --values=values.yaml \
              --set image.tag=${output_of_git-describe} \
              --set image.pullPolicy=Always \
              myimage kubernetes/myimage
           """
```

Will the `sha256sum` of `configmap.yaml` change since I am passing `--set image.tag` value from the command line?
