### ISSUE TITLE
Rendering error when using range function along with --set

### ISSUE THREAD

**Issue by chobolt** [helm/helm#5094]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Bare Metal

When using range to loop over env values, rendering will fail if I'm overriding values with --set as seen below.

`more values.yaml`
```
image:
  repository: alpine
  tag: latest
  pullPolicy: IfNotPresent

env:
- name: a
  value: 1
- name: b
  value: 2
- name: c
  value: 3
```

`more template.yaml`
```
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}

      env:
      {{- range .Values.env }}
      - name: {{ .name }}
        value: {{ .value | quote }}
      {{- end }}
```

`helm install --dry-run --debug .`
```
[debug] Created tunnel using local port: '35057'

[debug] SERVER: "127.0.0.1:35057"

[debug] Original chart version: ""
[debug] CHART PATH: /root/chart-dwcel_edl/chart-ticket

NAME:   killjoy-deer
REVISION: 1
RELEASED: Fri Dec 21 16:34:15 2018
CHART: dwcel_edl-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
env:
- name: a
  value: 1
- name: b
  value: 2
- name: c
  value: 3
image:
  pullPolicy: IfNotPresent
  repository: alpine
  tag: latest
replicaCount: 1

HOOKS:
MANIFEST:

---
# Source: dwcel_edl/templates/template.yaml
apiVersion: v1
kind: Pod
metadata:
  name: killjoy-deer-dwcel_edl
spec:
  containers:
    - name: dwcel_edl
      image: "alpine:latest"
      imagePullPolicy: IfNotPresent

      env:
      - name: a
        value: "1"
      - name: b
        value: "2"
      - name: c
        value: "3"
```

`helm install --dry-run --debug --set env.a="0" .`
```
[debug] Created tunnel using local port: '33575'

[debug] SERVER: "127.0.0.1:33575"

[debug] Original chart version: ""
[debug] CHART PATH: /root/chart-dwcel_edl/chart-ticket

Error: render error in "dwcel_edl/templates/template.yaml": template: dwcel_edl/templates/template.yaml:13:17: executing "dwcel_edl/templates/template.yaml" at <.name>: can't evaluate field name in type interface {}
```
