### ISSUE TITLE
Helm job is blocked hook job even it completed.

### ISSUE THREAD

**Issue by cropse** [helm/helm#5098]
Output of `helm version`:
> Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
> Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.4-gke.12", GitCommit:"d48a38d6599484b4b98c39d1c584a3662a67d486", GitTreeState:"clean", BuildDate:"2018-12-07T00:26:53Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

The issue for me is the job with the `cloudsql-proxy` as the sidecar mode to access database with the hook setting.
```yaml
# my-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
....
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",........
```
so the pod with sql-proxy container, and the job is completed and exited:
> NAME                                 READY     STATUS      RESTARTS   AGE
my-job-pgq7j                      1/2       Completed   0          1d

and running `helm upgrade`, and new job is completed, but helm is blocked until it timeout
> Error: UPGRADE FAILED: timed out waiting for the condition
The terminal process terminated with exit code: 1
> my-job-9n2rn                      1/2       Completed     0          26s
my-job-pgq7j                      0/2       Terminating   0          1d

I try to remove the hook, and it work fine.
