### ISSUE TITLE
Nested sub charts values

### ISSUE THREAD

**Issue by jamborta** [helm/helm#5135]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS (KOPS)

I have added a dependency to my charts as follows:

```
dependencies:
  - name: prometheus-operator
    version: 1.5.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: prometheus.enabled
```

prometheus-operator has its own dependencies (https://github.com/helm/charts/blob/master/stable/prometheus-operator/requirements.yaml), which I assume should be able to disable like this in my values.yaml:

```
prometheus-operator:
  nodeExporter:
    enabled: false
```

This does have some effect, that it is picked up in the prometheus-operator templates, but it does not disable the actual dependency. I need to add this to turn off the templates and disable the dependency:

```
nodeExporter:
  enabled: false
prometheus-operator:
  nodeExporter:
    enabled: false
```

Is this expected behaviour?

**Comment by pavdmyt** [comment]
Having similar issue.

I'm having `my-chart` with `prometheus-operator` as a dependency:

```
$ cat requirements.yaml
dependencies:

  - name: prometheus-operator
    version: 1.5.2
    repository: https://kubernetes-charts.storage.googleapis.com/
```

and following `values.yaml`:

```
## Configuration for prometheus-operator subchart
##
prometheus-operator:
  ## Using default values from https://github.com/helm/charts/blob/master/stable/grafana/values.yaml
  ##
  grafana:
    enabled: false
```

If I'm doing `$ helm install ./my-chart --namespace monitoring`, grafana resources get created and I see them among the pods:

```
NAME:   ornery-koala
LAST DEPLOYED: Wed Jan  9 17:00:13 2019
NAMESPACE: monitoring
STATUS: DEPLOYED

RESOURCES:
==> v1/Prometheus
NAME                                   AGE
ornery-koala-prometheus-op-prometheus  3s

==> v1/PrometheusRule
ornery-koala-prometheus-op                  3s
ornery-koala-prometheus-op-kube-etcd-rules  3s

==> v1/ConfigMap
ornery-koala-grafana-config-dashboards  3s
ornery-koala-grafana                    3s
ornery-koala-prometheus-efk-tests       3s

==> v1/ServiceAccount
ornery-koala-grafana                   3s
ornery-koala-kube-state-metrics        3s
ornery-koala-prometheus-node-exporter  3s
ornery-koala-prometheus-op-operator    3s
ornery-koala-prometheus-op-prometheus  3s

==> v1/ClusterRole
ornery-koala-grafana-clusterrole           3s
ornery-koala-prometheus-op-operator        3s
ornery-koala-prometheus-op-operator-psp    3s
ornery-koala-prometheus-op-prometheus      3s
ornery-koala-prometheus-op-prometheus-psp  3s

==> v1/ClusterRoleBinding
ornery-koala-grafana-clusterrolebinding    3s
ornery-koala-prometheus-op-operator        3s
ornery-koala-prometheus-op-operator-psp    3s
ornery-koala-prometheus-op-prometheus      3s
ornery-koala-prometheus-op-prometheus-psp  3s

==> v1beta1/Role
ornery-koala-grafana  3s

==> v1/Service
ornery-koala-grafana                                3s
ornery-koala-kube-state-metrics                     3s
ornery-koala-prometheus-node-exporter               3s
ornery-koala-prometheus-op-coredns                  3s
ornery-koala-prometheus-op-kube-controller-manager  3s
ornery-koala-prometheus-op-kube-etcd                3s
ornery-koala-prometheus-op-kube-scheduler           3s
ornery-koala-prometheus-op-operator                 3s
ornery-koala-prometheus-op-prometheus               3s

==> v1beta1/ClusterRoleBinding
ornery-koala-kube-state-metrics            3s
psp-ornery-koala-prometheus-node-exporter  3s

==> v1/Role
ornery-koala-prometheus-op-prometheus-config  3s
ornery-koala-prometheus-op-prometheus         3s
ornery-koala-prometheus-op-prometheus         2s

==> v1beta1/DaemonSet
ornery-koala-prometheus-node-exporter  3s

==> v1/ServiceMonitor
ornery-koala-prometheus-op-coredns                  2s
ornery-koala-prometheus-op-apiserver                2s
ornery-koala-prometheus-op-kube-controller-manager  2s
ornery-koala-prometheus-op-kube-etcd                2s
ornery-koala-prometheus-op-kube-scheduler           2s
ornery-koala-prometheus-op-kube-state-metrics       2s
ornery-koala-prometheus-op-kubelet                  2s
ornery-koala-prometheus-op-node-exporter            2s
ornery-koala-prometheus-op-operator                 2s
ornery-koala-prometheus-op-prometheus               2s

==> v1beta1/PodSecurityPolicy
ornery-koala-grafana                   3s
ornery-koala-prometheus-node-exporter  3s
ornery-koala-prometheus-op-operator    3s
ornery-koala-prometheus-op-prometheus  3s

==> v1/Secret
ornery-koala-grafana  3s

==> v1/Pod(related)

NAME                                                  READY  STATUS             RESTARTS  AGE
ornery-koala-prometheus-node-exporter-dfx9m           0/1    ContainerCreating  0         3s
ornery-koala-prometheus-node-exporter-dp2s8           0/1    Running            0         3s
ornery-koala-prometheus-node-exporter-j25sk           0/1    ContainerCreating  0         3s
ornery-koala-prometheus-node-exporter-vpwhj           0/1    Running            0         3s
ornery-koala-prometheus-node-exporter-wtfm6           0/1    ContainerCreating  0         3s
ornery-koala-grafana-68c8d89d65-s2gtq                 0/3    ContainerCreating  0         3s
ornery-koala-kube-state-metrics-64b5cf45d-c7k8g       0/1    ContainerCreating  0         3s
ornery-koala-prometheus-op-operator-699df886b6-6ns2q  0/1    ContainerCreating  0         3s

==> v1beta1/ClusterRole

NAME                                       AGE
ornery-koala-kube-state-metrics            3s
psp-ornery-koala-prometheus-node-exporter  3s

==> v1beta1/RoleBinding
ornery-koala-grafana  3s

==> v1/RoleBinding
ornery-koala-prometheus-op-prometheus-config  3s
ornery-koala-prometheus-op-prometheus         3s
ornery-koala-prometheus-op-prometheus         3s

==> v1beta2/Deployment
ornery-koala-grafana  3s

==> v1beta1/Deployment
ornery-koala-kube-state-metrics  3s

==> v1/Deployment
ornery-koala-prometheus-op-operator  3s
```

However, specifying `grafana.enabled: false` at the top level solves the problem:

```
grafana:
  enabled: false

## Configuration for prometheus-operator subchart
##
prometheus-operator:
  ## Using default values from https://github.com/helm/charts/blob/master/stable/grafana/values.yaml
  ##
  grafana:
    enabled: false
```

Helm version:

```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Comment by jonathanjfshaw** [comment]
This is the expected behavior per https://github.com/helm/helm/blob/master/docs/charts.md#tags-and-condition-fields-in-requirementsyaml

Theoretically you can resolve it by specify multiple conditions ... this should work:

```
# parentchart/requirements.yaml
dependencies:
  - name: childchart
    repository: http://localhost:10191
    version: 0.1.0
    condition: childchart.enabled
```
```
# childchart/requirements.yaml
dependencies:
  - name: grandchildchart
    repository: http://localhost:10191
    version: 0.1.0
    condition: grandchildchart1.enabled,childchart.grandchildchart.enabled
```
```
# parentchart/values.yaml
childchart:
  grandchildchart:
    enabled: true
```

But in my testing all except the first condition in the requirements are ignored when nesting charts like this, so it doesn't work.

**Comment by cmeyertons** [comment]
Why is this the expected behavior when it behaves differently than the rest of the `values.yaml` file?

Spent a couple of hours scratching my head as to why this configuration wasn't working:
```yaml
istio:
  certmanager:
    enabled: true
    email: carl@loweconcierge.com
    tag: v0.5.2
    hub: quay.io/jetstack
```

the expected way is to do:
```yaml
certmanager:
  enabled: true # helm doesn't like nested

istio:
  certmanager:
    enabled: true # I have to keep this here because it might affect something else...
    email: carl@loweconcierge.com
    tag: v0.5.2
    hub: quay.io/jetstack
```

I really like how the rest of the `values.yaml` just passes in an encapsulated set of values -- it makes your subchart configuration clean & isolated.  I wish there wasn't a one off for conditional dependencies.

It also requires implementers to either:
1. duplicate the value outside of the nesting (not DRY)
2. analyze the underlying subchart to see if the flag is used outside of the conditional requirement (asking for trouble!)

It also can create conflicts with other subcharts.

In my example, what if istio's built-in `certmanager` didn't have the configuration options I needed and I need to separately install `certmanager` by itself?  I would be clashing w/ certmanager's enabled flag.

I'd honestly think of this as a bug / workaround rather than a feature or expected behavior :/

**Comment by arolls** [comment]
I have the same issue.
`Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}`

I created a demo chart to show the problem here: https://github.com/arolls/helm-dependency-enable-disable

The chart is for Kafka and Schema Registry, both of which require Zookeeper. There are shared requirements in both charts so we have to be able to enable/disable them as required. Here is a map of the requirements:
- helm-dependency-enable-disable:  
-- Kafka
--- Zookeeper
-- Schema Registry
---Kafka
----Zookeeper

I want to enable Zookeeper in the Kafka Chart and disable it in the Schema Registry chart so I have a values file as follows:
`kafka:
  enabled: true

schema-registry:
  enabled: true
  kafka:
    enabled: false`

The nested enabled: false flag in the Schema Registry chart is not being honoured which results in:
`helm install --name azure --namespace azure .
Error: release azure failed: poddisruptionbudgets.policy "azure-zookeeper" already exists`

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by cmeyertons** [comment]
@bacongobbler i still think this still should either to be addressed or a more valid reason for not implementing other than y’all haven’t got around to it :/

**Comment by arolls** [comment]
Agreed with @cmeyertons this is a problem Helm wide and is a problem for anyone trying to link together charts which have their own dependencies.

**Comment by thavlik** [comment]
Any update on this?

**Comment by bacongobbler** [comment]
```
nodeExporter:
  enabled: false
prometheus-operator:
  nodeExporter:
    enabled: false
```

> Is this expected behaviour?

Yes, this is expected behaviour. Dependencies are not uniquely identified based on the chart's name. It is entirely possible to include a dependency twice, like when your application requires two MySQL databases.

This is working as intended.

**Comment by loganmzz** [comment]
But if you include a chart twice (e.g. `A` and `B`) and want to disable subchart for one but not the other one. How to do this ? :thinking:  if condition values are not scoped ?

**Comment by maximmold** [comment]
I'm on helm 3.7.2.
argo-cd is my top level subchart which has a nested subchart of redis-ha. argo-cd has a condition of:

```
dependencies:
- condition: redis-ha.enabled
  name: redis-ha
  repository: https://dandydeveloper.github.io/charts/
  version: 4.12.17
```
I can't seem to be able able to disable via either...
```
redis-ha:
  enabled: false

argo-cd:
  redis-ha:
    enabled: false
```
Can someone help?

**Comment by loganmzz** [comment]
> Can someone help?

You will have more support & answer by posting on StackOverflow, than in a random project issue.

Regarding comments here, first one is supposed to do the job. First post seems to say both are required. I don't have my workstation ATM but can easily check on a MVCE tomorrow.

**Comment by maximmold** [comment]
I figured it out. I did not have a dependencies section in the top level chart. It didn't mention anything about the redis-ha grandchild chart, but once I added this it started working:
```
dependencies:
- condition: argo-cd.enabled
  name: argo-cd
  repository: https://argoproj.github.io/argo-helm
  version: 3.29.5
```
