### ISSUE TITLE
helm upgrade fails if deployment strategy type changes

### ISSUE THREAD

**Issue by jsravn** [helm/helm#5144]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`Minikube`

If I have a deployment template like:
```
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: prometheus-server
spec:
  replicas: 1

  strategy:
    type: RollingUpdate

  template:
    spec:
      containers:
      - name: server
        image: prom/prometheus:v2.2.1
```

And replace `type: RollingUpdate` with `type: Recreate`, the helm upgrade will fail:

```
Error: UPGRADE FAILED: Deployment.apps "prometheus-server" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

If I use `kubectl apply -f`, it works fine.

**Comment by jsravn** [comment]
Workaround is to set `rollingUpdate: null`.

**Comment by bacongobbler** [comment]
I believe this is a bug that has to do with the difference between how Helm patches resources (2-way merge with the old manifest vs. the proposed state) and how `kubectl apply` patches resources (a 3-way merge patch between the old manifest, the cluster's live state and the proposed state).

I know we're looking at alternative merge patch strategies for Helm 3.

**Comment by dannybitgo** [comment]
> Workaround is to set `rollingUpdate: null`.

Where do you set this?

**Comment by jsravn** [comment]
@dannybitgo 
```yaml
  strategy:
    type: RollingUpdate
    rollingUpdate: null
```
