### ISSUE TITLE
'helm dependency update' failed with 'x509: certificate signed by unknown authority' 

### ISSUE THREAD

**Issue by rhnewtron** [helm/helm#5179]
**Output of `helm version`:**

```
λ helm version
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
```

**Output of `kubectl version`:**

I use openshift / minishift 
```
λ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):**

```
minishift
```

**Description:**

I am running the chartmuseum via SSL on minishft with a self signed certificate. I was able to add the repo to helm and everything works properly if I have no dependencies when adding the ```--ca-file``` option.

```
helm repo add chartmuseum https://my-museum-with-private-cert/ --ca-file ca.crt
```

```helm install``` and ```helm repo update``` works. 

When I add dependencies to charts on the same chartmuseum, I get an error for downloading: 

```
λ helm dependency update spring-petclinic
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "chartmuseum" chart repository
...
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading xxx-build from repo https://my-museum-with-private-cert/
Save error occurred:  could not download https://my-museum-with-private-cert/charts/xxx-0.1.0.tgz: Get https://my-museum-with-private-cert/charts/xxx-0.1.0.tgz: x509: certificate signed by unknown authority
Deleting newly downloaded charts, restoring pre-update state
....
```

So it seems the chart download does not reuse the ca cert settings of the repo:

```
λ cat ~/.helm/repository/repositories.yaml
apiVersion: v1
generated: 2018-05-09T09:55:31.025782+02:00
repositories:
- caFile: c:\tmp\ca.crt
  cache: C:\Users\xxxx\.helm\repository\cache\chartmuseum-index.yaml
  certFile: ""
  keyFile: ""
  name: chartmuseum
  password: ""
  url: https://my-museum-with-private-cert/
  username: ""
```

**Comment by rhnewtron** [comment]
Maybe it is this line ??

* https://github.com/helm/helm/blob/fbda50a452b6db58faf2016b17c206ee27ddc999/pkg/downloader/chart_downloader.go#L173

**Comment by bacongobbler** [comment]
Does the machine which you're running `helm dep update` have that same self-signed key installed? That x509 error usually occurs when that key is not part of your root cert chain and it cannot verify the key.

**Comment by bacongobbler** [comment]
We should dive deeper into the `helm dep up` code to see if it's grabbing the proper chain cert when downloading. Thanks for the tip @rhnewtron.

**Comment by rhnewtron** [comment]
I digged some deeper and it seems to be a configuration issue.
I was running chartmuseum without ```--chart-url=```. This created relative records in the repository file: 

```
root@443dc750d55a:/go/src/k8s.io/helm# cat ~/.helm/repository/cache/chartmuseum-index.yaml
apiVersion: v1
entries:
  mychart:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-01-25T07:52:53.736Z"
    description: My Test Chart
    digest: 11c0e3b6d017e34c2678ad40585ef1993df18c89403e48ec0d35162def33b750
    name: mychart
    urls:
    - charts/mychart-0.2.0.tgz
    version: 0.2.0
generated: "2019-01-25T07:53:02Z"
serverInfo: {}
```

This makes the ```scanReposForURL``` function in ```pkg/downloader/chart_downloader.go``` fail with ```ErrNoOwnerRepo``` and this again enabled the fallback logic in ```ResolveChartVersion```:

```
			if err == ErrNoOwnerRepo {
				getterConstructor, err := c.Getters.ByScheme(u.Scheme)
				if err != nil {
					return u, nil, err
				}
				g, err := getterConstructor(ref, "", "", "")
				if t, ok := g.(*getter.HttpGetter); ok {
					t.SetCredentials(c.Username, c.Password)
				}
				return u, g, err
			}
```

This sounds valid, as the logic in the chartdownloader can not identify the repo to use. 

When running the chartmuseum with the proper ```--chart-url=```, everything works. 

I guess supporting a ```--ca-file``` option for all helm commands, overruling all repo settings would be an option to fix this, however this would still not address issues if client cert auth is used. A better approach would be for the *chartmuseum* server to autodetect the ```--chart-url=``` setting from the Host reader of the request. This would make all URL's absolute while still allowing a CDN functionality in case someone specifies ```--chart-url=```. I will now workaround the issue in the Openshift Template.
