### ISSUE TITLE
<b64dec>: invalid value; expected string

### ISSUE THREAD

**Issue by IvanovOleg** [helm/helm#5181]
I have the following string in the configmap:
`{{ printf "%s" "dGVzdA==" | b64dec }}`
When I use helm lint it fails:
`at <b64dec>: invalid value; expected string`

Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}`

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by hickeyma** [comment]
Seems to work for me. I added this to a template file:
`code: {{ printf "%s" "dGVzdA==" | b64dec }}`

and I get an output in the manifest of:
`code: test`

I'm using Helm v2.12.

**Comment by IvanovOleg** [comment]
@hickeyma output works, helm lint fails

**Comment by hickeyma** [comment]
Ok, missed that. Just tested and `lint` works as well.

Can you try with latest version of Helm to see if it is an issue in a certain release?

**Comment by IvanovOleg** [comment]
@hickeyma 
I tried the helm 2.12.2 and got the same issue. I ran it on Windows, maybe this is the reason.

**Comment by IvanovOleg** [comment]
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}

**Comment by hickeyma** [comment]
@bacongobbler could you try this on Windows?

**Comment by bacongobbler** [comment]
I added that example to a template on Windows and it worked fine. There shouldn't be a difference based on the OS, but I checked to make sure. Here's how I tested:

```
$ helm create foo
```

Added a new label to the deployment template using the example:

```
PS C:\Users\me> helm template .\foo\ -x templates/deployment.yaml
---
# Source: foo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-foo
  labels:
    app.kubernetes.io/name: foo
    helm.sh/chart: foo-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    test-5181: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: foo
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foo
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: foo
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
```

`helm lint` also shows no errors:

```
PS C:\Users\me> helm lint .\foo\
==> Linting .\foo\
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
```

So it looks like it's something else to do with your chart. Is there something else in the template that you might not be showing here? The error appears to indicate that you're piping a non-string value to `b64dec`.

**Comment by bacongobbler** [comment]
For completeness, here's the template:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "foo.name" . }}
    helm.sh/chart: {{ include "foo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    test-5181: {{ printf "%s" "dGVzdA==" | b64dec }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "foo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "foo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
```
