### ISSUE TITLE
helm install/upgrade multiple charts in one line command

### ISSUE THREAD

**Issue by dorsany** [helm/helm#5204]
in some cases I have multiple charts to install. it will be amazing if helm will handle the loop/iteration to install those carts instead of a script.

some ideas to solve it:
1) argument in the cli to pass chart array like ```{<name of the chart>,<chart path>}``` . like the --set logic
```
helm upgrade --install --chart {mongo,/tmp/mongo} --chart {redis,/tmp/redis}
```
2) config file of the carts that need to install
for example:
```
charts:
  - name: mongo
    path: /tmp/mongo
  - name: redis
    path: /tmp/redis
```
