### ISSUE TITLE
Helm TLS certs rotation procedure

### ISSUE THREAD

**Issue by antoniaklja** [helm/helm#5216]
As far I know Helm doesn't support natively TLS certs rotation.
Also, I couldn't find anything related in [Using SSL Between Helm and Tiller](https://github.com/helm/helm/blob/master/docs/tiller_ssl.md).

Example command below doesn't update content of Kubernetes Secret `tiller-secret`:
```
helm init \
  --tiller-tls \
  --tiller-tls-cert "tiller-server.pem" \
  --tiller-tls-key "tiller-server-key.pem" \
  --tls-ca-cert "ca.pem" \
  --upgrade
```
more than that, if you remove `tiller-secret` manually, the next run of `helm init` won't re-create the `tiller-secret`.

You have to either recreate Helm deployment from scratch (clean all releases) or manually update `tiller-secret`.

**Comment by antoniaklja** [comment]
The only reasonable solution is to update existing k8s Secret, otherwise, it can have an impact on production workloads (esp. rollback to previous release),

```
 cat <<EOF > tiller_secrets
apiVersion: v1
data:
    tls.crt: ${tls_crt}
    tls.key:  ${tls_key}
kind: Secret
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-secret
EOF

  kubectl apply -f tiller_secrets
```
