### ISSUE TITLE
Merge in template does not work with boolean values

### ISSUE THREAD

**Issue by Overbryd** [helm/helm#5238]
Output of `helm version`:

```console
$ helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Output of `kubectl version`: irrelevant

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  irrelevant

<br>

### Context

I have a template that is rendered from another charts template.
I use the other chart as a _base chart_ and therefore `{{ $_ := merge .Values .Values.base }}` in the templates.

Unfortunately, as documented in [this sprig issue](https://github.com/Masterminds/sprig/issues/134#issuecomment-458999247) and that [mergo issue](https://github.com/imdario/mergo/issues/91) `merge` will not work as advertised.

I could observe that unexpected behaviour in one of my templates.

Given a chart `test` that requires a `common`-chart, I expect the following template to work:

```
# test/charts/common/templates/_test.yaml
{{- define "common.test" -}}
{{- $commonValues := .Values.common -}}
{{- $chartValues := omit .Values "common" -}}
{{- $mergedValues := merge (dict) $chartValues $commonValues -}}
{{- $_ := set . "Values" $mergedValues -}}
apiVersion: apps/v1
kind: Deployment
data: |-
{{ .Values | toYaml | indent 2 }}
{{- end -}}
```

```yaml
# test/charts/common/values.yaml
test:
  enabled: true
  overwrite: default
```

```yaml
# test/templates/test.yaml
{{- template "common.test" . -}}
```

```yaml
# test/values.yaml
test:
  enabled: false
  overwrite: overwritten
```

#### Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
data: |-
  test:
    enabled: false
    overwrite: overwritten
```

#### Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
data: |-
  test:
    enabled: true
    overwrite: overwritten
```
