### ISSUE TITLE
helm template and helm install --debug --dry-run differ from final result

### ISSUE THREAD

**Issue by proskehy** [helm/helm#5244]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Baremetal (Centos 7 VMs)

------------------------------------------------------------------------------------

Edit: 
Turned out to be a syntax error in Kubernetes (strangely not picked up by Helm).
The problem was that the generated volumes looked like this:
```
 volumes:
  - name: commonconfig
    projected:
      sources:
      - configMap:
        name: configmap-name-1
      - configMap:
        name: configmap-name-2
```

But the correct syntax is this:
```
 volumes:
  - name: commonconfig
    projected:
      sources:
      - configMap:
          name: configmap-name-1
      - configMap:
          name: configmap-name-2
```

For some reason, Helm didn't complain when applying this manifest. I only found out that this was the root of the issue by applying the created `Deployment` manifest manually using `kubectl create`.

I'm not sure if I should close this or keep it open (as it might be a bug?), so I will leave it open and feel free to close it if you want to.
