### ISSUE TITLE
Helm Lint `error converting YAML to JSON` when using $ with toYaml

### ISSUE THREAD

**Issue by znorris** [helm/helm#5261]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
```
Output of `kubectl version`:
N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

**Issue:**
Now that I've written the the steps below it seems to me that `toYaml` isn't able to use  `$` to refer to the global context when in this range scope. Shouldn't `$` always refer to the global context? (as mentioned here https://github.com/helm/helm/blob/master/docs/chart_template_guide/variables.md)

**Reproduce:**
1. Using the helm version noted above run `helm create test`.
1. Add a key to `values.yaml` that is an array.
1. Convert all references of `{{ .Something }}` to `{{ $.Something }}` (I did this line-by-line running the linter after each change).
1. Run linter, success.
1. Wrap `deployment.yaml` in a `range`.
1. Re-run linter, error.

Linter error:
```
$ helm lint --strict
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/deployment.yaml: unable to parse YAML
        error converting YAML to JSON: yaml: line 40: did not find expected key

Error: 1 chart(s) linted, 1 chart(s) failed
```
Dry-run error:
```
$ helm install --dry-run --debug .
[debug] Created tunnel using local port: '61609'

[debug] SERVER: "127.0.0.1:61609"

[debug] Original chart version: ""
[debug] CHART PATH: /test

Error: YAML parse error on test/templates/deployment.yaml: error converting YAML to JSON: yaml: line 39: did not find expected key

---
# Source: test/templates/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtuous-liger-test
  labels:
    app.kubernetes.io/name: test
    helm.sh/chart: test-0.1.0
    app.kubernetes.io/instance: virtuous-liger
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test
      app.kubernetes.io/instance: virtuous-liger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test
        app.kubernetes.io/instance: virtuous-liger
    spec:
      containers:
        - name: test
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
            ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtuous-liger-test
  labels:
    app.kubernetes.io/name: test
    helm.sh/chart: test-0.1.0
    app.kubernetes.io/instance: virtuous-liger
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test
      app.kubernetes.io/instance: virtuous-liger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test
        app.kubernetes.io/instance: virtuous-liger
    spec:
      containers:
        - name: test
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
```

Copy of `deployment.yaml`:
```yaml
{{- range .Values.apps -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test.fullname" $ }}
  labels:
    app.kubernetes.io/name: {{ include "test.name" $ }}
    helm.sh/chart: {{ include "test.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "test.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "test.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
```

Copy of `values.yaml`:
```
# Default values for test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

apps:
  - one:
      bar: "one"
  - two:
      bar: "two"
```
