### ISSUE TITLE
pod tiller-deploy crashes with permission denied on token

### ISSUE THREAD

**Issue by sven-carstens** [helm/helm#5269]
Output of `helm version`:
```
# helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Error: could not find a ready tiller pod
```

Output of `kubectl version`:
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-CCE2.0.7-B003", GitCommit:"302f471a1e2caa114c9bb708c077fbb363aa2f13", GitTreeState:"clean", BuildDate:"2018-06-20T03:27:16Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
Open Telekom Cloud CCE-2.0 https://docs.otc.t-systems.com/en-us/usermanual2/cce/cce_01_9991.html
```

Setup with rbac according to the docs.

serviceaccount and clusterrolebinding
```
# cat rbac-config.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
```

Creating rbac binding
```
# kubectl -n kube-system create -f rbac-config.yaml
serviceaccount "tiller" created
clusterrolebinding "tiller" created
```

helm init
```
# helm init --service-account tiller
$HELM_HOME has been configured at /root/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
```

Pod keeps failing
```
# kubectl -n kube-system describe po tiller-deploy-7c78f74c-lzscm
Name:           tiller-deploy-7c78f74c-lzscm
Namespace:      kube-system
Node:           192.168.10.234/192.168.10.234
Start Time:     Wed, 06 Feb 2019 13:29:03 +0000
Labels:         app=helm
                name=tiller
                pod-template-hash=37349307
Annotations:    <none>
Status:         Running
IP:             172.16.0.7
Controlled By:  ReplicaSet/tiller-deploy-7c78f74c
Containers:
  tiller:
    Container ID:   docker://776e31514297f92d5f33962b1b5ed52c7ca916e64781c81a5a04b6ffe97b1515
    Image:          gcr.io/kubernetes-helm/tiller:v2.12.3
    Image ID:       docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:cab750b402d24dd7b24756858c31eae6a007cd0ee91ea802b3891e2e940d214d
    Ports:          44134/TCP, 44135/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 06 Feb 2019 13:30:47 +0000
      Finished:     Wed, 06 Feb 2019 13:30:48 +0000
    Ready:          False
    Restart Count:  4
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from tiller-token-hzntg (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  tiller-token-hzntg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tiller-token-hzntg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age                From                     Message
  ----     ------                 ----               ----                     -------
  Normal   Scheduled              2m                 default-scheduler        Successfully assigned tiller-deploy-7c78f74c-lzscm to 192.168.10.234
  Normal   SuccessfulMountVolume  2m                 kubelet, 192.168.10.234  MountVolume.SetUp succeeded for volume "tiller-token-hzntg"
  Normal   SuccessfulMountVolume  2m (x2 over 2m)    kubelet, 192.168.10.234  Successfully mounted volumes for pod "tiller-deploy-7c78f74c-lzscm_kube-system(2c07142b-2a13-11e9-9ff9-fa163e1c80f4)"
  Normal   Pulled                 1m (x4 over 2m)    kubelet, 192.168.10.234  Container image "gcr.io/kubernetes-helm/tiller:v2.12.3" already present on machine
  Normal   SuccessfulCreate       1m (x4 over 2m)    kubelet, 192.168.10.234  Created container
  Normal   Started                1m (x4 over 2m)    kubelet, 192.168.10.234  Started container
  Warning  BackOffStart           31s (x10 over 1m)  kubelet, 192.168.10.234  Back-off restarting failed container
```

Log of Pod
```
# kubectl -n kube-system logs tiller-deploy-7c78f74c-lzscm
[main] 2019/02/06 13:32:16 Cannot initialize Kubernetes connection: failed to read token file "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: permission denied
```

Secret has token set inside of data (secrets replaced by XX)
```
# kubectl -n kube-system get secret tiller-token-hzntg -o yaml
apiVersion: v1
data:
  ca.crt: XX
  namespace: a3ViZS1zeXN0ZW0=
  token: XX
kind: Secret
metadata:
  annotations:
    generator: JWT
    kubernetes.io/service-account.name: tiller
    kubernetes.io/service-account.uid: 0e9bd70d-2a13-11e9-ba56-fa163e0a415a
  creationTimestamp: 2019-02-06T13:28:14Z
  enable: true
  name: tiller-token-hzntg
  namespace: kube-system
  resourceVersion: "37224"
  selfLink: /api/v1/namespaces/kube-system/secrets/tiller-token-hzntg
  uid: 0e23f967-2a13-11e9-9ff9-fa163e1c80f4
type: kubernetes.io/service-account-token
```

**Comment by elemakil** [comment]
I have the same problem. I am also using the CCE product of the Open Telekom Cloud. It is a brand-new CCE instance.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Error: could not find a ready tiller pod
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-CCE2.0.7-B003", GitCommit:"302f471a1e2caa114c9bb708c077fbb363aa2f13", GitTreeState:"clean", BuildDate:"2018-06-20T03:27:16Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by elemakil** [comment]
I have done some digging and I am convinced that this permission problem is in some way related to the use of the [user nobody](https://github.com/helm/helm/blob/ead111dd4f699b3cb0a56f1e6d4585e3363f925b/rootfs/Dockerfile#L25) in the `Dockerfile` of the image. I found that the `.../tokens` file is present in the container but not accessible by the user `nobody`, see below for my step-by-step analysis.

I suspect that this is some bad interplay between the EulerOS linux distribution that the CCE machines use and the mounting mechanism.

---

I have generated the `deployment.yaml` from the `helm init` command using:

```shell
$ helm init --service-account tiller --dry-run --debug
```

and modified it:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: TILLER_NAMESPACE
          value: kube-system
        - name: TILLER_HISTORY_MAX
          value: "0"
        image: gcr.io/kubernetes-helm/tiller:v2.12.3
        imagePullPolicy: IfNotPresent
        command: [ "sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        name: tiller
      serviceAccountName: tiller
```

After `kubectl create`-ing this deployment, I have ssh'd onto the node and entered the pod using `docker exec`. Doing so allows me to override the linux-user that is used inside the docker container:

```shell
# no user supplied -> will use `nobody`
$ docker exec -u user -ti k8s_tiller_tiller-deploy-8cd9fc8d8-sz9q6_kube-system_b44311af-3908-11e9-9727-fa163e88ed1f_0 sh
# user `root` supplied
$ docker exec -ti -u root k8s_tiller_tiller-deploy-8cd9fc8d8-sz9q6_kube-system_b44311af-3908-11e9-9727-fa163e88ed1f_0 sh
```

I observe that I can't access the `.../tokens` file as user `nobody` but, as one might expect, can do so as user `root`:

```shell
# as user `nobody`:
$ cat /var/run/secrets/kubernetes.io/serviceaccount/token 
cat: can't open '/var/run/secrets/kubernetes.io/serviceaccount/token': Permission denied

# as user `root`
$ cat /var/run/secrets/kubernetes.io/serviceaccount/token
eyJhbGciOiJSUzI1NiIsInR.............ga
```
