### ISSUE TITLE
Merge function for values overriden with null does not take effect

### ISSUE THREAD

**Issue by josecv** [helm/helm#5274]
Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

`kubectl` version isn't really relevant as this is a templating issue.

In helm < 2.12, the merge function would allow one to set a value to `null` when merging, and the resulting dict would have that value set to `null`. In helm >= 2.12, setting a value to null will behave the same as if it that value were absent, resulting in the selection of a lower-precedence value instead of the null.

To reproduce:

templates/deployment.yaml
```yaml
{{- $resourcesSpec := (merge (.Values.resourcesOverride | default (dict)) .Values.resourcesSpec) }}
          resources:
{{ toYaml (pluck "resources" $resourcesSpec | first) | indent 12 }}
```

values.yaml
```yaml
resourcesSpec:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
```

values2.yaml
```yaml
resourcesOverride:
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
```

In helm < 2.12:

```
$ helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
$ helm template . -f values2.yaml
---
# Source: repro/templates/deployment.yaml

          resources:
            limits:
              cpu: null
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
```

In helm >= 2.12:

```
$ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

$ helm template . -f values2.yaml
---
# Source: repro/templates/deployment.yaml

          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
```

**Comment by josecv** [comment]
i suspect this may be related to this sprig issue https://github.com/Masterminds/sprig/issues/134

**Comment by hickeyma** [comment]
@josecv Can you test if this issue is now fixed?  Helm is using sprig with this fix: https://github.com/Masterminds/sprig/pull/137 This fix might solve your issue also?

**Comment by josecv** [comment]
Just tried out the latest helm from `master` and it worked:

```bash
$ helm version
Client: &version.Version{SemVer:"1.0.1-rc.12+unreleased", GitCommit:"ead111dd4f699b3cb0a56f1e6d4585e3363f925b", GitTreeState:"clean"}
$ helm template . -f values2.yaml
---
# Source: repro/templates/deployment.yaml

          resources:
            limits:
              cpu: null
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
```

thanks!

**Comment by yann-soubeyrand** [comment]
Hi,

I'm using latest Helm 2 version
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
and still hitting the bug
```
helm template -f values.yaml -f values-override.yaml .
---
# Source: merge-test/templates/test.yaml

          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

```

According to the comment in the code https://github.com/imdario/mergo/blob/7c29201646fa3de8506f701213473dd407f19646/merge.go#L204, this seems to behave as expected.

I've also tried with the mergeOverwrite function which I expected to do the job
```
{{- $resourcesSpec := .Values.resourcesOverride | default (dict) | mergeOverwrite .Values.resourcesSpec }}
          resources:
{{ toYaml (pluck "resources" $resourcesSpec | first) | indent 12 }}
```
but the result is the same. Again, comment in the code seems to indicate this is intended https://github.com/imdario/mergo/blob/7c29201646fa3de8506f701213473dd407f19646/merge.go#L212.

Newer version of the mergo package (helm uses sprig, which makes use of mergo) have an option to overwrite with empty values https://github.com/imdario/mergo/blob/4c8d33afe3b211a221b8ae2f06f510d974e5991f/merge.go#L248. However, I didn't manage to make it work during a quick test. I'll have to dig deeper into the code.

@bacongobbler could you reopen this issue please?

**Comment by jkdey-better** [comment]
Seeing this behavior in Helm 3:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.6"}
```

```
helm template . -f values2.yaml
---
# Source: test/templates/deployment.yaml
resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
```
