### ISSUE TITLE
Helm template silent rendering error with @ symbol

### ISSUE THREAD

**Issue by paktek123** [helm/helm#5301]
Below is how to reproduce this bug. 

With the follow directory structure:

```
.
├── Chart.yaml
├── templates
│   └── namespaces.yaml
└── values
    └── test.yaml

2 directories, 3 files
```

Chart.yaml
```
apiVersion: v1
name: helmbugtest
version: 0.1.0
description: test
sources:
  - https://github.com/helm/helm
maintainers:
  - name: paktek123
appVersion: 0.1
```

templates/namespaces.yaml
```
{{- $files := .Files }}
{{- range $path, $_ := $files.Glob "values/**.yaml" }}
{{- $values := $files.Get $path | fromYaml }}
{{- $anothertest := $values.anothertest }}
{{- range $values.namespaces }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .name }}
  labels:
    test: {{ default $anothertest .anothertest }}
{{- end }}
{{- end }}
```

values/test.yaml
```
name: hello
anothertest: defaultval
namespaces:
  - name: test
  - name: anothertest
    anothertest: overrideval
```

When I run `helm template . -x templates/namespaces.yaml` I get:

```
---
# Source: helmbugtest/templates/namespaces.yaml

---
kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    test: defaultval
---
kind: Namespace
apiVersion: v1
metadata:
  name: anothertest
  labels:
    test: overrideval
```

When I modify the values/test.yaml as follows:
```
name: hello
anothertest: defaultval
namespaces:
  - name: test
  - name: anothertest
    anothertest: @overrideval
```

I get nothing rendered:
```
helm template . -x templates/namespaces.yaml
---
# Source: helmbugtest/templates/namespaces.yaml
```

```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  On-Prem, no provider

**Comment by hickeyma** [comment]
I have verified this issue. The issue is when it tries to render the values which contain the value with the '@'. 

Helm calls the external function [ExecuteTemplate](https://golang.org/pkg/text/template/#Template.ExecuteTemplate)                                       
[here](https://github.com/helm/helm/blob/master/pkg/engine/engine.go#L278). It does not return an error but instead a buffer with Hex values `\x00`, which is essentially an empty string. 

@bacongobbler What are your thoughts? Should this be raised as an issue upstream against Go templating?

**Comment by bacongobbler** [comment]
As per the YAML format, strings containing any of the following characters must be quoted. Although you can use double quotes, for these characters it is more convenient to use single quotes, which avoids having to escape any backslash (`\`):

    :, {, }, [, ], ,, &, *, #, ?, |, -, <, >, =, !, %, @, `

Backticks and ampersats are [reserved indicators](https://yaml.org/refcard.html), so this seems in line with the YAML parser.

Try wrapping `@overrideval` with single quotes:

```
name: hello
anothertest: defaultval
namespaces:
  - name: test
  - name: anothertest
    anothertest: '@overrideval'
```

Let me know if that works for you.
