### ISSUE TITLE
Set namespace for subcharts using values.yaml

### ISSUE THREAD

**Issue by crubier** [helm/helm#5358]
This is a feature request, related to #2813 .

I have this use case with strong operational constraints (integration with terraform on one side, and with gitlab on the other side), where I would like to be able to specify namespaces of subcharts, for example by using a `values.yaml` like this:

```yaml
my-subchart-1:
    enabled: true
    namespace: gitlab-managed-apps
    foor: bar

my-subchart-2:
    enabled: true
    namespace: my-namespace
    bar: foo
```

I tried it at first, not doubting that this would work, as I expected this behaviour. But I was surprised to see that it does not work, even though it "feels helm idiomatic".

I also believe that it would not be much effort to implement, but I might be mistaken!

**Comment by hickeyma** [comment]
@bacongobbler with the addition of [State Management](https://github.com/helm/community/blob/master/helm-v3/003-state.md) and the removal of Tiller in v3, will it be possible to use multiple namespaces in the one release?

**Comment by hickeyma** [comment]
@crubier For v2, you could install each namespace individually using `--skip-dependencies` or with [conditions](https://github.com/helm/helm/blob/master/docs/charts.md#tags-and-condition-fields-in-requirementsyaml)

**Comment by crubier** [comment]
@hickeyma using tags might be a fair workaround for me in this case. Tag subcharts with different values and execute one release per namespace

**Comment by bacongobbler** [comment]
This feels like a solid use case for [helmfile](https://github.com/roboll/helmfile). I don't think this will be resolved in Helm 3 as the original post is requesting a new feature within requirements.yaml (or Chart.yaml in Helm 3). We haven't ironed out the details for managing a single release across multiple namespaces, though several community members have written tools to manage that state across the cluster.

See also #980 for some background context/disucssion on this topic.

**Comment by crubier** [comment]
@bacongobbler this is not use case for helmfile, as I don't really want to add an additional third party alpha dependency to this (already quite complex) stack, that will have to run in various environments.

Using tags and multiple releases allows me to work around, but with a pretty high complexity.

**Comment by nicorikken** [comment]
@crubier the proposal you outlined would suit are use-case and looks very ergonomic. I too tried this, assuming that would work, but no.
When it comes to combining charts, Helm is missing some key features. We need these features to start sharing and combining more templates in the community, rather than everyone having to build their own.

**Comment by nicorikken** [comment]
I've been able to work around this by introducing an `namespaceOverride` value in a chart https://github.com/helm/charts/pull/15202 ,picked up by the `_helpers.tpl`. I combine this with the `alias:` option in the `values.yaml` of the main chart to duplicate the subcharts under different names as to configure them differently.

**Comment by MichaelMitchellM** [comment]
Is there any update on support for this?

**Comment by kevupton** [comment]
This would definitely be useful in my scenario where I have mutliple helm subcharts across different namespaces.

**Comment by sadoMasupilami** [comment]
would be useful for cases like deploying external-dns or aws-alb-ingress together with your stack as options.

**Comment by mforutan** [comment]
The approach I took was to combine `global` variables with `namespaceOverride` so it can be overridden from multiple level in umbrella charts,

In the scenario below when an umbrella chart has a dependency and its dependency has its own dependency, just overriding nemespace on the first level is not flexible enough and will result in moving `chart-1` to `name-space-2` but `chart-2` will be still in the `name-space-1`:

```
top-umbrella-char:
- namespace: name-space-1
- values.yaml:
  chart-1:
    namespaceOverride: name-space-2
- dependencies:
    - chart-1:
      dependencies:
      - chart-2:
```
to resolve this, I am using `global.namespaceOverride` so it can push down to the lower level:

```
top-umbrella-chart:
- namespace: name-space-1
- values.yaml:
  global.namespaceOverride: name-space-1
  chart-1:
    global.namespaceOverride: name-space-2
- dependencies:
    - chart-1:
      dependencies:
      - chart-2:
```
in this case, `chart-2` will follow the same namespace from chart-1 instead of using `release.namespace`

An example of using this was merged for [stable/mongodb-replicaset](https://github.com/helm/charts/tree/master/stable/mongodb-replicaset) chart

[values.yaml](https://github.com/helm/charts/blob/5a8cfbe5729cb64cc2995326769de89246e37809/stable/mongodb-replicaset/values.yaml#L5-L7) file and [_helper.tpl](https://github.com/helm/charts/blob/5a8cfbe5729cb64cc2995326769de89246e37809/stable/mongodb-replicaset/templates/_helpers.tpl#L80-L93)

Do you think this can be a possible solution for this issue?
