### ISSUE TITLE
Values file set to "{}" cannot overwrite

### ISSUE THREAD

**Issue by zhanglijingisme** [helm/helm#5407]
Hi,
We have a helm chart with following values.yaml , like this
```
Files:
  alerts:
    kinds:
    - name: 12345
    ...
```
Helm chart template is
```
{{- if eq $key "alerts" }}
  {{ $key }}: |
{{ toYaml $value | default "{}" | indent 4 }}
{{- end }}
```

Now we want to overwrite this "alerts" with an empty object. We wrote a values-new.yaml
```
Files:
  alerts: {}
```
and do this
`# helm install mychart -f values-new.yaml`

However, it failed to overwrite. After helm install, default values still exist - not replaced by {}

Output of `helm version`: 2.9.1 / 2.11.0
Output of `kubectl version`: 1.10.2 / 1.12.3

**Comment by bacongobbler** [comment]
Hey there, can you please try a newer version of helm first to verify it hasn't already been fixed in a later version? Please verify if this issue still exists with Helm 2.13.0. Thanks.

**Comment by jlegrone** [comment]
@zhanglijingisme I've had luck in the past solving this by doing something like

```yaml
Files:
  alerts: null
```

It's _not_ pretty, but I believe this is necessary if your chart has defaults already specified in `values.yaml`.

**Comment by bacongobbler** [comment]
Ah yeah, I think @jlegrone identified the correct behaviour. `{}` is treated differently than `null` when merging values together.

See also https://helm.sh/docs/chart_template_guide/#deleting-a-default-key

This question was also answered in #3891 (and fixed in #3912) so please make sure you're on a more recent version of Helm. That fix made it into Helm 2.10.0, so you'll need to upgrade your client to get the fix.

Thanks!

**Comment by james-mchugh** [comment]
On a similar note, setting a YAML dictionary to `null` does not seem to delete the value either, but perhaps this is expected bahavior. I am currently running on Helm 3.2.0, and the following does not work as I expected:
filebeat/values.yaml
```yaml
filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: docker
      containers.ids:
      - '*'
      processors:
      - add_kubernetes_metadata: ~

    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
```
mychart/values.yaml
```yaml
filebeat:
  filebeatConfig: null

```
configmap.yaml template:
```yaml
{{- if .Values.filebeatConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "filebeat.fullname" . }}-config
  labels:
    app: "{{ template "filebeat.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.filebeatConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
```
configmap.yaml out:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: perceptor-filebeat-config
  labels:
    app: "perceptor-filebeat"
    chart: "filebeat-7.6.2"
    heritage: "Helm"
    release: "perceptor"
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: docker
      containers.ids:
      - '*'
      processors:
      - add_kubernetes_metadata: ~
    
    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
```

However, I expected configmap.yaml to not be populated.

**Comment by ktlast** [comment]
Same as #7902 

Not only updating `null` not work, but any values (via `-f ./my_values.yml`; it works only when use `--set`)

**Comment by fedos3d** [comment]
Is there a valid workaround for now? I am using helm v3.13.3 and still cannot override.
`template.yaml`:
```
      affinity:
    {{- if .Values.affinity }}
    {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- else }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values: mem
              topologyKey: failure-domain.beta.kubernetes.io/zone
      {{ end }}
```
Chart `values.yaml`:
```
affinity: {}
```
Overrdie `values.yaml`:
```
affinity: {}
```

In any case I still get this:
```
    affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values: mem
              topologyKey: failure-domain.beta.kubernetes.io/zone
```
