### ISSUE TITLE
Escape prefix ":" in values or template

### ISSUE THREAD

**Issue by AlexandrSemak** [helm/helm#5445]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.3",
GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

Hello,

How can I escape ":" in values or template:

values:

```
goreplay:
  port: ':3000'
```

template:
`args: ["--input-raw", {{ .Values.goreplay.port | quote }}, "--output-http", {{ .Values.goreplay.url }}]
`   

Error:     
 
`error converting YAML to JSON: yaml: line 145: did not find expected node content`

Can I pass ":" to template and how?

**Comment by hickeyma** [comment]
@AlexandrSemak Try setting the port as follows:
`port: ":3000"`

Let me know how you get on.

**Comment by AlexandrSemak** [comment]
> @AlexandrSemak Try setting the port with double quotes as follows:
> `port: ":3000"`
> 
> Let me know how you get on.

@hickeyma 
`error converting YAML to JSON: yaml: line 145: found unexpected ':'`

**Comment by AlexandrSemak** [comment]
whole yaml template block:

```
        - name: {{ .Values.goreplay.name }}
          image: "{{ .Values.image.repository }}/{{ .Values.goreplay.name }}:{{ .Values.goreplay.tag }}"
          command: ["goreplay"]
          args: ["--input-raw", {{ .Values.goreplay.port | quote }}, "--output-http", {{ .Values.goreplay.url }}]
          ports:
            - hostPort: {{ .Values.goreplay.hostPort }}
              containerPort: {{ .Values.goreplay.containerPort }}
              protocol: TCP
          resources:
{{ toYaml .Values.goreplay.resources | indent 12 }}
```

**Comment by hickeyma** [comment]
Can you show the whole template to get a better understanding of what is happening?  It works when set and accessed as a value without any modification in the template.

**Comment by AlexandrSemak** [comment]
@hickeyma 
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.image.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    version: {{ .Values.image.tag }}
    cluster: {{ default "unknown" .Values.cluster }}
    region: {{ default "unknown" .Values.region }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  minReadySeconds: {{ .Values.deploy.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.deploy.revisionHistoryLimit }}
  progressDeadlineSeconds: {{ .Values.deploy.progressDeadlineSeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  replicas: {{ default "1" .Values.hpa.minReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
        version: {{ .Values.image.tag }}
        cluster: {{ default "unknown" .Values.cluster }}
        region: {{ default "unknown" .Values.region }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          {{- if .Values.volume }}
          volumeMounts:
          - mountPath: "{{ .Values.volume.path }}"
            name: "{{ .Values.volume.name }}"
            readOnly: true
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
          {{- if .Values.wcenv }}
          {{- $l := split " " .Values.wcenv }}
          {{- range $l }}
          {{- $v := . | split "=" }}
          {{- if $v._0 }}
          - name: {{ $v._0 | trim }}
          {{- end }}
          {{- if $v._1 }}
            value: {{ $v._1 | trim | quote }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.deploy.env.open }}
          {{- range $name, $value := .Values.deploy.env.open }}
          - name: {{ $name }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.deploy.env.secret }}
          {{- range $index, $element := .Values.deploy.env.secret }}
          {{- range $name, $map := $element }}
          - name: {{ $name }}
            valueFrom:
              secretKeyRef:
                {{- range $secret, $key := $map }}
                name: {{ $secret }}
                key: {{ $key }}
                {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
          livenessProbe:
            {{- if .Values.deploy.livenessProbePath }}
            httpGet:
              path: {{ .Values.deploy.livenessProbePath }}
              port: {{ .Values.service.port }}
            {{ else }}
            tcpSocket:
              port: {{ .Values.service.port }}
            {{- end }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            {{- if .Values.deploy.readinessProbePath }}
            httpGet:
              path: {{ .Values.deploy.readinessProbePath }}
              port: {{ .Values.service.port }}
            {{ else }}
            tcpSocket:
              port: {{ .Values.service.port }}
            {{- end }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- if .Values.goreplay.deploy}}
        - name: {{ .Values.goreplay.name }}
          image: "{{ .Values.image.repository }}/{{ .Values.goreplay.name }}:{{ .Values.goreplay.tag }}"
          command: ["goreplay"]
          args: ["--input-raw :{{ .Values.goreplay.port }}", "--output-http {{ .Values.goreplay.url }}"]
          ports:
            - hostPort: {{ .Values.goreplay.hostPort }}
              containerPort: {{ .Values.goreplay.containerPort }}
              protocol: TCP
          resources:
{{ toYaml .Values.goreplay.resources | indent 12 }}
        {{- end }}
      {{- if .Values.volume }}
      volumes:
      - name: "{{ .Values.volume.name }}"
        secret: 
          defaultMode: 420
          secretName: "{{ .Values.volume.secret }}"
      {{- end }}
```
