### ISSUE TITLE
Helm template doesn't call function on upgrade

### ISSUE THREAD

**Issue by cgetzen** [helm/helm#5449]
Goal: Update an annotation if a given value is set in values.yaml
What's actually happening: 
```
 helm upgrade name ./charts/my_chart --set refresh="some_value" --reuse-values
```
When  I set .Values.refresh to "some_value", it does not update the annotation.

Failing snippet:
```
{{- define "resolved" -}}
{{- $repo := index . "repo" -}}
annotation_name: {{- if eq .Values.refresh $repo }} {{ .Release.Revision | quote }} {{- else }} "true" {{- end }}
{{- end -}}

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test_name
  labels: &labels
    ...
  annotations:
    {{ include "resolved" (merge . (dict "repo" "some_value")) | nindent 4 }}
```

Working snippet:
```golang
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test_name
  labels: &labels
    ...
  annotations:
    annotation_name: {{- if eq .Values.refresh "some_value"}} {{ .Release.Revision | quote }} {{- else }} "true" {{- end }}
```

I would expect the two snippets to behave similarly.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:36:43Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.13-eks-g484b8", GitCommit:"484b857e3134d55ac6373fea2f51798fefa0533f", GitTreeState:"clean", BuildDate:"2019-03-08T05:32:36Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

**Comment by hickeyma** [comment]
What are the outputs of both cases when you run with `dry-run`: `helm upgrade --debug --dry-run ..` ?

**Comment by cgetzen** [comment]
Failing snippet:
`helm upgrade name ./charts/my_chart --set refresh="some_value" --reuse-values --debug --dry-run` returns the same as `--set refresh="not_some_value"`:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test_name
  labels: &labels
    ...
  annotations:
    annotation_name: "true"
```

Working snippet:
`helm upgrade name ./charts/my_chart --set refresh="not_some_value" --reuse-values --debug --dry-run` returns the above snippet (annotation_name = true), which is correct. Running the working snippet with `--set refresh="some_value"` also returns my expected output:

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test_name
  labels: &labels
    ...
  annotations:
    annotation_name: "40"
```
