### ISSUE TITLE
Using a multi-line value in a configmap

### ISSUE THREAD

**Issue by cakrit** [helm/helm#5451]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"archive", BuildDate:"2019-03-05T11:25:47Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.4", GitCommit:"618716cbb236fb7ca9cabd822b5947e298ad09f7", GitTreeState:"clean", BuildDate:"2019-02-05T19:22:29Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

---

I've been trying unsuccessfully to have the entire contents of a multi-line configuration file in a `configmap.yaml` specified in `values.yaml`. The hack that got me the closest was to do the following:

In `values.yaml`:
```yaml
somekey: |-
  first line
  second line
  ...
```

In `configmap.yaml`:
```
myfile.conf: {{ toYaml .Values.somekey | indent 2 }}
```

Note: The reason I had to use `toYaml` is that is that the following syntax ends up adding an unexpected, second `|-` :
```
myfile.conf: |-
{{ .Values.somekey | indent 2 }}
```

The hack eliminates the `error converting YAML to JSON` errors and produces an output that looks almost identical to putting the lines directly in `configmap.yaml`, i.e.
```
myfile.conf:   |-
  first line
  second line
  ...
```

I expected the additional spaces after the first `:` to not matter and indeed I don't see any warnings about that. The error I get though is the following (cutting some of it, because it's a big long):
```
Error: ConfigMap "..." is invalid: [metadata.labels: Invalid value: "first line\n  second line\n...": must be no more than 63 characters, ... a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), ...
```

Of course there are no problems when I don't do the substitution. 

Are there any workarounds you could suggest, so that we don't ask users to download the chart and edit the configmap manually? `values.yaml` is an excellent way to do it, but our configuration files have many hundreds of possible, complex settings and it's impossible to add individual parameters for each one.

**Comment by cakrit** [comment]
It does work with `{ toYaml .Values.somekey | indent 2 }}`. The error was completely unrelated, an error earlier in the configmap.

**Comment by antonalechnovic** [comment]
I think this should be included into documentation, should not scramble through non working solution on stackoverflow:

https://stackoverflow.com/questions/50951124/multiline-string-to-a-variable-in-a-helm-template

and thanks for including sample :bowing_man:

**Comment by vigneshsweekaran** [comment]
> It does work with `{ toYaml .Values.somekey | indent 2 }}`. The error was completely unrelated, an error earlier in the configmap.

Its works and its additionally inserting ---- in first line of the content

**Comment by ypicard** [comment]
This is driving me mad. Could someone please post a clean example on how to do this?

**Comment by ypicard** [comment]
Answering my own comment after struggling way more than I should have for what seems a simple task.
In my Helm chart, I have the following:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-name
data: 
  configMapKey: {{ toYaml .Values.my-multiline-value | indent 2 }} # This is where black magic happens
---
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  ...
  template:
    ...
    spec:
      containers:
        - name: my-container-name
          image: my-image-name
          ...
          volumeMounts:
          - name: my-config-volume
            mountPath: /path/in/container
            subPath: configMapKey
      volumes:
        - name: my-config-volume
          configMap:
            name: my-config-name
```
And in the values file I use to deploy it:
```
my-multiline-value: | # Use the pipe for the YAML multiline string
  why
  was
  this
  so
  hard
  ?
```

**Comment by ZiaUrRehman-GBI** [comment]
values.yaml
```
  command: |
    until curl -fsI http://127.0.0.1:15021/healthz/ready; do echo \"Waiting for Sidecar...\"; sleep 5; done;
    echo \"Sidecar available. Running the command...\";
```
cronjob.yaml
```
              command:
              - "/bin/sh"
              - "-c"
              - {{- toYaml .Values.cronjob.command | nindent 16 -}}
```
helm template dry run result is below
```
 helm template helm/ --dry-run
apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: demo
              image: busybox:latest
              command:
              - "/bin/sh"
              - "-c"
              -
                |
                  until curl -fsI http://127.0.0.1:15021/healthz/ready; do echo \"Waiting for Sidecar...\"; sleep 5; done;
                  echo \"Sidecar available. Running the command...\";
```
it add the command in new line
