### ISSUE TITLE
When release status is PENDING_UPGRADE, helm upgrade --install will error "... has no deployed releases", --install --force will error "a released named ... is in use, cannot re-use a name that is still in use"

### ISSUE THREAD

**Issue by Nowaker** [helm/helm#5513]
Sometimes, my `helm upgrade --install` will fail with `transport is closing` error (timeout), then the release will enter `PENDING_UPGRADE` status and all subsequent `helm upgrade --install` will result in:

- `Error: UPGRADE FAILED: "namehere" has no deployed releases` if `--force` is NOT passed
- `Error: UPGRADE FAILED: a released named namehere is in use, cannot re-use a name that is still in use` if `--force` IS passed

There are no YAML errors in the deployment. It deploys correctly when a different release name is provided.

A general way to recover from this problem is:
```
helm history <namehere>
# note the revision number of the revision before PENDING_UPGRADE
helm rollback <namehere> <revision number>
```

And an automated one that's confirmed working in our CI:
```
TIMEOUT=600
ENV_NAME="release-name"
RELEASE_STATUS=$(helm history "$ENV_NAME" --max 1 -o json | jq -r '.[0].status')
if [ "$RELEASE_STATUS" == 'PENDING_UPGRADE' ]; then
  # Find the highest revision number with status SUPERSEDED.
  GOOD_REVISION=$(helm history "$ENV_NAME" -o json | jq '[.[] | select(.status == "SUPERSEDED")] | max_by(.revision) | .revision')
  helm rollback --wait --timeout "$TIMEOUT" "$ENV_NAME" "$GOOD_REVISION"
fi
```

The biggest problem of this is it requires some custom self-baked code that recovers Helm release from this failed status. Heavy reliance on parsing some data structures is a red flag. `helm upgrade --install` is expected to be idempotent, so no `rollback` action should be required in the first place.

- Output of `helm version`: v2.12.3
- Output of `kubectl version`: client v1.12.5, server v1.12.4
- Cloud Provider/Platform (AKS, GKE, Minikube etc.): vanilla Kubernetes

Note: this error happened on previous versions of Helm and Kubernetes.

Related to: https://github.com/helm/helm/issues/4174 - I believe https://github.com/helm/helm/pull/4176 did not fix the problem as it's just an error message pimp-up. CC @bacongobbler

**Comment by JustDoItSascha** [comment]
Is there any fix in sight?

**Comment by allen-servedio** [comment]
Has anyone tried using `--atomic` with this to see if that addresses the issue (by doing an automatic rollback on a failed deploy)?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. I'm certain both a `helm rollback` or a `helm upgrade --atomic` should handle this case, but please let us know otherwise. Thanks.

**Comment by lkysow** [comment]
I do think this is reproducible. Unless this is a different issue?

```
helm version
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

```
mkdir -p /tmp/test /tmp/test/templates
cat <<EOF > /tmp/test/Chart.yaml
apiVersion: v1
name: upgrade-test
version: 0.0.1
EOF

cat <<EOF > /tmp/test/templates/pre-install.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install
  annotations:
    "helm.sh/hook": pre-install
spec:
  backoffLimit:  1
  template:
    metadata:
      name: pre-install
    spec:
      restartPolicy: Never
      containers:
        - name: fail
          image: "alpine"
          command:
            - "exit"
            - "1"
EOF
```

```
cd /tmp/test
helm install test ./
Error: failed pre-install: job failed: BackoffLimitExceeded
```

```
helm list
NAME	NAMESPACE	REVISION	UPDATED                             	STATUS	CHART              	
test	default  	1       	2020-08-18 14:28:19.357787 -0700 PDT	failed	upgrade-test-0.0.1
```

```
helm upgrade test ./
Error: UPGRADE FAILED: "test" has no deployed releases
```

```
helm upgrade --atomic test ./
Error: UPGRADE FAILED: "test" has no deployed releases
```

```
helm rollback test
Error: release: not found
```

```
helm install test ./
Error: cannot re-use a name that is still in use
```
