### ISSUE TITLE
`.Release.Namespace` renders empty in `_helpers.tpl`

### ISSUE THREAD

**Issue by FrostyLeaf** [helm/helm#5535]
Add a definition into `_helpers.tpl`:

```yaml
{{- define "appRelease.defaultSvcHostSuffix" }}
{{- .Release.Namespace -}}.svc.cluster.local
{{ end }}
```

Define a yaml file like below:

```yaml
{{- $fullname := include "appRelease.fullname" . -}}
...
spec:
  host:
  - {{ $fullname }}.{{ template "appRelease.defaultSvcHostSuffix" }}
...
```

And render this file with `helm template` command:

```bash
helm template ./chart_dir --name hello --namespace test-namespace > output.yml
```

Then get this:

```yaml
...
spec:
  host:
  - hello..svc.cluster.local # expect `hello.test-namespace.svc.cluster.local`
...
```

Output of `helm version`: 

```bash
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`: None

Cloud Provider/Platform (AKS, GKE, Minikube etc.): None
