### ISSUE TITLE
Can not work helm with local persistent volume

### ISSUE THREAD

**Issue by tetrar124** [helm/helm#5536]
I tried to use helm with a local persistent volume for stable/grafana or stable/mysql. Because I want to use the file of local persistent volume to construct other local kubernetes with same data and settings by using the file sharing system of clouds. 

After setting local persistentVolume and persistentVolumeClaim, the pods of grafana or mysql with helm was running and no errors, but mounted files were not made in the local folder and persistence did not work.

These settings worked fine without helm.

Please tell me how to fix these problems?

pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv001
  labels:
    type: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: hostpath
  local:
    path: /host_mnt/C/k/share/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
```
pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mysql-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath
  selector:
    matchLabels:
      type: mysql
```
mysqlConf.yaml
```
storageClass: hostpath
existingClaim: local-mysql-claim
accessMode: ReadWriteOnce
```
helm version: 2.13
kubectl version: 1.14
Platform: docker for windows
