### ISSUE TITLE
.Files.Get inside Range not working

### ISSUE THREAD

**Issue by discostur** [helm/helm#5547]
I'm trying to generate multiple k8s TLS secrets. I want to have one loop which generates all of the k8s secrets:

**values.yaml**
```
sslcertificates:
  - name: wildcard.domain.com
      tlscrt: wildcard.domain.com.crt
      tlskey: wildcard.domain.com.key
```

I tried different templates:

**chart/templates/secret.yaml**
```
{{- $root := . }}
{{- $files := .Files }}
{{- range .Values.sslcertificates}}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-{{ .name }}
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ $files.Get .tlscrt | b64enc }}
  tls.key: |-
    {{ $files.Get .tlskey | b64enc }}
{{- end }}
```

**chart/templates/secret.yaml**
```
{{- $root := . }}
{{- range $index, $val := .Values.sslcertificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-{{ $val.name }}
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ $.Files.Get $val.tlscrt | b64enc }}
  tls.key: |-
    {{ $.Files.Get $val.tlskey | b64enc }}
{{- end }}
```

result both in the following output (which is missing the TLS data):
```
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-wildcard.domain.com
type: kubernetes.io/tls
data:
  tls.crt: |-
    
  tls.key: |-
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
Can you check and confirm that the indentation level in your values.yaml is correct? I've seen it happen where indenting the list incorrectly results in the keys being in the wrong object. That might explain why they're unavailable.

**Comment by discostur** [comment]
@bacongobbler there was an copy / paste error, values.yaml is like that:

```
sslcertificates:
  - name: wildcard.domain.com
    tlscrt: wildcard.domain.com.crt
    tlskey: wildcard.domain.com.key
``` 

Should be correct ...
