### ISSUE TITLE
Helm unexpectedly breaks long lines to several lines during rendering a template

### ISSUE THREAD

**Issue by homelessnessbo** [helm/helm#5568]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:
Not relevant.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Not relevant.

An example of a template:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  name: my_lovely_configmap
data:
  my_key: |-
    {{- .Values.first_layer.second.third | default dict | toYaml | trim | nindent 4 }}
```

Values file (`description` value is one long string with spaces):
```
first_layer:
  second:
    third:
      fourth:
      - name: first_array_element
        another_layer:
        - annotations:
            description: asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas
```

Rendering command:
`helm-2.13.1 template -f bug_reproduce_values  --execute templates/bug-reproduce.yaml  helm-charts/bug-reproduce`

Rendering result (`description` value is split to several lines.):

```
---
# Source: bug-reproduce/templates/bug-reproduce.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  name: my_lovely_configmap
data:
  my_key: |-
    fourth:
    - another_layer:
      - annotations:
          description: asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas
            asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas asdasdasdas
            asdasdasdas asdasdasdas
      name: first_array_element
```

I've tried to play with several helm versions - didn't help much. I also noticed that helm starts to break the line only if there's whitespace met after a certain character number (~73th ??? :O).

Changing `  my_key: |-` to others like `>` or just `|` also doesn't help. Quoting the value also doesn't help.

Rendering is broken both when you do `helm template` and `helm upgrade/install`.
