### ISSUE TITLE
helm search didn't show versions named by git commit

### ISSUE THREAD

**Issue by YoninL** [helm/helm#5636]
`helm version`:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

## repo cache index file:
```
apiVersion: v1
entries:
  test:
  - apiVersion: v1
    created: "2019-04-08T03:05:31Z"
    description: A Helm chart for Kubernetes
    digest: e430c2cf2c92779e52acb55f1b2dffe59c4730c05d58806fa2bc6d942713f4be
    name: test
    tillerVersion: '>=2.10.0'
    urls:
    - charts/test-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    created: "2019-04-24T04:00:25Z"
    description: A Helm chart for Kubernetes
    digest: be09d34d3e08a2cd9eb682c9168d0bf382bffdbe87324b96fe6cb3f3affea9ac
    name: test
    tillerVersion: '>=2.10.0'
    urls:
    - charts/test-d80a763.tgz
    version: d80a763
```

## helm search result:
```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "chartmuseum" chart repository
hel...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
$ helm search test
NAME                            CHART VERSION   APP VERSION DESCRIPTION
chartmuseum/test                 0.1.0                       A Helm chart for Kubernetes
```
helm install will also ignore version `d80a763`.

## Expected result:
Chart version `d80a763` should be displayed.
