### ISSUE TITLE
File encoding makes `helm install` got error 

### ISSUE THREAD

**Issue by mumutu66** [helm/helm#5638]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Alicloud

System Env:

```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

the problem in brief is the file with encoding UTF-8 which I create by the notepad on Windows make `helm install` fails  and got the k8s api error `Error: unable to recognize "": no matches for kind "HorizontalPodAutoscaler" in version ""`

the content is copied from stable/nginx-controller/controller-hpa

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name:  nginx-ingress-controller
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: example
  minReplicas: 1
  maxReplicas: 11
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 50


```
using enca can see the file encoding is UTF-8
```
enca -L none hpa-wrong.yaml 
Universal transformation format 8 bits; UTF-8

```
but using kubectl apply -f hpa-wrong.yaml  no error occurs

the result diff with a `Right` file 

```
diff hpa-wrong.yaml hpa-right.yaml 
1c1
< ﻿apiVersion: autoscaling/v2beta1
---
> apiVersion: autoscaling/v2beta1

```

and can always reproduce by using the iconv

```
#from wrong to right
iconv -f utf-8 -t ascii//TRANSLIT hpa-wrong.yaml -o hpa-right.yaml

#from right to wrong 
iconv -t utf-16 -f ascii//TRANSLIT hpa-right.yaml -o hpa-wrong-16.yaml
iconv -t utf-8 -f utf-16le hpa-wrong-16.yaml -o hpa-wrong.yaml

```

I have no idea it is a bug or some kind of constraint
