### ISSUE TITLE
Create CI friendly Docker image

### ISSUE THREAD

**Issue by remcohaszing** [helm/helm#5682]
A Docker image for Helm / Tiller exists on `gcr.io/kubernetes-helm/tiller:v2.13.1`.

However, details about this image are vague.

- It isn’t mentioned in the readme.
- No version `latest` is available.
- The entry point is not a shell.

The following issues are related: #1929 #2507

Since Helm is typically a tool that is run as part of CI, it makes sense to provide an easy to use Docker image.

For example, to use `helm` in `.gitlab-ci.yaml`, one would need to use the following snippet:

```yaml
job:
  image:
    name: gcr.io/kubernetes-helm/tiller:v2.13.1
    entrypoint: /bin/sh
  script:
    - /helm --client-only
    # Run commands using /helm
```

It would be much more friendly if this just works:

```yaml
job:
  image: gcr.io/kubernetes-helm/helm
  script:
    - helm --client-only
    # Run commands using helm
```

Yes, it is better to explicitly specify a version, but it is also good to have a latest version available instead of getting an error reponse from the Docker daemon that the image can’t be found.

Also for CI the `tiller` binary is unnecessary. It could be omitted to save bandwidth.

I suggest to add a new `Dockerfile` (based on https://github.com/helm/helm/blob/master/rootfs/Dockerfile)

```dockerfile
FROM alpine:3.9

RUN apk add --no-cache ca-certificates socat

COPY helm /bin/helm
```

It might be useful to also add `kubectl`.

Unofficial solutions already exist (https://hub.docker.com/search/?type=image&q=helm), but I believe it’s a bad idea to just trust unofficial Docker images.
