### ISSUE TITLE
Chart repositiory `cache` value in config is ignored

### ISSUE THREAD

**Issue by Hiruma31** [helm/helm#5703]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
NA

Hello !

While trying to configure Helm globally, I stumbled upon an issue with the cache directory.

```
/etc/helm/conf/repository/repositories.yaml
apiVersion: v1
repositories:
- name: test-helm
  [...]
  keyFile: ""
  cache: "/tmp/test-helm-index.yaml"
```

`HELM_HOME=/etc/helm/conf`

All sub-folder exists as generated by helm init, helm repo update creates the -index.yaml file properly in the /tmp folder (with the exception of #5517 ) but when I try to fetch a chart, I get
```
Error: no cached repo found. (try 'helm repo update'). open /etc/helm/conf/repository/cache/test-helm-index.yaml: no such file or directory
```

I believe I narrowed it down to here:
https://github.com/helm/helm/blob/master/pkg/helm/helmpath/helmhome.go#L61

With Helm not actually parsing the`cache:` entry in the config as it should, but deriving it from `HELM_HOME` by appending `/repository/cache`.

Thank you for your time !
