### ISSUE TITLE
Helm v2.14.0 unknown field "rollingUpdate"

### ISSUE THREAD

**Issue by plexcellmedia** [helm/helm#5743]
After upgrading Helm to v2.14.0, I can't upgrade our application.

On upgrading, I get error:
```
Error: error validating "": error validating data: ValidationError(Deployment.spec): unknown field "rollingUpdate" in io.k8s.api.apps.v1.DeploymentSpec
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec): unknown field "rollingUpdate" in io.k8s.api.apps.v1.DeploymentSpec
```
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.10", GitCommit:"aaf0906400b5fc1d858ce0566a571e4f3ed06b9f", GitTreeState:"clean", BuildDate:"2019-03-30T19:30:48Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

What can I do to fix this problem?

**Comment by hickeyma** [comment]
@plexcellmedia I am investigating and trying to reproduce the issue. I need some more details to help me.

Can you show the command you are running and also your deployment template? Have you tried running the upgrade command with `--debug --dry-run` flags and what output do you get with this?

**Comment by plexcellmedia** [comment]
> 
> 
> @plexcellmedia I am investigating and trying to reproduce the issue. I need some more details to help me.
> 
> Can you show the command you are running and also your deployment template? Have you tried running the upgrade command with `--debug --dry-run` flags and what output do you get with this?


Command inside Travis script:
```
helm upgrade --install "$RELEASE_NAME" --namespace="$RELEASE_NAME" --debug --dry-run \
-f ./tools/travis/deploy/env_dist.yaml \
--set imageCredentials.username="${DOCKER_USERNAME}" \
--set imageCredentials.password="${DOCKER_PASSWORD}" \
--set image.repository="${DOCKER_USERNAME}/${DOCKER_REPO}" \
--set image.tag="$TRAVIS_COMMIT" \
./tools/helm-chart && \
rm -fr ./tools/travis/deploy/env_dist.yaml
```

Part of deploy script that uses RollingUpdate
```
web:
  ## If false, web container will not be installed
  ##
  enabled: true

  ## web container name
  ##
  name: 'web'

  ## Number of replica pods
  ##
  replicaCount: 1

  ## Custom Update Strategy
  ##
  updateStrategy:
    type: RollingUpdate

  service:
    type: LoadBalancer
    port: 80
  
  ingress:
    enabled: false
    annotations: {}
    paths: []
    hosts:
      - chart-example.local
    tls: []

  livenessProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 120
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 120
    successThreshold: 1

  resources:
    limits:
      cpu: 150m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 512Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}
```

Deployment.yaml
```
{{- if .Values.web.enabled -}}
  {{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
  {{- else }}
apiVersion: apps/v1beta1
  {{- end }}
kind: Deployment
metadata:
  name: web
  labels:
    app.kubernetes.io/name: {{ include "helm-chart.name" . }}-web
    helm.sh/chart: {{ include "helm-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-web
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm-chart.name" . }}-web
      app.kubernetes.io/instance: {{ .Release.Name }}-web
  strategy:
    type: {{ .Values.web.updateStrategy.type }}
  {{ if and .Values.web.updateStrategy.type (eq .Values.web.updateStrategy.type "RollingUpdate") }}
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helm-chart.name" . }}-web
        app.kubernetes.io/instance: {{ .Release.Name }}-web
    spec:
      imagePullSecrets:
          - name: {{ .Values.image.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: START_MODE
              value: "web"
            - name: WEB_SSL_FULLCHAIN
              value: ssl/fullchain.pem
            - name: WEB_SSL_PRIVKEY
              value: ssl/privkey.key
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          {{- if .Values.web.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: http
              initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.web.livenessProbe.periodSeconds }}
              timeoutSeconds: {{ .Values.web.livenessProbe.timeoutSeconds }}
              successThreshold: {{ .Values.web.livenessProbe.successThreshold }}
              failureThreshold: {{ .Values.web.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.web.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.web.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.web.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.web.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      restartPolicy: "Always"
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.web.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end -}}
```

--debug --dry-run gave no extra information.
