### ISSUE TITLE
Use error level for only things that break the chart installation

### ISSUE THREAD

**Issue by ialidzhikov** [helm/helm#5758]
Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

Output of `kubectl version`: Not applicable

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Not applicable

`helm lint --help` states:
```
If the linter encounters things that will cause the chart to fail installation,
it will emit [ERROR] messages. If it encounters issues that break with convention
or recommendation, it will emit [WARNING] messages.
``` 

Currently helm lint fails when naming convention issue is found:
```
helm lint mychart/
==> Linting mychart/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/scripts/_echo.sh: file extension '.sh' not valid. Valid extensions are .yaml, .yml, .tpl, or .txt

Error: 1 chart(s) linted, 1 chart(s) failed
```

The sample chart:
```
mychart/
  Chart.yaml
  values.yaml
  templates/
    scripts/
      _echo.sh
    pod.yaml
```

_echo.sh
```
{{- define "echo" -}}
{{ required "foo is required" .Values.foo }}
{{- end }}
```

pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - {{ include "echo" . }}
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
```

values.yaml
```
foo: sleep
```

`helm install ./mychart` is successful.

I would expect helm lint to file warning for things that break the convention and errors only for things that break the chart installation. `--strict` should transform the warnings to errors.
