### ISSUE TITLE
helm delete returns error when template contains leading comment

### ISSUE THREAD

**Issue by markwaldkat** [helm/helm#5769]
Certain comments in the templates YAML can break helm delete.

Repro template:

```
# some comment that breaks helm delete
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: somenp
spec:
  podSelector:
    matchLabels:
      label-key: bar
  ingress:
  - ports:
    - port: 8080
    from:
    - podSelector:
        matchLabels:
         key: value
```

`helm install` works fine.
But when I do "helm delete", I get:
`Error: deletion completed with 1 error(s): release "undercooked-dragon": object "" not found, skipping delete`

`helm ls` shows that the release is gone, but still the return code is 1. So this is bad when running `helm delete` in a script.

When I remove the comment, `helm delete` doesn't show the error and the return code is 0.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8", GitCommit:"4e209c9383fa00631d124c8adcc011d617339b3c", GitTreeState:"clean", BuildDate:"2019-02-28T18:49:34Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS
