### ISSUE TITLE
Helm 3 - legacy dependency conditions not respected 

### ISSUE THREAD

**Issue by planetf1** [helm/helm#5780]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1+IKS", GitCommit:"7212ba91727da63ce9cfb2b5eba7f988f0f125d0", GitTreeState:"clean", BuildDate:"2019-05-09T14:28:29Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
IBM Cloud (IKS)

I have a helm 2 chart that includes another chart by this content in requirements.yaml
```
dependencies:
  - name: cp-helm-charts
    version: 0.1.0
    repository: https://confluentinc.github.io/cp-helm-charts/
    condition: kafka.internal.enabled
  - name: openldap
    version: 0.3.0
    repository: https://kubernetes-charts.storage.googleapis.com/
```

However if kafka.internal.enabled is set to false (in my case values.yaml sets it to true, but I have content in an additional file specified by '-f ~/cloud.yaml which sets it to false), the cp-helm-chart (confluent kafka) IS deployed regardless

**Comment by jdolitsky** [comment]
@planetf1 thanks for opening

Perhaps somehow related to https://github.com/helm/helm/issues/5757

**Comment by hd-rk** [comment]
This issue happens even for dependencies specified in `Chart.yaml`. I have set up an example at https://github.com/hd-rk/helm-examples/tree/develop/v3-condition.

I took a look at the code, it might be because the function for processing sub-chart conditions/tags is not called in `action.Install.Run`
https://github.com/helm/helm/blob/ff818fceca20a4a5414fa26bcf63a305c6ef9343/pkg/chartutil/dependencies.go#L27-L32

Howerver, it's actually called in `action.Upgrade.Run`
https://github.com/helm/helm/blob/ff818fceca20a4a5414fa26bcf63a305c6ef9343/pkg/action/upgrade.go#L67-L70

**Comment by bacongobbler** [comment]
closed via #6084

**Comment by planetf1** [comment]
I cloned the helm repo and rebuild dev-v3 (as of today).
I then retried the deployment of a chart which worked ok with helm2

I hit the same problem as originally reported.

**Comment by planetf1** [comment]
I built from dev-v3 and can confirm the issue is fixed

**Comment by connorearl** [comment]
Running 3.0.1 and I seem to be running into this issue. Using helm package or helm install, with the condition set to false, it still asks me to run a dependency update, which downloads the dependency marked as not enabled. When I package it, it removes the condition in the archive, and if I install it direct, it ignores it.

**Comment by zzarkouna** [comment]
running 3.0.2 
```
apiVersion: v2
description: A Kong chart for Kubernetes
name: kong
version: 0.1.0

dependencies:
- name: postgres
  version: "0.1.0"
  repository: "file://../postgres"
  condition: postgres.enabled, kong.postgres.enabled
- name: gcloud-sqlproxy
  version: "0.1.0"
  repository: "file://../gcloud-sqlproxy"
  condition: gcloud-sqlproxy.enabled, kong.gcloud-sqlproxy.enabled
```
and values.yaml
```
gcloud-sqlproxy:
  enabled: false
postgres:
  enabled: false
```
helm packages ask me to run a dependency update 
and when it package it don't remove deps  
and when upgrade neither

**Comment by rhefner1** [comment]
I'm also facing an issue where this isn't working correctly.

I have an umbrella chart:
```
apiVersion: v2
name: base
version: 1.0.0

dependencies:
  - name: auth-proxy
    version: 1.0.0
    repository: "file://../../subcharts/auth-proxy"
    condition: auth-proxy.enabled
```

And the auth-proxy subchart:

```
apiVersion: v2
name: auth-proxy
version: 1.0.0

dependencies:
  - name: bypasser-nginx
    version: 1.0.0
    repository: "file://subcharts/bypasser-nginx"
    condition: auth-proxy.bypasser.enabled
```

And the values.yaml for the base (umbrella) chart:

```
auth-proxy:
  enabled: true

  bypasser-nginx:
    enabled: false
```

In Helm 2, this worked correctly. In Helm 3.0.2, the bypasser-nginx chart is deployed. This is a conditional dependency inside of another dependency, so I know that it's a bit complicated. But this definitely looks like an unintended behavior change from 2 to 3 (and a breaking change).

@bacongobbler can you please consider reopening this issue?

**Comment by marcadella** [comment]
Still not working one year later (v3.1.1)...

**Comment by technosophos** [comment]
@marcadella Did you have a particular use case that broke? Please provide more details.

**Comment by marcadella** [comment]
@technosophos I stopped using Helm because of this (and many other issues). But there has been example posted above such as [this one](https://github.com/helm/helm/issues/5780#issuecomment-579667566) describing thoroughly the issue.

**Comment by technosophos** [comment]
I am aware of several issues, @marcadella, and am in the process of finding and fixing as many as I can. There are actually several intertwined issues that seem to combine in different ways. When I saw your issue above, I thought that perhaps you would like to contribute a problem case so that I could continue my list.

This particular feature was hit hard by the loss of the core maintainer who wrote and maintained this code. The rest of us are trying to learn how these features are supposed to work. So it has been hard going for us. We almost just removed the entire set of features... but lots of people seem to at least want to use them. So I've taken on the task of trying to untangle the net.

**Comment by kchaber** [comment]
This issues have already been present in v2 (#4490, #3734) and fixed by #4917, which per comments should be merged into v3. It looks like we still don't have this fix here - it hasn't been mentioned in any release notes for v3.

**Comment by bacongobbler** [comment]
That PR you mentioned was merged into helm 3.0.0-beta.4.

**Comment by riker09** [comment]
At first I thought I was affected by this, then it turned out I was just stupid. But I want to share my findings in case that someone here tripped about the same thing:

After defining a dependency in a childchart, you must `helm dep up` in the parent chart, otherwise the changes are not pulled in (for obvious reasons). Here is my working configuration:

```yaml
## Child Chart.yaml
apiVersion: v2
name: child
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
- name: mssql-linux
  alias: mssql
  repository: https://kubernetes-charts.storage.googleapis.com
  version: ~0.11.2
  condition: mssql.enabled
```

```yaml
## Parent Chart.yaml
# ...
dependencies:
- name: child
  version: 0.1.0
  repository: file://../child/
```

```yaml
## values.yaml
child:
  mssql:
    enabled: false
```

Setting the value `child.mssql.enabled` to `true` will render the child > child dependency again. 👍

**Comment by SinisterMinister** [comment]
I just ran into this after converting all of my v2 charts to v3 charts after following [the documentation](https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags). Can we please remove this section or at least call out that this feature doesn't actually exist in v3.x yet?

Is there any effort happening on this anymore?

**Comment by madchap** [comment]
Running into this as well, helm 3.3.4.

**Comment by dmittriy13** [comment]
> Running into this as well, helm 3.3.4.

We have the same problem with this helm version

@bacongobbler can you please consider reopening this issue?

**Comment by benjamin658** [comment]
We are facing the same issue as well on helm 3.5.3.

Currently, we use `tag` as a workaround:

```yaml
# parent values.yaml

tags:
  subchart-enabled: true
```

```yaml
# parent Chart.yaml
dependencies:
- name: subchart
   ...
   tags:
   -  subchart-enabled
```

for more information, please visit: https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags

By the way, the issue should be reopened or simply remove the conditions part from the doc, it's really confusing.

**Comment by trynaeat** [comment]
Same issue in 3.6.0. The tags workaround suggested by @benjamin658 doesn't appear to work either.

Please, at the very least remove the page on conditions/tags from the docs. Even better, explicitly document that this is not possible and suggest design alternatives. I wasted way too much time figuring this out because of this nonexistent feature being documented.

**Comment by mrhydejc** [comment]
Does anyone have an example that works with Helm 3.7.1 to exclude an optionnal dependency ?

**Comment by rohitss912** [comment]
> ```yaml
> tags:
>   subchart-enabled: true
> ```

I can confirm this workaround with `tags` worked for me. I used HELM 3.7.1!
The `conditions` still doesn't seem to work as expected.

**Comment by bmitchinson** [comment]
similar to [riker09](https://github.com/riker09)'s comment in case some are stuck: 

I was doing everything right, but forgot that the chart still had the following at the top of `Chart.yaml`

```yaml
apiVersion: v1
...
```

You do need to be on helm 3, but you also need to ensure your chart apiVersion is `v2`
```yaml
apiVersion: v2
...
```

**Comment by planetf1** [comment]
Since I originally opened I felt obliged to add a quick update as I see the discussion is still going here -->  I have refactored. All is now working. Dependencies are now in Chart.yaml. API version is v2, and conditions are working fine

**Comment by chandanghoshsfos** [comment]
@planetf1 With latest helm 3.10, api V2 I am still seeing the issue. Which version of Hem you are using? Can you please share any sample chart to test ?

**Comment by planetf1** [comment]
@chandanghoshsfos I use it a few of our egeria helm charts, for example [egeria-base](https://github.com/odpi/egeria-charts/tree/main/charts/egeria-base) . 

We require 'strimzi' to setup these examples, so in our [Chart.yam](https://github.com/odpi/egeria-charts/blob/main/charts/egeria-base/Chart.yaml)l we depend on it by:

```
dependencies:
  - name: strimzi-kafka-operator
    version: 0.32.0
    repository: https://strimzi.io/charts/
    condition: strimzi.enabled
```

Then for our chart, in the [values.yaml](https://github.com/odpi/egeria-charts/blob/main/charts/egeria-base/values.yaml)  file I default this to true
```
# Normally we install the strimzi operator as part of the Chart. However this requires admin permissions, and
# will create cluster-scoped resources. Set to false to skip this when in a restricted environment, or needing multiple
# installs of egeria charts in the same cluster. Requires the strimzi operator to be
# installed on the cluster by an admin, or a prior install
strimzi:
  enabled: true
  ```
  
In our [docs](https://egeria-project.org/guides/operations/kubernetes/charts/overview/?h=strimzi.enabled#strimzi-permissions-and-co-existance) we tell users to specify an extra parameter if they want to omit strimzi ie:

```
helm install base egeria-base --set strimzi.enabled=false
```

This all works a treat. Hope that helps and feel free to ask any other questions about our simple example.
