### ISSUE TITLE
helm v2.14.0 - does not recognize 'release' & 'heritage' in metadata

### ISSUE THREAD

**Issue by vishiy** [helm/helm#5782]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"} 
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:59:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

I see an error if i have 'release' or 'heritage' in metadata :-
example : https://github.com/helm/charts/blob/164ee72d34f9f8e7888c0619186983d108019165/incubator/azuremonitor-containers/templates/omsagent-rs-configmap.yaml#L227

Error: validation failed: error validating "": error validating data: [ValidationError(ConfigMap.metadata): unknown field "chart" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta, ValidationError(ConfigMap.metadata): unknown field "heritage" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta, ValidationError(ConfigMap.metadata): unknown field "release" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta]

Is this deprecated ? I dont see any breaking changes in v2.14.0 release notes.

All works when using v2.13.1

**Comment by mattfarina** [comment]
I had to look at this for a moment to figure it out. The problem is with the chart. It looks like there have been validation improvements in a dependency.

In a bunch of places there are things like...
```yaml
name: omsagentclusterrolebinding
chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
release: {{ .Release.Name }}
heritage: {{ .Release.Service }}
```

That should instead be...
```yaml
name: omsagentclusterrolebinding
labels:
  chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
```

Notice how `labels` is missing.
