### ISSUE TITLE
Helm discovery report

### ISSUE THREAD

**Issue by nicgirault** [helm/helm#5799]
I started using Helm this week and spent  ~20 hours playing with Helm. I thanks all the team for this project.

I wanted to share a discovery report. I might say things that can already be doable but in this case I would suggest to consider to clarify the doc since I read carefully the doc and didn't find my answer.

- when I write `helm install nginx-ingress` I would expect `nginx-ingress` to be added to `requirements.yaml`

- "release" keyword is misleading. I started calling my releases v1, v2, v3 etc and then I understood that release is actually an instance of the chart.

- I would like to decorelate the fact to add a dependency to the chart I'm building and to deploy the dependency. I would expect `helm install xxx` to fetch the dependency and add it to my list of dependencies. Nothing more. `helm deploy` would then connect to my cluster.

- I'm still struggling to build my charts with a dependency used twice. For example I use https://hub.helm.sh/charts/incubator/aws-alb-ingress-controller and would like to instanciate this chart twice. To do so I would love to write something like this in `values.yaml`:

```yaml
aws-alb-ingress-controller:
  instance1:
    namespace: 'default'
    autoDiscoverAwsRegion: true
    autoDiscoverAwsVpcID: true
  instance2:
    namespace: 'monitoring'
    autoDiscoverAwsRegion: true
    autoDiscoverAwsVpcID: true
```

- It's really surprising that some of the most used Helm charts are not in a standard repository. I would like to be able to write `helm install nginx-ingress` without adding a repo first.

- I don't know if this feedback will be deprecated in helm 3 but I don't want to install tiller and thus I use helm like this: `helm template --name main . -f config.yaml | kubectl apply -f -` which seems to be a trick. I spent hours to find this solution but it seems to me that it should be the standard way to do.
