### ISSUE TITLE
chart builtins hook type

### ISSUE THREAD

**Issue by jasonkuhrt** [helm/helm#5801]
We have a case wherein our chart template would benefit from having access to a new [builtin](https://github.com/helm/helm/blob/master/docs/chart_template_guide/builtin_objects.md containing what lifecycle phase the release is in (`install` or `upgrade` or `delete` etc.)

Consider this job, where we would like to pass the lifecycle phase as a JSON value to service being called.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: locksmith-request
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: job
          image: appropriate/curl
          args:
            - --silent
            - some.thing/here
            - --header
            - 'content-type: application/json'
            - --data
            - '{ "phase": "{{ .Release.LifecyclePhase }}" }'
```

This is because the service we are calling needs to do something different between `install/upgrade` cases and `delete` case.

One possible workaround that we thought of so far is if `Release.IsUpgrade` and `Release.IsInstall` are not `true` then infer `IsDelete`.
