### ISSUE TITLE
prometheus-operator and thanos: dynamic externalLabels to be used on --query.replica-label

### ISSUE THREAD

**Issue by caarlos0** [helm/helm#5805]
Thanos query component has a flag called `--query.replica-label`, which is used to deduplicate metrics.

The idea is, for example, when I have 2 prometheus instances, one will have:

```yaml
global:
  external_labels:
    replica: 0
```

and the other

```yaml
global:
  external_labels:
    replica: 1
```

and when I run the query component, I set `--query.replica-label=replica`, so it can deduplicate metrics.

That being said, is there a way to set this "dynamically" in each prometheus replica? It could be even the pod name or something, I tried to find ways to do this but couldn't.

Sorry if this is not the right place to ask.

Thanks in advance.

---

FWIW here is my WIP thanos + prometheus-operator chart: https://github.com/caarlos0/thanos-helm-chart
