### ISSUE TITLE
Helm 3: --wait flag does not seem to wait.

### ISSUE THREAD

**Issue by jeremyje** [helm/helm#5814]
I ran the following command which you can [find in the open-match Makefile](https://github.com/jeremyje/open-match/blob/helmet/Makefile#L272). It does not seem that `--wait` waits for the resources to be ready. This is from a new GKE cluster and can also repro by deleting the chart via `helm delete open-match`.

The output that comes out is:

```bash
helm upgrade open-match --install --wait --debug install/helm/open-match \
        --timeout=10m \
        --namespace=open-match \
        --set openmatch.image.registry=gcr.io/jeremyedwards-gaming-dev \
        --set openmatch.image.tag=0.0.0-dev-67e02bd \
        --set grafana.enabled=true \
        --set jaeger.enabled=true \
        --set prometheus.enabled=true \
        --set redis.enabled=true \
        --set openmatch.monitoring.stackdriver.enabled=true \
        --set openmatch.monitoring.stackdriver.gcpProjectId=jeremyedwards-gaming-dev \
        --debug
history.go:108: [debug] getting history for release open-match
Release "open-match" does not exist. Installing it now.
printer.go:84: [debug] Original chart version: ""
printer.go:84: [debug] CHART PATH: /usr/local/google/home/jeremyedwards/workspace/helm/open-match/install/helm/open-match

client.go:78: [debug] building resources from manifest
client.go:83: [debug] creating 79 resource(s)
wait.go:47: [debug] beginning wait for 79 resources with timeout of 10m0s
```
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.0", GitCommit:"14c9138d6fb5b57473e270fe8a2973300fbd6fd6", GitTreeState:"clean", BuildDate:"2019-05-08T16:22:55Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`GKE`

**Comment by bacongobbler** [comment]
As of right now, `--wait` is partially re-implemented in Helm 3. We've done some refactoring in https://github.com/helm/helm/pull/5735 to clean up the client interface. We're planning on restoring `--wait` but wanted to take the time to re-think the internal design.

cc @adamreese

**Comment by bacongobbler** [comment]
@thomastaylor312 is this safe to close now that #5961, #5970 and #5971 have been merged?

**Comment by thomastaylor312** [comment]
Yes. Sorry I missed this issue. @jeremyje please let me know if you see any more problems

**Comment by shreben** [comment]
Hi
I'm using Helm 3.0.1 and `--wait` still doesn't seem to work. 
I've deployed a broken chart with wrong image reference and `helm`  marked a release as deployed even despite of the fact that pod failed to start. 
Helm version:
`version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}`
Output of `helm install ...`:
```
install.go:148: [debug] Original chart version: ""
install.go:165: [debug] CHART PATH: /home/test/test-service

client.go:87: [debug] creating 6 resource(s)
wait.go:51: [debug] beginning wait for 6 resources with timeout of 5m0s
NAME: testing
LAST DEPLOYED: Mon Dec 16 13:06:04 2019
NAMESPACE: test
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
```

**Comment by thomastaylor312** [comment]
@shreben Can you share your chart? Generally when that happens it is due to only having 1 replica in your Deployment. However, I have also see it happen where a pod is "flapping" (it goes ready for a bit and then fails). If there is a problem here, we should probably isolate what it doesn't wait for and open a new issue

**Comment by shreben** [comment]
Hi
I'm using a custom chart developed by myself from scratch.
Here is my resultant deployment.yaml after templating:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-base
  namespace: test
  labels:    
    app.kubernetes.io/name: base
    app.kubernetes.io/instance: dev-base
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: 
    helm.sh/chart: base-1.2.0
    helm.sh/release: dev
  annotations:
    kubernetes.io/change-cause: 1.2.0
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dev-base
  template:
    metadata:
      labels:        
        app.kubernetes.io/name: base
        app.kubernetes.io/instance: dev-base
        app.kubernetes.io/managed-by: helm
        app.kubernetes.io/part-of: 
        helm.sh/chart: base-1.2.0
        helm.sh/release: dev        
      annotations:
        checksum/config: 6f72dbccb8d1a3d882ec9b648ae9dfd9a24c2fea5d730e1eecc90569496bcc0e
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/-system/prometheus"
    spec:
      serviceAccountName: "default"
      automountServiceAccountToken: false
      containers:
        - name: dev-base
          image: "/kubernetes-demo-service:"
          imagePullPolicy: Always
          env:
          - name: JVM_ARGS
            value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8082"
          - name: JVM_INIT_MEM
            value: "256M"
          - name: JVM_MAX_MEM
            value: "256M"
          livenessProbe:
            httpGet:
              path: /-system/health
              port: 8081
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /-system/health
              port: 8081
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
          - name: config
            mountPath: /config/application.yml
            readOnly: true
            subPath: application.yml
          resources:
            limits:
              cpu: 1
              memory: 512M
            requests:
              cpu: 0.25
              memory: 512M
      volumes:
        - name: config
          configMap:
            defaultMode: 0444
            name: dev-base
```
Number of replicas is 1, indeed. I suppose "flapping" didn't take place because of completely wrong image reference, pod cannot start by any circumstances.
So, as I understood, correct me if I'm wrong, `--wait` will only work if there are at least 2 replicas?
