### ISSUE TITLE
How to `define` an always unique template name and refer to the name?

### ISSUE THREAD

**Issue by kivagant-ba** [helm/helm#5823]
I'm using the chart:
https://github.com/helm/charts/tree/master/incubator/common

And it requires the following syntax in a `templates/deployment-1.yaml`:

```yaml
{{- template "common.deployment" (list . "mychart.deployment") -}}
{{- define "mychart.deployment" -}}
## Define overrides for your Deployment resource here, e.g.
spec:
  template:
    spec:
      containers:
      - {{ template "common.container" (list . "mychart.deployment.container") }}
{{- end -}}
{{- define "mychart.deployment.container" -}}
## Define overrides for your Container here, e.g.
...
{{- end -}}
```

The problem is that if I have many templates for deployments, e.g.:
```
templates/
  deployment-1.yaml
  deployment-2.yaml
  ...
  deployment-N.yaml
```

...they can't re-use the same constructions `{{- define "mychart.deployment" -}}` and `{{- define "mychart.deployment.container" -}}` because template names must be unique (https://github.com/technosophos/k8s-helm/blob/master/docs/chart_template_guide/named_templates.md#named-templates). The thing is that I have already defined a unique name for the deployment using the trick:

```
{{- $_ := set .Values "fullnameOverride" "my-application-1" -}}
{{- include "common.deployment" (list . "this.deployment") -}}
....
```

...and now I need to copy the name such as "my-application-1" at least 2 times more just to define a unique deployment.

The final code now looks like in this example:

```yaml
# Source of templates/deployment-1.yaml
{{- $_ := set .Values "fullnameOverride" "my-application-1" -}}
{{- include "common.deployment" (list . ( print .Values.fullnameOverride ".deployment" )) -}}
{{- define "my-application-1.deployment" -}}
## Define overrides for your Deployment resource here
spec:
  template:
    spec:
      containers:
      - {{ template "common.container" ( list . ( print .Values.fullnameOverride ".deployment.container-1" )) }}
      - {{ template "common.container" ( list . ( print .Values.fullnameOverride ".deployment.container-2" )) }}
# ...
{{- end -}}
{{- define "my-application-1.deployment.container-1" -}}
## Define overrides for your Container here
command: date 
{{- end -}}
{{- define "my-application-1.deployment.container-2" -}}
## Define overrides for your Container here
command: date 
{{- end -}}
```

In this example `my-application-1` copied 4 times (after some optimization). For some reason `define` doesn't accept any dynamic arguments. I wish I could run it like this: 
```
{{- define (print .Values.fullnameOverride ".deployment.container-1") -}}
```

Does Helm or Go Templates support some syntax sugar that can help to DRY in this case?
