### ISSUE TITLE
can't upgrade charts with crd changes

### ISSUE THREAD

**Issue by caarlos0** [helm/helm#5853]
I have a custom chart for an operator we're writing.

The operator is under development, so it receives several changes... now, we needed to add a new non-required boolean field to the CRD.

When trying to upgrade it, I got this error:

```
UPGRADE FAILED
Error: failed to create patch: merging an object in json but data type is not struct, instead is: map
Error: UPGRADE FAILED: failed to create patch: merging an object in json but data type is not struct, instead is: map
```

The only things changed are the new field on the CRD and the image tag.

If I remove the new field from the CRD and upgrade it works.

What can I do to avoid this?

---
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.6", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-05-23T11:42:40Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

GKE

**Comment by caarlos0** [comment]
I tried to update the crd with `kubectl apply`, still helm fails...

**Comment by karuppiah7890** [comment]
@caarlos0 I tried debugging this, looks like more information is needed to debug why exactly this happened. Information about your CRD and the new field that you mentioned.

Let me put here what I found/guessed based on the details in hand - we know it's a CRD and we know the error message :

This is the place where the error occurs: 
https://github.com/helm/helm/blob/0d81d92a01c20a908d045c8067d04e3bb10be443/pkg/kube/client.go#L616-L620

Getting into `createPatch` you can see this part:
https://github.com/helm/helm/blob/0d81d92a01c20a908d045c8067d04e3bb10be443/pkg/kube/client.go#L597-L613

Reading the comment about CRDs, it's clear that `jsonpatch.CreateMergePatch` should be used for CRDs and that Strategic Merge Patch is not supported, but looking at the `jsonpatch.CreateMergePatch` function and the switch cases and all the digging, the code that executes is actually this:
https://github.com/helm/helm/blob/0d81d92a01c20a908d045c8067d04e3bb10be443/pkg/kube/client.go#L610-L612

And from there the flow goes like this (to external modules):
https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/pkg/util/strategicpatch/patch.go#L94

https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/pkg/util/strategicpatch/patch.go#L103

https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/pkg/util/strategicpatch/patch.go#L119

https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/pkg/util/strategicpatch/patch.go#L139

https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/pkg/util/strategicpatch/patch.go#L143

https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/pkg/util/strategicpatch/patch.go#L168

https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/pkg/util/strategicpatch/patch.go#L212

https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/pkg/util/strategicpatch/patch.go#L261

https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/pkg/util/strategicpatch/patch.go#L263

https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/pkg/util/strategicpatch/meta.go#L73

https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/pkg/util/strategicpatch/meta.go#L74

https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/third_party/forked/golang/json/fields.go#L29

https://github.com/kubernetes/apimachinery/blob/6a84e37a896db9780c75367af8d2ed2bb944022e/third_party/forked/golang/json/fields.go#L36

So, that's my guess. But if the guess is right, then it all starts from the switch case which says it's structured and has no errors and goes to the `default` which leads to `StrategicMergePatchType` when in fact it should only do `JSON merge patch` for CRDs

**Comment by karuppiah7890** [comment]
I think it will be possible to debug more if we see the CRD and it's structure and the field you mentioned. But I can't say for sure though

**Comment by caarlos0** [comment]
hey! thanks for looking into this!

here is the CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: builds.apps.example.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.status
    name: Status
    type: string
  - JSONPath: .status.start_time
    name: Started
    type: string
  - JSONPath: .status.completion_time
    name: Completed
    type: string
  group: apps.example.com
  names:
    kind: Build
    plural: builds
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            args:
              description: Docker build args in the form of a list of key=value elements
              items:
                type: string
              type: array
            cache:
              description: Wether to cache build image layers
              type: boolean
            cpu:
              description: How much CPU is required
              type: string
            cwd:
              description: CWD is the working directory to be used inside the source.
              type: string
            dockerfile:
              description: Dockerfile path inside cwd
              type: string
            env:
              description: Environment variables
              type: object
            memory:
              description: How much memory is required
              type: string
            source:
              description: Source spec
              properties:
                branch:
                  description: If the type is git, the branch or tag to clone
                  type: string
                path:
                  description: Path to the source, either a git repo or the pvc name.
                  type: string
                type:
                  description: Type of the source, either pvc or git
                  enum:
                  - git
                  - pvc
                  type: string
              required:
              - type
              - path
              type: object
            target:
              description: Target spec
              properties:
                image:
                  description: Image that should be generated
                  type: string
              required:
              - image
              type: object
          required:
          - source
          - target
          - cwd
          - dockerfile
          type: object
        status:
          properties:
            status:
              type: string
          required:
          - status
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```


The field added is the `spec.cache`.

Let me know if you need any more info.

PS: this CRD was generated by kubebuilder, if it helps with anything...
