### ISSUE TITLE
Unable to resolve .Release in ingress file

### ISSUE THREAD

**Issue by palashgoel7** [helm/helm#5932]
Output of `helm version`: 
`Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:55:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Docker-for-mac

Hi,

Tiller is not able to parse Release scope in ingress file. However, it is able to find it in all other kind of files.
Here's the file
```yaml
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "backend.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: 8090
            path: "/{{ .Release.Namespace }}(/|$)(.*)"
    {{- end }}
{{- end }}
```

**Comment by karuppiah7890** [comment]
Inside the `range`, the `.` refers to every element in the array `.Values.ingress.hosts`, and looks like the array contains strings which are hostnames, so when you say `.Release.Namespace` it won't work, instead you can do this which I have seen my team mates do

```
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "backend.fullname" . -}}
{{- $release := .Release }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: 8090
            path: "/{{ $release.Namespace }}(/|$)(.*)"
    {{- end }}
{{- end }}
```

and it will work
