### ISSUE TITLE
Helm upgrade doesn't wait for Job to complete

### ISSUE THREAD

**Issue by wieslaw-decent** [helm/helm#5948]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:53:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.13", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-06-19T20:50:07Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

I'm installing a chart that consists of a single Kubernetes `Job`. Since I want it to run on every `upgrade`, I've given it a name that changes each time:
`name: keycloak-migrations-{{ now | date "20060102150405" }}`

The problem is that Helm doesn't seem to wait for the `Job` to finish properly:
```
% helm upgrade --wait -i keycloak-post-install .                                                         Release "keycloak-post-install" has been upgraded.
LAST DEPLOYED: Wed Jun 26 20:08:22 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                 DATA  AGE
keycloak-migrations  1     95s

==> v1/Job
NAME                                COMPLETIONS  DURATION  AGE
keycloak-migrations-20190626180822  0/1          7s        7s

==> v1/Pod(related)
NAME                                      READY  STATUS   RESTARTS  AGE
keycloak-migrations-20190626180822-bc7zl  1/1    Running  0         7s
```

I guess this is a bug, since Helm waited for all of the other Jobs I've run using it.
Additional question: is there a simple way to run a `Job` on each `upgrade`?

**Comment by mfilotto** [comment]
I'm afraid Jobs are not managed by helm

**Comment by mfilotto** [comment]
I tried to set the Job as a hook but then I have the error "failed: no objects visited"
#4670

**Comment by hickeyma** [comment]
@ Jobs are managed by Helm. The discussion in #4670 mentions the use of hooks which are "un-managed" and if you have a chart which has everything marked as a hook then there is nothing to install (https://github.com/helm/helm/issues/4670#issuecomment-472896695).

**Comment by hickeyma** [comment]
@wieslaw-decent Can you show the job so I can get a better understanding of the situation?

**Comment by wieslaw-decent** [comment]
@hickeyma sure! here you go:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-migrations-{{ now | date "20060102150405" }}
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - image: us.gcr.io/decent-development/keycloak:latest
        name: migrations
        command: ["/bin/bash", "-x", "/usr/src/migrate.sh"]
        env:
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-admin
              key: password
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 50m
            memory: 1Gi
        volumeMounts:
        - name: config-volume
          mountPath: /usr/src
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
        - name: config-volume
          configMap:
            name: keycloak-migrations
      restartPolicy: Never
```

No annotations are present, so it shouldn't be treated as a hook.
