### ISSUE TITLE
Tpl funcion does not work in range

### ISSUE THREAD

**Issue by MaDeG** [helm/helm#5979]
I am pretty new to Helm and not really sure this is indeed an issue or an intended behaviour since I haven't managed to find enough documentation about the `tpl` function.

I am trying to use the `tpl` function in a `range` over a list of objects like the following one:
```
anything:
  - name: "Ciao"
    value: "value1"
  - name: "Mondo"
    value: "value2"
```
I want that for each object a string like `{{ .name }}` is evaluated giving as result "Ciao" at the first iteration and "Mondo" at the second iteration.
I have tried to implement this behaviour as follows:
```
{{- range .Values.anything }}
  trigger: {{ tpl "{{ .name }}" . }}
{{- end }}
```
Helm is not able to render the template and I get the following error:
`Error: render error in "tpl-bug/templates/configmap.yaml": template: tpl-bug/templates/configmap.yaml:5:17: executing "tpl-bug/templates/configmap.yaml" at <tpl "{{ .name }}" .>: error calling tpl: Cannot retrieve Template.Basepath from values inside tpl function: {{ .name }} (BasePath is not a value)`

I have developed a minimal chart that reproduces the issue: [tpl-bug.zip](https://github.com/helm/helm/files/3361861/tpl-bug.zip)

To me it looks like `tpl` always requires the root scope `$` in order to be able to find `Template.BasePath`, at least this is what I was able to understand from the code in engine.go:
```
basePath, err := vals.PathValue("Template.BasePath")
		if err != nil {
			return "", fmt.Errorf("Cannot retrieve Template.Basepath from values inside tpl function: %s (%s)", tpl, err.Error())
}
```
Is this the intended behaviour? If yes how could I achieve the same result anyway? 
I have simplified a lot my real scenario, in my real case the string "{{ .name }}" comes from an external resource.

Output of `helm version`:

`Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}`

Output of `kubectl version`:

`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Microsoft Azure

**Comment by bacongobbler** [comment]
At runtime, the rendering engine needs to know the path of the original template as well as the name of the template, both of which cannot be inferred ahead of time. `tpl` checks those values in order to know which template it is modifying. Looking at the code, that seems like the intended behaviour. The issue here is the `range` function: when inside a `range` function, the scope of dot (`.`) is limited to the scope of the range. In other words, your call to `tpl` is the equivalent of

```
{{ tpl "{{ .name }}" .Values.anything }}
```

Because the `tpl` function relies on objects that are in the root scope of the dot (`.`) value (like `.Template`), the rendering fails. Replacing `.` with `$` as you pointed out should allow the `tpl` function to work.

If you can determine another way to find out which template is calling `tpl`, we'd happily accept a PR.

**Comment by Zebradil** [comment]
I spend some time to find a workaround for this, so, this might be useful for someone:

```
{{- range $key, $value := .Values.list }}
{{- $_ := set $ "key" $key }}
{{- $_ := set $ "value" $value }}
{{- tpl ($.Files.Get "sub.yaml") $ }}
{{- end }}
```

Inside the nested template the global context of the parent template is accessible as usual through dot, the `range` variables are accessible like `.key`, `.value`.

**Comment by wmiller112** [comment]
I seem to be running into the same issue here and cannot figure out how to apply @Zebradil workaround
values.yaml:

```
 app_role:
  - app: test
    namespace: test-namespace
    roles:
      test-admin:
        rules: |
          resources:
            - "*"
          verbs:
            - "*"
      test-analytics:
        rules: |
          resources:
            - "pods"
            - "configmaps"
          verbs:
            - "get"
            - "list"
  - app: test2
    namespace: test2-namespace
    roles:
      test2-admin:
        rules: |
          resources:
            - "*"
          verbs:
            - "*"
```

templates/roles.yaml

```
{{- range .Values.app_role }}
{{- template "roles" . }}
{{- end }}
```

templates/_helpers.tpl
```
{{- define "roles" }}
{{- range $key, $value := .roles }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ $.namespace }}
  name: {{ $key }}
rules:
- apiGroups: [""]
  {{ tpl .rules . | indent 4 }}
  {{- end }}
{{- end -}}
```

**Comment by zffocussss** [comment]
> I spend some time to find a workaround for this, so, this might be useful for someone:
> 
> ```
> {{- range $key, $value := .Values.list }}
> {{- $_ := set $ "key" $key }}
> {{- $_ := set $ "value" $value }}
> {{- tpl ($.Files.Get "sub.yaml") $ }}
> {{- end }}
> ```
> 
> Inside the nested template the global context of the parent template is accessible as usual through dot, the `range` variables are accessible like `.key`, `.value`.

what is $ doing?

**Comment by Zebradil** [comment]
@zffocussss `$` is a reference to the global scope.
For example, these two lines mean the same (if they're located in the top scope):

```
{{ .Values.list }}
{{ $.Values.list }}
```

Now let's take a look at the following `values.yaml`:

```yaml
foo: bar
list:
- Values:
    foo: 1
- Values:
    foo: 2
```

```
{{ .Values.foo }} returns "bar"
{{ $.Values.foo }} also returns "bar"
{{ range .Values.list }}
    {{ .Values.foo }} returns 1 and then 2
    {{ $.Values.foo }} returns bar
{{ end }}
```

**Comment by vfiset** [comment]
@wmiller112 did you figure it out?

**Comment by gmpetrov** [comment]
To use the tpl funciton inside a range loop , i m passing $ (global ctx) instead of .

{{ range .Values.list }}
{{ tpl .item.template $ }}
{{ end }}

**Comment by JParkinson1991** [comment]
For anyone who stumbles upon this issues, one solution is to pass the `Template` object into the `tpl` function alongside your other values via `dict`.

See this implementation:

````yaml
kind: ConfigMap
apiVersion: v1
metadata:
    name: {{ include "config-map-name" . | quote }}
    labels:
        {{- include "config-map-labels" . | nindent 8 }}
    annotations:
        {{- /*
        Use checksums to track config template/value changes.
        If the checksum of this file is then used elsewhere (ie by a deployment) when config template/values changes,
        this files checksum changes which would cause the consumer to update itself to take in these changes.
        */}}
        checksum/config-nginx-server.conf: {{ $.Files.Get (print .Template.BasePath "config/nginx/server.conf") | sha256sum | quote }}
        checksum/values-sites: {{ .Values.sites | toString | sha256sum | quote }}
data:
    {{- range $siteName, $siteConfig := .Values.sites }}
    {{ $siteName }}.conf: |-
        {{- tpl ($.Files.Get "config/nginx/server.conf") (dict "Values" $siteConfig "Template" $.Template) | nindent 8 }}
    {{- end }}
````

**Comment by chudytom** [comment]
@JParkinson1991 thank you very much for your answer. So when applying your approach to the example given in the issue, the result would be like this:
```
apiVersion: v1
kind: ConfigMap
data:
  {{- range $key, $value := .Values.anything }}
  triggerBug: {{ tpl "{{ .Values.value }}" (dict "Values" $value "Template" $.Template) }}
  {{- end }}
  basePath: {{ .Template.BasePath }}
  name: {{ .Template.Name }}
```

**Comment by JParkinson1991** [comment]
@chudytom that should work find yes.

Obviously the structure of the `dict` depends on how the template used in the `tpl` function expects its values. This structure can be anything and the `Values` key is not necessarily required.

For example, if the template looks for values at: `.someValue` `.anotherValue`, your `tpl` call could look like
```
{{ tpl "{{ .Values.value }}" (dict "someValue" $someValue "anotherValue" $anotherValue "Template" $.Template) }}
```

As long as you pass through the root `.Template` object it should all work fine.

Hope that clears things up.

**Comment by sjentzsch** [comment]
I require exactly this pattern for releases, however, I am afraid this won't work within environment files, resp. where releases are defined, right?

With @Zebradil approach I get the error:
```
template: stringTemplate:11:14: executing "stringTemplate" at <$>: wrong type for value; expected map[string]interface {}; got state.EnvironmentTemplateData
```

... and with @JParkinson1991 approach I get the error:

```
template: stringTemplate:19:139: executing "stringTemplate" at <$.Templates>: can't evaluate field Templates in type state.EnvironmentTemplateData
```

Do I miss something, or is this indeed not supported?

**Comment by Zebradil** [comment]
@sjentzsch Do you have a snippet to show? What exactly are you trying to do?

**Comment by sjentzsch** [comment]
@Zebradil Sure :) I am trying to dynamically set up releases in my helmfile, and would like to outsource the respective values.yaml to a separate file which should be included:

```
{{- range $p := .Values.instances }}
- name: nginx
  chart: my-ingress-nginx
  installed: {{ $p.ingress.enabled }}
  namespace: {{ $p.namespace }}
  version: 0.1.0-1
  values:
- {{ tpl (readFile "../values/nginx.yaml.gotmpl") . | nindent 4 }}
{{- end }}
```

My `nginx.yaml.gotmpl` file should be able to make use of the templating variable I am iterating over (`$p`), e.g.:
```
ingress-nginx:
  controller:
    config:
      proxy-buffer-size: '{{ $p.ingress.mpls.config.proxyBufferSize }}'
```

This will render, but for `n>1` it always takes the content of `n=1`, so it does not really iterate.

As it appears, neither of the two approaches from above seem to work in helmfile/environment scope.
