### ISSUE TITLE
proposal: `helm dependency update` might not require `helm repo add`

### ISSUE THREAD

**Issue by lodejard** [helm/helm#6005]
I understand the reason a `requirements.yaml` uses the repo URL as the canonical location identifier. That seems like a good idea. I was surprised however when packaging a chart on a CI server that `helm repo add <name> <url>` must also be done before a subchart on a public repo can be used.

Steps to reproduce:

### requirements.yaml
```yaml
dependencies:
  - name: cert-manager
    version: v0.9.0-alpha.0
    repository: https://charts.jetstack.io
```
### actual
```
$ helm package charts/my-chart --dependency-update
Error: no repository definition for https://charts.jetstack.io. Please add them via 'helm repo add'
```
### expected
behavior of `--dependency-update` and `helm dependency update` to be more like `helm fetch`, which does not require `helm repo add` or `helm repo update` to be done.
```
$ helm fetch cert-manager --repo https://charts.jetstack.io --version v0.9.0-alpha.0 --destination charts/my-chart/charts
$ ls charts/my-chart/charts
cert-manager-v0.9.0-alpha.0.tgz
```

**Comment by woodcockjosh** [comment]
Agreed. Since we have the full repository url there is no need to make the user manually add it. Should be able to download a chart without having to add the repo first.

**Comment by bacongobbler** [comment]
We would happily accept PRs to support this.

**Comment by NishikaDeSilva** [comment]
Hi 
Is this issue fixed ?

**Comment by woodcockjosh** [comment]
@NishikaDeSilva see https://github.com/helm/helm/pull/6258. It might not have released yet.

**Comment by thomastaylor312** [comment]
It will be released in 2.15!

**Comment by masterkain** [comment]
I'm deploying a custom chart using flux with two requirements and this is particularly blocking, using `v3.0.0-beta.5`

```
2019-10-24T14:21:03.543964242Z ts=2019-10-24T14:21:03.543842664Z caller=release.go:147 component=operator release=podinfo targetNamespace=prod resource=prod:helmrelease/podinfo info="processing release (as bce0bac6-f633-11e9-bafa-06de94eea1a6)" action=CREATE options="{DryRun:true ReuseName:false}" timeout=5m0ss
2019-10-24T14:21:04.184450486Z ts=2019-10-24T14:21:04.184341328Z caller=chartsync.go:555 component=chartsync release=bstore-prod targetNamespace=prod resource=prod:helmrelease/bstore-prod warning="failed to update chart dependencies" err="no repository definition for https://kubernetes-charts.storage.googleapis.com/, https://kubernetes-charts.storage.googleapis.com/. Please add them via 'helm repo add'"
```

```
dependencies:
  - name: memcached
    version: ~3.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: ~9.3
    repository: https://kubernetes-charts.storage.googleapis.com/
```

`version.BuildInfo{Version:"v3.0.0-beta.5", GitCommit:"509a8819b7e8dba86b7982c006fce22628aeea28", GitTreeState:"clean", GoVersion:"go1.13.3"}`
