### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by segator** [helm/helm#6023]
command executed
```
helm install stable/prometheus-operator --name=monitoring --namespace=monitoring -f prom_values.yaml
```

Error get
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14f91b9]

goroutine 1 [running]:
main.readFile(0x7fffd9bcb57b, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000712201, 0xc00076b680, ...)
        /go/src/k8s.io/helm/cmd/helm/install.go:557 +0xa9
main.vals(0xc0002f5030, 0x1, 0x1, 0x2c0de18, 0x0, 0x0, 0x2c0de18, 0x0, 0x0, 0x2c0de18, ...)
        /go/src/k8s.io/helm/cmd/helm/install.go:399 +0x187
main.(*installCmd).run(0xc000458600, 0xc0003dce00, 0x0)
        /go/src/k8s.io/helm/cmd/helm/install.go:243 +0x1db
main.newInstallCmd.func2(0xc00013a780, 0xc000246550, 0x1, 0x5, 0x0, 0x0)
        /go/src/k8s.io/helm/cmd/helm/install.go:196 +0x30e
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc00013a780, 0xc000246500, 0x5, 0x5, 0xc00013a780, 0xc000246500)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:762 +0x465
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000de500, 0x6, 0x6, 0xc0000de500)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /go/src/k8s.io/helm/cmd/helm/helm.go:171 +0x7a
Error: failed to download "loki/loki-stack" (hint: running `helm repo update` may help)
```

prom_values.yaml
```
coreDns:
  service:
    selector:
      k8s-app: kube-dns

kubeControllerManager:
  service:
    selector:
      k8s-app: null
      component: kube-controller-manager

kubeEtcd:
  enabled: false
  endpoints: ["xxx.xxx.xxx"]
  service:
    port: '2379'
  serviceMonitor:
    scheme: https
    insecureSkipVerify: true
    certFile: "/etc/prometheus/secrets/etcd-cert/etcd.pem"
    keyFile: "/etc/prometheus/secrets/etcd-cert/etcd-key.pem"
prometheus:
  prometheusSpec:
    secrets: ["etcd-cert"]
    replicas: 1
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: local-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 130Gi
    #    selector: {}

kubeScheduler:
  service:
    selector:
      k8s-app: null
      component: kube-scheduler

grafana:
  enabled: true
```

Output of `helm version`:
2.14.2
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
RKE baremetal
