### ISSUE TITLE
YAML anchor handling changed

### ISSUE THREAD

**Issue by jordansissel** [helm/helm#6062]
Between Helm v2.12.3 and v2.14.1, YAML anchor handling changed. I don't know the YAML spec, but in Helm v2.12.3, a yaml anchor could appear _after_ an alias and it worked. In Helm 2.14.1, yaml anchors must appear _before_ an alias.

Example:

Template:

```
% cat templates/example.yaml
Greeting: {{ .Values.hello.greeting }}
```

Values file:

```yaml
hello:
  <<: *mydefaults

mydefaults: &mydefaults
  greeting: "Hello"
```

Helm v2.12.3:

```
% ~/build/linux-amd64/helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

% ~/build/linux-amd64/helm template --values values.yaml .
---
# Source: example/templates/example.yaml
Greeting: Hello
```

Helm v2.14.1

```
% helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

% helm template --values values.yaml .
Error: failed to parse values.yaml: error converting YAML to JSON: yaml: unknown anchor 'mydefaults' referenced
```

If I move the `mydefaults` anchor above any aliases, it works:

```
mydefaults: &mydefaults
  greeting: "Hello"

hello:
  <<: *mydefaults
```

**Comment by bacongobbler** [comment]
It's possible that a regression made its way into ghodss/yaml. Let us know if you find something.

**Comment by ArgTang** [comment]
This works in 2.13 but not 14.3

**Comment by karuppiah7890** [comment]
Anchor must appear before alias - This is the expected behavior according to YAML spec. [Here's the PR](https://github.com/go-yaml/yaml/pull/300) that fixed the bug in [`go-yaml/yaml`](https://github.com/go-yaml/yaml) and [`ghodss/yaml`](https://github.com/ghodss/yaml) [internally uses](https://github.com/ghodss/yaml/blob/master/go.mod) [`go-yaml/yaml`](https://github.com/go-yaml/yaml) and helm uses `ghodss/yaml`

**Comment by karuppiah7890** [comment]
So, this issue can be closed. 👍

**Comment by karuppiah7890** [comment]
The validity of the yamls can also be checked here: http://www.yamllint.com/ with these two yamls

```yaml
# invalid yaml. will crash the site
hello:
  <<: *mydefaults

mydefaults: &mydefaults
  greeting: "Hello"
```

```yaml
# valid yaml. shows correct output
mydefaults: &mydefaults
  greeting: "Hello"

hello:
  <<: *mydefaults
```
