### ISSUE TITLE
Requirements alias not working

### ISSUE THREAD

**Issue by NGTOne** [helm/helm#6195]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-gke.5", GitCommit:"5aa3a95d828fe45aab3611dfc4ebdc0341fe1507", GitTreeState:"clean", BuildDate:"2019-05-29T17:25:39Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

Exactly what it says on the tin. My `requirements.yaml` looks like this:
```yaml
dependencies:
  - name: mcrouter
    version: 1.0.0
    repository: https://kubernetes-charts.storage.googleapis.com
    alias: objectCache
  - name: mcrouter
    version: 1.0.0
    repository: https://kubernetes-charts.storage.googleapis.com
    alias: sessionCache
```

The resulting `requirements.lock` looks like this:
```yaml
dependencies:
- name: mcrouter
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.0.0
- name: mcrouter
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.0.0
digest: sha256:09459955a2e5d721ee0dfcc79ce08d9cd078b3684bf87c758e0d0f0d9608562e
generated: "2019-08-09T14:43:45.681670207+02:00"
```

Output from `helm dep up`:

```
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "common" chart repository
...Successfully got an update from the "gitlab" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 2 charts
Downloading mcrouter from repo https://kubernetes-charts.storage.googleapis.com
Downloading mcrouter from repo https://kubernetes-charts.storage.googleapis.com
Deleting outdated charts
```

After this, my `charts` subdirectory only contains `mcrouter-1.0.0.tgz`. My understanding is that it should contain:
- `sessionCache-1.0.0.tgz`
- `objectCache-1.0.0.tgz`

Is this correct, or have I misunderstood the purpose of this feature?
