### ISSUE TITLE
MountVolume.SetUp failed for volume “secret” : invalid character '\r' in string literal

### ISSUE THREAD

**Issue by salowenh** [helm/helm#6240]
`helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

`kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform: `AKS`/`Azure`

I'm trying to move from manual deployment to helm.  
After I've configured all my charts and fixed some issues, I've got to a point where after deployment the pods report the following error:
```
MountVolume.SetUp failed for volume “secret” : invalid character '\r' in string literal
```
`secret` is a `flexVolume` pointing to Azure Key Vault, here is the deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentName
spec:
  selector:
    matchLabels:
      run: deploymentName
  replicas: 2
  template:
    metadata:
      labels:
        run: deploymentName
        app: appName
    spec:
      containers:
      - name: deploymentName
        image: {{ .Values.image.acr.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        volumeMounts:
        - name: secret
          mountPath: /secrets
          readOnly: true
        ports:
        - containerPort: 1234
        env:
        - name: DOTENV_CONFIG_PATH
          value: "/secrets/env"
      volumes:
      - name: secret
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: "kvcreds"
          options:
            usepodidentity: "false"
            tenantid: {{ .Values.tenantid }}
            subscriptionid: {{ .Values.subsid }}
            resourcegroup: {{ .Values.rg }}
            keyvaultname: {{ .Values.kvname }}
            keyvaultobjecttype: secret
            keyvaultobjectname: {{ .Values.objectname }}
```
So at first I thought one of my values is invalid, I tried removing them one by one and even replacing them all, nothing changes.  

I've tried running `helm lint` but there were no errors 

Then I've tried running `helm template`, transofmr the output into a yaml file and manually deploy it using `kubectl --apply`. **It worked**, no errors.  

I've also tried replacing the `azure/kv` volume with `emptyDir` volume and I was able to deploy using helm. It looks like a specific issue of helm with `azure/kv` volume?

My suspicion is the `azure/kv` but I couldn't verify it

How can I work around this? (it's blocking my helm deployment) 

**Update:**
If I change the `mountPath` value it works for 2-3 deployments and then fails again
