### ISSUE TITLE
Missleading linting error message when no values.yaml file is provided for a chart

### ISSUE THREAD

**Issue by C0conuts** [helm/helm#6275]
Hi!

 ### The summary

In the chart of my project, I'm using several values files such as:
- `values-staging.yaml`
- `values-production.yaml`

Despite the chart successfully deploying, the linter would throw an error I could not understand:

```
[ERROR] templates/: render error in "test/templates/second-worker-deployment.yaml": template: test/templates/second-worker-deployment.yaml:8:21: executing "test/templates/second-worker-deployment.yaml" at <.Values.workers.second_worker.replicas>: nil pointer evaluating interface {}.second_worker
```
 ### How to reproduce

Create a test chart with the following files:
* `Chart.yaml`

```
name: test
version: 1.0.0
description: helm chart for test
maintainers:
  - name: Foo Bar
    email: foo@bar.com
```
* `values-staging.yaml`

```
workers: 
  first_worker:
    replicas: 1
  second_worker:
    replicas: 1
```

And two templates:

- `first-worker-deployment.yaml`

```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: worker-first-worker
  labels:
    name: worker-first-worker
spec:
  replicas: {{.Values.workers.first_worker.replicas}}
```

- `second-worker-deployment.yaml`

```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: worker-second-worker
  labels:
    name: worker-second-worker
spec:
  replicas: {{.Values.workers.second_worker.replicas}}
```

Now run `helm lint test` on the chart to get:

```
==> Linting test
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist
[ERROR] templates/: render error in "test/templates/second-worker-deployment.yaml": template: test/templates/second-worker-deployment.yaml:8:21: executing "test/templates/second-worker-deployment.yaml" at <.Values.workers.second_worker.replicas>: nil pointer evaluating interface {}.second_worker

Error: 1 chart(s) linted, 1 chart(s) failed
```

Inverting the template files order (by renaming them for example) would lead to the error being raised on the last file of the template folder.

 ### Expected behavior

Well just the following output, without an error:

```
==> Linting test
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```
