### ISSUE TITLE
BUG: Annotation value breaks helm deployment

### ISSUE THREAD

**Issue by dreic** [helm/helm#6279]
Output of `helm version`: v2.14.3

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Azure 

**Summary**
In order to force helm to redeploy image I had to add something to the container that changes on every deployment which is git hash of the commit. 

here is part of my values.yaml

```
# Git info
git:
  commit_hash: SHA ###HASH###
  branch_name: BRANCH ###BRANCH###
```

part of the deployment.yaml

```
template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "something-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        git.commit-hash: {{ .Values.git.commit_hash }}
        git.branch-name: {{ .Values.git.branch_name }}
```
During build I replace both values with actual values. I didn't manage to figure out with 100% but, if `commit_hash` value contains only numbers (I am taking only 1st 7 charts from the whole hash) then helm fails with following error:

> UPGRADE FAILED
> Error: Failed to recreate resource: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found 2, error found in #10 byte of ...|it-hash":2696394},"l|..., bigger context ...|-name":"Deployed_from_git_tag","git.commit-hash":2696394},"labels":{"app.kubernetes.io/instance":"co|...
> Error: UPGRADE FAILED: Failed to recreate resource: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found 2, error found in #10 byte of ...|it-hash":2696394},"l|..., bigger context ...|-name":"Deployed_from_git_tag","git.commit-hash":2696394},"labels":{"app.kubernetes.io/instance":"co|...
> 

I did a workaround and always have sha-value in the commit_hash and it looks it's working now. Not using helm very long btw.
