### ISSUE TITLE
cannot access root($) Chart.yaml Version from templated subchart

### ISSUE THREAD

**Issue by matankila** [helm/helm#6338]
hi,
i cant get the base chart version,
tried _helpers.tpl definition of argument with no success 
thanks alot!!!!!

```
{{- define "bitcore.deployment" -}}
{{- $common := dict "Values" .Values.bitcore -}} 
{{- $noCommon := omit .Values "bitcore" -}} 
{{- $overrides := dict "Values" $noCommon -}} 
{{- $noValues := omit . "Values" -}} 
{{- with merge $noValues $overrides $common -}}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    app: {{ .Chart.Name }}
    deploymentconfig: {{ .Chart.Name }}
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: {{ .Chart.Name }}
        deploymentconfig: {{ .Chart.Name }}
        test: required
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ $.Chart.Version }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        env:
          - name: BIT_CORE_RUNTIME_PROFILE
            value: '{{ required "Please provide runtime profile" .Values.global.runtimeProfile }}'
          - name: JAVA_OPTS
            value: '{{ required "Please provide Java Ops." .Values.global.javaOpts }}'
        livenessProbe:
        httpGet:
          path: management/health
          port: 1489
        initialDelaySeconds: 30
        periodSeconds: 60
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 10
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 1480
          protocol: TCP
        readinessProbe:
          httpGet:
            path: management/health
            port: 1489
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 10
        resources:
          {{- toYaml .Values.global.resources | nindent 12 }}
        volumeMounts:
          - mountPath: /logs
            name: {{ .Chart.Name }}-volume-1
      terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ .Chart.Name }}-volume-1
        emptyDir: {}
  test: false
{{- end -}}
{{- end -}}
```
