### ISSUE TITLE
Helm3: Release Names scoped to Charts?

### ISSUE THREAD

**Issue by towolf** [helm/helm#6339]
Introductory Quote:

> A Release is an instance of a chart running in a Kubernetes cluster. One chart can often be installed many times into the same cluster. And each time it is installed, a new release is created. Consider a MySQL chart. If you want two databases running in your cluster, you can install that chart twice. Each one will have its own release, which will in turn have its own release name.

If a release is an instance of a chart, why do release names have to unique per namespace? Should they not be unique per chart? 

Now that Helm 3 beta is already out, I'm afraid it will be too late for this, but I wanted to raise it anyway.

So, we never used Tiller before, because it was a headache, we only ever used `helm template` so far, but we are very much looking forward to Helm 3 and want to use it considering its 3-way merges, GC of deleted stray objects and all-around improvements (OCI registry support is fab!).

So we never ran into the issue that release names are not scoped to charts. They had to be globally unique and now they have to be unique in a namespace. 

But we used them like this:

app: frontend, environment: dev, release-name: dev
app: frontend, environment: qa, release-name: qa
app: frontend, environment: qa2, release-name: qa2
app: backend, environment: dev, release-name: dev 

So in Gitlab CI/CD the target of a deployment is the "environment", an instance of the app to be deployed. And in Helm, a "release" is an instance of a chart (see quote), so they naturally map to each other. Or so we thought.

So, we used "staging" as the environment and hence "staging" also as the release name:

`helm template "${CI_ENVIRONMENT_NAME##*/}" "{CHARTNAME}" "$@"`

Now the objects created by the standard _helpers template were like this for us, looking all proper: `{{ printf "%s-%s" .Chart.Name .Release.Name }}`, or with reverse order, doesn't matter.

Deployment `myapp-dev`, Configmap `myapp-dev`, etc.

But with the "official" scheme, this would be `myapp-myapp-dev`, or myapp-dev-myapp`.

So, with `helm install`, `upgrade` and `uninstall` I want to target the instance xyz of chart abc, and not instance xyz-abc.

**Comment by mattfarina** [comment]
This is a good question. Helm is a package manager and Kubernetes enables you to install the same application multiple times.

That means, the same chart can be installed in the same namespace. For example, consider the case where someone install Wordpress into the default namespace 3 times. This needs to work.

I know that some may want to debate whether people should or should not do something like this. The reality is that they do so we need to have some level of support for it.

Our top priority [role](https://github.com/helm/community/blob/master/user-profiles.md) is the application operator. We want to make the process of running commands as easy as possible for them. Consider someone with multiple releases of the same chart running in one namespace and now having to work with those.

Does that help to explain why we have what we have?

**Comment by towolf** [comment]
Yes, I absolutely want to continue to be able to install multiple releases of one chart.

But I want to be able to use the same release name for multiple charts. I was just not able to explain that very well.

So I would like to be able to say, »upgrade chart "frontend", release "staging"«, or »uninstall the release "staging" of the chart "backend"«.

So frontend and backend have a shared release name, and that can be interpreted like a shared environment: "staging" is the release "frontend-staging" connects to "backend-staging".

And then in my chart I can concatenate chart name and release name together as needed. Chart name and release name would become independent.

Now you could say, that this is what namespaces are for, but we often end up needing more subdivisions. For example, we have a "myproject-qa" namespace, but in the we have qa1, qa2, qa3 environments, which multiple charts installed that interact with each other. Each chart has an instance (release in Helm jargon) named qa1, qa2, qa3.

But with current Helm release tracking that does not work.

**Comment by w4rgrum** [comment]
Hello @towolf ,

I don't know if it was the case back when you created this issue, but it seems a kind of workaround is now provided in the default ``_helpers.tpl`` file generated by ``helm create``.
Indeed there is now a ``if`` condition to check if the release name contains the ``$name`` (which is the chart name by default), meaning as a result the double chart name at the beginning of the fullname is compacted to only one.

```django
{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "my-chart.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

Result of different commands with the default chart

* Case ``<release name>`` as release name
```bash
helm template releasename my-chart/
```
```yaml
---
# Source: my-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: releasename-my-chart
  labels:
    helm.sh/chart: my-chart-0.1.0
    app.kubernetes.io/name: my-chart
    app.kubernetes.io/instance: releasename
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
[...]
```

* Case ``<chart name>-<release name>`` as release name
```bash
helm template my-chart-releasename my-chart/
```
```yaml
---
# Source: my-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-chart-releasename
  labels:
    helm.sh/chart: my-chart-0.1.0
    app.kubernetes.io/name: my-chart
    app.kubernetes.io/instance: my-chart-releasename
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
[...]
```

To me this looks like a poor workaround (ordering of chart name and release name is not consistent between the 2 ways to do as you stated) but at least it should allow to solve your issue (and mine which was the same). The only difference to expect compared to what you are currently doing would be the value of the instance label.
