### ISSUE TITLE
Nested template directives

### ISSUE THREAD

**Issue by ghost** [helm/helm#6349]
I'm currently working on moving a project to using helmfile which has the concept of environments and values files for them. 

I want to have release specific values in my envrionment values file (i.e. the Namespace that release will be installed into). I essentially want to have something like this:

```yaml
# prod.yaml

namespaces:
  release1: r1ns
  release2: r2namespace 
```
Where the namespaces are not a composition of other helm values I can grab (i.e. not something like `{{ .Environment.Name }}/{{ .Release.Name }}`)

How can one do this with Helm? I've tried doing something like `{{ .Environment.Values.namespaces.{{ .Release.Name }} }}` but that doesn't work. Is there a way to essentially parameterize the path of your template directive? If not, is there a way to restructure the values file to allow for having certain release specific environments values?

**Comment by mattfarina** [comment]
I'm not entirely sure what you're asking for. At first you start off talking about [helmfile](https://github.com/roboll/helmfile). This is a separate project that builds on Helm. This project does deal with environment variables and I would ask on that project for details on handling those.

Right now Helm itself does not handle environment variables. There are security implications with doing that which need to be tackled and no one has worked this out, yet.

**Comment by whitlekx** [comment]
Sorry, let me restate a more generic case. 

I essentially want to nest a template directive inside another directive. 

If I have a values file that looks something like this: 

```yaml
# values.yaml

prod: 
  foo1: bar1
  foo2: bar2

dev:
  foo1: dev1
  foo2: dev2 

```

In a fake template I essentially want to parametrize a directive

```yaml
spec:
  metadata:
    name: {{ .Values.{{ .Values.Environment }}.foo1 }} 

```
This obviously doesn't make much sense for the generic case but in general I just want to know if there's a way to express nested directives like the above example.
