### ISSUE TITLE
Apply helm hook and release labels to hook resources

### ISSUE THREAD

**Issue by jlegrone** [helm/helm#6365]
Applying a standard set of labels to all resources managed by helm hooks will make it easier to implement log trailing and cleanup functionality.

Any resource created by a hook should have its labels patched to include the hook and release name:

```yaml
hooks.helm.sh/[HOOK NAME]: "true"
app.kubernetes.io/instance: "[RELEASE NAME]"
```

For example, a Job with the `pre-install` and `pre-upgrade` hook would include the following labels for a release named `foo`:

```yaml
hooks.helm.sh/pre-install: "true"
hooks.helm.sh/pre-upgrade: "true"
app.kubernetes.io/instance: "foo"
```

A solution for imperatively deleting hook resources is needed that does not involve re-executing the hook (a la the Helm 2`test --cleanup` flag). This will allow us to implement a generic cleanup subcommand that simply selects resources to delete by hook and release label, and works across resources created by multiple revisions of a chart.
