### ISSUE TITLE
error calling eq: invalid type for comparison

### ISSUE THREAD

**Issue by papanito** [helm/helm#6376]
I have a chart template which contains this line

```yaml
  {{- if eq $.Values.global.environment "dev" }}
```

When running `helm lint` this fails:

```bash
> helm lint my-services/
==> Linting my-services/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "my-services/templates/istio-gateway.yaml": template: acquiring-services/templates/istio-gateway.yaml:64:9: executing "my-services/templates/istio-gateway.yaml" at <eq $.Values.global.e...>: error calling eq: invalid type for comparison
```

Interestingly I have the same comparison  - just with another string - in line 8, which is not a problem at all. Removing the erronous line makes lint passing successfully

```bash
helm lint my-services/
==> Linting my-services/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
```

Here the relevant `yaml`-file:

```yaml
kind: VirtualService
metadata:
  name: acquiring-gateway-virtualservice
  namespace: {{ default $.Release.Namespace }}
spec:
  hosts:
  {{- if eq $.Release.Namespace $.Values.global.defaultNamespace }}
  {{- if eq $.Values.global.environment "prd" }}
  - {{ $.Values.global.ingressName }}.{{$.Values.global.environment}}.sc.intra
  {{- else }}
  - {{ $.Values.global.ingressName }}.svc.{{$.Values.global.environment}}.sc.intra
  {{- end }}
  {{- else }}
  - {{ $.Values.global.ingressName }}-{{ default $.Release.Namespace }}.svc.{{$.Values.global.environment}}.sc.intra
  {{- end }}
  gateways:
  - acquiring-gateway
  http:
  - match:
    - uri:
        prefix: /uaa

        prefix: /uaa/
    route:
    - destination:
        port:
          number: 80
        host: auth-server.{{ $.Release.Namespace }}.svc.cluster.local
    corsPolicy:
      allowOrigin:
      - '*'
      allowMethods:
      - OPTIONS
        - GET
        - PUT
        - POST
        - PATCH
      allowHeaders:
      - authorization

  {{- if eq $.Values.global.environment "dev" }}
  - match:
```

Also following the suggestion under [#2979](https://github.com/helm/helm/issues/2979) does not help

Output of `helm version`:

```json
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

Output of `kubectl version`:

N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

On-Premise
