### ISSUE TITLE
template function support eval 

### ISSUE THREAD

**Issue by wu0407** [helm/helm#6383]
Eval nested values is useful, some type is "a" or "b" , and "a" has value 1.
the function work like this 
values.yaml
```
type: a
a: 1
b: 2

```
template.yaml
```
{{ .Values.{{ .Values.type }} }}
or
{{ eval .Values.{{ .Values.type }} }}
```
output: 1

Output of `helm version`:
helm 3.0 beta3

Output of `kubectl version`:
1.14.1

**Comment by bacongobbler** [comment]
{{ index .Values .Values.type }}

**Comment by drivera-armedia** [comment]
I realize this is an old one, but there's definitely a use case for this.  Imagine this YAML:

```
global:
  subsystem:
    external:
      url: some-url
      pass: some-pass
      user: some-user

referenceOne: ".global.subsystem.external.url"
referenceTwo: ".global.subsystem.external"
```

I would like to be able to execute something like `{{ eval .reference $ }}` and get the value `some-url`.

I would also like to be able to execute something like `{{ $map := eval .referenceTwo $ }}` and have the `$map` variable be assigned a reference to `.global.subsystem.external` which can then be applied to `toYaml` or whatnot for replication of entire configuration segments, specified (even computed) dynamically.
