### ISSUE TITLE
Helm 2: Tiller deployment spec via `helm init` uses deprecated api for Kubernetes 1.16

### ISSUE THREAD

**Issue by lachie83** [helm/helm#6390]
Output of `helm version`:
```
$ helm version --client
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-beta.2", GitCommit:"48ca054daba9e610f13c6d6bfcedf6c7de12b138", GitTreeState:"clean", BuildDate:"2019-09-04T15:52:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-alpha.3", GitCommit:"28e88e3f19c37242db1a456b1f45c543c4a540fe", GitTreeState:"clean", BuildDate:"2019-08-07T16:08:39Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

Seeing the following error
```
$ helm init --service-account tiller
$HELM_HOME has been configured at /Users/${USER}/.helm.
Error: error installing: the server could not find the requested resource
```

Upon closer inspection. This API is deprecated in 1.16 as per - https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
```
$ helm init --service-account tiller --debug
---
apiVersion: extensions/v1beta1
```

Solution is to bump to apps/v1 of deployment

**Comment by lachie83** [comment]
Looks like there are other spec changes needed too
```
error: error validating "STDIN": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by lachie83** [comment]
The addition of the `spec.selector` seemed to at least get it to install
```
<snip>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm
      name: tiller
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
<snip>
```
