### ISSUE TITLE
v3: `helm status` does not list deployed resources

### ISSUE THREAD

**Issue by unguiculus** [helm/helm#6427]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker Desktop for Mac

`helm status` does not include deployed resources:
```console
$ helm3 status demo
NAME: demo
LAST DEPLOYED: 2019-09-13 16:45:41.719772 +0200 CEST
NAMESPACE: default
STATUS: deployed
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods -l "app.kubernetes.io/name=foo,app.kubernetes.io/instance=demo" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
```

Using `yaml` or `json` as output format, the `info` entry does not contain a `resources` entry:

```yaml
info:
  Description: Install complete
  deleted: "0001-01-01T00:00:00Z"
  first_deployed: "2019-09-13T16:45:41.719772+02:00"
  last_deployed: "2019-09-13T16:45:41.719772+02:00"
  notes: |
    1. Get the application URL by running these commands:
      export POD_NAME=$(kubectl get pods -l "app.kubernetes.io/name=foo,app.kubernetes.io/instance=demo" -o jsonpath="{.items[0].metadata.name}")
      echo "Visit http://127.0.0.1:8080 to use your application"
      kubectl port-forward $POD_NAME 8080:80
  status: deployed
```

JSON output is printed as one line. I'd expect it to be pretty-printed and indented by four spaces to be consistent with what `kubectl` does. The JSON formatting issue is also present in Helm 2.
