### ISSUE TITLE
Is there any option to randomize a string once and use it across several templates?

### ISSUE THREAD

**Issue by arielb135** [helm/helm#6456]
Basically i want to generate a random string, and use it across several yaml templates (let's say, a deployment that expects it, and a secret that expects it as well).

Thanks

**Comment by hickeyma** [comment]
A [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) or [Configmap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) is a way of doing this.

**Comment by hickeyma** [comment]
@arielb135 Probably best ask something like this out on the [Helm users](https://app.slack.com/client/T09NY5SBT/C0NH30761/details) Slack channel.

**Comment by arielb135** [comment]
> A [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) or [Configmap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) is a way of doing this.

i'll explain myself, i want to create a random string, then use it in multiple yaml files.
for example, if i could define in the helpers:
`
$password := (randAlphaNum 24 | nospace)
`
then use it it in several yaml files:
`
{{ {{ template "myapp.password" . }}
`

**Comment by hickeyma** [comment]
Here is a little example...

Define in helper template:
```
{{- define "chrt-6456.password" -}}
{{- randAlphaNum 24 | nospace -}}
{{- end -}}
```
and then reference it as:
```
data:
  password: {{ include "chrt-6456.password" .}}
```

**Comment by arielb135** [comment]
It will not work as every time you call the template, new value will be generated, eventually I had to put both yamls on one file

**Comment by hickeyma** [comment]
ok, I see. You get caught with random as it regenerates . on each call unfortunately.

**Comment by bridgetkromhout** [comment]
As explained above, if you want to share a randomized string being generated between multiple templates, then the templates need to be in the same file. See https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments for a usage example. I'll resolve this issue at this time; thanks for noting this. I've submitted a docs update: https://github.com/helm/helm-www/pull/877.

**Comment by agronholm** [comment]
How is this going to work if I need to generate a random password for the initial admin user, use it in a post-install hook to set it and then display it in NOTES.txt so the admin user can log in? It seems ridiculous having to save the password in a secret which is never going to be used later (not to mention a potential security issue).

**Comment by ebuildy** [comment]
my 2 cents, a Helm chart called "my-apps" to deploy argocd apps, our use case is to prefix all Application resources with the SAME random string:

```
# templates/argocd-apps.yaml
{{- range .Values.apps -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.randomPrefix }}-{{ .name }}
  ....
```

## The workaround:

I created another Helm chart that create a parent argocd app:

```
# templates/argocd-app-parent.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-demo-web
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    helm.sh/chart: petal-apps-0.1.17
    app.kubernetes.io/name: petal-apps
    app.kubernetes.io/instance: release-name-petal-apps
    app.kubernetes.io/version: "0.1.17"
    app.kubernetes.io/managed-by: Helm
    random: MvHpm2zvzNJIVNap1L6PxTUm
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    ....
  project: my-demo
  source:
    ...
    helm:
      values: |
        fullnameOverride: web
        randomPrefix: {{- randAlphaNum 24 | nospace -}}
```

Note: I could also use Helm controller, and deploy a Helm release from another Helm release:

```
# templates/helm-release-parent.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  ...
spec:
  chart: stable/nginx-ingress
  targetNamespace: nginx-ingress
  valuesContent: |-
    randomPrefix: {{- randAlphaNum 24 | nospace -}}
```
