### ISSUE TITLE
User supplied value doesn't override default value for map variables

### ISSUE THREAD

**Issue by ediezh** [helm/helm#6465]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): `EKS`

User supplied value:
```
master:
  JCasC:
    configScripts:
      jenkins-config: |
        jenkins:
          location:
            url: https://jenkins:8080
      k8s-config: |
        jenkins:
          clouds:
            - kubernetes:
                name: "advanced-k8s-config"
                serverUrl: https://kubernetes.default
                skipTlsVerify: true
                namespace: tooling
                jenkinsUrl: http://jenkins.tooling.svc.cluster.local:8080
                connectTimeout: 5
                readTimeout: 15
                containerCapStr: 100
                maxRequestsPerHostStr: 64
                retentionTimeout: 5
```
Default value:
```
  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
```

The computed value is:
```
  JCasC:
    configScripts:
      jenkins-config: |
        jenkins:
          location:
            url: https://jenkins:8080
      k8s-config: |
        jenkins:
          clouds:
            - kubernetes:
                name: "advanced-k8s-config"
                serverUrl: https://kubernetes.default
                skipTlsVerify: true
                namespace: tooling
                jenkinsUrl: http://jenkins.tooling.svc.cluster.local:8080
                connectTimeout: 5
                readTimeout: 15
                containerCapStr: 100
                maxRequestsPerHostStr: 64
                retentionTimeout: 5
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
```

As we can see from above, the computed value is a merge of both user supplied value and the default value. 
The expected behavior should be just the user supplied value.
