### ISSUE TITLE
Helm3: checksum annotation not processing template using range

### ISSUE THREAD

**Issue by teng1** [helm/helm#6469]
Hi,
I have the following configmap that renders a list of IP address from a values file. I'am trying to use checksum/<name> annotation to get the deployment to upgrade on change. however no change is detected by the checksum function
`checksum/config` changes fine on update, however `checksum/whitelist` does not. Is there a way to get the template to render prior to generating the checksum?
 ```
 annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/whitelist: {{ include (print $.Template.BasePath "/whitelist.yaml") . | sha256sum }}
```

does not show changes in hash or output when running `helm upgrade --dry-run --debug`
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "..fullname" . }}-whitelist-configmap
  labels:
{{ include "..labels" . | indent 4 }}
data:
  whitelist.txt: |-
{{- range .Values.whitelist }}
{{ . | indent 4 }}
{{- end }}
```
the below works fine however
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "..fullname" . }}-configmap
  labels:
{{ include "..labels" . | indent 4 }}
data:
  squid.conf: |-
{{ (tpl (.Files.Get "squid.conf") . ) | indent 4}}
```
