### ISSUE TITLE
helm init is failing with requested resource not found

### ISSUE THREAD

**Issue by c0debreaker** [helm/helm#6473]
I executed `helm init` and I got

```
Creating /Users/rcamara/.helm
Creating /Users/rcamara/.helm/repository
Creating /Users/rcamara/.helm/repository/cache
Creating /Users/rcamara/.helm/repository/local
Creating /Users/rcamara/.helm/plugins
Creating /Users/rcamara/.helm/starters
Creating /Users/rcamara/.helm/cache/archive
Creating /Users/rcamara/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /Users/rcamara/.helm.
Error: error installing: the server could not find the requested resource                                                                                        exit:1
```

I ran this command `kubectl config view`

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority: /Users/rcamara/.minikube/ca.crt
    server: https://192.168.99.101:8443
  name: minikube
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-for-desktop
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: minikube
  user:
    client-certificate: /Users/rcamara/.minikube/client.crt
    client-key: /Users/rcamara/.minikube/client.key
```

Helm version is
```
$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Error: could not find tiller
```

kubectl version
```
╰──➤  kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

I'm using mac osx
```
Darwin M-C02SQ8WFGTF1 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

**Comment by GovardhanChaudhari** [comment]
Same error in Windows 10

C:\WINDOWS\system32>helm init
$HELM_HOME has been configured at C:\Users\gvc\.helm.
Error: error installing: the server could not find the requested resource

C:\WINDOWS\system32>helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Error: could not find tiller

C:\WINDOWS\system32>kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by galkowskit** [comment]
Hm, I'm hitting the same issue on macOS.
```
$ helm init

$HELM_HOME has been configured at /Users/tkg/.helm.
Error: error installing: the server could not find the requested resource
```

```
$ helm version

Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Error: could not find tiller
```

```
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ minikube version

minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6
```

**Comment by subrnath** [comment]
I am facing the same issue.  I think, this issue is coming with K8s version 1.16.0. Till K8s version 1.15.3 it was ok.

If we take out the json file, helm init --output json , following parameter needs to be correct with respect to work with K8s version 1.16

1)  "apiVersion": "extensions/v1beta1" => it should be "apiVersion: apps/v1"
2)  
      "spec": {
        "replicas": 1,
        "selector": {
            "matchLabels": {
                "name": "tiller"
                }
            },

**Comment by bacongobbler** [comment]
Hey there, this issue has already been reported in https://github.com/helm/helm/issues/6374. I'm going to close this issue as a duplicate so we can keep the conversation in one place. Please follow up in that ticket and use the workarounds provided in this comment: https://github.com/helm/helm/issues/6374#issuecomment-533185074

Thanks!

**Comment by yuanyaosmile** [comment]
i also face this issue and i use the command in #6374  which is "helm init --service-account tiller --output yaml | sed 's@apiVersion: extensions/v1beta1@apiVersion: apps/v1@' | sed 's@  replicas: 1@  replicas: 1\n  selector: {"matchLabels": {"app": "helm", "name": "tiller"}}@' | kubectl apply -f -" , although helm problem will be get solved, but it also has some effects , for example minikube start problems.
=============
finally, i find that  the client version and server version of kubectl must be the same.  so make the version match and this issue will be solved.

**Comment by yuanyaosmile** [comment]
i also face this issue and i use the command in #6374 which is "helm init --service-account tiller --output yaml | sed 's@apiVersion: extensions/v1beta1@apiVersion: apps/v1@' | sed 's@ replicas: 1@ replicas: 1\n selector: {"matchLabels": {"app": "helm", "name": "tiller"}}@' | kubectl apply -f -" , although helm problem will be get solved, but it also has some effects , for example minikube start problems.
finally, i find that the client version and server version of kubectl must be the same. so make the version match and this issue will be solved.

**Comment by sergiomartins8** [comment]
It worked for me with the following:

1. `kubectl apply -f tiller.yaml`

1. `helm init --service-account tiller --override spec.selector.matchLabels.'name'='tiller',spec.selector.matchLabels.'app'='helm' --output yaml | sed 's@apiVersion: extensions/v1beta1@apiVersion: apps/v1@' | kubectl apply -f -`


> **Tiller.yaml:**

```yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
```
