### ISSUE TITLE
helm3  - can't override the ConfigMap

### ISSUE THREAD

**Issue by cynial** [helm/helm#6475]
helm version: 
v3.0.0-beta.3

kubectl version:
1.10.5

---

Upgrade haproxy-ingress 

`helm upgrade haproxy-ingress haproxy-ingress`

```
# values.yaml

controller:
  config:
    config-defaults: |
      option forwardfor header X-Real-IP
```

Check the configmap 

`kubectl describe configmap haproxy-ingress-controller`

```
Data
====
config-defaults:
----
option forwardfor header X-Real-IP
```
 ---

Change the configmap to: 

```
# values.yaml

controller:
  config:
    config-defaults: |
      option forwardfor header X-Real-IP
      option redispath
```

`helm upgrade haproxy-ingress haproxy-ingress`
`kubectl describe configmap haproxy-ingress-controller`

```
Data
====
config-defaults:
----
option forwardfor header X-Real-IP
```

Can't change the value of config-defaults.

---

It‘s working fine on helm2, but not helm3, has anyone encountered this issue?
