### ISSUE TITLE
Helm init --service-account tiller  on kubernetes 16.0 fails with error

### ISSUE THREAD

**Issue by n-able-consulting** [helm/helm#6478]
Executing:

#### script start
```
curl -LO https://git.io/get_helm.sh
chmod 700 get_helm.sh
./get_helm.sh

cat << EOF | kubectl apply -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
EOF

helm init --service-account tiller 
```
#### script end
Fails on the last statement, with error:
Error: error installing: the server could not find the requested resource.
Afterwards Tiller is not installed.

This exact script works for older versions of kubernetes 1.15.3<. Checked this.
But fails continuously on kubernetes v1.16.0

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Error: could not find tiller

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Bare Metal + ubuntu 18.04 os. Will try GCE + ubuntu 18.04 after finishing this issue. 

![helm-issue](https://user-images.githubusercontent.com/45829884/65446785-632c6e80-de35-11e9-81a6-239f5bff30b0.png)
