### ISSUE TITLE
$KUBECONFIG or --kubeconfig not working with helm init?

### ISSUE THREAD

**Issue by lucanaldini** [helm/helm#6503]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`Minikube`

I'm trying to understand why specifying `KUBECONFIG` or `--kubeconfig` in the `helm init` command has not the desired effect.

In my `~/.kube/config` configuration I have the following:
```
- cluster:
    certificate-authority: /Users/me/.minikube/ca.crt
    server: https://192.168.99.103:8443
  name: minikube
```
whereas in `/tmp/.kube/config` I have:
```
- cluster:
    certificate-authority: /Users/me/.minikube/ca.crt
    server: https://192.168.99.104:8443
  name: minikube
```

The correct server ip is `192.168.99.104`, so I would like to use the config in `/tmp/.kube/config`. Yes, I could change the ip in the default config location, but if you want to use a different config for any other reason, the problem remains.

If I run:
```KUBECONFIG=/tmp/.kube/config && helm init```
I eventually get the following error:
```dial tcp 192.168.99.103:8443: i/o timeout```
If I run:
```helm init --kubeconfig /tmp/.kube/config```
I get the same error.

If I run:
```export KUBECONFIG=/tmp/.kube/config && helm init```
then tiller is installed successfully. Of course this is not ideal because I have to remember to export `KUBECONFIG` back to its previous default value after the command completes.

Other commands like `helm ls` do not seem to be affected by this issue.
