### ISSUE TITLE
helm3 template fails when there are custom resource templates

### ISSUE THREAD

**Issue by paulczar** [helm/helm#6505]
Output of `helm version`: v3.0.0-beta.3

When I have a custom resource in a helm template, if I try and use `helm template` it fails with:

```
$ helm template .
Error: apiVersion "certmanager.k8s.io/v1alpha1" in test/templates/cert-pks.yaml is not available
```

but works with `helm install`

```
$ AME: test
LAST DEPLOYED: 2019-09-25 17:27:46.218812309 -0500 CDT m=+1.092955819
NAMESPACE: test
STATUS: deployed
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods -l "app=test,release=test" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
```

for reference sake ... I confirmed this behavior with a fresh `helm create test` and then added the following into templates dir

```yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "test.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "test.name" . }}
    helm.sh/chart: {{ include "test.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ include "test.fullname" . }}-cert
  dnsNames: ["bacon.potato.org"]
  acme:
    config:
    - dns01:
        provider: prod-clouddns
      domains: ["bacon.potato.org"]
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

```
