### ISSUE TITLE
How do I use git-sync with stable/airflow?

### ISSUE THREAD

**Issue by jpmolinamatute** [helm/helm#6509]
Output of `helm version`:  **v2.14.3**
Output of `kubectl version`: **v1.15.2**
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  **AKS**

Hello World!

I'm following the instructions from `helm inspect stable/airflow`, I have created a secrect
```sh
kubectl create secret generic airflow-secret --from-file=id_rsa=/home/juanpa/.ssh/airflow-key --from-file=known_hosts=/home/juanpa/.ssh/known_hosts --from-file=id_rsa.pub=/home/juanpa/.ssh/airflow-key.pub
```

and this bare minimum config file:

```yaml
airflow:
  image:
    repository: puckel/docker-airflow
    tag: 1.10.4
  schedulerNumRuns: "-1"
  config:
    AIRFLOW__CORE__DAGS_FOLDER: /usr/local/airflow/repo/data-pipeline/airflow_data/dags
dags:
  path: /usr/local/airflow/repo
  git:
    url: https://github.com/acend-io/data-pipeline.git
    ref: master
    secret: airflow-secret
  initContainer:
    enabled: true
    image:
      repository: alpine/git
      tag: 1.0.7
      pullPolicy: IfNotPresent
    installRequirements: false
```
when I enable initContainer the schedule, worker and web pod become Init:CrashLoopBackOff state and I cannot debug the reason why those pod are failing, if I disable initContainer everything works but without git-sync

so the big question is what am I missing? thanks for the help!
