### ISSUE TITLE
Helm3-beta.1 --dependency-update gives an error ".config/helm/repositories.yaml: no such file or directory"

### ISSUE THREAD

**Issue by NishikaDeSilva** [helm/helm#6531]
Output of `helm version`: v3.0.0-beta.1

Output of `kubectl version`: v1.10.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

I'm trying to install a chart with NFS dependency with the following command. 

```
helm install {CHART_NAME} {CHART} --dependency-update
```
But this command provides following error:

```
Error: couldn't load repositories file (/home/ubuntu/.config/helm/repositories.yaml): open /home/ubuntu/.config/helm/repositories.yaml: no such file or directory
```
*requirements.yaml* : 
```
dependencies:
  - name: nfs-server-provisioner
    version: "0.3.0"
    repository: "https://kubernetes-charts.storage.googleapis.com"
    tags:
      - internal-nfs
```
