### ISSUE TITLE
Append to a list in values.yaml?

### ISSUE THREAD

**Issue by reloaded** [helm/helm#6569]
Hello,

Is there a way to append to a YAML list/array via value overrides? 

For example if I have this `values.yaml`

```
produce:
  - name: strawberry
  - name: cucumber
  - name: orange
```

And this `values.overrides.yaml`
```
produce:
  - name: kale
  - name: beets
```

I'd like Helm to append to the list and not override it. Currently running `helm upgrade . -i -f values.yaml -f values.overrides.yaml` results in this transformed configuration:

```
produce:
  - name: kale
  - name: beets
```

But I'd like it to produce (no pun intended)
```
produce:
  - name: strawberry
  - name: cucumber
  - name: orange
  - name: kale
  - name: beets
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube
