### ISSUE TITLE
Helm3: Use registry as dependency URL

### ISSUE THREAD

**Issue by phoenix-bjoern** [helm/helm#6593]
Helm 3 has a new chart command to push/pull charts to a OCI registry. This seems to be an alternative to repositories to maintain dependencies. But ATM you have to retrieve each of the charts manually:

```
helm3 chart pull registry.local/application/helm-chart:latest
helm3 chart export registry.local/application/helm-chart:latest
```

I would expect that helm could manage the charts retrieved from OCI registries in the same way it pulls dependencies from chart repositories. Therefore chart dependencies in OCI registries should be declared in Charts.yaml in the same way:

```
dependencies: 
  - name: my-application
    version: 1.0.0
    condition: my-application.enabled
    repository: registry.local/application/helm-chart:latest
```

However this currently just causes an error.

Do I misunderstand the concept of OCI image/registry support for charts? Or is the additional support for OCI registries as dependency just a missing feature?

**Comment by bacongobbler** [comment]
Thanks for raising this.

OCI support as [a getter](https://github.com/helm/helm/tree/dev-v3/pkg/getter) (a dependency) is currently a missing feature. OCI registry support is experimental and isn't fully integrated with the rest of the CLI similar to chart repositories.

**Comment by bcg62** [comment]
this is a blocker for adoption, would much prefer to use registry storage and break free of repo managers.

this is core functionality needed for common use cases

**Comment by bacongobbler** [comment]
@bcg62 feel like taking this one on as a contribution?

**Comment by phroggyy** [comment]
@bacongobbler this is something I'm currently needing to proceed with a much simplified implementation of an umbrella chart. Hence, I'd love to have a look at contributing this functionality (perhaps alongside resolving #6982 which I believe is effectively two sides of the same coin). Do you, as a core maintainer, have a preference for how to annotate registry retrieval? Done implicitly, either through parsing the URL (checking for a tag by splitting on `:`) or trying the source in both "modes", or explicitly, e.g `oci: true`, or `oci@regist.ry/some/chart` (`latest` implicit, unless specified).

To summarise the options:

```yaml
dependencies: 
  - name: my-application
    version: 1.0.0
    repository: https://eu.gcr.io/project/helm-chart:latest # implicit OCI by specifying a tag

  - name: my-application
    version: 1.0.0
    repository: https://eu.gcr.io/project/helm-chart # implicit: check if it works as a regular chart first, otherwise try OCI with `:latest`

  - name: my-application
    version: 1.0.0
    repository: oci@eu.gcr.io/project/helm-chart # explicit OCI by specifying the mode in the URL

  - name: my-application
    version: 1.0.0
    oci: true # explicit boolean annotation
    repository: eu.gcr.io/project/helm-chart # explicit OCI by specifying the mode in the URL
```
