### ISSUE TITLE
helm 2 not forwarding values to dependency correctly

### ISSUE THREAD

**Issue by felippe-mendonca** [helm/helm#6605]
Output of `helm version`: 
```shell
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Output of `kubectl version`: 
```shell
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.24", GitCommit:"2ce02ef1754a457ba464ab87dba9090d90cf0468", GitTreeState:"clean", BuildDate:"2019-08-12T22:05:28Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

I'm working on a project that uses a chart as a dependency. This chart has another dependency with a condition.

My project:
```yaml
dependencies:
  - name: foo
    version: 0.1.0
```

foo project:
```yaml
dependencies:
  - name: bar
    version: 0.1.0
    condition: bar.enabled
```

When defining values for my project, the following configuration doesn't disable the dependency of `bar`.

```yaml
foo:
  bar:
    enabled: false
```

But, if I put `bar` values on a upper level:

```yaml
foo:
bar:
  enabled: false
```

Is that right? It only fails to enable/disable dependencies, all others values as working well.
