### ISSUE TITLE
Cannot access .Chart.AppVersion of parent in subchart

### ISSUE THREAD

**Issue by kprasad99** [helm/helm#6647]
I've  Parent chart which has multiple subcharts, for simplicity let subcharts be 2, of the two subchart in one chart I've an application which exposes REST endpoint to get the Release Version. I'm exposing the `Release Version` using `AppVersion` to application using `configmap`, config map template is shown as below. The issue is AppVersion here renders to subcharts AppVersion, not the AppVersion of Parent, Even tried with Release.Version, Release.Version renders Empty in subcharts.

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "k-config-example.fullname" . }}
  labels:
    app: {{ template "k-config-example.name" . }}
    chart: {{ template "k-config-example.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.properties: |-
    chart.name: {{ .Release.Name }}
    chart.version: {{ .Chart.AppVersion }} 
```

Output of `helm version`:
````
$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

````
Output of `kubectl version`:

````
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

````

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  On-Prem using Kubeadm

**Comment by hickeyma** [comment]
@kprasad99 From [Helm documentation](https://helm.sh/docs/chart_template_guide/#subcharts-and-global-values):

`A subchart is considered “stand-alone”, which means a subchart can never explicitly depend on its parent chart.  For that reason, a subchart cannot access the values of its parent.`

In your situation, it seems Helm is working as expected.

**Comment by kprasad99** [comment]
ok that stands good for AppVersion, but doesn't stand for Release Version, Release Version should be global scope right, Currently I'm getting {{ .Release.Version}} as blank in subchart

**Comment by iorlas** [comment]
@kprasad99 Helm has multiple versions, all tied to one Chart:

1. Chart version
2. App version
4. Release Version

The problem is, there is no such thing as "global release", i.e. release, which ties up subcharts as one release unit.

If you decompose your main chart into subcharts, you may not need to upgrade some dependencies(subcharts), since there could be no changes.

If you really need one global version for your release, if would be smarter to have one Chart instead.

**Comment by bacongobbler** [comment]
Perhaps you meant `.Release.Revision`. There is no such thing as `.Release.Version`. Please refer to [the documentation for a list of built-in objects available to charts](https://helm.sh/docs/chart_template_guide/#built-in-objects).

Closing as answered. Please comment on here if this should be re-opened for further discussion. Thanks.

**Comment by kprasad99** [comment]
@bacongobbler  `.Release.Revision` start from 1, which would give me info on deployed charts state whether there is upgrade or not etc.

@iorlas  `which ties up subcharts as one release unit.` this what I wanted, I wanted subcharts tied to release unit and wanted to store this release unit in a configmap written/part of one of the subcharts.

Here is my chart release plan.

.Initial Release
````
k-parent:
    version: 1.2.0
    charts:
        - subchart-1
           version: 0.5.0
        - subchart-2
           version: 0.6.0
           # this chart has configmap template which would store the version 1.2.0
```` 

.Second Release
````
k-parent:
    version: 1.2.1
    charts:
        - subchart-1
           version: 0.6.0
        - subchart-2
           version: 0.6.0
           # want to update the configmap with version 1.2.1
````

Here are my questions

- Why `{{ .Release.Version }}` is blank in subcharts?
- Is there any mechanism to create a variable which can be set in parent .tpl which can be accessed from subcharts
- Is there any mechanism to check if this subchart or standalone chart?
