### ISSUE TITLE
Can not install Ingress resource 

### ISSUE THREAD

**Issue by creativearmenia** [helm/helm#6648]
Trying to install ingress(apiVersion: extensions/v1beta1) will failed with error 

helm.go:81: [debug] the server could not find the requested resource

seems the issue is came from wait.go waitForResources method,  its try to request ingress from   NetworkingV1beta1 even the  apiVersion is extensions/v1beta1

```go
case *extensionsv1beta1.Ingress, *networkingv1beta1.Ingress:
				ing, err := w.c.NetworkingV1beta1().Ingresses(v.Namespace).Get(v.Name, metav1.GetOptions{})
				if err != nil {
					return false, err
				}
				if !w.ingressReady(ing) {
					return false, nil
				}
```

Output of `helm version`: 
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}

Output of `kubectl version`: 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.24", GitCommit:"2ce02ef1754a457ba464ab87dba9090d90cf0468", GitTreeState:"clean", BuildDate:"2019-08-12T22:05:28Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform GKE

**Comment by hickeyma** [comment]
PR #6651 opened to fix this.

**Comment by hickeyma** [comment]
@creativearmenia Can you provide more information on what you are running? is the chart a scaffold chart (`helm create`)? If not, can you provide more details on the chart and how you are running it?

**Comment by creativearmenia** [comment]
We have chart and I am trying to migrate from 2 to helm3.
On install helm fails "the server could not find the requested resource", as I understand helm try to check status by getting ingress from NetworkingV1beta1 which is wrong because our ingress belong to apiVersion: extensions/v1beta1

**Comment by hickeyma** [comment]
@creativearmenia  Are you installing a chart in v3 and it fails on the ingress resource? If so, can you show the template with the ingress?

**Comment by creativearmenia** [comment]
check the test chart repo https://github.com/creativearmenia/test-chart

run `helm upgrade --install --atomic bobo ./admin-panel` 

Error: release bobo failed, and has been uninstalled due to atomic being set: the server could not find the requested resource

**Comment by hickeyma** [comment]
Was the chart installed by Helm v2 first and then upgrade by Helm v3? Or installed by Helm v3 only?

**Comment by hickeyma** [comment]
What output do you get if you run the command with `--dry-run --debug` flags?

**Comment by creativearmenia** [comment]
```
λ helm upgrade --install --atomic --dry-run --debug  boo .\admin-panel\
history.go:52: [debug] getting history for release boo
Release "boo" does not exist. Installing it now.
install.go:148: [debug] Original chart version: ""
install.go:165: [debug] CHART PATH: C:\Users\sako\Desktop\test-chart\admin-panel

NAME: boo
LAST DEPLOYED: Fri Oct 11 17:58:53 2019
NAMESPACE: default
STATUS: pending-install
REVISION: 1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
{}

HOOKS:
MANIFEST:
---
# Source: admin-panel/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-test
  labels:
    app.kubernetes.io/name: "testingress"
spec:
  rules:
    - host: testdomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: test-service
              servicePort: 80

```

wihtout --dry-run flag
```
λ helm upgrade --install --atomic --debug  boo .\admin-panel\
history.go:52: [debug] getting history for release boo
Release "boo" does not exist. Installing it now.
install.go:148: [debug] Original chart version: ""
install.go:165: [debug] CHART PATH: C:\Users\sako\Desktop\test-chart\admin-panel

client.go:87: [debug] creating 1 resource(s)
wait.go:51: [debug] beginning wait for 1 resources with timeout of 5m0s
install.go:311: [debug] Install failed and atomic is set, uninstalling release
uninstall.go:90: [debug] uninstall: Deleting boo
client.go:215: [debug] Starting delete for "ingress-test" Ingress
uninstall.go:123: [debug] purge requested for boo
Error: release boo failed, and has been uninstalled due to atomic being set: the server could not find the requested resource
helm.go:81: [debug] the server could not find the requested resource
release boo failed, and has been uninstalled due to atomic being set
helm.sh/helm/v3/pkg/action.(*Install).failRelease
        /home/circleci/helm.sh/helm/pkg/action/install.go:319
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:283
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:209
main.newUpgradeCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/upgrade.go:111
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```
