### ISSUE TITLE
Values files don't get deeply merged

### ISSUE THREAD

**Issue by pablogarciamiranda** [helm/helm#6668]
Hi,

I would like to deeply merge the content of two yaml arrays of two different values files when running an upgrade.

```
# values_myrelease.yaml
secrets:
  - key: DB_PASSWORD
     value: SET_IN_ENVIRONMENT
```

```
# values_environment.yaml
secrets:
   - key: DB_PASSWORD
      value: admin1234
   - key: OTHER_PASSWORD
      value: 1234admin
```

The desired result after applying the helm upgrade would be:

> $ helm upgrade --install myrelease ./ --values values_myrelease.yaml --values values_environment.yaml

```
secrets:
  - key: DB_PASSWORD
     value: admin1234
```

Bu the result is:
```
secrets:
   - key: DB_PASSWORD
      value: admin1234
   - key: OTHER_PASSWORD
      value: 1234admin
```

Is this the desired behavior or is it a bug? How could I achieve my goal?

Many thanks,
 Pablo

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"archive", BuildDate:"2019-06-18T20:40:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): OpenStack

**Comment by pablogarciamiranda** [comment]
I guess the problem is just for arrays because for normal key/value pairs is working.

My workaround is the following:
```
# values_myrelease.yaml
secrets:
  DB_PASSWORD:
    required: true
    value: SET_IN_ENVIRONMENT
```
 
```
# values_environment.yaml
secrets:
  DB_PASSWORD:
    value: admin1234
  OTHER_PASSWORD:
    value: 1234admin
```

The expected value is:
```
secrets:
  DB_PASSWORD:
    value: admin1234
    required: true
  OTHER_PASSWORD:
    value: 1234admin
```

So now I can play in the template with only the required secrets using if statements.

**Comment by iorlas** [comment]
Yeeaah... This is how YAML parsers work. This is how structure merge works.

Either way, looking at your example, I don't think it is right way to supply values. You should describe applicable values in the Chart, then override it on upgrade/install. So your workaround it intended usage.

What's wrong with it, why it feels workaround-y to you? Why you need an array of secrets instead of fields for each secret?

**Comment by pablogarciamiranda** [comment]
Hi @iorlas,

I have a Chart which is used to deploy many applications.
For each application I have a values.yaml file where I specify the secret names that I just need for that application:
```
secrets:
 DB_PASSWORD:
    required: true
    value: SET_IN_ENVIRONMENT
```
And then I have a values_environment.yaml file with the sensitive data of all the secrets of all the applications (Which is not persisted in any repository).

```
secrets:
  DB_PASSWORD:
    value: admin1234
  OTHER_PASSWORD:
    value: 1234admin
```

My goal is to have just one secret.yaml file and create the data dynamically depending on the data that I have in the values.yaml for that application:
```
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
{{- range $secretName, $properties := .Values.secrets }}
  {{ if $properties.required }}
    {{ $secretName }}: {{ $properties.value | b64enc | quote }}
  {{ end }}
{{- end }}
```


 many different values.yaml file per application I am deploying, as all the
