### ISSUE TITLE
Helm didn't fill range property

### ISSUE THREAD

**Issue by petrklimov** [helm/helm#6721]
I'm trying to deploy elasticsearch with helm. For charts i'm using https://github.com/elastic/helm-charts/tree/master/elasticsearch
I use the follwing command 
```
helm repo add elastic https://helm.elastic.co 
helm install --name elasticsearch elastic/elasticsearch
helm get elasticsearch
```
i got that env variable is not set up
```
        env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: cluster.initial_master_nodes
            value: ""
```
expected result is
```
        env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: cluster.initial_master_nodes
            value: "elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2,"
```
in templates/helpers.tpl this fragment isn't working properly, in pervious version it works fine
```
{{- define "endpoints" -}}
{{- $replicas := .Values.replicas | int }}
{{- $uname := printf "%s-%s" .Values.clusterName .Values.nodeGroup }}
  {{- range $i, $e := untilStep 0 $replicas 1 -}}
{{ $uname }}-{{ $i }},
  {{- end -}}
{{- end -}}
```
Output of `helm version`:
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform Minikube
