### ISSUE TITLE
Helm could not find tiller

### ISSUE THREAD

**Issue by msschl** [helm/helm#6740]
```
kubectl create ns tiller-controller
kubectl apply -f src/helm/rbac/rbac.yaml

helm init \
        --tiller-namespace tiller-controller \
        --tiller-tls \
        --tiller-tls-cert src/helm/certificates/tiller.cert.pem \
        --tiller-tls-key src/helm/certificates/tiller.key.pem \
        --tiller-tls-verify \
        --tls-ca-cert src/helm/certificates/base-ca.cert.pem \
        --service-account tiller \
        --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}' \
        --history-max 3 \
        --wait
```

Output:
```
serviceaccount/tiller created
clusterrole.rbac.authorization.k8s.io/tiller-manager unchanged
$HELM_HOME has been configured at C:\Users\Markus\.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
Error: could not ping Tiller: context deadline exceeded
```

rbac.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: tiller-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tiller-manager
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
```

Binding for specific namespaces:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tiller-binding
  namespace: <NAMESPACE>
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: tiller-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tiller-manager
```

Output of `kubectl get pods -n tiller-controller`
```
$ kubectl get pods -n tiller-controller
NAME                             READY   STATUS    RESTARTS   AGE
tiller-deploy-85665c4869-wlkzg   1/1     Running   0          15m
```

Output of `kubectl get events --all-namespaces | grep -i tiller`:
```
$ kubectl get events --all-namespaces | grep -i tiller
tiller-controller   <unknown>   Normal   Scheduled           pod/tiller-deploy-85665c4869-wlkzg    Successfully assigned tiller-controller/tiller-deploy-85665c4869-wlkzg to lxkubenode01
tiller-controller   4m20s       Normal   Pulled              pod/tiller-deploy-85665c4869-wlkzg    Container image "gcr.io/kubernetes-helm/tiller:v2.15.0" already present on machine
tiller-controller   4m20s       Normal   Created             pod/tiller-deploy-85665c4869-wlkzg    Created container tiller
tiller-controller   4m19s       Normal   Started             pod/tiller-deploy-85665c4869-wlkzg    Started container tiller
tiller-controller   4m21s       Normal   SuccessfulCreate    replicaset/tiller-deploy-85665c4869   Created pod: tiller-deploy-85665c4869-wlkzg
tiller-controller   4m21s       Normal   ScalingReplicaSet   deployment/tiller-deploy              Scaled up replica set tiller-deploy-85665c4869 to 1
```

Output of `helm version`:
```
$ helm version --tls
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Error: could not find tiller
```

Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kubeadm self hosted kubernetes cluster
