### ISSUE TITLE
helm (v2.15.) upgrade with --wait is waiting till timeout and not showing status even though all kubernetes resources are in ready state.

### ISSUE THREAD

**Issue by saif-cl0ud** [helm/helm#6751]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On prem (Vmware)

I am trying to upgrade my chart. Everything is working fine in Kubernetes and all the Kubernetes resources is created and in ready state but helm is not showing status if I am using --wait.

This issue is coming only in helm v2.15.0 earlier version was working fine. The tiller pod is throwing following error.

[kube] 2019/10/22 23:21:38 Created a new Ingress called "dev-drupal"
[kube] 2019/10/22 23:21:38 beginning wait for 13 resources with timeout of 10m0s
[kube] 2019/10/22 23:21:40 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:21:42 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:21:44 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:21:46 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:21:48 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:21:50 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:21:52 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:21:54 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:21:56 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:21:58 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:00 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:02 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:04 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:06 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:08 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:10 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:12 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:14 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:16 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:18 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:20 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:22 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:24 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:26 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:28 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:30 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:32 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:34 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:36 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:38 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:40 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:42 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:44 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:46 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:48 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:50 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:52 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:54 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:56 Ingress is not ready: dev/drupal-ingress
[kube] 2019/10/22 23:22:58 Ingress is not ready: dev/drupal-ingress

**Comment by bacongobbler** [comment]
Can you show the output of the ingress template? Helm 2.15.0 introduced wait logic for ingress, which may not be catching a particular condition or mode.

cc @ds-ms as this was implemented in https://github.com/helm/helm/pull/5264. Would you mind investigating this further?

**Comment by Elexy** [comment]
It bit me too. My ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ***-ingress
  annotations:
      certmanager.k8s.io/cluster-issuer: "letsencrypt"
      ingress.kubernetes.io/custom-response-headers: "server:"
      kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: ***-svc
              servicePort: 80
      host: some.domain.net

  tls:
    - hosts:
        - some.domain.net
      secretName: ***-dev-cert
```
