### ISSUE TITLE
helm 3 beta 5 throws an error with --wait --timeout

### ISSUE THREAD

**Issue by antoineozenne** [helm/helm#6759]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-beta.5", GitCommit:"509a8819b7e8dba86b7982c006fce22628aeea28", GitTreeState:"clean", GoVersion:"go1.13.3"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On-premise platform.

This is my chart :
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.xxx.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.xxx.name | quote }}
    app.kubernetes.io/component: {{ .Values.xxx.name | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.xxx.name | quote }}
      app.kubernetes.io/component: {{ .Values.xxx.name | quote }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.xxx.name | quote }}
        app.kubernetes.io/component: {{ .Values.xxx.name | quote }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      containers:
      - name: {{.Values.xxx.name}}
        image: yyy.fr/xxx:{{.Values.xxx.image.tag}}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:                  
        - name: XXX
          value: xxx                  
        - name: Logging__LogLevel__Default
          value: {{ .Values.loglevel | quote }}
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
      imagePullSecrets:
      - name: secretname
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.xxx.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
  - hosts:
    - {{ required "A valid .Values.ingress.host entry required!" .Values.ingress.host | quote }}
    secretName: {{ .Values.tls.name | quote }}
  rules:
  - host: {{ required "A valid .Values.ingress.host entry required!" .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.xxx.name | quote }}
          servicePort: 80
---
apiVersion: v1
data:
  .dockerconfigjson: XXX
kind: Secret
metadata:
  name: secretname
  namespace: {{.Release.Namespace}}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.tls.name}}
  namespace: {{.Release.Namespace}}
type: kubernetes.io/tls
data:
  tls.crt: XXX
  tls.key: YYY
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.xxx.name}}
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: {{.Values.xxx.name}}
spec:
  ports:
  - name: http-portal
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: {{.Values.xxx.name}}
```
And this is my values.yaml :
```yaml
ingress:
  host:

xxx:
  name: xxx
  image:
    tag: latest

env: 
loglevel: 

tls:
  name: tlsname
```

Output of `helm upgrade --install mychart mychart_path --namespace=xxx --kube-context mycontext --wait --timeout 5m0s --set xxx.image.tag=latest --set ingress.host=xxx.fr --debug` :
```
history.go:52: [debug] getting history for release xxx
Release "xxx" does not exist. Installing it now.
install.go:148: [debug] Original chart version: ""
install.go:165: [debug] CHART PATH: D:\mychart_path

client.go:87: [debug] creating 5 resource(s)
wait.go:52: [debug] beginning wait for 5 resources with timeout of 5m0s
Error: the server could not find the requested resource
helm.go:81: [debug] the server could not find the requested resource
```

If I change the deployment's apiVersion from `extensions/v1beta1` to `apps/v1`, the output become :
```
history.go:52: [debug] getting history for release xxx
Release "xxx" does not exist. Installing it now.
install.go:148: [debug] Original chart version: ""
install.go:165: [debug] CHART PATH: D:\mychart_path

client.go:87: [debug] creating 5 resource(s)
wait.go:52: [debug] beginning wait for 5 resources with timeout of 5m0s
wait.go:209: [debug] Deployment is not ready: xxx/xxx. 0 out of 1 expected pods are ready
wait.go:209: [debug] Deployment is not ready: xxx/xxx. 0 out of 1 expected pods are ready
wait.go:209: [debug] Deployment is not ready: xxx/xxx. 0 out of 1 expected pods are ready
wait.go:209: [debug] Deployment is not ready: xxx/xxx. 0 out of 1 expected pods are ready
wait.go:209: [debug] Deployment is not ready: xxx/xxx. 0 out of 1 expected pods are ready
wait.go:209: [debug] Deployment is not ready: xxx/xxx. 0 out of 1 expected pods are ready
wait.go:209: [debug] Deployment is not ready: xxx/xxx. 0 out of 1 expected pods are ready
Error: the server could not find the requested resource
helm.go:81: [debug] the server could not find the requested resource
```

The last commands should succeeded, like the following. Output of `helm upgrade --install mychart mychart_path --namespace=xxx--kube-context mycontext --set xxx.image.tag=latest --set ingress.host=xxx.fr` (so without `--wait` and `--timeout 5m0s`) :
```
Release "xxx" does not exist. Installing it now.
NAME: xxx
LAST DEPLOYED: Wed Oct 23 11:13:23 2019
NAMESPACE: xxx
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
--> It's ok.

I found this issue in helm 3 beta 4 first.

**Comment by bacongobbler** [comment]
thank you for the report. I'll try and see if I can reproduce this today and identify the issue.

**Comment by adamreese** [comment]
does running `kubectl describe` on the deployment provide any useful information?

**Comment by yizha** [comment]
I had the same issue yesterday when trying to install an ingress rule to my 1.13 k8s cluster with helm v3 running with '--wait'.

After adding '--debug' to 'helm install' I got below '404'

`
I1026 21:48:26.755390   66653 round_trippers.go:443] GET https://my-cluster-api-server-hostname/apis/networking.k8s.io/v1beta1/namespaces/airflow/ingresses/airflow-webserver 404 Not Found in 299 milliseconds
`

I believe it used a wrong apiVersion, for k8s 1.13 it should use 'extensions/v1beta1' ('networking.k8s.io/v1beta1' is for 1.14 and above).

**Comment by yizha** [comment]
Looks like a dup of https://github.com/helm/helm/issues/6621.

**Comment by antoineozenne** [comment]
See the result of `kubectl describe deployment xxx -n xxx` :

```yaml
Name:                   xxx
Namespace:              xxx
CreationTimestamp:      Mon, 28 Oct 2019 09:10:47 +0000
Labels:                 app.kubernetes.io/component=xxx
                        app.kubernetes.io/name=xxx
                        helm.sh/chart=xxx-0.0.1
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app.kubernetes.io/component=xxx,app.kubernetes.io/name=xxx,helm.sh/chart=xxx-0.0.1
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  0 max unavailable, 2 max surge
Pod Template:
  Labels:  app.kubernetes.io/component=xxx
           app.kubernetes.io/name=xxx
           helm.sh/chart=xxx-0.0.1
  Containers:
   xxx:
    Image:      xxx:latest
    Port:       80/TCP
    Host Port:  0/TCP
    Readiness:  http-get http://:80/ delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ZZZ:                         Production
      YYY:                         YYY
      XXX:                         XXX
      Logging__LogLevel__Default:
    Mounts:                        <none>
  Volumes:                         <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   xxx-8679546bff (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  50s   deployment-controller  Scaled up replica set xxx-8679546bff to 1
```

I have an Ingress too, `kubectl describe ingress xxx -n xxx` :
```yaml
Name:             xxx
Namespace:        xxx
Address:
Default backend:  default-http-backend:80 (<none>)
TLS:
  xxx terminates xxx.fr
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  xxx.fr
                          /   xxx:80 (<none>)
Annotations:
  kubernetes.io/ingress.class:  traefik
Events:                         <none>
```
