### ISSUE TITLE
Possible race condition when deploying resources with helm (with example)

### ISSUE THREAD

**Issue by jamesla** [helm/helm#6769]
I have found what appears to me to look like a race condition in helm. I have created a template that deploys fine with kubectl however not with helm install.

Given the template:

```
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: mypipeline
spec:
  resources:
    - name: git-source
      type: git
  tasks:
    - name: build-docker-image
      taskRef:
        name: mytask
      resources:
        inputs:
          - name: git-source
            resource: git-source
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mytask
spec:
  inputs:
    resources:
      - name: git-source
        type: git
  steps:
    - name: build
      image: ubuntu
      command: ["/bin/bash"]
      args:
        - -c
        - echo building
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: git-source-$(uid)
    spec:
      type: git
      params:
      - name: revision
        value: $(params.gitrevision)
      - name: url
        value: $(params.gitrepositoryurl)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: mycipipeline
    spec:
      pipelineRef:
        name: mypipeline
      params:
      - name: message
        value: $(params.message)
      - name: contenttype
        value: $(params.contenttype)
      resources:
      - name: git-source
        resourceRef:
          name: git-source-$(uid)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: foo-trig
      binding:
        name: pipeline-binding
      template:
        name: pipeline-template
      params:
      - name: message
        value: Hello from the Triggers EventListener!
```

Works fine with:
```
kubectl apply -f file.yaml 
```

After adding to an empty helm projects template directory it breaks with: 
```
helm install .
```

Error: release ornery-yak failed: admission webhook "triggers-webhook.tekton.dev" denied the request: mutation failed: invalid value: triggerbindings.tekton.dev "pipeline-binding" not found: spec.triggers[0].binding.name

Given that it works fine with kubectl it looks like it's a problem with the way helm deploys. I'm a bit stuck with this one. Does anybody know what could be causing this?

---

Output of `helm version`:
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTre`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

This example also uses tekton pipelines so if you are trying to reproduce it you will need to run the following to get the CRDs:

kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
kubectl apply --filename https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml

**Comment by psschwei** [comment]
I have also had the same error occur when trying to install a Tekton Pipeline/Trigger via Helm (installs fine with `kubectl apply -f <template>`.

Relevant portion of template:

```
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: {{ .Release.Name }}-pipelinebinding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: default
    - name: gitrepositoryurl
      value: "https://github.ibm.com/$(body.repository.full_name)"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ .Release.Name }}-tekton-poc-listener
spec:
  serviceAccountName: {{ .Release.Name }}-tekton-triggers-admin
  triggers:
    - binding:
        name: {{ .Release.Name }}-pipelinebinding
      template:
        name: {{ .Release.Name }}-triggertemplate
```

Error message:
Error: release flippant-squid failed: Internal error occurred: admission webhook "triggers-webhook.tekton.dev" denied the request: mutation failed: invalid value: triggerbindings.tekton.dev "flippant-squid-pipelinebinding" not found: spec.triggers[0].binding.name

`helm version`
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:21:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9+IKS", GitCommit:"405ef9ab782f5b51dff56dabe3628585d99afbfa", GitTreeState:"clean", BuildDate:"2019-11-13T21:34:44Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider: IBM
