### ISSUE TITLE
Helm 3 cannot find dependencies during deploy with Helm Operator

### ISSUE THREAD

**Issue by masterkain** [helm/helm#6781]
Output of `helm version`:

`version.BuildInfo{Version:"v3.0.0-beta.5", GitCommit:"509a8819b7e8dba86b7982c006fce22628aeea28", GitTreeState:"clean", GoVersion:"go1.13.3"}`

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

I'm deploying a custom chart in a new EKS 1.14 cluster with Flux and Helm Operator.
This chart is for a rails app and has two requirements, redis and memcached.

```
2019-10-24T14:21:04.184450486Z ts=2019-10-24T14:21:04.184341328Z caller=chartsync.go:555 component=chartsync release=bstore-prod targetNamespace=prod resource=prod:helmrelease/bstore-prod warning="failed to update chart dependencies" err="no repository definition for https://kubernetes-charts.storage.googleapis.com/, https://kubernetes-charts.storage.googleapis.com/. Please add them via 'helm repo add'"
```

Chart.yaml (same issue with requirements.yaml)

```yaml
apiVersion: v2
#...
  - name: memcached
    version: ~3.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: ~9.3
    repository: https://kubernetes-charts.storage.googleapis.com/

```
