### ISSUE TITLE
Passing value to map inside list with --set removes other keys from map

### ISSUE THREAD

**Issue by ellisboddington** [helm/helm#6847]
I have a `values.yaml` that looks something like this:
```
ingress:
  enabled: true
  hosts:
    - host: example.com
      paths:
        - /api(.*)
```

I want to override only the value `example.com` with `--set`.

I'm trying `--set "ingress.hosts[0].host=foo.com"` but the output becomes this:
```
ingress:
  enabled: true
  hosts:
    - host: foo.com
```

So `paths` has been deleted from `ingress.hosts`. This isn't the behaviour I'd expect - am I doing something wrong? Is there a way to achieve what I want without having to duplicate the value under `paths` into my `--set` command, which I want to remain unchanged?
