### ISSUE TITLE
appVersion unmarshalling error, detected as a floating point

### ISSUE THREAD

**Issue by vicentfg** [helm/helm#6849]
If I try to use helm v3 release candidate with existing repositories on our organization, the helm repo add command fails. I was able to replicate it with this simple example:

index.yaml
```
apiVersion: v1
entries:
  test-chart:
  - apiVersion: v1
    appVersion:  72551e2
    created: 2019-05-06T14:27:00.396Z
    description: Test description
    digest:
    name: test-chart-example
    urls:
    - https://example.com/test-example-0.0.1-0.tgz
    version: 0.0.1-0
generated: "2019-10-31T14:14:13.186531513+02:00"
```

```
$ helm3 repo add test-local-repo http://localhost:8000
Error: looks like "http://localhost:8000" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal number into Go struct field ChartVersion.entries.appVersion of type string
```
It seems that yaml parser detects the appVersion as a floating point. This worked correctly with helm version v3.0.0-beta.5, but fails with v3.0.0-rc.1

Output of `helm version`: 
```
$ helm3 version
version.BuildInfo{Version:"v3.0.0-rc.1", GitCommit:"ee77ae3d40fd599445ebd99b8fc04e2c86ca366c", GitTreeState:"clean", GoVersion:"go1.13.3"}
```
