### ISSUE TITLE
Override one field of list in --set

### ISSUE THREAD

**Issue by DP19** [helm/helm#6853]
Output of `helm version`: 2.13.1

Output of `kubectl version`: 1.14.6

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 1.14.7-eks

I've seen some other issues sort of relating to this but nothing that really gives me hope this is possible. Any help would be great.

We have about ~100 deployments/cronjobs we're managing in our clusters via helm that we've built. We're now trying to bring up new environments by using a "super" chart that has all of our apps in it to deploy it all at once. 

However our cronjobs can be multi instance so we decided to have each helm chart be a list of jobs to setup on cron. Here's a subset of the top level values.yaml:

```
myapp-v1:
  targetcluster: "cluster"
  configBranch: "testBranch"
  jobs:
  - name: mycron
    image:
      repository: gcr.io/myapp
      tag: develop
      pullPolicy: IfNotPresent
    #schedule is in UTC time
    schedule: "00 16 * * *"
    command: '["/bin/sh", "-c"]'
    args:
      - |
        trap 'exit_status="$?" ; touch /app/myapp/logs/term ; exit "$exit_status"' EXIT
        java -Duser.timezone=America/New_York -jar -Xmx1024m *.jar
    restartPolicy: Never
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    startingDeadlineSeconds: 600
    activeDeadlineSeconds:
    concurrencyPolicy: Forbid
    backoffLimit: 0
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1"
      limits:
        memory: "2048Mi"
        cpu: "1.5"
```

We want to be able to deploy this chart and just change the version being deployed / upgraded but it seems this isn't possible without putting all of this list in the ```--set``` command. I've tried to template this and use ```--set myapp-v1.jobs[0].image.tag=testing123```
It renders but it overwrites the entire list to only have the image.tag and nothing else and it won't deploy successfully. Is there any option to get this working? Is this supposed to work already?
