### ISSUE TITLE
Error: validation: chart.metadata is required when using --repo

### ISSUE THREAD

**Issue by pniederlag** [helm/helm#6864]
I am trying to upgrade/install a chart in my cluster. I want to load the chart "on the fly" from a remote without configuring the repo beforehand (running this process on CI).

```
helm upgrade foo foo --install --repo https://someartifactory.example.com/some-helm-repo/ --username foo --password bar --version 0.5.0
```

For some reason I get 

```
Error: validation: chart.metadata is required
```

Downloading the chart first and installing it from local .tgz is working as expected. Also it's working installing it from a local configured repository. It seems to affect only the --repo approach.index.yaml from the repo seems fine also to me.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-rc.1", GitCommit:"ee77ae3d40fd599445ebd99b8fc04e2c86ca366c", GitTreeState:"clean", GoVersion:"go1.13.3"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by karuppiah7890** [comment]
@pniederlag I tried to reproduce this. The only way that worked was - creating a bad chart, one without `Chart.yaml` (chart metadata); then creating a tar ball using `tar` as `helm package` returned error. And then creating an index for it manually as using `helm repo index` also didn't work for an invalid chart. And then I tried to run a command similar to what you provided - 

```
$ helm upgrade test test --install --repo http://localhost:5000
Release "test" does not exist. Installing it now.
Error: validation: chart.metadata is required
```

 and it gave the above error.

So with current experimentation and findings I can only say the chart was probably a bad chart. Could you help us with more details to reproduce the error?

**Comment by pniederlag** [comment]
Thx for taking a look onto it. Unfortunatly the repo and chart are none public.

Here are two more observations

helm upgrade chart https://repo.example.com/helm-repo/chart-0.5.0. tgz ... [WORKS]
helm upgrade chart chart --repo https://repo.example.com/helm-repo --version 0.5.0 [FAILS WITH missing metada]

It's really puzzling me. Is there any way I can debug helm fetching and scanning the index from the repositiory? As it is working also with another chart one more thing that comes to my mind is:

I am failing on chart "chart", there are also some more, unrelated charts "chart-other" in our repo.

As workaround I'll just head for the explicit helm upgrade chart https://repo.example.com/helm-repo/chart-0.5.0. tgz approach. 

Thx for your efforts on helm and your prompt feedback.

**Comment by karuppiah7890** [comment]
That's weird. The commands you showed, look logically the same, as behind the scenes, same chart needs to be installed. Just different ways to do it.

For debugging repo index, you can actually download the repository index using the `<repo-url>/index.yaml` , in your case, it would be `https://someartifactory.example.com/some-helm-repo/index.yaml`, here you can look for the chart using find in your editor with the chart name and there will be multiple versions under it. Here's an example:

```
apiVersion: v1
entries:
  blah:
  - apiVersion: v2
    appVersion: "72551e2"
    created: "2019-11-05T22:19:34.854835+05:30"
    description: A Helm chart for Kubernetes
    digest: 63176e7bf7ef6a056b75679e2fee78c168cf8fbc64552e62733b7c0eb3992b0e
    name: blah
    type: application
    urls:
    - blah-0.1.0.tgz
    version: 0.1.0
  meh:
  - apiVersion: v2
    appVersion: abcdef123
    created: "2019-11-05T22:19:34.85567+05:30"
    description: A Helm chart for Kubernetes
    digest: d4a55417c8e6825796c7c588466a264b99f3a7d1db6d71340ed4805e1b4790e2
    name: meh
    type: application
    urls:
    - meh-0.1.0.tgz
    version: 0.1.0
  test-chart:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-11-05T22:19:34.856514+05:30"
    description: A Helm chart for Kubernetes
    digest: f3fa81e7ff38f1f3a981f0bf9cc5edab707493effae03007aec5328d89a71dc9
    name: test-chart
    urls:
    - test-chart-0.1.0.tgz
    version: 0.1.0
generated: "2019-11-05T22:19:34.851122+05:30"
```

in my index, only one version of each chart is present. In your case, more versions will be present. So, just look for the chart name and particular version you are trying to install, and then see what urls are present in it, it has to be ideally `<chart-name>-<version>.tgz`. I'll leave it to you debug 😄

**Comment by eladitzhakian** [comment]
I'm also getting this when trying to install the elasticsearch chart from their repo.
```
$ helm repo add elastic https://helm.elastic.co
"elastic" has been added to your repositories
$ helm install elastic/elasticsearch elastic
Error: validation: chart.metadata is required
```

**Comment by karuppiah7890** [comment]
@eladitzhakian could you also provide which version of helm you are using? And the version of elasticsearch chart by doing a `helm search elasticsearch`? This will help us debug the problem further 😄

**Comment by rbutola** [comment]
I was getting the same error when trying to install from a tgz file. 
The issue as it turned out was -- helm was expecting the file name as "Chart.yaml" .
However the way archive file was packaged , chart was packaged as "dir/Chart.yaml".
This was causing the mismatch failure "Chart.yaml" != "dir/Chart.yaml"
leading to error Error: validation: chart.metadata is required

**Comment by topikachu** [comment]
Hi, I meet this problem of the stable/metrics-server

When I use a local repo cache it works.
helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm install metrics-server stable/metrics-server


However, when I try to use --repo I meet the problem
helm install metrics-server metrics-server  --repo https://kubernetes-charts.storage.googleapis.com
Error: validation: chart.metadata is required

**Comment by rbutola** [comment]
@topikachu  - Works fine for me
~/go/src/helm.sh/helm/bin$ ./helm install metrics-server metrics-server --repo https://kubernetes-charts.storage.googleapis.com
NAME: metrics-server

**Comment by kevinkjt2000** [comment]
I found that installing from rancher-stable produces this as well:
```
$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
$ helm install rancher rancher --set hostname=rancher.somewhere.com --atomic --repo https://releases.rancher.com/server-charts/stable --namespace cattle-system --version 2.3.3 --set tls=external
Error: validation: chart.metadata is required
```
Versions of helm and the rancher chart are included above.

However, when I install from a local repo all is fine:
```
$ helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
$ helm install rancher rancher-stable/rancher --set hostname=rancher.somewhere.com --atomic --namespace cattle-system --version 2.3.3 --set tls=external
NAME: rancher
LAST DEPLOYED: Fri Jan  3 23:21:43 2020
NAMESPACE: cattle-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Rancher Server has been installed.

NOTE: Rancher may take several minutes to fully initialize. Please standby while Certificates are being issued and Ingress comes up.

Check out our docs at https://rancher.com/docs/rancher/v2.x/en/

Browse to https://rancher.somewhere.com

Happy Containering!```

**Comment by kevinkjt2000** [comment]
I dug a little deeper this morning, and started with the repo's index.yaml:

```
apiVersion: v1
entries:
  rancher:
  - apiVersion: v1
    appVersion: v2.3.3
    created: "2019-11-27T19:28:17.774253615Z"
    description: Install Rancher Server to manage Kubernetes clusters across providers.
    digest: b5bcc4c59319f9a096f60f7e6a4637b34f81850c532feb113749c36d7d2fe7f4
    home: https://rancher.com
    icon: https://github.com/rancher/ui/blob/master/public/assets/images/logos/welcome-cow.svg
    keywords:
    - rancher
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: rancher
    sources:
    - https://github.com/rancher/rancher
    - https://github.com/rancher/server-chart
    urls:
    - rancher-2.3.3.tgz
    version: 2.3.3
  - apiVersion: v1
    appVersion: v2.3.2
    created: "2019-10-28T23:40:58.578877905Z"
```

I also searched for the string `chart.metadata` is required to find out if the validation is different between the two options.

https://github.com/helm/helm/blob/19e47ee3283ae98139d98460de796c1be1e3975f/pkg/chart/metadata.go#L68-L71

When the function on line 68 is invoked, `md` must be `nil` at that point to cause the line 70 error to be seen. So I hunted for any calls of this function and found:

https://github.com/helm/helm/blob/19e47ee3283ae98139d98460de796c1be1e3975f/pkg/chart/loader/load.go#L146-L148
https://github.com/helm/helm/blob/19e47ee3283ae98139d98460de796c1be1e3975f/pkg/chartutil/save.go#L89-L100

Since the error is not wrapped with "chart validation", I'm guessing the error I encountered yesterday bubbled up from `chart/loader/load.go`. At this point, it becomes hard for me to continue to trace where to go. As I am not familiar with Go, figuring out how the `--repo` switch makes it to the `LoadFiles` function is something that would take more time than I care to give. I did try to see if any of the install tests cover the `--repo` option, but I couldn't find any in https://github.com/helm/helm/blob/v3.0.2/cmd/helm/install_test.go

Hopefully someone more knowledgeable with this project and Go can figure out the issue here.
