### ISSUE TITLE
Deletion Policy before-hook-creation does not work as expected

### ISSUE THREAD

**Issue by mircohaug** [helm/helm#6879]
The deletion policy `before-hook-creation` does not work when the pod in question is in some "running" state. For example plain `Running` but also `ContainerCannotRun` when the cluster blocks the execution for some reason like enforced nonRoot.

Whenever another `helm test RELEASE` is issued, the command fails with the message `Error: warning: Hook test [...]/test-abborted-hook.yaml failed: object is being deleted: pods "rel-test-abort" already exists

Steps to reproduce:
1. add this test to any chart and install the chart.
```
apiVersion: v1
kind: Pod
metadata:
  name: "rel-test-abort"
  annotations:
    "helm.sh/hook": test-success
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  containers:
    - name: test
      image: "alpine"
      command: ['sh']
      args:
        - -c
        - "sleep 60s"
  restartPolicy: Never
```

2. run `helm test [RELNAME]` and hit `CTRL`+`C` before the test succeeded

3. run `helm test [RELNAME]` again and observe that it fails with "resource already exists"

Expected behaviour: Helm deletes the present resource before creating the new one as it is defined in the docs for the deletion policy `before-hook-creation`

Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0-rc.2", GitCommit:"82ea5aa774661cc6557cb57293571d06f94aff0c", GitTreeState:"clean", GoVersion:"go1.13.3"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
on prem

**Comment by bacongobbler** [comment]
cc @jlegrone

**Comment by jlegrone** [comment]
Turns out the new Github notifications features work quite nicely. 😄 I've added this to my backlog to investigate.

**Comment by asitaru** [comment]
We are also affected by the bug behind this. We have a pre-install hook for a PVC that has delete-policy before-hook-creation.

The release fails when running `helm delete` and `helm install` in quick succession as there are pods in terminating state that are still using the PVC. 

I should mention that we are seeing the same error:
`Error: failed pre-install: warning: Hook pre-install chart/templates/foo-pvc.yml failed: object is being deleted: persistentvolumeclaims "foo" already exists`

**Comment by viorelflorian** [comment]
Any update on this topic?

**Comment by viorelflorian** [comment]
Any update on this topic?

**Comment by nicksc423** [comment]
Still an issue, running into this as well...

**Comment by Laurianti** [comment]
Any update?

**Comment by zak905** [comment]
I am walking into the same issue, anything new?

**Comment by mjaglan** [comment]
Regarding hook-delete-policy:

If the test hook pod is failing, `before-hook-creation` policy should be able to delete that test hook on the next `helm test` run is my understanding by looking at the documentation: https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies

Annotation Value | Description
-- | --
before-hook-creation | Delete the previous resource before a new hook is launched (default)

The behavior does not work as described in the documentation. I received the following error:
```
Error: warning: Hook test <test YAML file> failed: object is being deleted: pods "<test pod>" already exists

STATUS: deployed
Phase: Failed
```

Using Helm Version
```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

Using kubectl version
```
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:13:28Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Filter94** [comment]
Same here. Bump

**Comment by Laurianti** [comment]
News?

**Comment by polikeiji** [comment]
Same here.

**Comment by sbuckpesch** [comment]
same same. :-(

**Comment by barrynorman** [comment]
Same here as well.

**Comment by shydefoo** [comment]
Same here as well

**Comment by zak905** [comment]
Hello everyone, I did some investigations and I was able to reproduce using a finalizer. Here are the manifests of the chart I used to test:
deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-hooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: testing-hooks
  template:
    metadata:
      labels:
        app.kubernetes.io/name: testing-hooks
    spec:
      containers:
        - name: testing-hooks
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
```

the pod container post install hook:

```
apiVersion: v1
kind: Pod
metadata:
  name: random-pod
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": before-hook-creation
  finalizers:
    - kubernetes
spec:
  containers:
    - name: test
      image: "alpine"
      command: ['echo']
      args:
        - "bye bye"
  restartPolicy: Never
```

It can be reproduced by installing the chart, deleting it, and then installing it again. Because of the finalizer, the pod created by the post install hook will remain at the `Terminating` state, until the finalizer is removed (e.g using kubectl edit)

I submitted a patch #11387 that adds waiting for post install hooks resources to be deleted before the new ones from the current release can be applied.
