### ISSUE TITLE
Using Openshift Imagestream with helm 3 results in unnecessary redeployments 

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#6980]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-10-17T19:23:55Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Openshift on AWS

On Openshift we are using Kubernetes Deployment and StatefulSets in combination with Openshift ImageStreams. It's possible to define the trigger as annotation of the Deployment Object:
https://docs.openshift.com/container-platform/3.11/dev_guide/managing_images.html#image-stream-kubernetes-resources

> In the following example the trigger fires when the example:latest imagestream tag is updated. Upon firing, the object’s pod template image reference for the web container is updated with a new image value

In our charts, we are defining a dummy value since the image field value of the pod spec is controlled by openshift like:

```
---
# Source: timp/templates/qs/qs-dpl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: |
      [{
        "from": {
          "kind": "ImageStreamTag",
          "name": "jkr-timp-qs:latest"
        },
        "fieldPath": "spec.template.spec.containers[?(@.name==\"qs\")].image"
      }]
  name: jkr-timp-qs
  labels:
    app: "jkr-timp"
spec:
  replicas: 1
  selector:
    matchLabels:
      release: jkr-timp
      app: "jkr-timp"
      app.kubernetes.io/component: qs
  template:
    metadata:
      annotations:
        checksum/secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      labels:
        release: jkr-timp
        app: "jkr-timp"
        app.kubernetes.io/component: qs
    spec:
      containers:
      - name: qs
        image: " "
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: TZ
          value: "Europe/Berlin"
        resources:
          limits:
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 120
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
        volumeMounts:
          - mountPath: /etc/nginx/default.d/qs.conf
            subPath: qs.conf
            name: qs-config
          - mountPath: /usr/share/nginx/html/
            name: data
      securityContext:
        {}
      volumes:
        - name: qs-config
          configMap:
            name: "jkr-timp-qs"
        - name: data
          persistentVolumeClaim:
            claimName: "data-jkr-timp-qs"
```

After applying the manifest, the image field value is changed to `nginx:lastest` by openshift.

On the next helm upgrade, helm replaces the image field value back to `" "`. We identify this it with `helm upgrade -v10`:

```
I1115 16:45:06.834193   49498 request.go:968] Request Body: {"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"qs"}],"containers":[{"image":" ","name":"qs"}]}}}}
I1115 16:45:06.834224   49498 round_trippers.go:423] curl -k -v -XPATCH  -H "Accept: application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "Authorization: Bearer XXX" 'https://openshift.local:443/apis/apps/v1/namespaces/experimental/deployments/jkr-timp-qs'
```

The result forces a redeployment since the openshift trigger will reapply the image field to nginx.

This behaviour is new in helm 3.

Is this an expected behaviour? It will break all setups like this. Using Openshift Imagestreams with Deployments is a common use case inside Openshift.

Demo Chart which covers this issue perfectly: https://github.com/jkroepke/helm3-imagetrigger-test/tree/master
