### ISSUE TITLE
helm 3 doesn't install dependencies from remote repository

### ISSUE THREAD

**Issue by rodosskiand** [helm/helm#7018]
if i install release from local storage its ok, but when i upload chart to gcs, dependencies not installed.

i not see fails, just is installed only parent chart, as if i set dependency to `false` in values.yaml

Chart.yaml:

```
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: mychart
version: 0.1.0

dependencies:
  - name: redis
    version: 0.3
    repository: "https://myrepo.storage.googleapis.com"
    condition: redis.enabled
  - name: mysql
    version: 0.12.0
    repository: "@stable"
    condition: mysql.enabled
```
Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.23", GitCommit:"81c87c699557fed991e292cd328b2129c2f242a2", GitTreeState:"clean", BuildDate:"2019-11-07T19:23:23Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE
