### ISSUE TITLE
generating yaml files for multiple namespaces from template

### ISSUE THREAD

**Issue by adurai81** [helm/helm#7056]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: v1.15.3
Server Version: v1.13.5-6+d6ea2e3ed7815b
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  OKE

I would like to generate this file for multiple namespaces provided by 

```
{{- if .Values.config.authn_policy.enabled -}}
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: default
  namespace: {{ .Values.namespace }}
spec:
  origins:
    - jwt:
        issuer: "https://identity.oraclecloud.com/"
  principalBinding: USE_ORIGIN
  {{- end -}}
```

For example if the namespace was 'test1` the generated file would look like this -

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: default
  namespace: test1
spec:
  origins:
    - jwt:
        issuer: "https://identity.oraclecloud.com/"
  principalBinding: USE_ORIGIN
```
