### ISSUE TITLE
Subchart handling of aliases not working

### ISSUE THREAD

**Issue by rhmms** [helm/helm#7061]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

I Have a rather large system consisting of subsystems, that are composed of multiple similar units.

You can think of it like this:

- system - one installation if the application
  - subsystem_mgmt - management subsystem consisting of many spring applications and some databases
    - componentA - actual Spring boot application
    - componentB - actual Spring boot application
    - componentC - mysql community chart
  - subsystem_delivery1 - delivery subsystem consisting of many spring applications and some databases and some pod autoscaler
    - component1 - actual Spring boot application
    - component2 - actual Spring boot application
    - component3 - actual Spring boot application
    - componentZ - mysql community chart
  - subsystem_delivery2 - same as above
    - component1 - actual Spring boot application
    - component2 - actual Spring boot application
    - component3 - actual Spring boot application
    - componentZ - mysql community chart
  - subsystem_deliveryN - same as above
    - component1 - actual Spring boot application
    - component2 - actual Spring boot application
    - component3 - actual Spring boot application
    - componentZ - mysql community chart

Now I tried to put this into a helm chart following a common naming schema and reusing community charts also with as little DRY as possible. For this I created a PoC

Directory Layout

```
$ tree
├───library-charts
│   ├───component
│   │   ├───charts
│   │   └───templates
│   └───subsystem
│       ├───charts
│       └───templates
├───system
     ├───charts
     └───templates
```
Chart **system**

```
# Chart.yaml
dependencies:
  # Subsystem1
  - name: subsystem
    version: 0.1.0
    repository: file://../library-charts/subsystem
    alias: subsystem1
  # Subsystem2
  - name: subsystem
    version: 0.1.0
    repository: file://../library-charts/subsystem
    alias: subsystem2
```

```
# values.yaml
subsystem1:
  nameOverride: "delivery1"
  component1:
    nameOverride: "delivery1-webserver1"
  component2:
    nameOverride: "delivery1-webserver2"

subsystem2:
  nameOverride: "delivery2"
  component1:
    nameOverride: "delivery2-webserver1"
  component2:
    nameOverride: "delivery2-webserver2"
```

Chart **library-charts/subsystem**

```
# Chart.yaml
dependencies:
  # Component1
  - name: component
    version: 0.1.0
    repository: file://../component
    alias: component1
  # Component2
  - name: component
    version: 0.1.0
    repository: file://../component
    alias: component2
```

Chart **library-charts/component**

- No dependencies
- Just an Ingress Resource

Now I run the build system (It seems that he build is required, as helm dos not handle transitive dependencies)

```
# Update Subsystem and Community Charts 
for i in library-charts/*; do helm dependency update $i; done
Saving 2 charts
Deleting outdated charts

# Update System Chart 
helm dependency update system
Saving 2 charts
Deleting outdated charts
```

If I now render the templates, the variables are not passed correctly

```
helm template xxx system  | grep -e "^kind:" -e "^  name:"

kind: Service
  name: xxx-system
kind: Deployment
  name: xxx-delivery1
kind: Deployment
  name: xxx-delivery2
kind: Ingress
  name: xxx-delivery1-webserver1
kind: Ingress
  name: xxx-delivery1-webserver2
kind: Ingress
  name: xxx-component
```

The expected result would be 

```
kind: Service
  name: xxx-system
kind: Deployment
  name: xxx-delivery1
kind: Deployment
  name: xxx-delivery2
kind: Ingress
  name: xxx-delivery1-webserver1
kind: Ingress
  name: xxx-delivery1-webserver2
kind: Ingress
  name: xxx-delivery2-webserver1
kind: Ingress
  name: xxx-delivery2-webserver2
```

So is this 

a) a Bug ? 
b) unintended Use of subcharts ?
c) unspecified behaviour ? 

Please advice.

**Comment by tomislater** [comment]
Is it not connected to https://github.com/helm/helm/issues/7093?

**Comment by rhmms** [comment]
Actually the Basic Concept works if I just use one layer of abstraction. 

- Umbrella
  |- Subchart1
  |- Subchart2

In this case I can use the alias Name to overwrite values, not the Chart Name.

**Comment by gajus** [comment]
Not stale.

**Comment by tylerhoadley** [comment]
I had a similar issue with `alias:` and my sub chart overlays. I do not set name overrides, however we use aliases to override the names as devs may deploy multi versions of a similar app under one master subchart.

The issue I found is that when I call these charts with alias nested under the name, the chart would error with Kind issues

```
# Chart.yaml
dependencies:
  # Component1
  - name: component
    version: 0.1.0
    repository: file://../component
    alias: component1
```

However, if I flip the name and alias directives in the dep list, like so, it works as expected.

```
# Chart.yaml
dependencies:
  # Component1
  - alias: component1
    name: component
    version: 0.1.0
    repository: file://../component
```

Not sure if this would address your issues above, but might shock you like it did with me.
