### ISSUE TITLE
Hook scripts in helm

### ISSUE THREAD

**Issue by guru1306** [helm/helm#7069]
Hi All

I am trying to use hooks in helm. Can I package some scripts inside helm charts and execute them as part of pre-install hook? For example, I want to do some schema upgrade before bringing the pods. Is this possible? 

Thanks
Guru

**Comment by mattfarina** [comment]
You can package scripts that make changes. You can read about using hooks at https://helm.sh/docs/topics/charts_hooks/#the-available-hooks.

I would test to make sure that what you want is possible with your application. Schema changes can be a problem to manage as part of an upgrade process. Especially if you want to do things in an HA manner.

**Comment by guru1306** [comment]
Thanks Matt.

Here is my directory structure.

```
simple-chart/
├── Chart.yaml
├── scripts
│   ├── second.sh
│   └── test.sh
└── templates
    ├── deployment.yaml
    ├── hpa.yaml
    ├── preinstall.yaml
    └── service.yaml
```


Here is the content of the preinstall.yaml file

```
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  ttlSecondsAfterFinished: 500
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: "alpine:3.3"
        **command: ["/bin/sh", "-c", {{.Files.Get "scripts/test.sh" }} ]**
```

This job runs successfully as a pod. In some examples the "Files.Get" is not there in the command. In my environment it works only if I add the "Files.Get". Is this normal or am I doing something wrong? Is there a way to run this scripts outside the context of pod?
