### ISSUE TITLE
Removing dynamically created pods on chart remove

### ISSUE THREAD

**Issue by djklim87** [helm/helm#7092]
Help request

Our chart can dynamically create pods via k8s API calls. Which we must add to metadata for removing these pods when we remove all chart?
I tried to add the same metadata as (they are) in pods, which were created by Helm chart. But it didn't work /help

```
metadata:
  labels:
    app.kubernetes.io/app: ...
    app.kubernetes.io/instance: ...
    app.kubernetes.io/managed-by: ...
    helm.sh/chart: ...
    name: ...
``` 

Does Helm 3 can handle that case?

Output of `helm version`:
v3
