### ISSUE TITLE
file not overriding child default values when alias

### ISSUE THREAD

**Issue by marcadella** [helm/helm#7093]
I have a chart with a sub-chart `mk-backend` (aliased as `backend`).
```
dependencies:
  - name: "mk-backend"
    repository: "@stable"
    version: "x.y.z"
    alias: backend
```

Since I upgraded from Helm v2.x to v3.0.0, the overrides for `backend` (defined in a file (`-f`) or with `--set`) are ignored: it is the default values that are used.
It seems to happen only when alias are used.

Output of `helm version`:
`version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube v1.5.2

**Comment by bacongobbler** [comment]
Can you provide an example to reproduce this issue on our end? nginx-ingress is a good example to demonstrate this issue. Thanks!

**Comment by marcadella** [comment]
This is not a question, this is a bug report. [Here](https://github.com/helm/helm/files/3901950/helmTest.tar.gz) is an archive containing a minimal chart reproducing this error.
It defines a `main` chart and it's two sub-charts `child` and `child2`. Both sub-charts are identical. The difference is that `child2` is aliased as `childalias`.
Unpack the archive, then in `build.sh`, set a repo name, url, user and password (for instance chartmuseum). In addition you might want to install `helm-push` plugin: `helm plugin install https://github.com/chartmuseum/helm-push`.
Have a k8s cluster running (for instance minikube).
Finally run `./build.sh`.
This is the printout you'll get:
```
---
# Source: main/charts/child/templates/child-conf.tpl
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-child
data:
    param3: runtime
    param4: default
---
# Source: main/charts/childalias/templates/child-conf.tpl
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-childalias
data:
    param3: runtime
    param4: default
---
# Source: main/templates/main-conf.tpl
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-main
data:
    param1: runtime
    param2: default
```
then later:
```
apiVersion: v1
items:
- apiVersion: v1
  data:
    param3: runtime
    param4: default
  kind: ConfigMap
  metadata:
    creationTimestamp: "2019-11-28T13:36:46Z"
    name: test-child
    namespace: test
    resourceVersion: "117013"
    selfLink: /api/v1/namespaces/test/configmaps/test-child
    uid: 6ba49810-98d2-44a1-9189-f277a542155c
- apiVersion: v1
  data:
    param3: default
    param4: default
  kind: ConfigMap
  metadata:
    creationTimestamp: "2019-11-28T13:36:46Z"
    name: test-child2
    namespace: test
    resourceVersion: "117015"
    selfLink: /api/v1/namespaces/test/configmaps/test-child2
    uid: 5ccae5a1-1a25-4406-bbf3-b9e75bc43de7
- apiVersion: v1
  data:
    param1: runtime
    param2: default
  kind: ConfigMap
  metadata:
    creationTimestamp: "2019-11-28T13:36:46Z"
    name: test-main
    namespace: test
    resourceVersion: "117014"
    selfLink: /api/v1/namespaces/test/configmaps/test-main
    uid: b4b581fe-591a-40f2-81fc-6fa9e8d5e030
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

The first printout is the result of `helm template`. It shows three config maps (one from the chart `main`, one from chart `child` and one from chart `child2` aliased `childalias`). For both `child` and `child2` the cm value is:
```
data:
    param3: runtime
    param4: default
```

This is because we run `helm template` with `--set childalias.param3=runtime,child.param3=runtime`, so `param3` takes the value `runtime`. **Note that there is a first issue here** since `param4` should take the value `override` since it is overridden in `main/values.yaml`.

Now let's move to the second printout section which corresponds to `helm install` (still with `--set childalias.param3=runtime,child.param3=runtime`), then `kubectl get cm -o yaml -n test`. Here we see that for `childalias`, the value of `param3` is `default` (which is **wrong**) while it is `runtime` for `child` (which is right). In addition, both values for `param4` **are wrong** since it was expected `override`.
