### ISSUE TITLE
template: ../secrets.yaml executing ..secrets.yaml" at <b64enc>: invalid value; expected string

### ISSUE THREAD

**Issue by githubvick** [helm/helm#7095]
`helm version`:
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): VMWare Virtual machine 

I'm trying to implement a simple secret in Helm chart and its been elusive so far. 
Steps done:

1) Installed gpg and configured with default values
2) Created helm_vars folder inside the base folder where templates and Chart.yaml file reside
3) create .sops.yaml file inside helm_vars with creation_rules
4) create secrets.yaml file with mysecret:mypassword in it
5) run "helm secrets enc secrets.yaml" and see that it encrypts properly
6) create secrets.yaml file inside of templates folder

```
apiVersion: v1
kind: Secret
metadata:
  annotations:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: mytestpwd
type: Opaque
data:
  mysecret: {{ .Values.mysecret | b64enc  | quote }}

```
7. Inside of deplyoment.yaml in templates folder, added this piece of code
```
        env:
           - name: SOMEPASSWORD
             valueFrom:
               secretKeyRef:
               name: mytestpwd
               key: mysecret
  
```

When I do a dry run or run helm template, get this error

Error: render error in "testsec/templates/secrets.yaml": template: testsec/templates/secrets.yaml:12:34: executing "testsec/templates/secrets.yaml" at <b64enc>: invalid value; expected string

When I pass the value explicitly "helm template testsec --set-string mysecret="thepassword"", then it works fine which confirms that it is not able to retrieve .Values.mysecret . When | b64enc is removed, it runs fine but doesnt have any value inside.

Ideally I think .Values.mysecret inside of templates folder should reference the mysecret value inside of helm_vars folder correct? Seems like it isn't. I see that this happens with helm version 3.0.0 and also 2.15.1 which says that I'm performing some steps wrong. Any help is appreciated.

**Comment by zwwhdls** [comment]
Maybe you can try it with deleting `` in secret.yaml

**Comment by githubvick** [comment]
Sorry, that was a typo added as part of inserting code

**Comment by zwwhdls** [comment]
When you write `mysecret: {{ .Values.mysecret | b64enc  | quote }}` in templates/secret.yaml, it means helm use `mysecret` in values.yaml to render it. But you didn't write `mysecret` in values.yaml, so ` .Values.mysecret ` got nothing. Then b64env got nothing without string, the error raised.

You have to define `mysecret` field in values.yaml.

**Comment by githubvick** [comment]
Got it, but what would be the value to define inside of values.yaml file? Should it be in plain text?

mysecret:mypassword

**Comment by githubvick** [comment]
I was able to finally get it working by defining as above in the values.yaml file, but doesn't it defeat the purpose of all the encryption. sops.yaml file and encryption happened to prevent storing the password in plain text isnt it?

**Comment by zwwhdls** [comment]
@githubvick Hi, I think you can use the encrypted password as secret value in values.yaml. 😁

**Comment by githubvick** [comment]
@zwwhdls Thanks for your inputs. 

The secrets.yaml inside helm_vars has the below value

mysecret: ENC[AES256_GCM,data:W/s38F5gQ/M=,iv:Ekpf6AX/hyHFGjUvaTPH6HncMNRYFgB3C5cJquZ8HPU=,tag:iCq1Pkf0axazh9mGyBcUPA==,type:str]

I think W/s38F5gQ/M= is the encrypted data. Tried using 

mysecret:W/s38F5gQ/M=

inside of values.yaml. The resulting container only has the env value of W/s38F5gQ/M= instead of mypassword.

Guess it is just templating whatever is inside of the values.yaml, it doesnt bother about all the encryption done.

**Comment by zwwhdls** [comment]
@githubvick , I believe you can try this:

templates/secret.yaml:
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: mytestpwd
type: Opaque
data:
  mysecret: {{ .Values.mysecret | quote }}
```

values.yaml:
```
mysecret: bXlzZWNyZXQK
```
where "bXlzZWNyZXQK" is base64 encode of "mysecret".

deployment.yaml:
```
        env:
           - name: SOMEPASSWORD
             valueFrom:
               secretKeyRef:
               name: mytestpwd
               key: mysecret
```

**Comment by githubvick** [comment]
I believe you asked me to use the base64 value of the actual password value. bXlzZWNyZXQK decodes to "mysecret" instead of mypassword.

Nevertheless, I tried both ways, to use the base64 encoded value of mysecret in values.yaml file and mypassword. Both times its just the encoded value that is set as env variable inside the container.

```
[root@mcjca080171 test-helm]# kubectl exec -it mysql-testsec-6bc657db8d-qbgsx -- /bin/sh
# env
KUBERNETES_PORT=tcp://10.233.0.1:443
MYSQL_TESTSEC_SERVICE_PORT=80
KUBERNETES_SERVICE_PORT=443
MYSQL_TESTSEC_PORT=tcp://10.233.61.7:80
HOSTNAME=mysql-testsec-6bc657db8d-qbgsx
HOME=/root
mysecret=bXlzZWNyZXQK
```

**Comment by zwwhdls** [comment]
@githubvick  Hi, I just tried the secret but it works well. Here are my files:

templates/pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: nginx
    env:
    - name: SOMEPASSWORD
      valueFrom:
        secretKeyRef:
          name: mytestpwd
          key: mysecret
```

templates/secret.yaml:
```
apiVersion: v1
kind: Secret
metadata:
  name: mytestpwd
type: Opaque
data:
  mysecret: {{ .Values.mysecret }}
```

values.yaml:
```
mysecret: bXlzZWNyZXQK
```

Then helm install the chart:
```
helm install test test
```

Get the env in pod test:
```
# kubectl exec -it test env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=test
TERM=xterm
SOMEPASSWORD=mysecret

DETAILS_PORT_9080_TCP_PORT=9080
RATINGS_PORT_9080_TCP_PORT=9080
...
```
