### ISSUE TITLE
non-deterministic ordering with {{range until N}} for generating multiple YAML docs

### ISSUE THREAD

**Issue by andpol** [helm/helm#7097]
The following pattern of using `range until N` to generate multiple Kubernetes objects in separate YAML docs has non deterministic ordering as of Helm 3.0.0:
```yaml
{{- range $i, $e := until 5 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myChart.fullname" $ }}-{{$i}}
  labels:
    {{- include "myChart.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "myChart.selectorLabels" $ | nindent 4 }}
{{- end }}
```

Steps to reproduce:
1. Create a basic helm chart with `helm create myChart`
1. Modify `myChart/templates/service.yaml` as above to include `range`
1. `docker pull alpine/helm:3.0.0`
1. Generate output with: `docker run --rm -v $PWD/myChart:/myChart -v $PWD/out:/out alpine/helm:3.0.0 template myName /myChart --output-dir /out`
1. Inspect and see unsorted output:
```
╰─➤  grep myname-myChart out/myChart/templates/service.yaml 
  name: myname-myChart-2
  name: myname-myChart-3
  name: myname-myChart-4
  name: myname-myChart-0
  name: myname-myChart-1
```

Note that this output _is_ ordered for Helm 2.16.1 and the following command: `docker run --rm -v $PWD/myChart:/myChart -v $PWD/out:/out alpine/helm:2.16.1 template -n myname /myChart --output-dir /out`

Although I suppose you could argue that since they're separate YAML docs, and therefore the order doesn't matter, this certainly makes our lives harder since our deployment process performs a diff on the output of `helm template` as part of a human validation step, before continuing with the deploy. This changing ordering shows up as a diff on every deploy.

---

Output of `helm version`:
Works for:
```
╰─➤  docker run --rm alpine/helm:2.16.1 version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused
```

Doesn't work for:
```
╰─➤  docker run --rm alpine/helm:3.0.0 version                                                                                           
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"
```

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A
