### ISSUE TITLE
Add method for replacing releases

### ISSUE THREAD

**Issue by remcohaszing** [helm/helm#7103]
### Problem

I use Helm to deploy review environments in GitLab CI for every merge request. Such a job looks like this:

```yaml
.helm:
  image:
    # This is the most official Helm image at the moment.
    # https://github.com/helm/helm/issues/5682#issuecomment-490084864
    name: lachlanevenson/k8s-helm:v3.0.0
    entrypoint: [/bin/sh, -c]

review:
  extends: .helm
  only:
    - merge_requests
  allow_failure: false
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    on_stop: stop review
  script:
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
    - helm dependency build charts/my-chart
    - helm install "$CI_ENVIRONMENT_SLUG" charts/my-chart --atomic # options…

stop review:
  extends: .helm
  when: manual
  only:
    - merge_requests
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  script:
    - helm delete "$CI_ENVIRONMENT_SLUG"
```

After this deployment, another job runs which provisions the deployed environment.

This works like a charm, except for one thing: If not everything works correctly (provisioning failed half way, new commits are pushed to the merge request branch, etc.), the review environment needs to be stopped manually, and then redeployed manually.

I used to think `helm install --replace` was supposed to solve this, but it was broken. However, it turns out this isn’t supposed to replace the current installation.

Another way to solve this is to delete the release before installing it, but this would fail if no installation exists yet. This can be solved by using `/bin/true` to continue the job anyway, but not every failure should be caught, only the attempt to delete a missing release.

```yaml
  script:
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
    - helm dependency build charts/my-chart
    - helm delete "$CI_ENVIRONMENT_SLUG" || true
    - helm install "$CI_ENVIRONMENT_SLUG" charts/my-chart --atomic # options…
```

I propose one of these 2 features to resolve the issue:

### Proposal 1: Purge existing conflicting releases

A flag for `helm install` would delete a conflicting release before attempting to install a new one.

```sh
helm install "$CI_ENVIRONMENT_SLUG" charts/my-chart --delete-conflict
```

### Proposal 2: Ignore missing releases when deleting

A flag for `helm delete` would exit with exit code 0 if the release it tries to delete, doesn’t exist.

```sh
helm delete "$CI_ENVIRONMENT_SLUG" --ignore-missing
```
