### ISSUE TITLE
White space trimming issue with array and map

### ISSUE THREAD

**Issue by parjun8840** [helm/helm#7123]
White space trimming is not behaving similarly for array and map in helm template rendering. 

Output of `helm version`: `version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Output of `kubectl version`: NA, as it seems related to the template

There are 2 input files
1. **values.yaml**
```
app02:
  servers:
    "node01":
      enabled: false
      env:
        DB_HOST: database01
        DB_USER: dbuser
    "node02":
      enabled: true
      env:
        DB_HOST: database02
        DB_USER: dbuser
```
2. mod_values.yaml
```
node:
  - node1
  - node2
  - node3 
```
1. **Array:** 
Template1:
```
lenghtArray : {{ .Values.node | len }}
{{- range $item := .Values.node }}
  {{- $item }}
{{- end }}
```

Output is: 
`lenghtArray : 3node1node2node3`

The **expected** result could be:
```
lenghtArray : 3
  node1
  node2
  node3
```

2. **Map:**
Template2:
```
{{- range $controller_id, $config  := .Values.app02.servers }}
controller: {{ $controller_id }}
config: {{- $config.enabled }}
env: {{ $config.env }}
{{- end }}

```
`Error: YAML parse error on dummy/templates/job.yaml: error converting YAML to JSON: yaml: line 10: could not find expected ':'`
It is throwing an error at - config: {{- $config.enabled }}
The **expected** result could be:
Element whitspace trimmed and print

**Command used:**
`helm template --name-template="dummy-temp" -f dummy/values.yaml -f dummy/mod_values.yaml dummy --namespace="mynamespace"`
