### ISSUE TITLE
[Helm 3] improper RBAC setup causes release to be stuck in `pending-install` status despite installing fine

### ISSUE THREAD

**Issue by johnmcollier** [helm/helm#7139]
I tried deploying a simple Go application with a Helm chart using Helm 3, running on Kubernetes. You can find the helm chart [here](https://github.com/johnmcollier/gotemplate). The application installs fine, without error and even reports a status of `deployed`.
```
sh-4.2# helm install gotemplate .
NAME: gotemplate
LAST DEPLOYED: Tue Dec  3 21:36:02 2019
NAMESPACE: che
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

However, it does not show up in the list of releases when I run `helm list`. If I run `helm list --all` it shows up with a status of `pending-install`, despite the install completing fine.
```
sh-4.2# helm list
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
sh-4.2# helm list --all
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
gotemplate      che             1               2019-12-03 21:36:02.653465978 +0000 UTC pending-install gotemplate-0.1.0        1.0     
```

The same Helm chart deploys fine on Helm 2.x.

Output of `helm version`:
```
sh-4.2# helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:
```
sh-4.2# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+2e5ed54", GitCommit:"2e5ed54", GitTreeState:"clean", BuildDate:"2019-10-10T22:04:13Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OpenShift

**Comment by johnmcollier** [comment]
The debug logs also didn't indicate anything wrong:
```
sh-4.2# helm install gotemplate . --debug
install.go:148: [debug] Original chart version: ""
install.go:165: [debug] CHART PATH: /tmp/gogotet/gotemplate

client.go:87: [debug] creating 2 resource(s)
NAME: gotemplate
LAST DEPLOYED: Tue Dec  3 21:50:54 2019
NAMESPACE: che
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
image:
  pullPolicy: Always
  repository: sample
  tag: v0.1.0
replicaCount: 1
resources:
  cpu: 100m
  memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  name: Node
  servicePort: 8000
  type: NodePort

HOOKS:
MANIFEST:
---
# Source: gotemplate/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cw-gogotet-dccf38f0-160f-11ea-ab26
  labels:
    chart: gotemplate-0.1.0
    projectID: dccf38f0-160f-11ea-ab26-791dd12c33b3
    release: cw-gogotet-dccf38f0-160f-11ea-ab26
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: codewind-workspace798zbeq2cf3esdnq-6f76c8dbbc
    uid: dce9dd7b-160d-11ea-92b4-00000a1012bc
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
  selector:
    app: gotemplate-selector
    release: cw-gogotet-dccf38f0-160f-11ea-ab26
---
# Source: gotemplate/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cw-gogotet-dccf38f0-160f-11ea-ab26
  labels:
    chart: gotemplate-0.1.0
    release: cw-gogotet-dccf38f0-160f-11ea-ab26
    projectID: dccf38f0-160f-11ea-ab26-791dd12c33b3
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: codewind-workspace798zbeq2cf3esdnq-6f76c8dbbc
    uid: dce9dd7b-160d-11ea-92b4-00000a1012bc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gotemplate-selector
        version: current
        release: cw-gogotet-dccf38f0-160f-11ea-ab26
        projectID: dccf38f0-160f-11ea-ab26-791dd12c33b3
    spec:
      containers:
      - name: gotemplate
        image: docker.io/johncollier/cw-gogotet-dccf38f0-160f-11ea-ab26:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        resources: null
        env:
        - name: PORT
          value: "8000"
      serviceAccountName: che-workspace

```
