### ISSUE TITLE
cannot install service account token due to install order

### ISSUE THREAD

**Issue by dastrobu** [helm/helm#7159]
Given a chart containing the following template 
```yaml
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: tmp
secrets:
- name: tmp
---
apiVersion: v1
kind: Secret
metadata:
  name: tmp
  annotations:
    kubernetes.io/service-account.name: tmp-token
type: kubernetes.io/service-account-token
```
Helm will install the service account token (Secret) first and Kubernetes will instantly delete this secret, since no service account is available for this secret (see [Token Controller](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#token-controller)). 
Then Helm installs the service account, but the token is gone. 
When doing an upgrade of the Helm release after the initial install the token is generated as expected. 

The reason for this behavior is the current [KindSortOrder](https://github.com/helm/helm/blob/9b42702a4bced339ff424a78ad68dd6be6e1a80a/pkg/releaseutil/kind_sorter.go#L27) where secrets come before service accounts. 
Currently I cannot see why one would ever need a secret before a service account, but there are good reasons for the other way around. 
I propose to change the order and install service accounts before secrets. 

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:51:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-16T01:01:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kind
