### ISSUE TITLE
Secret is not correctly set

### ISSUE THREAD

**Issue by Tchoupinax** [helm/helm#7172]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-29T18:43:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

Hello :) !

i met a strange issue when trying to use a docker-registry with helm.

My command is the following:
```
helm install \
  --name docker \
  --set secrets.htpasswd="toto:$2y$05$Zmlu4xQrDEicRlcsp/YuFeYAbYeF4QXmcr27uZYwgrHg/fvN.weBC" \
  stable/docker-registry
```

Then, i tried to login to this registry but it always answered a 401. I decided to explore why, because i'm sure that i did all things as the good way.

It appears that this [comment](https://github.com/helm/charts/issues/3298#issuecomment-387427991) advises to edit the secret. So i was going to show it and i discovered that when i decode this string (reverse base64) it do not match my original htpasswd.

My original string : 
```toto:$2y$05$Zmlu4xQrDEicRlcsp/YuFeYAbYeF4QXmcr27uZYwgrHg/fvN.weBC```
My decoded secret
```toto:y/bin/bash5/YuFeYAbYeF4QXmcr27uZYwgrHg/fvN.weBC```

It appears the end is the same but what is this `/bin/bash` ?? It is awesome.

I tried to understand the helm templates but i do not know if the problem comes from helm binary, templates or kubernetes.

The bonus is, when i added my secret to values.yaml and launched helm from my disk (i download this repository), it works !! So the issue comes from when or after setting the secret or the htpasswd.

(from values.yaml)
```
# Set this to name of secret for tls certs
# tlsSecretName: registry.docker.example.com
secrets:
  haSharedSecret: ""
  htpasswd: "toto:$2y$05$Zmlu4xQrDEicRlcsp/YuFeYAbYeF4QXmcr27uZYwgrHg/fvN.weBC"
```

**Comment by bacongobbler** [comment]
Looking at the chart itself, it appears that the value is passed as-is to the resource. 

https://github.com/helm/charts/blob/7f2ce76723049b2b1ce6c5011b83264b761a653a/stable/docker-registry/templates/secret.yaml#L12-L14

Transferring to helm/charts as a support question about a particular chart. This doesn't appear to be an issue from Helm's end, as the following example works for me:

```
PS C:\Users\me\code\wasm-experiments\wasm-web-framework> helm template stable/docker-registry --set secrets.htpasswd="foo" --generate-name                                  
---
# Source: docker-registry/templates/secret.yaml   
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-docker-registry-secret       
  labels:
    app: docker-registry
    chart: docker-registry-1.8.3
    heritage: Helm
    release: RELEASE-NAME
type: Opaque
data:
  htpasswd: Zm9v
  haSharedSecret: "YWx3NFZpU3Rad2QxbVp4VA=="
```

base64-decoding `Zm9v` reveals `foo` as expected.
