### ISSUE TITLE
Proposal: Add annotations to all chart manifests

### ISSUE THREAD

**Issue by gadelkareem** [helm/helm#7193]
I need to be able to add metadata labels and annotations to all the k8s objects that will be installed with helm from the chart. 
for ex:
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/env: prod
```

Is that possible without modifying the chart?
