### ISSUE TITLE
[Question] How to render dynamic key in template with --set option

### ISSUE THREAD

**Issue by hanks** [helm/helm#7194]
Here is my secret template yaml:

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
{{- printf "\n" }}
{{- range .Values.secret }}
{{- printf "  %s: {{ .Values.HELM_SECRET_%s }}\n" . . }}
{{- end }}
```

and values.yaml

```
secret:
  - password
  - token
```

when I run command:

```
helm install --dry-run --debug --set HELM_SECRET_password=foo --set HELM_SECRET_token=bar ./secret-demo
```

The output is:

```
apiVersion: v1
kind: Secret
metadata:
  name: named-turtle-secret
data:
  password: {{ .Values.HELM_SECRET_password }}
  token: {{ .Values.HELM_SECRET_token }}
```

But I want it to be: 

```
apiVersion: v1
kind: Secret
metadata:
  name: named-turtle-secret
data:
  password: foo
  token: bar
```

It looks like need to render `{{ .Values.HELM_SECRET_password }}` twice to get the final value. Is it possible to do things like this? Thank you for you time.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
