### ISSUE TITLE
b64enc returns nil on empty string

### ISSUE THREAD

**Issue by mvandervliet** [helm/helm#7205]
Output of `helm version`:

```text
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:

```text
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

OKE, Docker Desktop 

## Description

When specifying data with default to an empty string in `kind: Secret` templates, an error is thrown:

As an example: `my-secret.yaml` secret template

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-my-secret
type: Opaque
data:
  myKey: {{ .Values.myKey | default "" | b64enc }}
```

> Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in Secret.data.myKey]

**Comment by mvandervliet** [comment]
This forces a workaround like the following:

```yaml
# ...
type: Opaque
data:
  {{ if .Values.myKey }}myKey: {{ .Values.myKey | b64enc }}{{ end }}
```
