### ISSUE TITLE
Dependency build without added repos

### ISSUE THREAD

**Issue by remcohaszing** [helm/helm#7214]
When running `helm dependency build` or `helm install --dep-up`, I need to add a repository using `helm repo add <repo_name> <url>`. As far as I can think of, this makes sense for 2 situations:

- Commands that depend on `<name>` (I.e. `helm install <release_name> <repo_name>/<chart_name>`
- Chart repositories that require specific security requirements.

However, this seems like an unnecessary step when using `helm dependency build` or `helm install --dep-up`. For example, I have a chart with the following `requirements.yaml`:

```yaml
dependencies:
  - name: postgresql
    version: 6.5.9
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgresql.enabled
```

All information to download the chart is there. Still I need to run `helm repo add thiscouldbeanythingreally https://kubernetes-charts.storage.googleapis.com` first. On a development machine it’s no problem to add these repositories once, but it’s annoying having to run this step in CI every time.

I suggest to just use default repository settings the repository url isn’t registered. Worst case scenario Helm fails to download the dependency, which is the same as having wrong credentials defined.

Output of `helm version`: 

```go
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
