### ISSUE TITLE
Helm3 post-upgrade hooks not firing on subsequent upgrades

### ISSUE THREAD

**Issue by guice** [helm/helm#7228]
It does not appear hooks in Helm3 are working.

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
````

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS

----

Trying to run post-upgrade hooks. First upgrade of a newly created Job succeeds, all subsequent upgrades do _not_ re-run the job. The job is never removed before rerunning (i.e. "If no hook deletion policy annotation is specified, the `before-hook-creation` behavior applies by default.")

I have a Job defined as a post-upgrade and post-install hook
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-stop-all-queues-listener
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.service.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
          {{- include "app.consumer.labels" . | nindent 8 }}
      annotations:
        "helm.sh/hook": pre-upgrade,pre-install
[... spec definition ...]
``` 

If the job doesn't exist, it will create it - but helm does _not_ wait before it's completed for other pods to start up.

If the job exists, upgrades not rerun this job. The job definition remains within kuberentes, resulting in issues if I make modifications to the annotations.

I've tried playing around with the 
```
        "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
``` 
definition, but no luck. Nothing works. The Job remains and never reran.

In all intents and purposes, it appears as if the hooks don't work at all.
