### ISSUE TITLE
 Error retrieving endpoints for the service xyz: No endpoints for target port 80 in service xyz

### ISSUE THREAD

**Issue by githubvick** [helm/helm#7229]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

VMWare virtual machine cluster

**Issue -** 

When deploying ingress through HELM charts, getting this error in nginx-controller.

Error retrieving endpoints for the service dev-app: No endpoints for target port 80 in service dev-app

And a little later, these logs.

Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"dev-app", UID:"bb446c02-1d50-11ea-bdaf-00505605e916", APIVersion:"extensions/v1beta1", ResourceVersion:"50358989", FieldPath:""}): type: 'Normal' reason: 'AddedOrUpdated' Configuration for default/dev-app was added or updated
****

**Config files:**

templates/service.yaml

```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80 --> hardcoded values here for troubleshooting
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

```
templates/deployment.yaml

```
     containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80 --> hardcoded values here for troubleshooting
              targetPort: 80
              protocol: TCP
```
templates/ingress.yaml

```
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "app.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: cafe-secret
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
#              serviceName : nginx-errors
#              servicePort : 80
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}

```
values.yaml

```
ingress:
  annotations: {}
  enabled: true
  hosts:
  - host: testapp.federated.fds
    paths:
    - /
  tls:
  - hosts:
    - testapp.federated.fds
#    secretName: appdevsecret
service:
  port: 80 --> hardcoded values here for troubleshooting
  type: ClusterIP
```
**Troubleshooting:**

1) 
Tried to deploy ingress standalone by following this example https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example and didnt notice any errors in ingress.

```
curl --resolve cafe.example.com:31059:11.208.80.168 https://cafe.example.com:31059/coffee --inse
Server address: 10.233.66.70:80
Server name: coffee-56668d6f78-zfj62
Date: 13/Dec/2019:19:14:05 +0000
URI: /coffee
Request ID: 96835df43dd860e6d46ef502768b4a4f
```

2) 
kubectl get endpoints

```
NAME                ENDPOINTS                                         AGE
dev-app            10.233.66.90:80                                   16h
```

3)
kubectl describe svc dev-app
```

Name:              dev-app
Namespace:         default
Labels:            app.kubernetes.io/instance=dev
                   app.kubernetes.io/managed-by=Tiller
                   app.kubernetes.io/name=app
                   app.kubernetes.io/version=2.1.2
                   helm.sh/chart=app-0.2.0
Annotations:       <none>
Selector:          app.kubernetes.io/instance=dev,app.kubernetes.io/name=app
Type:              ClusterIP
IP:                10.233.2.71
Port:              http  80/TCP
TargetPort:        80/TCP
Endpoints:         10.233.66.90:80
Session Affinity:  None
Events:            <none>
```

4) kubectl describe pod

```
Name:               dev-app-b6cb987ff-bn5dm
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               x.x.x.x/x.x.x.x
Start Time:         Thu, 12 Dec 2019 21:31:56 -0500
Labels:             app.kubernetes.io/instance=dev
                    app.kubernetes.io/name=app
                    pod-template-hash=b6cb987ff
Annotations:        rollme: bwET7
Status:             Running
IP:                 10.233.66.90
Controlled By:      ReplicaSet/dev-app-b6cb987ff
Containers:
  app:
    Container ID:   docker://fe4d3e3f9c6f8faa5cff201045e614ae1593f48ef6241a5670251e3b8f9f796d
    Image:        ...  
    Image ID:    ...   
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 12 Dec 2019 21:31:58 -0500
    Ready:          True
    Restart Count:  0

```

5) kubectl describe ingress
```
Name:             dev-app
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<none>)
TLS:
  cafe-secret terminates testapp.federated.fds
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  testapp.federated.fds
                          /   dev-app:80 (<none>)
Annotations:
Events:  <none>
```

```
[root@11 xibo]# curl -ivs --resolve testapp.federated.fds:31059:x.x.x.x https://testapp.federated.fds:31059/ --insecure
* About to connect() to testapp.federated.fds port 31059 (#0)
*   Trying 11.208.80.168...
* Connected to testxibo.federated.fds (11.208.80.168) port 31059 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=cafe.example.com,O=Internet Widgits Pty Ltd,ST=CA,C=US
*       start date: Sep 12 16:15:35 2018 GMT
*       expire date: Sep 11 16:15:35 2023 GMT
*       common name: cafe.example.com
*       issuer: CN="cafe.example.com  ",O=Internet Widgits Pty Ltd,ST=CA,C=US
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: testapp.federated.fds:31059
> Accept: */*
>
< HTTP/1.1 302 Found
HTTP/1.1 302 Found
< Server: nginx/1.17.6
Server: nginx/1.17.6

```

I cant figure out the issue. Please help.

**Comment by githubvick** [comment]
Looks like this log is something that can ignored. The ingress wasnt working due to another issue.

**Comment by athulnath** [comment]
happening here, 
any solution?

**Comment by stealthHat** [comment]
im facing a similar problem, any update?

**Comment by stealthHat** [comment]
I manage to fix the problem, I set the wrong range of ip on the metallb config, after i fix that the app run as expected.

But the nginx ingress controller log still with that error menssage 
`W0721 22:49:50.203750       1 controller.go:1803] Error retrieving endpoints for the service devops-cqat: Error determining target port for port {0 80 } in Ingress: No pods of service devops-cqat`

weird

**Comment by bridgetkromhout** [comment]
Hi, all - Can anyone let us know if you can reproduce this issue with Helm 3? We are no longer providing support for Helm 2 as of today: https://helm.sh/blog/helm-2-becomes-unsupported/

**Comment by erritis** [comment]
I had this problem using [kubernetes-ingress](https://github.com/nginxinc/kubernetes-ingress) until I added the name field to ports :
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  externalIPs: []
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    cdk8s.io/metadata.addr: my-deployment-c820fc9e
  type: ClusterIP
```
