### ISSUE TITLE
Helm upgrade works wrong for HPA

### ISSUE THREAD

**Issue by kvendingoldo** [helm/helm#7232]
I found that helm upgrade works wrong for HPA. If we will change `maxReplicas` or `minReplicas` pods will be recreated. Expected result that if we will change `maxReplicas` nothing will be made. In the case of `minReplicas` pods will be added without redeployment of existed pods.

### Test chart:
templates/deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: "33%"
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
```

templates/hpa.yaml
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    name: nginx-deployment
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
```

Chart.yaml:
```
apiVersion: v1
name: test
appVersion: 1.0.0
version:  1.0.0
```

### How to reproduce:

1.  Deploy this chart. Result:

```
nginx-deployment-654f4bdfb6-bnxxw   1/1     Running            0          118s
nginx-deployment-654f4bdfb6-mg7hq   1/1     Running            0          102s
```

2. Set `maxReplicas: 4` and make `helm upgrade`. Result:

```
nginx-deployment-654f4bdfb6-bnxxw   1/1     Running            0          2m34s
nginx-deployment-654f4bdfb6-xc9rn   1/1     Running            0          18s
```

as you can see one pod was recreated. I expect that nothing will be made.

Let's try to do the same by using patch mechanism.

1.  Let's deploy this chart:

```
nginx-deployment-654f4bdfb6-8gfw2   1/1     Running            0          68s
nginx-deployment-654f4bdfb6-bnxxw   1/1     Running            0          4m24s
```

2. And let’s apply patch file by the following command: `kubectl patch hpa nginx-deployment --patch "$(cat patch.yaml)"`.

patch.yaml
```
spec:
  minReplicas: 2
  maxReplicas: 4
```

And we can see the expected result, nothing was made.

```
nginx-deployment-654f4bdfb6-8gfw2   1/1     Running            0          100s
nginx-deployment-654f4bdfb6-bnxxw   1/1     Running            0          4m56s
```

Output of `helm` version:

`version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}`

`Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.17", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-13T20:47:11Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

```
Cloud Provider/Platform: 
`GKE, Minikube`
