### ISSUE TITLE
nested helm chart using checksum/configmap for Roll Deplopyments throws error

### ISSUE THREAD

**Issue by ganchandrasekaran** [helm/helm#7265]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kubeadm based k8s installation on BM Server

What Happened:
```
chart/
-values.yaml
-templates/
--configMap.yaml
-charts/
--chart2/
--values.yaml
--templates/
---deployment1.yaml  
--chart3/
--values.yaml
--templates/
---deployment2.yaml  
```
Any Change in the configMap in root chart. I would like the Deployments in the subchart (deployment1 & deployment2) to have a Rolling Update.

Deployment1.yaml:
```
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
[......]
        envFrom:
          - configMapRef:
              name: e2eo
```
Command Run:
`helm install chart`

Error Message:
```
Error: render error in "e2eo/charts/chart1/templates/deployment1.yaml": template: charts/chart1/templates/deployment1.yaml:15:28: executing "charts/chart1/templates/deployment1.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: no template "charts/chart1/templates/configmap.yaml" associated with template "gotpl"

```
