### ISSUE TITLE
"--show-only" shows an error when the template is empty

### ISSUE THREAD

**Issue by dani8art** [helm/helm#7295]
I get an error when using `helm template --show-only templates/test.yaml my-chart` and the manifest generated from this is empty, e.g:

1. Having a template in `templates/secret.yaml` and `values.yaml`:
```yaml
{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  labels: 
    app.kubernetes.io/name: my-app
    helm.sh/chart: my-chart-1
type: Opaque
data:
  bind-password: {{ (include "postgresql-ha.ldapPassword" .) | b64enc | quote }}
{{- end -}}
```
```
secret:
  enabled: false
```

2. Executing `helm template --show-only templates/secret.yaml my-chart` I get:
```
Error: could not find template templates/secret.yaml in chart
```

3. And executing `helm template --show-only templates/secret.yaml --set secret.enabled=true my-chart` I get:

```
---
# Source: postgresql-ha/templates/ldap-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  labels: 
    app.kubernetes.io/name: my-app
    helm.sh/chart: my-chart-1
type: Opaque
data:
  bind-password: "YWRtaW4="
```

**should it be an error? Actually, the template is there but it is empty, right?**
**How can I avoid this error message?**

Output of `helm version`:
```bash
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
Output of `kubectl version`: **not relevant**

Cloud Provider/Platform (AKS, GKE, Minikube etc.): **not relevant**
