### ISSUE TITLE
Work with local chart dependencies easier

### ISSUE THREAD

**Issue by ebuildy** [helm/helm#7297]
-----

Output of `helm version`: 3
Output of `kubectl version`: 1.16
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kubespray on-premise

-----

FEATURE REQUEST: make easier the use of local chart.

Given a chart ``app`` that use a local chart ``nginx``,   ``Chart.yaml``

```
name: app
apiVersion: "0.0.1"
version: "0.0.1"
dependencies:
- name: "nginx"
  repository: file://../../stacks/nginx
  version: "1.16.1"
```

Where ``stacks/nginx`` is a chart created with ``helm pull bitnami/nginx   --untar`` (and modified).

**Error** Running ``helm template .`` is saying ``Error: found in Chart.yaml, but missing in charts/ directory: nginx`` , it should take the path ``../../stacks/nginx``.
