### ISSUE TITLE
Let's enable .Files.Get to read arbitrary file by external relative path

### ISSUE THREAD

**Issue by jjangga0214** [helm/helm#7305]
Let's enable `.Files.Get` to read arbitrary files by relative path, even outside of the chart.

```yaml
# secrets.yaml
data:
  foo: {{ .Files.Get  "../../../../../../path/to/external/foo" | b64enc }}
```

In the example above, I want to use an external file(`foo`) as a secret, but I don't want it to be in the chart.
