### ISSUE TITLE
Helm 3- immutable field and 3-way merge

### ISSUE THREAD

**Issue by pbecotte** [helm/helm#7350]
Output of `helm version`: version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Hi, so I see a BUNCH of tickets related to this that are closed, but I'm not 100% sure if what I am seeing is the same. The problem seems to be an issue with 3-way-merge if you use `--force` on `helm upgrade`. The previous tickets are closed saying "don't change immutable fields" ... the problem is, I'm not. For a super simple replication, make a helm chart with one template file-

```
kind: Service
apiVersion: v1
metadata:
  name: svc
  labels:
    release: {{ .Release.Name | quote }}
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
    - name: blah
      port: 8080
```

Install this chart, then run `helm upgrade --force`, you'll get `Error: UPGRADE FAILED: failed to replace object: Service "svc" is invalid: spec.clusterIP: Invalid value: "": field is immutable`.

The issue is `kubectl get -o yaml` includes immutable fields in the output, and the merge strategy is pulling those into the new manifests, meaning that --force simply can't work on any resource that has an immutable field. I think there needs to be a filter to prevent those fields from making it into the final output (and maybe throw an error directly in helm if they're in the template input to the merge?)

(apologies if there is already an open issue for this, none of the ones I saw made it clear that this is not an issue with changing the immutable field)
