### ISSUE TITLE
include is returning string instead of map

### ISSUE THREAD

**Issue by black444** [helm/helm#7370]
Is it possible to return map when I call include function?

I've got values file like this:
```
global:
  resources:
    profiles:
      - name: application-name-1
        min:
          memory: 1G
        max:
          memory: 2G

      - name: application-name-2
        min:
          memory: 2G
        max:
          memory: 4G
```

Function is searching for application name and returns its content:
```
{{- define "common.spec.template.spec.containers.envs.resources" -}}
  {{- $found := 0 }}
  {{- $profile := "" }}

  {{- range .Values.global.resources.profiles }}
    {{- if (eq .name (include "common.resources.profile" $) ) }}
      {{- $found = 1 }}
      {{- $profile = . }}
    {{- end }}
  {{- end }}

  {{- if (eq $found 1) }}
  {{ $profile }}
  {{- end }}
{{- end -}}
```

I want to write two another functions that will format output in different ways.
To not duplicate the code I would like to call my function `common.spec.template.spec.containers.envs.resources`, save output to variable and have access to them through for example `$variable.max.memory`. When I want to use it I can't, because this object is a string, not a map (I've checked it by kindOf function), however it looks ok `map[max:map[memory:2G] min:map[memory:1G] name:application-name-1]`
Of course I can copy entire searching function, but it isn't clean solution.

Is it possible? If not then then maybe it is good feature request?

Tested on version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
