### ISSUE TITLE
Can't create crb without groups in Openshift

### ISSUE THREAD

**Issue by mKamleiter** [helm/helm#7376]
Hi all,

right now I'm trying to upgrade our helm2 workflows to helm3 (v3.0.1).
We are creating clusterrolebindings for our openshift cluster bind a clusterrole to a serviceaccount.

The ClusterRolebinding created with helm2:
```apiVersion: authorization.openshift.io/v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2020-01-10T14:18:03Z"
  name: test-crb
  resourceVersion: "58921408"
  selfLink: /apis/authorization.openshift.io/v1/clusterrolebindings/infratest-crb
  uid: 03d1da58-33b4-11ea-af23-005056a75381
roleRef:
  name: test-cr
subjects:
- kind: ServiceAccount
  name: test
  namespace: testnamespace
userNames:
- system:serviceaccount:testnamespace:test
```
The Helm template is the following:
```
apiVersion: authorization.openshift.io/v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  name: test-crb
roleRef:
  kind: ClusterRole
  name: test-cr
subjects:
- kind: ServiceAccount
  name: test
  namespace: testnamespace
userNames:
- system:serviceaccount:testnamespace:test
```

With helm2 everything went fine, but an upgrade using helm 3 (after converting the secrets) fails with the following error:
```
15:21:32  + /usr/local/bin/helm upgrade --wait -i infrtest --namespace infrtest ./helm
15:21:32  Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(ClusterRoleBinding): missing required field "groupNames" in com.github.openshift.api.authorization.v1.ClusterRoleBinding
```

We don't have any groups to insert in the crb.

Output of `helm version`:
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `oc version`:
Client Version: v4.3.0
Kubernetes Version: v1.11.0+d4cacc0

BR

Michael
