### ISSUE TITLE
Cached template rendered regardless library dependency version

### ISSUE THREAD

**Issue by segrived** [helm/helm#7388]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): baremetal

---

- Create new `shared` chart with `library` type:

shared 0.1.0 chart template:
```go
{{- define "test" -}}
{{- printf "%s" "0.1.0" -}}
{{- end -}}
```

in shared 0.1.1 chart template was changed to:
```go
{{- define "test" -}}
{{- printf "%s" "0.1.1" -}}
{{- end -}}
```

- pack both versions of `shared` chart and upload to repository
- create `chart1` and `chart2` with `application` type

Template content of both charts is:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  config.xml: |-
    {{- include "test" . | nindent 4 -}}
```

- `chart1` will has dependency to `shared 0.1.0`, chart2 - to `shared 0.1.1`:

```
chart1 0.1.0 -> shared 0.1.0
chart2 0.1.0 -> shared 0.1.1
```

- after `helm dependency update .` command, execution `helm template .` for each chart is predicted:

`chart1` template output:
```yaml
---
# Source: chart1/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  config.xml: |-
    0.1.0
```

`chart2` template output:
```yaml
---
# Source: chart2/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  config.xml: |-
    0.1.1
```

for `chart2`

- pack both charts and upload to repository

- create `main` chart with dependencies to `chart1 0.1.0` and `chart2 0.1.0`
- update dependencies and execute `helm template .`

output
```yaml
---
# Source: main/charts/chart1/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  config.xml: |-
    0.1.0
---
# Source: main/charts/chart2/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  config.xml: |-
    0.1.0
```

so both charts was rendered with same template from `shared 0.1.0`

---

expected result: i expect rendered `chart2` will render template from `shared 0.1.1`, but looks like it was cached and reused regardless of chart version

[MinimalRepro.zip](https://github.com/helm/helm/files/4052564/MinimalRepro.zip)
