### ISSUE TITLE
helm 3.0.2 doesn't respect dependencies conditions

### ISSUE THREAD

**Issue by zzarkouna** [helm/helm#7389]
Output of `helm version`:
helmenv version
3.0.2
Output of `kubectl version`:
k version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.23", GitCommit:"81c87c699557fed991e292cd328b2129c2f242a2", GitTreeState:"clean", BuildDate:"2019-11-07T19:23:23Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

parent chart.yaml
```
apiVersion: v2
description: A Kong chart for Kubernetes
name: kong
version: 0.1.0

dependencies:
- name: postgres
  version: "0.1.0"
  repository: "file://../postgres"
  condition: postgres.enabled, kong.postgres.enabled
- name: gcloud-sqlproxy
  version: "0.1.0"
  repository: "file://../gcloud-sqlproxy"
  condition: gcloud-sqlproxy.enabled, kong.gcloud-sqlproxy.enabled
```
and parent values.yaml
```
gcloud-sqlproxy:
  enabled: false
postgres:
  enabled: false
```
subchart chart.yaml
```
apiVersion: v2
description: A Kong chart for Kubernetes
name: kong
version: 0.1.0

dependencies:
- name: kong
  version: "0.1.0"
  repository: "file://../../../my_chart/kong"
```
and subchart values.yaml
```
kong:
  postgres:
    enabled: true

  gcloud-sqlproxy:
    enabled: false
```

`helm packages` asks me to run a dependency update
and when it packages it doesn't remove deps
and when it upgrades neither
