### ISSUE TITLE
Is there a way or work around to render value file for use in third part chart which doesn't use tpl function?

### ISSUE THREAD

**Issue by polasekr** [helm/helm#7392]
Use case:

I have a chart with has its my own templates, but it also includes 3rd party charts. 
Example is my chart which contains my template for deploying openldap and it also includes chart dependency “jupyterhub”. Jupyter hub is using ldap for user authentication, so it needs to know values for ldap configuration. In my value file I would like to do have it organized the way that I do not duplicate any value:

values.yaml
```
global:
  env: dev
  dnsZone: "clnt-{{ .Values.global.env }}.example.com" 

openldap:
  env: 
    LDAP_ORGANISATION: "{{ tpl .Values.global.dnsZone . }}"
    LDAP_DOMAIN: "{{ tpl .Values.global.dnsZone . }}"

jupyterhub:
    auth:
	dns: "{{ tpl .Values.global.dnsZone . }}"
```

The problem rises due to fact that jupiterhub as a third party chart doesn’t use tpl function to process .Values.auth.dns (same as many other third party charts) and it results that value in the template being redered literal `{{ tpl .Values.global.dnsZone . }}` rather than expected `clnt-dev.example.com`.

Is there any workaround for this issue? 

I want to ensure that value file has each value defined only once and used in multiple places if required, to avoid deploying misbehaving application due to inconsistency of configurations used by application in a scenario where changes to a specific value weren’t done in all places. 

I know that I can get the helm code for third party chart and make local modifications to it, but this in my view diminishes the benefit of using third party chart, since I have to keep maintaining the modified chart.

Any suggestions/tricks/workarounds are welcome.
Thank you for reading it.

Just for completeness I am using helm 3.0.0.
