### ISSUE TITLE
Helm doesnt create a serviceaccount with a imagepullsecret

### ISSUE THREAD

**Issue by morrowyn** [helm/helm#7394]
Hi, 
I'm using the default helm template as basis. I have modified the following files:
values.xml
```
serviceAccount:
  create: true
  name:
  imagePullSecrets:
  - acr-auth
```
where acr-auth is a secret using the 
` kubectl create secret docker-registry acr-auth --docker-server $ACR_NAME.azurecr.io --docker-username $ACR_NAME --docker-password $ACR_PWD --docker-email ignore@dummy.com` 

After that I modified the `serviceaccount.yaml` inside the `/templates` directory
```
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mychart.serviceAccountName" . }}
  labels:
{{ include "mychart.labels" . | indent 4 }}
  imagePullSecrets:
  {{- range .Values.serviceAccount.imagePullSecrets }}
  - name: {{- . | indent 1}}
  {{- end }}
{{- end -}}
```
When I `--debug` and/or `--dry-run` the install I get the following output
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: peddling-lightningbug-mychart
  labels:
    app.kubernetes.io/name: mychart
    helm.sh/chart: mychart-0.1.0
    app.kubernetes.io/instance: peddling-lightningbug
    app.kubernetes.io/version: "1.1"
    app.kubernetes.io/managed-by: Tiller
  imagePullSecrets:
  - name: acr-auth
```
from what I see the service account pickup the imagePullSecret just fine. However when I install the chart and do a `describe serviceaccounts` on the created serviceaccount I get the following.
```
Name:                peddling-lightningbug-mychart
Namespace:           default
Labels:              app.kubernetes.io/instance=peddling-lightningbug
                     app.kubernetes.io/managed-by=Tiller
                     app.kubernetes.io/name=peddling-lightningbug
                     app.kubernetes.io/version=1.1
                     helm.sh/chart=peddling-lightningbug-0.1.0
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   peddling-lightningbug-mychart-token-k9tkj
Tokens:              peddling-lightningbug-mychart-token-k9tkj
Events:              <none>
```
And because the service account doesn't have the imagepullsecret, it fails to download the image because it's not authorized. 

I tested the private registry with a basic `kubectl run --image=` and a patched default serviceaccount with the acr-auth and the image is downloaded as expected.

Any ideas what I'm missing here?

I'm using
``` 
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
```
on microk8s and I have manually added the azurecr.io registry to the `/var/snap/microk8s/current/args/containerd-template.toml` file and restarted it.
