### ISSUE TITLE
Helm does not support having two dependencies using the same name but from a different repository

### ISSUE THREAD

**Issue by desaintmartin** [helm/helm#7413]
If one defines a chart with Chart.yaml: 
```yaml
apiVersion: v2
name: willcrash
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
- alias: elasticsearch-new
  name: elasticsearch
  repository: "https://helm.elastic.co"
  version: "*"
- alias: elasticsearch-legacy
  name: elasticsearch
  version: "*"
  repository: https://kubernetes-charts.storage.googleapis.com/
```

Only one of the two subcharts will get stored (even if the two are downloaded).

Is helm supposed to support this use case or is it an expected behavior?

Related to https://github.com/helm/helm/issues/7411

Output of `helm version`:
`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`
