### ISSUE TITLE
using --set key[0]=value and toYaml strips yaml

### ISSUE THREAD

**Issue by abelal83** [helm/helm#7438]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

I have a config as below in values.yaml

```
config:
  client: {}
  clients:
    - url: http://loki:3100/loki/api/v1/push
      backoff_config:
        maxbackoff: 5s
        maxretries: 20
        minbackoff: 100ms
      batchsize: 102400
      batchwait: 1s
      timeout: 10s
      # Set label for k8s cluster identification
      external_labels:
        kubernetes_cluster: kube-dev
        loki_host: loki-dev

    - url: http://loki:3100/loki/api/v1/push
      backoff_config:
        maxbackoff: 5s
        maxretries: 20
        minbackoff: 100ms
      batchsize: 102400
      batchwait: 1s
      timeout: 10s
      # Set label for k8s cluster identification
      external_labels:
        kubernetes_cluster: kube-dev
        loki_host: loki-dev
      basic_auth:
        username: loki-dev
        password: "password"
```

I set values `helm upgrade --install ./ --namespace loki --wait --set config.clients[0].external_labels.kubernetes_cluster="kube-dev-we",config.clients[1].external_labels.kubernetes_cluster="kube-dev-ne"`

This get's transformed by /template/configmap.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "promtail.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "promtail.name" . }}
    chart: {{ template "promtail.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  promtail.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
```

I expect the output to be

```
config:
  client: {}
  clients:
    - url: http://loki:3100/loki/api/v1/push
      backoff_config:
        maxbackoff: 5s
        maxretries: 20
        minbackoff: 100ms
      batchsize: 102400
      batchwait: 1s
      timeout: 10s
      external_labels:
        kubernetes_cluster: kube-dev-we
        loki_host: loki-dev

    - url: http://loki:3100/loki/api/v1/push
      backoff_config:
        maxbackoff: 5s
        maxretries: 20
        minbackoff: 100ms
      batchsize: 102400
      batchwait: 1s
      timeout: 10s
      external_labels:
        kubernetes_cluster: kube-dev-ne
        loki_host: loki-dev
      basic_auth:
        username: loki-dev
        password: "password"
```

instead I get this

```
config:
  client: {}
  clients:
    -   external_labels:
        kubernetes_cluster: kube-dev-we

    -   external_labels:
        kubernetes_cluster: kube-dev-ne
```

Am I doing something wrong or is there a bug?
