### ISSUE TITLE
helm install stuck on helm.sh/hook

### ISSUE THREAD

**Issue by phumberdroz** [helm/helm#7447]
Hey I just found the following bug when executing `helm upgrade -i`
Have a `helm.sh/hook` with a `serviceAccountName` that does not yet exist.

The job does not execute because of this error: `Warning  FailedCreate  10s (x2 over 20s)  job-controller  Error creating: pods "message-service-migration-" is forbidden: error looking up service account 01/message-service: serviceaccount "message-service" not found` from `kubectl describe job`. 

The command for `helm upgrade -i` will not exit or fail.
```
# Source: message-service/templates/deploymentMigration.yaml
apiVersion: batch/v1
kind: Job
metadata:
    annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
    template:
    spec:
        serviceAccountName: RELEASE-NAME-message-service   
```

Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Digitalocean

**Comment by phumberdroz** [comment]
@bacongobbler is this the desired behavior?

**Comment by lkysow** [comment]
The workaround for us was to set the weight of the job to be greater than the weight of the service account so that the serviceaccount gets created first. Since the default weight is 0, we set the job to 1.

```yaml
# job spec
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
```

**Comment by phumberdroz** [comment]
That is an awesome followup thanks!

**Comment by hickeyma** [comment]
@phumberdroz From [chart hooks](https://helm.sh/docs/topics/charts_hooks/) doc:

> The library sorts hooks by weight (assigning a weight of 0 by default) and by name for those hooks with the same weight in ascending order.
The library then loads the hook with the lowest weight first (negative to positive)
The library waits until the hook is “Ready” (except for CRDs)

That mirrors the advice from @lkysow in https://github.com/helm/helm/issues/7447#issuecomment-611115950.

Seems to be working as expected. Let me know if that answers your question.

**Comment by lkysow** [comment]
I'm not sure it's working as expected because it seems like the service account isn't submitted to the cluster when it has the same weight as the job.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: abc
  annotations:
    "helm.sh/hook": pre-delete
spec:
  serviceAccountName: abc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: abc
  annotations:
    "helm.sh/hook": pre-delete
```

You'll need to add a command to the job but I bet when you submit this the job never runs because the service account doesn't exist.

**Comment by hickeyma** [comment]
If same weight applies, its alphabetical order which means the Job tries to be created before the ServiceAccount.

**Comment by bacongobbler** [comment]
If the names are identical as demonstrated in your last comment @lkysow, I believe the sorting algorithm takes them in its current order. In your example, the job would be submitted first, then the service account.

Have you tried reversing the order?

I think given that @phumberdroz's original question has been answered, we can probably close this issue out. Is there any other questions you had, @phumberdroz?

**Comment by lkysow** [comment]
> Have you tried reversing the order?

In our helm chart they're in different files. Maybe it's doing lexicographical sorting on the files too if the names are the same?

> its alphabetical order

I would have thought this was alphabetical on the name, not the kind of the resource. Perhaps the docs should be updated to say that it's alphabetical on the name and then on the kind?

@bacongobbler I think it'd be pretty hard to sort on the "right" order that wouldn't cause dependency issues so I guess this would be pretty hard to fix. Maybe if helm submitted all resources with the same weight and same name at the same time?

**Comment by bacongobbler** [comment]
> Maybe if helm submitted all resources with the same weight and same name at the same time?

Unfortunately, the current behaviour is what's described as Helm's current behaviour, and many users rely on that behaviour. I don't think we can make that change without breaking user's assumptions about how Helm's hook system works.

We could potentially discuss changing this behaviour for Helm 4, but I'm curious how submitting the service account and the job at the same time would solve your issue. Unless I'm mistaken, it would still result in the same issue. The service account has to be present in the cluster by the time the job is submitted. Submitting both the job and the service account at the same time won't solve the issue AFAIK

**Comment by lkysow** [comment]
I hear you, makes sense. Just to clear it up though, applying the service account even if it's after the job is submitted does allow the job to run. But because we're waiting for the job to be ready before submitting the service account it will never run. Example:

```yaml
# job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: abc
  annotations:
    "helm.sh/hook": pre-delete
spec:
  template:
    spec:
      serviceAccountName: abc
      containers:
        - name: test
          image: nginx
      restartPolicy: Never
```

```bash
k apply -f job.yaml
k get job
NAME   COMPLETIONS   DURATION   AGE
abc    0/1                      20s
k describe job abc
Name:           abc
Namespace:      default
Selector:       controller-uid=801fd95f-7a8e-11ea-a9db-eaea9bea97cf
Labels:         controller-uid=801fd95f-7a8e-11ea-a9db-eaea9bea97cf
                job-name=abc
Annotations:    helm.sh/hook: pre-delete
                kubectl.kubernetes.io/last-applied-configuration:
                  {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{"helm.sh/hook":"pre-delete"},"name":"abc","namespace":"default"},"spec":{...
Parallelism:    1
Completions:    1
Pods Statuses:  0 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           controller-uid=801fd95f-7a8e-11ea-a9db-eaea9bea97cf
                    job-name=abc
  Service Account:  abc
  Containers:
   test:
    Image:        nginx
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type     Reason        Age                From            Message
  ----     ------        ----               ----            -------
  Warning  FailedCreate  14s (x2 over 24s)  job-controller  Error creating: pods "abc-" is forbidden: error looking up service account default/abc: serviceaccount "abc" not found
```

```yaml
# sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: abc
```

```
k apply -f sa.yaml
k describe job abc
Name:           abc
Namespace:      default
Selector:       controller-uid=801fd95f-7a8e-11ea-a9db-eaea9bea97cf
Labels:         controller-uid=801fd95f-7a8e-11ea-a9db-eaea9bea97cf
                job-name=abc
Annotations:    helm.sh/hook: pre-delete
                kubectl.kubernetes.io/last-applied-configuration:
                  {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{"helm.sh/hook":"pre-delete"},"name":"abc","namespace":"default"},"spec":{...
Parallelism:    1
Completions:    1
Start Time:     Thu, 09 Apr 2020 11:18:54 -0700
Pods Statuses:  1 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           controller-uid=801fd95f-7a8e-11ea-a9db-eaea9bea97cf
                    job-name=abc
  Service Account:  abc
  Containers:
   test:
    Image:        nginx
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type     Reason            Age                From            Message
  ----     ------            ----               ----            -------
  Warning  FailedCreate      30s (x2 over 40s)  job-controller  Error creating: pods "abc-" is forbidden: error looking up service account default/abc: serviceaccount "abc" not found
  Normal   SuccessfulCreate  10s                job-controller  Created pod: abc-59zp4
```
