### ISSUE TITLE
Search Repo --versions parameter, ignores appVersion

### ISSUE THREAD

**Issue by ebogdum** [helm/helm#7462]
Made a chart with one chart version (0.2.0) and two appVersions (1.16.0, 1.16.1)
Added that index file to a local repo.

When searching for all versions ( -l, --versions ... with each version of each chart on its own line ...) it doesn't show all the versions, just the last one.

appVersion 1.16.0 is missing from the list.
```
& helm search repo local -l
NAME            CHART VERSION   APP VERSION     DESCRIPTION                
local/chart     0.2.0           1.16.1          A Helm chart for Kubernetes
```

I also tried to update the repo before searching and still the same result
```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "local" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

& helm search repo local -l
NAME            CHART VERSION   APP VERSION     DESCRIPTION                
local/chart     0.2.0           1.16.1          A Helm chart for Kubernetes
```

index.yaml file looks like this
```
apiVersion: v1
entries:
  chart:
    - apiVersion: v2
      appVersion: 1.16.0
      created: "2020-01-24T11:10:47.408792+02:00"
      description: A Helm chart for Kubernetes
      digest: 7c08ece0dcdf8b14bfdd876e4b0542c52c6521d3643e88be9b34d831bccaa494
      name: chart
      type: application
      urls:
        - http://localhost:5050/chart-0.2.0.tgz
      version: 0.2.0
    - apiVersion: v2
      appVersion: 1.16.1
      created: "2020-01-24T11:10:47.409917+02:00"
      description: A Helm chart for Kubernetes
      digest: 03fbbd58325cd46705cc190c23feca63779b3a6a77521f8f55f82085dc460433
      name: chart
      type: application
      urls:
        - http://localhost:5050/chart-0.2.0.tgz
      version: 0.2.0
generated: "2020-01-24T11:10:47.406749+02:00"
```

Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.6"}

Local Environment:
(Mac) OS X
