### ISSUE TITLE
Unable to deploy chart with K8 secret as ENV

### ISSUE THREAD

**Issue by joshk132** [helm/helm#7467]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:
```Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kops cluster on AWS

Error message:
```
Error: template: billing/templates/deployment.yaml:36:31: executing "billing/templates/deployment.yaml" at <.Values.env.mongo_uri>: can't evaluate field mongo_uri in type interface {}
```
Inside env section of values.yaml
```
- name: 'mongo_uri'
    valueFrom:
      secretKeyRef:
        name: mongouri
        key: mongo_uri
```

K8's secrets file minus my DB string
```
apiVersion: v1
kind: Secret
metadata:
  name: mongouri
  namespace: production
type: Opaque
data:
  mongo_uri: <base64 db string>
```
Why am I getting this error message? I was able to hard code the values properly using the 
```
-name:
 value: 
```
format however when I introduce the env variable via a kubernets secret I then am unable to get it to work

_edit(mattfarina): fix display of code snippets_
