### ISSUE TITLE
a failed `lookup` removes all rendered output

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#7473]
After testing the `lookup` function introduced in #6752, I found calling `lookup` in a template caused the rendered output to be empty.

Here's what I used to test. After creating a new chart with `helm create foo`, I modified `foo/templates/deployment.yaml` to add a new label that performs a lookup:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foo.fullname" . }}
  labels:
    foo: {{ (lookup "v1" "Deployment" .Release.Namespace "nginx").metadata.name }}
...
```

And then created a deployment to match that lookup:

```
><> kubectl run nginx --image=nginx --replicas=5
deployment.apps/nginx created
```

No output is rendered.

```
><> ./bin/helm template --validate ./foo/

><> ./bin/helm version
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"9c680e604be8d516960eecbbc3718ace91643cea", GitTreeState:"dirty", GoVersion:"go1.13.6"}
```

Calling `helm install` fails to render, as no objects were rendered.

```
><> ./bin/helm install foo ./foo/
Error: no objects visited
```

I will look further into this, but @raffaelespazzoli, can you please look further into this and see where the issue may be stemming from?
