### ISSUE TITLE
Override child chart values

### ISSUE THREAD

**Issue by jacobtomlinson** [helm/helm#7493]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

I have two charts, one is the parent and one is the child. I'm trying to figure out how to override the child values but remapped to the child's namespace.

For example my child chart's `values.yaml` looks like this.

```yaml
foo: bar
```

and the parent's `values.yaml` looks like this

```yaml
foo: baz
```

When I run `helm install --dry-run --debug test parent` the computed values are

```yaml
child:
  foo: bar
  global: {}
foo: baz
```

I'd like to remap this so I just get

```yaml
child:
  foo: baz
  global: {}
```

My expectation was that adding the following to my `requirement.yaml` file would do this. But it doesn't seem to.

```yaml
dependencies:
- name: child
  import-values:
    - child: foo
      parent: foo
```

Am I doing something wrong or misunderstanding the purpose of `import-values`?

**Comment by omkensey** [comment]
I think you can just set this key in the parent chart's values to do what you want:

```
child:
  foo: baz
```

**Comment by bacongobbler** [comment]
@omkensey's right. This is also explained in the documentation: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart

Closing as answered.

**Comment by jacobtomlinson** [comment]
No this is not what I want. I'm well aware that I can do that, but I do not want to reference the child chart by name within the parent chart config.

Here's a more concrete example. If `rbac.enabled` is in both charts and defaults to false, I only want to set it to true once.

I want to avoid 

```
rbac:
  enabled: true

child:
  rbac:
    enabled: true
```

I just want a concise config like

```
rbac:
  enabled: true
```

**Comment by hickeyma** [comment]
@jacobtomlinson If you have access to parent and children charts, you could use global values: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

**Comment by jacobtomlinson** [comment]
Thanks but I do not have access to the child chart.

**Comment by hickeyma** [comment]
Hmmm, not sure then. Might be worth asking out in #helm-users channel if someone doesn't respond here.

**Comment by jacobtomlinson** [comment]
Thanks I'll try there. 

Could I get the re-opened until it has an actual answer? If that answer is that it's not possible then fine, but it's currently not clear.

**Comment by omkensey** [comment]
When you use import-values in requirements.yaml, does the chart actually render or do you get an exit with an error?

**Comment by jacobtomlinson** [comment]
The chart renders with no errors.

## Example configs 

_Both charts have an empty templates directory._

```yaml
# parent/values.yaml
rbac:
  enabled: true
```

```yaml
# parent/charts/child/values.yaml
rbac:
  enabled: false
```

```yaml
# parent/Chart.yaml
apiVersion: v2
name: parent
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
- name: child
  import-values:
  - child: rbac
    parent: rbac
```

## Output

```console
$ helm install --dry-run --debug test parent
install.go:149: [debug] Original chart version: ""
install.go:166: [debug] CHART PATH: /tmp/parent

NAME: test
LAST DEPLOYED: Mon Feb  3 10:09:39 2020
NAMESPACE: jtomlinson
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
child:
  global: {}
  rbac:
    enabled: false
rbac:
  enabled: true

HOOKS:
MANIFEST:
```

## Expectation

I would expect the `child.rbac.enabled` value to be `true`.
