### ISSUE TITLE
--set-string interprets value as scientific notation

### ISSUE THREAD

**Issue by mdibaiee** [helm/helm#7496]
Steps to reproduce:

Create a new Helm chart:
```
helm create test
```

Modify `templates/_helpers.tpl` and add this to the end:
```
app.kubernetes.io/test: {{ .Values.image.tag | quote }}
```

So your common labels section looks like:
```
{{/*
Common labels
*/}}
{{- define "set-string-scientific-notation.labels" -}}
app.kubernetes.io/name: {{ include "set-string-scientific-notation.name" . }}
helm.sh/chart: {{ include "set-string-scientific-notation.chart" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/test: {{ .Values.image.tag | quote }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}
```

Now try a dry-run and debug install:
```
helm upgrade --install --set-string 'image.tag=00215e6' test-issue . --debug --dry-run
```

Output includes:
```
  labels:
    app.kubernetes.io/name: set-string-scientific-notation
    helm.sh/chart: set-string-scientific-notation-0.1.0
    app.kubernetes.io/instance: test-issue
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/test: "2.15e+08"
    app.kubernetes.io/managed-by: Tiller
```

As you see, the new label has the value `2.15e+08`, even though I've used `--set-string`.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.12", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-07T19:27:01Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by bacongobbler** [comment]
Have you tested this with a more recent version of Helm? Looks like you're using 2.14.3.

**Comment by omkensey** [comment]
In Helm 3 I get this when I render with `helm template`:

```
  labels:
    helm.sh/chart: test-0.1.0
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: test
    app.kubernetes.io/test: "00215e6"
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
```
Version info:
```
$ helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
```
