### ISSUE TITLE
Proposal / Request: Chart Overloads / Appendments

### ISSUE THREAD

**Issue by DandyDeveloper** [helm/helm#7512]
**Summary**
Allow consumers of a parent chart to append to an existing template using an overload mechanism akin to object orientated languages allow. This allows a consumer to circumvent the defined template, without missing out on potential updates/upgrades contributed to the parent chart. 

**Issue** 
With the current outlook on the helm ecosystem, parent charts are typically owned by an entity and open sourced to allow contributions. These items being merged are dependent on the owner of said chart approving the contribution.

As a consumer of said chart, if there is a certain attribute in a resource spec, I am unable to access or populate that unless it is explicitly defined in the template of the parent chart. 

I would like to, without missing core updates to the chart, make my own amendments to the template. 

**Workarounds**
There are clear workaround here. However, they all have problems: 

 - Make a contribution correcting / adding the object you need. _Depends on owner_
 - Copy the chart locally, referencing it using `file://` instead. _Missing core updates. QOL changes made publically_

**Scenarios**
I have a chart that doesn't support the `hostPath` attribute as a volume to mount a directory, instead the parent template has the following:

```
volumes:
  - name: empty
    emptyDir: {}
```

but I actually need this:

```
volumes:
  - name: host
     hostPath: /var/lib/host/xyz
     type: Directory 
```

This could be solved by adding some form of override to the chart, but this has a dependency on the owner agreeing to your change. Which in many cases, they probably would not, because it is a niche use-case. 

**Proposal**
Support a mechanism to provide an `overloads.yaml` in the same dir as the `values.yaml`. This could look something like this: 

```
name: overrideDeploy
template: parentChart/template/deployment.yaml
overrides:
  - location: spec.containers[0].labels
    override:
       labels: 
         example: LabelExampleOverride
```

I could probably make a POC for this, but I want to know if this is something that would genuinely be helpful. I would also like to know if there are any suggestions on a better approach to this.
