### ISSUE TITLE
Timeout 'helm upgrade --wait'

### ISSUE THREAD

**Issue by ArieGato** [helm/helm#7513]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

I created a helm chart to run in a release pipeline in devops with the flag --wait. The build task times out and with --debug flag it continuously shows:
```
2020-02-03T07:46:29.3015941Z wait.go:182: [debug] Service does not have IP address: ******
```
But when I check the service in k8s it is running and functioning properly.

This is the output of --dry-run:
```
# Source: identityserver/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: identityserver
  labels:
    app: identityserver
    chart: identityserver-0.1.0
    release: identityserver-1580717645
    heritage: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  externalIPs:
    - 172.16.253.90
  selector:
    app: identityserver
    release: identityserver-1580717645
```
