### ISSUE TITLE
Helm 3.0.3: helm upgrade --force returns UPGRADE FAILED: failed to replace object

### ISSUE THREAD

**Issue by rasentry** [helm/helm#7516]
helm upgrade --force ends with error:
Error: UPGRADE FAILED: failed to replace object: Service "test-service" is invalid: spec.clusterIP: Invalid value: "": field is immutable

```
# Source: test-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    helm.sh/chart: test-service-0.1.0
    app.kubernetes.io/name: test-service
    app.kubernetes.io/instance: test-service
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    changeable-lable: "value1"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: test-service
    app.kubernetes.io/instance: test-service
```
Error occurs only when I change value of lable "changeable-lable" to "value2"
I think this issure is related to #6378 and there nothing related with to the `clusterIP: ""`

Output of `helm version`:
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
