### ISSUE TITLE
Cannot pull from private repository

### ISSUE THREAD

**Issue by iohenkies** [helm/helm#7519]
**Output of `helm version`:**
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

**Output of `kubectl version`:**
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** 
On prem, Rancher created

**Steps:**
Following the steps as described here:
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

1. Creating the secret like below, shows in my Rancher UI with credentials 'Username: myusername - Password: Saved'
```
kubectl create secret docker-registry secretname \
  --docker-server=myprivate.registry.com:8080 \
  --docker-username=myusername \
  --docker-password=myuserpass \
  --namespace=appnamespace
```

2. Created a pod like below:
```
apiVersion: v1
kind: Pod
metadata:
  name: private-reg
  namespace: appnamespace
spec:
  containers:
  - name: private-reg-container
    image: myprivate.registry.com:8080/myapp/app/viewer
  imagePullSecrets:
  - name: secretname
````

3. kubectl apply it: will pull the correct image and run. This shows us, I believe, that Kubernetes and the private registry (on prem GitLab) are working correctly.

Now for helm, following the official guide here:
https://helm.sh/docs/howto/charts_tips_and_tricks/#creating-image-pull-secrets

Or some of the instructions here:
https://devops.stackexchange.com/questions/4013/how-to-pull-a-docker-image-from-a-private-docker-registry-using-helm

1. I'm starting from scratch:
$ helm create mychart
$ vim mychart/values.yaml
```
image:
  repository: myprivate.registry.com:8080/myapp/app/viewer
  pullPolicy: IfNotPresent

imageCredentials:
  registry: myprivate.registry.com:8080
  username: myusername
  password: myuserpass
```

2. Add it to _helpers.tpl
$ vim mychart/templates/_helpers.tpl
```
{{- define "imagePullSecret" }}
{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imageCredentials.registry (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc) | b64enc }}
{{- end }}
```

3. Add the secret.yaml
$ vim mychart/templates/secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
```

4. Apply and put online:
$ helm package mychart/
$ helm repo index mychart/
$ helm push mychart-0.1.0.tgz biochartstst
$ helm repo update
$ helm install mychart -f mychart/values.yaml biochartstst/mychart

5. This will create the deployment but unfortunately is not able to pull the image.
$ kubectl logs mychart-8fd5c577f-6vtzv
```
Error from server (BadRequest): container "mychart" in pod "mychart-8fd5c577f-6vtzv" is waiting to start: trying and failing to pull image
```
$ kubectl describe pod mychart-8fd5c577f-6vtzv
```
Events:
  Type     Reason            Age                   From                      Message
  ----     ------            ----                  ----                      -------
  Normal   Scheduled         <unknown>             default-scheduler         Successfully assigned default/mychart-8fd5c577f-6vtzv to tst-kube-03
  Normal   Pulling           31m (x3 over 32m)     kubelet, tst-kube-03  Pulling image "myprivate.registry.com:8080/myapp/app/viewer:1.16.0"
  Warning  Failed            31m (x3 over 32m)     kubelet, tst-kube-03  Failed to pull image "myprivate.registry.com:8080/myapp/app/viewer:1.16.0": rpc error: code = Unknown desc = Error response from daemon: Get https://myprivate.registry.com:8080/myapp/app/viewer/manifests/1.16.0: denied: access forbidden
  Warning  Failed            31m (x3 over 32m)     kubelet, tst-kube-03  Error: ErrImagePull
  Normal   BackOff           31m (x4 over 32m)     kubelet, tst-kube-03  Back-off pulling image "myprivate.registry.com:8080/myapp/app/viewer:1.16.0"
  Warning  Failed            31m (x4 over 32m)     kubelet, tst-kube-03  Error: ImagePullBackOff
```
What I noticed from the Rancher UI, and is different from the manual creation of a secret earlier, is that it creates a secret with type _Auth token Saved_ instead of _Username: myusername_ & _Password: Saved_. But maybe it's nothing.

What am I doing wrong? :-)

**Comment by mattfarina** [comment]
I'm not sure where it's going wrong. If you look at the [example Kubernetes docs there are two methods to create the secret](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/). The first method uses the existing logged in details with the auth token to pass in the information. The second contains both the auth token and user credentials.

The method Helm outlines mirrors the first while noting a detail from the second.

> To understand what is in the auth field, convert the base64-encoded data to a readable format:
>
> ```
> echo "c3R...zE2" | base64 --decode
> ```
>
> The output, username and password concatenated with a :, is similar to this:
>
> ```
> janedoe:xxxxxxxxxxx
> ```

According to the docs the auth token is the username and password separated by a `:` and base64 encoded. The Helm snippet generates that.

So, the Helm snippet should work. A couple things you can look at:

1. Some registries use a different sort of password for the CLI/API than the login on. Quay is one of those. The password I would use for Quay is different from my Quay password. You can find this in the Account settings.
2. In the manifest Helm is generating (e.g., a pod, deployment, etc) is the `imagePullSecrets` present?

**Comment by iohenkies** [comment]
Hi Matt. I tried both methods to create a secret and verified the creation with a base64 --decode.  Username, password and auth token seem valid.

1. I understand and I can check for possibilities (we're using GitLab). But wouldn't the 'kubectl create secret' workflow as described above and 'docker login' stumble upon the same problem then? These two do work
2. This could be a thing. The official documentation doesn't mention it though:
https://helm.sh/docs/howto/charts_tips_and_tricks/#creating-image-pull-secrets
What should it be? Below is a snippet from the default that is generated from a 'helm create mychart'.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mychart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
```
