### ISSUE TITLE
helm dependency update -- prevent attempting to fetch locally

### ISSUE THREAD

**Issue by nodesocket** [helm/helm#7526]
When running `helm dependency update` it is possible to prevent the message:`Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):`? i.e. don't try to fetch locally.

```
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Downloading minio from repo https://kubernetes-charts.storage.googleapis.com
Deleting outdated charts
```

My `requirements.yaml` is simply:

```yaml
dependencies:
  - name: minio
    version: 2.5.9
    repository: https://kubernetes-charts.storage.googleapis.com
```
