### ISSUE TITLE
helm 3.0.3 not rendering <CHARTNAME> in values file when using starters

### ISSUE THREAD

**Issue by davidgp1701** [helm/helm#7532]
We use some starters for creating some helm charts automatically in our CI/CD pipelines.

Let's image that we have a test starter with these two files among others:

* Chart.yaml:
```yaml
apiVersion: v2
description: <CHARTNAME> helm chart
name: <CHARTNAME>
version: 0.0.1
```
* values.yaml:
```yaml
# Chart example
#
<CHARTNAME>:
  port: 8080
  environment:

resources: {}
```
When creating the Chart with helm **v3.0.2**:

```shell
$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

$ helm create -p test example
Creating example
```
The chart and value files are rendered like this:

```shell
$ cat example/Chart.yaml
apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for Kubernetes
name: example
type: application
version: 0.1.0

$ cat example/values.yaml
example:
  environment: null
  port: 50051
resources: {}
```
That it is the expected behavior.

When creating the chart with helm **v3.0.3**:

```shell
$ helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}

$ helm create -p test example
Creating example
```
The output files
```shell
$ cat example/Chart.yaml
apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for Kubernetes
name: example
type: application
version: 0.1.0

$ cat example/values.yaml
# Chart example
#
<CHARTNAME>:
  port: 50051
  environment:

resources: {}
```

That it is not the expected behavior, I would expect in the values file  that `<CHARTNAME>` would be rendered to `example`.
