### ISSUE TITLE
helm create with custom chart.yaml

### ISSUE THREAD

**Issue by laurencee** [helm/helm#7566]
Helm version: 3.0.3

This might be a feature request rather than a bug as I'm not sure if this was intended behavior.

For our use case we have a various helm templates available for different application types and want to provide preconfigured `Chart.yaml` files to help enforce naming conventions for different application types.

The issue is that the command `helm create charts -p my-template` seems to write out its own `Chart.yaml` ignoring any existing `Chart.yaml` in `my-template`.

**Comment by hickeyma** [comment]
@laurencee It is intended that the generator overwrites the `Chart.yaml`. See docs: https://helm.sh/docs/topics/charts/#chart-starter-packs

It is an interesting use case that you raise. To get a better understanding, could you show by example why you would need to keep the `Chart.yaml` file intact.

**Comment by laurencee** [comment]
@hickeyma Thank you for the prompt reply and I apologies for missing that in the docs. I've updated the title appropriately.

A simple example for our case is that we do not currently use the appVersion field from the `Chart.yaml`. We also have a convention to use the chart name to determine the names of various other resources such as the docker image name and have documentation to indicate this to users. 

We also had planned to display some additional comments above the name field to describe where to see our chart naming conventions.

So given the following chart.yaml
```yaml
apiVersion: v2
name: replace-me-cron
description: A cron job Helm chart for Kubernetes
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates.
version: 0.1.0
```

In the `_helpers.tpl` we have entry defined as such
```
{{/*
Provide a default image repository value using the name of the chart.
*/}}
{{- define "charts.imageRepository" -}}
{{- if .Values.image.repositoryOverride -}}
{{- .Values.image.repositoryOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := (include "charts.name" .) -}}
{{- printf "our.repository.io/%s" $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
```

From within `cronjob.yaml`
```yaml
...
containers:
  - name: {{ .Chart.Name }}
    image: "{{ include "charts.imageRepository" . }}:{{ .Values.image.tag }}"
...
```
