### ISSUE TITLE
helm --set change only one list element

### ISSUE THREAD

**Issue by suppix** [helm/helm#7569]
Hello. 

Is it possible to change only one list element ? 

I created chart using helm create command, ingress.yaml - is the original, I didn't change it.

Somehow when I try to change "host", I loose paths data.

values.yaml
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: my.domain.com
      paths:
        - /my/domain
```
helm template --debug --set-string ingress.hosts[0].host="your.domain.com"  .

The result is:
```
spec:
  rules:
    - host: "your.domain.com"
      http:
        paths:
```
