### ISSUE TITLE
reference Chart.yaml appVersion from values file

### ISSUE THREAD

**Issue by nodesocket** [helm/helm#7578]
Is it possible to reference the **Chart.yaml** `appVersion` from a `values.yaml` file? I tried:

```
# values.yaml
global:
  env: default

default:
  IMAGE_TAG: {{ .Chart.AppVersion }}
```

But this breaks with:

```
helm upgrade api --values values/valyes.yaml ./
Error: failed to parse values/values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Chart.AppVersion":interface {}(nil)}
```
