### ISSUE TITLE
helm v3.1: dependencies are not stored in the Chart.yaml after exporting the chart

### ISSUE THREAD

**Issue by muecahit94** [helm/helm#7612]
Output of `helm version`: 
` version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}`

Hello, we have an issue with helm v3.1.  We use docker-registry to store our chart.
In our chart we have some dependencies in the Chart.yaml file, but if we pull and export the chart, then the dependencies are not stored in the Chart.yaml

It works fine with Helm v3.0.

exported the chart with helm v3.0, the Chart.yaml file:
```yaml
apiVersion: v1
appVersion: 2.3.2
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: ~9.2.2
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: ~6.8.3
- condition: mariadb.enabled
  name: mariadb
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: ~6.12.0
- condition: phpmyadmin.enabled
  name: phpmyadmin
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: ~4.1.1
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: https://helm.elastic.co/
  version: ~7.4
description: Description
home: https://git.ourcompany.com/application/helm-chart
keywords:
- keywords
maintainers:
- email: hostmaster@ourcompany.com
name: chartname
sources:
- registry.ourcompany.com/application/helm-chart
type: application
version: 0.1.0
```
export the chart with helm v3.1, the Chart.yaml file:
```yaml
apiVersion: v1
appVersion: 2.3.2
description: Description
home: https://git.ourcompany.com/application/helm-chart
keywords:
- keywords
maintainers:
- email: hostmaster@ourcompany.com
name: chartname
sources:
- registry.ourcompany.com/application/helm-chart
type: application
version: 0.1.0
```
