### ISSUE TITLE
Iterate over a range to create Network Policy rule using toyaml format

### ISSUE THREAD

**Issue by Mishra-Akash** [helm/helm#7614]
I need to create separate Network policy rules as per input from value.yaml. I need to iterate over rule using toyaml so N number of rules can be applied.  I tried few ways but no luck.

Any suggestion will be a great help; 

Values.yaml

```
ingress:
   rule1:
     ipblock:
        cidr: 172.61.216.0/23
     ports:
     - protocol: TCP
       port: 22
     - protocol: TCP
       port: 22
     

   rule2:
     ipblock:
        cidr: 172.62.216.0/23
     ports:
     - protocol: TCP
       port: 443
     - protocol: TCP
       port: 53
     - protocol: UDP
       port: 161
```

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"524294565799aba901a242fb7a12cef454c9cb10", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"524294565799aba901a242fb7a12cef454c9cb10", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:45:27Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:40:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Baremetal - 
NAME="SLES"
VERSION="15"
VERSION_ID="15"
PRETTY_NAME="SUSE Linux Enterprise Server 15"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15"

**Comment by bacongobbler** [comment]
Have you tried converting your values to a list of rules? e.g.

```
ingress:
  rules:
  - ipblock:
      cidr: 172.61.216.0/23
    ports:
    - protocol: TCP
      port: 22
    - protocol: TCP
      port: 22 
  - ipblock:
      cidr: 172.62.216.0/23
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 161
```

In your case, you should be able to achieve this with

```
{{ range $idx, $rule := .Values.ingress.rules }}
    {{ toYaml $rule }}
{{ end }}
```
