### ISSUE TITLE
"required" does not output an error message when running helm template or helm install, it just fails silently instead

### ISSUE THREAD

**Issue by Maistho** [helm/helm#7620]
I have an empty `values.yaml`, a single template file and a `Chart.yaml` file

```yaml
# My template file
apiVersion: v1
kind: namespace
metadata:
    name: {{ required "This is required" .Values.required }}
```

```yaml
# My Chart.yaml
apiVersion: v2
name: test
type: application
version: 0.1.0
```
My chart is named `test`.

When running `helm template test` I will get an empty line as output.
When running `helm install test --generate-name` I get an error:
```
Error: no objects visited
```
Only when running `helm lint test` will I get any useful errors:
```
engine.go:159: [INFO] Missing required value: This is required
==> Linting test
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

### Expected behaviour:
I expect to get more useful error messages when running `helm template` or `helm install`

### Versions:

Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Not relevant, but AWS EKS
