### ISSUE TITLE
Add support for a YAML concat tag/extension

### ISSUE THREAD

**Issue by depeele** [helm/helm#7647]
I would like to propose adding support for a YAML `concat` tag/extension to allow simple concatenation of YAML alias values.

For example, given a valid YAML `values.yaml` file like:
```yaml
server:
  host: &server_host test.com
  port: &server_port 1234

service1:
  host: *server_host
  port: *server_port

service2:
  endpoint: !concat [ *server_host, ":", *server_port ]

```

The final `values.yaml` file ingested by helm would become:
```yaml
server:
  host: test.com
  port: 1234

service1:
  host: test.com
  port: 1234

service2:
  endpoint: test.com:1234
```

This would enable minimal, YAML-compliant templating within a `values.yaml` file.
