### ISSUE TITLE
Kubernetes YAML not saved properly during install, but is correct in --dry-run and template tests

### ISSUE THREAD

**Issue by carlsoncoder** [helm/helm#7654]
Output of `helm version':
```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

I'm running into a strange issue.  I'm trying to deploy the elastic/elasticsearch chart using the elastic repo, which eventually leads here I believe:  https://github.com/elastic/helm-charts/tree/master/elasticsearch

I tried to run the following (note the "elasticsearch-helm-values.yml" is attached to this issue as a txt file):
`
helm install elastic-template elastic/elasticsearch --values elasticsearch-helm-values.yml
`

[elasticsearch-helm-values.txt](https://github.com/helm/helm/files/4237660/elasticsearch-helm-values.txt)

This seems to install without error, but eventually, all my pods fail to start, noting that they're unable to mount volumes on the pod.

If I go and look at the StatefulSet via kubectl and output it to YAML, I see something odd in the "volumes" section:

```
      volumes:
      - name: elastic-certificates
        secret:
          secretName: elastic-certificates
      - configMap:
          name: security-master-config
        name: esconfig
```

Something got flip-flopped here - this syntax is wrong and will mess up any pod trying to load up volumes.  What it SHOULD look like, is this (note difference in last three lines):

```
      volumes:
        - name: elastic-certificates
          secret:
            secretName: elastic-certificates
        - name: esconfig
          configMap:
            name: security-master-config
```

I tried some of the other options - the "template" command, as well as the install command with the "--dry-run" and "--debug" commands:

```
helm template elastic-template elastic/elasticsearch --values elasticsearch-helm-values.yml >> elastic-helm-output.yaml

helm install elastic-template elastic/elasticsearch --values elasticsearch-helm-values.yml --debug --dry-run
```

If I look at the output of either of those commands, specifically going again to the volumes section of the StatefulSet, I again see the correct data:

```
      volumes:
        - name: elastic-certificates
          secret:
            secretName: elastic-certificates
        - name: esconfig
          configMap:
            name: security-master-config
```

I wouldn't think this is a problem with the helm chart template itself (which I'm pretty sure is this one [here](https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/statefulset.yaml)), since it seems to generate properly in template and dry-run mode....it's just not sending the right data to kubernetes when it's actually creating the k8s resources I guess?  The debug command didn't really output any helpful data (except showing what it *thought* the k8s YAML should be).

Any thoughts on what's wrong here?  I'm not sure what else to check.

Thanks,
Justin
