### ISSUE TITLE
After configuring another helm repo, the caFile of the first repo is lost in /root/.config/helm/repositories.yaml

### ISSUE THREAD

**Issue by wuchuxiong** [helm/helm#7681]
I add a helm repo with helm repo add command. It worked perfectly. Then I add the second repo. And it worked correctly. Two repos are added. But while I check the detailed repo configurationn info in /root/.config/helm/repositories.yaml . I found caFile is lost of the first repo.

########Version Info#########
Output of `helm version`:
```
[root@myhost1 repository]# helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
```

Output of `kubectl version`:
```
[root@myhost1 repository]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

########Detailed steps and output#########
```
[root@myhost1 repository]# helm repo add --ca-file /opt/prod/ssl/de.crt firstrepo https://myhost1.cdf.net:5443/cdf/charts
"firstrepo" has been added to your repositories
[root@myhost1 repository]# cat /root/.config/helm/repositories.yaml 
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: /opt/prod/ssl/de.crt
  certFile: ""
  keyFile: ""
  name: firstrepo
  password: ""
  url: https://myhost1.cdf.net:5443/cdf/charts
  username: ""

[root@myhost1 repository]# helm repo add --ca-file /opt/prod2/ssl/ca.crt  secondrepo https://myhost2.cdf.net:5443/cdf/charts
"secondrepo" has been added to your repositories
[root@myhost1 repository]# cat /root/.config/helm/repositories.yaml
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  keyFile: ""
  name: firstrepo
  password: ""
  url: https://myhost1.cdf.net:5443/cdf/charts
  username: ""
- caFile: /opt/prod2/ssl/ca.crt
  certFile: ""
  keyFile: ""
  name: secondrepo
  password: ""
  url: https://myhost2.cdf.net:5443/cdf/charts
  username: ""
[root@myhost1 repository]#
```

_Note(mattfarina): edited to add code blocks for readability._
