### ISSUE TITLE
[hooks] Support `during-install/upgrade` hooks

### ISSUE THREAD

**Issue by sc250024** [helm/helm#7683]
# Description

I'm wondering if there is a desire for `during-install` and `during-upgrade` hooks. The use case is for sure an interesting one, and if people have solved this another way, I'd be happy to hear how this was done.

# Desired Outcome

As a result of what I mentioned above, I should be able to create a `Job` template like so:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    helm.sh/hook: during-install,during-upgrade
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
```

# Motivation / Use Case

My company has a Helm chart which installs our product; essentially it's a parent chart, which is made up of many dependencies and child charts, which contain the actual logic.

One of those dependencies is Kafka, which many other components depend on. The components that depend on Kafka have an `initContainer` which essentially does a `sleep` command until all Kafka brokers are ready.

We then have a `Job` template in the parent chart that currently ***only*** runs during the initial installation. It's essentially a script that runs the equivalent `kafka-topics.sh` command to create topics; the script has some internal logic to determine things like replication factor, number of partitions, etc. 

We now have a use case to not only run the script during installations, but now also during upgrades in case new Kafka topics should be created. The problem is that the current `pre-install` and `post-install` hooks will not work. This is why:

- ❌ For an installation, a `pre-install` hook will fail because the Kafka topic creation job depends on Kafka being already spun up.
- ❌ For an installation, a `post-install` hook will fail because the processes that need the Kafka topics to be present will never make it to a full `Running` state, and this hook will never be called.
- ✅ For an upgrade, a `pre-upgrade` hook would create the topic successfully. This is the only case that would work.
- ❌ For an upgrade, a `post-upgrade` hook will fail for the same reasons as a `post-install` hook: namely, the processes that depend on the new topic would never reach a `Running` state.

# Potential Workarounds

There are several that I have found:

- Use a Kafka Operator. This way, `KafkaTopic` CRDs can be configured as part of the deployment itself as a template. However, this is a bit heavier than simply including a Kafka chart like Bitnami's.
- Use a `Job` template that always runs, without any Helm hooks. We tried this, but unless you're using the [`ttlSecondsAfterFinished`](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) feature (and thus, have enabled the feature gate), this doesn't work. During an upgrade, we find that if the job is in a `Completed` state, and hasn't expired, Kubernetes will not create a new `Job` to re-run.
- Use `initContainers` to create the topics. While this could work, the problem is they will always re-run when the pod itself gets moved. While technically this works, it slows down a new deployment.

Output of `helm version`:

**Helm v3**:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Helm v2**:

```
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS EKS
