### ISSUE TITLE
helm upgrade --delta - keep everything and add only the delta

### ISSUE THREAD

**Issue by dpolicastro** [helm/helm#7689]
Hello, I'm trying to create a new deployment with a `metadata.name=app-2` to run alongside with the current revision's deployment (`metadata.name=app-1`), by creating a new revision to my release. I want to use the same templates, but different values:
![picture](https://user-images.githubusercontent.com/29067941/75406794-2850ca00-58f0-11ea-8912-9b5b4c52772e.png)

I have tried to make an upgrade while setting a new name for the deployment, but I notice it is still deleting the old one.

```yml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.version }}
  namespace: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ quote .Values.version }}
```
The goal for this experiment is to create a mechanism for blue/green deployment strategy, I want to keep both versions of the deployment running and then redirect the traffic when every pods are health, but I'm struggling to do that using helm. There is no such manner to make this happen? Can I keep old resources and only add the Delta?
