### ISSUE TITLE
gitlab cicd hostAliases

### ISSUE THREAD

**Issue by vamkaxifa** [helm/helm#7703]
Output of `helm version`:

```
root@7ae5d062ef80:/# helm version 
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

```

Output of `kubectl version`:
```
root@7ae5d062ef80:/# kubectl version 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:21:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Rancher

I am on gitlab CICD.  Using `helm install`, I  got gitlab runner run on Kubernetes cluster, but when 
I triggered CI Job on gitlab-ci, it end up with error :
```
Running with gitlab-runner 12.7.1 (003fe500)
  on gitlab-runner-lcy-gitlab-runner-5574f59d98-5wfml 29a75399
Using Kubernetes namespace: gitlab
Using Kubernetes executor with image docker:latest ...
Waiting for pod gitlab/runner-29a75399-project-1420-concurrent-0kw76p to be running, status is Pending
Waiting for pod gitlab/runner-29a75399-project-1420-concurrent-0kw76p to be running, status is Pending
Running on runner-29a75399-project-1420-concurrent-0kw76p via gitlab-runner-lcy-gitlab-runner-5574f59d98-5wfml...
Fetching changes...
Initialized empty Git repository in /builds/openImage/ec-java-image/.git/
Created fresh repository.
fatal: unable to access 'http://xx.xx-xx:8765/openImage/ec-java-image.git/': Could not resolve host: xx.xx-xx
ERROR: Job failed: command terminated with exit code 1
```

Here is my values.yaml:
```
## The GitLab Server URL (with protocol) that want to register the runner against
## ref: https://docs.gitlab.com/runner/commands/README.html#gitlab-runner-register
##
gitlabUrl: http://xx.xx-xx:8765

## The registration token for adding new Runners to the GitLab server. This must
## be retrieved from your GitLab instance.
## ref: https://docs.gitlab.com/ee/ci/runners/
##
runnerRegistrationToken: "XXXXXXXXXXXXX"

## Set the certsSecretName in order to pass custom certificates for GitLab Runner to use
## Provide resource name for a Kubernetes Secret Object in the same namespace,
## this is used to populate the /etc/gitlab-runner/certs directory
## ref: https://docs.gitlab.com/runner/configuration/tls-self-signed.html#supported-options-for-self-signed-certificates
##
#certsSecretName:

## Configure the maximum number of concurrent jobs
## ref: https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-global-section
##
concurrent: 50

## Defines in seconds how often to check GitLab for a new builds
## ref: https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-global-section
##
checkInterval: 30
hostNetwork: true

## For RBAC support:
rbac:
  create: false
  serviceAccountName: gitlab-pod
  ## Run the gitlab-bastion container with the ability to deploy/manage containers of jobs
  ## cluster-wide or only within namespace
  clusterWideAccess: false

  ## If RBAC is disabled in this Helm chart, use the following Kubernetes Service Account name.
  ##
  # serviceAccountName: default

## Configuration for the Pods that the runner launches for each new job
##
runners:
  ## Default container image to use for builds when none is specified
  ##
  image: centos:7

  tags: k8s-runner

  ## Run all containers with the privileged flag enabled
  ## This will allow the docker:stable-dind image to run if you need to run Docker
  ## commands. Please read the docs before turning this on:
  ## ref: https://docs.gitlab.com/runner/executors/kubernetes.html#using-docker-dind
  ##
  privileged: false

  ## Namespace to run Kubernetes jobs in (defaults to 'default')
  ##
  namespace: gitlab

  ## Build Container specific configuration
  ##
  builds:
    # cpuLimit: 200m
    # memoryLimit: 256Mi
    cpuRequests: 100m
    memoryRequests: 128Mi

  ## Service Container specific configuration
  ##
  services:
    # cpuLimit: 200m
    # memoryLimit: 256Mi
    cpuRequests: 100m
    memoryRequests: 128Mi

  ## Helper Container specific configuration
  ##
  helpers:
    # cpuLimit: 200m
    # memoryLimit: 256Mi
    cpuRequests: 100m
    memoryRequests: 128Mi

```

`echo "xx.xx.xx.xx    xx.xx-xx" >> /etc/hosts`,  Does `values.yaml` can cover this ?
