### ISSUE TITLE
Issues with `fromYaml`

### ISSUE THREAD

**Issue by paulbdavis** [helm/helm#7708]
Having an issue using `fromYaml`

The following happens in a chart that consists of a single file (`deployment.yaml` in this case)

```yaml
{{- fromYaml (include "test"  .) | default (dict ) -}}
{{- define "test" }}
metadata:
  name: foo  
{{- end }}
```

Running `helm lint` on this results in the error `[ERROR] templates/deployment.yaml: unable to parse YAML: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type rules.K8sYamlStruct` 

The chart correctly renders with the following instead, and appears to generate valid YAML.

```yaml
{{- include "test" . -}}
{{- define "test" }}
metadata:
  name: foo 
{{- end }}
```

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

**Comment by paulbdavis** [comment]
Doing some experimenting it seems this is the minimum required for `fromYaml` to work without error (for a deployment anyway)

```yaml
{{- fromYaml (include "test" .) -}}
{{- define "test" }}
spec:
  template:
    spec:
      containers:
      - name: common-test
        image: "nginx:"
{{- end }}
```

This also seems to work

```yaml
{{- fromYaml (include "test" .) -}}
{{- define "test" }}
spec:
  containers:
  - name: common-test
    image: "nginx:"
{{- end }}
```

The issue with this is that it does not allow a helper chart like common to generate a mainfest without providing at least one container in the template using it, meaning you cannot automate templating the image name.
