### ISSUE TITLE
Dependencies alias require the repo to be added

### ISSUE THREAD

**Issue by rocketspacer** [helm/helm#7710]
Output of `helm version`:            
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  **AWS EKS**

I use fully qualified url for my Chart dependencies.

This works fine when I do `helm dep build`
```yaml
# Chart.yaml
dependencies:
  - name: argo-cd
    version: 1.8.0
    repository: https://argoproj.github.io/argo-helm
```
![image](https://user-images.githubusercontent.com/17026876/75619480-3421e200-5bb7-11ea-8b25-795fd2ebb18c.png)

However, whenever I use **alias**, like:
```yaml
# Chart.yaml
dependencies:
  - name: argo-cd
    version: 1.8.0
    repository: https://argoproj.github.io/argo-helm
    alias: argocd
```
`helm dep build` then require the repo to be added.
![image](https://user-images.githubusercontent.com/17026876/75619386-1d2ec000-5bb6-11ea-804c-c03b789b6f6f.png)
