### ISSUE TITLE
[BUG]: Alias in subchart dependencies not respected

### ISSUE THREAD

**Issue by damienwebdev** [helm/helm#7729]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Any

Assume a chart setup for a chart below called `mychart`:

```txt
Chart.yaml
charts/
-- chart1
-- -- Chart.yaml
-- -- charts/
-- -- -- redis-10.5.5.tgz
```

And `mychart/charts/chart1/Chart.yaml`:

```yaml
...
dependencies:
  - name: redis
    alias: cache1
    version: 10.5.5
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: redis
    alias: cache2
    version: 10.5.5
    repository: https://kubernetes-charts.storage.googleapis.com
```

When you try to install `mychart` via:

```
helm install releasename mychart/
```

You will not get two redis deployments called "cache1" and "cache2" you will get a single redis deployment. The subchart aliases are entirely ignored.

This is a duplicate of many issues, but has yet to be addressed.

See:
https://github.com/helm/helm/issues/2993
https://github.com/helm/helm/issues/3457
https://github.com/helm/helm/issues/3909
https://github.com/helm/helm/issues/4300
https://github.com/helm/helm/issues/4390
https://github.com/helm/helm/issues/7061
https://github.com/helm/helm/issues/7093
https://github.com/helm/helm/issues/7413

This is a long-standing issue and prevents combinations of charts.

cc: @bacongobbler
