### ISSUE TITLE
 (.Files.Glob "conf/**" ).AsConfig render error when file with extend name properties

### ISSUE THREAD

**Issue by ghost** [helm/helm#7764]
the dir **conf** contains **a.yaml** and **a.properties**
```yaml
# configmaps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{.Values.fullnameOverride}}-config
data:
{{ (.Files.Glob "conf/**" ).AsConfig | indent 2 }}
````
run **helm template .**, I get  configmaps.yaml like this, but the files contains something
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: demo-ecloud-config
data:
```
If I delete **a.properties**, it is right.

Output of `helm version`:
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
