### ISSUE TITLE
Helm deploys subchart if it's not specified in `requirements.yaml`, but exists in `charts/` folder

### ISSUE THREAD

**Issue by korjek** [helm/helm#7770]
```
helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

```
To reproduce the issue please create umbrella chart that installs 2 different subcharts from `requirements.yaml`, like:
```
cat requirements.yaml
dependencies:
- alias: chart1
  name: heapster
  repository: '@stable'
- alias: chart2
  name: joomla
  repository: '@stable'
```
 and run `helm dep update && helm upgrade -i myrelease ./ -f values.yaml` to download subcharts to `charts/` folder. After that update `requirements.yaml` be removing a dependency for any subchart, like:
```
cat requirements.yaml
dependencies:
- alias: chart1
  name: heapster
  repository: '@stable'
```
and manually remove `joomla` related k8s deployment.
After `helm dep update && helm upgrade -i myrelease ./ -f values.yaml` joomla deployment will be created in k8s again (while it's not specified in `requirements.yaml` (`requirements.lock` file is up-to-date and contains only one subchart)

Workaround: manually clean up `charts/` folder before running `helm dep update`.
