### ISSUE TITLE
Chart.yaml `import-values` should import additional values files or manifests to be used by a dependency. (Umbrella chart feature)

### ISSUE THREAD

**Issue by oCroso** [helm/helm#7780]
## Problem

Import-values currently imports a subset of exported data from a child chart to be used by the master-chart/other charts in a dependency list (I believe based on the documentation language).  One of the big reasons I am proposing against this, is that the current use case is not easily utilized when dealing with remote community charts (or idempotent private repo'd charts), many times you do not have access to the child chart's values.yaml, to begin with, as you are pulling it from a repo (such as stable/grafana). 

From the docs for comparison of current functionality:

**Parent's Chart.yaml file:**
```
dependencies:
  - name: subchart
    repository: http://localhost:10191
    version: 0.1.0
    import-values:
      - data
```

**Child's values.yaml file:**
```
exports:
  data:
    myint: 99
```
## Proposed Solution

I am proposing this functionality change to facilitate a much more likely use case, and to support a function that matches its name a little more clearly.   What does happen, more often than not, is that you want to import your own additional values files specific for that chart (such as dashboards for grafana as an example, or additonal values files so that you aren't chunking thousands of variables into a single values.yaml). 

I am familiar with the way you can specify multiple values files at the command line, but sometimes this overwrites preceding values potentially in a way you do not want. Many other tools function this way, such as variables files in Ansible for example.  Currently the work around requires quite a bit of automation and assumptions to be made/configured within a helm runner, or in the case of our custom grafana configurations, a separate process altogether to pull in additional manifests.  Here is an example of what I am proposing:

**Directory:**
```
--ImaMasterChart/
----Chart.yaml
----dashboards/
------dashboard1.yaml
------dashboard2.yaml
----values.yaml
```
**Chart.yaml:**
```
apiVersion: v1
appVersion: "1.0"
description: A helm master chart
name: im-a-master-chart
version: 0.1.0

dependencies:
- name: nginx-ingress
  version: 1
  repository: stable

- name: grafana
  version: 1
  repository: stable
  import-values:
    - dashboards/dashboard1.yaml
    - dashboards/dashboard2.yaml
```

This would be a powerful addition to helm that would make using publicly available charts much more flexible, and drastically cut down on the tools and coding required to use Helm effectively in multi-environment, idempotent setups.

In the event this solution above is a little off, one could distinguish between manifests to execute during chart execution, and values to apply to the chart's values.  One could also see it functioning this way potentially:

**Directory:**
```
--ImaMasterChart/
----Chart.yaml
----dashboards/
------dashboard1.yaml
------dashboard2.yaml
----values.yaml
----nginx-values.yaml
```
**Chart.yaml:**
```
apiVersion: v1
appVersion: "1.0"
description: A helm master chart
name: im-a-master-chart
version: 0.1.0

dependencies:
- name: nginx-ingress
  version: 1
  repository: stable
  import:
    - values: nginx-values.yaml

- name: grafana
  version: 1
  repository: stable
  import:
    - manifest: dashboards/dashboard1.yaml
    - manifest: dashboards/dashboard2.yaml
```
