### ISSUE TITLE
Chart.yaml Master/Umbrella Chart dependencies should allow setting namespaces per dependency

### ISSUE THREAD

**Issue by oCroso** [helm/helm#7782]
## Problem

Currently there is no feasible way to set namespaces, per dependency, in a master chart.

## Proposed Solution

Add a feature to specify child chart specific namespaces.  This would make the master chart model much more useful for deploying "per environment" umbrella charts.

```
apiVersion: v1
appVersion: "1.0"
description: A helm master chart
name: im-a-master-chart
version: 0.1.0

dependencies:
- name: nginx
  version: 1
  repository: stable
  namespace: some-namespace

- name: grafana
  version: 1
  repository: stable
  namespace: some-other-namespace
```
