### ISSUE TITLE
Helm 'file://' directive does not package unbuilt dependent dependencies

### ISSUE THREAD

**Issue by cep21** [helm/helm#7821]
Output of `helm version`:
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

Bug:

I have one chart "company-datadog" with a dependency
```
dependencies:
- name: datadog
  repository: file://../datadog
  version: 2.0.14
```

Inside the directory `../datadog`/ I have another chart with another dependency
```
dependencies:
  - name: kube-state-metrics
    version: ~2.8.2
    repository: https://kubernetes-charts.storage.googleapis.com/
```

If I build `company-datadog` before building `datadog`, the dependency of `kube-state-metrics` is not in the final `*.tgz` created by `company-datadog`.  However, if I build `datadog` first, then the chart for `kube-state-metrics` is in the final chart.

The most surprising part of this is that I got no error messages when I tried to install the `company-datadog` chart.

Workaround:

Rearrange build order to build `datadog` before `company-datadog` (in my case, since things are alphabetical, I added a z to the name)
