### ISSUE TITLE
toyaml function more than basic example

### ISSUE THREAD

**Issue by bvandorf** [helm/helm#7822]
So I have been searching the internet with no luck for a more than a basic example of how to convert the settings like below that get run through the toyaml function of a template to a --set command line argument and how to directly put it in the values.yaml file so that the annotations tag comes out exactly the way the example says it needs to be formated.

Example:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: Test
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rate-limit: |
      extractorfunc: client.ip
      rateset:
        api-rateset:
          period: 60s
          average: 10
          burst: 20
spec:
```

with the defult ingress.yaml template 
```
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
```
