### ISSUE TITLE
Creating a secret in manifest where content is a file?

### ISSUE THREAD

**Issue by jamesla** [helm/helm#7824]
I can create a following secret from file like this quite easily:

```
kubectl create secret generic mySecret --from-file=mySecret.yaml=mySecret.yaml
```

Is it possible to do the same thing inline using a manifest something like this:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: testyaml
type: Opaque
data:
  test.yaml: |-
    ---
    yaml:
      my: testyaml | b64enc
```

Is this possible?

(Using helm secrets so will do this securely).
