### ISSUE TITLE
Helm test yaml does not work with .Chart values

### ISSUE THREAD

**Issue by bjayanth** [helm/helm#7858]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`:
 ```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): On-prem

I have test-connection.yaml as (for example):
```
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "fullname" . }}-test-connection"
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: curl
      image: curlimages/curl:7.69.1
      command: ["/bin/sh", "-c"]
      args: ["echo", "{{ .Chart.appVersion }}"]
  restartPolicy: Never
```
Running `helm lint` on this chart gives:
```
[ERROR] templates/: template: test-chart/templates/tests/test-connection.yaml:14:31: executing "test-chart/templates/tests/test-connection.yaml" at <.Chart.appVersion>: can't evaluate field appVersion in type interface {}

Error: 1 chart(s) linted, 1 chart(s) failed
```

This is the contents of the Chart.yaml:
```
apiVersion: v2
name: test-chart
description: A Helm chart for test-chart
type: application
version: 0.1.0
appVersion: 3.1.91
```

It seems like the test yaml file only has scope of `.Values` and `.Release`, but not `.Chart`.
Is this a bug or something I'm doing wrong?
