### ISSUE TITLE
Skip adding stable/incubator on init flag

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#7868]
In Helm v2 when `helm init` is run it adds the stable repo and an update happens. Even if you specify the tiller image. This is a problem for air gaped environments. They can specify a local tiller image but still have issues due to the upstream charts repo.

Since we are [extending the Helm v2 support window](https://helm.sh/blog/covid-19-extending-helm-v2-bug-fixes/) it may be worth adding a flag to `init` to skip trying to add the stable repo. 

Note, this was captured in the [CNCF Air Gapped Working Group](https://docs.google.com/document/d/1TLCvhy283FMNupQNxkfmQGjE2um2Pnl-piA_lTRsh9w/edit#heading=h.8ngolbigvi7q).

**Comment by technosophos** [comment]
I think that this is a necessary change in order to allow Helm2 users to continue using Helm when the Stable and Incubator repositories go away.

**Comment by hickeyma** [comment]
Sounds reasonable to me.

**Comment by rimusz** [comment]
why not just to remove of adding stable/incubator repos in helm v2 with `init`?
then document it as we have it for the helm v3?

**Comment by bacongobbler** [comment]
That’s would be a breaking change.

**Comment by rimusz** [comment]
the change will be needed sooner or later anyway :)

**Comment by bacongobbler** [comment]
Helm 2's support window will be closed by the time the stable chart repository is shut down, @rimusz. It will not be necessary to remove the stable repository from `helm init` during Helm 2's lifetime. That's why it'd be best as a feature flag so users can continue to use Helm 2 after the support window has closed.

Now normally, we have mentioned that we would not accept new features for the Helm 2 branch. However, this does seems like a necessary feature we need to get in before the stable repository is shut down. I'm less concerned about providing this to help support the air-gapped scenario given our current support window for Helm 2, but it certainly would help out in that regard.

Have there been any suggestions on a flag name from the Air Gapped WG? Perhaps `helm init --skip-repos`?

**Comment by rimusz** [comment]
then flag with a name `helm init --skip-repos` is needed for sure.

**Comment by mattfarina** [comment]
@bacongobbler `helm init --skip-repos` works for me. I can start dev on this.

**Comment by rjbez17** [comment]
For those waiting for this, this is the hack we've used internally to work around the issue. Run before `helm init`

```
# Make helm work without internet
# We need to make a dummy repository so helm init doesn't try to add
# an existing valid stable repo.
mkdir -p $HOME/.helm/repository/cache
mkdir -p $HOME/.helm/repository/local
mkdir -p $HOME/.helm/cache/archive

DATE=$(date +%F)
cat <<EOF > $HOME/.helm/repository/repositories.yaml
apiVersion: v1
generated: ${DATE}T12:00:00.111111-06:00
repositories:
- caFile: ""
  cache: /root/.helm/repository/cache/stable-index.yaml
  certFile: ""
  keyFile: ""
  name: stable
  password: ""
  url: localhost
  username: ""
EOF
# End hack
```
