### ISSUE TITLE
Use HELM behind proxy: support insecure repositories when charts get downloaded

### ISSUE THREAD

**Issue by TPX01** [helm/helm#7875]
### Version info
Output of **helm version**: v3 canary build 4/4/2020
Output of **kubectl version**: 1.16.2
Cloud Provider/**Platform** (AKS, GKE, Minikube etc.): Minishift

---

### Context
Recently support for insecure registries has been added:

- Initial ticket: https://github.com/helm/helm/issues/5434
- Pull request: https://github.com/helm/helm/pull/7254

Although adding the insecure registries works perfectly, we cannot pull/install/upgrade images due to TLS verification still being done.

### Configuration:
Helm 'repositories.yaml' configuration:
```
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: true
  keyFile: ""
  name: fluxcd
  password: ""
  url: https://<helm-repository>/repository/helm-fluxcd/
  username: ""
```

### Problem
When pulling the chart we get following error:
```
bamboo@app-bamboo-agent-5:~$ helm pull fluxcd/flux
Error: Get https://<helm-repository>/repository/helm-fluxcd/flux-1.3.0.tgz: x509: certificate signed by unknown authority
```
Just making sure by specyfing the repo directly:
```
bamboo@app-bamboo-agent-5:~$ helm pull fluxcd/flux --repo https://repo.crelan-int.be/repository/helm-fluxcd/
Error: looks like "https://<helm-repository>/repository/helm-fluxcd/" is not a valid chart repository or cannot be reached: Get https://<helm-repository>/repository/helm-fluxcd/index.yaml: x509: certificate signed by unknown authority
```
### Fix
Current `pull`, `install` and `upgrade` commands should keep into account that TLS verification is not required if the repository is marked as insecure.
