### ISSUE TITLE
Helm not deploying multiple resources in the same template

### ISSUE THREAD

**Issue by glueric** [helm/helm#7883]
Output of `helm version`:
helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`:
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-12-06T01:33:57Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

My deployment process relies on deploying multiple copies of my deployment, hpa, and service so that I can have blue/green deployments. I've tried to do this with helm by ranging my entire deployment under these sub-deployment names. Everything shows up perfectly in the manifest. However, when helm actually deploys the resources, it only deploys the very last resource from each template output.

```
# Source: assets-version/templates/hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: assets-scaler-v0-1-0-blue
  namespace: assets
  labels:
    helm.sh/chart: assets-version-1.2.0
    app.kubernetes.io/name: assets-version
    app.kubernetes.io/instance: assets-v0-1-0
    app.kubernetes.io/version: "0.2.3"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: assets-backend-v0-1-0-blue
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50



apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: assets-scaler-v0-1-0-green
  namespace: assets
  labels:
    helm.sh/chart: assets-version-1.2.0
    app.kubernetes.io/name: assets-version
    app.kubernetes.io/instance: assets-v0-1-0
    app.kubernetes.io/version: "0.2.3"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: assets-backend-v0-1-0-green
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
```
From this manifest output, only the last hpa is actually created. Obviously I need all the resources in the manifest to be deployed.

template:  (yes my chart is called 'version')
```
{{ $labels := include "version.labels" . }}
{{ range .Values.deployment.suffixes }}
{{ $deploymentSuffix := . }}
{{ $resourceSuffix := include "resourceSuffix" (dict "Values" $.Values "deploymentSuffix" $deploymentSuffix) }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Values.horizontalPodAutoscaler.name }}{{ $resourceSuffix }}
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- $labels | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Values.deployment.name }}{{ $resourceSuffix }}
{{- with $.Values.horizontalPodAutoscaler }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  targetCPUUtilizationPercentage: {{ .targetCPUUtilizationPercentage }}
{{- end }}
{{ end }}
```
values.yaml excerpt:
```
deployment:
  suffixes:
    - "blue"
    - "green"
```

Would appreciate any help on this, thanks!
