### ISSUE TITLE
Subcharts with clashing global values?

### ISSUE THREAD

**Issue by danrobdean** [helm/helm#7889]
Say I have two subcharts/dependencies with the following in their `values.yaml` files:
```yaml
global:
  image:
    repository: <repo address string>
```

How can I override each subchart with a different value for `global.image.repository`? It doesn't seem to be possible to set a global value for a specific subchart, unless I'm missing something.

The obvious workaround would be to use a hierarchy like:
```yaml
global:
  subchartA:
    image:
      repository: <repo address string A>
  subchartB:
    image:
      repository: <repo address string B>
```
This is a bit clunkier for passing values through the CLI though, and I don't see how this would work in the situation where both of those subcharts are external dependencies (so we would be unable to change the names/layouts of the clashing values).
