### ISSUE TITLE
"display name" in the index.yaml

### ISSUE THREAD

**Issue by sbose78** [helm/helm#7896]
Is there a way to add a displayName to the index.yaml ?

**Comment by bacongobbler** [comment]
Hi @sbose78. Can you elaborate more on your use case? I'm not sure what you mean by `displayName`.

**Comment by sbose78** [comment]
Thank you @bacongobbler !

I would like to display a user-friendly name in a UI rendered based on index.yaml
 
cc @waveywaves @pedjak @rohitkrai03 @morstad

**Comment by bacongobbler** [comment]
Thanks for clarifying more on your use case.

Can you describe why this cannot be accomplished at the UI level for your UI project? I'm having a tough time determining why a display name needs to be part of the chart index format. 

For most users, the "display name" is the name provided with `helm repo add`. Users can give the repository any name. For example,

```
$ helm repo add stable https://kubernetes-charts.storage.googleapis.com/
```

I could also use an alternative name, like the following:

```
$ helm repo add charts https://kubernetes-charts.storage.googleapis.com/
```

The idea being here that the "display name" is just a shorthand alias for the full repository URL, such that a user can reference charts in that repository based on the name provided. This was designed to prevent cases where two chart repositories might share the same display name (for example, if you forked the stable chart repository).

By providing a display name, that might cause name conflicts. For example, if I forked the stable charts repository and hosted it at https://example.com:

```
$ helm repo add https://kubernetes-charts.storage.googleapis.com/
$ helm repo add https://example.com
```

Both repositories would attempt to claim the display name `stable`, resulting in an exception.

If we were to consider this feature, how do we reconcile between the display name and the name provided on the command line? How do we handle name conflicts? Additionally, how do we handle backwards compatibility with chart repository indices with no display name?

**Comment by sbose78** [comment]
Thanks for explaining Mat!

I'm actually talking about the display name of the chart. As am example, the following chart has a `name` which is typically `my-chart-name` instead of a `My Business friendly chart name` :)

```
apiVersion: v1
entries:
  alpine:
  - created: 2016-11-18T15:05:51.078570269-07:00
    description: Deploy a basic Alpine Linux pod
    digest: f44f733d69008e86c3989d3b094a5e6151d168921a09eda61c0897472e2f0399
    home: https://k8s.io/helm
    name: alpine
    sources:
    - https://github.com/kubernetes/helm
    urls:
    - alpine-0.3.0.tgz
    version: 0.3.0
  - created: 2016-11-18T15:05:51.078096239-07:00
    description: Deploy a basic Alpine Linux pod
    digest: 99c76e403d752c84ead610644d4b1c2f2b453a74b921f422b9dcb8a7c8b559cd
    home: https://k8s.io/helm
    name: alpine
    sources:
    - https://github.com/kubernetes/helm
    urls:
    - alpine-0.2.0.tgz
    version: 0.2.0
```

I was thinking of introducing 

```
entries:
  alpine:
  - created: 2016-11-18T15:05:51.078570269-07:00
    displayName: "The Alpine" <------- This
    description: Deploy a basic Alpine Linux pod
    digest: f44f733d69008e86c3989d3b094a5e6151d168921a09eda61c0897472e2f0399
    home: https://k8s.io/helm
    name: alpine
    sources:
    - https://github.com/kubernetes/helm
    urls:
    - alpine-0.3.0.tgz
    version: 0.3.0
```

What do you think ?
