### ISSUE TITLE
With block skipped when value is zero

### ISSUE THREAD

**Issue by superstator** [helm/helm#7905]
When using a `with` block for a value of 0, the entire block is skipped. For example:

```
    {{ with .Values.deploymentId }}
    deployment: {{ . }}
    {{ end }}
```

If `deploymentId` is any value but 0, this outputs the expected value. If it is 0, it outputs nothing. 0 is a valid (and required) value, so how can I use `with` to scope a legitimate value of 0?

Output of `helm version`: `version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`

**Comment by waveywaves** [comment]
@superstator Have you tried setting the value for `.Values.deploymentId` as a string ? Are you setting it as an int currently ? And is there an if block doing a `{{ if .Values.deploymentId }} ` before this ? `if 0` would return false and it is possible that might be the reason.

If the above is not the case, can you share a chart as an example for this ?

**Comment by superstator** [comment]
If the value is a quoted string in the values.json, the `with` executes, but if I pipeline it back to an int it does not. Here's a slightly more involved example:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config
data:
  default.conf: |
    deployments:
    {{- range .Values.deployments }}
    - id: {{ .id }}
      host: {{ .host }}
      size: {{- with .id | int }}
        {{- if gt . 5 }} large
        {{- else }} smol
        {{- end }}
      {{- end }}
    {{- end }}
```

values.json:

```
deployments:
- id: 0
  host: somehost
- id: 3
  host: somehost
- id: 10
  host: someotherhost
```

Outputs:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config
data:
  default.conf: |
    deployments:
    - id: 0
      host: somehost
      size:
    - id: 3
      host: somehost
      size: smol
    - id: 10
      host: someotherhost
      size: large
```

Quoting the Id's in this case changes nothing.

Sample repo:

https://github.com/superstator/helmwith

This is ultimately related to this SO question/answer:

https://stackoverflow.com/questions/61161011/encode-integer-in-helm-template
