### ISSUE TITLE
dependencies enable flag not work as doc explain

### ISSUE THREAD

**Issue by kikicarbonell** [helm/helm#7908]
Output of `helm version`: 
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:Client Version: 
version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

We need install a chart with some dependencies and som time we need disable some dependendt charts....for example I have a chart definition like this:

```
apiVersion: v2
name: app-deployment
description: A Helm chart for deploying Technisys' microservices-based CDP solution
type: application
version: 1.0.0
appVersion: 3.0
dependencies:
  - name: appA
    version: 1.0.1
    repository: https://myrepo.azurecr.io/helm/v1/repo
    enabled: false
.....
```
But after apply command `helm upgrade` the helm try to deploy appA chart. How we can include declaration to avoid chart dependencies installation with enabled flag?
