### ISSUE TITLE
Helm 3 Upgrade Fails on Previous Invalid Chart

### ISSUE THREAD

**Issue by gsexton** [helm/helm#7933]
Output of `helm version`: 3.1.2

Output of `kubectl version`:2.14.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kubernetes on VMWare

Title: Helm 3 Upgrade Fails on Previous Invalid Chart

## Steps to Reproduce:

Using Helm 2 install a chart that contains a validation error. In my particular case, a StatefulSet definition where the volumeClaimTemplate is invalid. The example shown contains a reclaimPolicy which is not valid on the API for a Pod Template Spec.

```
  volumeClaimTemplates:
  - metadata:
      name: logelasticsearch
    spec:
      accessModes:
      - ReadWriteOnce
      reclaimPolicy: Delete
      resources:
        requests:
          storage: 35Gi
      storageClassName: es-sc-deletepolicy
```

I've fixed the chart by removing the reclaim policy from the StatefulSet's volumeClaimTemplate.Spec.

## Observed Behavior

When I try to install the updated chart a validation error is thrown:

```
 helm upgrade common-services /opt/avaya/flex/clusters/default/staging/common-services-1.1.89766/common-services --namespace default --values /opt/avaya/flex/clusters/default/workdir/flex-upgrade-vwjlxkkz/framework.yaml --reuse-values

Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(StatefulSet.spec.volumeClaimTemplates[0].spec): unknown field "reclaimPolicy" in io.k8s.api.core.v1.PersistentVolumeClaimSpec
[11925 14976 :008306: nftcx 04/15/2020 22:10:01 -0600 ERROR   ]    
```        

## Expected Behavior
If the new chart is valid, it should be installed.

## Additional Comments
Can any point me to a work-around or way to get around this? I did try dumping the StatefulSet to a yaml file, verified that it doesn't contain the invalid reclaimPolicy, and then applied it using kubectl apply -f file.yaml, but the error remained.

Thanks!

George

**Comment by bacongobbler** [comment]
As I understand it, PersistentVolumes may contain reclaim policies, but not PersistentVolumeClaims.

https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims

If you remove the reclaim policy from your template, what happens?

**Comment by gsexton** [comment]
@bacongobbler I don't think the issue is kubernetes. I did a kubectl get StatefulSet, and verified the reclaimPolicy isn't in the running version. I've also verified it's not in the current chart. Could this be an outcome of the three-way merge?

**Comment by bacongobbler** [comment]
In your template you pasted above, I see a `reclaimPolicy: Delete`.

**Comment by gsexton** [comment]
@bacongobbler Sorry, I'm not being clear enough. Let me start over. In the original helm chart deployed by Helm 2 there was:

```
  volumeClaimTemplates:
  - metadata:
      name: logelasticsearch
    spec:
      accessModes:
      - ReadWriteOnce
      reclaimPolicy: Delete
      resources:
        requests:
          storage: 35Gi
      storageClassName: es-sc-deletepolicy
```
I know this was invalid. 

The current running state returned by kubectl get statefulset is:

```
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: logelasticsearch
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 35Gi
      storageClassName: es-sc-deletepolicy
      volumeMode: Filesystem
    status:
      phase: Pending
```
In the new chart which I'm attempting to upgrade using Helm 3, the definition is:
```
  volumeClaimTemplates:
  - metadata:
      name: logelasticsearch
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 35Gi
      storageClassName: es-sc-deletepolicy
```
So, I fully understand the original chart was invalid. However, it doesn't show the invalid part when I look at it using Kubectl, and the new chart is valid. So it looks to me like there's something being retained/dragged in from somewhere.
