### ISSUE TITLE
Broken `ports` update with multiple same number ports

### ISSUE THREAD

**Issue by bozaro** [helm/helm#7957]
# Issue summary
I created simple chart with ports from values (show only related part, link to full file below):
```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: "nginx"
          ports:
            {{- .Values.ports | toYaml | nindent 12 }}
```
And install this chart to minicube with values:
```
ports:
- name: http
  containerPort: 80
  protocol: TCP
- name: grpc-look-aside
  containerPort: 8080
  hostPort: 34567
  protocol: TCP
- name: grpc-service
  containerPort: 8080
  protocol: TCP
```
As expected I got pod with 3 ports (`http`, `grpc-look-aside`, `grpc-service`).

After that I upgrade chart with values (remove `grpc-look-aside` port):
```
ports:
- name: http
  containerPort: 80
  protocol: TCP
- name: grpc-service
  containerPort: 8080
  protocol: TCP
```

As result deployment became to unexpected state: all 8080 ports was removed.

I expected:
```
[
  {
    "containerPort": 80,
    "name": "http",
    "protocol": "TCP"
  },
  {
    "containerPort": 8080,
    "name": "grpc-service",
    "protocol": "TCP"
  }
]
```
but actual port specification was:
```
[
  {
    "containerPort": 80,
    "name": "http",
    "protocol": "TCP"
  }
]
```

# How to reproduce
I created minimal chart with reproducing script: https://github.com/bozaro/helm-ports-issue

 1. checkout
 2. `pip install yq`
 3. `./ports.sh`

# Versions
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
version.BuildInfo{Version:"v3.2.0-rc.1", GitCommit:"7bffac813db894e06d17bac91d14ea819b5c2310", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-14T16:45:05Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
```
