### ISSUE TITLE
Render helm subtemplate in addition to parent

### ISSUE THREAD

**Issue by VihanAgarwal97** [helm/helm#7961]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:17:09Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

I have the following format in one of my charts - 

`template1.yaml` - 
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: logging
data:
  config.yaml: |-
  {{- include "alertmanager.configs" . | indent 4 }}
```
and `template2.yaml` - 
```
{{ define "alertmanager.configs" }}
  someConfigs:
{{ end }}
```
When I run `helm template` everything works correctly and outputs a new `template1.yaml` in the output dir. How do I get `helm template` to also render the sub-template `template2.yaml` in the same dir? Is there a way to output it to a different dir?

Thanks!

**Comment by bacongobbler** [comment]
Hi @VihanAgarwal97. I'm not quite sure I understand the issue.

1. Can you please try with a more recent version of Helm 2? v2.16.5 is the most recent version. Please check and confirm this behaviour still exists there first.
2. Please provide a set of instructions to reproduce the problem you are experiencing. I'm not sure what you mean by "When I run helm template everything works correctly and outputs a new template1.yaml in the output dir". Without a set of steps to reproduce your issue, I cannot tell if you are referring to `helm template --output-dir` or some other setup.

Thanks.

**Comment by VihanAgarwal97** [comment]
Here is my `config.yaml` -
```
{{ define "alertmanager.configs" }}
global:
  resolve_timeout: 5m
{{ end }}
```

Here is my `configmap.yaml` - 
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: logging
data:
  config.yml: |-
  {{- include "alertmanager.configs" . | indent 4 }}
```

When I run the following command
```
helm template deploy/helm -n test-chart -f deploy/vars/alertmanager.config.values.yaml --output-dir "$workDir"
```
I check $workDir and I can see that `configmap.yaml` has been rendered there. However, I don't see `config.yaml` in the directory. It seems as though helm is rendering `config.yaml` into `configmap.yaml` but it doesn't save `config.yaml` 

I hope this clarifies things...
