### ISSUE TITLE
Wrong error message in `helm dep update/build`

### ISSUE THREAD

**Issue by vkropotko** [helm/helm#7990]
Output of `helm version`:
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}

Chart.yaml:
```
apiVersion: v1
appVersion: "1.0"
description: A Helm chart
name: my-chart
version: 0.1.0
dependencies:
- condition: mydep.enabled
  name: mydep
  version: 0.0.1
  repository: https://example.charts.com/
  ```

In case of Helm can not access `$HOME`, when I run `helm dep update my-chart` I receive next error:
```
Save error occurred:  could not find : chart mydep not found in https://example.charts.com/
Deleting newly downloaded charts, restoring pre-update state
Error: could not find : chart mydep not found in https://example.charts.com/
```
But it starts to work with  `HOME=/tmp helm dep update my-chart`
Looks like CLI needs additional checks for access to `.config`, `.cache` under home directory.
