### ISSUE TITLE
 spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

### ISSUE THREAD

**Issue by willzhang** [helm/helm#7998]
Output of `helm version`:
```
[root@master01 ~]# helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
Output of `kubectl version`:
```
[root@master01 ~]# kubectl version --short
Client Version: v1.18.1
Server Version: v1.18.1
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
barametal
```

## what happend
```
[root@master01 ~]# helm upgrade mysql apphub/mysql --set root.password=$ROOT_PASSWORD       
Error: UPGRADE FAILED: cannot patch "mysql-master" with kind StatefulSet: StatefulSet.apps "mysql-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden && cannot patch "mysql-slave" with kind StatefulSet: StatefulSet.apps "mysql-slave" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

## how to reproduct it
```
helm install mysql \
  --set root.password=Mysql123 \
  --set db.name=testdb \
  --set db.user=test \
  --set db.password=test123 \
  --set global.storageClass=openebs-jiva-default \
  --set slave.replicas=2 \
  --set service.type=NodePort \
  apphub/mysql
```

why can't i upgrade msyql release use helm?

**Comment by qingguee** [comment]
StatefulSet does not allow to change thing outside 'replicas', 'template', and 'updateStrategy' . 
So have you change anything which not belong/under above?

**Comment by omkensey** [comment]
I would say this might be the easiest way to troubleshoot:

1. Install a new mysql release as above but first using `helm install --dry-run --debug` to save the manifest to a file -- then do the real install without `--dry-run --debug`.
2. Then try to do the upgrade as above, with `--dry-run --debug` and save to a file.
3. Diff the two files to see what might have changed that isn't allowed to change in a StatefulSet.

**Comment by technosophos** [comment]
To be clear, this restriction is from Kubernetes itself, not Helm. So you can read the Kubernetes documentation on StatefulSet if you would like to learn more about why this is the case.

**Comment by bridgetkromhout** [comment]
Hi, @willzhang - as mentioned above, Kubernetes restricts the updates for StatefulSet. You can read more here: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets

Resolving as this is not a behavior Helm can change.

**Comment by tdyas** [comment]
StatefulSets supports rolling updates though? Why doesn't Helm trigger a rolling update as per the Kubernetes docs at https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#rolling-update?

**Comment by mamiu** [comment]
@qingguee @technosophos @bridgetkromhout 

It does indeed seem to be a bug.

I use the [official Jaeger Helm Chart](https://github.com/jaegertracing/helm-charts/tree/master/charts/jaeger), which has [Cassandra](https://github.com/helm/charts/tree/master/incubator/cassandra) as a [dependency](https://github.com/jaegertracing/helm-charts/blob/master/charts/jaeger/requirements.yaml#L2).

If I try to change the [`replicas` value of Cassandra's StatefulSet](https://github.com/helm/charts/blob/master/incubator/cassandra/templates/statefulset.yaml#L16) (which is set via the `{{ .Values.config.cluster_size }}` variable and is used only once in the StatefulSet) by upgrading the Jaeger Helm chart like so...

```bash
helm upgrade jaeger jaegertracing/jaeger --set "cassandra.config.cluster_size=0"
```

... I'm also getting this error message:

```
Error: UPGRADE FAILED: cannot patch "jaeger-cassandra" with kind StatefulSet: StatefulSet.apps "jaeger-cassandra" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

Even though, the output of `--dry-run` and `--debug` (suggested by @omkensey) is printing the expected result:

```yaml
...
# Source: jaeger/charts/cassandra/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jaeger-cassandra
  labels:
    app: cassandra
    chart: cassandra-0.15.2
    release: jaeger
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: cassandra
      release: jaeger
  serviceName: jaeger-cassandra
  replicas: 0
  podManagementPolicy: OrderedReady
...
```

As you can see the `replicas` value is set to `0` as defined in the helm command above.

Am I missing something?

**Comment by Ferlonas** [comment]
I use a statefulset for deploying keydb as part of my chart. I have bumped the chart version, and the upgrade will fail with the aforementioned error. Reason for this is here:

```
    volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          app.kubernetes.io/name: redis
          app.kubernetes.io/component: cache
          app.kubernetes.io/part-of: user
          app.kubernetes.io/instance: user
-         helm.sh/chart: user-0.1.0
+         helm.sh/chart: user-0.1.1
```

It seems to me the easiest way of solving this would be to not add the chart to the volumeClaimTemplates, but I don't know if it's the correct one.
@bridgetkromhout I'm aware that the basic issue lies with kubernetes, but as the chart version is added by helm's library, is this helm-specific enough to consider it an issue?

Regards
