### ISSUE TITLE
"failed to create patch: The order in patch list" when helm upgrade using --force

### ISSUE THREAD

**Issue by liuming-dev** [helm/helm#7999]
Output of `helm version`:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

**Situation**
part of deployment yaml
```yaml
      hostAliases:
      - hostnames:
        - cpc0101.mongodb
        ip: 10.153.44.147
      - hostnames:
        - cpc0102.mongodb
        ip: 10.153.52.224
      - hostnames:
        - cpc0103.mongodb
        ip: 10.153.53.139
      - hostnames:
        - cpc0201.mongodb
        ip: 10.153.52.63
      - hostnames:
        - cpc0202.mongodb
        ip: 10.153.58.52
      - hostnames:
        - cpc0203.mongodb
        ip: 10.153.60.75
      - hostnames:
        - cpc0301.mongodb
        ip: 10.144.122.209
      - hostnames:
        - cpc0302.mongodb
        ip: 10.144.125.225
      - hostnames:
        - cpc0303.mongodb
        ip: 10.144.126.191
      - hostnames:
        - cpcrank0101.mongodb
        ip: 10.153.52.61
      - hostnames:
        - cpcrank0102.mongodb
        ip: 10.142.69.176
      - hostnames:
        - cpcrank0103.mongodb
        ip: 10.153.52.62
      - hostnames:
        - cpcrank0201.mongodb
        ip: 10.144.97.235
      - hostnames:
        - cpcrank0202.mongodb
        ip: 10.142.32.128
      - hostnames:
        - cpcrank0203.mongodb
        ip: 10.134.107.236
      - hostnames:
        - cpcrank0301.mongodb
        ip: 10.144.126.213
      - hostnames:
        - cpcrank0302.mongodb
        ip: 10.144.127.168
      - hostnames:
        - cpcrank0303.mongodb
        ip: 10.152.99.208
      - hostnames:
        - dev.kafka.broker1
        ip: 10.134.55.168
      - hostnames:
        - dev.kafka.broker2
        ip: 10.134.73.192
      - hostnames:
        - dev.kafka.broker3
        ip: 10.134.73.196
      - hostnames:
        - download.ceph.com
        ip: 158.69.68.124
      - hostnames:
        - galaxywirelesslog01.mongodb
        ip: 10.144.122.209
      - hostnames:
        - galaxywirelesslog02.mongodb
        ip: 10.144.125.225
      - hostnames:
        - galaxywirelesslog03.mongodb
        ip: 10.144.126.191
      - hostnames:
        - hourreport0101.mongodb
        ip: 10.144.126.213
      - hostnames:
        - hourreport0102.mongodb
        ip: 10.144.127.168
      - hostnames:
        - hourreport0103.mongodb
        ip: 10.152.99.208
      - hostnames:
        - hourreport0201.mongodb
        ip: 10.144.14.227
      - hostnames:
        - hourreport0202.mongodb
        ip: 10.152.100.136
      - hostnames:
        - hourreport0203.mongodb
        ip: 10.152.105.194
      - hostnames:
        - hourreport0301.mongodb
        ip: 10.134.97.208
      - hostnames:
        - hourreport0302.mongodb
        ip: 10.134.110.147
      - hostnames:
        - hourreport0303.mongodb
        ip: 10.142.79.219
      - hostnames:
        - idea0101.mongodb
        ip: 10.153.44.147
      - hostnames:
        - idea0102.mongodb
        ip: 10.153.52.224
      - hostnames:
        - idea0103.mongodb
        ip: 10.153.53.139
      - hostnames:
        - idea0201.mongodb
        ip: 10.153.52.63
      - hostnames:
        - idea0202.mongodb
        ip: 10.153.58.52
      - hostnames:
        - idea0203.mongodb
        ip: 10.153.60.75
      - hostnames:
        - idea0301.mongodb
        ip: 10.144.122.209
      - hostnames:
        - idea0302.mongodb
        ip: 10.144.125.225
      - hostnames:
        - idea0303.mongodb
        ip: 10.144.126.191
      - hostnames:
        - kafka.broker1
        ip: 10.142.115.37
      - hostnames:
        - kafka.broker2
        ip: 10.142.112.29
      - hostnames:
        - kafka.broker3
        ip: 10.152.58.89
      - hostnames:
        - kuaitoureport01.mongodb
        ip: 10.153.52.191
      - hostnames:
        - kuaitoureport02.mongodb
        ip: 10.153.54.239
      - hostnames:
        - kuaitoureport03.mongodb
        ip: 10.153.61.232
      - hostnames:
        - noclickcpc0101.mongodb
        ip: 10.153.44.147
      - hostnames:
        - noclickcpc0102.mongodb
        ip: 10.153.52.224
      - hostnames:
        - noclickcpc0103.mongodb
        ip: 10.153.53.139
      - hostnames:
        - noclickcpc0201.mongodb
        ip: 10.153.52.63
      - hostnames:
        - noclickcpc0202.mongodb
        ip: 10.153.58.52
      - hostnames:
        - noclickcpc0203.mongodb
        ip: 10.153.60.75
      - hostnames:
        - noclickcpc0301.mongodb
        ip: 10.144.122.209
      - hostnames:
        - noclickcpc0302.mongodb
        ip: 10.144.125.225
      - hostnames:
        - noclickcpc0303.mongodb
        ip: 10.144.126.191
      - hostnames:
        - qa.bizlog0101.mongodb
        ip: 10.134.97.208
      - hostnames:
        - qa.bizlog0102.mongodb
        ip: 10.142.79.219
      - hostnames:
        - qa.bizlog0103.mongodb
        ip: 10.134.110.147
      - hostnames:
        - qa.bizlog0201.mongodb
        ip: 10.134.97.208
      - hostnames:
        - qa.bizlog0202.mongodb
        ip: 10.142.79.219
      - hostnames:
        - qa.bizlog0203.mongodb
        ip: 10.134.110.147
      - hostnames:
        - qa.bizlog0301.mongodb
        ip: 10.144.14.227
      - hostnames:
        - qa.bizlog0302.mongodb
        ip: 10.152.100.136
      - hostnames:
        - qa.bizlog0303.mongodb
        ip: 10.152.105.194
      - hostnames:
        - qa.bizlog0401.mongodb
        ip: 10.144.14.227
      - hostnames:
        - qa.bizlog0402.mongodb
        ip: 10.152.100.136
      - hostnames:
        - qa.bizlog0403.mongodb
        ip: 10.152.105.194
      - hostnames:
        - qa.bizlog0501.mongodb
        ip: 10.144.14.227
      - hostnames:
        - qa.bizlog0502.mongodb
        ip: 10.152.100.136
      - hostnames:
        - qa.bizlog0503.mongodb
        ip: 10.152.105.194
      - hostnames:
        - qa.bizlog0601.mongodb
        ip: 10.144.14.227
      - hostnames:
        - qa.bizlog0602.mongodb
        ip: 10.152.100.136
      - hostnames:
        - qa.bizlog0603.mongodb
        ip: 10.152.105.194
      - hostnames:
        - qa.iflow01.mongodb
        ip: 10.134.109.215
      - hostnames:
        - qa.iflow02.mongodb
        ip: 10.134.110.238
      - hostnames:
        - qa.iflow03.mongodb
        ip: 10.134.115.189
      - hostnames:
        - qa.memcache1.dubhe
        ip: 10.153.57.225
      - hostnames:
        - qa.memcache2.dubhe
        ip: 10.153.57.229
      - hostnames:
        - qa.memcache3.dubhe
        ip: 10.153.60.164
      - hostnames:
        - qa.scxbigquery.mysql
        ip: 10.152.70.220
      - hostnames:
        - querykey0101.mongodb
        ip: 10.153.52.61
      - hostnames:
        - querykey0102.mongodb
        ip: 10.153.52.62
      - hostnames:
        - querykey0103.mongodb
        ip: 10.153.52.63
      - hostnames:
        - querykey0201.mongodb
        ip: 10.144.97.235
      - hostnames:
        - querykey0202.mongodb
        ip: 10.142.32.128
      - hostnames:
        - querykey0203.mongodb
        ip: 10.134.107.236
      - hostnames:
        - querykey0301.mongodb
        ip: 10.144.126.213
      - hostnames:
        - querykey0302.mongodb
        ip: 10.144.127.168
      - hostnames:
        - querykey0303.mongodb
        ip: 10.152.99.208
      - hostnames:
        - regionreport0101.mongodb
        ip: 10.144.126.213
      - hostnames:
        - regionreport0102.mongodb
        ip: 10.144.127.168
      - hostnames:
        - regionreport0103.mongodb
        ip: 10.152.99.208
      - hostnames:
        - regionreport0201.mongodb
        ip: 10.144.14.227
      - hostnames:
        - regionreport0202.mongodb
        ip: 10.152.100.136
      - hostnames:
        - regionreport0203.mongodb
        ip: 10.152.105.194
      - hostnames:
        - regionreport0301.mongodb
        ip: 10.134.97.208
      - hostnames:
        - regionreport0302.mongodb
        ip: 10.134.110.147
      - hostnames:
        - regionreport0303.mongodb
        ip: 10.142.79.219
      - hostnames:
        - xuridailyspend01.mongodb
        ip: 10.144.103.130
      - hostnames:
        - xuridailyspend02.mongodb
        ip: 10.144.99.237
      - hostnames:
        - xuridailyspend03.mongodb
        ip: 10.144.119.212
      - hostnames:
        - xuriopt01.mongodb
        ip: 10.148.35.161
      - hostnames:
        - xuriopt02.mongodb
        ip: 10.148.38.193
      - hostnames:
        - xuriopt03.mongodb
        ip: 10.148.33.147
      - hostnames:
        - xurispend01.mongodb
        ip: 10.144.103.130
      - hostnames:
        - xurispend02.mongodb
        ip: 10.144.99.237
      - hostnames:
        - xurispend03.mongodb
        ip: 10.144.119.212
```

there are duplicated ips in `hostAliases`, and use `helper.Replace(target.Namespace, target.Name, true, target.Object)` to deploy, everything goes well.

when switching to helm, use `helm upgrade` with the default values, error is returned `failed to create patch: The order in patch list: ...`

```
~/.kube » helm history janus-fe --kubeconfig ./pre -n bizqa                                                                apple@liuming216448
REVISION	UPDATED                 	STATUS    	CHART                  	APP VERSION	DESCRIPTION
1       	Tue Apr 21 21:31:22 2020	superseded	thanos-deployment-1.0.0	1.16.0     	Install complete
2       	Sun Apr 26 15:57:09 2020	failed    	thanos-deployment-1.0.0	1.16.0     	Upgrade "janus-fe" failed: failed to create patch: The order in patch list:
        	                        	          	                       	           	[map[hostnames:[cpc0101.mongodb] ip:10.153.44.147] map[hostnames:[noclickcpc0101.mongodb] ip:10.153.44.147] map[hostnames:[idea0201.mongodb] ip:10.153.52.63] map[hostnames:[cpc0201.mongodb] ip:10.153.52.63] map[hostnames:[querykey0103.mongodb] ip:10.153.52.63] map[hostnames:[noclickcpc0201.mongodb] ip:10.153.52.63] map[hostnames:[noclickcpc0202.mongodb] ip:10.153.58.52] map[hostnames:[idea0202.mongodb] ip:10.153.58.52] map[hostnames:[noclickcpc0203.mongodb] ip:10.153.60.75] map[hostnames:[cpc0203.mongodb] ip:10.153.60.75] map[hostnames:[idea0203.mongodb] ip:10.153.60.75] map[hostnames:[cpc0301.mongodb] ip:10.144.122.209] map[hostnames:[idea0301.mongodb] ip:10.144.122.209] map[hostnames:[galaxywirelesslog02.mongodb] ip:10.144.125.225] map[hostnames:[cpc0302.mongodb] ip:10.144.125.225] map[hostnames:[galaxywirelesslog03.mongodb] ip:10.144.126.191] map[hostnames:[cpc0303.mongodb] ip:10.144.126.191] map[hostnames:[cpcrank0103.mongodb] ip:10.153.52.62] map[hostnames:[querykey0102.mongodb] ip:10.153.52.62] map[hostnames:[cpcrank0201.mongodb] ip:10.144.97.235] map[hostnames:[querykey0201.mongodb] ip:10.144.97.235] map[hostnames:[querykey0301.mongodb] ip:10.144.126.213] map[hostnames:[hourreport0101.mongodb] ip:10.144.126.213] map[hostnames:[regionreport0101.mongodb] ip:10.144.126.213] map[hostnames:[querykey0302.mongodb] ip:10.144.127.168] map[hostnames:[regionreport0102.mongodb] ip:10.144.127.168] map[hostnames:[querykey0303.mongodb] ip:10.152.99.208] map[hostnames:[regionreport0103.mongodb] ip:10.152.99.208] map[hostnames:[hourreport0103.mongodb] ip:10.152.99.208] map[hostnames:[cpcrank0303.mongodb] ip:10.152.99.208] map[hostnames:[qa.bizlog0401.mongodb] ip:10.144.14.227] map[hostnames:[regionreport0201.mongodb] ip:10.144.14.227] map[hostnames:[qa.bizlog0601.mongodb] ip:10.144.14.227] map[hostnames:[hourreport0201.mongodb] ip:10.144.14.227] map[hostnames:[regionreport0202.mongodb] ip:10.152.100.136] map[hostnames:[hourreport0202.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0302.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0602.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0402.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0502.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0303.mongodb] ip:10.152.105.194] map[hostnames:[regionreport0203.mongodb] ip:10.152.105.194] map[hostnames:[qa.bizlog0603.mongodb] ip:10.152.105.194] map[hostnames:[qa.bizlog0503.mongodb] ip:10.152.105.194] map[hostnames:[hourreport0203.mongodb] ip:10.152.105.194] map[hostnames:[qa.bizlog0403.mongodb] ip:10.152.105.194] map[hostnames:[regionreport0301.mongodb] ip:10.134.97.208] map[hostnames:[qa.bizlog0201.mongodb] ip:10.134.97.208] map[hostnames:[hourreport0301.mongodb] ip:10.134.97.208] map[hostnames:[qa.bizlog0203.mongodb] ip:10.134.110.147] map[hostnames:[regionreport0302.mongodb] ip:10.134.110.147] map[hostnames:[regionreport0303.mongodb] ip:10.142.79.219] map[hostnames:[qa.bizlog0102.mongodb] ip:10.142.79.219] map[hostnames:[hourreport0303.mongodb] ip:10.142.79.219] map[hostnames:[xurispend01.mongodb] ip:10.144.103.130] map[hostnames:[xuridailyspend01.mongodb] ip:10.144.103.130] map[hostnames:[xuridailyspend02.mon...
3       	Sun Apr 26 15:58:39 2020	failed    	thanos-deployment-1.0.0	1.16.0     	Upgrade "janus-fe" failed: failed to create patch: The order in patch list:
        	                        	          	                       	           	[map[hostnames:[cpc0101.mongodb] ip:10.153.44.147] map[hostnames:[noclickcpc0101.mongodb] ip:10.153.44.147] map[hostnames:[idea0201.mongodb] ip:10.153.52.63] map[hostnames:[cpc0201.mongodb] ip:10.153.52.63] map[hostnames:[querykey0103.mongodb] ip:10.153.52.63] map[hostnames:[noclickcpc0201.mongodb] ip:10.153.52.63] map[hostnames:[noclickcpc0202.mongodb] ip:10.153.58.52] map[hostnames:[idea0202.mongodb] ip:10.153.58.52] map[hostnames:[noclickcpc0203.mongodb] ip:10.153.60.75] map[hostnames:[cpc0203.mongodb] ip:10.153.60.75] map[hostnames:[idea0203.mongodb] ip:10.153.60.75] map[hostnames:[cpc0301.mongodb] ip:10.144.122.209] map[hostnames:[idea0301.mongodb] ip:10.144.122.209] map[hostnames:[galaxywirelesslog02.mongodb] ip:10.144.125.225] map[hostnames:[cpc0302.mongodb] ip:10.144.125.225] map[hostnames:[galaxywirelesslog03.mongodb] ip:10.144.126.191] map[hostnames:[cpc0303.mongodb] ip:10.144.126.191] map[hostnames:[cpcrank0103.mongodb] ip:10.153.52.62] map[hostnames:[querykey0102.mongodb] ip:10.153.52.62] map[hostnames:[cpcrank0201.mongodb] ip:10.144.97.235] map[hostnames:[querykey0201.mongodb] ip:10.144.97.235] map[hostnames:[querykey0301.mongodb] ip:10.144.126.213] map[hostnames:[hourreport0101.mongodb] ip:10.144.126.213] map[hostnames:[regionreport0101.mongodb] ip:10.144.126.213] map[hostnames:[querykey0302.mongodb] ip:10.144.127.168] map[hostnames:[regionreport0102.mongodb] ip:10.144.127.168] map[hostnames:[querykey0303.mongodb] ip:10.152.99.208] map[hostnames:[regionreport0103.mongodb] ip:10.152.99.208] map[hostnames:[hourreport0103.mongodb] ip:10.152.99.208] map[hostnames:[cpcrank0303.mongodb] ip:10.152.99.208] map[hostnames:[qa.bizlog0401.mongodb] ip:10.144.14.227] map[hostnames:[regionreport0201.mongodb] ip:10.144.14.227] map[hostnames:[qa.bizlog0601.mongodb] ip:10.144.14.227] map[hostnames:[hourreport0201.mongodb] ip:10.144.14.227] map[hostnames:[regionreport0202.mongodb] ip:10.152.100.136] map[hostnames:[hourreport0202.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0302.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0602.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0402.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0502.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0303.mongodb] ip:10.152.105.194] map[hostnames:[regionreport0203.mongodb] ip:10.152.105.194] map[hostnames:[qa.bizlog0603.mongodb] ip:10.152.105.194] map[hostnames:[qa.bizlog0503.mongodb] ip:10.152.105.194] map[hostnames:[hourreport0203.mongodb] ip:10.152.105.194] map[hostnames:[qa.bizlog0403.mongodb] ip:10.152.105.194] map[hostnames:[regionreport0301.mongodb] ip:10.134.97.208] map[hostnames:[qa.bizlog0201.mongodb] ip:10.134.97.208] map[hostnames:[hourreport0301.mongodb] ip:10.134.97.208] map[hostnames:[qa.bizlog0203.mongodb] ip:10.134.110.147] map[hostnames:[regionreport0302.mongodb] ip:10.134.110.147] map[hostnames:[regionreport0303.mongodb] ip:10.142.79.219] map[hostnames:[qa.bizlog0102.mongodb] ip:10.142.79.219] map[hostnames:[hourreport0303.mongodb] ip:10.142.79.219] map[hostnames:[xurispend01.mongodb] ip:10.144.103.130] map[hostnames:[xuridailyspend01.mongodb] ip:10.144.103.130] map[hostnames:[xuridailyspend02.mon...
4       	Sun Apr 26 16:33:17 2020	failed    	thanos-deployment-1.0.0	1.16.0     	Upgrade "janus-fe" failed: failed to create patch: The order in patch list:
        	                        	          	                       	           	[map[hostnames:[cpc0101.mongodb] ip:10.153.44.147] map[hostnames:[noclickcpc0101.mongodb] ip:10.153.44.147] map[hostnames:[idea0201.mongodb] ip:10.153.52.63] map[hostnames:[cpc0201.mongodb] ip:10.153.52.63] map[hostnames:[querykey0103.mongodb] ip:10.153.52.63] map[hostnames:[noclickcpc0201.mongodb] ip:10.153.52.63] map[hostnames:[noclickcpc0202.mongodb] ip:10.153.58.52] map[hostnames:[idea0202.mongodb] ip:10.153.58.52] map[hostnames:[noclickcpc0203.mongodb] ip:10.153.60.75] map[hostnames:[cpc0203.mongodb] ip:10.153.60.75] map[hostnames:[idea0203.mongodb] ip:10.153.60.75] map[hostnames:[cpc0301.mongodb] ip:10.144.122.209] map[hostnames:[idea0301.mongodb] ip:10.144.122.209] map[hostnames:[galaxywirelesslog02.mongodb] ip:10.144.125.225] map[hostnames:[cpc0302.mongodb] ip:10.144.125.225] map[hostnames:[galaxywirelesslog03.mongodb] ip:10.144.126.191] map[hostnames:[cpc0303.mongodb] ip:10.144.126.191] map[hostnames:[cpcrank0103.mongodb] ip:10.153.52.62] map[hostnames:[querykey0102.mongodb] ip:10.153.52.62] map[hostnames:[cpcrank0201.mongodb] ip:10.144.97.235] map[hostnames:[querykey0201.mongodb] ip:10.144.97.235] map[hostnames:[querykey0301.mongodb] ip:10.144.126.213] map[hostnames:[hourreport0101.mongodb] ip:10.144.126.213] map[hostnames:[regionreport0101.mongodb] ip:10.144.126.213] map[hostnames:[querykey0302.mongodb] ip:10.144.127.168] map[hostnames:[regionreport0102.mongodb] ip:10.144.127.168] map[hostnames:[querykey0303.mongodb] ip:10.152.99.208] map[hostnames:[regionreport0103.mongodb] ip:10.152.99.208] map[hostnames:[hourreport0103.mongodb] ip:10.152.99.208] map[hostnames:[cpcrank0303.mongodb] ip:10.152.99.208] map[hostnames:[qa.bizlog0401.mongodb] ip:10.144.14.227] map[hostnames:[regionreport0201.mongodb] ip:10.144.14.227] map[hostnames:[qa.bizlog0601.mongodb] ip:10.144.14.227] map[hostnames:[hourreport0201.mongodb] ip:10.144.14.227] map[hostnames:[regionreport0202.mongodb] ip:10.152.100.136] map[hostnames:[hourreport0202.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0302.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0602.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0402.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0502.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0303.mongodb] ip:10.152.105.194] map[hostnames:[regionreport0203.mongodb] ip:10.152.105.194] map[hostnames:[qa.bizlog0603.mongodb] ip:10.152.105.194] map[hostnames:[qa.bizlog0503.mongodb] ip:10.152.105.194] map[hostnames:[hourreport0203.mongodb] ip:10.152.105.194] map[hostnames:[qa.bizlog0403.mongodb] ip:10.152.105.194] map[hostnames:[regionreport0301.mongodb] ip:10.134.97.208] map[hostnames:[qa.bizlog0201.mongodb] ip:10.134.97.208] map[hostnames:[hourreport0301.mongodb] ip:10.134.97.208] map[hostnames:[qa.bizlog0203.mongodb] ip:10.134.110.147] map[hostnames:[regionreport0302.mongodb] ip:10.134.110.147] map[hostnames:[regionreport0303.mongodb] ip:10.142.79.219] map[hostnames:[qa.bizlog0102.mongodb] ip:10.142.79.219] map[hostnames:[hourreport0303.mongodb] ip:10.142.79.219] map[hostnames:[xurispend01.mongodb] ip:10.144.103.130] map[hostnames:[xuridailyspend01.mongodb] ip:10.144.103.130] map[hostnames:[xuridailyspend02.mon...
5       	Sun Apr 26 17:00:43 2020	failed    	thanos-deployment-1.0.0	1.16.0     	Upgrade "janus-fe" failed: failed to create patch: The order in patch list:
        	                        	          	                       	           	[map[hostnames:[cpc0101.mongodb] ip:10.153.44.147] map[hostnames:[noclickcpc0101.mongodb] ip:10.153.44.147] map[hostnames:[idea0201.mongodb] ip:10.153.52.63] map[hostnames:[cpc0201.mongodb] ip:10.153.52.63] map[hostnames:[querykey0103.mongodb] ip:10.153.52.63] map[hostnames:[noclickcpc0201.mongodb] ip:10.153.52.63] map[hostnames:[noclickcpc0202.mongodb] ip:10.153.58.52] map[hostnames:[idea0202.mongodb] ip:10.153.58.52] map[hostnames:[noclickcpc0203.mongodb] ip:10.153.60.75] map[hostnames:[cpc0203.mongodb] ip:10.153.60.75] map[hostnames:[idea0203.mongodb] ip:10.153.60.75] map[hostnames:[cpc0301.mongodb] ip:10.144.122.209] map[hostnames:[idea0301.mongodb] ip:10.144.122.209] map[hostnames:[galaxywirelesslog02.mongodb] ip:10.144.125.225] map[hostnames:[cpc0302.mongodb] ip:10.144.125.225] map[hostnames:[galaxywirelesslog03.mongodb] ip:10.144.126.191] map[hostnames:[cpc0303.mongodb] ip:10.144.126.191] map[hostnames:[cpcrank0103.mongodb] ip:10.153.52.62] map[hostnames:[querykey0102.mongodb] ip:10.153.52.62] map[hostnames:[cpcrank0201.mongodb] ip:10.144.97.235] map[hostnames:[querykey0201.mongodb] ip:10.144.97.235] map[hostnames:[querykey0301.mongodb] ip:10.144.126.213] map[hostnames:[hourreport0101.mongodb] ip:10.144.126.213] map[hostnames:[regionreport0101.mongodb] ip:10.144.126.213] map[hostnames:[querykey0302.mongodb] ip:10.144.127.168] map[hostnames:[regionreport0102.mongodb] ip:10.144.127.168] map[hostnames:[querykey0303.mongodb] ip:10.152.99.208] map[hostnames:[regionreport0103.mongodb] ip:10.152.99.208] map[hostnames:[hourreport0103.mongodb] ip:10.152.99.208] map[hostnames:[cpcrank0303.mongodb] ip:10.152.99.208] map[hostnames:[qa.bizlog0401.mongodb] ip:10.144.14.227] map[hostnames:[regionreport0201.mongodb] ip:10.144.14.227] map[hostnames:[qa.bizlog0601.mongodb] ip:10.144.14.227] map[hostnames:[hourreport0201.mongodb] ip:10.144.14.227] map[hostnames:[regionreport0202.mongodb] ip:10.152.100.136] map[hostnames:[hourreport0202.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0302.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0602.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0402.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0502.mongodb] ip:10.152.100.136] map[hostnames:[qa.bizlog0303.mongodb] ip:10.152.105.194] map[hostnames:[regionreport0203.mongodb] ip:10.152.105.194] map[hostnames:[qa.bizlog0603.mongodb] ip:10.152.105.194] map[hostnames:[qa.bizlog0503.mongodb] ip:10.152.105.194] map[hostnames:[hourreport0203.mongodb] ip:10.152.105.194] map[hostnames:[qa.bizlog0403.mongodb] ip:10.152.105.194] map[hostnames:[regionreport0301.mongodb] ip:10.134.97.208] map[hostnames:[qa.bizlog0201.mongodb] ip:10.134.97.208] map[hostnames:[hourreport0301.mongodb] ip:10.134.97.208] map[hostnames:[qa.bizlog0203.mongodb] ip:10.134.110.147] map[hostnames:[regionreport0302.mongodb] ip:10.134.110.147] map[hostnames:[regionreport0303.mongodb] ip:10.142.79.219] map[hostnames:[qa.bizlog0102.mongodb] ip:10.142.79.219] map[hostnames:[hourreport0303.mongodb] ip:10.142.79.219] map[hostnames:[xurispend01.mongodb] ip:10.144.103.130] map[hostnames:[xuridailyspend01.mongodb] ip:10.144.103.130] map[hostnames:[xuridailyspend02.mon...
```

**Dive into source code**

It seems to use patch method `helper.Patch` to perform upgrade,  and the above error is returned.

when given `--force`, it seems to try to use `helper.Replace`, but was blocked by 
```
patch, patchType, err := createPatch(target, currentObj)
```
where the error is returned.

[https://github.com/helm/helm/blob/master/pkg/kube/client.go](https://github.com/helm/helm/blob/master/pkg/kube/client.go)
```go
func updateResource(c *Client, target *resource.Info, currentObj runtime.Object, force bool) error {
	var (
		obj    runtime.Object
		helper = resource.NewHelper(target.Client, target.Mapping)
		kind   = target.Mapping.GroupVersionKind.Kind
	)

	patch, patchType, err := createPatch(target, currentObj)
	if err != nil {
		return errors.Wrap(err, "failed to create patch")
	}

	if patch == nil || string(patch) == "{}" {
		c.Log("Looks like there are no changes for %s %q", target.Mapping.GroupVersionKind.Kind, target.Name)
		// This needs to happen to make sure that tiller has the latest info from the API
		// Otherwise there will be no labels and other functions that use labels will panic
		if err := target.Get(); err != nil {
			return errors.Wrap(err, "failed to refresh resource information")
		}
		return nil
	}

	// if --force is applied, attempt to replace the existing resource with the new object.
	if force {
		obj, err = helper.Replace(target.Namespace, target.Name, true, target.Object)
		if err != nil {
			return errors.Wrap(err, "failed to replace object")
		}
		c.Log("Replaced %q with kind %s for kind %s\n", target.Name, currentObj.GetObjectKind().GroupVersionKind().Kind, kind)
	} else {
		// send patch to server
		obj, err = helper.Patch(target.Namespace, target.Name, patchType, patch, nil)
		if err != nil {
			return errors.Wrapf(err, "cannot patch %q with kind %s", target.Name, kind)
		}
	}

	target.Refresh(obj, true)
	return nil
}
```

**Solution**

So, I think that the source code could be refactor to the following one, maybe

```go
func updateResource(c *Client, target *resource.Info, currentObj runtime.Object, force bool) error {
	var (
		obj    runtime.Object
		helper = resource.NewHelper(target.Client, target.Mapping)
		kind   = target.Mapping.GroupVersionKind.Kind
	)

	// if --force is applied, attempt to replace the existing resource with the new object.
	if force {
		var err error
		obj, err = helper.Replace(target.Namespace, target.Name, true, target.Object)
		if err != nil {
			return errors.Wrap(err, "failed to replace object")
		}
		c.Log("Replaced %q with kind %s for kind %s\n", target.Name, currentObj.GetObjectKind().GroupVersionKind().Kind, kind)
	} else {
		patch, patchType, err := createPatch(target, currentObj)
		if err != nil {
			return errors.Wrap(err, "failed to create patch")
		}

		if patch == nil || string(patch) == "{}" {
			c.Log("Looks like there are no changes for %s %q", target.Mapping.GroupVersionKind.Kind, target.Name)
			// This needs to happen to make sure that tiller has the latest info from the API
			// Otherwise there will be no labels and other functions that use labels will panic
			if err := target.Get(); err != nil {
				return errors.Wrap(err, "failed to refresh resource information")
			}
			return nil
		}
		// send patch to server
		obj, err = helper.Patch(target.Namespace, target.Name, patchType, patch, nil)
		if err != nil {
			return errors.Wrapf(err, "cannot patch %q with kind %s", target.Name, kind)
		}
	}

	target.Refresh(obj, true)
	return nil
}
```

**Result**
the error was eliminated，and everything goes well.
