### ISSUE TITLE
Error: Cannot detect VCS

### ISSUE THREAD

**Issue by adampeklay** [helm/helm#8029]
**Context:**

- AWS
- [hrval GitHub action](https://github.com/stefanprodan/hrval-action)
-- Helm: 3.1.1 (as seen in [deps.sh](https://github.com/stefanprodan/hrval-action/blob/8b042044d504a72aa00760a763b4918420a8694e/src/deps.sh))
-- K8s: latest stable release, v1.18.2  (as seen in [deps.sh](https://github.com/stefanprodan/hrval-action/blob/8b042044d504a72aa00760a763b4918420a8694e/src/deps.sh))
--- To avoid any confusion, as seen in the snippet below via `kubernetesVersion`: the GH Action will [validate against](https://github.com/stefanprodan/hrval-action/blob/8b042044d504a72aa00760a763b4918420a8694e/action.yml#L14) 1.14.9

---
Hi,

I saw in [issue 7679](https://github.com/helm/helm/issues/7679) there is some great feedback on February 26th.  That comment sure helped break down the operations of things.  I have tried those suggestions yet I'm still getting the error `Error: Cannot detect VCS`.

I tried using `git://` instead of `https://` and I have had `.git` in the path for both `git://` and `https://` approaches.  Both are yielding the same result.  For both approaches I also excluded declaring a version, and I tried quoting entire value as well with the version declared..  Wondering if I can get someone to shed some light on this situation.

**More context**
- I forked hrval-action and got a PR merged to include AWS S3 Helm Repo support and ran into this error.
- Here is the last GitHub Action workflow configuration I tried (I used an example for awsS3RepoName below):

```
name: HelmRelease Validation

on: [pull_request]

jobs:
  hrval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Helm Releases
        uses: stefanprodan/hrval-action@v3.2.0
        with:
          helmRelease: envs/
          awsS3Repo: true
          awsS3RepoName: example-s3-helm-repo
          awsS3Plugin: git://github.com/hypnoglow/helm-s3.git --version 0.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
      - name: Validate Helm Release from Helm Repo
        uses: stefanprodan/hrval-action@v3.2.0
        with:
          helmRelease: envs/
          helmVersion: v3
          kubernetesVersion: 1.14.9
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
```
Here is the GitHub Action output:
```
Run stefanprodan/hrval-action@v3.2.0
/usr/bin/docker run <redacted, no errors were here though>
Creating /github/home/.helm 
Creating /github/home/.helm/repository 
Creating /github/home/.helm/repository/cache 
Creating /github/home/.helm/repository/local 
Creating /github/home/.helm/plugins 
Creating /github/home/.helm/starters 
Creating /github/home/.helm/cache/archive 
Creating /github/home/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /github/home/.helm.
Not installing Tiller due to 'client-only' flag having been set
Error: Cannot detect VCS
```
*another test that failed with the same error:
```
name: HelmRelease Validation

on: [pull_request]

jobs:
  hrval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Helm Releases
        uses: stefanprodan/hrval-action@v3.2.0
        with:
          helmRelease: envs/
          helmVersion: v3
          kubernetesVersion: 1.14.9
          awsS3Repo: true
          awsS3RepoName: ihm-sre-helm-repo
          awsS3Plugin: git://github.com/hypnoglow/helm-s3.git --version 0.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
      - name: Validate Helm Release from Helm Repo
        uses: stefanprodan/hrval-action@v3.2.0
        with:
          helmRelease: envs/
          helmVersion: v3
          kubernetesVersion: 1.14.9
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
```
Here is the GitHub Action output:
```
Run stefanprodan/hrval-action@v3.2.0
/usr/bin/docker run <redacted, no errors were here though>
Error: Cannot detect VCS
```

AFAIK the `helm plugin install <example>` is correct.  Syntax [is here](https://github.com/stefanprodan/hrval-action/blob/8b042044d504a72aa00760a763b4918420a8694e/src/hrval-all.sh#L19)

Thoughts?

Thank you!

**Comment by bacongobbler** [comment]
In your `version` field, you specified 0.9.3. If I look at the repository, the tag is listed as `v0.9.3` (note the “v”). If you add the v to the version specifier, what happens?

**Comment by bacongobbler** [comment]
To clarify: the git plugin instead clones the repository, and uses a `git checkout` to the version specified. If the branch or tag does not exist, it returns an error. It’s a little cryptic, but hope that helps.

**Comment by adampeklay** [comment]
@bacongobbler thanks for the feedback!  I'm still getting the same error (I think you meant 0.9.2 btw as AFAIK there [isn't a 0.9.3 version](https://github.com/hypnoglow/helm-s3/releases)).

I tested both `https://` and `git://`

```
name: HelmRelease Validation

on: [pull_request]

jobs:
  hrval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Helm Releases
        uses: stefanprodan/hrval-action@v3.2.0
        with:
          helmRelease: envs/
          helmVersion: v3
          kubernetesVersion: 1.14.9
          awsS3Repo: true
          awsS3RepoName: ihm-sre-helm-repo
          awsS3Plugin: https://github.com/hypnoglow/helm-s3.git --version v0.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
      - name: Validate Helm Release from Helm Repo
        uses: stefanprodan/hrval-action@v3.2.0
        with:
          helmRelease: envs/
          helmVersion: v3
          kubernetesVersion: 1.14.9
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
```

workflow error:
```
Run stefanprodan/hrval-action@v3.2.0
/usr/bin/docker run <redacted, no errors though>
Error: Cannot detect VCS
```
for the heck of it, I also tried using PAT token instead of `secrets.GITHUB_TOKEN`, same results.

Thoughts?  This is by no means pressing as I have a ticket backlogged but would definitely like to sort it out sometime soon.  I will be out of the office next week and not able to work, so I can test things out today and tomorrow but I can't log into work next week (TL/DR: its Covid related).
