### ISSUE TITLE
Same apps multiple in Charts.yaml dependencies will fail to build

### ISSUE THREAD

**Issue by ysaakpr** [helm/helm#8035]
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Chart.yaml
```yaml
description: test
name: test-apps
version: 0.0.1
dependencies:
  - name: mysql
    alias: mysql56
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.6.3
  - name: mysql
    alias: mysql80
    repository: https://charts.bitnami.com/bitnami
    version: 6.11.5
```

this gives error like 
>Error: can't get a valid version for repositories mysql. Try changing the version constraint in Chart.yaml
