### ISSUE TITLE
Helm does not attach configMap as volume to container

### ISSUE THREAD

**Issue by trustdark** [helm/helm#8057]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kops upon AWS EC2 instances

It seems weird but helm doesn't render volumeMount and volumes for my self-made chart, but does it for charts from stable repo.
I created chart with `helm create chart`, added ConfigMap like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-cm
data:
  clients.yaml: |
    internal:
      client_secret: 'internal-secret'
      grant_types:
      - client_credentials
  logins.yaml: |
    admin:
      password: password
      profile:
        name: Administrator
```
Then added such lines to deployment.yaml:

```
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: server-cm
```
I was expecting that files would be mounted to /config but got:
```
    Environment:
      ENV_VAR:  development
    Mounts:      <none>
  Volumes:       <none>
```
Also, if i make `helm template my-chart` and then add lines describing mounting ConfigMap to container it works fine.
Did i miss something in creating helm charts?

**Comment by bacongobbler** [comment]
Looks fine to me. Let us know if you figure out anything.

A set of steps to help reproduce the issue would be helpful to determine if there's some action we need to take here on our end. I can't help you further without some way to test out the behavior you are describing.

Hope this helps.

**Comment by trustdark** [comment]
It seems that im tired and should go to sleep. Sorry for inconvenience. 
Appreciate it if you remove it from issues that shame)
```
      {{- with .Values.nodeSelector }}     
     volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: oidc-cm
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```
