### ISSUE TITLE
toYaml converts int keys to string

### ISSUE THREAD

**Issue by AmitThakkar** [helm/helm#8072]
If we define YAML content in the value file as:
```
groups:
  50:
    - .*group1.*
  90:
    - .*group2.*
```

And in the configMap.yaml, we consume it as:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myGroups
data:
  groups: |-
{{ toYaml .Values.groups | indent 4 }}
```

toYaml convert all the keys to string from int.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myGroups
data:
  groups: |-
    "50":
    - .*group1.*
    "90":
    - .*group2.*
```

Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS
