### ISSUE TITLE
helm 3.2.1: import-values with child-parent format, the parent values are not updated

### ISSUE THREAD

**Issue by harivemula** [helm/helm#8097]
Output of `helm version`:
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): minikube

When i am using import-values by child-parent method, I don't see the child values overriding the parent values.
I have created a sample helm chart to reproduce this scenario. Will attach to the issue.
[mainchart-0.1.0.tgz.zip](https://github.com/helm/helm/files/4613612/mainchart-0.1.0.tgz.zip)

```
#mainchart/values.yaml

mysubchart:
  service:
     port: 0
     type: ClusterIP
```

```
#subchart/values.yaml

service:
  type: NodePort
  port: 80
```
```
#mainchart/Chart.yaml

dependencies:
- name: subchart
  version: 0.1.0
  repository: https://harbor.galaxy.env2.k8scloud.cf/chartrepo/library/
  condition: subchart.enabled
  import-values:
    - child: service
      parent: mysubchart.service

```

When I run the below command the output of COMPUTED VALUES shows that mysubchart.service.port and type are still the same.
```
helm install maintest . --dry-run --debug

COMPUTED VALUES:
....
mysubchart:
  service:
    port: 0
    type: ClusterIP
...
subchart:
....
  service:
    port: 80
    type: NodePort
....
```

**Expected COMPUTED VALUES should be:**
```
....
mysubchart:
  service:
    port: 80
    type: NodePort
...
subchart:
....
  service:
    port: 80
    type: NodePort
....
```

Am i doing anything wrong or is it a bug?

Thanks,
Hari
