### ISSUE TITLE
error validating data: kind not set

### ISSUE THREAD

**Issue by gionapaolini** [helm/helm#8102]
This is my yaml file:

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "service1-chart.fullname" . }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "service1-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "service1-chart.fullname" . }}
    spec:
      containers:
        - name: service1
          image: service1:latest
          env:
            - name: ConnectionStrings__Context
              values: Server={{ template "mssql.fullname" . }}.default.svc.cluster.local:{{ index .Values "mssql-linux" "service" "port"}};Database={{ index .Values "mssql-linux" "dbname"}};User=sa;Password={{ index .Values "mssql-linux" "sapassword" }};
```
Output of `helm template . `:

```
# Source: service1-chart/templates/application.yaml
﻿kind: Deployment
apiVersion: apps/v1
metadata:
  name: RELEASE-NAME-service1-chart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RELEASE-NAME-service1-chart
  template:
    metadata:
      labels:
        app: RELEASE-NAME-service1-chart
    spec:
      containers:
        - name: service1
          image: service1:latest
          env:
            - name: ConnectionStrings__Context
              values: Server=RELEASE-NAME-mssql.default.svc.cluster.local:1433;Database=TestDB;User=sa;Password=Test123:456;
```
If I try to run `helm install test .` I get:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: kind not set
```

Output of `helm version`: 

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Local development with K8s for Docker Desktop
