### ISSUE TITLE
helm dep update is not working correctly if the repository is not present in the local repo list

### ISSUE THREAD

**Issue by technosophos** [helm/helm#8118]
Output of `helm version`:

version.BuildInfo{Version:"v3.2+unreleased", GitCommit:"324c7cbc076f4e673e246f6cdc97939815e4af13", GitTreeState:"clean", GoVersion:"go1.14.2"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Kind

---

While looking into #8028, we discovered a long-standing issue in `helm dep update`.

The correct behavior:

If a repository is added to Helm (e.g. `helm repo add ...`), and then a chart in that repository is referenced in a `dependencies` section of a `Chart.yaml`, the resolver correctly does SemVer comparisons and pins to a specific version of the chart.

The incorrect behavior:

If a repository is NOT PRESENT when `helm dep up` is run (or when `helm dep build` is called and no `Chart.lock` is present), then the chart repository is fetched out-of-band. While the proper version is resolved for the chart that is updated locally, the `Version` field in the `chart.lock` is incorrectly set to the SemVer query, not to the resolved version.

## Reproducing

Create a chart with `helm create` and then add this to the `Chart.yaml`:
```yaml
dependencies:
- name: argo-cd
  version: ">=1.8.0"
  repository: https://argoproj.github.io/argo-helm
```

Make sure that the chart repository is not already in your `helm repo list`. If it is, remove it and clear the cache directory.

```
$ helm repo list
Error: no repositories to show
```

Now do a `helm dep build` or `helm dep update`.

```
$ helm dep build
Saving 1 charts
Downloading argo-cd from repo https://argoproj.github.io/argo-helm
Deleting outdated charts
```

Now look at the generated `Chart.lock`:

```yaml
dependencies:
- name: argo-cd
  repository: https://argoproj.github.io/argo-helm
  version: '>=1.8.0'
digest: sha256:1801b6e7653b3cba2a78902a8268a453f376bed85b1ff81b96ac88c4aacbea2c
generated: "2020-05-13T17:05:42.497865-06:00"
```

Note that `version` is wrong. It should not be a range query. It should be the _specific version_ that the dependency resolver found.

Why is this a problem? Because the lockfile is no longer doing its job: It is no longer pinning to a single version.

Note that in the above example, the actual version that it downloaded was version 3.2.0. So it is correctly negotiating the SemVer range, but it is not generating the correct value for `Chart.lock`

This issue _may_ impact Helm 2, but it definitely impacts Helm 3, all versions.
