### ISSUE TITLE
[Question/Support] Help with import-values 

### ISSUE THREAD

**Issue by whitleykeith** [helm/helm#8143]
Hey all,
I have a somewhat complex chart I want to build that contains multiple subcharts. Many of those subcharts contain values I want exported to other subcharts. i.e.:
```yaml
# Subchart 1 values.yaml
# This subchart installs istio
istio:
  enabled: true
```
```yaml
# Subchart 2 values.yaml
# This subchart has apps that may create Istio CRDs, but only if the flag is set to true
istio:
  enabled: false
```
```yaml
# Parent Chart Chart.yaml
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: parentchart
version: 0.1.0
dependencies:
- name: subchart1
  version: 0.1.0
  import-values:
  - child: istio
    parent: subchart2.istio
- name: subchart2
  version: 0.1.0
```
This doesn't work unless I remove the default value in subchart2. However, that's not desirable as values.yaml should have all possible values with working defaults.

Does anyone know how I could do this with the current feature set of helm? I think it'd work if I set it in global but then I'd have to write logic in each subchart to look at the global value. I also wish import-values would let me only import one value instead of entire maps as it's a bit crazy
