### ISSUE TITLE
Chart dependency conditions vs enabled

### ISSUE THREAD

**Issue by eddycharly** [helm/helm#8155]
From the docs [here](https://helm.sh/docs/topics/charts/):
```yaml
dependencies: # A list of the chart requirements (optional)
  - name: The name of the chart (nginx)
    condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
    enabled: (optional) Enabled bool determines if chart should be loaded
```

What is the difference between `conditions` and `enabled` in chart dependencies ?
I guess i understand `conditions` but what is the `enabled` purpose ?
