### ISSUE TITLE
Adding prometheus scrape to chart's annotations fails

### ISSUE THREAD

**Issue by grapevineai** [helm/helm#8164]
I have the following service template to allow prometheus to scrape the service:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
  prometheus.io/scrape: 'true'
```

When I try to install/upgrade it, I get the following error:
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Service.metadata): unknown field "prometheus.io/scrape" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
```

PS: when I manually add this annotation to the existing service via the GKE editor, the annotation is properly added and everything works.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
GKE
```

**Comment by bacongobbler** [comment]
I think the error is fairly clear here: a label cannot be part of the object metadata field. It has to be listed under an object’s labels.

Try the following:

```

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    prometheus.io/scrape: 'true'
```

Can you point out where you found the documentation that described the scrape label?
