### ISSUE TITLE
Chart with CRD and webhook

### ISSUE THREAD

**Issue by eddycharly** [helm/helm#8171]
As helm v3 doesn't support CRDs templating, how one would configure a conversion webhook for a CRD ?

Let's take this for example:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.example.com
spec:
  group: example.com
  versions:
  - name: v1beta1
    served: true
    storage: true
  - name: v1
    served: true
    storage: false
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1","v1beta1"]
      clientConfig:
        service:
          namespace: default
          name: example-conversion-webhook-server
          path: /crdconvert
```

From what i understand, there is no way to configure the conversion webhook service namespace, name, port, etc...

What would be the best approach here ?
- One dedicated chart containing only the CRD and the webhook, not using the crds folder but regular templates ? (something like this https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts)
- No separate chart for CRD and webhook, deploy CRD without conversion infos, and run a job to update the CRD with the conversion webhook service infos ?
- Something else ?

Thanks
