### ISSUE TITLE
Manage Helm chart repo configuration within cluster

### ISSUE THREAD

**Issue by pedjak** [helm/helm#8175]
# Motivation

Currently, Helm chart repository configurations are kept in local `.config/helm/repositories.yaml` file only and its content it managed by issuing `helm repo add/remove` commands. Such approach imposes the following issues:

* Right configuration should be distributed and kept in sync on all relevant machines
* Repository configuration cannot be added on a read-only filesystem, forcing the usage of absolute chart URLs
* Inability to have repository configurations per a cluster
* Inability to share repository configurations in a team

# Proposal

The `HelmChartRepository` is a simple cluster-scoped CR for letting cluster admins define Helm chart repository configurations in a cluster.

```yaml
apiVersion: config.helm.sh/v1alpha1
kind: HelmChartRepository
metadata:
  name: myCharts
spec:
  url: http://my.chart-repo.org/stable

  # optional and only needed for UI purposes
  displayName: myChartRepo

  # optional and only needed for UI purposes
  description: my private chart repo

  # set to true if need to be disabled temporarly
  disabled: true

  # other fields from
  # https://github.com/helm/helm/blob/master/pkg/repo/chartrepo.go#L42
```

The proposed CR should be semantically equivalent to [repo.Entry](https://github.com/helm/helm/blob/master/pkg/repo/chartrepo.go#L42) structure.

This change would enable Helm to read repository configurations from the configured cluster as well and use them in appropriate actions.

## Configuring Repositories

Cluster admin can add a number chart repositories:

```shell
$ cat <<EOF | kubectl apply -f -
apiVersion: config.helm.sh/v1alpha1
kind: HelmChartRepository
metadata:
  name: stable
spec:
  url: https://kubernetes-charts.storage.googleapis.com

  displayName: Public Helm stable charts

---
apiVersion: config.helm.sh/v1alpha1
kind: HelmChartRepository
metadata:
  name: myCharts
spec:
  url: http://my.chart-repo.org/stable

  displayName: my private chart repo
EOF
```

## Usage

The cluster treats them as any other resource:

```shell
$ kubectl get helmchartrepositories
NAME          AGE
stable        1m
myCharts      1m
```

and Helm can access them and use them as they were added using `helm repo add` command:

```shell
# repositories configured in the cluster.
$ helm repo list
NAME     	URL
stable   	https://kubernetes-charts.storage.googleapis.com
myCharts	https://kubernetes-charts-incubator.storage.googleapis.com

# install a chart from the "stable" repo defined in the cluster
$ helm install mysql stable/mysql
```

__NOTE__: Storing repository configuration locally still works and is perform as usual using `helm repo add/remove` commands. However, the configuration stored in the cluster is managed using `kubectl`/K8S API.

## Benefits

* Easy configuration sharing across teams/infrastructure
* Simpler team onboarding
* Repository configuration can be cluster-scoped, e.g. `stable` repo in cluster A must not be the same as `stable` repo in cluster B
* [Helm Hub](https://hub.helm.sh) can publish curated configurations, easily consumable by cluster admins
* Cluster admins could white list repositories
* A step forward to running Helm in read-only environments

 ## Open Questions

 * Should we allow namespaced `HelmChartRepository`?
