### ISSUE TITLE
unable to create common(library) configmap data from files glob

### ISSUE THREAD

**Issue by vsirimalla** [helm/helm#8200]
I am following this [documentation](https://helm.sh/docs/topics/library_charts/) to make use of common configmap data. However, only difference I am making is that, I would like to have use file glob to have the template pick up the files content as config data. 

so in `mylibchart/templates/_configmap.yaml`, instead of adding directly, I am using this :
`{{ (.Files.Glob "config-dir/*").AsConfig | indent 2 }}`, but its not picking up files from config-dir under libary chart.
This is how my `mylibchart/templates/_configmap.yaml` looks: 
```
{{- define "common.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}
data: 
{{ (.Files.Glob "config-dir/*").AsConfig | indent 2 }}
{{- end -}}

{{- define "common.configmap" -}}
{{- include "common.util.merge" (append . "common.configmap.tpl") -}}
{{- end -}}
```

**Comment by bacongobbler** [comment]
hi @vsirimalla. Can you please describe the issue you are experiencing, and what was the expected output? From your comment I cannot tell what issue you are running into. Thanks!

**Comment by bacongobbler** [comment]
Also as per the github issue template, please let us know what version of helm/kubernetes you are using, as well as any further information you can provide.

**Comment by vsirimalla** [comment]
![folder-tree](https://user-images.githubusercontent.com/30087468/83201174-8ddc6e80-a10a-11ea-959b-219477d072ca.png)


@bacongobbler This is how my charts tree looks. 
I am looking to merge config files from two different charts into a configmap.

1.  Library chart, named as common
`common/config-dir` has `file-1.xml` and `file-2.pem`
2. Other is appChart, named as : device-alertsprocessor.
`device-alertsprocessor/config-dir` has `file-3.xml` and `file-4.jks`


and when I run helm install, 
` helm install demo ./ --dry-run`

**Excepting** (to merge both common and device-alertsprocessor config files):
```
---
# Source: device-alertsprocessor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: device-alertsprocessor
data: 
  file-1.xml: this is common file-1
  file-2.pem: this is common file-2
  file-3.xml: this is app chart file-3
  file-4.jks: this is appchart file 4
```

**Actual:**
```
---
# Source: device-alertsprocessor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: device-alertsprocessor
data: 
  file-3.xml: this is app chart file-3
  file-4.jks: this is appchart file 4
```

Attaching the code here. [project-blue.zip](https://github.com/helm/helm/files/4698682/project-blue.zip)

Helm version: v3.2.1
Kubernetes version : v1.15.5
