### ISSUE TITLE
When installing umbrella chart, if the subcharts have template definition of same name it's not working as expected

### ISSUE THREAD

**Issue by subramani95** [helm/helm#8209]
When installing umbrella chart, if the subcharts have template definition of same name it's not working as expected

### Steps to reproduce
- Create a chart `first`
```
$helm create first
Creating first
```
- Add definition `my.name` as below in `templates/_helpers.tpl`:-
```
{{- define "my.name" -}}
{{- "first" -}}
{{- end -}}
```
- Call `my.name` and set env variable as below by changing the `templates/deployment.yaml` in the chart `first`:-
```    env:
            - name: MY_NAME
              value: {{ include "my.name" . }}
```
- Create another chart `second`
```
$helm create second
Creating second
```
- Add definition `my.name` as below in `templates/_helpers.tpl`:-
```
{{- define "my.name" -}}
{{- "second" -}}
{{- end -}}
```
- Call `my.name` and set env variable as below by changing the `templates/deployment.yaml` in the chart `second`:-
```    env:
            - name: MY_NAME
              value: {{ include "my.name" . }}
```
- Create an umbrella chart with `first` and `second` as subcharts
```
$cat requirements.yaml
dependencies:
  - name: first
    version: "0.1.0"
    repository: "file://first"
    condition: global.deploy.first
  - name: second
    version: "0.1.0"
    repository: "file://second"
    condition: global.deploy.second

$cat values.yaml
global:
  deploy:
    first: true
    second: true

$cat Chart.yaml
name: test
version: 1.0.0
description: Umbrella Chart
```
- Build dependency by executing `helm dep build`
- Install the umbrella chart. Now both the `first` and `second` deployments have the same value `first` for the env variable `MY_NAME` instead of respective `my.name` `first` and `second`.

Output of `helm version`:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
minikube version: v1.8.2
commit: eb13446e786c9ef70cb0a9f85a633194e62396a1
