### ISSUE TITLE
Escape/turn-off GO helm templating for a section of config file present in templates folder

### ISSUE THREAD

**Issue by sahil-sawhney** [helm/helm#8236]
Helm Version -> 3.2.0
Kubectl Version -> 1.17.0
Kubernetes Version -> 1.16
Cloud Provider -> AWS

**Description ->**
I am using Helm 3 and I am looking for way by which in the same YAML file I can turn Helms GO Templating off. For example, in the following snippet, I want that helm should not try to substitute **{{ $value }}** and let it pass as it is, so that Prometheus can actually fill in the $value as per the value of the alert expression. And also I want **{{  .Values.global.namespace  }}** to follow helm templating.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules-conf
  labels:
    name: prometheus-rules-conf
  namespace: {{ .Values.global.namespace }} 
data:
  prometheus.rules: |-
    groups:
    - name: demo.rules
      rules:
      - alert: TESTING NGINX POD STATUS
        expr: sum(kube_pod_info{namespace="test", pod=~"nginx.*"}) < 3
        for: 1m
        labels:
          severity: critical
        annotations:
          description: Nginx Trouble In Harmony Demo
          summary: The Nginx Pod count is {{ $value }} which is less than expected value of 3.
```

The error I get while running the command **helm lint alert_manager** is as follows

> [ERROR] templates/: parse error at (alert-manager/templates/prometheus-rules-conf.yaml:20): undefined variable "$value"
