### ISSUE TITLE
a `.Files.Get` in a `define` of a subchart breaks encapsulation, it reads files from parent chart

### ISSUE THREAD

**Issue by rubensayshi** [helm/helm#8266]
Output of `helm version`:
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

---

When you use `.Files.Get` in a `define`d template in a subchart and `include` the template in the parent chart, it will read files from the parent's directory instead of from the the subchart.

I'd expect that if a subchart `define`s a template which reads a file using `.Files.Get` that it will be encapsulated and read the specified file from the subcharts directory, not from the parent. 

I've created a tiny repo to demonstrate; https://github.com/rubensayshi/helm-subchart-files. 
The result is;
```
---
# Source: test/charts/lib/templates/subchart-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: subchart-secret
data:
#
include: from lib
---
# Source: test/templates/mysecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  #
included: from root
```
