### ISSUE TITLE
coalesce.go:160: warning: skipped value for secrets: Not a table.

### ISSUE THREAD

**Issue by KR411-prog** [helm/helm#8283]
I am trying below template for generating secrets from values files..

Template:
```
{{- range $secretName,$secretValue := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ required "a valid name is required" $secretName }}
type: {{  $secretValue.type | default "Opaque" }}
data:
    {{- range $key, $val := $secretValue.data }}
      {{ $key }}: {{ required "a valid key is required" $val }}
    {{- end }}
{{- end }}
```
value1.yaml
```
secrets:
 sample1: 
  type: "Opaque"
  data:
   test2: "YXBpa2V5MQo="
```

value2.yaml
```
secrets:
 sample2: 
  type: "Opaque"
  data:
   test2: "YXBpa2V5MQo="
```

Output is fine:
```
helm template apicentral-secrets-template -f value1.yaml -f value2.yaml                                                                                    
coalesce.go:160: warning: skipped value for secrets: Not a table.
---
# Source: apicentral-secrets-template/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: sample1
type: Opaque
data:
    test2: YXBpa2V5MQo=
---
# Source: apicentral-secrets-template/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: sample2
type: Opaque
data:
      test2: YXBpa2V5MQo=

```
But I am getting below warning eventhough it works fine..Is this a problem?How to fix this warning?

`coalesce.go:160: warning: skipped value for secrets: Not a table.`

Output of `helm version`: 3.4.3

Output of `kubectl version`: 1.15

Cloud Provider/Platform : EKS

**Comment by KR411-prog** [comment]
Sorry...
HELM_VERSION=v3.2.1
HELMSMAN_VERSION=3.4.3

**Comment by jdolitsky** [comment]
@KR411-prog I believe this is just a tabbing/spacing issue. It appears you have one extra tab.

Try doing this:
```
data:
{{- range $key, $val := $secretValue.data }}
  {{ $key }}: {{ required "a valid key is required" $val }}
{{- end }}
```

instead of this:
```
data:
    {{- range $key, $val := $secretValue.data }}
      {{ $key }}: {{ required "a valid key is required" $val }}
    {{- end }}
```

**Comment by KR411-prog** [comment]
I even tried this and same warning,
```
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ required "a valid name is required" $secretName }}
type: {{  $secretValue.type | default "Opaque" }}
data:
{{- range $key, $val := $secretValue.data }}
    {{ $key }}: {{ required "a valid key is required" $val }}
{{- end }}
{{- end }}
```

**Comment by woodcockjosh** [comment]
I also have this problem

**Comment by ManCon** [comment]
I have done some tests

**I Get the ERROR with this Chart Version:**
    name:    loki-stack
    version: 0.38.3

**It is working like expected without ERROR with the older Chart Version:**
    name: loki-stack
    version: 0.38.1

Best regards
Manfred

**Comment by KR411-prog** [comment]
May I know if there is any update on this issue please?

**Comment by 11xor6** [comment]
I can provide some extra context. I'm working with the `stable/dex` chart and this is a snippet of it's `values.yaml` file:
```yaml
securityContext:
  # Rejecting containers trying to run with root privileges
  # runAsNonRoot: true
  # Preventing privilege escalation to root privileges
  # allowPrivilegeEscalation: false
  # Set the user ID used to run the container
  # runAsUser: 1001
  # Set the primary group ID used to run all processes within any container of the pod
  # runAsGroup: 1001
  # Set the group ID associated with the container
  # fsGroup: 1001
```
Note that there are no actual entries in the map and I believe this means it gets treated as a scalar of some kind, maybe `nil`.

And in my `values.yaml` file I have:
```yaml
securityContext:
  runAsNonRoot: true # Rejecting containers trying to run with root privileges
  runAsUser: 1001 # Set the user ID used to run the container
  runAsGroup: 1001 # Set the primary group ID used to run all processes within any container of the pod
  fsGroup: 1001 # Set the group ID associated with the container
```
I of course get the same error: `coalesce.go:160: warning: skipped value for securityContext: Not a table.`

I believe this occurs when helm tries to merge a table with a scalar. It seems like a valid warning in this case. This would need to be fixed in the chart generating the error. I haven't tested this, but I'd assume if this chart looked like `securityContext: {}` then this error would not occur.
