### ISSUE TITLE
Unable to see updated configuration in configmap with helm upgrade command

### ISSUE THREAD

**Issue by darshandeshmukh11** [helm/helm#8293]
Output of `helm version`:
`Client: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}`

Output of `kubectl version`:
`Client: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

Prometheus Helm Chart Version - 11.0.2

Issue - 
Unable to see updated configuration in AlertManager UI after `helm upgrade`

1. Added below code snippet in default `values.yaml`

```
alertmanagerFiles:
  alertmanager.yml:
    global:
      smtp_from: 'from address'
      smtp_smarthost: 'SMTP'
    receivers:
      - name: 'Receiver Name'
        email_configs:
          - send_resolved: true
            to: 'to address'
    route:
      receiver: Receiver Name
      group_wait: 5m
      group_interval: 5m
      group_by: [alertname]
      repeat_interval: 3h
      continue: false
```

2. Used below command for upgrade - 
 `$ /usr/local/bin/helm upgrade -f values.yaml prometheus ./prometheus`

3. Helm template command shows correct output 
```
$ # /usr/local/bin/helm template -f values.yaml prometheus ./prometheus
---
# Source: prometheus/templates/alertmanager-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: release-name
    chart: prometheus-11.0.2
    heritage: Tiller
  name: release-name-prometheus-alertmanager
data:
  alertmanager.yml: |
    global:
      smtp_from: from address
      smtp_smarthost: SMTP host
    receivers:
    - email_configs:
      - send_resolved: true
        to: to address
      name: WK-GBS-GRCMLAlerts
    route:
      continue: false
      group_by:
      - alertname
      group_interval: 5m
      group_wait: 5m
      receiver: WK-GBS-GRCMLAlerts
      repeat_interval: 3h
```

4. Whereas I could not see the actual configuration in alert-manager UI
![image](https://user-images.githubusercontent.com/7932274/84356349-af952580-abe1-11ea-9e15-76c615f87bdf.png)

**Comment by mattfarina** [comment]
I suspect the issue is that the pods using the configmap are not updating. There is a fix for the chart, described in the tips and tricks, that can help with this... https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

I'm not sure whose chart this is. Is this yours or part of an open source project? 

Have you tried to kill the pods and let Kubernetes recreate them to see if that fixes it? If so, it means the pods aren't updating to the new version of the ConfigMap.

**Comment by darshandeshmukh11** [comment]
@mattfarina I am using official stable/prometheus helm chart - https://hub.helm.sh/charts/stable/prometheus/11.0.2 

I tried to kill the pods manually but since the pods have associated volumes I run into unstable deployment.

```
Events:  Type     Reason              Age                  From                                                 Message
  ----     ------              ----                 ----                                                 -------
  Normal   Scheduled           9m15s                default-scheduler                                    Successfully assigned monitoring/prometheus-alertmanager-5f6867576-9m4h7 to ip-10-226-64-26.us-east-2.compute.internal
  Warning  FailedAttachVolume  9m15s                attachdetach-controller                              Multi-Attach error for volume "pvc-1a77639c-684a-11ea-b460-023d7956adb6" Volume is already used by pod(s) prometheus-alertmanager-698ccf55fd-7gv25
  Warning  FailedMount         25s (x4 over 7m12s)  kubelet, ip-10-226-64-26.us-east-2.compute.internal  Unable to mount volumes for pod "prometheus-alertmanager-5f6867576-9m4h7_monitoring(e73d9b44-aa45-11ea-8db9-026bf6d3eb58)": timeout expired waiting for volumes to attach or mount for pod "monitoring"/"prometheus-alertmanager-5f6867576-9m4h7". list of unmounted volumes=[storage-volume]. list of unattached volumes=[config-volume storage-volume prometheus-alertmanager-token-ljwz8]
```

**Comment by darshandeshmukh11** [comment]
@mattfarina As suggested I tried to use the suggested trick here - https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
```
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
```

Result - It does restart the containers as expected but the new pod created stucks in `ContainerCreating` state and the old pod stucks in `Running` state due to below error - 

`Multi-Attach error for volume "pvc-1a77639c-684a-11ea-b460-023d7956adb6" Volume is already used by pod(s) prometheus-alertmanager-698ccf55fd-7gv25`
