### ISSUE TITLE
HPA not scaling down using helm

### ISSUE THREAD

**Issue by nirupbbnk** [helm/helm#8302]
`helm version`: 2.12

`kubectl version`: 1.17

Cloud Provider: AWS (cluster is built using **Kops**)

Horizontal pod autoscler is not scaling down resources when doing with helm , but its working when using declarative scrips directly.

It should scaledown if its less than target value

How to reproduce it (as minimally and precisely as possible: use the below script
################
{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
name: {{ template "auth-server-helm.fullname" . }}
spec:
scaleTargetRef:
apiVersion: apps/v1
kind: Deployment
name: {{ template "auth-server-helm.fullname" . }}
minReplicas: {{ .Values.replicaCount }}
maxReplicas: {{ .Values.hpa.maxReplicas }}
metrics:
{{- if .Values.hpa.memory }}

type: Resource
resource:
name: memory
target:
type: Utilization
averageUtilization: {{ .Values.hpa.memory }}
{{- end }}
{{- end }}
################

Anything else we need to know?:
It scales down if we use declarative steps , but not with helm.
below is declartive script
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
name: document-mgmt-helm
namespace: default
spec:
scaleTargetRef:
apiVersion: apps/v1
kind: Deployment
name: document-mgmt-helm
minReplicas: 1
maxReplicas: 1
metrics:

type: Resource
resource:
name: memory
targetAverageUtilization: 98
Environment:

Kubernetes version (use kubectl version): 1.17
Cloud provider or hardware configuration: AWS
OS (e.g: cat /etc/os-release): Debian GNU/Linux 9
Kernel (e.g. uname -a):Linux ip-172-20-95-48 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux

**Comment by bacongobbler** [comment]
Can you please test and confirm if this is an issue with the latest version of helm 2 or helm 3? 2.12 is very old.

**Comment by bridgetkromhout** [comment]
Hi, @nirupbbnk - the latest Helm 2 is here: https://github.com/helm/helm/releases/tag/v2.16.8
And the latest Helm 3 is here: https://github.com/helm/helm/releases/tag/v3.2.3

Please let us know if you still see this behavior with a more recent version of Helm. Thanks!

**Comment by nirupbbnk** [comment]
Hi @bridgetkromhout ,
Thanks for the reply,
I tried to upgrade helm to latest version and tried, no luck.

Inserting the hpa template for your reference

`
```yaml
{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "knowledge-base-helm.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "knowledge-base-helm.fullname" . }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.cpu }}
  - type: Resource
    resource:
      name: memory
      target: averageUtilization: {{ .Values.hpa.memory }}
  {{- end }}
{{- end }}
````
