### ISSUE TITLE
[BUG] Helm 3.2.2 and 3.2.3 upgrade fails because service of spec.clusterIP

### ISSUE THREAD

**Issue by moosecanswim** [helm/helm#8307]
My helm upgrade fails with version 3.2.2 and 3.2.3 but works with helm 3.2.0.

Command:

`helm upgrade sense adx/sense --set=global.waiter.service_account.create=false -f values.yaml -f ../global.yaml --no-hooks --force --install
Error: UPGRADE FAILED: failed to replace object: Service "catalog" is invalid: spec.clusterIP: Invalid value: "": field is immutable`

The helm chart template:
```
apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  selector:
    {{ .Values.global.control.cluster_label }}: catalog
  ports:
    - name: catalog
      port: {{ .Values.catalog.port }}
      targetPort: {{ .Values.catalog.port }}
  type: ClusterIP
  sessionAffinity: None
```

Running a `helm template` with version 3.2.3
```
# Source: sense/charts/catalog/templates/catalog-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  selector:
    greymatter.io/control: catalog
  ports:
    - name: catalog
      port: 9080
      targetPort: 9080
  type: ClusterIP
  sessionAffinity: None
```

Running a `helm template` with version 3.2.0 (same as 3.2.3)
```
# Source: sense/charts/catalog/templates/catalog-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  selector:
    greymatter.io/control: catalog
  ports:
    - name: catalog
      port: 9080
      targetPort: 9080
  type: ClusterIP
  sessionAffinity: None
```

Output of `helm version`:
`helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}`

Output of `kubectl version`:
`kc version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)
oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS
