### ISSUE TITLE
Set does not work with arrays

### ISSUE THREAD

**Issue by brianharwell** [helm/helm#8320]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

According to [the docs](https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set) I should be able to do this...

```
--set servers[0].port=80
```

But I have tried and it does not work. I have a very simple helm template.

template.yaml
```
array:
  {{- range .Values.array }}
  - name: {{ .name }}
    value: {{ .value | quote }}
  {{- end }}
```

values.yaml
```
array:
  - name: Name1
    value: Value1
  - name: Name2
    value: Value2
  - name: Name3
    value: Value3
```

If I run `helm template .` it works as expected and outputs the following:
```
---
# Source: Test/templates/template.yaml
array:
  - name: Name1
    value: "Value1"
  - name: Name2
    value: "Value2"
  - name: Name3
    value: "Value3"
```

If I run `helm template . --set array[2].name="foo"` it fails with the error:
```
Error: template: Test/templates/template.yaml:3:13: executing "Test/templates/template.yaml" at <.name>: nil pointer evaluating interface {}.name
```

The only way this works is if I rebuild the entire array like so...
```
helm template . --set array[0].name="foo",array[0].value="bar",array[1].name="dog",array[1].value="cat"
```
And that outputs
```
---
# Source: Test/templates/template.yaml
array:
  - name: foo
    value: "bar"
  - name: dog
    value: "cat"
```

The desired result is to be able to:

1. Change a value in the array without rebuilding the array
2. Append values to the array without rebuilding the array
