### ISSUE TITLE
helm3 --value flag not overwrite values.yaml of charts

### ISSUE THREAD

**Issue by dellkeji** [helm/helm#8335]
my chart:

```
# test.yaml
apiVersion: xxx
kind: ClbIngress
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  http: {{ .Values.ingresses.http }}
  https: {{ .Values.ingresses.https }}
  statefulset:
{{- with .Values.ingresses.statefulset }}
    {{- toYaml . | nindent 2 }}
{{- end }}

# values.yaml
clbName: xxxxx
ingresses:
  http: []
  https: []
  tcp: []
  udp: []
  statefulset:
    tcp:
    - startPort: xxx
      startIndex: 0
      endIndex: 1
      serviceName: tcp-test
      namespace: clb
      sessionTime: 50
      healthCheck:
        enabled: true
```

i want to renderer the **test.yaml** by set the values file A，but the content of A not overwrite the values of default chart value.yaml

A file content：
```
clbName: xxxxx
ingresses:
  http: []
  https: []
  tcp: []
  udp: []
  statefulset:
    udp:
    - startPort: xxx
      startIndex: 0
      endIndex: 1
      serviceName: tcp-test
      namespace: clb
      sessionTime: 50
      healthCheck:
        enabled: true
```

```
helm3 template test123 test -f values.yaml
``` 

output content:
```
apiVersion: xxx
kind: ClbIngress
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: test
  namespace: test123
spec:
  http: []
  https: []
  statefulset:
  tcp:
  - endIndex: 1
    healthCheck:
      enabled: true
    namespace: clb
    serviceName: tcp-test
    sessionTime: 50
    startIndex: 0
    startPort: xxx
  udp:
  - endIndex: 1
    healthCheck:
      enabled: true
    namespace: clb
    serviceName: tcp-test
    sessionTime: 50
    startIndex: 0
    startPort: xxx
```

expect output content:
```
apiVersion: xxx
kind: ClbIngress
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: 
  namespace: test123
spec:
  http: []
  https: []
  statefulset:
  udp:
  - endIndex: 1
    healthCheck:
      enabled: true
    namespace: clb
    serviceName: tcp-test
    sessionTime: 50
    startIndex: 0
    startPort: xxx
```

the docs show values content can be overwrite

https://helm.sh/docs/chart_template_guide/values_files/

Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
When merging two maps together (or dictionaries, depending on what you prefer to call them), any values that collide are overwritten by the values provided on the command line.

In your case, you provided two maps: one with the key `udp` and one with the key `tcp`. These are treated as different tree structures, and are treated as a clean merge. One does not overwrite the other.

In other words, you requested the following values:

```
clbName: xxxxx
ingresses:
  http: []
  https: []
  tcp: []
  udp: []
  statefulset:
    tcp:
    - startPort: xxx
      startIndex: 0
      endIndex: 1
      serviceName: tcp-test
      namespace: clb
      sessionTime: 50
      healthCheck:
        enabled: true
    udp:
    - startPort: xxx
      startIndex: 0
      endIndex: 1
      serviceName: tcp-test
      namespace: clb
      sessionTime: 50
      healthCheck:
        enabled: true
```

Change the key `udp` in your example's "A file" to `tcp` and it will work as you'd expect.

If you wanted to remove the `tcp` key and use a `udp` port instead, use the following in your "A file" instead:

```
clbName: xxxxx
ingresses:
  http: []
  https: []
  tcp: []
  udp: []
  statefulset:
    tcp: null
    udp:
    - startPort: xxx
      startIndex: 0
      endIndex: 1
      serviceName: tcp-test
      namespace: clb
      sessionTime: 50
      healthCheck:
        enabled: true
```

Notice how it set `tcp` to null. That will null out the value entirely.

```
><> helm template -f values.yaml ./mychart/
---
# Source: mychart/templates/test.yaml
apiVersion: xxx
kind: ClbIngress
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: RELEASE-NAME
  namespace: default
spec:
  http: []
  https: []
  statefulset:
  udp:
  - endIndex: 1
    healthCheck:
      enabled: true
    namespace: clb
    serviceName: tcp-test
    sessionTime: 50
    startIndex: 0
    startPort: xxx
```

Hope this helps.
