### ISSUE TITLE
Helm fails when Chart has 2 dependencies with the same name.

### ISSUE THREAD

**Issue by Nuru** [helm/helm#8345]
#### Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

#### Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.11", GitCommit:"436254b798f772bcb8e67dcfe122e46500eeb254", GitTreeState:"clean", BuildDate:"2020-06-17T11:49:23Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
#### Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS EKS

#### Example:

<details><summary>chart/Chart.yaml</summary>

```yaml
name: prometheus-operator
version: 1.0.0
apiVersion: v2
dependencies:
- name: prometheus-operator
  repository: https://charts.bitnami.com/bitnami
  version: 0.18.0
- name: prometheus-operator
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 8.13.8
```
</details>

`helm` fails: 
```
$ helm dependency update chart
...
Error: can't get a valid version for repositories prometheus-operator. Try changing the version constraint in Chart.yaml
```

- Adding aliases for the dependencies does not help. 
- If I make 2 separate charts, one for each dependency, `helm dependency update` works for each chart.
