### ISSUE TITLE
Subchart pods are prefixed by parent chart release name

### ISSUE THREAD

**Issue by kaniapm** [helm/helm#8354]
Output of `helm version`:
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

I have the following parent Chart.yaml defining some dependencies:

```yaml
apiVersion: v2
name: abc
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 4.0.0

dependencies:
  - name: inventory
    version: ~0.1.0
    repository: "@my-charts"
  - name: master
    version: ~0.1.0
    repository: "@my-charts"
  - name: site
    version: ~0.1.0
    repository: "@my-charts"
```

If I install this chart then Kubernetes creates following pods:

```console
abc-inventory-7fc7fbcf46-t6zsz              0/1     ContainerCreating   0          3s    <none>           test10   <none>           <none>
abc-master-0                                0/2     ContainerCreating   0          3s    <none>           test23   <none>           <none>
abc-master-1                                0/2     ContainerCreating   0          3s    <none>           test21   <none>           <none>
abc-site-0                                  0/4     ContainerCreating   0          3s    <none>           test23   <none>           <none>
abc-site-1                                  0/4     ContainerCreating   0          3s    <none>           test21   <none>           <none>
```
Both master and site charts define _StatefulSet_ resources.
The problem is the name of the subchart pods are prefixed by parent pod name. I would like to ommit this.
Previously I used to access some services by DNS name like site-0 or master-1. Now this is not working any more.

Is it possible to skip prefixing subcharts pods by parent chart release name ?

**Comment by bacongobbler** [comment]
This depends on how the chart uses certain variables in their templates. Helm has no control over this, but the chart author does.

Have you looked into the templates of those charts?

**Comment by kaniapm** [comment]
I checked templates following suggestion from @bacongobbler 
I found the code generating pod and other resource names (located in **subchart** module _templates/_helpers.tpl_ file):
```go
{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "site.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}
```

Then I have updated the **parent** chart _values.yml_ file by adding the following snippet:
```yaml
site:
  fullnameOverride: site

master:
  fullnameOverride: master

inventory:
  fullnameOverride: inventory
```

and this solved my problem: now subchart pods names are not prefixed by parent chart release name.
```console
kubectl get pods
NAME                         READY   STATUS              RESTARTS   AGE   
inventory-75d7ff6bc6-zkxwv   0/1     ContainerCreating   0          5s    
master-0                     2/2     Running             0          5s
master-1                     2/2     Running             0          5s
site-0                       0/4     ContainerCreating   0          5s
site-1                       4/4     Running             0          5s
```
Thanks @bacongobbler  for your help.
