### ISSUE TITLE
when using configmap with map, it is causing indentation issue

### ISSUE THREAD

**Issue by kushalagrawal** [helm/helm#8374]
Hi,
I want to create configmap using a map of dynamic values. But it is causing indentation issue while generating configmap. Is there any way I can make this indentation proper. otherwise only first line goes to configmap. rest all are discarded.

**_values.yaml_**
```
pluginDetails:
    key1:value1
    key2:value2
    ......
     .....


```
**_and in my configmap:_**

```
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-plugin-details
data:
  plugin_data.yaml:
    {{ tpl .Values.pluginDetails . }}

```

output :
```
# Source: test-helm/templates/pluginDataConfigMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: open-quetzal-plugin-details
data:
  plugin_data.yaml:
    key1: value1
key2: value2
key3: value3
```
