### ISSUE TITLE
Config set in Master/Umbrella charts not propagated to Grandchildren - The Perfect Storm

### ISSUE THREAD

**Issue by rblaine95** [helm/helm#8385]
### This is an informational issue, not a bug report.
I found this when debugging a perfect storm and couldn't find any information online regarding it.

When you do the following 5 things, you create a perfect storm and you will have the above issue:
1. Using `apiVersion: v1` in `Chart.yaml`
2. Setting `dependencies: []` in `Chart.yaml`
3. Using Helm v3
4. Your chart is a Sub-chart of a Master/Umbrella Chart
5. Your chart has Children/Sub-charts of its own

For example:
Your chart, `someService`, is a sub-chart of `umbrella`.
Your chart is doing 1, 2, 4, and 5 of the list above.
Your chart also has a Child/Sub-chart for Postgres.

```yaml
# umbrella/Chart.yaml
apiVersion: v2
dependencies:
  - name: someService
    version: 1.2.3
    repository: file:///path/to/someService
    condition: someService.enabled
---
# umbrella/values.yaml
someService:
  enabled: true
  postgres:
    enabled: false
---
# /path/to/someService/Chart.yaml
apiVersion: v1
dependencies:
  - name: postgresql
    version: 0.15.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgres.enabled
---
# /path/to/someService/values.yaml
postgres:
  enabled: true
```

### Why does this happen?
When running `helm dep up` in `someService`, a `requirements.lock` file is generated and Postgres is packaged in `someService/charts/`
Following this by running `helm dep up` in `umbrella` causes a `Chart.lock` to be generated and `someService` is packaged in `umbrella/charts/`
If you untar the `umbrella/charts/someService.tgz`, the `requirements.lock` file is present, but there's no corresponding `requirements.yaml` and the `dependencies: []` field in `Chart.yaml` is missing (because `apiVersion: v1` doesn't support this field in this file)
Because there is no `dependencies: []` config in your chart anymore (but there are charts in `charts/`), all the config you set in `umbrella/values.yaml` for `someService.postgres` is dropped, but `someService.postgres` will still be installed.

### How do I fix this?
Upgrade to `apiVersion: v2`

### My helm info 
Output of `helm version`:
```
» helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```
Output of `kubectl version`:
```
» kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"archive", BuildDate:"2020-06-20T07:41:29Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS EKS
