### ISSUE TITLE
Enhancement: Support customization of un-rendered templates

### ISSUE THREAD

**Issue by musabmasood** [helm/helm#8395]
The new `--post-renderer` flag is great for last-mile modifications, mostly it is used with kustomize and overlays. 

However, many times we want to modify/add/delete a **template** from an upstream chart and still be able to use the values from the original `values.yaml`.

For instance, consider an upstream chart with a `ConfigMap` manifest:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
data:
  foo: {{.Values.foo}}
```

I would like to use this chart as a dependency but also add `bar: {{.Values.bar}}` to it:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
data:
  foo: {{.Values.foo}}
  bar: {{.Values.bar}}
```

Since this is just a YAML manifest, I should be able to do it with kustomize or any renderer.

This way, the sequence of rendering would be:

1. Collect all unrendered templates from the entire helm chart and subcharts
2. Apply kustomization to add/delete/modify/patch these templates
3. Render with values

I can't come with a good name but may be `--pre-render` would suit.
