### ISSUE TITLE
Can't create secret with helm

### ISSUE THREAD

**Issue by timam** [helm/helm#8397]
- I am converting my k8s IaaC into helm, I have a secret as following which works fine with `kubectl apply`
```
kind: Secret
apiVersion: v1
metadata:
  name: sit-helloworld-django
type: Opaque
stringData:
  DEBUG: "true"
  SECRET_KEY: "dert56*&67$=@_tb^7s8do_u$s34R$67HYlyorub1b8h&tg*93"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgresuser"
  POSTGRES_PASSWORD: "postgresuserpass"
  POSTGRES_HOST: "sit-helloworld-postgres"
  POSTGRES_PORT: "5432"
```
- After conversion, my helm template gets following look
```
kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Values.env }}-{{ $.Values.project}}-{{ .name }}
type: Opaque
stringData:
  DEBUG: "true"
  SECRET_KEY: {{ .secret_key }}
  POSTGRES_DB: {{ .dbname }}
  POSTGRES_USER: {{ .dbuser }}
  POSTGRES_PASSWORD: {{ .dbpass }}
  POSTGRES_HOST: {{ .dbhost }}
  POSTGRES_PORT: {{ .dbport }}
```
- Here is the value form Vars.yaml
```
djangomodules:
  helloworld-django:
    name: django
    replicas: 2
    containerPort:
    servicePort:
    dbname: postgres
    dbuser: postgresuser
    dbpass: postgresuserpass
    dbhost: sit-helloworld-postgres
    dbport: 5432
    secret_key: "dert56*&67$=@_tb^7s8do_u$s34R$67HYlyorub1b8h&tg*93"
```
- When I try to install/upgrade helm char I get following error
```
Error: UPGRADE FAILED: failed to create resource: Secret in version "v1" cannot be handled as a Secret: v1.Secret.StringData: ReadString: expects " or n, but found 5, error found in #10 byte of ...|ES_PORT":5432,"POSTG|..., bigger context ...|RES_PASSWORD":"postgresuserpass","POSTGRES_PORT":5432,"POSTGRES_USER":"postgresuser","SECRET_KEY":"d|...
```
- I have tried with {{ quote .secret_key }} [uncoated value form Values.yaml ] which gives me same result.
- I have tried with {{ .secret_key | quote }} [uncoated value form Values.yaml ] which gives me same result.

Output of `helm version`:
`version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS EKS

**Comment by wawa0210** [comment]
It looks like you are caused by the naming problem of your values.yaml key and cannot contain special characters, such as'-'

**Comment by hickeyma** [comment]
@timam There are a few things that I notice first off. The way you are trying to access values looks incorrect. To access values you usually start with `{{ .Values.`. As you are using nested values:

```yaml
djangomodules:
  helloworld-django:
    name: django
    replicas: 2
    containerPort:
    servicePort:
    dbname: postgres
    dbuser: postgresuser
    dbpass: postgresuserpass
    dbhost: sit-helloworld-postgres
    dbport: 5432
    secret_key: "dert56*&67$=@_tb^7s8do_u$s34R$67HYlyorub1b8h&tg*93"
```

you therefore need to reference each value starting with: `{{ .Values.djangomodules.helloworld-django`. Hence, the `name` value is referenced as: `{{ .Values.djangomodules.helloworld-django.name }}`. The same format would apply to other vales like `secret_key`, `dbname` etc. More information on values in [docs](https://helm.sh/docs/chart_best_practices/values/).

I am unsure what you are trying to reference with these: `{{ $.Values.env }}-{{ $.Values.project}}`. Maybe you can provide some details on them.

If you haven't had a chance I would suggest having a look through the [docs](https://helm.sh/docs/) to give a good insight into using Helm. To help you debug your rendered output you can add the following flags to install/upgrade commands: `--debug --dry-run`. It will show the rendered templates without deploying into the cluster.

**Comment by timam** [comment]
@hickeyma  I skipped few lines while pasting here. I am updating code now. 

> templates/secrets-django.yaml
```
{{- range .Values.djangomodules }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $.Values.env }}-{{ $.Values.project }}-{{ .name }}
  labels:
    app: {{ $.Values.env }}-{{ $.Values.project }}-{{ .name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ $.Values.env }}-{{ $.Values.project }}-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.env }}-{{ $.Values.project }}-{{ .name }}
    spec:
      containers:
        - name: {{ $.Values.env }}-{{ $.Values.project }}-{{ .name }}
          image: {{ $.Values.aws_account_id }}.dkr.ecr.{{ $.Values.region }}.amazonaws.com/{{ $.Values.env }}-{{ $.Values.project }}-{{ .name }}:1
          ports:
            - containerPort: {{ .containerPort }}
          envFrom:
            - secretRef:
                name: {{ $.Values.env }}-{{ $.Values.project }}-{{ .name }}
---
  {{- end}}

```

> values-sit.yaml
```
project: helloworld
env: sit
djangomodules:
  helloworld-django:
    name: django
    replicas: 2
    containerPort: 8000
    servicePort: 8000
    dbname: postgres
    dbuser: postgresuser
    dbpass: postgresuserpass
    dbhost: sit-helloworld-postgres
    dbport: 5432
    secret_key: "dert56*&67$=@_tb^7s8do_u$s34R$67HYlyorub1b8h&tg*93"
```

- Dry Run : ` helm upgrade --dry-run  sit-helloworld  -f ./values-sit.yaml ./`

> Output of Dry Run 
```
---
# Source: helm/templates/secrets-django.yaml
kind: Secret
apiVersion: v1
metadata:
  name: sit-helloworld-django
type: Opaque
stringData:
  DEBUG: "true"
  SECRET_KEY: "dert56*&67$=@_tb^7s8do_u$s34R$67HYlyorub1b8h&tg*93"
  POSTGRES_DB: postgres
  POSTGRES_USER: postgresuser
  POSTGRES_PASSWORD: postgresuserpass
  POSTGRES_HOST: sit-helloworld-postgres
  POSTGRES_PORT: 5432
---

```
