### ISSUE TITLE
Helm silently skips template if file is outside chart directory

### ISSUE THREAD

**Issue by carlosonunez** [helm/helm#8404]
Output of `helm version`: `version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}`

Output of `kubectl version`: 

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:57:29Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:45Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): local k3s

Hi there! Long time lurker, first-time Helm user.

I tried to provision `Secret`s that get generated from an environment dotfile. The template I created looks like this:

```yaml
# ./helm/templates/secrets.yaml
{{- range .Files.Lines ".env.test" }}
{{- $key := regexReplaceAll "^([A-Z0-9_]+)=" . "$1" }}
{{- $value := replace (printf "%s=" $key) "" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{- printf "%s-secret" (lower $key) }}
type: Opaque
data:
  value: {{- $key }}
{{- end }}
```

I have two other templates in my chart that render correctly.

When I run `helm template <chart_name> <chart_path>`, I see the other two templates rendered correctly in the output but `secrets.yaml` is missing entirely:

```yaml
---
# Source: hello-azure/templates/hello_azure_svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-azure
  labels:
    app: hello-azure
spec:
  selector:
    app: hello-azure
  ports:
    - port: 80
      protocol: TCP
---
# Source: hello-azure/templates/hello_azure_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-azure
  labels:
    app: hello-azure
    release: hello-azure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-azure
  template:
    metadata:
      labels:
        app: hello-azure
    spec:
      containers:
        - name: hello-azure-webserver
          image: hello-azure
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
```

However, if I remove `Files.Lines` from my secrets and replace the `$key` and `$value` variables with fixed dummy strings, it shows up:

```yaml
# secrets.yaml, modified
{{- $key := "Foo" }}
{{- $value := "Bar" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "Foobar"
type: Opaque
data:
  value: {{- $key }}

```

Output:

```yaml
---
# Source: hello-azure/templates/hello_azure_secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "Foobar"
type: Opaque
data:
  value:Foo
---
# Source: hello-azure/templates/hello_azure_svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-azure
  labels:
    app: hello-azure
spec:
  selector:
    app: hello-azure
  ports:
    - port: 80
      protocol: TCP
---
# Source: hello-azure/templates/hello_azure_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-azure
  labels:
    app: hello-azure
    release: hello-azure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-azure
  template:
    metadata:
      labels:
        app: hello-azure
    spec:
      containers:
        - name: hello-azure-webserver
          image: hello-azure
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
```

Am I missing something?
