### ISSUE TITLE
Failure in interpolating values.yaml variables into the data copied from .Files object 

### ISSUE THREAD

**Issue by sanamsarath** [helm/helm#8407]
Hello,

I am trying to pass the configmap data using files, and the issue is that the helm variables from values.yaml are not being substituted into the data defined in the files. I am not sure if the substitution is failing because of the scope of variables not valid in the .Files object or not. Following are the template files and output

template file:
```
{{- $files := .Files }}
{{- range $path, $bytes := .Files.Glob "*.yaml" }}
{{- $filename := trimSuffix (ext $path) (base $path) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-test
  namespace: {{ $.Release.Namespace }}
data:
  {{ base $path }}: |-
  {{ $files.Get $path | trim | indent 4 }}
---
{{- end }}
```

capture-test-agent.yaml:
```
test: {{ .Values.port }}
```
values.yaml
```
port: "9890"
```
Output:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-test
  namespace: default
data:
  capture-test-agent.yaml: |-
        test: {{ .Values.port }} <-- this is not being substituted
```
expected output:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-test
  namespace: default
data:
  capture-test-agent.yaml: |-
        test: 9890
```

Thanks.
