### ISSUE TITLE
Conditional dependencies works only when specified in requirements.yaml and not in charts.yaml

### ISSUE THREAD

**Issue by pjastrzabek** [helm/helm#8417]
**Output of `helm version`:**
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}

**Output of `kubectl version`:**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:57:24Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

minikube

I tried to use conditional helm dependency and it seems that it works only if dependency is specified in requirements.yaml file.
If I move it to charts.yaml it's ignored (so dependency is always installed)

A lot of documentation not directly, but suggests that dependencies can be specified in chart.yaml file
For example here: https://helm.sh/docs/helm/helm_dependency/

But conditional expression seems to not work in such case.

Is it a bug and if so. Is it in helm or rather documentation could be improved?

**Comment by pjastrzabek** [comment]
To be more specific.

This is my values.yaml

mysql:
  nameOverride: db
  root:
    password: xxx
  enabled: false

and requirements.yaml

dependencies:
  - name: mysql
    condition: mysql.enabled
    alias: helmmysql
    version: ~6.14.4
    repository: https://charts.bitnami.com/bitnami

In such setup all works (dependency is not installed as value of mysql.enabled is false)

If I move dependencies section to charts.yaml dependency is installed **always**.

**Comment by jeff-knurek** [comment]
@pjastrzabek I wasn't able to reproduce. I used the same values that you provided, but maybe the problem is a yaml formatting issue _(it's hard to tell without the formatting in your github post)_.

I have a `Chart.yaml` with the following:
```yaml
apiVersion: v2
name: my-test
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: mysql
    condition: mysql.enabled
    alias: helmmysql
    version: ~6.14.4
    repository: https://charts.bitnami.com/bitnami
```
and the `values.yaml` file with this, where i turn on/off the mysql.enabled 
```yaml
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

mysql:
  enabled: false
  nameOverride: db
  root:
    password: xxx
```

and I run `helm install example my-test` and in between disabling/enabling the dependency I delete the release: `helm delete example`
