### ISSUE TITLE
[bug] Secrets added by pre-upgrade hook are deleted even though they shouldn't

### ISSUE THREAD

**Issue by deiga** [helm/helm#8420]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:13:57Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
EKS
```

### Situation:
We have a couple of Secrets that are generated by a `pre-install,pre-upgrade` hook with this configuration:
```
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: bar-gcr-secret-{{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: keep
data:
  .dockerconfigjson: lorem ipsum
```

This secret is required by Pods both in the pre-install phase as well as the actual install phase.

### Issue: 
After the pre-install phase is done all the Secrets generated by hooks are being deleted. Even though the delete policy does not specify that they should be.

Here is a debug log from when this happens
```
history.go:52: [debug] getting history for release foo
walk.go:74: found symbolic link in path: /home/jenkins/workspace/Deployments/mozart/qa/helm/mozart/charts/mozart-common resolves to /home/jenkins/workspace/Deployments/mozart/qa/helm/mozart-common
walk.go:74: found symbolic link in path: /home/jenkins/workspace/Deployments/mozart/qa/helm/mozart/static/nginx/fastcgi_params resolves to /home/jenkins/workspace/Deployments/mozart/qa/docker/resources/etc/nginx/fastcgi_params
walk.go:74: found symbolic link in path: /home/jenkins/workspace/Deployments/mozart/qa/helm/mozart/static/nginx/nginx.conf resolves to /home/jenkins/workspace/Deployments/mozart/qa/docker/resources/etc/nginx/nginx.conf
walk.go:74: found symbolic link in path: /home/jenkins/workspace/Deployments/mozart/qa/helm/mozart/static/nginx/request_uuid.conf resolves to /home/jenkins/workspace/Deployments/mozart/qa/docker/resources/etc/nginx/request_uuid.conf
walk.go:74: found symbolic link in path: /home/jenkins/workspace/Deployments/mozart/qa/helm/mozart/static/php/php.ini resolves to /home/jenkins/workspace/Deployments/mozart/qa/docker/resources/usr/local/etc/php/php.ini
walk.go:74: found symbolic link in path: /home/jenkins/workspace/Deployments/mozart/qa/helm/mozart/static/squarespace/squarespaceInitializer.json resolves to /home/jenkins/workspace/Deployments/mozart/qa/config/mockserver/squarespaceInitializer.json
upgrade.go:121: [debug] preparing upgrade for foo
upgrade.go:129: [debug] performing update for foo
upgrade.go:308: [debug] creating upgraded release for foo
client.go:258: [debug] Starting delete for "foo-env-sensitive" Secret
client.go:108: [debug] creating 1 resource(s)
client.go:258: [debug] Starting delete for "bar-gcr-secret-foo" Secret
client.go:108: [debug] creating 1 resource(s)
client.go:258: [debug] Starting delete for "predeploy-render-test-learning-card" Job
client.go:108: [debug] creating 1 resource(s)
client.go:467: [debug] Watching for changes to Job predeploy-render-test-learning-card with timeout of 20m0s
client.go:495: [debug] Add/Modify event for predeploy-render-test-learning-card: ADDED
client.go:534: [debug] predeploy-render-test-learning-card: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:495: [debug] Add/Modify event for predeploy-render-test-learning-card: MODIFIED
client.go:534: [debug] predeploy-render-test-learning-card: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:495: [debug] Add/Modify event for predeploy-render-test-learning-card: MODIFIED
client.go:173: [debug] checking 14 resources for changes
client.go:440: [debug] Looks like there are no changes for Secret "basic-auth-foo"
client.go:440: [debug] Looks like there are no changes for ConfigMap "foo-dd"
client.go:440: [debug] Looks like there are no changes for ConfigMap "foo-health"
client.go:440: [debug] Looks like there are no changes for ConfigMap "foo-nginx-config"
client.go:440: [debug] Looks like there are no changes for ConfigMap "foo-nginx-site"
client.go:440: [debug] Looks like there are no changes for ConfigMap "foo-php-fpm-config"
client.go:440: [debug] Looks like there are no changes for ConfigMap "foo-php-ini-config"
client.go:440: [debug] Looks like there are no changes for Service "foo"
client.go:440: [debug] Looks like there are no changes for Service "foo-php-fpm-exporter"
client.go:440: [debug] Looks like there are no changes for Ingress "foo"
client.go:222: [debug] Deleting "foo-env-sensitive" in web-services-qa...
client.go:222: [debug] Deleting "bar-gcr-secret-foo" in web-services-qa...
wait.go:53: [debug] beginning wait for 14 resources with timeout of 20m0s
```

### Workaround:

The current "solution" is to set `helm.sh/resource-policy: keep` in the Secrets, but at least how I understand it this is not the intended way.

**Comment by bacongobbler** [comment]
Can you provide a sample chart along with a set of steps we can use to reproduce the issue? Thanks.

**Comment by hickeyma** [comment]
@deiga Was this answered in #helm-users channel in https://app.slack.com/client/T09NY5SBT/C0NH30761/thread/C0NH30761-1594212959.320100:

"normally hooks should get their own exclusive resources/secrets and don't leaving anything around since then you get annoying versioning problems when you start changing those"

**Comment by deiga** [comment]
@hickeyma Well, I don't know. The docs make it seem like Resources generated by hooks would not be cleaned up, but the code is clearly deleting them.

Either this is a bug in the code or the documentation is wrong.

**Comment by deiga** [comment]
> Can you provide a sample chart along with a set of steps we can use to reproduce the issue? Thanks.

I can try, but no promises. The next coming weeks are going to be super busy for me

**Comment by trilitheus** [comment]
I'm seeing the exact same issue except with configmaps.

```
$ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
I use a pre-install.pre-upgrade hook to create a configmap that is used by a pre-install hook created job.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "releaseName" . }}-db-yml
  labels:
    app: {{ template "releaseName" . }}-db-yml
    chart: {{ include "this.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"                                                                                              
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  {{- (.Files.Glob "conf/database.yml").AsConfig | nindent 2 }}
```

These are used to run rails migrations so the db.yml etc needs to be in place before the job runs - this is fine, but then when the main chart installation is performed, the configmaps are deleted so the main rails pod can;t start due to having no `database.yml` configmap available to mount as a volume

I don't want to do this with initContainers as I don't want migrations to run when a pod is terminated and restarted, only on initial install or upgrade.
