### ISSUE TITLE
How can i defaulting items of .Values.yaml if it's not set, like this

### ISSUE THREAD

**Issue by zhb127** [helm/helm#8434]
This is my original issue: https://github.com/helm/helm/issues/8406, Sorry, did not clearly describe my needs。I test:
```
# _helpers.tpl
{{ default “test value” .Values.xxx }}

# deployment.yaml
metadata:
  labels:
    app: {{ include "metadataLabelsApp" . }}
    appgroup: {{ include "metadataLabelsAppGroup" . }}
    xxx: {{ .Values.xxx }}
```

debug output:

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: RELEASE-NAME
  labels:
    app: RELEASE-NAME
    appgroup: RELEASE-NAME
    xxx:
```

![image](https://user-images.githubusercontent.com/5210208/87265330-1b2a2580-c4f5-11ea-9c02-87e44c758925.png)

How can i defaulting items of .Values.yaml if it's  not set, like this:

```
# Values.yaml
# cpu: 200m
# memory: 200Mi

# _helper.tpl
{{ default "500m" $.Values.cpu }}
{{ default "1Gi" $.Values.memory }}

# deployment.yaml
cpu: {{ .Values.cpu }}   # here, use .Values.cpu safely, no need using default statement
memory: {{ .Values.cpu }} # here, use .Values.cpu safely, no need using default statement

# statefulset.yaml
cpu: {{ .Values.cpu }}   # here, use .Values.cpu safely,  no need using default statement
memory: {{ .Values.cpu }} # here, use .Values.memory safely, no need using default statement
```

**So, I can use .Values.xxx safely, don't care if it's  set(because i have set the default value for it in the _helper.tpl)**

Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:50:54Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Minikube
