### ISSUE TITLE
[helm-3.3.0-rc.1] Helm Lint fails due to blank resource name

### ISSUE THREAD

**Issue by rblaine95** [helm/helm#8467]
I've got a helm chart which uses internal Helm Libraries to initialize a Database and User in a DB Cluster as a pre-install hook.
```yaml
# templates/pg-job.yaml
{{- if .Values.pgJob.enabled }}
  {{- include "zenlibs.pgJob" (list . .Values.pgJob) }}
{{- end }}

# values.yaml
[...]
pgJob:
  enabled: true
  init: true
  clean: true
  admin:
    secret:
      name: dev-aurora
  host: *pgHost
  port: 5432
  version: 10.7
```
Brief output of `helm template example .`
```yaml
# Source: example/templates/pg-job.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-secret-role
[...]
# Source: example/templates/pg-job.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-secret-rolebinding
[...]
# Source: example/templates/pg-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example-initpg
[...]
# Source: example/templates/pg-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example-cleanpg
[...]
```
Output of `helm lint`
```sh
==> Linting .
[ERROR] templates/pg-job.yaml: object name does not conform to Kubernetes naming requirements: ""

Error: 1 chart(s) linted, 1 chart(s) failed
```

`helm lint` succeeds if I use `helm lint --set pgJob.enabled=false`

### Extra Info

Output of `helm version`:
```sh
» helm version
version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}
```

Output of `kubectl version`:
```sh
» kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"archive", BuildDate:"2020-07-01T16:28:46Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS EKS

**Comment by mattfarina** [comment]
@rblaine95 I tried to reproduce this but failed to. I created a chart with only a `_helpers.tpl` file and the following template:

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "example.fullname" . }}-role
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "example.fullname" . }}-rolebinding
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "example.fullname" . }}-initpg
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "example.fullname" . }}-cleanpg
```

The chart was created using the command `helm create example` and I used v3.3.0-rc.1 for all of this.

When running `helm lint` I was unable to reproduce the issue. I wonder if the problem is in the `[...]` that you didn't share (and may not be able to). Or, if the actual name has an issue. The [names need to be safe for [DNS](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names). Helm does it's checking for this with the same [regular expression](https://github.com/helm/helm/blob/6a536661fcf1dc0315798ece70bbf193e725945c/pkg/lint/rules/template.go#L46) Kubernetes uses.

**Comment by hickeyma** [comment]
@rblaine95 It might be worth running `helm install` with the `--dry-run --debug`. It might some more in the rendering and it doesn't install it in the cluster.

**Comment by rblaine95** [comment]
Hi @mattfarina, thank you for responding.
I mainly omitted the extra stuff in `[...]` because it was just additional metadata (labels and annotations) and because I wanted to keep it short and concise.

Here's some extra output:
```yaml
---
# Source: example/templates/pg-job.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-secret-role
  labels:
    helm.sh/chart: example-0.1.0
    app.kubernetes.io/name: example
    app.kubernetes.io/instance: example
    app: example
    app.kubernetes.io/version: "10.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-99"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
# Source: example/templates/pg-job.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-secret-rolebinding
  labels:
    helm.sh/chart: example-0.1.0
    app.kubernetes.io/name: example
    app.kubernetes.io/instance: example
    app: example
    app.kubernetes.io/version: "10.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-99"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: example-secret-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: example/templates/pg-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example-initpg
  labels:
    helm.sh/chart: example-0.1.0
    app.kubernetes.io/name: example
    app.kubernetes.io/instance: example
    app: example
    app.kubernetes.io/version: "10.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-90"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        helm.sh/chart: example-0.1.0
        app.kubernetes.io/name: example
        app.kubernetes.io/instance: example
        app: example
        app.kubernetes.io/version: "10.0.0"
        app.kubernetes.io/managed-by: Helm
[...]
---
# Source: example/templates/pg-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example-cleanpg
  labels:
    helm.sh/chart: example-0.1.0
    app.kubernetes.io/name: example
    app.kubernetes.io/instance: example
    app: example
    app.kubernetes.io/version: "10.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-weight: "90"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        helm.sh/chart: example-0.1.0
        app.kubernetes.io/name: example
        app.kubernetes.io/instance: example
        app: example
        app.kubernetes.io/version: "10.0.0"
        app.kubernetes.io/managed-by: Helm
[...]
```

It's likely I may be doing something stupid in the Library `zenlibs.pgJob`, but the rendered templates all look good to me and should pass lint :thinking:
Maybe I made some stupid mistake in the lib and that's causing the lint issue. ᴰᵒⁿ'ᵗ ᵗᵉˡˡ ᵃⁿʸᵒⁿᵉ ᵇᵘᵗ ᴵ'ˡˡ ᵗᵃˡᵏ ᵗᵒ ᵐʸ ᵃʳᶜʰᶦᵗᵉᶜᵗ ᵗᵒᵐᵒʳʳᵒʷ ʳᵉᵍᵃʳᵈᶦⁿᵍ ᵗʰᵉ ᵖᵒˢˢᶦᵇᶦˡᶦᵗʸ ᵒᶠ ᵒᵖᵉⁿ⁻ˢᵒᵘʳᶜᶦⁿᵍ `ᶻᵉⁿˡᶦᵇˢ`

**Comment by rblaine95** [comment]
Hi @hickeyma, running `helm install example --dry-run --debug .` prints out the templates and no errors.

**Comment by rblaine95** [comment]
When using Helm v3.2.4 to do an install, everything goes through normally - pre-install hooks run, app gets deployed, pre-install hooks get cleaned
Same goes for doing a delete - everything gets removed, post-delete hooks run and get cleaned up.

But, when using Helm v3.3.0-rc.1, things don't work properly.
Pre-install hooks run, then the application gets installed, then the pre-install and post-delete hooks run at the same time.

Did something change with helm hooks in 3.3?

**Comment by mattfarina** [comment]
@rblaine95 please let me know if you can open source the chart. It will make debugging easier.

If you are running an install, the `post-delete` hooks SHOULD NOT be running. yikes.

**Comment by rblaine95** [comment]
@mattfarina, think it might be a Helm 3.3 bug?

**Comment by rblaine95** [comment]
@mattfarina 
I was experimenting with shrinking the scope to see what the issue was (whether it was the Jobs or the Roles)
It looks like the issue may be with the Roles in the util.
If I set the following:
```yaml
# values.yaml
rbac:
  enabled: true

pgJob:
  enabled: true
  init: false
  clean: false
  debug: false
```
Then the Jobs won't render, but the Roles, which give the default service account permission to Create Secrets in the Release Namespace, still render.
Linting fails.
If I comment out the call to the Roles (so they aren't rendered), then linting passes.

```yaml
# templates/charts/zenlibs/templates/_pg-job.yaml
{{- define "zenlibs.pgJob" -}}
{{- $ctx := index . 0 }}
{{- $config := index . 1 }}
{{- if $ctx.Values.rbac.enabled }}
{{- include "zenlibs.container.secret.rbac" (list $ctx true) }}
{{- end }}
[...]

# templates/charts/zenlibs/templates/_utils.tpl
{{- define "zenlibs.container.secret.rbac" -}}
{{- $ctx  := index . 0 -}}
{{- $pre  := index . 1 -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zenlibs.fullname" $ctx }}-secret-role
  labels:
    {{- include "zenlibs.labels" $ctx | nindent 4 }}
  {{- if $pre }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-99"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zenlibs.fullname" $ctx }}-secret-rolebinding
  labels:
    {{- include "zenlibs.labels" $ctx | nindent 4 }}
  {{- if $pre }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-99"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  {{- end }}
subjects:
- kind: ServiceAccount
  {{- if $pre }}
  name: default
  {{- else }}
  name: {{ include "zenlibs.serviceAccountName" $ctx }}
  {{- end }}
  namespace: {{ $ctx.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "zenlibs.fullname" $ctx }}-secret-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
```
Removing the Roles seems to fix the Linting issue.

Some of the other utils (`zenlibs.fullname`, `zenlibs.serviceAccountName`, `zenlibs.labels`) are straight from `helm create zenlibs` to generate the `_helpers.tpl`

**Comment by mattfarina** [comment]
@rblaine95 Thanks for putting in the effort to narrow it down to roles. We will have to dig more deeply on this. I'm considering this a release blocker of 3.3.0. We need to make sure it's not an issue in Helm somewhere.

**Comment by rblaine95** [comment]
If I delete the `{{- include "zenlibs.container.secret.rbac" (list $ctx true) }}` line and replace it with the Role and RoleBinding, linting passes :thinking:

**Comment by technosophos** [comment]
It may be possible that somehow an empty YAML document was being created, and the first lint rule to trigger was the name checker. An empty YAML document (e.g. between an `---` or `===`) will pass the parsing validation check, but would definitely fail every subsequent check.

**Comment by rblaine95** [comment]
@technosophos, your comment got me thinking that it might be a ghost new-line causing Helm to automatically insert a `---` when Linting (but not when Templating)

```go
// this passes linting
{{- define "zenlibs.pgJob" -}}
{{- $ctx := index . 0 -}}
{{- $config := index . 1 -}}
{{- $ns := $ctx.Release.Namespace -}}
{{- if $ctx.Values.rbac.enabled -}}
{{- include "zenlibs.container.secret.rbac" (list $ctx true) }}
{{- end }}
[...]

// this fails linting
{{- define "zenlibs.pgJob" -}}
{{- $ctx := index . 0 }}
{{- $config := index . 1 }}
{{- $ns := $ctx.Release.Namespace }}
{{- if $ctx.Values.rbac.enabled }}
{{- include "zenlibs.container.secret.rbac" (list $ctx true) }}
{{- end }}
[...]
```

**Comment by technosophos** [comment]
Have you ran `helm template` on that segment above to see what it outputs? Lint's parsing is definitely more primitive than other areas of Helm. (It tends to not do any error correction so that it can find flaws). So it is possible that where Helm will normally ignore something, Lint might get snagged on it.

**Comment by mattfarina** [comment]
@technosophos might be worth updating the name check to validate it has content before running the regex on it.

**Comment by technosophos** [comment]
Here's what it currently does:

1. Check to see if the content is non-empty (after trimming whitespace)
2. Parses it with a YAML parser, populating a very minimal struct
3. Checks the struct for the name field
4. Checks for deprecations
5. Validates selectors on some types

So the template is non-empty, but the output is non-conformant. I am trying to reproduce given the info above. But without seeing what the problematic data is, it's hard to construct an exception or alternate handling.

**Comment by technosophos** [comment]
@rblaine95 If you feel comfortable compiling Helm, I built a version that will print out each template before it sends it into the linter. I'm using it now to try to reproduce what you are encountering. But you might be able to spot things faster on your end.

Here's the branch:

https://github.com/technosophos/k8s-helm/tree/fix/8467-linter-failing

I'll keep updating here if I find anything else new.

**Comment by rblaine95** [comment]
@technosophos 
```sh
» ../helm-debug version
version.BuildInfo{Version:"v3.3+unreleased", GitCommit:"4dfde2818d601c128ef73ae65e1fb92349e90f18", GitTreeState:"clean", GoVersion:"go1.14.5"}

```
```yaml
# » ../helm-debug lint
walk.go:74: found symbolic link in path: /home/robert/zenaptix/helm/example/charts/zenlibs resolves to /home/robert/zenaptix/helm/zenlibs
Template templates/pg-job.yaml: 
  apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-secret-role
  labels:
    helm.sh/chart: example-0.1.0
    app.kubernetes.io/name: example
    app.kubernetes.io/instance: test-release
    app: example
    app.kubernetes.io/version: "10.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-99"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-secret-rolebinding
  labels:
    helm.sh/chart: example-0.1.0
    app.kubernetes.io/name: example
    app.kubernetes.io/instance: test-release
    app: example
    app.kubernetes.io/version: "10.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-99"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
subjects:
- kind: ServiceAccount
  name: default
  namespace: yourproject
roleRef:
  kind: Role
  name: example-secret-role
  apiGroup: rbac.authorization.k8s.io
```
Looks like the `apiVersion: v1` of the Role is indented :thinking:
Which explains why doing the following fixed it
```go
{{- define "zenlibs.pgJob" -}}
{{- $ctx := index . 0 -}}           // adding the -}} fixes the lint
{{- $config := index . 1 -}}        // adding the -}} fixes the lint
{{- if $ctx.Values.rbac.enabled -}} // adding the -}} fixes the lint
{{- include "zenlibs.container.secret.rbac" (list $ctx true) }}
{{- end }}
```

**Comment by mattfarina** [comment]
The `-` next to `{{` or `}}` tells the template engine to remove all whitespace next to the brackets. So...

`foo {{- "bar" }}` would be `foobar` while `foo {{ "bar" }}` would be `foo bar`. The `{{-` removes the whitespace to the left of it... the space between the `o` and the `{{-`.

So, use the `-` when you want the whitespace removed.

**Comment by mattfarina** [comment]
@rblaine95 Did fixing the YAML cause normal `helm lint` to pass as well?

**Comment by rblaine95** [comment]
@mattfarina, [yes](https://github.com/helm/helm/issues/8467#issuecomment-660904098), adding the `-}}` fixed the normal helm lint as well.

**Comment by technosophos** [comment]
I think I will try modifying the linter to provide an error when apiVersion is not found. That should definitely be the first thing that fails a lint, and I am not sure we check that

**Comment by technosophos** [comment]
Ah! Okay, I found the issue. The package `k8s` gets this YAML:

```yaml
  apiVersion: v1
kind: Pod
metadata:
    name: foo
```

And parses it into this result:

```go
rules.K8sYamlStruct{
  APIVersion:"v1", 
  Kind:"", 
  Metadata:rules.k8sYamlMetadata{
    Namespace:"",
    Name:"",
  }
}
```

So the parser figures out the indent depth by the first line, and seemingly ignores all content outdented from there. I think the linter is right to catch this case... but clearly we need a better error message.

It appears that in at least some parts of Helm, we to a `strings.TrimWhitespace()` on YAML docs prior to parsing, which we actually shouldn't do... but which in this case actually saves us from an error. I'm definitely not going to change any of those. But we might have other bugs in Helm related to this sort of thing.

**Comment by technosophos** [comment]
@mattfarina I created a PR here: #8496 But I don't know if this issue is considered blocking for 3.3. Feel free to set which release you want it on.

**Comment by mattfarina** [comment]
I don't think this should block 3.3.0 going out. I'll review the PR over there.

Thanks for jumping on a fix so quickly @technosophos

**Comment by mattfarina** [comment]
@rblaine95 are you still having an issue with the `post-delete` hook?

**Comment by rblaine95** [comment]
@mattfarina, I completely forgot about the `pre-install` and `post-delete` hooks issue, thank you for reminding me

I just ran a test install with
```
» ../helm version
version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}
```
The pre-install hooks run properly.
As soon as they succeed, they get cleaned up. (`helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded`)
Then the app deployment, as well as the `pre-install`, and `post-delete` hooks all run simultaneously.

When running `helm delete`, the app deployment and `post-delete` hooks are deleted, then the `post-delete` hook is run again and the floating `pre-install` hook that ran on after the `pre-install` succeeded is left floating.
```yaml
---
# Source: example/templates/pg-job.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-secret-role
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-99"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
[...]
---
# Source: example/templates/pg-job.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-secret-rolebinding
  labels:
    standard-helm-labels: "true"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-99"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
[...]
---
# Source: example/templates/pg-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example-initpg
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-90"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
[...]
---
# Source: example/templates/pg-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example-cleanpg
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-weight: "90"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
[...]
```
Running the same install with
```
» h3v version 
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```
Everything runs as expected
