### ISSUE TITLE
Issues with values.yaml when list of values is at root level

### ISSUE THREAD

**Issue by tehleet** [helm/helm#8494]
Hey, I have such yaml

```YAML
- id: id1
  name: "item1"
  some-item: "yes"
- id: id2
  name: "item2"
  some-item: "epic"
- id: id3
  name: "item3"
  some-item: "no"
```
when I try to generate template **(template code doesn't matter in this case)**
`helm template path/to/chart -f my_values.yaml` I get error
```BASH
Error: failed to parse test.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type map[string]interface {}
```
Problem is that I get this yaml autogenerated and I would need to do some formatting to make it work, maybe I'm missing something? See example below with working yaml structure

If I change my yaml to this, it works
```YAML
top:
- id: id1
  name: "item1"
  some-item: "yes"
- id: id2
  name: "item2"
  some-item: "epic"
- id: id3
  name: "item3"
  some-item: "no"
```

Output of `helm version`:
```BASH
version.BuildInfo{Version:“v3.2.1”, GitCommit:“fe51cd1e31e6a202cba7dead9552a6d418ded79a”, GitTreeState:“clean”, GoVersion:“go1.13.10"}
```
