### ISSUE TITLE
helm repo breaking on version 'y' interpreted as bool in LoadIndexFile() (pkg/repo/index.go)

### ISSUE THREAD

**Issue by robrys** [helm/helm#8531]
### Example files to reproduce
I have the following two example index.yaml files stored locally.

At /tmp/index-empty.yaml:
```
apiVersion: v1
entries:
generated: 2020-01-01T01:23:45.678912Z
```

At /tmp/index-versiony.yaml
```
apiVersion: v1
entries:
  fakeapp:
    - apiVersion: v1
      appVersion: "1.0"
      created: 2020-01-01T01:23:45.678912Z
      description: A Fake Helm Chart
      digest: 00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff
      name: fakeapp
      urls:
      - https://fake.url.com:443/helm/fakeapp-y.tgz
      version: y
generated: 2020-01-01T01:23:45.678912Z
```

And an example program to show the issue:
```
package main

import (
        "fmt"
        "helm.sh/helm/v3/pkg/repo"
)

func main() {
        _, noErr := repo.LoadIndexFile("/tmp/index-empty.yaml")
        fmt.Printf("No error from an empty index.yaml file:\n\t%v\n", noErr)
        _, versionErr := repo.LoadIndexFile("/tmp/index-versiony.yaml")
        fmt.Printf("Error from index.yaml file with an entry of 'version: y':\n\t%s\n", versionErr.Error())
}
```

# Example output/error/issue

The program produces the following output:
```
No error from an empty index.yaml file:
        <nil>
Error from index.yaml file with an entry of 'version: y':
        error unmarshaling JSON: while decoding JSON: json: cannot unmarshal bool into Go struct field ChartVersion.entries.version of type string
```

# Risk
This has the potential to be very dangerous.

If someone publishes a chart with version `y` accidentally (or intentionally), then all helm commands using that repo would fail as the index.yaml file is now un-loadable.

`version: n` seems to have the same effect, and potentially there are other strings that may act this way.

# Versions
With the example code above, I've just run `go mod init` and `go mod vendor`, which results in the following `go.mod` file:
```
$ cat go.mod 
module indexissue

go 1.14

require helm.sh/helm/v3 v3.2.4
```
