### ISSUE TITLE
[feature request] `helm packages` command to support an extra namespace in requirements.yaml/Chart.yaml

### ISSUE THREAD

**Issue by rimusz** [helm/helm#8537]
We have released Chartcenter.io which is a central immutable helm repository for 250+ helm repos.
Using it, it brings an extra name space which is a name of helm repository, and you do not need to add many helm repos but just only one, e.g.:

```
helm repo add center https://repo.chartcenter.io
helm repo up
helm install postgresql center/bitnami/postgresql
```
from example above we see an extra namespace `bitnami`.

All helm commands as `install/upgrade/pull/dependency` understand an extra namespace well, and work without issues.
The issue is with `helm package`, an example requirements.yaml file:

```
dependencies:
- name: bitnami/postgresql
  version: 8.7.3
  repository: https://repo.chartcenter.io
  condition: postgresql.enabled
- name: stable/rabbitmq-ha
  version: 1.46.4
  repository: https://repo.chartcenter.io
  condition: rabbitmq-ha.enabled
- name: bitnami/rabbitmq
  version: 7.4.3
  repository: https://repo.chartcenter.io
  condition: rabbitmq.enabled
```

`helm dependency` pulls all the files and stores in `charts` folder without issues, but then running `helm package` error gets shown:
```
Error: found in Chart.yaml, but missing in charts/ directory: bitnami/postgresql, bitnami/redis, bitnami/rabbitmq
```

I think the ideal fix would be to ignore in `helm dependency` the first namespace and `/` `- name: bitnami/postgresql` so the rest of helm commands do not need any patching.

To overcome the issue I have created the helm [plugin](https://github.com/jfrog/chartcenter-plugin), which of course can be used with helm v2 all time as helm v2 doesn't accept any new features.
For helm v3 the fix for `helm dependency` would be a welcome solution.
