### ISSUE TITLE
Backward-compatible proposal to pass values to sub-charts by supporting value constraints

### ISSUE THREAD

**Issue by jorgecarleitao** [helm/helm#8576]
This is a proposal to extend Helm 3 in a backward compatible manner to support passing arbitrary values to subcharts without requiring developers to expose them on `values.yaml` or as globals. This is resolved as a consequence of the broader problem that this proposal addresses: add support to pass transformed/mapped values to `.Values`.

This proposal allows:

* chart developers to hint to chart users that some values are not intended to be overwriten, by removing them from `values.yaml`.
* pass values to sub-charts that are _derived_ from `values.yaml` (example below)
* improve chart's API by not asking users to use anchors or copy-pasting values passed to `helm create ...`.

In summary, this allows chart developers to have full discretion over the API that they want to expose in `values.yaml`, by hiding implementation detail currently on `values.yaml` to a different place.

# Specification

Introduce a new optional reserved file in a chart, `map.yaml`, on the root of the chart (same level as `Chart.yaml`) that:

1. is (in-memory) templated using all values passed via `values.yaml`, `--set`, etc.
2. is (in-memory) merged to `values.yaml` before all values are passed to `.Values`

when users call any `helm` commands that require rendering.

`map.yaml` uses the same syntax as any other template, and is expected to be rendered to a normal `yaml` file, like `values.yaml`. It's primary goal is to offer developers the opportunity to map/transform any value in `values.yaml` to a set of new values that are required by the chart.

For example, if `map.yaml` contains `sub.a: {{ print "%s-%s" .Values.b .Values.c }}`, `.Values.sub.a` equals `{b}-{c}` where `{b}` and `{c}` are the values passed by either `values.yaml` or `--set b= --set c=`.

When templating `map.yaml`, `.Values` is populated according to the same precedence rules of other templates (priority is given to values passed by the user over the ones in `values.yaml`).

A chart's `.Values.valueX` is populated according to the following precedence (higher takes priority):

1. `valueX` provided by the user (e.g. via `--set valueX`)
2. `valueX` rendered on `map.yaml` when that key is defined in `map.yaml` and `map.yaml` exists in the chart
3. `valueX` on `value.yaml`

This precedence applies equally to both a chart's main templates with subchart's templates. Specifically, subchart's that have a `map.yaml` use their `map.yaml` to populate their own `.Values` (together with whatever was passed by the parent chart).

# Motivation

Chart developers that use a subchart often specialize the subchart by requiring specific values to be passed to the subchart in order for the whole deployment to work as intended (a value constraint). Currently, chart developers have two ways to achieve this:

* add an entry `subchart: ...` to the chart's `values.yaml`
* refactor the subchart to use `globals` and use `globals` on `values.yaml`

These two approaches suffer from two distinct but fundamental limitations:

* `globals` are prone to naming collision across charts, both vertically (a chart with 5 sub-charts) and in depth (sub-chart of subchart of subchart).
* `subchart` requires the chart to expose all options to its user, even if some of them are not intended to be changed or break if changed. I.e. it does not allow the `subchart` to be an implementation detail of the parent chart.

The problem of passing values to sub-charts can be summarized as value constraints: a value passed to a sub-chart is often not independent, but derived from (constrained by) other values.

For simple charts, chart developers address value derivations through templates: create a named template that constructs a new value `Y` based on `.Values.X` and use the template throughout the chart. For subcharts, they do not have a mechanism to address this, and instead have to ask the chart's userto address it themselves (or use globals).

When a developer exposes a set of keys in `values.yaml` from subcharts that are related to each other, they are not doing so because the values are configurable, but because they have no mechanism to pass values to subcharts that are inter-dependent.

However, chart users rely on `values.yaml` to know how they can parameterise a chart. I.e. users only need to worry about those values and  appreciate when a chart's developer already though through which variables users need to worry about. This implies that keys in `values.yaml` that need some inter-dependency are an hassle to users, as they need to be educated (by chart developers) on which values to use and which constraints those values need to have.

Example of usage of this proposal: given a chart with

```yaml
# values.yaml
foo: ""

auth:
  app: "myapp"
```

```yaml
# map.yaml

# this chart expects that `bar` to be `test-{%foo}` (a constraint)
bar: {{ printf "test-%s" .Values.foo  }}

subchart:
  # same here: `some_app` is expected to be constructed in this specific way (a constraint)
  some_app: {{ printf "%s-%s" .Values.auth.app .Values.foo  }}
```

that a user installs with 

```bash
helm install ... --set foo="aa" --set auth.app="otherapp"
```

, the resulting `.Values` is

```yaml
foo: "aa"
bar: "test-aa"

auth:
  app: "otherapp"

subchart:
  some_app: "otherapp-aa"
```

This would be equivalent to have the chart written as

```
# values.yaml

foo: ""
bar: "test-"

auth:
  app: "myapp"

subchart:
   some_app: ""
```

and the user run

```
helm install ... --set foo="aa" --set bar="test-aa" --set auth.app="otherapp" --set "subchart.some_app=otherapp-aa"
```

Note how, in this call, the user needs to set `subchart.some_app` to be "%{auth.app}-%{foo}" for the chart to work as expected (a constraint). This is the core problem that this proposal addresses.

# Rationale

This design was selected primarily based on the following factors: 

* backward compatibility
* recursive support for sub-charts
* Clarity of chart's public API
* simplicity of usage

### backward compatibility

This design was considered due to its backward compatibility, and how it has a backward compatible migration path for chart developers. This change is backward compatible because:

1. `map.yaml` is optional and this functionality is only activated by its existence
2. ``--set subchart.valueX`` takes precedence over the values derived in `map.yaml` and thus charts can add `map.yaml` without breaking backward compatibility
3. `map.yaml` does not collide with existing templates (because it is not placed in `templates/`)

Furthermore, developers have a clear migration path from charts without `map.yaml` to charts with `map.yaml`. Specifically:

1. add `map.yaml` and to it any value that needs to be written in `.Values` that depend on any value from `values.yaml`
1. warn users in INFO that the chart plans to move to `map.yaml`, so that users no longer need to populate certain values.
1. remove entries from `values.yaml` that are now populated by `map.yaml`

They can decide when to move from one step to the next as part of their own chart's release life-cycle.

### Recursive support for sub-charts

Another reason for this design is that a sub-chart can itself have a `map.yaml`, and the precedence described in the specification works recursively. This allows charts to be self contained, as the developer of `subchart1` can decide which values to expose in `values.yaml` and which ones to derive using `map.yaml`, irrespectively of whether `subchart1` has `subchart2` or not. A chart that has subchart `subchart1` only needs to populate the values of `subchart1`'s `value.yaml`, and leave any value of `subchart2` to be populated by `subchart1`'s `map.yaml`.

### Clarity of chart's public API

So far, `values.yaml` has been a place to allow users to pass values to `.Values` and subcharts. A major reason for the choice of design in this proposal is that it effectively allows chart developers to make `values.yaml` _the public interface_ of their helm chart.

Even if a subchart would require a value `complicated_name_oauth_client_id` to be set, developers can expose that value as `oauth_client_id` and map it to `subchart.complicated_name_oauth_client_id` on `map.yaml`. Before, developers had to expose in `values.yaml` an implementation detail - that the chart uses a subchart, and users had to set `subchart.complicated_name_oauth_client_id` themselves.

### Simplicity of usage

The usage of the functionality hereby proposed is unchanged for users of helm charts: they continue to use helm exactly as before, and require no extra calls. This was a major reason for consideration of this design, as it ensures that no training is required for chart users.

For chart developers, the functionality here proposed is easy to explain: `values.yaml` contains all values that a user can change independently. All dependent (constrained, derived) values are placed in `map.yaml` so that they are available in `.Values`. For backward compatibility, keep placing those values also in `values.yaml`, so that they can continue to be passed by users using an Helm version that does not support `map.yaml`.

Another simplification of this design is that developers no longer need to write named templates to construct names derived from `.Values`. They can just write them in `map.yaml`. An example would be `componentName: {{ .Release.name }}-component` on `map.yaml`, thus allowing them to use `.Values.componentName` on the chart (instead of declaring the named template to the same effect).

This proposal considers `map.yaml` a template for two reasons:

1. because chart developers are already familiar with templates;
2. because templates provide full flexibility on the transformations they support

# Backwards Compatibility

This proposal is backward compatible.

# Reference Implementation

A proof of concept is presented in [#8580](https://github.com/helm/helm/pull/8580).

**Comment by mattfarina** [comment]
Thank you for the proposal.

I would like to back up to the problem for a moment. The two roles involved in this are the chart developer and the Helm user who is installing the chart. These two roles may not be the same person and they may not be at the same organization. The Helm user may not even be an expert Kubernetes user or something who has any expertise in the app they are installing. This also affects the experience for that Helm user.

What is the problem in the current experience you are trying to solve? I'm not sure I'm entirely clear. Is it that you want to have a parent chart set sub-chart properties in a way that the Helm user cannot override? If so, why is that?

The motivation and impact on users is very important to us. We want to fully understand it.1

It also occurred to me that schemas could be used to enforce certain values being passed to the subchart. Changes to values would then fail validation.

**Comment by jorgecarleitao** [comment]
Thanks a lot, @mattfarina for taking the time to look at this. Maybe I can use a concrete example to show case this.

Let's say that I would like to offer an helm chart that deploys `jupyterhub` together with some other application, that both will rely on Azure AD for authentication and authorization, and that they are both deployed on the same subdomain, `example.com`. The canonical chart for `jupyterhub` is this one: https://jupyterhub.github.io/helm-chart/ . To configure it to use Azure AD, we need to pass

```
auth:
  type: azuread
  azuread:
    clientId: ""
    clientSecret: ""
    tenantId: ""
    callbackUrl: ""
```

to it.

So, as a developer of a chart that uses this subchart,

```
dependencies:
  - name: jupyterhub
    repository: https://jupyterhub.github.io/helm-chart/
    version: 0.9.0
```

I need to add to `values.yaml` the above configuration. Now, my other application has a more generic configuration, and only requires an openid-configuration, that on azure looks like this: `https://login.microsoftonline.com/$TENANT_ID/v2.0/.well-known/openid-configuration`

So, my `values.yaml` is now:

```
app:
    confUrl: ""
    clientId: ""
    clientSecret: ""
    subdomain: ""

jupyterhub:
  auth:
    type: azuread
    azuread:
      clientId: ""
      clientSecret: ""
      tenantId: ""
      callbackUrl: ""
```

This `values.yaml` suggests that users of my chart need to specify 7 parameters, but this chart is not really parameterized by 7 parameters, since `jupyterhub.azuread.tenantId` and `app.confUrl` are both constructed from the `TENANT_ID` (what I call a derived value). Currently, my chart's documentation would have to state

> the tenant that you pass to `app.confUrl` must be `https://login.microsoftonline.com/$TENANT_ID/v2.0/.well-known/openid-configuration`, where `$TENANT_ID` must be equal to the value passed to `jupyterhub.auth.azuread.tenantId`
>
> Furthermore, the `callbackUrl` must be on the same domain as `app.subdomain`.
> Furthermore, the `app.clientSecret` must be on the same as `jupyterhub.auth.azuread.clientSecret`
> ...

Having to write this on a README is not really needed, and is a just a consequence of `values.yaml` being both the interface to users of charts and the "place to pass values to subcharts". More importantly, it is an hassle both to users and developers, and lead to an overall poor experience and challenges in re-using charts as subcharts.

This proposal overcomes this by offering chart developers the option to not have to write that. In this example, they would write instead:

```
# values.yaml

tenantId: ""
subdomain: ""
clientSecret: ""
clientId: ""
```

```
# map.yaml
app:
    confUrl: {{ printf "https://login.microsoftonline.com/%s/v2.0/.well-known/openid-configuration" .Values.tenantId }}
    clientId: {{ .Values.clientId }}
    clientSecret: {{ .Values.clientSecret }}
    subdomain: {{ .Values.subdomain }}

jupyterhub:
  auth:
    type: azuread
    azuread:
      clientId: {{ .Values.clientId }}
      clientSecret: {{ .Values.clientSecret }}
      tenantId: {{ .Values.tenantId }}
      callbackUrl: {{ printf "https://notebook.%s/callback" .Values.subdomain }}
```

`map.yaml` is an implementation detail of the chart that chart users can't do anything to it. `values.yaml` is the public interface of the chart, and users can overwrite values as before.

We dramatically simplified the usage and documentation of this chart with this small trick. This is the benefit of this proposal and associated draft PR.
