### ISSUE TITLE
HPAs don't get changed during an upgrade

### ISSUE THREAD

**Issue by sharkymcdongles** [helm/helm#8579]
**Output of `helm version`:**
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

**Output of `kubectl version`:** 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.6", GitCommit:"14bc8ad5f8c245f1240a8e4eab128c4d51bfeffe", GitTreeState:"clean", BuildDate:"2020-05-30T02:07:03Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** GKE

I use this helm chart: https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx

**Relevant Deployed Values:**
```
  autoscaling:
    enabled: true
    maxReplicas: 14
    minReplicas: 3
    targetCPUUtilizationPercentage: 200
    targetMemoryUtilizationPercentage: 200
  autoscalingTemplate:
  - pods:
      metric:
        name: nginx_ingress_controller_nginx_process_requests
      target:
        averageValue: 10000m
        type: AverageValue
    type: Pods
```

**I update the values to below and run helm upgrade:**
```
  autoscaling:
    enabled: true
    maxReplicas: 14
    minReplicas: 3
    targetCPUUtilizationPercentage: 200
  autoscalingTemplate:
  - pods:
      metric:
        name: nginx_ingress_controller_nginx_process_requests
      target:
        averageValue: 10000m
        type: AverageValue
    type: Pods
```

HPA remains unchanged and memory utilization is still there.

I expect the HPA to be recreated. If I manually delete the HPA then run the command the HPA is created with proper values.
