### ISSUE TITLE
Install order: podpreset before depoyments

### ISSUE THREAD

**Issue by DatzAtWork** [helm/helm#8587]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.6-dhc", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"dirty", BuildDate:"2020-08-11T01:30:09Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

I have a helm chart with a podpreset:
```
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
spec:
  selector:
    matchLabels:
      inject: mypodpreset
```
and a deployment which uses the podpreset:
```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      labels:
        inject: mypodpreset
```

The problem is, that helm seems to create the podpreset AFTER the deployment. This leads to missing environment variables in the pods.

I suggest to deploy the podpresets before deployments, so they can even be used in the same helm chart in which they are defined and not just in other charts.
