### ISSUE TITLE
Helm search repo doesn't get some chart version

### ISSUE THREAD

**Issue by yinjianjin** [helm/helm#8593]
There is a repo as below:
[root@master repository]# helm3 repo ls
NAME    URL
obj     https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-adp-eric-data-object-storage-mn-dev-helm/

and obj_index.yaml from cache includes some charts like as below:
```
apiVersion: v1
entries:
  eric-pc-obj-storage:
  - apiVersion: v1
    appVersion: 0.1.0-116.dirty
    created: 2019-12-11T07:14:51.079Z
    description: Ericsson S3 compliance Object Storage Helm chart
    digest: ab571dd0df45fd6fc578ba978d326dbefef078a5139ca566909218aeadfec6df
    keywords:
    - storage
    - object-storage
    - eric-pc-object-storage
    name: eric-pc-obj-storage
    urls:
    - https://arm.sero.gic.ericsson.se/artifactory/proj-adp-eric-data-object-storage-mn-dev-helm/eric-pc-obj-storage-0.1.0-116.dirty.tgz
    version: 0.1.0-116.dirty
  eric-pc-obj-storage-client:
  - apiVersion: v1
    appVersion: 1.6.0-hd2db446.dirty
    created: 2020-08-13T07:02:34.240Z
    description: Ericsson S3 compliance Object Storage Client Helm chart (for testing
      only)
    digest: 3b195fe33acab210b402d8968605a074bc4f6bfb8645b26cb1b9528ffb552088
    keywords:
    - storage
    - object-storage-client
    - eric-pc-object-storage-client
    name: eric-pc-obj-storage-client
    urls:
    - https://arm.sero.gic.ericsson.se/artifactory/proj-adp-eric-data-object-storage-mn-dev-helm/testtool/eric-pc-obj-storage-client-1.6.0-hd2db446.dirty.tgz
    version: 1.6.0-hd2db446.dirty
```

But when execute  command of helm version 3 "helm search repo obj/object-storage-client", the results is "no results found",
however, use helm version 2, the result is alright, that really confuses me.

Output of `helm version`: version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`: 
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:45:27Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:40:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

_Edited for code readability_
