### ISSUE TITLE
New convention for image registry and sha256-tags

### ISSUE THREAD

**Issue by bmarwell** [helm/helm#8603]
This request is to add two new parameters to the default chart after calling `helm create`.
The parameters are:

```
image:
  registry:
  sha256:
```

Rationale:
* `image.repository` is not an atomar key. It can contain a domain for a image registry.
* `image.tag` cannot contain a sha256 hash.

## Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

## Current status of "helm create"

Currently, when creating a new chart using `helm create`, the following snippets will be created:

`templates/deployment.yaml`:
```
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
```

`values.yaml`
```
image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
```

## Proposed new outcome after `helm create`

Hint: the default `{{ .Values.image.tag | default .Chart.AppVersion }}` is missing.

`templates/deployment.yaml`:
```
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.image.sha256 }}
          image: {{ printf "%s/%s@sha256:%s" .Values.image.registry .Values.image.imageName .Values.image.sha256 | quote }}
          {{- else }}
          image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.imageName .Values.image.tag | quote }}
          {{- end }}
```

`values.yaml`
```
image:
  registry: ""
  imageName: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  sha256: ""
```

## Use case

**Registry:**
In some environments, an image registry mirror is used. Specifying a seperate key for the registry will make it easier to just specify the registry using an additional `-f values.registry.yaml` parameter.

**sha256:**
In some environments, you want to have full control over which exact image will be deployed. Currently, it is not possible to specify a hash, because the syntax is different. 
With the current default template, you would need to specify `repository: nginx@sha256` and then put `tag: ffac1234` into your `values.image.yaml`.

**Using both keys**
Currently, as the repository is not split up into atomar keys, it is not possible two define both values in seperate `values.yaml` files via  `-f` parameter. Imagine one `values.registry.yaml` was generated by system a and would define `image.repository: dockerhubmirror.mycompany.invalid/_/nginx`, while the second system b would add another `values.yaml` containing `image.repository: nginx@sha256`, `image.tag: ffac1234`. The repository domain would get lost in the process.

## Things which needs to be considered

I used a new `imageName` key. For full backwards compatiblity with the existing conventions, more if constructs needed to be used.

If no registry is given, another `if` statement must be used to avoid leading slashes in the image name.

The default `{{ .Values.image.tag | default .Chart.AppVersion }}` is missing and not part of my example.

The idea is that, if adapted by other applicatons, those application can be deployed in restricted environments without touching / modifying their `deployment.yaml` because of the existing convention.

This idea probably needs more conceptional work.

**Comment by mattfarina** [comment]
I would suggest a few things happen for this feature request...

1. It's called digest rather than sha256. Digest is the word used by the OCI and the existing docs and tools. Somethings like...

```
image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  digest: ""
```

2. The priority order goes digest, then tag, then appVersion. Digest is the most specific.
3. If digest and tag are both given it should give an error
4. All this logic can be rolled into a function in the helpers so it doesn't need to clutter anything up.
