### ISSUE TITLE
serviceName field is being called out as invalid when installing via helm v3

### ISSUE THREAD

**Issue by raul1991** [helm/helm#8604]
Output of `helm version`: 

version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-16T17:47:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): internal company's server

When I do helm install , I get this error with helm v3

```
helm.go:75: [debug] error validating "": error validating data: [ValidationError(Deployment.spec): unknown field "podManagementPolicy" in io.k8s.api.apps.v1.DeploymentSpec, ValidationError(Deployment.spec): unknown field "serviceName" in io.k8s.api.apps.v1.DeploymentSpec]

```

here is yaml file

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deploymentVariant.fullname" . | quote }}
  labels:
    {{- include "deploymentVariant.labels" . | indent 4 }}
    helm.sh/chart: {{ include "deploymentVariant.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ include "deploymentVariant.fullname" . | quote }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "deploymentVariant.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      name: {{ include "deploymentVariant.fullname" . | quote }}
      labels:
        {{- include "deploymentVariant.labels" . | indent 8 }}
      annotations:
        prometheus.io/path: "{{ .Values.prometheus.path }}"
        prometheus.io/port: "{{ .Values.service.port }}"
        prometheus.io/scrape: "{{ .Values.prometheus.scrape }}"
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{.Values.deploymentVariant.configMap}}
            optional: true
      serviceAccountName: {{ .Values.deploymentVariant.serviceAccount.name }}
      containers:
        - name: {{ .Values.images.mainContainer.name }}
          image: {{ include "deploymentVariant.image-registry-url" . | quote }}
          imagePullPolicy: {{ .Values.imageCredentials.pullPolicy }}
          env:
          - name: "FABRIC8_PID_FILTERS"
            value: "appGroup={{ .Values.deploymentVariant.appGroup }}"
          - name: "SERVICE_NAME"
            value: {{ include "deploymentVariant.fullname" . | quote }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          resources:
            requests:
              memory: {{ .Values.resources.mainContainer.requests.memory | quote }}
              cpu: {{ .Values.resources.mainContainer.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.mainContainer.limits.memory | quote }}
              cpu: {{ .Values.resources.mainContainer.limits.cpu | quote }}
          {{- if or .Values.imageCredentials.registry.pullSecret .Values.global.registry.pullSecret }}
      imagePullSecrets:
        - name: {{ or .Values.imageCredentials.registry.pullSecret .Values.global.registry.pullSecret | quote }}
    {{- end }}

```
