### ISSUE TITLE
Helm3 lint fails when using Kind: List

### ISSUE THREAD

**Issue by pchugh79** [helm/helm#8615]
Issues during lint with resource Kind:List  -  object name does not conform to Kubernetes naming requirements

Using Helm 3.3 on linux 

helm lint --strict <<chart>>

```
apiVersion: v1
kind: List
items:
  -apiVersion: v1
  kind: ConfigMap
  metadata:
    name:  XXX  

 -apiVersion: v1
  kind: ConfigMap
  metadata:
    name:  YYY
```
======

Helm 2 does not fail with same resource.

**Comment by mattfarina** [comment]
Kubernetes objects should have a metadata section with a name property. Helm v2 did not check that names were present or valid, during lint. Helm v3 does. That is why you see that now.

List is not a resource but rather a list of resources. There is an explanation at https://github.com/kubernetes/kubectl/issues/837#issuecomment-632092853. No official documentation exists on it.

I have not tried to send a list to Kubernetes. If it works we should handle linting that case.

**Comment by pchugh79** [comment]
Yes Kind:List works on Kubernetes , and if i do upgrade or install with Helm3.3 it works, its just that the lint fails on linux only.
We have also observed that, Helm 3.3 lint does not fail on windows.

**Comment by mattfarina** [comment]
That being the case on Windows is surprising. We'll need to look into it. Thanks for that piece of detail.

**Comment by wawa0210** [comment]
/assign
I can try to dig deeper

**Comment by dbluxo** [comment]
Hello, since Helm 3.3.0 I have problems with liniting the following resource:

```
{{- if and .Values.grafana.enabled .Values.grafana.defaultDashboardsEnabled }}
{{- $files := .Files.Glob "config/grafana/default-dashboards/*.json" }}
{{- if $files }}
apiVersion: v1
kind: ConfigMapList
items:
{{- range $path, $fileContents := $files }}
{{- $dashboardName := regexReplaceAll "(^.*/)(.*)\\.json$" $path "${2}" }}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: {{ printf "%s-%s" (include "prometheus.grafana.fullname" $) $dashboardName | trunc 63 | trimSuffix "-" }}
    labels:
      {{- if $.Values.grafana.sidecar.dashboards.label }}
      {{ $.Values.grafana.sidecar.dashboards.label }}: "1"
      {{- end }}
      app: {{ template "prometheus.grafana.fullname" $ }}
  data:
    {{ $dashboardName }}.json: {{ $.Files.Get $path | toJson }}
{{- end }}
{{- end }}
{{- end }}
```

```
 $ helm lint .
==> Linting .
[ERROR] templates/grafana/configmap-default-dashboards.yaml: object name does not conform to Kubernetes naming requirements: ""

Error: 1 chart(s) linted, 1 chart(s) failed
```
With Helm 3.2.4 it worked.

Is this related to this issue or should I open a separate one?

**Comment by mattfarina** [comment]
@dbluxo this is related. All lists are affected. This is due to a new linting feature in Helm 3.3.0.

**Comment by dbluxo** [comment]
The workaround for this is probably to configure the list with a `metadata.name`, then it works:

```
apiVersion: v1
kind: List
metadata:
  name: ZZZ
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name:  XXX  
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name:  YYY
```
