### ISSUE TITLE
Linting fails in 3.3.0 when a template file results in only a comment.

### ISSUE THREAD

**Issue by devSolo** [helm/helm#8621]
Output of `helm version`:
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

An error occurs when linting a chart that results in a template file containing only a comment:
```` 
# comment on first line
{{- if false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mychart-configmap
data:
  myvalue: "Hello World"
{{- end }}
````

the resulting lint throws an error:
````
[ERROR] templates/configmap-false.yaml: object name does not conform to Kubernetes naming requirements: ""
````

Essentially an empty file with only a comment triggers this issue.

```` 
# comment on first line
{{- if true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mychart-configmap
data:
  myvalue: "Hello World"
{{- end }}
````

results in a successful lint:
````
1 chart(s) linted, 0 chart(s) failed
````
