### ISSUE TITLE
chart with sepcific version is not listed

### ISSUE THREAD

**Issue by laplasz** [helm/helm#8625]
Output of `helm version`:
SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050

Output of `kubectl version`:
Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
microk8s

The index.yaml contains the following chart:

```
apiVersion: v1
entries:
  mychart:
  - apiVersion: v1
    appVersion: 0.14.0
    created: 2020-08-19T11:31:36.601Z
    description: My Helm Chart
    digest: 55693233e1c0fecfe30d86f07a3ae2a0add93b34192bb77ffe916399d983f288
    name: mychart
    urls:
    - local://myrepo/mychart-0.1.0-1.tgz
    version: 0.1.0-1
```
chart with version `0.1.0-1` is not listed which `helm search`
However if the version is `0.1.0` then it is listed.
