### ISSUE TITLE
Allow resources not created by Helm to be deleted when a release is deleted

### ISSUE THREAD

**Issue by mkjpryor-stfc** [helm/helm#8634]
It would be really cool if Helm allowed resources that were not created by Helm to be incorporated into a release for deletion purposes by using labels or annotations. These resources would not be touched by an update, but could be deleted when the release is deleted.

We could use the standard Kubernetes labels to do this, i.e. anything with these labels is considered part of the release:

```yaml
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: my-release  # release name
```

Or we could use additional labels under the `helm.sh` namespace.

**Use case 1: Helm chart that creates a StatefulSet** 

If a Helm chart declares a PVC that is used by a deployment, then the PVC is deleted when the release is deleted. However if a Helm chart declares a statefulset with `volumeClaimTemplates`, the PVCs created are **not** deleted when the release is deleted - they must be cleaned up manually by the user. **This also risks accidental reuse of PVCs if new release is made with the same name as before.**

However, if Helm supported the functionality suggested by this issue, the following statefulset definition would mean that the PVCs were cleaned up by Helm when the release was deleted:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
  labels:
    # ... other labels, e.g. chart, version ...
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: my-release  # release name
spec:
  # ...
  volumeClaimTemplates:
    - metadata:
        name: my-vol
        # These labels mean that the PVC is treated as part of the release for deletion
        labels:
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/instance: my-release  # release name
      spec:
        # ... pvc spec ...
```

**Use case 2: Helm charts for applications that spawn pods**

The classic example of this is JupyterHub. The JupyterHub Helm chart manages the deployment of the hub components, but the spawned notebook servers are not managed by Helm. This means that deleting the hub release leaves notebook servers dangling and inaccessible, requiring manual cleanup.

It is possible to configure JupyterHub to add extra labels to the notebook server pods. If Helm supported the functionality described in this issue, it would be possible to get JupyterHub to spawn notebook server pods that would be deleted when the release was deleted.
