### ISSUE TITLE
Go SDK upgrade performing actions in the wrong namespace

### ISSUE THREAD

**Issue by imilchev** [helm/helm#8685]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Rancher on bare-metal

I am writing an application using the Helm Go SDK which is supposed to upgrade an already deployed helm chart on my cluster. The chart is `bitnami/kafka` and is deployed in namespace `kafka`. All works well apart from the fact that for some reason when I actually perform the upgrade, helm starts creating StatefulSets and ConfigMaps in my default namespace and deletes things from the `kafka` namespace. I already spent 1 day investigating this issue and I am nowhere so some help would be appreciated.

```golang
package main

import (
	"log"
	"os"

	"helm.sh/helm/v3/pkg/action"
	"helm.sh/helm/v3/pkg/chart/loader"
	"helm.sh/helm/v3/pkg/cli"
)

func main() {
	settings := cli.New()

	actionConfig := new(action.Configuration)
	// You can pass an empty string instead of settings.Namespace() to list
	// all namespaces
	if err := actionConfig.Init(settings.RESTClientGetter(), "kafka", os.Getenv("HELM_DRIVER"), log.Printf); err != nil {
		log.Printf("%+v", err)
		os.Exit(1)
	}

	// Get current state
	getClient := action.NewGetValues(actionConfig)
	release, err := getClient.Run("kafka")
	if err != nil {
		log.Printf("%+v", err)
		os.Exit(1)
	}

	currentReplicaCount, ok := release["replicaCount"].(float64)
	if !ok {
		log.Printf("The current replica count %s is not a number.", release["replicaCount"])
		os.Exit(1)
	}
	log.Printf("Replica count: %+v", currentReplicaCount)

	// Upgrade
	upgradeClient := action.NewUpgrade(actionConfig)

	upgradeClient.Namespace = "kafka"
	upgradeClient.Atomic = true
	upgradeClient.ReuseValues = true

	//upgradeClient.DryRun = true
	updatedValues := map[string]interface{}{
		"replicaCount": currentReplicaCount + 1,
	}

	chartPath, err := upgradeClient.ChartPathOptions.LocateChart("bitnami/kafka", settings)
	if err != nil {
		log.Printf("%+v", err)
	}

	ch, err := loader.Load(chartPath)
	if err != nil {
		log.Printf("%+v", err)
	}

	upgrade, err := upgradeClient.Run("kafka", ch, updatedValues)
	if err != nil {
		log.Printf("%+v", err)
		os.Exit(1)
	}

	log.Printf("%+v", upgrade)
}
```

 - Retrieving the current config works fine
 - Dry run of the upgrade seems to return correct values (all namespaces are `kafka`)
 - Actual execution output:
```
2020/09/02 09:18:52 &{cfg:0xc000057d80 ChartPathOptions:{CaFile: CertFile: KeyFile: InsecureSkipTLSverify:false Keyring: Password: RepoURL: Username: Verify:false Version:} Install:false Devel:false Namespace:kafka SkipCRDs:false Timeout:0s Wait:false DisableHooks:false DryRun:false Force:false ResetValues:false ReuseValues:true Recreate:false MaxHistory:0 Atomic:true CleanupOnFail:false SubNotes:false Description: PostRenderer:<nil> DisableOpenAPIValidation:false}
2020/09/02 09:18:53 preparing upgrade for kafka
2020/09/02 09:18:53 reusing the old release's values
2020/09/02 09:18:54 performing update for kafka
2020/09/02 09:18:54 creating upgraded release for kafka
2020/09/02 09:18:54 checking 10 resources for changes
2020/09/02 09:18:54 Looks like there are no changes for PodDisruptionBudget "kafka-zookeeper"
2020/09/02 09:18:54 Looks like there are no changes for PodDisruptionBudget "kafka"
2020/09/02 09:18:54 Looks like there are no changes for ServiceAccount "kafka"
2020/09/02 09:18:54 Created a new ConfigMap called "kafka-scripts" in default
2020/09/02 09:18:54 Looks like there are no changes for Service "kafka-zookeeper-headless"
2020/09/02 09:18:55 Looks like there are no changes for Service "kafka-zookeeper"
2020/09/02 09:18:55 Looks like there are no changes for Service "kafka-headless"
2020/09/02 09:18:55 Created a new StatefulSet called "kafka" in default
2020/09/02 09:18:55 beginning wait for 10 resources with timeout of 0s
2020/09/02 09:18:57 StatefulSet is not ready: default/kafka. 0 out of 3 expected pods are ready
```

P.S.: The output of ` helm upgrade -n kafka --reuse-values --set replicaCount=4 kafka bitnami/kafka --debug`

```
upgrade.go:121: [debug] preparing upgrade for kafka
upgrade.go:440: [debug] reusing the old release's values
upgrade.go:129: [debug] performing update for kafka
upgrade.go:308: [debug] creating upgraded release for kafka
client.go:173: [debug] checking 10 resources for changes
client.go:436: [debug] Looks like there are no changes for PodDisruptionBudget "kafka-zookeeper"
client.go:436: [debug] Looks like there are no changes for PodDisruptionBudget "kafka"
client.go:436: [debug] Looks like there are no changes for ServiceAccount "kafka"
client.go:436: [debug] Looks like there are no changes for ConfigMap "kafka-scripts"
client.go:436: [debug] Looks like there are no changes for Service "kafka-zookeeper-headless"
client.go:436: [debug] Looks like there are no changes for Service "kafka-zookeeper"
client.go:436: [debug] Looks like there are no changes for Service "kafka-headless"
upgrade.go:136: [debug] updating status for upgraded release for kafka
Release "kafka" has been upgraded. Happy Helming!
```

**Comment by bacongobbler** [comment]
Did you make sure to set the namespace parameter for the kube client? By default, it will use the kubeconfig's default namespace.

https://github.com/helm/helm/blob/04fb35814f64122c0aa08165f6fdb7b67c216558/pkg/kube/client.go#L61-L62

**Comment by crazybg321** [comment]
Well, I have set the namespace to `kafka` for the action configuration and also for the upgrade client.

```golang
upgradeClient := action.NewUpgrade(actionConfig)

upgradeClient.Namespace = "kafka"
upgradeClient.Atomic = true
upgradeClient.ReuseValues = true

log.Printf("%+v", upgradeClient)
```

This code actually says that the namespace is `kafka` for the client itself. The weird thing is that just for part of the chart this happens and I really have no clue what more I can do to debug this.

```
2020/09/02 21:17:43 &{cfg:0xc0002a5c40 ChartPathOptions:{CaFile: CertFile: KeyFile: InsecureSkipTLSverify:false Keyring: Password: RepoURL: Username: Verify:false Version:} Install:false Devel:false Namespace:kafka SkipCRDs:false Timeout:0s Wait:false DisableHooks:false DryRun:false Force:false ResetValues:false ReuseValues:true Recreate:false MaxHistory:0 Atomic:true CleanupOnFail:false SubNotes:false Description: PostRenderer:<nil> DisableOpenAPIValidation:false}
```

**Comment by bacongobbler** [comment]
Is it possible that the resources are hard-coding a namespace parameter?

Looking at https://github.com/helm/helm/blob/04fb35814f64122c0aa08165f6fdb7b67c216558/pkg/kube/client.go#L181-L197

It would appear that the namespace is coming from the resource rather than the kube client. Check the output of `helm template`.

**Comment by crazybg321** [comment]
What I did also is logging the `KubeClient` in the action config and this was the output:

```
2020/09/02 21:44:01 &{Factory:0xc0001313e0 Log:0x4fc280 Namespace:}
```

**Comment by crazybg321** [comment]
The output of `helm template` is:

```yaml
---
# Source: kafka/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-11.8.2
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: kafka
---
# Source: kafka/templates/scripts-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-scripts
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-11.8.2
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
data:
  setup.sh: |-
    #!/bin/bash

    ID="${MY_POD_NAME#"kafka-"}"
    export KAFKA_CFG_BROKER_ID="$ID"

    exec /entrypoint.sh /run.sh
---
# Source: kafka/charts/zookeeper/templates/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper-headless
  namespace: kafka
  labels:
    app.kubernetes.io/name: zookeeper
    helm.sh/chart: zookeeper-5.21.5
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: zookeeper
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    
    - name: tcp-client
      port: 2181
      targetPort: client
    
    
    - name: follower
      port: 2888
      targetPort: follower
    - name: tcp-election
      port: 3888
      targetPort: election
  selector:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/component: zookeeper
---
# Source: kafka/charts/zookeeper/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper
  namespace: kafka
  labels:
    app.kubernetes.io/name: zookeeper
    helm.sh/chart: zookeeper-5.21.5
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: zookeeper
spec:
  type: ClusterIP
  ports:
    
    - name: tcp-client
      port: 2181
      targetPort: client
    
    
    - name: follower
      port: 2888
      targetPort: follower
    - name: tcp-election
      port: 3888
      targetPort: election
  selector:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/component: zookeeper
---
# Source: kafka/templates/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-11.8.2
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-client
      port: 9092
      protocol: TCP
      targetPort: kafka-client
    - name: tcp-internal
      port: 9093
      protocol: TCP
      targetPort: kafka-internal
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/component: kafka
---
# Source: kafka/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-11.8.2
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  ports:
    - name: tcp-client
      port: 9092
      protocol: TCP
      targetPort: kafka-client
      nodePort: null
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/component: kafka
---
# Source: kafka/charts/zookeeper/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-zookeeper
  namespace: kafka
  labels:
    app.kubernetes.io/name: zookeeper
    helm.sh/chart: zookeeper-5.21.5
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: zookeeper
    role: zookeeper
spec:
  serviceName: kafka-zookeeper-headless
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/instance: kafka
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      name: kafka-zookeeper
      labels:
        app.kubernetes.io/name: zookeeper
        helm.sh/chart: zookeeper-5.21.5
        app.kubernetes.io/instance: kafka
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: zookeeper
    spec:
      
      securityContext:
        fsGroup: 1001
      containers:
        - name: zookeeper
          image: docker.io/bitnami/zookeeper:3.6.1-debian-10-r88
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          command:
            - bash
            - -ec
            - |
                # Execute entrypoint as usual after obtaining ZOO_SERVER_ID based on POD hostname
                HOSTNAME=`hostname -s`
                if [[ $HOSTNAME =~ (.*)-([0-9]+)$ ]]; then
                  ORD=${BASH_REMATCH[2]}
                  export ZOO_SERVER_ID=$((ORD+1))
                else
                  echo "Failed to get index from hostname $HOST"
                  exit 1
                fi
                exec /entrypoint.sh /run.sh
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          env:
            - name: ZOO_DATA_LOG_DIR
              value: ""
            - name: ZOO_PORT_NUMBER
              value: "2181"
            - name: ZOO_TICK_TIME
              value: "2000"
            - name: ZOO_INIT_LIMIT
              value: "10"
            - name: ZOO_SYNC_LIMIT
              value: "5"
            - name: ZOO_MAX_CLIENT_CNXNS
              value: "60"
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: "srvr, mntr, ruok"
            - name: ZOO_LISTEN_ALLIPS_ENABLED
              value: "no"
            - name: ZOO_AUTOPURGE_INTERVAL
              value: "0"
            - name: ZOO_AUTOPURGE_RETAIN_COUNT
              value: "3"
            - name: ZOO_MAX_SESSION_TIMEOUT
              value: "40000"
            - name: ZOO_SERVERS
              value: kafka-zookeeper-0.kafka-zookeeper-headless.kafka.svc.cluster.local:2888:3888 
            - name: ZOO_ENABLE_AUTH
              value: "no"
            - name: ZOO_HEAP_SIZE
              value: "1024"
            - name: ZOO_LOG_LEVEL
              value: "ERROR"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          ports:
            
            - name: client
              containerPort: 2181
            
            
            - name: follower
              containerPort: 2888
            - name: election
              containerPort: 3888
          livenessProbe:
            exec:
              command: ['/bin/bash', '-c', 'echo "ruok" | timeout 2 nc -w 2 localhost 2181 | grep imok']
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command: ['/bin/bash', '-c', 'echo "ruok" | timeout 2 nc -w 2 localhost 2181 | grep imok']
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /bitnami/zookeeper
      volumes:
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
---
# Source: kafka/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-11.8.2
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: kafka
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/instance: kafka
      app.kubernetes.io/component: kafka
  serviceName: kafka-headless
  updateStrategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
        helm.sh/chart: kafka-11.8.2
        app.kubernetes.io/instance: kafka
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: kafka
    spec:      
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: kafka
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka:2.6.0-debian-10-r0
          imagePullPolicy: "IfNotPresent"
          command:
            - /scripts/setup.sh
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "kafka-zookeeper"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT"
            - name: KAFKA_CFG_LISTENERS
              value: "INTERNAL://:9093,CLIENT://:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "INTERNAL://$(MY_POD_NAME).kafka-headless.kafka.svc.cluster.local:9093,CLIENT://$(MY_POD_NAME).kafka-headless.kafka.svc.cluster.local:9092"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_DELETE_TOPIC_ENABLE
              value: "false"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx1024m -Xms1024m"
            - name: KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES
              value: "10000"
            - name: KAFKA_CFG_LOG_FLUSH_INTERVAL_MS
              value: "1000"
            - name: KAFKA_CFG_LOG_RETENTION_BYTES
              value: "1073741824"
            - name: KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS
              value: "300000"
            - name: KAFKA_CFG_LOG_RETENTION_HOURS
              value: "168"
            - name: KAFKA_CFG_MESSAGE_MAX_BYTES
              value: "1000012"
            - name: KAFKA_CFG_LOG_SEGMENT_BYTES
              value: "1073741824"
            - name: KAFKA_CFG_LOG_DIRS
              value: "/bitnami/kafka/data"
            - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_CFG_NUM_IO_THREADS
              value: "8"
            - name: KAFKA_CFG_NUM_NETWORK_THREADS
              value: "3"
            - name: KAFKA_CFG_NUM_PARTITIONS
              value: "1"
            - name: KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR
              value: "1"
            - name: KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES
              value: "102400"
            - name: KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES
              value: "104857600"
            - name: KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES
              value: "102400"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS
              value: "6000"
          ports:
            - name: kafka-client
              containerPort: 9092
            - name: kafka-internal
              containerPort: 9093
          livenessProbe:
            tcpSocket:
              port: kafka-client
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 
            periodSeconds: 
            successThreshold: 
          readinessProbe:
            tcpSocket:
              port: kafka-client
            initialDelaySeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
            periodSeconds: 
            successThreshold: 
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka
            - name: scripts
              mountPath: /scripts/setup.sh
              subPath: setup.sh
      volumes:
        - name: scripts
          configMap:
            name: kafka-scripts
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"

```
