### ISSUE TITLE
Helm install not working with dependencies containing subpath

### ISSUE THREAD

**Issue by longngn** [helm/helm#8686]
My `Chart.yaml`:

```
apiVersion: v2
name: nginx-ingress
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: kubernetes-ingress-nginx/ingress-nginx
    version: 2.x.x
    repository: https://repo.chartcenter.io/
```

After running `helm dep build`, Helm will get the dependency in the path `charts/ingress-nginx-2.15.0.tgz`

Then I run:

```
helm install ingress-nginx -n test .
```

Output:

`Error: found in Chart.yaml, but missing in charts/ directory: kubernetes-ingress-nginx/ingress-nginx`

Output of `helm version`:

`version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}`

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T11:09:22Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Kops 1.18.0 on AWS

**Comment by bacongobbler** [comment]
Try the following:

```
dependencies:
  - name: ingress-nginx
    version: 2.x.x
    repository: https://repo.chartcenter.io/kubernetes-ingress-nginx/
```

Does that work?

**Comment by longngn** [comment]
> Try the following:
> 
> ```
> dependencies:
>   - name: ingress-nginx
>     version: 2.x.x
>     repository: https://repo.chartcenter.io/kubernetes-ingress-nginx/
> ```
> 
> Does that work?

Thanks for the support. Sadly it doesn't work. Output when I ran `helm dep update`:

```
Saving 1 charts
Downloading ingress-nginx from repo https://repo.chartcenter.io/kubernetes-ingress-nginx/
Save error occurred:  could not download https://repo.chartcenter.io/empty/kubernetes-ingress-nginx/ingress-nginx-2.15.0.tgz: failed to fetch https://repo.chartcenter.io/empty/kubernetes-ingress-nginx/ingress-nginx-2.15.0.tgz : 404 Not Found
Deleting newly downloaded charts, restoring pre-update state
Error: could not download https://repo.chartcenter.io/empty/kubernetes-ingress-nginx/ingress-nginx-2.15.0.tgz: failed to fetch https://repo.chartcenter.io/empty/kubernetes-ingress-nginx/ingress-nginx-2.15.0.tgz : 404 Not Found
```

**Comment by mikegggit** [comment]
Believe it's because helm doesn't untar the dependencies downloaded into charts subdir.  If you manually untar the dependencies in charts and then run install, it works.

**Comment by jakuboskera** [comment]
Put subchart into this path `charts/ingress-nginx-2.15.0.tgz`.

Then your Chart.yaml:
```
apiVersion: v2
name: nginx-ingress
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: **ingress-nginx**
    version: 2.x.x
    repository: https://repo.chartcenter.io/kubernetes-ingress-nginx/
```
