### ISSUE TITLE
Add an option to helm template not render resources in tests directory 

### ISSUE THREAD

**Issue by torstenwalter** [helm/helm#8691]
This issue was already brought up in #6483 and proposed to be incorporated as a feature in helm 3.

#6444 implements an option to not render hooks, but that's not the same.

For example https://github.com/helm/charts/tree/master/stable/jenkins/templates/tests contains two manifests:

```
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-ui-test-{{ randAlphaNum 5 | lower }}"
  namespace: {{ template "jenkins.namespace" . }}
  annotations:
    "helm.sh/hook": test-success
```

and

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jenkins.fullname" . }}-tests
  namespace: {{ template "jenkins.namespace" . }}:
```

As you can see only the pod has the hook annotation. I've seen the same in other charts some are also rendering `Roles` or `RoleBindings` which are needed for testing e.g. https://github.com/helm/charts/tree/master/stable/grafana/templates/tests
