### ISSUE TITLE
helm removes "config-mode" key when using AKS-managed Azure Active Directory integration

### ISSUE THREAD

**Issue by bingosummer** [helm/helm#8709]
Output of `helm version`: v2.16.10

Output of `kubectl version`: v1.18.8

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

We use an [Azure AD backed authentication with our AKS](https://docs.microsoft.com/en-us/azure/aks/managed-aad). In my kubeconfig, I have the following block:

```
users:
- name: azure-ad
  user:
    auth-provider:
      config:
        access-token: ....
        apiserver-id: ....
        client-id: ....
        config-mode: "1"
        environment: AzurePublicCloud
        expires-in: "3600"
        expires-on: "1556718695"
        refresh-token: ....
        tenant-id: ....
      name: azure
```

After running any helm command, the "config-mode" is removed from my kubeconfig. After the access-token is expired (1 hour), it will fail when running kubectl:

```
$ kubectl get pods
error: You must be logged in to the server (Unauthorized)
```
