### ISSUE TITLE
Default "fullname" template issue

### ISSUE THREAD

**Issue by RoSk0** [helm/helm#8722]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-26T20:32:49Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Not relevant

Let's say we have `frontend` chart that depends on `backend` chart.
If we try to deploy `frontent-backend-test` release it will fail with something like :
```
Error: UPGRADE FAILED: cannot patch "frontend-backend-test" with kind Deployment: Deployment.apps "frontend-backend-test" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"frontend-backend-test", "app.kubernetes.io/name":"frontend"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
or 
```
Error: serviceaccounts "frontend-backend-test" already exists
```

This is because default `fullname` template:
```
{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "frontend.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}
```
contains this logic described by `If release name contains chart name it will be used as a full name.`.

I'm not sure what would the `fix` look like, but this feels like an issue that should be fixed.

References:
* Introduced in  https://github.com/helm/helm/pull/3193
* Introduced to fix https://github.com/helm/helm/issues/1186
* Related ? https://github.com/helm/helm/issues/6339

**Comment by bacongobbler** [comment]
Hi @RoSk0. I cannot tell what is the issue here with the information you provided in this ticket. Can you please provide a sample that demonstrates your issue more clearly?

**Comment by RoSk0** [comment]
I will try to explain a bit more clearer. When we, **we** is an open source or Helm community, provide a default implementation of something, `fullname` template we need to think not only in scope on a single implementation(chart) but rather the whole ecosystem - how multiple charts combined together under umbrella chart would work?

To demonstrate the issue I would use just created charts. 
Produced with the latest Helm version:
```
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

You can copy/paste following lines to your terminal and see the issue for yourself:
```bash
mkdir helm-issues-8722-test
cd helm-issues-8722-test/
helm create backend
helm create frontend
helm create umbrella
echo 'dependencies:' >> umbrella/Chart.yaml
echo '- name: backend' >> umbrella/Chart.yaml
echo '  version: "0.1.0"' >> umbrella/Chart.yaml
echo '  repository: "file://../backend"' >> umbrella/Chart.yaml
echo '- name: frontend' >> umbrella/Chart.yaml
echo '  version: "0.1.0"' >> umbrella/Chart.yaml
echo '  repository: "file://../frontend"' >> umbrella/Chart.yaml
helm dep update umbrella/
helm template frontend-backend-test umbrella/ | grep --before-context=4 --after-context=4 --line-regexp '  name: frontend-backend-test'
```

Resulting output:
```yaml
# Source: umbrella/charts/backend/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-backend-test
  labels:
    helm.sh/chart: backend-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: frontend-backend-test
--
# Source: umbrella/charts/frontend/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-backend-test
  labels:
    helm.sh/chart: frontend-0.1.0
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend-backend-test
--
# Source: umbrella/charts/backend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-backend-test
  labels:
    helm.sh/chart: backend-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: frontend-backend-test
--
# Source: umbrella/charts/frontend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-backend-test
  labels:
    helm.sh/chart: frontend-0.1.0
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend-backend-test
--
# Source: umbrella/charts/backend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-backend-test
  labels:
    helm.sh/chart: backend-0.1.0
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: frontend-backend-test
--
# Source: umbrella/charts/frontend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-backend-test
  labels:
    helm.sh/chart: frontend-0.1.0
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend-backend-test
```

demonstrates how Helm tries to create 2 ServiceAccount's, 2 Service's and 2 Deployment's all with the same name `frontend-backend-test`. This off course will fail.
