### ISSUE TITLE
.Chart object empty in sub-chart 

### ISSUE THREAD

**Issue by reschex** [helm/helm#8733]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform: EKS

I suspect I'm doing something stupid.. but let me explain:

I have a parent chart that installs a subchart:

parent Chart.yaml
```
apiVersion: v2
name: my-parent-chart
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 10.5.1

dependencies: 
  - name: my-sub-chart
    version: 1.1.0
    repository: "https://my-helm-repo.com/helm"
    tags:
      - my-sub-chart
```

subchart Chart.yaml:
```
apiVersion: v2
name: my-sub-chart
description: A Helm chart for Kubernetes
appVersion: 10.5.1
version: 1.1.0
```

The installation fails like so (I know its a lint command, but the error is the same)

```
helm lint -f ../../tenants/common-secrets.yaml.dec -f ../../tenants/tenant-a-test-values.yaml -f ../../tenants/tenant-a-test-secrets.yaml.dec
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: my-parent-chart/charts/my-sub-chart/templates/secrets.yaml:101:3: executing "my-parent-chart/charts/my-sub-chart/templates/secrets.yaml" at <include "my-sub-chart.labels" .>: error calling include: template: my-parent-chart/charts/my-sub-chart/templates/_helpers.tpl:20:27: executing "my-sub-chart.labels" at <include "my-sub-chart.name" .>: error calling include: template: my-parent-chart/charts/my-sub-chart/templates/_helpers.tpl:6:18: executing "my-sub-chart.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

Suffice to say that the `../../tenants/tenant-a-test-values.yaml` contains
```
tags:
  my-sub-chart: true
  my-other-sub-chart: false

# sub-chart configuration
my-sub-chart:
  some:
    config: "values"
```

As you can see above, the subchart Chart.yaml does contain a name, and so does the parent Chart.yaml..
I did some playing around and it's of course not just `.Chart.Name` that's nil, but all fields of the `.Chart` object. Same for the `.Release` object.. it's just the first thing helm picks up per order of operation its trying to create a secret first, which includes a bunch of templated lables which includes the .Chart.Name:

from the offending tpl:
```
{{- define "my-sub-chart.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

[...]
{{- define "my-sub-chart.labels" -}}
app.kubernetes.io/name: {{ include "my-sub-chart.name" . }}
helm.sh/chart: {{ include "my-sub-chart.chart" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/deployed-version: {{ default .Chart.AppVersion .Values.deployedVersion | replace "/" "_" | trunc 63 | quote }}
app.kubernetes.io/deployed-by: {{ default "Helm" .Values.deployedBy | replace "/" "_" | trunc 63 | quote }}
{{- end -}}
```

Any idea what I'm doing wrong here? 

Thanks!

**Comment by bacongobbler** [comment]
> nil pointer evaluating interface {}.Name

Looks like you're passing a nil value to the template. Check and make sure that the values being passed to an `include` are the correct values.

https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-include-function

**Comment by LozanoMatheus** [comment]
Hi @bacongobbler 

Could you share an example?

I'm also getting the same error, but I'm using a bit different. For example, the `.Release.Name` and `.Chart.Name` it works only on `metadata.namespace` (I'm not going to use in there) and I get the error when I set as a label or under the `affinity`.

File -> `templates/deployment.yaml`
```yaml
...
kind: Deployment
spec:
metadata:
  name: {{ include "test.fullname" . }}
  namespace: {{ include .Values.namespace . }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
...
  template:
...
    spec:
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
...
```

File -> `values.yaml`
```yaml
labels:
  test: {{ .Chart.Name }}

namespace: {{ .Release.Name }}-{{ .Chart.Version }}

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
```

Thanks
