### ISSUE TITLE
Deleting resources that were created using helm's keep annotation

### ISSUE THREAD

**Issue by imyashvinder** [helm/helm#8736]
How to remove resources using helm that was initially created using the "keep" policy. It's hard to track the resources Kubernetes provisions via helm.

I created a service type Loadbalancer in eks. It creates A Load balancer along with a security group. Now because it was created using keep policy, I don't seem to remove it other than manually.

```
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-externalendpoint"
  annotations:
    helm.sh/resource-policy: ""
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "xxxxxxxxxxx"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    helm.sh/chart: "{{ $.Chart.Name }}"
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
spec:
  type: LoadBalancer
  selector:
{{- include "chart.labels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.externalloadbalancer }}
      targetPort: {{ .Values.deployment.port }}
      name: https
```
