### ISSUE TITLE
Helm install/upgrade with --repo is not working

### ISSUE THREAD

**Issue by chandungc** [helm/helm#8744]
Installing release using --repo flag is not working using `helm install` command.
But specifying full path of the chart works. 
`helm install -h` shows below flag can be used:
`--repo string                  chart repository url where to locate the requested chart`

More details:
Working helm command:
`helm install RELEASE https://artifactory.in.here.com/artifactory/REPONAME/CHARTNAME-1.0.1.tgz -f values.yaml --namespace NAMESPACE --dry-run`

Non-Working helm command:
`helm install RELEASE CHARTNAME --repo https://artifactory.in.here.com/artifactory/REPONAME/  -f values.yaml --namespace NAMESPACE --dry-run`

Output for non-working command:
`Error: failed to download "local://CHARTNAME-1.0.1.tgz" (hint: running 'helm repo update' may help)`

I tried --devel, and --v flags but no additional information is printed by helm and same error is shown.
The repo has no authentication for our internal network. I did still try with --username and --password using an account that can manage the repo. It did not help either.
It seems helm is recognizing 1.0.1 as latest version as I did not pass --version flag. But looks like it is not pulling from repo.
The same behavior is seen for `helm upgrade` command as well.

If there is nothing wrong with the way I am executing these commands, and if indeed this is a bug,
either `--repo` should be supported or this should be removed from help section.

Output of `helm version`:
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.11", GitCommit:"436254b798f772bcb8e67dcfe122e46500eeb254", GitTreeState:"clean", BuildDate:"2020-06-17T11:49:23Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"ea5f00d93211b7c80247bf607cfa422ad6fb5347", GitTreeState:"clean", BuildDate:"2020-08-13T15:11:47Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

**Comment by jdolitsky** [comment]
@chandungc - I wasn't able to reproduce. Can you share some of the output of index.yaml? (https://artifactory.in.here.com/artifactory/REPONAME/index.yaml). Wondering if the chart URL is an issue

**Comment by chandungc** [comment]
Hi Josh,
Thanks for the response. Below is how index.yaml looks. The URL is using "local://".
The helm repo is hosted on artifactory.
```
apiVersion: v1
entries:
  CHART_NAME:
  - apiVersion: v2
    created: 2020-09-16T18:28:34.811Z
    description: ...
    digest: ...
    keywords:
    - ...
    maintainers:
    - email: ...
      name: ...
    name: CHART_NAME
    sources:
    - GITLAB_REPO_URL
    urls:
    - local://CHART_NAME-1.0.1.tgz
    version: 1.0.1
    .
    .
    .
```
