### ISSUE TITLE
Incorrect behavior of toYaml function

### ISSUE THREAD

**Issue by pdebicki** [helm/helm#8789]
Output of `helm version`: 
`version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

Hi,

I've ran into a problem with toYaml function.

Content on values.yaml:

```yaml
application.yaml:
  logging:
    pattern.console: "%date{ISO8601} %-5level [%thread] %mdc{workflowId:--} %logger{36} : %msg%n%ex"
```

Content of `templates/configmap.yaml':

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configuration
data:
  application.yaml: |
    {{- toYaml (index .Values "application.yaml") | nindent 4 -}}
```

Helm command:
```
helm template attributor .
````

Actual output (incorrect pattern.console:):
```yaml
---
# Source: attributor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configuration
data:
  application.yaml: |
    logging:
      pattern.console: '%date{ISO8601} %-5level [%thread] %mdc{workflowId:--} %logger{36}
        : %msg%n%ex'
```

Expected output:
```yaml
---
# Source: attributor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configuration
data:
  application.yaml: |
    logging:
      pattern.console: '%date{ISO8601} %-5level [%thread] %mdc{workflowId:--} %logger{36} : %msg%n%ex'
```

**Comment by pdebicki** [comment]
[helm-bug-8789-test.zip](https://github.com/helm/helm/files/5262024/helm-bug-8789-test.zip)

Here's a chart set up to reproduce this problem.

**Comment by mattfarina** [comment]
@pdebicki thanks for providing so much detail. I've replicated the issue

**Comment by mattfarina** [comment]
This seems to be an issue in the YAML library provided by Kubernetes or one of the dependencies of that library. Or, there is some nuance of YAML that is escaping me.

https://play.golang.org/p/w4xG_w2JmTW

The above uses that package (both Helm and Kubernetes use it) to parse and then write the YAML back out. The new line is added in.

**Comment by mattfarina** [comment]
Still investigating... the new line is caused by the `:` in the string.

**Comment by pdebicki** [comment]
Original setup:

```yaml
application.yaml:
  logging:
    pattern.console: "%date{ISO8601} %-5level [%thread] %mdc{workflowId:--} %logger{36} : %msg%n%ex"
---
# Source: attributor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configuration
data:
  application.yaml: |
    logging:
      pattern.console: '%date{ISO8601} %-5level [%thread] %mdc{workflowId:--} %logger{36}
        : %msg%n%ex'
```

No dots in key, last key fragment has 6 characters:

```yaml
application.yaml:
  logging:
    pattern:
      c23456: "%date{ISO8601} %-5level [%thread] %mdc{workflowId:--} %logger{36} : %msg%n%ex"
---
# Source: attributor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configuration
data:
  application.yaml: |
    logging:
      pattern:
        c23456: '%date{ISO8601} %-5level [%thread] %mdc{workflowId:--} %logger{36} : %msg%n%ex'
```

No dots in key, last key fragment has 7 characters:

```yaml
application.yaml:
  logging:
    pattern:
      c234567: "%date{ISO8601} %-5level [%thread] %mdc{workflowId:--} %logger{36} : %msg%n%ex"
---
# Source: attributor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configuration
data:
  application.yaml: |
    logging:
      pattern:
        c234567: '%date{ISO8601} %-5level [%thread] %mdc{workflowId:--} %logger{36} :
          %msg%n%ex'
```

Seem to be correlated with length of the key, or at least it looks like it.
