### ISSUE TITLE
If my deployment have 2 or more containers. How write my  values.yaml?

### ISSUE THREAD

**Issue by sober-wang** [helm/helm#8797]
Output of `helm version`: 3.3.0

Output of `kubectl version`:  1.18.2

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  kubernetes v1.18.2

If my deployment have 2 or more containers, these containers used different images. How write my  values.yaml?

**Comment by bacongobbler** [comment]
This is up to the author. However, a common convention typically would be

```
containers:
  - name: foo
    image: example.com/foo
    imagePullPolicy: Always
  - name: bar
    ...
```

Hope this helps.
