### ISSUE TITLE
Question about using different versions of the same dependency in the same chart

### ISSUE THREAD

**Issue by qfliu** [helm/helm#8804]
I have a question about using different versions of the same dependency in the same chart. I notice that if I made changes to a template definition in a newer version, and only update one service to use the latest version of the dependency in the chart, then I am still getting the service config of using the older version of the dependency. My understanding is that this is due to the design of go template, and as a result, i will only get one version of the template definition.

Example situation:
```
requirements.txt
dependencies:
  - name: chart-A
    version: 0.1.0
    repository: '@repo'
    alias: service-A
  - name: chart-A
    version: 0.2.0
    repository: '@repo'
    alias: service-B
```
In version 0.1.0, I have template chart-A.label as 'abc' ; in version 0.2.0, I have template chart-A.label as 'cde'. I want service-A to show label 'abc' and service-B to show label 'cde'. Right now, they both show the label as 'abc' .

I just want to check whether it is possible to have different versions of one dependency in the same chart and have the template definition work correctly respect to the version I specified. Or is the only solution right now to break the one chart for all services paradigm to one chart per service?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

**Comment by mattfarina** [comment]
It should be possible to have two versions of the same dependency with different configuration, such as labels.

I wanted to make sure there was no bug so I created a simple chart called bar with two versions. It simple creates a configmap and each one is the same except for the value of a label. I added it as a requirement to a chart, foo, and used helm template. Here is what I had for the two configmaps...

```
---
# Source: foo/charts/ba/templates/configmap.yaml
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: foo-ba
  labels:
    test-label: abc
    helm.sh/chart: ba-0.1.0
    app.kubernetes.io/name: ba
    app.kubernetes.io/instance: foo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  foo: bar
---
# Source: foo/charts/bb/templates/configmap.yaml
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: foo-bb
  labels:
    test-label: cde
    helm.sh/chart: bb-0.2.0
    app.kubernetes.io/name: bb
    app.kubernetes.io/instance: foo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  foo: bar
```

The requirements are:

```
dependencies:
  - name: bar
    version: 0.1.0
    repository: http://localhost:8000
    alias: ba
  - name: bar
    version: 0.2.0
    repository: http://localhost:8000
    alias: bb
```

The template was:

```
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ include "bar.fullname" . }}
  labels:
    test-label: {{ .Values.label }}
    {{- include "bar.labels" . | nindent 4 }}
data:
  foo: bar
```

This is all with the latest release of Helm.

If you are doing something else or have another question, please let us know.

**Comment by qfliu** [comment]
Thank you for your reply. I think I did not explain myself clearly. I will provide a more detailed example:

v0.0.1:
```
{{- define "bar.labels" -}}
helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
{{- end -}}
```

v0.0.2:
```
{{- define "bar.labels" -}}
label1: value1
label2: value2
{{- end -}}
```

configmap.yaml:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "bar.fullname" . }}
  labels:
    test-label: {{ .Values.label }}
{{- include "bar.labels" . | nindent 4 }}
data:
    foo: bar
```

requirements:
```
dependencies:
  - name: bar
    version: 0.1.0
    repository: http://localhost:8000
    alias: ba
  - name: bar
    version: 0.2.0
    repository: http://localhost:8000
    alias: bb
```

helm template output:
```
---
# Source: test-top-chart/charts/ba/templates/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: ba
  labels:
    test-label: abc
    helm.sh/chart: ba-0.0.1
data:
  foo: bar
---
# Source: test-top-chart/charts/bb/templates/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: bb
  labels:
    test-label: cde
    helm.sh/chart: bb-0.0.2
data:
  foo: bar
```

basically, the implementation of `bar.labels` changed and it is not represented when we have both 0.0.1 and 0.0.2 in the same requirements file.

**Comment by qfliu** [comment]
> It should be possible to have two versions of the same dependency with different configuration, such as labels.
> 
> I wanted to make sure there was no bug so I created a simple chart called bar with two versions. It simple creates a configmap and each one is the same except for the value of a label. I added it as a requirement to a chart, foo, and used helm template. Here is what I had for the two configmaps...
> 
> ```
> ---
> # Source: foo/charts/ba/templates/configmap.yaml
> kind: ConfigMap 
> apiVersion: v1 
> metadata:
>   name: foo-ba
>   labels:
>     test-label: abc
>     helm.sh/chart: ba-0.1.0
>     app.kubernetes.io/name: ba
>     app.kubernetes.io/instance: foo
>     app.kubernetes.io/version: "1.16.0"
>     app.kubernetes.io/managed-by: Helm
> data:
>   foo: bar
> ---
> # Source: foo/charts/bb/templates/configmap.yaml
> kind: ConfigMap 
> apiVersion: v1 
> metadata:
>   name: foo-bb
>   labels:
>     test-label: cde
>     helm.sh/chart: bb-0.2.0
>     app.kubernetes.io/name: bb
>     app.kubernetes.io/instance: foo
>     app.kubernetes.io/version: "1.16.0"
>     app.kubernetes.io/managed-by: Helm
> data:
>   foo: bar
> ```
> 
> The requirements are:
> 
> ```
> dependencies:
>   - name: bar
>     version: 0.1.0
>     repository: http://localhost:8000
>     alias: ba
>   - name: bar
>     version: 0.2.0
>     repository: http://localhost:8000
>     alias: bb
> ```
> 
> The template was:
> 
> ```
> kind: ConfigMap 
> apiVersion: v1 
> metadata:
>   name: {{ include "bar.fullname" . }}
>   labels:
>     test-label: {{ .Values.label }}
>     {{- include "bar.labels" . | nindent 4 }}
> data:
>   foo: bar
> ```
> 
> This is all with the latest release of Helm.
> 
> If you are doing something else or have another question, please let us know.

Thank you for your reply. I think I did not explain myself clearly. I will provide a more detailed example:

v0.0.1:
```
{{- define "bar.labels" -}}
helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
{{- end -}}
```

v0.0.2:
```
{{- define "bar.labels" -}}
label1: value1
label2: value2
{{- end -}}
```

configmap.yaml:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "bar.fullname" . }}
  labels:
    test-label: {{ .Values.label }}
{{- include "bar.labels" . | nindent 4 }}
data:
    foo: bar
```

requirements:
```
dependencies:
  - name: bar
    version: 0.1.0
    repository: http://localhost:8000
    alias: ba
  - name: bar
    version: 0.2.0
    repository: http://localhost:8000
    alias: bb
```

helm template output:
```
---
# Source: test-top-chart/charts/ba/templates/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: ba
  labels:
    test-label: abc
    helm.sh/chart: ba-0.0.1
data:
  foo: bar
---
# Source: test-top-chart/charts/bb/templates/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: bb
  labels:
    test-label: cde
    helm.sh/chart: bb-0.0.2
data:
  foo: bar
```

basically, the implementation of bar.labels changed and it is not represented when we have both 0.0.1 and 0.0.2 in the same requirements file.
