### ISSUE TITLE
Multiple chart URLs are not supported in index.yaml

### ISSUE THREAD

**Issue by jdolitsky** [helm/helm#8808]
There appears to be an unresolved TODO here:
https://github.com/helm/helm/blame/b0fdb5461fbc7e1b52f61613d3e7a22d85c7a794/pkg/downloader/chart_downloader.go#L241

```
// TODO: Seems that picking first URL is not fully correct
u, err = url.Parse(cv.URLs[0])
```

I think the expected behavior is that Helm goes through the list until one resolves. If the first URL does not return 200, should not resolve in error if subsequent URLs work.

```yaml
apiVersion: v1
entries:
  nginx:
    - created: 2016-10-06T16:23:20.499543808-06:00
      description: Create a basic nginx HTTP server
      digest: aaff4545f79d8b2913a10cb400ebb6fa9c77fe813287afbacf1a0b897cdffffff
      home: https://helm.sh/helm
      name: nginx
      sources:
      - https://github.com/helm/charts
      urls:
      - https://technosophos.github.io/tscharts/nginx-1.1.0.tgz
      - https://some.other.amazing.chart.site.com/nginx-1.1.0.tgz  # <--- this is ignored
generated: 2016-10-06T16:23:20.499029981-06:00
```

cc @thomastaylor312
