### ISSUE TITLE
helm dependency update says x.y.z-prerelease+build is invalid format

### ISSUE THREAD

**Issue by weriKK** [helm/helm#8819]
Hello. 

Our CI pipelines need to include build hashes and git branches in the helm chart versions. 
We decided to use the `x.y.z-hash+branchname` format.

Here is an example requirements.yaml:
```
dependencies:
  - name: myservice
    condition: myservice.enabled
    repository: '@myrepo'
    version: 0.0.9-7991b44+maste​r
```

However it seems that helm dependency update does not like this versioning format:

Output of `helm version`:
```
$ helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

Output of `helm dependency update`
```
Update Complete.
Error: dependency "myservice" has an invalid version/constraint format: improper constraint: 0.0.9-7991b44+maste​r
```

While this is not exactly in the spirit of semver versioning, my understanding is that this is a valid SemVer v2 format.
Shouldn't helm accept this version string?

What do you think?
