### ISSUE TITLE
How to divide single chart to multiple charts and deploy the new charts in the same namespace?

### ISSUE THREAD

**Issue by qfliu** [helm/helm#8827]
Right now I have a single chart contains all the services I need in a namespace:
namespace-folder/requirements.txt
```
dependencies:
  - name: chart-A
    version: 0.0.1
    repository: http://localhost:8080
    alias: service-A
  - name: chart-A
    version: 0.0.2
    repository: http://localhost:8080
    alias: service-B
```

Currently, this is causing issue when there is an update to template function in version 0.0.2 as the change will not get picked up (more details are mentioned in this issue: https://github.com/helm/helm/issues/8804). As a result, I want to separate this one chart to different charts. 
Here is the new structure:
namespace-folder/service-A/requirements.txt
```
dependencies:
  - name: chart-A
    version: 0.0.1
    repository: http://localhost:8080
    alias: service-A
```

namespace-folder/service-B/requirements.txt
```
dependencies:
  - name: chart-B
    version: 0.0.1
    repository: http://localhost:8080
    alias: service-B
```

However, when I try to install the charts in the new structure, i.e. multiple Releases per service instead of a single Release containing all services. It is complaining about duplicate resources already exist, e.g. Services.

Is it possible to do this change in-place (within the existing namespace) without creating another temporary namespace? What's a good way to do it if it is possible? Preferably, I can do this without bringing down existing services.
