### ISSUE TITLE
Helm 3.3.4 - pre-upgrade hook, race condition

### ISSUE THREAD

**Issue by jakubbujny** [helm/helm#8863]
Our annotations:
```
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "5"
```
We get that error randomly

```
Error: UPGRADE FAILED: pre-upgrade hooks failed: warning: Hook pre-upgrade infrastructure-XXX.yaml.tpl failed: object is being deleted: YYY "resource-name" already exists
```

what suggest some kind of race condition - maybe Helm tries to create resource when it's in "deleting" state?

helm3 version:
```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mattfarina** [comment]
@jakubbujny Do you happen to have an example chart that produces this? One we can see.

Also, what kind of resource is this happening on. Deployment, StatefulSet, something else?

**Comment by jakubbujny** [comment]
It happens for our custom resource.

```
{{- range $client := $clients  }}
---
apiVersion: incubator.xxx/v1alpha1
kind: CustomResourceXXX
metadata:
  name: {{ $client }}
  namespace: {{ $namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "5"
spec:
  secrets:
    - name: id
      secretStorage:
        field: id
        key: {{ printf "%s/%s" $.Values.main.clientsPath $client }}
    - name: secret
      secretStorage:
        field: secret
        key: {{ printf "%s/%s" $.Values.main.clientsPath $client }}
{{- end }}
```

Sadly I can't give you whole Chart as it can be considered as security breach in our company.

How can I help more?
