### ISSUE TITLE
Helm tags get deleted from Chart.yaml

### ISSUE THREAD

**Issue by Aishwarya-Nair-work** [helm/helm#8867]
I was utilising helm tags to do selective helm charts deployments, where I write a piece of code in my parent charts' charts.yaml like this:
```
apiVersion: v1
name: wordpress
version: 1.0.0
appVersion: 1.0.0
description: wordpress
dependencies:
- name: mariadb
  version: 1.0.0
  tags:
    - all
```

Now, when I run helm package command, I see that the below field goes missing in the tar file generated.
```
tags:
  - all
```

Also when I install chart with tag all=false it still goes and creates pod
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}

**Comment by hickeyma** [comment]
@Aishwarya-Nair-work I tested this using the latest code in the main branch and added the findings below. It seems to be working as expected whereby it is maintaining the tag during package. Do you mind trying it out using the latest [canary builds](https://helm.sh/docs/intro/install/#from-canary-builds) ?

```console
$ helm3 create issue-8867

$ cat issue-8867/Chart.yaml 
apiVersion: v2
name: issue-8867
description: A Helm chart for Kubernetes

[...]

dependencies:
- name: mariadb
  version: 6.x.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled
  tags:
    - all

$ cat issue-8867/Chart.yaml 
apiVersion: v2
name: issue-8867
[...]
affinity: {}

tags:
  all: true
```

$ helm3 dep update issue-8867/
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading mariadb from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts

$ helm3 package issue-8867/
Successfully packaged chart and saved it to: /home/marty/test/helm-charts/issue-8867-0.1.0.tgz

$ rm -rf issue-8867/

$ tar -xvzf issue-8867-0.1.0.tgz
issue-8867/Chart.yaml
issue-8867/Chart.lock
[...]

$ cat issue-8867/Chart.yaml 
apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
  - all
  version: 6.x.x
description: A Helm chart for Kubernetes
name: issue-8867
type: application
version: 0.1.0
```

**Comment by Aishwarya-Nair-work** [comment]
I am still facing issue.

I installed below helm version as suggested : 
version.BuildInfo{Version:"v3.3+unreleased", GitCommit:"fc9b46067f8f24a90b52eba31e09b31e69011e93", GitTreeState:"clean", GoVersion:"go1.14.9"}

$ cat Chart.yaml 
```
apiVersion: v1
appVersion: 5.5.1
name: wordpress
version: 1.0.0
description: Web publishing platform for building blogs and websites.
dependencies:
- name: mariadb
  version: 7.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
  tags:
    - all
```
```
helm package wordpress/

Successfully packaged chart and saved it to: ./wordpress-1.0.0.tgz
```
```

tar -xvf wordpress-1.0.0.tgz

cat Chart.yaml 

apiVersion: v1
appVersion: 5.5.1
description: Web publishing platform for building blogs and websites.
name: wordpress
version: 1.0.0
```

**Comment by hickeyma** [comment]
Hmm, looks the same. Have you added tags to the values file?

**Comment by Aishwarya-Nair-work** [comment]
Yes I have.

**Comment by hickeyma** [comment]
Do you mind this dependency incase there is s/thing added to the 7.x.x chart in the bitnami repo:

```yaml
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
  - all
  version: 6.x.x
```

**Comment by Aishwarya-Nair-work** [comment]
Still no luck.

cat Chart.yaml
```
apiVersion: v1
appVersion: 5.5.1
name: wordpress
version: 1.0.0
description: Web publishing platform for building blogs and websites.
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
  - all
  version: 6.x.x
```
Contents of Chart.yaml after helm package

```
cat Chart.yaml 
apiVersion: v1
appVersion: 5.5.1
description: Web publishing platform for building blogs and websites.
name: wordpress
version: 1.0.0

```

**Comment by Aishwarya-Nair-work** [comment]
Also, I have tried with another chart as well. Gives me the same result. tags gets eliminated from the packaged **Chart.yaml**

**Comment by hickeyma** [comment]
At this moment I am unable to reproduce @Aishwarya-Nair-work. Do you. mind troubleshooting some more in your environment to see if you notice anything further?

**Comment by Aishwarya-Nair-work** [comment]
Yes. I have tried actually everything possible. But not able to get pass this. Not sure why it is working differently for both of us.

**Comment by mattfarina** [comment]
@Aishwarya-Nair-work what operating system are you on?

**Comment by Aishwarya-Nair-work** [comment]
Ubuntu 18.04

**Comment by mattfarina** [comment]
I'm unable to reproduce the problem. So, I'm going to start with some possibly strange questions to try and track this down.

- How did you install Helm? I'm curious of the process and source
- Did the dependency handling work in a previous Helm version? If so, what version? I'd like to compare code paths
- Can you share the lockfile (i.e. Chart.lock or requirements.lock)?
- Are we sure the characters used in dependencies are english and that no other unicode characters are showing up in that section?

**Comment by Aishwarya-Nair-work** [comment]
Sure.

1.  Installed using steps from [official helm site ](https://helm.sh/docs/intro/install/)
2. Nope, never worked for me.
3. contents requirements.lock
```
dependencies:
- name: mariadb
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 6.x.x
digest: sha256:0e90d70d4ad67c7bd861751af2c7b1c6b66851d565c663db77e76e0da0ac5e60
generated: "2020-10-09T21:00:33.617397541+05:30"
```
4. Yes. I tried it for another chart as well. Same result. Also one of my teammates tested the same and is facing the same issue
