### ISSUE TITLE
Helm commands use default value file instead of specified one

### ISSUE THREAD

**Issue by penumbra23** [helm/helm#8897]
My understanding of the values file was when specifying the exact file (with `-f` or `--values` flag) it uses that and ONLY that file. But I have the following situation:

`service.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  {{- if .Values.service.nodePort }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: 80
      targetPort: http
      name: http

```

`values.yaml`
```yaml
service:
  enabled: true
  nodePort: 31333
```

`values-staging.yaml`
```yaml
service:
  enabled: true
```

Running both `helm install .` or `helm install . -f values-staging.yaml` renders the service as a `NodePort`, because it somehow uses the `values.yaml` file as a fallback option. Ofc, solved the problem by renaming `values.yaml` with `values-dev.yaml`, but shouldn't it use the specified file all along while rendering the template? Thanks!

Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", 
GoVersion:"go1.13.12"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`RKE v1.1.4 on-premise cluster, Ubuntu 18.06`
