### ISSUE TITLE
[BUG] can't install if there are numbers in environment virables

### ISSUE THREAD

**Issue by dfang** [helm/helm#8905]
Output of `helm version`:

version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker for mac

How to reproduce:

helm create test

add this to values.yaml
```
env:          
- name: DBAdapter
  value: "postgres"
- name: DBPort
  value: "5432"
- name: DBName
  value: "qor-local"
- name: DBHost
  value: "localhost"
- name: DBUser
  value: "postgres"
- name: DBPassword
  value: "postgres"
```

add this to deployment.yaml, between image and imagePullPolicy, same indention level 
```
{{- with .Values.env }}
env:          
{{- range . }}
-  name: {{ .name }}
    value: {{ .value }}
{{- end }}
{{- end }}
```

```
helm install . --generate-name 

Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 5, error found in #10 byte of ...|,"value":5432},{"nam|..., bigger context ...|er","value":"postgres"},{"name":"DBPort","value":5432},{"name":"DBName","value":"qor-local"},{"name"|...

```

if only i remove DBPort from env list, `helm install . --generate-names` works.
