### ISSUE TITLE
render a complex yaml

### ISSUE THREAD

**Issue by NICK-DUAN** [helm/helm#8918]
I'm writing a kongplugin resource, and the config is so complex that makes me crazy, anybody can help me?

What I want is:
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: test
plugin: custom-plugin
config:
  rules:
    - client: rainbowX
      jwt_secret: YXNkZ2UzNjQzNTd5MzI4OSsvLSovNisN
      routes:
      - path: /
        methods:
            - GET
            - POST
      - path: /api/v1
        methods:
            - PUT
            - DELETE  
```

values
```yaml
name: coding-external-token
config:
  rules:
    - client: rainbowX
      jwt_secret: YXNkZ2UzNjQzNTd5MzI4OSsvLSovNisN
      routes:
      - path: /
        methods:
            - GET
            - POST
      - path: /api/v1
        methods:
            - PUT
            - DELETE  
```

template:
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ .name }}
plugin: {{ .name }}
{{- if .config }}
config:
  rules:
    # ???    
{{- end }}
```

**Comment by mattfarina** [comment]
I would suggest you look at the `toYaml` and either `indent` or `nindent` template functions. These will let you take the objects from your _values.yaml_ file and directly render them into manifests. It looks like you are trying to do that. You can look in the charts repo for examples.

**Comment by NICK-DUAN** [comment]
> I would suggest you look at the and either or template functions. These will let you take the objects from your _values.yaml_ file and directly render them into manifests. It looks like you are trying to do that. You can look in the charts repo for examples.`toYaml``indent``nindent`

Thank you, It's a nice way to me. But I get a new problem, some number are converted to scientific counting. 
Like:
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: ci-loging-kong-ingress
proxy:
  connect_timeout: 1.8e+06
  read_timeout: 1.8e+06
  write_timeout: 1.8e+06
```

**Comment by mattfarina** [comment]
@NICK-DUAN This has to do with yaml parsing and rendering.

Helm parses the numbers in the _values.yaml_ file as numbers. That is how they are internally stored. Then, when Helm renders the numbers is renders them as numbers. Helm and any other compliant YAML parser would see these as numbers and parse them that way, too.

You can find this in the YAML spec at https://yaml.org/spec/1.2/spec.html#id2804092

Note, something about how the number is parsed is causing it to be read as a float instead of an integer.

Helm uses the same YAML parser/writer that Kubernetes does. If Helm can handle it then Kubernetes can as well.

**Comment by NICK-DUAN** [comment]
I got this. let me show you the code:

template:

```yaml
{{- range .Values.services }}
{{ $svcName := .name }}
{{- range .plugins }}
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ $svcName }}-plugin-{{ .name }}
plugin: {{ .name }}
config:
  {{- toYaml .config | nindent 2 }}
---
{{- end }}
{{- end }}
```

values:

```yaml
services:
  - name: ci-ws-server
    port: 8081
    strip_path: true
    keepalive: true
    kong_ingress_name: ci-wsserver-kong-ingress
    connect_timeout: "1800000"
    read_timeout: "1800000"
    write_timeout: "1800000"
    paths:
      - /api/ci-ws/task
```

result:

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: ci-webconsole-kong-ingress
proxy:
  connect_timeout: 1800000
  read_timeout: 1800000
  write_timeout: 1800000
```

Big number already in quotes, And it worked for me.

And Thanks.
