### ISSUE TITLE
helm package incorrectly strips zeros from RHS

### ISSUE THREAD

**Issue by liamwhan** [helm/helm#8966]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```
Output of `kubectl version`:
N/A - Using rancher `rancher version v2.4.5`

`helm lint` catches this so I'm not sure whether you even want to fix this but given a version number such as 519.460, `helm package` is removing the trailing zero when packaging and outputting `519.46`

For example given a chart: 
```yaml
apiVersion: v1
appVersion: 519.460
description: A Helm chart for myimage
name: myimage
version: 519.460
questions:
- variable: myimage.image
  default: "myrepo/myimage"
  description: "image name"
  type: string
  label: image name
  group: "APPLICATION VERSION"
  required: true
- variable: myimage.imageTag
  default: "519"
  description: "myimage image tag"
  type: string
  label: myimage image tag
  group: "APPLICATION VERSION"
  required: true
```
The output of `helm package` on this chart is:
```sh
Successfully packaged chart and saved it to: /home/vsts/work/r1/a/myimage-519.46.tgz
```

I know that 519.460 is not a valid SemVer version, but the behaviour is inconsistent with version numbers without trailing zeros 519.461 which helm parses correctly.
