### ISSUE TITLE
Impossible to use dynamic values in secrets file

### ISSUE THREAD

**Issue by ecourtial** [helm/helm#8997]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Minikube

Hi. With the below content, I can use my secrets file without any issue via the command _kubectl apply -f templates/secrets.yaml_:

_secrets.yaml_
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: test-secret
data:
  DB_HOST: dXRj
  MYSQL_DATABASE: dXRj
  MYSQL_USER: dXRj
  MYSQL_PASSWORD: dXRj
```

However, if I want it to be dynamic, using a value :
_values.yaml_
```
...
secrets:
  name: "my-test-secrets"
...
```
I have an issue. While the _helm lint_ command shows that the value is properly used, I have the below error when applying it:
```
error: error parsing templates/secrets.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"$.Values.secrets.name":interface {}(nil)}
```

Any idea ?

**Comment by mattfarina** [comment]
Without seeing the chart, this will be difficult to figure out. Can you share the secret template? Also, can you share the command you are using to run Helm?

Helm is regularly used for custom names like this. If it stopped working there would be many issues reported.

**Comment by ecourtial** [comment]
Thank you for your answer. Below is the secret template:
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Values.secrets.name }}
data:
  DB_HOST: dXRj
  MYSQL_DATABASE: dXRj
  MYSQL_USER: dXRj
  MYSQL_PASSWORD: dXRj
```
This is how I update my release in Helm:
``` helm upgrade eric . -n chapter5```

I tried with something else, for instance the _DB_HOST_ field_, I have the same issue. I am pretty sure it is nothing but I don't have this issue with other files.
