### ISSUE TITLE
Dependency build generates incorrect url's and fails to save charts

### ISSUE THREAD

**Issue by tstevens** [helm/helm#9005]
When I run `helm dependency build .` on the below chart when using the updated repo locations for incubator and stable the chart fails to download. Taking a look at the generated chart URL it appears to be including both stable and incubator into the url's path or potentially prefixing the incorrect repo url to the desired path. If I manually modify the url to remove this inconsistency I am able to curl and download the package. I'm not super familiar with helm so I'm unsure if this is somehow user error or if I have stumbled across a bug.

Helm created url:
https://charts.helm.sh/stable/incubator/packages/kafka-0.21.3.tgz

Modified url:
https://charts.helm.sh/incubator/packages/kafka-0.21.3.tgz

```
test tstevens$ helm dependency build .
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "cetic" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading kafka from repo https://charts.helm.sh/incubator
Save error occurred:  could not download https://charts.helm.sh/stable/incubator/packages/kafka-0.21.3.tgz: failed to fetch https://charts.helm.sh/stable/incubator/packages/kafka-0.21.3.tgz : 404 Not Found
Deleting newly downloaded charts, restoring pre-update state
Error: could not download https://charts.helm.sh/stable/incubator/packages/kafka-0.21.3.tgz: failed to fetch https://charts.helm.sh/stable/incubator/packages/kafka-0.21.3.tgz : 404 Not Found

```

*Chart.yaml*
```yaml
apiVersion: v2
name: mychart
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: kafka
    version: "0.21.3"
    repository: "https://charts.helm.sh/incubator"
  - name: mysql
    version: "1.6.7"
    repository: "https://charts.helm.sh/stable"

```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Rancher

Configured helm repos:
```
test tstevens$ helm repo list
NAME     	URL                                
bitnami  	https://charts.bitnami.com/bitnami 
cetic    	https://cetic.github.io/helm-charts
stable   	https://charts.helm.sh/stable      
incubator	https://charts.helm.sh/incubator 
```
