### ISSUE TITLE
helm template command fails if sub-chart name contains  slash('/')

### ISSUE THREAD

**Issue by abhinavkhanna-sf** [helm/helm#9017]
Output of `helm version`: 

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:5
8:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeState:"clean", BuildDate:"202
0-08-28T23:04:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS
 
Issue: helm template command fails if sub-chart name contains  slash('/')

1. Create a Chart.yaml with sub-chart with slash in the name

```
name: artifactory-jcr
description: JFrog Artifactory Container Registry
apiVersion: v2
version: 1.0.0
appVersion: 1.0.0
type: application
deprecated: false
dependencies:
  - repository: 'https://repo.chartcenter.io'
    name: 'jfrog/artifactory-jcr'
    version: '3.2.2'
    alias: 'artifactory-jcr'

```
2. Run 

```
helm dependency update
# This downloads a file artifactory-jcr-3.2.2.tgz in ./charts/   folder
```
3. Run 

```
helm template . --name-template artifactory-jcr  --debug
```

Error/Debug logs

```
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: C:\Users\****\git\****

Error: found in Chart.yaml, but missing in charts/ directory: jfrog/artifactory-jcr
helm.go:81: [debug] found in Chart.yaml, but missing in charts/ directory: jfrog/artifactory-jcr
helm.sh/helm/v3/pkg/action.CheckDependencies
        /home/circleci/helm.sh/helm/pkg/action/install.go:606
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:215
main.newTemplateCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/template.go:70
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
```

looks like its trying to find jfrog/artifactory archive instead of the download one (artifactory-jcr-3.2.2.tgz)
