### ISSUE TITLE
helm lint fails object name must be between 0 and 253 characters: ""

### ISSUE THREAD

**Issue by armanzor** [helm/helm#9019]
Output of `helm version`:
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Docker Desktop

Lint fails with message in topic with versions v3.4.0 and v3.4.1
Easy to reproduce: 

1. take kube-prometheus-stack https://github.com/prometheus-community/helm-charts/tree/kube-prometheus-stack-11.1.1/charts/kube-prometheus-stack
2. define any values in `additionalServiceMonitors: []` or/and `additionalPodMonitors: []` (just names are sufficient)
3. run `helm lint .`
4. Result:
```
$ helm lint .
==> Linting .
[ERROR] templates/prometheus/podmonitors.yaml: object name must be between 0 and 253 characters: ""
[ERROR] templates/prometheus/servicemonitors.yaml: object name must be between 0 and 253 characters: ""
```
5. `helm template` output:
```
# values.yaml
#~~~~~
  additionalServiceMonitors:
  - name: abc-def
#~~~~~
  additionalPodMonitors:
  - name: frg-ght
```
```
---
# Source: kube-prometheus-stack/templates/prometheus/servicemonitors.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: abc-def
      namespace: default
      labels:
        app: kube-prometheus-stack-prometheus

        chart: kube-prometheus-stack-11.1.1
        release: "RELEASE-NAME"
        heritage: "Helm"
    spec:
      endpoints:
        null
      selector:
        null
---
```
```
---
# Source: kube-prometheus-stack/templates/prometheus/podmonitors.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: monitoring.coreos.com/v1
    kind: PodMonitor
    metadata:
      name: frg-ght
      namespace: default
      labels:
        app: kube-prometheus-stack-prometheus

        chart: kube-prometheus-stack-11.1.1
        release: "RELEASE-NAME"
        heritage: "Helm"
    spec:
      podMetricsEndpoints:
        null
      selector:
        null
---
```
Doesn't reproduce on v3.2.4
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"
