### ISSUE TITLE
Unable to access `genCA` attributes

### ISSUE THREAD

**Issue by mitchya1** [helm/helm#9020]
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"clean"}
```
Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Minikube and EKS

I've run into a weird issue with the `genCA` function. The `Cert` and `Key` attributes are empty, but the map is populated. `genSignedCert` works fine, however. Here's an example:

`_helpers.tpl`:

```go
{{- define "webhook.certs" -}}
{{- $fullName := ( include "auth-proxy-injector.fullname" . ) -}}
# fullname, fullname.namespace, fullname.namespace.svc
{{- $altNames := list ( printf "%s" $fullName ) ( printf "%s.%s" $fullName .Release.Namespace ) ( printf "%s.%s.svc" $fullName .Release.Namespace ) -}}
{{- $ca := genCA "auth-proxy-injector" 3650 -}}
{{- $cert := genSignedCert ( include "auth-proxy-injector.fullname" . ) nil $altNames 3650 $ca -}}
caCert: {{ $ca.Cert | b64enc }}
caCertMap: {{ $ca  }}
clientCert: {{ $cert.Cert | b64enc }}
clientKey: {{ $cert.Key | b64enc }}
{{- end -}}
```

`templates/webhook.yaml`:

```go
{{ $tls := fromYaml ( include "webhook.certs" . ) }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "auth-proxy-injector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    caMap: {{ $tls.caCertMap }}
    app: {{ include "auth-proxy-injector.fullname" . }}
{{ include "auth-proxy-injector.labels" . | indent 4 }}
webhooks:
  - name: {{ include "auth-proxy-injector.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    clientConfig:
      caBundle: {{ if .Values.generateCerts }} {{ $tls.caCert }} {{ else }} {{ .Values.clusterCABundle }} {{ end }}
...
```

`tls_secret.yaml`:

```go
{{ $tls := fromYaml ( include "webhook.certs" . ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-proxy-injector.tlsname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "auth-proxy-injector.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ if .Values.generateCerts }} {{ $tls.clientCert }} {{ else }} {{ .Values.base64EncodedCertificate }} {{ end }}
  tls.key: {{ if .Values.generateCerts }} {{ $tls.clientKey }} {{ else }} {{ .Values.base64EncodedKey }} {{ end }}
```

`helm install --dry-run --debug ./ -n test` output (keys and certs truncated):

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: test-auth-proxy-injector
  namespace: default
  labels:
    caMap: map[-----BEGIN CERTIFICATE----- MIIDCD... -----END CERTIFICATE----- -----BEGIN RSA PRIVATE KEY----- MIIEpA... -----END RSA PRIVATE KEY-----:<nil>]
    app: test-auth-proxy-injector
    app.kubernetes.io/name: auth-proxy-injector
    helm.sh/chart: auth-proxy-injector-0.1.3
    app.kubernetes.io/instance: test
    app: auth-proxy-injector
    chart: auth-proxy-injector-0.1.3
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Tiller
webhooks:
  - name: test-auth-proxy-injector.default.svc.cluster.local
    clientConfig:
      caBundle:
...

apiVersion: v1
kind: Secret
metadata:
  name: test-auth-proxy-injector-tls
  namespace: default
  labels:
    app.kubernetes.io/name: auth-proxy-injector
    helm.sh/chart: auth-proxy-injector-0.1.3
    app.kubernetes.io/instance: test
    app: auth-proxy-injector
    chart: auth-proxy-injector-0.1.3
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Tiller
type: kubernetes.io/tls
data:
  tls.crt:  LS0tLS... 
  tls.key:  LS0tLS...
```

I expected `MutatingWebhookConfiguration.webhooks[0].clientConfig.caBundle` to not be empty. I'm seeing this issue on Minikube and on EKS clusters (Kubernetes 1.16)
