### ISSUE TITLE
Could not delete default keys from subcharts if subchart is defined in dependencies

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#9027]
Hi,

looking at docs https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key I'm able to remove keys from default values located in subcharts:

values.yaml:
```yaml
# demo/values.yaml:
global:
  hash:
    key1: null
    key2: null
    key3: 13

subchart:
  hash:
    key1: null
    key2: null
    key3: 13
---
# demo/charts/subchart/values.yaml:
global:
  hash:
    key1: 1
    key2: 2
    key3: 3
    key4: 4
    key5: 5
    key6: 6

hash:
  key1: 1
  key2: 2
  key3: 3
  key4: 4
  key5: 5
  key6: 6
```

Output:

```
jkr@joe-nb demo % helm template .
---
# Source: demo/charts/subchart/templates/values.yaml
global:
  hash:
    key3: 13
    key4: 4
    key5: 5
    key6: 6
hash:
  key3: 13
  key4: 4
  key5: 5
  key6: 6

```

But If I add:

```yaml
dependencies:
  - name: subchart
    version: 0.1.0
```

to the main Chart.yaml the behavior changes:

```
jkr@joe-nb demo % helm template .
---
# Source: demo/charts/subchart/templates/values.yaml
global:
  hash:
    key1: 1
    key2: 2
    key3: 13
    key4: 4
    key5: 5
    key6: 6
hash:
  key1: 1
  key2: 2
  key3: 13
  key4: 4
  key5: 5
  key6: 6

```

The merge of values is still working while removing key isn't working.
This bug exists on helm2 w/ requirements.yaml, too. Just for notice.

Output of `helm version`:

```
jkr@joe-nb demo % helm version  
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```

Demo: [chart.tar.gz](https://github.com/helm/helm/files/5549239/chart.tar.gz) (wrong file extension, its an uncompressed tar)

**Comment by bacongobbler** [comment]
The attachment you provided is not a gzipped tarball, FYI. Just a tar file.

```
><> tar xzf chart.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

I can reproduce this behaviour via the values file.

```
/tmp/test-9027/demo ><> helm template .
---
# Source: demo/charts/subchart/templates/values.yaml
global:
  hash:
    key1: 1
    key2: 2
    key3: 13
    key4: 4
    key5: 5
    key6: 6
hash:
  key1: 1
  key2: 2
  key3: 13
  key4: 4
  key5: 5
  key6: 6
```

However, this can be worked around by setting a value via `--set` to `null`.

```
/tmp/test-9027/demo ><> helm template . --set subchart.hash.key1=null,subchart.hash.key2=null
---
# Source: demo/charts/subchart/templates/values.yaml
global:
  hash:
    key1: 1
    key2: 2
    key3: 13
    key4: 4
    key5: 5
    key6: 6
hash:
  key3: 13
  key4: 4
  key5: 5
  key6: 6
```

**Comment by jkroepke** [comment]
Thanks for the info about the attachment, I add a note.

If you are removing

```
dependencies:
  - name: subchart
    version: 0.1.0
```

from Chart.yaml everything works as expected. 

I don't know if the YAML parser is wrong here but it seems like there is a different code path if dependencies are defined.

**Comment by sbaier1** [comment]
I am seeing a similar problem, except it's one layer deeper, making it even more annoying: I'm including [loki-stack](https://github.com/grafana/loki/tree/master/production/helm/loki-stack) as a sub-chart, which then has the `loki` chart as a sub-chart.

I am trying to remove the resulting `loki-stack.loki.config.storage_config.filesystem` key, which i can only do using `helm template --set loki-stack.loki.config.storage_config.filesystem=null` (as you also observed).

The only practical workaround appears to be to extract the chart locally and remove the actual default value itself.

Basic reproducer (helm version i used: v3.4.1):
- Chart.yaml with the loki-stack chart as dependency
- Override to delete in `values.yaml`:
```yaml
loki-stack:
  loki:
    config:
      storage_config:
       filesystem: null
```
- Run template and check the loki secret

**Comment by jkroepke** [comment]
My workaround conflicts with

https://github.com/helm/helm/issues/3585

If no dependency are defined, `helm lint` will fail.

**Comment by jkroepke** [comment]
.

**Comment by jkroepke** [comment]
.

**Comment by kkujawa-sumo** [comment]
I'm observing the same issue with helm 3.7.0 
```
$helm version
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

**Comment by kkujawa-sumo** [comment]
My case - I want to change `livenessProbe` for Fluent Bit. 
I can change `livenessProbe` when I deploy Fluent Bit Helm Chart:
```bash
helm repo add fluent-bit https://fluent.github.io/helm-charts
helm repo update

helm install test fluent-bit/fluent-bit --version 0.12.1 -f values-fluentbit.yaml
```
where `values-fluentbit.yaml` has this content:
```yaml
livenessProbe:
  httpGet: null
  exec:
    command:
    - /bin/bash
    - -exc
    - >
      function getOutTotalF0() { curl -s --connect-timeout 5 --retry 3 -f http://localhost:2020/api/v1/metrics/prometheus |grep '^fluentbit_output_proc_records_total{name="forward.0"}' | awk '{print $2}' ;};
      T=$(getOutTotalF0);test -e ./m_oprtf0 && { test $(cat ./m_oprtf0) -ge $T && { echo "OutputRecordsTotal Forward0 freeze: $T"; exit 1;} ;}; test $T -ge -10 && { echo "$T" >| ./m_oprtf0; } || true;
  initialDelaySeconds: 120
  periodSeconds: 60
  failureThreshold: 8
  timeoutSeconds: 5
```
and livenessProbe is correctly set:
```
$ kubectl get pods test-fluent-bit-gwv2g -o yaml
...
  containers:
  - image: fluent/fluent-bit:1.6.10
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - /bin/bash
        - -exc
        - |
          function getOutTotalF0() { curl -s --connect-timeout 5 --retry 3 -f http://localhost:2020/api/v1/metrics/prometheus |grep '^fluentbit_output_proc_records_total{name="forward.0"}' | awk '{print $2}' ;}; T=$(getOutTotalF0);test -e ./m_oprtf0 && { test $(cat ./m_oprtf0) -ge $T && { echo "OutputRecordsTotal Forward0 freeze: $T"; exit 1;} ;}; test $T -ge -10 && { echo "$T" >| ./m_oprtf0; } || true;
      failureThreshold: 8
      initialDelaySeconds: 120
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 5
...
```

when Fluent Bit is a sub chart in [sumologic helm chart ](https://github.com/SumoLogic/sumologic-kubernetes-collection) then default key from Fluent Bit helm chart is not removed, steps to reproduce:
```
helm repo add sumologic https://sumologic.github.io/sumologic-kubernetes-collection
helm repo update

# Deploy receiver mock - needed to test sumologic helm chart
kubectl apply -f "https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection/release-v2.1/vagrant/k8s/receiver-mock.yaml"

helm upgrade --install collection sumologic/sumologic \
  --namespace=sumologic \
  --version 2.1.5 \
  -f values_sumologic.yaml
```

where `values_sumologic.yaml` has this content:
```
sumologic:
  accessId: "dummy"
  accessKey: "dummy"
  endpoint: http://receiver-mock.receiver-mock:3000/terraform/api/

fluent-bit:
  livenessProbe:
    httpGet: null
    exec:
      command:
      - /bin/bash
      - -exc
      - >
        function getOutTotalF0() { curl -s --connect-timeout 5 --retry 3 -f http://localhost:2020/api/v1/metrics/prometheus |grep '^fluentbit_output_proc_records_total{name="forward.0"}' | awk '{print $2}' ;};
        T=$(getOutTotalF0);test -e ./m_oprtf0 && { test $(cat ./m_oprtf0) -ge $T && { echo "OutputRecordsTotal Forward0 freeze: $T"; exit 1;} ;}; test $T -ge -10 && { echo "$T" >| ./m_oprtf0; } || true;
    initialDelaySeconds: 120
    periodSeconds: 60
    failureThreshold: 8
    timeoutSeconds: 5
```
I'm getting this error in output from `helm upgrade`:
```
DaemonSet.apps "collection-fluent-bit" is invalid: spec.template.spec.containers[0].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type
```
in output from dry-run I see that default key from Fluent Bit helm chart is not deleted:
```yaml
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -exc
              - |
                function getOutTotalF0() { curl -s --connect-timeout 5 --retry 3 -f http://localhost:2020/api/v1/metrics/prometheus |grep '^fluentbit_output_proc_records_total{name="forward.0"}' | awk '{print $2}' ;}; T=$(getOutTotalF0);test -e ./m_oprtf0 && { test $(cat ./m_oprtf0) -ge $T && { echo "OutputRecordsTotal Forward0 freeze: $T"; exit 1;} ;}; test $T -ge -10 && { echo "$T" >| ./m_oprtf0; } || true;
            failureThreshold: 8
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 60
```

**Comment by R-omk** [comment]
Related https://github.com/helm/helm/issues/9136, or maybe duplicate

**Comment by danfromtitan** [comment]
Starting having this issue again with helm Version:"v3.7.2". In previous versions I used to carry an empty configuration key as such.

```
livenessProbe:
      httpGet:
      exec:
        command:
        - /bin/bash
        - -exc
        [...]
```

Leaving **httpGet** empty in outer values would override the httpGet probe from community chart values.

Now this workaround doesn't work anymore, the resulting template has two probes and helm installation trips over _Forbidden: may not specify more than 1 handler type_

**Comment by jkroepke** [comment]
.

**Comment by jkroepke** [comment]
Unstale

**Comment by acondrat** [comment]
This is so inconvenient! How can it be ignored for so long?

**Comment by turowicz** [comment]
> This issue has been marked as stale because it has been open for 90 days with no activity. This thread will be automatically closed in 30 days if no further activity occurs.

That's just great!

**Comment by jkroepke** [comment]
.

**Comment by Spitfire1900** [comment]
I've reproduced this also when attempting to define a pdb's `minAvailable` field in place of a subchart's default `maxUnavailable` field. The merge includes both a `minAvailable` and `maxUnavailable` field, which is invalid.

```yaml
    pdb:
      enabled: true
      maxUnavailable: null
      minAvailable: 1
 ```
 outputed:
 ```yaml
 spec:
  maxUnavailable: 50%
  minAvailable: 1
 ```

**Comment by CarpathianUA** [comment]
Pain in the ass for me as well :(

**Comment by mabdh** [comment]
> Starting having this issue again with helm Version:"v3.7.2". In previous versions I used to carry a null configuration key as such.
> 
> ```
> livenessProbe:
>       httpGet:
>       exec:
>         command:
>         - /bin/bash
>         - -exc
>         [...]
> ```
> 
> Leaving **httpGet** empty in outer values would override the httpGet probe from community chart values.
> 
> Now this workaround doesn't do anymore, the resulting template has two probes and helm installation trips over _Forbidden: may not specify more than 1 handler type_

I exactly faced the same issue with this. Trying to overriding livenessProbe that has a default value.

**Comment by GSeibt** [comment]
Using Helm `version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}` and the Traefik `20.3.0` chart as a dependency. I can't remove `traefik.updateStrategy.rollingUpdate` when setting `type` to `Recreate`. The Helm doc does not suggest that this is not possible...

**Comment by alfsch** [comment]
Struggling on the same issue with kube-prometheus-stack subcharts

**Comment by cschlesselmann** [comment]
Running into this issue as well, we deploy all our stuff with ArgoCD via helm dependencies and this is really makes some deployments impossible

**Comment by des-esseintes** [comment]
same issue on my side too (also via Argo CD)

**Comment by tonyqui** [comment]
I'm willing to help coding this @jkroepke, let me know if I may help somehow.

**Comment by jkroepke** [comment]
@tonyqui As I know, there is already a PR: https://github.com/helm/helm/pull/11440

**Comment by dastrobu** [comment]
Seems that #11440 did not make it to the 3.10.3 milestone.

**Comment by tonyqui** [comment]
That's the point.
As it's not part of 3.10.3 milestone I wonder if is there still anything missing or a lack of confidence that #11440 fix the issue correctly.

Any comment on this?

**Comment by jkroepke** [comment]
@tonyqui its better to ask this in the PR

**Comment by brsolomon-deloitte** [comment]
Still waiting on a fix.

**Comment by tspearconquest** [comment]
Also encountering this wanting to remove cpu limits in the falco chart when used as a subchart. I guess I will do it with `--set` for now but I'm leaving the value marked as null in values.yaml for whenever this is finally fixed.

**Comment by m-wack** [comment]
We are also unable to deploy a service to our Cluster because of this issue. 
Using ArgoCD and wanting to override default values of '10001' with none (which is a requirement for the chart in question) will fail linting because the null-value we set gets ignored by Helm as the chart is used as a dependency sub-chart.

Hopefully the PR at #11440 gets integrated soon, so we can deploy again.

**Comment by jkroepke** [comment]
Thanks for the info 👍

**Comment by rptaylor** [comment]
Removing keys in subcharts was supposed to be fixed by https://github.com/helm/helm/pull/12162  but the bug is still present in Helm 3.13.2 and 3.13.3: https://github.com/helm/helm/issues/12488  (The fix only works if --values is not used.)

**Comment by turowicz** [comment]
does it work for `-f` @rptaylor ?

**Comment by rptaylor** [comment]
> does it work for `-f values-file.yaml` @rptaylor ?

No, the behaviour for -f and --values is the same.

**Comment by messiahUA** [comment]
I'm experiencing this issue or similar with a chart that has a dependency. Using helm v3.13.3, executing:
`helm template chart -f values1.yaml -f values2.yaml`

values1.yaml contains some key and values2.yaml sets this key to null, but helm doesn't the key.

**Comment by ravnalexquinn** [comment]
I'm also still seeing what seems to be the bug in v3.14.0 

The following is defined in the values.yaml of a dependency sub-chart:
```
foo:
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 20Mi
```

If I set the below in my chart's values yaml the cpu limit is not removed from the sub-chart's values as it should be:
```
chartname:
  foo:
      resources:
        limits:
          cpu: null
          memory: 202Mi
        requests:
          cpu: 202Mi
          memory: 102Mi
```

Applied using: `helm template . --values my-values.yaml`
Also tried using: `helm template . --set chartname.foo.resources.limits.cpu=null --values my-values.yaml` to no avail
