### ISSUE TITLE
helm 3 does not honour the readiness probe handlers in Deployments when installing an initial Release

### ISSUE THREAD

**Issue by octplane** [helm/helm#9051]
This bugs happens when you install a release over previously existing Deployments in the cluster:

- A Deployment was created using kubectl earlier
- It has been patched to have the correct `Helm` release annotation attached
- Upon initial install, the `readinessProbe` rules are not correctly updated and Helm fails to install the Release because it does not remove the previous readinessProbe handler correctly from the live object.

This is a sibling of #9049 

Use the attached [tc.zip](https://github.com/helm/helm/files/5583320/tc.zip) to reproduce:
## Render and apply manually the default release

```
./helm template first tc > manifest.yaml
kubectl apply -f manifest.yaml
```

## Patch the deployment to add the Helm annotations

```
kubectl patch deploy readiness-tcp-breaker -p '{"metadata":{"annotations":{"meta.helm.sh/release-name":"first", "meta.helm.sh/release-namespace": "delivery-platform"}}}'
```

## Install the release and change its readinessProbe

```
./helm install first tc -f tc/values/breaking.yaml
Error: cannot patch "readiness-tcp-breaker" with kind Deployment: Deployment.apps "readiness-tcp-breaker" is invalid: spec.template.spec.containers[0].readinessProbe.tcpSocket: Forbidden: may not specify more than 1 handler type
```

This will fails despite the new manifest being well-formed:

```
---
# Source: crd/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-tcp-breaker
  namespace: delivery-platform
spec:
  minReadySeconds: 45
  selector:
    matchLabels:
      app.kubernetes.io/instance: crd-first
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: crd-first
    spec:
      containers:
      - name: goproxy
        image: k8s.gcr.io/goproxy:0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
```

### System info

Output of `helm version`:

```
./helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.11-beta.1-dd.2", GitCommit:"aad6faa4b873b634be466d2801e37ae39e849874", GitTreeState:"clean", BuildDate:"2020-01-03T13:42:24Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

- On prem.
