### ISSUE TITLE
Aliased dependencies condition not respecting specified default value

### ISSUE THREAD

**Issue by oliviermichaelis** [helm/helm#9052]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.15.4"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-15T17:26:49Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
**Issue**
The dependencies of a helm chart fail to respect their `condition` in case the dependency has an `alias`. I've prepared a repo that reproduces the error here: https://github.com/oliviermichaelis/helm-bug-reproduction.
The charts have the following structure:
```
umbrella1:
  parent1:
    dep
  parent1:
    dep
umbrella2:
  parent2:
    dep
  parent2:
    dep

```
The `parent2` chart has the following dependency in the `Chart.yaml` with `condition: depAlias.enabled` :
```
dependencies:
  - name: dep
    alias: depAlias
    version: "0.1.0"
    repository: "file://../dep"
    condition: depAlias.enabled
```
The `values.yaml` disables the dependency by default:
```
depAlias:
  enabled: false
```
However, the `umbrella2` charts subdependency `dep` is rendered, even though it should be disabled:
```
$ helm template test ./umbrella2   
---
# Source: umbrella2/charts/parent2b/charts/dep/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-dep
  labels:
    helm.sh/chart: dep-0.1.0
    app.kubernetes.io/name: dep
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dep
    app.kubernetes.io/instance: test
```
Note that only a single resource is rendered, not both. I guess it has something to do with how the hierarchical values are merged.

---
In order to help to better understand what's going on, I have included the `umbrella1` chart without an `alias`. 
The `parent1` chart has the following dependency in the `Chart.yaml` with `condition: dep.enabled` :
```
dependencies:
  - name: dep
    alias: dep
    version: "0.1.0"
    repository: "file://../dep"
    condition: dep.enabled
```
The `values.yaml` disables the dependency by default:
```
dep:
  enabled: false
```
As expected, the `dep` subcharts are not rendered:
```
$ helm template test ./umbrella1

```

Thanks for having a look, I'm happy to help where I can! :)

**Comment by bacongobbler** [comment]
What's interesting with your example is that it appears the second alias falls under two failing conditions here:

1. Notice that `parent2a`'s dependency called `dep`. Not `depAlias`.
2. Because of the first point, it appears there is no way to disable it, as there is no condition set.

If you modify your example a little bit by removing `parent2/values.yaml`, then call `helm dep up` on `umbrella2`, the issue is easier to see:

```
~/code/helm-bug-reproduction/umbrella2 ><> rm ../parent2/values.yaml 
~/code/helm-bug-reproduction/umbrella2 ><> helm dep up
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Deleting outdated charts
~/code/helm-bug-reproduction/umbrella2 ><> helm template ./
---
# Source: umbrella2/charts/parent2a/charts/depAlias/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-depAlias
  labels:
    helm.sh/chart: depAlias-0.1.0
    app.kubernetes.io/name: depAlias
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: depAlias
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: umbrella2/charts/parent2b/charts/dep/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-dep
  labels:
    helm.sh/chart: dep-0.1.0
    app.kubernetes.io/name: dep
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dep
    app.kubernetes.io/instance: RELEASE-NAME
```

Notice how `parent2a` refers to the sub-sub-dependency as `depAlias`, while `parent2b` refers to it as `dep` (looking at the line where it says `# Source:`, FYI).

I tried a number of values. Disabling `parent2a`'s sub-sub-dependency was simple. But I could not determine how to disable `parent2b`'s sub-sub-dependency.

```
~/code/helm-bug-reproduction/umbrella2 ><> helm template . --set parent2a.depAlias.enabled=false,parent2b.depAlias.enabled=false,parent2b.dep.enabled=false,depAlias.enabled=false,dep.enabled=false
---
# Source: umbrella2/charts/parent2b/charts/dep/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-dep
  labels:
    helm.sh/chart: dep-0.1.0
    app.kubernetes.io/name: dep
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dep
    app.kubernetes.io/instance: RELEASE-NAME
```

Let us know what you discover. I look forward to seeing a patch!
