### ISSUE TITLE
helm template's --output-dir flag unexpectedly influence rendering of hook resources

### ISSUE THREAD

**Issue by consideRatio** [helm/helm#9061]
## Bug description

When `helm template` is used on a template file with multiple resources in it of which some have a `helm.sh/hook` annotation, then only the hook annotated resources will render if `--output-dir` is used.

## Template for reproduction

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: not-a-hook
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: a-hook
  annotations:
    # what matters seem to be that "helm.sh/hook" is specified at all
    "helm.sh/hook": pre-install,pre-upgrade
```

## Versions

Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

---

Ping @zhouhao3 who is working to address #9018 in #9026 :heart: :tada:! This issue is a related as both issues regard the `--output-dir` flag for `helm template` so I figured you may be interested knowing about it also!
