### ISSUE TITLE
range can't iterate over

### ISSUE THREAD

**Issue by ziyou434** [helm/helm#9064]
I use helm install --dry-run --debug debugging my chart.

deployment.yaml
```yaml
...
          volumeMounts:
            - mountPath: /usr/local/apisix/conf/config.yaml
              name: apisix-config
              subPath: config.yaml
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
              {{- range $customerPlugin := .Values.customerPlugins}}
            - mountPath: /usr/local/apisix/apisix/plugins/{{ $customerPlugin }}
              name: apisix-config
              subPath: {{ $customerPlugin }}
              {{- end }}
...
```
values.yaml

```yaml
customerPlugins:
  hmac-auth.lua
  count.lua
```

```
[root@localhost gjn]# helm install mychart --dry-run --debug ./apisix
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /home/gjn/apisix

Error: template: apisix/templates/deployment.yaml:95:50: executing "apisix/templates/deployment.yaml" at <.Values.customerPlugins>: range can't iterate over hmac-auth.lua
helm.go:94: [debug] template: apisix/templates/deployment.yaml:95:50: executing "apisix/templates/deployment.yaml" at <.Values.customerPlugins>: range can't iterate over hmac-auth.lua

```
I think I may not use the function well, but I don't know how to use range() to achieve my target. 
I hope you can give me some advices.
