### ISSUE TITLE
Helm doesnt seem to like having booleans in the values file

### ISSUE THREAD

**Issue by pbalexlear** [helm/helm#9077]
Output of `helm version`:
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}

Also on helm version 
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS on Azure 

Error:
Error: UPGRADE FAILED: failed to create resource: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true},{"nam|..., bigger context ...|d7ced4d597"},{"name":"BASICAUTH_ENABLED","value":true}

in the values file we have :

`basicauthEnabled: true`

when this is set like this we get the above error, if we change this to be 

`basicauthEnabled: "\"true\""`

the error goes away and the chart is correctly installed.

the reference to this value is in our deployment.yaml as follows:

          - name: BASICAUTH_ENABLED
            value: {{ .Values.basicauthEnabled }}

inside the env section of our pod spec. Please let me know if more information is required.

**Comment by bacongobbler** [comment]
The kubernetes specification requires that environment variables are represented as a string value. They cannot be integers, booleans, or other types. You can use the `quote` function to ensure a value is wrapped in quotes which will coerce it as a string.

Hope that makes sense.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by Wang-Kai** [comment]
Thanks for the great project, the helm help our team to improve CI/CD efficiency. In my company, we use gitlab CI to deliver sofeware. Our `.gitlab.yml` like :

```yaml
dry_run_merge_to_develop_branch:
  stage: dry_run
  image: $HELM_CD_IMAGE
  script:
  # test
  - kubens pre-shchildren-manager
  - helm upgrade --dry-run --install shchildren -f pre/manifest.yaml -f pre/env.yaml chart

upgradePreEnv:
  stage: upgrade
  image: $HELM_CD_IMAGE
  script:
  # upgrade project
  - kubens pre-shchildren-manager
  - helm upgrade --cleanup-on-fail --install shchildren -f pre/manifest.yaml -f pre/env.yaml chart
```

Due to we use ConfigMap as environment variables frequently，we make mistake because use Interge or Boolean as environment variables. It can not be found by `helm --dry-run`. Dose the helm team deside to solve it ?
