### ISSUE TITLE
enabled field Charts.yaml

### ISSUE THREAD

**Issue by indrojeet1061** [helm/helm#9079]
Hi!
I do not think its a bug but may be some unclear documentation. 

Output of `helm version`:
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"} 

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform: AWS 

Description : 
I am trying to use "enabled" field in the Charts.yaml. Here's how my Charts.yaml file look like : 

```
apiVersion: v2
appVersion: "${revision}"
name: "${chart.name}"
description: Demo Work
version: 1.0.0 

dependencies:
- name: AA
  repository: file://AA
  version: 1.0.0 
  enabled: true
- name: BB
  repository: file://BB
  version: 1.0.0 
  enabled: true
- name: CC
  repository: file://CC
  version: 1.0.0 
  enabled: true
- name: DD
  repository: file://DD
  version: 1.0.0 
  **enabled: false**
```

My assumption here was when I have enabled set to false , the DD chart would not be loaded (also not zipped in the charts/ folder) when I do a helm dep update. But even having enabled set to false , this charts gets loaded and installed on kubernetes cluster. 
I understand this can be achieved with conditional field in CHarts.yaml but for now I don't want to try that. 
Have a missed it somewhere ?
Please let me know if you need more information.
