### ISSUE TITLE
Templatize CRD in helm v3.x

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [helm/helm#9081]
Although i know it's not recommended to templatize CRDs for helm chart but is there any way to do so ? Currently, I have written a helm chart for an operator that has webhooks enabled and i'll have to templatize an annotation to inject certs i.e. c`ert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)`

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: mock.example.com
```

What is the recommended approach for handling such a scenario ? I have the following possible alternates:

- Keeping the crd in templates, although i think this would fail when we will use helm releases because CRD is a pre-req for webhooks. And using something like values.crds.create to create them
- Hard code the namespace name in crd, something i wouldn't prefer
- Keep the CRD in separate folder from the helm chart all together. And maintain it separately from the helm chart. User will need to install crds and then the helm chart. This is something i am more inclined towards since helm in general doesn't support update/delete for CRDs and that is still a manual step i.e. if you keep them in crds folder.

Output of `helm version`:
`v3.4.1`

Output of `kubectl version`:
`v1.19.0`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS(although not a cloud dependent query/issue)
