### ISSUE TITLE
When migrating from Helm 2 to 3 re-annotating and re-labelling leaves Deployment unusable

### ISSUE THREAD

**Issue by onkobu** [helm/helm#9082]
A broken re-naming way back in the past with Helm 2 left me with two Helm releases with different names. Currently helm upgrade with Helm 3.4.1 is failing with errors.

Moving everything out of the --tiller-namespace succeeded. Now resources (gateway, ingress, service, deployment, ConfigMaps) are still spread across the two releases. As suggested in other issues I used `kubectl annotate` and `kubectl label` to fix meta.helm.sh/release-name, meta.helm.sh/release-namespace and app.kubernetes.io/managed-by for every resource in the old release. I also used --overwrite, even if the label/ annotation was already set to the same value.

After doing so one environment got along and `helm upgrade` succeeded. The other failed with:

```
Error: UPGRADE FAILED: cannot patch "the-app" with kind Deployment: Deployment.apps "the-app" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"the-app", "release":"the-app-test-ns"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

I also checked multiple times, that deployment.yaml has correct spec.selector and spec.template-settings. The first one creates an anchor &appLabels. The second one uses this anchor with *appLabels. Manifests of current release of both environments only differ in the attribute for the label release – silly but legacy to have the environment as infix to set them apart. (I'm aware that --namespace is already sufficient separation.)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 2
  labels:
    app: {{ .Chart.Name }}
    chart: {{ $chart }}
    build: {{ .Values.image.tag | quote }}
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels: &appLabels
      app: {{ .Chart.Name }}
      release: "the-app-{{ .Release.Namespace }}"
  template:
    metadata:
      labels: *appLabels
      name: {{ .Chart.Name }}
```
Release.Namespace/ namespace is set to the-app-test-ns accordingly, also visible in the output (omitted the header section with a few {{- printf  -}} and definition of $chart).

Deleting the old release from the failing environment (without --purge) made `helm upgrade` succeed but also caused a downtime since pods were taken down completely followed by re-creating them. I'd like to do it with no downtime and adopt all the resources from the old release for the new one.

What did I miss? Where did I go wrong?
