### ISSUE TITLE
How to pass 'global' variables to subcharts

### ISSUE THREAD

**Issue by akosyrev** [helm/helm#9111]
Output of `helm version`: version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

Hello, I have a chart with set of subCharts('redis', etc).
I put this variables to values.yaml and want to pass them to subChart's values:

```
securityContext:
  fsGroup: "1000240000"
  runAsUser: "1000240000"
...
redis:
  master:
    securityContext:
      fsGroup: "{{ .Values.securityContext.fsGroup }}"
      runAsUser: "{{ .Values.securityContext.runAsUser }}"
```
When I run
`helm template app ./ -f /tmp/values.yaml -n app-ns > /tmp/app-templated.yaml --debug`
I get an error in subChart's template:
```
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /home/akosyrev/git-repos/glados/k8s/glados

Error: YAML parse error on **app/charts/redis/templates/redis-master-statefulset.yaml**: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.securityContext.fsGroup":interface {}(nil)}
helm.go:81: [debug] error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.securityContext.fsGroup":interface {}(nil)}
YAML parse error on glados/charts/redis/templates/redis-master-statefulset.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
    /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
...
```

I guess the main problem is that ".Values.securityContext.fsGroup" is not visible for redis as subchart. Is it possible to fix this without changing subcharts?

And it seems helm does not substitute {{ }} placeholders in values.yaml with real values before applying it's values to charts. Can I force this substitution somehow?

**Comment by mattfarina** [comment]
You're passing `.Values.master.securityContext.fsGroup` to the _redis_ chart. Notice the use of master in there. Did you mean to have `master` as part of the path or did you need to remove that section from the YAML?

**Comment by akosyrev** [comment]
Sorry if my question in OP was unclear. 
Subchart's template `app/charts/**redis**/templates/redis-master-statefulset.yaml` contains:
```
...
      securityContext:
        fsGroup: {{ .Values.master.securityContext.fsGroup }}
        runAsUser: {{ .Values.master.securityContext.runAsUser }}
...
```
Helm trying to read these `.Values.master.securityContext.fsGroup`  and `.Values.master.securityContext.runAsUser` from this part of values.yaml:
```
**redis**:
  master:
    securityContext:
      fsGroup: "{{ .Values.securityContext.fsGroup }}"
      runAsUser: "{{ .Values.securityContext.runAsUser }}"
```
because subchart **redis** has same name as key in values.yaml. And on this step helm fails as it cannot resolve `.Values.securityContext.fsGroup` and `.Values.securityContext.runAsUser` - they are out of scope for redis subchart.

If I set this values helm works without any issue: 
```
...
**redis**:
  master:
    securityContext:
      fsGroup: "1001"
      runAsUser: "1001"
...
```
