### ISSUE TITLE
Add a function to generate sha256 hash from maps (i.e. `.Values`)

### ISSUE THREAD

**Issue by MOZGIII** [helm/helm#9120]
This is a feature request.

There is a recommended trick to restart the `Pod`s when the `ConfigMap` template changes:

```yaml
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
[...]
```

I'd like to have another annotation, that would generate a hash value over arbitrary maps. I intend to pass the `.Values` into it, to effectively produce a hash of the input configuration:

```gotemplate
sha256summap .Values
```

I'd use it like this:

```yaml
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/values: {{ sha256summap .Values }}
[...]
```

The tricky part here is that this function should traverse the map keys in a reliable order.

**Comment by MOZGIII** [comment]
I figured this works for me:

```gotpl
{{/*
Values checksum annotation.
*/}}
{{- define "libvector.valuesChecksumAnnotation" -}}
{{- $global := default (dict) .Values.global }}
{{- $global := default (dict) $global.vector }}
{{- $enabled := .Values.podValuesChecksumAnnotation }}
{{- if hasKey $global "podValuesChecksumAnnotation" }}
{{- $enabled = $global.podValuesChecksumAnnotation }}
{{- end }}
{{- if $enabled }}
checksum/values: {{ toJson .Values | sha256sum }}
{{- end }}
{{- end }}
```

I guess this trick can be added to the docs too.

**Comment by MOZGIII** [comment]
Also, it looks like a simple fix for the recommended trick would suffice:

```yaml
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ tpl (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/values: {{ sha256summap .Values }}
[...]
```

Notice that `tpl`  instead of `include` at `tpl (print $.Template.BasePath "/configmap.yaml") . | sha256sum`.
