### ISSUE TITLE
helm package removes multiple version of the same subchart.

### ISSUE THREAD

**Issue by czerwe** [helm/helm#9128]
Hi, i am using the feature to use the same dependency chart twice by using an alias. I do switch between those two by using tags.

Thats part of my chart.yaml:

```
dependencies:
  - name: vsa
    alias: transcoderExperimental
    version: 6.0.0-rc2
    repository: "https://artifacts.core.pke.de/artifactory/helm-stable"
    tags:
      - experimental
  - name: vsa
    alias: transcoderExperimental
    version: 5.3.1
    repository: "https://artifacts.core.pke.de/artifactory/helm-stable"
    tags:
      - production
```

if i do update the dependecies i get both version inside the charts directory. But if i execute an 
`helm package <chartname>` the resulting .tgz does contain unpacked directorys. The problem is that both version contain the same directory so only one version resides that way.

I guess currently the only possibility is to pack it myself and upload it that way, correct?

Is this an known or wanted behavior?

Output of `helm version`:
`version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:17:09Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  
on-prem vanilla kubernetes
