### ISSUE TITLE
Changes to comments are seen as changes to the resource

### ISSUE THREAD

**Issue by zaphod72** [helm/helm#9134]
```
➜ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.50", GitCommit:"bc01f00cf59008a36aa47f67c37c36b9d66db718", GitTreeState:"clean", BuildDate:"2020-09-09T03:06:32Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

I edited a comment above a PersistentVolumeClaim definition. Helm upgrade failed with:

`Error: UPGRADE FAILED: failed to replace object: PersistentVolumeClaim "cbc-stable-backup-storage" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims`

Here is the helm diff output:

```
  # Source: couchbase-backup/templates/persistentvolumeclaims.yaml
- # Define backup storage volume---
+ # Define backup storage volume
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: cbc-stable-backup-storage
  spec:
    storageClassName: cbc-stable-backup-fast-storage
    resources:
      requests:
        storage: 15Gi
    accessModes:
      - ReadWriteOnce # ReadWriteOnce
```
