### ISSUE TITLE
helm install cannot find chart x.y.z-prerelease when omiting --version

### ISSUE THREAD

**Issue by donatelloOo** [helm/helm#9148]
Helm cannot find the latest pre-release version of an helm chart.

Let's suppose we build a chart using a pre-release SemVer2 compliant version: `/path/to/charts/my-chart-1.0.0-alpha.tgz`

We build a repository index using: `helm repo index my-repo /path/to/charts/`
The output is like:
```
apiVersion: v1
entries:
  my-chart:
  - apiVersion: v2
    appVersion: 1.0.0-alpha
    created: "2020-12-18T10:31:02.3844024+02:00"
    description: my chart (alpha version)
    digest: c2c535712c9c96c37cc4d5badc3ff39fdd629b808d41cf14107096819908d8a1
    urls:
    - my-chart-1.0.0-alpha.tgz
    version: 1.0.0-alpha
generated: "2020-12-18T10:31:02.3310774+02:00"
```
> Note that to reproduce you can serve this file by running a simple http server like `python3 -m http.server 8000` in the same directory

Now **we want to install the latest version** of this chart so we use the following command:
`helm install my-release my-chart --repo http://helm-repo.server.local/ --dry-run --debug`
> Note that we deliberately omit `--version`, so that when the release will be out, we will use it automatically

Unfortunately, **when there is only pre-releases version**, the output is:
```
install.go:172: [debug] Original chart version: ""
Error: chart "my-chart" not found in http://helm-repo.server.local/ repository
helm.go:94: [debug] chart "my-chart" not found in http://helm-repo.server.local/ repository
helm.sh/helm/v3/pkg/repo.FindChartInAuthRepoURL
        /home/circleci/helm.sh/helm/pkg/repo/chartrepo.go:244
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        /home/circleci/helm.sh/helm/pkg/action/install.go:657
```

This is NOT compliant with SemVer2 specification which states that the precedence of pre-release version should also be supported: https://semver.org/#spec-item-11

Of course, we would also expect precedence to be properly computed for multiple pre-releases version, as specified by SemVer2 specifications,
like: `1.0.0-alpha < 1.0.0-beta < 1.0.0-beta2 < 1.0.0-beta3`

Output of `helm version`: version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
