### ISSUE TITLE
Hook with ConfigMap

### ISSUE THREAD

**Issue by jycamier** [helm/helm#9163]
Refering to the documentation, (https://helm.sh/docs/topics/charts_hooks/) I have try to load a ConfigMap during `pre-install` and  `pre-upgrade` hooks.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
  name: pre-install-job-cm
data:
  1.json: |-
    {
      "foo": "bar"
    }
  2.json: |-
    {
      "foobar": "foobar"
    }

---

apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
  name: helm-hook-job-sample
spec:
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    spec:
      containers:
      - command:
        - /bin/sleep
        - "60"
        image: alpine:3.3
        name: c
        volumeMounts:
        - mountPath: /data
          name: foo
      restartPolicy: Never
      volumes:
      - configMap:
          name: pre-install-job-cm
        name: foo
```

My Job is creating during the "hook step" but not my ConfigMap.

Output of `helm version`: 
```
3.3.0
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
```
Minikube
```

**Comment by sisimora** [comment]
I was able to load the configmap by adding `helm.sh/hook-weight: "-1"` in the annotations of configmap.yaml
```

metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "-1"
  name: pre-install-job-cm
```

As the default hook-weight is 0 (job), adding the hook-weight -1 to configmap, will force helm to load configmap first, before the job.
