### ISSUE TITLE
Helm Template ordering breaks dependent environment variables

### ISSUE THREAD

**Issue by Sovietaced** [helm/helm#9165]
Hello. We have an application that has [dependent environment variables](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/). 

For instance, our environment variables may be declared this like in the helm chart. (A is dependent on B and C)
```
    env:
    - name: B
      value: "Hello"
    - name: C
      value: "World"
    - name: A
      value: "$(B) $(C) "
```

If this were in a raw kubernetes manifest this would result in an environment variable `A` with the value "Hello World". However, when we generate our kubernetes manifest using helm template, it seems that the environment variables are generate in sorted order. As a result, `A` has a value of "$(B) $(C) ". 

```
    env:
    - name: A
      value: "$(B) $(C) "
    - name: B
      value: "Hello"
    - name: C
      value: "World"
```

It would be nice if there were a way to omit some things from being sorted. 

Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-cc7316", GitCommit:"cc731611ec6dcf69c8c3e98a1b1650b5fb32b2e3", GitTreeState:"clean", BuildDate:"2020-08-05T16:25:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS EKS

**Comment by mattfarina** [comment]
Thanks for providing a base example to try and reproduce. Unfortunately, I was unable to reproduce your situation.

Helm does not have special handling to sort this kind of information. When Helm reads YAML, such as when reading the `values.yaml` file, it uses the same parser as Kubernetes. Their internal storage is Go variables and follow the semantics of those. When they are written it depends on the template functions used.

How did you specify the environment variables for the chart? How did you inject them into the templates?

When I tried, I copied your first block into my `values.yaml` file. I then used ...

```
env:
  {{- toYaml .Values.env | nindent 12 }}
```
 to inject them into a template.

Did you do something differently?

**Comment by Sovietaced** [comment]
> Did you do something differently?

Thanks for trying to reproduce the issue. Here is some more context. 

We have some templating code which takes in a dictionary and produces environment variables like so. 

```
env:
  {{- with .Values.env }}
  {{- range $field, $env := . }}
  {{ $name := $field | snakecase | upper }}
  {{- if ne ($env | typeOf) "string" }}
    {{- if hasKey $env "name" }}
      {{- $name = $env.name }}
    {{- end }}
  {{- end }}
  - name: {{ $name }}
  {{- if eq ($env | typeOf) "string" }}
    value: {{ required (printf "String value is required for '%s' env variable" $name) $env | quote }}
  {{- else if hasKey $env "value" }}
    {{- if hasKey $env "optional" }}
      {{- if $env.optional }}
    value: {{ $env.value | quote }}
      {{- else }}
    value: {{ required (printf "Value '.value' is required for '%s' env variable" $name) $env.value | quote }}
      {{- end }}
    {{- else }}
    value: {{ required (printf "Value '.value' is required for '%s' env variable" $name) $env.value | quote }}
    {{- end }}
  {{- else if hasKey $env "valueRef" }}
    value: {{ tpl (printf "{{ %s }}" $env.valueRef) $ | quote }}
  {{- else if hasKey $env "fieldRef" }}
    valueFrom:
      fieldRef:
        fieldPath: {{ required (printf "Value '.fieldRef' is required for '%s' env variable" $name) $env.fieldRef | quote }}
  {{- else if hasKey $env "secretRef" }}
    valueFrom:
      secretKeyRef:
        name: {{ required "Value (env) '.secretRef.name' is required" $env.secretRef.name | quote }}
        key: {{ required "Value (env) '.secretRef.key' is required" $env.secretRef.key | quote }}
  {{- else if hasKey $env "configRef" }}
    valueFrom:
      configMapKeyRef:
        name: {{ required "Value (env) '.configRef.name' is required" $env.configRef.name | quote }}
        key: {{ required "Value (env) '.configRef.key' is required" $env.configRef.key | quote }}
  {{- else if hasKey $env "volumeRef" }}
    {{- if hasKey $.Values "volumes" }}
    {{- $found := false}}
    {{- with $.Values.volumes }}
      {{- range $name, $volume := . }}
        {{- if eq $env.volumeRef $name }}
        {{ $found = true }}
    value: {{ $volume.mountPath | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if not $found}}
      {{- fail (printf "Cannot create %s env var, no volume found with name %s" $name $env.volumeRef)}}
    {{- end }}
    {{- end }}
  {{- else }}
    {{- fail "Either (env) '.value', '.valueRef', '.fieldRef', '.secretRef', '.configRef', '.volumeRef' field is required for env variable" }}
  {{- end -}}
  {{- end -}}
  {{- end -}}
{{- end -}}
```

The input would look something like this
```
- env:
        - name: KEY_CONFIG
          valueFrom:
            configMapKeyRef:
              key: configmap_data_key
              name: configmap-name
        - name: KEY_FIELD
          valueFrom:
            fieldRef:
              fieldPath: some.field.ref
        - name: KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: secret_data_key
              name: secret-name
        - name: KEY_VAL
          value: env_var_value
        - name: KEY_VAL_DIRECTLY
          value: env_var_value_as_string_also_do
        - name: KEY_VOLUME
          value: /jwt/truststore.p12
        - name: OPTIONAL_KEY_VAL
          value: ""
        - name: PORT
          value: "123"
```

It seems that the range function (which seems to be the recommended way to iterate) iterates through the map keys in sorted order. To me this behavior is quite unusual as maps / dictionaries typically have non deterministic iteration order. 

I guess non deterministic iteration is also not helpful for me though. I need the iteration order to match the insertion? order.

**Comment by Sovietaced** [comment]
I am particularly confused because the documentation has the following example, which seems to maintain the insertion order.

Input
```
favorite:
  drink: coffee
  food: pizza
pizzaToppings:
  - mushrooms
  - cheese
  - peppers
  - onions
```

Template
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  {{- end }}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end }}
```

Result
```
# Source: mychart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgy-dragonfly-configmap
data:
  myvalue: "Hello World"
  drink: "coffee"
  food: "PIZZA"
  toppings: |-
    - "Mushrooms"
    - "Cheese"
    - "Peppers"
    - "Onions"
```
