### ISSUE TITLE
Helm Access Environment Variables in the Container 

### ISSUE THREAD

**Issue by rajivml** [helm/helm#9178]
Hi,

When am building the image path, this is how I want to build the image Path, where the docker registry address, I want to fetch it from the configMap.

I can't hard code the registry address in the values.yaml file because for each customer the registry address would be different and I don't want to ask customer to enter this input manually. These helm charts are deployed via argoCD, so fetching registryIP via shell and then invoking the helm command with set override is not an option

I tried below code, it isn't working because the env variables will not be available in the context where image path is constructed.

Is it possible to achieve this using helm templating ? if yes, can you please share an example, I have spent quite a lot of time figuring it out but couldn't get it right 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "helm-guestbook.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- if eq .Values.isOnPrem "true" }}
          image: {{ printf "%s/%s:%s" $dockerRegistryIP .Values.image.repository .Values.image.tag }}
          {{- else }}
          env:
         - name: DOCKER_REGISTRY_IP
            valueFrom:
              configMapKeyRef:
                name: docker-registry-config
                key: DOCKER_REGISTRY_IP
```
