### ISSUE TITLE
Unable to use helm but kubectl works just fine

### ISSUE THREAD

**Issue by aanogueira** [helm/helm#9213]
Hello,

When I try to do any operation with helm I get the following error: (ex: helm ls -A)
`Error: Kubernetes cluster unreachable: Get "https://192.168.33.10:15000/version?timeout=32s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")`

The same error doesn't apply to kubectl, where I can do any opperation.

Kind config:
```yaml
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
kubeadmConfigPatches:
- |
  apiServer:
    certSANs:
      - localhost
      - 127.0.0.1
      - 192.168.33.10
    extraArgs:
      authorization-mode: Node,RBAC
      timeoutForControlPlane: 4m0s
      enable-admission-plugins: NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,DefaultIngressClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
networking:
  disableDefaultCNI: true
  podSubnet: 10.100.0.0/16
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
```

The major change I made was generating new certificates in order to be able to access the server through that IP address (192.168.33.10):

```shell
docker exec `docker ps | grep control | cut -d" " -f 1` mv /etc/kubernetes/pki/apiserver.crt /etc/kubernetes/pki/apiserver-etcd-client.key /etc/kubernetes/pki/apiserver-kubelet-client.crt /etc/kubernetes/pki/front-proxy-ca.crt /etc/kubernetes/pki/front-proxy-client.crt /etc/kubernetes/pki/front-proxy-client.key /etc/kubernetes/pki/front-proxy-ca.key /etc/kubernetes/pki/apiserver-kubelet-client.key /etc/kubernetes/pki/apiserver.key /etc/kubernetes/pki/apiserver-etcd-client.crt /root
docker exec `docker ps | grep control | cut -d" " -f 1` kubeadm init phase certs all --apiserver-advertise-address `kubectl get no -o wide | grep control | cut -d" " -f 16` --apiserver-cert-extra-sans 192.168.33.10,127.0.0.1
docker exec `docker ps | grep control | cut -d" " -f 1` mv /etc/kubernetes/admin.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/scheduler.conf /root
docker exec `docker ps | grep control | cut -d" " -f 1` kubeadm init phase kubeconfig all
docker restart `docker ps | grep control | cut -d" " -f 1`
```

> Configuration done on the control-plane container.

**Output of `helm version`:**
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}

**Output of `kubectl version`:**
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-14T07:56:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):**
kind version 0.9.0 running Kubernetes v1.16.15

**Comment by aanogueira** [comment]
Found out what the problem was.
Since the name of the kubeconfig was different from name of the cluster:

```yaml
clusters:
  - cluster:
      name: kind-sandbox
```

The helm was detecting the certificate present inside the file.
Since I need to connect to multiple clusters, the way I populate the `KUBECONFIG` environment variable is through a script:

```shell
#!/usr/bin/env bash

DEFAULT_KUBECONFIG_FILE="$HOME/.kube/config"

if test -f "${DEFAULT_KUBECONFIG_FILE}"
then
  export KUBECONFIG="$DEFAULT_KUBECONFIG_FILE"
fi

ADD_KUBECONFIG_FILES="$HOME/.kube/config-files"
mkdir -p "${ADD_KUBECONFIG_FILES}"

OIFS="$IFS"
IFS=$'\n'
for kubeconfigFile in `find "${ADD_KUBECONFIG_FILES}" -type f -name "*.yml" -o -name "*.yaml"`
do
    export KUBECONFIG="$kubeconfigFile:$KUBECONFIG"
done
IFS="$OIFS"
```

If I set the `KUBECONFIG` variable with the value `~/.kube/config` it works just fine.
With the script approach, the name of the file needs to mach `name` inside the file.
