### ISSUE TITLE
Built in object .Chart.dependency[].name is overridden by .Chart.dependency[].alias

### ISSUE THREAD

**Issue by consideRatio** [helm/helm#9214]
I read [in the docs](https://helm.sh/docs/chart_template_guide/builtin_objects/) about the .Chart built in object.

![image](https://user-images.githubusercontent.com/3837114/125372940-8286e980-e384-11eb-9ffc-e9654139a829.png)

I concluded that if the above statement were true, I could by using `.Chart.dependencies` draw conclusions if a certain chart was listed as a dependency. This turned out to be incorrect, as when I inspected the .Chart object I found that the `name` field of the chart dependency had been overridden with the `alias` field.

In the output below, I expected to see `name: jupyterhub` and `alias: dep-chart-alias`, but now both keys name and alias had the value `dep-chart-alias`. In other words, what was listed in Chart.yaml wasn't reflected correctly in the built in .Chart object!

## Reproduction

__Terminal commands__
```
helm create testchart
cd testchart
# update Chart.yaml and configmap.yaml

helm dep up
helm template . --set dep-chart-alias.proxy.secretToken=asdf | grep -A 10 FINDME
```

__Terminal commands output__
```
  FINDME: |
    apiVersion: v2
    dependencies:
    - alias: dep-chart-alias
      enabled: true
      name: dep-chart-alias
      repository: https://jupyterhub.github.io/helm-chart
      version: 0.10.6
    name: testchart
    version: 0.1.0
```

__Chart.yaml__
```yaml
apiVersion: v2
description: irrelevant
name: irrelevant
version: 0.1.0
dependencies:
  - name: jupyterhub
    version: "0.10.6"
    repository: "https://jupyterhub.github.io/helm-chart"
    alias: dep-chart-alias
```

__templates/configmap.yaml__
```yaml
kind: ConfigMap
apiVersion: v1
data:
  FINDME: |
    {{- .Chart | toYaml | nindent 4 }}
```

Output of `helm version`: 3.4.2
Output of `kubectl version`: 1.18.5
