### ISSUE TITLE
Some deployment attributes are always patched even if their values don't change

### ISSUE THREAD

**Issue by sraillard** [helm/helm#9221]
Output of `helm version`:
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+k3s2", GitCommit:"746cf4031370f443bf1230272bc79f2f72de2869", GitTreeState:"clean", BuildDate:"2020-12-18T01:41:55Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+k3s2", GitCommit:"746cf4031370f443bf1230272bc79f2f72de2869", GitTreeState:"clean", BuildDate:"2020-12-18T01:41:55Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
k3s v1.19.5+k3s2

**Issue:**

When upgrading the same chart without any change, if some attributes are present in a deployment, the deployment is patched every time `helm upgrade` is called. This seems to happen only to few attributes, not all. You'll find below a deployment that I have used to reproduce the issue in a local chart (the chart only contains this deployment).

Here is the PATCH request sent each time by `helm upgrade`:
```
I0111 15:51:41.316857   23826 request.go:1097] Request Body: {"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"my-container"}],"containers":[{"$setElementOrder/volumeMounts":[{"mountPath":"/data"},{"mountPath":"/sar"}],"name":"my-container","resources":{"limits":{"cpu":0.5},"requests":{"cpu":0.5}},"volumeMounts":[{"mountPath":"/sar","readOnly":false}]}]}}}}
I0111 15:51:41.317292   23826 round_trippers.go:423] curl -k -v -XPATCH  -H "Accept: application/json" -H "Content-Type: application/strategic-merge-patch+json" 'https://127.0.0.1:6443/apis/apps/v1/namespaces/management/deployments/my-deployment'
I0111 15:51:41.340076   23826 round_trippers.go:443] PATCH https://127.0.0.1:6443/apis/apps/v1/namespaces/management/deployments/my-deployment 200 OK in 22 milliseconds
```

If you update the deployment with the following changes, there is no more patching:
* Removing the cpu requests
* Removing the cpu limits
* Change `readOnly: false` to `readOnly: true`

Command line for upgrading:  
`helm upgrade --debug --install --namespace management management ./basic-alpine/`

`deployment.yaml` test file: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "my-deployment"
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      pod: "my-pod"
  template:
    metadata:
      labels:
        pod: "my-pod"
    spec:
      containers:
      - name: "my-container"
        image: "docker.io/alpine:3.12.3"
        imagePullPolicy: "IfNotPresent"
        command: [ "/bin/sh", "-c", "--", "echo Sleeping; trap : TERM INT; sleep infinity & wait"]
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 0.5
            memory: 256Mi
          limits:
            cpu: 0.5
            memory: 256Mi
        volumeMounts:
        - name: my-data
          mountPath: /data
        - name: my-sar
          mountPath: /sar
          readOnly: false
      volumes:
      - name: my-data
        hostPath:
          path: /data/test-seb/
          type: DirectoryOrCreate
      - name: my-sar
        hostPath:
          path: /var/log/sa/
          type: Directory
```
