### ISSUE TITLE
Structure storage to support read-only RBAC setup

### ISSUE THREAD

**Issue by glenjamin** [helm/helm#9228]
This is a spin off from https://github.com/helm/helm-www/issues/1003

We're trying to organise our k8s RBAC roles so that engineers have two roles, a read-only role and a read-write role they can elevate to when they want to make an intentional change.

In helm 3, the default storage backend uses secrets for all information, which means the default k8s cluster view role is unable to perform actions like `helm list`, `helm status` or `helm history`.

If we give the read-only user access to secrets, then this exposes quite a lot of sensitive information, which we'd hope to keep behind the second role.

There doesn't appear to be a way to allow k8s RBAC to only expose a subset of secret in a namespace, but as noted in the linked ticket, the helm secrets could still contain sensitive information.

Would it be possible to allow the storage backend to safely expose the information needed to use some "safe" helm commands without including all of the other data?

**Comment by sbose78** [comment]
Do you mean, could we potentially:

* Split storage into sensitive & non-sensitive categories
* Store non-sensitive information (metadata?) in configmaps that would list, status and history commands.

That way users who didn't have the permission to read secrets in a namespace would still be able to perform  `helm list`, `helm status` or `helm history`.

**Comment by bacongobbler** [comment]
Limiting what's sensitive and insensitive is a fool's errand, IMO. Any information about a chart's metadata is considered sensitive information.

RBAC roles can restrict access to a subset of a certain resource based on label selectors, resource names, or other selection criteria, so your point about "exposing quite a lot of sensitive information" is moot.

https://kubernetes.io/docs/reference/access-authn-authz/rbac/

> You can also refer to resources by name for certain requests through the resourceNames list. When specified, requests can be restricted to individual instances of a resource. Here is an example that restricts its subject to only get or update a ConfigMap named my-configmap:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: configmap-updater
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing ConfigMap
  # objects is "configmaps"
  resources: ["configmaps"]
  resourceNames: ["my-configmap"]
  verbs: ["update", "get"]
```

If you are concerned about exposing secrets other than Helm release metadata, that is one way you can restrict a user's view.

The alternative is to use an [alternative storage backend](https://helm.sh/docs/topics/advanced/#storage-backends), or store your sensitive information in another namespace so that a RoleBinding will not provide read access to these secrets.

Ultimately this is a design decision on RBAC and how Kubernetes applies it. I'd urge you to make any feature requests regarding how to limit the visibility of certain resources through the Kubernetes project.
