### ISSUE TITLE
Adopting resources created by helm hook doesn't work

### ISSUE THREAD

**Issue by lead4good** [helm/helm#9229]
We are deploying a pvc via a pre-install hook which is then used from within the main deployment and are currently having the problem that this pvc is not deleted after release deletion. To fix this issue, we are trying to deploy the same pvc without the hook annotations, while adding the adoption label and annotations to both pvcs as described in #7649. The installation still fails, with helm not adopting the pvc created during the hook.

```
$ helm install testenc .
Error: persistentvolumeclaims "testenc-madana-enclave" already exists
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "madana-enclave.fullname" . }}
  labels:
{{ include "madana-enclave.labels" . | indent 4 }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
spec:
  accessModes:
    {{- toYaml .Values.enclave.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.enclave.pvc.storage }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "madana-enclave.fullname" . }}
  labels:
{{ include "madana-enclave.labels" . | indent 4 }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    {{- toYaml .Values.enclave.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.enclave.pvc.storage }}
```

Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```
