### ISSUE TITLE
Helm 3.5 - Fail to use OCI Hosted Chart Dependency

### ISSUE THREAD

**Issue by ssc327** [helm/helm#9278]
Output of `helm version`:

```version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}```

Output of `kubectl version`:

```Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): **AKS**

I am trying to use the new OCI support but I cannot get it to work. I am using ```HELM_EXPERIMENTAL_OCI=1```

My app chart has the following.
```
apiVersion: v2
name: my-chart

type: application

version: 0.2.0

# The following is replaced by the application Docker image TAG during the deployment.
appVersion: none

dependencies:
- name: common
  version: "^0.0.5"
  repository: "https://charts.helm.sh/incubator/"
- name: mylib-chart
  version: "0.1.0"
  repository: oci://acrmythingdev001.azurecr.io/helm/incubator/mylib-chart:0.1.0
```

When I then run a ```helm dependency update``` I get the following error:

```
> helm dependency update
Getting updates for unmanaged Helm repositories...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x12bdfee]

goroutine 24 [running]:
helm.sh/helm/v3/internal/experimental/registry.(*Client).PullChart(0x0, 0xc0002c8720, 0xc0002c8720, 0x0, 0x0)
        /home/circleci/helm.sh/helm/internal/experimental/registry/client.go:156 +0x18e
helm.sh/helm/v3/pkg/getter.(*OCIGetter).get(0xc0008e5400, 0xc000087020, 0x57, 0x20, 0x163fa20, 0x173f601)
        /home/circleci/helm.sh/helm/pkg/getter/ocigetter.go:52 +0xd0
helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get(0xc0008e5400, 0xc000087020, 0x57, 0xc0002c8680, 0x4, 0x4, 0xc000346780, 0x0, 0x0)
        /home/circleci/helm.sh/helm/pkg/getter/ocigetter.go:36 +0x7e
helm.sh/helm/v3/pkg/repo.(*ChartRepository).DownloadIndexFile(0xc0002e1ae0, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/helm.sh/helm/pkg/repo/chartrepo.go:125 +0x333
helm.sh/helm/v3/pkg/downloader.(*Manager).parallelRepoUpdate.func1(0xc0007fb3b0, 0xc000038aa0, 0xc0002e1ae0)
        /home/circleci/helm.sh/helm/pkg/downloader/manager.go:655 +0x47
created by helm.sh/helm/v3/pkg/downloader.(*Manager).parallelRepoUpdate
        /home/circleci/helm.sh/helm/pkg/downloader/manager.go:654 +0x9b
```

On a side note, if my chart dependecy does not include a tag
```
dependencies:
- name: common
  version: "^0.0.5"
  repository: "https://charts.helm.sh/incubator/"
- name: cpglib-chart
  version: "0.1.0"
  repository: oci://acrmythingdev001.azurecr.io/helm/incubator/mylib-chart
```
I get a different error however I think that is expected
```
> helm dependency update
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://acrmythingdev001.azurecr.io/helm/incubator/mylib-chart" chart repository:
        tag explicitly required
...Successfully got an update from the "https://charts.helm.sh/incubator/" chart repository
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "acrmythingdev001" chart repository (https://acrmythingdev001.azurecr.io/helm/v1/repo):
        failed to fetch https://acrmythingdev001.azurecr.io/helm/v1/repo/index.yaml : 401 Unauthorized
Update Complete. ⎈Happy Helming!⎈
```
