### ISSUE TITLE
Dependency pods get recreated every time even if nothing changes

### ISSUE THREAD

**Issue by beatrichartz** [helm/helm#9290]
Output of `helm version`: `version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube but also Tanzu Kubernetes Grid

I don't know whether what I'm experiencing is expected behaviour: We depend on the [Bitnami Redis Chart](https://github.com/bitnami/charts/tree/master/bitnami/redis). When deploying a new version of the main chart, we see a delete and recreate of all pods in the stateful set in that chart, e.g:

```
Normal  SuccessfulDelete  3m7s (x21 over 22h)  statefulset-controller  delete Pod main-chart-redis-master-0 in StatefulSet main-chart-redis-master successful
  Normal  SuccessfulCreate  3m5s (x21 over 22h)  statefulset-controller  create Pod main-chart-redis-master-0 in StatefulSet main-chart-redis-master successful
```

The expected behaviour would be for helm to only trigger an update of the dependent chart if there are changes to the chart values. The command that we use is:

```
helm upgrade main-chart . --values ./values.yaml --set-string image.tag=new-image-tag --wait
```

Dependency definition in `Chart.yaml`:
```yaml
dependencies:
  - name: redis
    version: "12.6.2"
    repository: "https://charts.bitnami.com/bitnami"
```

Chart.lock:
```
dependencies:
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 12.6.2
digest: sha256:f0aa9c2bd559ac7917e9e5ddf2a1f6f69958f3a9341a9470242a333652cd41b0
generated: "2021-01-21T05:46:37.345272648Z"
```

Redis values in `values.yaml`:
```yaml
redis:
  cluster: 
    enabled: false
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
```
