### ISSUE TITLE
Possibility to create a new template in case of helm upgrade?

### ISSUE THREAD

**Issue by batistein** [helm/helm#9310]
I have the use case that during an helm upgrade  a template with new values should be created. The previous template with its own values should exists in parallel. The name of the new template should then be edited in a deployment, which works with helm upgrade without problems. What unfortunately does not work is that the one template is created instead of being overwritten. 

Here is the Template which should be created newly on helm upgrade each time the name (.Values.controlPlanes.machineTemplate.version) has changed. 
```
apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
kind: HcloudMachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-control-plane-mt-{{ .Values.controlPlanes.machineTemplate.version }}
  namespace: {{ .Values.cluster.namespace }} 
spec:
  template:
    spec:
      type: {{ .Values.controlPlanes.server.type}}
      image: {{ .Values.controlPlanes.server.image}}

```

This is the MachineDeployment file where the reference under spec.template.spec.infrastructureRef.name should be equal to the new name of the MachineTemplate. This change is of course working due to a helm upgrade. But for working correctly all the old templates must be kept.

```{{- define "cluster.HcloudMachineDeployments" }}
{{- range $deployment := .Values.hcloudWorkers -}}
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: {{ $.Values.cluster.name }}-hc-workers-{{ $deployment.name }}
  namespace: {{ $.Values.cluster.namespace }}
  labels:
    nodepool: {{ $deployment.server.nodepool }}
spec:
  replicas: {{ $deployment.server.replicas }}
  revisionHistoryLimit: {{ $deployment.revisionHistoryLimit }}
  progressDeadlineSeconds: {{ $deployment.progressDeadlineSeconds }}
  clusterName: {{ $.Values.cluster.name }}
  selector:
    matchLabels:
      nodepool: {{ $deployment.server.nodepool }}
  template:
    metadata:
      labels:
        nodepool: {{ $deployment.server.nodepool }}
    spec:
      clusterName: {{ $.Values.cluster.name }}
      version: {{ $.Values.cluster.kubernetesVersion }}
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: {{ $.Values.cluster.name }}-hc-workers-{{ $deployment.name }}-ka-{{ $deployment.kubeadmTemplate.version }}
      infrastructureRef:
        apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
        kind: HcloudMachineTemplate
        name: {{ $.Values.cluster.name }}-hc-workers-{{ $deployment.name }}-mt-{{ $deployment.machineTemplate.version }}
      failureDomain: {{ $deployment.server.location }}
      nodeDrainTimeout: {{ $deployment.server.nodeDrainTimeout | quote }}
---
{{- end }}
{{- end }}

```
