### ISSUE TITLE
[Feature Request] Option to templatize the custom configuration

### ISSUE THREAD

**Issue by arsulegai** [helm/helm#9316]
Output of `helm version`: v3.3.4

Output of `kubectl version`: 1.17

Cloud Provider/Platform (AKS, GKE, Minikube etc.): -Not Applicable-

**[Description]**
Let's say I want to use the configuration in my helm chart, there is currently an option to load it from the file.

```yaml
kind: ConfigMap
metadata:
  name: my-configuration-in-configmap
data:
  {{ (.Files.Glob "config/custom-configuration-to-be-templatized.conf").AsConfig | indent 2 }}
```

The challenge however is `config/custom-configuration-to-be-templatized.conf` has to load parameters from the `Values.yaml`. The only available option currently is to pre-fill the `config/custom-configuration-to-be-templatized.conf` and then use the helm-cli/flux to apply this.

The pre-fill part, can be automated through an external mechanism. However, it would help if helm can add a feature that will allow us to templatize similar configuration through a known mechanism.

_A random thought, but let experts comment on it:_ How about making a `config` directory within `templates` allow the users to add templatized config files.

Ref: The StackOverflow answer from https://stackoverflow.com/a/51847086/1486285 led me to create this issue. We have a need for this feature.
