### ISSUE TITLE
Helm lint without --with-subcharts failing due to subchart

### ISSUE THREAD

**Issue by nycza** [helm/helm#9324]
When running `helm lint <folder>`or `helm lint <packaged tgz>`, the following error is given:
`[ERROR] templates/: template: chart-a/charts/chart-b/charts/chart-c/templates/secret.yaml:3:40: executing chart-a/charts/chart-b/charts/chart-c/templates/secret.yaml" at <b64enc>: invalid value; expected string`

In my understanding, no matter the content of chart-c, I shouldn't get errors in helm lint when not specifying `--with-subcharts`.  
Additionally, chart-c currently isn't even retrieved anyway, and `helm template` generates a content that is correct. Not sure what is the expected output when linting subcharts with conditions.
  
Project structure:
* chart-a includes chart-b (as well as others)
* chart-b includes chart-c (as well as others) with a condition that is false per default (and not overridden in chart-a)
```yaml
dependencies:
- condition: chart-c.enabled
  name: chart-c
  repository: '@apps'
  version: 2.5.0
...
```
* Here is an extract of the failing template:
```yaml
apiVersion: v1
data:
  ca.crt: {{ .Values.caCertificate | b64enc | quote }}
...
```

Output of `helm version`:
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
