### ISSUE TITLE
Add item to array through --set?

### ISSUE THREAD

**Issue by gionapaolini** [helm/helm#9325]
I have an array defined in my values.yaml file:
```
envVar: 
- name: ENV1
  value: "VALUE1"
- name: ENV2
  value: "VALUE2"
- name: ENV3
  value: "VALUE3"
```
That I then access in the deployment file with 
```
env:          
{{- range .Values.environmentVar }}
  - name: {{ .name }}
    value: {{ .value }}
{{- end }}
```
But now I would like to define some more environment variables at the moment of chart install, something like:

`helm install release-name ./chart --set env.ENV4="VALUE4"`

Is this achievable somehow?
