### ISSUE TITLE
Helm hooks post-install (kubectl apply resource)

### ISSUE THREAD

**Issue by shahriak** [helm/helm#9351]
Hi everyone,

I am trying to deploy a kubernetes resource as part of a Helm hook post-install step. I created configmap which calls the script to be executed and mounts it as a volume on the container.

This is the deployment file:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myappnamespace
  name: myapp
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      serviceAccountName: istio-operator
      containers:
        - name: myapp
          image: image:3.7
          imagePullPolicy: IfNotPresent
        - name: myotherapp-install
          image: alpine:3.7
          command: [ "/bin/sh", "-c", "/opt/scripts/jenkins.sh"]
          volumeMounts:
            - name: config-volume
              mountPath: /opt/scripts
     volumes:
        - name: config-volume
          configMap:
            name: peerauth-config
```

config file
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: peerauth-config
data:
  jenkins.sh: |-
{{ .Files.Get "jenkins.sh" | indent 4}}

```
jenkins.sh (This file simply creates resource I am trying to deploy onto the cluster)

```
#!/bin/bash

kubectl apply -f - <<EOF
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "peerauthentication"
  namespace: "istio-system"
spec:
  mtls:
    mode: STRICT
EOF

exit 1
```

Error I am getting:
, Error: YAML parse error on templates/jenkins.sh: error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context
.
exit 1
Output of `helm version`:
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"41d24ec9c736cf0bdb0de3549d30c676e98eebaf", GitTreeState:"clean", BuildDate:"2021-01-18T09:12:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS, Linux

**Comment by bacongobbler** [comment]
Have you tried replacing `indent 4` with `nindent 4`?

**Comment by shahriak** [comment]
Yes I get the same error

, Error: YAML parse error on istio-operator/templates/jenkins.sh: error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context

**Comment by shahriak** [comment]
Does anyone have clue on this issue?

@bacongobbler 
Here is another configuration I am trying but this time the pod going into Terminating state.. 

ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: peerauth-config
data:
  peerauthconfig.yaml: |
    kubectl apply -f - <<EOF
    apiVersion: "security.istio.io/v1beta1"
    kind: "PeerAuthentication"
    metadata:
      name: "peerauthentication"
      namespace: "istio-system"
    spec:
      mtls:
        mode: STRICT
    EOF
```

Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myappnamespace
  name: myapp
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      serviceAccountName: istio-operator
      containers:
        - name: myapp
          image: image:3.7
          imagePullPolicy: IfNotPresent
        - name: myotherapp-install
          image: alpine:3.7
          command: [ "/bin/sh", "-c", "/config/peerauthconfig.yaml"]
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /config
     volumes:
        - name: config-volume
          configMap:
            name: peerauth-config
