### ISSUE TITLE
Single array value from command line overrides all other properties defined in values.yml

### ISSUE THREAD

**Issue by larsduelfer** [helm/helm#9358]
Hi there, we try to pass in a value using the --set parameter on the command line that is a nested value in an array. When doing to, all other child properties defined in our values.yml file are ignored.

We have a chart that has a dependency to another chart in requirements.yml. Our chart has a values.yml containing the following properties:

```
kafka-lag-exporter:
  clusters:
  - name: "default"
    # bootstrapBrokers: <from command line>
    consumerProperties:
      client.id: kafka-lag-exporter
      reconnect.backoff.max.ms: 15000
      reconnect.backoff.ms: 2000
      request.timeout.ms: 20000
      retry.backoff.ms: 5000
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
      session.timeout.ms: 30000
      ssl.endpoint.identification.algorithm: https
```

When deploying the chart, we hand over the values for the commented property above using the --set parameter like this:

```
helm upgrade --install --set kafka-lag-exporter.clusters[0].bootstrapBrokers=***
```

As soon as the additional property is handed over using the --set parameter, all values defined for index 0 of the "clusters" array from the values.yml file are ignored.

We expected the values to be merged. Are we doing anything wrong here or is this not supported?

Help and answers are much appreciated! Thanks a lot in advance!

**Comment by mattfarina** [comment]
What version of Helm are you using?

**Comment by larsduelfer** [comment]
We are using 3.5.2

**Comment by mattfarina** [comment]
Before I responded in detail I wanted to double check the expected behavior. I verified in both Helm v2 and v3 along with looking at the docs.

The current Helm behavior is the expected behavior and has been this way for quite a few years. Any change to this behavior will end up being treated as a behavior change and could happen in one of the two following ways:

1. As a default behavior change that could be proposed for Helm v4. Breaking changes only occur in Helm at major releases
2. Using an opt-in flag

All of the functionality for this is in `pkg/strvals/`. Basically, at each level of the data structures Helm replaces the old one with the new one. In the case of `kafka-lag-exporter.clusters[0].bootstrapBrokers=***`, `bootstrapBrokers` is set to `***`, then `clusters[0]` is set to the new object with `bootstrapBrokers=***`, and up the data structure it walks doing the same thing. There is no merging.

It sounds like you would like the merging behavior.

**Comment by larsduelfer** [comment]
Yes, that is right. Whether it is as a default behaviour or via opt-in flag does not matter that much from my perspective.

The reason why I find the current behaviour a bit strange is as follows:

Imagine in my example above, there would only be a single cluster

```
kafka-lag-exporter:
  cluster:
    name: "default"
    # bootstrapBrokers: localhost://abcd
    consumerProperties:
      client.id: kafka-lag-exporter
      reconnect.backoff.max.ms: 15000
      reconnect.backoff.ms: 2000
      request.timeout.ms: 20000
      retry.backoff.ms: 5000
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
      session.timeout.ms: 30000
      ssl.endpoint.identification.algorithm: https
```

When doing the same now using the helm command line as in my original post above like this:
```
helm upgrade --install --set kafka-lag-exporter.cluster.bootstrapBrokers=***
```` 
it merges the values. It only behaves different in the original post because "clusters" is a list element. That is quite confusing and since it is a common use case to set helm values on the command line to override default values that are delivered with the chart, you should not be forced to pass in all values of the list element again.

**Comment by larsduelfer** [comment]
Is there any progress on this? Will this be considered for a future helm release?

**Comment by NMFR** [comment]
Even if it is a default behaviour i find it very strange. I am with the OP. It should only override the path mentioned in the `--set`.

**Comment by larsduelfer** [comment]
Is there any update on this topic? Any chance that this will be considered?

**Comment by larsduelfer** [comment]
Hi there again, just wanted to catch up and see, if there is any progress on this issue?

**Comment by onurtashan** [comment]
Hi there! Is there any progress on this issue?

**Comment by anuar45** [comment]
Hey, looks like I have very same problem. Any updates?

**Comment by japoch** [comment]
Hey, same issue happens to me. It looks like #5711

**Comment by joejulian** [comment]
> However, this values.yaml works as expected:
> 
> ```yaml
> webserver:
>   service:
>     type: NodePort
>     ports:
>       - name: airflow-ui
>         port: 8080
>         nodePort: 30001
> ```
> 
> But it would be nicer to avoid the repetition in some cases.

iirc, you don't have to repeat the whole stanza, just the value you want to change and the `name`:
```
webserver:
  service:
    type: NodePort
    ports:
      - name: airflow-ui
        nodePort: 30001
```
