### ISSUE TITLE
Helm randomly adds ident tokens

### ISSUE THREAD

**Issue by Sonlis** [helm/helm#9364]
Output of `helm version`: version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.16", GitCommit:"d88fadbd65c5e8bde22630d251766a634c7613b0", GitTreeState:"clean", BuildDate:"2020-12-18T15:59:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

I am trying to deploy ConstraintTemplates from Gatekeeper, but some indent tokens are being added which makes the rego code fail.

Template.yaml:
```yaml 
{{- if .Values.Template }}
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: {{ .Values.Template.name }}
  annotations:
    description: {{ .Values.Template.description }}
spec:
  crd:
    spec:
      names:
        kind: {{ .Values.Template.kind }}
      validation:
        openAPIV3Schema:
          properties:
          {{- range $key, $properties := .Values.Template.properties }}
            {{ $key }}:
              type: {{ $properties.type }}
              items:
                type: {{ $properties.input }}
          {{- end }}
  targets:
    - target: {{ .Values.Template.target }}
      rego: {{ .Values.Template.rego }}
{{- end }}
```

values.yaml:
```yaml
Template:
  name: k8sallowedrepos
  description: Allow deployments to pull only from certain repositories
  kind: K8sallowedrepos 
  properties:
    repos:
      type: array
      input: string
  target: admission.k8s.gatekeeper.sh
  rego: |+
        '
        package k8sallowedrepos
        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          satisfied := [good | repo = input.parameters.repos[_] ; good = startswith(container.image, repo)]
          not any(satisfied)
          msg := sprintf("container <%v> has an invalid image repo <%v>, allowed repos are %v", [container.name, container.image, input.parameters.repos])
        }
        violation[{"msg": msg}] {
          container := input.review.object.spec.initContainers[_]
          satisfied := [good | repo = input.parameters.repos[_] ; good = startswith(container.image, repo)]
          not any(satisfied)
          msg := sprintf("container <%v> has an invalid image repo <%v>, allowed repos are %v", [container.name, container.image, input.parameters.repos])
        }' 
```

helm install:
```bash 
Error: admission webhook "validation.gatekeeper.sh" denied the request: 1 error occurred: templates["admission.k8s.gatekeeper.sh"]["K8sallowedrepos"]:1: rego_parse_error: unexpected ident token: expected \n or ; or }
```
helm install --dry-run --debug:
```bash
COMPUTED VALUES:
Template:
  description: Allow deployments to pull only from certain repositories
  kind: K8sallowedrepos
  name: k8sallowedrepos
  properties:
    repos:
      input: string
      type: array
  rego: "'\npackage k8sallowedrepos\nviolation[{\"msg\": msg}] {\n  container := input.review.object.spec.containers[_]\n
    \ satisfied := [good | repo = input.parameters.repos[_] ; good = startswith(container.image,
    repo)]\n  not any(satisfied)\n  msg := sprintf(\"container <%v> has an invalid
    image repo <%v>, allowed repos are %v\", [container.name, container.image, input.parameters.repos])\n}\nviolation[{\"msg\":
    msg}] {\n  container := input.review.object.spec.initContainers[_]\n  satisfied
    := [good | repo = input.parameters.repos[_] ; good = startswith(container.image,
    repo)]\n  not any(satisfied)\n  msg := sprintf(\"container <%v> has an invalid
    image repo <%v>, allowed repos are %v\", [container.name, container.image, input.parameters.repos])\n}'
    \       \n"
  target: admission.k8s.gatekeeper.sh
```

There is a backslash token being added in front of "satisfied", whereas every other line have a correct /n + 2 spaces. I tried writing the file with multiple text editors, but it seems Helm keep adding this token for some reasons.
