### ISSUE TITLE
values rendering not correct when setting an array value over --set

### ISSUE THREAD

**Issue by FlyingDogFood** [helm/helm#9369]
When you are using `--set` to set an value inside an array all other values disappear and only the setted value remains.
But when setting the array over `--values` the values render out as expected. Using Helm Version 3.5.2.
To Reproduce:
My Chart:
```
test
|--templates
|   |--test.yaml
|--Chart.yaml
|--test-values.yaml
|--values.yaml
```
test.yaml
```yaml
{{ .Values | toYaml }}
```
values.yaml
```yaml
array:
  - name: pos1
    subarray:
      - name: subpos1
        value: somevalue
  - name: pos2
    subarray:
      - name: subpos1
        value: somevalue
```
test-values.yaml
```yaml
array:
  - name: pos1
    subarray:
      - name: subpos1
        value: somevalue
  - name: pos2
    subarray:
      - name: subpos1
        value: somevalue
```
Unexpected behavior:
```
>helm template --debug test . --set array[0].subarray[0].value=someothervalue
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: F:\test

---
# Source: test/templates/test.yaml
array:
- subarray:
  - value: someothervalue
```

When using `--values` to set the base array helm behaves like I would have expected without setting the additional value file.
```
>helm template --debug test . --set array[0].subarray[0].value=someothervalue --values test-values.yaml
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: F:\test

---
# Source: test/templates/test.yaml
array:
- name: pos1
  subarray:
  - name: subpos1
    value: someothervalue
- name: pos2
  subarray:
  - name: subpos1
    value: somevalue
```

**Comment by mattfarina** [comment]
What version of Helm are you using?

**Comment by FlyingDogFood** [comment]
@mattfarina Im using Helm Version 3.5.2.
```
>helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

**Comment by mattfarina** [comment]
Before I responded in detail I wanted to double check the expected behavior. I verified in both Helm v2 and v3 along with looking at the docs.

The current Helm behavior is the expected behavior and has been this way for quite a few years. Any change to this behavior will end up being treated as a behavior change and could happen in one of the two following ways:

1. As a default behavior change that could be proposed for Helm v4. Breaking changes only occur in Helm at major releases
2. Using an opt-in flag

All of the functionality for this is in `pkg/strvals/`. Basically, at each level of the data structures Helm replaces the old one with the new one. In the case of `array[0].subarray[0].value=someothervalue`, `value` is set to `someothervalue`, then `subarray[0]` is set to the new object with `value=someothervalue`, and up the data structure it walks doing the same thing. There is no merging.

It sounds like you would like the merging behavior.

**Comment by FlyingDogFood** [comment]
From the docs: https://helm.sh/docs/chart_template_guide/values_files/
>The list above is in order of specificity: values.yaml is the default, which can be overridden by a parent chart's values.yaml, which can in turn be overridden by a user-supplied values file, which can in turn be overridden by --set parameters.

For my understanding that would mean the `--set` parameter should not behave differently if you set an extra values file or not because the values file is merged before the `--set` applys.
In my first example the `--set` overrides the array and in my second example it merges with the array. In my Opinion it doesn't make sense that `--set` isn't consistent.

What i was expecting is:
`--set array=[{subarray: [{value: someothervalue}]}]` overrides the array
`--set array[0].subarray[0].value=someothervalue` merges with the array(like it does when using an extra values file), because i'm excessing a specific Object in the array.

**Comment by akunszt** [comment]
We already faced this issue. The chart which demonstrates this issue is simple.
```
chart
|--templates
|   |--test.yaml
|--Chart.yaml
|--values.yaml
```
The `test.yaml`:
```yaml
{{- range .Values.array }}
---
{{- with .parameters }}
array:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}

---                                                                                                                                                                                         
noArray:
{{ toYaml .Values.noArray | indent 2 }}
```

The `values.yaml`:
```yaml
---
array:
  - parameters:
      arrayOption1: arrayValue1
      arrayOption2: arrayValue2

noArray:
  option1: value1
  option2: value2
```

Running `helm template chart` gives back the expected result.
```yaml
---
# Source: test/templates/test.yaml
array:
  arrayOption1: arrayValue1
  arrayOption2: arrayValue2
---
# Source: test/templates/test.yaml
noArray:
  option1: value1
  option2: value2
```

Setting an option in both the array and noArray cases gives back different results which are unexpected.
```
helm template --set 'array[0].parameters.arrayOption3=arrayValue3' --set 'noArray.option3=value3' chart
```
```yaml
---
# Source: test/templates/test.yaml
array:
  arrayOption3: arrayValue3
---
# Source: test/templates/test.yaml
noArray:
  option1: value1
  option2: value2
  option3: value3
```
Of course editing the `values.yaml` and inserting `arrayOption3: arrayValue3` there instead of using `--set` will give you the correct results. It's very unintuitive that setting the same thing on different places will yield different results IF the path contains an array, but will be the same if it doesn't.

I think this is a bug in the current version of the Helm. It shouldn't matter if a user uses the `values.yaml` or the command line to achieve the same configuration. The end result should be the same.
