### ISSUE TITLE
Dependencies deployed despite false condition

### ISSUE THREAD

**Issue by MrDrMcCoy** [helm/helm#9374]
#### Output of `helm version`

```
version.BuildInfo{Version:"3.4.2", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.15"}
```

#### Output of `kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-20T00:00:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

#### Cloud Provider/Platform (AKS, GKE, Minikube etc.)

AKS

## Issue description

When specifying dependencies and conditions for a chart, all of the dependencies are deployed, regardless of any conditions specified in `Chart.yaml`, `values.yaml`, or `user_values.yaml`. Here is an example:

```yaml
#Chart.yaml
apiVersion: v3
name: my_chart
description: my_chart
type: application
version: 0.0.1
appVersion: 1.0.0
dependencies:
  - name: my_dependency
    repository: file://../my_dependency
    version: 2.1.0
    tags:
      - my_dependency
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 12.7.4
    tags:
      - redis
```

```yaml
# user_values.yaml
tags:
  my_dependency: true
  redis: false
```

```shell
$ helm upgrade --install --namespace=test  test repo/my_chart -f user_values.yaml
Release "test" does not exist. Installing it now.
NAME: test
LAST DEPLOYED: Wed Feb 17 17:17:18 2021
NAMESPACE: test
STATUS: deployed
REVISION: 1

$ kubectl get pods --namespace test | grep redis
test-redis-master-0                        1/1     Running   0          4m59s
test-redis-slave-0                         1/1     Running   0          4m59s
test-redis-slave-1                         1/1     Running   0          4m45s
```

The same behavior is experienced when I use `condition:` as well. Am I doing it wrong, or is this a known issue? I've seen similar issues reported here in the past, but were all closed for one reason or another.

**Comment by mattfarina** [comment]
I tried to reproduce this issue and was unable to. I used `helm create` to create a new chart. Then I added the following section to the `Chart.yaml` file:

```yaml
dependencies:
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 9.3.2
    tags:
      - my_dependency
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 12.7.4
    tags:
      - redis
 ```

Since I didn't have your dependency I used a second bitnami chart.

At the top of the `values.yaml` file I added:

```yaml
tags:
  my_dependency: true
  redis: false
```

In my case redis was not installed.

In your setup do you have default values for your tags in your `values.yaml` file?
