### ISSUE TITLE
Generate a list in template

### ISSUE THREAD

**Issue by nick-lehmann** [helm/helm#9379]
Being unsuccessful in finding an answer in the docs, I would like to know if it is possible to modify each element in a list taken from the `values.yaml`, modify it and then iterate over it using the `range` operator.

My specifiy usecase would be a list of customers specifiy in `values.yaml`

```yaml
customers:
  - customer1
  - customer2
 ```

Based on these customers, I have to generate urls for the ingress.

```
customer1 -> api.customer1.root-domain.com
customer2 -> api.customer2.root-domain.com
```

This is quite easy using the `range` operator.

```yaml
{{ $rootDomain := .Values.something }}
{{- range .Values.customers }}
    - host: "api.{{- . -}}.{{- $rootDomain -}}"
      http:
        paths:
          - backend:
              serviceName: some-service
              servicePort: http
            path: /
{{end}}
```

However, I need this information in two other templates and would like to avoid duplicating this loop. Is it possible to generate the urls in a helper and use the returned list in conjunction with the `range` operator ?

Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-20T11:18:11Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.3-r1-CCE2.0.17.B003", GitCommit:"df1a90c11bd86b0bdd0685ed8a973500dd9b37ba", GitTreeState:"clean", BuildDate:"2018-12-05T08:01:57Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Telekom

**Comment by mattfarina** [comment]
What you're asking about is possible. I would [create a new list](https://helm.sh/docs/chart_template_guide/function_list/#lists-and-list-functions) via a template function in helpers and add my generated url to the list. Then return that. It's even possible to use variables to cache the result so you only generate it once.

**Comment by nick-lehmann** [comment]
@mattfarina Thank you very much for the response. However, I do not see how it is possible. The example you have linked does not state how you manipulate every item in a list, in this case appending the base domain. Would you be so kind to give me hint or even a code snippet?

**Comment by bacongobbler** [comment]
There is no way to store state across template renders. Helm takes the input provided from your values and renders each tempalte in isolation.

The best way to achieve this would be to write out a helper function which you can reference in every template, using @mattfarina's suggestion of creating a new list in said helper.

https://helm.sh/docs/chart_template_guide/named_templates/#declaring-and-using-templates-with-define-and-template

**Comment by nick-lehmann** [comment]
Found some time to work on this again and finally figured out what you meant. For anybody else finding this, a solution to this could be:

```yaml
# _helpers.tpl
{{- define "test.customerUrls" -}}
{{- $customerUrls := list -}}
{{- range .Values.customers -}}
    {{- $customerUrls = printf "via.%s.via-cloud.de" . | append $customerUrls -}}
{{- end -}}
{{ join "," $customerUrls }}
{{- end -}

# somewhere.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "test.fullname" }}
spec:
  rules:
    {{- range include "test.customerUrls" $ | split "," }}
    - host: {{ . }}
    {{- end }}
```

However, it seems like you cannot return lists from template helpers directly. According to [this Stackoverflow anwser](https://stackoverflow.com/a/61155898/2633995), template can only return string so one has marshal the list into a string and parse it again. @mattfarina @bacongobbler is this correct or did I miss something?

Nevertheless, it works and the issue can therefore be closed
