### ISSUE TITLE
Can't add icons with helm chart

### ISSUE THREAD

**Issue by cccs-cat001** [helm/helm#9383]
Output of `helm version`: version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"c7c4f6ce84bf8535a782b67465807651a4bd649b", GitTreeState:"clean", BuildDate:"2021-01-18T09:49:05Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

I've got a basic values.yaml file: 
```yaml
apps:
  - name: app1
    icon: app1.png
  - name: app2
    icon: app2.png
```
And a config-map template: 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: icons-config
  labels:
    tier: app
    component: config
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end -}}
{{- $Global := . }}
data:
  {{- range $app := .Values.apps }}
  {{- if $app.icon }}
  {{ $app.icon }}: |-
  {{ $.Files.Get "icons/$app.name/$app.icon" }}
  {{- end }}
  {{- end }}
```
and an icons directory set up as 
```
icons
├── app1
│   └── app1.png
└── app2
    └── app2.svg
```
When I try to run the `helm install` I get: 
```yaml
---
# Source: discovery/templates/icons-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: icons-config
  labels:
    tier: app
    component: config
    release: app
    chart: "app-0.1.0"
    heritage: Helm
data:
  app1.png: |-
  
  app2.png: |-
```
.. The icons don't get populated into the outputs. When I do 
```bash
kubectl create configmap icons-config --from-file icons/app1/app1.png --from-file icons/app2/app2.png
```
It creates it suceessfully. 
I have no idea why helm won't populate the template with the icons. Can anyone guide me?
