### ISSUE TITLE
Helm dep up fails with OCI repo in dependencies while helm pull works

### ISSUE THREAD

**Issue by vzabawski** [helm/helm#9386]
I use Docker registry for storing Helm chart and reference it in Chart.yaml:
```
dependencies:
  - name: ingress-nginx
    version: "3.23.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: master.ingress.create_controller
    tags:
      - ingressController
  - name: jenkins
    version: "1.16.0"
    repository: "oci://project-containers.example.com/helmcharts/jenkins-helm"
  - name: velero
    version: "2.14.8"
    repository: "https://vmware-tanzu.github.io/helm-charts"
    condition: velero.enabled
    tags:
      - backup
```

When I run `helm dep up`, I get the following output:
```
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://project-containers.example.com/helmcharts/jenkins-helm" chart repository:
        tag explicitly required
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "vmware-tanzu" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Downloading ingress-nginx from repo https://kubernetes.github.io/ingress-nginx
Downloading jenkins from repo oci://project-containers.example.com/helmcharts/jenkins-helm
1.16.0: Pulling from project-containers.example.com/helmcharts/jenkins-helm/jenkins
Save error occurred:  could not download oci://project-containers.example.com/helmcharts/jenkins-helm/jenkins: project-containers.example.com/helmcharts/jenkins-helm/jenkins:1.16.0: not found
Deleting newly downloaded charts, restoring pre-update state
Error: could not download oci://project-containers.example.com/helmcharts/jenkins-helm/jenkins: project-containers.example.com/helmcharts/jenkins-helm/jenkins:1.16.0: not found
```

Pull works:
```
helm chart pull project-containers.example.com/helmcharts/jenkins-helm:1.16.0
1.16.0: Pulling from project-containers.example.com/helmcharts/jenkins-helm
ref:     project-containers.example.com/helmcharts/jenkins-helm:1.16.0
digest:  b667d99d64a3b10b5841fa4655c4c201604bd63691cf855236f80f7a25b885d1
size:    47.4 KiB
name:    jenkins-helm
version: 1.16.0
Status: Downloaded newer chart for project-containers.example.com/helmcharts/jenkins-helm:1.16.0
```
Output of `helm version`:
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

Not sure if it's a bug or just partial implementation of a new feature, so could anyone please clarify?

**Comment by bacongobbler** [comment]
I think this is because the registry you specified is called `jenkins-helm`, but the name of the dependency you provided was `jenkins`.

If you change your Chart.yaml to the following, it should work.

```
dependencies:
  - name: ingress-nginx
    version: "3.23.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: master.ingress.create_controller
    tags:
      - ingressController
  - name: jenkins-helm
    version: "1.16.0"
    repository: "oci://project-containers.example.com/helmcharts"
  - name: velero
    version: "2.14.8"
    repository: "https://vmware-tanzu.github.io/helm-charts"
    condition: velero.enabled
    tags:
      - backup
```
