### ISSUE TITLE
Local dependency charts breaks "helm dep update"

### ISSUE THREAD

**Issue by Ziphone** [helm/helm#9387]
Command _helm dep update_ "broke" when I added a local dependency to my chart. The chart works fine with the new dependency (e.g template, install, upgrade), but "helm dep update \<path of my chart\>" returns exit code 1 and this message:
```
Update Complete. ⎈Happy Helming!⎈
Error: Chart.yaml file is missing
helm.go:81: [debug] Chart.yaml file is missing
```
  
This might be a feature, but then I'd like to know the rationale behind. I suggest that Helm omits local dependencies rather than failing.
  
The dependencies section of my Chart.yaml.
```yaml
dependencies:
  - name: <some external chart>
    version: 1.2.x
    repository: <some external repo>
  - name: <my local chart>
    version: 0.1.8
    repository: file://charts/<my local chart>-0.0.1.tgz
```

Output of `helm version`:
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): No clusters involved.

**Comment by mattfarina** [comment]
The error looks like one you would get if `<path of my chart>` were wrong.

I notice the dependencies section isn't quire right for a local dependency. It should be:

```yaml
dependencies:
  - name: <some external chart>
    version: 1.2.x
    repository: <some external repo>
  - name: <my local chart>
    version: 0.1.8
```

Notice the local chart does not have a repository. Does changing that make a difference?

**Comment by Ziphone** [comment]
Hi, Matt. Thanks for looking at my issue.

First I have to point out a mistake in my first post. My dependency section initially looked like this (version 0.1.8 of \<my local chart\> was a mistake):
``` yaml
dependencies:
  - name: <some external chart>
    version: 1.2.x
    repository: <some external repo>
  - name: <my local chart>
    version: 0.0.1
    repository: file://charts/<my local chart>-0.0.1.tgz
```

I verified the path \<path of my chart\> by executing "helm template \<path of my chart\>", which returns the expected output.

I removed the repository field of dependency \<my local chart\> as advised, but "helm dep update" still fails. Now it fails with this message:
```
Update Complete. ⎈Happy Helming!⎈
Error: directory <path of my chart>/charts/<my local chart> not found
helm.go:81: [debug] <path of my chart>/charts/<my local chart> not found
```
I got _helm dep update_ working by removing the repository field of \<my local chart\> (as advised by Matt) and then unzipping charts/\<my local chart\>-0.0.1.tgz to charts/\<my local chart\> . 

I think the solution is a bit unfortunate in an environment where keeping track of versions is critical. My interpretation of the docs [1] was also that the repository field should be specified for local charts as well, even after unzipping the dependency chart the repository field is a showstopper.

1 - Helm | Helm Dependency - https://helm.sh/docs/helm/helm_dependency/#helm-dependency
