### ISSUE TITLE
helm template . -- could not find expected `:` -- line reporting is odd

### ISSUE THREAD

**Issue by jsoref** [helm/helm#9401]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

Input 1 (`Chart.yaml`):
```
apiVersion: v1
kind: Pod
metadata:
  name: "{{.Release.Name}}-{{.Values.Name}}"
spec:
  containers:
  - name: waiter
    image: "alpine:3.9"
    command: ["/bin/sleep","9000"]
invalid
 


:
```

Run:
```
helm template .
```
Output:
```
Error: cannot load Chart.yaml: error converting YAML to JSON: yaml: line 14: could not find expected ':'
```
Delete the `:` on the last line and then run:
```
helm template .
```
Output:
```
Error: cannot load Chart.yaml: error converting YAML to JSON: yaml: line 15: could not find expected ':'
```

Expected results:
```
Error: cannot load Chart.yaml: error converting YAML to JSON: yaml: line 10: could not find expected ':'
```

Note: this is a variation of https://github.com/helm/helm/blob/master/cmd/helm/testdata/testcharts/chart-with-template-with-invalid-yaml/templates/alpine-pod.yaml

I'm debugging it because I'm trying to improve the error reporting #8657 

This is ~probably~ technically a bug in the underlying Yaml library ~but while I can debug into the library, there doesn't appear to be a command-line interface to it, which makes useful testing painful~. And practically, end users expect reasonably good error reporting from `helm`. ~If someone else could figure out how to report this to the yaml library, I'd appreciate it, or if someone could helm me report it, that'd also be great.~
