### ISSUE TITLE
How to set complex object use --set？

### ISSUE THREAD

**Issue by bigfacewo** [helm/helm#9427]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.7"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
Now I have a field that is a key value pair. I want to pass it in through -- set, but the key contains the dot character. For example:
```
volumeClaimTemplates
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: "nfs-client"
```

I pass parameters through -- set :
```
--set persistence.annotations={"volume.beta.kubernetes.io/storage-clasnfs-lient":"nfs-client"}
```
The final result is:
```
  volumeClaimTemplates:
    - metadata:
        annotations:
          0: volume.beta.kubernetes.io/storage-class=nfs-client
```
Here's how the helm template is written:
```
{{- with .Values.persistence }}
  volumeClaimTemplates:
    - metadata:
        name: state
        {{- with .annotations }}
        annotations:
          {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
          {{- end }}
        {{- end }}
  {{- end }}
```
Or you can look at this project:
https://artifacthub.io/packages/helm/adwerx/github-actions-runner

What should I do？
