### ISSUE TITLE
[Question/Support] : Is helm3 support use values in crds?

### ISSUE THREAD

**Issue by gxglls** [helm/helm#9429]
### Env
Output of `helm version`:
v3.5.0-rc.1
Output of `kubectl version`:
v1.20.1
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
k8s

### question
My helm project depend [cert-manager](https://cert-manager.io/docs/installation/kubernetes/) which need install cert-manager  crd first, cert-manager's crd depend a service in cluster for webhook, the service name depend on the helm .Release.Name, the crd config which in my project's crds dir like this:
```yaml
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: {{ .Release.Name }}-cert-manager-webhook
          namespace: {{ .Release.Namespace  }}
          path: /convert
```
When I use helm install , output:
```bash
Error: failed to install CRD crds/cert-manager.crds.yaml: error parsing : error converting YAML to JSON: yaml: line 30: did not find expected key
```
 looks like {{ .Release.Name }} can not be parse in crds dir， Is helm3 support use values in crds?
