### ISSUE TITLE
Helm 3 --kubeconfig Error: Kubernetes cluster unreachable

### ISSUE THREAD

**Issue by Mel-Github** [helm/helm#9434]
Output of `helm version`:

```bash
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

Output of `kubectl version`:

```bash
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2+k3s1", GitCommit:"1d4adb0301b9a63ceec8cabb11b309e061f43d5f", GitTreeState:"clean", BuildDate:"2021-01-14T23:52:37Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  **k3s**

When using the --kubeconfig, helm is returning connection refuse error . Not sure why helm is attempting to connect to localhost:8080

Portion of the k3s.yaml file.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTVRNMk1qQXhPRE13SGhjTk1qRXdNakU0TURNME9UUXpXaGNOTXpFd01qRTJNRE0wT1RRegpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTVRNMk1qQXhPRE13V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTVEFoK3JRZklBbEFKOXdOdmYwaDBvblBCOUVPZEt0UVVHdVNmeDRScTIKWlZMckFTTUxBVEF3L2x2Rk5yQ3QvZ0t1QTVzRjQxVUl5WHlNUDAzQ2xvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUNjQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVkyaG5kS1VzbVNnR2MwZVBQSGdtClUxaXdnaEV3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUlNeW1EZmdKMmJ6RStYdFdXajFNM2xpNWxsSEsyNEUKK241c2hCbVdNQUtzQWlFQTJGS2hrZmtiSHdPZHFRQ045blhEcy8xbHZUS3BXYXhkQlg1QkZSMDB1Vjg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.20.101:6443
```

```bash
helm --kubeconfig /Users/melmeow/.kube/k3s.yaml ls --debug

Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused
helm.go:81: [debug] Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused
Kubernetes cluster unreachable
helm.sh/helm/v3/pkg/kube.(*Client).IsReachable
	/home/circleci/helm.sh/helm/pkg/kube/client.go:115
helm.sh/helm/v3/pkg/action.(*List).Run
	/home/circleci/helm.sh/helm/pkg/action/list.go:148
main.newListCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/list.go:80
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
```

However without the --kubeconfig arugment, `helm` is behaving normally

```bash
helm ls
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```

I am having multiple k3s clusters inside my `$KUBECONFIG`

```
echo $KUBECONFIG
/Users/melmeow/.kube/config:/Users/melmeow/.kube/config_k3s:/Users/melmeow/.kube/gloo:/Users/melmeow/.kube/woodland-gloo
```
