### ISSUE TITLE
Beginner Question: Including whole yaml template from dependency

### ISSUE THREAD

**Issue by Knaackee** [helm/helm#9449]
I am getting the following error running `helm install . --generate-name --dry-run --debug` inside my charts folder.

```
$ helm install . --generate-name --dry-run --debug
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: 
***\packages\my-package\.ci

Error: YAML parse error on .ci/templates/deployment.yaml: error converting YAML to JSON: yaml: did not find expected node content
helm.go:81: [debug] error converting YAML to JSON: yaml: did not find expected node content
YAML parse error on .ci/templates/deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        /home/circleci/helm.sh/helm/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:240
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
```

I followed this tutorial [HELM Docs - Library Charts](https://helm.sh/docs/topics/library_charts/)

Here is the content of `packages/my-package/.ci/templates/deployment.yaml`

    {{- include "nodejs-backend.deployment" . }}

Here is the content of `.ci/nodejs-backend/templates/_deployment.yaml`

    {{- define "nodejs-backend.deployment" -}}
    apiVersion: apps/v1
    kind: Deployment
    ...
    {{- end }}      

The dependency is defined inside `packages/my-package/.ci/Chart.yaml` 

    dependencies:
      - name: nodejs-backend
        version: 0.0.1
        repository: file://../../../.ci/nodejs-backend  

Here is my folder structure.

    + .ci
      + nodejs-backend
        + charts
        + templates
           _deployment.yaml
           _service.yaml
        Chart.yaml
    + packages
      + my-package
        + .ci
          + charts
          + templates
             deployment.yaml
             service.yaml
          Chart.yaml

Ive read the docs the douzen times and played with the yaml's, without success.

**Comment by initvik** [comment]
Seems like a problem is with the YAML formatting, majorly with an indentation or in the values file. Please try to use the YAML lint, you can give it a try with any of the following YAML linting solutions if there will be any formatting issues you can recognize.

https://github.com/rasshofer/yaml-lint#readme
https://github.com/adrienverge/yamllint

**Comment by initvik** [comment]
I tried something similar from your reference 
This is what your chart structure looks like after adding the dependency to your actual chart, please don't use the template chart i.e "mylibchart" it won't work.

Make sure your library chart is installable 
```
helm install mylibchart mylibchart/
Error: library charts are not installable
```
Note: you have to pull the dependencies before using the actual chart 
```
helm dependency update mychart
```

```
├── mychart
│   ├── Chart.lock
│   ├── Chart.yaml
│   ├── charts
│   │   └── mylibchart-0.1.0.tgz
│   ├── templates
│   │   └── configmap.yaml
│   └── values.yaml
├── mylibchart
│   ├── Chart.yaml
│   ├── charts
│   └── templates
│       ├── _configmap.yaml
│       └── _util.yaml
```
```
helm install mydemo mychart/ --debug --dry-run
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH:  ~/Projects/kubernetes/chartstest/mychart

NAME: mydemo
LAST DEPLOYED: Sat Mar  6 11:24:51 2021
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: ""
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
mylibchart:
  global: {}
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ""
tolerations: []

HOOKS:
MANIFEST:
---
# Source: mychart/templates/configmap.yaml
apiVersion: v1
data:
  myvalue: Hello World
kind: ConfigMap
metadata:
  name: mychart-mydemo
  ```
