### ISSUE TITLE
Working with unpackaged charts as dependency

### ISSUE THREAD

**Issue by BlueCog** [helm/helm#9461]
Hello Helm Community! 

Out team is working with Helm for some time now and we like to use it to do our K8 deployments for internal usage. 

Out team has (**unpackaged**) Helm umbrella charts & dependend Helm charts in a seperate GIT repositories. With GitOps in mind we'd like to work only with unpackaged charts. We also like to minimize any build steps, so we would like to skip the packaging & pushing to internal Helm repo steps. 

So we would like to point a helm dependency in `chart.yaml` to a GIT repository. 

```
# Chart.yaml
dependencies:
- name: nginx
  version: "1.2.3"
  repository: "ssh://git@git.host:7999/helm-dep/helm-dep.git"
- name: memcached
  version: "3.2.1"
  repository: "https://another.example.git.host/helm-dep"
``` 

A different solution would be to pull the dependend charts by hand (or scripted). But with GitOps in mind out team like to have the some kind overview of the deployed dependend charts (versions) in that moment of time. And we like to minimize any custom scripting and files. We also could use the `file:// ` option in `chart.yaml` but it seems working with the  `file:// ` option doesn't work togehter with other Helm repo's. So a ```helm dependency update``` wont work....

I've searched trough blogs/github issues/stackoverflow but it seems this is not supported at the moment. Is this something wat would be on the Helm roadmap? Or is this not the way to go / working as intended.
