### ISSUE TITLE
New Ingress Template (helm new) might be wrong / or at least hard to understand

### ISSUE THREAD

**Issue by adrianliechti** [helm/helm#9462]
in template/ingress.yaml

the name of the service is generated by the _helper using the release name
{{- $fullName := include "chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}

```
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
```

but in values.yaml, the recommended way seems to overwrite the whole path object including backend:
https://github.com/helm/helm/commit/1e126ff4d1f09b806c1952757516f6fc67506ce0

```yaml
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        backend:
          serviceName: chart-example.local
          servicePort: 80
```

I'm not entirely sure, but I think this backend setting would be ignored anyway using the generated ingress template...
with the ingress v1 warning on helm install, this topic might get more important for customers

what is your recommended way now to specify a simple/minimal ingress with v1 in mind?

Thanks for clarifying,
Adrian

**Comment by bacongobbler** [comment]
> what is your recommended way now to specify a simple/minimal ingress with v1 in mind?

I'm sorry, I don't fully understand your question. What do you mean by "with v1 in mind"?

Helm templates are generated based on the values provided by the user. In this particular case, the ingress rules will read what's in values.yaml and generate an ingress route. Add another route to values.yaml and the ingress routes will be updated.

**Comment by adrianliechti** [comment]
with a change in the last release, the template got changed what "helm create" generates for values.yaml:
https://github.com/helm/helm/commit/1e126ff4d1f09b806c1952757516f6fc67506ce0

I do have the feeling the change was not a good idea - since the actual generated ingress (template/ingress.yaml) will not work with this suggesting in the values.yaml.

furthermore, the Kubernetes CLI throws warnings when installing/upgrading such charts generated with "helm create".
infos here: https://kubernetes.io/blog/2020/09/03/warnings/

Your template currently generates ingress in version v1beta1. In the meantime v1 has been released and changes the section quite a lot. So I think it's worth to refactor the whole helm create template for ingress

**Comment by bacongobbler** [comment]
Thank you for pointing this out. PRs welcome to fix this.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/543364fba59b0c7c30e38ebe0f73680db895abb6/pkg/chartutil/create.go#L219-L223

**Comment by adrianliechti** [comment]
see, I think this issue should not be classified as "bug" and not "support".
and I suggest to revert the mentioned change.

```bash
helm create example
```

``` yaml
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        backend:
          serviceName: chart-example.local
          servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```

when I edit this part:

```yaml
        backend:
          serviceName: my-fancy-backend
          servicePort: 9090
```

if I install the chart with enabled ingress

```bash
helm install svc1 . --set ingress.enabled=true  --dry-run
```

the installed ingress element does not contain my intended config

```yaml
# Source: example/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: svc1-example
  labels:
    helm.sh/chart: example-0.1.0
    app.kubernetes.io/name: example
    app.kubernetes.io/instance: svc1
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /
            backend:
              serviceName: svc1-example
              servicePort: 80
```

**Comment by adrianliechti** [comment]
I'm happy to create a pull request for a new idea about the default template of an ingress.

I have the feeling that there are many ideas around for best ideas of a chart config when I look at various helm charts of popular vendors. Since the Helm CLI might be considered kind as the Authority how to create a good Helm Chart, changes to the "helm create" command should be done carefully.

the new kubectl command can now create ingress objects

```bash
kubectl create ingress simple --rule="foo.com/bar*=svc1:8080,tls=my-cert" --dry-run=client -o yaml
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: simple
spec:
  rules:
  - host: foo.com
    http:
      paths:
      - backend:
          service:
            name: svc1
            port:
              number: 8080
        path: /bar
        pathType: Prefix
  tls:
  - hosts:
    - foo.com
    secretName: my-cert
```

I could imagine to go into this direction 

```yaml
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  rules:
    - host: chart-example.local
      path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```

**Comment by sagikazarmark** [comment]
Would be nice to add `ingressClassName` support as well. Dex has an experimental, backwards compatible implementation here: https://github.com/dexidp/helm-charts/blob/256796084cbe900421822b266c9d60dc7f3e2455/charts/dex/templates/ingress.yaml#L14-L26

**Comment by adrianliechti** [comment]
thanks alot for reading through this issue, your interest and linking!

ingressClassName absolutely makes sense. thanks for this hint

variant A

```
ingress:
  enabled: false
  # className: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  rules:
    - host: chart-example.local
      path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```

variante B:

```
ingress:
  enabled: false
  # class:
  #   name: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  rules:
    - host: chart-example.local
      path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```

**Comment by sagikazarmark** [comment]
I vote for variant A

**Comment by adrianliechti** [comment]
this is a first draft:

- I removed support for K8s 1.13 and below (ingress in extensions/v1beta1 group)
- based on capabilities, I try to add / skip feature (ingressClassName, pathType); the handy dex workaround is implemented


it's currently pretty untested on older versions of Kubernetes. But I think it could be a first discussion basis.

cheers, Adrian

ingress.yaml
```
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $kubeVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- if semverCompare ">=1.19-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" $kubeVersion)) }}
    {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
    {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
    {{- end }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" $kubeVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.rules }}
    - host: {{ .host | quote }}
      http:
        paths:
        - path: {{ .path }}
          {{- if and .pathType (semverCompare ">=1.18-0" $kubeVersion) }}
          pathType: {{ .pathType }}
          {{- end }}
          backend:
            {{- if semverCompare ">=1.19-0" $kubeVersion }}
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
            {{- else -}}
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
            {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- end }}
```

NOTES.txt
```
1. Get the application URL by running these commands:
{{- if .Values.ingress.enabled }}
{{- range $rule := .Values.ingress.rules }}
  http{{ if $.Values.ingress.tls }}s{{ end }}://{{ .host }}{{ .path }}
{{- end }}
{{- else if contains "NodePort" .Values.service.type }}
  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ include "chart.fullname" . }})
  export NODE_IP=$(kubectl get nodes --namespace {{ .Release.Namespace }} -o jsonpath="{.items[0].status.addresses[0].address}")
  echo http://$NODE_IP:$NODE_PORT
{{- else if contains "LoadBalancer" .Values.service.type }}
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get --namespace {{ .Release.Namespace }} svc -w {{ include "chart.fullname" . }}'
  export SERVICE_IP=$(kubectl get svc --namespace {{ .Release.Namespace }} {{ include "chart.fullname" . }} --template "{{"{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}"}}")
  echo http://$SERVICE_IP:{{ .Values.service.port }}
{{- else if contains "ClusterIP" .Values.service.type }}
  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app.kubernetes.io/name={{ include "chart.name" . }},app.kubernetes.io/instance={{ .Release.Name }}" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace {{ .Release.Namespace }} $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace {{ .Release.Namespace }} port-forward $POD_NAME 8080:$CONTAINER_PORT
{{- end }}
```

**Comment by adrianliechti** [comment]
a minimal sample would be this:

```
ingress:
  enabled: true
  className: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  rules:
    - host: chart-example.local
      path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-chart
  labels:
    helm.sh/chart: chart-0.1.0
    app.kubernetes.io/name: chart
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  rules:
    - host: "chart-example.local"
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: test-chart
              port:
                number: 80
```
