### ISSUE TITLE
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused

### ISSUE THREAD

**Issue by JudeNiroshan** [helm/helm#9466]
I get the following error in my Google Cloud Build when I upgrade to helm v3.5.2. The current setup is working without any errors for helm v2.17.0.

My helm v3 command setup looks as follows for Google Cloud Build:

```
  - name: 'gcr.io/private-folder/helm:v3.5.2'
    args:
      - 'upgrade'
      - '--install'
      - '--wait'
      - '$_AUTHOR_RELEASE_NAME'
      - '--namespace'
      - '$_NAMESPACE'
      - 'k8s/charts/abc-webshop/'
      - '-f'
      - 'k8s/charts-values/abc-webshop/$_VALUES_DIRECTORY/values.yaml'
      - '-f'
      - 'k8s/charts-values/abc-webshop/$_VALUES_DIRECTORY/author/values.yaml'
      - '-f'
      - 'k8s/charts-values/abc-webshop/$_VALUES_DIRECTORY/secrets.yaml'
      - '--set-string'
      - 'shop.image.tag=author_$SHORT_SHA'
      - '--timeout'
      - '3600s'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_ID'
      - 'KUBECONFIG=/workspace/.kube/config'

```

Error log is as follows:

```
Pulling image: gcr.io/private-folder/helm:v3.5.2
v3.5.2: Pulling from private-folder/helm
4c0d98bf9879: Already exists
70c15b15f056: Pulling fs layer
da21cc66ee7f: Pulling fs layer
da21cc66ee7f: Verifying Checksum
da21cc66ee7f: Download complete
70c15b15f056: Verifying Checksum
70c15b15f056: Download complete
70c15b15f056: Pull complete
da21cc66ee7f: Pull complete
Digest: sha256:722e4f1f4726d962eb87eb71b3f35ff41c36574fd44e8740e8eabfbb693bb0d4
Status: Downloaded newer image for gcr.io/private-folder/helm:v3.5.2
gcr.io/private-folder/helm:v3.5.2
W0311 14:30:10.975738       1 loader.go:223] Config not found: /workspace/.kube/config
W0311 14:30:10.976432       1 loader.go:223] Config not found: /workspace/.kube/config
W0311 14:30:10.976726       1 loader.go:223] Config not found: /workspace/.kube/config
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
```

**Output of `helm version`:**
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

**Output of `kubectl version`:** 
Not known as Google doesn't mentioned the exact version number: https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/kubectl

**Cloud Provider/Platform (AKS, GKE, Minikube etc.):** GKE + Google Cloud Build

Any help would be greatly appreciated! Thanks

**Comment by bacongobbler** [comment]
> W0311 14:30:10.975738       1 loader.go:223] Config not found: /workspace/.kube/config

This error is particularly relevant. You defined your $KUEBCONFIG to point at `/workspace/.kube/config`. That file does not appear to exist.

Can you please check and verify it is in the correct location?

**Comment by JudeNiroshan** [comment]
Thanks for the heads up. Unfortunately, as I'm using the Google Cloud Build service in GCP, I do not have the flexibility over ssh into a build server. 

Do you think the default Kubernetes config file location on a Linux machine is always located under `~/.kube/config`? Maybe I can change the ENV path again and give it a try.

**Comment by JudeNiroshan** [comment]
I tried with `~/.kube/config` and it doesn't work. I still get the 
`W0311 14:30:10.975738       1 loader.go:223] Config not found: ~/.kube/config`

Is this ENV variable really required for helm v3 in Google Cloud Build?

**Comment by JudeNiroshan** [comment]
I have resolved my problem. I will write down what change fixed my problem for anyone who will come across with the same problem running helm v3 on Google Cloud Build.

Google Cloud Build generally consists of multiple steps. For example: 

```
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'kms'
      - 'decrypt'
      - '--ciphertext-file=secrets.yaml.enc'
      - '--plaintext-file=secrets.yaml'
      - '--location=global'
      - '--keyring=abc-keyring-$_ENVIRONMENT'
      - '--key=abc-webshop-$_ENVIRONMENT'
    dir: 'k8s/charts-values/gcloud-sqlproxy/$_VALUES_DIRECTORY'
    ## Fetch GKE credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '$_CLUSTER_ID'
      - '--zone=europe-west3-a'
  - name: 'gcr.io/customer-abc/helm:v3.5.2'
    args:
      - 'upgrade'
      - '--install'
      - '--wait'
      - '$_RELEASE_NAME'
      - '--namespace'
      - '$_NAMESPACE'
      - 'rimusz/gcloud-sqlproxy'
      - '-f'
      - 'k8s/charts-values/gcloud-sqlproxy/$_VALUES_DIRECTORY/values.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_ID'
```
      
**Note:** the `## Fetch GKE credentials` step would help me to resolve my problem.
