### ISSUE TITLE
Can't specify subchart's imagePullSecrets

### ISSUE THREAD

**Issue by dledanseur** [helm/helm#9480]
Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.13", GitCommit:"4c00c3c459261e8ff3381c1070ddf798f0131956", GitTreeState:"clean", BuildDate:"2020-12-09T11:09:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

**Problem:**
When specifying a value for a subchart's imagePullSecrets, helm fails with the following error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.imagePullSecrets[0].name): invalid type for io.k8s.api.core.v1.LocalObjectReference.name: got "array", expected "string"
```
**Steps To reproduce:**

```
helm repo add sentry https://sentry-kubernetes.github.io/charts
helm install sentry sentry/sentry --dry-run --set clickhouse.clickhouse.imagePullSecrets={docker-hub}
```

Same error using values files and without the `--dry-run` parameter.

**Additional information:**

The sentry chart depends on the clickhouse chart:

```yaml
apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 9.1.2
appVersion: 21.2.0
dependencies:
...
  - name: clickhouse
    repository: https://sentry-kubernetes.github.io/charts
    version: 1.5.0
    condition: clickhouse.enabled
```

In the clickouse chart, the template injects the imagePullSecrets like this:

```yaml
    {{- if .Values.clickhouse.imagePullSecrets }}
      imagePullSecrets:
    {{- range .Values.clickhouse.imagePullSecrets }}
      - name: {{ . | quote }}
    {{- end }}
```

By directly targetting the clickhouse chart, helm generates the manifests correctly:

```
helm install sentry sentry/clickhouse --dry-run --set clickhouse.imagePullSecrets={docker-hub}
```

Both charts are hosted there: https://github.com/sentry-kubernetes/charts
