### ISSUE TITLE
Ingress syntax mismatch, helm 3.5.3 and kubernetes 19.x

### ISSUE THREAD

**Issue by KalleJohansson** [helm/helm#9485]
Output of `helm version`: 
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

Output of `kubectl version`:
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
minikube version: v1.13.1

Helm documentation, supported kubernetes version:
https://helm.sh/docs/topics/version_skew/

While deploying a helm chart to a local minikube cluster, ingress seems to have an outdated syntax in <CHART-NAME>/templates/ingress.yaml, resulting in following error message:
"Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]"

Beside this i was also required to change the following part in <CHART-NAME>/templates/ingress.yaml
(at row 5)
from:
```yaml
apiVersion: networking.k8s.io/v1beta1
```
to:
```yaml
apiVersion: networking.k8s.io/v1
```

However, changes according to the following tip:
https://stackoverflow.com/a/64126069/517457
Referencing:
https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

And changing in <CHART-NAME>/templates/ingress.yaml, does acctually make the above helm install error go away.
(starting at row 33)
from:
```yaml
paths:
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
```

to:
```yaml
paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
```
