### ISSUE TITLE
`helm lint` fails due to deprecations, but the recommended versions aren't available in our version of Kubernetes

### ISSUE THREAD

**Issue by tchupp** [helm/helm#9523]
### Background

When upgrading from helm `v3.4.2` to `v3.5.0` we see a new error when linting our charts.

`helm lint` fails due to deprecations, but the recommended versions aren't available in our version of Kubernetes:
```
$ helm lint --name-template test-lint .
==> Linting .
[WARNING] templates/ingress.yaml: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

This is the Ingress file:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sweet-ingress-name
  labels:
    app: sweet-app-name
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sweet-domain-name.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sweet-service-name
          servicePort: 80
```

It looks like the Kubernetes version that is being validated against is currently hardcoded as `v1.20` here: https://github.com/helm/helm/blob/master/pkg/lint/rules/deprecations.go#L28

Depending on how you look at it, this is either a bug (broken backward compatibility) or an enhancement.

### Debug information

Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"clean", GoVersion:"go1.15.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-eks-31566f", GitCommit:"31566f851673e809d4d667b7235ed87587d37722", GitTreeState:"clean", BuildDate:"2020-10-20T23:25:14Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS
