### ISSUE TITLE
Helm adds release name to dependent charts

### ISSUE THREAD

**Issue by canuysal** [helm/helm#9543]
I have few dependencies like this 
```
dependencies:
- name: some-chart
  version: "1.2.3"
  repository: "file://../some-chart"
  ```
And I install my chart like so
```
helm install my-chart .
```
However, it adds dependent charts my release name. so for example a pod deploys like this
```
my-chart-some-chart-server-0
```
If I only install the dependent chart on its own, for example `helm install some-chart ../some-chart` it deploys like this
```
some-chart-server-0
```
Is there a way to deploy dependent charts without adding release name as its  intended?

`helm version` : 3
