### ISSUE TITLE
Helm 3 libraries used with starters question

### ISSUE THREAD

**Issue by dsargent3220** [helm/helm#9551]
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Local development k3s cluster stood up with k3d

I'm creating a Helm starter for our mono repo apps.  I'm using a library for most of the code and including the library in the chart dependencies of the starter.
When I create a new chart using the starter, the result is not valid because the dependency is not in the charts folder and I can't do a `helm dep update` because the Chart.yaml is generated and does not include the dependency.  
If I perform `helm dep update` on the starter template (and check the compiled chart into source control, yuck) then copy down the starter to local and use that to create the new helm chart, then the library chart exists in the charts folder and the chart is valid.  However, there is no easy way to update the library chart and if it gets deleted, the app chart is broken.  
The Chart.lock file that existed in the starter also does not copy over so there is no way to easily get the library chart back into the resultant new chart and no way to update it.
This seems like something broken with starters.  The chart.yaml that gets created is generated and does not use the starters chart.yaml at all, (which is really sad and I believe also has a ticket open) but this also really breaks starters that use libraries as the resultant chart can not easily get any updates to the libraries thus kind of defeating the purpose of using a library to begin with.

Am I missing something?

**Comment by dsargent3220** [comment]
Why isn't the `Chart.yaml` in the starter just copied verbatim?  Seems like it should, as that's kind of the point of the starter.  
I think that would solve my problem.  
If the `Chart.yaml` from my starter was copied over then so would the `dependencies` section and the chain would remain intact.
For example, my starter `Chart.yaml` looks like this
```
apiVersion: v2
name: <CHARTNAME>
description: Describe the SEL SaaS application
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

dependencies:
  - name: platform-deployment
    version: 0.1.0
    repository: file://../../libraries/platform-deployment
```
I realize the `repository` would need to be a remote repo, it's a file now for dev purposes.
However, this is what we get
```
apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for Kubernetes
name: htest1
type: application
version: 0.1.0
```
Which is none of what I wanted.  

For now, if we could just get the Chart.yaml from the starter copied over, that would be awesome.
