### ISSUE TITLE
Helm ignores custom resources if introduced in a failing deployment

### ISSUE THREAD

**Issue by henrikb123** [helm/helm#9557]
Output of `helm version`:
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

NOTE: the same issue was seen on a cluster running Kubernetes 1.19.7, but that was less accessible for reproduction.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

# Description

We have a CRD in the cluster that existing applications should start using so the situation is existing deployments should deploy a new version of the Helm chart that includes such custom resource (CR).

On a sunny day this works fine, deployment succeeds and after that the CR can be updated as needed.

However, if they made some mistake in the CR content that will have impact on the release so that it fails, after this it is impossible to update the CR/correct the problem using helm.

# Simplified reproduction

## 1. Install a CRD

Create foobar-crd.yaml:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foobars.foobar.com
spec:
  group: foobar.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: foobars
    singular: foobar
    kind: FooBar
    shortNames:
    - fb
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
```
Install it:
```
kubectl apply -f foobar-crd.yaml
```

## 2. Install a helm chart that succeeds
```
helm create foobar
kubectl create ns foobar
helm upgrade --debug --install --wait --timeout 30s --namespace foobar foobar foobar
```

## 3. Create a custom resource fb.yaml and include it in the helm chart
```
apiVersion: "foobar.com/v1"
kind: FooBar
metadata:
  name: my-foobar
spec:
  update_me: foo
```

```
cp fb.yaml foobar/templates
```

## 4. Modify the chart so deployment will fail by pointing probes to a bad port
```
sed -i '' 's/port: http/port: 5000/g' foobar/templates/deployment.yaml # or simply edit the file
```

## 5. Make a new helm release with the updated chart
```
helm upgrade --debug --install --wait --timeout 30s --namespace foobar foobar foobar
```
Output as expected:
```
...
client.go:222: [debug] Created a new FooBar called "my-foobar" in foobar
...
```

and helm returns an error because probes fail so new pod doesn't come up.

But by doing
```
kubectl get fb -n foobar -oyaml
```
we can see the new resource was created with correct data.

## 6. Modify the CR and redeploy
Edit cr.yaml so that it says
```
  update_me: bar
```

```
helm upgrade --debug --install --wait --timeout 30s --namespace foobar foobar foobar
```

Output NOT as expected:

```
...
client.go:464: [debug] Looks like there are no changes for FooBar "my-foobar"
...
```

And by doing
```
kubectl get fb -n foobar -oyaml
```
we can see that the resource in the cluster still says update_me: foo.
