### ISSUE TITLE
YAML Anchor on values.yaml isn't overrided by --set argument

### ISSUE THREAD

**Issue by 42Atomys** [helm/helm#9558]
Hi everyone,

I found somethings on YAML parser, when we use an anchor on `values.yaml` and override value of anchor with `--set`, the output of called anchor is not overrided by set 

Repo to bug : https://github.com/42Atomys/helm-bug-yaml-anchor

Output of `helm version`:
```go
version.BuildInfo{
  Version:"v3.2.1",
  GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a",
  GitTreeState:"clean",
  GoVersion:"go1.13.10"
}
```

Output of `kubectl version`:
```go
Client Version: 
version.Info{
  Major:"1",
  Minor:"19",
  GitVersion:"v1.19.7",
  GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15",
  GitTreeState:"clean",
  BuildDate:"2021-01-13T13:23:52Z",
  GoVersion:"go1.15.5",
  Compiler:"gc", Platform:"linux/amd64"
}

Server Version: 
version.Info{
  Major:"1", 
  Minor:"20", 
  GitVersion:"v1.20.4", 
  GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", 
  GitTreeState:"clean", 
  BuildDate:"2021-02-18T16:03:00Z", 
  GoVersion:"go1.15.8", 
  Compiler:"gc", 
  Platform:"linux/amd64"
}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Scaleway, GKE and kubeadm on Baremetal

**Comment by mattfarina** [comment]
I was not able to reproduce the problem but that may be because of the usage.

YAML anchors are useful within a single YAML file. They are part of the parsing and serialization process. But, they are not going to work to override multiple values when merging data. Helm (and other Go programs using the YAML parsers) will read the YAML file into memory as an object. Once the parsing is complete the anchors are no longer useful as the data from the YAML file is represented in an object in memory.

Helm will then have an object representing the values and it will merge it with other objects representing the values or with specific values being set at the command line. These are all operations performed after parsing. So, anchors have no effect.

Here's an example of a change that worked...
```
❯ helm template . --set services.web.ingress.tlsSecretName=foo
---
# Source: helm-bug-yaml-anchor/templates/template.yaml
kind: ConfigMap
metadata:
  name: foobars.foobar.com
  annotations:
    # Default Anchor value :
    a: "super-secret-tls"

    # Called Anchor value :
    b: "foo"
    c: "super-secret-tls"
data:
```
