### ISSUE TITLE
Semantics of --version flag

### ISSUE THREAD

**Issue by wbrefvem** [helm/helm#9566]
I've noticed that `--version` flag as used in commands like `helm pull` does not match a version, per se, but matches a version of equal precedence. Following SemVer, determinations about precedence ignore build meta (i.e., everything after the `+` in the version string). This leads to non-deterministic behavior when attempting to pull a chart from a collection of charts of equal SemVer precedence but differing in their build meta.

For example, let's say I have the following index cached locally:

```
apiVersion: v1
entries:
  foo:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-03-25T17:00:17Z"
    description: deploys the foo service
    digest: d26cc8b93fd24fe4b072374116fa6b286441a712fad4751cb7795c74efde2422
    name: foo
    type: application
    urls:
    - charts/foo-0.1.0+build-xyz789.tgz
    version: 0.1.0+build-xyz789
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-03-30T20:17:33Z"
    description: deploys the foo service
    digest: 73d39eb9b96231a24b24012941dd1f286110ec00510e85a54c72033498892c68
    name: foo
    type: application
    urls:
    - charts/foo-0.1.0+build-abc123.tgz
    version: 0.1.0+build-abc123
```

If I run helm pull on the second version in the list, I get the first:
```
$ helm pull myrepo/foo --version 0.1.0+build-abc123
$ ls
foo-0.1.0+build-xyz789.tgz
```

My guess from this behavior is that helm is performing a precedence comparison on each version of the chart and returning the first one that matches, which is a very strange design choice. It essentially means that build metadata on chart versions are useless, and that means that helm's utility in a CD workflow that generates many versions of a chart per day is very limited.

Am I missing anything?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS
