### ISSUE TITLE
helm lint does not error on invalid env in values.yaml

### ISSUE THREAD

**Issue by teebszet** [helm/helm#9575]
To Reproduce:

create a helm chart with values.yaml file including:

```
env:
  - name: "ASPNETCORE_ENVIRONMENT"
    value: "Development"
    valueFrom:
      secretKeyRef:
        name: quorum-secret
        key: mercury_address
```

and deployment.yaml file including:
```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - env:
          {{- toYaml .Values.env | nindent 10 }}
```

If I try to helm install this chart, it will give an error like:

`spec.template.spec.containers[0].env[9].valueFrom: Invalid value: \"\": may not be specified when `value` is not empty"`

but `helm lint -f values.yaml` will not find any errors

Expected Result: helm lint to return an error

Output of `helm version`: `version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-31T15:33:39Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS EKS
