### ISSUE TITLE
Helm gotpl merging templates issue since 3.5.0-rc.1

### ISSUE THREAD

**Issue by anthony-pastor** [helm/helm#9583]
Hi,

We are using gotpl to merge information like metadata to Helm templates.
Example can be found here: https://github.com/JordanGoasdoue/golang-demo-app-reproduce-flux-error/blob/non-working-version/charts/golang-demo-app/templates/svc.yaml#L15
It was working fine, until we upgraded from Helm 3.4.2 to 3.5.0-rc.1 (and above).
Since the upgrade we observe issues with this behavior.

To reproduce the issue:
```
git clone git@github.com:JordanGoasdoue/golang-demo-app-reproduce-flux-error.git
cd golang-demo-app-reproduce-flux-error
git checkout non-working-version
cd charts
kubectl create namespace test
helm -n test install golang-demo-app ./golang-demo-app
```
- With Helm 3.4.2 the Chart is installing as expected.
- Since Helm 3.5.0-rc.1 it's failing with this error message:

`Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: resource name may not be empty`.

**Comment by bacongobbler** [comment]
It sounds like your cluster contains resources that clash with the ones being rendered by your chart. To resolve this, determine which resources your helm chart wishes to install in the cluster and delete any existing ones already present there. Helm does not "commandeer" existing resources already present as that presents several issues, most notably namespace clashes or accidentally deleting production data.

**Comment by bacongobbler** [comment]
Or in this case, your templates may not contain a name in the resource at all.

There are a few tickets discussing this issue, most notable of which is #9019. Have you been tracking that discussion?

**Comment by anthony-pastor** [comment]
@bacongobbler 
Doig a `helm template` on the _non-working-version_ branch we get:

- For Helm 3.4.2:
```
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: golang-demo-app
    helm.sh/chart: golang-demo-app
  name: RELEASE-NAME
  namespace: default
```

- For Helm 3.5.0-rc.1 and above:
`metadata: null`
