### ISSUE TITLE
Helm release of Kubernetes job times out despite the Job completing successfully

### ISSUE THREAD

**Issue by leiter-jakab** [helm/helm#9584]
Output of `helm version`:
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

# Description

1. I have a helm chart that deploys a flyway migration as a kubernetes job. The chart is in local file system directory `./db-migration`.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    aadpodidbinding: key-vault-identity
  annotations:
    kubernetes.io/change-cause: {{ .Values.change_cause }}
  name: {{ .Values.application_name }}-database-migration-{{ .Values.version }}
spec:
  activeDeadlineSeconds: 420
  backoffLimit: 0
  template:
    metadata:
      labels:
        aadpodidbinding: key-vault-identity
    spec:
      containers:
        - args:
            - migrate
          env:
            - name: MIGRATION_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: database-schema-admin
            - name: MIGRATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: database-schema-admin
          image: "{{ .Values.environment }}{{ .Values.application_name | replace "-" "" }}.azurecr.io/{{ .Values.application_name }}-flyway-with-test-data:{{ .Values.version }}"
          imagePullPolicy: Always
          name: flyway-migration
          volumeMounts:
            - mountPath: /flyway/conf
              name: flyway-config
            - mountPath: /mnt/secrets-store
              name: secrets-store-inline
              readOnly: true
      restartPolicy: Never
      volumes:
        - configMap:
            name: {{ .Values.application_name }}-flyway-conf
          name: flyway-config
        - csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kvname
          name: secrets-store-inline
```

2. I install the release with the following command:

```
helm upgrade --install db-migration-release db-migration \
    --namespace migration-namespace \
    --set version=1.0.0.0 \
    --set application_name=test \
    --set environment=test \
    --set change_cause=test \
    --wait --wait-for-jobs --cleanup-on-fail --timeout 7m10s
````

3. The migration runs to completion. The Job/Pod has status `Complete`.

# Expected result

The helm release finishes successfully shortly after the Job completes.

# Actual result

The helm release waits for the full timeout duration and finishes with failure due to timeout. Resources are not cleaned up after the failed release.
