### ISSUE TITLE
What is the recommended method of creating file secrets from external files with newlines and special characters?

### ISSUE THREAD

**Issue by willieowens** [helm/helm#9594]
I have file secrets stored in GCP Secret Manager which we decrypt and use to dynamically set values in a helm install/upgrade. For environment variable secrets, I can simply use --set-string to pass in values, but for file secrets (perhaps private keys, or even JSON) I'm not sure the recommended pattern to follow.

I tried a combination of `--set-string` and/or `--set-file` to pass the filenames and/or contents dynamically to no avail. Passing in the file contents via `--set-string` produces an invalid helm command due to the newlines and json file contents. If I use `--set-file` I can pass in the values to helm -- they'll look something like:
```yaml
some-private-key:
  pem: |
    -----BEGIN RSA PRIVATE KEY-----
    ...
```
as the file is named `some-private-key.pem`, but when I try to use that value in my template I get the error: `<b64enc>: invalid value; expected string`...
```bash
fileIdx=0
for SECRET_NAME in $FILE_SECRET_NAMES; do
    fileSecrets[${fileIdx}].value='${SECRET_VALUE}'"
    args="${args} --set-string fileSecrets[${fileIdx}].name=${SECRET_NAME}"
    args="${args} --set-file ${SECRET_NAME}=$DECRYPTED_ROOT_DIR/files/$SECRET_NAME"
    fileIdx=$((fileIdx + 1))
done
```
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: file-secrets
  namespace: "{{ .Value.namespace }}"
data:
  {{- range $.Values.fileSecrets }}
  {{ .name }}: {{ index $.Values .name | b64enc }}
  {{- end }}
```

I made things work by passing in file secrets using `--set-string` to pass name/value pairs, where I first base64-encoded (and stripped whitespace) the file contents in a bash script, but this feels like a hack rather than using something built into helm.

Output of `helm version`:
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-dispatcher", GitCommit:"a39a896b5018d0c800124a36757433c660fd0880", GitTreeState:"clean", BuildDate:"2021-01-28T21:47:26Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-gke.2800", GitCommit:"4ef0543cc59f482d118ae33397108118ec80d447", GitTreeState:"clean", BuildDate:"2021-02-20T01:42:15Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

*edit*
It seems one possible solution here is to copy file secrets to the chart directory and configure them as secrets like:
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: file-secrets
  namespace: "{{ .Values.namespace }}"
data:
{{ ($.Files.Glob "fileSecrets/*").AsSecrets | indent 2 }}
```
is this the recommended pattern? Seem slightly cumbersome to need to copy them to a specific directory and then clean them up, though I'm pretty much having to do that regardless, so...
