### ISSUE TITLE
Is there any way to debug `Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: apiVersion not set`

### ISSUE THREAD

**Issue by red8888** [helm/helm#9601]
This error is an embarrassing frustration when working with helm: https://stackoverflow.com/questions/62747453/helm-3-chart-install-error-error-validating-data-apiversion-not-set#:~:text=This%20error%20means%20that%20the,from%20the%20directory%20where%20Chart.

It always results in a big process of elimination for me because there is zero useful info in that error of where the issue is.

How do you get better error messages for this? Am I doing it wrong? 

Last time I had this error it was a comment that looked like this:
`# TODO: update to .Capabilities.KubeVersion.Version
`
I suppose I should _aways_ use `{{/* ... */}}` for comments? But sometimes its useful to have comments in the manifest itself.

Wondering if there is some debug mode you can turn on to actually get a line number or _something_

**Comment by bacongobbler** [comment]
Sorry to hear you're running into this.

After the templates are rendered, they are then sent to Kubernetes for validtation. In this case, your templates rendered successfully, but failed Kubernetes validation. In this case, the `apiVersion` field from one of your templates was not set.

Here's an example of a well-formed Kubernetes manifest:

```
apiVersion: v1
kind: Pod
metadata:
  name: docker-react-pod
  labels: 
    component: web
spec:
  containers:
    - name: docker-react-app
      image: dashsaurabh/progressive-coder
      ports: 
      - containerPort: 3000
```

Notice how there's an `apiVersion` field with the value `v1` in the manifest. This is required by Kubernetes.

I would check two things:

1. You can append the `--debug` flag to help display to the screen what's being sent to Kubernetes.
2. Alternatively, you can run `helm template` locally to view the rendered output.

With this information, check to see whether you're accidentally sending an empty manifest (commonly this occurs when an entire template is commented out), or a manifest with an empty `apiVersion` field. That field is required by all kubernetes objects IIRC.

Hope this helps.
