### ISSUE TITLE
Can Helm upgrade preserve an existing deployment with a name change? 

### ISSUE THREAD

**Issue by davidshaw2018** [helm/helm#9603]
I have a simple Helm chart that deploys a single Deployment. The deployment should be named after my package version, with the hope that subsequent `helm upgrade` calls will create a new deployment and preserve the existing one. 

However, it seems that the existing deployment is indeed spun down when the chart is upgraded. Any workarounds to this? 

Minimal yaml example: 
```yml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: foobar-{{ .Values.package_version }}
  labels:
    app: foobar-{{ .Values.package_version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foobar-{{ .Values.package_version }}
  template:
    metadata:
      labels:
        app: foobar-{{ .Values.package_version }}
        name: foobar-{{ .Values.package_version }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: foobar_url
```

Installing the chart produces 1 deployment as expected. But I'm curious about the upgrade behavior when deploying as such:

```
helm install foobar . --set package_version=1.0
helm upgrade foobar . --set package_version=2.0
```

Expected output: 
```
(jm) Davids-MacBook-Pro / % kubectl get deployments
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
foobar-1.0                   1/1     1            1           13m
foobar-2.0                   1/1     1            1           13m
```

Observed:
```
(jm) Davids-MacBook-Pro / % kubectl get deployments
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
foobar-2.0                   1/1     1            1           13m
```

I'm curious about how `helm upgrade` works exactly, are existing replicas destroyed after new replicas are created? And if so, are there any simple workarounds to preserve the existing replicas? 

I'm on version 3.5.2, by the way.
