### ISSUE TITLE
Text inside comment incorrectly interpreted 

### ISSUE THREAD

**Issue by luckerby** [helm/helm#9634]
Consider the following yaml file, based on the simple examples found [here](https://helm.sh/docs/chart_template_guide/variables/):
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
# This is a comment
data:
  myvalue: "Hello World"
  drink: "test"
  anotherValue: "test"
  # anotherValue: {{ $relname }}
```
Trying to do `helm lint` against a new Helm chart (itself created using `helm create`) that includes the file above results in the output below. The same outcome can be seen by using `helm install <chart-name> --dry-run --debug .`
```
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: parse error at (smtp4dev/templates/configmap.yaml:9): undefined variable "$relname"
```
**It appears as if the comment on the last line is actually parsed**, which I wouldn't have expected, nor did find this documented. Am I doing something wrong on my end?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"c7c4f6ce84bf8535a782b67465807651a4bd649b", GitTreeState:"clean", BuildDate:"2021-01-18T09:49:05Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS
