### ISSUE TITLE
how to helm ls -l 

### ISSUE THREAD

**Issue by rootdeep** [helm/helm#9646]
Output of `helm version`:
v3.5.2
Output of `kubectl version`:

v1.16.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

I'm testing the command  ' helm ls -l  ( or --selector)' , but  it never works.

I downloaded the stable coredns chart from https://github.com/helm/charts/tree/master/stable/coredns

and installed the chart successfully.

I  fount the  deployment coredns with label as bellow:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: coredns
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-04-25T13:30:51Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: coredns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coredns
    helm.sh/chart: coredns-1.13.8
    k8s-app: coredns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: coredns-coredns
```
After  running commond   helm ls -l  helm.sh/chart=coredns-1.13.8 or  helm ls -l "helm.sh/chart=coredns-1.13.8" ,  the terminal  dosen't  print  any  release information .
however, the expected  result  as bellow
```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
coredns         default         1               2021-04-25 21:30:50.788806729 +0800 CST deployed        coredns-1.13.8                          1.7.1      
```
what's wrong with me?
