### ISSUE TITLE
helm upgrade not patching resources in other namespaces

### ISSUE THREAD

**Issue by GerryWilko** [helm/helm#9656]
I believe I have found a bug with the `helm upgrade` command (I believe this affects install too). I believe this is related to installing a helm chart with resources across many namespaces. I'm not sure if this is meant to be supported but I couldnt find anything saying you can't 😄 

Essentially what I was trying to achieve was enable our team to define custom ingress routes to our services. which tenanted. Each tenant has its own namespace in the cluster.

I created a really simple `values.yaml`:
``` yaml
customIngress:
- namespace: ingress-nginx
  host: some-custom-host
```

And manifest:
``` yaml
{{- range .Values.customIngress }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-custom-{{ .host }}
  namespace: {{ .namespace }}
spec:
  rules:
    - host: {{ .host }}.custom.example.com
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: some-service
              port:
                number: 80

---

{{- end }}

```
Full chart zipped here: 
[custom-ingress.zip](https://github.com/helm/helm/files/6390922/custom-ingress.zip)

When installing this the first time it works perfectly but any upgrades to this file afterwards that are not new ingress definitions do not work i.e:
``` yaml
customIngress:
- namespace: other-namespace # same host different namespace fails
  host: some-custom-host
- namespace: other-namespace # different host same or different namespace succeeds
  host: new-custom-host
```

I get the following error. Which seems to be that helm is not patching the current manifest but trying to redeploy which obviously doesnt work as there is already a host defined for this:
```
Error: UPGRADE FAILED: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "some-test.custom.example.com" and path "/" is already defined in ingress some-namespace/ingress-custom-some-test
```

Now the strange part is that once this error has occured the manifests orginally deployed by Helm seem to have become detached. They no longer uninstall when uninstalling the release, which points to the same issue when trying to upgrade. It appears that helm just doesnt like doing an upgrade to manifests across namespaces. Interestingly though if I were to install then uninstall without trying to upgrade anything the manifests across the other namespaces are correctly removed.

It also seems that after an install that errors (for example putting in a namespace that doesnt exist) helm still creates the release which looking at the docs it seems that shouldnt happen.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"8ab00ff68a1763b5a506a7073cb8e67b12dfbcd7", GitTreeState:"clean", BuildDate:"2021-03-10T23:40:01Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
AKS
```
