### ISSUE TITLE
Command helm-template can't render an invalid yaml

### ISSUE THREAD

**Issue by artemlops** [helm/helm#9663]
- Output of `helm version`:
```
$ helm version  
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"archive", BuildDate:"2021-03-25T19:02:48Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.16", GitCommit:"d88fadbd65c5e8bde22630d251766a634c7613b0", GitTreeState:"clean", BuildDate:"2020-12-18T15:59:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`Azure`

- Description
The problem is that `helm template` is supposed to render the manifests even if the result isn't a valid YAML after the helpers were processed. However, it's still trying to parse the rendered output as a YAML and fails:
```
$ helm create test-chart
$ line_escaped="app.kubernetes.io\/instance: {{ .Release.Name }}"
$ sed -i "s/$line/  $line/g" test-chart/templates/_helpers.tpl

$ helm template test-chart                                       
Error: YAML parse error on test-chart/templates/deployment.yaml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context

Use --debug flag to render out invalid YAML
```
As a result, it's very hard to debug templates in `_helpers.tpl`.

**Comment by yxxhero** [comment]
Please show the `_helpers.tpl` file that you handled.

**Comment by artemlops** [comment]
```
$ cat test-chart/templates/_helpers.tpl 
{{/*
Expand the name of the chart.
*/}}
{{- define "test-chart.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "test-chart.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "test-chart.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "test-chart.labels" -}}
helm.sh/chart: {{ include "test-chart.chart" . }}
{{ include "test-chart.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "test-chart.selectorLabels" -}}
app.kubernetes.io/name: {{ include "test-chart.name" . }}
  app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "test-chart.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "test-chart.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}
```

The template `"test-chart.selectorLabels"` is broken

**Comment by yxxhero** [comment]
and test-chart/templates/deployment.yaml

**Comment by artemlops** [comment]
well, as the commands in the description show, the template is generated via `helm create` and then 1 single line is changed using `sed` in `_helpers.tpl`. 

So the idea is that we have the template `test-chart/templates/_helpers.tpl`:
```
{{/*
Selector labels
*/}}
{{- define "test-chart.selectorLabels" -}}
app.kubernetes.io/name: {{ include "test-chart.name" . }}
  app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
```
(note 2 spaces before `app.kubernetes.io/instance`).

And this template is used in the manifest `test-chart/templates/deployment.yaml`:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-chart.fullname" . }}
  labels:
    {{- include "test-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "test-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
...
```

The `spec.selector.matchLabels` uses the template `test-chart.selectorLabels` which is not a valid dictionary (because of the wrong indent).

What I expect to get with `helm template test-chart` is:
```
# Source: test-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-test-chart
  labels:
    helm.sh/chart: test-chart-0.1.0
    app.kubernetes.io/name: test-chart
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-chart
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-chart
          app.kubernetes.io/instance: RELEASE-NAME  # <-- here I expect to see the wrong indent
    spec:
      serviceAccountName: RELEASE-NAME-test-chart
      securityContext:
```
But what I get is the error:
```
Error: YAML parse error on test-chart/templates/deployment.yaml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context

Use --debug flag to render out invalid YAML
```
Obviously, Helm is trying to parse the rendered manifests as YAML and fails to do so. From my point of view, this makes it difficult to debug templates, at least for the beginners.
