### ISSUE TITLE
Mapping Multiple Files to pod

### ISSUE THREAD

**Issue by letran3691** [helm/helm#9682]
Hello
I'm try Mapping Multiple to config folder pod.
I've try volumeMount 2 way mountPath: /etc/nginx/ and mountPath: /etc/config/
then helm --debug and helm lint output don't error
I've install chart with option mountPath: /etc/config/. and check folder in pod  nginx.conf, mime.types mounted
when i install chart mountPath: /etc/nginx/  error
![image](https://user-images.githubusercontent.com/19284401/117539854-a6e9e100-b036-11eb-9842-60748b8670c8.png)

Output of `helm version`: version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

file configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  nginx_conf: {{ tpl (.Files.Get "files/nginx.conf") . | quote }}
  mime_types: {{ .Files.Get "files/mime.types" | quote }}

```

deployment.yaml
```
      volumes:
        - name: nginx-config
          configMap:
            name: my-config
            items:
              - key: nginx_conf
                path: nginx.conf
              - key: mime_types
                path: mime.types


          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/


```

update:
I'm try syntax template go however return string it's not true
![image](https://user-images.githubusercontent.com/19284401/117543314-7f9b1000-b046-11eb-8163-89e7e29dc172.png)
