### ISSUE TITLE
Print generated chart contents when yaml validation error - to make debug easier

### ISSUE THREAD

**Issue by ieugen** [helm/helm#9684]
Hi,

This is a feature proposal to improve debugging by a lot IMO.
Yaml is not the prietiest format to write, even more so when you make mistakes.

Right now the current information is most of the times not enough to properly debug YAML related problems, especially if you are not as familiar with it. 

The current debug output looks like this:
```
history.go:56: [debug] getting history for release biz
upgrade.go:123: [debug] preparing upgrade for biz
Error: UPGRADE FAILED: YAML parse error on ofbiz/templates/configmap.yml: error converting YAML to JSON: yaml: line 9: could not find expected ':'
helm.go:81: [debug] error converting YAML to JSON: yaml: line 9: could not find expected ':'
YAML parse error on ofbiz/templates/configmap.yml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
```

My configmap has 7 lines:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "ofbiz.fullname" . }}
data:
  security.properties: |
    "{{ .Values.config.security_properties }}"
````
The working syntax in my case is :

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "ofbiz.fullname" . }}
data:
  security.properties: |-
    {{ .Values.config.security_properties | indent 4}}
```

But without seeing what helm is trying to validate it's a guessing game.

It would be great if we could access the data that helm is trying to validate instead of just the error. 
That way, we could read the error and the text that is causing the error and figure out a solution.
