### ISSUE TITLE
Format output of --debug --dry-run to be friendly with YAML modes of code editors

### ISSUE THREAD

**Issue by sandipchitale** [helm/helm#9691]
This is really an enhancement request.

I use ```--debug``` ``` --dry-run``` flags with ```install``` and ```update``` commands to see how various values files will be merged and what Kubernetes templates are generated. I typically capture the output in ```*.yaml``` files (as most interesting output is in yaml format) and then open the output in code editors. However, some of the generated section headers cause the code editors and wikis to complain about the broken syntax. It will be nice if the header lines are generated with ```# HEADER``` format so that the code editors ignore those.

It will be useful to generate code folding sections markers surrounding each section.

The ```# Source: ``` lines are already generated correctly.

For example, instead of generating the output ike this:

```yaml
NAME: sample
LAST DEPLOYED: Tue May 11 23:58:59 2021
NAMESPACE: default
STATUS: pending-install
REVISION: 1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
...

HOOKS:
---
# Source: sample/templates/tests/test-connection.yaml
...
MANIFEST:
---
# Source: sample/templates/serviceaccount.yaml
...

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=sample,app.kubernetes.io/instance=sample" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
```
generate it like this:

```yaml
# NAME: sample
# LAST DEPLOYED: Tue May 11 23:58:59 2021
# NAMESPACE: default
# STATUS: pending-install
# REVISION: 1
# USER-SUPPLIED VALUES:
{}

# COMPUTED VALUES:
...

# HOOKS:
---
# Source: sample/templates/tests/test-connection.yaml
...
# MANIFEST:
---
# Source: sample/templates/serviceaccount.yaml
...

# NOTES:
# 1. Get the application URL by running these commands:
#   export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=sample,app.kubernetes.io/instance=sample" -o jsonpath="{.items[0].metadata.name}")
#   export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
#   echo "Visit http://127.0.0.1:8080 to use your application"
#   kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
```
Hope this makes sense.
