### ISSUE TITLE
Failed deployments not considered when patching resources

### ISSUE THREAD

**Issue by jlyheden** [helm/helm#9692]
When running helm upgrade on an existing release, it appears that helm ignores state that was changed resulting in a failed release. This manifests itself in particular when we use the --wait flag and say that a developer bumps the version of their software component and at the same time want to activate a feature using a new environment variable, the deployment fails because of code issues and now the pod container has an environment variable set that is not tracked by helm.

Here is an example how to reproduce it with a simple helm chart:

chart/templates/deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: busybox
          image: busybox:latest
{{- if .Values.deploy1 }}
          command: ["/bin/sh", "-ec", "while :; do sleep 5; done"]
          env: []
{{- else if .Values.deploy2 }}
          command: ["false"]
          env:
            - name: UNWANTED_VAR
              value: foo
{{- else if .Values.deploy3 }}
          command: ["/bin/sh", "-ec", "while :; do sleep 5; done"]
          env:
            - name: WANTED_VAR
              value: bar
{{- end }}
```

First deploy the initial successful version with no environment variables:
```
$ helm upgrade --install --wait --set deploy1=true chart chart
```

Then deploy a crashing version with new environment variable:
```
$ helm upgrade --install --wait --set deploy2=true chart chart
```

Finally deploy a working version with another environment variable:
```
$ helm upgrade --install --wait --set deploy3=true chart chart
```

The result, where the expected output would be only the WANTED_VAR but now also contains the UNWANTED_VAR from the failed deployment:
```
$ kubectl get po -o json | jq '.items[0].spec.containers[0].env'
[
  {
    "name": "WANTED_VAR",
    "value": "bar"
  },
  {
    "name": "UNWANTED_VAR",
    "value": "foo"
  }
]
```

Output of `helm version`:
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kubeadm
