### ISSUE TITLE
OCI: no version range support for dependencies/`helm install`

### ISSUE THREAD

**Issue by TZdybel** [helm/helm#9694]
I'm trying to make my helm chart with dependencies to get newest version I pass to it.
I see that "latest" tag is not possible so I've tried with semantic versions like "~1.x" which should work according to documentation.
It works for things like mongodb chart from bitnami repo, but not for my Azure Container Registry.
My `Chart.yaml`:
```yaml
apiVersion: v2
name: somename
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: common
    version: 1.0.0
    repository: "oci://myazurecr.azurecr.io/helm"
```
Output from `helm dependency update`:
```
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://myazurecr.azurecr.io/helm" chart repository:
        tag explicitly required
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "kured" chart repository
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "gitlab" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading common from repo oci://myazurecr.azurecr.io/helm
~1.x: Pulling from myazurecr.azurecr.io/helm/common
Save error occurred:  could not download oci://myazurecr.azurecr.io/helm/common: myazurecr.azurecr.io/helm/common:~1.x: not found
Deleting newly downloaded charts, restoring pre-update state
Error: could not download oci://myazurecr.azurecr.io/helm/common: myazurecr.azurecr.io/helm/common:~1.x: not found
```
Is this a bug related to recent introduction of OCI references as repository?
