### ISSUE TITLE
wrong version matching with helm show chart

### ISSUE THREAD

**Issue by ltagliamonte-dd** [helm/helm#9697]
Hello community!
I'm trying to automate the upload of charts in my private helm registry and i stumbled on a problem with `helm show chart`.
It doesn't seems to respect at all any semver options, for example:
```
helm show chart --version '0.*.0+luigi-upgrade' repo/signadot
apiVersion: v1
appVersion: 0.5.7
dependencies:
- condition: sidecar-injector.enabled
  name: sidecar-injector
  repository: ""
  version: 0.5.1
description: Signadot Proxy Chart
name: signadot
version: 0.3.0+chart-upgrade-c405a19a
```

as you can see my search pattern contains `luigi-upgrade` that's the branch ref, but i get back `0.3.0+chart-upgrade` that belongs to another branch.

I also tried: 
`helm show chart --version '0.[0-9]{1,}.0+luigi-upgrade' repo/signadot`
`helm show chart --version '0.[0-9]{1,}.0+chart-upgrade' repo/signadot`
and both return:
```
Error: failed to download "repo/signadot" (hint: running `helm repo update` may help)
```

My end goal is to updating the chart version automatically and avoid collision if 2 developers are working on the same chart.

```
helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```
