### ISSUE TITLE
Helm pre-delete hooks Remove Chart Metadata on Failure

### ISSUE THREAD

**Issue by jonathan-innis** [helm/helm#9700]
Output of `helm version`: 

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"w
indows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"lin
ux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): kind Cluster

In order to ensure that the cluster is in a good state to delete the helm release, I am onboarding a pre-delete hook to check the state before actually deleting the release. This works fine and times out for the resources themselves, but the chart release metadata is gone when running `helm ls -A`.

![image](https://user-images.githubusercontent.com/26334334/118331149-0cb5ed00-b4bd-11eb-900a-e8ca88144d85.png)

Because of this behavior, if the initial delete fails, I am no longer able to remove the resource through a `helm uninstall` because the chart release itself has disappeared.

My pre-delete hook is below:

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-delete
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: flux-operatorsa
      restartPolicy: Never
      containers:
        - name: pre-delete-job
          image: mcr.microsoft.com/oss/kubernetes/kubectl:v1.21.0
          command:
            - 'sh'
            - '-c'
            - '/scripts/pre-delete.sh'
          volumeMounts:
            - name: pre-install-script
              mountPath: "/scripts"
      volumes:
        - name: pre-install-script
          configMap:
            defaultMode: 0777
            name: flux-extension-hooks
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  name: flux-extension-hooks
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  pre-delete.sh: |
    #!/bin/bash

    export HAS_FLUX_CONFIG_CRD=$(kubectl get crd fluxconfigs.clusterconfig.azure.com -o json)
    if [ ! -z "$HAS_FLUX_CONFIG_CRD" ]
    then
      echo "Found the flux config CRD on the system"
      export FLUX_CONFIGS=$(kubectl get fluxconfigs -A -o json)
      if [ ! -z "$FLUX_CONFIGS" ]
      then
        echo "Flux configurations still remain on the cluster, cleanup of these instances must be done before deletion of extension..."
        exit 1
      fi
    fi
    echo "No more flux configuration instances found on the cluster, deletion is proceeding..."
```
