### ISSUE TITLE
Helm does not support NamespaceSelector in NetworkPolicy

### ISSUE THREAD

**Issue by michaelcourcy** [helm/helm#9703]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"c66c03f3012a10f16eb86fdce6330433adf6c9ee", GitTreeState:"clean", BuildDate:"2021-03-13T02:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+2f3101c", GitCommit:"2f3101cb663d0cb102ccb9730b63753604f6d29b", GitTreeState:"clean", BuildDate:"2021-02-26T13:55:24Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): ARO (openshift on azure) 

When submitting this api 
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: openshift-sdn-allow
spec:
  ingress:
  - namespaceSelector:
      matchLabels:
        name: openshift-sdn
    ports:
    - port: 8000
      protocol: TCP
  podSelector:
    matchLabels:
      release: k10
  policyTypes:
  - Ingress
```

It validates. 

But when including that in a helm chart I get 

```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(NetworkPolicy.spec.ingress[0]): unknown field "namespaceSelector" in io.k8s.api.networking.v1.NetworkPolicyIngressRule
```

**Comment by michaelcourcy** [comment]
my fault on openshift this is tolerated but in kubernetes it should be 

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: openshift-sdn-allow
spec:
  ingress:
  - from: 
      - namespaceSelector:
           matchLabels:
           name: openshift-sdn
    ports:
    - port: 8000
      protocol: TCP
  podSelector:
    matchLabels:
      release: k10
  policyTypes:
  - Ingress
```
