### ISSUE TITLE
How to use tags and condition in the chart templates?

### ISSUE THREAD

**Issue by hnlzq163** [helm/helm#9712]
Hi,
This is a document question, but it is also important, and I think it is typical usage scenario for us.

**Good**: I can find the usage for **tags** and **condition** for the sub charts in [conditions-and-tags](https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags)

**Question**: 
1. I just want to know can I use the **tags** or **condition** in the **chart templates** except for sub charts?
If yes, **how can I use it?** **any limitation?**

2. **If I want to use global tags(subchart and parent chart can share the same tags and also can use it as condition in template if i have 3 or more level subcharts), how to define?**

I think it is useful for us for using helm charts. 
Hope you can add this section for it whether it can use or not in chart templates.
Thanks

**Comment by bacongobbler** [comment]
I’m not totally sure I understand the issue. Would you mind providing a more concrete example of the issues you are running into wand why you think this would solve that issue?

**Comment by hnlzq163** [comment]
# Source: test/requirements.yaml
```
dependencies:
  - name: subchart1
    version: ~1.0.0
    repository: "https://test.com/chart-repo"
    tags:
      - t1
      - t2
```
# Source: test/deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
template:
  spec:
    containers:
    - name: test-container
      env:
        - name: ENV1
          value: value1
      {{- if index .Values "tags" "t1" }} # for question-1
        - name T1_ENV
          value: value2
      {{- end }}
```
# Source: test/subchart1/deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
template:
  spec:
    containers:
    - name: sub-container
      env:
      {{- if index .Values "tags" "t1" }} # for question-2
        - name T1_ENV
          value: value2
      {{- end }}
```
1. Is it right style to check tags "t1" enabled or not for the "T1_ENV" as it do not have example or usage in the document?
2. If I want to enabled "T1_ENV" in test chart and subchart1 chart at the same time, 
from my understanding, i should set "tags.t1=true" and "subchart1.tags.t1=true" at the same time.
Can I have a simple way just set one tag to enabled all "t1" tags in any level charts like the "global" values? 
  e.g  just set  "global.tags.t1=true" is fine

**Comment by mattfarina** [comment]
I can understand why this is confusing. The [docs on tags and conditions](https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags) need to be expanded.

Tags and conditions are special cases. For example,

```yaml
dependencies:
  - name: subchart1
    version: ~1.0.0
    repository: "https://test.com/chart-repo"
    condition: subchart1.enabled
    tags:
      - t1
```

In this case, the _subchart1_ won't be install into a cluster unless `subchart1.enabled` is set to true and the tag is listed and set to true in the _values.yaml_ file like the following:

```yaml
subchart1:
  enabled: true

tags:
  t1: true
```

These can also be passed through the command line.

Tags are not going to be passed to sub-charts. The structure of what is passed does not allow for that. I had not considered this situation until now.

Conditions can have their YAML structure passed to subcharts based on the location of the condition in the YAML.

Tags and conditions allow you to turn on and off dependencies as they are installed. They are usually used independently from each other but do not need to be. Conditions are processed before tags.

**Comment by hnlzq163** [comment]
Hi @mattfarina,
You're right, for simply usage we just use tag or condition.
But in many business scenarios it is not enough, we should use advance composition style, and it may be widely used in each company. 

We meet this issue,  so we just use the workaround, 
- use tags control the sub-charts, 
- and add a `global` value used in sub template
but we should keep both value aligned by manually.

But from coding craftmanship, we hope it can just use one value to control.
So I suggest you can consider to strengthen the tags function(support tags in sub charts), it would benefit the world. 
And we can keep the existing tag function and scope, and then extend it with new style.
Of course, if you don't mind, I can provide below 2 options:
**Option1** add a global section under tags(it may break the current code struct, should add `tags.global` pass to sub-chart along with `global` values):  
``` yaml
# source: test/values.yaml
tags:
  global: #add a global section
     t1: true
# source: test/requirements.yaml
dependencies:
  - name: subchart1
    version: ~1.0.0
    repository: "https://test.com/chart-repo"
    condition: subchart1.enabled
    tags:
      - global.t1    #should append prefix "global."
# source:  test/subchart1/deployment.yaml
apiVersion: apps/v1
kind: Deployment
template:
  spec:
    containers:
    - name: sub-container
      env:
      {{- if index .Values "tags" "global" "t1" }} # support parent global tags used in sub-charts
        - name T1_ENV
          value: value2
      {{- end }}
```

**Option2** add tags under `global`(it can reuse the global structure to pass value, just `tags` in requirement.yaml can handle and check `tags` under `global` section):
``` yaml
# source: test/values.yaml
global:
  tags: #add a tags section
     t1: true
# source: test/requirements.yaml
dependencies:
  - name: subchart1
    version: ~1.0.0
    repository: "https://test.com/chart-repo"
    condition: subchart1.enabled
    tags:
      - global.tags.t1   #should append prefix "global.tags."
# source:  test/subchart1/deployment.yaml
apiVersion: apps/v1
kind: Deployment
template:
  spec:
    containers:
    - name: sub-container
      env:
      {{- if index .Values "global" "tags" "t1" }}   # support parent global tags used in sub-charts
        - name T1_ENV
          value: value2
      {{- end }}
```
 
If you don't mind, and I also can try to create PR for it if you accept any option above.
Thanks.
