### ISSUE TITLE
Provide separate values files for charts in dependencies in Charts.yaml?

### ISSUE THREAD

**Issue by dev-samples** [helm/helm#9720]
Using helm 3.1.2 and k8s 1.15

I have this "umbrella" chart:

```
apiVersion: v1
description: Deploy Chart
name: my-app
version: 1.0.0

dependencies:

  - name: app-a
    repository: https://helm.repo.internal
    version: 1.0.103

  - name: app-b
    repository: https://helm.repo.internal
    version: 3.2.1
   # values: values/app-b.yaml  does not work :-(
```

Is it possible to specify a custom values file for each dependency?

I have found:
https://stackoverflow.com/questions/54770636/helm-chart-with-requirements-yaml-did-not-find-local-charts

but I cannot rely on the chart sources being in the same file tree as the umbrella chart.

I need to be able to install the binary release but provide a local values file.
