### ISSUE TITLE
Using the "tpl" function in a template disallows any template functions with quotes

### ISSUE THREAD

**Issue by davidmichaelkarr** [helm/helm#9732]
I've written a couple of different issues that show the key element of what our Helm process is doing.

This is a short excerpt from our "configmap.yaml":
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.msname_wr }}-configs
  namespace: {{ .Values.kube_namespace }}
data:
{{ tpl (.Files.Glob "configs/*").AsConfig . | indent 2 }}
```

In this "configs" directory, we have several Java properties files, and those files also have "{{}}"" references, like this:

```
redis.cluster.config={{.Values.redisconfigspath}}/redis.properties
```

This works fine.  However, if we instead change this reference to use particular template filter functions, like "default", then we get errors from Helm, like (not sure of the exact wording right now):

`Unexpected character: "\\\"`

I narrowed this down to the fact that the result of that "tpl" function is a structure like this:

```
data:
    system.properties: "........
```

As opposed to, perhaps:
```
data:
    system.properties: |
        ...
```

It appears that when a template function that uses quotes is referenced inside a quoted value, something gets confused about escape characters, resulting in an unparseable string.

So, it's not clear to me whether it's possible to change that "tpl" invocation phrase so that it uses the multi-line format, but it seems like that would at least give us the ability to use template functions that use quotes. I also don't know if doing that would have any unexpected consequences.

**Comment by mattfarina** [comment]
Do you have an example that could reproduce the problem? I'm unsure of how something like `default` would cause a situation like this and a test situation would help figure that out.

**Comment by davidmichaelkarr** [comment]
I am now attempting to recreate this, but I'm having trouble getting it to go into "quote mode".  I tried with an almost empty directory of config files, with just two files with a few simple properties, and it consistently uses the multiline character ("|") instead of generating a single quoted line. It seems like some characteristic of the sample data makes it decide to render them as quoted strings.  Any idea what might be doing that?

**Comment by davidmichaelkarr** [comment]
I've managed to reduce this to a much smaller test case.  I think there still are some unnecessary files, but the zip file is only 16kb, so I think that's small enough, and you should be able to demonstrate curious behavior just by editing one file in the zip file and rerunning the test script.

This sample has a "cmdline" script. You run it to run the test case. When you run it without change, it should produce "output/idpchart/templates/k8s/configmap.yaml".  Right now, that looks like this:

```
---
# Source: idpchart/templates/k8s/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: checkoutms-blue-configs
  namespace: com-att-idp
data:
  application.properties: "# needs to exactly match with configmap name for applicationcontext refresh upon configmap edit.\nserver.tomcat.max-connections=10000 \n"
```
Notice that it rendered the "application.properties" file as a quoted string. That doesn't demonstrate the error I was seeing, but it would lead to it if I referenced a "default" template function in the file.

You'll want to find the "application.properties" file and copy the current contents outside of this tree, or simply be prepared to undo changes to the file.

The current contents of that file is this:
```
# needs to exactly match with configmap name for applicationcontext refresh upon configmap edit.
server.tomcat.max-connections=10000 
```
If you remove the second line and then rerun the "cmdline", it will produce the "application.properties" entry in multiline mode, not quoted string. If you add the line back in and run it again, it will go back to a quoted string.

From this so far, you might think the issue has something to do with the size of the file.  It does not.  The way I got to this sample file was starting with the original "application.properties" file, which was a few hundred lines, and simply chopping off a block of lines at the end.  If it produced a multiline, I added the lines back and then removed a smaller set at the end.  I finally determined that it was that actual line, the setting of the "server.tomcat.max-connections" property, that puts it in quoted string mode.  I know that doesn't make any sense, I just know what I saw.  If I had that line in the file, no matter how large it was, it would produce a quoted string.  If I removed it, it would produce a multiline.
[quotesTestCase.zip](https://github.com/helm/helm/files/6542247/quotesTestCase.zip)
