### ISSUE TITLE
helm templating add empty line when using "nindent" in "define" bloc

### ISSUE THREAD

**Issue by antoineozenne** [helm/helm#9743]
Output of `helm version`:

```sh
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Output of `kubectl version`:

```sh
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:20:25Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

My `deployment.yaml`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  labels:
    app: foo
spec:
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      {{- include "pod" . | nindent 6 }}
```

My `_pod.tpl`:

```yaml
{{- define "pod" -}}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
serviceAccountName: foo
containers:
  - name: foo
    image: nginx:latest
{{- end }}
```

The result of `helm template foo/ --debug`:

```yaml
# Source: foo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  labels:
    app: foo
spec:
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      
      imagePullSecrets:
        - name: bar
      serviceAccountName: foo
      containers:
        - name: foo
          image: nginx:latest
```

There is an empty line after `spec.template.spec`. But if I swap `imagePullSecrets` and `serviceAccountName` in my `_pod.tpl`:

```yaml
{{- define "pod" -}}
serviceAccountName: foo
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
containers:
  - name: foo
    image: nginx:latest
{{- end }}
```

So there is no empty line in my generated `deployment.yaml`:

```yaml
# Source: foo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  labels:
    app: foo
spec:
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      serviceAccountName: foo
      imagePullSecrets:
        - name: bar
      containers:
        - name: foo
          image: nginx:latest
```

I would expect to have no empty line in both cases. Is this a bug or did I miss something?
