### ISSUE TITLE
Canonical way of using dynamic object names within values.yaml

### ISSUE THREAD

**Issue by thesobercoder** [helm/helm#9754]
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `Docker Desktop on Windows 10 1909`

I'm trying to build a chart, composed of other charts from Bitnami. Some of the values that I need to override are `ConfigMap` values. These `ConfigMap`s are named with best practices, which include generating the name dynamically using the release and chart name. I don't want to hard-code the `ConfigMap` name in the `values.yaml` file, because I'm generating the name using the `-g` flag during installation. It seems like template interpolation doesn't work in `values.yaml`. What is the canonical way of doing this then?

`Chart.yaml`

```
apiVersion: v2
name: mychart
description: My first helm chart
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: grafana
    version: 5.2.16
    repository: https://charts.bitnami.com/bitnami
```

`values.yaml`

```
grafana:
  replicaCount: 1
  config:
    useGrafanaIniFile: true
    grafanaIniConfigMap: "{{ .Release.Name }}-{{ .Chart.Name }}-grafana-config-map"
  admin:
    user: admin
    password: admin
```

`templates/grafana/grafana-config-map.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-grafana-config-map
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  grafana.ini: |-
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
    serve_from_sub_path = true
```

**Comment by bacongobbler** [comment]
Templates in a values.yaml is not supported for the reasons stated in https://github.com/helm/helm/issues/2492#issuecomment-413635332.

One way to accomplish this would be to generate your name beforehand, then inject that via the `--set` flag. https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set

I'm curious why you're concerned about hard-coding the name. Helm release names are unique to the namespace, so you cannot have two Helm releases named "foo" in the "bar" namespace. In other words, a ConfigMap named "foo" is a unique name and should be fine to use in 99% of most common use cases. Many of the charts available in ArtifactHub implement a similar pattern, and [this pattern is documented as such](https://helm.sh/docs/chart_template_guide/getting_started/#adding-a-simple-template-call):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  myvalue: "Hello World"
```

Hope that helps.
