### ISSUE TITLE
Not able to access file with subcharts

### ISSUE THREAD

**Issue by speedfl** [helm/helm#9767]
This is a followup of https://github.com/helm/helm/issues/1892.

Currently it is still not possible to access files from sub-charts.

This case is valid. Here is sample case:

From webserver chart I want to be able to mount config maps for custom modules (from sub-charts). 

```
{{- define "application.module-configmaps.1.yaml" -}}
{{- if .Values.server.modules.custom }}
{{- $files := .Files }}
{{- range .Values.server.modules.custom }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $.Values.global.componentName }}-module-{{ .name }}"
data:
{{ .name | indent 2 }}.module: |-
{{ $files.Get .path | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
```

Then in application which is using my dependency I have 2 custom modules:

```
- ping.module
- pong.module
```

I would in my values do:

```
global:
  componentName: my-component-name
parent:
    modules:
      custom:
        - name: ping
          path: path/to/my/module/ping.module
        - name: pong
          path: path/to/my/module/pong.module
```
As the modules has an extension (xml, py or whatever) I would like to be able to keep them editable without using a template.

Thanks in advance!

Regards
