### ISSUE TITLE
helm test should support Job

### ISSUE THREAD

**Issue by schollii** [helm/helm#9776]
Output of `helm version`:

2.17

Output of `kubectl version`:

1.18

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AWS with kops

It does not seem possible to define a helm test template to use a Job instead of a plain Pod: 

```
$ helm test RELEASE_NAME
Error: RELEASE_NAME is not a pod
```
The manifest in `tests` folder of chart: 
```
apiVersion: v1
kind: Job
metadata:
  name: {{ .Values.service.name }}-test
  annotations:
    "helm.sh/hook": test-success
spec:
  backoffLimit: 2
  completions: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .Values.service.name }}-test
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
```

A Job would give more control such as multiple retries, and seems more aligned with the kubernetes way of thinking about these types of tasks (such as running a test).
