### ISSUE TITLE
Helm 3.6 -  mapping values are not allowed in this context

### ISSUE THREAD

**Issue by Phaniharsha2908** [helm/helm#9786]
Hi Team,

when we run the following code we are getting the error **converting YAML to JSON: yaml: line 3: mapping values are not allowed in this context** with helm v3.6.0. whereas, the same code snippet working flawlessly with helm v2.7.0

```
{{- if eq (default "true" .Values.createVaultCluster | toString) "true" }}
{{- if lt (.Values.vaultClusterConfig.server.ha.replicas | int64 ) 2  -}}
{{ print "The grace period is the duration in seconds after the processes running in the pod are sent a termination signal and the time when the processes are forcibly halted with a kill signal. Set this value longer than the expected cleanup time for your process.Value must be non-negative integer. The value zero indicates delete immediately. Defaults to 30" }}
{{ end }}
apiVersion: vault.example.com/v1
kind: VaultCluster
metadata:
  name: {{ .Release.Name }}-vault
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
{{ .Values.vaultClusterConfig | toYaml | nindent 4}}
{{ end }}

```
Tried some variants – the mapping error is not showing up by adding the dash's ("-") in the end block on line 6 but line 7 is appending to the print statement as shown below, which leads to Kubernetes syntax error.

```
The grace period is the duration in seconds after the processes running in the pod are sent a termination signal and the time when the processes are forcibly halted with a kill signal. Set this value longer than the expected cleanup time for your process.Value must be non-negative integer. The value zero indicates delete immediately. Defaults to 30apiVersion: vault.example.com/v1
kind: VaultCluster
metadata:
  name: test-vault
  namespace: default

```

`helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```
 `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1400", GitCommit:"ec68c7064ea987ad0c7fb63930df96bdefeb93c4", GitTreeState:"clean", BuildDate:"2021-04-07T09:20:04Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform : GKE
