### ISSUE TITLE
first line indent 2 space then under line not indent will be ignore  in values file

### ISSUE THREAD

**Issue by wu0407** [helm/helm#9793]
I find some  unusual behavior use helm. If first line indent 2 space in values.yml file, then under lines with no indent are be ignored. 

Are these behaviors desirable ?

```
root@ip-10-2-0-172:~# cat values.yaml 
  kind: DaemonSet
  podLabels:
    es-index: traefik2-ingress-controller

additionalArguments:
  - "--providers.kubernetesingress.ingressclass=traefik2"
  - "--providers.kubernetescrd.ingressclass=traefik2"
  - "--entryPoints.web.forwardedHeaders.insecure"
  #- "--entryPoints.web.proxyProtocol.insecure"
  - "--api.insecure=true"
  - "--metrics.prometheus=true"
  - "--entryPoints.web.transport.lifeCycle.requestAcceptGraceTimeout=20"


root@ip-10-2-0-172:~# helm get values traefik2 -n kube-system
USER-SUPPLIED VALUES:
kind: DaemonSet
podLabels:
  es-index: traefik2-ingress-controller

```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
on permise
