### ISSUE TITLE
unsupported value: encountered a cycle via map[string]interface {} calling named template multiple times

### ISSUE THREAD

**Issue by sheisnicola** [helm/helm#9803]
Output of `helm version`: 

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

I have made a post elsewhere about this, but I wonder whether this might be a bug instead. https://stackoverflow.com/questions/67986019/helm-named-template-explodes-with-unsupported-value-encountered-a-cycle-via-ma

I receive a `helm.go:81: [debug] json: unsupported value: encountered a cycle via map[string]interface {}` error when calling a named template that does some interesting merges more than once. Strangely though the problem does not happen if I only call the named template once -- instead everything works as I would expect.

```
$ helm upgrade --install --namespace mergeproblem --debug mergeproblem ./mergeproblem/
history.go:56: [debug] getting history for release mergeproblem
upgrade.go:123: [debug] preparing upgrade for mergeproblem
upgrade.go:131: [debug] performing update for mergeproblem
upgrade.go:303: [debug] creating upgraded release for mergeproblem
Error: UPGRADE FAILED: create: failed to encode release "mergeproblem": json: unsupported value: encountered a cycle via map[string]interface {}
helm.go:81: [debug] json: unsupported value: encountered a cycle via map[string]interface {}
create: failed to encode release "mergeproblem"
helm.sh/helm/v3/pkg/storage/driver.(*Secrets).Create
	/private/tmp/helm-20210414-93729-197z3ms/pkg/storage/driver/secrets.go:156
helm.sh/helm/v3/pkg/storage.(*Storage).Create
	/private/tmp/helm-20210414-93729-197z3ms/pkg/storage/storage.go:69
helm.sh/helm/v3/pkg/action.(*Upgrade).performUpgrade
	/private/tmp/helm-20210414-93729-197z3ms/pkg/action/upgrade.go:304
helm.sh/helm/v3/pkg/action.(*Upgrade).Run
	/private/tmp/helm-20210414-93729-197z3ms/pkg/action/upgrade.go:132
main.newUpgradeCmd.func2
	/private/tmp/helm-20210414-93729-197z3ms/cmd/helm/upgrade.go:155
github.com/spf13/cobra.(*Command).execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/private/tmp/helm-20210414-93729-197z3ms/cmd/helm/helm.go:80
runtime.main
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/proc.go:225
runtime.goexit
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/asm_amd64.s:1371
UPGRADE FAILED
main.newUpgradeCmd.func2
	/private/tmp/helm-20210414-93729-197z3ms/cmd/helm/upgrade.go:157
github.com/spf13/cobra.(*Command).execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/private/tmp/helm-20210414-93729-197z3ms/cmd/helm/helm.go:80
runtime.main
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/proc.go:225
runtime.goexit
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/asm_amd64.s:1371
```

The example code in question is as follows:

```
{{- define "mergeproblem.configmap" -}}
{{- $ := index . 0 -}}
{{- $name := index . 2 -}}
{{- with index . 1 -}}
{{- $this := dict "Values" (get .Values $name) -}}
{{- $defaultRoot := dict "Values" (omit .Values $name) -}} 
{{- $noValues := omit . "Values" -}} 
{{- with merge $noValues $this $defaultRoot -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mergeproblem.fullname" . }}-{{ $name }}
  labels:
    {{- include "mergeproblem.labels" . | nindent 4 }}
data:
  MergeProblemExample: |
    Values: {{ .Values | toYaml | nindent 6 }}
    Template: {{ .Template | toYaml | nindent 6 }}
    Chart: {{ .Chart | toYaml | nindent 6 }}
    Release: {{ .Release | toYaml | nindent 6 }}
{{- end -}}
{{- end -}}
{{- end -}}
```

Calling is as so (working single invocation):

```
{{- template "mergeproblem.configmap" (list $ . "myfoo") -}}
```

or (broken multiple call invocation):

```
{{- template "mergeproblem.configmap" (list $ . "myfoo") -}}
{{- template "mergeproblem.configmap" (list $ . "yourbar") -}}
```

Example `values.yaml`:

```
########
#
# Component specifics
#

myfoo:
  image:
    repository: REPOSITORY-FROM-MYFOO-BLOCK
    tag: TAG-FROM-MYFOO-BLOCK
  autoscaling:
    minReplicas: 33

yourbar:
  image:
    repository: Repository-From-Yourbar-Block
    tag: Tag-From-Yourbar-Block



########
#
# Example defaults
#

replicaCount: 1

image:
  repository: default-repository-from-top-level-image-block
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "default-tag-from-top-level-image-block"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
```
