### ISSUE TITLE
Allow import-values to use all values from a sub chart

### ISSUE THREAD

**Issue by aemaem** [helm/helm#9817]
Currently it is not allowed to define import values with a dot `.` in order to use all values from a sub chart:
```
# parent's Chart.yaml file
dependencies:
  - name: subchart1
    repository: http://localhost:10191
    version: 0.1.0
    ...
    import-values:
      - child: .
        parent: myimports
```

This is especially useful for using values, which are at the root level of a sub chart:
```
# sub chart''s values.yaml file
myValue1: true
myValue2: "foo"
myValueN:
  foo: "1"
  bar: "false"
```
Since only table values can be used it is currently just possible to import the values `myValueN` as described in the [docs](https://helm.sh/docs/topics/charts/#importing-child-values-via-dependencies). When trying to import `myValue1` or `myValue2` a warning is shown: `dependencies.go:247: Warning: ImportValues missing table from chart subchart: "" is not a table`.

This issue relates to #2746.

**Comment by digihunch** [comment]
This feature would be very helpful when I want to organize values that are logically relevant. For example, both elasticsearch and kibana subcharts are related to logging, and I want properties for both managed under the group of logging. The values.yaml for parent would be:
```yaml
logging:
  enabled: true
  kibana:
    replicas: 2
  elasticsearch:
    replicas: 3
```

The Charts.yaml file at parent level reads:
```yaml
dependencies:
  - condition: logging.enabled
    name: kibana
    import-values:
      - child: .
        parent: logging.kibana

  - condition: logging.enabled
    name: elasticsearch
    import-values:
      - child: .
        parent: logging.elasticsearch
```

The values.yaml for kibana subchart:
```yaml
---
replicas: 1
property2: xyz
```

The values.yaml for elasticsearch subchart:
```yaml
---
replicas: 1
property2: xyz
```


Looking forward to the implementation.
