### ISSUE TITLE
helm dependency build fails when repo URL contains escaped 

### ISSUE THREAD

**Issue by sathieu** [helm/helm#9821]
With the following : `Chart.yaml`:

```yaml
apiVersion: v2
name: "gatekeeper"
version: 0.0.1
dependencies:
  - name: gatekeeper
    repository: https://gitlab.example.org/api/v4/projects/external-packages%2fgatekeeper/packages/helm/stable/
    version: 3.4.0
```

(the ending `/` is to workaround #9764).

`helm dependency build` failed exit status 1:

```
Error: could not download https://gitlab.example.org/api/v4/projects/external-packages/gatekeeper/packages/helm/stable/charts/gatekeeper-3.4.0.tgz:
failed to fetch https://gitlab.example.org/api/v4/projects/external-packages/gatekeeper/packages/helm/stable/charts/gatekeeper-3.4.0.tgz
```

As you can see, `%2` has been replaced by `/`.
