### ISSUE TITLE
Can't overwrite object from chart values.yaml

### ISSUE THREAD

**Issue by steffakasid** [helm/helm#9830]
Output of `helm version`:
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"dirty", GoVersion:"go1.16.5"}

Output of `kubectl version`:
not relevant pure templating issue

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
not relevant pure templating issue

Basically I've a chart which defines the following in it's values.yaml:
```
alertmanagerFiles:
  # Alertmanager configuration documentation: https://prometheus.io/docs/alerting/configuration/
  alertmanager.yml:
    key: value
```

If I now try to overwrite this with:
```
alertmanagerFiles: {}
```

This simply doesn't work. In my templates I still see (e.g. a ConfigMap):
```
alertmanagerFiles:
  # Alertmanager configuration documentation: https://prometheus.io/docs/alerting/configuration/
  alertmanager.yml:
    key: value
```

If I just remove the definition from the charts values.yaml Everything works as expected.

Based on the documentation I would expect it to be overwritten with the value I provide in my user values.yaml:

> The list above is in order of specificity: values.yaml is the default, which can be overridden by a parent chart's values.yaml, which can in turn be overridden by a user-supplied values file, which can in turn be overridden by --set parameters.

Do I oversee something or why can't I overwrite this object?

Regards
Steffen
