### ISSUE TITLE
Is it possible to use a subchart with different versions?

### ISSUE THREAD

**Issue by IlonkaO** [helm/helm#9849]
Output of `helm version`: version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

What I want to do:

I've created a parent chart which uses another Helm Chart as dependency. The dependency chart includes also image tags for every installation.
Now I have to stage my deployments and if the image tags change I change the dependency Helm Chart and create a new version of it. Actually the dependency Helm Chart resides as tarball in the chart folder of my parent chart. 

If I now try to reference the different versions for different values files in my parent chart always one version of the dependency chart is used. It is always the same independent using conditions and/or tags.

I'd expected, of I declare the different versions of my dependency chart in the Charts.yaml of my parent chart I could reference each version with different values files in my parent chart.

Structure of my parent chart
```
|- chart
  |-- Charts.yaml
  |-- values-develop.yaml
  |-- values-production.yaml
  |-- README.md
  |-- _helper.tpl
  |-- files
     |-- file_a
     |-- file_n
  |-- templates
     |-- deployment.yaml
     |-- ...
  |-- charts
     |-- subchart-0.1.0.tar.gz
     |-- subchart-0.1.1.tar.gz
```

Example of my Chart.yaml of the parent chart:

```yaml
apiVersion: v2
name: mandant-helm
description: Umbrella Chart für Deployment der nscale Mandanten

type: application

dependencies: # A list of the chart requirements (optional)
  - name: subchart
    version: 0.1.0
    condition: production.enabled
    tags:
      - production
  - name: subchart
    version: 0.1.1
    condition: develop.enabled
    tags:
      - develop

# This is the chart version. 
version: 0.1.0

# This is the version number of the application being deployed. 
appVersion: "0.1.0"

```

The first lines of my values-develop.yaml
```yaml
develop: 
  enabled: true
tags:
  develop: true

global:
....
```
And the values-production.yaml starts with:
```yaml
production: 
  enabled: true
tags:
  production: true

global:
....
```
Output from `helm template` is always the same.

Did I understand something wrong?
