### ISSUE TITLE
Helm3 PGRADE FAILED: pre-upgrade hooks failed

### ISSUE THREAD

**Issue by serg-bs** [helm/helm#9864]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Self hosted Vanila kubernetes

We have database migration which take about 3 hour.
```yaml 
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm.fullname" . }}-migration
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Values.version}}"
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-migration
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Values.version}}"
      annotations:
          version: {{ .Values.version | quote }}
    spec:
      containers:
        - name: migration
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - /commands/migrations.sh
          envFrom:
            - secretRef:
                name: {{ include "helm.secretName" . }}
            - configMapRef:
                name: {{ include "helm.fullname" . }}
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm.secretName" . }}
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm.secretName" . }}
                  key: mysql-root-password
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          {{- if .Values.extraVolumeMounts }}
          {{- .Values.extraVolumeMounts| toYaml | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.extraVolumes }}
        {{- .Values.extraVolumes| toYaml | nindent 8 }}
        {{- end }}
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
```
I run it with command
```
helm upgrade --install my-release --timeout=24h
```
But after 1 hour get 
```
Error: UPGRADE FAILED: pre-upgrade hooks failed: failed to deploy itf-migration
```
Expected:
helm should wait until pre install hook complete.
