### ISSUE TITLE
Helm can't save local requirements as TAR

### ISSUE THREAD

**Issue by rstoermer** [helm/helm#9866]
Output of `helm version`: version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"dirty", GoVersion:"go1.16.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Docker-Desktop

I got the following Chart.yaml:

```
apiVersion: v2
name: nextor-dependencies
description: Helm chart to install nextor dependencies
type: application
version: 2020_06_2
dependencies:
- name: ingress-nginx
  version: 3.29.0
  repository: https://kubernetes.github.io/ingress-nginx
  condition: install.ingress-nginx
- name: nextor-logging
  version: 0.1.0
  repository: "file://charts/logging"
  condition: install.nextor-logging
- name: nextor-rbac
  version: 0.1.0
  repository: "file://charts/rbac"
  condition: install.nextor-rbac
``` 

 When doing a  `helm dependency update` I get: 
```
❯ helm dependency update --debug
Repository from local path: file://./charts/logging
Repository from local path: file://./charts/rbac
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://kubernetes.github.io/ingress-nginx" chart repository
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jertel" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Downloading ingress-nginx from repo https://kubernetes.github.io/ingress-nginx
Archiving nextor-logging from repo file://./charts/logging
Save error occurred:  directory charts/logging not found
Deleting newly downloaded charts, restoring pre-update state
Error: directory charts/logging not found
helm.go:81: [debug] directory charts/logging not found
helm.sh/helm/v3/internal/resolver.GetLocalPath
        helm.sh/helm/v3/internal/resolver/resolver.go:219
helm.sh/helm/v3/pkg/downloader.tarFromLocalDir
        helm.sh/helm/v3/pkg/downloader/manager.go:837
helm.sh/helm/v3/pkg/downloader.(*Manager).downloadAll
        helm.sh/helm/v3/pkg/downloader/manager.go:302
helm.sh/helm/v3/pkg/downloader.(*Manager).Update
        helm.sh/helm/v3/pkg/downloader/manager.go:201
main.newDependencyUpdateCmd.func1
        helm.sh/helm/v3/cmd/helm/dependency_update.go:74
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:80
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
```

The Chart.yaml of logging is:
```
apiVersion: v2
name: nextor-logging
description: Helm chart to install logging stack
type: application
version: 0.1.0
```

I also tried to switch around the path from file://charts/logging to file://./charts/logging and nothing helped. Curiously, when I switch the path to something that really doesn't exist I get, so HELM finds _something_: 

```
helm dependency update --debug
Error: directory charts/notexists not found
helm.go:81: [debug] directory charts/notexists not found
helm.sh/helm/v3/internal/resolver.GetLocalPath
        helm.sh/helm/v3/internal/resolver/resolver.go:219
helm.sh/helm/v3/pkg/downloader.(*Manager).resolveRepoNames
        helm.sh/helm/v3/pkg/downloader/manager.go:565
helm.sh/helm/v3/pkg/downloader.(*Manager).Update
        helm.sh/helm/v3/pkg/downloader/manager.go:168
main.newDependencyUpdateCmd.func1
        helm.sh/helm/v3/cmd/helm/dependency_update.go:74
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:80
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
```
