### ISSUE TITLE
[feature] 401 Unauthorized for dependency build when use repository with basic authentication

### ISSUE THREAD

**Issue by lyzhang1999** [helm/helm#9874]
Output of `helm version`:

version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"dirty", GoVersion:"go1.16.5"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Minikube

Bug：

helm dependency build now is not support dependencies repository URL with basic authentication.

here I have helm chart in Git Repo: https://codingcorp.coding.net/public/wangwei_test_cd/bookinfo/git.

Chart.yaml:

```
apiVersion: v1
appVersion: "1.3"
description: Nocalhost Bookinfo Helm chart for Kubernetes
name: nocalhost-bookinfo
version: 1.2.2

dependencies:
  - name: nocalhost-rattings
    version: 1.2.2
    repository: "https://helm-1624626656778:c7df48d7408f1b692ca85f26ff1d98946f7fc7dd@codingcorp-helm.pkg.coding.net/wangwei_test_cd/helm"
```

when I use `helm dependency build`, get error:

```
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://helm-1624626656778:c7df48d7408f1b692ca85f26ff1d98946f7fc7dd@codingcorp-helm.pkg.coding.net/wangwei_test_cd/helm" chart repository
Saving 1 charts
Downloading nocalhost-rattings from repo https://helm-1624626656778:c7df48d7408f1b692ca85f26ff1d98946f7fc7dd@codingcorp-helm.pkg.coding.net/wangwei_test_cd/helm
Save error occurred:  could not download https://codingcorp-helm.pkg.coding.net/wangwei_test_cd/helm/nocalhost-rattings/nocalhost-rattings-1.2.2.tgz: failed to fetch https://codingcorp-helm.pkg.coding.net/wangwei_test_cd/helm/nocalhost-rattings/nocalhost-rattings-1.2.2.tgz : 401 Unauthorized
Deleting newly downloaded charts, restoring pre-update state
Error: could not download https://codingcorp-helm.pkg.coding.net/wangwei_test_cd/helm/nocalhost-rattings/nocalhost-rattings-1.2.2.tgz: failed to fetch https://codingcorp-helm.pkg.coding.net/wangwei_test_cd/helm/nocalhost-rattings/nocalhost-rattings-1.2.2.tgz : 401 Unauthorized
```

hope is when repository have basic authentication info, then should use it for helm dependency chart download.

and I create PR to fix it: https://github.com/helm/helm/pull/9867

**Comment by lyzhang1999** [comment]
@Matthew Fisher

**Comment by bacongobbler** [comment]
Putting the username and password in the URL isn't usually a good idea. There are places where Helm displays the URL and the username and password would then be displayed. So, this is discouraged in general. We don't want to accidentally log credentials, for example.

The recommended solution is to use the `--username` and `--password` fields with `helm repo add` instead. Then you can reference the repository as

```
dependencies:
  - name: nocalhost-rattings
    version: 1.2.2
    repository: "https://codingcorp-helm.pkg.coding.net/wangwei_test_cd/helm"
```

To add the repository to your list, you would use `helm repo add coding-net https://codingcorp-helm.pkg.coding.net/wangwei_test_cd/helm --username myuser`. It will then prompt for your password.

Hope this helps.
