### ISSUE TITLE
helm v3 init creates invalid image name.

### ISSUE THREAD

**Issue by zzzz465** [helm/helm#9895]
Output of `helm version`: v3.5

Output of `kubectl version`: Client v1.21, Server v1.20+

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

helm init creates pod and it fails with `InvalidImageName`.

```yaml
# values.yaml
image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
```

helm init creates default nginx image with `tag: ""` which creates pod yaml below.
```yaml
# $ kubectl get pod $POD_NAME --output yaml > error.yaml
spec:
  containers:
  - image: 'nginx:'
    imagePullPolicy: IfNotPresent
# ... additional codes here
```
and image name `nginx:` is not valid.
after changing `tag: ""` to `tag: "latest"` in values.yaml, it works however.
