### ISSUE TITLE
range in child Helm Chart needs more than one entry in parent Helm Chart

### ISSUE THREAD

**Issue by IlonkaO** [helm/helm#9896]
Output of `helm version`: version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

Output of `kubectl version`: Kubernetes Version: v1.19.0+9c69bdc

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  OpenShift 4.6

Description:
I have created a child Helm Chart where I create a number of PVCs. In the values file I use a list entry:
```yaml
module:
...
  pvc:
  - name: blabla
    access: ReadWriteMany
    storageClass: nfs
    size: 1G
    mountPath: /somewhere
```  
pvc template:
```yaml
{{- if .Values.module.pvc }}
{{range $pvc := .Values.module.pvc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvc.name }}
  labels:
    {{- include "nscale.labels" $ | nindent 4 }}
    {{- with $.Values.module.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  - {{ $pvc.access }}
  resources:
    requests:
      storage: {{ $pvc.size }}
  storageClassName: {{ $pvc.storageClass }}
{{- end }}
{{- end }}
```
Executing `helm template` on this child Helm Chart is successful independent of the number of defined PVCs. It also works with one PVC declaration.

Now I'm using this child Helm Chart as a dependency in a parent Helm Chart. I do nothing with the values for the PVC in this Helm Chart. The dependency chart resides as a fresh created .tar.gz in the _/charts_ directory in the parent Helm Chart. I've tried different _values.yaml_ from the parent chart:

- I didin't fill in any information about the module with mentioned pvcs above
- I filled in the same values like in the child chart values.yaml
 
Every time I get error message executing `helm template`

```bash
coalesce.go:203: warning: destination for pvc is a table. Ignoring non-table value [map[access:ReadWriteMany mountPath:/somewhere name:blabla size:1G storageClass:nfs]]

Error: template: parent-helm/charts/child-helm/templates/module/pvc.yaml:7:15: executing "parent-helm/charts/child-helm/templates/module/pvc.yaml" at <$pvc.name>: can't evaluate field name in type interface {}

Use --debug flag to render out invalid YAML
```

Actually after add a **second** PVC declaration in the parent _values.yaml_ the parent chart now works and sometimes I only get warnings like this:

```bash
coalesce.go:200: warning: cannot overwrite table with non table for pvc (map[claims:[map[access:ReadWriteMany name:blabla size:1G storageClass:nfs]] enabled:true])
```

My challenge now is, that I actually don't need 2 PVCs. But with only one declaration the parent Helm Chart doesn't work.

Any suggestions?

Thanks for your support
