### ISSUE TITLE
Move dependency to be independent

### ISSUE THREAD

**Issue by mosheavni** [helm/helm#9908]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Amazon EKS

Is there any way to manage a dependency chart as individual?
For example, I'm installing a chart called `production-baseline` with `Chart.yaml`:
```
apiVersion: v2
appVersion: "1.0"
description: A baseline Helm chart for production
name: production-baseline
version: 0.1.2

dependencies:
- name: aws-load-balancer-controller
  version: 1.1.4
  repository: https://aws.github.io/eks-charts
- name: cluster-autoscaler
  version: 9.9.2
  repository: https://kubernetes.github.io/autoscaler
```
Now I want to manage `aws-load-balancer-controller` and `cluster-autoscaler` independent of `production-baseline`, as their own charts, but without removing them first, maintaining the same deployment, same resources.
Is that possible?
Thanks.
