### ISSUE TITLE
did not find expected alphabetic or numeric character for list in list

### ISSUE THREAD

**Issue by safredAAs** [helm/helm#9917]
Hello everyone!

I'm currently struggeling to iterate over my list nested in another list!

This is my values.yaml
```
application:
  domains:
    google-de:
      domain: google.de
      aliases:
        - www.google.de
        - "*.google.de"
      redirectDomain: https://github.com/helm/helm
    bing-de:
      domain: bing.de
      aliases:
        - www.bing.de
        - "*.bing.de"
      redirectDomain: https://github.com/helm/helm
```

In my virtualservice yaml, I want to loop over that list to generate the hosts list on which the virtualservice shoud listen:

```
spec:
  hosts:
{{- range $key, $value := .Values.application.domains }}
    -{{ $value.domain }}
  {{- range $key, $valAl := $value.aliases }}
    -{{ $valAl }}
  {{- end }}
{{- end }}
```

That works so far, Output:

```
spec:
  hosts:
    -bing.de
    -www.bing.de
    -*.bing.de
    -google.de
    -www.google.de
    -*.google.de
```

But for it to work inside the kube cluster, a whitespace as to be added between each dash and the value:

```
spec:
  hosts:
{{- range $key, $value := .Values.application.domains }}
    - {{ $value.domain }}
  {{- range $key, $valAl := $value.aliases }}
    - {{ $valAl }}
  {{- end }}
{{- end }}
```

This produces:
`error converting YAML to JSON: yaml: line 14: did not find expected alphabetic or numeric character`

Can you please point me to the issue and how to solve it?

Thanks!

Best Regards

**Comment by mattfarina** [comment]
The issue has to do with the yaml. Take the generated YAML output you have and put it into a YAML validator. Massage it to what it should be and you'll find it's not valid YAML. This is because of the `*` character.

The `*` is used as part of the anchors and aliases feature in YAML. So, the parser found that character when it did not expect to.

What you need to do is wrap the strings in quotes. This will cause the parser to see it as a string and not try to figure out what it is.

**Comment by glensc** [comment]
Faced the same issue, very difficult to understand from error message what is wrong, came to conclusion with elimination process and found that the helm values first char was "*", as some wildcard DNS was the value.

so, to answer the OP, the fragment needs to be:

```yaml
spec:
  hosts:
{{- range $key, $value := .Values.application.domains }}
    - "{{ $value.domain }}"
  {{- range $key, $valAl := $value.aliases }}
    - "{{ $valAl }}"
  {{- end }}
{{- end }}
```
