### ISSUE TITLE
feature: Use packaged subcharts without external repository

### ISSUE THREAD

**Issue by scalen** [helm/helm#9928]
`helm version`:
```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

## Problem

I have an umbrella chart containing multiple private microservice subcharts.  I want to define these Subcharts beside their respective micro services, but then vendor them with the umbrella chart.  To this end, I want to store the packaged Subcharts in the umbrella chart, where they can be versioned.

However, as in the example below, Helm only seems to expect Subcharts in unpackaged form when no repository is specified.  The same is true when using the `file://` repository protocol to identify the package explicitly.

### Example: Setup
```
umbrella-chart
|-- Chart.yaml
|-- values.yaml
|-- charts
    |-- microservice1-chart-1.0.0.tgz
    |-- microservice2-chart-1.0.0.tgz
```
umbrella-chart/Chart.yaml
```
apiVersion: v2
name: umbrella
description: A test umbrella
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
- name: microservice1
  chart: microservice1
  version: ^1.0.0
- name: microservice2
  chart: microservice2
  version: ^1.0.0
```
### Example: Result
```bash
> helm dependency update umbrella-chart
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: directory umbrella-chart/charts/microservice1 not found
> echo $?
1
```
### Expected
```bash
> helm dependency update umbrella-chart
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
> echo $?
0
```

**Comment by mattfarina** [comment]
`dependencies` is the place to specify all of the charts dependencies. Helm has dependency management capabilities where it can pull in updates from a repository or location on disk for a chart (i.e., using `file://`). When no repository is specified Helm cannot perform dependency management because it has no location to get packages or metadata from. When no repository is specified Helm expects the sub-charts to be in the `charts` directory in either directory or archive form. If the chart is not in the `charts` directory and there is no repository specified, Helm reports an error because of the missing dependency.

**Comment by scalen** [comment]
Hi @mattfarina

If I may list out the above in a more structured form?

1.  Chart dependencies should be listed in `dependencies`.
2. Depending on the specification of a `repository` in a given `dependency`:
  a. With a `repository`: Helm can pull in updates from remote repositories (or the local filesystem, using `file://`).
  b. Without a `repository`: Helm cannot perform dependency management, and will expect Subcharts present in`dependencies` to be present in `charts` as either subdirectories or archives.

In my example above, we have `dependencies` listed as specified in 1, unmanaged as per 2.b.  These dependencies are present in the `charts` directory as archives matching the name and version spec from `dependencies`.

Based on your response, I would therefore expect `helm dependency update` to ignore the unmanaged subcharts and exit cleanly.

However, it exits with an error message and (more importantly for a CD pipeline) an error exit code.  Based on your description above, this is a bug, yes?

**Comment by scalen** [comment]
As a note:  In the real-world example, the umbrella chart also contains 3rd party charts that do need updating from remote repositories, hence requiring `helm dependency update`.  Furthermore, our CD pipeline needs to know whether the `dependency update` worked in order to know whether to try upgrading the release.

I only included the minimal reproducing example in my OP.

**Comment by scalen** [comment]
For the record, I also tried the below setup using option 2.a:

### Example: Setup
```
umbrella-chart
|-- Chart.yaml
|-- values.yaml
charts
|-- microservice1-chart-1.0.0.tgz
|-- microservice2-chart-1.0.0.tgz
```
umbrella-chart/Chart.yaml
```
apiVersion: v2
name: umbrella
description: A test umbrella
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
- name: microservice1
  chart: microservice1
  version: ^1.0.0
  repository: file://../chart/microservice1-1.0.0.tgz
- name: microservice2
  chart: microservice2
  version: ^1.0.0
  repository: file://../chart/microservice2-1.0.0.tgz
```
### Example: Result
```bash
> helm dependency update umbrella-chart
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: Chart.yaml file is missing
> echo $?
1
> ls umbrella-chart/charts

```
### Expected
```bash
> helm dependency update umbrella-chart
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
> echo $?
0
> ls umbrella-chart/charts
microservice1-1.0.0.tgz        microservice2-1.0.0.tgz
```
