### ISSUE TITLE
Value files precedence behaviour changes when custom values file is used

### ISSUE THREAD

**Issue by ankitabhopatkar13** [helm/helm#9940]
Edit: The issue can be reproduced and outputs can be seen here - https://github.com/ankitabhopatkar13/helm-values-issue

Output of `helm version`: `version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"dirty", GoVersion:"go1.16.5"}`

I have 3 kind of charts -

- Library Chart
- App Chart (Uses Library Chart as dependecy)
- Umbrella Chart (Has all the app charts as dependencies)

Library chart has value structure like -
----- templates/
----- values.yaml
```
- exports:
     service:
       type: ClusterIP
       port: 9090
```

App Chart has value structure like -
----- templates/
----- values.yaml
```
service:
  type: ClusterIP
  port: 1234
```

Umbrella Chart has value structure like -
----- values/
------- aws/
--------- test.yaml
--------- accp.yaml
              
`helm upgrade --install release release --values aws/test.yaml`, the service port is still used as 9090 and not 1234.

But if I don't pass the custom values file and just use values.yaml in the umbrella chart, the port is getting set to 1234 which is what should be the case even when custom values file(test.yaml) is used.

**Comment by yxxhero** [comment]
@ankitabhopatkar13 Please show the content of `aws/test.yaml` and `aws/accp.yaml`. thanks very much.

**Comment by ankitabhopatkar13** [comment]
Thanks for the reply @yxxhero

`aws/test.yaml` contains the key values like -

```
global:
  environment: test

subchart:
  enabed: true
  image:
    tag: "0.0.1"
```

It has nothing regarding the service or it's port.

`aws/accp.yaml` doesn't have anything yet and is also not used during the helm deployment.

**Comment by mattfarina** [comment]
This is both a rare and good question. When it comes to handling `exports` the code is [here](https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/chartutil/dependencies.go#L219-L274). The docs on `exports` can be found [here](https://helm.sh/docs/topics/charts/#using-the-exports-format).

@ankitabhopatkar13 Can you provide the `dependencies` section of your app chart? Is there an `imports` section?

**Comment by ankitabhopatkar13** [comment]
Yes, the dependencies section of the app chart does have an imports section.

The library chart has exports as defaults like -

```
- exports:
     defaults:
       service:
         type: ClusterIP
         port: 9090
```

And the app chart uses them like -

```
dependencies:
- name: lib-chart
  version: 0.1.0
  repository: path_to_repo
  import-values:
    - defaults
```

Just to elaborate a bit -

The precedence is only getting changed when a values file is passed with `--values` flag while installing the Umbrella chart. But if there is no `--values` flag and when the values are getting read from default `values.yaml` file, the precedence works just fine.

`helm upgrade --install release release --values aws/test.yaml` -----> exported values from library chart takes precedence over app chart values.

`helm upgrade --install release release` -----> app chart values take precedence over library chart values(which is what seems the right order).
