### ISSUE TITLE
When using the `default` in the template, must there be a key in the values?

### ISSUE THREAD

**Issue by YuzeZhang** [helm/helm#9953]
Output of `helm version`:
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}

When I using `helm template` like this:
xxx.template.json:
```json
{
  "foo": {
    "bar": "{{ default `aaa` .Values.foo.bar }}"
  }
}
```

values-xxx.yaml:
```yaml
foo:
  bar:
```
It worked fine and will render out:
```json
{
  "foo": {
    "bar": "aaa"
  }
}
```

But if I remove the key(foo & bar) in values-xxx.yaml, I get an error:
```
Error: template: my-path/xxx.template.json:80:76: executing "my-path/xxx.template.json" at <.Values.foo.bar>: nil pointer evaluating interface {}.bar
helm.go:81: [debug] template: my-path/xxx.template.json:80:76: executing "my-path/xxx.template.json" at <.Values.foo.bar>: nil pointer evaluating interface {}.bar
```
Is there a way to solve this problem?

I think it's weird to write useless keys in values.

**Comment by hickeyma** [comment]
@YuzeZhang When using nested values, it is recommended to check that values exist to avoid this issue. 

Something similar to this:

```yaml
{{ if .Values.foo }}
  {{ default "aaa" .Values.foo.bar }}
{{ end }}
```

Check out [Flat or Nested Values](https://helm.sh/docs/chart_best_practices/values/#flat-or-nested-values) for more details.

**Comment by YuzeZhang** [comment]
> @YuzeZhang When using nested values, it is recommended to check that values exist to avoid this issue.
> 
> Something similar to this:
> 
> ```yaml
> {{ if .Values.foo }}
>   {{ default "aaa" .Values.foo.bar }}
> {{ end }}
> ```
> 
> Check out [Flat or Nested Values](https://helm.sh/docs/chart_best_practices/values/#flat-or-nested-values) for more details.

@hickeyma I tried this way and it looks like I still need to add the corresponding key to the values, otherwise I get the same `nil pointer evaluating interface {}.bar` error

Could you please tell me how I can write the template in this case so that I can render the default result with empty values file (without the key `foo` and `bar`) and not report an error?

**Comment by hickeyma** [comment]
@YuzeZhang Maybe it is something in your template file? 

As an example, here is a sample template file:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favoriteDrink }}
  {{ if .Values.service }}
  port: {{ .Values.service.port }}
  {{ end }}
  {{ if .Values.foo }}
  bar: {{ default "aaa" .Values.foo.bar }}
  {{ end }}
```

and values file:

```yaml
service:
  port: 80

foo:
  bar: 

favoriteDrink: coffee
```

I can disable `foo` or `service` and the template will still render:

```console
$ cat issue-9953/values.yaml

service:
  port: 80

#foo:
#  bar: 

favoriteDrink: coffee

$ helm install issue-9953 issue-9953 --dry-run --debug

install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: helm/charts/issue-9953

NAME: issue-9953
LAST DEPLOYED: Thu Jul 22 07:05:36 2021
NAMESPACE: helm-test
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
favoriteDrink: coffee
service:
  port: 80

HOOKS:
MANIFEST:
---
# Source: issue-9953/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: issue-9953-configmap
data:
  myvalue: "Hello World"
  drink: coffee
  
  port: 80
```

**Comment by hickeyma** [comment]
@YuzeZhang Did you get time to try out the suggestion in https://github.com/helm/helm/issues/9953#issuecomment-884677623?

**Comment by YuzeZhang** [comment]
> apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favoriteDrink }}
  {{ if .Values.service }}
  port: {{ .Values.service.port }}
  {{ end }}
  {{ if .Values.foo }}
  bar: {{ default "aaa" .Values.foo.bar }}
  {{ end }}

@hickeyma I understand your approach to this, but my need is to disable `foo` and `bar` in values and still have the default `aaa` in the rendered result, not have `bar` not exist in the rendered result.

My ideal values-1.yaml:
```
service:
  port: 80

foo:
  bar: bbb

favoriteDrink: coffee
```

My ideal result-1:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: issue-9953-configmap
data:
  myvalue: "Hello World"
  drink: coffee
  
  port: 80
foo:
  bar: bbb
```

My ideal values-2.yaml:
```
service:
  port: 80

#foo:
  #bar: bbb

favoriteDrink: coffee
```

My ideal result-2:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: issue-9953-configmap
data:
  myvalue: "Hello World"
  drink: coffee
  
  port: 80
foo:
  bar: aaa
```

So how can I write a template in this case?
