### ISSUE TITLE
helm upgrade with tests fail when --atomic flag is set

### ISSUE THREAD

**Issue by Zeltserj** [helm/helm#9959]
Hi,
I have a chart and a test container (put in `templates/tests/test.yaml`), which looks like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-test"
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: {{ .Release.Name }}-test
      image: busybox
      command: ["echo","hello, world!"]
  restartPolicy: Never
```
My command:
```
helm upgrade my-release my-chart --atomic 
```

I see that the pod `my-release-test` is Completed, and therefore helm waits for it to be Ready, which does not happen until timeout, and the the upgrade rolls back.
 
running `helm upgrade my-release my-chart && helm test my-release` works.

I think the correct behavior should be that `--atomic` should only fail if the test pod failed.

helm version:
```
version.BuildInfo{Version:"v3.3", GitCommit:"", GitTreeState:"", GoVersion:"go1.14.2"}
```
