### ISSUE TITLE
Chart.lock / bundled dependencies not used with remote chart repositories

### ISSUE THREAD

**Issue by travisgroth** [helm/helm#9962]
Output of `helm version`: `version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:23:45Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Docker Desktop, GKE

It appears that dependencies built with `Chart.lock` and placed into the `charts/` directory of a chart have different behavior depending on whether the chart is from a remote repository or a local file.  This seems like a bug.

I would expect `Chart.lock` and and a matching chart tarball in `charts/` to be honored regardless of how the chart is installed.

Reproduction - using an off the shelf chart that I'm familiar with:

### Remote

```bash
helm repo add pomerium https://helm.pomerium.io
helm install pomerium pomerium/pomerium --set redis.enabled=true
kubectl get pods pomerium-redis-master-0 -o jsonpath='{.metadata.labels.helm\.sh/chart}'
```

Result: `redis-14.7.2`

### Local

```bash
git clone git@github.com:pomerium/pomerium-helm.git
helm install pomerium pomerium-helm/charts/pomerium --set redis.enabled=true
kubectl get pods pomerium-redis-master-0 -o jsonpath='{.metadata.labels.chart}'
````

Result: `redis-13.0.1`

### `Chart.lock`

```yaml
dependencies:
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 13.0.1
digest: sha256:958cb986704578954e4cce8a87eca611ae037a291ef106c6cd694727b9982b95
generated: "2021-04-14T10:52:12.914773446-05:00"
```

### `Chart.yaml`

```yaml
dependencies:
- name: redis
  version: ">= 10.9.0"
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
```

I recognize the version in `Chart.yaml` match allows for a newer redis chart version but, based on the docs, I'd expect `Chart.lock` and the contained `charts/` to be what is used for consistency, if nothing else.
