### ISSUE TITLE
How to escape the content of go template contained in configmap to keep raw data

### ISSUE THREAD

**Issue by nic-chen** [helm/helm#9963]
Hi, here is an example yaml, please have a look. Thanks!

```yaml
apiVersion: v1
data:
  alert-rules.yaml.tmpl: |
    groups:
    - name: alert-rules
      rules:
    {{range $alarm := gets "/alarm/*"}}
    {{$alarmJson := json $alarm.Value}}
    {{range $alarmJson.rules}}
      - alert: {{$alarmJson.name}}
        expr: {{.expr}}
        labels:
          alarm: "{{$alarmJson.id}}"
          condition: "{{.metric}}{{.operator}}{{.value}}"
        annotations:
          summary: {{$alarmJson.message}}
          description: {{$alarmJson.message}}
    {{end}}
    {{end}}

kind: ConfigMap
metadata:
  name: rules-tmpl
  namespace: test
```
