### ISSUE TITLE
Namespace labeling fails

### ISSUE THREAD

**Issue by i3oc9i** [helm/helm#9965]
Output of `helm version`: v3.5.4

Output of `kubectl version`:  1.21

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

Description:
We need to add a label to a namespace. To do that we create a namespace template in our chart
```
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Release.Namespace }}
  labels: 
    project: hello
 ```

Then we install the chart using the command:

```
helm upgrade  --install  --create-namespace -n hello hello ./helm
```

The deployment fails the first run when the namespace does not exist inside the cluster. 

```
Release "hello" does not exist. Installing it now.
Error: namespaces "hello" already exists
```

NOTE: If the namespace `hello` exist the deployment succeeds.
