### ISSUE TITLE
bug: template & lint fails on charts with name matching one of the dependencies, unless sub-chart is extracted

### ISSUE THREAD

**Issue by anapsix** [helm/helm#9976]
When parent chart name matches the name of one of the charts from dependencies, Helm gets upset during `template / install / lint` if TGZ files retrieved with `helm dep update` are not unpacked (for the namesake sub-charts).

```yaml
# Chart.yaml
apiVersion: v2
type: application
name: kafka
description: Helm chart for a very old version of Kafka 
version: 0.2.0
appVersion: 0.8.2
dependencies:
- name: zookeeper
  version: "7.0.8"
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.install
- name: kafka
  alias: kafka2
  version: "13.0.4"
  repository: https://charts.bitnami.com/bitnami
  condition: kafka2.install
```

When running `helm template` (similar output for `helm install`):
```sh
helm template -n my-namespace my-release . | grep "Source: "
Error: found in Chart.yaml, but missing in charts/ directory: kafka
```

And for `helm lint`:
```sh
❯ helm lint  .
==> Linting .
[WARNING] ~/helm-charts/kafka: chart directory is missing these dependencies: kafka
1 chart(s) linted, 0 chart(s) failed

❯ helm lint --with-subcharts .
==> Linting .
[WARNING] ~/helm-charts/kafka: chart directory is missing these dependencies: kafka
==> Linting charts/kafka-13.0.4.tgz
==> Linting charts/zookeeper-7.0.8.tgz
3 chart(s) linted, 0 chart(s) failed
```

But after unpacking `bitnami/kafka` chart with `tar -C ./charts -xf ./charts/kafka-13.0.4.tgz`, it's happy as a clam:

Template now succeeds:
```sh
❯ helm template -n my-namespace my-release . | grep "Source: "
# Source: kafka/charts/zookeeper/templates/poddisruptionbudget.yaml
# Source: kafka/charts/kafka2/templates/serviceaccount.yaml
# Source: kafka/charts/kafka2/templates/scripts-configmap.yaml
# Source: kafka/charts/kafka2/templates/svc-headless.yaml
# Source: kafka/charts/kafka2/templates/svc.yaml
# Source: kafka/charts/zookeeper/templates/svc-headless.yaml
# Source: kafka/charts/zookeeper/templates/svc.yaml
# Source: kafka/templates/kafka2-rest-service.yaml
# Source: kafka/templates/service.yaml
# Source: kafka/templates/kafka2-rest-deployment.yaml
# Source: kafka/charts/kafka2/templates/statefulset.yaml
# Source: kafka/charts/zookeeper/templates/statefulset.yaml
# Source: kafka/templates/statefulset.yaml
# Source: kafka/templates/tests/test-connection.yaml
```

Lint succeeds as well:
```sh
❯ helm lint -n my-namespace .
==> Linting .
1 chart(s) linted, 0 chart(s) failed

❯ helm lint --with-subcharts .
==> Linting .
==> Linting charts/kafka
==> Linting charts/kafka/charts/common
==> Linting charts/kafka/charts/zookeeper
==> Linting charts/kafka/charts/zookeeper/charts/common
==> Linting charts/kafka-13.0.4.tgz
==> Linting charts/zookeeper-7.0.8.tgz
7 chart(s) linted, 0 chart(s) failed
```

While I'm not necessarily saying having parent chart name match one of the sub-chart names is a particularly great.. nonetheless, this Helm behavior is unexpected, and seemingly erroneous.

Output of `helm version`: `v3.6.3 / d506314abfb5d21419df8c7e7e68012379db2354`
Output of `kubectl version`:  `v1.21.1`
Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

**Comment by anapsix** [comment]
eh.. It might have nothing to do with chart name matching the sub-chart dependency name..
renamed by top level chart to `kafka-provisioner` and still getting same error
```yaml
# Chart.yaml
apiVersion: v2
type: application
name: kafka-provisioner
description: Helm chart for Kafka
version: 0.2.0
appVersion: 0.8.2
dependencies:
- name: zookeeper
  version: "7.0.8"
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.install
- name: kafka
  alias: kafka2
  version: "13.0.4"
  repository: https://charts.bitnami.com/bitnami
  condition: kafka2.install
```

```sh
❯ helm template -n my-namespace my-release . | grep "Source: "
Error: found in Chart.yaml, but missing in charts/ directory: kafka
```

I'm a bit lost on where did I go wrong.. will update when I have more details.
