### ISSUE TITLE
Question: How to use the same dependency multiple times?

### ISSUE THREAD

**Issue by Nosmoht** [helm/helm#9979]
Hi All,

i'm working heavily with [Google Config Connector](https://cloud.google.com/config-connector/docs/overview). Therefore i've created many Helm charts for common stuff like a GCP bucket with permissions to follow the DRY principle.

Now i would like to use the chart multiple times as a dependency for my application because the app needs two buckets.

I would like to use something like this
```yaml
# Chart.yaml
dependencies:
- name: app-bucket
  version: "1.2.3"
  repository: "https://mygit.example.com/helm-gcp-bucket")
- name: backup-bucket
  version: "1.2.3"
  repository: "https://mygit.example.com/helm-gcp-bucket")
```

```yaml
# Values.yaml
app-bucket:
  project_id: my-project-123
  name: app-bucket

backup_bucket:
  project_id: my-project-123
  name: backup-bucket
```

As far as i understood the [docs](https://helm.sh/docs/helm/helm_dependency/) the `name` of a dependency must match the chart name. So how can i use the same dependency multiple times?
