### ISSUE TITLE
Local dependency charts breaks "helm dependency update"

### ISSUE THREAD

**Issue by MatteoInfi** [helm/helm#9987]
Trying to run `helm dependecy update`, but is seems to be broken with a local chart

```
Update Complete. ⎈Happy Helming!⎈
Error: Chart.yaml file is missing
helm.go:81: [debug] Chart.yaml file is missing
````

The dependencies section of my Chart.yaml.

```
dependencies:
  - name: mychart-3.1.1.tgz
    version: 3.1.1
    repository: file://charts/mychart-3.1.1.tgz
  - name: anotherchart
    version: 10.0.0
    repository: https://company/anotherchart
```

I have tried many combinations, but in the end it is not working

### Output of helm version:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

### Output of kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mattfarina** [comment]
I think the problem may be that the chart is in the _charts_ directory. That's a directory that's managed by Helm itself. The one exception is the case of having a chart as a directory in the _charts_ directory and its listing in the `dependencies` has no `repository` value. This is for local charts.

Can you try moving the chart out of the source and pointing to it there?

**Comment by andrewnazarov** [comment]
Something like this worked for us
```
...
dependencies:
  - name: mychart
    version: 3.1.1
    repository: file://../mychart
...
```
Assuming that there is a chart called mychart of this version in the parent directory.

**Comment by MatteoInfi** [comment]
Ok, let me describe what I have done and what is my setup:

This is my folder structure

```
.
- values.yaml
- charts
- - local-chart-3.1.1.tgz
- - remote-chart-10.8.0.tgz
- Chart.lock
- templates
  ....
- Chart.yaml
- .helmignore

```

This is the content of the local-chart `Chart.yaml`:

```
name: local-chart
version: 3.1.1
```

This is what I have tried in my `Chart.yaml`

### 1. Link to the local tgz

```
dependencies:
  - name: local-chart
    version: 3.1.1
    repository: file://charts/local-chart-3.1.1.tgz
  - name: remote-chart
    version: 10.8.0
    repository: https://charts.repository.com/remote-chart
```

`helm dependency update` produce this error:

```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "eks" chart repository
...Successfully got an update from the "kong" chart repository
...Successfully got an update from the "https://codecentric.github.io/helm-charts" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: Chart.yaml file is missing
```

### 2. No repository

```
dependencies:
  - name: local-chart
    version: 3.1.1
  - name: remote-chart
    version: 10.8.0
    repository: https://charts.repository.com/remote-chart
```

```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "kong" chart repository
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "https://codecentric.github.io/helm-charts" chart repository
...Successfully got an update from the "eks" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: directory charts/local-chart not found

```

### 3. full name of the package

```
dependencies:
  - name: local-chart-3.1.1.tgz
    version: 3.1.1
```

```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "kong" chart repository
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "eks" chart repository
...Successfully got an update from the "https://codecentric.github.io/helm-charts" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Dependency local-chart-3.1.1.tgz did not declare a repository. Assuming it exists in the charts directory
Error: Unable to load chart: Chart.yaml file is missing

```
