### ISSUE TITLE
How to set values ​​for dependent chart

### ISSUE THREAD

**Issue by nic-chen** [helm/helm#9996]
Hi community.

I am a beginner of helm.

I did not see a clear description in the document how to set values ​​for the dependent chart.

Mentioned in https://helm.sh/docs/chart_template_guide/values_files/:
`If ​​this is a subchart, the values.yaml file of a parent chart`

Does it mean we set values ​​for the dependent chart in the `values.yaml` of the main chart?

If so, how to distinguish values for the same name keys between the parent chart and the child chart?

Looking forward to your answer, thank you very much.

**Comment by hickeyma** [comment]
@nic-chen Welcome to the community. 👋 

This is described in [Subcharts and Global Values](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/).

For dependent charts, you will set the values in the parent chart's `values.yaml` file.  You reference the child chart values by putting them under the child chart name. For example, if you dependency is as follows:

```yaml
[...]
dependencies:
- name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 9.x.x
```

then the parent chart values file would lookm like this:

```yaml
[...]

mariadb:
  nameOverride: 
  commonLabels:
```
